### ISSUE TITLE
Merging of #9327 is not a fix, but a breaking change

### ISSUE THREAD

**Issue by keikland** [CesiumGS/cesium#10009]
Hi.
The KmlDatasource was amended in v1.89 to have all tag src paths relative to the KML source, while it was previously relative to the html or javascript root.   

In addition, the change also enforced imposition of rules on valid characters in the src, where for example semicolon ; is no longer accepted in the src.  As a result, the src becomes terminated at that location when semicolon is present.   This is not the case in Google Earth, and browsers generally seem to accept explicit semicolons even if it is strictly not allowed.

Both of these changes broke my app.  While it was not all that hard to get it back in order, the diagnosis and necessary changes tookk some time and it would be appropriate to change the Cesium release labeling on this from "Fix" to "Breaking change."

Kjell

**Comment by ggetz** [comment]
Sorry to hear that @keikland. I assume this was the change in https://github.com/CesiumGS/cesium/pull/9328? Would you be able to contribute a fix to `README.md` putting this item in the breaking change category?

@dtryse Would you know what is possibly causing the following?
>  the change also enforced imposition of rules on valid characters in the src, where for example semicolon ; is no longer accepted in the src.

**Comment by keikland** [comment]
Hi @ggetz .  Yes it was the change in #9328 .  I'll see if I can figure out the README.md change.

@dtryse  : Tried to figure it out and did some JS fiddle tests of URI.js, but could not track it down after an hour or so.  I noticed the problem when I had an iframe with src constructed from an ExtendedData variable that had a semicolon in it.

**Comment by ggetz** [comment]
Thanks @dtryse.

[According to this RFC](https://www.ietf.org/rfc/rfc3986.txt) `;` is a valid separator. @keikland, I would recommend encoding the string--

>  If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

@keikland Since there appears to be no change in behavior in this release from the previous release, there should be no need to add to `CHANGES.md`. I'm going to close this issue.
