### ISSUE TITLE
Cesium crashes on iOS

### ISSUE THREAD

**Issue by stacy-rendall** [CesiumGS/cesium#10006]
In iOS Safari: loading the CesiumJS homepage https://cesium.com/platform/cesiumjs and panning/zooming on the globe for a minute, or the Sandcastle link below, gives an error "DeveloperError: Expected width to be greater than 0, actual value was 0"

Sandcastle example: https://sandcastle.cesium.com/?src=3D%20Tiles%20Feature%20Styling.html

Browser: Safari 15.2

Operating System: iOS 15.2

**Comment by stacy-rendall** [comment]
Thanks for looking into it @ggetz - this is a developer testing iPhone, so it is pretty clean.

I was doing a bit more testing and noticed that the error only occurs if there are multiple tabs open with Cesium viewers in them, i.e. the original error I had the homepage and the feature styling page open in separate tabs, I can replicate with two feature styling pages open as well. Sometimes you have to zoom/pan for a minute before the crash will occur.

The full error is:
WebGL: CONTEXT_LOST_WEBGL: lostContext: context lost
An error occurred while rendering. Rendering has stopped.

DeveloperError: Expected width to be greater than 0, actual value was 0

Would you be able to test this scenario?

**Comment by ggetz** [comment]
Ah, sounds like the WebGL context, which is a browser feature that cesium depends on to run, is being lost. There's not much we can do about that that except handle the case more gracefully, as tracked in https://github.com/CesiumGS/cesium/issues/5991.
