### ISSUE TITLE
CesiumTerrainProvider try to request a failed tile again and again?

### ISSUE THREAD

**Issue by xiaodi0003** [CesiumGS/cesium#10013]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
I use a locale terrain server to provide terrain data
My terrain data is not very good, and some of the terrain tiles is missed, they will return 404
When it return 404, CesiumTerrainProvider try to request the terrain file again and again, for thousands of times
If i can do some thing to avoid the repeat request? I hope only one request be requested for each failed terrain file

**Comment by cooljser** [comment]
I have the some question.

**Comment by ggetz** [comment]
Hi @xiaodi0003, it sounds like you need to define your terrain availability for your dataset. I'd recommend asking a question on  the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. [This thread may help.](https://groups.google.com/g/cesium-dev/c/MdJKPtvjQFs/m/dvMTimbCAwAJ)


Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
