### ISSUE TITLE
iPhone SE CONTEXT_LOST_WEBGL

### ISSUE THREAD

**Issue by stacy-rendall** [CesiumGS/cesium#10017]
Panning/zooming the view with Sandcastle 3D Tiles Feature Styling demo on iPhone SE about 50 times causes the application to crash with error:

```
[Error] WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
	readPixels
	(anonymous function) (Cesium.js:266904)
	(anonymous function) (Cesium.js:310124)
	(anonymous function) (Cesium.js:314268)
	pickGlobe (Cesium.js:323082)
	zoom3D (Cesium.js:324147)
	reactToInput (Cesium.js:322441)
	update3D (Cesium.js:324651)
	(anonymous function) (Cesium.js:324831)
	(anonymous function) (Cesium.js:328743)
	(anonymous function) (Cesium.js:347600)
	render (Cesium.js:346859)
[Error] An error occurred while rendering.  Rendering has stopped.
DeveloperError: Expected width to be greater than 0, actual value was 0
DeveloperError@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:83:22
@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:260:31
Texture@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:101883:36
createTextures$1@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:297948:48
updateFramebuffers$4@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:298041:23
@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:298236:25
updateAndClearFramebuffers@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:328520:29
executeCommandsInViewport@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:328254:35
@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:327990:32
render@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:328861:35
tryAndCatchError@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:328880:24
@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:328970:23
@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:347602:25
render@https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:346859:26
	(anonymous function) (Sandcastle-client.js:42)
	(anonymous function) (Cesium.js:347503)
	(anonymous function) (Cesium.js:347188)
	(anonymous function) (Cesium.js:17244)
	tryAndCatchError (Cesium.js:328882)
	(anonymous function) (Cesium.js:328970)
	(anonymous function) (Cesium.js:347602)
	render (Cesium.js:346859)
```

The demo is the only tab open in the browser, and Safari is the only application open on the phone.

Note I previously created related issue #10006 and that was closed with a link to #5991, but what I'm really interested in is some explanation as to **why** the context is being lost...

Does this device lack enough RAM to run Cesium? Is there some issue with Cesium that is causing it to crash?

We are developing a 3D data viewer, do we need to tell our users that certain devices simply will not work with the viewer? If so, which other devices?

Sandcastle example: https://sandcastle.cesium.com/?src=3D%20Tiles%20Feature%20Styling.html (standalone version: https://sandcastle.cesium.com/standalone.html#c=xVhtbxu5Ef4rA7U4rVBl17KcS6OTjMZ22gR16uBs9D5ERkHtUhJhitSRXPm2d/rvHXLJfbFkWYfk0CCAtVzOMw/nnZsk8EE+gpGQawpmSWF4BXeMUw23puBMLIATscjJgtpNGtcoMJGxDctywmFOickV1X3g7IHCLGc8QyEdT0WS7ELoNU3ZnKXEMClGsDRmrUdJsmBmmc/iVK6SS6pZvvrHbTLMXhnLIzGK0mRFmEha0okHn4oNUbBh9JEqmICgj1BixP92a9G0k7rnSykMolA17fTh16kAMFQpXPmsJJ6GqlEQTBWeiv4kFc/uyi1Rrz8V294PpbIlERl/qu0Wpai4XZOUvt9QYT6Um6KSWaxTKmicEgTQFsfZ512WeXG4uf1UW8+a2vrCCQHRIHMF9BeyWvPaQdTEJR2pVxdB0r9Baq2z3DS2RO4YTVZrxVbMsA3VMcmyaA9exfgWsS0zJlAA/Z+SFVXE8uVSPgAxuIMYw+kTFeW+GKGsVyJn/oxqw4QPBU/3kiiDv4gYxnMlV1d0gVbV0avB6Wk8PHtz2oezN/Hrt3/tw/DNiXUKgFQMze1hHDDAkhJLv4L9RMwyNvJHXCVCRwMvCrBmJl0+t+1V2LcN3m9F9TwXqdWq/fql5FLBrIAVWlw56yxp+qBhjssi5xw2hOeYWZqJlIKQBgjnTrT2/JJsyjysQNZKrqkyBXo7aITUqrooPvk9Ua88+B7PxWXKtkK1/DO8slvsYWjkzZbROSaIrswIFYsRTDt//tVn+5du4DsK77v3W0yrUmrr/zqSDaxUYt1wBhvBl7AI+BORA84WJpOJM5bNUkxdixF1H5fM0G5v2rnvHxTsLjjRutuS1Q/FDM3e7cNJ/PoICKSJSYPqWigYh8UxBGaKpQ9tUVsuiVA0O0ZeGymeqOZssTSa475jSayoQZfsghwrrw2l++TdujPmLohROX3OZ4AhfrdkGvC/jW3KsdmkRNOAcN8KHZdqW5tVVcAvUb2j8I7zHzF8M0x55Nsoat8mA46O2eon7M8MTIjSlmSNJW2FdHUXfvsNDm1V9cG6VTYFHd6qaUGEC+W3vdaWljesLw5nz4sG10v5eFEEW94VaxrNGg/e3PrR1k/Y9wqcg5GEnGPLxtAYBd1f6yP7z9IbvWD5UnHTku6c5c8Z9sWHH1pEa0/9H8g2wuRlwlinSc7NaPfd1vuxakc23eruMsOTZoDuxWWmIGPaENuLbK8FAppymhrcgT3bKOw9XJbD1m7rufKid/JSSpXZPk6jNdY+ml2jiMkzjED/LMXCLfxhXSqcY1TbfNoJi9GGpqdRw/blOPgnHmihD/qw570/Br7u9cGBTDvwl1rFk9M1X1kX7tvrIdtbe72vap3hnFs4x7JwMjhrVeFnqvWu2MnTdkfFMXIn37fkCsq5fDxK8GTQktzfHw91lZdqGebAT0sqIMMBKpOPAuTaRTA2ITt7TTtlhlwUEIIZ7iTOrz4HrkPsW+cglqIr6WczTucGUo4+xUF4nRugduJ3c16ZQnY8JIeyqASrU+czYqHQjbhG6EuLHDpaJtPc1oX455yqomQn7a0mZmIuPxNBcVTqlQkUb5hmM8aZKTCXpp0ly7CfTDuuNPhbS1yq/mh5v3NkomduMLaYx9fv/373n8vrj5f/bNrVXlzKM3M0HQ74yt1ZKksj4dybG6fjb3QEe9dxwJPaKAtq3nNqf14UHzOEDBQQ0M3rViD2TL6c3Mf4x+lHkMoZwdTHOMWZcmf8tqbZVTc4rA7teFUWcms7Z3f4F6XoJHvls3G2G0BwsP7i3ej705PXgz74C9Pb4aBk/DUucI94oyvDyHt/JwXs14HyqKRqOHYRow6vrngMfMOMRv6Brm5GJTaBZkjWxrIuscyrsSLcK32evsd5yRHNRdkYMt8kbbiUZTd0G9zUvvdajwb8eC21K7Gh5bI5RG35Xl2Qa/Cqpk+eaLOx+dnf3aJmvX/SX6ad8LJu9g34qr38bvwguU/B13RxD7Itb8bwO6rHboqcfqOMfPl+sF//8Bvp3zMu15PvM7rP/kjdzWH2qX6RYtYt6D6lt5iOOA4brALKDmZehY1H7LsrFGkdwT2ETPyICfjLvdtvc8ft/+47MEhIzp1447wTW1mCeqQYUqu1zWvfBvr76u5UdPqdsStc5yG6/8ZWa6kM5IpHcZwg5Npen3UyyzGUTZxqHaJ4nDRFxxnbAMsme74ZYrEjWk8sac5v2X/Rr+fjBPfviHLpPj7dbKjipMBtgdZ4OTi/Ll/GcTxO8DGQ2IdjpOQzopoA3nqBSkny1Sw3xhqxFKs74HldFcZ+9nFfoHATTnvn1fhT1cdg2HFSbj8AMGgCHJyfjgA7RbAPIYOhkb8VNX0EyhBRbjEX4MblXS0LN4IXRwCcBYB3IXlewsDoccetFwzBVlk5qNFcm3rNTGbFefN+Pzaq9WxXsnOX5fa61m6poc/uHxLGCUq2sJMWOD621OOz5bwnFDGxwhd6XdeF1H9YlqtkQTj27iL5Hw)

Browser: Safari 15

Operating System: iOS 15.2 on iPhone SE (Model Number MHGT3X/A)

**Comment by ggetz** [comment]
I believe the issue here is described in more detail in https://github.com/CesiumGS/cesium/issues/11270. I'll close this as a duplicate.
