### ISSUE TITLE
DeveloperError

### ISSUE THREAD

**Issue by jinyuttt** [CesiumGS/cesium#10019]
![e049b2a9cf94279ddac48d5c8c98df9](https://user-images.githubusercontent.com/13539621/150265156-5a855e28-d349-4c9f-add3-6768214431eb.jpg)

chrome

windows  10

**Comment by ggetz** [comment]
Hi @jinyuttt! We're going to need a bit more context for this. Can you provide more information about how this error occurred, and maybe including a [Sandcastle example](https://sandcastle.cesium.com/) which duplicates it?

**Comment by ggetz** [comment]
To keep things tidy, I'm going to close this issue. If you have anymore info, please feel free to reopen.
