### ISSUE TITLE
Entity viewFrom refresh

### ISSUE THREAD

**Issue by stardast** [CesiumGS/cesium#10021]
Hi,
the viewFrom property is re-evaluated only if the trackedEntity is unset and set:

[sandcastle example](https://sandcastle.cesium.com/#c=zVhLc9s2EP4rqC+lbJmiqKdl2VPHSdp0nFiNXacHzWQgEpIwJgEOAFpROv7vXQAERephp9NLD1YIYLH77XuRJyzQEyUrItAFYmSFromkeeo/mD1vehSZ9TVnClNGxPSoif6eMoTkkudJfMVoihUZISVy0pyy58b5lE1Zq/URPxIkc0EcdyoRVkgtCYqBoyAxUjQl/pQ9AQKpsFAAoBD+e55QzN4CY38ueKo/PI3NfIRBe9hE7Tb8hfDXa2iRmoniCid3JOIslsCrHZw75jzbyxvHcUHuGY00iKb+qnIyGxXDbO57jSkzso2CfpTw6NE3TO5BM5BovvU+A9pdQp6VdDw7RBblQhD2QxzN72fMFmSj7XW559/c3k6+3t3fTjb3tAcS8Kr/nfP0nnvWAgaP8yO6FgR0RRhlWC3RnAvEcwgZsqRRQtBsjRIiMsoWaEbUihCG1IqjjEuqKGey8K9b12PsDqdZQuJJcTgRPCNCrb3GeSUqJnuvXsMJfGHWMa47DTuDs16v7w/OzjqDcNjvGreddvv9Xi8c+mHQCzpB2O+Y7U4/HAbtjt8O+r2zs/5gWPgRRBIW/7jAftDxB8Gg2w46g+5gI7Efdvzu8OwsCIelwMGwH/jDcBB0e/2BlQfGvQJDgoeoWsNHpMC4WWEEtKJJghb0iaBcmrSBKAC6nyWSGYHswSxGMeRRZLBCamG2NvSsmliO/YPh7iy8lep7aYyazm9GizlOJNmYqs76oLUKTe+Ahhg9VktCElBDQJIZ7PwJyoPGjCgoglxUFDgKRcytK7ZIyH4ltm55n/J0RoTDurkNtwIT2nqbGaLbub1si4Y+1VHuaQJqyOGf8cU28Tk6OaENWws16RwXZqCotUPriJRN41dLUbUYIcf6eLcuvVCZELIpjBBY/wZyFOJIpylGjLNTnfUb0JKDZ4rq7DIbRxGB1AZuOoktfHC4cdl7p+tHqAl+xleeZdREYeN8m7hSjMqo8HXRqGo6qQYaqqZhsVMXvat8NeKc8pv4NfY1vvC0C5olO0sGFvqso7ESoBLNsIQ0A/xLvgJDybp5oJ2l/MkYVCGCo6XxrVQks9bam1P+gqgHnOQORZ1qY7qUKCLkhAjr670WTPGCUZXHxDvExejxGcc015Ed+L3wHDSFHLPsS69GVER5OifQZyLinDr5APFW5XCMwpKzS90axG3QrTrjIhgrmXhyYb3oeRuJ4VaUN3aTqYGO7b1dFOd1CaXZt72/IdHWetbI5jmzlTTPYgiEO11jb/CMJMUVQWSeKJfv/wPvPqbA4TfdiwuPCZ6z2Ntmfow6ft9VAkFULljl6gmaHsGytYS5zlmi6uD9tfYaJ8kMR49lsS2NZ1LaaG/FaZtBx7BWK6QXTP7IwcyC6eTUM97VNyqNR4qqsGuSPz99uP/6V5H5e5xcs36joHMQbEF4hl3TxRplCzCM7gVmEop+incb/ycek/p5qbbVqjDVaMdom3HY9JodPjorDYsvpuCM9mFpbs6/pjR+lQaGNXGI6NmNdFdxXBviUoCWlAOD2Xtnhg0AWEyKZvig0AoglazerrSO6kMCFxRoC4vsGTJuN+elHR2DRlNX4qtccY05gihbI0lqdRfmhooEKBX2RVHOQVQBBTQjKMymvhnVRtbMCOWCjiDifb9lywH0StwyJLL1q8mfByumvvIXyQzePUVE5cw+erQHR3Yocu1o18WjfZuG/Nn8JrrElPgU+aZGL2badnVqWgAu3OfwTNMahkH2DUkQeiqJoPMSPDzaVm+A38KoV77a9FFMoRFDnX5LZZbgNTz4YrrjxbcHiIqkRdBlgqb7hlnKD+zC4SNrcjufg09HB3p30IR61WuioFEayeVQ8WQRAJ/Em/isxque9qprX196D9Xl4HR62taI0UD/dP3AipqymEPjgijTReVdQvTnm/WHGJ7DcFG1p0cNn7MoodEjcHbVzyMwfOsWgWyP+FdAQL6Fon/LrvQyjvAVHAbGfrOB98kcZkDbMv8r1oNitr3zfNQ8Gku1Tsili5JfaJpxePznIvEgMRWBxNRDZ2uWAyt47EppRSA0blWvjmP6hGh8see/KFCUYCnhZJ4nyR39TqZHl+MW0O9cTThMN2xxC08QiGdNtmxf3thN3/fHLVjuv6k4h9QEYa+ewJnCs4rKemPG43VlQ2+J2lrvxJfjWa6UrmuGsY09pNYZgaU9AjFv8sVP45ZdAlq49gOMwj2MvnDxiE1peIEfbFSQwqqmCqwrulZN9w8)

Is it possible to change the viewFrom avoiding the reset?

**Comment by ggetz** [comment]
Thanks @stardast for the report and the sandcastle example!

According to the documentation, it doesn't appear that `viewFrom` is designed to work this way (emphasis is mine)--

> A _suggested initial_ offset for viewing this object

What are you looking to accomplish? There may be a different way to accomplish that using existing API. We've also been considering a better camera API, and would like to know your use case.
 
I'm going to close this issue to keep things tidy since I don't think there is a bug here.
