### ISSUE TITLE
Clamped point in wrong position in 2D and Columbus view

### ISSUE THREAD

**Issue by srcejon** [CesiumGS/cesium#10036]
It seems points entities that are clamped to ground or relative to ground can appear in the wrong place on the 2D and Columbus views

See this simple example:

[Sandcastle example](https://sandcastle.cesium.com/#c=fZJha9swEIb/yuFPGXiyXdovqRs2HNiXdAltt8HqUhT5aovJkpFkd83If59kp65LQsEc6L17H1l311ENbFcLuIL7XAL88wGAF3PIg0KxtkZp8yAcZElr9Ins9/UKNopPUh1qw5X02YTEB3kfHjEb74LkCNm8ozXKcNvjDmYARrVVpaZNxdkSS41o5nD/OUncdSGcxz7GDwf/fuQ46hSihNKTM4Aut9Rxzi4uQngXXlFvMADVWsElZh9S4v77mPCLF7aaw/moN/wvilu+c704i0e1Ql5W9gafUKNkQ+tXX683j3frx2836x/fl2PH9mPDHy5zmcvODbbj+IzajVbiM2RoeFuTn702ywPWnzMlLXU/pPPg0+XgKqilt6rVDDda1dygAxzMmduU5ZgmQtFi5rent/Zg8uY2hBbF7Ig2qd0pVd+p0yW5DMIgNfZF4OK1HV943ShtodViRkhksW4EtWiibcv+oCXMGG/1pWk0taYF79z+XZ14NTBBjXGZp1b0A8iDRRq5+iOrfy2X5dptuqAvvqxKFqtBJISkkTuedlqlxJbqCXmo+A8)

The point is in the USA on the 3D globe.

![image](https://user-images.githubusercontent.com/57259258/151155985-2b0fd580-8581-480c-b087-063cdb9ae757.png)

If we switch to the Columbus view, it first goes to the correct position:

![image](https://user-images.githubusercontent.com/57259258/151156085-1df97c57-b8aa-429c-897f-baea2ad0aa12.png)

However, if we then switch to the 2D view, it disappears:

![image](https://user-images.githubusercontent.com/57259258/151156135-8d426880-f807-4168-b145-0fa33db2e57d.png)

Then if we switch back to the Columbus view, it's in the wrong place:

![image](https://user-images.githubusercontent.com/57259258/151156203-209b4d5f-098b-424a-b0ef-8bb8e057a6dc.png)

This happens for heightReference of both "CLAMP_TO_GROUND" and "RELATIVE_TO_GROUND", but not for "NONE".

Sometimes they appear in the wrong place when first switching to Columbus view - but that can be a bit random. The above approach seems to be 100% reproducible for me.

**Comment by ggetz** [comment]
Thanks @srcejon. I believe the issue is with `CLMAP_TO_GROUND`, and this is a duplicate with https://github.com/CesiumGS/cesium/issues/7118.  I'm going to close your issue now to keep the discussion in one place. If you have any further input on this, please post it there instead.
