### ISSUE TITLE
Cesium3DTileStyle.pointSize in ModelExperimental

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10046]
the `pointSize` property is not currently handled by ModelExperimental, this should be added.

Though @lilleyse does this fall under CPU or GPU styling? Since it deals with point clouds, I presume the latter? If so, this should be considered in tandem with #9944

**Comment by lilleyse** [comment]
Yes, this would be part of #9944

**Comment by j9liu** [comment]
@ptrgags can I close this now that #10560 is merged?
