### ISSUE TITLE
`GregorianDate` constructor does not properly handle values

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10057]
I found this issue while trying to convert a `GregorianDate` into a `JulianDate`. The [`GregorianDate` constructor](https://github.com/CesiumGS/cesium/blob/48c8abaca6257b568edc8c992ede5f2c487cdd38/Source/Core/GregorianDate.js) simply takes the parameters and puts them in `GregorianDate`'s respective fields, without actually validating them. For instance, the `hour` value should be in the range [0, 23], but nothing in the constructor actually enforces this.

Additionally, the [`GregorianDate` documentation](https://cesium.com/learn/cesiumjs/ref-doc/GregorianDate.html) says that all parameters can be optional. This seems strange -- what is the expected outcome of saying `var date = new GregorianDate()` ? It may make sense for some of these fields to be optional, like `second` and `millisecond`, but there is nothing in the constructor that provides a default value. This becomes problematic if I'm writing code along these lines:

```
var gregorianDate = new Cesium.GregorianDate(2022, 2, 1, 12, 0, 0);
var julianDate = new Cesium.JulianDate.fromGregorianDate(gregorianDate);
```

`JulianDate` expects the `GregorianDate` to have valid values. However, I didn't specify the `millisecond` value of the `GregorianDate`, so that is undefined. Thus, when `JulianDate` tries to perform this conversion, it results in a `NaN`.

**Comment by GatorScott** [comment]
I would expect defaults to be the minimum allowable value for any missing field, thus for new GregorianDate() => 1 January 1583 00:00:00.000 (first possible use).

.NET 6 specifies the default date as 1 Jan 0001 C.E., but 1 Jan 0001 00:00:00.000 seems ok too.

**Comment by SubhajitS** [comment]
Hi folks, I would like to work in this issue. I am new to open source contribution, so might just need some guidance here.

**Comment by j9liu** [comment]
@SubhajitS - feel free to ask questions and let us know what guidance you need!

**Comment by ggetz** [comment]
@SubhajitS [CONTRIBUTING.md](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md) is a good place to start.

**Comment by SubhajitS** [comment]
Thanks for the guidance, though I have couple of questions on the implementation. 
- In the GregorianDate constructor it mentions the range of millisecond is 0, 1000. Is 1000 an inclusive value here?
- Other than just checking the input parameter's range we should also validate whether the combination of the parameters create a valid date. Is that a correct assumption?

**Comment by j9liu** [comment]
Hi @SubhajitS,

- 1000 should not be included in the range.
- That's a good point, there are dates like "February 30" or "June 31" that technically pass because each parameter is valid. It would be good to catch those.

**Comment by SubhajitS** [comment]
Hi @j9liu I have raised a draft commit [10075](https://github.com/CesiumGS/cesium/pull/10075). Please review the same and let me know if I need to cover any other corner case.

**Comment by javagl** [comment]
Just stumbled over this, a small thought:

> what is the expected outcome of saying `var date = new GregorianDate()`

One _could_ argue to handle this similar to [`Date()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#parameters), where the no-args call causes the creation of a date that represents **"now"**.

**Comment by rravula77** [comment]
Hello, my team and I would like to work on the issue

**Comment by ggetz** [comment]
Hi @rravula77, this has quite a few corner cases, so https://github.com/CesiumGS/cesium/issues/10349#issuecomment-1335621264 may be more straightforward to tackle first.

**Comment by gaurav8y785675474** [comment]
hello j9liu
i am a beginner in open source world
can you please tell me exact location of code[related to this issue] in files 
so that i can work on that

**Comment by j9liu** [comment]
Hi @gaurav8y785675474,

The location of the code is actually linked to in the first comment I wrote. This would involve changing the GregorianDate constructor implementation and also writing unit tests for it.
