### ISSUE TITLE
Ambiant const enums are being generated in TypeScript type definitions

### ISSUE THREAD

**Issue by mjacques** [CesiumGS/cesium#10069]
Since version 1.90.0 of  cesium, some ambient enums TypeScript type definitions are being generated as const enums, which triggers an error in TypeScript projects that use the isolatedModules flag (typically all CRA projects).

The explantation of why an error is being triggered can be found here [Isolated Modules](https://www.typescriptlang.org/tsconfig#isolatedModules)

Typically, the following error is being thrown, which prevents the project from being transpiled:

```
TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
                  labelEntity.label.style = new ConstantProperty(LabelStyle.FILL_AND_OUTLINE);
                                                               ^^^^^^^^^^
```

@ggetz It seems that this has been caused by PR #10026

**Comment by ggetz** [comment]
Thanks for bringing this up @mjacques.

[The TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls) recommends the following as an option:
> Do not publish ambient const enums, by deconstifying them with the help of [preserveConstEnums](https://www.typescriptlang.org/tsconfig#preserveConstEnums). This is the approach taken internally by the [TypeScript project itself](https://github.com/microsoft/TypeScript/pull/5422). [preserveConstEnums](https://www.typescriptlang.org/tsconfig#preserveConstEnums) emits the same JavaScript for const enums as plain enums. You can then safely strip the const modifier from .d.ts files [in a build step](https://github.com/microsoft/TypeScript/blob/1a981d1df1810c868a66b3828497f049a944951c/Gulpfile.js#L144).

I believe we'll be able to modify how we generate our TypeScript definitions accordingly.
