### ISSUE TITLE
Elevation Band Material Sandcastle broken with WebGL2 context

### ISSUE THREAD

**Issue by ebogo1** [CesiumGS/cesium#10065]
With a WebGL2 context, the elevation band material doesn't show up. Console prints a bunch of WebGL warnings:

```
[.WebGL-0x7fe337081c00]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: invalid internalformat/format/type combination GL_LUMINANCE/GL_LUMINANCE/GL_FLOAT
[.WebGL-0x7fe337081c00]RENDER WARNING: texture bound to texture unit 3 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
```

Sandcastle example: [link](https://sandcastle.cesium.com/#c=1Vltc5s4EP4runyp3RDMi/Fb3Mxdcp27m2mbzvTtQ9MPMmxsTTCiApy4Hf/3WyHAwi+p47rJXWdiQLur3Wf3kRbUGRVkxuAWBHlBIrglF5CwbGp+zMcaV0d+/nzBo5SyCMTVkUG+X0WEpCAEjrwVfMYCEIPS0BdAU/jERRi8VyqNXJ8QAV8zSNKPIFK4e8PFlIbJgKQiA4O0Wm8AAghIyjGcJKMh+wYkCXkM0njRNOTFxyjgLr2MU8YjtK1P/AlG49ApZsyt8HfRPL2KriIF0fTpFAQ1E0glPhVYgKYsonLKgZ6BC4pxJoxGbkO5cfpWx+2anue2u67rWB1DjXs42u7aptd3u1a34zpGqd/tOV7H7NlOp+90HbstxxUSLhhgRpXTAsYEaMCi8YC0TZzP6XT6nY7b7uN9MWHMUn8yICeW6aD3fr/X83pev2P3S4+Ch+GAdEynZ7lty/PaXq/b97y1ZBQ1f80DCLHsuf+xQO8Y04BcY11UAkc0Cuy3PGEqzq5lWaZVSRxN4tUk7lLSq9u8nzD/JoIEi2fXBYJGSUwFRP58QCzTKyT+zVjwbF3elQqLHE5Rr5uI+zc8S81UoFWjAigxS8Qp5+GISpoH3M+mCNUcQ/oyBHl7Pv8nQLIXOldH0mh1XhrH4fycRbJIyXJ+o5xZ2lxzQRrSW4RMIyxa5rmp0syuydLUnNDk8lauoRgXxbwhjZrNkg8r/tUgITLqy1ECYkZHIehx5OaVWpKNEl+wETSyOMAl+Rr/BKN5PpAOmD2ZvOss8mWlSF2pUUQhoZTMwMydI1KgkYagFKpZpXqNNGjzJpuOcCdZmtQU6nbOj+yczXbuj+zczXYVHbfZVQordhobt5pqOrr1JkZvnmOTplrBaq6QzkHI0D9/2TD/KyktVzchWCPcc3DdfS4Z8r28kVsPG09w6bedalGqfz4Puahvi3KkIbVI8eMYW1A1q4kWxj1OtS3ifqe29Lf8+Tmn3kOcLuHu6vRLccV2BVHwJ7+NbqkIEq07lbIP8apkkVdTVdeMs2TSWKmqToKxYMG7FHvV3zkyLLgq4qmu8DIKKnGv1+6tiC9wZiny1HC1iTEcs07xMlyq4ePxcbVH5TQEEedMY6RFGsv5ToiteK/UVObPIeS3qFvkGPebiSknaJQJXMFj6OMVjGpU+VZP687+GPEZoDPd9TE2ngK+UqVhPKHkRTnjWmA5wS2zbRTOmuT5FhYUk+qFq5i3vvxqtFwSU4vV0OU7LoocTVOzXBg7OcxTdWCH5RpYVC2nJB2NUmwyjMrNK8/0FF8T7WKB6dvyc8y8XdJd9s7fqoajUzBvKcu97gHprnerkw3uPRyt4t0pQ8vdotw8HlSQHULaJ4y1nrR/TMf/l5hw9NeUrqJ2QU3tFWZvGjq/goa19vXg9DqHoqGtNdCfLLlzKBo+Xkz70XCH0m2nobs3Dd0D03DlBWofGroHoOHae9xPltw9AA0fOaYH03DX0q3TsP7yivt083SzwNkmcIuXBgJhAnqv9/l0xCIIzlHpV7X8J+ll1SbyJFvYk/H5fvLo1V57jZwWpxXL7wl1+vgyhFl+tiatqiONAnriQwSD4tDTzJ8M3e+guKpPseLLXVM2xyEfgan5Lm9PizOV1aMUHD8yjoZJOg/hrIT9O5vGXKQkE2HDNFspTOMQLZLWKPNvIDX98syBkGFLNx0GbEZY8GLD0SzxQ5okKLnOwvAd+wZXR2fDFuqvmYY8P2u8nIFAtFJtYp+9UoOmaQ5b+LjZsjoiq5AMU3kQdbas7TAd8WB+pjNmmIrasxwJzs6rzyii82TYQtm6dn0Ex1gUZylJ5zFgXGg/RrwEvyTwCfkn7+kd3tv5fZJCrAQ2PmGB6AkSSyKa0TCDwZZvOoPk4g95SQfkWe7zmYa+iGU1ZBwQO2XgP4L9CVCXG8wBINsaYsvSIN+Ht/T/GGBtUm6vB0DbVhAVXnmcsxPequU9Bl7n6fE6j4nXfXq87iPh/as4gNkLqD8B/2bE71Zg5MMQDKr/a3hwtPhYazr4rHUlvZX9Cw)

Browser: Chrome 97

Operating System: macOS 11.6

**Comment by ggetz** [comment]
Fixed with https://github.com/CesiumGS/cesium/pull/10894.
