### ISSUE TITLE
Handle content metadata for explicit tiling

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10105]
Another spec change (schema TBD, @lilleyse when ready could you link it here?) is to allow metadata within a content (likely `content.metadata`). This needs to be handled in the implementation.

This will be somewhat similar to how `TileMetadata` works. However, since there are a large number of `Xxx3DTileContent`, it may be better to have `Cesium3DTile` create the object and set `content.metadata = new ContentMetadata`.

This involves:

- [x] Create a `ContentMetadata` class. This will be very similar to `TileMetadata`. 
- [x] in `Cesium3DTile.makeContent()`, parse the content metadata extension (see where `content.groupMetadata` is initialized) and set `content.metadata`. This way, you don't have to add logic to every single type of content
- [x] Update `Cesium3DTileFeature.getPropertyInherited()` to look for `content.metadata`. This should go between the batch table and the tile metadata.

Some of these steps will be similar to #10104, as they both will populate the `content.metadata` field with either a `ContentMetadata` or an `ImplicitContentMetadata`. The two are mutually exclusive by the spec, though in the implementation for tile metadata I think I did this by not checking and just making the implicit one overwrite the explicit one.

**Comment by lilleyse** [comment]
The latest revision is here: https://github.com/CesiumGS/3d-tiles/blob/extension-revisions/extensions/3DTILES_metadata/schema/content.3DTILES_metadata.schema.json

Just note that is still part of the extension so it would be `content.extensions.3DTILES_metadata.` In 3D Tiles 1.1 it would likely be `content.metadata`.
