### ISSUE TITLE
Node Transformation is stopping model animation

### ISSUE THREAD

**Issue by jackbr0gm** [CesiumGS/cesium#10117]
Sandcastle example: https://sandcastle.cesium.com/#c=vVVbb9owFP4rHg9V0Kgp6qRKXKr1Mu1l3aVUfYpUmeSEWnNsZDtQqPjvO7YTkgCbqmkaiOAcf+ec79zsREljyZLDCjSZEAkrcgOGFzl99LIo7iT+/UZJy7gEHXd6r7EkxDyrQqRXkufMwtDqAmK57Y5i6b5LpslCGW65kmi2NHnDtMUVk+c00yq/hbkGMNHpxUWPnONvcOY+zobTB2m5XaN2YEf9OwdDWZpGnkLlYbhb9Zw4VymIIfEQQgrNhyTuUNqfsnwh4JZZ1vcQ0w+8rrguV0+4pHMxiztOd9sMKHCwmiU/If1UUQscPSYrZOLDfZqD/Sxs9hV9mCgguhUbnxjNc2S7BFMHZxKQQOudUQ0XIOf2GaH1Lg2yEpQpTSKH5Ag6G+HfuFTC9fv3O98H/ts2kXbEu6MayzMS7fYpT8lkUkVMTk4aZjj2EJMJqKyq9J3Lr3dcm3MfDbbQslZteNuGZflXAguZQoZdlyJw64xNmUwTZqwA1wYPSokZ09eFtUpiq6Jbnq3Jqq+Iy/6DZtJgdrBDsTDYuKQqUtT1ORFgiUQgJuJo1VxOnABNf9dqEXdCelxi3pWRlvwiZ4YqzedcMnHHrOYv3VbmjwDcwDlp7t9oIpSEKLjY7ujB6pGJAuopCrof/Aj5CIUP70eBc6glru6V9ZJpwgREry/Ds94af5vh6fm2R/w7cQKycY/VcBCkA+pw7rlxz20g0iB4SCEvhOULsY7+GGavsVtG0xbtmY26YTcQSPCEUlhuoeZYhkbAZKU0ziKZFZYwfww5obFqsYA0lKoc3zc1zfX67T1jWyDjeqN9eB5achjQdh01WsLWwQzJXp3KaQg5qPq0bdK0fVYertk8qmu3p+ISsKNSdXXvWEDBRBgE6s9L+hsKh9L/U7h7MGD/7VT/1VDnrWFuw1tD3dApDOzOgIwJA/XUvyHlrWOxO+r0OmNj1wIuKy8feb5Q2uLlJyK8+SzgzYfHg+nPCry/LE2MqSiN+03VccqXhKeTI9c+SQQzBneyQogp30DcuRz3EX+gKhRLuZx/W4IWbO1gz4PLL0FIKR338fW4pg0l3rP8Cw

Browser: Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)

Operating System: Windows 10 Professional x64

Hello Team members,

I’m applying transformation on a model node. Model’s node has its own animation. I want to apply transformation without effecting its own animation.

I have tried translation using [model.nodeTransformations](https://cesium.com/learn/cesiumjs/ref-doc/ModelGraphics.html#nodeTransformations) Property and [ModelNode.matrix](https://cesium.com/learn/cesiumjs/ref-doc/ModelNode.html#matrix) also.

Both are working fine and model node is translating. But animation of that particular node is getting stopped.

Here is the reference sandcastle [link](https://sandcastle.cesium.com/#c=vVVbb9owFP4rHg9V0Kgp6qRKXKr1Mu1l3aVUfYpUmeSEWnNsZDtQqPjvO7YTkgCbqmkaiOAcf+ec79zsREljyZLDCjSZEAkrcgOGFzl99LIo7iT+/UZJy7gEHXd6r7EkxDyrQqRXkufMwtDqAmK57Y5i6b5LpslCGW65kmi2NHnDtMUVk+c00yq/hbkGMNHpxUWPnONvcOY+zobTB2m5XaN2YEf9OwdDWZpGnkLlYbhb9Zw4VymIIfEQQgrNhyTuUNqfsnwh4JZZ1vcQ0w+8rrguV0+4pHMxiztOd9sMKHCwmiU/If1UUQscPSYrZOLDfZqD/Sxs9hV9mCgguhUbnxjNc2S7BFMHZxKQQOudUQ0XIOf2GaH1Lg2yEpQpTSKH5Ag6G+HfuFTC9fv3O98H/ts2kXbEu6MayzMS7fYpT8lkUkVMTk4aZjj2EJMJqKyq9J3Lr3dcm3MfDbbQslZteNuGZflXAguZQoZdlyJw64xNmUwTZqwA1wYPSokZ09eFtUpiq6Jbnq3Jqq+Iy/6DZtJgdrBDsTDYuKQqUtT1ORFgiUQgJuJo1VxOnABNf9dqEXdCelxi3pWRlvwiZ4YqzedcMnHHrOYv3VbmjwDcwDlp7t9oIpSEKLjY7ujB6pGJAuopCrof/Aj5CIUP70eBc6glru6V9ZJpwgREry/Ds94af5vh6fm2R/w7cQKycY/VcBCkA+pw7rlxz20g0iB4SCEvhOULsY7+GGavsVtG0xbtmY26YTcQSPCEUlhuoeZYhkbAZKU0ziKZFZYwfww5obFqsYA0lKoc3zc1zfX67T1jWyDjeqN9eB5achjQdh01WsLWwQzJXp3KaQg5qPq0bdK0fVYertk8qmu3p+ISsKNSdXXvWEDBRBgE6s9L+hsKh9L/U7h7MGD/7VT/1VDnrWFuw1tD3dApDOzOgIwJA/XUvyHlrWOxO+r0OmNj1wIuKy8feb5Q2uLlJyK8+SzgzYfHg+nPCry/LE2MqSiN+03VccqXhKeTI9c+SQQzBneyQogp30DcuRz3EX+gKhRLuZx/W4IWbO1gz4PLL0FIKR338fW4pg0l3rP8Cw).

I have applied translation on right propeller of the aircraft. It’s rotation is getting stopped after applied translation.

How to do node transformations without effecting node animation?

Is it possible or not?

**Comment by ggetz** [comment]
@sanjeetsuhag Could you please confirm if this is expected behavior or a bug?

**Comment by sanjeetsuhag** [comment]
I believe this is expected behavior. When the user sets the `matrix` property on a `ModelNode`, the `useMatrix` flag is set on that object. It's stated here that glTF animations are not applied if this flag is set:
https://github.com/CesiumGS/cesium/blob/2a8cfc27145d827c878308eb613fc0402907f2e6/Source/Scene/Model.js#L4220-L4223

**Comment by jackbr0gm** [comment]
@sanjeetsuhag Thank you for confirming me that it's an expected behavior. As a solution I have tried to translate parent node of the actual node. Now inbuilt animation and translation both are working.

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag and @jackbr0gm! Sounds like this is not a bug.

**Comment by srcejon** [comment]
Although the code may be doing what the comment says, does it either conform with the Cesium docs or make sense?

The docs for nodeTransformation says:

    The transformation is applied after the node's existing transformation as specified in the glTF, and does not replace the node's existing transformation.

Also, the CZML Model specification doesn't say that using nodeTransformations will prevent animations from running.
