### ISSUE TITLE
camera.getPickRay throws exception if scene is not visible

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#10125]
Calling `getPickRay` throws an exception if the scene is not rendered:

* Paste the following code into Sandcastle:
```js
const viewer = new Cesium.Viewer("cesiumContainer");

Sandcastle.addToolbarButton('Pick', function(){
    const ray = viewer.scene.camera.getPickRay(new Cesium.Cartesian2(0,0));
});

Sandcastle.addToolbarButton('Hide', function(){
  viewer.scene.canvas.style.display = 'none';
});
````
* Hit `Pick` (no problems)
* Hit `Hide` (globe disappears)
* Hit `Pick` again, exception inside of `getPickRay`

I'm pretty sure all of our other pick operations return `undefined` if the pick fails, but it's been a while. It doesn't make sense for the user to have to perform the additional checking here, since it's all internal to Cesium.

**Comment by ephjos** [comment]
Related https://github.com/CesiumGS/smart-construction/issues/5560

**Comment by mramato** [comment]
Looks like this was fixed in the above PR, but not closed?

**Comment by ggetz** [comment]
Yes, fixed in https://github.com/CesiumGS/cesium/pull/10139.
