### ISSUE TITLE
Some images cannot be read when using TextureUniform

### ISSUE THREAD

**Issue by xuebingzzz** [CesiumGS/cesium#10121]
One case is when the image is a cross-domain image, the correct texture cannot be obtained.
, the other case is when I set the TextureUniform’s url to base64 or blob-url, the image also fails to load.
Is there something wrong with my use?

**Comment by ggetz** [comment]
Hi @xuebingzzz, would you be able to provide a [sandcastle example](https://sandcastle.cesium.com/) which replicates the issue you're having?
