### ISSUE TITLE
shadows of tileset does not work when using 3dtiles next

### ISSUE THREAD

**Issue by Gu-Miao** [CesiumGS/cesium#10132]
I find that `shadows` property does not work when using 3dtiles next.

```js
const tileset = new Cesium3DTileset({
  url: 'http://xxx/xxx/xxx/tileset.json',
  backFaceCulling: false,
  shadows: ShadowMode.DISABLED,
})
```

**Comment by Gu-Miao** [comment]
Here's a pr for this: https://github.com/CesiumGS/cesium/pull/10131

**Comment by ggetz** [comment]
@ptrgags Can you verify if this is expected behavior or a regression?
