### ISSUE TITLE
Draco Webwork URL Rewritten incorrectly in Electron

### ISSUE THREAD

**Issue by beachtom** [CesiumGS/cesium#10145]
Hi,

I've encountered a bug when loading Cesium under electron - when utilising draco encoding only. The URLs to load the draco webworker gets rewritten incorrectly at some point - but the URL to WASM is fine.

Webworker URL <img width="492" alt="Screenshot 2022-02-26 at 16 31 09" src="https://user-images.githubusercontent.com/26248350/155851041-974e5c14-a601-4b2a-a124-c19507a4911a.png">

WASM Url <img width="434" alt="Screenshot 2022-02-26 at 16 31 16" src="https://user-images.githubusercontent.com/26248350/155851039-18797d62-1f3d-4869-bbe8-7d47b3b297ee.png">

I've done some experimenting and the error occurs in how the url is rewritten sometime after it is set in Scene/DracoLoader.js but before it reaches WorkersES6\decodeDraco.js  - if I manually inject the correct URL into the decodeDraco(...) function then it works correctly. Sorry I can't be more precise but I am not familiar enough with the codebase to go into more detail

**Comment by ggetz** [comment]
Hi @beachtom, have you tried setting the `CESIUM_BASE_URL` global variable to the root cesium directory?

**Comment by beachtom** [comment]
Yes - we are setting it in our webpack build - all other workers and the draco WASM seem to load fine. Really not sure why it is not rewriting it properly.

**Comment by ggetz** [comment]
Ah, thanks @beachtom. Would you be able to show us your webpack configuration?

**Comment by beachtom** [comment]
[vue.txt](https://github.com/CesiumGS/cesium/files/8170574/vue.txt)

Attached - we are building with vue cli - I attach the config file here
