### ISSUE TITLE
Type question regarding the orientation property on Entity

### ISSUE THREAD

**Issue by avenmia** [CesiumGS/cesium#10140]
I'm working on a Cesium app and converting it into TypeScript. I'm using the [sandcastle code](https://sandcastle.cesium.com/?src=3D%20Models.html) as a base. 

For this code here:

```
const orientation = Cesium.Transforms.headingPitchRollQuaternion(
    position,
    hpr
  );

  const entity = viewer.entities.add({
    name: url,
    position: position,
    orientation: orientation,
    model: {
      uri: url,
      minimumPixelSize: 128,
      maximumScale: 20000,
    },
  });
  viewer.trackedEntity = entity;
```

Cesium.Transforms.headingPitchRollQuaternion returns type Quaternion, but the orientation property is of type Property | undefined. Is there a way to convert a type Quaternion to a type Property or should the orientation property be of type Quaternion.

Thank you

**Comment by ggetz** [comment]
Hi there @avenmia. [Properties](https://cesium.com/learn/cesiumjs-learn/cesiumjs-creating-entities/#the-property-system) are generic types which can Quaternions or other values. You should be able to create a `ConstantProperty` and pass in your quaternion to the constructor.
