### ISSUE TITLE
Warning about `gl.MAX_SAMPLES` when using WebGL

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10167]
Steps to reproduce:

1. Open https://sandcastle.cesium.com/
2. Open browser developer tools
3. Look for a warning about `WebGL: INVALID_ENUM: getParameter: invalid parameter name` or something similar.

This points to the line:

```
ContextLimits._maximumSamples = gl.getParameter(gl.MAX_SAMPLES);
```
in Context.js.

It seems that `gl.MAX_SAMPLES` is only available in WebGL 2, as if I use [this sandcastle](https://sandcastle.cesium.com/#c=bY7BagIxEIZfZchJYUmoR41LwWvBg6CXvWSzUxs6m2yTyVorvrvRvZTWy8D/zfcPM5oIo8MTRliDxxNsMLncy/2DzRphH3kTPBvnMTaigkvjAWwh+M3bgV3waTlBgIhfGRMfsD3SYgkcM1b3zbXM63wlKqETnwnrSQd4df0QIkOONJNSMfYDGcak2mw/kaVNab6aZK1+V3XnRnDd+smLYMmkVDbvmWjnfrARtVbF/1elYDrnj9sRI5nzXft4qd8mKKXUqsTnTQ6BWhP/XL4B) which is just Hello World + WebGL 2, no warning shows up in the console.

CC @ebogo1

**Comment by suryakumara** [comment]
Hi, I got same warning.

**Comment by suryakumara** [comment]
![image](https://user-images.githubusercontent.com/51102773/167325801-9e0f57dc-1931-46b6-9265-e620ef479fc2.png)
@ebogo1 
I use Mac M1, MacOS Monterey. Chrome Version 101.0.4951.54

**Comment by suryakumara** [comment]
Solved after update Cesium version. Thanks !
