### ISSUE TITLE
Crash when classifying a tileset with draco compressed glTFs

### ISSUE THREAD

**Issue by na9da** [CesiumGS/cesium#10160]
Hi,

First off, thanks for the awesome work in developing a top-notch library and keeping it open.

I have a tileset that has draco compressed glTFs (converted through ion). It works perfectly in normal mode but crashes when I use it for classification. I am assuming it is because of the different code path of classification models that is not draco aware?

![image](https://user-images.githubusercontent.com/1430/156704060-1576dd36-9c2d-4a4b-b86d-af1e83b638ee.png)

Below is a simple sandcastle example of the problem using the NYC tileset.

[Sandcastle example](https://sandcastle.cesium.com/#c=lVNRb9MwEP4rpz5MjlQ5mgpC2tKKUiQYQhqiEU95cZ1ra+HYke2kZKj/HTt2u5UxBE+xfd939313lzyHD4YpByu0oms+rYFxjtaC0zDozoDQCpi16GylKsW1sg56gQc0MAeFh0Sk38Y3Uk34eF9p5ZhQaKrJFH5WCsChMf7li9G9qNHcPCXHT3mJICMNoDPy5gS80+orWq+LI90a3SyDsruaXGfTAD6GzzG7rVSUSC1HhXQn9QZpja3bl2jdcuerWJfKeRvOdHj7aM8JiT6tD1xkaY1ohBM9WsrqmoR6zyzM3peR/D/i37yevZpFAwB5Dlw3DfqRuL0Y5yA1q/0Fz8KUNg2TcogMLv18xFZw5vywyqHFc8XVsxB9d19+jK2qVDaaJswOigPJYL5IozIDJP3swMS5I9Qgqwc/n0bY0LBHQGrUg9ZNqUmCx/TJ1LJt5TC6qHHLOunAukEiiC14Pv4QNmxYAPfM+LszzIbRpMrjCtL4nCp7JoknOPn1qf3O1STiMri6+iuA+qb8E4gmzesgOYvw7NQiOIuMjuYvrcXIfjFrcnUchwN+YnwPxK+oNudKYT21RCr1LkVG0jHsPAnnyXRSjCIW4f2taFptXNhBQmnusGklc2jzTce/e7nc2kAq8hOlqEUPop7/4SeOW+Yj207KtXjAarIoco+/oIVNFWp336ORbPCQIKPYXy8+xwCltMj9NRT9neu0lhtmnuT9BQ).

Probably this is a known issue, but if there is an easy fix for it I'm happy to contribute.

Thanks!

**Comment by lilleyse** [comment]
Hi @na9da!

`ClassificationModel` doesn't support Draco compressed models right now. In the short term you can use the code from this PR: https://github.com/CesiumGS/cesium/pull/8316. In the medium term we plan to integrate the new `GltfLoader` into `ClassificationModel` and Draco will automatically work: https://github.com/CesiumGS/cesium/issues/9520.

https://github.com/CesiumGS/cesium/blob/999ee4e6b82438996c30955cc47103bcfce4a35f/Source/Scene/ClassificationModel.js#L58-L64

**Comment by na9da** [comment]
Thanks @lilleyse 

I'll test out the draco loading code from #8316 to see if we can use it.
Good to know that a fix is in scope in medium term.
