### ISSUE TITLE
Globe `lambertDiffuseMultiplier` test failing/timing out

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10168]
In the latest `main`, one unit test is either failing or timing out all of a sudden.

![image](https://user-images.githubusercontent.com/8422414/157065137-38fe36f5-7e8f-4b78-b3d9-e4d24f4127d7.png)

error in the console (thanks @ebogo1):
```
An error occurred in "SingleTileImageryProvider": Failed to load image Data/Images/Red16x16.png
```

[Unit test link](localhost:8080/Specs/SpecRunner.html?spec=Scene%2FGlobe%20renders%20terrain%20with%20lambertDiffuseMultiplier)

Browser: 

Chrome 98.0.4758.80
Firefox 97.0.2

Operating System: Ubuntu 18.04

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/10263#issuecomment-1086262447
