### ISSUE TITLE
Is Earth  rendered using an orthographic sphere?

### ISSUE THREAD

**Issue by Phlicess** [CesiumGS/cesium#10192]
I have a data based on an orthographic projection，when rendering to Cesium, it is found to be offset to the north and south poles。My data's radius is 6378137m orthographic projection。
So，what is my mistake？

(｀ﾍ´)=3

**Comment by Phlicess** [comment]
My data format is 3DTiles，My question is whether the 3dtile data points will be converted to positive sphere coordinates and then rendered to the earth?
Or the rendering coordinate system of the sphere is originally EPSG4979 ellipsoid ？

**Comment by lilleyse** [comment]
@Phlicess By default CesiumJS uses an Earth-centered, Earth-fixed cartesian coordinate system (EPSG:4978) and most 3D Tiles use this same coordinate system. If the data is in an orthographic projection than it may not display correctly.

**Comment by ggetz** [comment]
Closing as the question appears to be answered. If there are anymore questions, please ask on the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
