### ISSUE TITLE
pickFromRay/drillPickFromRay return incorrect position

### ISSUE THREAD

**Issue by WilliamLiu-1997** [CesiumGS/cesium#10201]
This bug seems to only appear on specific devices. The position of the object returned from `pickFromRay/drillPickFromRay` sometimes will go through the object, and some times will float near to the camera.

Here is an video about the behavio: https://www.loom.com/share/f21e8aa434f748cd86436e70de4664b6
(The red point should be on the tileset, however, it will sometimes pick through the tileset and sometimes just float in the air -- around 0.5m away from the camera)

I have test five GPUs and it happens on one of them:
1. RTX 2060 ✅ 
2. GTX 1050Ti ✅ 
3. M1 ✅ 
4. Intel UHD Graphics 630 GPU of i7 8750H ✅ 
5. Intel UHD Graphics 630 GPU of i7 9750H ❌

It seems that the issue will also happen on Intel UHD Graphics 630 GPU of i7 9700

Sandcastle example: https://sandcastle.cesium.com/#c=dVNra9swFP0rIp9sMMrGtjLyYiFJV8NIQmJaBoaiSDetVlkykuwuLfnvkyU3cbbOH+Lce88592mqpLGo5vAMGo2RhGc0A8OrAt96X5T3qLdnSlrCJei8l6DXXCJkQWvnWWtVcwZ68EakGoiFO6UFywIkipNcHuNhLnNJfULLBRiwlxnD69M8C8HIZ6m0OCmnSm7AqEpTwHutiqlxsJRFnz98vbrq5AjtYENBAi41L7jlNRhMGIvazA2whb0oVWSqG8jlvpLUciXRlLG14tJGZfMb+5JaHkjrdFtZH2ieUhneMAfIM5Kz31kDdMJ5H/8NYstfYIC+JN0AVUKdBzprLLxZzC8wjBuyEzCH0j5mYOycG0skdVrLqti5+tarbZqlt4v7dHmdLtPs54l+9P/8sI5Nt50dbN32QG5LQmFRuw5viGTCncHFSCmRNTExbqYvy8pO/ayiCGI0noQWw5qD2rodidu2W0drDM8oTQ4u1GagpABN8APYNadPG3KILkXiDlHtfgG1Z267cMe7dtfRcJ10IJz2GDinMvwMkv91nx1KwJv0+012P1/dLeNhL+mNjD0ImLzN8hsvSqVtc6cRxn0LRSnc+Zv+rqJPYDE1JlSA0KjfpY4YrxFn43c+MEQFMcZF9pXw95H3JqO+w/9DFYowLh9WNWhBDg3s8ePkR3BijEd9Z77PtEqJHdF/Kf8B

Browser: Chrome / Microsoft Edge

Operating System: Win11

**Comment by ggetz** [comment]
Thanks @WilliamLiu-1997 for the detailed report! I don't have the needed hardware to reproduce, but if you're able to investigate any further on the device you're seeing the issue it would be a big help.

**Comment by WilliamLiu-1997** [comment]
Hi @ggetz, just found that the problem is actually caused by the **Intel graphics driver version**. The version `30.0.101.1221` and `30.0.101.1631` will have the problem and version `26.20.100.7985` won't have the problem. I haven't tested others.
https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

**Comment by ggetz** [comment]
Thanks @WilliamLiu-1997 and @joshsink for tracking down the driver version! 

Unfortunately if there is an issue with a specific driver, there's nothing really we can do on our end to fix. I'd suggest opening a bug report with Intel. Hopefully they can address it soon.
