### ISSUE TITLE
Unit test command line usage is more limited than the old SpecRunner

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10200]
I understand why SpecRunner was removed (to avoid maintaining it in `ThirdParty` separate from `npm`, but the command line testing workflow is more limiting.

One thing I do quite often in SpecRunner is to filter for tests. That way when I'm working on code, I can select a single test or many tests using `?spec=<search query>` or the "Select a unit test to run". This is a lot easier to work with than `fit/fdescribe`.

I've been trying out the new `--includeName` and it's not finding tests from nested describe blocks as well as the `?spec=<search query>` in the `SpecRunner.html` does.

(on branch `extension-revisions`) I wanted to run the tests from the describe block `Scene/MetadataClassProperty > "normalize and unnormalize"` but when I run `--includeName 'normalize and unnormalize'` (being very careful to use strong quotes in bash to avoid escaping the spaces) or even just `--includeName normalize`, 0 tests execute so I think this test filter doesn't look at nested describe blocks. Meanwhile in the SpecRunner, `?spec=normalize and unnormalize` works fine and gives me the 10 specs I want to run.

...I suppose I could always do `fdescribe()`, though I've gotten used to the search query workflow that doesn't involve fiddling with the code (and accidentally committing it in the process)

Talking about this with @ebogo1, one of the limitations is that `--includeName` only has access to the top-level tests, not the inner describe blocks. That's unfortunate.

@j9liu you had a few more limitations of using `npm run test`, could you add the details in a comment here?

**Comment by IanLilleyT** [comment]
GUI is useful because I never remember the name of the unit I'm debugging. It's usually some randomly constructed sentence describing the behavior. (Check out all the unit test descriptions -- there's no consistency, and I'm not sure there should be either). The html make it easy to find what I'm looking for.

Just my initial thoughts. I haven't used the new system much but I will be in the coming days

**Comment by ggetz** [comment]
I appreciate you both writing up your thoughts. As a more meta comment, it would be great of we could move discussions like this to the forum, to engage more of the community. We have [a thread already for discussion around the testing changes](https://community.cesium.com/t/changes-to-unit-test-debugging-in-cesiumjs/17537).

Besides the fact that before we were clicking a link to a static page and now we're running a command to start a server, everything we were able to do with the standalone runner, we should be able to do through karma. We're still using jasmine just like before, just changing the form factor of how it's run.

> I've been trying out the new --includeName and it's not finding tests from nested describe blocks as well as the ?spec=<search query> in the SpecRunner.html does.

We have control over what we want to do with the search query and can adjust it. Right now I believe we are filtering at the `describe` level, but not the `it` level. But we can add that if that's what needed here (I couldn't find the tests or blocks you're referencing, so I'm not sure). I'm pretty sure nested describes can be filtered, but I'm not sure of the details.

> I suppose I could always do fdescribe(), though I've gotten used to the search query workflow that doesn't involve fiddling with the code (and accidentally committing it in the process)

eslint will catch this if you accidentally leave it in. 

> Having a graphical interface with SpecRunner helped me to visually confirm I wasn't missing any test cases, and that the unit tests were properly organized.

There are some options for more visual test results through different **reporters** that aren't tied to the standalone version we had previously, such as [karma-jasmine-html-reporter](https://www.npmjs.com/package/karma-jasmine-html-reporter), which we can explore adding as an option.

> The ability to keep the same SpecRunner window open, make changes to code, and then refresh the change made for quick and easy testing. It's slower to type npm run build after every change and restart the tester.

While `SpecList.js` needs to be rebuilt with `npm run build` when you add or delete a file, I believe this was also the case for the standalone runner. And unless you are running the release tests, you shouldn't need to rebuild each time you run the tests.

> I find it a lot easier to debug in VSCode vs. browser debuggers. I have to search through the Source / Spec files in the browser console, put multiple breakpoints, and then restart the page. It's inconvenient to repeat this process every time I have to restart the debug window every time I make a change

It's possible to debug with VSCode still. @ebogo1 I think we should commit to adding a launch configuration for VSCode as a part of finalizing the testing improvements as it'll help make it clear that this is possible and avoid developers having to deal with the overhead of setting it up.

**Comment by ptrgags** [comment]
@IanLilleyT according to https://github.com/CesiumGS/cesium/pull/10170 you need to add the `--debug` flag so Karma doesn't exit at the end.

**Comment by ptrgags** [comment]
I linked to this issue in the [forum thread mentioned above](https://community.cesium.com/t/changes-to-unit-test-debugging-in-cesiumjs/17537/9?u=ptrgags)

**Comment by IanLilleyT** [comment]
I tried some other things from [this stackoverflow post](https://stackoverflow.com/questions/42805028/how-to-debug-karma-tests-in-visual-studio-code) but no success.

```
{
    "name": "Attach Karma Chrome",
    "request": "attach",
    "type": "chrome",
    "address": "localhost",
    "port": 9876,
    "pathMapping": {
        "/": "${workspaceRoot}/",
        "/base/": "${workspaceRoot}/"
    },
},
{
    "name": "Test Cartesian3",
    "request": "launch",
    "type": "node",
    "runtimeExecutable": "npm",
    "runtimeArgs": ["run", "test", "--", "--includeName", "Cartesian3"],
    "cwd": "${workspaceFolder}",
    "serverReadyAction": {
        "action": "startDebugging",
        "name": "Attach Karma Chrome",
        "pattern": "SUCCESS Core/Cartesian3 construct with default values"
    }
}
```

The idea behind this was `Test Cartesian3` would kick off `Attach Karma Chrome` when the string `SUCCESS Core/Cartesian3 construct with default values` was printed to console. This was modeled after the `Launch Server` configuration in `launch.json` which looks for `Cesium development server running locally.` before opening a browser window. I chose the `SUCCESS...` string because that was the first thing printed in the karma `Debug` tab. So it's not a good fix because it's hardcoded to `Cartesian3`. We would need to print something more generic. Also it doesn't seem to trigger the `serverReadyAction`, possibly because nothing is getting printed to the VSCode debug console which might be what VSCode is looking for before it can kick off the `Attach Karma Chrome`.

Side note: How would we debug with Firefox, Safari, etc?

**Comment by ptrgags** [comment]
Also when fixing merge conflicts in #10189, I noticed a couple issues:

* If you have an uncaught exception in a promise chain (in my case we had some stray `.otherwise()` clauses that needed to be converted to `catch()`, an error gets thrown and reported in the log. In that particular case it was something using `pollToPromise` so I wasn't getting the whole traceback. The Karma window hung so it wasn't printing the whole summary, so I couldn't see the full error report. If there's no summary, you have to scroll back in the terminal a lot to find the full error (and often the history gets cut off)
* When I put the Karma tab in the background, some tests about the render loop timeout. When I run it with the tab visible it works fine. I don't remember seeing this before. I'm using Kubuntu, might be good to see if that can be reproduced on another OS.

**Comment by ebogo1** [comment]
> When I put the Karma tab in the background, some tests about the render loop timeout. 

This has been an issue for a while with the SpecRunner too, where some specs time out if the cursor moves. I couldn't find an open issue for this but I don't think it's new behavior.

**Comment by ggetz** [comment]
> If you have an uncaught exception in a promise chain (in my case we had some stray .otherwise() clauses that needed to be converted to catch(), an error gets thrown and reported in the log. In that particular case it was something using pollToPromise so I wasn't getting the whole traceback.

I think that's from removing when.js, not from karma. Because of our use of `defer` a lot of the errors we throw are not properly handled, and throwing any error will fail a test. I'm not sure what was all involved in your case, but there's some cleanup we're doing so that errors are properly handled https://github.com/CesiumGS/cesium/issues/10178.

**Comment by lilleyse** [comment]
Is it possible to see `console.log` messages in the terminal when running tests? Sometimes the spawned browser window closes before I can read logs that are printed.

**Comment by ggetz** [comment]
> Is it possible to see console.log messages in the terminal when running tests? Sometimes the spawned browser window closes before I can read logs that are printed.

Use the `--verbose` flag. You'll get some other noise since both karma and cesium itself can dump a lot into the console.

**Comment by lilleyse** [comment]
Thanks, that works.

In this case I'm just printing a string but if I'm printing an object the browser window is useful. Of course, running the debugger is an option too.
