### ISSUE TITLE
Performance issues with clustering.

### ISSUE THREAD

**Issue by AstrosChen** [CesiumGS/cesium#10202]
I loaded 50000 points using clustering. : )
this is my code:
`
    
randomPoint (num) {
      num = num || 100
      const arr = [] 
for (let i = 0; i < num; i++) {
        arr.push({
          lng: Math.random() * 180,
          lat: Math.random() * 90,
          name: 'point-' + i
        })
      }
      return arr
    }

    clustering () {
      const img = require('@/assets/img/icon.png')
      function formatGeoJson (data, types) {
        return {
          type: types[0],
          features: data.map(ele => ({
            type: types[1],
            properties: { ...ele, RAWDATA: ele },
            geometry: {
              type: types[2],
              coordinates: (ele && ele.coordinates) || [
                +ele.lng || +ele.longitude || 0,
                +ele.lat || +ele.latitude || 0
              ]
            }
          }))
        }
      }

      function formatGeoJsonPoint (data) {
        return formatGeoJson(data, ['FeatureCollection', 'Feature', 'Point'])
      }

      const data = formatGeoJsonPoint(this.randomPoint(50000))

      new window.Cesium.GeoJsonDataSource('converge').load(data).then(dataSource => {

        window.ktcesium.viewer.dataSources.add(dataSource)

        dataSource.clustering.enabled = true

        dataSource.clustering.pixelRange = 15

        dataSource.clustering.minimumClusterSize = 3

        let removeListener

        function customStyle () {
          if (window.Cesium.defined(removeListener)) {
            removeListener()
            removeListener = undefined
          } else {
            removeListener = dataSource.clustering.clusterEvent.addEventListener(
              function (clusteredEntities, cluster) {
                cluster.label.show = true
                cluster.billboard.show = true
                cluster.billboard.id = cluster.label.id
                cluster.billboard.verticalOrigin = window.Cesium.VerticalOrigin.BOTTOM
                cluster.billboard.image = img
              }
            )
          }

          // force a re-cluster with the new styling
          const pixelRange = dataSource.clustering.pixelRange
          dataSource.clustering.pixelRange = 0
          dataSource.clustering.pixelRange = pixelRange
        }

        // start with custom style
        customStyle()
        const handler = new window.Cesium.ScreenSpaceEventHandler(
          window.ktcesium.viewer.scene.canvas
        )
        handler.setInputAction(function (movement) {
          const pickedLabel = window.ktcesium.viewer.scene.pick(movement.position)
          if (window.Cesium.defined(pickedLabel)) {
            const ids = pickedLabel.id
            if (Array.isArray(ids)) {
              for (let i = 0; i < ids.length; ++i) {
                ids[i].billboard.color = window.Cesium.Color.RED
              }
            }
          }
        }, window.Cesium.ScreenSpaceEventType.LEFT_CLICK)
      })
    }`

This is a picture showing the effect and performance：
![image](https://user-images.githubusercontent.com/16367328/158762260-b4a2fa14-b633-453e-a2a4-97811eb06410.png)

my doubts：
The loading speed is not slow, but the frame rate is very low when dragging.
Can clustering currently support such a large amount of point data? Can this problem be solved in other ways?

**Comment by ggetz** [comment]
@AstrosChenI think with the amount of points you are rendering, you may be running into the upper limits of the entity system. We usually recommend using [a point primitive collection](https://cesium.com/blog/2016/03/02/performance-tips-for-points/) for better performance, but the API is a bit lower level.

I'd suggest asking this on the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help troubleshoot more.

This also may have overlap with https://github.com/CesiumGS/cesium/issues/5096#issuecomment-472400199.

**Comment by maylortaylor** [comment]
Can you use Clustering with Point Primitive Collections? I don't think you can.
