### ISSUE TITLE
Light behaves differently in customShader than it does in normal scenarios

### ISSUE THREAD

**Issue by xuebingzzz** [CesiumGS/cesium#10218]
So here’s a model, in the normal case, that looks something like this
![image](https://user-images.githubusercontent.com/56542531/159395110-7d39a0b5-ab5b-40b8-af09-b6889213f86c.png)
When I added,
Cesium. ExperimentalFeatures. EnableModelExperimental = true;
after,
The lighting is too extreme
![image](https://user-images.githubusercontent.com/56542531/159395300-d4fb5d00-0950-45a8-b21a-843cfecf4e41.png)
However, after I remove the lighting, I can’t see the outline clearly. How do I get the effect of figure 1 in CustomShader
![image](https://user-images.githubusercontent.com/56542531/159395338-507b10ed-d0bf-4070-a188-5e91f4204891.png)

**Comment by ptrgags** [comment]
@xuebingzzz I think what's happening here is `ModelExperimental` does not yet support image-based lighting, so glossy surfaces are far too dark.

Fortunately, we are actually working on adding IBL to ModelExperimental in the next couple weeks. See these issues:

* https://github.com/CesiumGS/cesium/issues/10059 (in progress)
* https://github.com/CesiumGS/cesium/issues/9838

**Comment by ptrgags** [comment]
Just to cross-link things, this issue corresponds to [this forum post](https://community.cesium.com/t/how-do-i-adjust-lighting-settings-for-customshader/17789)

**Comment by xuebingzzz** [comment]
Now that IBL has been added to the shader, the existing effect seems to be to replace the completely black texture with shadows, but when the lighting changes, this part of the texture does not change, and I'm not sure if the IBL takes reflections into account.

**Comment by xuebingzzz** [comment]
![image](https://user-images.githubusercontent.com/56542531/163295216-96cf3734-e6a1-4e00-a9cc-1192ffb211e3.png)
![image](https://user-images.githubusercontent.com/56542531/163295348-c908c9b0-abaa-4797-bf6d-909c5ad70357.png)
This is the display effect of the model under different lighting, the color of the marked part is always unchanged
