### ISSUE TITLE
`Model` spec failure: "Loads with incrementallyLoadTextures set to true"

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10216]
This was introduced in #10214. Despite not changing anything in `Model` or `ModelSpec`, this test is consistently failing in Chrome on Windows 10:

![image](https://user-images.githubusercontent.com/32226860/159351028-3248e5bd-3e85-4c7d-92a1-5f6519bcb7b6.png)

However, `fit`-ing this test causes it to pass just fine. `fdescribe`-ing the entire `Model` spec causes this to fail. I went through the trouble of `fit`-ing tests that come before it to find out the earliest one that introduces the error: `"renders z-forward model"`.

Unfortunately there isn't a simple fix for this right now. Adding an `afterEach()` that calls `primitives.removeAll()` breaks several tests that expect models to persist between tests (yikes!). Additionally, as @ptrgags pointed out, if one were to set `jasmine.random: true` in `karma.conf.cjs` there are even more test failures that arise. Overall, it seems that `ModelSpec` was written in a brittle manner and it would take more effort to debug.

We're working on bringing `ModelExperimental` to production such that it can replace the old `Model` class, so it may not be worth it to salvage the `Model` specs. This issue is moreso to note the test failure in case it gets reproduced on other machines.

**Comment by ebogo1** [comment]
I can reproduce this on macOS as well

**Comment by jiangheng90** [comment]
I think maybe the test will fail on high performance device. It failed on my rtx 3070 desktop, but will pass on my amd laptop.

**Comment by j9liu** [comment]
`ModelExperimental` has replaced `Model` as of the 1.97 release, so the old `Model` specs have been deleted. This issue is no longer relevant.
