### ISSUE TITLE
Metadata group ID is required but should be optional

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#10223]
As of the current state of the [`group.schema.json`](https://github.com/CesiumGS/3d-tiles/blob/56d64d704b5b109b74c01d027c21db633ce299e4/specification/schema/group.schema.json#L13), the `id` is not `required`, but the [`GroupMetadata` constructor](https://github.com/CesiumGS/cesium/blob/3520c520abd447c7d0b7f13f4d910d154bb20b02/Source/Scene/GroupMetadata.js#L29) checks for its presence and throws if it is not present.

**Comment by lilleyse** [comment]
@j9liu could you take a look at this? `group.id` was recently removed in https://github.com/CesiumGS/3d-tiles/pull/678#event-6320122581. The property should still exist for backwards compatibility with the dictionary form of `groups` but it should be optional.

Another place that expects `group.id` to exist is [here](https://github.com/CesiumGS/cesium/blob/75f90c2d8ce290ee0d56b39f334ec493da448abb/Source/Scene/Cesium3DTilesetMetadata.js#L56-L65).
