### ISSUE TITLE
`GlobeTileSurfaceProvider` spec failure: "culls tiles but does not render fog visuals when renderable is false"

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10225]
This test is consistently failing in Chrome on Windows 10. It wasn't present when I wrote up #10216 so it must be something recent.

![image](https://user-images.githubusercontent.com/32226860/159777962-79bcc3a8-7dcd-45d1-a3dd-c011cb9150bd.png)

@ptrgags also ran into this test failure on Linux (Kubuntu 18.04), Chrome 99.0.4844.51

**Comment by lilleyse** [comment]
Related to https://github.com/CesiumGS/cesium/pull/10186?
