### ISSUE TITLE
Continuously printing error messages when zooming to a tileset that cannot be loaded

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#10222]
<sup>Tested with Cesium 1.91, with the current [state of `main`](https://github.com/CesiumGS/cesium/tree/3520c520abd447c7d0b7f13f4d910d154bb20b02), on Google Chrome, Version 99.0.4844.82 - although the latter is likely not relevant here</sup>

The following sandcastle tries to load a tileset that does not exist, and then zoom to it:
```
const viewer = new Cesium.Viewer("cesiumContainer");
const tileset = viewer.scene.primitives.add(
  new Cesium.Cesium3DTileset({
    url: "http://example.com/tileset.json"
  })
);
viewer.zoomTo(tileset);
```
It causes the following error to be printed continuously, flooding the console:
```
Uncaught (in promise) RequestErrorEvent {... }
  Promise.then (async)		
  updateZoomTarget	@	Viewer.js:2194
  Viewer._postRender	@	Viewer.js:2176
  Event.raiseEvent	@	Event.js:138
  Scene.render	@	Scene.js:3897
  CesiumWidget.render	@	CesiumWidget.js:790
  render	@	CesiumWidget.js:42
  requestAnimationFrame (async)		
  requestAnimationFramePolyFill	@	requestAnimationFrame.js:65
  render	@	CesiumWidget.js:43
  ...
```
This happens regardless of what caused the loading error - a malformed JSON or any other invalid element in the tileset causes the same behavior, with a different error message.

---

My gut feeling is that somewhere around [`Viewer#updateZoomTarget`](https://github.com/CesiumGS/cesium/blob/3520c520abd447c7d0b7f13f4d910d154bb20b02/Source/Widgets/Viewer/Viewer.js#L2194), there should be something like
```
if (target.failedToLoad()) { return nopeNotGonnaTryThatAgain(); }
else { return target.readyPromise().then(...); }
```
or maybe the Error that is thrown from trying to load the tileset should cause a call to `cancelZoom` or `clearZoom` or so in the chained promise that is created there, but these are just guesses until now.

**Comment by ggetz** [comment]
Thanks @javagl, there's a few areas where we're in the process of cleaning up error handling after the transition from when.js to native promises-- https://github.com/CesiumGS/cesium/issues/10178. I believe this should be addressed as part of that effort.

**Comment by javagl** [comment]
This still seems to happen in 1.95 - OK to reopen this?

**Comment by ggetz** [comment]
@javagl Sure, if you're testing from the latest `main`. We thought the was fixed in https://github.com/CesiumGS/cesium/pull/10523.

**Comment by javagl** [comment]
I might have got the release cycles wrong. It happens in 1.95, but no longer in main. Sorry for the noise.
