### ISSUE TITLE
Can `package.json` export `Build` & `Source` directory?

### ISSUE THREAD

**Issue by onsummer** [CesiumGS/cesium#10235]
like:

``` diff
{
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "require": "./index.cjs",
      "import": "./Source/Cesium.js"
    },
+   "./Build": "./Build",
+   "./Source": "./Source"
  }
}
```

So in some bundle environment (like `Vite` or `Webpack`) can find the css resources exported from `cesium` pkg:

``` js
import { Viewer } from 'cesium'
import 'cesium/Source/Widgets/widget.css'

// or
import 'cesium/Build/CesiumUnminified/Widgets/widget.css'
```

Otherwise can only add `<link href="path/to/widget.css">` to `index.html`, here is a personal demo using Vite to build Cesium `Hello World` app: [openspacing/cesium-vite-template](https://github.com/openspacing/cesium-vite-template)

**Comment by ggetz** [comment]
Hi @onsummer, is this question about exportig css specifically? With the current configuration of `package.json`, there is a problem with that covered in https://github.com/CesiumGS/cesium/issues/9212. We'll probably take a look at that in the near future as part of a larger modernization effort. 

I'm closing this as a duplicate, but if that issue doesn't cover your issue let me know.
