### ISSUE TITLE
Ellipsoid renders differently with fixed vs callback properties

### ISSUE THREAD

**Issue by Sboddd** [CesiumGS/cesium#10245]
Given two ellipsoids that are otherwise identical, if one has CallbackProperties (or other dynamic properties) and one does not, the actual rendered geometry on the screen will be different.  The linked Sandcastle example has two ellipsoids, one with innerRadii and radii specified as `Cartesian3` values, and the other with them specified as a `CallbackProperty` that returns the same `Cartesian3` value.  You can see from this screenshot that the rendered geometry is significantly different:
![image](https://user-images.githubusercontent.com/48965472/160696149-e54b9c0a-69d1-4082-819a-9ef0a8f26dc1.png)

From some local experimentation, it seems like if any of the geometric properties are set using a dynamic property, this issue crops up - e.g. if the inner/outer radii are specified as `Cartesian3` values, but the min/maxCone values are `CallbackProperty`, you still get the same problem.

Sandcastle example: https://sandcastle.cesium.com/#c=vVZtb9owEP4rFl8aJGaSQBLCKNoKtCCtpaOo3SS+mMQtXo0d2U4prfrf54SXLiGlL9oWIWFf7nnOvud8TsCZVOCO4AUW4BAwvAAdLEk8h5epzZiUgnTe4UwhwrCYlMqfJyxIcXz665zLLK6DhNIjxGrGJ8ttmJZpmhXgeLaXDizXcZNRQrIKCzFTRBEsIQpD43HCAGBojpvg4JwTpg4qiSXiUvtw1syGonSKgttzwSMs1NIwyuCwvV5VBVwjKnE5hT8/XBAdD6241jzfY6SwYNoEB93e2Xgw/plDCXyNBWYBPhbp0tbAUcYMjwc/et0cMkr20ASPWWvyBJxysaXqJDN4Mur1ziq7vjxWVCe/UwC56g/GvZchVyRUsyawCjwico/pBXnQ+7HMgvcyQBQfLbtEKqT3mEn9GUbiGIkL7YKEYUEH21pb6FSAbUITexWg/8pZzqdcDIqmmBamRuF7lVU6KTfE1FbpdW2UC5Y90xI/JNVKh4LckGeZ+7kXcDQ46Y8LGO50CBLs4C8zZng0HI+Hp38jbzY00+Rt0lbAqQRiksaBLrbl+yTZS52XRM74oqmDxXjCnpIj+vohvcLhDd57SLf9QC8l+a0WgSklkeQk3FaAQCEhL2E9z3dMq6a3sTva7Iow3Z9G+1jsuu1ZKXZ3tGGZE0bmuuFRHtxutT9FagYVT8i1EIazzeQc3b/q7Zp5bs506kxou5bn+7WG3ohv1f16jjP1smHD8z2/ZruO55tuveZsvXTTIojm+sGo14ULomZfaTRDho6RnsKnN+vZOQL/VtJczwarpv0R1bMd/kX1Cy+Jj9RHNt5b6sR9V500/medpFfNnkopVUotqZYUtzct4guZR1woEAtqQFhVeB5RzS2r0zi4xQoGUibAxLVV/RPaCskdIOFhwbcECCiSUr+5jml6F01K7VZV++9AKddZYjdD3ZwpWiZuM6v9bWWEELaqelqMVJzrChA55t8

Browser: Chrome 100.0.4896.60

Operating System: Windows 11

Cesium version: 1.91 and 1.74

**Comment by srtrotter** [comment]
I stumbled into this bug recently as well. Any status on when this might be addressed, @ebogo1, @ggetz ?
