### ISSUE TITLE
spec failure: renders terrain with lambertDiffuseMultiplier

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#10258]
`renders terrain with lambertDiffuseMultiplier` will fail when I run test in afternoon(China)
I think it need to set a sunlight direction

**Comment by ptrgags** [comment]
Hi @jiangheng90, does the error message look like the one in https://github.com/CesiumGS/cesium/issues/10168 (failing to load a texture) or does this give a different error?
