### ISSUE TITLE
`tileset.modelMatrix` not working for `.i3dm` with `ModelExperimental` enabled

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10255]
Found this while testing for #10250. With `ExperimentalFeatures.enableModelExperimental = true`, the instanced model doesn't show up at the correct position, instead remaining on the ground. The PR itself did not introduce it; I tested on `main` and the same behavior occurs.

![image](https://user-images.githubusercontent.com/32226860/161143298-ff36c9b2-ad59-485e-97ba-6392a2099797.png)

Here's a [sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=7Vl7b9s4Ev8qPB+wta8O47y6PTvpXZq4aIDtpte4LRZ1saAlxuZGFnUU5cRb+Lvf8CWRshw77f55QZtI5HCeP84MqQuas2KOhw8ZFWxOU0mSN5TIQtAc05RMEvqOxzTx59EZkqKgg3E6Tvf30XkcI4KihGUZS6coS0hKuzCiH9CU8jmVYokkR/mM3yM5o0jQDPgrZpLxFPFbNaqZudVpjCKeSsETvWBOpimTRUwtrWUes1ySNKLonsmZIeRFTrHSDJbnEi0YvacCNE7pPbowtn7SY+1xK9LvFyCHsJSKcauLvo1ThFh6y1/zhz66JUlOu2oopwmNlLJXacwiIrmoZledgROXRxTUOrNisX4dVNooJ11P/gBOORB9GbeuUmNA3EUpB+XB02CrFOxBKePNGwtDgq8D30odJuCqLYjppJi+5gUom04/8aSY03yooxn7VtF4Sm/kMgGiclaF1kw+kHmW0NEyo3nfV13PRoUQEMBhRRTQfOl9VZ7RtidUIknElMrfQL8e7g3MmI7hMJVMMqr98dVOGGfT+L0isGMOX3osd9i70ZQWDfczmhoAoJjfl05Xz28BUEkdBzeRoDS9yUhEhwuwxRK1lXl+AHFE0gXJx6mKs8cN51RepVkhzzUy2rdFqh9Qe84XVO2VjomG0SNj0R2NjX9AEcNaDZbkOOM5UxyUIIDhLdK6IKdwTG8Bp3Hb59RBP/20lQizeFc6rH3ZUaRWexTGA1RvXDJooMUAVUgbOmVYsRc84QJ/fns1GmKF6fMkm5E2gOKk08iBFxLgSfWyRi5ulXZnXoX0gsypIBcmiahomWymA6bQpneBXrwCoHY3gUIhG/8yfDP6/fL6868dB7wPoCTJXR7iDndF5lBXZH8d5kpemxFnY6UgU4tv4M5Oc0yfEKeDHwxTDUqQoYyeLhI62T41lrYc7RLFj+/LGH7MYjC7HkK1GV0Q1fNfF0aP286pY/eA2mRHE0lUmi1zChQQId/bxIKXaK+aomlcTdgAuUT9/Mzy2nGLvLv+eDP8/d31p6Hxb2kREIOXtbLG4W/sTNtkGqO/oNBypGgN0MiEB5eV/sxpaPW1C6sUpGrOqiw7LIE+Qw48fRJO4pEZbhcicSk6KC9hsC/8uQsFQKO/ryBUyC/mFW1c2nYEIQmEB55IeqSyYBfpX3sHuNfpVvQw6F7c8Ff7V9XwzyyWs37VBuD1wo7+hYAn6mv+2k8mTsj5qNa14AzaPYDGAvpAEsdWd19v/efo0vnym1MQnNpXv0r1Q9/2a++WbGVKTqgT1n3MDbSNYS+DzsyiyuBHGp6Bhy/HFzAZL98LPmc5NawwdI8NCbXaWRPL/CabUaFxaHmFE4NwlSAxKxSeQipsxq21zhTw/Z+cz0fcQ4qV0m3EzlswQzmSyWj2gaRTChA6AfT08GHXif4HOgYslejxRFb9hfr5m+X5TneXx5j+t4AK6RFUURGcSywFSfNbLuZdn6TG5Opy+OvoavRbRVJpUjkYIcjGI+jew0MEYjm04oBBkiRL5HojgDKRute36jzLkVIIlQrhgO95lsFqkiJAsWZAXAetjiQAdah8ml1NOIBAjbq4odzE3SzwRJg4l8IvDMOzuicgZY0UTaKPPE91a3O+6HhuHWzWCBbwqSDZjEVeafZG8S3shJJvqFto12MCQ4T/mNTGrYWjrTrMKJvOpEsP5mezXtiS7zVbvE7pywuSGNYnMxPr9dgrQzcFf1slMIIbI72qtjLoi9qq4DF1whrAn9O6hglNp3I2QM+fs2Dr2cOJ7cdqiwC1bbbu5urktqzKBrUnOV0uvvk2uq3bR40BDZCuWfdRsB7Os+rqIQcWUD6aPHbYDulRlf0OISM+NhnOdWq0rjHub++LayutIYG2STIh0R3UnYwKuVzTeVurtGaHPsM8boBtzL1z/dqcNqnJwIB85b2t/DKCwoM8zop81vYQEgDW+j+oxgO/A4BKHBEoZ14ppkJwUavHPKE44VM7V3JwvV/Q7ekO4f+9nncTYfdjmJeNYjpZXdIptPiu+O8dHB7h3s/Hxy8O/mkVOYae4qR39HPvhR046lm1TSxcNtbtSZAQZ1jyDzAM2bB9cHQCpg/8KxKIfHlHVPZQEIa1wVlWO5IFvRCsaFvpXcO1q9n4wrhg5Q1kqeHIZf8cz2oM/1OoXJBWCdy50boANKo7gO6QIlM42/r9cpUsa/w9ffv+i53WFchLnIVgYRueRyQBSS/LgTk0V/Ni/p490OSG/QlzBz2HmN379hBg1lAoouqKqCwRxhGW5juL1e6F6slFaqPPm+rR9lqkN0PX7Al/Z39fMXliIXlSEakVEH9yU+HYuWisul5W9tLnlkKxsincBJG5C/CPIjFt3biF8T78u9EXz5dEkv3gKLpf3plXT9fVbtl3veUfOU/HLXNB7V0J+ALLm6KRgrP5KKG9a04GTLcyucazGlAQM9vQaS85h0CpRBXzqNB3LgDUYaKvX14vr+BY3bI045aSZt15l/LoDhxt9lG7zPVNJESdb15bXSrSrhNujKitUo5UqlxPcioWqmj4K8et9dt90E8vyotJHgk2oV6BBmh+IklBy60qtCuruKuTpiNCZ2dntS8FXm1/LBQaTIgCYnen10dAd8mlo1RSlRcfZMIXEFJoJQgruxoHk7Cx9zbh9ua+ufAfnOiif/ISv+iikx5+eXgSnM7LRmn1XZF75CLksRAugvg13Dpaf3S8WG29pEGa64/btN7h7G6KLcSucXJK+S1SCdNaTfEXlc8Dz4xSpsW7kVmvNIKqC9dz6EhMeDfdshm60tGatvETGVr7muZf4vk36jqRtrqt0xy8R1+5wP2bzTMupOoO2pBJJYVNDlkt358UULUljvK82j9/d0nMK4Gq+EyFinYfiemEtI8Pu8j9B0j7J8ZM3buk0z46zh684QkXMRV75iQWTq7WRDN1Ve4rsICyx6Cf2SMJm0LZnrM4Tui61D3Jsz46DCS7qQmXks/D2XXRug2kgfW3PJV79/pcrk60SVxffrrv+/s0ZgvE4rOG782AOJLnMHNbJLoFG7dene4D/dpSledA6WswPCFLRTY7ePWLGcQYn+7Da/PKsr6U4T81XxAQNAdkT1UxoOKZNB2N/9W3a/ZKHzWVAxBn+FR8TZgkTCtjZzS6m/AHsFJzUVbqbqMVCNZk6rvzI4nL6mHamT56puU88yxSyae6qVvoxTtrpfqbTUqtZ56tuhg6vRLlZqlDhQmPefsf) to demonstrate.

**Comment by ptrgags** [comment]
Not sure if it's the same problem, but I noticed in [this sandcastle](https://sandcastle.cesium.com/#c=jVZbc9o6EP4rGuY8mBkifMM2SZo5CUl6YAJpG3pL6ZwaWwQFW+ZIMinp8N/PWjJgJ+nlAdusdr+9fbt2jwiap/ji+5JwmhImw+SShDLnRGDCwmlChllMkuo5eoUkz8nRhE1YlDEh0YqSB8JBzsgD6mnED0pmTBqR+t/LwJQywieNprJst9FrHjJZ6g9uUBiBqkAyQ+ss54hmDIVCECkmrMTsZwzHZBbmiTxVyuNsQRj4nTTIejCfvo7oNR303z/2rRHtiz5714l6fa+/WH760Bt0MSj9F79egFL/cZRezoePt+nwxqLD+8X6avzWHZ4P5fXHi8frnrW4TS/vhx8/f79N369HH/v0qjdY3gLY6Pyt6KfJPIbn4fjzw2h8ag3Hp52RY+LY/5SOppf99M2Fc9ahd4NPg/f+bXAenpn+8kzcv5surH+kHJ/ni0lD1y+BFNEYKsvRjwlDSBWU55HMuJGEU5I0tRwhOacCKxEkrO5HlQMhQy4LHDjMGRQJah1XFQiLXzzeFJfipxCMursqKhBglvE0ZBHBLHswmk/Ns+UT673L39guOWUV15pUMZ3NCCdg8q8gEYAYNdCDJxE2URtZpmli82iPkiUEJ9mdUcfaed/sKSyLFgjw8mNTIfaSZykVpJB/+arks5xFsqBmYXCVhbHuUgvlfNsqbcpJGK91Y/VcqGfj218/lMEGGUrjjfbQ/KaD0raUUUnD5JfWO52EiCIOEtcxshXhYfJrjFJna7g3jjNWtK0cO6AL2GmdbUXwMhdzo9DDpWiPUXWNS1qpw31NauJtByATIutbRN+c87E+NEqGQLFVC7V9aYnT8DtN8/Qm4oSwm2UYkQvOsyJ7V+npNYVFRFTUNIUKriCVMI6NEmOfxBa02iUs54QZQNRXJ1uu1lIqJqBkX7WFtWQ3exdVN8/bWYR1sYKNe0WFhIh53fETBxXXT8pfOVHtgs2eJSvyPBw9Al8UOb4Wk1DJ8LCSaKsWwGEtklYthMNaLMrdUTl1u/GB1Z2QVVjM1KTRQvtN/w7izDksjBkU/7R4EfRjwwq8TtdsFkFXEO6EekmJPwLwncB9BiA1wBmn8R35IxjH9p7BSCCe+FPrTlO/CLfcgjIZ2+lqFrV6gW2wRJGhx+VLuXdKAqkKi68om6Hr6T2JJCxKySkRhm5rc7dd65tRv2OOtkc1NM19XG7nn+iU3f+NVsmDnRbSapsdBSesnM4oBIMQz5L1ONPjHhMhKVMMQYe15QBTBU8hc4wD2+3YXc/Cnmc7luu6ptdCB67vdy3Lwo7nul3H77gt5Lg23C3s267tWV0n8JqKsxnUCr5QSie7UsWUk+iXnk3sml2rY7mm5XRdq2ub4OUApJbbCTzPclzHt+DaUdLAsgPXLg481++6QbO19ZQvf56cie3AdDzb9xyvAwT2LO2ja7qBC0CO79t24AUtZGLHNp2g6ztmEDiOY5ceNuoa53yboQlz2DxqtBrHQq4TcrIN42+aLjMuiw1rYNyWJF0mIQTSnubRAvZUJMS2x8ftqulxTFeIxq9e+OBD6isHTmZ5ktzQRxiwk+M26D8zTWCOKLu7BrYk4bpQm1snV1qIMT5uw9+XLWWWJdOQP0H+Hw) that the i3dm models seem to be oriented incorrectly:

The trees are knocked down:
![image](https://user-images.githubusercontent.com/8422414/163044391-55d280a6-1307-453d-a103-50a8da13a774.png)

I need to check if the bridge is an i3dm, but it also seems to be oriented incorrectly:
![image](https://user-images.githubusercontent.com/8422414/163044715-7a06aa7a-2601-4b9c-9aa9-162580bb570f.png)

**Comment by ptrgags** [comment]
Some more details:

* I did a `git bisect`, it pointed me to [this commit](https://github.com/CesiumGS/cesium/pull/10092/commits/8315ebfd6861b13191ee21b3aed89267edd58e80). It seems like when we refactored the model matrices to support model size, we didn't take .i3dm into account
* Looking back at the instancing code, I'm finding it rather confusing. i3dm handles world space and the RTC transform differently than `EXT_mesh_gpu_instancing` so there's a separate shader code path (see `LegacyInstancingStageVS.glsl`). I wonder how much overlap there is. If needed, we could split `InstancingPipelineStage` into two if there's not much overlap.
* I notice that the old `Instanced3DModel3DTileContent` computes a model matrix with the RTC offset baked in before passing it to `ModelInstancingCollection`. The instancing stage doesn't include this offset in the matrix passed to the shader
* I also notice that InstancingPipelineStage has a `u_instance_nodeTransform` matrix which includes handling the axis correction. I wonder if this matrix isn't quite correct with the other matrix changes

**Comment by ptrgags** [comment]
Interesting, if I set `u_instance_nodeTransform()` to return `Matrix4.IDENTITY` things look correct.

![image](https://user-images.githubusercontent.com/8422414/163266797-15955fbb-4441-45b1-9761-512cf3539065.png)

**Comment by ptrgags** [comment]
Not quite... it doesn't seem to make a difference for the [cubes example](http://localhost:8080/Apps/Sandcastle/index.html#c=7Vp7c9s2Ev8qqG6mkS4yJfmR5iQ7d7ajTjzT1G6sJNOJMhmIhCU0JMEDQNlqxt/9Fi8SoCRbbvrneSYxCSz2+cPuAnSvh06TBGEUp7QoaD5HRYpz0oUR/YDmhGVE8hWSDIkFu0VyQRAnBSeC5BJLynLEbtToNO/1qtV5gmKWS85SvSDD85zKMiGW1jJPqJA4jwm6pXJhCFkpSDTNpzksFxItKbklHJ2gnNyicyJomUUf9Fh72or1+znIwTQnfNrqom/THCGa37AzdjdENzgVpKuGBElJrJS9yBMaY8l4PXvfGTlxIiag1okVG+nXUa2NctLl7A/gJIDo07R1dvFWSZ22rhjNJTpPWZmYgYvcmGZf37KEpNPW55FvmB4ERlrphMzK+RkrQb98/oGlZUbEOMezlCS+ISSZk2u5SoGompW8tJN3OCtSMlkVRAx9bfVsXHIOMRvXRAHNp/5n5QxtbkokkpjPifwd9OtH/ZEZ02Eb55JKSrQLPtsJ41+SXCkCO+YgpceE5gsIudaUFgC3C5KbmKOE3VZ+Vs9vAENpM/TXMSckvy5wTMZLsMUStZV5fsyiGOdLLKa5Cq3HLRJEXuRFKU81GNo3Za4fUDtjS5IBx46JhtGjoPFXkhj/gCKGtRqsyKOCCao4KEGAvBukdUFO4YTcADSTts+pg3788VGiiCa70kXalx1FarVHYTxA9Y1LRhtoowxLwilWuLRiz1nKePTxzcVkHKmNepoWC9wGUBx1NnJgpQR4Er1sIxe3SrtT1CE9xxnh+NzkDRUtohGuA6bQpneBXnwPQO1uA4VCdvTL+OfJl9eXH3/tOOC9AyWxcKmHOdyVhUNdWfx9mKt4bUecjZWCTCO+gTs7m2P6hDgNvjNMDShBhjJ6ukjo/PrUWKqcNdotiu+vqhi+LxIwuxlCtRldENXz3xdGj9vOqWP3gNpkR1KJVZqtcgpUDi6vbGKJVmivniJ5Uk/YALlE/fzE8tpxi7y9fH89/vL28sPY+LeyCIjBy1pZ4/Cf7UzbZBqjPyey5DlaAzQy4Ymq4n7iNLT62oV1ClI1574qOzSF1kKOPH1ShpOJGW6XPHUpOigvYbDP/blzBUCjv68gVMhP5hVtXdp2BCEJhAeecH6gsmAX6f/2BlG/063pYdC9uOHP9req4R9pIhfDug2I1gs7+jcCnmio+Ws/mTgh56NGoxIVnGYAjSUREU4Sq7uvt/518Nr58ptTEJw6VP9V6oe+HTbeKzKzp7X+47sC0pHCKE5NR2KI7k1dChWPdLNzDe1k2PCgE7Oo9soDXdHIA6HjC8BNVlecZVRY+RF0lRuybr39Zpb5dbEgXIPV8gonRuEqjhNaKtCFVJEZt9Y6UyBAfzKWTZgHJyuluxFgb8AM5W0q48U7nM8J4OwIINaP9rtO9D/RIQCugpgnsm5C1M8PludbLDm9O4zIf0soox5BHRXOmIwkx7m4YTzr+iQNJhevx79OLia/1yS1JrWDEYKUPYGuPjxcICqgRQeg4jRdIddAAd6x1GcAq84zgZRCqFIoCvieFgWsxjkCqGsGUAozrZ46qsB+gPKo2TWEAwjUqIsbEibuZoEnwsS5En5uGJ40PQF5baJoUn0UeqpbNyeVjufW0XaNYAGbc1wsaOzVb280uoGdUPENdQvtekhgiPDvk7pxa0XxozosCJ0vpEsP5me7XpEl39ts8TqlLy/IdFGmspCJ9XrslaHbgv9YuTCCN0b6vt7KoC9qq6pI1TFsBL+OmxqmJJ/LxQg9f06DrWdPMLZpaywC1Lbpupvr492qri3EHvd0Tfnm2+i27hBtDGiAdM16iIL1cOhVFUMAC6gxmzy23w7pUZ399iEjPjQZznUatK57Hj7ePDdWWkMCbdN0huOvUHegBsrVms6P9VNrduiDzsMG2O7dO/yvzWmTNhkYkN97b/d+GUHhaT8qSrFoewgJAGv9H1Tjkd8BQCWOMZQzrxQTzhlv1GOWkihlcztXcXANYtAS6g5BNYTdbY3I/ztFu6/tRg0TtlFMZ7HXZA4HBNcV7A32D6L+T4eHLwb/soocQrNx1D/4qf/CDhz0rdomSC5N674lyJSLSLJ3MAxpsj04OALTR/4FC0CiumGqmisIw9rgomgc6IImCVa0rfSu4drVbHxhjNPqyrLScOLKgogWDYa/lSpJ5HVmd260LgCNmg4gO+TOHE7GfrddZ9EGf0/fof9ip3Vp8jJqyWnYxIsYpyDpZTWQQdeVldkVvSPpNf0T5gZ9h5gndP12U4ZAswZDlVUXTVUNMQ6xNH+xmu1eyZ5cxbb6flPBerxY6U3RNXvD3+F/rdo8sdI8qco0Kow/ua2y7FxVXEXxqskuleTe5njo7a+YuvRXpqjrEUHnuUE7Kjhb0gQS3myFziCkKVmh65WQJBPuAmhGs/fcuxW7YPk7IljJY6JT3alQFzlJ++XRi8P64r9Q9/f6+n6nxYMXh/uDejV1l/16sTJm2urBAUX0rvVd+2sscS84ffeq7wP102W9xXuuU/5DsHzaGtW3W+AFo+G0FUU+ez0lrJRTyu3TF3iM5ulMM1HO9S9TjK+q27WJ2rzm243GkjkoUd3ZCb171YDaUEYRp5VkDGCp0nPC4lLfU8G2HKf6yupsBf6atizNtKWkWe9+zVn8FWBlska7qnCbSLA67p1ZXWrSrhNujGisUpFQqlzOBOFLVSr9ldPW+hcR0E8vEuVMxJzOiNevwEb8gNOSVImJayfWKFcHb0eETk5OGl9XvFZnWxj0tkEQR/Iws4HPzGcV4PgpHPe3cfSx3dU5oW789Fa1rYWCRkVb3VDhGVsCjqCdw7TqLB24w8OVl+ceP2Bt7rEGR7q/OnoZveiio370cv8ouCHxnBHYajpJt7kqSq/APRFYD1xbPYSwZQCvDRfJ1nMdL1aPXqkhzfX7bVpvO3c3xXZHrpt1Svl9a7WLGgXeX1Q9jzwzKpl2OxqZzbLPibpDP4U20YR328WpoascrWk3fvVEax9I/XtZ/yOJrmqtbutYgPfIKxe4/9CsYFyqlq0NqRxqGMgBJPdmJbRQMoqFqHfaP1yO9foR1QnMuYr2EPH5DLcP97vI/QPw++f7Qt2S5fMhOizuvOEZ4wnhe+bcHE7er4mm6uuHr8ASehAKTeYeTqFED6G/TJKUrEvdk6wYov1AspuaMSlZFs6ui9a9OQmsv2G53LvVtyjq/iFNmsuPe76/jxO6RDQ52fBXA4A4LATM3JSp7ounrVfHPaBfW6pyBSh9CYaneKXIFoNXv5jBKIqOe/C6eWVV/qrwH5uPQgg6NbyniixQsUKa9tL/kN81e2WINlUrEGf41HxNmCRMK2MXJP46Y3dgpeairNStXysQrMnUnxI8kLisHqa3HKJnWs4zzyKVfOp71aVevLNW+ovBFqXWM8+juhg6vRIJs9ShwoTHvP0P). Sounds like this will require some more digging to better understand the matrices in the instancing code.

**Comment by lilleyse** [comment]
These are the expected orders of transformations

```
i3dm: computed tile transform * RTC center * instance transform * model matrix * y-up-to-z-up * glTF node hierarchy * vertex
gltf: computed tile transform * model matrix * y-up-to-z-up * glTF node hierarchy * instance transform * vertex
```

_(Computed tile transform includes the tileset's model matrix and the tile transforms)_

**Comment by ptrgags** [comment]
I'm starting to understand this in bits and pieces.

I've been taking a closer look at the above equations and trying to translate them to the current code's variables. Let me try to organize my thoughts so far:

```
Tile = "computed tile transform" = tile.computedTransform
Rtc = "RTC Center" = components.transform (poorly named! this is only ever used for RTC)
Instance = "instance transform" = TRS from instancing parameters = getInstancingTransform() in shader stage
Model = "model matrix" = sceneGraph.modelMatrix
Zup = "y-up-to-z-up" = applied via ModelExperimentalUtility.correctModelMatrix()
Node = "gltfNode hierarchy" = runtimeNode.transformToRoot * runtimeNode.transform
```

Let me re-write the desired transforms a little bit:

```
let Local = Model * Zup * Node // local transform for this node

i3dmModel = Tile * Rtc * Instance * Local
gltfModel = Tile * Rtc=Identity * Local * Instance
```

Introducing `Identity` to take the place of the Rtc transform, then it's more obvious that the only difference is where to apply the `Instance` transform.

That said, there's some gotchas here:

* in the `glTF` case, `Tile * Rtc * Local` can be used directly as `drawCommand.modelMatrix` which is used in `czm_modelView` However, in the i3dm case, you have to keep `Local` separate since `Instance` comes from an attribute and must be handled in the shader. This is why the old code had a legacy instancing stage.
* I'm noticing that for 3D Tiles we pass `Tile` to `model.modelMatrix`, which means `Tile = Model`. It might be necessary to make more of a distinction in the code.

Some other potential problems in the current code:
* I think due to the confusing name of `components.transform`, I thought this was applied like `Model * components.transform`, but really it should go on the _left_. 
* `runtimeNode.transform`'s meaning changed recently, so now `u_instance_nodeTransform = runtimeNode.transform * Zup` is only using a single node's matrix, not the whole chain to the root node.  Plus it's applying `Zup` incorrectly according to the previous comment.

I have to think a bit about the cleanest way to fix these problems.

**Comment by ptrgags** [comment]
Hm, looking at the old code for 3D Tiles 1.0 formats, it was a bit different:

* for b3dm, the content passes in `Model = Tile * Rtc`. 
* for i3dm, `ModelInstanceCollection.modelMatrix = Tile` and then for a specific instance, `Model = Rtc * Instance`. So I think the equations become:

```
let Components = components.transform
let Model = Tile * Components
let Local = Zup * Node // local transform for this node

i3dmModel = Model * Instance * Local
gltfModel = Model * Local * Instance
```

Furthermore, I found at least one case where `components.transform` is used for more than the RTC transform (see `PntsLoader.js`) so I'll start with just documenting the property better.

**Comment by ptrgags** [comment]
Update: I tried an experiment:

```
uniformMap.u_instance_nodeTransform = function () {
  return Matrix4.multiply(
    renderResources.runtimeNode.transformToRoot, 
    renderResources.runtimeNode.axisCorrectedTransform, 
    new Matrix4());
};
```

and that seems to fix things. What was happening is the glTF root node had a z-up-to-y-up transform that was getting ignored, so the axis correction was not being canceled out properly.

This still doesn't address the `tileset.modelMatrix` problem with the cubes example. That's probably something else... I'm surprised, since that should be folded into the computed tile transform.

**Comment by sanjeetsuhag** [comment]
Regarding the `tileset.modelMatrix` issue, my understanding of the non-I3DM path is that when we change the model matrix of the model (by multiplying the `tileset/tile.modelMatrix`, the change gets applied to the model matrix that is attached to the `DrawCommand`. That is then set to the `czm_model`/`czm_modelView` in `UniformState`  and accessed in the shader. Since the legacy instancing path uses, `u_instance_modifiedModelView` which is based on `sceneGraph.components.transform` - if that remains unchanged, then any change to the model matrix will not have an effect. So, perhaps the thing to try would be to make sure the world space transformation of the model is being propagated to `u_instance_modifiedModelView`.
