### ISSUE TITLE
When selecting 'Show tile coordinates' imagery provider crashes

### ISSUE THREAD

**Issue by MuhammedKalkan** [CesiumGS/cesium#10265]
Happens to be on the  sandcastle 1.92

```
An error occurred while rendering.  Rendering has stopped.
TypeError: imagePromise.then is not a function
TypeError: imagePromise.then is not a function
    at doRequest (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:298518:10)
    at ImageryLayer._requestImagery (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:298526:5)
    at Imagery.processStateMachine (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:297392:25)
    at TileImagery.processStateMachine (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:297468:20)
    at GlobeSurfaceTile.processImagery (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:296642:47)
    at Function.GlobeSurfaceTile.processStateMachine (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:296575:46)
    at GlobeSurfaceTileProvider.loadTile (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:301855:22)
    at processSinglePriorityLoadQueue (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:306894:20)
    at processTileLoadQueue (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:306853:22)
    at QuadtreePrimitive.endFrame (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:305966:5)
```

**Comment by ggetz** [comment]
Hi @MuhammedKalkan. Is this one of the default Sandcastle examples, or your own? Can you provide a link or code sample to reproduce?

**Comment by MuhammedKalkan** [comment]
Hey Gabby,

Default samples behave the same way. Just add inspector mixin and try to show tile coordinates. Here is a link for you

[Here is a link](https://sandcastle.cesium.com/#c=zRrLcts48lewPlFjGeJTJG1Pam3HedTEk1SsSmorzgEiIQkViNASoGRlyrf9s/2xbRIkRUqULc8mNeODRAL97kZ3o+VIJFKhlUh5PKJpSliCfkVXVLJsjqOUEkU/N/aMP+4ShFL674xK9Rk20xsiv50ilWa039j6RFNF738X6ZxwWW8/9M7ukrskKlguGV3RFJgldFUx/FSsGXdHUfF+JRIFTGl6d9RHBWelxfiQiiWLaXraEnzDYTBAkirE2XSmWDJFShQi3CWaKZYRTSiecjGmmCZkzOm7CvTXArJBJVsgwoFvQhRb0koCtChFkJU+lHO2kILFlXBt1a6r7VFbBaNlk3Q00/buJvLpY7W/TaWwTpbyU3R3NFNqcToYrFYrvExP1IwWRsKRmA8a7wPFOJUWNrE58J0BmDgnAS6PmcqpVNEQE0VQJDJwqFyjTyN089///FZAt9xJ0ug1k91iX8De29sR8IuvOV2CIUWyV4H8G5VaSFCDVhhOjIHJlMlCE/04SCHYBpKmSwYhMyhMU7NwXg5KLvD0dk6m9BYAi2hqRsotRBhakSWtVIkyqcT8Dc1DYk4Wn1msZqCQY5/tgdAPj4J0G+aqDbRtk9wUf2h7rHIhTjtF62uIWbF42i1bCRMRzsckggM7yZIotxEy7vto3UdgM8p7FTeA1GmhVL2L7VkbdFbZoJP/FvA4m0xqW7zigijHvgDd14bm+EtJTvtIY05EigwOp3q9BkTzLP8+L+Hyl+PjhvgN8Pt7DQ7f51qh/HkLuhIsA1jjHh3n0ANUSnOCrF4PXm+ImuGFWBl2Za+zXQrLnMIaKIB4QKE0y6MkdolorE+EZxTIuaZpgkmMAllCEg70wrIHHyb2gBl8dlNiSUxzA4A0v5TuzJVrCa698aUA/QqwDe4NuIfq8WHDJ4X0mCYlgRL2oYg1ANIC3ZIkjohUnGISxyMhIADTG5pkRXR/0Ti1J6BoFMlHn4+t8wBW1OuoOOeo3C4zV/4HKkO6iFQzvlt+LvP/VhkBnZt15GwH/pB6URqn37TC/6kZLCcCUTBupOQPUXN/Ye/9JBVWA1TZ6idr0DrOj/YhdUj3/j6uBjsV/dRfYKSuPm7HQE9qu6/B+SEK7TRXz/DCozX2h0i3p9YfLuPevu6HiLfbVR4uWdm6/QSp2g3jHom+Fp93RyV6XjfujrpLy0s6IRlXh1aYG5ElCl1DOwgn4DkKcSG+XagbVaI+J3G+IXyCXoo5fQ4/XccVSadUbXWPJO/JGUkco3mqT2w3CIe2h83AGdq2Z7l+v7XvOqETuhZ24c8xbbe16wSB7TkeDl3PtXwnCP3NbjNdarHEZCIPFWsYeD52zdC0Tcf33GGLrWvZ2LEDN3C8Yeg6XtDatUEH7Hkgkj0MLNu0nW6hymCLyJymBGtPGdp0/VLWp8BHKUkkNI9zo1QHuq6U3bv47cvr30dvR/96hr8hQNEroBcxGQl0SdY/2e++GQSWiwPPCxwIgi2v2+BQL8SuZwauF5r+lttDyzWd3O2+a4fw9YPc7ptD18bDoQmRZobu0GtL5VjDoYU9yw/B9ZYfbIvleaaHYTcMfct1HGf493N8laO+CzG/zJQCC21yVH4DKZPXLZkvOP0gJMu9LYvt2vc7WUWHwjOCwDFN34d7gBn4NnjTCapz7Q0dN4TjZTkWHHsvqDxgh35geTa2g2F+tCyrsK3W8hluBuouDn042MHQD7yhXZI/8UMHO64V+mFgBpbvWhVfNwxxCHIGQ9MfQgDYG74H+/FPe/ChZXZZ+KQsb7dZFFEpjW5/tTxS9yObZqvuf/Dn17eBW97GBoPLNYp1aepXnV8sqITOHgw8lllK0ZRCTVDpWiOM6QyuYlXUYHRLlR5izZhEE06mSPelElaIwg1rNHvXmC7UbAShdDEFKlJthnv1fKvGo4kCHanEMpMLmsQQhImSRsvSNUxK52JJLzg3qhtnfdVm+qbN4KLdbUPMaTLNL+DHx6xOdtqiixImF7AT9wv7Wt9wt2WC8r/pbBOIidOaHta3WazEK3ZPY8Pq1QmmAjnduBMCKlVimpLFjEUjUQe7UcFusMeM87EgaXzaanfgwsEiwt+nbMqAcjW4ay3jy/ej0fubRqaTsAdCm7iZ/lg+ssrrCMaD4lkOJiRinKk1nrJJo5g81E+cjClvSaSL0QHmyB2ZFHXLMhcKzUUi5IJEzWYFoZlI2fd8LLut4ZutDXwFZ+76YwN1AQz5++IMn3ZmFNsw++jEclsigZWvBBdpzah4w5fvLq5+a8CJTHGW0ENA5UysLkn0bZpCCxjv3HnG9VZJrClqvmKYOOyj5off68T/AGEJB3efsm4fOb0dF5ZXrofuoyezOW2cznYy09e91ymLjRQ6C5JMOc1bzlv2nbay1xRAqqmma521N+phZmuH6rr0joAoWUw3aa8YSinxkcSglDRsH4d5B+n3OpBFMn0cOxjiMG9YvRZ2uwB9rFQr688O8RO0o32/DVop8TRkTfT4YKIdkNt1tTvBgZpfvp61Emo16YSEunFNnj3XdfbczDnLMWcJq2e0AHq/M9Xle/zAabpo9G4Ur0CvfnOBktZCMSPdBFM+5Kw2e1sTX94dODssJRzkWYtnItLWyrpi+mYzWt3HtVFUts5gleON2hj9WsYNlT1VbJHJ2aYiVHPP+tiWU9G9bd9D11x0CvGiu0dDt5PXRZHfHp49OaUqoDZXimhGo280rmPgkClXiXP26Bx3n7wT0SkqLJeM4udI2EA7VLDi+t+STHuguuvXEzei0Lt8BI/CUuCOi9gT57WRcU1sml4VCx9SMWeS5glb8CWtI7wMwFbXaTw1K2nEfthv1vUuoeqToB96WM1oYnS1uZWs3fOMh/JSozF3rjUHG/1GgP1eUkXyH/+2XbDf7myCjH+U1oLuGSp7bHRbB5Ml0Cbjoi3qNXLdCpposcLQV6WqYeNKpVKEXL5aPKa7cpktFpB0YCFPrmBApK/qNN759Te3yHbq0ce/mRWeG0d/LpCaqjwnqP7SQKpanHsF947q3qYX9cvbBK4kkRLpDbtngHTUPzqXas3pi0rCf7J57q78x2MDOmVFgRFYUw7GGWQLhaONiOeDJup5zJaIxb92/LsBijiREnYmGedFCT96cT4A+B1ULkje5L0HpXk+4HlxPrNevNOLGOPzAbx2Yyp9agCl0qSx15x3tvCbUK2Jw16oLcu3pWk8/w8)
