### ISSUE TITLE
report errors

### ISSUE THREAD

**Issue by hehexxxgo** [CesiumGS/cesium#10266]
![2022-04-03_22-27-58](https://user-images.githubusercontent.com/94695071/161432865-e48e389b-98f9-43b4-9856-0f5c4bee13b7.png)
There was no problem before. Suddenly, an error was reported

**Comment by aneekbasu** [comment]
What version of `cesium` are you running? In the new [1.92 release](https://github.com/CesiumGS/cesium/releases/tag/1.92) we have have removed `when.js` and moved to native promises, that is why `otherwise` is not being recognized. Please follow the upgrade guide to upgrade your code base.

**Comment by ehermellin** [comment]
Hi, 
I face an issue too when updating to 1.92. 
I have followed the [guide provided by the Cesium Team](https://community.cesium.com/t/cesiumjs-is-switching-from-when-js-to-native-promises-which-will-be-a-breaking-change-in-1-92/17213) but i have this issue now when i open my apps 

![Capture](https://user-images.githubusercontent.com/7964512/161484171-d4e4afcd-da5d-48ea-aada-45d690634646.PNG)

I do not understand the error, do you have an idea ?
Thanks in advance.

**Comment by ggetz** [comment]
I see @ehermellin has [started a thread on the forum](https://community.cesium.com/t/error-when-updating-to-cesiumjs-1-92/17999). I've answered there, so I'll  go ahead and close this issue.

**Comment by hehexxxgo** [comment]
I didn't update. Will I update it automatically?

**Comment by ggetz** [comment]
> I didn't update. Will Vue-cesium update it automatically?

I'm not sure since we don't support vue-cesium. It's a third-party component. It will depend on how vue-cesium handles versioning ceisum. If you're not ready to update and are using npm, I'd recommend pinning a specific version in `package.json`.
