### ISSUE TITLE
Ensure entities and CZML work with `ModelExperimental`

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10285]
While reviewing #10282, I noticed that models used in CZML and entities only use the old `Model`. (see `ModelVisualizer.js` where it calls `Model.fromGltf()`). This is fine for now, but when we replace the old `Model` with `ModelExperimental`, we need to make sure this still works. 

Some things to check for API parity:

* [the CZML Node Transforms Sandcastle](https://sandcastle.cesium.com/?src=CZML%20Model%20-%20Node%20Transformations.html&label=3D%20Tiles%20Next) should run even when using `ModelExperimental`
* Also check the [other ModelGraphics options](https://cesium.com/learn/cesiumjs/ref-doc/ModelGraphics.html?classFilter=modelgraph#.ConstructorOptions) to make sure those get propagated correctly.

**Comment by j9liu** [comment]
I went through all of the sandcastles involving these changes. They all appear to work after #10530 was merged + subsequent PRs were merged to fix the bugs. I'm closing this issue now.
