### ISSUE TITLE
getCesiumBaseUrl() detects wrong URL

### ISSUE THREAD

**Issue by ezze** [CesiumGS/cesium#1028]
I tried to integrate minified `Cesium.js` to my web site written using Yii PHP framework and faced a strange issue resulting the following errors in JavaScript console:

```
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/IAU2006_XYS/IAU2006_XYS_14.json 404 (Not Found) Cesium.js:24706
GET http://web-catalog/assets/1e5f082f/webglobe./Workers/cesiumWorkerBootstrapper.js 404 (Not Found) Cesium.js:35169
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/Textures/SkyBox/tycho2t3_80_py.jpg 404 (Not Found) Cesium.js:36976
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/Textures/SkyBox/tycho2t3_80_my.jpg 404 (Not Found) Cesium.js:36976
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/Textures/SkyBox/tycho2t3_80_mx.jpg 404 (Not Found) Cesium.js:36976
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/Textures/SkyBox/tycho2t3_80_pz.jpg 404 (Not Found) Cesium.js:36976
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/Textures/SkyBox/tycho2t3_80_mz.jpg 404 (Not Found) Cesium.js:36976
GET http://web-catalog/assets/1e5f082f/webglobe./Assets/Textures/SkyBox/tycho2t3_80_px.jpg 404 (Not Found) Cesium.js:36976
```

Yii provides an opportunity to hide application's scripts in Apache protected directories and publish them once to `assets` directory only when they are required. In production mode a single minified script `webcatalog.min.js` besides `Cesium.js` is being loaded but in debug mode I have the following `head` tag generated:

```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/acef2cce/Widgets/CesiumWidget/CesiumWidget.css" />
    ...
    <link rel="stylesheet" type="text/css" href="/css/webcatalog.css" />

    <!-- JavaScript -->
    <script type="text/javascript" src="/assets/df77ce7f/jquery.js"></script>
    ...
    <script type="text/javascript" src="/assets/1e5f082f/webglobe.abstract-globe.js"></script>
    <script type="text/javascript" src="/assets/1e5f082f/webglobe.cesium.js"></script>
    <script type="text/javascript" src="/assets/8affbe59/jquery.webglobe.js"></script>
    <script type="text/javascript" src="/assets/acef2cce/Cesium.js"></script>
</head>
```

This case leads to using `/assets/1e5f082f/webglobe.cesium.js` script implementing abstract globe class to determine Cesium base url in [getCesiumBaseUrl()](https://github.com/AnalyticalGraphicsInc/cesium/blob/b19/Source/Core/buildModuleUrl.js#L12) method of [buildModuleUrl](https://github.com/AnalyticalGraphicsInc/cesium/blob/b19/Source/Core/buildModuleUrl.js) module.

Changing `cesiumScriptRegex` from `/(.*?)Cesium\w*\.js(?:\W|$)/i` to `/(.*?)\/Cesium\w*\.js(?:\W|$)/i` solved the issue. Don't you want to make this regular expression more strict to avoid such kind of confussions?

Thanks.

**Comment by luogeng2017** [comment]
i use thy way of `npm i cesium` to build my demo.then, use `webpack` to pack my code up.
but when i debugged ,thw code ` var result = cesiumScriptRegex.exec(src);` get a `result=null`.
Have you any way likes `npm i cesium` .thanks
