### ISSUE TITLE
The polygon with holes loaded by cesium through geojson has no fill color

### ISSUE THREAD

**Issue by javcn** [CesiumGS/cesium#10297]
var geosjon = test.txt 

  viewer.dataSources.add(
    Cesium.GeoJsonDataSource.load(
      geosjon,
      {
        stroke: Cesium.Color.HOTPINK,
        fill: Cesium.Color.PINK.withAlpha(0.5),
        strokeWidth: 3,
      }
    )
  );
[test.txt](https://github.com/CesiumGS/cesium/files/8494606/test.txt)

**Comment by ggetz** [comment]
Hi @javcn, I think the issue you are seeing is the same as https://github.com/CesiumGS/cesium/issues/4871. I'm going to close this issue to keep the discussion in one place. Thanks!
