### ISSUE TITLE
Normal mapping incorrect for `Model`

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10296]
This issue was found in #10294. The [Water Bottle sample model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WaterBottle/) looks different for `Model` and `ModelExperimental`. Notably, the `ModelExperimental` version has dark patches that may be the result of incorrect material code or normal mapping.

| Model | ModelExperimental |
| ------- | --------------------- |
| ![image](https://user-images.githubusercontent.com/8422414/163420900-3dd0285e-7aed-4d4a-a624-e97e4ba7d42b.png) | ![image](https://user-images.githubusercontent.com/8422414/163421076-fba6165d-eb51-4c0d-9c21-3bb5f87b0918.png) |

**Comment by j9liu** [comment]
When I last investigated this issue, I went through all of the sample models and posted the rendering differences in #10346. It seems like image-based lighting is the main culprit for rendering differences; with IBL turned off, the models otherwise appear identical.

**Comment by jjhembd** [comment]
This is no longer an issue after recent lighting improvements. Here is a screenshot from the [glTF PBR Extensions Sandcastle](https://sandcastle.cesium.com/?src=glTF%20PBR%20Extensions.html) in the current `main` branch:

![image](https://github.com/user-attachments/assets/4ccdaab3-1841-4ec3-940c-52a0626f1db1)

**Comment by j9liu** [comment]
That looks awesome @jjhembd ! I'm glad you were able to find a fix :smile:
