### ISSUE TITLE
Cesium.Property.getValueOrClonedDefaultis 调用不了的问题

### ISSUE THREAD

**Issue by crithes** [CesiumGS/cesium#10301]
Cesium.Property.getValueOrClonedDefaultis 在版本为1.69.0调用不了

**Comment by ggetz** [comment]
Hi @crithes, can you create a [sandcastle example](https://sandcastle.cesium.com/) which shows the problem?

**Comment by crithes** [comment]
已经解决，降级到1.68.0就行了

**Comment by ggetz** [comment]
OK. `Property.getValueOrClonedDefault` is a private function, so forward compatibility is not guaranteed.
