### ISSUE TITLE
screenSpaceCameraController.maximumZoomDistance not work,when I set enableCollisionDetection to false.

### ISSUE THREAD

**Issue by andy259** [CesiumGS/cesium#10303]
I wanted maximumZoomDistance working on any case.But when I set enableCollisionDetection to false,camera can higher than maximumZoomDistance value.  

Sandcastle example: here is the [example](https://sandcastle.cesium.com/#c=vVLBTsMwDP2VqKdOGmnLBEismxAdNyQOQxxQL17qjojUmRJ3YyD+nXQdEmJDcMIn2/F7fi+JsuRZrDVu0ImJINyIAr1uG/mw68VlpHZ1YYlBE7oyGoxL6hHSKySUChp0ID1yB4rfShIhKvSsCVhbEpefrAU4DhnQSNbONjNcOkQfn2TZhczOh2J0Ki+yocjO0jSV6aCk94NtXgUIzVegsNgt7qQ5a0yYaOBFN23zaAO19gykMLgapV0EnpLmQJUCzwYlVNW9tWYB7rplthSs3hAsDBaBS/sge4aMqtNfRkNRt7TLRTwQvcM/q8IfaIM0di2O9y5/Uxcc/be8Gozf64uGUe55a3DaP68QV7pZWceidSaWMmFsVgbC6yaLVj0jS+V9Z6sbzZOv0LzSa6GryZG/JZQB78NJ3Roz169YRtM8CfMHUGOh0rS8W6MzsO3GnrLpbd+UUuZJKI8jub/Xb8wf)  

The code is below:
``` javascript
const viewer = new Cesium.Viewer("cesiumContainer");
viewer.scene.camera.setView({
    destination : Cesium.Cartesian3.fromDegrees(-117.16, 32.71, 15000.0)
});
viewer.scene.screenSpaceCameraController.maximumZoomDistance = 300000;

Sandcastle.addToolbarButton("EnableCollisionDetection", function () {
   viewer.scene.screenSpaceCameraController.enableCollisionDetection = true;
});

Sandcastle.addToolbarButton("DisableCollisionDetection", function () {
   viewer.scene.screenSpaceCameraController.enableCollisionDetection = false;
});
```

Browser: Chrome 100.0.4896.88

Operating System: Windows 11, 22000.613

**Comment by andy259** [comment]
I don't understand why it's designed this way.

> I believe this may be by design. If you look at the source code, [we explicitly check for `enableCollisionDetection` before adjusting for the `maximumZoomDistance`](https://github.com/CesiumGS/cesium/blob/1.92/Source/Scene/ScreenSpaceCameraController.js#L558). If its true the behavior is intentional, it's not documented. So I think the right thing to do here is leave the behavior as is, but update the documentation to make it clear that `enableCollisionDetection` effects `maximumZoomDistance` and `minimumZoomDistance`

**Comment by ggetz** [comment]
`enableCollisionDetection` is working as an on/off switch for all camera limits, including minimum zoom, maximum zoom, and collision with terrain.

Could you describe your use case in more detail? There's been some interest in taking a look at the camera API in general to make it easier to use, and knowing more could help that effort.

**Comment by andy259** [comment]
Thanks @ggetz   
In my case,my scene is a small area and I have some model in the underground.    
So,I both limited user maximum zoom distance and user can go undergound the globe.

> `enableCollisionDetection` is working as an on/off switch for all camera limits, including minimum zoom, maximum zoom, and collision with terrain.
> 
> Could you describe your use case in more detail? There's been some interest in taking a look at the [camera API in general](https://github.com/CesiumGS/cesium/issues/1060) to make it easier to use, and knowing more could help that effort.
