### ISSUE TITLE
Lines in I3DM cannot be displayed properly

### ISSUE THREAD

**Issue by SunnyBily** [CesiumGS/cesium#10305]
Hello!

 I am trying to display the lines of models in cesium, so I wrote the lines to glTF and added mode=1 to the Primitive of meshes, like this:
![企业微信截图_16503398062735](https://user-images.githubusercontent.com/36740211/163915907-33c1640b-f11d-438d-8fd7-d0fe1f6ef6d0.png)

Lines in B3DM can be displayed correctly. But when written in I3DM, lines are displayed as faces instead of lines. This is the result of cesium ion:
![企业微信截图_16503358929294](https://user-images.githubusercontent.com/36740211/163916342-a01c4ca8-8593-43be-a5df-fecbd351a859.png)

This is the result of glTF viewer, with the same glTF data.
![企业微信截图_1650335960939](https://user-images.githubusercontent.com/36740211/163916492-e1ac4c36-07af-4ad8-8e9f-98dc955ff68b.png)

It seems that the data type is not recognized when parsing i3DM.

Is this a bug? Or is it not allowed to write line data in 3dTiles I3DM？

Looking forward to your reply!
Best Regards!

**Comment by j9liu** [comment]
Hi @SunnyBily, how are you loading in this model? Is it possible to provide a sandcastle that demonstrates this problem?

**Comment by lilleyse** [comment]
I wonder if this is fixed in the experimental i3dm loader. @SunnyBily could you try the `enableModelExperimental` option?

```js
const tileset = new Cesium.Cesium3DTileset({
  url: "tileset.json",
  enableModelExperimental: true
});
```

**Comment by SunnyBily** [comment]
Thank you @lilleyse and @j9liu , but the lines in i3dm are still not being loaded correctly by experimental option. Here is a sandcastle that I mentioned in the problem description.
[I3DMLines.zip](https://github.com/CesiumGS/cesium/files/8517515/I3DMLines.zip)

**Comment by lilleyse** [comment]
@SunnyBily it's possible you're using an older version of CesiumJS that doesn't support the option. It seems to be working for me on `main`.

![image](https://user-images.githubusercontent.com/915398/164221441-dfd62728-07bc-4345-8364-1219f03917f8.png)

**Comment by lilleyse** [comment]
One other thing to note is that the experimental option isn't available in ion, but once the experimental loader is ready you'll see the i3dm loaded correctly in ion. This will happen around July. See https://github.com/CesiumGS/cesium/issues/9520 for the roadmap issue.

**Comment by SunnyBily** [comment]
@lilleyse  Hi, I updated the latest version of CesiumJS, but I still can't get the expected result.
I notice that you used tileSet0, but the root tileSet of the sample model is manifest.json. When I use manifest.json as the root tileSet with experimental option, nothing is displayed.
![企业微信截图_16505030154602](https://user-images.githubusercontent.com/36740211/164362351-c08f5714-bb2d-4fbf-824a-e311cd5bdfa7.png)

But when I use tileSet0 as root tileSet, as you do, I finally get what I expect.
![企业微信截图_1650502875755](https://user-images.githubusercontent.com/36740211/164362374-80c45bea-9b08-4c3f-8a7f-d012c1435e24.png)

Then I tried another model, an i3dm with both meshes and lines. The glTF of this model looks like:
![image](https://user-images.githubusercontent.com/36740211/164362969-322f8100-ec3c-43d5-b2f9-502c3540b4b1.png)
![image](https://user-images.githubusercontent.com/36740211/164363040-5dc068f3-c183-4858-80df-796e2bbc7b9b.png)

This time I just used one tileSet to organize tile. But it still shows nothing. 
![image](https://user-images.githubusercontent.com/36740211/164363318-5d225d07-48fb-4da5-9026-dcf08a5fac6a.png)

After I removed the lines in i3dm, everything was fine again.
![企业微信截图_16505130378098](https://user-images.githubusercontent.com/36740211/164369536-36a99bd0-e274-48ca-9def-25d669acffbb.png)

All of the above results were rendered with the experimental option.

Here are the files I just mentioned.
[TreeWithLines.zip](https://github.com/CesiumGS/cesium/files/8527082/TreeWithLines.zip)
[TreeWithoutLines.zip](https://github.com/CesiumGS/cesium/files/8527079/TreeWithoutLines.zip)

I wonder why I can't use the actual root tileset, manifest.json, for the first file. And, why does the problem still appear for later model even though I only use a tileset file?

**Comment by SunnyBily** [comment]
May I ask is there any new progress on this issue? @lilleyse

**Comment by lilleyse** [comment]
@SunnyBily It looks like the batch table is invalid. I see the property `edgeLineIndex` but it's neither a valid batch table JSON property or batch table binary property. See [BatchTable](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/BatchTable#json-header) for details on the batch table format.

<img width="688" alt="Screen Shot 2022-05-09 at 3 59 07 PM" src="https://user-images.githubusercontent.com/915398/167487937-d819ee1c-b267-4328-8417-192645a80c00.png">

The error in the console is:

```
A 3D tile failed to load: http://localhost:8002/static/Downloads/TreeWithLines/3dTiles/6.i3dm.gz?v=1.1
Error: Failed to load model: http://localhost:8002/static/Downloads/TreeWithLines/3dTiles/6.i3dm.gz?v=1.1
Failed to load I3DM
Property edgeLineIndex requires a batch table binary.
```
