### ISSUE TITLE
support both 2d and 3d scene

### ISSUE THREAD

**Issue by abigstupidbear** [CesiumGS/cesium#10315]
can  cesium support two scenes in two divs？
I want the two views ,one is 2d ,the other one is 3d. and the entities are drawn same.just one is other's mirror.
thanks for your reply. 
like this ![image](https://user-images.githubusercontent.com/29300501/164714677-68457d7d-47ec-417c-99b4-e08770ddff53.jpeg)

**Comment by abigstupidbear** [comment]
> can  cesium support two scenes in two divs？
> I want the two views ,one is 2d ,the other one is 3d. and the entities are drawn same.just one is other's mirror.
> thanks for your reply. 
> 

![image](https://user-images.githubusercontent.com/29300501/164714593-f1bacc21-8aa4-46ee-a345-ed82f29b9525.jpeg)

**Comment by j9liu** [comment]
Hello,

Yes, you can support the scene in two different viewers. We have a [Sandcastle](https://sandcastle.cesium.com/?src=Multiple%20Synced%20Views.html) that demonstrates this functionality.

For future reference, this kind of question is better suited for [Cesium Forum](https://community.cesium.com/), where both members of the community and team developers can help. We use GitHub for bug-tracking exclusively. Thanks!
