### ISSUE TITLE
EllipsoidGeodesic ignores height [Math]

### ISSUE THREAD

**Issue by mwaddell** [CesiumGS/cesium#10312]
The EllipsoidGeodesic's interpolateUsingFraction and interpolateUsingSurfaceDistance methods ignore the heights of the starting and ending cartesian.

If I calculate a point 30% of the way from (-80,-30,1000) to (-20,-10,2000), I would expect to get something near (-47,-33, 1300) but instead the height is always zero.

Sandcastle example:
 https://sandcastle.cesium.com/#c=lZDfS8MwEID/ldCnKl3abS+C3XBsdQj+YsMnKyNNb20wTUqSVuZf72WjMNQHzcOFXL7v7pKeGcLIjCzBiq6hS2acrgxra8Hp3uhmBZUBsOHoKonIaIphnCTJxXWuejSLP5gTL44xTM5EQFHBxyBnUorWalGuQZeY4iGLSDHADcJAhXJgWi2ZgxcrVHVrGHdCqzCh04HES2QbirtwXQnkcujwwFxNV9l6k2Xb3XO22W0Wq7vF4+BpdfK0qv4lMnlqWIOoaodJrpXVErBSFb5iucjPFHnuzQ8ZREFq3UHCPFfkuG5E02rjSGdkSGnsoGn9E21cdPwdHOXWetGjaXyupqXoiShnecCPky61ckwoMHlAuGTW4s2+k3IrPiEP5mmM/A9ValbiXz71YCQ7eKwez+9PSUppGuPxd9NpLQtmvlX+Ag

Browser:
n/a

Operating System:
n/a

**Comment by mwaddell** [comment]
Our use case is that we are drawing polylines and we want a way to position a billboardgraphic at the midpoint of each line segment to visually label each line with a unique icon.  Some of these lines are between two points on the ground (so using the geodesic's interpolate fraction works just fine) but others are between different elevations, so the icon is in the wrong place.

**Comment by ggetz** [comment]
OK, and those heights are relative to the ellipsoid surface, right? I think in that case, you can [linearly interpolate](https://cesium.com/learn/cesiumjs/ref-doc/Math.html?classFilter=math#.lerp) between the two heights, or take the average since you're looking for the midpoint specifically.

**Comment by mwaddell** [comment]
Ok, thank you.
