### ISSUE TITLE
Add support for MAXAR_content_geojson 3D Tiles extension

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#10320]
The [MAXAR_content_geojson](https://github.com/erikdahlstrom/3d-tiles/tree/MAXAR_content_geojson/extensions/MAXAR_content_geojson) extension allows a tileset to use [GeoJSON](https://tools.ietf.org/html/rfc7946) directly as tile content. This initial implementation should be marked as `@experimental` with certain constraints specific to the OWT WFF use case:

* CRS is always assumed to be EPSG:4979
* Arc type should be geodesic rather than rhumb line
* Only polygons and polylines are supported. Polygons should be treated as polylines and should not be triangulated.
* Material or color information should be ignored

Updates to the loading code

* Update `preprocess3DTileContent` so that it recognizes when JSON content is GeoJSON
* Update `Cesium3DTileContentFactory` with new GeoJSON content type
* Add `ModelExperimental.fromGeoJson`
* Add `GeoJsonLoader` - this will parse the GeoJSON and convert it to `ModelComponents`
  * Is it possible to share any parsing code with GeoJsonDataSource?
  * Feature properties in the GeoJSON should be preserved. Generate feature IDs and property tables.

**Comment by ptrgags** [comment]
For existing examples of transcoding other formats to `ModelComponents`, see some of these classes:

* `B3dmLoader` and `B3dmParser` -- this one is simpler since it can use `GltfLoader` so it focuses more on adding the metadata
* `PntsLoader` and `PntsParser` -- this one produces a `ModelComponents` from scratch.
