### ISSUE TITLE
iOS 15.4.1 Bug

### ISSUE THREAD

**Issue by TJKoury** [CesiumGS/cesium#10323]
Sandcastle example: https://sandcastle.cesium.com/index.html?src=Partial%20Ellipsoids.html&label=Geometries

Browser: All (Safari)

Operating System: iOS 15.4.1

Materials with alpha channel appear transparent, looks like a problem with alpha blending.

I filed a bug report with Apple already, probably a good idea to follow up on your end.

**Comment by ggetz** [comment]
Hi @TJKoury, I think this is a duplicate with https://github.com/CesiumGS/cesium/issues/9827.

Basically, it appears to be [a WebGL regression](https://bugs.webkit.org/show_bug.cgi?id=237906) that is affecting other 3D engines as well. In this case, there's nothing we can do on our side until Apple addresses the issue. 

I'll close this to keep the reports in one place, but feel free to re-open if you believe this is a different issue.

**Comment by brentfulgham** [comment]
Just to close the loop, we believe the underlying issue is fixed in Safari 15.5.
