### ISSUE TITLE
requestWebgl2 Bug Cesium 1.92

### ISSUE THREAD

**Issue by Lemonjay** [CesiumGS/cesium#10329]
![image](https://user-images.githubusercontent.com/9245295/165422787-864bbd69-fd94-4c34-9072-3ca7f6927485.png)

**Comment by ggetz** [comment]
Hi @Lemonjay,

I'm unable to duplicate this error. Could you please provide more information about your system? It helps if you visit https://webglreport.com/ and take a screenshot.

**Comment by Lemonjay** [comment]
This package of the Cesium 1.92 is which I build from the recent updates.  It may be a bug from Cesium recent update。

**Comment by ggetz** [comment]
Ah I see. Thanks @Lemonjay. I can reproduce this in `main`.

@lilleyse Could this be due to https://github.com/CesiumGS/cesium/pull/10063?

**Comment by lilleyse** [comment]
It's possible... what shader is the error coming from?

**Comment by ggetz** [comment]
`GlobeFS.glsl`

**Comment by ebogo1** [comment]
Ah, I noticed this in the atmosphere PR and mentioned it offline but I didn't realize at the time that the new shaders would be on by default. I can reproduce this on `main` but not on the live sandcastle.com site.

**Comment by lilleyse** [comment]
Pushed a fix here: https://github.com/CesiumGS/cesium/pull/10333
