### ISSUE TITLE
Rendering issues when rendering OSM buildings with ModelExperimental

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10338]
In [This forum thread](https://community.cesium.com/t/modelexperimental-rendering-buildings/18347/4?u=ptrgags), a [Sandcastle](https://sandcastle.cesium.com/#c=xVj/b9s2Fv9XHnzDLAOuFMfpevWc4JovW4ull2IOth/q4EZLtE2EJj2Scurr/L/fIynKUqw43trhigKRKL7P+/B9p5ME3soHMBJyTcHMKfQv4ZZxqmFk1pyJGXAiZjmZUbtJ4xoFJjK2YllOOEwpMbmiuguc3VOY5IxnKKTjsUiSXQi9pCmbspQYJsUA5sYs9SBJZszM80mcykVyQTXLFz+Okn72wlgeiVGUJgvCRFKTTgrwsRgLLxRffVpSxRZUGMJ/KIjFVJAJp+9lRnn1O5yCUTn9fixSKbSBFaMPVOGqoA9Q4P3i1qJxK3XvFxIFmaBq3OrC57EAMFQpXPmgJJqDqkEQTBVqp79KxbNbvyXqdMdi0ynVzYnI+GN9I5SjYrQkKb1aIcu3flPkucU6pYLGKREroi2SM/GbLCvE4Wb0fusA6y3rTicERIPMFdBPZLHkWx9TEwdCUi/Og2zxDcnVznNT2RJZAjVeS7QsM2yFJidZFjXglZxHiG25MYEC6IqULKgiljGX8h6IwR3EGE4fqfD7YoSynomcCzKqDRNFPBV0L4gy+EREP54qubikM7Srjl70jo/j/smr4y6cvIpfvv5nF/qvjqxjAKRiNiw8jAMGmFNi6Zew74mZx0b+jKtE6KhXiAIsmUnnT217EfZtQgTUUmOai9Rq1cX6heRSwWQNC7S4ctaZ0/RewxSXRc45rAjPMT01EykFIQ0Qzp3o1vdzsvLJXIIslcTYN2v0d9AIqVV1vn5f7Ik6/uANnot93teC1f/pX9ot9jA0KsyW0SkmiS7NCCWLAYxb33wuSsbHduA7CN/bdxtMLS+1Kf46khUsjNaMOYMN4GNYBHxE5ICzgdPTU2csm6mYvhYjaj/MmaHtzrh1190r2J5xonW7Jqvv1xM0e7sLR/HLAyCQJiYNqquhYByuDyEwUSy9r4vamkuEotkh8tpI8Ug1Z7O50Rz3HUpiQbFMNoAcKq8NpU3ybt0ZcxfEluSnfAYY4rdzpgH/29imHDtWSjQNCHe10HGptrFZVQb8HNU7Cm84/xnDN8OUR76VovZ1MuDgmC0foTkzMCG8LckSS5ptXLoNf/wB+7aq7cHaZTYFHYVV0zURLpRfd2pbat6wvtifPc8aXM/lw/k62PJ2vaTRpPJSmFs/2PoJTZ/AORhJyCn2fQyNQdD9pT6y/yy9wTOW94qrlnTn9I8T7Iv339eIbj31fyBbCZPnCWOdJjk3g91vm8KPZTuy6bbtLhM8aQboXlxmCjKmDbG9yPZaIKApp6nBHdizjcLew6Wf2HZbz2UheisvpFSZ7eM0WmLto9k1ipg8wwgs3qWYuYW/rUuFcwzgt/AYrWh6HI3HFZv7UfAfPNBB22OSNO0oDoAbOl1wQN98fnSWTbdcKnZvOp3fvqADBuIbOMPsPuqd1IrpE0V3V+zocdei4hC5o+9qcmvKuXw4SPCoV5NsbnP7msNzJQlD+dc5FZDhHJTJBwFy6QIRe4kdocYtH+jnawgxCbcSx9AilK9DCNusQixFF7IYsTidGkg5ehHn2WVugNrR3Y1rPhPslEf2JYMH22bAB8RCoRtxjdAXFjk0pkymuU3v+PecqrVnJ+0FJWZiKj8QQXHi6fg8iFdMswnjzKwxJcatOcuwLYxbLsOL60fsVb+zvN84MtETVxFbk+Prqx9u/3Nx/e7ip6pd7Q3En5mj6XBOV+7yUVoaCeeFuXHI/UpH8JcWB326NcuMmitO7eP5+l2GoIEEQrrB2wrEBZePR3cx/nEMEKR0RzD2IW5xxtyZo61xdtX19qtDS176imyt5ywP/6YU3WRvbzbSdkMI9hZSvOR8d3z0steF4ubzut/zjL/ECe4Vr2Y+kAr/7ySB/a3AH5WUncMuYtzhLRSPgV+Y0cg/0NXVuMRqXg3KrbGsSyzzcj4IF8QiU69w8HFEc+ErfBbaswsYX2xD48Bt9Sus9WnQEC+ldmU2dE82hagu36kV5RI+1HKEr++38fmhuIhF29IWfl8oW8a4FT5uO3dNQegff15DkGxW8debcgGy8Rdd+BNVZDdRjr9SXj4/7jfr738l/Q3T73aQfUL3yd+puzqbPtYvUsy9GW1SOsKkxOnWYC1Qds4qy56NSOzACxSqHcK9hIx8h4n46c5J2Axy+7/9FgxSklMnXjnxqa0wgQCSDAlW21bo34QDNNXfsWh1W0NXwM5CfP+LLZZSGcgVj+I4QcilvQ/rZJJjMJs41TrE8TCpig4ztgKWnTb8EIhFj2h9aklzPmL/Rc+eDRPcvyPKpfs16WZFFSdr3BZoDee9s2v/MY7jYYKvgUQTjpGST4iqAhTWC1Q8yReT3BhrRC+27YRn27owLKYg95MSbsK576wchMoqGQw7TPz2PQC9KsDeSeoAsGMEextyGCoZXFLTB6D0EWWE2QA3LvO2snAj+PoAgJMA8Cakz3MYGD3uuNsFY3+DLh1UabJVvWYis/VZ9cI+NKr2bleyM5fn9v5Vb62h3zYPC8MEJWvYSQ0cX2vq8d1ybgjF/wE) was presented to demonstrate incorrect rendering.

I think I see 3 problems here:

1. OSM buildings use the `CESIUM_primitive_outline` glTF extension, this is not yet implemented. This was mentioned in https://github.com/CesiumGS/cesium/issues/9520
2. It seems like the lighting is using a constant normal (which could be the default normal in the model material?
![image](https://user-images.githubusercontent.com/8422414/165993747-564489d0-c6a5-48f5-9517-d304a4e64d1d.png)
3. The dropdown option "Color by Distance to Selected Location" breaks the shader. Might have to do with fetching metadata. Note that OSM buildings uses the batch table hierarchy extension, not sure if that has an impact here.
![image](https://user-images.githubusercontent.com/8422414/165993824-ad3ba1d0-d24c-4e52-a45a-17a72da8c9d6.png)

**Comment by j9liu** [comment]
Making a note: when we add support for `CESIUM_primitive_outline` can we test that if the bug in #10452 comes up?

**Comment by ptrgags** [comment]
Today I discovered that the problem isn't a constant normal (Cesium OSM buildings do have normals!) but that the material is rendering as too shiny, that's just the IBL reflecting the sky. It is more noticeable compared to the old Model, not sure why.

And I'm currently working on `CESIUM_primitive_outline` support in `ModelExperimental`. (not quite ready for a PR yet, but I can at least render outlines locally!). The lighting looks a bit off, but it's a lot better than before!
![image](https://user-images.githubusercontent.com/8422414/176286313-8931faee-70bb-4806-b566-8a55e78e7984.png).

**Comment by kring** [comment]
Yeah Cesium for Unreal renders the buildings as crazy shiny, too. I think the problem is that I chose the material parameters in Cesium OSM Buildings based on the old Model code, and that didn't fully capture the shine I was putting on it.
![image](https://user-images.githubusercontent.com/924374/176584825-9ea8b633-2105-43c6-8057-e542c46d116c.png)

**Comment by ptrgags** [comment]
Now that #10506 is merged, I'm closing this too. Here's a screenshot from the current `main`:

![image](https://user-images.githubusercontent.com/8422414/177865959-ff88db29-5ea1-4408-b320-057786bc78c2.png)
