### ISSUE TITLE
Regression introduced by switch to native promises

### ISSUE THREAD

**Issue by ephjos** [CesiumGS/cesium#10345]
As part of https://github.com/CesiumGS/cesium/pull/10149, when was removed in favor of native promises. In some places, this now introduces a race condition. One place where this is obvious is `Cesium3DTileStyle`:

https://github.com/CesiumGS/cesium/blob/d2495353101d99965e5e042aa88db2e2daf79c52/Source/Scene/Cesium3DTileStyle.js#L85-L97

In the else branch (line 90) we use `Promise.resolve` to create a fulfilled promise. when and native promises do not behave the same in this situation. `when.resolve` creates a fulfilled promise, calling then on this value will actually behave synchronously. See [the when.js source code for version 1.7.1](https://github.com/cujojs/when/blob/5eb87955402ee172f7257697585ccbb609b5d65b/when.js#L59-L102) which was the last used version. Native promises will [always run .then asynchronously](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#return_value). 

This introduces a small gap where the `then` is waiting to be run. For previous code that assumed this constructor was sync, this introduces a window where the style is defined but not ready. The sandcastle below illustrates this by forcing the style to be set right before a `scene.pick` call.

It may make sense to break out the async behavior from the constructor and move it to a `fromString` static method so that the caller can decide which path they want to take.

While this is the only example I have come across, I imagine anywhere that `when.resolve` was replaced with `Promise.resolve` is a potential candidate for this bug.

---

Sandcastle example: [Mouse over viewer and error will be logged](https://sandcastle.cesium.com/#c=fVRtb9owEP4rJz6lEjUJSUjKKFrHJq1Tt6LSvUl8McnRenVsZDu0rOp/nx2HFvqyT+C7e+557h7Hvd5UMmFgwmVdwmIDUyWXBKZoUMEJ5yi6MJG8rhaMwnfB1qg0Mxu4kAtpWKHhjC4IzAoqBBNXrsEJxz9UlErCpZJFITkDe4Sv1CCDCZMFVZwhmYtCCm1gzfDWUh2DwFuYoGZ1RX40sWDeKZrzRApDmUA173Thfi4ArDhlI1brmpWohltgodDS/JSKl5e+JDjozsXDwbu52BJaRRwLw6TYJ50qVjFjB5w8FgQO5wUSXaBAstoWaULLMnjqtctgGEeNZr+9/4k/Xvpk0MxRK/6o/VSKC9SyVgWSpZLVibZlp2UQDZJ+9DjFE2MjoKXy7LdMlPLWxT+tUZgzpo3V7Pa4ch6jquQa3Q4DPIDjsV9luxQq1lR/kLUorY0XloGKK452hL3xfRm5QrMtnVgvhXGAZlnbfncWacub5C84fKs/4bg0O7DNDuz3f2BGrpqJt7h2vqm0d9Mb+2V2/o1ooyyMLTfBPdwN4a4Lm6HleNhVWsla4w5w1zKqjP1HRT9wUI9qrp/fuu2/aXb0hs0zl/ZGg5c4Y39xCPNOal1w4VbJ/hVjxU2wp8oVtVf4mRsVKkqsEvfBeKIStWGCOtjw1VniwOtJkjDKkoQMkiRK0jhKuj7e76dhGpEkCrP8KIrCtN8mkvQoTfohibMky5Mkjl34oElK5Qx7SfoZqfNtykxxfWEvbkudWtJBFsd5mIbxUZZmLcNhSPrZYBBmURrn8VGeD9rEgPTzyGrJszQJwzBPt9TtVjrdzqjxYuzrAd6zaiWVcR9YQEjPYLXi9mXQvUVd3FjnCq396gFGvV3oqGRrYOXxK28PFJxqbTPLmnPn5LwzHvVs/Qsol83c5/ax5HTjyq6j8ZkPEkJGPXt8HWmk5AuqnnX+Bw)

Browser: Chromium 101.0.4951.54 Arch Linux

Operating System: Linux cesium 5.17.5-arch1-1 x86_64 GNU/Linux

**Comment by kring** [comment]
I ran into this exact problem when helping my old team upgrade Cesium, and implemented a fix:
https://github.com/TerriaJS/cesium/commit/1fd27c5d7c9e542abf83bf9e9fd900b9468d9b69#diff-1517c5b6881be5d0d9d1e7537153137ca8ea476adf92ec450ec165bfac53718b

I suspect a solution like this could be used more widely, and abstracted better. Checking if something is already a Promise by checking `typeof foo.then === "function"` is pretty legit too IMO.

Feel free to grab this and make it into a PR if it helps.

**Comment by kring** [comment]
Example of checking for `.then` in that same commit:
https://github.com/TerriaJS/cesium/commit/1fd27c5d7c9e542abf83bf9e9fd900b9468d9b69#diff-0f3818eddd95010bfc4edeff10249d3f9e6e11f9aae308611d198a062a8fcd89R726

**Comment by ggetz** [comment]
At least in this case,  I think we could get a lot of milage out of removing the `string` and `Resource` options from the constructor and having a `fromUrl` or similar static function which resolves the url before constructing the `Cesium3DTileStyle`. That would remove any need to have a `readyPromise` at all, let us treat a style as always synchronous, and would make a lot of our specs cleaner.
