### ISSUE TITLE
Label background is broken in 1.93 (unwanted gradient)

### ISSUE THREAD

**Issue by UniquePanda** [CesiumGS/cesium#10342]
Hi all,
We've just updated from 1.92 to 1.93 and found out that our labels (Cesium entities) now have some kind of gradient added to their background. As I wasn't able to find any related changelogs or code changes, I guess this is a bug?

You can see it in action in the attached sandcastle and in this screenshot:  
![image](https://user-images.githubusercontent.com/3686982/166413213-d8f245d0-2ffc-41a9-8d69-1d2fa39e22b1.png)

For comparison here's a screenshot of a label from our App with a previous Cesium version:  
![image](https://user-images.githubusercontent.com/3686982/166413483-3a4d39e1-d4ee-4575-8dce-f50c7e6b17f2.png)

Sandcastle example:  
https://sandcastle.cesium.com/#c=bZBRT8IwFIX/ys2eRjK7IIJhDqJME40kPmj0pS/ddoGGriVtx0TDf7fdUIzSh6b33POdm95CSWNhy7FBDROQ2ECGhtcVeW21kAZFW2dKWsYlahr0rqiksmMISsstR0NYWYafVAJslHGKksl3Usa0dS8mB2ShVXWLS41owrPLIemPLvqj0WUEgzEZD8/96UU+RLAcRQJtIIDFd5sADeZehYbbFcxYsV5qVcuSBlHnWnAhMiWUPk72FZnNb7LHg8esVHNEE7C6xkMr/5FPhbzdP7zctc69u/d+B0EUpMbuBE67AIBrXm2UtlBrERISW6w2grm/x3ldrNGSwhgPemsa/0bTkm+Bl5MT24ZCMGNcZ1EL8cw/kAbTNHb+f6hQrORy+bRFLdjO21b96bwTCSFp7MrTpFVK5Ez/Sf4C

Browser:  
Tested on Chrome 100.0.4896.127

Operating System:
Windows 10

**Comment by anne-gropler** [comment]
I confirm this happens on Firefox, too. (Windows 10)

**Comment by GatorScott** [comment]
Looks good though!

**Comment by ggetz** [comment]
Thanks for the report @UniquePanda! I can replicate the issue. This is a bug, not an intentional change
