### ISSUE TITLE
Remove Cesium3DTilesStyle ready, readyPromise, and constructor option in 1.96

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#10355]
https://github.com/CesiumGS/cesium/pull/10348 deprecated `Cesium3DTilesStyle.ready`, `Cesium3DTilesStyle.readyPromise`, and `Resource` or `string` parameters for the `Cesium3DTilesStyle` constructor.

**Comment by j9liu** [comment]
@ggetz it seems like this issue is still open even though 1.96 was released?
