### ISSUE TITLE
Are there any books on cesium？

### ISSUE THREAD

**Issue by wozaicik** [CesiumGS/cesium#10352]
Are there any books on cesium，i only find one

**Comment by katSchmid** [comment]
https://www.taylorfrancis.com/chapters/mono/10.1201/9781439865583-7/globe-rendering-patrick-cozzi-kevin-ring

**Comment by ggetz** [comment]
Hi @wozaicik, we have a list of all our [publications and presentations on our website](https://cesium.com/learn/presentations/).

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. Next time, please ask questions on the [Cesium Forum](https://community.cesium.com/), where there are members of the community and developers from the team who can help. 😃
