### ISSUE TITLE
Under different perspectives, the Feature of B3dm cannot be picked

### ISSUE THREAD

**Issue by islovingness** [CesiumGS/cesium#10367]
Hi there,

I generated B3dm and showed it in version 1.91.
I changed the color of the Feature through the following code,

`
tileset.tileLoad.addEventListener(function (tile) {
        // console.log(tile);
        var content = tile.content
        var len = content.featuresLength
        for (let i = 0; i < len; i++) {
            var feature = content.getFeature(i)
            // console.log(feature);
            var eleId = feature.getProperty("eleId")
            tempMap.set(eleId, feature)
            feature.color = new Cesium.Color(Math.random(), Math.random(), Math.random(), 1)
        }
    });
`

Does this prove that my B3dm is ok?
However, in some perspectives, I click on the same Feature but cannot pick it, as shown in the picture below:

![1](https://user-images.githubusercontent.com/17868490/167968628-d978373f-3f5d-4bea-ae11-cf51ebef567e.jpg)

![2](https://user-images.githubusercontent.com/17868490/167968639-e67368f0-eb84-405b-8f75-ca34387c3429.jpg)

Where I click is where the arrow is in the scene.
The pick code is as follows:
`
viewer.screenSpaceEventHandler.setInputAction((movement) => {
    console.log(scene.pick(movement.position));
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
`

I hope someone will respond. Thank you

**Comment by ggetz** [comment]
Hi there @islovingness. I was not able to reproduce this using our [BIM 3D Tiles example](https://sandcastle.cesium.com/?src=3D%20Tiles%20BIM.html). Would you be able to provide a sandcastle example with this 3D tileset that is causing the issue so we can take a look?

**Comment by islovingness** [comment]
@ggetz  Thank you for your reply!
I uploaded the 3DTiles using Ion,And you can see my problem using the Html below:


`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <script src="https://cesium.com/downloads/cesiumjs/releases/1.93/Build/Cesium/Cesium.js"></script>
    <link href="https://cesium.com/downloads/cesiumjs/releases/1.93/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
</head>

<body>
    <style>
        html,
        body,
        #cesiumContainer {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
    </style>
    <div id="cesiumContainer"></div>
    <script>

        Cesium.Ion.defaultAccessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1OTMxZDI5YS1jZjM2LTQyYmMtYmNjYi1hNmQ4ODdjZTI2ZGEiLCJpZCI6OTM1NzMsImlhdCI6MTY1MjQwMTY5MH0._G_KBjPnhnerY_9BlJeiwTqT71h7GiNDkzqrUlvurYw';
        const viewer = new Cesium.Viewer('cesiumContainer');
        var scene = viewer.scene;
        // Tileset Load
        var tempI = 0;
        function TilesetLoad(path, modelCenter) {
            const tileset = new Cesium.Cesium3DTileset({
                url: path,
            });
            tileset.readyPromise
                .then(function (tileset) {
                    let tempV3 = Cesium.Cartesian3.fromDegrees(
                        modelCenter[0],
                        modelCenter[1],
                        modelCenter[2]
                    );
                    tileset._root.transform = Cesium.Transforms.eastNorthUpToFixedFrame(
                        tempV3
                    );
                    viewer.scene.primitives.add(tileset);
                    if (tempI == 0) {
                        viewer.zoomTo(
                            tileset,
                            new Cesium.HeadingPitchRange(
                                0.0,
                                -0.5,
                                tileset.boundingSphere.radius * 2.0
                            )
                        );
                    }
                    tempI++
                })
            var tempMap = new Map()
            tileset.tileLoad.addEventListener(function (tile) {
                // console.log(tile);
                var content = tile.content
                var len = content.featuresLength
                for (let i = 0; i < len; i++) {
                    var feature = content.getFeature(i)
                    // console.log(feature);
                    var eleId = feature.getProperty("eleId")
                    tempMap.set(eleId, feature)
                    feature.color = new Cesium.Color(Math.random(), Math.random(), Math.random(), 1)
                }
            });
        }
        var tileConf = [
            { url: Cesium.IonResource.fromAssetId(1018366), modelCenter: [117.24, 39.080722698745542, 600] },
        ]
        for (let i = 0; i < tileConf.length; i++) {
            const element = tileConf[i];
            TilesetLoad(element.url, element.modelCenter)
        }
        // click
        viewer.screenSpaceEventHandler.setInputAction((movement) => {
            console.log(scene.pick(movement.position));
        }, Cesium.ScreenSpaceEventType.LEFT_CLICK);
    </script>
    </div>
</body>

</html>`

**Comment by ggetz** [comment]
Thanks for the example @islovingness! 

I'm still having trouble getting `pick` to return `undefined` with the latest version of Cesium (1.93).

> I want to know, whether scene.pick is closely related to tileset's boundingVolume?

The tileset's boundingVolume will effect rendering and picking, yes.

Also if you're trying to adjust the tileset's transform, I think setting [`modelMatrix`](https://cesium.com/learn/cesiumjs/ref-doc/Cesium3DTileset.html#modelMatrix) is the recommended way of doing so, rather than adjusting the `_root` directly.

**Comment by islovingness** [comment]
@ggetz  Thank you for your answer!

**Comment by javagl** [comment]
The bounding volume will affect many things - not only picking, but also clipping, loading/refinement, and visibility checks in general. It can be helpful to enable "debug" bounding volumes with 
```
  new Cesium.Cesium3DTileset({
    ....
    debugShowBoundingVolume: true,
  });
```
to see whether they are correct.
