### ISSUE TITLE
Destroying the viewer when 3D tileset is being loaded results in error

### ISSUE THREAD

**Issue by SentretC** [CesiumGS/cesium#10363]
Simply call `viewer.destroy()` soon (directly or after a short timeout) after `viewer.scene.primitives.add(Cesium.createOsmBuildings())`, and check the console.

I encountered this problem because I'm using React and it can [automatically unmount and remount every component](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state) to prepare apps for a future feature.

Not a big problem it seems, but a bug anyway.

Sandcastle example: https://sandcastle.cesium.com/#c=bY89T8QwDIb/StQplU4JzLQV4lakG0BMXXKJAYt8VLHTU0H8d5q7GxA0S+Q3z2PHNkViMSOcIIteRDiJPRCWoF7OmRwbe673KbLBCHls2rsxXgxFFiKoKWNAxhlIGefktYHNYBgOFB4KeofxjWRbVa2v85QD4pwWWVMCfsYAqbCUregH8TVGsQV+78RNvZtd0xEvHoYK1nOPYUqZRcleKqUZwuTXH5A+FvsBrCxRFSva6d9q53AW6PqNXYX1hmh9eS3eP+EnjM3Q6ZX/p/pk6pKHGbI3S8Xeb4fHS6iU6vRabpuckj+a/KfzDw

Browser: Edge 101.0.1210.39 & Firefox 100.0

Operating System: Windows 10 21H2

**Comment by lilleyse** [comment]
@SentretC I believe this is being fixed as part of https://github.com/CesiumGS/cesium/pull/10361. @ggetz can you confirm?

**Comment by ggetz** [comment]
Yes, in https://github.com/CesiumGS/cesium/pull/10361 there is no error in the console.
