### ISSUE TITLE
Failure to load geojson file on the map the second time, out of memory error occur

### ISSUE THREAD

**Issue by edeles-navagis** [CesiumGS/cesium#10369]
**Description**: 
A geojson file is loaded and is shown on the map on the first load.
It was removed a minute after and when re-loaded again, the datasource is loaded but it does not show in the map.
A out of memory error occur.
Sample layer loaded contains border countries of the world.

Sandcastle example:  [ Cannot re-load a geojson data source the second time around](https://sandcastle.cesium.com/#c=xZTfa9RAEMf/lSEvzWG7ae9BpE0PoQVBBIWKTwHZS+Zyq5udY3dyRxX/dyfZmDvvUrG+uA8J2fn1nc8MKckFhq3BHXq4BYc7uMNg2kZ96u/SIin77ztyrI1DXySzm8JZZKg06wdqfYkS2boKV2KvBmNg7flec2frXsrRLj2N/OCpMaFzGsq+QXobyN2PHsqSrkTGmnkTrrMsMHldo6qJaot6Y4IqqckYm83nZVt+RZ5fzudZSa1jbzBcLMlX6FWN9EUSR/mFiy2rvZKgdFWlJ8pmitfoUqsfO0AL+F44+L3z3nTTXZcCk2ynuBbBMaRTjxWwafAaigReQLrHARd7TjMxnTXhrJP3I2rMMvDY0BZjDdAr7p7QGNcyFi4gf5S81HK6al3Jhlw66wU+jR+OZfYVjKtjjYhHnCb4RC0HiCbzRanR93l9Sypp/RxeXsoZCchUQNeyeiCDOCQfaYzyDf8rkCP9MrARR6w8Qvnve9sjmp7O329vf55Y4f78YY+HSTxrmyVjv9Ay2qtXcbbJeZIHfrS4+FX0tWk25Blab1OleixW8oQsslFlCEMuyLPD0LwyWzDV7cSPCkqrQxDLqrX2wXzDIlnkmfifhA5Df79FL+12buurxbt4qZTKM/mcjmQiu9T+KPNP)

Browser: 
- Chrome Version 101.0.4951.64 (Official Build) (64-bit)
- FireFox 100.0

Operating System: Windows 10

Out of memory error occurred.
![image](https://user-images.githubusercontent.com/8393864/168011310-05b64111-c3e8-4f6c-a0d0-143a2aea5143.png)

**Comment by ggetz** [comment]
Thanks for the report @edeles-navagis. It looks like we're already tracking this issue in https://github.com/CesiumGS/cesium/issues/9058. I'm going to close your issue now to keep the discussion in one place. If you have any further input on this, please post it there instead.
