### ISSUE TITLE
`ModelExperimental` Sandcastle Testing

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10379]
## ModelExperimental Sandcastles

As part of https://github.com/CesiumGS/cesium/issues/10346, I did a sweep through the old 3D Tiles and Model Sandcastles to see what happens when I set `enableModelExperimental = true` or use `ModelExperimental.fromGltf` instead of `Model.fromGltf`.

EDITED: 07/08/2022

### 3D Tiles Sandcastles

Working Sandcastles:

* 3D Tiles Adjust Height
* 3D Tiles Batch Table Hierarchy
* 3D Tiles Compare
* 3D Tiles Feature Picking
* 3D Tiles Feature Styling
* 3D Tiles Formats
* 3D Tiles Inspector
* 3D Tiles Interior
* 3D Tiles Photogrammetry
* 3D Tiles Point Cloud Classification
* 3D Tiles Point Cloud Shading
* 3D Tiles Point Cloud
* 3D Tiles Terrain Classification
* Clamp to 3D Tiles
* Sample Height from 3D Tiles
* Development/3D Tiles Split

Broken Sandcastles:

* 3D Tiles BIM
  * Shader compilation error. Expected, this is glTF 1.0
* ~3D Tiles Batch Table Hierarchy~ -- fixed in #10525 
  * "Color all doors" doesn't work, as `batchTable.isExactClass` is not a function
  * "Color all features derived from door" doesn't work, as `batchTable.isClass` is not a function
* 3D Tiles Clipping Planes
  * Fails due to the glTF 1.0 BIM model
* ~3D Tiles Compare~ fixed in #10506 
  * OSM Buildings have incorrect shading (see #10338)
* ~3D Tiles Feature Styling~ fixed in #10514 
  * OSM Buildings have incorrect shading
  * Color by Distance to Selected Location crashes shader -- fixed by #10514 
* ~3D Tiles Formats~ fixed in #10524 
  * Wireframe mode will need `enableDebugWireframe: true`
  * Composite tileset is repeated for some reason
* ~3D Tiles Inspector~ fixed in #10526 
  * Wireframe mode will need `enableDebugWireframe: true`
  * Statistics are not available (not yet implemented)
* ~3D Tiles Interior~ fixed in #10524 
  * Some parts of the model (most notably the floor!) are not loading
* 3D Tiles Photogrammetry Classification
  * The classification isn't showing up
* 3D Tiles Point Cloud Styling
  * Many of the styles are failing due to an `undefined` property value
* Polylines on 3D Tiles
  * Fails due to glTF 1.0 BIM model
* ~Development/3D Tiles Split~ fixed in #10524 
  * still using `.otherwise()`
  * Again, composite model renders multiple times

### Other 3D Tiles Sandcastles

These Sandcastles were found by searching "Cesium3DTileset" and "osmBuildings"
in the Sandcastle searchbar

Working Sandcastles:

* Classification Types
* Classification
* Cesium OSM Buildings
* Clouds
* FXAA
* Fog Post Process
* Scene Rendering Performance
* Terrain Clipping Planes
* development/3D Tiles Performance Testing
* development/Many Clipping Planes
* development/Pick From Ray
* development/Picking
* development/Shadows
* CZML 3D Tiles

Broken Sandcastles:

* Ambient Occlusion
  * Fails due to glTF 1.0 BIM model
* MSAA
  * Fails due to glTF 1.0 BIM model
* Montreal Point Cloud
  * Point cloud styling not showing up (GPU styling not implemented). See also #9944 
* ~Cesium OSM Buildings~ - fixed in #10506 
  * Incorrect lighting of OSM Buildings
  * No outlines
* ~Clouds~ fixed in #10506 
  * Incorrect Lighting of OSM Buildings

### Model Sandcastles

For these ones, I replaced `Model.fromGltf` with `ModelExperimental.fromGltf`

Working Sandcastles:

* Manually Controlled Animation
* development/Display Conditions
* development/Multiple Shadows

Broken Sandcastles:

* HeadingPitchRoll
  * Plane is frozen in place.
  * The camera doesn't zoom to the model correctly
* Image-Based Lighting
  * Doesn't seem to load the environment map. The sandcastle might need more
    adjustment to the new IBL API
  * The camera doesn't zoom in correctly
* LocalToFixedFrame
  * The camera zooming is incorrect
* development/3D Models Articulations
  * 404 on asset from `assets.agi.com`
* development/3D Models Instancing
  * ModelInstanceCollection... how will that work with ModelExperimental?
* development/3D Models Node Explorer
  * `nodesByName` is undefined
* development/3D Models
  * Again, the camera zooming doesn't work properly

**Comment by ptrgags** [comment]
Today I looked into why the glTF 1.0 BIM model crashes in ModelExperimental.

There's one shader that declares the normals as `attribute vec2 a_n;` and does the oct decoding in the technique's vertex shader.

Trying to allow a special case for this in `ModelExperimental` will add considerable complexity, so I wouldn't recommend we do that. Better to update the asset to use glTF 2.0

Some thoughts about how to update the model: 

* Probably the easiest thing would be to decode the oct-encoded normals an just use the standard `NORMAL` attribute.
* The techniques would have to be converted to regular glTF materials. 
* If the shaders in the techniques are still desired, they could be manually converted to a `CustomShader`. Though you'd need a `_FEATURE_ID` attribute to determine which shader to apply.

Unfortunately this upgrade process would have to be done on a case-by-case basis since glTF techniques are very open-ended (depends highly on the GLSL shader used)

**Comment by j9liu** [comment]
Came up in #10388: `Model` keeps its `boundingSphere` in local space, whereas `ModelExperimental` returns the bounding sphere in world space (i.e. with `modelMatrix` applied). The `ModelExperimental` method is better and more consistent with `Cesium3DTileset`, we just need to update the `Model` Sandcastles with this in mind and document it `CHANGES.md`
