### ISSUE TITLE
Multiple tilesets.json as one tileset

### ISSUE THREAD

**Issue by kamillasak** [CesiumGS/cesium#10382]
Hello, is there any way to add multiple tilesets to primitives? 
Cesium version is 1.70
Currently we have like 4 big tilesets. We try to add them like:

var tilesets = ["/tileset2,json", "tileset2.json", etc]
tilesets forEach(element => {
  tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url: element.url)}
})

When we open our site, we have randomly getting errors like A 2D tile failed to load
Error: Invalid tile content.

When we add only one of these tilesets, all work fine.
Problem is when we want to add couple od them. Sometimes we get 3 working, sometimes only one.

**Comment by ggetz** [comment]
Hi @kamillasak. You can create one tileset.json that points to multiple external tileset.json files. But I'm not sure if that will solve your issue. 

This question would be best suited for the Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
