### ISSUE TITLE
Translucent custom shaders on point clouds render opaque points as transparent

### ISSUE THREAD

**Issue by UniquePanda** [CesiumGS/cesium#10393]
Hi all,
I just noticed that a custom shader that has `isTranslucent` set to `true` and then just sets `material.alpha` to `1.0` in the `fragmentShaderText` will render points of a point cloud transparent.
As I wasn't able to reproduce this with any of the  "3DTiles Next" examples in the sandcastle (which doesn't use point clouds yet), I guess this is not intended.

You can see this in the attached sandcastle example (I also added a vertex shader to make the points bigger so that the effect is more visible).

Sandcastle example:
https://sandcastle.cesium.com/#c=dVRdb9owFP0rFk8gMZOQhISVVqvYpiHRFbV0e0FajXMp3hwb2Q4trfrfdxMHBGv3FN8Pn3O495heb6aFcmQsdZmT5Y7MjF5RMgMHhlxKCapLxlqWxVIwcqfEFowVbkdu9FI7wS2ZsiUlt5wpJdRDBXAp4TdTudFkbjTnWgqCIbliDgQZC82ZkQLoQnGtrCNbAY9IdU4UPJIxWFEW9Eeday9avI7HWjkmFJhFq0teFooQFGcwg1q3IgfzcX+RG0Can9rIfO5b2p3uQr12zhZqT+iEBAvulNF/os9zX2zXLKWRB+SJVjdgdWk40JXRxaXFtkneDgdxP6w4CAHFlhKudA7yy9MGjCgAdSOEMyXUHby0The3a1ZrPqY/KnhuQoSdG6asLDnCHIEQIsXD2uG0a6qDwulxlt59n07mTT/uzMGTR5/DE4Ld+wKWtMib+lU1rR/1caI2JW7G1t8uEUpjyJ+LX0WF7XuuS+eb/KFDXvaY5JCkm8pbt+IZcNoJDc72La/+cN8IXBn2UA3rHYm1wH29lvi1CbzI1X9EVnYzgklSNIcjgfsUZXKzZigtPEg7EfZ68I43KbW4CqAb3Kxw+BIsZXnebvzkLXbSyFkBhlEsVob2e83B4pKYE1qdOoDhUK1gKmp7CXEchGkc00Ech3EShXEzq34/CZKQxmGQZsMwDJJ+U4iTYRL3AxqlcZrFcRRVae9MbURlxTek34Dl6JiZcHx9o6VsqBMkHaRRlAVJEA3TJG0YPgS0nw4GQRomURYNs2zQFAa0n4WoJUuTOAiCLNlTNw+v1W2NrNtJuNiv4JMoNtq46om1Ke05KDYSt2J7y5L/AUe5tZ1mJaPe8dVRLrZE5Ofv/DcQLpm1WFmVUlamW7QuRj3sf3NV6vp3X6PxJdtVbevwYuqTlNJRD8P3bzqt5ZKZf5D/Ag

Browser:
Chrome 101.0.4951.67

Operating System:
Windows 10

**Comment by UniquePanda** [comment]
Hi @lilleyse,
I see, that makes sense.
As I was experiencing this, while working with custom shaders, I was assuming it's related to them. Wrong conclusion 😄

Thank you. I'll close this issue then.

**Comment by katSchmid** [comment]
Is it going to be much slower?
