### ISSUE TITLE
when.resolve().then and Promise.resolve().then are executed in a different order

### ISSUE THREAD

**Issue by Lifengm** [CesiumGS/cesium#10404]
Scene/Cesium3DTileStyle.js resulting in an error
![image](https://user-images.githubusercontent.com/34083435/170425012-b239662e-1a80-4868-8c70-d77efffebf21.png)

The order of execution is as follows：

![image](https://user-images.githubusercontent.com/34083435/170426535-df833e28-6615-404e-be41-3311bc3e7cf2.png)

![image](https://user-images.githubusercontent.com/34083435/170426561-5fa19d6a-0416-45ee-832f-f36f5989479f.png)

**Comment by ggetz** [comment]
Hi @Lifengm, a fix for this went in with https://github.com/CesiumGS/cesium/pull/10348 earlier this month. It should be released on June 1st. If you are using a style URL that needs to be loaded, note that the API has changed slightly. If you are passing in a synchronous style, no changes are needed, and you should no longer run into this issue. Thanks!
