### ISSUE TITLE
Custom Shader Guide included in Build folder

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#10400]
After running `npm run makeZipFile` the Custom Shader Guide gets added to the Build folder.

The quickest fix would be to remove `Source/Scene/ModelExperimental/CustomShaderGuide/README.md` since it just points to the new location at `Documentation/CustomShaderGuide/README.md`. Otherwise we'd have to modify the gulpfile so that it doesn't copy this file.

<img width="425" alt="Screen Shot 2022-05-25 at 10 38 03 AM" src="https://user-images.githubusercontent.com/915398/170288766-92dad2d6-fb9e-4391-bbeb-94de9a3cdaa6.png">

**Comment by ggetz** [comment]
This is a quick fix which I'll account for in https://github.com/CesiumGS/cesium/pull/10399.
