### ISSUE TITLE
Crash in handleTileFailure

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#10423]
`handleTileFailure` in Cesium3DTileset.js assumes that `error` is always defined, but there appear to be edge cases where `error` is undefined and we access it anyway. I have an app constantly spitting errors to the console because of this. The problem seems to stem from Cesium3DTileset not properly handling in flight requests once it is destroyed, but I don't have a reduced test case.

There are probably two issues here: 1) Why is `error` sometimes undefined and 2) The error handler should check for that.

It's `requestContent` in Cesium3DTileset.js that is registering `handleTileFailure` on `tile.contentReadyPromise`

Is there a workaround here we can apply to avoid this? It's otherwise a showstopper for the app.

CC @ggetz @lilleyse

**Comment by mramato** [comment]
Thanks, updating now and will let you know.

**Comment by ggetz** [comment]
@mramato Was this fixed for you as of 1.94?
