### ISSUE TITLE
untimeError: Aborted(CompileError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by Yaozefen** [CesiumGS/cesium#10420]
Cesium version：1.94.0
environment：npm

This is a small example of loading b3dm
My code：
const viewer = new Cesium.Viewer('cesiumContainer', {
        terrainProvider: Cesium.createWorldTerrain(),
      });

      const tileset = new Cesium.Cesium3DTileset({
        url: Cesium.IonResource.fromAssetId(40866),
      });

      viewer.scene.primitives.add(tileset);
      viewer.zoomTo(tileset);

But an error occurred that could not be loaded：
draco_decoder_nodejs.js:23 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at f (draco_decoder_nodejs.js:23)
    at draco_decoder_nodejs.js:38

I tried to roll back the version, but they all had the same problem.

He can load this layer： Cesium.IonResource.fromAssetId(8564)
But this layer cannot be loaded：Cesium.IonResource.fromAssetId(40866)

**Comment by ggetz** [comment]
Hi @Yaozefen, could you provide some more info about how you are including cesium in your npm app? Are you using any particular build tool?

It looks like you're having trouble decoding Draco, which some tilesets are encoded with and others aren't. To decode, you'll need to load an auxiliary `.wasm` file, which looks like it's not being successfully loaded in this case.

**Comment by Yaozefen** [comment]
@ggetz Thank you. Now I know that I need to load additional files. I have found a solution. Excuse me.
.

**Comment by mrjunn** [comment]
> @ggetz Thank you. Now I know that I need to load additional files. I have found a solution. Excuse me. .

man which these additional files are?

**Comment by Yaozefen** [comment]
> > @ggetz Thank you. Now I know that I need to load additional files. I have found a solution. Excuse me. .
> 
> man which these additional files are?

首先找到node_modules/cesium/ThirdParty目录
找到draco_decoder.wasm文件。
在项目根目录下的public目录下新建ThirdParty，将draco_decoder.wasm复制进去，

**Comment by mrjunn** [comment]
> 

成功了！多谢

**Comment by mrjunn** [comment]
> > > @ggetz Thank you. Now I know that I need to load additional files. I have found a solution. Excuse me. .
> > 
> > 
> > man which these additional files are?
> 
> 首先找到node_modules/cesium/ThirdParty目录 找到draco_decoder.wasm文件。 在项目根目录下的public目录下新建ThirdParty，将draco_decoder.wasm复制进去，

成功了！多谢

**Comment by IDHD713** [comment]
@Yaozefen hi,I find cesium in my node_modules,but it don't have ThirdParty folder just have a ThirdParty.extra.json and ThirdParty.json.what can I do then
