### ISSUE TITLE
Resource retryCallback parameter error not has valid status code

### ISSUE THREAD

**Issue by danny-wang** [CesiumGS/cesium#10436]
Resource retryCallback parameter error not has valid status code

Sandcastle example:

Browser: chrome

Operating System: mac os

`
function refreshTokenRetryCallback(resource, error) {
    console.log('error.statusCode:', error.statusCode);
   console.log('error:', error);
  if (error.statusCode === 403) {
    // 403 status code means a new token should be generated
    return getNewAccessToken()
      .then(function(token) {
        resource.queryParameters.access_token = token;
        return true;
      })
      .catch(function() {
        return false;
      });
  }

  return false;
}

const resource = new Resource({
   url: 'http://server.com/path/to/resource.json',
   proxy: new DefaultProxy('/proxy/'),
   headers: {
     'X-My-Header': 'valueOfHeader'
   },
   queryParameters: {
     'access_token': '123-435-456-000'
   },
   retryCallback: refreshTokenRetryCallback,
   retryAttempts: 1
});
`

i write the code like doc, but from console: 
![企业微信截图_8942bcf8-6e80-4462-b000-16edb415cd54](https://user-images.githubusercontent.com/10558518/172603544-ab57dcd7-4a41-4e6c-89d4-f1955e83f8b4.png)

error.statusCode: undefined
error: RequestErrorEvent {statusCode: undefined, response: undefined, responseHeaders: undefined}

i think the 404 status code should be return. is it a bug?

**Comment by ggetz** [comment]
We return the status code when a valid response is received. On an error event, it appears we do not specify a status code. Perhaps the CORS error you see is the reason why no status code is logged.

Would you be able to provide a [Sandcastle code example](https://sandcastle.cesium.com/) which duplicates the error?
