### ISSUE TITLE
UrlTemplateImageryProvider and CORS Errors

### ISSUE THREAD

**Issue by mlptownsend** [CesiumGS/cesium#10449]
I reproduced this using a random MapProxy instance I found published out in the wild. Ignore the fact that Cesium won't actually place the tiles properly without some sort of zoomOffset parameter (it needs -1). But if you run the below Sandcastle example, you'll be flooded with CORS errors in the console and network request tabs.

Access to XMLHttpRequest at 'https://go-tiles1.gistda.or.th/mapproxy/tms/1.0.0/thaichote/EPSG3857/2/1/0.png' from origin 'https://sandcastle.cesium.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Sandcastle-client.js:20 An error occurred in "UrlTemplateImageryProvider": Failed to obtain image tile X: 1 Y: 3 Level: 2.
go-tiles1.gistda.or.th/mapproxy/tms/1.0.0/thaichote/EPSG3857/2/1/0.png:1          Failed to load resource: net::ERR_FAILED

Network requests look like this.
![image](https://user-images.githubusercontent.com/38544371/173150615-59c955b3-0afd-4561-9a0d-77b10fb7426c.png)

I had a coworker in a wholly different location try the sandcastle and he got the same thing.
![image (18)](https://user-images.githubusercontent.com/38544371/173150683-291e9521-d85c-47da-bad6-1d5f6176cb68.png)

Also below is a JSFiddle that loads this same tile url in Leaflet, and it's working just fine.

There's a second URL commented out in the example. Same deal, random MapProxy server I found, but it doesn't throw CORS errors.

Sandcastle example:
https://sandcastle.cesium.com/#c=rZNha9swEIb/ivCnBLJTsjFW0jQMwiiDjgWSbWwYiiJfbFFZZ3SKk7Tkv0+205GmGfuyD0bo9L66584nTY6DqA1u0Ysb4XArZshmU8L3NtZLE93uZ+SCMg59mgzEU+qEMKXK0e/nnmqToR+fmpfG4ozIZ8apgPz5pbTX+oUIxhqXL3SBJb6w/8DVF/RaBfLLE02v3/gO/UGzrBTjndqjnxv90KRfK8sYjw7969SlTreV2UbBsbKuRGCNDuGI3to5qjsVqCw7J20ynYB983aJZWVjUf+tpkFnlPKv1luk3KuqMPqiszTuF1E5FsPngNp1gdHVn8uXhWFBDsWW/APDc3jj7VikSRFCxeMWARkyrCF4tW7bBDlSxaALGUqWIxjCUDa9v195kxfhvn4rP80Xt++u3n+QT48H+bSLn8c6NhR/HqByeZyYVxQZIQtH4QhyhpHTm5ZkBLnhkCkgD6GQpaoqT7v9CUkolNEFBfw3RDc7qetfi2SQTDjsLU679EJ8NGVFPjQgPQAZjj+Z5WoTpyuAZm7GqpFO5Kl1kplamOzmwjsR2irmeLLeWLswj5gm04mM+ldWSyq+lPxr5I2j2MiK0fSuCwLARMbtZWcgsivlz27+DQ

https://jsfiddle.net/p81aom5s/

Browser: Chrome 102.0.5005.63

Operating System: Win11

**Comment by ggetz** [comment]
Hi @mlptownsend, usually CORS errors like this occurs because of how the server (go-tiles1.gistda.or.th in this case)  is configured. There's some good discussion on this topic in https://community.cesium.com/t/cors-error-adding-urltemplateimageryprovider-layer/16734. Ultimately, I would check with the provider what the CORS policy is.

I'm closing this as I don't think it is a bug with Cesium, but feel free to re-open if you get more info that may point to an issue.
