### ISSUE TITLE
Gltf with CESIUM_primitive_outline extension render error

### ISSUE THREAD

**Issue by chenxx08** [CesiumGS/cesium#10452]
Sandcastle example:
[test example](https://sandcastle.cesium.com/#c=jVRtc9o4EP4rGj507BkiYsgLaUjmKHkpuQCZxMkApdMR9oIVbImTZALc5L/fyjaENm3mvtiSdp9Hu89qt1Ih14oJQ1qgeZrcPBAWBKA1MZKsZKoIl4IwrcHokch9aFsKGsKEpbFpZs6+nIEgZ2RUgtVNNL4OeI/ftB/Xba/L27ot7g+DVvuoPZv3n1o3JxSd/gmvZ9YpGfrDWffi6XnY8pLhRcRv/fto+Dw1g+fLqj0b+DOv5zcPB9XOsud3+G3rZj5Esu76ct3xO7qdxFGI+44/WHf9y3XvovPS7e9T//DrsH9ZO4D+pN+9B7X/wxvv1afHX/+WV3ePD7X9yXD4YxGk6aA5Kp2ORCCFNmTB4QUUZiLgpVCEPmVnzqgUZPuWFIZxAWpUchG3QRoeA4qE0JyD6gAE0LniCTd8AZqyMHRGguxS57/ahZ+DnX+tnZBUxZ/Jm9b3oLEQAdCJkknTlqIdOp5X3T+qnrjlHKIj+dJLTYyBfSZGpZCdv7ojkQc5SUVgbCkTuYAv0hiZtEAYUL50itDLJJYCPwxXEfBpZFySBbRgiozlElMrPKmS0lDM2yDFF5mKkIvpk4zTBOj4p+3pBs+WoJEAaWjE4kkTt1tbgIaNIEwZXDFRozodG8UC4+QJWmSQRVxkvCvjFuXYe74dfS9nF3473izq390PYa41utuIDFNTMHfmt4HZKlzAVAFo551iW4rEewN3mFF8eZAhfWw2jQishfNRRHsBXZYJflfZd/1LhEn1jT6jnEiVaApMm65UJnqc+/KKLyG8UiwBZ5PQDkHtfXwJNjSfx6st4W6YSbVQMPHeS1kw7Oq4eSuJDCHO7XhjUkPjq32RDtMrERDHJWfn+TszakWKDmAvjJu35wYsXN2heFznL4p8+Iz36ke0elyvHtXL5MCjXt07Ofbc013mokfXEguyReadYp0qFdKcoxDERECKSUe0WcVA+IQgHpZc24Fona2asMS3qnc6JJuYND8ubkZkISXZyIbU2LChk/u55NOnDx0oVuN/OW2m84MN2c3d3Y22b6XJMzr700TK0H9kLbJ6zeYMCZgJIuKAUlJtb7KTUcZAYzktLBkIIa+uY9elcqmRBXFuz//iyRzfrh1/DqUVA8kcGwV0ZZwGMww30NqCGpUNpBHyBeHh2W9GMwliLAFaJmkcP/A1jErnjQr6/wSLJbOzqrcAFbMVutgwGpF3fpsbKKWNCm7tpb9ijZTxmKkd3v8A)

Browser:
Microsoft Edge v102.0.1245.39

Operating System:
win11 

**Cesium3DTileset showOutline: false**
![0](https://user-images.githubusercontent.com/4447956/173334959-0ae3e04e-204b-4ced-9f10-6c81100618e8.png)

**Cesium3DTileset showOutline: true**
![1](https://user-images.githubusercontent.com/4447956/173335012-4e76cc07-c771-4e20-90d0-837c11182d4b.png)

tileset with glb model:
[data.zip](https://github.com/CesiumGS/cesium/files/8890267/data.zip)

**Comment by j9liu** [comment]
Hi @chenxx08,

Thanks for reporting this bug! We're working on adding support for the `CESIUM_primitive_outline` extension to `ModelExperimental` in #10338, so hopefully we can fix this in one go. We'll keep you updated.

**Comment by ptrgags** [comment]
Just to give an update on this, I'm currently working on `CESIUM_primitive_outline` in `ModelExperimental` this week. I can reproduce the problem in `ModelExperimental` now, so later this week I'll look into what's going wrong with the index generation.

![image](https://user-images.githubusercontent.com/8422414/176286566-c0df289f-9cf8-4368-a5d2-5c870eaaf95b.png)

**Comment by ptrgags** [comment]
Update:

1. My past comment was incorrect, I had forgotten to set the `enableModelExperimental` flag in my local Sandcastle :sweat_smile:. The good news is it renders correctly! [Local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=jVZtUyI5EP4rKa5qa6jCwIAvLKvWueju4i1o6Wgpy5YXZnogkpnMJRkErvzv15kXQN217oND0t1PvzzpdKzXyVfFYkO6oHkanV8T5vugNTGSLGWqCJcxYVqD0aM4t6E9GdMAQpYKc5IZe3IGMTkiowosz6fjrz6/4Oe9m1XPHfCe7sVXe363t9+bJXe33fOPFI3+Cb7OrFE09Iazwent47DrRsPTKf/uXU2HjxNz/3jWtLJ7b+ZeeCd7983+4sLr8+/d82SIzgars1Xf6+teJKYB7vve/Wrgna0uTvtPg7sG9fa+De/OWrtwF94NrkA1HtzxTnty8O0v+eXy5rrVCIfDh7mfpvcno8qnUezLWBsy5/AECiuJ4alghN5mMmdU8bN9V8aG8RjUqFJFXIn0U21kdD1lwWt8d0vj/DuKCQkVm0QQm1zmwcJ0yN9WMZc8WGv7GMX5Umx6cZIaEurst0Z4LHHrr6KHSAYg+syA4kyQqFhUSRYIQwnJDBmnXAQ8nvQCTC0TOYUrGgIzqYJeoDfLh4atzMJLfzTgYZhqQHjEF84c/Jbj0ka1RrJlgzZqpEH3aiQXbuLljp7tByt83mbMcAHYVugyZ51qH2KgieIRN3wOmrIgcCxym8zsp3Xq5WCnKDNVokM23XkFGlvXBxoqGZ3Y5u0Fjus2G/vNj9VaDtFT+XSRGoFH2SFGpVDI63WZS7tSSLX2mu3o1dnp2iyAcTq5Ri+fZRrbam+lSKPXzrb7ohBCzMYC+vbgzhYJ8msPmIkcmNFVHcU5U2Ea+8bewEjO4bM06KqLxtg00in4qxEhY/wwXE2BT6amOPw5U2QsF8hvYUmVlIYi+QZdvEyajl9sP5V4tgCNDtANnTIRnuB2rfNRUZLDlMEVi1tUp2OjmG+cvFaL9LOMi+K3z3KNcmycH/s/a1nAHwflov2z+i6sapXVdUaGqQmYS/PLxGwrnMJEAWjnDWNrF5G7AeOtUnyxmyE9nJEaEXgWznsZ7fh0USP4XWbf1asMo+bGfeYylCrSFJg2A6nM9Cbx5Be+gADvfQROWdCWg9bb/CKcwzwRy7XD7TSjZsFg5L6lsvCwzWPZK+VcQb299C1UPtuOdJhexj5xquToOO8zo5bltGFPjJtNuwELlpdIHtdQzpN32ninvU+bB+3mfrtGdl3qtt2PB245iHLPxaBYSTyQNTK/KfltIycJEkHMFEjxQBFtlgIIDwniYcG1fcessWUTJ69ieuuGZA8dzcVFZEQWVJKSNnSN8yFwcrsq+fDhXQOKp/G/jMpH9dqmXM3N15N8czR5RUe/G4sZ+rdei6qyifxMfGb8KXFAKanWkex4lgKokJNCUw7x56qTs12pVQ6zNI7L5P7kUYIdbCexQ2ndQJTgdQFdH6f+DJP2tS5jE/KHkVKM8QDWteGkYP5souwY6hA1GTNnt4l9UPw1aHuDJiTBlwGHVYfsJost8VgqnLI7igU81S+Vz29C8+xF3UpgDspwn4kdJvgk7uBDFwQC3kbdMTLpkOaLyKVqnPX2S20R+rC+TdhhwOeEB0e/+K+C+ALbEDVhKsQ1X8GocnxYR/s3UHzIbdQLzFywpTWbusffcyGl9LCO218jCxJeef4P) (requires the `model-experimental-outline` branch from #10506 for now)
![image](https://user-images.githubusercontent.com/8422414/176966999-6d2699ec-8041-4fed-a99f-7457135c8792.png)
2. I also discovered the source of this bug. In the code for handling outlines for the old `Model` (`ModelOutlineLoader`), a comment mentioned making an assumption that each buffer view only contains a single range of vertices. The new implementation in #10506 does not make this assumption and thus renders correctly.

@chenxx08 If you want to use the current `Model` implementation, try moving the second primitives' attributes to their own buffer view in the glTF, that might fix the problem. However, by the August release we plan to remove `Model` and rename `ModelExperimental -> Model` (see #10346). The fix in #10506 will be included.

**Comment by j9liu** [comment]
Hi @chenxx08,

We just merged #10506 into main, so this bug shouldn't appear while using outlines in `ModelExperimental`. Let us know if any other rendering errors come up!
