### ISSUE TITLE
appearance of gltf model material problem

### ISSUE THREAD

**Issue by qiangwai** [CesiumGS/cesium#10465]
my gltf model display in three:
![image](https://user-images.githubusercontent.com/41463375/174255811-1c2eda2b-cadc-4f3c-95cb-b10b397bc62e.png)
display in  cesium :
![image](https://user-images.githubusercontent.com/41463375/174255890-b866e846-fe51-4595-ac8d-b561f26e3f84.png)
How to show better texture effect？

**Comment by lilleyse** [comment]
I think this is related to https://github.com/CesiumGS/cesium/issues/6506. CesiumJS doesn't generate normals for glTF models when they are missing which leads to this unlit appearance. I'm going to close this issue but mention it in https://github.com/CesiumGS/cesium/issues/6506.
