### ISSUE TITLE
Can not render the model

### ISSUE THREAD

**Issue by guishilike** [CesiumGS/cesium#10470]
When loading oblique photography data, it can request the 3D tiles data and locate the area, but can not render the model
![fbcc747f6c5ca21f58fc4edbaeaa779](https://user-images.githubusercontent.com/51023060/174578631-8ef5198d-32fd-4c9e-a37c-4da02ab829ec.png)

**Comment by ggetz** [comment]
Hi @guishilike, would you be able to provide the tileset so we can take a look?

**Comment by guishilike** [comment]
There is no problem with tile data, we have experimented.
The cause of the problem may be the use of relative paths.
So we deployed js, css and tile data as services, now the problem is solved, thanks.
