### ISSUE TITLE
Strange Transparent Effect

### ISSUE THREAD

**Issue by JiaoJianing** [CesiumGS/cesium#10487]
This is the [live demo](https://sandcastle.cesium.com/#c=bVPJbtswEP0VwpfYgEst1GbHCYokPRQokAI2WqDQhaJGMluKVEnKiVvk30tRShq00YHSzLw3erOQKWksOnF4AI2ukIQHdAuGDx3+4n3LcsG8faukpVyCLhdr9LuUCDHngUd731vukmwnJ0Iafg5g7FeoWhFvkdUDjIGn9Xh2htI97XoBjpB4l9I16I+yhh7cIe1BU2nEwECy8zP9aXVZSualGhcAp3SSjL3pgrPZK2M/a+Ukm72lLRjcPFKKQdJKQO1oYz4Hf85muVMC1gV8Itxr3nHLT45I63o56nvVkulF7g4TazlXPGixRRdHa3uzDQLGOzZUgFuhaiUxU11QNYEGowbNIEhonCYAYUhZlmVVyiApaJUWIZB0U1X0L/JEAlJ7gcEsE383Sl74bq5KufJ1zIUz2oGmuBHng5p01W4IXNJxONuXAqi27otKghutujtoNYBZRiHBmzAroiQLkw1Jw3iNSIiTJI3yKEyKJI+ziKxRtMFRQTKS5STP4jAmZDWPkLvBzb+am3IEWnPZblGIo3yTxpssT6M4JnkeZesJ0nPLjlv0LsRp5gCbNCJpHCcOPAO0Eq6zGY4LEhVplBapoxPiGzAvRSn3VNaMGitgHNlBta2Am8FaJd3ufvCDR0K16Nu4uOP416gZJBvFIj9gdgT2A2rX0En7tAmOQjW3x46zO+jt8WZoGn9FZvjliwDkn8V6sTP2LOD62fOed73SdlyPJcaBBbf21LU/qAaXwGJmzJhghO6C19RdzU+I11dvXD3EBDXGRZpBiD3/BeXiehc4/H9UoXz/70+gBT2PsGN0/WlyYox3gTPfZlqlREX1P5n/AA)
The question is:
Construct Viewer with orderIndependentTranslucency: true, the glasses look like this color:
![image](https://user-images.githubusercontent.com/12868409/176074657-9472bac2-4563-4669-8cf3-296c874c35f0.png)
with orderIndependentTranslucency:false, they look like another color:
![image](https://user-images.githubusercontent.com/12868409/176074708-6e80a520-6b9b-41a3-a4d6-3ee7b220c9c7.png)
Is this the same problem in [4170 4](https://github.com/CesiumGS/cesium/issues/4170) ?
Looking forward to your help!

**Comment by JiaoJianing** [comment]
Maybe it's the correct transparent effect when disabling OIT?

**Comment by JiaoJianing** [comment]
@sanjeetsuhag sorry I can't find an available 3dtiles loader in BabylonJS or ThreeJS. But I seem to find a bug?
When create renderState in [Model.js](https://github.com/CesiumGS/cesium/blob/main/Source/Scene/Model.js#LC3392) it uses WebGLConstants.ONE as functionSourceRgb(Maybe it's OIT algorithm's requirement). But when construct Viewer using orderIndependentTranslucency:false, should it use WebGLConstants.SRC_ALPHA?

**Comment by ggetz** [comment]
I believe this is an expected result of using https://github.com/CesiumGS/cesium/issues/4170#issuecomment-237333922.
