### ISSUE TITLE
ES6 Modernization: when to update old usage patterns?

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10486]
As CesiumJS relaxes ES5-only syntax (see https://github.com/CesiumGS/cesium/pull/10396) and eventually allows more modern features, the question is what to do about the existing code, when does it make sense to update old patterns to use newer features?

To take a concrete example, consider the `AssociativeArray` class. This is a class that's designed to store key-value pairs and allow iteration. This sounds very much like an [ES6 `Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) in terms of what operations it supports. Though this leads to questions like:

* Should we remove `AssociativeArray` and replace it with `Map`? (after considering overall performance impact (not microbenchmarks) and how much it impacts the public API).
* If we need a backwards-compatible interface, should the `AssociativeArray` just store a `Map` and delegate functions?

Another example: There are spots in the code where a dictionary is used like a set (need a collection of keys with `O(1)` lookup time):

* In `CustomShader`, I used a dictionary with dummy values for storing shader variables (e.g. `{key1: true, value: true}`), though a `Set` would have had a clearer intent that I just need it for fast key lookups. (This might be a bad example, as set union/intersection would be helpful as well for comparing sets of shader variables more like a Python `set`)
* In `ModelOutlineLoader`, the edges are stored in a strange data structure: an array used like a dictionary except index 0 stored the original vertex count... The `ModelExperimental` replacement code for this feature will use the dictionary approach (which can be easily swapped out for a `Set`) 
* Where else? We'd have to search through the code to see what other parts of the code fake a set data structure using an `AssociativeArray`, a dictionary, or something else.

**Comment by jjhembd** [comment]
Here's another pattern that appears frequently in our code:
```javascript
for (const key in myObject) {
  if (myObject.hasOwnProperty(key)) {
    const value = myObject[key];
    // do something with value
  }
}
```
This pattern loops unnecessarily over inherited properties.

We could now use the ES8 method [Object.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values), which only returns 'own' properties), and skip the call to `.hasOwnProperty()`:
```javascript
for (const value of Object.values(myObject)) {
  // do something with value
}
```
If the property names are also needed, we can use [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) with a destructuring assignment:
```javascript
for (const [key, value] of Object.entries(myObject)) {
  // do something with key and value
}
```

**Comment by jjhembd** [comment]
A few more old polyfills that could be replaced:
- [requestAnimationFrame](https://cesium.com/learn/cesiumjs/ref-doc/global.html#requestAnimationFrame): replace with the [Web API method](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
- [cancelAnimationFrame](https://cesium.com/learn/cesiumjs/ref-doc/global.html#cancelAnimationFrame): replace with the [Web API method](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame)
- [combine](https://cesium.com/learn/cesiumjs/ref-doc/global.html#combine): replace with [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign). Most cases could be directly replaced, but a few using the `deep` flag would require more thought
- [getAbsoluteUri](https://cesium.com/learn/cesiumjs/ref-doc/global.html#getAbsoluteUri), [getBaseUri](https://cesium.com/learn/cesiumjs/ref-doc/global.html#getBaseUri), [getFilenameFromUri](https://cesium.com/learn/cesiumjs/ref-doc/global.html#getFilenameFromUri), and a few others: These are mostly wrappers around the third-party library [urijs](https://www.npmjs.com/package/urijs), which is now deprecated in favor of the Web API [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL)

These are all on the public API, so we would need to phase them out with a deprecation period.

**Comment by ggetz** [comment]
We've begun using many of the features described in this issue, such that I don't think keeping the issue open is helpful. We'll discuss additional feature usage as they come up, and update any automating linting rules or the coding guide when appropriate.
