### ISSUE TITLE
Cesium Assets are not laoded.

### ISSUE THREAD

**Issue by Saumya-NebCodes** [CesiumGS/cesium#10499]
I am using **Ionic(Angular) 5** with **Electron** to build my **Linux OS Application**. Everything is running fine but whenever I load my Cesium component for the very first time it throws these errors.

**This error only occurs once after that it works perfectly(after hard refresh it works perfectly fine)**

`Failed to load resource: the server responded with a status of 504 (Gateway Timeout) file:///opt/ElectronTestPAIGroundControl/resources/app.asar/www/assets/cesium/Assets/approximateTerrainHeights.json`

Similar error occurs for others assets like Texture, cesium styles etc.

![Screenshot from 2022-06-30 18-29-54](https://user-images.githubusercontent.com/78317459/176683454-07ee5a7c-14a2-4400-8f3f-9bfa1b3fa9b1.png)

If anyone faced similar issue? please guide me, as it has been weeks and finally I am posting this on every libraries/framework, I think it might be the issue of.

**Comment by ggetz** [comment]
Hi @Saumya-NebCodes, that [504 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) usually indicates something is going wrong on the server. Perhaps something is going wrong when serving any static files on a repeated request?

This doesn't appear to be Cesium specific, so I'll close this issue.
