### ISSUE TITLE
What are the rules of the metadata extension in terrain

### ISSUE THREAD

**Issue by zhangiser** [CesiumGS/cesium#10503]
Hi there! I'm new to cesium,and i'm using Cesium World Terrain provided by ion,of cause it's contains water mask and metadata,and there has a function createQuantizedMeshTerrainData in CesiumTerrainProvider.js.When QuantizedMeshExtensionIds is 4,it means metadata,so create a Quadtree.So what's the rules of the metadata extension in terrain?

I only know some that:
terrain is tms standard service.
Level0 is 000 and 010,and when comes to level1,the 000 is divided into four tiles,so
Level1:{endX: 1, endY: 1, startX: 0, startY: 0}
Level2:{endX: 3, endY: 3, startX: 0, startY: 0}
Level3:{endX: 7, endY: 7, startX: 0, startY: 0}
Level4:{endX: 15, endY: 15, startX: 0, startY: 0}

but,when comes to Level5,it's divided into three area:
{endX: 21, endY: 31, startX: 0, startY: 0}
{endX: 31, endY: 5, startX: 22, startY: 0}
{endX: 31, endY: 31, startX: 22, startY: 6}

and Level6,Level7,Level8 also be divided into three area.When comes to Level9,it's divided into 226 area:
{endX: 355, endY: 298, startX: 298, startY: 213}
{endX: 355, endY: 426, startX: 298, startY: 369}
{endX: 355, endY: 113, startX: 284, startY: 99}
{endX: 341, endY: 212, startX: 298, startY: 128}
......

So may I know the rules of area or block?

**Comment by ggetz** [comment]
Hi @zhangiser, Cesium World Terrain is [quantized mesh format](https://github.com/CesiumGS/quantized-mesh). That link contains an explanation of the format and how metadata works. 

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. If you have any further questions, I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by zhangiser** [comment]
> Hi @zhangiser, Cesium World Terrain is [quantized mesh format](https://github.com/CesiumGS/quantized-mesh). That link contains an explanation of the format and how metadata works.
> 
> Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. If you have any further questions, I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

Thanks, i saw this page many times but cannot got anything useful else.
