### ISSUE TITLE
Handle `skipLevelOfDetail` and backface commands in `ModelFeatureTable`

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10535]
`Cesium3DTileBatchTable` has code for handling `tileset._skipLevelOfDetail`, which determines whether backface commands are generated for tiles in the tileset. The equivalent class in `ModelExperimental` `ModelFeatureTable`, does not handle this yet.

When done, this should be tested by the "create duplicate backface commands" test in `Cesium3DTilesetSpec`

**Comment by j9liu** [comment]
This came up on the forum: https://community.cesium.com/t/modelexperimental-rendering-3dtileset-failed/19759/3

**Comment by lilleyse** [comment]
I started to address that here: https://github.com/CesiumGS/cesium/tree/skip-lods-experimental

The `ModelExperimentalDrawCommand` refactor was pretty far along and I was about to change how commands are pushed to the command lists to avoid array allocations. If someone else would like to pick that up go ahead!
