### ISSUE TITLE
Trim subtree of 3dtiles 

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#10543]
When I load large scale of 3dtiles, the memory used by tileset will be bigger and bigger, cesium will release content, but cannot release the tree node. When I load tileset which have about 70Gb size and about 2 million tile will finally cause chrome out of memory and shut down.
Do I have a proper way to trim tileset?

**Comment by ggetz** [comment]
Hi @jiangheng90, how was your tileset generated? And would you be able to provide a link to it for testing?

**Comment by jiangheng90** [comment]
@ggetz I have seen assets of Photogrammetry in ION, the number of tiles are very small. memory usage of tileset is not big.So I think optimize data decrease tiles rather than trim tile in frontend may be a good idea .
