### ISSUE TITLE
How to clear entity containing the extrudedlight: new Cesium.CallbackProperty attribute

### ISSUE THREAD

**Issue by gisergit** [CesiumGS/cesium#10561]
I use entity's _extrudedheight: new Cesium.CallbackProperty_ attribute to simulate the flooding effect, but after implementing entity's removal method, the flooded part still exists on the map. 

Please give me some suggestions on how to remove it.
Thanks.

`
let entity =  this._drawLayer.entities.add({

    polygon : {
    	hierarchy : new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArrayHeights(areaCoor)),
    	perPositionHeight: true,

    	extrudedHeight: new Cesium.CallbackProperty(function () { 
    	    waterHeight+=2;
    	    if(waterHeight>targetHeight){
    	        waterHeight=targetHeight;
    	    }
    	    return waterHeight
    	 },false),

    	 material : Cesium.Color.fromBytes(0,191,255,100),
    }
});
`

**Comment by ggetz** [comment]
>  but after implementing entity's removal method, the flooded part still exists on the map.

I'm not sure how you are removing the entity. Would you be able to provide a [sandcastle example](https://sandcastle.cesium.com/) which shows the problem?

**Comment by gisergit** [comment]
> > but after implementing entity's removal method, the flooded part still exists on the map.
> 
> I'm not sure how you are removing the entity. Would you be able to provide a [sandcastle example](https://sandcastle.cesium.com/) which shows the problem?

Thank you. It's my problem. After testing, it was solved.
