### ISSUE TITLE
Viewer.destroy not checking if ScreenSpaceEventHandler is defined

### ISSUE THREAD

**Issue by TJPovey** [CesiumGS/cesium#10576]
Sandcastle example:
https://sandcastle.cesium.com/#c=hVA9a8MwEP0rhztYhiDTuY4ppIUOgQ6BTl4U6ZqKyJIrnRzc0v9eOUogoYFqu/dx7+mks4Fg1HhAD0uweIAVBh17/nbEWFfI47xyloS26LuieuhsZ7OHB+kR7WYQEp9HtPQirDIJVxjIu4llsXIy9onlnxH9tEGDkpxn5d1JlsPKiguljmvWOhCmNFZKo+W+XACrYNnCd2cBZCrtDHLjduyfGjo85QRUrJq7wOmzVwV/cstiUTSBJoPtrJvfo+4H5wmiN4zzmrAfjCAM9TbKPRKXIeSlAE19aW2UHkGr5Y3zgTQihMS8R2M2+gu7om3qpP9jNU4obXevI3ojpln2cd+uM8g5b+o03naSc2YrUtiZ2UYiZzN5dfMkOV0IMtDUWXt2Xuz/BQ

If the viewers ScreenSpaceEventHandler has been destroyed prior to the viewer being destroyed, unminifed cesiumjs is throwing a developer error:
```The object is destroyed...```
The viewers destroy method is not checking if the handler has been destroyed prior to using it, like it is for other fields:
https://github.com/CesiumGS/cesium/blob/51f3c656e638dd2ead7a2e297f8a391bcb75b915/Source/Widgets/Viewer/Viewer.js#L1681

Happy to create a PR or remove the issue if it is desired behaviour. Although it does look like the viewer is only removing two input actions and not actually destroying the handler:
```
  this.screenSpaceEventHandler.removeInputAction(
    ScreenSpaceEventType.LEFT_CLICK
  );
  this.screenSpaceEventHandler.removeInputAction(
    ScreenSpaceEventType.LEFT_DOUBLE_CLICK
  );
```

**Comment by ggetz** [comment]
@TJPovey  Thanks for the report! Though I think there was an underlying assumption that the screenSpaceEventHandler wouldn't be destroyed separately, I don't see why a simple verification in the destroy method would hurt.

**Comment by nayangoyal** [comment]
Hi, @ggetz can you assign this issue to me?

**Comment by ggetz** [comment]
Hi @nayangoyal, great! Please go ahead and get started by taking a look at [`CONTRIBUTING.md`](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md).
