### ISSUE TITLE
Better hints to set `enableDebugWireframe` in tileset constructor

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10608]
As of Cesium 1.97, the `enableDebugWireframe` flag will be required for `debugWireframe` to work, for both `Model` and `Cesium3DTileset`. Otherwise, nothing happens when `debugWireframe` is toggled. We should more clearly convey to the user that `enableDebugWireframe` needs to be set true for `debugWireframe` to work.

Some suggestions:
- `oneTimeWarning` if a user is setting `debugWireframe: true` in the tileset constructor without setting `enableDebugWireframe` true, or if a user is setting `debugWireframe` at runtime
- same for `Model`
- disabling the wireframe checkbox in `Cesium3DTilesInspector`, with some text that `enableDebugWireframe` should be true for this to work`

**Comment by j9liu** [comment]
Link to the forum post that brought this up: https://community.cesium.com/t/debugwireframe-not-working-with-3dtiles-content-gltf/19741/4

**Comment by Sn00pyW00dst0ck** [comment]
I can take a look into implementing this if nobody else has started working on it.

**Comment by j9liu** [comment]
Thanks for your interest in contributing @Sn00pyW00dst0ck! I don't believe anyone has started working on it, so feel free to contribute and open a PR when you're able 😀

**Comment by j9liu** [comment]
Looks like this was addressed by #10803, so I'm closing this issue.
