### ISSUE TITLE
How to load multiple models for planing and control them independently？

### ISSUE THREAD

**Issue by Makabaka-goodnight** [CesiumGS/cesium#10603]
In this sandcastle demo，https://sandcastle.cesium.com/?src=3D%20Tiles%20Clipping%20Planes.html  ， I load multiple 3dtiles models in a scene and add a plane entity to each model，When I move one of the plane entities, the others will move up and down，The parameter printed in the callback function of callbackproperty is always the plane of the last model，How can I control it separately？

**Comment by ggetz** [comment]
Hi @Makabaka-goodnight, you will likely need to maintain separate `targetY` values for each plane.

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. I would ask that you take this to the [Cesium Forum](https://community.cesium.com/), where there are members of the community and developers from the team who can help, to continue troubleshooting if needed. Thanks!
