### ISSUE TITLE
Improve atmosphere

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1064]
CC @tfili
- Show atmosphere on the globe, not just the sky
- Maybe show atmosphere on objects

**Reading** (old to new)
- [Rendering Outdoor Light Scattering in Real Time](http://www2.ati.com/developer/gdc/GDC02_HoffmanPreetham.pdf) - old, but good intro material
- [Accurate Atmospheric Scattering](http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter16.html) in GPU Gems 2 - what [Cesium does now](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/SkyAtmosphere.js) (sky only).  Perhaps do ground atmosphere as a separate pass over the central body?
- [Real-Time Rendering of Planets with Atmospheres](http://www.vis.uni-stuttgart.de/~schafhts/HomePage/pubs/wscg07-schafhitzel.pdf) - too big to stream?
- [Precomputed Atmospheric Scattering](http://evasion.inrialpes.fr/~Eric.Bruneton/)
- An Approximation to the Chapman Grazing-Incidence Function for Atmospheric Scattering in GPU Pro 3

Lots of stuff on [vterrain.org](http://vterrain.org/Atmosphere/).

**Comment by hpinkos** [comment]
![image](https://cloud.githubusercontent.com/assets/3451886/10497844/2aa1eba8-7296-11e5-8a2b-08d117731096.png)
Side note: The moon currently obstructs the atmosphere

**Comment by hpinkos** [comment]
Also, the atmosphere doesn't render on some mobile devices.  Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/Z3KJnMCkSSc

**Comment by mramato** [comment]
#3141 has weblreport for my phone (which doesn't show atmosphere).  My Nexus 9 tablet shows the atmosphere fine.

**Comment by jmgomezpoveda** [comment]
I have realised of the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/1064#issuecomment-148201181 looking at the globe from afar. When the Moon is behind the Earth, the Moon is rendered below the Earth, but on top of the atmosphere.

**Comment by philipjmurphy** [comment]
@jmgomezpoveda et al you can see this issue, where the moon appears in front of the atmosphere, but behind the earth, more pronounced when the size of the moon is increased with the following code snippet:

    var radius = Cesium.Math.LUNAR_RADIUS * 10;
    viewer.scene.moon = new Cesium.Moon({
        ellipsoid : new Cesium.Ellipsoid(radius, radius, radius)
    });

![image](https://cloud.githubusercontent.com/assets/1055915/17653622/40ebd550-6290-11e6-8093-54361ce08d15.png)

**Comment by pjcozzi** [comment]
* [Tutorial series on atmosphere](https://www.alanzucconi.com/2017/10/10/atmospheric-scattering-1/)

**Comment by pjcozzi** [comment]
* Hot off the press: [Precomputed Atmospheric Scattering: a New Implementation](https://ebruneton.github.io/precomputed_atmospheric_scattering/) - a new implementation of Eric Bruneton's Precomputed Atmospheric Scattering paper.

**Comment by pjcozzi** [comment]
* Follow up to the GPU Pro 3 chapter: [Followup to Atmospheric Scattering—Part 1](http://www.thetenthplanet.de/archives/4519)

**Comment by pjcozzi** [comment]
CC ground atmosphere, #6877

**Comment by ggetz** [comment]
Closing this after recent atmosphere improvements we've made. Going forward, we'll track specific enhancement ideas in new issues.
