### ISSUE TITLE
3D Object Color Bug -- all objects get same color

### ISSUE THREAD

**Issue by paherbst** [CesiumGS/cesium#10656]
when creating 2 entities for the same Model, but each a different color, the 1st object gets the color assigned to the 2nd one.

proof of example with 1.96

https://sandcastle.cesium.com/#c=1ZPfT9swEMf/FSu8FAkcpy0w2lKByo+XSUyrtCdLyE2O7jTHrmynUCb+dy5O0lWFTXvYyyJFuV/fO9/HSm6ND2yN8ASOXTADT2wGHquSf4uxnkzy6M+sCQoNOJkcjqWRRkNgK+sxoDVfoSBxK5wpF8hSZsAfnS2vYekAfE8aRs9x1h9wcTYcnmbnR01oOOTiRAzOxGkXEJmorfdz7qiT+aeTxN4kMAHDptmnocJjCMFzVRS9n43QqBJGTCZUKJO2WXfI0S6WNlfaAvSItWrGKoe1nPN0rsqVhmsVVBqLfNosd4WutR7I5Eu92A6idmiwrMov+Ax6ji90lKz/6VdWPdfZea40Zfq0o9jmcqutG20B1l5kN/M+OvPg0Czp1g9ub2sh3XarfY3f131U3ZX8BaxY+gdcMf//AhOiRvYbYB2f4FT+A4qbyI6w7UCkuuQokcm4lnUvYxMfNhqm3XkusVxZFwiI7hGNAERD0V+QLipqHHju/eG4Vaa70kmBa4bFxQc/NMu18p4yj5WOeGQynaRU/06qrSpo3fs1OK02ddn3bPq5CXLOJym5HyuDtXqh3F7nNw

**Comment by sanjeetsuhag** [comment]
Hi @paherbst,

Running this on the `main` branch as of https://github.com/CesiumGS/cesium/commit/633af0dfcee59c8bf65252f4b764946d31d9457f, it seems like this has been fixed.

![image](https://user-images.githubusercontent.com/5172619/183741978-077d1cfc-28a7-45cc-a404-9c904a8151f1.png)
