### ISSUE TITLE
Lighting issues when rendering glb models with EXT_mesh_gpu_instancing extension

### ISSUE THREAD

**Issue by Error806** [CesiumGS/cesium#10659]
I'm having trouble replacing an i3dm file with a glb file that uses the EXT_mesh_gpu_instancing extension, the lighting of the model rendered in Cesium doesn't seem to be correct. Every instance seems to have the same lighting and shadows, regardless of rotation. Am I setting some properties wrong or is there another reason?
The following example has two instances, one of which is rotated by 90°. I took screenshots in 3 angles.
![image](https://user-images.githubusercontent.com/38496128/183609742-ff2f791c-a000-4864-b3b2-be088e761af7.png)
![image](https://user-images.githubusercontent.com/38496128/183609773-3840e3b2-e18b-4cfc-ac51-999ac0f3411b.png)
![image](https://user-images.githubusercontent.com/38496128/183609786-a18bc72c-6fc1-446b-be76-7dd8fa54021c.png)

For comparison, the lighting of the original i3dm is not the same as the glb.I took screenshots from the same 3 angles.
![image](https://user-images.githubusercontent.com/38496128/183609842-ac63dbab-2fa6-4c51-a38f-d5a80a93b8c7.png)
![image](https://user-images.githubusercontent.com/38496128/183609858-91fd91d5-46ec-458a-8083-5642843bf561.png)
![image](https://user-images.githubusercontent.com/38496128/183609880-20b20bd6-c488-4636-a31b-f15efb2663f7.png)

(from google translate)

Sandcastle example:

Browser:
Microsoft Edge 104.0.1293.47

Operating System:
Windows 10

model file i use
[twoInstances.zip](https://github.com/CesiumGS/cesium/files/9288964/twoInstances.zip)
:

**Comment by j9liu** [comment]
Hi @Error806,

Thank you for the bug report! I opened #10690 to fix this issue.
