### ISSUE TITLE
Polygon with a hole as the whole polygon

### ISSUE THREAD

**Issue by kurdupovk** [CesiumGS/cesium#10657]
Hello everyone!

I have a polygon with hole points the same as the polygon points.
I expected that I would get an empty polygon or only outlined polygon if outline is provided.

But I get a polygon with only a half hole.
Here is the code:
```
const viewer = new Cesium.Viewer("cesiumContainer");

const points = Cesium.Cartesian3.fromDegreesArray([0, 0, 1, 0, 1, 1, 0, 1]);

viewer.entities.add({
  polygon: {
    hierarchy: new Cesium.PolygonHierarchy(points, [new Cesium.PolygonHierarchy(points)]),
    outline: true,
    height: 1,
    outlineColor: Cesium.Color.WHITE
  }
});

viewer.zoomTo(viewer.entities);
```

Is it a bug or I don't provide a hole correctly?

**Original issue:**
I was trying to get an extruded polygon without **the top side** with some tricks.
I tried to create 2 polygons - one as the bottom side, which is clamped to ground, and another, also is clamped, extruded polygon with only "walls" using the **holes** parameter as in example above.

I tried **Wall**, but It does not suit my case, because wall does not have "clamp to ground".

I also tried a **Corridor** as a wall for my polygon, but It did not work well, sometimes I got Corridor walls under the ground.

I appreciate any help!

**Comment by GatorScott** [comment]
I don't think what you've described is a bug since it is essentially a degenerate polygon.

[PolygonGraphics ](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html) has the property ```closeTop``` which could do what you want, though I could be missing something.

```
const viewer = new Cesium.Viewer("cesiumContainer");

const points = Cesium.Cartesian3.fromDegreesArray([0, 0, 1, 0, 1, 1, 0, 1]);

viewer.entities.add({
  polygon: {
    hierarchy: new Cesium.PolygonHierarchy(points),
    height: 1,
    outline: true,
    extrudedHeight: 10000,
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
    closeTop: false,
    outlineColor: Cesium.Color.WHITE
  }
});

viewer.zoomTo(viewer.entities);
```
![image](https://user-images.githubusercontent.com/4126790/183658435-e86c0248-0986-4561-a860-ecffcb36c61a.png)

**Comment by kurdupovk** [comment]
Thank you! My case is resolved!
