### ISSUE TITLE
Cesium no longer works under Node.js when using ESM modules

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#10684]
1. Create a file called `test.mjs` with contents `import { Cartographic } from "./Source/Cesium.js";`
2. Run node `test.mjs`
3. It fails with the below callstack

```
$ node test.mjs 
file:///home/mamato/Git/CesiumGS/cesium/node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js:33
class Crc32Stream extends TransformStream {
                          ^

ReferenceError: TransformStream is not defined
    at file:///home/mamato/Git/CesiumGS/cesium/node_modules/@zip.js/zip.js/lib/core/streams/crc32-stream.js:33:27
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

I did a little digging and it appears `zip.js` module released a new version in the past month that caused this. Pinning to an older version fixes the issue (need to experiment to find out the exact version). May be worth opening an issue with them to see what they have to say.

Once we address this, it would be good to add the test.mjs and run it as part of CI to avoid breaking ESM support in the future.

CC @ggetz

**Comment by ggetz** [comment]
Thanks for the report @mramato! I opened a fix for this in https://github.com/CesiumGS/cesium/pull/10694/. Looks like [the zip.js maintainer addressed this and suggests](https://github.com/gildas-lormeau/zip.js/issues/340#issuecomment-1177329994) either locking to `2.4.x` or adding a polyfill for `TransformStream`. I've locked it in the above PR.

**Comment by mramato** [comment]
Thanks @ggetz!

Should we write up another issue to undo the pinned npm version once the zip.js maintainer has a better fix on their end?

**Comment by ggetz** [comment]
Opened https://github.com/CesiumGS/cesium/issues/10712
