### ISSUE TITLE
useWebVR only shows left eye, the right view is black

### ISSUE THREAD

**Issue by zxj5470** [CesiumGS/cesium#10692]
Sandcastle example:
https://sandcastle.cesium.com/#c=bY5Na8MwDIb/ivClLQSbXpcPynod9DDYyRfXUVdTxS62nJCN/felzQYjnUCH9+MRssEnht7hgBFq8DjAHpPLnXy7e+uVvct98Gycx7gq4FN7mKaPz5k5+CfgmFH7r00pCqFFeYt/F6BKPBI2swDYue4aIkOOtJZSMXZXMoxJHbO9IEub0qb8IdVftGpdD66ttVh8pAVYMilNySkTvboP1KKp1NR/QCmY1vn3Q4+RzHirnbfNy2xKKSs1yf9JDoGOJi4ufwM
Browser:
Edge Chrome 102/ Firefox103
Operating System: Windows 10
Current Cesium Version: 1.96

![image](https://user-images.githubusercontent.com/20026798/184820115-aa244b8e-683c-474c-8ae4-a6525029d795.png)

And we can't see right view until we zoom in... zoom in .... zoom in...
Until you can't see the edge of the earth.

![image](https://user-images.githubusercontent.com/20026798/184820399-82f5c9ea-f584-4906-afdd-5b30d440aef5.png)

![image](https://user-images.githubusercontent.com/20026798/184820526-87633081-d49c-41e3-bd8a-ed313e6b7e38.png)

**Comment by ggetz** [comment]
Hi @zxj5470, thanks for the report! The VR feature has not had much focus lately as we've been instead investing in this feature in the Cesium for Unreal project and other game engine integrations. We feel our current implementation is really a stop gap solution for VR and would rather proper XR support. If you have any interest in the implantation or have further thoughts, please let us know here: https://github.com/CesiumGS/cesium/issues/3422.

**Comment by hyflzh1314** [comment]
Is this problem solved now?
