### ISSUE TITLE
I use cesium3dtileset and add it to the primitivecollection to load the model of bd3m. When loading multiple models, rendering is not possible. It can correctly locate the model, but only one of them will be rendered

### ISSUE THREAD

**Issue by Criska9527** [CesiumGS/cesium#10709]
Sandcastle example:
![image](https://user-images.githubusercontent.com/37037014/185831989-d052471f-70dd-4b67-81c7-05981cb5dc8e.png)

Browser:
microsoft edge

Operating System:
win10

I use cesium3dtileset to load multiple bd3m models, but I can locate the models normally, but I can only render one

![image](https://user-images.githubusercontent.com/37037014/185832178-4925d2e1-2bc3-4aab-8568-93b769057f72.png)

As can be seen from the above figure, I loaded four models, but only rendered one

**Comment by Criska9527** [comment]
I found the reason because of this parameter setting of mine

```
Cesium.ExperimentalFeatures.enableModelExperimental = true
```

**Comment by lilleyse** [comment]
@Criska9527 could you try this out in `main`? The new model implementation was merged earlier this month and we want to make sure you don't see the same issue.
