### ISSUE TITLE
Remove pinned "zip.js" version in `package.json`

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#10712]
https://github.com/CesiumGS/cesium/pull/10694/ pinned zip.js to `2.4` in order to fix https://github.com/CesiumGS/cesium/issues/10684 based on [this recommendation by the zip.js maintainer](https://github.com/gildas-lormeau/zip.js/issues/340#issuecomment-1177329994). Once the package no longer uses `TransformStream`, this workaround should be removed.

**Comment by ggetz** [comment]
An issue with the pinned version of zip reported in https://github.com/CesiumGS/cesium/issues/11526.

**Comment by ramtob** [comment]
@ggetz 
Hi. Is there some working plan when this issue will be dealt with?

**Comment by jjhembd** [comment]
Since #11598, we have updated the minimum Node version to 18, which [now supports TransformStream](https://github.com/nodejs/node/pull/42225). With Node 18 or higher installed, the test in #10684 runs through without error.

I think we can update zip now. @ggetz or @mramato am I missing anything?

**Comment by mramato** [comment]
@jjhembd No, that sounds reasonable to me.

**Comment by ggetz** [comment]
Sounds good to me @jjhembd.
