### ISSUE TITLE
picking cache is not invalidated when camera.setView was used

### ISSUE THREAD

**Issue by anne-gropler** [CesiumGS/cesium#10728]
Behaviour I'd expect: When changing the camera, the picking cache is invalidated so that the new depth values are used.

Behaviour I currently see: It seems that even after calling `setView` on the camera, the `pickPosition` is still getting old depth values.

How to use the Sandcastle:

The blue/green canvas lines mark the center of the screen.

After loading, use Double Click on a point cloud point (e.g., the roof). This will add 3 point entities:
1. Red marks the point picked from the center of the screen from the current camera position/orientation.
2. Green marks the point picked from the current mouse position from the current camera position/orientation.
3. Blue marks the point picked from the center of the screen from a camera positioned at the green point looking towards earth center.

However, the blue point is placed exactly on the same spot as the red point (which I consider a bug).

Now click the button to remove all point entities. Now use **Shift** + Double Click on a point cloud point (e.g., the roof again). Now the red point is visible at the screen center, because the blue point is placed somewhere on the ground (or within the Earth). Blue should be exactly below green ("dropped a perpendicular").

The difference between DoubleClick and Shift+DoubleClick is that when pressing Shift, the code manually updates the picking (and thus invalidating the picking cache) after the camera is positioned at the green mark.

My initial goal was that the blue point is positioned somewhere in the church (church ground), but I guess it misses a picked point because of low precision, points not being rendered yet, etc. However, having to manually update the picking cache is something that a user shouldn't be required to do; it's not part of the public API.

Sandcastle example:
https://sandcastle.cesium.com/#c=vViNb9o4FP9XfD2dGiQaCCSFfuo6yla0rkOFrjoJqQqJKb4zduQ4dGzq/37PdhJICB3TdFdpGsn7+r3n9+UEnMUSLQl+wQJdIIZfUA/HJFnYX/Q7a3IQ6OceZ9InDIvJQR19nzCEJBYC3gwFX5IQi9NMMBDYl/iRCxqODYtVq0/Ya+1swias0RhywiTqUZ6EaLpCID+z0RCDOnRFKWZ11OM0WUyJjx4YWWIRE7lC93zKJQlidOtPbTQKfMYIe1YKrij+22eh4GgseBBwShA8ok8AgqAe4YEvKMH2hAXaV0kojrEsOmv+a1+PDdHSDiaC5k4NOLvHMU9EgO2Z4IurGNgGoeUcuy1HuYdQpPzSbo3mfgjgTk2cEPKlxCzxJeHsFEmR4Lp5z7hY+DTnnvk0NqTXLF7mYOw4wAzbkSALIiEise2HoZU6YsI6ApcDP5YUK9qYczr1xbtESs4spfFQ4AVfYoSZBBU4PtR2ZgkLFCpkqP2UaNUy5Kn9TMo2fHBMljILQCdsT/vPHEmOCAM9PoVYwaGC4T1hqFhryZ6/wMIfptJlELmenfxGYSGqgWaxQURlvJVaDHEsCUuPbDNRfCHhl8/almFEyHWbTsd17WPXdVyv7bj1jNJqeU3PsV2n2emeOE7Ta+Uk1zvx3FbTbnfcTtd1221DqKUMXBCI+bb5G6xzZUhkML/ncAyZPg/MH3fa7W7Ta7ZPOl4nt3TUtFud4+Nmx/Ha3fZJt3uck47tVtcBXN2O5zabza63CQLyDyFIQxXYt+JfCHxEgn9GMpnNrIDCz/4SvKijhQ/ZT+nqIQqhKIdAAB96fjDH6YGYyoyhc2CWKS8VaBb3Frg8kaUTZEs/tsEiWHskoZyjBlKhfovvBpPnuUwZwWftSYZEuYHDIRbXOAJtF8WMUdQ8BEXQJiHVPzJDVlFNLU2tKhM65VdFl827LCHVn+4weVfJ35KvmI7IN3yKvHqRxBNJoWfrmJyiVjUVui1fd2/9ZD/eDMb9EntQwXffvy5xhST2pxRrr8ZQRNcklj4LANwd9HSI4fDzaDAefOk/De7eD+4G4782FLymv19NHFFllOxoR4ZQ6DlwMoJHWEDgoNovLksa6qbJZurL7U211SqTeZ9Zn+0Pc7rUZp4iw2InWsAqqTRJoYsGjK8d3J146wLLA2J0KnS/pUEJ8QxOOLRKims5RmWXQ9N+8QWzDq9JCENJojmRMENXcg6AD7NgCSwTwdawM1HKn63DGU9g5oJAnPJvUsvWz3Z6vE8dVFXBRg047UJGvlUCbxTAh/t+/67AHOxVJr+Q/q9Z29XRqYrLz2V+SUUh9asSv9Jk1hcbDTVU4YAxMgNTTXP9ZKTyia53L5WoSK1JikVgFPIXBhkWxhsHb7RcVA3jQi/mNEynDrgXg0B68JnB0+3RDC2eM2ylkz2vjjTSIRE42Esy58xEk+iHMkmUjs+CEyoAAD3LaEpJFHMS2o8fRl3XfsY8xLDcjhIx8wN8p9fC6qrZts7ws+onykJd29nJqNVCjZR41yiTaI3xDf82ylfoIVopJHgcp5aSqL5jh6rtAmvEtXqDVGnJ0VaubKWlrZz+GVNhtfperN08MbTFTZo6eXCjolZ3bQ2tn14btleGVm2NsNLGfnvDrs3hrb754/Xhzf757vahv8Uf7Llp/OIWsd4jNjYJVB26X1kmWqVtYp99olVYKBAG8fIo1vO0nEsk1oM5neeH+faw0ZvTjqpg710kxeaaB+PniqWkJKdsFVCJsbqetFN54agqGUXQFPWmcwPDhar36j4SJfJK27Hy6wdn1zyBvOmp2rfyOapl4ZJoPKi+o+Qn+VpH+/5NWJouoxLO8SrC9m3//fjp+vPDu9v+U+920PtYuND/b46p7w3/rV/1rGo+4tWUw5jXvJ94SGYEfBrdDN6PFYKD+sHkIL8gmaM/j+WK4sssD/4ki4gLqT69WLbdkHgRUZhucWOaQD1IO4jjrNrOG5ui5yFZIhJeVHyuglD5cQyUWUJ1r5scZEJzirQSIH47IizEX6EPnm2sFv4USjKR+Ay9mCboNJt/nMGFVjwTIDezn0cUz6C/Am3Khf4YxmBmniHzdDTlUvIFSEdwy+UUtuzfnaDjTYOcQ/Kokqzfe6AXQJ835jRDvtwf+VzfdHdD1yZ2ITd+FYBNAVpOF6nubQYjmUNf5tAbcFRbp0a5/rDxeYkF9VdKYu5c3pqXtm2D685ltaQ035q0kTX9Xw

Browser: Firefox, Chrome

Operating System: Windows

**Comment by ggetz** [comment]
Thanks for the detailed write-up @anne-gropler!

@lilleyse Can you confirm this behavior is unexpected? And is it related to any other recently reported `pickPosition` issues, such as  https://github.com/CesiumGS/cesium/issues/9846?

**Comment by anne-gropler** [comment]
I forgot to mention that we use Cesium 1.92, I hope this helps tracking down the bug, in case you confirm that this is unexpected behaviour.

**Comment by lilleyse** [comment]
This is expected behavior, at least with how `pickPosition` currently works.

`pickPosition` gets the position from the depth buffer of the last rendered frame, so you'd need to manually render the scene if you want to get a new value.

```js
const firstPosition = scene.pickPosition(screenPosition);
camera.setView(...); // set camera to new position
scene.render();
const secondPosition = scene.pickPosition(screenPosition);
camera.setView(...); // set camera back
```

The danger of doing this with 3D Tiles is that not all the tiles will be loaded during the second render and you'll get different results depending on where the camera is and what tiles are currently loaded.

[`pickFromRayMostDetailed`](https://github.com/CesiumGS/cesium/blob/4237eef463198f6ed8ee4a7abe8a06eb48d17213/Source/Scene/Scene.js#L4123-L4147) may be helpful here? Though it's also private API.

**Comment by anne-gropler** [comment]
I guess that `pickFromRayMostDetailed` won't be public soon. But we really rely on it currently, so I just hope it will make it to public API.
I'll close this issue because the original issue was answered as "expected behaviour", and my underlying problem is fixed using `pickFromRayMostDetailed ` 👍
