### ISSUE TITLE
The color properties of multiple ModelGraphics become consistent

### ISSUE THREAD

**Issue by 627496967** [CesiumGS/cesium#10722]
Use Viewer.entities.add () to add multiple ModelGraphics and set different color properties. The last added model color affects the previously created model color.

Cesium Version: 1.96.0
browser: Google Chrome 104.0.5112.102

**Comment by j9liu** [comment]
Hi @627496967,

Is this the same bug as #10656? We have a fix for that coming in the CesiumJS 1.97 release, so I'm closing this issue to keep things tidy. Please feel free to reopen this issue if I've misunderstood your report. Thanks!
