### ISSUE TITLE
PolylineVolume : 2D shape not always extruding along strip line on sharp turns

### ISSUE THREAD

**Issue by matusa96** [CesiumGS/cesium#10733]
When using PolylineVolume with a strip line that has sharp turns (<90°), the strip line goes outside the wrapping 2D shape (see attachment) at the turning points, whereas the expected behavior is that the strip line always remain inside the wrapping 2D shape, even (and especially) at the turning points.

The bug is best highlighted when superposing the PolylineVolume and a Polyline geometry having the same coordinates than the strip line of the PolylineVolume.

Sandcastle example:

https://sandcastle.cesium.com/#c=5VVLj9owEP4ro5xYKTWPlqoFFlWFai+0uyrbPXTDwSRTsOrYke3Awor/XpuQEJJUale9NUqi+Jv55uGZcUIptIFwH3O4hsdAADy7FwCLBhB4kQzTGIUJPD+DBY3RCSbfP8/gBmWMRjHUA7iTfMeZQHiQ3FIKwgaVZlI4Tpd0TvDBr3laKUTxUT7VPN04ASzlE2yZWcMSN8gxglAqYU0DFRHI1DjXBTU5xZKFMsgdOYFmxkajSxhASJWRK0WTNQun6AKx8sezHODV+w7p+GXkda8CXK4aCG8rQLfjrgrrzd+4WRTfh+JLr2mCtexQMyp61aT69QDq0AuVXkRrSiir8/0uOTbD19tvX6afpkWlAWJqUDHKL3LWkrNoIrlUF7CzVscA1GpJ7eZ0fOj1+77dY+j23i0uQj2UVoeGME8tOACjUqyi9UjOHrPb+q0nf/jdrCiMZuV+z0dlbmcxgcZR+K+G4B/2RN4Q1Rr9SU9sWWTWA+g54KKigVgMAxGI8Hj4bhhuUdnjV+AWJnZU05g8HLFW4IXH9UQKQ20VVeBdDXNeRA2dy1SFeKdkzDRaEyf6xJ7n00JMuKRRy53xjpy5I2e2JjSKWjVrJd29lPG9bFYJhOd7gTd0ieUPwEibHcdxvhMfWJxIZSBVvEVI22CccFsj3V6m4U80JNT6anhitsvUUcQ2tumvGzYCQk61tpIfKedztrc9Px61rX6N6tJnYnVrf0Wc7pzaujueZSAhZNS2y2amkZIvqSpZzjR+AQ

Browser: Chrome

Operating System: windows 10

![PolylineVolume_sideView](https://user-images.githubusercontent.com/112341180/187087964-3c62fce6-f34f-4fd7-8336-f24933f4ce54.png)

![PolylineVolume_viewFromAbove](https://user-images.githubusercontent.com/112341180/187087960-fcab926c-5811-422a-b0c6-46e0bcb3de66.png)

**Comment by jjhembd** [comment]
Hi @matusa96, are you looking for behavior more similar to `stroke-linejoin="round"` in SVG? See this [picture on MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin#round). Our `ROUNDED` cornerType behaves a little differently, as you noticed.

Let us know if `MITERED` cornerType will work for your case.

**Comment by matusa96** [comment]
Hi @jjhembd,
unfortunately the MITERED cornerType will not work for my case as i am requested to display a 3D geobuffer around a polyline that behaves like the stroke-linejoin="round" you pointed out (actually the same kind of buffer operators with rounded corners that are produced by spatial analysis librairies like ESRI or Turf.js, but....i need it in 3D....:)

Thanks for you answer anyway, now i know that i have to compute the shape by my own and probably render it with cesium with a combinaison of polygons and walls
