### ISSUE TITLE
Last model color applies to all models

### ISSUE THREAD

**Issue by pikvic** [CesiumGS/cesium#10730]
[Sandcastle example](https://sandcastle.cesium.com/#c=tVdZjyI3EP4rDk+NRMwxsLshzCgcm2yUjLIZyCpSiFamu6CtcdvIds8wWc1/T9nuhuaIIkLgyS7b9R1dPoiVNJY8cXgGTW6JhGcyBsPzjH7ysWhei31/rKRlXIKe1xrky1wSwuVSjdSmT5ZMGGi4kAEBseVK/igTHjOr9N5oyhL1bPrE6ryMqFwkQ8kzZmEbf61/O5dzucylz0ViDTh8rxIQUa5Fg6TAV6mtBxqBOwVpueVgqIZMPcFQiCikIST2GtfKcJ/utlQ4Ztpii8kbutQqm8BKA5jILSHk63bnhrbedrtv2t80Qqjbpa1e6+Zt600RCDxc20EdAnUuReq++0ekHVoKLOFytcO6ZzalVj1gmEkTtW96e+S4jVOc3KrEtBLiIJSuD6rhQ4D56JY/4PyowG2EjA2fpAqkNMdPwvYdn2mktFQ6MzQ9SPhrjt9YS5xe2FLaWDqw1qX8kyCd/xularIvrhdEOCw2liTRl7BUsgxL2NXnfub+IUaFdL/aKYYzV+d9UmQlmJFX0+IEjvslzz7yDYgp/wtB2513u1G2caPTmAkc6bTwtx2LlXA7sixK1/P1+LBasKi16fVGo+FwMqmH+a9+3Wv1owYfOpca0fkXJzpXs+KEskKJ1Sx+hOR9+aWDVD+jUE09HepNrGxt7+LD+wlOfXW1WVTm2gkxOO8Pl6KQYGFj+2ReG3Ida7a0eJYWTshwdOJxWZ56UX0nvHoCljGszxqlzSnL1gImzLKm52eagRhCFK3P2KQrsdiCuV8PzaCtsh+c2BrTOEF5opWEK/L1+avtI8rt3nmMf9Aqlwn5BCmPxXWoB4gCYb93RP8c6h+UJfjVyIgJoZS8ou0Fwn7v2Ppzq+Wei0cy03n8eEXuDsRjHPYv8n76yKWEhIxThkeC9Q+eqylgpfOfsXkR7QmSVWSssrUGY5C/J3IV7h5qh3TCfbv8zzp+mv3eqco4cwvwJYm+Ko7m71FTrmECNjxKqcnXa6WtGTHDTVQc/CYGCfVKCkKeucSHKsVrQ9uKHc6QWcoNWWh8xuJ7OVFgiMS9WiQmPjH5TfIn0IYJvDW3Opw+JGPmtV3C0g604vIt7Iw7jpy9lf/0D6wpk0nMjMVzDG/2mVJiwfQ9yDwqLja3sNaozWvbl1JINDD2RcBdmf87nnlj8NKOUIIFlID6THOBhQKWxsaUFAbN6tJBwp8IT25P/P0gsWDG4MgyF/7Wn9fuBk2cf7RUKP/6+wW/hmAvblravvs5BCmlgyZ2T6+0QfFB5r8B)

Browser:
Google Chrome 104.0.5112.102
Operating System:
Windows 10

**Comment by j9liu** [comment]
Hi @pikvic,

This is the same bug as #10656 and #10722. We have a fix for that coming in the CesiumJS 1.97 release, so I'm closing this issue to keep things tidy. Thanks!
