### ISSUE TITLE
Request render mode was broken in v1.96

### ISSUE THREAD

**Issue by azurre** [CesiumGS/cesium#10756]
Cesium ignore the request render mode after adding any entity. 

Steps to reproduce: 
1. Create a default viewer with request render mode on. 
2. Add any entity

Expected behavior:
Idle shouldn't trigger re-rendering

Actual behavior:
After adding any entity re-rendering triggered infinitely

Affected versions: 1.96+

Sandcastle example: [Sandcastle](https://sandcastle.cesium.com/#c=bZHBbtswDIZfhfClDuDKyXbL3GBbup02bEiKnnxRJCYVJpMdJSVIi777ZKdes64EZFjUx5/iL8MUIuwdHlDgCggPsMTgUqduh1zZFmbYL5midoTSFhU8Cv5OGOIKyaJ8Z4tziJLwafKhpZOYCgYJlcVN2q3v+PBVdIfhJ8oaDZPNvfqCjLe01mSNDtGj0tbeMPuNls8pRqby4pO1gBRdPF5UsE1komOCcgKPLUGO524D4jD0CuXzUR/OzqEtXAgJ88Vf8oImatr5fPEzug/DLNaRjhjmoxerkVZb4e4ad4IYysvZbFrBu7wuZ9P8fT+dVP9qdVlFnPZ/hZbsWdTqy/UL93T6Haw7G+iBubvh8tV4PZTJoiraYuDHBdCEePS4GIU/uu6eJUISXypVR+zufT9TvUnmF0ZlQhg7NvV5aWPdPtt29cbDg/E6hHyyTd6v3UO2dNHUmf+v1LPOHu5+7FG8PvbY3Wzx7ZRUSjV13r5dGU/P/0r5Dw)

Browser: Chrome

Operating System: Windows, MacOS

**Comment by ggetz** [comment]
Thanks for the report @azurre. I can replicate the issue and can confirm its a regression.

**Comment by rodrigonzalz** [comment]
Will this make it for 1.98? Have been facing this issue, we can't update from 1.95 because of it.
