### ISSUE TITLE
3dtiles  gltf1.0 贴图丢失

### ISSUE THREAD

**Issue by dgjkl** [CesiumGS/cesium#10768]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
最新1.97版本，3dtiles  gltf1.0 贴图丢失。1.91版本没有出现问题。
尝试调试修改：
修改updateVersion.js：
将 const baseColorTextureNames = ["u_tex", "u_diffuse"];  修改为：const baseColorTextureNames = ["u_tex", "u_diffuse","u_diffuseTex"];

但是这样修改，贴图是出来了，但是贴图显示是乱的，并且有黑块。

因此请教大家，怎么修改？

**Comment by ggetz** [comment]
Hello @dgjkl.

We [dropped support for glTF 1.0 in Cesium 1.97](https://community.cesium.com/t/dropping-support-for-gltf-1-0/19969). Please use that thread to get help updating your model. 

Thanks!
