### ISSUE TITLE
Scene crash when GLTF has no `nodes` attribute

### ISSUE THREAD

**Issue by ilyaly** [CesiumGS/cesium#10769]
When loading Cesium3DTileset tile that has empty nodes list (empty in this case means that no `nodes` attribute exist in corresponding GLTFs), scene crashes with error:

![image](https://user-images.githubusercontent.com/30498863/189100052-1e821375-0204-40eb-8dc6-800fbcc46f0a.png)

This error occurs because `gltf.nodes.length` is accessed without checking if it exists, which leads to scene crash when it does not exist.

As attribute  `nodes`  is [not required](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_gltf_nodes) according to GLTF 2.0. specification, the GTLF models without this attribute considered valid and should not lead to scene crash. 

The fix is quite simple, it is required to check if `gltf.nodes` exist in the `loadNodes()` method of the `GltfLoader()` :

```Javascript
if (!defined(gltf.nodes)) {
    return [];
 }
```

https://github.com/CesiumGS/cesium/blob/ba2835b96d46274b4c87a1e094eb8e521ac814ac/Source/Scene/GltfLoader.js#L2133

**Comment by ilyaly** [comment]
Attaching sample tileset.

[SampleTileset_EmptyNodes.zip](https://github.com/CesiumGS/cesium/files/9526091/SampleTileset_EmptyNodes.zip)

**Comment by lilleyse** [comment]
Thanks @ilyaly. That looks like the right fix to me. Would you like to open a PR?

**Comment by ilyaly** [comment]
@lilleyse , thanks for the reply, here it is: https://github.com/CesiumGS/cesium/pull/10770

**Comment by ilyaly** [comment]
@lilleyse , thanks for reviewing the issue. Here is PR: https://github.com/CesiumGS/cesium/pull/10770
