### ISSUE TITLE
Why Load geojson with Cesium3DTileset in 2d is not same as GeoJsonDataSource?

### ISSUE THREAD

**Issue by libofei2004** [CesiumGS/cesium#10777]
I load a geojson with dataSources in 2d like this way:
viewer.dataSources.add(
					  Cesium.GeoJsonDataSource.load(
					  "../../Cesium-1.97/p1.json",				  
					  {
						stroke: Cesium.Color.HOTPINK,
						fill: Cesium.Color.PINK.withAlpha(0.5),
						strokeWidth: 3
					  }
					)
				);
It  seems like this:
![image](https://user-images.githubusercontent.com/10001548/189539849-5f320935-2418-4bff-8b0c-0f08d09816dc.png)

Then I load the same geojson with Cesium3DTileset in 2d like this way:
const tileset = new Cesium.Cesium3DTileset({
		  url:  "../../Cesium-1.97/tileset.json"
	    });
	    viewer.scene.primitives.add(tileset);
	    tileset.style = new Cesium.Cesium3DTileStyle({
		  color: "rgba(255, 0, 0, 0.8)"
	    });
the tileset.json content is：
{
"asset":{"version":"0.0","tilesetVersion":"1.0"},
"root":{
	"boundingVolume":{
		 "region": [-3.14159,-1.57,3.14159,1.57,0,10000]
		},
	"geometricError":100000,
	"content":{"uri":"p1.json"}
}
}
The geojson  seems like this, it's bend.
![image](https://user-images.githubusercontent.com/10001548/189539987-1294f926-86c1-43ba-9f38-a20d16ad456c.png)

In 3d mode, they looks the same,but in 2d mode,they are different, why?
How to make geojson with Cesium3DTileset looks the same as GeoJsonDataSource?

**Comment by libofei2004** [comment]
I load a geojson with dataSources in 2d like this way:
viewer.dataSources.add(
					  Cesium.GeoJsonDataSource.load(
					  "../../Cesium-1.97/p1.json",				  
					  {
						stroke: Cesium.Color.HOTPINK,
						fill: Cesium.Color.PINK.withAlpha(0.5),
						strokeWidth: 3
					  }
					)
				);
It  seems like this:
![image](https://user-images.githubusercontent.com/10001548/189539849-5f320935-2418-4bff-8b0c-0f08d09816dc.png)

Then I load the same geojson with Cesium3DTileset in 2d like this way:
const tileset = new Cesium.Cesium3DTileset({
		  url:  "../../Cesium-1.97/tileset.json"
	    });
	    viewer.scene.primitives.add(tileset);
	    tileset.style = new Cesium.Cesium3DTileStyle({
		  color: "rgba(255, 0, 0, 0.8)"
	    });
the tileset.json content is：
{
"asset":{"version":"0.0","tilesetVersion":"1.0"},
"root":{
	"boundingVolume":{
		 "region": [-3.14159,-1.57,3.14159,1.57,0,10000]
		},
	"geometricError":100000,
	"content":{"uri":"p1.json"}
}
}
The geojson  seems like this, it's bend.
![image](https://user-images.githubusercontent.com/10001548/189539987-1294f926-86c1-43ba-9f38-a20d16ad456c.png)

In 3d mode, they looks the same,but in 2d mode,they are different, why?
How to make geojson with Cesium3DTileset looks the same as GeoJsonDataSource?

**Comment by ggetz** [comment]
So the root of the difference in curvature is likely due to [a difference in the arc type](https://github.com/CesiumGS/cesium/issues/4000) used in either case, which will determine how a 3D line is projected into 2D space. Though its odd that `Cesium3dTileset` and `DataSource` are not consistant. My guess is they both should be using Rhumb lines and result in a "straight line" in 2D. 

@lilleyse Can you confirm?

**Comment by lilleyse** [comment]
[`GeoJsonLoader`](https://github.com/CesiumGS/cesium/blob/fd5ea748e3b86c95e227985e32a562b5185ac7ba/Source/Scene/Model/GeoJsonLoader.js#L23-L42) (used by 3D Tiles) uses geodesic lines for performance reasons to avoid subsampling the geometry. Generally unless you have a tileset with the `MAXAR_content_geojson` extension you should be using `GeoJsonDataSource` which is a much more complete GeoJson implementation.

**Comment by libofei2004** [comment]
@lilleyse  I use a tileset for drawing geojson is indeed for good performance，drawing by tileset is much more efficient than GeoJsonDataSource.

**Comment by libofei2004** [comment]
@lilleyse  I use a tileset for drawing geojson is indeed for good performance，drawing by tileset is much more efficient than GeoJsonDataSource.
