### ISSUE TITLE
KML with unsupported feature will cause Cesium to not load supported features, run out of memory

### ISSUE THREAD

**Issue by robert-irving-snc** [CesiumGS/cesium#10774]
Sandcastle example:

https://github.com/robert-irving-snc/cesium/tree/kml-sectional-chart-issue
Run the KML sample on my cesium fork branch and select the 'KML Samples with Sectional Charts' option from drop down. Or just grab the KmlSamplesWithSectionalCharts.kml file from the branch, and try to load it as a Cesium.KmlDataSource

Browser:
Chrome

Operating System:
Windows

This KML file loads fine in Google Earth. I understand that Cesium may not want to support the way this KML is used to load Imagery, but would be better to ignore that instead of displaying numerous errors and crashing.

**Comment by ggetz** [comment]
Hi @robert-irving-snc. While we do ignore a few unsupported features, I think you are also running into a different issue here which is ultimately leading to performance issues. I think the root of that issue is a lot of concurrent network requests. Are you seeing the issue just in Chrome, or in other browsers as well?

There is a PR open to properly handle KML partial updates - https://github.com/CesiumGS/cesium/pull/9647 - which needs a final review. Would you be able to give this a test in that branch?

**Comment by robert-irving-snc** [comment]
Hey @ggetz I think you are right that the issue is lots of network requests. I believe if the KML <Region> feature was implemented then the network requests would be limited to the supported area defined in the KML, but since it's not Cesium seems to be trying to request global coverage from these charts.

I'll try it out on that branch.

**Comment by robert-irving-snc** [comment]
@ggetz I pulled in the changes from that PR to test. I was still able to get both Chrome and Edge to crash. I also tested with Firefox, which did not crash, or show the flood of error messages, but also didn't fully load all of the KML Samples from the test .kml file. 

I read through the KML docs on <Region>'s some more: https://developers.google.com/kml/documentation/regions
And it seems the issue is that this sample data is following the guidelines for creating a 'super-overlay' described in this link. In Google Earth the amount of queries made against the sectional charts server will be limited by the user's view and the Region statements, but if the Region's are ignored then Cesium just tries to download everything at once, all zoom levels of imagery. 

With that in mind it really seems like a network link that has a <Region> and <viewRefreshMode>onRegion</viewRefreshMode> should be skipped over to avoid this issue.

**Comment by robert-irving-snc** [comment]
@ggetz I found that checking for viewRefreshMode==="onRegion" in processNetworkLink and return-ing from that gets the desired behavior, no flood of queries and the other kml placemarks load as expected. 

https://github.com/robert-irving-snc/cesium/commit/77ea7a93d2d3410dd59a6f549f2c3fc4345c5e5a

Please let me know if this would be acceptable and I'll submit a PR.

**Comment by ggetz** [comment]
Thank you for investigating @robert-irving-snc! I think your fix works great until the feature is entirely supported. We'd be happy to review the PR.

Just to cross link, the request to support this KML is documented in https://github.com/CesiumGS/cesium/issues/873.
