### ISSUE TITLE
How can I set esbuild properties that I can rewrite some class ?

### ISSUE THREAD

**Issue by Lemonjay** [CesiumGS/cesium#10788]
![image](https://user-images.githubusercontent.com/9245295/190082031-d5721c5f-be47-44c4-94cb-674aa0e129b9.png)

**Comment by ggetz** [comment]
Hi @Lemonjay. We don't support re-writing parts of the CesiumJS library at runtime. 

If you run a local fork with `npm start`, the local server should watch for changes in the source code and automatically rebuild.

**Comment by Lemonjay** [comment]
Thanks @ggetz , but sometimes , I need rewrite some class. Is there any way that I can rewrite ?

**Comment by ggetz** [comment]
Hi @Lemonjay, I would suggest forking cesium and rewriting the classes in the source code. Re-writing libraries at runtime in general is not commonly supported as far as I know.
