### ISSUE TITLE
mipmap will be lost when use KHR_texture_transform in Cesium

### ISSUE THREAD

**Issue by yuz1** [CesiumGS/cesium#10787]
[correct.zip](https://github.com/CesiumGS/cesium/files/9562204/correct.zip) without 'KHR_texture_transform'

three.js
![1_threejs](https://user-images.githubusercontent.com/25155589/190048233-b540edc0-e007-4ce4-a342-0312b790320b.png)
babylon.js
![1_babylon](https://user-images.githubusercontent.com/25155589/190048235-2ac477fb-83f1-419e-888c-84412086d519.png)
cesium
![1_cesium](https://user-images.githubusercontent.com/25155589/190048237-b7f3e7ae-b5ec-4ce3-9fdf-a0a451b2fe0a.png)

[wrong.zip](https://github.com/CesiumGS/cesium/files/9562205/wrong.zip) with 'KHR_texture_transform'
three.js
![2_threejs](https://user-images.githubusercontent.com/25155589/190048274-fa361a25-c5da-4c0d-b098-69ece4dd9b99.png)
babylon.js
![2_babylon](https://user-images.githubusercontent.com/25155589/190048262-f8c0e970-7020-4d42-9938-55ad1eb379f0.png)
cesium
![2_cesium](https://user-images.githubusercontent.com/25155589/190048268-6cdc2603-d995-45d7-bcef-b7396d953ea7.png)

**Comment by lilleyse** [comment]
It looks like there's a special case for `KHR_texture_transform` that originates from https://github.com/CesiumGS/cesium/pull/7549/commits/47071d34dfaddd3fd52c2e9c4ef75fb0359eb510.

I'm not sure if the special case is needed. If you would like to open a PR to remove it we'd be happy to merge it.

https://github.com/CesiumGS/cesium/blob/30762131d119256348869b704becefab94363bb5/Source/Scene/GltfLoaderUtil.js#L106-L125

**Comment by jjhembd** [comment]
Also reported in #11401. See that issue for some additional test datasets.
