### ISSUE TITLE
How to use 'removePragmas' in 'import' mode

### ISSUE THREAD

**Issue by huoxiaoliang** [CesiumGS/cesium#10798]
How to remove warnings in 'import' mode？

**Comment by ggetz** [comment]
Hi @huoxiaoliang, this will depend on how you are importing CesiumJS and any build tools you are using. For example, if you are using webpack, [this is how we recommend you remove pragmas](https://github.com/CesiumGS/cesium-webpack-example#removing-pragmas).

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.
