### ISSUE TITLE
trackedEntity with CLAMP_TO_GROUND is not tracked

### ISSUE THREAD

**Issue by kurdupovk** [CesiumGS/cesium#10804]
Hello!

Today I have updated my Cesium version from **1.95.0** to **1.97.0**.
I found that camera does not follow anymore the **trackedEntity** with _heightReference: Cesium.HeightReference.CLAMP_TO_GROUND_.
It worked perfectly in 1.95.0, but it is broken at least in 1.97.0, I did not check 1.96.0.

Here is the default [Interpolation example](https://sandcastle.cesium.com/#c=zVh5b9s2FP8qhP+SV1W2c61xkmJekrUZnNiI3RbDXAS0RNtEKFIgKTtpke++x0NX4iAphmE1UpkW38H3eycbC640WlOyIRKdIE426JQomqfRZ/sumLVi+/tUcI0pJ3LWCtH3GUeI8oX4Xdz10QIzRULU6ZxRheeMoAu3gzY0WRJtaBVhJNZU8Aue0BhrIbewlUQg2lNZ3pXIWTLgNMWa9JGWueVC59xyYbsBXMoQayIlHHMsxZomBLR4a2JJgPuLkCyZOpKgHc74Q/toxme80/HCGF2uNOVLNMeKJAiOoldwsJyjTChqtMy4AytSMeEkWjIxJxGx3MOC+cQesik5IZlewfGUpVACBMNCoTmB78Sq8WdHCeCRZQTLaKsyK2kKggZLoFba29PUOiHaypSYJyJFPE/n4GBFwKiFkCgGuKjShGskicqZVqDLQ3WJ9SpSRF9b1ivLOQHGYLddEz4XOU8UEgskchBM05xZLyBNUzLjsY0rpbHUcDAv+c+cUczPwBHRQorULAITcXax0+3th2gH/uCrd9A2ygopItsqBCfJhABNogIbKEZbaFa7B137XQvnii1oz3hhySW+Ne6VpEgBqhB2yCXAJwEuY0/liJiJ+DaymqawAceya/Oeg+SjJ4QiK+lE9hxZnEsJvniNRPsE1yxJBclp+S4ajkbjm8l0ND6CFBkKAM6bQ3jySBJ4TNOMUZv4vW49cOAcDHIdaVH3rHN5KaWgir4JkU5F4OC3dhbwfoColQA5wkUgxlTGIE+iDGuIdw41AtJijeW9SYsVMSlkYnGRc1cKYpFmuSanwMcM4x82RQMAJ0RwrhAEJzRXbVeTXMBkUmRE6vtmQZvgNGMkGftEHnsiCzGyWREwMJ4CV/cIvo5PTByZ1ZsTtLfvNRQ6jFrMVeUEmzZaXLv3AXViC3LtXPtiDJtPFcfmQ8vVs9FsNpvqimpVixGQCSvMd13ukaUkpNIJeKI3Hkv0C+pF+/C0JsVCBd7YdnkUQL5O7koG1NQnhHVwOLlrFJWgDaz73S5I6v26323aUfjQAmQ9FxgMw9I0F2OGtNMZMCiorsRDqGWCQl0zDiU4XiFludGGoKUPx8jx+TiGxAOBRBlNwffi4IWafrkKqy2Q30clKbyhd4RN6DdoT+/C6nUsmKha0Kn5FU2vB1eT8eD6/GpaoxS5Nql0uoXhr/PhcPTlKe0XmuhVH+2WOw9+9eAgfDAPSXQOSVaACRsPLjNPXVr50gAA3FcxU0JfFOBaND2Tjm97vZ2o1+seHO6GkDVR9/Bw791eL0TdqFu2jUGsc8zYfeGpSnehyJ/k5HnXVJ3N0+I1pgzPKTM/tHD9GkOygY+IXGOGsHIvmy3KxkCduV/PL1OJL7wAcIOfS4K/HcLPEFbBYzO4/yiRTWHs22fpKLv4ar6cbZ8Use3Uo5yUyNvZZmtIOsZBroWZgmKHr3eukBRQ8sW7GGhKZ6ZiTVLYt0jUSBtAfCbQKwCdUbVfFs4yE8tjDAV2o4zjRhnD0EVSkRBmfCNJBtOGGTrqrkeOoEyoXNI+mrWiqOPyHqoc7lgS1XFyB1T61Q0sYSyaw1DqmFMK42CejquEPNjzW665XJMFgV4bkzLNPjbfR6fDweX4Zjq6+XA9+nR1ZnOptHCyEht7euhfKxNaUG4ov0W2XbpKk0DooR7MWqaqwxqi3cCsLM6GrbQUwBAsd5j3CgMgMyTFrOGFsWD3RsMHJjaXnqB0Qxl1MB5uxmJjpt5u1CvjLn6pqDwU5XrjSkrPDU8P9fl4kCRonmttskfY9KxQMP3EDbAwbiRiAwwTKPMxVprZBndGFhiGjakQbI7l71YMXCzMDQNNgefM8MC1omz6gW+2xaQhcXxLkvOiOsAYQhYAR3JUI/JTyNbSHj7J248EOhVfjqmOV3ZyCrrhM5387WG3bZusweLHAFFwB3kMxlYUJobw/0ZgW89uwhC+QNLbr0igoxct/QXwrHGNmq4Q1bY+qVehB0UglnihfwRBp+rxobCpnXMBo+6dHSD8lRRGUztK2J6SCd9GTE2KnjngJeG5BdS3jDJJNQxBprxd1EX10RCcCVPxIIPme+cvtGVRg/LM3Un6T+1zH2dOVJRkc39raBhlto0ENRbUNMdNhFUh2kIyYEvoE3qVltXEHbtx6hr7QzHM1YaT8JV44KW0lxxT+rhIoeD9DODsvwacOkmZKoVBlT3/AWofiUyp/tlA2/mRiPIm/AuYvtrnrNVQZPJx1nIX/1bYmrUsc/EPoWOl7xl5X0j8jaaZkBpmERbAIKIJNHbou6ozz6GKwOVcqUL9cafOepzQNaLJyZb/NkMxw0rBziJndjaZtd4fd4D+CSsTtjSP1kQyfG/IVr33Q/cyiqLjDvzczqld9QGWwpJqbwseTSm19T8) with only _heightReference: Cesium.HeightReference.CLAMP_TO_GROUND_ property added.

Just click on **View AirCraft**. The camera does not follow Airplane and it always sticks to the position.

Is it a bug?

**Comment by ggetz** [comment]
Thanks for the report @kurdupovk. I can replicate the issue.

@sanjeetsuhag Could this be related to https://github.com/CesiumGS/cesium/pull/10631? If so, we should probably get this fixed for the next release.
