### ISSUE TITLE
Update glTF supported extensions list

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#10809]
The `Model` documentation doesn't list the full set of supported extensions. The actual full list is [here](https://github.com/CesiumGS/cesium/blob/af9af427446d96d7b67a50dcbf2eb41365cfc53b/Source/Scene/Model/ModelUtility.js#L346-L367).

![image](https://user-images.githubusercontent.com/915398/191852832-1c512c4e-9134-403a-9d45-20602b4fbf01.png)

**Comment by oussamabonnor1** [comment]
@lilleyse a friendly reminder to close this one in case it's no longer needed :)
