### ISSUE TITLE
When globe.translucency.enabled = true, the scene.pickPosition(ev.position) will be return a Incorrect value

### ISSUE THREAD

**Issue by laobel** [CesiumGS/cesium#10806]
Copy the following code to Sandcastle and run it. Click the same location multiple times to return different results.

const viewer = new Cesium.Viewer("cesiumContainer");

viewer.scene.globe.depthTestAgainstTerrain = true;

function test(){
  viewer.scene.globe.translucency.enabled = !viewer.scene.globe.translucency.enabled;
}

let scene = viewer.scene;
let globe = scene.globe;

scene.screenSpaceCameraController.enableCollisionDetection = false;
globe.translucency.frontFaceAlphaByDistance = new Cesium.NearFarScalar(50.0,0.0,100.0,1.0);
globe.translucency.enabled = true;
globe.translucency.frontFaceAlphaByDistance.nearValue = Cesium.Math.clamp(0.3, 0.0, 0.1);
globe.translucency.frontFaceAlphaByDistance.farValue = 1.0;

let handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(movement) {
  var cartesian = viewer.scene.pickPosition(movement.position);
  console.log(cartesian);
  test();
},Cesium.ScreenSpaceEventType.LEFT_CLICK);

**Comment by lilleyse** [comment]
Normally you would also need to set `viewer.scene.pickTranslucentDepth = true;`

But that doesn't seem to be working for the globe, only for other translucent objects.

**Comment by ggetz** [comment]
I think this falls under https://github.com/CesiumGS/cesium/issues/4368. Closing this as a duplicate.
