### ISSUE TITLE
Wrong argument type definition in Matrix multiplyByScale functions

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#10801]
The type of the `scale` parameter is annotated as `Number` in https://github.com/CesiumGS/cesium/blob/fb8158eba1ece2406556fad53fa58403b659f76f/Source/Core/Matrix3.js#L1196 and https://github.com/CesiumGS/cesium/blob/fb8158eba1ece2406556fad53fa58403b659f76f/Source/Core/Matrix2.js#L785 , although it should be `Cartesian3` and `Cartesian2`, respectively. 

This may raise the question of whether it should be `Cartesian4` (instead of `Cartesian3`) at https://github.com/CesiumGS/cesium/blob/fb8158eba1ece2406556fad53fa58403b659f76f/Source/Core/Matrix4.js#L2097 ...

**Comment by javagl** [comment]
I could create a PR for that. But **iff** the type is changed from `Cartesian3` to `Cartesian4` for the `Matrix4`, then this would be a breaking change. (I think it _should_ be, for consistency, but am not sure about the trade-offs here...)

**Comment by lilleyse** [comment]
`Cartesian3` is fine for `Matrix4` since scale is only expected to apply to the top-left 3x3 portion of the matrix.

**Comment by jjhembd** [comment]
A little more context for non-graphics people who come across this thread:

We are using `Matrix4` to transform [homogeneous coordinates](https://en.wikipedia.org/wiki/Homogeneous_coordinates). The scaling matrix in this case is usually:

$$ {\left\lbrack \matrix{s_x & 0 & 0 & 0 \cr 0 & s_y & 0 & 0 \cr 0 & 0 & s_z & 0 \cr 0 & 0 & 0 & 1} \right\rbrack}$$

See [Yan-Bin Jia's course notes](https://faculty.sites.iastate.edu/jia/files/inline-files/homogeneous-transform.pdf), or [this interactive guide](https://wordsandbuttons.online/interactive_guide_to_homogeneous_coordinates.html).

**Comment by javagl** [comment]
The same type of error - just added here to keep track of it: https://github.com/CesiumGS/cesium/blob/fb8158eba1ece2406556fad53fa58403b659f76f/Source/Core/S2Cell.js#L267 

It returns a `string`, not a `BigInt`.
