### ISSUE TITLE
Texture on ellipsoid entity does not work when using SampledPositionProperty as entity position

### ISSUE THREAD

**Issue by calogeromauceri** [CesiumGS/cesium#10812]
The texture on a ellipsoid entity is not rendered when the position of the entity is initialized using SampledPositionProperty (e.g. for animating the object over time).

[Sandcastle example](https://sandcastle.cesium.com/index.html#c=zVVRb9owEP4rJ55SjTrQVnugUG1r9zJVAg20p0iTmxyJV8fObIeunfjvO8cJBMr2sL0MCQuf77777ruzSbWyDjYCn9DADBQ+wS1aUZfsS2OLkkHa7G+1clwoNMng7DpRiUqbSOu4E+lHKUVltcgIImAxVE44gZbxLIt+JgpA8RInkAyWVYEGk8HQGyttyU2rSZf2lhtHv7i6ZGujyzvMDaKNzsfjKzYawtXIr5cj/2GjswYDu+wTaBIBGJ4JMelXs4eNLtrgIbz+FQABSu7QCC4938K5yk7iWDBR5rVhqS7jZXrx3ZkP7FuVt4Vsad0GZSS6XV2WFMnRLbpt5F1aiVKp08ewfuYqR3Lt2O5s7H4+X3xdruaLnuil3giV/4Xo4PCHq0+If0jxv1Q1juGhFjIDDlKQCHrdE9lpkFpX4Aqj67wAvaFxdqLERK1rlXqnoxpDUcet6tW25GUlMetCFkZXaNxz08AQSLNv3D0hz+B8PHrLRrsT2Ri7853ZE9o3+VMtSbk70sTPgMLocCxqY6idKwoJGZ8KITHyyFOf7uqsa4tHJt5EtDdAp28RRb+6QtcHKKs/U3Q7OvvpaaYtqBW1CMOWUOca1oP6rNNVm6wNCr7B9bdK+VRItyCz+1zjIfR5eYnezGDExo1h6xf/NUijr/a06XTrB6ul5SEkPXDsRetypaMjtiRoyHayin+51QdxZS2dqKRoXuPLZqQOExa6ltl7JfxdIhdnatz7HFLvXgNPbjAcJIPrToog1NS6Z4k3YQPwTpSVNg5qIyPGYofUUUpi44c6fUTHUrvr5zTuh04zsQGRzU78VUAqubV0sq6lXIoXenlupjH5vwqVml4Xlc/p4kr+7N2K8c19MDLGpjFtT0c6reUDN0fIvwA)

As a side note, using `CallbackProperty` for setting the position causes the same misbehavior. It seem the texture is only applied when the entity `position` is initialized with a `Cartesian3` object

Browser:
Chrome, Firefox

Operating System:
Windows 10

**Comment by ggetz** [comment]
Thanks for the report @calogeromauceri. This looks like a duplicate with https://github.com/CesiumGS/cesium/issues/9674 (CZML data sources use entities under the hood). I'll close this to keep discussion in one place.
