### ISSUE TITLE
remove clippingplane cause an error

### ISSUE THREAD

**Issue by MingFanZhu** [CesiumGS/cesium#10811]
here is [Sandcastle example](https://sandcastle.cesium.com/#c=pVZNj9s2EP0r0+2hcuLQ3s324o9FF84CNZA2QddtUcQ9cKWxRYQiFZLy1g383zsUJVmy5QRBL5bImcd582aGcqyVdbAT+IwG5qDwGRZoRZGxP8q9aH0Vl+uFVo4LhWZ9NZiu1VrFJfJJZL8bScgKtdTqN7S6MDGyjdHZvbXolkl0fXM7vh3feOiOG4ilyHOhtu8lV2i7gRdt20JLibETWkWf1wogLwET+OAXcBEWBXPXgRtHb1y9jsZsPITy59U1Gw+GtTdthdew9fdaHUKynrMTEikZIhvkYjZGhSw3IhNO7NAyniRl4HbQ8vH6zSqAQxIAhZGTSrsqeFeRycm6dDoM1qqiEwhs5H6lo4pXsFQLZpAn+/dUAGHRY5lLUUWbQpVaQjSAiklVRl2ohKI95ikapBTrc7qGaRtjeCIKX7uuDwv7JRvvLDbQVOO7SpVfuDPin1uGnwoubWOGJqzR2jFnuLIbbbLh0eHkgOWbh19Xy9VftcOgKl+dHcBoBKsUGzlDA4GwIBRVjUu5h1xb4VXBBLgDEqqm8YMFTwQaIqx16n2eE5YroKqXcC4hK2mB00Ct4Wii3HloUt/v1qKBDZIHQBMgSNwEXoTj5qf5b9GtvI/k5Yh8g5D9gzFohJxeYkLOemt4nor4yKe9W859c2abUzebS6G67fR/4vX2MIu/GD1FsU1pyI/HXObDKudXfTme+x0jdWabZTpBGSp6XmGfXH+Jv3a1haBnFT3Ug0ksIZJ0oQmKOp7SY3bKTKLaunQKL1+K1kgFoUI3z08h1JGROBW19H2gy8ntj9cn+rWors3Px7zqcZxAb+FaPVweO4EWFiARGSpLcLpD+xS6idreUN9iL+CG/Ti8bGpbBh0/mnk0dJFMmlBaasP+/Hm5emDPwqX3Mk851eW6i6vIl4+OQRdOCm9ypui1lAH6wrWcD837oVX4arVWiY4L0smxTwWa/SP6b6z2H/vvndbyib52T4VzWtHHnmlFJY4/zuuPRzQoBa+n66T+BjO9w3spoxDXN4CWyKTe0vHBGv5CHKZXwytPbGbdXuJdTfgnkeXaOP+NjBgbOcxIIyre6KmIP/qA1tYpzUZt6CwROxDJvOcvC3Upt5Ysm0LKR/EvUbibjcj/DCo19y33bodG8r13S6/v3oZNxthsRMt+ZKUcQepMZkHEu5D1bFQta+7HQ/4D)
When click button,code means remove current clippingplane,but it dos not work well.
![image](https://user-images.githubusercontent.com/44891554/191892768-be7ae7ec-8d16-49e5-9076-01b4495f6a22.png)
But v1.96 is ok.
![image](https://user-images.githubusercontent.com/44891554/191892820-40acb9de-1039-416d-b6f5-61cae31b863b.png)

**Comment by lilleyse** [comment]
@j9liu would you have a chance to look at this before the release on Monday?

**Comment by j9liu** [comment]
@lilleyse I can try to give it a look later this week, like Wednesday

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/10827
