### ISSUE TITLE
3d tiles can not display in two viewer at the same time

### ISSUE THREAD

**Issue by eclosion** [CesiumGS/cesium#10825]
I create two viewer, they add the same 3d tiles, but the models only display in one of them

![image](https://user-images.githubusercontent.com/13535652/192514941-45724394-8a71-4fbb-bec1-9c7f2d2f42db.png)

Cesium: 1.97

Sandcastle example:
https://sandcastle.cesium.com/#c=xVZ/b9s2EP0qBw8FbMCTHGXFgNgJ1jgBViDdijpogUF/lJbOFheKFEjaqjb4u/dISrLsdBu2bliAwPHx3bvjux9MHMMHhJpJC2qnwdYK9hxrA1bBGsE0MsMcWKaVIRsvcQpGQY2QaWQWUxnHwMAUTBMsEyp7ArX+FTMLtmAW1soWLaHHpDJT0tiAfE/2NypHAdcgsYYlGr4ro+XJ2Xgy75xUZTn9cXlH+N9TCbDZCWEoEZS3O2uVvIINEwan7sxkKNExvOXZE+rh0Wnwq7PvBDmch0z6kIUq8Xmw/yoRAC436lZ9GnptUWV0fsJEVejjXHVCrjpLtFre/3Sf3HmoZHu+Ze5aP6KonufLJC/98dHo9Ih9o4Sq922C2kyp/CQPk9QlQKVRMjTFY4GwXK2AU+XRwq5yHVUJlpF3gSUYniOsG//Zqe0ofXVrLnNVRyHExWl7vPfGcToK6HQ0PTbGsVfcYfKMKvkTqmRIlXiqjkzgxpJnCBh5oaNK85JbvkcTsTwfe2UHPew/Lu8euUC6/tj3DsBOi746r5V8h4aGLsNoo1X5yhDwdT7+/uXld5cTX4rDJJXDPDTfFl0iyf+TSKvBRjSPaux0CeZUbnYyc9L5lZHcOWnHkzAzbboZK1GziMj9YZsJQI7Gctm2XMvfYitluLN/WE47tNIcpW3RPYf7KZDlXG7POVrzdAituM2KZ8Gc8QSmlRDnKGfrMIegDSlwcBJQ17+qKtH4TepkgF4U3KNu/P503e/mJNB5csgKJrdoenXbUMGcu7Le7+nSD9xYqrgeHyWehMm8bUjFDdsJO/X8H08ZPrr4tOFrLgRY6qItaqgLlB7cZlIw0yaSu7l8OXsR5lhByZ4QuIVSaXoRUBrfblP/CjAJa03yAg2Zo/PjHhDcNuc3qpCajKq3xWUb6Rpm0exi3sq34jLsB7dSvDQbklu55yio5mw+cM4NWwukvdN4z/YSpdpj6a6q5JAm5NGPTFjVq4qW0dL7LZW0rrCoI5SO952ybs9dhxU4/9v+j5pJI76K4helyq9IgAv7z70flHoaeI+mo3Q0d83e/QIsjG0E3nSj8AMvK6WtWyzjKIotlpW7vonXO3r1bJQZM5l34G8yv3lcWMapoYdzTIUlz4YeH4Gf5kd7zXNLI3sxm70YWAt0K/HMfOjjtA/Kl+i5FBT627V7cv8izClf8m/xLeKhhIuc74Hn1+noTJx0RP8XMGPoxP2bseK/YTrqdT+6dc/hzSIm2x8AknPAyd89VCi/M3+mrUWXcy7Fxc1DMEZRtIjp65c9rVJizfRZlM8

Browser:
chrome  105.0.5195.127

Operating System:
windows 11

**Comment by lilleyse** [comment]
Thanks for the bug report @eclosion. This seems to be a regression introduced in 1.97.
