### ISSUE TITLE
HarmonyOS loading gltf error

### ISSUE THREAD

**Issue by CLF1992108** [CesiumGS/cesium#10833]
Other Android phones can be opened without problems，But using the HarmonyOS system phone will report the following error
RuntimeError: Fragment shader failed to compile. Compile log: ERROR: 0:147: 'model_iblReferenceFrameMatrix' : undeclared identifier

See more...

OK

**Comment by ggetz** [comment]
Thanks for the report @CLF1992108. Would you be able to post a minimal code sample to reproduce the failure on HarmonyOS?

**Comment by ggetz** [comment]
Closing this in favor of https://github.com/CesiumGS/cesium/issues/10858, which appears to cover the same issue with more information.
