### ISSUE TITLE
zoomTo ignores the scale property of the entity

### ISSUE THREAD

**Issue by yuan-java** [CesiumGS/cesium#10830]
entity.model = {..., scale: 0.01, maximumScale: 0.01};
zoomTo will ignore the 0.01 scaled property, but still zoomTo the original un-scaled entity.

When the model is very large (e.g. 500 hundred meters in width) on map, the center after zoomTo may be hundreds meters away from the 'real' scaled entity.

flyTo has the same issue.

https://sandcastle.cesium.com/#c=lVRhb9owEP0rJz4FiZoEStVRikbphIJI2pUMlSpfXMdQQ2JT24GFif8+JySUTf1SRYpyd++9u3u20mzCSGKuYUgVS5PxFDAhVCnQAjKRSmCCA1aKahXyIwa5gqOILnAa60EBDsSacriFsEaz8dvriLAHNnZ/7V3HZ65y+VOHDN0rd715ng3H35ABvUejdQ5aeyN/Nd/fJd7UvnwJZmwS/Ox4wUDPg9nKz+yO15o7fjBm/v289bJy2WQ43rwYMX/lZd7KiCfxW2RiL5hn/n7d8vZk57dtdOFuBmyg9gM/C/Dan6Yjoa7U8/x9NXTSR8eZ3Dleli0fL5JdWLsJeciJ4ErDltEdlWYXTnelJ2hW5KywRop4KLjGjFMZ1uoF08Iq4wSsOtz24U/IwRiRKgpKS0Z0IQ+gZXasARw7SaqMv4SaXniHWXUCubtPZQktpEgGufluZDnt9uV166p+cy5CuWY6MxLHuVERM6oQjiKrbAewEcpkBe9WPYZYavOFebtocU+XklJlOc51Ay7alw1wbLveqOiJiGjchZMcQCpZ97RA4yOvCI5pF2zkNCDBv1mSJtNTqoIdSsKhWqWcXUtM1jT6Ua103K3EHN/GiYAlVKTaKt3+qJ109kIkgbCO9KrHwezUMUvdfEGI4IRKjBKxpXdmtB2W5hQ69plky/6Q/ILwIs4+G7BdquWPSQDBmryBRaUUsn5+eURMUSyWZaUQOIT8ULfy71qj1lM6i2k/z39nyUZIbU4sthBqappsYmzOvvmaGrM1IkrlpF6zovQitgUW3X5y24HE5k9gKos0jqdsT8Nav9c0+H9oscAR48uHLZUxzgwkH6P35vQnxwJCqNc0Yd70f64WIn7F8kz3Lw

// Grant CesiumJS access to your ion assets
Cesium.Ion.defaultAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkMGNjYzBmMS04ZTViLTQ5MTAtYTVjNy05M2Y1NTJiNDY2ZjIiLCJpZCI6NjMyMjIsImlhdCI6MTYyNzk2MzcwN30.-IpAiAszANyTakNSuGos6sXYqjC1uP11LB1MyygP-mw";

const viewer = new Cesium.Viewer("cesiumContainer");

(async () => {
  "use strict";
  try {
    const resource = await Cesium.IonResource.fromAssetId(1334826);
    const entity = viewer.entities.add({
      position: Cesium.Cartesian3.fromDegrees(118, -34, 100),
      model: {
        uri: resource,
        scale: 0.1, maximumScale: 0.1
      },
    });
    viewer.trackedEntity = entity;
    
    setTimeout(() => {    
      viewer.zoomTo(entity);
    }, 1500);
    setTimeout(() => {    
      viewer.camera.moveBackward(150);
    }, 2000);
    
    setTimeout(() => {    
      viewer.flyTo(entity);
    }, 3000);

  } catch (error) {
    console.log(error);
  }
})();

**Comment by yuan-java** [comment]
flyTo has the same issue

**Comment by ggetz** [comment]
@sanjeetsuhag Is this at all related to https://github.com/CesiumGS/cesium/pull/10631?

**Comment by sanjeetsuhag** [comment]
@ggetz I don't think so. I went back to 1.96 and this issue still showed up. #10631 went into 1.97. There's also no terrain in the Sandcastle, so I don't think it is related to that system.

**Comment by ggetz** [comment]
Got it, thanks @sanjeetsuhag!

And thanks for the report @yuan-java! This doesn't appear to be a regression, so we'll need to take a look into the cause.

**Comment by na9da** [comment]
It could be that the `modelMatrix` [passed here](https://github.com/CesiumGS/cesium/blob/0fcd8ca4d0d64f0d9b10c04608f938337f629c2a/Source/Scene/Model/Model.js#L1132) does not include the uniform `.scale` set by the entity. 

Previously the scaling used to be [applied here](https://github.com/CesiumGS/cesium/blob/39d3cbd9ffd8820e74e36aa56affc98cc7287280/Source/Scene/Model.js#L849-L856) explicitly.

**Comment by ggetz** [comment]
@ptrgags or @j9liu Was this change part of the model refactor and was it intentional?

**Comment by j9liu** [comment]
The `scale` should be applied by the `updateBoundingSphere` function, which is included in the `boundingSphere` getter. But currently it's only affecting the bounding sphere's radius -- there are extra computations in old `Model` that aren't in the new one.

I can't tell right away if the fix is to duplicate the old `Model` code, because `Model` used to return a bounding sphere in local space, so it didn't take into account `modelMatrix`.  I'll have to take a look later today.

**Comment by j9liu** [comment]
@yuan-java The PR to fix this (#10855) just got merged into `main`. Let me know if you're still having issues!
