### ISSUE TITLE
Support for array uniforms in custom shaders

### ISSUE THREAD

**Issue by jinjun1994** [CesiumGS/cesium#10851]
The code that passes uniform one by one is ugly，how to support for array uniforms in custom shaders?

like [Uniform – three.js docs](https://threejs.org/docs/#api/en/core/Uniform)

I want to implement this feature, any guidance?

**Comment by UniquePanda** [comment]
There already is issue #10310 with exactly the same title as yours.  
Maybe you can add a comment there to keep that discussion in one place.

**Comment by ggetz** [comment]
Thanks @jinjun1994 and @UniquePanda! I'm going to close this issue as a duplicate. Please add further discussion in #10310.
