### ISSUE TITLE
How to drag and drop in cesiumjs

### ISSUE THREAD

**Issue by rustam-cloud** [CesiumGS/cesium#10862]
Hi,
I need help, I have created many entities that can be moved using ScreenSpaceEventHandler and it works, but now I have ScreenSpaceEventHandler associated with each entitу, which means when I create a new entitу I have a new ScreenSpaceEventHandler created... As I understand it is a globаl event, and when i created 1000 entitу i have 1000 ScreenSpaceEventHandler , and my application start to freeze. I think that this is related to a lot of created global ScreenSpaceEventHandler, that is what affecting the performance.
Can you explain to me what is the right way to manage this ScreenSpaceEventHandler, because each of them has its own function...
After that I tried to use events on the entity itself (as onMouseMove etc.) but when I move the mouse quickly the mouse moves away from the entity area and the event stops running, can you please help what I am doing wrong.

Thanks in advance...

**Comment by ggetz** [comment]
Hi @rustam-cloud, I would recommend you use one `ScreenSpaceEventHandler` and use [picking](https://sandcastle.cesium.com/?src=Picking.html) to select an entity.

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. This question is better suited for the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
