### ISSUE TITLE
A BUG about the setRotation method in the Matrix4 Class lacks the result parameter

### ISSUE THREAD

**Issue by ShenTiger** [CesiumGS/cesium#10864]
![QQ图片20221019173355](https://user-images.githubusercontent.com/53333129/196654690-1d1d87e6-ee70-4ec4-a504-ef1f8dfc4725.png)
The underlying implementation requires the parameter, but the externally exposed method lacks this variable, which is not passed in when it is used, resulting in bugs!
![image](https://user-images.githubusercontent.com/53333129/196670433-1cc5faaa-3a28-4560-8ed4-088b96b630bb.png)

**Comment by ShenTiger** [comment]
To avoid this bug, I passed this parameter when using it, but an error will be prompted in ts.
![image](https://user-images.githubusercontent.com/53333129/196672136-ec3f79d4-580e-4efb-94f4-83faf82678dd.png)
In ts.
![QQ截图20221019190145](https://user-images.githubusercontent.com/53333129/196674414-92979332-a037-4962-8ce4-030433d587bd.png)
So I added this parameter to the source code.
![image](https://user-images.githubusercontent.com/53333129/196672705-dab6523c-c8e4-4079-8778-7c575fce4038.png)
![image](https://user-images.githubusercontent.com/53333129/196672758-3de8b86b-d6be-45de-9c66-b798a64946c5.png)
It's OK!

---------------------------
Therefore, Cesium maintenance personnel may also need to add this parameter.

**Comment by ggetz** [comment]
Thanks for the report @ShenTiger! 

This can be fixed by adding the result parameter to the jsdoc comment. That will ensure it is included in the generated TypeScript definitions.

**Comment by gaurav8y785675474** [comment]
hello shentiger
i am a beginner in open source world
can you please tell me exact location of code in files .
so that i can work on that

**Comment by ggetz** [comment]
@gaurav8y785675474 That would be at https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Core/Matrix4.js

**Comment by javagl** [comment]
@ggetz I think that this was fixed with https://github.com/CesiumGS/cesium/pull/10954 and could be closed.

**Comment by ggetz** [comment]
Thanks @javagl!
