### ISSUE TITLE
The latest version of Cesium does not read variable properties

### ISSUE THREAD

**Issue by LittleHong12138** [CesiumGS/cesium#10878]
The latest version of Cesium does not read variable properties
![43E96413-4E3D-4DBC-9C38-DB53E7F921EF](https://user-images.githubusercontent.com/42067099/198824587-cfeed9fd-3e20-44f0-8cdf-245fa9dded7f.png)

**Comment by ggetz** [comment]
Hi @LittleHong12138, we're going to need a bit more context. Could you provide more information about what is different from the previous version, and maybe include a [Sandcastle example](https://sandcastle.cesium.com/) which shows the issue?

**Comment by LittleHong12138** [comment]
The output printed using the console function cannot be directly viewed by the type and is instead confused with jh

**Comment by ggetz** [comment]
@LittleHong12138 How are you including CesiumJS? From the release zip, or npm? Are you using `CesiumUnminified/Cesium.js` or `Cesium/Cesium.js`?

**Comment by LittleHong12138** [comment]
@ggetz I use  npm including  Cesium/Cesium.js, so how including  CesiumUnminified

**Comment by ggetz** [comment]
@LittleHong12138 

`Cesium/Cesium.js` is [minified](https://en.wikipedia.org/wiki/Minification_(programming)). 

If you'd like to use `CesiumUnminified/Cesium.js` the advice will be based on your app setup. What framework/tools are you using, if anything? Can you show us what your import statements look like?
