### ISSUE TITLE
Missing V1.98.1 in release page?

### ISSUE THREAD

**Issue by xingrui94** [CesiumGS/cesium#10870]
There is only the v1.98 in the github release page, I cannot find the CesiumJS version 19.8.1.Finally, I find the v1.98.1 in the npm repos.
![image](https://user-images.githubusercontent.com/29156275/197462778-14248238-d539-44cc-a877-7742b0aec2e4.png)
![image](https://user-images.githubusercontent.com/29156275/197462630-cb0f0b1d-517c-4bc5-8928-3f744d679eb8.png)

**Comment by kring** [comment]
1.98.1 was only published to npm because its only purpose was to fix a problem with the way 1.98.0 was published to npm. See the changelog:
https://github.com/CesiumGS/cesium/blob/1.98.1/CHANGES.md

**Comment by xingrui94** [comment]
> 1.98.1 was only published to npm because its only purpose was to fix a problem with the way 1.98.0 was published to npm. See the changelog: https://github.com/CesiumGS/cesium/blob/1.98.1/CHANGES.md

I see, Thank you.
