### ISSUE TITLE
Terrain clamped Entities and Primitives containing polygons defeat RequestRenderMode

### ISSUE THREAD

**Issue by Marvosg** [CesiumGS/cesium#10872]
I want to use Request Render Mode (RRM) to reduce the battery consumption for my users on mobile devices. My application does not display time-dynamic data. I update the data displayed when the user interacts with my UI, so if the camera is not moving, the displayed map and data are static.

Adding a terrain clamped Entity (height: undefined) or a GroundPrimitive that contains a Polygon to the scene seems to request a new render every frame, defeating the purpose of RRM.

Sandcastle examples: 
[Polygon 'height: undefined'](https://sandcastle.cesium.com/#c=nVZtbyI3EP4rI6qqiwQLXJIqJSQqJeQaKbmLCMl9KNXJrAew4rWp7Q2hVf57x/sCuxwk1wbBZu155pmXx7PbasHAIHMIDJ4FrtCAWzAHK61+cmBQcVphoHAFM8NihERJtHaiWi1IlpyAFpwmDIKNUCFB/kqEQRDOrxvkSYSgn9EwKWFw9wCJZXMMJ2qiIq2s54gcU3OJcA4DtCKJw1GxFM6Mji9xbhBt0Ox02mG7AUcn/rf5S3o5pt/6mfeWYwcUpGHh5fCq/3Az/vp4PfzydTQcjPufPt4MiWJDd/Ym5Ko/GH8ekX077Jxtg81LdJ4WJIc/pmvBpBal9wOtHBMKzaTWgH8mCtKSoHWjtJi3mmMXnEmw4fdi9iLiJM72xiLGwYKiI4trNRNKuHVq5dAY8nln9LMgu25BHaWt+6KN5OPMJEgZN5yPaBy+fNImZtKWaF/rdHmtlzLLuneeZximt7SdXkOO02R+v9CrK68Be4fmHgnGyd67TN1MSBgO5kYnit8ZEQsnnrOdWaIiJ7QCxvlQOUoqWKCYL1w9q09OiX5LoA3JbJtG3q0u5CsAkdaGC+Wl190aNIrtmDaMYHJTpIGW2oSj4WW4Em7Rl8sFC9rhSX2DyILp5tds9TUvEyXwWsnBoEV376sSHAjfYEx670sZeDRklQ13ClOYBTvr3xJSNR5IHKQG5L+nEeY1rBfq2gaU8m2rnBS4ciAVNQZ7+T5WYzrItBM7qeFArr6jWV1L52aXZdPgOeoYnVlfky6Zinyby7Cd3S1ui6wANtOkQJYRsEdB+fEobphzRkyTVG4VZOSFVaFKpbYbYL/AB+n46mx+KiIsJFehz//5j+27/F9iaX8Hy3ZUMCO0pYb/4TF5VWjS0Cma1DKH0IR8JkEkWbxEDsFvNK+eLIxGt3WajhmKXKKkHnQPKj07io09TDsS+g6CHcRh1/uTEGoOXFg2lT4dogEavk/2ANnlG7n8mY7Ge6Z4xKyjRx3Zj7WWU2ZuUSXBpsjZkK41apNa2qDiC9Czbi3xolDNryJeauMgMTIIw5bDeCn9kGxNk+gJXRjZ3Fdm/oPL2MqanrLoKTu8NFnnUxYcf6BHbP5th6eZRLK/JQVM5ejC8fKltDyl4YymaRgXia1uvu4hXxxtx/BxOZSYmblQXWjT58PyBdpvuhFl6IyewE0r/qaHxunJj2/inO/kPlpPeVRJjJ7UzZXgbkGbp+130nK87DQvVXOqndNxFzrvwcPsVaJJU8PRmd4T38++JO8VRS0TVwbTW5gTEZNNJsWcnMSC8/RF6B0f3Y3kS87y6ceZIcmwddlLKs5WWZ09Lp5B8PM9L0n+YFlLO7NEynvq2qR20WuR/TdQqZkv42dKQ7K1N1t0Lm6yxTAMey263Y/MsyFIEWUv7fzFNp2em2q+Li+0qit0X4KUef4F)
[Polylines 'clampToGround: true'](https://sandcastle.cesium.com/#c=vZTfb9owEMf/lRNPYaUBVvUFaLUOtmlSu1UFdQ+jD258CWaOzWyHH53433dOIASK0KZJExJ2fJ/z3fm+9pwZmAtcoIErULiAPlqRpeFjvhaMa1H+3dfKMaHQjGuNX2MFYPBnhtY9oOJo7jTHDjiTYcPbUrYUaZYWtpFIsT9hKiHis4qFEm6VUw6NoS3vjZ4L4jrbyJFB5vCbNpKPCiTII5YxH9E4XH7RJmXSVsKu6zSs692xKgoKbYQKQ47PWTKc6MVHw1K092iGGGnFqV7vSrj/xZmKnNAKuGGLey1Xkqq1QSRZOqtDnkCsDQQSHQhybXVp6MGlH8/ONkSFmRbMdMNMKwyAB5YeCFutNrwB0a1aVhXLtLRsakLlhBNoQ8Z5UG4IMNuk3IHKol+2wpdly+PtMzo9K5i6CGOj0wEmBtHe0EGvgu9VV4DzdrsFZ7BswMUljUXbXpmDJf3l+db/FgxWu5WTof8Y3A/9tE8vBHeTDrzdW0xJbEYwuTsgLbUJHz4M9rBcCCP9yehM8U7xWQHW5TwXYD7JNUmKLAQ2ZIpHzDqJvnUDjFkm3Uhr+czMHaos8PimAWULSeeuA+PagERZxEQOpTrpLm5B6jBKjAguhRzUq1I4lI/BVM/xRsqg3t1R++L316Nq3ezxonU60sHBjjtwexbb8Xg1mTr/7wXF9GD8e0VPY1XvHrTUoKWbe/U62dNprvN9ao1az7qVxOttwHcinWnjIDMyCMOmw3QmSae2+ZxFP9CFkS2z6zWrrj0u5iD41ZF32+vHWrLEmZRD8YLj2nWvSfwrV6kZFyr5Okcj2cpjk/b1bbEYhmGvSZ/HPV2hZ3LZVlKxFY+51/pB5CrlW/E+c476f4JyOkkk3opk4iinE6AlhUk8vmF1/hs)
Browser: All
Operating System: All

In the Polygon example, select an option from the dropdown and observe the framerate counter. Only the last example will stop rendering frames when there are no more changes. But the rectangle is not clamped to the terrain and mountains show through, this is not an acceptable solution.

In the Polyline example, observe that clamped polylines do not request further frames after max detail tiles are loaded into the scene. This shows that a terrain clamped entity does not need to redraw every frame to display properly.

I found another issue referencing a similar behaviour: 
[#6631 Entity primitive continuously re-drawn when position is SampledProperty](https://github.com/CesiumGS/cesium/issues/6631)

I am not very familiar with the inner workings of Cesium yet, is terrain clamping implemented with a SampledProperty, are these issues related?

[Comment by adi64](https://github.com/CesiumGS/cesium/issues/6631#issuecomment-1012932182) in the above issue states:

> If you define a dynamic property of an Entity (e.g. CallbackProperty, but probably also SampledPositionProperty), it is marked as dynamic. A dynamic entity is updated every frame, because Cesium has no way of knowing if property values for the new frame will change. That's all fair.

I would say that is not correct behaviour. A CallbackProperty can have `isConstant` set to `true`, and so does not have to be called every frame just to see if the data changed. Terrain clamping should behave the same, whether implemented by SampledPositionProperty or not. 

As explained in ['Improving Performance with Explicit Rendering' by Gabby Getz](https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/):

> When [RRM] enabled, a new frame will be rendered **only** in the following scenarios:
>- The camera changes, either with user input or with the Cesium API.
>- The simulation time advances beyond a specified threshold.
>- Loading in terrain, imagery, 3D Tiles, or data sources, including each individual tile load. At a lower level, this is triggered when a web request is resolved via a URI or blob, or an asynchronous process returns from a web worker.
>- Globe imagery layers are added, removed, or changed.
>- Globe terrain providers change.
>- The scene mode morphs.
>- A frame is explicitly rendered with the Cesium API.

When the terrain provider has finished loading tiles, a Primitive with terrain clamping enabled should not have to redraw every frame. A frame is requested when the terrain data changes, which is requested when the camera moves, which is handled by the camera controller. There is no other reason to request a frame. I would say the current behaviour demonstrated in the Polygon sandcastle example is a bug.

**Comment by ggetz** [comment]
Thanks for the detailed write-up @Marvosg!

As long as you are not using a `SamplePositionProperty`, in which case https://github.com/CesiumGS/cesium/issues/6631 may still be an issue, I think the issue you are running into is https://github.com/CesiumGS/cesium/issues/10756. The good news is this was fixed in https://github.com/CesiumGS/cesium/pull/10865 and will go out with the next release on Nov 1.

I'll close the issue as a duplicate, but please let me know if you think I missed anything.
