### ISSUE TITLE
Error on mobile devices with lower RAM

### ISSUE THREAD

**Issue by vlkpa** [CesiumGS/cesium#10888]
Hello, I am using React Native WebView with Cesium.js and I am facing this error “Expected width to be greater than 0, actual value was 0” or “drawingBufferWidth must be greater than zero” on mobile devices with lower RAM. Now I am testing on Xiaomi Redmi 9A (2GB RAM) and this error always shows when I am trying to show the 3D tiles or sometimes when I want to camera fly to my current location.
My Cesium3DTileset options are:
`   maximumScreenSpaceError: 64,
   maximumMemoryUsage: 128,
   dynamicScreenSpaceError: true,
   skipLevelOfDetail: true,
   immediatelyLoadDesiredLevelOfDetail: true,`

*This error always shows when I am trying to open [3D Tileset Photogrammetry sandcastle](https://sandcastle.cesium.com/?src=3D%20Tiles%20Photogrammetry.html) on this device (in Chrome).

**Comment by ggetz** [comment]
Hi @vlkpa, that error can show up when the WebGL context is lost, which [can happen when the browser](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/isContextLost#usage_notes), or in this case the WebView, determines too many resources are being used.

> 2GB RAM

While WebGL has no minimum requirements, this is very much on the low end of hardware, so you will need to be careful about your configuration for the best performance on this device. I see you've already adjusted the `maximumScreenSpaceError` which is great. Here's [a post on our community forum](https://community.cesium.com/t/performance-optimization-on-old-hardware/5785/3) which goes through some additional configuration options for low-end hardware. The most important of those is probably decreasing [`Viewer.resolutionScale`](https://cesium.com/learn/cesiumjs/ref-doc/Viewer.html#resolutionScale), which will render the scene at a lower resolution loading less data overall.

Cesium is a big project, and we use GitHub for feature requests and bug tracking exclusively. I'm going to close this issue, but please feel free to ask more on the [Cesium Forum](https://community.cesium.com/), where there are members of the community and developers from the team who can help. Thanks!
