### ISSUE TITLE
Billboard lack of Bounding Rectangle 

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#10895]
Recently I developed on label dynamic placement 。For overlap calculation algorithms, It’s very hard for developers to verify the correction. So I have made a debug wireframe for each billboard. Just like this
![68FBE468-730E-40BD-B2E3-419638140AF6](https://user-images.githubusercontent.com/1418843/200830428-67f663fd-2c71-4493-aa67-231878de87f2.jpeg)
If this feature is needed, I can make a pull request. :p

**Comment by ggetz** [comment]
@jiangheng90 I think the biggest outstanding change is https://github.com/CesiumGS/cesium/pull/10824, which altered the directory structure. `Source` files will now live in `packages/engine/Source` or `packages/widgets/Source`. To merge with an existing branch, merge the `1.99` tag to merge all changes before #10824. Then merge the `post-workspaces` tag and make sure any new files or changes are in the right directory. Thanks!

**Comment by ggetz** [comment]
> So for changes I want merge to cesium, I need to start with tag 1.99

That is the easiest way to merge, yes.

> There are several error and build fail.

Could you list the errors here?

If you are still having trouble merging the latest changes, I think it will still be a help to leave a git back on an older version.

**Comment by jiangheng90** [comment]
@ggetz for ```npm run build-watch``` command. both my computer in home and company got error below
```
[21:53:07] Finished 'build' after 18 s
[21:53:07] Starting '<anonymous>'...
[21:53:07] '<anonymous>' errored after 527 ms
[21:53:07] TypeError: (intermediate value) is not iterable
    at file:///E:/cesium/gulpfile.js:162:44
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[21:53:07] 'buildWatch' errored after 18 s
```
for error throw in gulpfile, it comes from
```
let [esmResult, iifeResult, cjsResult] = await bundleCesiumJs({
  minify: minify,
  path: outputDirectory,
  removePragmas: removePragmas,
  sourcemap: sourcemap,
  incremental: true,
});
```
the deconstruction throw it. I see the return of ```bundleCesiumJs``` is a object.

I have tried to fix this one with:
```
const bundleResult = await bundleCesiumJs({
  minify: minify,
  path: outputDirectory,
  removePragmas: removePragmas,
  sourcemap: sourcemap,
  incremental: true,
});
let esmResult = bundleResult.esmBundle;
let iifeResult= bundleResult.iifeBundle;
let cjsResult= bundleResult.nodeBundle;
...
```

then ```bundleWorkers``` comes another ```options.input``` undefined cause ```globby``` throw error
I am not sure, Maybe problem is in node version or terminal. here is my develop environment
my home computer
node version: ```v14.17.5```
npm version: ```6.14.14```
terminal: ```cmd``` on window 11

my working computer
node version: maybe after 16
npm version: maybe after 8.19
terminal: ```cmd``` on window 10

I am goina to sleep for now .Tomorrow I will continue keep track of this :)

**Comment by jiangheng90** [comment]
@ggetz I have make two patches
```0001-add-debug-bounding-rectangle-for-billboards```
and
```0002-update-post-workerspaces```
[patch.zip](https://github.com/CesiumGS/cesium/files/9985968/patch.zip)

the first one I have tested in tag ```1.99``` and works fine 
the second one is move changes to work space

**Comment by ggetz** [comment]
Thanks @jiangheng90! I'll close this issue since there's nothing actionable at the moment, though this thread will still come up in searches.

We'll follow up on the error in #10897.
