### ISSUE TITLE
command error on npm run build-watch

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#10897]
for ```npm run build-watch``` command. both my computer in home and company got error below
```
[21:53:07] Finished 'build' after 18 s
[21:53:07] Starting '<anonymous>'...
[21:53:07] '<anonymous>' errored after 527 ms
[21:53:07] TypeError: (intermediate value) is not iterable
    at file:///E:/cesium/gulpfile.js:162:44
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[21:53:07] 'buildWatch' errored after 18 s
```
for error throw in gulpfile, it comes from
```javascript
let [esmResult, iifeResult, cjsResult] = await bundleCesiumJs({
  minify: minify,
  path: outputDirectory,
  removePragmas: removePragmas,
  sourcemap: sourcemap,
  incremental: true,
});
```
the deconstruction throw it. I see the return of ```bundleCesiumJs``` is a object.

I have tried to fix this one with:
```javascript
const bundleResult = await bundleCesiumJs({
  minify: minify,
  path: outputDirectory,
  removePragmas: removePragmas,
  sourcemap: sourcemap,
  incremental: true,
});
let esmResult = bundleResult.esmBundle;
let iifeResult= bundleResult.iifeBundle;
let cjsResult= bundleResult.nodeBundle;
...
```

then ```bundleWorkers``` comes another ```options.input``` undefined cause ```globby``` throw error
```
[22:14:17] Finished 'build' after 23 s
[22:14:17] Starting '<anonymous>'...
[22:14:17] '<anonymous>' errored after 786 ms
[22:14:17] TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (file:///E:/cesium/node_modules/globby/index.js:15:9)
    at toPatternsArray (file:///E:/cesium/node_modules/globby/index.js:21:2)
    at file:///E:/cesium/node_modules/globby/index.js:55:66        
    at bundleWorkers (file:///E:/cesium/build.js:420:25)
    at file:///E:/cesium/gulpfile.js:177:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[22:14:17] 'buildWatch' errored after 23 s
```

then I stop on this error, recently I wiil keep track on this

**Comment by ggetz** [comment]
Hi there, thanks for the report. What version of node are you using?

For example:

```sh
$ node -v
v16.15.0
```

**Comment by jiangheng90** [comment]
@ggetz here is my develop environment
my home computer
node version: ```v14.17.5```
npm version: ```6.14.14```
terminal: ```cmd``` on window 11

my working computer
node version: some version after 16
npm version: some version 8.19
terminal: ```cmd``` on window 10

both this two versions throw error

**Comment by ggetz** [comment]
@sanjeetsuhag Would you be able to take a look at this? Technically [NodeJS 14 is the minimum version we recommend](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/BuildGuide#build-the-code). Is that still accurate?

**Comment by sanjeetsuhag** [comment]
Taking a look at this now, @ggetz. On my system, I mostly use Node 16 and 18, so I'll check what works and doesn't work on Node 14 with the new scripts.

**Comment by ggetz** [comment]
Thanks for your patience @jiangheng90.

[npm workspackes](https://docs.npmjs.com/cli/v7/using-npm/workspaces) are only supported in Node 16 and above, which is why we've [documented a minimum Node version of 16 or above in the build guide](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/BuildGuide#build-the-code) to build the code or run development scripts.

However, workspaces are not required to run the packaged/shipped code, which is why the minimum supported Node version defined in `package.json` is >14.
