### ISSUE TITLE
Cesium.Viewer instantiated inside my lit component: CreditDisplay is missing its styles

### ISSUE THREAD

**Issue by rudifa** [CesiumGS/cesium#10907]
I have a project, [cesium-lit-demo](https://github.com/rudifa/cesium-lit-demo), set up to create a Lit component, `<cesium-lit>`. The component instantiates a `Cesium.Viewer` and adds, for now, just a couple of buttons to zoom in and out, and to display the target height.

The demo is deployed on [netlify](https://cesium-lit-demo.netlify.app/), and it looks good.

The problem of missing styles can be seen in an [earlier commit 6f8df87](https://github.com/rudifa/cesium-lit-demo/commit/6f8df877898d708707ce1485a7008436c232d4af)

<img width="746" alt="Screenshot 2022-11-16 at 13 34 17" src="https://user-images.githubusercontent.com/172404/202190332-335b5f44-1b8f-4313-bf58-502a2d75daa2.png">

1. The source of the problem is in the lines 273-276 of the file [CreditDisplay.js](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/CreditDisplay.js#L177-L277):

```
  const head = document.head;
  const css = document.createElement("style");
  css.innerHTML = style;
  head.insertBefore(css, head.firstChild);
```
Above code assumes that the calling object, Cesium.Viewer, is instantiated in the document's DOM, not in a shadow DOM, as is the case in my Lit component.

2. To fix this problem, above code should check whether it is being called under a shadow DOM, and accordingly attach the css to the shadow root of the component, perhaps along these lines:

```
    const rootOrHead = this.renderRoot || document.head;
    const css = document.createElement("style");
    css.innerHTML = style;
    rootOrHead.insertBefore(style, rootOrHead.firstChild);
```

3.  A little more detail can be found in my project's [issue #13](https://github.com/rudifa/cesium-lit-demo/issues/13)

**Browser**: Chrome Version 107.0.5304.110 (Official Build) (x86_64)

**Operating System**: macOS Ventura 13.0.1

**Contribute a fix?**

I'd love to, but I'd need to find time for a deep dive into the Cesium project's build-and-test process.

Probably someone knowledgeable can easily beat me to it.

**Comment by ggetz** [comment]
Thanks @rudifa! When implementing the viewer inside a web component, we've previously applied a similar workaround importing `Build/Cesium/Widgets/Widgets.css`.

As an aside, we do have some interest in [implementing an official Cesium web component using lit under the hood](https://github.com/CesiumGS/cesium/issues/10876) if you would like to contribute to that discussion.

**Comment by rudifa** [comment]
Thank you @ggetz for the comments on this issue. 

I guess it is really a feature request: that Cesium components should also work under a shadow DOM.

For the `CreditDisplay.js` this is clearly not the case. Do you have any plans to fix it?

cc @olange who has put me onto the Lit components and Cesium trails.

Our future work with Cesium and additional data sets will likely produce some ideas and suggestions for your discussion re Cesium + Lit components.

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11129
