### ISSUE TITLE
Cesium 1.99.0 Build error on linux operating system

### ISSUE THREAD

**Issue by williams9438** [CesiumGS/cesium#10900]
ERROR in ./node_modules/cesium/Source/Scene/Model/MetadataPipelineStage.js 86:29
Module parse failed: Unexpected token (86:29)
File was processed with these loaders:
 * ./node_modules/strip-pragma-loader/index.js
You may need an additional loader to handle the result of these loaders.
|   const { shaderBuilder, model } = renderResources;
|   const { structuralMetadata = {}, content } = model;
>   const statistics = content?.tileset.metadataExtension?.statistics;
| 
|   const propertyAttributesInfo = getPropertyAttributesInfo(
 @ ./node_modules/cesium/Source/Cesium.js 956:0-90 956:0-90
 
 ===================================================
 Nodejs - v14.20.1
 NPM - v9.1.1
 OS - Ubuntu 20.04.2 LTS

**Comment by williams9438** [comment]
Note that this compiles well on windows10 Operating System but build error on Linux

**Comment by williams9438** [comment]
@ggetz any solution

**Comment by jjhembd** [comment]
Hi @williams9438, thanks for the bug report.
To help track this down, can you tell us what browser version you are using on Linux?

**Comment by ggetz** [comment]
This is likely due to using NodeJS 14. We are investigating– see https://github.com/CesiumGS/cesium/issues/10897.

In the meantime, is updating NodeJS 16 or 18 an option?

**Comment by williams9438** [comment]
For now upgrading nodejsto 16 or 18 is not an option.
Note: it compiles well with nodejs 14 on windows.

**Comment by 3DGISKing** [comment]
The same happened to me

![image](https://user-images.githubusercontent.com/26606704/201808907-6cfa1d8d-c9b0-4d0c-82df-54d8bdbba9de.png)


nodejs v16.15.0
OS: 
![image](https://user-images.githubusercontent.com/26606704/201808831-ec418a34-2e72-4c7a-bb59-bd4f912f9d1d.png)

**Comment by 3DGISKing** [comment]
I fixed this by changing browserslist in package.json
![image](https://user-images.githubusercontent.com/26606704/201869262-8157d5f3-0d7f-4983-bb11-312c527a0ef3.png)

**Comment by 3DGISKing** [comment]
> 

we are using CesiumJS in CRA as a module. we changed "browserlist" in package.json, but I can not confirm that is the best solution.

**Comment by williams9438** [comment]
> Thanks @williams9438 and @3DGISKing. How are you building/compiling your app?
> 
> The `?.` or [optional chaining operator](https://caniuse.com/mdn-javascript_operators_optional_chaining) is not supported in all versions of all browsers. It's common for build tools to transpile source code down to a set of features with wider support if needed, such as ES6.

For now what i did is to downgrade Cesium down to 1.95.0 and the compilation works for me in that version. version 1.97.0 compilation works as well but it has a 3D display error on some dataset

**Comment by ggetz** [comment]
If you are using a webpack based build process, such as the one create-react-app sets up, you should be able to set properties under [`output.environment`](https://webpack.js.org/configuration/output/#outputenvironment) to configure what features of ES you want to output — In this case, `optionalChaining: false`.

**Comment by DreamInSun** [comment]
the same problem i conflict with in Win10， node 16.15.0， vue，change the browserlist doesn't works, so i rollback to 1.95。so it works well at the moment

**Comment by ggetz** [comment]
Thanks all! As this is a question of external tooling configuration, I'll close this issue. Please feel free to continue discussion here or on the [Cesium Forum](https://community.cesium.com/).

**Comment by shanshiping** [comment]
> I have the same problem, but I have resolved this. @williams9438 My app is created by vue cli 4, and the version is win11, node 14, webpack 4, babel 7. If your app is created by vue cli 4 also, you can follow my steps:
> 
> 1. The Problem is caused by Optional chaining, so we can install babel plugins about Optional chaining, And I also install plugin about Nullish coalescing operator. Please run the shell:
> 
> ```shell
> $ npm install --save-dev @babel/plugin-proposal-nullish-coalescing-operator
> $ npm install --save-dev @babel/plugin-proposal-optional-chaining
> ```
> 
> 2. Insert the plugins into the `babel.config.js` in the root path:
> 
> ```js
> module.exports = {
>  presets: ['@vue/cli-plugin-babel/preset'],
>  plugins: [
>    '@babel/plugin-proposal-optional-chaining',
>    '@babel/plugin-proposal-nullish-coalescing-operator',
>  ]
> }
> ```
> 
> 3. Don't forget that you should set babel include `node_module` path in the file `vue.config.js`:
> 
> ```js
> module.exports = {
>   transpileDependencies: [
>     /[/\\]node_modules[/\\]cesium[/\\]/,
>   ]
> }
> ```
> 
> enjoy it.

I got the same problem, and I use your solution, it's very helpful. I use vue cli 4 , node16.17.0, webpack4 and cesium1.112.

**Comment by shanshiping** [comment]
I got the same problem, and I use your solution, it's very helpful. I use vue cli 4 , node16.17.0, webpack4 and cesium1.112. Thank you very much. @hljwkwm
