### ISSUE TITLE
Cesium dependency on es5-ext protestware trojan

### ISSUE THREAD

**Issue by cfairchi** [CesiumGS/cesium#10919]
Cesium has a dependency on gulp@4.02 -> undertaker@1.3.0 -> es6-weak-map@2.0.3 -> es5-ext

es5-ext\_postinstall.js is flagged as a Trojan

 SHA-256:       921812FD619E8E575AB52F426E2F47DD313787DB49C7C938A7A52D0F403C16EE
       SHA-1:         4E7D5E7992F67E6EA4D602D8145360890EDD1C3D
       MD5:           078B8FFDCEC9D4DD803B73E2CE332384
       THREAT NAME:   Script.Trojan.A6117991
               File: node_modules\es5-ext\_postinstall.js
                       Quick Heal:    Script.Trojan.A6117991

It appears to be protestware and is blocking us from using cesium as it won't pass virus scans.
https://medium.com/checkmarx-security/new-protestware-found-lurking-in-highly-popular-npm-package-d46f8ba67e36

![image](https://user-images.githubusercontent.com/984128/203313924-415b1ef7-8def-4ef2-8371-19276cffc23f.png)

**Comment by cfairchi** [comment]
https://github.com/gulpjs/gulp/issues/2704

**Comment by ggetz** [comment]
Thanks for the report @cfairchi! 

To clarify, this an issue when using the zip file or running `npm install` from the root directory, correct? If so, as a workaround you may avoid installing `gulp` and the other `devDependencies` by using the `--production` flag, however you will not be able to run any of the development scripts.

To resolve the root issue, we can wither wait, and update gulp when they release the next major version (which will hopefully happen soon), or remove the gulp dependency.

**Comment by Atulin** [comment]
Gulp hasn't had a new release for 4 years now, and nothing makes me believe they'll have one for at least 4 more years, if at all. I'm afraid withering or removing Gulp dependency are the only choices.

**Comment by Dimava** [comment]
This can be solved by forcing an exact version of es5-ext (the example below works with Yarn)
```
<package.json>
  "resolutions": {
    "es5-ext": "0.10.53"
  }
```
