### ISSUE TITLE
加载整合地形（terrain）之后，viewer.flyTo(ImageryLayer) 报错：DeveloperError: normalized result is not a number

### ISSUE THREAD

**Issue by Southjor** [CesiumGS/cesium#10937]
因英语水平有限，怕软件翻译的不准确，这里使用了中文，见谅！

Sandcastle example:

viewer.flyTo(ImageryLayer) 

Browser: google

Operating System:

win10

开启地形之后（Terrain），地形资源为混合资源，即 0-12 级为全球地形，13-15级为中国地形。其他功能都正常，只有 ImageryLayer 对象，在设置 rectangle 之后，使用 viewer.flyTo(ImageryLayer) 功能，会报错。

地形资源为正常资源的时候，没有这个问题，比如只有全国1-10级数据，layer.json 跟金字塔数据完全匹配。

报错信息为：

DeveloperError: normalized result is not a number

Error
    at new DeveloperError (http://localhost:8009/lssec.js:83514:11)
    at Cartesian3.normalize (http://localhost:8009/lssec.js:69756:11)
    at Ellipsoid.geodeticSurfaceNormal (http://localhost:8009/lssec.js:87921:65)
    at Ellipsoid.cartesianToCartographic (http://localhost:8009/lssec.js:88014:18)
    at Array.createUpdate3D (http://localhost:8009/lssec.js:237640:30)
    at CameraFlightPath.createTween (http://localhost:8009/lssec.js:237932:39)
    at Camera.flyTo (http://localhost:8009/lssec.js:236172:86)
    at updateZoomTarget (http://localhost:8009/lssec.js:427653:14)
    at Viewer._postRender (http://localhost:8009/lssec.js:427539:3)
    at Event.raiseEvent (http://localhost:8009/lssec.js:92422:20)

经过调试代码，发现是归一化的时候，参数均为 NaN，引起的后续报错。

但是使用 camera 定位没有问题。

ImageryLayer.getViewableRectangle().then(function (rectangle) {
                return cameraFlyTo(rectangle, undefined, options);
            });

不确定是不是 bug，望解答！

**Comment by ggetz** [comment]
Hi @Southjor,

Can you provide a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the error?

It would help if you can provide us a link to the relevant terrain.

**Comment by Southjor** [comment]
here is ths code,thanks.

[viewer flyTo ImageryLayer](https://sandcastle.cesium.com/#c=lVTNbtNAEH6VVS51JGvt/NHYTStEQQiJQkWr9hIJbZxJstTeNbvrhDTqkccAiTMPwdP0wFsw6784JQXVB3s9883fNzMbSaENWUkVTy9BKcYFOSYCVuQUNM8SWnxK1bmSSz4F5WzGYixI/ngeWYACwjUxCyCKzxeGaJmpCIicEVNYbtGZiklIDhbGpDr0PJmCiNkalKZLnnpRHs4rrbwJ8E9czL0D95FwiJOKVEr0/VTXH2M2abhX8DkDba4Zws6YvgmJURm4qHmAuAJl4Ms7qRIW6xJVkHLXPrKHKCd2yWEFapfSq1zmjFtFRqdSGEwI1Ljlko31YHbZDnfag1HKCFWMtMTtRrmGyRlLL0AteQRvEjYHtW72r6gI6UzWZA5SIxBTEP8hsUZ6ETfgrRJdcId+7n99vf/x0/4UeHRiMWHX9/0ClDLFEjC5blPxaRQTGjUgTE1joZlZclF4wG32Xirm2z7p3P+r84vXYb8f+Dvz8fvb920uOdisY7D4g7w/blH8Tp/ylHcJLDl7azVOxbG7KavVYHAUIsPEPAYrq3/CysGHSkJnSiYvYa4AtNPpDGi/0xv6QRA8Q2r8gUt6Ae33O8Hh0B8OrOjQJZ3OIe0HQTdH2FfXJf0O9QdBd9j3h71c3i6rwHzYdEqMLOdtLIov5Y0aNEWMkxdazc8jy4Ti0n4Wry/l1obUTxMUYVMVK7DWFVsyjlsVQ43NHdA5GDv6VlNT47QpRhbOLBOR4VIQp+axXc3InjDOppnMFPeRC2btw9rc3UFkqlCTXinPebt7WNTTzi23NW4dVatUaEb5sJ1UsOc8SaUydqkcSvHySdIY7xbtTbLoBgyNtK5yGHlN09GULwmfHu+5JUgUM61RM8vi+ILfwrh1MvIQ/5dpLNkU77j3uK/YAgtbdE7eFkJK6cjD3/2WRsp4wjBYXUlDV1xEZyCyB5GbqFspkxeZMbhe/0BphoTAflzz/Ac)
`

**Comment by ggetz** [comment]
Thanks @Southjor!

I think the issue is arising here: https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/computeFlyToLocationForRectangle.js#L52-L58

For some values of  `positionsOnTerrain`, `height` is `undefined`. This is not handled, resulting in the returned value of `computeFlyToLocationForRectangle` being a position with a height `NaN`. The `undefined` heights should be skipped instead.

@Southjor would you be interested in contributing a fix?

**Comment by Southjor** [comment]
乐意效劳！

目前我自己的处理方案：
1. 完整的地形（terrain）数据，指的是 layer.json 必须和金字塔目录的地形数据完全对应。
2. 开启地形之后，对于 ImageryLayer 使用 camera 的定位（flyTo），不使用 viewer 的定位。

源码层面的处理方案：
之前经过调试，也发现是 undefined 引起 NaN 导致的 ：**For some values of positionsOnTerrain, height is undefined.** 
那么可以加个判断，height 为 undefined 的时，赋值为 0。

已经提交分支：[修复问题](https://github.com/CesiumGS/cesium/compare/main...Southjor:cesium:patch-1)

**Comment by ggetz** [comment]
Thanks @Southjor, would you be able to open a Pull Request with the fix?

The guide to open a Pull Request is in [`CONTRIBUTING.md`](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md).

**Comment by fuuhoo** [comment]
老哥，地形整合怎么做的
