### ISSUE TITLE
How to remove the blue shadow? 

### ISSUE THREAD

**Issue by CharleeWa** [CesiumGS/cesium#10938]
`
const viewer = new Viewer(cesium.value, {
    terrainProvider: createWorldTerrain()
}
`

![截屏2022-12-06 09 38 00](https://user-images.githubusercontent.com/22477554/205788289-d00a63bd-30b8-44e2-96f3-45a6c515f95c.png)

Macos, Chrome Latest, Cesium Latest

**Comment by ggetz** [comment]
Thanks for the report @CharleeWa. Is this happening frequently across the globe, or specifically in one location?

**Comment by ggetz** [comment]
Thanks @CharleeWa. I do think what you're seeing is two tiles of the Bing Maps Imagery layer with mis-matched coloration.

Here is the same area shown in CesiumJS, but with a different imagery provider. The seam is much less obvious.

![image](https://user-images.githubusercontent.com/4439461/206199496-f08adb00-693c-4ece-ad77-0572130dc6a9.png)

Unfortunately, the data is provided by Bing, so there's no actionable fix on our end. I would suggest trying out different imagery provider options if this continues to be a problem in the area your app frequently uses.
