### ISSUE TITLE
model invisible。In columbus mode，model is invisible。

### ISSUE THREAD

**Issue by lewhonly** [CesiumGS/cesium#10943]
Sandcastle example:
![modelInVisible](https://user-images.githubusercontent.com/15715364/206109079-401f5afa-fb5d-44bd-937d-95af91b87dbc.jpg)
https://sandcastle.cesium.com/index.html#c=tVbbbts4EP2VqZ9kwEvZubSo1wma2Ei32E37EKdYoCoKRhrFRCjSIKlctui/75CUHMV2H4zAARyQQ/LMOcMRZ3KtrIN7gQ9o4AQUPsAUragr9jXYkqyXh/lUK8eFQpP1BvAzUwBClfpcP46h5NLiwJssSsyd0OqTKkTOnTYvVhe80A92DM7UrUXXsjhTouIOu/YcFV7qgmyjYEjTYDqcfVHyqcHM1K/+n5nKVFmr4BRyg4Tjz8mkNnIACxS3C9ePfKNIFoDY0ohKOHGPlhms9D2eSZlEOIA8BGWprQiwJ21Iptw4GnF1yEqjqxneGkSb+CMAf4wODtnw3dHR29H7QTQdHbHh8fDw3fBtY4h8/Ni7IkrcQOXpXnJnxOOzp7nhypbaVJYht+6zNm5xvZzrC/GIxYXhFSYtvTUkwvidUF4USYMfYhREfJSuTH5GegAUNRj7/4PW0qU37s5WO2zOJdLawSBG71e/oRRp5ETWcGbR+Yx6dlWgdUJxL2G8ivUgAoTzdL8eMF6GXvplS+q++bUGxeGjG0PWOxMmN7x0lJtxgbaGVKRUaZMj6cPKdzdRWhs57DGWXvFqKXHGHU+DWJvGkJGLZvSDhuxW3qyc+b/j4XDIhu08CiAlUc9gC+WZ0Qr3yDfgd8cblEfHuzH+aHStCviKC5HL/VCPLhoPL2cb9Heh/pd2QLcG51xKrdUew954eDnbDP2u2XIp5B3MTZ3f7ZG7dxJ8rM9fFfurO6EUFjBdcMNzFwrI3hTwNvI/aPgq2tdKCgdU3/ZCl3CDg9WAuLpyLUd2fE94rmGqq6VBaynegcleyAdXz562ZMualF10/D3/96ArY8dPVpSQvGmK3AVpqg3O0MWmhNl6uaRKas+5FTbplsl+BwLgQShqVBiVNeM64fABmS+EhRtDbQz1S4VGC4relgYYAjBcKyq3xnJJjcRKh9dHZGzWewZsw0GheP2T4wO3aXn90/OJyi9Xub+K/X0MKycvJls+iuPfM/8eurcrroqcWiaqGNTvzLWWN9xcoqqTpoXwB3uDXtZrmoz4A5hY9yTxtMX/IKpwpdQLJcTaIbEmSTa9oRRHx3JrWwqTtHt0Uoh7EMXJlsYZcsmtpZWylvJK/EdF9HSS0v6No1LzQqjbL5RHkj/5bYvR6T/RyBibpDTdftJFxWvI/wM
Browser:
Chrome 108.0.5359.94
Operating System:
windows
My solution
set minimumPixelSize: 1
![image](https://user-images.githubusercontent.com/15715364/206109731-57193f1e-e3d3-4446-814d-2e5545af3020.png)

**Comment by ggetz** [comment]
Hi @lewhonly, thanks for the report. [I modified the Sandcastle a bit](https://sandcastle.cesium.com/index.html#c=tVZtbyI3EP4rUz4tEjVwSe5UjkRNQLme2vQqQU6VSnUyu7PBitdGtjeEnvLfO7Z3yfJyH1BEJCJ7bD/zzONZz6RaWQdPAldo4BIUrmCEVpQF+xpsyayVhvlIK8eFQjNrdeD7TAEIlesb/TyAnEuLHW+yKDF1QqvPKhMpd9psrS54pld2AM6UtUWXMrtWouAOm/YUFd7pjGz9YOh2g+ls/EXJdYU5Uy/tjzM1U9yuVQp5qYJrSA0Smj8tk9LIDixQPCxcO7KOobIAx5ZGFMKJJ7TMYKGf8FrKJIICpEGapbYiwF7Wwoy4cTTi6ozlRhdjfDCINvFHAH7uvztjvQ/n5+/7v3Si6fyc9S56Zx967ytD5OPH3hVR4gYKT/eOOyOeXz1NDVc216awDLl1f2rjFvfLqb4Vz5jdGl5gUtPbQSKMHwXKsyyp8INGIYhP0uXJ90gPgFSDgf/fqS1NeoPmLOx4aUf3/sdXXLi4gzTl2fovghcWPzbET4m54czPbnRJqaIeJssFGkziufmWscZ+8dcSL0UvfcyWovzHr1XEHT67Acxa18KkhueOMjUu0NaQmIPXJEnasAm3mTC1jRy2GOtOeLGUOOaOdwM1243SkYtq9I2G7EHON87830Wv12O9eh4DIJmiWJ0DlMdGKzwh34DfHO9R7l8cx/iT8ZcEX3EhUnka6tFF5WF7tkf/GOq/aQd0a3DDpdRanVD2ysP2bF/6Y7PlTshHmJoyfTwhd+8k+Nidv0n7yaNQCjMYLbjhqQvl5GQR8Fr5bzR8E+17JelVo2p3ErqEGxxsBsTV5Ts5cuR7wlMNI10sDVpLegcmJyEfXL16OpAtO6EcE8fv07/fNcM48pMVOSQ/VcXulmIqDY7RxRaF2XK5pIpqb7gVNmmWy3YDAmAlFLUtjEs0riGHF2S6EBbmhpoa6p4yjRYUvS0VMARguFdUdo3lkhqKTRw+PiJjZ61XwFoOkuLtT44Xbt/y9qfnM5VfrlJ/Faf7GDZOtiYHPoqLHzP/N3RxE66ylFonqhjU90y1lnNu7lCVSdVC+IOtTmvW2jQwEWho3VriVY3/qyjClVJPlBBrh8SaQrLdOaU4OpZaW1MYdptHh5l4ApFdHmijIZXcWlrJSykn4j8qolfDLu3fOyo19+3QF8ojydd+26J/9Uc0MsaGXZoePulixDvI/wM) so you can see that the model loads in and is briefly shown, then disappears. It also seems to happen inconsistently when choosing models from the drop down list.

@ptrgags or @lilleyse Any idea what may be going on here?

**Comment by lilleyse** [comment]
Yeah, it is strange that some models work and others don't.

Might be worth checking 1.96 or earlier to see if this is a regression with the new Model.js. @j9liu would you have a chance to look at this?

**Comment by j9liu** [comment]
@lilleyse This does seem to be a regression with the new `Model.js`; I tested in 1.96 and `Model` works while `ModelExperimental`. I'll take a closer look soon.

**Comment by lewhonly** [comment]
Thanks! It works well.
