### ISSUE TITLE
GlobeTranslucency

### ISSUE THREAD

**Issue by FM3631** [CesiumGS/cesium#10947]
GlobeTranslucency Rectangle属性如何设置多个区域透明度呢？ 有没有大佬告知一下

**Comment by ggetz** [comment]
Hi @FM3631,

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.

Thanks!
