### ISSUE TITLE
Can not zoom to entities when globe is not displayed

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#10957]
The following (working!) sandcastle creates an entity and zooms to it, using `viewer.zoomTo(viewer.entities)`:

https://sandcastle.cesium.com/index.html#c=bZFRS8MwFIX/yqVPFWrSuuqw64ayPQo+THwKSNbe1WCajCTd2GT/3TTdROYogXtu7/lyeltpZR1sBe7QwBQU7mCOVnQteQ+9mEVV0HOtHBcKDYsS+GYKgNJG6hUWsObSYsLU8WbCFFNVQG60FU5o5aEn4Jwb5yuuRmRtdLvAxiDauEfdZncjko7z/CF7TPpGnpP0Ph2N04cgszRNmerxAxyVE27v0UNwErRAS3hdxyHc+fritwqgVtcoiyE/QGdEASwihC55u5G44I7TMGLpEPpZmFP14UvSyBWLeu/x/LmnAAet2zcdX8QZ9tE/URKxaNI7zwegtG4vcTYIgCfRbrRxPpSMfSKHPhH3C6OrrvpCRyobeMFJ/1rLWmxB1NMrfwoqya31b9adlEtxQBbNSurn/1ml5rVQzesWjeT7fuwzm70MTUJISb287nRayxU3F+Qf

However, when UN-commenting the line that sets
`globe: false,`
for the viewer, it creates an error message:
```
TypeError: Cannot read properties of undefined (reading 'ellipsoid')
    at ModelVisualizer.getBoundingSphere (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:143767:29)
    at DataSourceDisplay.getBoundingSphere (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:146162:32)
    at updateZoomTarget (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:217126:47)
...
```

This is caused by [this line in `ModelVisualizer.js`](https://github.com/CesiumGS/cesium/blob/828d6799916196a6f9c79dd8e5b001d58305e093/packages/engine/Source/DataSources/ModelVisualizer.js#L382) that accesses the globe and its ellipsoid:
```
  const globe = scene.globe;
  const ellipsoid = globe.ellipsoid;
```

Note: A fragment like `const ellipsoid = globe.ellipsoid;` appears in several other `*Visualizer` classes. **Some** of them do check whether the `globe` is valid. Others may not. This has to be investigated. (Another questions is why obtaining the bounding sphere of a model requires the `globe` and its `ellipsoid`, but that might be beyond the scope of this issue)

**Comment by gaurav8y785675474** [comment]
hello javagl
In which file i can find the code related to this issue

**Comment by javagl** [comment]
@gaurav8y785675474 I pointed to the file/line https://github.com/CesiumGS/cesium/blob/828d6799916196a6f9c79dd8e5b001d58305e093/packages/engine/Source/DataSources/ModelVisualizer.js#L382 , but mentioned that there may be _multiple_ files or places where the same error could happen. 

As part of solving this issue, someone will have to look for places where `scene.globe` is accessed, and make sure that the case that the case where no globe is present is handled appropriately. Basically, 
```
if (!defined(scene.globe)) {
    // There is no globe. You'll have to think about what to do here. 
    // (In some cases, it might be as simple as using a default ellipsoid.
    // in other cases, it may be more tricky...)
} else {
    // Do whatever you want to do with the globe...
}
```

**Comment by javagl** [comment]
I'm not sure whether this issue should be reopened, or whether this should be traced in a new, more general issue. 

(For now, I could only describe that general issue as: There are quirks when `globe=false`, and various places. And someone should go through the code, and review this. This may even start pragmatically, by doing a full-text search for `globe.` and make sure that there is a `defined` check *each and every time* that the globe is accessed....)

Specifically: In the demo sandcastle of https://sandcastle.cesium.com/?src=3D%20Tiles%20Photogrammetry.html , adding a `globe: false` will cause a `TypeError ... undefined`.

I know, one can argue about that, and maybe say that setting a `terrain` together with `globe:false` does not make sense. But this is not apparent from the documentation, and even if it was, it should be handled by saying: "ERROR: That doesn't make sense" _at construction time_, and not at some random later place... 

What's particularly surprising is that this is caused in the line https://github.com/CesiumGS/cesium/blob/cd5d6087d4c605a5a81da1a38894792350628df3/packages/engine/Source/Scene/Scene.js#L4402 , which could trivially be wrapped into a `defined` check, and a few lines _above_ that, that exact `defined`-check is indeed applied!
