### ISSUE TITLE
Mac M1: Box entities "dance" as camera moves

### ISSUE THREAD

**Issue by jonathanvhive** [CesiumGS/cesium#10953]
Hi all and @ggetz ,
My name is Jonathan, I'm the head of web development here at vhive.ai
We are also affected by the M1 bugs. Specifically, our box entities "dance" up and down and are shown tilted as the camera rotates. We are happy to share a video privately.
We are looking for a better workaround other than asking our clients to turn off chrome hardware acceleration in settings. Is there a viewer configuration in code which disables hardware acceleration? We can selectively use this based on browser reported OS.

Thank you,
Jonathan

**Comment by ggetz** [comment]
This is likely the same root issue as https://github.com/CesiumGS/cesium/issues/9417, which has been reported to webkit and is waiting on Apple for a fix. Unfortunately, I'm not aware of a workaround as the bug affects the double precision implementation fundamental for many of CesiumJS's features. 

I'm going to close this issue as a duplicate, but I'll add your report to the original thread. If you disagree, let us know and we can certainly take a look at your video.

>  Is there a viewer configuration in code which disables hardware acceleration?

As far as I'm aware, this is a browser setting that cannot be enabled or disabled through code.
