### ISSUE TITLE
entity can not be added after scene.primitives.removeAll

### ISSUE THREAD

**Issue by freyafuuu** [CesiumGS/cesium#10982]
Sandcastle example:  https://sandcastle.cesium.com/#c=1Vr7Txs5EP5XLH7aSKnZZx6UVkchPSIBQSFtdXdUyNl1slad3cjrQOmJ//3G+95k82hLjrYSsGuPvTOfZ8afx3XDIJLontEHKtAbFNAHdEojtpjhj3Gbdnvgxu+nYSAJC6i4PWi8vg1ug8kicCULA0Q87x3jfBwS4WkN9O9tgNANCTyXRJJT7FGXE0G1slgyA0q/i2kgmWQ0wiCjxeMRmocRU9MfZfqcEiHhiQQWnohwdkangtJIe9V2sNNtt9tNZOtYtzodq9FMphhnnztC6aQIsRmZ0iN0e4DxYfwcHSbz312E0/AuvKeCk0c8D6a3B+k0T/HfJ6XzU8XwiMrcomsRzqlQRmyAoH7AbwIGOjxEHp2QBZdHaBHAI3iDl00V+eHDEZJiQcuCWe+cfaV8MJkAAEdlH8vNMDW9iV45eqP6GdWqN7JZ6CPdNIelgckgn/5q1Cnih4J9U57MB4JNWQHo+VIHPu1djXrDujnu1bK5KzN8rDTjd4PRaHBZNSeZM4cMhAF9U+lbljKwnom4IQ9FsejqDV/0L3vVAZ/O+6NeNkSEklRc5ZJIH1/37wYfe8O794MPw+pgvfga4WwKS3rylUV1jvZ3bziow+OBedIHtXV9i4/4lE196DCdjYJr4831STCl3xdya8dkUefGCTAOukdIgM8QhJm5RTBmLVlM5g2Wrv5lK7C/vFUYms8NtiZG47zptRLL33DsnyBmYX2pJ3ZL6Kn4ZeyF+IFJ/4TPfQLBaDo1OZN9K1ajH1xSScXGlFknv7+12/9ugmIIMkvSlFm7YKk538JwNgq1xMpVQMHIS4giNucFTtHmbXhVvgooB90/CA6I7mTY62LkhLiMg5qro7MePGWTeMiL7niphau4P49OHR1DirMcbNg7KFMCbY8KGWYTEi+2Wz+r0VI8qyTx7vGMRZIELt0UyVXJX4r1VL2zWdmhC5UrtOOKEvGeiBsQIUIzsEMVwGovV89tRUGcxjb0JsTbDbyq4G9FnxGkOBJEfOHSwH3cCc1sIEIJrsW7Arja2y69A+TZy1bow5hJ7gT+smgSl0AlZiyimHCu/ZN8LDVmSKNwIVyKJ1S6fl/BpO2EWKb0jvNUvTYZ/LmBpU8DLbdTS4Qb2RoC8TqJsgOf2lsi5PIwghcZ5oFfrH0zH8UCV1AS0TKZR/CBRFllTIlcwFzSZ1FK+ZI5qlvEedwDu0Si3z/GZ5wIp74df1MRDZdI6hVTR004d82JgFZEckOmVGZ2JIM3hMazBEd9eOQBkhtV8s7vPnsUQ7/ryJENe8pCIPHXXwUT/SUx2e0oqrL4q6qjNuqnuNl5hyiGq7ylU6u51LL07tBWpaV0Tiuy209m1x/VxKjTZMndnuqpKhFfqNiZqC5JZ/ueymGeB3kAfIDwUm5AY0hQnspKkAQRGUN2TdwOslfSJDmJ8C+zdz74TNIbn8xBgeqeGQvcLMZDOo01Ka3muxAOzCyYDqkLSz3lVLO7oIEFzKOjfoolWVs+2BfNtFXkWF1VfHkJHFoGULD1OJSjXbXE1SXF1I2EtumNfQHTjlOKbbwYMOCiHWWjrX52AEahouPu/wGNFftM+6WgMQEaQwenMRV/NzcHz7B3tjccujEOzkvhYOgqEOJfO2SRv3oXF4NPazg2B2IoqRCEBUCS75lHxevSNuCxiIw5PaNz6Y9oJDfsAcui2QawNHtR+1n9LFrTVZSvFK2V9FMouDdKZLTKskawtVI85eFYKZZqcjIFuUimA2AyVcd5xmOZYZrY6DqwFHYLHgzneU60CcUe0gkVNGYJGd2qtuPTi5PL67vR4O7P4eDD1Vk+fnlBCrpxtZiNwejrwU1/1P/Yu+tfve9f9Ud/bYiXBFiXzGAXx0Cm1I1TBpQHk7MgrWTXV/vzOqtpOW2n3cKmbRm2acMukHdZbdu2jTZ2WrrdaentTqkY63SMjt7GHcfp6la7bVSLsMA/YQFXFTinRAXONYMj2TCEs182n4O7XVPvGIajwxd1u+0Uaui4pVtmx9Rts9vptEyjONOC2tBuWLpltGy92ylrUYRUKTbAm0ZhyMdEXNJgkRw9U9Ak/SqVGyhylPtJvvpw/KIc4v0IFYfDRuFElUWZCzYDR70H7xV0BjTqBCzNzhFo6covby5p6YM/ceVTK/d+JW9o1uh+Q8tF6nlerwfqhuJIBb33YdK6y7zNxq2/0dti5ml8L1Fr6T6s23B1stnAjfcn25aSfStbCGlyFhe9dzVwzV3BlhVZd2GwRVkVM7O0MF46Ueyq65oy/NbQqK/FbwM2vpkZP2bVDy/NwjsDu1y03QLpauV2i4Lvifcz+i2XRTert1ob3aJdWrv6cf1Wa4ebNawvIG53x/j4+4POuHLQ3u6KNaftLVqeJXQgPlrH1Ah6IokefBogYHCzOY1LgVOh6Oau2q/yw82q15HEqt6fE95YGi2o8oA3qwqkSTUlJRP+eB7OqKbX8/xqplUSbIK0lCikd9raEu9s5Jau5aV1JLaO8+b35tX63m58dUJ4RJNKDXAMeDhoHqR3edkPQseRfOT0bQb/H2w2D4VEC8E1oJqSzuYcqHN0OF64X6jEbpQ7zfFheeixx+4R897U/Gci5SdRBD2TBedqx7g9eHt8CPIrQ3kYM69BUjFXYr7x9iJpxBgfH8Jr/UiZ8KWlmf8D

Browser:  chrome 108.0.5359.125（正式版本） （64 位）

Operating System:  win10

**Comment by ggetz** [comment]
Hi @freyafuuu. I'm entirely sure if what you're proposing is indeed the expected behavior. Generally, we recommend not mixing the Entity and Primitive APIs. The Entity layer adds items to `scene.primitives` under the hood in order to render. When `scene.primitives.removeAll` is called, its destroying the Collections that are used to manage the entities' underlying primitives, and therefore another entity cannot be added.

I'll close this, but let me know if you still see an issue here. Thanks!
