### ISSUE TITLE
Update Custom Shader Guide for voxels

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#10995]
First of all, I was excited to see that #10253 was merged yesterday!

I noticed that the `CustomShader` guide hasn't been updated yet. Since voxels have metadata, statistics, and grid coordinates, it would be helpful to document these shader structs/fields

**Comment by ggetz** [comment]
Closing to consolidate with https://github.com/CesiumGS/cesium/issues/11832
