### ISSUE TITLE
About function Primitive.getGeometryInstanceAttributes

### ISSUE THREAD

**Issue by renyanxing** [CesiumGS/cesium#10998]
![image](https://user-images.githubusercontent.com/44050141/210479937-c3c4342a-ec7e-4cbd-8048-ddc66d936057.png)
pipeLine is a Primitive instance. 
data count about  100,000.
i want change geometryInstance's color attribute;
First call changeTest(),It takes 33 milliseconds;
but second call it ,It takes 3283 milliseconds;
I want change geometry's color by custom condition,How can i do? Thanks Thanks Thanks.

**Comment by ggetz** [comment]
Hi there,

I would suggest reading through the [Geometry and Appearances tutorial](https://cesium.com/learn/cesiumjs-learn/cesiumjs-geometry-appearances/#combining-geometries), particularly the portion on [PerInstanceColorAppearance](https://cesium.com/learn/cesiumjs/ref-doc/PerInstanceColorAppearance.html).

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by renyanxing** [comment]
Thanks!
