### ISSUE TITLE
multi featureIds can not be identified in custom shader

### ISSUE THREAD

**Issue by insar-dev** [CesiumGS/cesium#11026]
I have two feature ids in gltf
![image](https://user-images.githubusercontent.com/1676595/211268315-9040b59d-6439-4dd5-a2e8-83bd727ed2ff.png)

but in custom shader, it can not identity feature_id_1
![image](https://user-images.githubusercontent.com/1676595/211268571-e5a13929-7b55-464d-a07c-1944a6e0b82a.png)

i find feature_Id_1 is stored in attributes.
![image](https://user-images.githubusercontent.com/1676595/211268796-233a56c9-e397-4a12-b5ba-59263a0825c5.png)

and the type of feature_id_1 is changed to float, i declare it ushort in gltf

the doc says i can get feaure id by :fsInput.featureIds.featureId_1

![image](https://user-images.githubusercontent.com/1676595/211269514-d781fbeb-3d66-4370-a96d-bc0f4dff78f2.png)
 

Sandcastle example:

Browser:

Operating System:

[gltf.zip](https://github.com/CesiumGS/cesium/files/10371681/gltf.zip)

**Comment by insar-dev** [comment]
i find another bug, i set feature_id_0 all value to 0, but featureId has value > 0. it seems use the point index as feature_id_0.
![image](https://user-images.githubusercontent.com/1676595/211301467-02055c35-ef2e-42dc-af14-ffe8b338215e.png)



[gltf.zip](https://github.com/CesiumGS/cesium/files/10372885/gltf.zip)

**Comment by lilleyse** [comment]
Hi @insar-dev - I was planning on looking at this but since you closed the issue, I just wanted to check whether you're still seeing a bug in CesiumJS.

**Comment by insar-dev** [comment]
@lilleyse i have resolved it. there was something wrong in my gltf.
Thank you very much.
