### ISSUE TITLE
Cesium is unable to dynamically import https

### ISSUE THREAD

**Issue by csgibson** [CesiumGS/cesium#11028]
This is the import that fails in esbuild (via vite):
https://github.com/CesiumGS/cesium/blob/27abb992eb5a434f1c9391f5e926643473ebc985/packages/engine/Source/Core/Resource.js#L2069

Background: we are migrating multple apps from a webpack + google closure compiler toolchain to one based on vite. Esbuild (which vite is built on) fails to resolve this import statement as it parses all of the modules. 

The [node docs](https://nodejs.org/docs/latest-v16.x/api/https.html#httpscreateserveroptions-requestlistener) recommend prefixing like `import(node:https)` and this fixes the issue for us. 

Note: there are others as well (i.e. http, url, zlib)

**Comment by ggetz** [comment]
Thanks for the report @csgibson.

> Esbuild (which vite is built on) fails to resolve this import statement as it parses all of the modules.
> Note: there are others as well (i.e. http, url, zlib)

Would you mind providing the exact error message to be clear on what to address here?

We handle this when building with esbuild by excluding the known node libraries with the configuration
`external : ["https", "http", "url", "zlib"]`.

I do see your point about explicitly prefacing the node modules for clarity, though I wasn't aware that this made a difference in the module resolution.

**Comment by csgibson** [comment]
@ggetz thanks for the tip, the team tells me that it works for our configuration. We'll remove our patch and run with this config for now. 

I don't have the exact error, sorry! I should have grabbed it from our internal system when it was relevant 👎 
It was a failure to resolve `https` though.

**Comment by mioxs** [comment]
remove loadWithHttpRequest function，
not support ie https://caniuse.com/?search=XMLHttpRequest
