### ISSUE TITLE
chrome console warn  Canvas2D

### ISSUE THREAD

**Issue by dslming** [CesiumGS/cesium#11025]
Sandcastle example:

Browser: Chrome

Operating System: windows

warn file: LabelCollection.js

warn info:
```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true
```

fix: 
```js
function rebindAllGlyphs(){
-  const ctx = canvas.getContext("2d");
+ const ctx = canvas.getContext("2d", { willReadFrequently: true });
}

```

**Comment by ggetz** [comment]
There was some conversation started about this in https://github.com/CesiumGS/cesium/pull/10873.

**Comment by mramato** [comment]
There are likely multiple places throughout the code that can benefit from this. Given the browser thinks it's important enough to show a warning, I would suggest looking into this and seeing it if actually improves performance.
