### ISSUE TITLE
Voxels - render sharp edges

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#11020]
One of the visual quality improvements we want to tackle next is rendering sharp edges for opaque voxels.

It's possible to approximate sharp edges by setting a smaller step size, but this hurts performance and may cause the ray to miss the dataset completely if it exceeds [`STEP_COUNT_MAX`](https://github.com/CesiumGS/cesium/blob/b68be0e5dbb42652ce64a3c54b482f571007b07f/packages/engine/Source/Shaders/Voxels/VoxelFS.glsl#L11) before it hits a non no-data value.

`options.jitter` was added to improve the visual quality, but it's still not great.

No jitter|Jitter
--|--
![nojitter](https://user-images.githubusercontent.com/915398/210655394-f203a11a-e241-4926-8405-2c332057cd59.png)|![not-sharp](https://user-images.githubusercontent.com/915398/210655396-034e93fa-8372-4612-be4a-47917d52f3d3.png)

This isn't always a problem. For example, if a voxel is on the edge of shape it looks nice and crisp. That's because the ray casting starts from the point of the first intersection and the math to determine the intersection point is fairly precise. It's only when it starts traversing through space (i.e. `noData` values or translucent values) before it hits an opaque voxel that the visualization becomes non crisp. You can see that near the top of the screenshot below.

![sharp](https://user-images.githubusercontent.com/915398/210658606-842b3f1d-5e51-49aa-8280-79c835cd0237.png)

Option A: Since we know the intersection math is precise, one possible solution might be to step until we hit an opaque value, then do a ray intersection against that individual voxel. That will give us the exact `t` that the ray enters the voxel. One problem is that if the step size is large enough it could jump over the corner of the voxel, and we're back where we started.

![IMG_20230104_172354962](https://user-images.githubusercontent.com/915398/210661833-d6005041-e595-4245-855c-2160030108ff.jpg)

Option B: This could be extended further so that we don't do stepping at all, and always do ray-shape intersections even through empty space. That's what the bottom ray is doing. I'm worried that this will have terrible performance for cylinders and ellipsoids because there will be many shape intersections to get to the first opaque voxel.

![IMG_20230104_172345782](https://user-images.githubusercontent.com/915398/210661831-49c60b03-0d97-4d68-800f-b025ef263504.jpg)

These are just starting points for thinking about the problem, need to try some stuff out to see what works.

**Comment by lilleyse** [comment]
Another good thing about finding the exact intersection point is that we can easily determine which side was hit. From there we can compute the normal and do shading.

**Comment by jjhembd** [comment]
Resolved in https://github.com/CesiumGS/cesium/pull/11875
