### ISSUE TITLE
I found a bug maybe?

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [CesiumGS/cesium#11043]
Watch this video, please. https://twitter.com/peace_engine/status/1615317374009511937
Notice that when i click on the map, it draws a dot. (normal)
But sometimes, in between, the dot gets rendered somewhere else, instead of the location i clicked.

File: [METAVERSE-DAO_CLOUD-ATLAS/Cesium.svelte at master · worldpeaceenginelabs/METAVERSE-DAO_CLOUD-ATLAS · GitHub](https://github.com/worldpeaceenginelabs/METAVERSE-DAO_CLOUD-ATLAS/blob/master/src/Cesium.svelte) (well commented, dot and sync function at the end, its JS/Typescript but nothing Svelte specific except the bind:value )

Can you confirm and reproduce maybe?
Is that a known Cesium bug maybe?

**Comment by ggetz** [comment]
Based on the video and your app code, it looks like you're seeing an issue with the `pickPosition` function returning the wrong position, right? 

If that's the case, you're likely running into https://github.com/CesiumGS/cesium/issues/4368. The workaround for your case would be to use either `scene.camera.pickEllipsoid` if you don't have terrain or `scene.globe.pick` if you do have terrain. 

I'll close this issue as a duplicate, and add your report to the original issue. Thanks for the report!
