### ISSUE TITLE
The display effect of entity.path is strange

### ISSUE THREAD

**Issue by webdq** [CesiumGS/cesium#11057]
I added 4 coordinate positions，then created a model entity with `availability`  `position` `orientation` `path`

but the `path` is bent at the coordinate position

![Snipaste_2023-01-31_17-45-29](https://user-images.githubusercontent.com/17735764/215725412-e4716261-62dd-443e-a663-19f72942437c.png)

[code link](https://sandcastle.cesium.com/#c=nVVrT9swFP0rVj+lI3LTVtpYKGiooD3UqRVFmyaCkJuY1MKxI8dpKaj/fdd2kgYo7FGpie378LnnHjuxFIVGK0bXVKFjJOgajWnBygz/sGte1IntfCyFJkxQFXW6R5GIRGwjc1kwzWAIwVeRQOgRcSlSpsuEhqgffPARJ7qaDgMfLSlLl9qY4Ie2/p6Yw/+I+fjvMf3gDzGRuG5VWmiiNFRZ0fOt5IyIM6IpvlUyMwPPsGcHg2Aw9AN/2Pf7QdfQVaeQ+b9nGLYy5ErmVOnN01bNSZZzmsyqXswqJ8/E1RG4oPqr0FTl0hQtxTS3ffMeDTOsbTmjqaJAycB/YTrlqVRML7Ow3vsLVRnTdCb5RsiMEX6aw5b3LLP+kdgaELdSIY9TjRgAD47gNdopB3MqUr2E1YODLrJwXLGaZXQvXSRJ5hR8ksIz3sj1xndjht6h94F9VCstpnZJvK4xGnD1do+NOHa6qDWxBRwN4Ct23Qqrl3dIxwAGRkQMXWMtnYX3RnoHo2mVqc+21DMU+M0Wzs383YHFVEAeRgsT4RqJGuewGfm1AVoZosoN5uye8jl7sOfHr1djyaVqujs2M3xxfubMW/OyHd2ag1GhiLmM77DtwaVrmR2bdUGtCJ85yrzxk/lrbnGpFNT3Nxnt84KItCWXcbOGJ9Pp7GZ+OZ3t4gyvHG4z/CBldik9JyCLp327WX7NYXuVb7IijJMF4+AXtpVmcNvztiIcWOQ0Nq3wrl5Isu3oNc2xgMInwkYWXmifVTushq+71qHV90pHdhmOK6AmztK+3ikQBKCnO3tzb9QJXOJMJpQ3uikVC1HUwbjnJApnifSsS9FzqU+ZqkY3MMQpX0SdqoSMCZaV2aylvMFhbSP3xjaPCTd3j7mCrcVd3TnRywaDooXkpSup34QDhXD9PCnS3EqmzZ+5XH+vHJoqG65TsM4k9DdEAe6/eRJ+nU8m0581+5XrmiUGXD+o4W6dhirRVBJzWnKWjt8ZFXrD6Um92SeW5RK+L6XiHnCrKXALgIveoozvKCi/KNzpR2jUa4eOErZCLDne851GMSdFAZbbklu6o87JqAf+L0K5JAkT6XRFFScb47bsn0zcIsZ41IPp/kgtJV8Q9Szzbw)

**Comment by ggetz** [comment]
Hi there, would you please explain the importance of using `HermitePolynomialApproximation` for your use case? I notice none of the other interpolation algorithms are resulting in this visual.

**Comment by webdq** [comment]
> 

I'm a novice and don't know the difference between these three interpolation algorithms，When I switch the algorithm `LinearApproximation` , the display is normal

**Comment by webdq** [comment]
> Hi there, would you please explain the importance of using `HermitePolynomialApproximation` for your use case? I notice none of the other interpolation algorithms are resulting in this visual.


I'm a novice and don't know the difference between these three interpolation algorithms，When I switch the algorithm LinearApproximation , the display is normal

**Comment by ggetz** [comment]
Thanks @webdq, I would suggest using [linear](https://cesium.com/learn/cesiumjs/ref-doc/LinearApproximation.html) or [lagrange](https://cesium.com/learn/cesiumjs/ref-doc/LagrangePolynomialApproximation.html). If you have additional questioned, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
