### ISSUE TITLE
Imagery Layer Manipulation Bucket.css

### ISSUE THREAD

**Issue by tiqvahub** [CesiumGS/cesium#11054]
Hi all,

I am trying to reproduce the project showed in the [sandcastle](https://sandcastle.cesium.com/index.html?src=Imagery%2520Layers%2520Manipulation.html). I realized that the [bucket.css](https://transfer.hft-stuttgart.de/gitlab/sven.schneider/urbanvis/-/raw/908e4819e0b1fa82905b101afe1366daa3588003/public/templates/bucket.css) is crucial to have the layer tree displayed. However, I'm unable to display the layer tree by replacing the bucket.css in sandcastle by the one I aforementioned. Any direction on this aspect will be very appreciated. Is there any another bucket.css file that I must consider for this project?

Julierme

**Comment by ggetz** [comment]
Hi there, in that particular example, there is some additional CSS defined in the `HTML body & CSS` tab:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/4439461/215187265-5e1dc1a1-8575-47be-9c6f-e0211f145982.png">

Perhaps that's what you're missing?

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by tiqvahub** [comment]
Hi @ggetz,

I got it. Thank you very for your valuable time to answer my question and sorry for posting on the wrong spot. I will refer to the Cesium Forum next time.

I appreciated it.
