### ISSUE TITLE
Primitive getGeometryInstanceAttributes _perInstanceAttributeCache

### ISSUE THREAD

**Issue by verybigzhouhai** [CesiumGS/cesium#11066]
Hi,
    I need to load a lot of line data in cesium. In order to improve rendering efficiency, I use Primitive After loading, I need to modify the color of all lines, which means that if I add 5w line data, I will execute the Primitive.prototype.getGeometryInstanceAttributes method 5W times to get the corresponding attributes to modify the color.
     I encountered a strange problem. When I first modified the color of all lines, the speed was very fast, But when I changed the color of all the lines for the second time, I got stuck. (The order in which I call the getGeometryInstanceAttributes method is the same as the order in which I add data. This is also why I don't get stuck the first time, but the second time.)
     Through debugging the code, I found that the first time I get the corresponding attributes, there is no cache. The second time I access the cache, but the speed is slower. The main reason is that I call it in sequence_ LastPerInstanceAttributeIndex, which can quickly calculate the location of the division id.
    What I want to propose is that the cache here uses array storage, and the index is consistent with the index of the original ID. Each time you get it, you need to calculate the index first. If you want to get the attributes of a line, there is no problem. But when you get the attributes of a large number of lines, there will be performance problems. Should you use the id as the key and use object or map to store the cached attributes object, so that you can quickly get the cache through the id and reduce the cost of the for loop.

> like this:

  `this._perInstanceAttributeCache = {};`
    ` ... ...`
    `Primitive.prototype.getGeometryInstanceAttributes = function (id) {`
    ` ... ...`
    `  let attributes = this._perInstanceAttributeCache[id];`
     ` if (defined(attributes)) {`
     `   return attributes;`
     ` }`
     ` let index = -1;`
    ` ... ...`
     `this._perInstanceAttributeCache[id] = attributes;`
    ` return attributes;`
 ` }`

**Comment by ggetz** [comment]
Since the values are only being written and read from within the `getGeometryAttributes` function, I think this optimization suggestion makes sense. I think [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) provide a performance benefit over Objects in this case as well.

@verybigzhouhai Do you have any bandwidth to submit this as a contribution?

**Comment by verybigzhouhai** [comment]
@ggetz

**Comment by verybigzhouhai** [comment]
[singapore.txt](https://github.com/CesiumGS/cesium/files/10672038/singapore.txt)

test data

**Comment by verybigzhouhai** [comment]
@ggetz Refer to the example. It is necessary to replace the test data address in the code. The first time you click the button, it will end quickly, but the second time you click the button, the page will be stuck for a few seconds.
The test data is the [singapore.txt](https://github.com/CesiumGS/cesium/files/10672038/singapore.txt) file in the previous reply. Due to cross-domain problems, it needs to be replaced

https://sandcastle.cesium.com/#c=rVbbbts4EP0VwQ+NhAaUY7dFazvButm2u0CKBIk3WCAOXEaiLboUKZCUU23hf98hZcqWIqV5KB9skjozwzlzIZc5jzQV3MNxfEE58QPv55x7MJZER4n/LdE6G4UhExFmiVB69L7/fhAqylc4E5Ig/UN/C0oJM5BOCPclUZngininZ56bo7US3A/asAb2c79vRgQiGs6AdW4BRg1yy/Gct6Ep/GAeWfjd/bgOWQrp+RssPQpf+2P4m1TqESN8pRPYfP3a+l8X3VvIpMiI1NSacNJ39B7tP4y7ZIVKFzQGuT0WlXstIoyAMdG0siIiJVoWKBJCxpRjDfv9+06Ti1LFXRui4mNd8rEGPgBeUbHeUeG1DKMXZblKfJjcre/hDMH4hdCTVui2nYJIMDjmqXdOFM1TdG6WaClFeo15LFI/GHfHymUDiHPy6FR82VH49+6r3+Gio3pUE5Yi5/GVYAWDUnGqulSYAU5TU15qVPmAJUSNYj60jvxJVpIQNZUSF74hKzju1vZIY52MvMEzECyjWZGRyty0XKPrv/75+vEZuQ1kJPnxWcgU60rYeWp5n2YZwdJwhm4/Xc8+/bv4fHn9dTrrULrtcgRrLelDDiSMvGeYs6Ef1SLfjN3UabJMWohvxYKOI3WciMajXXW2ALZt6Vp1mjK13bIJ3Taz8+rm4gIXRHqvXlVztMgkTSFLNqAOurDfNNeZgFdOri0DVw2ygO3q1C1u4iq6tYzvyAC/wfA2qFeiJc16v3T3y4rohdG0iBLMV/Bnw1W1GFPt0HqgWFt5OZhDBzlYXma2vNATd10j211mptsZGwfdHwBtHb/sHoRrqovfdxxo3+OnVqo7oTSH7F3QBO0L5oXHAao7S0X5pc16vMLwwApyXfeFxafFLWY58TubdAAWSlu7No8ZdBv/iPD4qEqU0tcNJY9E1lv2rd3z573Irs8F1xgSSc57RriUQBFOicRoyYqZcOUQE6XNJQkR+UX7Pai5kyF6OzwZvhsee28H6M2HwbvBBzPvwyhRrrHFudzp7sOOTXmTYVWN15w4z5UGc1jjG5FLqKAjhzs68CKuvpetwGHKaFVPNLu6AXYjrDQjBjoTgj1g+THXGl5Z854pt31I571jz1XivuY6SnK8c2bOe8e9idIFI2eOnz9oCq8+7eWS+QiFmqQZM6+Q8CGPvhONIqVcE5yEh6KTmG6g0Z62RNGLGFYKvixzxm7of2TeO5uEgH8iygSGV8/qEi4rhgsDS07OLspNhNAkhGW7pC7paWj+Hw

**Comment by verybigzhouhai** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11069
