### ISSUE TITLE
PolylineGraphics Material Color is not updated

### ISSUE THREAD

**Issue by webdq** [CesiumGS/cesium#11070]
I draw a polyline

```
const entity = viewer.entities.add({
  polyline: {
    show: true,
    positions: new Cesium.CallbackProperty(() => {
      return positions[0] ? [...positions, positions[0]] : [];
    }, false),
    width: 10,
    material: new Cesium.ColorMaterialProperty(
      Cesium.Color.GREEN
    ),
    clampToGround: false,
    arcType: Cesium.ArcType.GEODESIC,
  },
});
```

then I will set the blinking effect of polyline display

```
const callback = new Cesium.CallbackProperty((time) => {
  const s = Math.floor(time.secondsOfDay);
  const color = s % 2 === 0 ? Cesium.Color.RED : Cesium.Color.BLUE;
  return color;
}, false);
entity.polyline.material = new Cesium.ColorMaterialProperty(callback);
```

then set `material ` BLACK after 5 seconds

```
entity.polyline.material = new Cesium.ColorMaterialProperty(Cesium.Color.BLACK);
```

but the last color displayed is not black

[code link](https://sandcastle.cesium.com/#c=pVRdb9MwFP0rV5XQEim4SaOB1C8YbTUBg6Gt8NL2wUvc1ZpjR7azKkP979hx0qZdBQ+8RPfrXB/fe5xEcKXhmZItkTACTrYwIYoWGfpVxbxlJ6n8ieAaU07ksuMPljypcLlQVFNjGmgNm2CpjYV5jNZSZFPyKAlRV1Li0lssOcDbKLpEYWDN+H1ttGO9fSxs0nF8iDXpODoTc01WlmBDkXBNdWn4uTuiyqdEIZym3m+LygUrmblZHyoXQG3Etg9aFiRwgf01++0BTTBjDzh5+iFFTqQuPc+H0bhpAiCJLiQ/gBfhCj7AAiG0DwVH2RX0YbEaOPwugDVmivg1hy1N9aYPUVj7GdZEUsyOKQkm5Lc6s+fVEGoXoeu72ey7yzRHJAxn+VxcS1HwtO+Or1NYJvMyNyOqe1w5H13Pbqez+8+Tqmxnvjs3+3XBE3stWDOsNp7SRhVTwysApUVuLd8Nyi5JMIKYePQuquILf9AkNFTAg7i+FMwoy8KduIxx6H2ME/m/YDWPFiqpN3r8EF7vWdOMtHddn2lgZvYbtGZCyKoIKWJyqbpdT3HpD9rVid2CQSh4Az0YjUYQGnUcrehuNoX+cejTzc9Z3aaWV9Vn4MZfK6bynO5RI27U6OXkbmcF08zBdtrZdSqi5+Y6otBtkbvd2m7VRHthLw6i4F0QxUEc+gEcZ3r7jCNYv8eEieQJmSdXsPSKU0vTULSPzx4eRGEYOkmd5/DXLtU4/nsaJwu4mnyt5hJc7qkteU3jRYhsLryTX40/gCXvBJ2h0iUj4+Y5fqRZLoy6C8k8hLqaZDkzZ6vuQ5E8EY0SpRrJDLtt6DClz0DT0Zlfs33DSpnMumDsnr6QZWc87Jr6V1AmcEr54+0zkQyXtmwTjW9c0Pyihl3jnkdqIYw65EnnPw)

**Comment by webdq** [comment]
> Hi @webdq, can you explain the use case for this? I'm not sure this approach would be the most efficient use of the property system.

I return `color.clone()` in the callback , it is ok

**Comment by ggetz** [comment]
Thanks @webdq!
