### ISSUE TITLE
Viewer.entities.add How to add EntityCollection for use

### ISSUE THREAD

**Issue by WaterSeeding** [CesiumGS/cesium#11073]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
I used Cesium.js's custom EntityCollection to add a Point, but it didn't appear. Please help me find the problem：
![image](https://user-images.githubusercontent.com/31184164/217195908-d181ef9d-c673-43e0-92b3-7f62e4e0758b.png)
![image](https://user-images.githubusercontent.com/31184164/217196009-5074d34f-0096-43b0-b6e9-7e736c090f8e.png)
If I directly use the viewer.entities.add of Cesium.js to add a point, it can be displayed directly：
![image](https://user-images.githubusercontent.com/31184164/217196439-ff54366a-1359-4674-8042-94667a8756b9.png)
![image](https://user-images.githubusercontent.com/31184164/217196529-0ee2378f-8581-4ee2-8d2c-9386a9d2ff47.png)
Please tell me where the mistake is? Is viewer.entities.add unable to add EntityCollection for use

**Comment by ggetz** [comment]
Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.  Thanks!

Also see [our Entity tutorial](https://cesium.com/learn/cesiumjs-learn/cesiumjs-creating-entities/).
