### ISSUE TITLE
UrlTemplateImageryProvider broken after upgrade from 1.91 to 1.92+

### ISSUE THREAD

**Issue by arye97** [CesiumGS/cesium#11077]
Upgrading from CesiumJS 1.91 to 1.92+ causes jest tests to be unable to invoke the UrlTemplateImageryProvider constructor, the returned object is empty (all default values) when on 1.91 and lower it was populated.

Running in debugger we can see there is a stack trace error now which gives 
`Error: STACKTRACE TRACKING
    at getStacktraceWithUncaughtError (__project-path__\node_modules\zone.js\bundles\zone-testing-bundle.umd.js:3573:16)`

However other constructors such as new Cesium.Resource(options) works perfectly fine, so I believe this is just something wrong with UrlTemplateImageryProvider.

We are using Angular 13, typescript 4.4.3, cesium 1.92 (error actually found at v1.101.0 then we rolled back) and jest 29.
 
To recreate, using CesiumJS 1.92 or higher and angular 13, create an angular component and then method which uses the `new Cesium.UrlTemplateImageryProvider(options)` constructor, then test this method in a jest test and see that the object returned has all default values, not taking on any attributes passed in such as resource `new Cesium.Resource(options)`.

Thanks for any help :)

There is an error message that I can get through the debugger - this does not cause an app crash but the object remains unpopulated. 

`TypeError: Cannot read properties of undefined (reading 'length')
    at Object.get (__project-path__\node_modules\cesium\Build\CesiumUnminified\index.cjs:26966:30)
    at Object.<anonymous> (<anonymous>:1:26)`

Sandcastle example:

Browser: Chrome

Operating System: Windows

**Comment by ggetz** [comment]
Hi @arye97, I'm not able to [reproduce this in Sandcastle](https://sandcastle.cesium.com/#c=bVJrb9owFP0rUaRKVGJ2gZKQjKJtXdUhsa0SdNWkfDH2JfHm2JHt8Oi0/z47oYVR8sXxuedcn/ugShobaKCWyFxAcBP8yWQQbMDYNHg3QL3r3jDpR8PBcJTEyaDrg0bVtnDRHhrGV3ESDfpRnFyPkihqwkC89rxUKu2lb5WZ/Ps+k7Rxw0uSg949aLXmDLTzJGET3ILhdYketVhAWQliYfo/r9M4r7VIX7jLmgv2VbFagJN1srCwtjIpxoZIRp1NAYi2VKpK3KoeZcklX3Fg+KMxYA1ewNbWGgz+RtxJxB1xRUyn+CL+9HwRf/bndn9qWIM28NNd0a8qz8LLpmzLBZf5nBZQQnpczT2oXJOq4HRxROnso3dC8MooztDT/Xx03T3MqU37ek0Pvy/vwRNnvtX9YfQKfQGeF/aA+ULLupw5065pVy1GtkdY383l0g2mHY1y/RIq75wM6ECwwZrD5nRkPxrMtb/t9a2SlnAJOgu77bad5EtPgcbYkhiYkR3oB05/e9KKCNOWm4Oiih1jjemwG46N3QmYeJL/PvCychvol6SDELb7RTJ4WbucFlFjvNBTx/hYOmZ8HXB2c6aGgApijIusaiHm/BmycDLGjv9GKhRhbsbf3YoIsvO0ojeZtSBCaIzd9bzSKiWWRJ9k/gc). Di you have a minimal code example or app configuration which can reproduce this error?

**Comment by ggetz** [comment]
Closing this as we're [troubleshooting it on the forum](https://community.cesium.com/t/urltemplateimageryprovider-broken-after-upgrade-from-1-91-to-1-92/22245/3).
