### ISSUE TITLE
Using primitive type instead of built-in object in jsdoc

### ISSUE THREAD

**Issue by onsummer** [CesiumGS/cesium#11079]
CesiumJS using jsdoc to get better experience, such as API documents.

Currently, CesiumJS uses JavaScript built-in object types in jsdoc, such as `String`, `Number`, etc. But now whether it is jsdoc or the front-end popular practice, primitive types are widely used, I mean use `string` instead of `String`, and so on.

eg. :

```diff
/**
 * Asynchronously transitions the scene to Columbus View.
- * @param {Number} [duration=2.0] The amount of time, in seconds, for transition animations to complete.
+ * @param {number} [duration=2.0] The amount of time, in seconds, for transition animations to complete.
 */
Scene.prototype.morphToColumbusView = function (duration) {
  // ..
}
```

So is it possible to do a replacement, or what is the reason for not replacing it so far? Thanks.

**Comment by ggetz** [comment]
Hi @onsummer, yes [its known that the primitive types are inconsistently cased](https://github.com/CesiumGS/cesium/pull/10899) throughout the docs. it should be possible to do a replacement for the jsdoc types, it just hasn't been done up until this point.

We'd be happy to accept contributions for this!

**Comment by onsummer** [comment]
@ggetz OK, I Will do this in #11080
