### ISSUE TITLE
PolygonGraphics.ConstructorOptions.`hierarchy` should accept `Cartesian3[]` as a possible type option

### ISSUE THREAD

**Issue by cmcleese** [CesiumGS/cesium#11072]
**PolygonGraphics.ConstructorOptions**
property: `hierarchy` : `Property | PolygonHierarchy`
should accept `Cartesian3[]` as a possible type option.
It's usages are currently supported like this and is included in the sandcastle examples

Link to documentation: https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html#.ConstructorOptions

**Typescript msg:**

![image](https://user-images.githubusercontent.com/2061466/217097174-ce0c60e7-9f52-4b6d-8e2f-893d94b4684c.png)

This code needs to be used in a code IDE with Typescript support 
```js

viewer.entities.add({
  name: "Orange polygon with per-position heights and outline",
  polygon: {
    hierarchy: Cartesian3.fromDegreesArrayHeights([
      -108.0,
      25.0,
      100000,
      -100.0,
      25.0,
      100000,
      -100.0,
      30.0,
      100000,
      -108.0,
      30.0,
      300000,
    ]),
    extrudedHeight: 0,
    perPositionHeight: true,
    material: Color.ORANGE.withAlpha(0.5),
    outline: true,
    outlineColor: Color.BLACK,
  },
});
```

**Comment by ggetz** [comment]
Thanks @cmcleese, I do see `Cartesian3[]` being used in several Sandcastle examples. Would you be able to submit a PR to update the documentation?

**Comment by cmcleese** [comment]
Hi, its not a error, its simply a typings issues.
The type is missing like I showed in the screenshot.

**Comment by ggetz** [comment]
@cmcleese Sorry for the confusion. We generate our TypeScript definitions from our inline JSDoc. So to fix this, the type would need to be updated in https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/DataSources/PolygonGraphics.js#L24.

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11148
