### ISSUE TITLE
where is the model.gltf after updated Cesium1.99

### ISSUE THREAD

**Issue by traveler-h** [CesiumGS/cesium#11085]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
After cesium is updated to version 1.99, the model.gltf attribute is missing. Is there any other way to get this attribute?

**Comment by ggetz** [comment]
[This was removed in 1.97](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#breaking-changes-mega-3).

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
