### ISSUE TITLE
How to get featureId in EXT_mesh_features.

### ISSUE THREAD

**Issue by insar-dev** [CesiumGS/cesium#11088]
I have points cloud tileset(3D Tiles Next). There are two featureIds(Feature ID by Vertex) in each tile.
In Sandcastle, I can't get the feaureId of the selected feature.  
I can't even get Cesium3DTileFeature. Picking result is something else.
![image](https://user-images.githubusercontent.com/1676595/219351275-08c091d4-20e0-4691-b78d-02af3fe874c1.png)

So how to get featureid?   I want to use this id to get properties from database.
Thanks.

[Sandcastle example](https://sandcastle.cesium.com/#c=rVVrb+I4FP0rFh9GiVQ50G33MUurZeljwkDaKdBpK6SVcW4G08TO2A4EVv3v48QJBZbOjlb7hcS555z7Np6HriXhGnVBsSzpDRGhFJRCWqCVyCRigiOiFGg14RaDfcFxCBHJYt0pwSPxDBydoUkDVr3Z9JqyG9bzx2u/FTBf+fzulHb9n/3n9OG+2/sNG9DX8PrZgPw8OL5sBvNB65G1kqfrT+v+6C4J5mP9OB+vH4eteHAxi5+MfTD6kz2Nxqzf7aVPRiy4GOQDtmTk81XTn4s8mNNmcDE+DdaPy+gThnx5DPenvfS2MzjuyMEw+vjQbGXka377OSJ5FHSC/ORh2h/kJ5PG7xNOBVcaLRgsQZpEOCyrguD78pszadDy3BVcE8ZBThqu4dVMRYGDIVoFXB63zJrFYEq4B8CpZAnTbAEKkzB0Jhxte7aPny5Gluz8XdgRymT8Hr124g6UaRMFHEmRdIpG+aHTOj35tdX6xT0qKC/uhNtYHaJWnCLHRWfnqJTTcoUqXbIkbBMplkDC1a2RZKpI5BVQJbAWIhkJp4Jb+QJU8yMgOpPgh30yhdgk3qxU7K/noU6axiukZ4CqWUJKr2JALELGDeRMFSNXgG0NIdeSKKNUuyinEtvPlbjhOvYN1SUy4qZdoWNxLnr37rsAbOb9h0D1BgyLoF0Ld+tavtbB5nT2Vl9L9puqVVYvZRcRJZrOkANSCrnxVNRGxIBj8aWylCRDeXEd25Z6CGeEh/H+eA+pBODDlFC4XADXHyzI2ZlTSvjC1G6zJzRm9PnD/yBXhYSLqeVpZq4TbYrgRBkvX5CTiAUkRqfKt+ivlhnspK9RasKB8GY6B/rPHTO2jQxOhWKFcl3a7fJtq7g708oiZ28OdrBV9ze9L6LcCYmZIAmnIKJDM3BlV8Wt6Rud/QAnDbMYTCGCqu2yd5AFvtQvECs4IHVIKLgZ/YvY/vP7lXjdevdgNrsxlCtee2fhf0+GC7Rx/ANZ2M/1lhy9NbqjVQq4f3k1+qvb97sf7S41jhrtcqXPC/4fLEmF1MWV7GDsaUjSmGhQ3jQzRdGYqnLK215NaYdsgVh4duDfxCyVudCMJcrieMjWph/nbc/gd2ixICHjX24WIGOyMpAijPasdd63Boxx2zPHwuk+VwsRT4nc0v0G)

**Comment by ggetz** [comment]
Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
