### ISSUE TITLE
Cesium.Resource throw error in microsoft edge

### ISSUE THREAD

**Issue by kuangyunsheng** [CesiumGS/cesium#11084]
TileMapServiceImageryProvider work incorrectly in microsoft edge, because of failed to fetch "tilemapresource.xml". It reports error "Invalid XMLHttpRequest response type."

Sandcastle example:

```
const viewer = new Cesium.Viewer('cesiumContainer', {
  baseLayerPicker: false, 
  imageryProvider: new Cesium.TileMapServiceImageryProvider({
      url : 'http://192.168.1.69/tiles'
  })
})
```

Browser: Microsoft Edge 109.0.1518.78

Operating System: windows 10

**Suggestion:**

packages\engine\Source\Core\Resource.js

change Resource.prototype.fetchXML:

```
Resource.prototype.fetchXML` = function () {
  return this.fetch({
    // responseType: "document",
    responseType: "xml",
    overrideMimeType: "text/xml",
  });
};

```
add  "if branch" in "function loadWithHttpRequest"

```
else if (
  responseType === "xml"
){
  parser = new DOMParser()
  const xml = parser.parseFromString(xhr.responseText, overrideMimeType)
  deferred.resolve(xml)
}
```

**Comment by ggetz** [comment]
Could you check the network tab with the result of the request? There could be an error with the response, so  this error would be expected.

**Comment by kuangyunsheng** [comment]
Maybe it was caused by cache. When I press ctrl+F5,  it's ok.
