### ISSUE TITLE
requestWebgl1 in ContextOptions went wrong with requestWebGl1

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#11082]
In ```Viewer``` constructor ```contextOptions``` setting
in typescrpt will tips ```requestWebGl1``` options
this will lead viewer setting webgl1 invalid

it have fixed in #11083

**Comment by ggetz** [comment]
Thanks @jiangheng90! Fixed in https://github.com/CesiumGS/cesium/pull/11083.
