### ISSUE TITLE
Polyline collection overlaps billboards

### ISSUE THREAD

**Issue by nikitakogan** [CesiumGS/cesium#11097]
Hello ,

I found an issue where I cant use polyline collection cause its overlaps billboard and there is no way to control the heights .

Here an example :
https://sandcastle.cesium.com/#c=nVRbb9owFP4rVl4GgjoByigpRatopU3a1kpIe1n2YJwDWJg4sg0hq/rfd+wQSC/TpEV5OOfzd+7H5iozluwFFKDJDcmgIDMwYrelPzzWSgLu9ZnKLBMZ6CToPiUZIYZDBt9UCvHRYF4DdD67/37fv0uy5/Z1knEfIleylGhvXkZ5PMIzJSVwK1TWcjZJduJTlqatJ+JC5soIRzEkru1nTFuUWDagS622d7DSAOZWa1Z+BrFaW9P66UwJuRgNaS/qksGYDkfdXhR1a3xEoz7iV3Q4aOJXER06PppdvsJ7yO8P6eVHj/9q+6NCpHaNmQ28ZtaqiK3ewXNVz55pYvarO2bZHXDJNGAjkiBFPRZbtoIQTzuHrewmwfWJPhOaS8f8MOGVyA83SdCLkoDwspY0CkMnGKvVBlBbSMY3J+DCp4bwAKGlkBJFDSkq4ZR8OEd71LAUBx8NNbIHbbDbLgrtIRmTywxqa2vzOAyLoqDFgCq9CvtRFLn8a1J8wNFt3qX2xuNx6I8dGSlRfkCpPEl1rpeVuvZTPOvoPzY5467KXIMBvYckmDaqmO+WVRVJMHFJTZsNnVstshUensvtNBrdOTvwUwtDwjUwC8Susfd+5whkVtjy5PLeq1/cDCu/zRl3zkFdEv5OUe9A1KtdrVW92//Y7NabtWwf93KBc10optOYHF26z69W/CrN7vk8FweQc/EbOaOogTMpVhmktwdh4v9MyH1QwsNyacDGzUt/9tRCQ/wvnFll9Xx8NU7N8u8MzbXYYn/2x6adXof2X7r6smDHCrrBxNhSwrRO75PY5kpbstOyRWloYZtLHLUJFzu+AUu58e4dFRepYTpJxZ6I9Oadt5Hg2I27JMud9H3F3ZyEyH9jKhVLcSse8JZJVjraujf9WoGU0kmI6vuWVim5YPqV5z8

is there any way to solve it by code or its a bug?

@ggetz

**Comment by ggetz** [comment]
Hi there, @nikitakogan, I think this is another manifestation of https://github.com/CesiumGS/cesium/issues/4108.

I'll close this issue and add this report to https://github.com/CesiumGS/cesium/issues/4108. Thanks for the report!
