### ISSUE TITLE
Serious accident！！！ The Earh will be disappear when you zoom out to the More than one million meters.

### ISSUE THREAD

**Issue by mainblade** [CesiumGS/cesium#11090]
On Android mobile， The Earh will be disappear when you zoom out to the More than one million meters.
The device version I tested is as follows：
1、Android:12, RAM:11G, chrome  -----This device is show bug
2、 Android:12, RAM:15G, chrome  -----This device is Normal

Refer to the video below.
https://user-images.githubusercontent.com/40046356/219537820-75080e60-067f-4393-ba9c-927022603860.mp4

Please help me , is very worry！ please!

**Comment by ggetz** [comment]
Hi @mainblade, would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. 

Also, could you please visit webglreport.com and take a screenshot of your results?

Thanks!

**Comment by mainblade** [comment]
I am deeply sorry for my late reply.
As you said,I create a Sandcastle example that replicates the issue.
The Sandcastle example contains only a Viewer,but on android phone, the Earth will be disappear when you zoom out to the More than one million meters.
I am not sure what kind of android phone configuration will cause this problem.
I visited webglreport.com and take a screenshot of my results,as follows:
![andriod-webgl1](https://user-images.githubusercontent.com/40046356/221747274-c183640f-d25d-4363-99a6-960fec7bc26d.jpg)
![andriod-webgl2](https://user-images.githubusercontent.com/40046356/221747329-f24998f2-5fe0-4411-8dc8-51a382a3cb9c.jpg)
![andriod-info](https://user-images.githubusercontent.com/40046356/221747331-3b05fe17-9cdb-426a-a05d-f87950d2d7fe.jpg)

**Comment by IKangXu** [comment]
Is there a solution?
