### ISSUE TITLE
Clustering of entities from composite entity collections only clusters entities from a single entity collection.

### ISSUE THREAD

**Issue by joshhussey** [CesiumGS/cesium#11091]
I can't replicate this issue in the SandCastle as I have no access to multiple dataset's.

When I attempt to enable EntityClustering on custom datasources that create CompositeEntityCollection's only a single EntityCollection from the CompositeEntityCollection gets clustered.

In my particular case, I have two entity collections. One that contains planes, one that contains the planes logo's. When I enable clustering, only the icon's get clustered.

It is set up such that:
exampleCompositeSet  =  new CompositeEntityCollection()
featureSet = new EntityCollection()
iconSet = new EntityCollection()

CompositeEntityCollection.add(featureSet)
CompositeEntityCollection.add(iconSet)

The clustering seems to be linked to a particular datasource and not a collection, I see no way(at least from the ref docs) to point the clustering at a specific collection or collections.

Perhaps this is expected behaviour and I am doing something incorrectly, but I thought it was worth noting as I am having quite a time creating a workaround.

Thank you.

**Comment by ggetz** [comment]
Hi @joshhussey, thanks for the report! It's possible that clustering may only be applied to one of the entity collection in the composite collection.

> I can't replicate this issue in the SandCastle as I have no access to multiple dataset's.

For the purposes of tracking down the root issue, is it possible to create a dummy dataset which replicates the issue?
