### ISSUE TITLE
Passing `children` in the `options` of creating Entity will override `_children`

### ISSUE THREAD

**Issue by i-tengfei** [CesiumGS/cesium#11101]
```
new Entity({ children: 1 })
```

https://github.com/CesiumGS/cesium/blob/05eebc7e9ad38d9f49f629b28171a63f0c82ec66/packages/engine/Source/DataSources/createPropertyDescriptor.js#L64-L70

**Comment by ggetz** [comment]
Thanks @i-tengfei, I agree this behavior appears to be unintended. Would you have any bandwidth to open a Pull Request to fix?
