### ISSUE TITLE
Tracked Entity within requestAnimationFrame() sluggish since version 1.98.1 (Regression)

### ISSUE THREAD

**Issue by tobias74** [CesiumGS/cesium#11105]
I am updating the position of the tracked entity in a requestAnimationFrame callback by setting the position object of the tracked entity like this: 

`trackedEntity.position = newPosition`

Everything is working fine and very smoothly up until version 1.96.0

* In version 1.97.0 the tracked entity is not being tracked anymore and is just leaving the screen as it moves.
* In version 1.98.0 same as 1.97.0
* Since version 1.98.1 the tracked entity is being tracked again, but the camera moves very sluggishly. 

 The browser is Chrome on Windows.

**Comment by ggetz** [comment]
Hi @tobias74, thanks for the report. Would you mind leaving a small [Sandcastle code example](https://sandcastle.cesium.com/) which duplicates the issue? Were you using the native browser implementation of `requestAnimationFrame` across all versions?

**Comment by tobias74** [comment]
The effect that I mentioned is much smaller now in version 1.102 which is currently used in the sandcastle. But it is still there, and it is caused by including the 

`            terrainProvider: Cesium.createWorldTerrain({
                requestVertexNormals: true
            }),
`
as it can be seen in this sandcastle:
[cesium man with jitter when zoomed in closely](https://sandcastle.cesium.com/#c=rVRbT9swFP4rXl9IROU00I6plGqosIvEoGs79hIJmeS0sebYne2UdhP/fSfOpSnwuCgP9rl8Pv7OdyzAkg2HJ9Dkgkh4IhMwPM/ovbN5USd2+4mSlnEJOup0yd9IEmJBa7RMtdrwBPSwTow1MAs/lRbJogzxXHzxafidg7H3oC1sb5XOmDBDYnUORcSz3yWkWJhU5SK5lDxDpNLfjeSzfx5JgeUKpdYTlUvrau5V1jJpbtUajUsEBnRUCcxymyeAjv4HGp6ehYN+41wrwy1XEp3VDSYMyzOcyVO61Cq7gpUGMF4Y0sHZ+/Ck320Au6RHB0VZsZLGknT9gsQvwBIuV1Nu43SmhPDC/gBz8N8nKc0BuT0sYaGZNEskyND0Bcb3HEnREsO9uvRucbLf3Kjs2LXEGncIWXaXQrHnYChLkrojkmXIb9SxmsW/ICEuZoctLt01/rBZVY5WzcP2pnJnKgExJE3bCck1L85JrV2bYRAYJpOYGSuAxpVqVBbMWbYWcMUsCxyCCUo2vjFZrR5wSVfisanQncZRKHk25VsQc/4HL3R60nazbeGex0yg66SHX8ubAl+ldgZL0CBjGO47d2Cns+uby8XX++uHxd3D59ndj9urCuS5VmYkK6IrMhv+2+1wcXsVF0rNZVxQ5/k1Xy15Hx+flza+JF5b9mMS4j38NsWFmhQSKtTKOypnB2E/aWwx0bmUqCFK6ZF/vk95PUjuRkWF9aHv9mN1cFoQEFbOJ1KooU5xqPW0HSMm7bkvbE5txSEJOCvT/zF/DQktrmlrslvntKJbxVQv0yFvjnJ/T4tjprB5ftXISHa6nZGxOwHjGuwjz9ZKW9S88CgNLKCqkScTPOaoC0tjY2rMUdBOHSV8Q3hy8cabS2LBjEHPMhdO5FFnPAow/lWqUO65uNuAFmxXhKXh+KY0Yv9HAW7fzrRKiUemXyD/Aw)

in this sandcastle I removed the terrainProvider, and everything looks very smooth again:
[cesium man without an jitter, moving smoothly](https://sandcastle.cesium.com/#c=rVRbT9swFP4rXl9IReU00I6plGqosIvEBmsZT5GQSU4ba46d2U6hm/jvO3EudYHHRX2wz+U7x9/5TgVYsuHwCJqcEQmPZA6Glzm9c7Yg7iXuPlfSMi5Bx70B+RtLQkymSpGeS54zCxNidQmDWD73T2MpEFMoVcxVKa0DHjbWOmlpVYHGFRMG0NEkMMttmQI6Rh9odHwSjUeds1CGW64kOpv+5kxbPDF5TFda5Rew1gAmiCI6PnkfHY0GHeCADOm4aitR0liSFS9e+gVYyuX6htskWyghgmg0xhz87ZKU5oAE7Ldwq5k0K6VzQ7MXGD9KJEVLDA/a1gdV5X73oprWS4k9bhGyHgGF6s7BUJamgaOZEMly5DfuWc2SX5ASF7PFOdTuFn/SnRqH1/PEvzTuXKUgJqQpUn2l5lWdzNrCTMLQMJkmzFgBtG6WJioPlywvBFwwy0KHYMKajW9MNqd7PNK1eOg6dNU4CqXMb/gTiCX/gw86PvLd7KlyLxMm0HU0xM/zZsDXmV3ACjTIBAO6ye3Z6eLy6vz2693l/e31/efF9c/vFw3Ic6vMWDZEN2R2/PvjcHE7FVdKLWVSURf0W748eR8entY2viKBL/sZifAdfZ/iSk0KCRVqHRzUu4OwnzSOmOhSStQQpfSgf7pLeb1I7kVVh23Rd7u12qsWhoTV+4kUamhTHGq7bYeISYfui7qqXhySgLty8z/2ryPB45p6m+3V8aK9ZjT8LsHYfd4c5f0dLY6Zyhb0m0HGsjfoTY3dCpi1YB95XihtUfMioDS0gKpGnkz4UKIuLE2MaTGnoZ86TfmG8PTsjT9GkghmDHpWpXAij3uzaYjxr1KFcn8X1xvQgm2rsCyaXdVGnP80xOvbmVYp8cD0C+R/)

**Comment by tobias74** [comment]
The problem also exists with the new 

```
let viewer = new Cesium.Viewer("cesiumContainer", {
  terrainProvider: await Cesium.createWorldTerrainAsync({
      requestVertexNormals: true
  }),  
  shouldAnimate: true,
});

```

[cesium man with createWorldTerrainAsync and slight jitter when zoomed in closely](https://sandcastle.cesium.com/#c=rVRbT9swFP4rXl9IROU00I6plGqosIvEoGs79hIJmeS0sebYne20dBP/fSfOpSnwuCgP9rl8Pv7OdyzAkg2HLWhyQSRsyQQMzzN672xe1IndfqKkZVyCjjpd8jeShFjQGi1TrTY8AT0kbMu4rdNjDczCT6VFsigDL81Oxp5LLT4Nv3Mw9h60hadbpTMmzJBYnUMR8ex3CSkWJlW5SC4lzxCu9Hcj+eyfR1Jg5UKp9UTl0rrye5W1TJpbtUbjEoEBHVUCs9zmCaCj/4GGp2fhoN8418pwy5VEZ3WNCcPyDGfylC61yq5gpQGMF4Z0cPY+POl3G8Au6dFBUVaspLEkXb/g8wuwhMvVlNs4nSkhvLA/wBz890lKc0CaD0tYaCbNEgkyNH2B8T1HUrTEcK8uvVuc7Dc3Kpt3LbHGHUKWjaZQ7DkYypKk7ohkGfIbdaxm8S9IiIvZYbdLd40/bFaVo1XzsL2p3JlKQAxJ03ZCcs2Lc1Jr12YYBIbJJGbGCqBxJR2VBXOWrQVcMcsCh2CCko1vTFarB1zSlXhsKnSncRRKnk35E4g5/4MXOj1pu9lT4Z7HTKDrpIdfy5sCX6V2BkvQIGMMaDp3YKez65vLxdf764fF3cPn2d2P26sK5LlWZiQroisyG/7b7XBxexUXSs1lXFDn+TVfLXkfH5+XNr4kXlv2YxLiPfw2xYWaFBIq1Mo7KmcHYT9pbDHRuZSoIUrpkX++T3k9SO5GRYX1oe/2Y3VwWhAQVs4nUqihTnGo9bQdIybtuS9sTm3FIQk4K9P/MX8NCS2uaWuyW+e0olvFVC/TIW+Ocn9Pi2OmsHl+1chIdrqdkbE7AeMa7CPP1kpb1LzwKA0soKqRJxM85qgLS2NjasxR0E4dJXxDeHLxxvNLYsGMQc8yF07kUWc8CjD+VapQ7rm424AWbFeEpeH4pjRi/0cBbt/OtEqJR6ZfIP8D)

**Comment by tobias74** [comment]
I have observed an interesting development in Version 1.112: The jitter goes away if the users clicks (and thereby focuses) on the tracked entity. Once focus is lost by clicking somewhere else the jitter returns.

**Comment by tobias74** [comment]
This issue does not exist anymore in 1.114, I believe we can close this :-)
