### ISSUE TITLE
Camera will go througth 3dtiles in zoom

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#11107]
The issuse is from #11062 , this morning I found camera will go throght buildings when camera is above 50m
I think this may comes from
```javascript
  const inertiaMovementApproachingGround = Math.abs(height) < 50;

  const needPickGlobe = inertiaMovement
    ? inertiaMovementApproachingGround
    : height < controller._minimumPickingTerrainHeight;
  if (needPickGlobe) {
    intersection = pickGlobe(controller, windowPosition, zoomCVIntersection);
  }
```
this condition will still fail when camera go through 3dtiles in a relative high altitude. so I think use the distance in previouse maybe more reliable.
fixed in pr #11108

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11108
