### ISSUE TITLE
Make result optional in Cartesian3 static methods calls

### ISSUE THREAD

**Issue by cnovel** [CesiumGS/cesium#11113]
## Request
Currently, all Cartesian3 static methods require the `result` argument. This is cumbersome and non intuitive when chaining multiple operations. Is is possible to make the `result`argument optional?
![image](https://user-images.githubusercontent.com/5690282/221164023-7f46a8bb-4a0a-49d2-af60-c6c97167cb55.png)

## Use case example
I want to normalize and negate a Cartesian3.
Current code:
```typescript
var c = new Cartesian3(1, 2, 3);
Cartesian3.negate(c,c);
Cartesian3.normalize(c,c)
```

Expected code
```typescript
var c = new Cartesian3(1, 2, 3);
c = Cartesian3.normalize(Cartesian3.negate(c));
```

**Comment by ggetz** [comment]
Hi @cnovel, thanks for the suggestion! 

The API was [structured this way intentionally for performance's sake– to avoid allocating more memory by default](https://github.com/CesiumGS/cesium/issues/1161). It's unlikely we'll change this approach anytime soon.

**Comment by cnovel** [comment]
Thanks for the quick response. I however see some other parts of the api (eg [Ray.getPoint](https://cesium.com/learn/cesiumjs/ref-doc/Ray.html?classFilter=ray#.getPoint)) that uses `optional` result. Is this only because of old specs and non breaking changes that this is different?

**Comment by ggetz** [comment]
I believe we enforce the result parameters for frequently used core classes like `Cartesian*`, `Matrix*`, and `Quaternion` since these are usually the abused types when it comes to performance. I do see your point about inconsistency in the API, but these cases are deliberate exceptions.
