### ISSUE TITLE
how to get billboard instance witch created by entity

### ISSUE THREAD

**Issue by jinrilong** [CesiumGS/cesium#11110]
Cesium 1.102.0 version
is there a way to get billboard instance witch created by entity?

PS:
at ScreenSpaceEventType.LEFT_CLICK event 
use viewer.scene.pick() can get billboard instance

**Comment by ggetz** [comment]
Hi @jinrilong! Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
