### ISSUE TITLE
rotating ellipsoid dose not show material and  the ellipsoid has gap after being flipped.

### ISSUE THREAD

**Issue by lxydft** [CesiumGS/cesium#11123]
Sandcastle example:
https://sandcastle.cesium.com/index.html#c=7Vn/b+I2FP9XLH5Z0KhJCKHAaLVei26nsZVx3VUnIVVucMGrYyPbadeb7n+fnW8FQtskBXU3XVWlD+L38t77fPzynutzJhW4I/geC3AEGL4Hp1iSMICfou+sac2PPp9yphBhWExr9Z+mbMr8SFMiFQo25pIowpm2kGifIqG0hJgLbwQPzvBcYCytKQPgoOdBu2Gkdiq4tvmB9pQZ27E3EDOljWIJ0Wxm/WOWMRTgPpjWPkYPndYi3WXy7P6GL9FNTClZSk5mfRBZAECgGSH91UAfXbVaiR8NkJfqjdhAgBQWBNF1G5xyYdmw5zWADbstc233YpWv+vo1zlnByH6QgDCdaiAImxcJkwuibaL4fuLShUBM3nARSLjAOmg2HxPlLyac0j9CEwPTq604pi0mwWp4v2wYSNRAev83pBZQ8YlepR9quSvpKrYmwt4IdfOnXgW7doZYXkofFGV18pwVN9PNSxkDCCNBtCNw/4nouj3YfSTM3y8t79mwVYFf5uq9gmQ8VN9JVo5knYxaOak4ydqOl+rmpP8Lyc54gHOsev7lcOC0kl2bpmEv5fuJRI0/XJ1/Gk6uLi7Pc0laTRB8N/pzCO+JWpzQ5QLpfLmpbb2fKDF2lQhxpYwBYzct/jrUUJbOodN+XQ69fA4dryzDnUy3mwqdXeMwGZ7tFwbFl8APlbFXGgW7u3cml0EhL5WoM62dwvZ5OBqdX+4DuQuNF2IzcM2V4kF16FopdDpb7dVsfcsgdoqA+LjcaW9tedeQPDuZ/Hr6+eT3fWD5jt/Tssj1OlG31oPeZp7fBris9OWlEsA5zstIvJ8Mh3uB4ZRy/9bspAobqWcncLwpCN7mSyz/OktBMLE+hUIUzeb+eU5BI737Ivu4/PBlUlTqUyhWIOnk9TDvFKDIWCdbPxzMKjR83ahXcbtpg7k2YqwBSuk18m/Hgi+xUA+WpUiAGwLLkKr60XHkUOL2j0faaxCfTmgTi+XGuUZuzNie4MRaXbe/+tekRvMVmwmmyuxTNhHxZKR9jyYVjU3jBlGJtTf7aosL7IGSO8At+crpbaX0tAZhkwRojmUz1rsa8Tm/ijn+1zIdXTMG75Wwh511nL4j8VZIdONR0f22kDj4r0JxiWdzXLFVdr0se6mzrz0rqvxgULjUjz+AJnBMr2gKvNavfCjkZQzKSyX7/Ky5XxFKtSmOV7JN8Up1KYdeuSnC9vY3RRQuLxmcpTvYiF9uu2IHW+Qs+WVeHKaqm0IZXqx3owV40bZ3Uad2PC5+4Ty44NYG8GZJrVEbSPVA8XF62PszCZZcKBAKauliqXCwpNov2bwO/VusoC9l3NQBMGiuqg5m5A6Q2dGWf3wBnyIp9Z2bkNKP5IsumMeDpl6fU6U8qjznd1hQ9GCWLZzjUfwlhHDQ1B+3ayrOdasrNiz/Cw

Browser:

Operating System:

![微信图片编辑_20230228154141](https://user-images.githubusercontent.com/67900038/221796878-3dc57961-af0f-42b5-bba5-b93dd10185b6.jpg)

**Comment by ggetz** [comment]
Thanks for the report @lxydft. I believe this is the same issue as was reported in https://github.com/CesiumGS/cesium/issues/9601.

I'm going to close your issue now to keep the discussion in one place. If you have any further input on this, please post it there instead.
