### ISSUE TITLE
ContextOptions.requestWebGl1 doesn't work

### ISSUE THREAD

**Issue by samkallon** [CesiumGS/cesium#11127]
i can run the undering example in cesium 1.96  in my local environment
i set the ContextOptions.requestWebGl1 to be true but it still come to the error like this

![image](https://user-images.githubusercontent.com/39991473/222025089-0a816983-6a5c-4beb-887c-29bbe63c9cce.png)

Sandcastle example:
https://sandcastle.cesium.com/#c=7VtLc9vIdv4rKGVDShSE7kYDDcl2RePR2KqyLcXSvVOp0S0NTLZEZEiAFwBl0VNep7LLOlXZp7LIKpv8nyR1f0a+03gQfAAKdllEMxYF9Onu77zPaYDjJM5y6ynSX3VqvbZi/dV6q7NoObf/aO4N7g7G5vptEudhFOv07mD0+11s4SeMo3mYR0l8auXpUo+Ku3k01zMQljet4u6jTsbJRKebd6fJXP+wzPN6ifJ+NtaxFj9exbPV5sCXMNMfwpVOr6Pxb9urxeFT9GgAvdezRbXuQzjLapKH5WyWjVOt483hYjSKH5IfkucNdsDio05X12nyFBn8DRGdp+N3UfYxXNzo9Emnl5ukg1JMlrVMZ6fWr9M8X2SnJycZiCMI1Q7T8WOUJTFJyx4n8xNa7/LmJNVZXlOd/Jyks8l9ufZJvdmvxeLfhyXOeRaGN+F8MdPZqcXLm5me6TEJ5DKeROMwT9JNhsdQqn7OrxZEg3k14lT/eQkUP+sv72askEe5X6VlnaYwh7VYSpFAtmGuDebbgmRQIQRbyWxJO92Mwxnsw7GVxNj34dldXFigbRRvP86SL9qe6EU+vQWK80csk+XlerBSgkNzwtRaJFGcf4hgw6+tX4p9aibuDmZJ/Bjly4m+O4BQbOZ43OOO7zDue45bSclQwm4qQseWrudz5rmu9ARXfoNuqqPHaU5Uvh0EUjLFQSi5FwSbAupG4QaO42N9xny3E4XjMSYdxpgR1S4KZTsOEzJQ0guUCgK3FwrhKq48l3vM60LhKTfwlackJrXLAux43JeeFMrrg0I6kjOfuY4vOkFI11eucn0fSmyVhWCOr4x6PdYHhIA5CPDosaAThOtJ5asAcIN2hXCyChlI3wVrvVCwQHCfpC39ThjCDVzmC+b5rB2GUEwFXHIuJJO9YPiuJ3wnAAvdKmGeCFwhFQ8C1QZDeJw7XLoM3tJLGMoHcAXzl7LTOmXgu9jBVVKqNhRKKKlcz3VcR8mgl2XAPQR3fS8As50wfIf7ju8q5QT7IwZjtnAFYDgO2QaW7YPD95nvSxnABTphcOHhJ5DYSbRIQ/jChAuXKQTDoB8KnyM2uq7qNFDX9RFnPV8K6botIQMIPVgol8JjsLRepsE9RF4vcHzZKQzYhQfMDrAEog2GUA5zpYNAKEQvy5DK4UIEiAdutzDgqSZ4Qu/7UTDfRsRwGFAy7lEU6IUjgE0xcldXduLABlAJkoovgjZpSIdCPdxa+qxf1HA5Y67LFXTaqRR4gIMNOHxA7g9egU1CFbRkgCDgi36pFTzCXV3vBRgwHxkESJ7MbbMNCIo5SkAmCOmsl7sGcHWf1mZSdsNAllBIwVL6bYWG9FABcGRIeIvok+GRIBRMOxCiM6sJ+CmD0Hywq1oxQBKwGwjNQ4TrYxlUngTI3wFqLr8bBw8QWgAYymvDoTgCIehgQohFPWC4jvAD/Ocjd76AQioPmRsoWCsKF4FWcNIKhNsHBYcEIedgMyLt8RIYnYOggGKjVRZ+wBhifeCgBO1VgLoSboLcikiuXnASAEZR0qEQ+AZXDqKxCzPqAwIxV8I6XCYQn7s14jkBCi8XZtQWuDz4KpzD8wPkpl45TQrkVbi356vu6AmTowoxUK2yQPRRcGdOpREKtD4g0A0gTwXMcd1uuwgUoouD+NlejCPjsACJBOWfizDaBwaVc+AVMdTr1giqORSKHmJCqzAgV64YCgzI1/X7oICUPaqenSDohkGxDYqjSpW1CgPrKcehnOD0SvAe3AOBEZlQdKMQwkO1hdqI+639EYpf9Gho1iTMvY95Ui2HjgL6FKwTBac8ItBTwqDbZAGcjLqSAPEl6KMSn3IUog3aqhfSKrHnI1egSGvL7kwq5FWXIzty5Os+MND8oXBA4eU53TrhDHUwSgjEz5aai9tgyfeQzpBzqOXpgwPtLswKSdHtbpGAA2VOANtQLc0Jc23UQvA4qNllcF3VAwfqARkAO7yw2zgkyk8UXuinvLauAA7nIQK5qN0VFNMHBawTLatEgfKCvyLKUW2EYpuLFuPwPWrUkM5cjzOvFwzHQXKnLCFeqLnQPziUO1ELyxZX8el8hmCaosTrBYNzn9A73OtOKNA6/odnSb/NRBkV9YgvEAqSpeploqg80YUFvDuteQIkPED/4bYdJXjIqGiuBToCNLiyFwgHJofygAqVzrYVbsI4YiT015ri4apoMDyoA3jdfgbKiUElulUi0SsinHM6lGqNoXTKFlDB4Aa9WgLlk4V65GFcvtDCI4ZzJFg0VPsNQ5hzFeqbkYJREPeJoYr+Q5pH3626TzTQm6DqF1Cf2J9dmWcLanXoJAhakb1UImB1qJKk293DA2cgHBgyEqdqiRnQhk/Htb5DEb1XQkEVg4zGmAi6YwaiOEKXw+AKrRUPuklU9hIogkD2Kv8gPcgP/QZU3n3wx4RATQV+W+I4TAPWi3GFggfhK1C9ag1kWDozQWfRfQAJw0BJEFB10mqirqB6ks5K0Sz1Sige43TUxVD+vXAwjYyDntX1meRtZ2508gL1IsEa3+5Th0o6IsfHi+JAoENhhGZQKtHaoCDt4B/VYHRs2wcHApdDtbTbXZXDBxTsGK6lXNV60ISCmXyaK4V83KdnRCL0kQS8F06FfdcP6LCUDk1alKJsRR4nAoYan+qSPqcJaKw8hCSYSCcKSYfjMA3KbW0qgdKodUbzCtn2wQA5S3AHP+muhum0jcoNl7qU1qKco2BAYYsSsV8MpfKWYjSSVvezLJQk8Gv0jJuHxxtFqAAJJOFQqyRZn+AlBMo1Xwg0jU5nDEVJQme91DiqtvKPbBwJCkaBEMb7BC+4iIL5Y2lg6YYhXO6g2FYea+0NkFchWLRT8JV+DRtXmObDPOgEsBMHOogA/TmZapu3mgwpUfmgaBa9WhTACCBn1Jc+77ZRl5pjHzlFitZDco7e1mUwEDoZLlHQx5/O7uKxeYfgOpmtHpP4faTTMB1PV/RAlkbv4voZrT0PFwP9+o3BvU1vL5bZdFA+Rv4Y5lM7T37Uj6nW2UDbNX9Delrce3bJc+dkbRccW0cWHdUTqXk0XbC3KOZsviNRLvROJ3Odp6viif+TTnP9/FOSzsPcqh+M/7Fx176+urm8vbz6dP/p6vPH8w/3559+vL+5NbJfbGE73d2uHhtUyirH34bYI4vCWNgPaTIv+T9P03D13rCWDbaXGNISxRP6gvtT1PgbjD+WzIHz/VyXz/xrIZQcDI3uZzq36OH9ptwq2kuMhPFYF4Krdjqt/6reDqDRkxPrL3//r//1b//0n//xD//9z//4l3//l2L1cLH95grUr9MonJ0vFjpM1+vPy/un+4irtzUewi9pNG68CrGMowdorfl2hGVFt9Gc3mCo3eV7/VeWLNOxPv21ui6kCA+wPv3hI7R8cX0DuOqsfgMDow+zBLZyfWkmvLaETY8NAr6HBrMvP1x9Iiqmj0VJcXLyVxP9EMW6Gr//9PmjNXBsZp1Y0ef6xQv7eVhM6CBHZLSdYbWulemwiYL4uLy9+Hz/7uLq48Xt578luGd7KX76fP7u48WnW1DIPZzcXJzfv7+4fPeeCBzbayF5+/7q+pp2cW2nheTm+uLiRxKIrVoofvp88TdmF7a5zZMeC0Pww/nNBQjomsQwwr8Avzgf7qf/+Zw4fHv14erzeprCDJrlDXfUQnNuLz9eWANmOwgwxn6swzX8YXMbGCq3knEePun7Odana0z0Rszmo2P6xZqb0Pi0fAsozIVFvn+xnOl0YPCG8eNwbbu4xa2QFaj5IIviAQhgGKNxkpV/VktX1HyberWmXu1Qi23qb2vqbw1qg3W+vvzF+VMly5DZq8NQ2Ksj/PV8GHL6JeznUTFQXR4RySGRjI5x00x5bmzwC6tXLMdZY43ViBZqkvM1gGphs9lRhcdMLvY+rjEaklG1/2q9YKrzZRrXLH4vA4yxymmIjFMIbGE11FOOAsckyQeLkREkSl3YpEAv4w93ln9Iw3FuZD0dHqLikApJXQrGxXDfxnESZXoAL92zubkTYW+QJumABjd1+0BjZr/dsSWNHT4cDoTtHHPbOXzYgQrTdY5oaB49Dyzzq5BDBJcwnCL0jCj8WMPROtiWP1ukbE1qLcl+Nye0rc7+96uz5ur4vdoSKDxvRikzih+bEp5EDw9LyNg4XzwyH7NRMbYYNt+xM0JZJF8HpOt4NBsiIji2CwwIIqPFXv1lCz1ezsJ0a3nzoctdsh2DilOKI4MMSyvi6sQaINscmouzPYDm4bMBleoHeoNwoEfxEPiMwEcZ4cSKO9LIflsVfxs0jzq/+W31NpklJVjdgKXtlQlszyi7VmbZbRjGDwkL1HBMRJz2tqorEtFRNTY8hNh2tVPnrlIsOrwvouqgsNinUTkyniaLxaoBb/lkHb0ufWX5tGXpX59MsnGOwy+ZcTxQbJFkhobGKfJtjJsRss6vTyOQjb4+7dUArU+fX5/sZ4gbHyQmTyKWFmD3GQfV10bUix0LeEj1n7FxlQ3PNkfD+aIcLFLy1nCxZUlRZOQt5yemFvbztzP8SYAp2fpya5nJyEQ2p87kViNHm/Ro5LovP64nwJqoxKAw5Zzh49VmPYJbR0fDZq02AWVD9dDGUbXf8JDEsiXRYs7R9qTjFydNadIEqCHNxm3IBuKo0vlZoYlD4jQ4M4I3wuK8MaWWN9lJcTEq4h1fb/h922rgUsfWtMUu7ic6D6OZnvxfNpA+dtBqUS0GUpWj/28gGwZSh2odNkL1YmSV+cUqE0zxqVe6/GuCfn6fDWWxngHXeAbgptg9torsdoy5Qwrbjgnia5jrSRTvyquRoDRF6dCTTUsSVpmSNGmtmWLqVLWiZDXcmURli5lU1/tHdapG7h0pp9hxu7wnDIxvLjemHUvp10uPamSjkonhthPluY7LtLcWDUlyVIiT9nIcZqS0nlzsdvR6D7RBodO1XxZrMEVGRrvtLmLyal1FEOckMY923ElEZtJOWs3Bb13zVPbziU42ZrX1FAzrRbZZXsKi6j3isgRohKbFsDH6vD1aVAQox7HsCIzjH/oJsI+VGvO+tc2r5tD8PfMIDUa2ZRAbxqJvsJK9Obc4NvkYLm4LsRQiSNKodpR0ZCXLsnncjbv5fG9KzIl9OofaGZmWghlgD2PDKZSdNxqZ6GEAmjfGiCou8uftVeb7Vplvm2w+jyYvB9j6ZGM3uJYLkKfk81H+jIA9PxlM58fTZp9pWZReNqFEk8ZwBbpYDLAXzcnEMQ29Knj+vVndG0FurWYVQpxu3v1u6Vmmt2bP986e75ndFnYbs783FoE5uNb42/wezlMfQplc+fSHp2GDcAPPOpmCagNTdROy4ya2sIbOGgqlhPq6TqyOLUy74aCCdtgGPTw9DVdbm5vjhPrIgyI534pWDVLSZ3064iCky9EWYeUhdIBX+5mZQFXCakSNJMyESODXiF4zHT/mU6qoi0AnN5bbXgnXRLc+EKGzkG0mN8JZA9ZiU+Xbbk4eTr692MuROfFcQAsg2x2Pi9xVxkyEy5080DiY27O+aTt3ZVb2t6gC1HCHTRPLd1ZqZrJNDTZzK8lxtDtclQyLEdIIQTICMSxsUVNmz+ZJkk+zXC8M0GP8kjSBTpNghsNtE2o0gu7ArGDAjkpWfTks2kFrY2LtYr+OGj5Xfk0Oqo6z2XKs47zxJb/iwP5mGk50elOc3lr18S2yaBp9Wea6NIoki+gkVfz4HgyfvUj1Ifm6h6hwxS9hPp5eTvYvgh4yb1u+UPu6JAnTFSyymPV035jXGBEYqWBdvG2jKFZujicIq3PzNb6tQHRvTLyxWR3UKJRTYBsn8wUwX5e7DrYMuQGHziZoxjyZ6Bl98fSzpkc2T/o2uVhRmFoMEQ3QO1TGXE2lcyyULzDjJJ1EMcJotrlHxVAJqbik44tChFbbD/Yoabt3eJzdV/yVW9Q8XKfJ3xXfvtzhZrdEb/4Ulouq8nEOQ91rl20qf0nh3epuKnurbKtWMiwYcR7vt6e1fRqqRoSqd2tUtiSvMvddxjAWa+OqeVS8vmvvLN/Yf5NyF/XWnZZ5xrQ3Pclk6zJY7mRtUK6Zgkn8BN29rYh3a+hNVe9+/3WRRvOIDCazw8lk0HwCWI1sPjGrnqNlp+Zhm7GfsH76dWqekRU3s1U8nqZJnCwzq/wuMCEoHrKVIMbhXKeh/TBb3SaD3yc6y8nu6XvepU3cHTzTY+FjTl+A8jm9cCRdUT/7vztY0bDrB76S3OauVNxZv/9wd/CNhumtAd9HHOeuFyg3KF7A+F4+73tYxsZ1kARimP+HJFkMqHQBn/PF8PeCQWCt9GZXj+nsorJ5bdXUJ1RFGwWU32o+r763DjXN9WC9g3nkS7s3Nh2eHYwOXmX5aqbfVNr762i+SNKcvtc9sO2TXM8XMwoMJ1+W4990bo+zrDKHVyfNqa8m0ZMVTV7v+VI9dcxZhhH6ivoNHObu4M2rE9DvTEXuQCB6vELamqE+A9mUvflQ3LRt+9UJLvfPzJNk9iVMt1b+Hw

Browser:

Operating System:

**Comment by ggetz** [comment]
Hi, the option is [`requestWebgl1`](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#major-announcements-loudspeaker-2) instead of `requestWebGl1`. [There was a typo in the reference doc which has since been fixed](https://github.com/CesiumGS/cesium/pull/11083). Thanks!
