### ISSUE TITLE
Entity with color and image background

### ISSUE THREAD

**Issue by vitosalvia** [CesiumGS/cesium#11121]
Sandcastle example:

https://sandcastle.cesium.com/#c=rZRdb9MwFIb/ipWrVKtO2l1w0WYVU4cQCASiEjcEVWfJaWNwbMt2Ograf8fOR5eyTYomfJMc+33e449j50paxw6c7siwKybpjq3J8rqCr01fnEV5E6+VdMglmSyaLDOZScbyhtVGVdyShzvwLan3VskbdLhRtckJhMIiDgRjWQSQbLDSgoIgkbSdz6ptbbfWoSMLTmn1w+NZFIA+VZek9QBXkox3tcwdV5LFxSnThP1pJaxbEjyMWcCiGGqXJykaRtJxx8n6ZTxIoO+FA4qa7IlgbKcMiwPIPTFb+k968gBBcu9K33lxMZhRaIJcKzt6rNd/49+XQ1G7r3R+HO8q3NNHv0WGo/hslCbjjvGZ+XPNGZRWo/H5Fj6oaTqG4iHhoj2w5t8mtvQm81f6F2i5z6JRNoY0oc87WMoajT9pjvIyHuNwOYPZ9L8KJ2NUuRLKLE5zDhHsfBleC13iqIk/bmdmX97cTF9mM38BN2rN95NBIbZ1ClqJ415JqLraC4XbqO67Gy0bLppGqXVHQave4TWvtDKO1UbEvoYc+UsfrnhyW+c/yUFubZ8uTYZoWvAD48XVE08PywVa60d2tRAb/puyaJUmXv8IDW8Ol/tPBzICj0FWzlcf2k4ASBMfPk06pcQtmn+c/wI

Browser: Chrome

Operating System: macOs

It's possible to apply to an entity a background color with an image like leaflet?

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
