### ISSUE TITLE
CDN version for Cesium `1.103.0` unavailable

### ISSUE THREAD

**Issue by turansky** [CesiumGS/cesium#11130]
Cesium example - https://cesium.com/learn/cesiumjs-learn/cesiumjs-quickstart/#import-from-cdn

### Test case
1. Open CDN url from example - https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js

### Expected
1. `Cesium.js` content

### Actual
1. Page 404

<img width="1464" alt="Screenshot 2023-03-01 at 11 03 54 PM" src="https://user-images.githubusercontent.com/9942723/222264623-a7b43975-8ddc-4ab4-8f99-3d8c0a85d5ad.png">

**Comment by ggetz** [comment]
Thanks for the report @turansky, we are looking into this now!

**Comment by ggetz** [comment]
This should now be fixed on the website. A fix for the publish step is in https://github.com/CesiumGS/cesium/pull/11131. Thanks again!
