### ISSUE TITLE
Fragment shader failed to compile.  Compile log: ERROR: 0:? : 'varying' : Illegal use of reserved word

### ISSUE THREAD

**Issue by HuangRan** [CesiumGS/cesium#11132]
Our team plans to upgrade Cesium from 1.9X to the latest version, but there are some problems after the upgrade, such as the incompatibility of some glsl previously written.
Sandcastle example: https://sandcastle.cesium.com/#c=7RoLTxs5+q94o5VIdDB5Uh4l6GiSLuigVCXdVdUg6sw4ia/OeDR2Aiziv9/nxzwzQ0KpurerVqog9vd+fw71OjpBgs4DRpBH5hzxCWr30ZAyItCEYLkICQqo+5X6U3RL5QzN+JKECPseEoQRV6IxmeEl5eHIr9fRmwVlnoL1sMTI5YtQEnGvqL771EOXAfH76iLgocTsEM2kDA7r9dvb26bj37vOlC/rgkpS9ziVsk59KimWdElEve3tjC1xJ8BTMvJd7guJlpTcgkBd5JNb1COCLubO7/qsOqq4+nOP+xJTn4SjyjZ6GPkISRKGcPI+5EvqkfAwQnRDUJn8wUPmDQ1ItbY98h9rr0f+yDesHOESnzhTxsfE8UggZ0Mi5MkUgIW0WCCODBfkteLFiETEm5I+kWAuyuFSHSf/LO/3XEgQCEQWVxIUPKfjEIf3VqZBmoK+rxqhEjqKUWCJxFSyhsnzqD5kRfHxnByiLffPeRCI5tZ29nYS4umc+PJqhpXRspcIbS18OuHhHAms4ils9SEAGA+H5E6F0est9K8NUKxFy1GWYBQVYUvittDyRhrQHuchxAZYShRjceqhuXKo+q1WBPJQdDhhHEsjFJgSDHMD7vD66nM1Lep2oSi1YlmI2zGmUXFikFr9atpYzyFHJ0aSo6bTQDuo4TTUv2atUJ8pu3kLbuxZ7ppnIdXHokPCBNmErNKwCuJsN+x/+L22OZvHbOQ9bhTpzReEeusvCfWQeM9DEJTN+IJISf5/EkQHM2ii9e8m0Zwo9+zUSNTsrSTJign+2sSLFHeAYhepKN8kPeb0zjDdLs6U7bwJHFz7/kn6zNx/zOeIjU9xiB7ywInzD1cT1VGpt51HWXHsYbZrFmE9rpaJNUWi9XSR6PE5oMAAkq8W9Xoe9Ilq0s5bSigEsNPnjEbbq+IVHDWvc8SoHywAhMDMtTAgscEmGFxf6qWsOaPzIhNmBp0gp7hwsOdVVy1rijTMgFdgeDkjyExvDLlgmxBrokhyxDj/iqCnXmB/hqXEfjTJWfj3ygF6TIq81MNqiqTYbzuTkM/7ZBoSIqpK0p29jtNo7u83243WfqPR6uxrfToN59VBs9lpt9t7zc5+q6lP93bbI1+JmeF3GVIo9NiyTAXHKTR6qKPvqXRnHzhjK8xbTae1t793sL+33zpo77d3NZcdOG532geN3d3G/l6r88owh9zea7462G0egLgH+53mrpElY2tjKkcQqUZYE4QeTJeqCoF8h3kbaco8UeCwQCkNQ3xvGGJfKJfH0+4FliG96zhn/cG74dnwUzLpghfPOfa0G9XgHk3eAkm1GRAZ2dB+zBrO/Gj3h+bSqLEIWcz4jPsfiIDlwCXaqCcCwM68Kjio044H7mwUhnRO9Sagw8/yjaU9HV6cI7WZMHyPQEkkZvxWNcFoh1EJisDDc0gaogAjDdTFpUXsIo+7C9X3o6mbEfUJNgmPLkeVlFRutFM4OICtxuvNwELVFDEFm/rouAwL8U5J0UWjyhi7X72QB6NKDkzIewZrBRWBEWhU8blPSsCCJFVGFTwWnC1kGeyYS8nnGrJRAsLIRD4F8HlUCTj1YXnaIUswixhVrteKCN5SflBgneCuTDgwxzTkC7CjbU5gIgaHGl57+MxXsWvSFI/5wtQYdxGGIAm7t9so8SKPR/6Nz7umTdnrQyiMHpmAB70oiaaQZUzzP8xEszoxa2Aky4kPCSWphMV2/F+1A9/OqDuD/Zgx2I+ZB1k44RtJqWNVQY/5HbJez0s+MKwyKWbOqnH8/0bUkjLBCyaRdqPLYGlHM9jTYXTUXG5nBCwXM6YC+Vzq3R7EAaMmaJEA+sOpJdFNugIUQP8qwC4ZqCiwAM4UUli1phPdX3SBtMJe5TCG9wFxzgdvhze987Pef0wdNE6epOYAgTDIKRaBei0AN6WuIi0E2A6N2SJJbZQ8TyTQqmT7CYjWyyljqKySYuqCDWGNVm6MTGcmSGhl94QxflvAu4QhnaC0Xco2fiquYpmuIkmq6XJYA5uZcFb9tsxi6t6GUgzyRhmr+6I3B5QjF48STjRapzPHeXP+cfAkFiP+VG/X0CKbRZCpFP58bVfBvF6/aYt/P8U0vTWanZ9dDJ5Ge0o1A1qk2wbjlxnaNlI2FUta08/RwJe18vbqsZbQnl/X1M9oEc9EXaqoRKmoHwmdjC7FRUNki8Zk4ZsnMu5fqMy5ADpW1zn8qnqxFiPaOEwGJ/xvsUCBHY2h2s7odMbgv05kqPdcp3F8amhsEGya0XtVULEuwnGLUVcmEk0dfWvl6OZ8CJfVSAEHpoVofos2FlUYfrHetF2pmqFYqyVL1objQrSJAbpvPz6m1DnJGk0zgxLL9eSEqNwS8TylZh1r+XXcx4zbpl0MG08hX36N9YkmKuwvMWQaU5PrKVEOQjuoyGrOvVUnuPtSyskOM8CnkMRdCjkZBAEhY3bV1CCzAhJCsx1V3py9M0NgnqV6MegZK6k+DTfpyDmNAi7TRcDn2sqq32CmXhWT8cBJwiIbWL90uwmQpZQKjSdiOUPnOgmIaIt+qldfXH68GtxcXP4+WFcAIHUNUz2mqS6somlOJNZfCEC3ViZQs9wbfveyAnEODu6pxvqCAhEZaJPqUF6vv295CF5SG9IjW0yytr4aXJnvcjaNz0SyMvt8bsBq0M2lU0rQcknw0kxb+VFZFSQ7pJsJLG3fVKVPjFySDSDa67L8UiKv0tosw64LtElSHwKjcEtZF2QreZvymUycFa0QBBKJBip+0uaxYO/WlzhVu5Ial11BHFsiU9SK4VJSJF92bakXBbUKHsEujfQ63I2+oduhpiLsMAMzqhwf1QHseMsyiPIlvxJlD54hTar/gGhHEo8ZKRPKLlZDBaMkk2Pu3R9n3khHlSMZws3sGHrEUR1+HknveFSJIB5/fVjfWB4B0QPFgdKXhPiXiHL/8mw4RGf9mPyTNFOiacSbs34izjpWV5cfP/QG38LLYG7GrG4MCT+VZY9NO17fjZLNUYXpI1Lv3aXLUGabc6DzCAmVrHytc+L+tu7BIVUm0tm8Uo+ih4fSp4fNHh/AMknvNa8kSVtLFtG/0+Stym+usaXw4vEmVX0LruPVLH2XMejrJ7ABL3ZGeib6B038P+f9/Lyvvhnyn9sKixymIPJ+WkOUegnJxw0XiR++RhQnSoZEHG6ZFxGXQSym+kHWEuYrz+S2NGPjzhFzKSCUf435NDg/v/zjOyw2+eL6j9tpCuruSjCkR97cXWz++KK43Obxfkyt/ZHr04uXpxULPWNjKjFxUZZ+w1q1djUqKBtPloLSZE8VhOKAWq0GGzby1GRYIl5RfSqRorbi9s12uw0qV/yO/HOt+7nW/f3XOsvsnPtTKhceeTYzFmE+gxnsad/GyyJuzsqMqs9mNNNom7OJ/pLYTsbVAWM0EOpP857N2pI63VSC77OXq3mqsl050uP5cUT933SudnH15yBVx6lLModdApb1+ngBqkjHFSKqUkf1NKouL9TrFvxRd5zgkwVjV/RPEteZPKqtQ3baVmCz5rEtYI7jHNXhYzGm5JyNcZij/D8

Browser: Chrome

Operating System: Windows10

**Comment by katSchmid** [comment]
me too 
https://sandcastle.cesium.com/#c=7RsLbxpH+q9MUSXDHV6MwfUT6xxMG+vsOKpJqipEzrA7wFyWndXOACaV//t989qdXZaHm6i9nurIhp355ns/B9JooCvE6TQOCQrIlCE2Qq1r1Kch4WhEsJglBMXU/0yjMVpQMUETNicJwlGAOAmJL9CQTPCcsmQQNRro1YyGgYQNsMDIZ7NEEL6UWN/82kX3MYmu5UbMEoHDMzQRIj5rNBaLRdOLlr43ZvMGp4I0AkaFaNCICooFnRPeaAX7Q4Pci/GYDCKfRVygOSULYKiDIrJAXcLpbOq9V2vVQcVXz10WCUwjkgwqdfTbIEJIkCSBlbcJm9OAJGf2oJ+AyOQXloRBX4NUa/VB9Fw7H0TynyY5SgiPSPiegHBPDxMMGB5AUp8AF58keoTmjAZorgDuJBYNexPFM+CYq9c6ohGDR//L9HHKAovvfiY0kH5T0wwj+6KQP/osZFJmrN+du3vAYAdx4a4Rvw0q57A+M6RAQXdYJPQJ/UNtV/EjAIC2WVRvege1c3kO7GkXgVdElgQsyhIwASiJuzQjlkxx2Os2FQn9lOLHZuEcFX+AgN7agt5yoQnAk/e0/LKKrgT9TvyPw8e3Fk7yHyfsP+DZ8JjKAHjOkT7x/Ol8xRV+TPB4SiKxwRlGBkS5g4XXDjFa4xBAnSQUtDM1b0qdgfitVMw+6y1Jrwuk93NaOwddyEC5pokWrHDe2k+GkXpLv5CqY9aa400O7Aj7ZMSSBU6Cql2uK4zVA++gjtQf6U51tG/3XVSjkGGBAsAUMOFgyHgoCFarnTcaRucQoNMiKunifMqYmHBB4qqlX0d4yKtBrVYMioRCcgjBXHBOhUEzPWH/rJyZEj7pmvibr8Qf+JI0rgWY0qdqSqSena2DyRZVLlV0lLJV5lnao/LprTvjgk31TtW4wiyiYIkpP3N9YyXac7vyRyxjkma/dxpHH9a8u6t+u56HneNwlgFrhG3v5rr3pn/T/9UBfq67LBSj6c/gwc1IL6Lf2oF+axN9+zrHyRJKV94+kKxVDSWBcooU73sNrJh43+u6TOTCercDaRTvBu5vYqVdz5eadXCHRfGdWtknT3BubRE1J0a5lJo7U5ZtsyqtGwKP+yQi3jhkQ+IFJBaTPuHiagzZlwtT2yGqRDIjKvpCIhAJxuSaCO2sqJO3vJETCoWAtgEaC/4goA25pcMERDedQ8/FoParmqkMjyQUGyQplnx8F2lUCw4b4Sn44B7UiTjmzb2Ci+YVd5bfRGjPZArEsez6ksNrpCwuNQzN3vke+ucOR4xG1x8x/i5T5iF4itCg3az8lp+SlXIqK6R8VysD+a1s0RQSyRSoUhZQMEdwLZ+rLqv1UlZq5bzIZG8bLXPo8LrqKusl6OhIc3IBNQXty9Iof5q1UnkKVUQXmTLA57JFEnKyC9q04h2YX1XudibznPe85508vfkVrn74p7h6QoKXHeA0nLAZEYL87wSI7nZIoOTvZN6cCffi0MjE7K4EyYoK/tzAs4J7gLGjmrpdwkP2br5u1kojpV5UgYdr3z5IXxj7z8UYKW0M9U9m/LPVQPVk6NWLR1YMe5avmmWnnlfTxJYkcbg5SXTZVDVBK9mi0SiCbsgmraKmuDwAevqQk6i+yl7JUvNjARmVE93bhMwpm2mQVGEjDKZfa6W8Ou16mQpzjU5cEJx7OAiqq5rVSRom4wdQvJgQpO9YQuSDbhKskCLBUMjYZwQ19Q5HEywETucSA+8MzHYqwfKuh+Ko5Y0SNr0m44QQXpWc7h+3vYPmyUmzdXB4cnBw2D5R8rQPvB9Om812q9U6brZPDptq9fioNYgkmzl69wmFRI8NScc5XkOhhzz6lgp/8jMLwxXih03v8Pjk+PTk+OTwtHXSOlJU9mG51W6dHhwdHZwcH7Z/0MQhto+bP5weNU+B3dOTdvNI85LTtVaVx4mQk5V2wgC6S5mFgL+zoo4UZpYJcFYilIIhUdBPcMSlyTcNOc+pFW8ZDpQZ5fWavR/jSMj7OyKsDs1jYYpUL63rvt7UYsySMCV8w6KfCVfdtVLqFQewm6AKBmq30muxvBfCrEvVfZ1yP0M35fZ1/+4WyfvDEC8RCIn4hC1kEbQ3jTJAEVh4CkFDJKCVQG7cm4PytsCfybpvu+6QyKfqoBLQ+aDicOXbmz8PxzFotzsBDVUdZBLWefT8EHP+RnLRQYPKEPufg4TFg0oBjItlCGMF5bFmaFCJWETWgMVZqAwqeMhZOBPrYIdMwGivIA/WgIRkJDYBfBhUYkYjQZJ9Mge18EHl41YWwVrSDhKsHT+tYw7UMU7YLApscQIVhbCo4JWFbyLpuzpM8VDeZknn9GdJApyES2TnXWtxa990vaPLlNk+g8QYkBFYMLBBNIYoC8247HqzXNGXtZaXqwgCSlCxRGwobyDQYkL9CVrQMEQTFgYQhSO2E5fKVyX0kD0hY/Ui5z1NKhdieq2a+v9PRA4pIzwLBVJm9EPqf0YTHAXQOioqiwkBzaWEKUcRE+oGHtgBpWbHLAPq4bVB0cmqAiTA6CHGPulJLzAA3pjoS8crVV9UgjTMPhROqFH+tvdj/7F7e9P9t86D2sgjpw/gCAOffBbLO30wk7NlpeDy9nUYzrLQRtmHCBm0TNlRBqLk8tYRlFpxiPqgQxijpRmt6nQHCaVsScKQLUporyFIR8jVy7qJn/KHlKcHy0nVTYc10Jl2Z1lv12lM7htXSkFeSWV1vurOARXQpa2EZ1trN3K8V7fvehtPhSQaq+kaSmSzDNIJ4Q8fzShYlOsnpfFvJ5jCt0Wy25u73uZjm0TToGWy7dB+6aZtJ2EdX1KSfrANX17L9dVlxaFZ/1iTr3YQz3mdk1RsKKqP8rycLOVJg+eTxmgW6SsyFt3JyLkDPEbWKbyVtVixYScOHcEZ/QXmKDatMWTbCR1PQvhVgQz5nqkwTlc1jh2cTRF6KxMqVkk4LTFyS3uizqM/Gj46BRvCZtUK4EG3YPs3O7HIxPCdsaapStUcxlotG7J2bBfsJAbHI/sxgCPOVV5pihikWKY6J0TFHk/7KdnrGM1voz4MmSna5bBpF/Lp+1Qe21HhaI4h0kLZub4m0kBoH5VpzVsaceKnT2spmWYG6JSieHIOZ42g/AzQVbssahBZMUmg2A4qr27e6CawSFLeGHS1lmSdhh3Xc15bh8tVEbC50rKsNziUt4pZe+BlbpF3rO86nQzIYHJcY4Mv5/B8zBzCTtGbavXd/buH3uPd/fvetgQAoauJqjZNVmHpTVMisPrYHqq1VIHs5V6xp69LELdg4K4srF+RIKyCdskO6/P1t00P8dfkBrdlS1HWtmeDB/2Ni139M+NsnX4+HMBo0CmEk8Poek7wXHdbxVZZJiTTpOsOzNWvk+kzJa+JBmDtfF18SZZXce0WYR9LpMlCHxyjdErZ5mQrcevYTGTGsiMEgUCicfZBvPnIV4O92Z7iZO7Kclx+BPFMinSwlcM5XGQfdu3JGwU5Cl7ALI3UONyx36PZpzoj7IcaZlC5vGgA2OWeIWDjpTgS5RdewI1Tf4C1C4GHIVnHlBms+hJGciaGLFhe5u5IB5ULkcDO5BJqxEUDXi9EcDmoWIjn73/bXlie4WAAggOmTxnyTxbz9f1Nv49urlP0G3E6rKmDjzfXGTvbSD3cv/u52/s9tPTJ3Yg1tCLhVWr2Upfj7dUomxylmz4jed+9dhjKTXMeVB4uIJOtH+u8tL5tu3Bw0oQbzSv5yF48rL162O3yATST1V59S5KVtWwQ/St13jL9Fgqbcy5tb5zsW7KdjmbuXk6h5xtOy29lWWO4PdH/Ucf/d79f7PflJ0PRS0thmcEkRNFOW5DSIEP5vOMg8YePEeWBkkORulvuRsQPwRedepDXhP7IM9tdG7Fp5UiplCAq3sb82ru9vf/lGww2xeT6fzfTlOTdFWdwW97CXqr+dKM83RbP/TG59o8cn756eFrR0AsmpjUqLovS3zFWbR2NStLGxlSwNtidhFDuUKvZYMdC7nSGa9gry09ruKitmH232W6HzJXeI/891v091v31xzpD7JZFYypmAXkxsdCefAExmNN+Hy1zcHdSulV9MaGJOrY7GftNYtMZV3thSGMuv5r3YtIG1etdOfg2c7nspyr1yoVqzy8t9n/RqZzF5ddBqp7XEGQKswQM643hDEQRns+5zVIXDfeoSi806JT816s0wEezMHygX0iaZ4pHTR4y3bYEmzQvTQLzPO+iAY/lJwVj4RAnBcz/BQ

**Comment by katSchmid** [comment]
have a look at the example https://cesium.com/learn/ion-sdk/ref-doc/CustomShader.html the declarations are separate

**Comment by njglen** [comment]
I don't know how to solve the same problem.
@ggetz

**Comment by ggetz** [comment]
* In order to work in a WebGL2 context, any custom materials, custom primitives or custom shaders will need to be upgraded to use GLSL 300.
* Otherwise to request a WebGL 1 context, set requestWebgl1 to true when providing ContextOptions as shown below:
```
const viewer = new Viewer("cesiumContainer", {
  contextOptions: {
    requestWebgl1: true,
  },
});
```

**Comment by HuangRan** [comment]
> * In order to work in a WebGL2 context, any custom materials, custom primitives or custom shaders will need to be upgraded to use GLSL 300.
> * Otherwise to request a WebGL 1 context, set requestWebgl1 to true when providing ContextOptions as shown below:
> 
> ```
> const viewer = new Viewer("cesiumContainer", {
>   contextOptions: {
>     requestWebgl1: true,
>   },
> });
> ```
Thanks for your reply, I have tried this method and can run it now, but it does not meet the 1.9X rendering requirements.I found that the same version can achieve the desired results on Sandbox, but not locally.
The first screenshot is the online effect.
![image](https://user-images.githubusercontent.com/8411877/222623739-a1e4768d-9b2e-4024-a0bb-b1b953f92fe9.png)

The second screenshot on the local.
![image](https://user-images.githubusercontent.com/8411877/222624244-5a0f6ca8-253b-441f-9d19-7af917e18591.png)

I don't know why?

**Comment by HuangRan** [comment]
> > * In order to work in a WebGL2 context, any custom materials, custom primitives or custom shaders will need to be upgraded to use GLSL 300.
> > * Otherwise to request a WebGL 1 context, set requestWebgl1 to true when providing ContextOptions as shown below:
> > 
> > ```
> > const viewer = new Viewer("cesiumContainer", {
> >   contextOptions: {
> >     requestWebgl1: true,
> >   },
> > });
> > ```
> 
> Thanks for your reply, I have tried this method and can run it now, but it does not meet the 1.9X rendering requirements.I found that the same version can achieve the desired results on Sandbox, but not locally. The first screenshot is the online effect. ![image](https://user-images.githubusercontent.com/8411877/222623739-a1e4768d-9b2e-4024-a0bb-b1b953f92fe9.png)
> 
> The second screenshot on the local. ![image](https://user-images.githubusercontent.com/8411877/222624244-5a0f6ca8-253b-441f-9d19-7af917e18591.png)
> 
> I don't know why?

We use the Ion sdk,not the open source sdk
