### ISSUE TITLE
npm run prettier should be given --no-config option

### ISSUE THREAD

**Issue by rudifa** [CesiumGS/cesium#11135]
`cesium/package.json` contains 2 prettier scripts:

```
  "scripts": {
  ...
    "prettier": "prettier --write  \"**/*\"",
    "prettier-check": "prettier --check  \"**/*\""
  ...
  }
```
Problem: if the user has a `.prettierrc*` config file in one of parent directories, e.g. `$HOME,` options in that file may contradict the default option values that `cesium` relies on.

I suggest that above scripts should be given the option `--no-config`, which would avoid any interference from the user's config files.

my operating System: macOS 13.2.1
my prettier version: 2.8.4
cesium prettier version: 2.1.2

Note: my `$HOME/.prettierrc` contains the option `"bracketSameLine": true`, which is unknown to prettier 2.1.2, so running `npm run prettier-check` produces a warning `Ignored unknown option bracketSameLine: true` for every cesium file scanned, which masks any real warnings.

**Comment by ggetz** [comment]
Thanks @rudifa, good catch! I don't think we ever ran into this situation before.

I confirmed the `--no-config` option doesn't interfere with ignored files, so it should be safe to use. :+1:
