### ISSUE TITLE
How to calculate rendering a frame time in cesium

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium#11133]
Hi,cesium teams,
This may not be a bug,but it affects the experience.The problem is that different computers call callbackProperty at different frequencies, resulting in the animation effect on different computers may be fast or slow.
I look forward to your response. Thank you.

**Comment by ggetz** [comment]
Hi @engineerhe, maybe try [`Scene.debugShowFramesPerSecond`](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html?classFilter=scene#debugShowFramesPerSecond).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by engineerhe** [comment]
Hi @ggetz ,Thanks you for your answer.It won't happen again.
