### ISSUE TITLE
build lost modify code 

### ISSUE THREAD

**Issue by 1wobuzhidao1** [CesiumGS/cesium#11149]
hello everyone :
      When I modify the cesium source code and execute npm run build, but the modified department does not exist in the packaged file, as shown in the following screenshot:
cesium version:1.103 
build before modify code 
![modifyCode](https://user-images.githubusercontent.com/76717277/224216793-d1a65fd6-e8d4-47b0-b6c0-8f3f09d603af.png)

build after 
![buildAfter](https://user-images.githubusercontent.com/76717277/224216826-74351925-27a0-4d45-9676-4b5647ad33ee.png)

**Comment by ggetz** [comment]
Hi @1wobuzhidao1, which file is the packaged file? The `build` task builds some, but not all, artifacts.

**Comment by 1wobuzhidao1** [comment]
**E:\Cesium-1.103\packages\engine\Source\Core\TileProviderError.js**   this file

> 嗨@1wobuzhidao1，哪个文件是打包的文件？该任务会生成一些（但不是全部）项目。`build`

![image](https://user-images.githubusercontent.com/76717277/225180755-c2704480-6132-49da-8071-bf6ce46006aa.png)

**Comment by 1wobuzhidao1** [comment]
> Hi @1wobuzhidao1, which file is the packaged file? The `build` task builds some, but not all, artifacts.
Thank you for answering my question

**Comment by jjhembd** [comment]
Hi @1wobuzhidao1, it sounds like @ggetz answered your question, so I will close this now. Feel free to re-open if you still think there is a problem.
