### ISSUE TITLE
custom geometry dosen't appear

### ISSUE THREAD

**Issue by lxydft** [CesiumGS/cesium#11156]
i want to add custom geometry and set Appearance with a image,there is no error message,but the geometry is not show.please help me,i have waste three days on it. i have no idea.
Sandcastle example:
https://sandcastle.cesium.com/index.html#c=zVhtb9s2EP4rhD80yqbJL3KTzo2LuXGSBnBbo0n6ZS5cWj7baiVRICknTpD/vhMlUi9WmxQYsAkILd4bj3fPHal4LBKSbH24BU6GJIJbcgrCT0Lns6JZs5an5qcsktSPgM9ah69n0SzaUk5iJnzpowlUzdVOKZf4RiPXWXEWjmHNAcSIc7qz/p5FhPxx/NJ5+efx8bFN+h2n47565dr79G6FfvQkXdv5kjqnXOs+5ZPV6ArpdTodY6T3pJEmt0m3sOA+y8LRTyz0n7eReizQRKfIlMcCxkWe4fOAUen2SkkhpOt0bNIxQzrNGGZaZ3SfZughz8ssCkASxFvmxo0fyVclJzp2ZqFrfrt2Ru/axkK6mTWwECTfVQF7kVOth1SJSsn9RYLhGpCHzC+N1kGT1kjLW7k0wZiFMYsgkmMqqdzFMDB5qHOc8cebt5Mze09VTIEb0wPiGoktDRL0zaTjqF9JR/bEXefOTsedGu/tCrOnmD3F7NWZrmK6iunWmX3F7Ctm37nXvC+H2dvjYSEu5HPD9WsBO598HF3bDbq1iPVKMnnM0CdNM54qfP+3nvYbPN2rtqwOtdfGfRxTcCNFEfxo6XtaPy2T7lGOjrSesEdhzanR/ZJZiLkfIra3cF3ey7RMda4/XY4+XEzOrpTGgiW4SLS+ijfAC5W3FbLqMp+By9Qb63+GVQTrY9ETQiqB+zSo9oT3OTXL/YouuO+ZfpDl/eA0TclBvmgS+SvGw6JpNEFLaVj7HdOk1dapzB3UTtI4Bspp5EHVzZGh5yDVuxn8eDP6qW1KPw0b0Y8f0jUMZi3HaatX0c4WmE/Yms3V5pxv8XrWsquaj7W5YAn3MIJfvftwbuKfTtYgjbNl5mUUJ5JUZvYWvB7ZzoU8rFrfcxurCrx+lg4Mn4Q7mXCw1BbszMLrfZ2KbyWQ5G6OYUWToPC24luTPS3gLP3VKhFpIpVHDl8vfiZOg3hDh5kobRDkgLuJjHxN4vFr1h7MvJjoHkIXbAsXPK3fAZE8gVK2VtSDc8ZvKW/gBVTuESWCUQSJh11ugNqBKDM5REvgV9geoYauRQCqexTtJCcoYWf66Wz+/mZyfTmdXJ6N56PJ9N1ojsfmh3EFWUuI5eYa0pPngUBE0eoy96KGQSX5norvexsoy604XYe4k6sNTf3WqK1G2MCwFvkt85eYFT+ynsbnE1B/LjqH9RKqFcwPkF5UxzB9tfaQ+nuBRgh9IfAqZFfx2WTWX2WHlnM3HGKPe/Eim+0qs/vK7FbNDsvO4OBaaZ/M/w7V0LAcS+T8HBN2mpe5srFXDeWjFo8nuKvlNg2Gay587vidv97UF6uJTNhtg0SP7CECKwbPQLKg0ttcLl//+zBSiYzzHpVVImbpE+CYnuXsbAdWdWt2dR+N6ECfhqIJg3qlkC0hSL/6ppx9Ay+1VlmT/EbiBvV1MJ/mi6OhusRjdaraWOnUNveW6nloLi7ZUafv+5f4rZoekqLxoqe51gPJFtVqA/Nm55x2u/J5kFORrA/78kFft2+ufOp2lN0FKgrO28nNGdGXgXb7US/rYxs7QGUarQM4yKh5+y5uBoPiVXHEht0OTHejYhd5G84iloiiM6uIZh/xjsCmDY4JrHDocmmZqYJGLunREDh1BMg06+VbxRKbrx9RldPBL30A649o/PjE+ta3XFy0ZbdOhNwF8EYv85eP92guScIDC68iEsI4xbloLxLvO0jHE0ID+aRdVj1Z+luM5bDhXxPEC6gQyFklQXDl38Os9eakjfJ7qljD6cH0EdtHQHep2Kb7ZpIRHcc5aeO0WVMyFiwor1n+Bw

Browser:

Operating System:

**Comment by ggetz** [comment]
Hi @lxydft,

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

Please also provide more info about what you are trying to render.

 The [primitive tutorial](https://cesium.com/learn/cesiumjs-learn/cesiumjs-geometry-appearances/) may be helpful if you haven't already seen it.

Thanks!
