### ISSUE TITLE
DebugCameraPrimitive can not render OrthographicFrustum

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#11159]
In this [case](https://sandcastle.cesium.com/#c=fVRNc5swEP0rjE94hshCX0iNk2nrtKd00mk6PfmiYNlWixEjwGmSyX/vCoxN0kw42LtvV/seTxK5K+sm2ltzb3x0EZXmPlqY2rY79KvD4uUk7/KFKxttS+OXk+n5slyWebfyKapzU5roGRb3U0bFytW2sa58OXihfQORLmlMZMZFirikmKRUMplwwYTAClHIMMdcJUQJypQARLBUSMUCfT9/Zb3J3yU4wwgzpiTBXHDCsZCEJgBKSUnGoUAJD8QBA2KhUs4FIYQKcaJpq3fnE5pREZRlKhOKKnoYhuHlmFSKcyqSQMkYwSmjCgNtNprv7WbbvEehlMwwz4K8jLKMwTTwRgr4EZzxVApFkjMwTWaZIoIAN5E0NWcpObHc21WzBRaacSkRBXmcYonBmPNo6NF1BYb+0OBpdJGC5cF7LMENTCU5jiqNDocFo/QIrTskxfCMDkCud8br168WsLg7Np26LkejszKEp+J4o4/xqdxtUFudgMHR7v8Er31bN+3uoGcQdOObrdt4XW1t/rXviJ+WZQRP51nSxyNvDkiw4RCuu+h5cNsVBhVuE7/kRZV3v3vt33Tj7d/+InVOQM3u4K33pkZ6tYoHhqNtV+au3fTefR9aB5nRwejkmLrC+Q9Hx0OGbq6vrj8tvhx6nqch6AX09xYNYouHn+6za8uVLTe31dZ4E490vKoMe5VEJOz9dHo+SSbzunkozOWg5qPdVc7DPfJFjNCsMbuq0HC8Z3dt/sc0KK/rICS0zmfjpfOV3Ud2dfHGNyjKC13XUFm3RXFrH81ycjmfQf9/Swung96bvfGFfght2/TyugcRQvMZpG+vbJwr7rR/Nfkf), I want to debug orthographic camera frustum.

but It will not render in minified cesium, or it will crash in unminified cesium when I annotate
```
// console.log(camera.frustum.projectionMatrix);
```

then I look througth. and found OrthographicFrustum will not init it's ```offCenterFrustum```.
fix in pull request #11160

**Comment by ggetz** [comment]
Fixed in #11160
