### ISSUE TITLE
3dtiles Loading with holes

### ISSUE THREAD

**Issue by wangcaijie** [CesiumGS/cesium#11164]
The 3D tiles model shows many holes when the viewing angle changes due to some tiles not being loaded

![image](https://user-images.githubusercontent.com/33952795/225842741-9c4882ea-e739-4379-8c07-bbe621071fe7.png)

**Comment by wangcaijie** [comment]
for example html


`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
    <script src="https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js"></script>
</head>
<body>
	<div id="map"></div>
	<script>
	  Cesium.Ion.defaultAccessToken ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4ZGJkNjZiZC0yZGUwLTQwZWItOGQyZi0wZjhjNTk4ZGM1YmEiLCJpZCI6NjMzMzcsImlhdCI6MTY2NDI2MTgyMX0.cir5_s5hs_chd0j5f1GEwI4_9OXABcIiSYwpdQZ1DYI";
	  
	  var viewer = 	new Cesium.Viewer("map");

      var layer = new Cesium.Cesium3DTileset({
			url:"http://36.152.66.51:8088/3dtiles/南京谷里/tileset.json"
		})
		
	   viewer.scene.primitives.add( layer)
	   
	   layer.readyPromise.then(function (tileset) {
			viewer.camera.flyToBoundingSphere(tileset.boundingSphere, {})
		})
			
	</script>
</body>
</html>`


this is cesium1.103  The 3D tiles model shows many holes



but   cesium1.95  is  OK

**Comment by jjhembd** [comment]
Hi @wangcaijie, I tried loading your html and couldn't easily see the holes. Can you give the camera position for your screenshot? See the [Performance Testing Guide](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/PerformanceTestingGuide/README.md#pick-a-fixed-camera-view) for an explanation of how to capture the camera position.
Thanks!

**Comment by IKangXu** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11358.
