### ISSUE TITLE
Is it possible using multiple worker for each task processor?

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#11161]
In Cesium, I found each task runs on one single worker
I think for now days cpu basically have multi-core
one worker for one task-processor may not use cpu performance in a proper way.
So, Is there any possible to make task processor runs in multiple worker ?

**Comment by ggetz** [comment]
Hi @jiangheng90, the `TaskProcessor` class itself creates and uses one web worker per instance. You could create multiple TaskProcessors to create multiple workers.
