### ISSUE TITLE
cesium particle system frame rate drops sharply after losing focus and returning

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium#11171]
Hi,cesium teams,
I found a bug.When you lose focus and come back, the more particles you emit per unit of time, the more you drop the frame.

**Comment by ggetz** [comment]
Thanks for the report @engineerhe! I believe this is already being tracked in https://github.com/CesiumGS/cesium/issues/9266. I'm going to close this issue to keep the discussion in the original issue. Thanks!
