### ISSUE TITLE
 3D Tiles Opacity Problem since 1.97 version

### ISSUE THREAD

**Issue by moisesrbd** [CesiumGS/cesium#11199]
The recent versions of CesiumJS does not work the same as the previous ones regarding the management of the opacity of the 3D Tiles.

The last version that worked  was  **Cesium 1.96.**

There’s been a few major changes recently, including a move to WebGL 2 by default in 1.102, and a major refactor of the model code in 1.97.

Maybe something was changed in version 1.97 that causes this functionality to fail.

Tests were performed on versions: 1.97, 1.102, 1.103

In the following Sandcastle example it shows that it only works correctly with value  0 opacity. It is observed that the opacity is not applied to all visible tiles, moreover, sometimes for value 1 the opacity persists and collisions are lost.

Sandcastle example:
[Opacity Sandcastle](https://sandcastle.cesium.com/#c=pVTfTxsxDP5XrO6h19GmhQFCpVQbbNKQNkDA9nQvuZzbRs0lpyRXKKj/+3w/ex3d9rCHU2L7s/3Z51gY7TysJD6hhQvQ+ARX6GSWsJ+FLgg7opCvjPZcarRhp3ce6lCLxvO7iVGR82uoAUzKhfTrMRz2Q70pkFXApTZiaTLPvOViGTSe7XDeGBXxnElsRJag9myO/ovC/Hq5vo6JT4Upefwem6epWl9KHUs9d9sc/TryTjKp0KHfLbs8Pnx+LI1BUVRm1bgGXBt9j85kViCbWZN8cgQjYsejs9PTXl50maOKzizyeH1HQOkwj8X8AnUwy7Tw0mgIKlyvbB9U/4I5gRpZamUivVyhYzyOG+z5DvTFmOTRBKUO6rL6tdwq7itxocbcSS8W91zPsXECGLFRfysNRuykJdbFRCYrWvuQLtAisxQuc/AejtioBvfKS8mxvNfezq8V/rndD7k5eN1mFUYZO4ZucQZh2H1aSI909qF7sB09Vs0cHEC3161Yb0oCm4IOE5wqbjUdrTW2aXk+DkYhU2ZeWSrffeNbxKOhvI0c2hWPiHJrzMJORYbGs0C6LHLCyghb2StIk7/mfwE3WRLRo6sB1X+WMwiku+E3jaFxBbDoM6sr5CYn/D8t/1fT97W61Ww6Ov3OpMg6ra0fZZIa6/NXFDA29Jikint0wygTS+IonKsrBXhXr4AWqYj2xdzmozcGO494cHzUh/obsbOtN0BK74QGdAzH6XNLHRkbox2UA7tr3LxJLXWa+TaBFVovBVcDruRcjyGRcazwbdaBN+kYjnYy16bIeG+SXWuVejJsN2wSyxXI+GLP5gWhuHNkmWVKPcgXDDvTyZDwb1yVKV76LTFXfJ3DFofTb6WSMTYZkrjfs1mvzf/LbdPb8se3fchSdsqvUyRPm28UIplITdIov/Fnuh3SzXlMcyUb5VLMPR9EtKVJteIqw3E9WH0o5B8pQUjbLRJ022R2Unp89nl0agVJJ38N3QQpa/gF)

Browser:  Google Chrome

Operating System: Windows 11,

**Comment by ptrgags** [comment]
I'm starting to look into this. To start, I'd like to compare this across different CesiumJS versions to understand the visual difference better.

For the comparison I'm going to do:

- The style from the provided example which mixes in a translucent white color.
- Similar thing but with a red color to exaggerate differences in blending.

| Version | Screenshot (`color('white', 0.5)`) | Screenshot (`color('red', 0.5)`) |
| --- | --- | --- |
| latest (1.112) (requires [modernized Sandcastle](https://sandcastle.cesium.com/#c=lVRdT9swFP0rV92kpiN1CwOESqk22KQhbTANtqc84Di3rVXHjmynpaD+99lxUlJgm/YQ2df3nHO/7DAljYUlxxVqOAOJK7hAw8uc/KrOoqTDKvtCSUu5RJ10eqeJTCTbMr+pDIUjPyYSQBWUcbsewZAcxYncVNhaciEVW6jSEqspW0RbblvQKiVS6nPJFCtzlJbM0H4W6Lfn68vMZVRjQibPtWlRiPU5lxmXM/MUI26Ud4JxgQatC0ZXlNum9LC8/3Qb3GSqVX6p5EfjDJfA4fDk+NjLhLYRw1AiKTTPueVLNIRmWVRLt2APSuW3KvJNqp2x37da/gWpz/o7t2z+g8oZVmBwrRzGYdcPXfXbWoOkqqxqvSnmqJFoJ1EaeAcHZOiBvUSGihu8sWuBu6Nu13vj3dFjiMGUUHoE3WqNkqS7mnOLbo2hu/c0e1IPHfag2+v6qfdeG7vX9MO8Tg3qJU1dnNZ4kk6t4sZaIU2ZGqZ5itG0lMxyJSGqIT2oE2wCn8FVmafuujaA0+DnU4i4uaJXW8eWCqDRllrWyI1fmqqlUQKJULPoD6XvFByKbc/kf3r87z4/727DGgxq3l3gdTVmjvH2sSZsenc1ehP6US2duDOu8ps0Sh94XihtodQiImRgMS8EtWgGackWrhpmTNNPgDfNA22ln7rXPNP+Ho5Az1IaHR7E0HxDcvLEBijc43C3dQSHxX3rOFU6Q90Pt3fXuXkRmsuitO0ElqgtZ1T0qeAzOYKcZ5nAl1H7VhUjONiJ3LhSZa3Kd7116PGg3bBxxpfAs7NX/ozABDXGeaalEDf8AZPOZDxw+BdUoaqnfu0yF3TtYfP9yddwSAgZD5z5OnP789vOz/sm12HmbY7zhE7ZdYGOqf0vxSWZc+msod/Re7fbdztjsfCHZOitjFraT90/1B0tqShx1FzCGCr7Z+Eg7rRbBei2k9kJafHeenXXCmcd/VV6KxJq+A0) | ![image](https://github.com/CesiumGS/cesium/assets/8422414/3a7e1831-3da0-42bb-9e51-4b58e1bd904a) | ![image](https://github.com/CesiumGS/cesium/assets/8422414/f87b2ebf-1b9e-48d3-a908-4d6d004443d0) | 
| 1.97 | TODO | TODO |
| 1.96 | TODO | TODO |

**Comment by ptrgags** [comment]
The changelog didn't turn up. I'll try `git bisect`. 

`v1.103` - Known bad commit. I'm inspecting some things in the shader:

I notice that the blending is off, though the color is passed in correctly.
![image](https://github.com/CesiumGS/cesium/assets/8422414/972c0208-cf0b-4808-94a2-438508ce18e9)
![image](https://github.com/CesiumGS/cesium/assets/8422414/c781ad3f-9a3e-4200-90c5-fe0f3aecab31)

main - known good commit.

TODO

**Comment by ptrgags** [comment]
While in the middle of using `git bisect`, I found a relevant branch name:

![image](https://github.com/CesiumGS/cesium/assets/8422414/e1c5a6ee-4149-4594-950b-dc499c67c30c)

In GH I looked it up and here's the PR that fixed the bug:

https://github.com/CesiumGS/cesium/pull/11399

So this bug was fixed in CesiumJS 1.107.
