### ISSUE TITLE
CustomeMaterial

### ISSUE THREAD

**Issue by zenggpzqbx** [CesiumGS/cesium#11205]
你好，我正在学习Cesium，发现自定义材质比较麻烦（相应的学习资料少，编写过程不够智能），有更便捷的方法或更多的学习资料吗？
期待你的回复

**Comment by ggetz** [comment]
Hi,

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.

For custom materials, [this guide](https://github.com/CesiumGS/cesium/tree/main/Documentation/CustomShaderGuide) is our best documentation at the moment.

We'd be happy to hear feedback about the learning material to make it better.

 Thanks!
