### ISSUE TITLE
Is it free for cesium to call Google Maps commercially?

### ISSUE THREAD

**Issue by CodeBoySun** [CesiumGS/cesium#11212]
Hello,  I want to use cesium develop Maps width google Map.I  want to know commercial Google Maps for free.

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

Cesium is a big fan of open standards, so you're free to use any service in CesiumJS which serves a supported data format. However, some services have their own terms and conditions. In the case of Google Maps, I believe using the API outside of a Google Maps application is not permitted. See https://maps.google.com/help/terms_maps/
