### ISSUE TITLE
Map lag when updating entities once per second

### ISSUE THREAD

**Issue by alon6699** [CesiumGS/cesium#11229]
Hey, when map is loaded with entities and I want to update some entities once per second (doesn’t really need to be exactly a second) I get a map lag and I can see animation frame took too long in chrome profiler.
BUT when doing TWO consecutive updates every second there is no lag.
You can see the example in this sandcastle (you can see a lag every second in the map rotation and by changing ‘updates’ variable to 2 this behavior stops) :
[sandcastle](https://sandcastle.cesium.com/#c=tVRRb9MwEP4rp0poCQ1uyqQJre0E2uBpiIkBL8se3OTSWHPsYjstBfW/c46TpmUve6EPbX3+7s73fZ+da2UdlIbX+JU7hAVcpLNMTSawrVAB/my4tOA0TMFVaBCEBQ6SrwB5XoHFXKsClo0L+JVBqmIIyxWlRLih4NsYtto8CbUCW2vtKrnLVN42btYF4S21nc4gUxtuYCNwSxUWoHAL12hFU7MfbSw6y9vltVaOC4XmLIE/mQJw3KzQfToMcTkMlKl9TPOEoszmqJAVuGxW95Xethn2Ds19GGMBzjQ4C+fItZSYO6HV6VnutFDuzohaOLHB6wMqetZn3YMs40URDQXjrsXal/LDPzxSpGX9Q1HANE2TNE37bSLfcFXomgJW+HybqVIbiHwNQenpjH7mPo8+9H88jgMxAB4iuSMQfOauYqFSFMNrOL9I4Q1M36We+QNWk0ovAYfDsXVjq6PJ2kG71gEVTkySdPRdc0OCC67OWWl0fYNkGbQRnTFpm8fJUbb4hfJe/MZLmIboPvbc7TuyvrfuGZroEriUPW/kPbPrHBr4lty6b6L2Lr+hRKb0Nuq1sLnhjhx9ovVw2ANOOKxbyjMlsbs53fof8TEcz1Pyka6BuxXW0Y6JykZ1jgkqdXk5VTKcGe0o6xZL1/YEEGUUusz763Kirui6+/W2EhKj3gv/3wSDER48L+PxIzuIsXip4gmkCTSqwJLudJH0SsSzoQdREHhfLHrjSVQrVx1GPCAHefrQ/qjOeNxttMH2q+W2i/dqht9XwzMy696RUTKaW7eTeBXKvBf1Wht6x4yMGJtQ87X0Ck2WTf6EjuXW+rT5pE+aF2IDolhko3/esmwEOfnT0k7ZyNb12ehqPiH8SZrUvKCX9AuZW/Kdh1TTq9sQZIzNJ7R8nuW0lktujir+BQ)

**Comment by ggetz** [comment]
Hi @alon6699, thanks for the report.

I'm not sure I can duplicate a noticable lag on my machine. In both scenarios, I'm seeing the framerate hold at around 57/58 FPS.

Generally, for performance sake, we do advise batching updates where possible. So I'm not sure this is a bug exactly.

Would you mind telling us more about your use case, and maybe provide your system specs? Could you please visit webglreport.com and take a screenshot of your results?

**Comment by alon6699** [comment]
Hey [ggetz](https://github.com/ggetz) thank you for the quick reply.
Yes there is no drop in frame rate so you can see the lag only in chrome profiler or with the naked eye.
Because you probably have better pc than mine and this behavior accurses when there is a big load of entities I just bump up the entities amount so now you should see it.
If you still can't see it just increase 'totalEntities' variable.
Notice that there is only 1 entity changes per update and it makes a big lag - So increasing the amount of entities is not a problem here.
So batching updates to one big update will sadly make the map lag.
[new sandcastle](https://sandcastle.cesium.com/#c=tVRRb9MwEP4rp0poCQ1uyqQJre0E2uBpiIkBL8se3OTSWHPsYjstBfW/c46TpmUve6EPbX3+7s73fZ+da2UdlIbX+JU7hAVcpLNMTSawrVAB/my4tOA0TMFVaBCEBQ6SrwB5XoHFXKsClo0L+JVBqmIIyxWlRLih4NsYtto8CbUCW2vtKrnLVN42btYF4S21nc4gUxtuYCNwSxUWoHAL12hFU7MfbSw6y9vltVaOC4XmLIE/mQJw3KzQfToMcTkMlKl9TPOEoszmqJAVuGxW95Xethn2Ds19GGMBzjQ4C+fItZSYO6HV6VnutFDuzohaOLHB6wMqetZn3YMs40URDQXjrsXal/LDPzxSpGX9Q1HANE2TNE37bSLfcFXomgJW+HybqVIbiHwNQenpjH7mPo8+9H88jgMxAB4iuSMQfOauYqFSFMNrOL9I4Q1M36We+QNWk0ovAYfDsXVjq6PJ2kG71gEVTkySdPRdc0OCC67OWWl0fYNkGbQRnTFpm8fJUbb4hfJe/MZLmIboPvbc7TuyvrfuGZroEriUPW/kPbPrHBr4lty6b6L2Lr+hRKb0Nuq1sLnhjhx9ovVw2ANOOKxbyjMlsbs53fof8TEcz1Pyka6BuxXW0Y6JykZ1jgkqdXk5VTKcGe0o6xZL1/YEEGUUusz763Kirui6+/W2EhKj3gv/3wSDER48L+PxIzuIsXip4gmkCTSqwJLudJH0SsSzoQdREHhfLHrjSVQrVx1GPCAHefrQ/qjOeNxttMH2q+W2i/dqht9XwzMy696RUTKaW7eTeBXKvBf1Wht6x4yMGJtQ87X0Ck2WTf6EjuXW+rT5pE+aF2IDolhko3/esmwEOfnT0k7ZyNb12ehqPiH8SZrUvKCX9AuZW/Kdh1TTq9sQZIzNJ7R8nuW0lktujir+BQ)](https://sandcastle.cesium.com/#c=tVRNj9NADP0rViVESkPasgIh2q5ABU6LWLHAZcthNnGaEZOZMuO0LGj/O56P9IMFiQs9pBnb79l5tqc02hHUVrT4QRDCAp5NZis9HsOuQQ34rRPKARmYAjVoEaQDAUqsAbdob8FhaXQFAXHTUUStLTKXZYTQDJQEjoQlqdeeaWfsV2gNc7nWGGrUbYRnxHzsLxm1Rv/2JH+aTydDdpehTP/EsiO5xU+bilM4rnc6691kSKg3miTJ4Dmb+N/ejcnz0SxDhku0kSWRbIWFrcQdF74AjTtYopNdW3wOtuxhGY5Lo0lIjfZhDj9XGoC/bI30dq/gi4OaK3039MSBoHAlaiwqvOnWV43ZBYTjIq6ihAsg22GqozRKYUnS6NNaLo3UdGllK70Iy31Udi/Ppg9yhaiq7EA4TCk2nsrLdP2FLaEDr6oKppNJzqr1bu6CFboyLRuc9Hi30rWxkHkOyfDJjP/mp+KzaTQaRn0AfKQSxLHwTlBTRMJsCI/g7NkEHsP0OZMcxRoelH8JjjUWm841Rx8YvjeljlGxcO5MUnHJw8hvQp8VtTXta+SBRZdxjXlIPsyP0PI7qiv5A1/ANFrvhl7Cu6RZGqF9ElODUKqX73hJouxKOPooWz90rxlYaLPL+pa40goqm9OWH4rdx0nCNii/0grT9qbzbzOQ9sRL8mbLC3AhHbHHZnWn0+DELiVcyUxWFJabSXiBNYWcALLOYpb5H5bwpNEyFeLPu0YqzPx0/HX3/v+QHAbl2us2Gn0p9s1a/OtE5DDJodMV1rz6Vd53ajg75GCJYl8Wi34wFeo1NftP3Ece2teb7o54RqPkCMbwCNone9/t+P/gcNvM0nUzyAdzR7cKzyPNS9lujCXorMqKYszJN8q3bXzTlV+RitI5D5uPe9C8kluQ1WI1+O3KWw2g5Pl17Kk7FbZiNTifjzn+BKaMqPiyf8/Dr8StD2mm5xfRWBTFfMzH+ygyRt0Ie8T4Cw)

**Comment by alon6699** [comment]
Notice: I renamed 'updates' variable to 'consecutiveUpdates'.
Profiler result when consecutiveUpdates set to 1 (updating one entity once per second)
![image](https://user-images.githubusercontent.com/26170942/231816843-ef1eb65b-3fa8-46e7-976b-ac28d7d39e62.png)

Profiler result when consecutiveUpdates set to 2 (updating one entity twice in 2 consecutive frames per second)
![image](https://user-images.githubusercontent.com/26170942/231816621-5d23db1a-dac1-4cff-ac5d-0818c6e3101f.png)

**Comment by alon6699** [comment]
Hey, after some digging I found out that this behavior doesn't replicate in other types of entities like (Polylines, Polygons and Labels). And it just get a lag with frame rate drop (in primitive and not primitive entities).

**The general solution for this issue is just separate to more datasources.** 

When updating single entity in huge datasource it probably makes a lot of calculations and makes the lag. 

_I still can't understand why points have such strange behavior._

You can close this issuse if you don't have any new ideas or suggestions.

**Comment by ggetz** [comment]
> The general solution for this issue is just separate to more datasources.
> When updating single entity in huge datasource it probably makes a lot of calculations and makes the lag.

This is due to how [point primitive collections are designed for performance](https://cesium.com/blog/2016/03/02/performance-tips-for-points) under the hood. From the [`PointPrimitiveCollection` documentation](https://cesium.com/learn/cesiumjs/ref-doc/PointPrimitiveCollection.html?classFilter=pointP#PointPrimitiveCollection)

> Organize collections so that points with the same update frequency are in the same collection, i.e., points that do not change should be in one collection; points that change every frame should be in another collection; and so on.

I'll go ahead and close this given the above. Thanks @alon6699!
