### ISSUE TITLE
nvidia geforce gt 730   requestWebgl1:true   

### ISSUE THREAD

**Issue by 1wobuzhidao1** [CesiumGS/cesium#11225]
cesium version:103
NVIDIA GT730 graphics card
sets requestWebgl1 to true, but still reports an error 
![1681300450292](https://user-images.githubusercontent.com/76717277/231449201-cd44dbf7-12e8-4085-bdd4-2f0fb6645850.png)
but cesium version:101 no error;

`const viewer = new Cesium.Viewer("cesiumContainer", {
        baseLayerPicker: false, //关闭图层选择器
        //放大镜图标，查找位置工具，查找到之后会将镜头对准找到的地址，默认使用bing地图
        geocoder: false,
        //房子图标，视角返回初始位置
        homeButton: false,
        //经纬网图标，选择视角的模式，有三种：3D，2D，哥伦布视图（2.5D)
        sceneModePicker: false,
        //地图图标，图层选择器，选择要显示的地图服务和地形服务,默认会用到cesium.ion
        baseLayerPicker: false,
        //问号图标，导航帮助按钮，显示默认的地图控制帮助
        navigationHelpButton: false,
        animation: false, //动画器件，显示当前时间，允许跳转特定时间
        timeline: false, //时间轴
        //全屏图标，全屏按钮
        fullscreenButton: false,
        //虚拟现实
        vrButton: false,
        //阴影
        shadows: false,
        //点击后显示详细信息
        infoBox: false,
        //展示数据版权属性
        CreditsDisplay: false,
        //terrainExaggeration: 3.0, //地形夸大
        shouldAnimate: false,
        contextOptions:{
          requestWebgl1:true
        }
      });`

**Comment by ggetz** [comment]
Hi @1wobuzhidao1.

I'm having trouble replicating the error. 

Could you please visit webglreport.com and take a screenshot of your results?

Also is there any additional code beyond this example here?

**Comment by GatorScott** [comment]
Please go to https://github.com/CesiumGS/webglreport to download the web page source.  Unzip it then open index.html to get the results.  You should be able to share as you did previously.

**Comment by 1wobuzhidao1** [comment]
> Please go to https://github.com/CesiumGS/webglreport to download the web page source. Unzip it then open index.html to get the results. You should be able to share as you did previously.

thank you ,i have a try.

**Comment by 1wobuzhidao1** [comment]
> Hi @1wobuzhidao1.
> 
> I'm having trouble replicating the error.
> 
> Could you please visit webglreport.com and take a screenshot of your results?
> 
> Also is there any additional code beyond this example here?

**Comment by 1wobuzhidao1** [comment]
> Hi @1wobuzhidao1.
> 
![webgl2](https://user-images.githubusercontent.com/76717277/231630748-c26a20e0-4ed1-4428-b75e-fd1a34bd3d67.jpg)

> I'm having trouble replicating the error.
> 
> Could you please visit webglreport.com and take a screenshot of your results?
> 
> Also is there any additional code beyond this example here?

**Comment by 1wobuzhidao1** [comment]
![webgl](https://user-images.githubusercontent.com/76717277/231631012-ab724124-68fe-4406-896c-dff3b3ca126b.jpg)
@ggetz

**Comment by ggetz** [comment]
Thanks @1wobuzhidao1. It looks like `layout` in used in `AdjustTranslucentFS` regardless of whether webgl 1 or 2 is requested.

**Comment by ggetz** [comment]
@jjhembd Would you be able to take a look at this and see if it's a quick fix?

**Comment by jjhembd** [comment]
Hi @1wobuzhidao1, this was a bug in `demodernizeShader.js`. I just opened #11230 to fix it.

I would like to confirm that #11230 fixes your problem, but I am not able to run your example code. Can you share a Sandcastle link that replicates your problem? Here is how to do it:

1. Go to [https://sandcastle.cesium.com](https://sandcastle.cesium.com)
2. Edit the "JavaScript code" window with your code
3. Click on the "Share" button and copy the provided URL

**Comment by 1wobuzhidao1** [comment]
> 嗨，这是中的一个错误。我刚刚打开#11230来修复它。`demodernizeShader.js`
> 
> 我想确认#11230解决了您的问题，但我无法运行您的示例代码。你能分享一个复制你的问题的沙堡链接吗？这是操作方法：
> 
> 1. 转到 https://sandcastle.cesium.com
> 2. 使用您的代码编辑“JavaScript代码”窗口
> 3. 单击“共享”按钮并复制提供的URL

hi ,you need a computer that unsupport webgl2  and click https://sandcastle.cesium.com/#c=bY5NSwMxEIb/SsipQknotU0XoVehB0EvuWSzYw3OJmtmsm2V/nezK0XRzu193g/Gp0gsxgBHyGIrIhzFDiiUXj3NbGGln/UuRXYhQrZy+WmjEL4COPF+4FA31jO7Xob3AsTP0B5wteZc4Me92Hi529gol9IQnxGaq3cf+iFlFiXjQinN0A/oGEi3xb8BK080Faeo0b+rpgujCN32xq/CoyOqzktBfAwfYGVjdM3/q2JyXYiH/QgZ3XmKva6ah2+olDK6yttNTglbl/8sfwE

**Comment by jjhembd** [comment]
Hi @1wobuzhidao1, the Sandcastle link you provided only shows this code in the "JavaScript code" tab:
```javascript
const viewer = new Cesium.Viewer("cesiumContainer",{
  contextOptions:{
          requestWebgl1:true
        }
});
```

This does not trigger any errors.

The `AdjustTranslucentFS.glsl` code pointed out by @ggetz is used for [Order Independent Transparency](https://cesium.com/blog/2014/03/14/weighted-blended-order-independent-transparency/). I tried replicating [the demo from that article](http://bagnell.github.io/OITDemo/) in a new [Sandcastle using the latest Cesium version](https://sandcastle.cesium.com/#c=1Vptc9s2Ev4rGN3cDHWRaTupro1kZ8527Wtm6jgTq2mnlqcDkZCIHEXoSNCWLqP/3sXihSAly7LjxD19sAVgsdh9nsUuASoSWSHJ52FGyLGY/5uJKZP5oqPaJzSXrOA0e4XNDyySNJukrCbkerF1TmXO59/h90FOs2Is8mmBTTvrLaxHs0jLn6YpnxWCxzWd71lupU5EKvKj2YzR3E3Cvqa6Iwkrj0rpiTgnxCSns4RHWnnOp1zyGyW4JIfkBFwsp/1hNswixOKGs1uWw0jGbs1o+BH7gmErwvaJyCTlGcuHrY7GDqZKNpcXM8lBSY98Jjn7b8kK+SsbTdL9HpF5ychSrdn21vpMiohlMADL6XVhELvCmI3KyWUibs9yOmUFYHLJYFIMkkpXTcnM+lSgJlTQr4YFl1V/qNbxBpmlwBOZpGLkrzAxYIPA1TX2j8ssUq6SKGdUMgdqEYyojJK2RqWyK8zZVNywozQNlP/EqQxTlk1kApr3UDFCCUtORcxSHU4wZuIqnJap5LN0cbzA6EqpsiFQs/x4Cxkt5DuRy+SX2UCc8TmLEUQjSCqfw8gLj4FwER/4YROOczH9kU1yBu7t/POHcK9DvtsL99ptra/d0f8xXtyeCfaUHP7p7qkPTPAEjUcB6mjXXBcQxbnbGTbATUA24z74rHVaPHsotbKvrBghNwwsnJ8BTlT2Nmy18OPph8Hpb3+cXXw4Pxp07PScxpz3mr5aDytfV71e2i8etT2/YYap3clqG9llI2Vc756tj0ShiGPasIJ9aNW+Y2Uv7LatmLMR/y/rfIyqvPhgMrycqsOIT1lWqBzxZIzETuUKLd93LRmr3/4ytPiMbEdLyiShDhbDxd24WaQlpowSMpzU+dhoj1JRsNjrcgvxManlMy9tzcoice54eY7GccNLlxsrxn1N1miA9WpNpHXuSAfXHV9ZhUbP++6JLCtMTdLCLLyEVFiwZ3Pu8U50ntq6r4qyn01yFrtnpkfl9pXnsMq53A71Kql69XrdVXvsJe60nR+w8cpLBl+YjFwu+QslC436Akq+uH1O4NHel10NPDZedZ8MeEISxicJTNy39febMvKYqpqW7Bn5qGIf+Pi+657pnpqPl9+aj2pz7G/Jx5OV0merm/44WZthO3WRO9JBQ2ptiNZk/u+q8L3YPGcR3oaV57Tv/nh4kieEKZ3/TCXsxS5s477XzzPd/6reD6fgtxmcw+EYoEZfho2TNKiDg/oh2dlX5aehUI+8rg+kItukcUJn0LvfXIdnP2HSU2Mm6/VrZrjhbjVcCXALdHXLQAic50mgnvdTNFT70sfWgbFft14c1q1+oax06adSgwBqhPvYemNw1a2dwzqcdTXWVMzT9oYIsy4clZIQyI7FNGh3yOamysnGP/Vxjtd3PNlYCutBem9B3LIs1sWJgrSz0qdgqqHUWTMNkPP5WKel3tVuiHxh/a1X4RoB5B8kqKJxpwrcNhjtGg1NbA5lLmbxT0ZjVdLtxq4ngnXl/XFFHuXr2pfrM0rflHcvo3zjSuxC+SvURbeHP+FlIfw78LaOvkbskxcvPnnbdb2zG9zd6PBml68+XTdi5l6/fc+d76tELms3rkUibo9FmcU8m1zOEpbDvlV9xm0HE9cwcYCpcdmqUOIrAXHFr6tLZ7vAR5GWU/VcqFbor7eHpZBLzllW6tvvAPZ72SFCX4WbZUzrSo2FegaDU3bM5tch9GMH3gzXdQM5AyHSEc2V/sBoAeVZlED2Ym13+64qDIiApbGISpVyQn01fZpiAgqGLb3KsKXhRUuilBbFO4oe2sv9Hdh/UmTDViVmlwMp+xUH3VITJs06x4u3EE8tqa2GxULFfBafJDyNEZp2s7QhUR0C3Cj92kXHlKIPvtcpM/fEKLrJYy1hPbYshOpNhXqFoau7pQboVwN10RsKzzx1IewyUoiO76CWa9ciRVsrxQSqzcXbwTmTiYirIr+7C3UJIiEHbBkZq4t6ECZRwqL/IEjnHwakKGczkUv7coRnsD1pyv/H9MV+27020aoCDXJjTZ0FEEPlaQ8ohzFyy2VCzvWbBQaFEW0Z0BxILYYt3K42RHvEhWbg2BBchn94JyKw91KbW72rWSuHS0IAVtJjCglPg1e9KqoAopmQsOENSNpuACfmBR2lLK7DNrXqK/A2WmrX3sJM49SDuFCV6D7VBtK7adtE3HvQwyxh91B2D2kVDVvy5rHsHa6Xhr2RSabkRmfTAiapJi8ITW/pwjHE4m1i9iidJZQcQ1ZQSr84Qn1nvyhEC6Z2ORkxzMXK+BVvrvYa6X6YNVJ8Y0Jn1Z2VeiMTDiWhMRHx91+16vGz346OzEtalYGUvkZgKQlymuGG2jaYdLiP55Re5LF6Uo2ZSokA4MBhGS3WxknnLhN+NJv6yW3w+a6MuL6bDA+zh9LhTV0hBB9LWbypfvFsVpqCbaRDuZiZYq0S3UjMsU7bUexk3jvyB1doo6ntzVVebpqP476Ohj8DoPWdiBlMOlba3ZkO5vqA4IPdxy3x0MJ3wGEGKzQs52bAe55Z5XPN46Wi1GpDHh+DrF77KwGrnlmJNZsYux2+Njw2+b3yQ4am0+TOJ+8KagtOc8HA51mdGPIysknoTrZjfqO59ieEhVzAoT0qCuU9Un/LY5n0yOvu3/v2cPm3MX4wGB5MlL+cqd2+ARsIqWwf5Qb8bad6XL6nmbpgYGP1K5ASDoBxTicPVPc0lgx4qi8I4hgeMJ7ZmN+FmIIxOd5arNjS6rQOMDTe2ILwLz7Fkl3maRCGu5JNZyloLHZHJYSqVCFkzwUHu/7UAwg8wuPDNb92InhggpFxmaaX8Mg3bL052AX5lampoGqbXNywPKULJZbsv/lZd4ZheLALzfUzXVTWxv8E). This also does not trigger the error you described, although it has a different bug for the "OIT with Multiple Passes" option.

**Comment by 1wobuzhidao1** [comment]
hi ,you need a computer that unsupport webgl2 and to click 
https://sandcastle.cesium.com/#c=bY5NSwMxEIb/SsipQknotU0XoVehB0EvuWSzYw3OJmtmsm2V/nezK0XRzu193g/Gp0gsxgBHyGIrIhzFDiiUXj3NbGGln/UuRXYhQrZy+WmjEL4COPF+4FA31jO7Xob3AsTP0B5wteZc4Me92Hi529gol9IQnxGaq3cf+iFlFiXjQinN0A/oGEi3xb8BK080Faeo0b+rpgujCN32xq/CoyOqzktBfAwfYGVjdM3/q2JyXYiH/QgZ3XmKva6ah2+olDK6yttNTglbl/8sfwE

**Comment by 1wobuzhidao1** [comment]
> Hi @1wobuzhidao1, the Sandcastle link you provided only shows the following code in the "JavaScript code" tab:
> 
> ```js
> const viewer = new Cesium.Viewer("cesiumContainer",{
>   contextOptions:{
>           requestWebgl1:true
>         }
> });
> ```
> 
> This does not trigger any errors.
> 
> The code pointed out by @ggetz is used for [Order Independent Transparency](https://cesium.com/blog/2014/03/14/weighted-blended-order-independent-transparency/). I tried replicating [the demo from that article](http://bagnell.github.io/OITDemo/) in a new [Sandcastle using the latest Cesium version](https://sandcastle.cesium.com/#c=1Vptc9s2Ev4rGN3cDHWRaTupro1kZ8527Wtm6jgTq2mnlqcDkZCIHEXoSNCWLqP/3sXihSAly7LjxD19sAVgsdh9nsUuASoSWSHJ52FGyLGY/5uJKZP5oqPaJzSXrOA0e4XNDyySNJukrCbkerF1TmXO59/h90FOs2Is8mmBTTvrLaxHs0jLn6YpnxWCxzWd71lupU5EKvKj2YzR3E3Cvqa6Iwkrj0rpiTgnxCSns4RHWnnOp1zyGyW4JIfkBFwsp/1hNswixOKGs1uWw0jGbs1o+BH7gmErwvaJyCTlGcuHrY7GDqZKNpcXM8lBSY98Jjn7b8kK+SsbTdL9HpF5ychSrdn21vpMiohlMADL6XVhELvCmI3KyWUibs9yOmUFYHLJYFIMkkpXTcnM+lSgJlTQr4YFl1V/qNbxBpmlwBOZpGLkrzAxYIPA1TX2j8ssUq6SKGdUMgdqEYyojJK2RqWyK8zZVNywozQNlP/EqQxTlk1kApr3UDFCCUtORcxSHU4wZuIqnJap5LN0cbzA6EqpsiFQs/x4Cxkt5DuRy+SX2UCc8TmLEUQjSCqfw8gLj4FwER/4YROOczH9kU1yBu7t/POHcK9DvtsL99ptra/d0f8xXtyeCfaUHP7p7qkPTPAEjUcB6mjXXBcQxbnbGTbATUA24z74rHVaPHsotbKvrBghNwwsnJ8BTlT2Nmy18OPph8Hpb3+cXXw4Pxp07PScxpz3mr5aDytfV71e2i8etT2/YYap3clqG9llI2Vc756tj0ShiGPasIJ9aNW+Y2Uv7LatmLMR/y/rfIyqvPhgMrycqsOIT1lWqBzxZIzETuUKLd93LRmr3/4ytPiMbEdLyiShDhbDxd24WaQlpowSMpzU+dhoj1JRsNjrcgvxManlMy9tzcoice54eY7GccNLlxsrxn1N1miA9WpNpHXuSAfXHV9ZhUbP++6JLCtMTdLCLLyEVFiwZ3Pu8U50ntq6r4qyn01yFrtnpkfl9pXnsMq53A71Kql69XrdVXvsJe60nR+w8cpLBl+YjFwu+QslC436Akq+uH1O4NHel10NPDZedZ8MeEISxicJTNy39febMvKYqpqW7Bn5qGIf+Pi+657pnpqPl9+aj2pz7G/Jx5OV0merm/44WZthO3WRO9JBQ2ptiNZk/u+q8L3YPGcR3oaV57Tv/nh4kieEKZ3/TCXsxS5s477XzzPd/6reD6fgtxmcw+EYoEZfho2TNKiDg/oh2dlX5aehUI+8rg+kItukcUJn0LvfXIdnP2HSU2Mm6/VrZrjhbjVcCXALdHXLQAic50mgnvdTNFT70sfWgbFft14c1q1+oax06adSgwBqhPvYemNw1a2dwzqcdTXWVMzT9oYIsy4clZIQyI7FNGh3yOamysnGP/Vxjtd3PNlYCutBem9B3LIs1sWJgrSz0qdgqqHUWTMNkPP5WKel3tVuiHxh/a1X4RoB5B8kqKJxpwrcNhjtGg1NbA5lLmbxT0ZjVdLtxq4ngnXl/XFFHuXr2pfrM0rflHcvo3zjSuxC+SvURbeHP+FlIfw78LaOvkbskxcvPnnbdb2zG9zd6PBml68+XTdi5l6/fc+d76tELms3rkUibo9FmcU8m1zOEpbDvlV9xm0HE9cwcYCpcdmqUOIrAXHFr6tLZ7vAR5GWU/VcqFbor7eHpZBLzllW6tvvAPZ72SFCX4WbZUzrSo2FegaDU3bM5tch9GMH3gzXdQM5AyHSEc2V/sBoAeVZlED2Ym13+64qDIiApbGISpVyQn01fZpiAgqGLb3KsKXhRUuilBbFO4oe2sv9Hdh/UmTDViVmlwMp+xUH3VITJs06x4u3EE8tqa2GxULFfBafJDyNEZp2s7QhUR0C3Cj92kXHlKIPvtcpM/fEKLrJYy1hPbYshOpNhXqFoau7pQboVwN10RsKzzx1IewyUoiO76CWa9ciRVsrxQSqzcXbwTmTiYirIr+7C3UJIiEHbBkZq4t6ECZRwqL/IEjnHwakKGczkUv7coRnsD1pyv/H9MV+27020aoCDXJjTZ0FEEPlaQ8ohzFyy2VCzvWbBQaFEW0Z0BxILYYt3K42RHvEhWbg2BBchn94JyKw91KbW72rWSuHS0IAVtJjCglPg1e9KqoAopmQsOENSNpuACfmBR2lLK7DNrXqK/A2WmrX3sJM49SDuFCV6D7VBtK7adtE3HvQwyxh91B2D2kVDVvy5rHsHa6Xhr2RSabkRmfTAiapJi8ITW/pwjHE4m1i9iidJZQcQ1ZQSr84Qn1nvyhEC6Z2ORkxzMXK+BVvrvYa6X6YNVJ8Y0Jn1Z2VeiMTDiWhMRHx91+16vGz346OzEtalYGUvkZgKQlymuGG2jaYdLiP55Re5LF6Uo2ZSokA4MBhGS3WxknnLhN+NJv6yW3w+a6MuL6bDA+zh9LhTV0hBB9LWbypfvFsVpqCbaRDuZiZYq0S3UjMsU7bUexk3jvyB1doo6ntzVVebpqP476Ohj8DoPWdiBlMOlba3ZkO5vqA4IPdxy3x0MJ3wGEGKzQs52bAe55Z5XPN46Wi1GpDHh+DrF77KwGrnlmJNZsYux2+Njw2+b3yQ4am0+TOJ+8KagtOc8HA51mdGPIysknoTrZjfqO59ieEhVzAoT0qCuU9Un/LY5n0yOvu3/v2cPm3MX4wGB5MlL+cqd2+ARsIqWwf5Qb8bad6XL6nmbpgYGP1K5ASDoBxTicPVPc0lgx4qi8I4hgeMJ7ZmN+FmIIxOd5arNjS6rQOMDTe2ILwLz7Fkl3maRCGu5JNZyloLHZHJYSqVCFkzwUHu/7UAwg8wuPDNb92InhggpFxmaaX8Mg3bL052AX5lampoGqbXNywPKULJZbsv/lZd4ZheLALzfUzXVTWxv8E). This also does not trigger the error you described, although it has a different bug for the "OIT with Multiple Passes" option.`AdjustTranslucentFS.glsl`



> hi ,you need a computer that unsupport webgl2 and to click
> https://sandcastle.cesium.com/#c=bY5NSwMxEIb/SsipQknotU0XoVehB0EvuWSzYw3OJmtmsm2V/nezK0XRzu193g/Gp0gsxgBHyGIrIhzFDiiUXj3NbGGln/UuRXYhQrZy+WmjEL4COPF+4FA31jO7Xob3AsTP0B5wteZc4Me92Hi529gol9IQnxGaq3cf+iFlFiXjQinN0A/oGEi3xb8BK080Faeo0b+rpgujCN32xq/CoyOqzktBfAwfYGVjdM3/q2JyXYiH/QgZ3XmKva6ah2+olDK6yttNTglbl/8sfwE

**Comment by jjhembd** [comment]
Hi @1wobuzhidao1, could you test the branch in #11230 and see if it works for you?

**Comment by 1wobuzhidao1** [comment]
> Hi @1wobuzhidao1, could you test the branch in #11230 and see if it works for you?

![微信截图_20230420180622](https://user-images.githubusercontent.com/76717277/233334518-9d5d0a40-d2e4-410b-931e-073ecf51b46d.png)

**Comment by 1wobuzhidao1** [comment]
> Hi @1wobuzhidao1, could you test the branch in #11230 and see if it works for you?

![image](https://user-images.githubusercontent.com/76717277/233518063-affe984c-ea7e-4a43-a7a2-ff10c2a14cd0.png)

**Comment by jjhembd** [comment]
Hi @1wobuzhidao1, it looks like we don't have the shader compilation bug anymore. And based on the test in #11230 the bug in `demodernizeShader` is fixed.
For the new error, you may need to update your drivers to make sure WebGL is working on your hardware.
