### ISSUE TITLE
how to add I3s layer by local coordinate 

### ISSUE THREAD

**Issue by wycode** [CesiumGS/cesium#11236]
I got local coordinate infomation with prj4 string ,but  not supported by  current cesium code .  I transformded local points to wkid 4326,  but  displayed  not expected . Please, someone help me .

**Comment by ggetz** [comment]
Hi @wycode, CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
