### ISSUE TITLE
Geojson rendering issue: polygon lose fill

### ISSUE THREAD

**Issue by Wuzh994** [CesiumGS/cesium#11238]
Sandcastle example: https://sandcastle.cesium.com/#c=tVd7b9s2EP8qN++P2ahDSZFs2XFSLM2jj3VpUWcbhrhoGYm2uMiiQFJxvcDffUdRsuQ82g7DDBiWeO+7393RkciUhlvOVkzCEWRsBSdM8WJJfi/PurNOVL6fiExTnjE56/Qms2yWRaXkX0pkKPf5Do/0rKPXOZt1DmDWOWdUF5KdiDRlkeYim3X6lmduKcrwXVm5xyRrfqQtmFgyLdeGXgvsiLwX6XrRmCipkRAy5hnVlaUtRbce8WUv9Inv7ge+6/dhRFx/OBiPBx9REzzyudrzPI8M/XAwDkd98PbJKByPBu7oKwL7ARkF3ng/CPowHJLQG3iB7z0p4LkDErjD0TBEf3wSBm44HoZPs4dk4Pv7Ix+1DwIydIfD8Xj8tDu+T8ah73mDPvgBCYdBOB4EH/v/KSePszcqt4/Vw2Zb2lyKnEnNbZHaxeU6rarrDUee54ZB6A788U6NlZbipuL6ceS5XuA+Qt8TOY24LuHjEfchfcVjnRiqv0Od8zStdLvu+Xng7eg21LZmlwTjKjrzs8FQN5+xUxzn7Atd5ikD7wDeChrDiusEYjanRapB6XXKswWZZVOaxRFVGDahcXxq6ZdCpNdUvii0Fhk24+muGHoE8yIrGwy6PZNAqLqZxFTTqSgk9q9R2LXFq7r7JRNvsHVPtzwkRde6dYHfTN9dkJxKxbqmw3v2vPwx3b+xI6AJbb8d2jVVPKo9BJEb59SDAO9H9qIt9X/FNesQ4kxLnw2Lk7FPnrv8VKhPSptJQbTIhYm4LLWVuWtQb/FyUBvD4SYkefXu8v3ri19azWGgcY/JcBCTneM0T2jXJYNe/77ePwwMEYRbwuZbafcP4DjP0zVEhdJiCQtJ84RHCuhc4zw3oX8z7ydW9GuJd5wpYzHohIFEXcidFctrNLBguBCoFhLm+JUsx9FNr9ExHO+IUlP0bWV+pTohiukPpYaLUoFR23VtVAB2o+BEWHLFcKl8T0n/RUHrLEJtwmogGFbWbWJu4NVrSv8E9Fq8VQzm4zgvmS6zRaWkaxBzYBnOMzPkKhYban2KsTaaSH1KbmlaMNVSbKUiA6hXVCUodreZ1ERTgW6KhjmeuxP8OdwaICnLFjrBw2fPem1AO845ijEaJZZ33YdIYhHR9brUpTnT04gAzI8Jq0wtZHTJSFvVFLe0pSlI6C2DJWKAG5zWfvRBCVgZJiFZqcpq5xnQtqbERIesOqHa8BfKcis0WYmYcM2RUS0rsy1vWgleYz5qB674x8l9JhNHzbIm5q3FYhJqDR41ib8yTG1FfA7dH0ryTnZhK7ozC+YIP9sF3bvdjUrNcKiXVHO86U0eKG38qD1r8WwazNjutXDM7TUJlpgryWkKWgBibqfSrRxWGamkyFbqoT3H+cCW4tYWSRQaJwlTT2uqOFDRnKaKTXa9PfuiZRGzHY8fwu8nhcS8SKnpWgJw1mC4raxEmrK6tleNLXjMaMFNB9WVFDiijaqqBWIwhdrJI8+i2q/aNHCctpAUC1YNxb4BbMxvOYZwvYaB+3QemI00fsX4ItFw1C5yzbp1mrxvbDpGrTu5tyc21ZomEdVR0hppTModZDrOKVd5iqOJZmtAKpIVWoxEkWGNMfJVwrFtzZy1dxMrt+KIkxWhKXpUKZ3Uptvr6QNTFeJUhBsCtbEMFG6/KDE3ghixcu8+IEuJo+/a+bKE2nGaduuh2yA8woaQ1OCawm9TQOs2Hs1TU1CjDWOOK2cQVtGNYUaFxjEcQysh0xha/x1IywurHdePuDnWu/eOEyqRmdPML9v7lC0kY6q7N8brcB8CrFa971t/sRohvBAg2x7exV38mGd/7NvHXrO3HnPjEptXIZ6X3WbPSv4lIK9Pzy4uX1/+WVYGv51+59Asefa8LufPfJkLqaGQaRe3qGa4RU3IznUR3TBNIqXq+h46bdFDhDfw+OiR/4YQpVQppMyLNJ3yv/Fy/vzQQf4HohW43t0yiUg0bIn3/G2FOEIOHXx9XFLbG8w9zf8A

Browser:
Chrome Version 112.0.5615.49 (Official Build) (arm64)

Operating System:
macOS Ventura 13.2 (22D49)

Screenshots:
![image](https://user-images.githubusercontent.com/84833907/232509835-f542e67f-1966-4479-8cb5-8f428f11967c.png)

**Comment by ggetz** [comment]
Thanks for bringing up this issue! It's a valid concern, and we're already tracking it in a previous issue, https://github.com/CesiumGS/cesium/issues/4871. I'm going to close your issue now to keep the discussion in one place. If you have any further input on this, please post it there instead.
