### ISSUE TITLE
Heading value changes drastically after camera.flyTo with W-E or E-W heading direction  

### ISSUE THREAD

**Issue by worldwidepaniel** [CesiumGS/cesium#11233]
Hi, I wanted to create a functionality that lets users look into a specific world direction after a click of a button (i.e North-South, South - North, etc ). 
I decided to go with this approach 

https://sandcastle.cesium.com/index.html#c=ZVFbT4MwFP4rJ7wACRZw0UVli4rxSWPipk+8nMFhayzt0haWafzvFtiMlzbp5XyXfm071NBx2pGGGUjaQU6Gtw17HWqBXw7bXEmLXJL2w6tC9n2BsirRWEEMq2qplFihvm2tVTLwc2xII9yLPSwVvCxu/AjqVpaWOzSEj0KCa+OxrBzIrBb7pQoOUEXGcok9//KYKEdt3QrlhNVaNXe01kQmOEnTKUvPI5icsmkaQXqWJAlLwmh0UpqTyz46HdwBNoQVl+tv70e0G2bVs6uiNMFFEo7Mz3767O88DF7kZcbuBc1H+Jo3W6UttFoEjMWWmq1AFzJeteUbWVYa08uy+CjKKt4Br2aF9+ddCw9KgcY4pG6FWPB3Krx5Fjv+L5lQQ/CnjrTAfU/ZpPOHscgYy2K3/a+y4/f8cPwC

If I try to rotate the camera (change it's heading) after it has flown to the given point, it changes heading drastically (about 90 degrees depending on where you grab from what i've noticed )

The problem is not present at very high altitudes ( try adding changing 15000.0 to 1500000.0 on the attached sandcastle )

Is this a wrong approach on my end or maybe it's a known bug? I tried searching but couldn't google a similar problem

Thanks for your answers!

**Comment by ggetz** [comment]
Hi there @worldwidepaniel,

I think this is expected behavior. You've set the camera's heading by 90 degrees when the flyTo completes:

```
orientation: {
      heading: Cesium.Math.toRadians(90)
    }
```

You can use `setView` to adjust the orientation again.
