### ISSUE TITLE
最新 API 页面，对于 Cesium3DTileset 介绍中示例代码有误。

### ISSUE THREAD

**Issue by Southjor** [CesiumGS/cesium#11237]
链接地址：[Cesium3DTileset](https://cesium.com/learn/cesiumjs/ref-doc/Cesium3DTileset.html#.fromUrl)

此页面有多处相同错误。

![image](https://user-images.githubusercontent.com/33611613/232428186-93b9e25f-0365-4fc5-ad4d-66e83c3fbce0.png)

Viewer 页面参数错误：[Viewer](https://cesium.com/learn/cesiumjs/ref-doc/Viewer.html#.ConstructorOptions)

![image](https://user-images.githubusercontent.com/33611613/232456351-6ef10ddd-3d72-41f6-ae44-1462e52bfc90.png)

**Comment by ggetz** [comment]
Thanks for the report @Southjor! I believe these have already been addressed by https://github.com/CesiumGS/cesium/pull/11221.
