### ISSUE TITLE
Polyline documentation missing arctype field

### ISSUE THREAD

**Issue by eric-g-97477** [CesiumGS/cesium#11248]
```
    viewer.entities.add({
      name: route.name,
      polyline: {
        positions: Cesium.Cartesian3.fromDegreesArray(flattened),
        width: 5,
        arcType: Cesium.ArcType.GEODESIC,
        material: Cesium.Color.GREEN
      }
    })
```

for example will add a polyline to the display. However, when I view the documentation for [polyline](https://cesium.com/learn/cesiumjs/ref-doc/Polyline.html?classFilter=polyline), it does not mention it accepts an arcType.

Perhaps this is mentioned elsewhere and should not be mentioned explicitly here. If that is the case, there should be some mention that other options for a polyline are available.

Are there other options other than arcType that can be supplied to a polyline?

**Comment by ggetz** [comment]
Hi @eric-g-97477, the name of the class to use here would be [`PolylineGraphics`](https://cesium.com/learn/cesiumjs/ref-doc/PolylineGraphics.html?classFilter=polylineGr), not `Polyline`. This is the case for all the different entity types, ie. `BillboardGrahpics`, `LabelGraphics`, etc.

I concede that this is non-obvious based on naming alone, but the relationship is documented in [`Entity`](https://cesium.com/learn/cesiumjs/ref-doc/Entity.html).

Happy to hear suggestions on how we can improve our reference doc, Sandcastle examples, or website tutorials to help make this relationship clearer.

**Comment by eric-g-97477** [comment]
Ah, makes sense. Thank you for the clarification.
