### ISSUE TITLE
Issues with rendering 3dtiles – Missing tiles with Insufficient buffer size error

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium#11254]
hello,cesium teams,
  I found that when loading 3dtiles tiles, there exist tiles which  are missing at some levels.Such as follows,
![image](https://user-images.githubusercontent.com/39166385/234555067-5ba7ab25-0b22-4125-8512-f106b4636522.png)

**Comment by ggetz** [comment]
Hi @engineerhe,

Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? Or be able to otherwise provide the tileset? That would help us give us more context to determine the issue. 

To confirm your 3D Tiles data is valid, you can run it through the [3d-tiles-validator](https://github.com/CesiumGS/3d-tiles-validator) and let us know the results.

Thanks!

**Comment by engineerhe** [comment]
Hi @ggetz ,
Thank you for your response first, and then tileset address is http://192.183.90/tileset/layer.json, When the load is finished locate this address 115.60096139316958, 32.431409313604654(longtitude,latitude,alitude), 30.028754144294794, and then scale, you will find that there are slices without rendering, [.webgl-000001C2002a8d00] GL_INVALID_OPERATION: Insufficient buffer size warning is displayed on the browser console.

**Comment by engineerhe** [comment]
Hi @ggetz ,
I'm sorry I didn't make that clear.The full code is as follows:
`const viewer = new Viewer("cesiumContainer");
let cesium3DTileset = new Cesium3DTileset({
    url: "http://202.96.98.106:9627/test/tileset.json"
});
cesium3DTileset.readyPromise.then((tileset) => {
    viewer.scene.primitives.add(tileset);
    // earthV.flyTo(tileset);
    viewer.scene.camera.flyTo({
        destination: Cartesian3.fromDegrees(115.6009, 32.4314, 30.028),
        orientation: {
            heading: 0.0,
            pitch: -Math.PI / 3,
            roll: 0.0
        }
    });
});`

**Comment by ggetz** [comment]
Thanks @engineerhe, I'm able to replicate this issue.

**Comment by IKangXu** [comment]
@ggetz Is there a plan to solve this problem? Version greater than 1.96 has this issue.

**Comment by IKangXu** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11358.
