### ISSUE TITLE
Unable to parse color from rgb/rgba CSS color string

### ISSUE THREAD

**Issue by aerialist7** [CesiumGS/cesium#11264]
Hi Team,

I've found a problem with parsing color from CSS string.
You can find a sample below.
It works correctly only with comma-separated rgb-colors, but CSS color can be different.

Sandcastle example: [link](https://sandcastle.cesium.com/#c=nZJPS8QwEMW/ylAPdkUzuOpF6yL0Kngo6qUg2XTsBtOkZNKu66c3za7gn0XEQg7zMu/NL0mVsxxg1LQmD9dgaQ0lsR468ZC0vM5Uqktng9SWfJ3NrmpbW0QonXGe4dm7DlYh9HyJ2NBIxvXkRefetDFSON8i2ZP7ChunGB9piWVVoZrMT6M0A6Fvlwe8iQNeU/IRVKmAtQ4r4F4qOmHqpZeBGkgWhiOsrUr0Kek00u/IE5aYqErmVFTBa9vmh3FOPr+4gN2aHU5H+RQy/0cIIIhdUkK/pVaqDcQumc9ge6rvsGd/nCN/pT3/T8oX3CnMGRLGtfn2Fj9GfFHne9Wzver5pGbHWcFhY2hRW0jfje565wMM3uRCYKCuN/E1GZeDeqEgFPNknFoL/GwtGj2Cbq73/IegjGSOO8+DMZV+ozpbFBj7f1iNk028jbuRvJGbqW11urjdikKIAmO53xmcM0vpvyW/Aw)

Browser: Latest Chrome/Firefox/Safari

Operating System: MacOS/Windows

Hope it will be fixed, because it's strange that I put valid CSS color as a value, but it parsed incorrectly.

**Comment by ggetz** [comment]
Thanks for identifying this @aerialist7. 

This would be a fairly minimal fix. The regex's in `Color.js` would need to be adjusted such that `,` becomes `[,\s]` to accept either a comma or a space. Then we would want to add a unit test or two to confirm the behavior is working.

Would you be able to contribute the fix?

**Comment by aerialist7** [comment]
Hi @ggetz, please take a look on #11271
