### ISSUE TITLE
Atmosphere not rendered if globe is not defined

### ISSUE THREAD

**Issue by jjhembd** [CesiumGS/cesium#11266]
Some tilesets (e.g. global terrain or imagery tilesets) are best rendered without a globe defined. For these datasets, the `Viewer` can be constructed without a globe:

```javascript
const viewer = new Cesium.Viewer("cesiumContainer", {
  globe: false,
});
```

However, turning off the globe also disables the atmosphere. See the [S2 Globe Sandcastle](https://sandcastle.cesium.com/?src=3D%20Tiles%20Next%20S2%20Globe.html). Users should be able to render an atmosphere even without the default globe.

**Comment by ggetz** [comment]
See @mramato's comment about hiding the globe after startup. In that case, the atmosphere is not actually turned off.
