### ISSUE TITLE
Map lag when executing a large calculation

### ISSUE THREAD

**Issue by alon6699** [CesiumGS/cesium#11265]
When executing a large calculation which takes more than 40ms I get a map lag if I am moving the map while running the calculation.
[sandcastle](https://sandcastle.cesium.com/#c=tVRRb9MwEP4rp0poCQ1uyqQJre0E2uBpiIkBL8se3OTSWHPsYjstBfW/c46TpmUve6EPbX3+7s73fZ+da2UdlIbX+JU7hAVcpLNMTSawrVAB/my4tOA0TMFVaBCEBQ6SrwB5XoHFXKsClo0L+JVBqmIIyxWlRLih4NsYtto8CbUCW2vtKrnLVN42btYF4S21nc4gUxtuYCNwSxUWoHAL12hFU7MfbSw6y9vltVaOC4XmLIE/mQJw3KzQfToMcTkMlKl9TPOEoszmqJAVuGxW95Xethn2Ds19GGMBzjQ4C+fItZSYO6HV6VnutFDuzohaOLHB6wMqetZn3YMs40URDQXjrsXal/LDPzxSpGX9Q1HANE2TNE37bSLfcFXomgJW+HybqVIbiHwNQenpjH7mPo8+9H88jgMxAB4iuSMQfOauYqFSFMNrOL9I4Q1M36We+QNWk0ovAYfDsXVjq6PJ2kG71gEVTkySdPRdc0OCC67OWWl0fYNkGbQRnTFpm8fJUbb4hfJe/MZLmIboPvbc7TuyvrfuGZroEriUPW/kPbPrHBr4lty6b6L2Lr+hRKb0Nuq1sLnhjhx9ovVw2ANOOKxbyjMlsbs53fof8TEcz1Pyka6BuxXW0Y6JykZ1jgkqdXk5VTKcGe0o6xZL1/YEEGUUusz763Kirui6+/W2EhKj3gv/3wSDER48L+PxIzuIsXip4gmkCTSqwJLudJH0SsSzoQdREHhfLHrjSVQrVx1GPCAHefrQ/qjOeNxttMH2q+W2i/dqht9XwzMy696RUTKaW7eTeBXKvBf1Wht6x4yMGJtQ87X0Ck2WTf6EjuXW+rT5pE+aF2IDolhko3/esmwEOfnT0k7ZyNb12ehqPiH8SZrUvKCX9AuZW/Kdh1TTq9sQZIzNJ7R8nuW0lktujir+BQ)
In the sandcastle above I am stalling the js thread (simulating a hard calculations) and it causes a visual map lag without any significant frame rate drop.
**The ‘stallingDuration’ variable controls the calculation time. Currently set to 100ms to make it more noticeable**
Do you have any suggestions to implement besides reducing the calculation time?

**Comment by alon6699** [comment]
hey sorry, the sand castle should be this:
[sandcastle](https://sandcastle.cesium.com/#c=ZZFPa8MwDMW/ishlLhtOe15aBusGg8IGZTvl4trqaubYRVYSupHvPjvryP5cAtZ7P+lJ0cFHhsjKOetf1y0ptsHDEhbz+TWUJVgPTax9pwg6iz1S0jz2cIvRto18GWviQo/P2+BZWY90MbtOzKjJqNGjNLhrX7eH0N+TajA+IW1RB29SO6YWk11PUfhAqLIkzDnRDJYr+Kg9QE6STMRJXitG6UMv8jiA/mAdiqkI1dl5CVOfsclQ+yEhEfnBM1KnnBDTiB8ZxN/T5EnDVT7P/N+OR8Lno8njlTF3HXre2MhJIbFvvc64OAc4czrdgpSkwIna4J7HTYb8Ka6KKvLJ4Sr7AW5scwxpl5ackLJkbI4uQbHctfoNWeoYM1aV31BlbAfWLOviz8+pC9BOxZiUfevc1r5jXayqMvl/YS4okzZ/7JCcOmXLYbHafBWllFWZnv8pDsHtFP3o+Ak)
So if I get it right the only good solutions is by reducing expensive calculations and using web workers.

**Comment by ggetz** [comment]
Thanks for the update!

Yes, if the main thread is stalled with other calculations, that's taking up resources which CesiumJS needs in order to render frames. You can use web workers to asynchronously perform large computations. Another option could be to [render less frequently with request render mode](https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/), but the web worker option is preferable here IMO.

**Comment by alon6699** [comment]
Thank you for the quick reply! In conclusion, request render mode wont work if I am moving the map with my mouse while the expensive calculations are running (in my case it was handling http request that contains lots of entities to render).
