### ISSUE TITLE
"ready" is deprecated, but is broken

### ISSUE THREAD

**Issue by paherbst** [CesiumGS/cesium#11274]
Starting with version 1.104, my custom TerrainProvider broke.  I understand "ready" and "readyPromise" are deprecated, but it was actually broken.

for example, one diff in 1.104 shows (
```
-    if (!terrainProvider.ready) {
+    // ready is deprecated. This is here for backwards compatibility
+    if (!terrainProvider._ready) {
```
This creates a dependency on ```_ready``` which is undocumented.  It also goes against convention in that variable names with a preceding ```_``` are considered private.  So this change creates a dependency on an undocumented private variable.

example
https://github.com/CesiumGS/cesium/blob/1.105/packages/engine/Source/DataSources/ModelVisualizer.js#L457

The change log for 1.104 doesn't mention this new dependency, nor does the normal documentation for TerrainProvider.

If ```ready``` is "deprecated", then why is ```_ready``` required for a terrain provider to work?

**Comment by paherbst** [comment]
more examples:

https://github.com/CesiumGS/cesium/blob/1.105/packages/engine/Source/Scene/Globe.js#L991

https://github.com/CesiumGS/cesium/blob/1.105/packages/engine/Source/Scene/GlobeSurfaceTile.js#L349

**Comment by ggetz** [comment]
Thanks for the report @paherbst. I think in these cases we can check for the existence of those properties and skip the async behavior if not present.
