### ISSUE TITLE
Please slow down the update frequency

### ISSUE THREAD

**Issue by pyp123** [CesiumGS/cesium#11279]
Please slow down the update frequency! For beginners, the files downloaded before will not work in a few days! Have you considered the sense of experience?

**Comment by ggetz** [comment]
Hi @pyp123,

CesiumJS typically releases once a month. 1.105.1 was an out-of-band release outside of the normal frequency.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
