### ISSUE TITLE
Custom web worder will block the rendering of cesium

### ISSUE THREAD

**Issue by Gxmg** [CesiumGS/cesium#11273]
I customized the web worker to process interface data, but all my cesium-related operations, such as loading primitives and layers, stopped

**Comment by ggetz** [comment]
Hi @Gxmg,

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

It would also help if you could include a code example to replicate the problem. Thanks!
