### ISSUE TITLE
105.1 Have a Fatal Error on 'https://sandcastle.cesium.com/?src=Cesium Inspector.html'

### ISSUE THREAD

**Issue by CHENJIAMIAN** [CesiumGS/cesium#11278]
### 105.1 Have a Fatal Error on 'https://sandcastle.cesium.com/?src=Cesium Inspector.html'
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <link
      href="https://cesium.com/downloads/cesiumjs/releases/1.105.1/Build/Cesium/Widgets/widgets.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="cesiumContainer" class="fullSize"></div>

    <script type="module">
      window.CESIUM_BASE_URL =
        "https://cesium.com/downloads/cesiumjs/releases/1.105.1/Build/Cesium";

      import * as Cesium from "https://esm.sh/cesium@1.105.1";

      const viewer = new Cesium.Viewer("cesiumContainer", {
        terrain: Cesium.Terrain.fromWorldTerrain(),
      });

      const scene = viewer.scene;
      scene.globe.depthTestAgainstTerrain = true;

      //Add Cesium Inspector
      viewer.extend(Cesium.viewerCesiumInspectorMixin);

      //Add Primitives
      scene.primitives.add(
        new Cesium.Primitive({
          geometryInstances: new Cesium.GeometryInstance({
            geometry: Cesium.BoxGeometry.fromDimensions({
              vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT,
              dimensions: new Cesium.Cartesian3(400000.0, 300000.0, 500000.0),
            }),
            modelMatrix: Cesium.Matrix4.multiplyByTranslation(
              Cesium.Transforms.eastNorthUpToFixedFrame(
                Cesium.Cartesian3.fromDegrees(-105.0, 45.0)
              ),
              new Cesium.Cartesian3(0.0, 0.0, 250000),
              new Cesium.Matrix4()
            ),
            attributes: {
              color: Cesium.ColorGeometryInstanceAttribute.fromColor(
                Cesium.Color.RED.withAlpha(0.5)
              ),
            },
          }),
          appearance: new Cesium.PerInstanceColorAppearance({
            closed: true,
          }),
        })
      );

      scene.primitives.add(
        new Cesium.Primitive({
          geometryInstances: new Cesium.GeometryInstance({
            geometry: new Cesium.RectangleGeometry({
              rectangle: Cesium.Rectangle.fromDegrees(
                -100.0,
                30.0,
                -93.0,
                37.0
              ),
              height: 100000,
              vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT,
            }),
            attributes: {
              color: Cesium.ColorGeometryInstanceAttribute.fromColor(
                Cesium.Color.BLUE
              ),
            },
          }),
          appearance: new Cesium.PerInstanceColorAppearance(),
        })
      );

      const billboards = scene.primitives.add(new Cesium.BillboardCollection());
      billboards.add({
        position: Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883, 150000),
        image: "../images/Cesium_Logo_overlay.png",
      });
    </script>
  </body>
</html>
```
![image](https://github.com/CesiumGS/cesium/assets/20126997/86ebece0-b3da-404c-be07-593d46f4e720)

---

### 105.0 is normal and there are no errors.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <link
      href="https://cesium.com/downloads/cesiumjs/releases/1.105/Build/Cesium/Widgets/widgets.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="cesiumContainer" class="fullSize"></div>

    <script type="module">
      window.CESIUM_BASE_URL =
        "https://cesium.com/downloads/cesiumjs/releases/1.105/Build/Cesium";

      import * as Cesium from "https://esm.sh/cesium@1.105.0";

      const viewer = new Cesium.Viewer("cesiumContainer", {
        terrain: Cesium.Terrain.fromWorldTerrain(),
      });

      const scene = viewer.scene;
      scene.globe.depthTestAgainstTerrain = true;

      //Add Cesium Inspector
      viewer.extend(Cesium.viewerCesiumInspectorMixin);

      //Add Primitives
      scene.primitives.add(
        new Cesium.Primitive({
          geometryInstances: new Cesium.GeometryInstance({
            geometry: Cesium.BoxGeometry.fromDimensions({
              vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT,
              dimensions: new Cesium.Cartesian3(400000.0, 300000.0, 500000.0),
            }),
            modelMatrix: Cesium.Matrix4.multiplyByTranslation(
              Cesium.Transforms.eastNorthUpToFixedFrame(
                Cesium.Cartesian3.fromDegrees(-105.0, 45.0)
              ),
              new Cesium.Cartesian3(0.0, 0.0, 250000),
              new Cesium.Matrix4()
            ),
            attributes: {
              color: Cesium.ColorGeometryInstanceAttribute.fromColor(
                Cesium.Color.RED.withAlpha(0.5)
              ),
            },
          }),
          appearance: new Cesium.PerInstanceColorAppearance({
            closed: true,
          }),
        })
      );

      scene.primitives.add(
        new Cesium.Primitive({
          geometryInstances: new Cesium.GeometryInstance({
            geometry: new Cesium.RectangleGeometry({
              rectangle: Cesium.Rectangle.fromDegrees(
                -100.0,
                30.0,
                -93.0,
                37.0
              ),
              height: 100000,
              vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT,
            }),
            attributes: {
              color: Cesium.ColorGeometryInstanceAttribute.fromColor(
                Cesium.Color.BLUE
              ),
            },
          }),
          appearance: new Cesium.PerInstanceColorAppearance(),
        })
      );

      const billboards = scene.primitives.add(new Cesium.BillboardCollection());
      billboards.add({
        position: Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883, 150000),
        image: "../images/Cesium_Logo_overlay.png",
      });
    </script>
  </body>
</html>
```

**Comment by CHENJIAMIAN** [comment]
[live demo to reproduce](https://codepen.io/571574085/pen/PoyaJxe )
> my [webglreport.com](http://webglreport.com/)  screenshot
![webglreport com__v=2](https://github.com/CesiumGS/cesium/assets/20126997/6fe36c0e-c466-41bc-8a6c-9feb29fd99a4)

**Comment by CHENJIAMIAN** [comment]
I'm also not able to reproduce the error on https://sandcastle.cesium.com/.

**Comment by easternmotors** [comment]
I am having a similar error once updating from `@cesium/engine@2.3.0` to `@cesium/engine@2.4.0` when just trying to load a Globe. I also can't reproduce my error in a Sandcastle example. Does Sandcastle use the built NPM dependency or does it reference the files using relative paths?

Note: Downgrading from `@cesium/engine@2.4.0` to `@cesium/engine@2.3.0` fixes the issue for me. I wouldn't expect this to be a breaking change with a `cesium` patch version/`@cesium/engine` minor version.

**Comment by tinco** [comment]
I had similar error upgrading to 105.1. I noticed in our yarn.lock file that we were loading both `@cesium/engine@2.3.0` and `@cesium/engine@2.4.0` at the same time and it was causing all sorts of problems.

**Comment by ggetz** [comment]
Got it, will bump the widgets version.A bit strange that this is causing a rendering error though.

**Comment by CHENJIAMIAN** [comment]
- cesium1.105.1 depends on
	- @cesium/engine@2.4.0
	- @cesium/widgets@2.2.0 depends on
		- @cesium/engine@**2.3.0**

The context of @cesium/engine@2.3.0 overlaps with the context of @cesium/engine@2.4.0, causing this strange error.

> Call stack is as follows:
 1. @cesium/engine@2.4.0/Scene 
 2. @cesium/engine@2.4.0/Context 
 3. @cesium/engine@**2.3.0**/ContextLimits 
 4. @cesium/engine@**2.3.0**/ContextLimits.maximumVertexTextureImageUnits === 0  
 5. throw new RuntimeError("Vertex texture fetch support is required to render primitives with per-instance attributes. The maximum number of vertex texture image units must be greater than zero.");

**Comment by CHENJIAMIAN** [comment]
I think I said it the other way around, It doesn't prevent us from understanding the reason, haha. 
The bolded part is "2.4".  The ones without bold are 2.3.

---
An error occurred while rendering.  Rendering has stopped.
RuntimeError: Vertex texture fetch support is required to render primitives with per-instance attributes. The maximum number of vertex texture image units must be greater than zero.
Error
    **at new RuntimeError (https://esm.sh/v120/@cesium/engine@2.4.0/es2022/engine.development.mjs:2308:11)
    at Primitive.update (https://esm.sh/v120/@cesium/engine@2.4.0/es2022/engine.development.mjs:40747:13)**
    at PrimitiveCollection.update (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:127695:19)
    at updateAndRenderPrimitives (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:190614:21)
    at executeCommandsInViewport (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:190466:3)
    at Scene4.updateAndExecuteCommands (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:190284:5)
    at render (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:190922:9)
    at tryAndCatchError (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:190936:5)
    at Scene4.render (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:190988:5)
    at CesiumWidget.render (https://esm.sh/v120/@cesium/engine@2.3.0/es2022/engine.development.mjs:192372:17)

---

**Comment by yongjias** [comment]
Had similar issue in 1.105.1 only.

**Comment by CHENJIAMIAN** [comment]
The issue has been resolved.
---

I have additional questions about 
https://cesium.com/downloads/cesiumjs/releases/1.105.2/Build/Cesium/Widgets/widgets.css which is currently showing a 404 error. 
There are also no static resources under https://cesium.com/downloads/cesiumjs/releases/1.105.2/Build/Cesium. 
such as https://cesium.com/downloads/cesiumjs/releases/1.105.2/Build/Cesium/Assets/approximateTerrainHeights.json 404

---
I am using them as a CDN.

**Comment by ggetz** [comment]
Thanks @CHENJIAMIAN. 1.105.2 was an npm only release, so we did not deploy to the CDN. The CDN version is also pre-built, so there are no dependencies to resolve.

**Comment by Southjor** [comment]
这个问题再最新版（1.106.0）还是存在！

![image](https://github.com/CesiumGS/cesium/assets/33611613/2717b5df-d03f-497d-9901-9447be515ae3)

![image](https://github.com/CesiumGS/cesium/assets/33611613/6e72c33b-fe2c-4211-8e16-c73a08782873)

但是，奇怪的是，npm 引入方式有问题，在 sandcastle 中不能复现。

[sandcastle 示例](https://sandcastle.cesium.com/#c=zVbBjts2EP0VwkWxXkCWvLtusFAco4tFDwESJGia9OILJY4tNhSpkpRtJQhQ9FYU6A/0A4oee8mlQL+mCdC/6JCSallW4qIpitowbI5m3rx5MyS9oZpsOGxBk3tEwpbcguFlHj7ztvFZ6pe3SlrKJeiz4OVSEnwl1MADWoF+zNPnoOMVFQYCEkVvfvztzS/f/vHNd2+///ntDz/9/uvrXkDcprif0zXoyhvDlVb5Y602nIG+MZVMx62Xko1j+9j73hgD9j4bX11fXJ6fB0v56vzuKBjNja0ELOqUhHzK80JpS0otxmEYWcgLQS2YKCmRtQ1TY87vLmXr/pFVSiSoyMvW4ninz9dalZLFRK8TOp5dBqT9TMNrF9/6FpQxLtcxmRW7jjlRGmlPNGW8NIcPXw0kz66C1pbNulRyqtdcxmSK78tiR6bvheHd0BU2cGL4C4jJ9ScfvzfO0kTAUFqX8uqgsJzuJlvObIYPr6cnyrKsC9pINUmUtSqPycWp8LCexElSYoAc4nfHSXJKFFmUthu8AW15SsWECr5GkJwzJuA0Rsy4cUIdFJUqoXC+GdU4MrTqorivedSdzjnjG8LZveWot8eWI5IKagw+WZVCPMGuLUeLeYT+R6FCUSfjIyxD0Mq5ZReLB7UxDMN5hMvhyKYaDGlZzn3nF/ty5jZRrOoYnEkfrJ2F9Sxoy66ObGhNFYPF3BRUokSWThIuPRPY2ZhgxfZzkLhRvuB5XbDzxC8fdpQiGsjxhOcl7m+O82ERhFDrYYn2uGSlKSL3gZqBslUBSKZedVpwMHZo7zJPBR5+eCzA1yW07DuC7l/1I3++DpOIavy+tlFPXDTof68f9WbYUFG6yq0uoV9fBnhMsl6FD7EfQR32tEB3PFPOPNQZhjcy+shE7QbVqAfhCLPpNAHpN9bf6vicL77MQLYxAaF7kQk3RElRNe3Hrbp1riYFCaT0zM0xOZWmpQ6I0n0o2BXYbm47gLi/+D9p2YHIG244co+JydTWzf6jwk2wOZJuuLOzD+us2ye3GZVr+KyV8AM628x5rXNvM6Y+ixlo62yorTcl3gvUn81/KV4D2wzeBU6SiixHD+numBoDYal3Xo5CcsO+KvFgGIJSdQYqeV5b8YZbgz1GpJLVyQ6wa/mIVcQAOCSukX2dwGS8+H/MzCHrd/TAD1HOJSacYmF42+OvS/fTWCicNbzozZUvPnauqGq+P8/rERueraDZvQPDuB877awDM9ewdH9tHLn/io67s47FPtFHXB5cqLju3Ljda/pP)

**Comment by coderzyq** [comment]
我在1.133版本上也遇到这个问题

<img width="1668" height="1047" alt="Image" src="https://github.com/user-attachments/assets/44e9040f-d8c7-4763-8844-0ae9fa7a92d8" />

代码如下
```js
const initCesium = async () => {
    Cesium.Ion.defaultAccessToken =
      "";
    const terrainProvider = await Cesium.createWorldTerrainAsync();
    viewer.value = new Cesium.Viewer(container.value!, {
      infoBox: false,
      selectionIndicator: false,
      animation: false,
      baseLayerPicker: false,
      geocoder: false,
      navigationHelpButton: false,
      fullscreenButton: false,
      homeButton: false,
      sceneModePicker: false,
      timeline: false,
      shadows: true,
      shouldAnimate: true,
      terrainProvider: terrainProvider,
    });
    viewer.value.scene.globe.depthTestAgainstTerrain = true;
    // @ts-ignore 清除版权信息
    viewer.value.cesiumWidget.creditContainer.style.display = "none";

    viewer.value!.camera.setView({
      destination: Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883, 3000),
    });

    let primitive: null;

    let positions = {
      x: -75.59777,
      y: 40.03883,
      z: 3000,
    };
    setTimeout(() => {
      initFrustum();
    }, 3000);

    function initFrustum() {
      // 初始参数
      const fov = 45;
      const aspectRatio = 1920 / 1080;
      const near = 1.0;
      const far = 2000.0;

      var position = Cesium.Cartesian3.fromDegrees(
        positions.x,
        positions.y,
        positions.z
      );
      var heading = Cesium.Math.toRadians(0);
      var pitch = Cesium.Math.toRadians(0);
      var roll = Cesium.Math.toRadians(135);

      var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
      var orientation = Cesium.Transforms.headingPitchRollQuaternion(
        position,
        hpr
      );
      const initialModelMatrix =
        Cesium.Transforms.eastNorthUpToFixedFrame(position);
      const frustum = new Cesium.PerspectiveFrustum({
        fov: Cesium.Math.toRadians(fov),
        aspectRatio: aspectRatio,
        near: near,
        far: far,
      });
      const frustumGeometry = new Cesium.FrustumGeometry({
        frustum: frustum,
        origin: Cesium.Cartesian3.ZERO, // 原点
        orientation: orientation,
        vertexFormat: Cesium.VertexFormat.POSITION_ONLY,
      });
      const instanceGeo = new Cesium.GeometryInstance({
        geometry: frustumGeometry,
        modelMatrix: initialModelMatrix,
        attributes: {
          color: Cesium.ColorGeometryInstanceAttribute.fromColor(
            new Cesium.Color(1.0, 0.0, 0.0, 0.3)
          ),
        },
        id: "frustum",
      });

      primitive = viewer.value!.scene.primitives.add(
        new Cesium.Primitive({
          geometryInstances: [instanceGeo],
          appearance: new Cesium.PerInstanceColorAppearance({
            translucent: true,
            closed: true,
            // flat: true,
          }),
          asynchronous: true,
          modelMatrix: initialModelMatrix, // 初始位置矩阵
        })
      );

      // animate();
    }
```
