### ISSUE TITLE
cesium from vscode

### ISSUE THREAD

**Issue by pyp123** [CesiumGS/cesium#11282]
Why is there no intelligent prompt for the relevant APIs in cesium in vscode? It's a bit tiring to manually complete a long string of words every time. Do you have any good suggestions

**Comment by an501920078** [comment]
Using typescript!

**Comment by pyp123** [comment]
I don't quite understand. Do you mean using TS for code writing and development? Or what kind of TS file is imported?

**Comment by an501920078** [comment]
![58EA6FE7-4062-4677-B87D-E2E80ED3CB7F](https://github.com/CesiumGS/cesium/assets/45625953/674e8293-648c-4295-858f-47fe52e2029d)
There are hints that I use typescript for development

**Comment by pyp123** [comment]
我去，大哥，我刚开始学cesium，从最基础的html引入一个cesium.js文件来进行展示，但是vscode不提示拼全，太烦了呜呜

**Comment by an501920078** [comment]
你需要一个typescript项目，配合cesium开发会很nice! typescript不光是针对cesium,而是针对所有的GIS库，各种GIS库API类型出参入参都得去翻文档，开发速度很缓慢。如果是初学没关系，后期实际项目建议使用

**Comment by pyp123** [comment]
好的，蟹蟹哥，方便留个vx给小弟吗

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
