### ISSUE TITLE
color rendering will fail when using the GroundPrimitives and geometryInstances are arrays

### ISSUE THREAD

**Issue by Waylawww** [CesiumGS/cesium#11292]
The ground color rendering will fail when using the GroundPrimitives and geometryInstances are arrays

Sandcastle example:
    viewer.scene.groundPrimitives.add(
        new Cesium.GroundPrimitive({
            geometryInstances: [],
            classificationType: Cesium.ClassificationType.TERRAIN,
        })
    );

Browser:

Operating System:

**Comment by Waylawww** [comment]
The same as GroundPrimitive Render Error #11291

**Comment by ggetz** [comment]
Thanks @Waylawww. I'm going to close your issue now to keep the discussion in one place. If you have any further input on this, please post it in https://github.com/CesiumGS/cesium/issues/11291 instead.
