### ISSUE TITLE
[webxr] How do I render cesium scene to webxr?

### ISSUE THREAD

**Issue by YHIsMyLove** [CesiumGS/cesium#11298]
I’m trying to make the scene displayed on my oculus quest 2 vr headset using WebXR API. I’ve searched the forum and the internet and the solution I got all seems outdated.
I wrote a demo using raw webgl where i call gl.clear and gl.drawArrays in the xrSession.requestAnimationFrame callback function and it works fine. But when I replace them with cesium’s render method, the headset screen only shows the clear color I set with gl.clearColor and nothing else.
Currently I only need to make the scene shown on the headset screen. What should I do to achieve this?

Here are part of my code

```js
function initVR() {
var gl = viewer.scene.context._gl;
navigator.xr.requestSession('immersive-vr').then((xrSession) => {
xrSession.requestReferenceSpace("local").then((xrReferenceSpace) => {  
    const xrWebGLLayer = new XRWebGLLayer(xrSession, gl,)
    xrSession.updateRenderState({ baseLayer: xrWebGLLayer })
    xrSession.requestAnimationFrame(animate)
    function animate() {
        xrSession.requestAnimationFrame((time, xrFrame) => {
             let poses = xrFrame.getViewerPose(xrReferenceSpace);
              // gl.clearColor(1,0,1,1)
               gl.bindFramebuffer(gl.FRAMEBUFFER, xrSession.renderState.baseLayer.framebuffer);
                // **draw call here**
                viewer.scene.render()
                 for (let xrView of poses.views) {
                        let xrViewport = xrWebGLLayer.getViewport(xrView);
                         gl.viewport(xrViewport.x, xrViewport.y, xrViewport.width, xrViewport.height);
                  }
                 animate()
             });
         }
       }).catch((err) => {
          console.log(err)
       });
       }).catch((err) => {
          console.log(err)
        });
 }
```

**Comment by ggetz** [comment]
Hi @YHIsMyLove, a feature request for WebXR support is documented in https://github.com/CesiumGS/cesium/issues/3422.

I'm going to close this issue as a duplicate, and would ask that you continue the conversation over in that issue to keep information in one place.

As an offhand suggestion, is the viewer rendering to the correct canvas that WebXR expects?

**Comment by pupitetris** [comment]
@YHIsMyLove check this pull request: #11372
