### ISSUE TITLE
Create new simple example with vue2 and vite

### ISSUE THREAD

**Issue by brunokunace** [CesiumGS/cesium#11306]
Hi everyone, im trying to create a simple example with vue2+vite and cesium 1.105.2

I use a vite plugin to copy node files to public:

//vite.config.js
```
import copy from "rollup-plugin-copy";
...

      copy({
          targets: [
              { src: "node_modules/@cesium/engine/Source/*", dest: "public/" },
              { src: "node_modules/@cesium/engine/Source/WorkersES6/*", dest: "public/Workers" },
              { src: "node_modules/@cesium/widgets/Source/*", dest: "public/Widgets" },
          ],
          hook: 'buildStart'
      })
```

and all files i need are copied to /public folder and its nice.

But when i try to initialize the script bellow, i receive these erros in console and the result a black sky with start moving

```
//Hello world example code used

      Cesium.Ion.defaultAccessToken = CESIUM_KEY

      const viewer = new Cesium.Viewer('cesiumContainer');
```

Error:
Note. /Workers/createVerticesFromHeightmap.js is working in the indicated path.

<img width="796" alt="image" src="https://github.com/CesiumGS/cesium/assets/16597320/6a58b579-341f-4ad8-aa2c-4b4218e5d702">

Result screen:
<img width="967" alt="image" src="https://github.com/CesiumGS/cesium/assets/16597320/7d44eb29-25af-4990-8f96-4c6dd7089185">

**Comment by TJKoury** [comment]
https://github.com/CesiumGS/cesium/issues/10619

I submitted for a Cesium grant to roll all this into Cesium, make some noise if this is something you want to see done.

**Comment by ggetz** [comment]
@brunokunace You'll want to use the pre-built workers in `Build/Workers/` instead of  the unbuilt `Source/WorkersES6/`.

But message received about an easy-to-follow example using vue/vite. 

CC https://github.com/CesiumGS/cesium/issues/11301

**Comment by mioxs** [comment]
https://www.npmjs.com/package/vite-plugin-cesiumjs

**Comment by ggetz** [comment]
Requested on the forum: https://community.cesium.com/t/is-there-a-good-way-to-use-cesium-with-vite/27545/2

**Comment by s3xysteak** [comment]
I found maybe a good solution to solve the problem. Here is the code [simply-cesium-vite-vue](https://github.com/s3xysteak/simply-cesium-vite-vue). Hope it helpful.
On my laptop, the bundling process only took 717ms, and the resulting "dist" folder was only 11.1 MB in size.
I have provided a detailed explanation of my approach in the readme. If there's anything I can assist you with, please feel free to ask. If you have any suggestions or improvements, I welcome them as well!

**Comment by ggetz** [comment]
Hi all, we've added https://github.com/CesiumGS/cesium-vite-example with a recommended setup for vite. It should also be straightforward to add vue to that setup.

Please leave a comment or issue in that repo if you have any feedback. Thanks!
