### ISSUE TITLE
Cesium reference docs host old versions of the documentation in certain pages.

### ISSUE THREAD

**Issue by ethanchristensen01** [CesiumGS/cesium#11303]
I was searching for "cesium docs createWorldTerrain" in a search engine and came across this: <https://cesium.com/learn/cesiumjs/ref-doc/createWorldTerrain.html> 

Trying to search for "createWorldTerrainAsync" in the search bar gives no results.
![Documentation for createWorldTerrain with "createWo" in the search bar. There are two results, but "createWorldTerrainAsync" is not one of them.](https://github.com/CesiumGS/cesium/assets/7553108/e3332a78-4867-40d0-864b-79371cfa3d24)

After a bit of sleuthing, it seems like this page specifically uses an older version of the documentation. Navigating to the [index](https://cesium.com/learn/cesiumjs/ref-doc/index.html), you can find [createWorldTerrainAsync](https://cesium.com/learn/cesiumjs/ref-doc/global.html#createWorldTerrainAsync), which navigates to the Global members page. Searching here for "createWorldTerrainAsync" does give a result.

![Documentation for createWorldTerrainAsync, which is part of a bigger page. "createWo" is in the search bar, and this time, there are four results, including createWorldTerrainAsync.](https://github.com/CesiumGS/cesium/assets/7553108/f11a21f0-f174-41c8-9310-ddf4f81c5bf7)

With this result, you can see different sections for packages/engine and packages/widgets. This makes me think there are different versions of the documentation available on different pages, which is probably a bug. There may be other pages that have this same issue.

**Comment by ethanchristensen01** [comment]
Also worth noting is that `createWorldTerrain` is not marked as deprecated in either page.

**Comment by ggetz** [comment]
Thanks for the report @ethanchristensen01! `createWorldTerrain` should indeed be marked as deprecated.
 
The older files are not explicitly cleaned up as part of our website deployment process, but are usually automatically clean up after a set amount of time. We'll take a look into this.
