### ISSUE TITLE
Cesium3DTileStyle - alpha value not respected for loaded tiles

### ISSUE THREAD

**Issue by TJPovey** [CesiumGS/cesium#11300]
**CesiumJS versions**
Issue present in CesiumJS version 1.105 & 1.105.1. (No issues in cesiumjs version 1.92) Only tested in versions: 1.105, 1.105.1, 1.92

**Expected behaviour:**

When changing the style of a Cesium3DTileset using either of the following:

```javascript
    tileset.style = new Cesium.Cesium3DTileStyle({
      color: 'rgba(255,255,255,0.5)'
    });
```
```javascript
    tileset.style = new Cesium.Cesium3DTileStyle({
      color: 'color("white", 0.5)'
    });
```

I expect that all existing / newly loaded tiles to respect the assigned alpha value. Regardless of if the style has been added before or after the initial render of a Cesium3DTileset.

**Actual behaviour**
When changing the alpha value of a Cesium3DTileset, existing tiles use the old alpha value. Newly loaded tiles use the new alpha value.

The alpha value is respected if the style has been added prior to the model being added to the scene. If the alpha value is changed after this, the issue occurs:

![Tile_Alpha_Issue](https://github.com/CesiumGS/cesium/assets/51401278/47d96800-755c-4faa-a0eb-ab45473d6770)

Sandcastle example:

By showing the tiles content volume, we can see that older tiles aren't affected by the alpha value change.

[Sandcastle](https://sandcastle.cesium.com/#c=lVNNb9swDP0rRLCDDQRK99FiyJJga7dDgQE7JOguPkSRGUeYLAYSnSAt/N8nSw7ibN1hFxvk4+Mj+WxF1jMcNB7RwRwsHuEBvW5q8RRzWTFSMX4gy1JbdMVoDC+FBWB0LmSmZ8IqxWLrqP5JzpR9IssL2+afCltYgwysDXrkS+yk9Xvp0HIYYCuNx4ixO/U6iRBAeZSaz3Lp9f7rKsFR9pHsFx+CxzL7cPPx7q5TBRg0ESVummq5o2O3T5C8p8aW2lZPZJoagwa7BiMr3UR4hRbF3ulasz6gF7Iss75bPix8JqpXdA0NlT2fDF6feLjCsoOzM60FJVntIAsnJJenQ6jgFRkUhqps/a0DwJDspj+LTOHNS2S0665TC90hC7uUtlTSc+CG6VdUVQbvG2aywd5lOO3q4kFnbzRhDJnaofqFZQ7zRW/FlVc9HEfW20F5rP3PzXtOt6UhN4W1qzYye3d7O4bL40bc5utU2KZTtYBh1n8pBm9xGz7aNGMbv8PReDSL+OKs+FnXe3IMjTOZEBPGem8ko59smrAPC+V9EgOYTYbUWakPoMv5K/8IKCO9D8i2MWapn7EYLWaTUP8XtbfwxwGdkaeubPd28T0lhRCzSQhfZzKR2Uj3R+ff)

Browser:
Tested on Chrome (Version 113.0.5672.127) & Edge (Version 113.0.1774.50)

Operating System:
Windows 10 Enterprise - version 21H2

**Comment by TJPovey** [comment]
More easily seen when showing content volumes:
![Tile_Alpha_Issue_2](https://github.com/CesiumGS/cesium/assets/51401278/0809a910-2391-4e6a-b802-c5ce1df763d5)

**Comment by TJPovey** [comment]
Ok, I've tested on all versions between 1.92 and 1.105.1, it looks like the bug was introduced in version 1.97. [These were the major changes in this version.](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#major-announcements-loudspeaker-5)
Maybe texture caching is the culprit?

**Comment by j9liu** [comment]
The culprit is this block of code:
```
/**
 * @private
 */
Model.prototype.applyColorAndShow = function (style) {
  const previousColor = this._color;
  const hasColorStyle = defined(style) && defined(style.color);
  const hasShowStyle = defined(style) && defined(style.show);

  this._color = hasColorStyle
    ? style.color.evaluateColor(undefined, this._color)
    : Color.clone(Color.WHITE, this._color);
  this._show = hasShowStyle ? style.show.evaluate(undefined) : true;

  if (isColorAlphaDirty(previousColor, this._color)) {
    this.resetDrawCommands();
  }
};
```

`previousColor` is storing `this._color`, and when `this._color` is later being changed by the style, this _also_ changes `previousColor`. The correct solution would be to use a scratch `Color` variable for `previousColor`. Then, use `Color.clone` to copy the color into `previousColor`, _before_ potentially changing it via the style.

**Comment by TJPovey** [comment]
perfect thanks @j9liu
