### ISSUE TITLE
Cesium no longer working with Webpack [Outdated Approach]

### ISSUE THREAD

**Issue by oussamabonnor1** [CesiumGS/cesium#11301]
This [blog ](https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/) was very helpful to setup what we needed from Cesium on a Nuxt/Vue project using `copy-webpack-plugin`

* Browser:
Chrome 113.0.5672.127 | 64 bit
* Operating System:
Windows 10 Version 21H2 (OS Build 19044.2965)

**Comment by TJKoury** [comment]
https://github.com/CesiumGS/cesium/issues/11306#issuecomment-1561310854

**Comment by ggetz** [comment]
Thanks @oussamabonnor1. More recently, we've been "maintaining" [`cesium-webpack-example`](https://github.com/CesiumGS/cesium-webpack-example), but it can certainly use a refresh.

**Comment by ggetz** [comment]
Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?

**Comment by oussamabonnor1** [comment]
> Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?

Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.

**Comment by bbhxwl** [comment]
> > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> 
> Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.

How should nuxt2 use cesium? I urgently need this feature.

**Comment by oussamabonnor1** [comment]
> > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > 
> > 
> > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> 
> How should nuxt2 use cesium? I urgently need this feature.

@bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files
Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).

My `package.json`'s dependencies section has these:

```json
"cesium": "1.92",
"copy-webpack-plugin": "6",
```

Good luck! 💪

**Comment by bbhxwl** [comment]
> > > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > > 
> > > 
> > > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> > 
> > 
> > How should nuxt2 use cesium? I urgently need this feature.
> 
> @bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).
> 
> My `package.json`'s dependencies section has these:
> 
> ```json
> "cesium": "1.92",
> "copy-webpack-plugin": "6",
> ```
> 
> Good luck! 💪

Is there any bug in 1.92? My project currently does not support upgrading to nuxt3, so can't I have a better experience with cesium?

**Comment by oussamabonnor1** [comment]
> > > > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > > > 
> > > > 
> > > > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> > > 
> > > 
> > > How should nuxt2 use cesium? I urgently need this feature.
> > 
> > 
> > @bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).
> > My `package.json`'s dependencies section has these:
> > ```json
> > "cesium": "1.92",
> > "copy-webpack-plugin": "6",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Good luck! 💪
> 
> Is there any bug in 1.92? My project currently does not support upgrading to nuxt3, so can't I have a better experience with cesium?

1.92 works fine! It just has less features than the newest available version. You can use it with Nuxt2.

**Comment by bbhxwl** [comment]
> > > > > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > > > > 
> > > > > 
> > > > > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> > > > 
> > > > 
> > > > How should nuxt2 use cesium? I urgently need this feature.
> > > 
> > > 
> > > @bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).
> > > My `package.json`'s dependencies section has these:
> > > ```json
> > > "cesium": "1.92",
> > > "copy-webpack-plugin": "6",
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Good luck! 💪
> > 
> > 
> > Is there any bug in 1.92? My project currently does not support upgrading to nuxt3, so can't I have a better experience with cesium?
> 
> 1.92 works fine! It just has less features than the newest available version. You can use it with Nuxt2.

What features are missing? I want to see if I need them and if there are any explanations? If using CDN references, you can use the latest version, right?

**Comment by bbhxwl** [comment]
> > > > > > > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > > > > > > 
> > > > > > > 
> > > > > > > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> > > > > > 
> > > > > > 
> > > > > > How should nuxt2 use cesium? I urgently need this feature.
> > > > > 
> > > > > 
> > > > > @bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).
> > > > > My `package.json`'s dependencies section has these:
> > > > > ```json
> > > > > "cesium": "1.92",
> > > > > "copy-webpack-plugin": "6",
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Good luck! 💪
> > > > 
> > > > 
> > > > Is there any bug in 1.92? My project currently does not support upgrading to nuxt3, so can't I have a better experience with cesium?
> > > 
> > > 
> > > 1.92 works fine! It just has less features than the newest available version. You can use it with Nuxt2.
> > 
> > 
> > What features are missing? I want to see if I need them and if there are any explanations? If using CDN references, you can use the latest version, right?
> 
> What features are missing => check the [change.log](https://github.com/CesiumGS/cesium/blob/1.110/CHANGES.md) for a complete list. Can a CDN approach work => I never tested it but it sounds like it wont since the compilation/imports will just be replaced from being fetched locally to being fetched via a request. I recommend you test it and see :)
> 
> Good luck!

So it seems like I should upgrade my project. I'll try using nuxt3, can I use the latest one?

**Comment by oussamabonnor1** [comment]
> So it seems like I should upgrade my project. I'll try using nuxt3, can I use the latest one?

With Nuxt3. Yes!

**Comment by bbhxwl** [comment]
> > So it seems like I should upgrade my project. I'll try using nuxt3, can I use the latest one?
> 
> With Nuxt3. Yes!

Do you have the correct method for loading maps with nuxt3? Ts


https://github.com/CesiumGS/cesium/issues/11586

**Comment by bbhxwl** [comment]
> Thanks @oussamabonnor1. More recently, we've been "maintaining" [`cesium-webpack-example`](https://github.com/CesiumGS/cesium-webpack-example), but it can certainly use a refresh.

Is it possible to use the latest version of cesium with nuxt2+webpack4?

**Comment by bbhxwl** [comment]
> > > > > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > > > > 
> > > > > 
> > > > > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> > > > 
> > > > 
> > > > How should nuxt2 use cesium? I urgently need this feature.
> > > 
> > > 
> > > @bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).
> > > My `package.json`'s dependencies section has these:
> > > ```json
> > > "cesium": "1.92",
> > > "copy-webpack-plugin": "6",
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Good luck! 💪
> > 
> > 
> > Is there any bug in 1.92? My project currently does not support upgrading to nuxt3, so can't I have a better experience with cesium?
> 
> 1.92 works fine! It just has less features than the newest available version. You can use it with Nuxt2.

Can we consider how to be compatible with the latest version? Because upgrading to nuxt3 is too challenging for me.

**Comment by bbhxwl** [comment]
> > > > Also, based on your title, can you provide more information on what makes this an outdated approach? Is it just that it's not working as-is, or does it go deeper?
> > > 
> > > 
> > > Sorry @ggetz , I meant it's not working as-is. Using `copy-webpack-plugin` (or a similar approach) would be great if it's still an option on the table.
> > 
> > 
> > How should nuxt2 use cesium? I urgently need this feature.
> 
> @bbhxwl Nuxt2 will only work with `Cesium 1.92` and older using this approach https://cesium.com/learn/cesiumjs-learn/cesiumjs-webpack/#manage-cesiumjs-static-files Anything newer than the 1.92 version will have to use a different approach (Nuxt3 or Webpack5 or...).
> 
> My `package.json`'s dependencies section has these:
> 
> ```json
> "cesium": "1.92",
> "copy-webpack-plugin": "6",
> ```
> 
> Good luck! 💪

![image](https://github.com/CesiumGS/cesium/assets/26525599/97e64444-68a2-443b-bd7c-8b5780834e7d)
![image](https://github.com/CesiumGS/cesium/assets/26525599/7a694af0-1f9e-4b37-b9be-4f33775b2172)
![image](https://github.com/CesiumGS/cesium/assets/26525599/a7021e3b-62b7-4831-b4a6-c918a683bdc3)

**Comment by bbhxwl** [comment]
> > So it seems like I should upgrade my project. I'll try using nuxt3, can I use the latest one?
> 
> With Nuxt3. Yes!

I have a question to consult here.


https://community.cesium.com/t/cesium-ion-1-110-webpack-problem/27351

**Comment by ggetz** [comment]
I'm going to close this as https://github.com/CesiumGS/cesium-webpack-example has been updated and is working with Webpack 5.

We are investigating wether we should provide an example of Webpack 4, specifically for use with Nuxt 2. However, given that Nuxt 2 will soon be end of life in June.

**Comment by ggetz** [comment]
Also see https://github.com/CesiumGS/cesium/issues/11306
