### ISSUE TITLE
3D MultiLineString penetrate the surface.

### ISSUE THREAD

**Issue by guy-j** [CesiumGS/cesium#11309]
I try to load geojson (type MultiLineString), Via GeoJsonDataSource.load method.

the polyline that were create has penetrated the surface, I want them to stop at surface height.
one position should be above the ground and the other on the ground.

![image](https://github.com/CesiumGS/cesium/assets/129680144/ce503ce5-150c-4984-9484-7dffca01ccd9)

I added the code below for reproduce in sandcastle:
[MultiLineString_Below_Surface.txt](https://github.com/CesiumGS/cesium/files/11557147/MultiLineString_Below_Surface.txt)

**Comment by ggetz** [comment]
Hi, maybe try the [`clampToGround` option](https://cesium.com/learn/cesiumjs/ref-doc/GeoJsonDataSource.html#.clampToGround).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
