### ISSUE TITLE
load my 3dtiles report errors but not report in version1.100 

### ISSUE THREAD

**Issue by happyfeet1996** [CesiumGS/cesium#11316]
Sandcastle example:

Browser:chrome safari

Operating System:macos ventura

<img width="1606" alt="image" src="https://github.com/CesiumGS/cesium/assets/40989006/8f669e3c-073c-4567-b5d9-7b7a60f35b16">

it reports errors in devtools,i can not find any useful info from errors.
it does not report in version 1.100, i update from 1.100 to 1.105.2,so i don't know which version start report errors

**Comment by ggetz** [comment]
Hi @happyfeet1996 Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

**Comment by happyfeet1996** [comment]
> Hi @happyfeet1996 Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

I find the problem and resolved this problem, in my angular application, i import cesium.js in angular.json before.but now,i import cesium in every component by "import * as Cesium from 'cesium'".
