### ISSUE TITLE
Terrain with multiple layers loading higher LOD tiles inconsistantly

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#11312]
As reported in [this forum thread](https://community.cesium.com/t/sampleterrainmostdetailed-returns-wrong-height-often/24147/3), terrain with multiple layers appears to load higher levels of detail inconsistently when sampling the most detailed terrain.

The user is working around the problem by ensuring the camera flies to that position and ensuring the tile is loaded before calling `sampleTerrainMostDetailed`. However, this should not be required.

[Sandcastle example](https://sandcastle.cesium.com/#c=5VRrc+I2FP0rGr5gplQIHONA2UwZku6YBmcDhOyDnY5iX2yBkFhJhkAm/70ykMVs8w9qe8Z6nPs4514pkkIbZFIlN3RDt+gDKsO2nz59jNgd6wcPu6AeskAHYuhFvaAZLFafJ71+C1vQj/jjwoICL5xzPtglm6+j+jyc35Pb8T0J55G5u47TcEuevzT6y8E8cMP5oBE+Buy21199tc7C3Y032G4YffyLBHP5HM6/uOF1lwzG0fPsHv89mrPg97ugFzyE4vHpn2R3O5hQd/N55A9J+pgp9+GS0onpDW7Kf0xFDzTLljiQAscwoxk33SgCrcdyAcLy+snRYqM96zWDDSi7JWCDjuaT/ZozLUX7eU8KQ5kANS1VX6YCHR+2pAmo7Scl1ywG1S56sAkE59vOC9UaTBC3kdvyLl4rU/FasVkc4mMDStkYb+jzfA6/8TnEKaSSKd4uhB6ClpmKAM+UXHYPYZ1602+5F41K9WSm4EcG2kxAGXgOpVpSrtvIqAyOyR1Ekhwwl4nVw1g0Ewk6ZjstVU6aa7pccTgmOZDaXINVjUPsvE+xir4VKVJlZKLoKmWRQzBpXdZ9ckH8Oql7Xp00qgT7l03f9X3ieq1L13Oble8VbFIQziwTkWFSIOeQg66ggjZFBuWVZMIg4LCmewumURn9hgbUpHjGpVRvLr6R7zgFlqSmYvfLy3LO1GqCclHWVCFDVQLG1unIDoRhhoHGNI6LpVlJzfJQ7SJTO6LC3ZfnGhIFoB0PNxsXvldFFx4mfjMfeYSQYrmAc7bSktkWekGn5X0laczYWQeewjj1Ksq/oqv8WVJbEUZPndOTXCo8HnbD0afu8CYcn/CvR9u8bY+EZ3w7ls5Bhl8K4VT2ApwpH6UQLfLeoYltgr2cCP2fWufnkcrfUrXU0WbL4eot2p9suZLK5EfZwbhmwPqyBdK1pyxagMGR1gfNEOrUiqadmK0Riz+8c1uhiNtLx+7MMs5HbAfT0lWnZvH/MeXSNpBI7tagON3msLR+dXtYxBh3anb6vqWRkj9R9YvnfwE)

**Comment by kubotron** [comment]
Just a few notes: I think i noticed wrong terrain height a few times even after flying camera to that particular place. It's happening more on a custom terrain assets, less on Cesium world terrain)

**Comment by kubotron** [comment]
I also think that I'm seeing network errors in console correlated to this. The assets where this is happening are hosted from S3 btw

**Comment by ggetz** [comment]
@kubotron I believe I've found a fix for this issue in https://github.com/CesiumGS/cesium/pull/11413. Would you be able to verify this fixes the behavior you've seen? There's a [deployed version of the code where you can test it out](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/terrain-availability-fix-2/).

**Comment by ggetz** [comment]
We believe this was fixed in https://github.com/CesiumGS/cesium/pull/11630.
