### ISSUE TITLE
How do I configure the module 'cesium/Cesium' or its corresponding type declarations in the Create React App

### ISSUE THREAD

**Issue by WaterSeeding** [CesiumGS/cesium#11321]
Yesterday, I created a program through the Create React App and added cesium library. Although it ran successfully, I met a problem:

![image](https://github.com/CesiumGS/cesium/assets/31184164/89c96f1f-db8b-4273-bbdf-e747e636d283)

![image](https://github.com/CesiumGS/cesium/assets/31184164/16124e11-eab4-40d0-83a7-1d3111261f7e)

Cannot find module 'cesium/Cesium' or its corresponding type declarations.

I have tried many ways to solve it

I am very upset about this problem, can you help me to solve it? thank you

This is the address of my warehouse：https://github.com/WaterSeeding/CesiumWorld

**Comment by ggetz** [comment]
Hi @WaterSeeding,

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

It might help to include the steps your took to set up the react app and how CesiumJS was added.

Thanks!
