### ISSUE TITLE
PostProcessStage crashes rendering when Pointcloud with attenuation is in the scene

### ISSUE THREAD

**Issue by DanRiess** [CesiumGS/cesium#11339]
Hello there,

I was trying to add a PostProcessStage to my Pointcloud project when i encountered this error:
<code>ERROR: 0:? : 'out_FragData_0' : conflicting output locations with previously defined output 'out_FragColor'</code>

I fired up a quick and dirty sandcastle to demonstrate, I can reproduce the error in there. Commenting out Line16 resolves the error, so the problem seems to lie within the the Attenuation Shading setting.
I used the same PostProcessStage as in your examples, but it also happens when the process' fragment shader is an empty function.

Is there any workaround for this behaviour?

Sandcastle example: [Click me](https://sandcastle.cesium.com/index.html#c=jVZtc+I2EP4rO5l+MC0RNraBvJBphty1N5NOMyFtP5ROIuwF1MoSI8skXCb/vSvZEHPJ9eoZDJJ2n317dkWvB5cK8IkXa4lQrvSjUEvgsNZCWcikrnKwQmKJbsXLUiwE5jDfksxPqAu0ZrsTYDOVaVVa2Ah8RANjUPgIEyxFVbDf/V4wO8r8eqKV5UKhmR114XmmACwaQzunO4W7es0WRhd/aCPzZiPodGfqpXM2UzPljHvlXg9uvMcT7zG5d2P0gsENEixcSomqCxMtq2IuOPymxAZNKewWbvVcW5GVcM3nDKYZV8olgAAuJf7NVW403BmdZVoKoCX8wi0KmAidcSMFMme9jnqXpjHwRy7sLo76K766a5Lk4vmk1WVJi095EA2SfuSiAdh9arhyxXPnynifXl8TH+C0PttrUfjH33waQZezTBcFKuvg7QqpTE8WJFXDv/4noBNrfGTcWlQVt0Ir56+psO2aJhtmH8/a6DUaK7CEhTaecqCV3LbxCv4kiqq4PIDtn7VFcItXRL9rsVzZJk07s18RmVqDamlX34K6pd2qJKmIpfswakqzMkOFbG1EISxxqGQ8z4OmPq6IL5Bxm60gIK5q06nJ6eqpJTKpl8HDB3cAUtfJaFRP4btnr/Hy4FEctw8sZrxAwxmJuj4KPGyOJbnrs3Pa7rQJN5Z+cRUHTgwgScJomCRskCRRksZR0q33+/00TCOWROFwdBJFYdpvDpL0JE36IYuHyXCUJHHstjv+UBtBxHlr9Gf0Ad0Iiv5WS9mYTsnoYBjHozAN45NhOmwsHIesPxwMwmGUxqP4ZDQaNAcD1h9F5MtomCZhGI7SnWnqeHBpmSlilOM/TSuUmFmaRoXOUcKjoNquqIjSFXI/jBaGLx3ZvY6Z6spkSMV9cMCVEsTBAko//kz/imoltbmjfqhMTSahYINZHzb3tt6daG1yl3csz9oYJJW8mvdHGy3IOT+zaia4x8t5M46zNWbQNtt911Y9ItwjFhBkn4v7XfhBp4XeWIhfPaH8jFtp4fB9a2WWc/gBgoiFcNwW6pCU98lJnLXBdWXvP1JKJ00ELpygZaxLbRO+OvsCKEuEZ/gvDG/pVcX98K8HP+S/XsYPxZpGeFPLN8l+A1FavnSlP+xlXVq6K+hWKqfuvG5pp9pi980XQkGT70OnTt91siF2Q5Py9LVW+6yRYqUyP+aCg1oaJBaog+Z2qXL16kLYeqWtjDcG6++Xzky5Mx8723fMGP786+yoe3Re2q3Ei53uj6JYa2OhMjJgrGeR2sKRrzevsn/oBsrKPQ/Pe23V81xsQOTjd673+m8DnSwqKafiM86OLs57JP9GtRmKv9LdLPnWia2ii+t6kzF23qPl+5pWaznn5gvkfwE)

Browser: Chrome 114

Operating System: Win11

**Comment by ggetz** [comment]
@jjhembd Would you be able to take a look and determine if this is a bug?

**Comment by DanRiess** [comment]
@jjhembd, thanks for the fix! It doesn't crash anymore. There is another problem now though. If you move or rotate the camera, the pointcloud flickers until the camera rests again. This only happens when shading.attenuation is true.
