### ISSUE TITLE
[UrlTemplateImageryProvider] When subdomains are placed within the port number, the imagery provider fails to load properly.

### ISSUE THREAD

**Issue by zouyaoji** [CesiumGS/cesium#11354]
Sandcastle example:

---

Browser:

---

Operating System:

UrlTemplateImageryProvider, when my subdomains are in the port number, throws an error like the following: `http://192.168.2.114:570{s}/tiles/arcgis_black/{z}/{x}/{reverseY}.png` 

 Uncaught (in promise) TypeError: Port "570{s}" is not a valid port.

![image](https://github.com/CesiumGS/cesium/assets/24430116/3cc55155-cf03-4034-9d11-e68cf3de64c0)

**Comment by IKangXu** [comment]
I think you should do this. http://192.168.2.114{s}/tiles/arcgis_black/{z}/{x}/{reverseY}.png

**Comment by ggetz** [comment]
@zouyaoji [Subdomains](https://en.wikipedia.org/wiki/Subdomain) are a different part of the URL. 


Here's an example of how they work with `UrlTemplateImageryProvider`
```
// Access the CartoDB Positron basemap, which uses an OpenStreetMap-like tiling scheme.
const positron = new Cesium.UrlTemplateImageryProvider({
    url : 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
    credit : 'Map tiles by CartoDB, under CC BY 3.0. Data by OpenStreetMap, under ODbL.'
});
```
