### ISSUE TITLE
Hello, what is the CesiumDev directory under the build folder for?

### ISSUE THREAD

**Issue by guoshengqin2023** [CesiumGS/cesium#11371]
Hello, what is the CesiumDev directory under the build folder for?

**Comment by ggetz** [comment]
Hi, this is a temporary build directory generated by running `npm start`.  The `start` task will watch for changes to code and rebuild artifacts as needed upon request. We don't want to override the other build artifacts generated by the `build` and `release` tasks, so `CesiumDev` is used.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
