### ISSUE TITLE
tileset.root.transform

### ISSUE THREAD

**Issue by guoshengqin2023** [CesiumGS/cesium#11381]
Hello, what is the difference between tileset.root.transform and tileset.modelMatrix? When I was adjusting the position of 3dtiles data, I found that a portion of 3dtiles data (converted from OSGB) can be modified by modifying the tileset. modelMatrix, while other 3dtiles data (converted from OBJ) must be modified by modifying the tileset. root. transform to adjust the position. I want to know what is the difference between tileset. root. transform and tileset. modelMatrix? Under what circumstances are they used separately? Is this a bug? This has been bothering me for a while, thank you

**Comment by IKangXu** [comment]
This is not a bug, take a look at the tileset structure and understand the role of each of them.

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.

For example there is some discussion on this topic in [this thread](https://community.cesium.com/t/is-there-is-a-way-to-rotate-the-the-3d-tile-model/5774).

Thanks!
