### ISSUE TITLE
PNTS files support Intensity, Segmentation and Classification

### ISSUE THREAD

**Issue by Madrich** [CesiumGS/cesium#11383]
Currently the PNTS format does not support PointClouds with intensity values (0->1.0), Segmentation and Classification index (both maybe an uint_32 or uint_64). This expension would not break backward compatibilty, so it can be integrated into the standard as well easily. Of cause using draco compressin too.
Would love to see that extension soon.

**Comment by ggetz** [comment]
Hi @Madrich, since this applies to the 3D Tiles standard itself, I would suggest moving this issue to https://github.com/CesiumGS/3d-tiles. Thanks!

**Comment by lilleyse** [comment]
@Madrich Per-point properties like intensity and classification are not actually part of the `pnts` format, you are free to use any of the component types listed in the [Batch Table](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/BatchTable) spec. However note that 64-bit integers are not supported.

<img width="252" alt="image" src="https://github.com/CesiumGS/cesium/assets/915398/a74f322c-8c8b-4b27-80fa-8106802cca31">
