### ISSUE TITLE
WebGL texImage2D: Conversion requires pixel reformatting

### ISSUE THREAD

**Issue by mioxs** [CesiumGS/cesium#11398]
Sandcastle example: https://sandcastle.cesium.com/?src=Offline.html

Browser: firefox 52

Operating System: window 10

baseLayer not load
![-234c59ce15f29452.png](https://github.com/CesiumGS/cesium/assets/49021590/18f24c72-cc29-49cc-90a7-ec7aacbfaefe)

Google 62

![3a1905ad3a498894.jpg](https://github.com/CesiumGS/cesium/assets/49021590/9410148c-9128-4bcd-b2a7-87f6b834b7ec)

fix ref：https://stackoverflow.com/questions/42963723/webgl-teximage2d-conversion-requires-pixel-reformatting

**Comment by ggetz** [comment]
This appears to be [an outstanding Firefox specific bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1246410), though I cannot duplicate it in Firefox with the provided example. 

Given that, I'm going to close the issue. If there's a minimal Cesium example which reproduces the error on recent Firefox versions, please let us know.
