### ISSUE TITLE
support vite

### ISSUE THREAD

**Issue by mioxs** [CesiumGS/cesium#11395]
https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Core/Resource.js
 
not use node module,and Vite doesn't support CommonJS files.
https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

**Comment by ggetz** [comment]
This is a duplicate of https://github.com/CesiumGS/cesium/issues/11306.

`https`, `http`, `zlib`, and `url` need to be marked as external when building the library from source. We also maintain https://github.com/CesiumGS/cesium-webpack-example as an example of how to configure webpack-like builds.
