### ISSUE TITLE
Picked feature doesn't move when globe is not showing

### ISSUE THREAD

**Issue by saadatali48** [CesiumGS/cesium#11396]
If we set the `globe.show = false;` then picked Feature is not being moved to a new position. 
Here is the code snippet, which I use to get the start and endpoint. when `globe.show=false`, the startPoint and endPoint returns undefined, and when globe is showing it's working perfectly fine. 

```
const endray = scene.camera.getPickRay(movement.endPosition, new Ray());
        if (!endray) return;
        const endPoint = scene.globe.pick(endray, scene, new Cartesian3());
        const startray = scene.camera.getPickRay(movement.startPosition, new Ray());
        if (!startray) return;
        const startPoint = scene.globe.pick(startray, scene, new Cartesian3());
```

**Comment by ggetz** [comment]
By design, `scene.globe.pick` will not pick a position if the globe is not rendered. 

You can use `scene.camera.pickEllipsoid` to pick a position on the WGS84 ellipsoid even if the globe is not rendered.
