### ISSUE TITLE
baseLayer not load

### ISSUE THREAD

**Issue by mioxs** [CesiumGS/cesium#11408]
Sandcastle example: https://sandcastle.cesium.com/?src=Offline.html

Browser:  Google Chrome 65

Operating System: win10

![3a1905ad3a498894.jpg](https://github.com/CesiumGS/cesium/assets/49021590/9410148c-9128-4bcd-b2a7-87f6b834b7ec)

```ts
import RollupCopy from 'rollup-plugin-copy';
import type { Plugin } from 'vite';

export default function cesiumCopy(dev?: boolean): Plugin {
  const dir = dev ? 'CesiumUnminified' : 'Cesium';
  return {
    ...RollupCopy({
      targets: [
        {
          src: `node_modules/cesium/Build/${dir}/Assets/*`,
          dest: `public/cesium/Assets/`,
        },
        {
          src: `node_modules/cesium/Build/${dir}/ThirdParty/*`,
          dest: `public/Cesium/ThirdParty/`,
        },
        {
          src: `node_modules/cesium/Build/${dir}/Widgets/*`,
          dest: `public/Cesium/Widgets/`,
        },
        {
          src: `node_modules/cesium/Build/${dir}/Workers/*`,
          dest: `public/Cesium/Workers/`,
        },
      ],
    }),
    enforce: 'pre',
    apply: 'build',
  };
}
```

set CesiumUnminified is successful, but Cesium dir should be use.
![2f41b71185d6fc50.jpg](https://github.com/CesiumGS/cesium/assets/49021590/32f934e6-57f3-4de6-aa63-cc2166e12dae)

**Comment by ggetz** [comment]
Hi @mioxs. The only difference between `Cesium` and `CesiumUnminified` workers is that some debug code removal with `rollupPluginStripPragma` and code minification with `terser`. Perhaps the minification is using language features that are not supported in Chrome 65? Are you able to reproduce in any other browsers?

**Comment by mioxs** [comment]
| brower | CesiumUnminified | Cesium |
|:--------:|:-----------:|:------------------:|
| Chrome 65  | √ |  ×  |
| Chrome 87 |  √ |  √  |
| Edge 106 |  √   |  √   |
| firebox 115|  √   |  √   |


| dir | use Workers dir  | test |
|:--------:|:-----------:|:------------------:|
|Cesium| CesiumUnminified/Workers   |   √  |
| Cesium|Cesium/Workers   |  ×  |

* Cesium/Assets -> Cesium/Assets
*  Cesium/ThirdParty -> Cesium/ThirdParty
*  Cesium/Widgets -> Cesium/Widgets
*  Cesium/Workers -> CesiumUnminified/Workers

use the CesiumUnminified/Workers directory is successful

**Comment by ggetz** [comment]
I can confirm that `terser` is using language features not supported in Chrome 65. You'll need to transpile the widgets to an older version of JS to run in the older browser versions.
