### ISSUE TITLE
How to use quadtreeprimitive with picked correctly

### ISSUE THREAD

**Issue by YHLpuyu** [CesiumGS/cesium#11421]
I use quadtreeprimitive to visual custom vector tile. For each tile, I create primitive with geometryinstances, and PerInstanceColorAppearance. In `updateforpick` function, I push all colorcommands of primitive to framestate. if the colors of all geometryinstances are same, use `scene.pick`，i can get right one, but if the colors are not same, `scene.pick` always return `undefine`, I can't pick nothing.
How can I write `updateforpick` function, so I can use 'scene.pick' to get right instance

**Comment by ggetz** [comment]
Hi @YHLpuyu!

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
