### ISSUE TITLE
Draping / projection of EPSG:3857 / WebMercator images

### ISSUE THREAD

**Issue by matthias-ccri** [CesiumGS/cesium#11428]
* Sandcastle example: [Sandcastle](https://sandcastle.cesium.com/#c=7VZRU+M2EP4rGh5qZ2rkBI47JgWulHIZZkqPIXB0hjAZxd7YOmzJJ8kJlMl/70pOHDvk6EP7eH7wSLv7rXdX364cSaENeRkJQr5wmIMK7PJK8ZwbPgO3G4DMwajnCzRlIqqE1xDhJslgpW1L3e6MKSMTxYqUR05wnmW80JLHw1JNWQSnRQFM1T4vmQHFWeY2dzC5BBUxI9WVkl/RMZeiciszqfrkDDQvc7dB8YIcLyW/jETkspq5hFAuYL7Mzh/tREuYMIwLUKOdTg3QEQhA+wpI3RaVIxGGlYHCKFBfZ0mnSua/Q6IAtL/b23sXkHc9ehiQ3Q8HuNynB2vnb2MPEbTfReAhAt931zCeJ0P+t43qvtftooV9P9RqKHSyf3jwYZnl1qL5a29ijoYrDC0qE38dk5DKpHPQxrfhdhqlgbeBWpYmBdYErqAJmFuVIdyf5xpXAcnYM6g/WQ4BuZ/z2KQBSYEnqXnokOOTio0KTKkEqSDkZ+J99PB9b1X2ufc0qBmPwAuId3c59B6CtWoGSmPeVtWjPdptKRV8KzFBqxyAuWRFS+tC06gEjD6G2+uLM5kXUoAwfh12p4mYTOSTV++drLmxj5jTp2BTqIE+bxO+tkR42/KBfpVc+F7gdVbiZkSupJgCtlNKlSxF7DtRK+yq4G2rStYy064Y3vnVcNC3R98q1lSqnLlK8pwlEBYiaekNtrYumMLiWSOjSmjptXnOwPlfih9ozgrfv38MyKziwqM9+mN79FsOZNbpLCvxk2cZt2iwrlRZDzlXkc+3zr3UmEL3wzDhE01x7pg0ZoZRwTSjiZyFyLVwRfFwghyxEholvDpe71SYVMlCJiB4NP6N49zTYzkdI/HHd1Jl8Xiv2+3t4ut9hVj27kis+wjD2vtOWBOmAdPHeGzTssyubVhMYQg6XPJdh7fDwfAGwwiRu0MUggqxAarVMtLulu+PBJ8Sv9ep2svNNuzj5ZzXlMWxX52MnSP1BeC/rI4r2bgFdN9Zbl4Oa8AaUlm+ujGapsTNR6fuu2WL8JiZgadPjm79N24R+uX8+ub8r/Gnz9eXpzcNF4tOvWksWQ2sIvy+42aobCJnMHAd0ydTlmlofCgMyRCAICXq20yTIRNxhLMxAwJPLC9sjqtT17WOVjcTjWQeftQqOq4d0NTk2fob+VJeBb2yaldzyiaKR33y0h4m5rnAb3sXtl29jUFTIkGwwvoVyBIJ7fuupzZAi9Z+8S8lX7h55Vp1RcjuD0L+IOR/IOTe/0fInWDnyF1JJyu7XzleNcpNbZ/S0ACWCrPT4aSMHsHQSGuLtaZHYRN6FPMZ4fHxlt9NEmVMa9RMyyxz43nn5ChE+1fQTLKYi+Qzkg1/PaxZ2jv5oxJSSo9C3G5HGimzCVMbnv8B)
* Browser: Chrome
* Operating System: Ubuntu

When using an Image Material Primitive that's very tall, it's draped / projected inaccurately. Note: the image is in the WebMercator projection (EPSG:3857).

This illustrates the error with a tall and narrow image. You see the great lakes are off by a significant amount.

![Selection_031](https://github.com/CesiumGS/cesium/assets/18034092/7f00d052-cb57-4281-ad1c-46d683e83f85)

I verified that the [WMS image from the server](https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?service=WMS&version=1.1.0&request=GetMap&layers=Anthropogenic_Biomes_of_the_World_2001-2006&bbox=-9796115.189808074%2C3503549.8435043753%2C-9462156.717428254%2C8399737.88981836&width=100&height=1000&srs=EPSG%3A3857&format=image%2Fpng&transparent=true&styles=) was the correct extent, by drawing the rectangle in geojson.io and overlaying the image on it in GIMP. It was a correct WMS image.

![Selection_035](https://github.com/CesiumGS/cesium/assets/18034092/6cbb1223-e79a-4d46-9198-a8ce7804f833)

In contrast, changing the rectangle to a short and skinny extent renders accurately (comment out the alternate `rect` on line 16 of the sandcastle).

![Selection_036](https://github.com/CesiumGS/cesium/assets/18034092/1c8c8f6e-49e6-4089-ac71-9c9332d0fff5)

So it looks like it inaccurately drapes images on the ground when the image is made using an Image Material in a Primitive. And the issue is apparent when the image spans a large latitude range.

Is there another way of placing an image on the globe? Note: I cannot use `Viewer` since I'm using `ol-cesium` which doesn't expose `Viewer`, only `Scene`. And I have a use case that prevents me from using tiles.

**Comment by ggetz** [comment]
Hi @matthias-ccri,

Is there a particular reason you chose to use a Primitive rather than an imagery layer with a [`WebMapServiceImageryProvider`](https://cesium.com/learn/cesiumjs/ref-doc/WebMapServiceImageryProvider.html)?

**Comment by matthias-ccri** [comment]
@ggetz yes, we're unable to use tiles because of the large amount of tiles requested (see https://github.com/CesiumGS/cesium/issues/11429), because (as it was relayed to me), our production use case will overload our geoservers, which serve live data in these WMS images.

So for one, the geoservers would be overloaded, and for two, the tiles would be out of sync since they are requested at differing times.

**Comment by ggetz** [comment]
Ah OK.

ImageMaterials were not really intended for precise mapping. Would a [`SingleTileImageryProvider`](https://sandcastle.cesium.com/?src=Imagery%20Cutout.html) work for your case?

**Comment by matthias-ccri** [comment]
Hi @ggetz,

It looks like the `SingleTileImageryProvider` has the same issue.

[Sandcastle](https://sandcastle.cesium.com/#c=fVVRT+M4EP4rUR8uqS44LSxQdQt3LIsQ0nYX0dvjoa0qNxkSL4mds52WHuK/39hJ2oT26EPqmfm+8cx4PA4FV9p5nXHH+ZvBGqRvlveSZUyzFVjpFkQGWm7uEEp5WCofIEQhTqG2trVWuqZSi1jSPGGhVdykKcuVYNGkkE80hKs8Byq3PsdUg2Q0tcIjLMcgQ6qFvJfiFzpmgpduRSrk0LkGxYrMClY9YWbjv1gKdxmNQW6QtmJRlVKl+0Y3dY6Ccb1NFN2kzS0wcnRP+QmKb85FtdnnGQ9twVa2VqjnsK4K5806YRUR15RxkLNOd0tQIXBAfEkkVkTjjAdBCZC4O9q3BSRPUmRfIZYAyjvqH3/ynU99MvCdo/NTXJ6Q053zj7kDJJ30kDhA4llvR2NZPGH/mqim/V4PEeY735ohV/HJ4PS8yvLgeXg7b3yNwJpD8hLi7WLiQupkDUp7JtxuozTwMVGJQidAm8SaGoP+KVOke+tM4cp3UnO+32kGvjNds0gnvpMAixM97zoXl2WjS9CF5E5JcX533D9c/E6NyfymrgK5YiG4vuM+jifu3N+ZViAV5m1MfdInvZZRwj8FJmiMt6DHNG9ZbWgKjYDRR/Dz4e5aZLngwLW3DbvbZCyX4sXdylbXFMyPr8mL/16pgGwOKfeRSG8j5+QX3gvP9d1urW5GZEuKKeBNTYgUBY88q2qFXRa8jSp1LZiyxXBv7ie3Q3P0rWI9CZlRW0lmLm6Q87hl1zg1VE4lFs+AtCygZVd6k4L1X6nnJKO5502ffWdV9sKzOfoLc/QHDmTV7VaV+M01HffW6LrCtlzZe57x7SZa52oYBDFbKoITTScR1ZRwqiiJxSrAVgvqDg+W2CJGQ8KYlafrXnGdSJGLGDgLF18YTlS1EE8L7PvFo5BptDju9fpH+DkrGdXVnfHmbUCf7yYfhtmce3Yu1LYrteGh9+HgtPg6ScfkXVX4ddcysr6nQ7usAG/mr2uF1ze/DtNOPcIaESlCo8jbD7zE14ml9BnGLExYTPkXobXIzMw6GpyTYzsVz47njTLkZrArRJTb5fWIL/cyo+z/Rr9nh0vJt2CbZy4UM9Zh41VoTdj98Ka9uX8g6ml/XtYkZy+QmgMcOgOrCPeeNPJw89W8Pd3PHb8zsu18WVf9T4ZtKm0jeoQEGrI8xadTBcsifAZNQqVMIgY6CprUUcRWDosuDjxVTphSpdDyVKQ2tFnnchQgfo+aChphx/zAUYhjy8CS/uW3UkkIGQUoHmZqIdIlle88/wc)

![Selection_035](https://github.com/CesiumGS/cesium/assets/18034092/5c01956b-1838-4a13-a5cf-944dade3c6c4)

The red dot is plotted at the bottom of Lake Michigan..

Maybe both ways render images in similar ways? I assume tiles are accurately rendered, so maybe tiles use different code? Any chance you can point me in the direction of that tile rendering code, because that's what I plan on looking for next.

**Comment by ggetz** [comment]
Relevant code is in [`SingleTileImageryProvider.js`](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/SingleTileImageryProvider.js), [`ImageryLayer.js`](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/ImageryLayer.js), [`/GlobeSurfaceTileProvider.js`](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/GlobeSurfaceTileProvider.js).

I would suggest checking the projection next: confirm whether the imagery services provides Geographic or Web Mercator. `WebMapServiceImageryProvider` accounts for this.

**Comment by matthias-ccri** [comment]
Ah, so the image was in WebMercator (EPSG:3857) instead of Geographic (EPSG:4326). If I change it to use 4326 then it works:

[sandcastle](https://sandcastle.cesium.com/#c=fVVtb+M2DP4rQj/MNubKSV+D9GXr3RVFgetWtLv1QxIUis3autqSJylJs6L/fZRkJ06bNR8ckXweiqQoKpVCG/I6FoT8zWEBKrbLW8UrbvgcnHQFsgKjltcIZSL1yjtIUchLaK2bWid9ZcrIXLG64KlTXJYlr7Xk2f1MPbEULuoamFr5vGEGFGelEx5gegMqZUaqWyV/omMuhXcrS6mG5CtoPquc4NT33G78Fy/humI5qCXS5jxrUmp039myzVFyYVaJopuyuwVGju6Z2EfxjZw1m52MReoKNne1Qr2ARVO4cLyTNhEJw7gANd6JVgSdggDEeyJ1IhrHIkk8QOHuaF8VkD4pWX2DXAHocLe/dxCTgz4dxGT3+BCX+/Rw7fxz7gBJ+z0kDpB41FvTeJXf839tVKN+r4cI+52crGOCWuf7g8PjJs+tJxJGHYJYILRl0dqDwnVcQipTLECb0IYcdakaPqdqOTMFsC7VE3MwP1SJ5HBRaVzFpLRn/AerICajBc9MEZMCeF6YSUTOzn2zKzAzJYinkF9J8FuA35E12d8o0KDmPIUgJsHDzX0widemOSiNmVtTn/Zpb8Oo4J8ZJmiNV2BuWL1hdaFpNAJGn8GPu+uvsqqlAGHCVdhRlzGdypdgJTtdVyAkScSCvsTvlRrocpvyIxLp75Hve6ZrndCfeHPCIA6iVt2N1xUcE8S7XFAlZyILnWojKX8cmyiv24BpV6rg8vb+aniwv3e0UconqSrm6szt1U5qkW/YDc4VXTOFpbUgo2awYddmWYLz36gntGJ1GI6eYzL3nfJsG+PMNsaW45pHUVOJXwLbjW/uOvuenLmG9J0ZWt9BYUyth0mS86mmOPNMkTHDqGCa0VzOE2zEpO3+ZIoNZDU0zbk/++BCmELJWuYgePr4hePM1Y/y6RHvxOODVGX2uNfr9Xfxc+QZzeUei6gTF/p8NxsxzO5kdJOjtV3opUjDT0erw7dJEpt3U+HXdcuo9g4P3bIBvNm/yAmvb3EbppuLlHci0pRlWfgxcI9vEyvZM9zwtOA5E1+kMbKyU213cEz33Nw82pt0ylDb0a8R4ber20fA72VH3f89DqEbPJ7vwC7PWmpurcPOu7Exgz+GN+pN4i1Rj/oTX5Oav0BpD3BIBk6Rfnj06N3lN/s6RSc78c6pa+fztuq/c2xT5RoxpDQxUNUlPq46mc7SZzA01domYqGnSZd6mvE54dnZlseMpCXTGi1Ps9KFNt45P00Q/4FaSpZhx/yJgxKHmoUV/fPvXkkpPU1Q3M40UpZTpt55/g8)

![Selection_034](https://github.com/CesiumGS/cesium/assets/18034092/4cd56918-e85b-44e0-b58b-38d40f0e198f)

I see now that `SingleTileImageryProvider` only supports 4326. From the [docs](https://cesium.com/learn/ion-sdk/ref-doc/SingleTileImageryProvider.html):

> The single image is assumed to use a [GeographicTilingScheme](https://cesium.com/learn/ion-sdk/ref-doc/GeographicTilingScheme.html).

though, perhaps this wording could be improved. I'll follow up on that separately.

Thanks for the code pointers @ggetz , I think I have a way forward! Should I close this issue, since 3857 images are not supported, so this would be a feature request instead of a bug?

**Comment by ggetz** [comment]
Awesome, glad that worked! Yes, I'll close this issue. 

https://github.com/CesiumGS/cesium/issues/3877 is where we've been tracking requests for support for additional projections. I'll add your request there. Thanks!
