### ISSUE TITLE
鼠标滚轮对地球的缩放

### ISSUE THREAD

**Issue by yang201806** [CesiumGS/cesium#11424]
107版本，鼠标滚轮滚一下，地球缩放变化非常大，edge，chrome浏览器表现不同，chrome浏览器 在本机与外接显示器上表现不同

**Comment by ggetz** [comment]
Hi @yang201806,

When you zoom in, [new data is loaded to meet the current screen space error](https://github.com/CesiumGS/cesium-ion-rest-api-examples/issues/208). This will vary based on display size and resolution. 

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
