### ISSUE TITLE
mousedown event not triggering on Cesium canvas

### ISSUE THREAD

**Issue by Jean-Dum** [CesiumGS/cesium#11425]
Hello and thank you for all the work you do on Cesium!
I want to use the mousedown event on the document body of my app.
However, this event does not fire when the click happens on Cesium canvas. It seems that Cesium uses an event.stopPropagation, is this normal?
The click event is working well, this only happens for mousedown or mouseup.

**Comment by ggetz** [comment]
Hi @Jean-Dum, thanks for your kind words!

[This thread describes the reason and rationale behind how we handle these events in CesiumJS](https://github.com/CesiumGS/cesium/issues/4768#issuecomment-278371212). If you have further thoughts, I would suggest adding them to that thread to keep everything in one place.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
