### ISSUE TITLE
Ellipse does not stick to the ground on the terrain

### ISSUE THREAD

**Issue by mioxs** [CesiumGS/cesium#11438]
Sandcastle example:
https://sandcastle.cesium.com/?src=Offline.html
```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  baseLayer: Cesium.ImageryLayer.fromProviderAsync(
    Cesium.TileMapServiceImageryProvider.fromUrl(
      Cesium.buildModuleUrl("Assets/Textures/NaturalEarthII")
    )
  ),
  baseLayerPicker: false,
  geocoder: false,
});

viewer.scene.globe.depthTestAgainstTerrain = true;
viewer.scene.logarithmicDepthBuffer = false;

viewer.entities.add({
    position: Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222, 0),
    label: {
      text: 'hello',
      eyeOffset: new Cesium.Cartesian3(0, 0, -1e6),
    },
    ellipse: {
      semiMinorAxis: 250000.0,
      semiMajorAxis: 400000.0,
      material: Cesium.Color.RED.withAlpha(0.5),
      height: 0,
      outline: true,
      outlineWidth: 12,
      outlineColor: Cesium.Color.ORANGE.withAlpha(1),
      classificationType: Cesium.ClassificationType.TERRAIN,
      heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
    },
  });

```
![image](https://github.com/CesiumGS/cesium/assets/49021590/252deb94-adc4-4c64-b48f-0b7c9c5ba6b4)

set ellipse.height undefined is successful,but outline notsupport  terrain.
Browser: Edge 115

Operating System: Win11

**Comment by ggetz** [comment]
Thanks for the report @mioxs. I believe this is a manifestation of two existing bugs:

* https://github.com/CesiumGS/cesium/issues/7065
* https://github.com/CesiumGS/cesium/issues/6694

I've added your reports and requests to the respective issues, so I'll go ahead and close this issue to keep discussions in their original threads.
