### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by attila135786** [CesiumGS/cesium#11449]
I have updated to the latest version of Cesium and I'm having issues with the globe displaying properly. After some investigation I found that making API requests to the Cesium API was failing with 401 Unauthorized. I researched many potential solutions and most of what I've seen is set the default access token or update Cesium to the latest. I'm on the latest and I'm still receiving these 401 errors. It actually started occurring yesterday.

**Comment by ggetz** [comment]
Hi @attila135786, we cycle through release tokens to prevent abuse. Ideally, you should [set the default access token to a personal access token from your Cesium ion account](https://cesium.com/learn/cesiumjs-learn/cesiumjs-quickstart/#step-1-create-an-account-and-get-a-token).

However, the most recent release should not be throwing 401 errors. Can you please let me know the steps to reproduce the error?

**Comment by attila135786** [comment]
Hello @ggetz ,  thank you for that response. I've seen that mentioned multiple times and gave up on it last night. This morning it determine that it wasn't on Cesium's side, it was on my side. We have a plugin architecture which I'm using to write a cool Cesium plugin for our application and there was actually a bug where we would transform the plugin code into the actual application code and that was broken. So after resolving that issue... Things are working as expected Thanks again for your response.

**Comment by ggetz** [comment]
Awesome, I'll go ahead and close this issue then.

@attila135786 If you'd like to share, you can let us know what you're building on the [Cesium Forum](https://community.cesium.com/). 😃

**Comment by attila135786** [comment]
@ggetz I will definitely chat with my architect about that and see what he thinks. Thank you again for getting back so quickly.
