### ISSUE TITLE
Documentation/Build Guide: Missing step to run build command

### ISSUE THREAD

**Issue by ethanchristensen01** [CesiumGS/cesium#11443]
The [Build Guide](https://github.com/CesiumGS/cesium/blob/91d84fdf623897e32d608cf0aa390c6cd2fd2de3/Documentation/Contributors/BuildGuide/README.md) should include a step to run `npm build` in the "Quickstart" and "Build the Code" sections.

If `npm build` is not run before `npm serve`, the shaders are never converted from .glsl to .js files, and the dev server crashes when it cannot find them. This seems to be documented in the [VSCode Guide](https://github.com/CesiumGS/cesium/blob/91d84fdf623897e32d608cf0aa390c6cd2fd2de3/Documentation/Contributors/VSCodeGuide/README.md#building-cesiumjs), but this note is missing from the Build Guide.

**Comment by devkthines** [comment]
I would like to tackle this ticket, From JTC.

**Comment by ggetz** [comment]
@devkthines You got it!
