### ISSUE TITLE
Stamen Map Tiles are broken

### ISSUE THREAD

**Issue by SunBlack** [CesiumGS/cesium#11451]
Stamen Map Tiles aren't working anymore - you can see it in the sandcaste:

![image](https://github.com/CesiumGS/cesium/assets/483922/e593ce50-fdc0-4d68-8028-53fb8f6d4571)

On the side of Stamen you can see the hint:

> As of July 31, 2023, Stamen Map Tiles are served by Stadia Maps. [Click here](http://maps.stamen.com/stadia-partnership/) to learn more.

**Comment by ggetz** [comment]
Thanks for the report @SunBlack! We'll evaluate whether or not we can include a default key based on the terms of use. Regardless, we'll make the necessary adjustments for the next release.
