### ISSUE TITLE
How to  scene.pick ignore Model?

### ISSUE THREAD

**Issue by gtk2k** [CesiumGS/cesium#11457]
I would like to move the model on the 3D Tile Map by dragging and dropping the mouse. I have set allowPicking to false, but scene.pickPosition() seems to get the position of the model.
Is it not possible to exclude Models with scene.pick() ?

I wrote sample code.
[sandcastle](https://sandcastle.cesium.com/#c=pVdtbxo5EP4rG76wSJyBJuSSNIkuCmlaNTSoQKuTkCKzOyy+eO2VbSDclf9+Y+8LC92kicoHhO2ZZ8aeZx6ba9BsEZNbKSMOfZpoEsKMLri5SthnWHsXXv1vuVDe1eCTh+P6+4kIpNDGWzJYgcJ1ASvvOkX55ub8SS1w42spDGUC1KTW9P6bCM+LuJzCmTejXMNEbBqIluNFLoMR46DBICxdUWZy4EABNZAmOZhLI3HMmTYsOOxlLr4FS5MiOgABJFEsZoYtQRMahv5OgDRyZh7QGBQlOG034LtMQ0B0QQ2T4ixL4poqg7+oOCQzJeMeRApA+3+0Sfv43Umne/rnu9P2URd/Hje9bod0253T06Pjbufk8Oike9zstNuNvU0nUjMbAvf7chCb0qsDeUfdiWgUlZoDDZmIBlmsr5Lz3bJ9zAyYCeZ21d/6ztgThB8UHtBIUaFnUsXbXIspTbgMKE/t5IfC5xbLoChWy+U/qQmpzBzJkI5WeMSTWpop1oIqL5YhuNwWnOMk1WsReLOFCNwZpSToWxufci5XAxY8Yt6NlFu58w5xnLU7yVtuZlcWMK2v/bDwzKvHjD8atQge6818fqH4GeZHSGtI44RDjxracvC6leL20WlknfbHJOLTbIMugsCkY8A24Hx9J2k4giezUKCzHigMYyZYvIgHeHR8yP7FHum0t4v0yS4O8YjtwnbeptSnRrGns4qazPfKWq6Mn2PgJydhszRXwZnychbshnOWaMlC8v12eHJUtqggTr7aKOzKVbRzrjc876Uudnu2ZhtLmoLiVIR8X42GePYghgkN4GaJNfiYGvk78AFF5mkLmGFYGfgkkoW5cqzzpejLhUbaLaH5HPJonQDp34+HNw/9+283v0a7g5npyZV4GfHu5sPooXf//cvrAMfJK+DGA6eT2GxM9xSNIjx6PDbHRteHRbuVNu7D0mRdxmb+wdazkfWSAmS1cMXb2C+OEp5gXZE/CL5bz3Ta0criEhBhPk7Lz2aef5BtBC8jvEBCP/NqZFnkEXOlKIUNUEBlpGgyZ8GurOazTg4KnS2g3+cIXIqImUUIW3dssjkxMlfjcgxSmJcQ8N54A0BmvfWfA4vm9hLcsUtnCyOpGJbglzdHkV6zSKuZBdgGjJ2IVCo7UG2+WN0eJzsCkoZPIVxTkpIcIVIKmTfqPqvyBigx66FqiZg5CB8F07u4zEtvW15ywIOP/PqeU72JzMhquSlkYu8iqYzkwI1al4KkHL6f/gOBqaKxo2+yw920QSrIm6I0vB8/SqCEhd7BxUX5EioIvuV4XUgzx2arZxE2WaBy/6IzZMvPqSdeRLaVCwF1AuzuyvLF6oSgUQWlt5py7R5M9nmn8GJACxB0yuGrNIhTUpPyJuRjmv8moHgf+aDUrnh4OENi0JpGkHf0s9QZJ88QJ1t4C23GyZtJg1Gy2FvCVMrp79fDFvZ3y1EixwvV8F5Xjp+TqzVr59qsOVzmzP2LxQlKhn1I+fiKMoCvKHTSrSlSHAwJtM73dN4qu56HbInPsouKfxBewKnWuDJDybdPpEnt8ryF9j+5cuneLvdLUJyurdm8c3mXThJCzls4rPY0UvIpVXvI/wM)
(Use Google Map 3D Tile. this sandcastle run requied apiKey)

**Comment by ggetz** [comment]
* [`drillPick`](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#drillPick) can let you pick multiple objects
* [`sampleHeight`](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#sampleHeight) or [`sampleHeightMostDetailed`](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#sampleHeightMostDetailed) will allow you to sample the height at a Cartographic position, excluding objects like models

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
