### ISSUE TITLE
glb error

### ISSUE THREAD

**Issue by 2548972983** [CesiumGS/cesium#11464]
![image](https://github.com/CesiumGS/cesium/assets/104083874/a75c5526-6924-4fff-90b4-e0d5e93ee8df)
fragment shader compile log: error: 0:9: 'gltf' : syntax error

**Comment by 2548972983** [comment]
Google browser will report an error, the first load can be displayed, and then refresh the error, please help to see, thank you

**Comment by ggetz** [comment]
Hi @2548972983, 

To confirm the model's validity, please run it through the [glTF-Validator](https://github.khronos.org/glTF-Validator/) tool and let us know the results.

If the glb is valid, would you be able to provide it for troubleshooting?
