### ISSUE TITLE
wrong render of cesium viewer

### ISSUE THREAD

**Issue by luca-moscatelli** [CesiumGS/cesium#11469]
**i have problem to render the viewer it seems broken help i use ts5 and react redux on nodejs HELP!!!**
![image](https://github.com/CesiumGS/cesium/assets/75081367/abadc160-487d-44ed-95f8-0bdbd2019f88)

**Comment by Makabaka-goodnight** [comment]
It seems that you haven't introduced CSS correctly

**Comment by ggetz** [comment]
Hi @luca-moscatelli, make sure you are including `Build/Cesium/Widgets/widgets.css` as described in [the Cesium Quickstart Guide](https://cesium.com/learn/cesiumjs-learn/cesiumjs-quickstart/#install-with-npm).
