### ISSUE TITLE
Cesium.Transforms.eastNorthUpToFixedFrame

### ISSUE THREAD

**Issue by guoshengqin2023** [CesiumGS/cesium#11463]
Hello, I set the origin of the ENU coordinate system to the origin of ECEF and obtained a transformation. According to theory, it should be an identity matrix, but in reality, the transformation matrix I obtained through the following code is not an identity matrix, it is a matrix rotated 90 degrees around the z-axis
const center = new Cesium.Cartesian3();
    const transform = Cesium.Transforms.eastNorthUpToFixedFrame(center);
    console.log(transform);

**Comment by ggetz** [comment]
Hi @guoshengqin2023, the 90 degree rotation is explained [here](https://gssc.esa.int/navipedia/index.php/Transformations_between_ECEF_and_ENU_coordinates).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
