### ISSUE TITLE
The Cesium3DTileset (of Cesium1.107.1) disappears when viewed by the camera at certain angles

### ISSUE THREAD

**Issue by yuzhouzhijia520** [CesiumGS/cesium#11471]
Sandcastle example:

Browser:

Operating System:

**Comment by ggetz** [comment]
Hi @yuzhouzhijia520, I'm closing this due to lack of information.

Next time, it would help us to include
* A description of the issue
* A [Sandcastle code example](https://sandcastle.cesium.com/)
* The data in question

Thanks!
