### ISSUE TITLE
`Cesium3DTileset.fromIonAssetId()` doesn't have an option for an ion token

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#11472]
I was loading some tilesets that come from two different Cesium ion accounts. I was trying to use `Cesium3DTileset.fromIonAssetId()` but there's no option for the 

It looks like it's still possible to use an `IonResource` with `Cesium3DTileset.fromUrl()` but that sort of API defeats the purpose of having `fromIonAssetId()` separate.

Somewhat related, I do find it a bit annoying that you have to do this instead of having a unified constructor like we used to. Is there a reason why we split it out this way?

```
    if (typeof this.urlOrAssetId === 'number') {
      this.tileset = await Cesium.Cesium3DTileset.fromIonAssetId(this.urlOrAssetId);
    } else {
      this.tileset = await Cesium.Cesium3DTileset.fromUrl(this.urlOrAssetId);
    }
```

**Comment by ggetz** [comment]
Thanks @ptrgags, `fromIonAssetId` was meant to be a helper function or shortcut for `IonResource` with `Cesium3DTileset.fromUrl()`. 

I think using different token for multiple tilesets is a non-typical use case, and would recommend using `IonResource` with `Cesium3DTileset.fromUrl()`:

```
  const resource = await IonResource.fromAssetId(assetId, { accessToken: token });
  return Cesium3DTileset.fromUrl(resource, options);
```

If we have a strong demand for thew ability to pass a token to `Cesium3DTileset.fromIonAssetId`, we can reconsider the API. But as mention above I don't think this is particularly common.
