### ISSUE TITLE
3dtiles with draco , 1.83 good to view, but newer version failed to view,      !!!waiting your reply!!!

### ISSUE THREAD

**Issue by geo3data** [CesiumGS/cesium#11478]
Sandcastle example:

Browser:

Operating System:

[dracoGlb.zip](https://github.com/CesiumGS/cesium/files/12390152/dracoGlb.zip)
3dtiles with draco , 1.83 good, but newer version failed to view,    
I can upload the data to ion, but failed to provide an sandcastle exapmle,  I guess ion can not process glb with draco is the reason,   
so please just download the zip file,  it contains a tileset.json and a glb.    you can easily reproduce the problem  I encountered.

**Comment by ggetz** [comment]
Hi @geo3data,

There was a major change to how we handle 3D Tiles in 1.97. Does this tileset work before or after version 1.97? 

> I can upload the data to ion, but failed to provide an sandcastle example

Cesium ion uses CesiumJS to render the examples. If there is an error loading the file, then the Sandcastle example.

**Comment by geo3data** [comment]
> Hi @geo3data,
> 
> There was a major change to how we handle 3D Tiles in 1.97. Does this tileset work before or after version 1.97?
> 
> > I can upload the data to ion, but failed to provide an sandcastle example
> 
> Cesium ion uses CesiumJS to render the examples. If there is an error loading the file, then the Sandcastle example.

1.90 Good,  1.93 crash, 1.95 crash,  with  [.WebGL-00000A6402D65400] GL_INVALID_OPERATION: Insufficient buffer size.

**Comment by ggetz** [comment]
I would suggest looking through [`CHANGES.md`](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) for the releases from 1.83 to 1.93 to identify the relevant change.

Perhaps https://github.com/CesiumGS/cesium/issues/9847?

**Comment by geo3data** [comment]
Finally, I found the problem in my code,  after draco, mesh vertex number and triangle count all changed, but I did not notice this, I thought they were not changed,  so close this issue.
