### ISSUE TITLE
3dtiles with draco , 1.83 good, but newer version failed to view

### ISSUE THREAD

**Issue by geo3data** [CesiumGS/cesium#11474]
Sandcastle example:
https://sandcastle.cesium.com/#c=jZJtb9MwEMe/yikvplRCTrN1sIluYmqmKqEPlGaDTpGQl7itF8fObKddgvbdcR4KGwLEiyiy73f/u/ufHQfGEnMNI6JokQVLwHFMlAItoBSFBCo4YKWIVhFvGeQLjhKyxgXTVw0cipRwuIDIImWwvR/HdE4D/6by3Rn1lc8/n8Yj/62f5l9vR8E5MtBjMk5rKF0dLwazcZDOl242re7oJFyUs8rX8y+Lk1XZr6bejTsz3523Gsy8mE5GQX5nxKYPi3LuTZWfsW1Sn8NVNXtYVHPvejDlfbQprkPirtOF/+0Mn6/OKBsFK+9mEvbVu/X46ZPb97bphnzclYPIeh/xWHClYUfJnkgzCSf7zhF029zZkRU355HgGlNOZGT1TF7EtSzhe8QBWglNGTFuGQ28x/TgK2p/J17YhtFaisz4eFU76yf2sXt6PHDPakXoukAqJpygXNKMarojCuEksTv5FmwrdHglRBaKl0CNOA5c5TkrQW8JdEsDpUtGgK7BZJMnqurdHvonT1piZdrvhFCzfNReN1VNnl3/4TCbkTWGJHbL9ODo6B9hZB7UfyCHB7asW+3VcK91GX421k7xalcvXW4y/6rYTPIc8WeIsY63YBMphez92qRgBDGx6e4NbmDrjTVsql7W1Aea5UJqKCSzEXI0yXKGNVHOfRGnpr9YqTpv6BxShgndAU0u/vCUIGbGZxNZF4wtaUUi63LoGP5VGhM4oXwz3xHJcGmQuo3h1r2ctAGE0NAxx7ro77laCHaP5QvdHw
Browser:

Operating System:

 hi, I have no idea what the problem is , or give some advice  how to set draco parameters when encoding ,

**Comment by ggetz** [comment]
Hi @geo3data , I'm seeing a 404 error for the top level `tileset.json`. Is this the same error you're seeing?

**Comment by geo3data** [comment]
hi,@ggetz,  I check3d the zip file uploaded to cesium ion, it did have the json, but I got the same error you got. This is the download link ,  https://api.cesium.com/v1/assets/2152418/archives/28303/download,   please try this link,

**Comment by geo3data** [comment]
> Hi @geo3data , I'm seeing a 404 error for the top level `tileset.json`. Is this the same error you're seeing?

please download the zip file, and check the data, we are waiting !!!

**Comment by geo3data** [comment]
> hi,@ggetz, I checked the zip file uploaded to cesium ion, it did have the json, but I got the same error you got. This is the download link , https://api.cesium.com/v1/assets/2152418/archives/28303/download, please try this link,

I found gltf with draco compression cannot be loaded to cesion ion,  so please download through the url https://api.cesium.com/v1/assets/2152418/archives/28303/download , and check the data, then give me some feedback about what the problem is , and we can check our code of draco compress method.

**Comment by ggetz** [comment]
I believe this is duplicate with https://github.com/CesiumGS/cesium/issues/11478. Closing this to keep discussion in one place.
