### ISSUE TITLE
git commit question about wheel event became smooth since 1.102 to 1.103 version

### ISSUE THREAD

**Issue by zxj5470** [CesiumGS/cesium#11479]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

I found that the Globe wheel event has been smoothed since version 103.
I tried to find out which commit changed it.
But find commit 3d8f53819fcf942f2bfbebaedfa65cae45365e2a with 700+ files changed!

Should we add some commit constraints, for example, the number of file changes committed at a time should not be more than 100…...

It's so hard to find diff changes. @onsummer

**Comment by onsummer** [comment]
That commit is only jsdoc type changes

**Comment by zxj5470** [comment]
'@@ -136,3 +135,0 @@ function listenToWheel(aggregator, modifier) {',
  '@@ -147,9 +143,0 @@ function listenToWheel(aggregator, modifier) {',
  '@@ -157 +144,0 @@ function listenToWheel(aggregator, modifier) {',
  '@@ -164,6 +151,8 @@ function listenToWheel(aggregator, modifier) {',
  '@@ -372 +361 @@ Object.defineProperties(CameraEventAggregator.prototype, {',
  '@@ -395 +384 @@ Object.defineProperties(CameraEventAggregator.prototype, {',
  '@@ -413 +402 @@ CameraEventAggregator.prototype.isMoving = function (type, modifier) {',
  '@@ -455 +444 @@ CameraEventAggregator.prototype.getLastMovement = function (type, modifier) {',
  '@@ -549 +538 @@ CameraEventAggregator.prototype.reset = function () {',
  '@@ -72 +71,0 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -78 +77 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -82,2 +81,2 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -85 +84 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -276 +274,0 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -278,3 +276,3 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -316,0 +315,2 @@ import WaterMaterial from "../Shaders/Materials/Water.js";',
  '@@ -588,0 +589,4 @@ function getStructAssignments(fieldNames, values, struct, type) {',
  '@@ -595,3 +598,0 @@ function getStructAssignments(fieldNames, values, struct, type) {',
  '@@ -604,4 +605,4 @@ function getStructAssignments(fieldNames, values, struct, type) {',
  '@@ -611 +612 @@ function getStructAssignments(fieldNames, values, struct, type) {',
  '@@ -2165 +2164,0 @@ function zoom3D(controller, startPosition, movement) {',
  '@@ -2191 +2190 @@ function zoom3D(controller, startPosition, movement) {',
  '@@ -2906 +2905 @@ ScreenSpaceCameraController.prototype.update = function () {'

**Comment by zxj5470** [comment]
https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/CameraEventAggregator.js#L133-L173

**Comment by ggetz** [comment]
Hi @zxj5470. Is there a problem with https://github.com/CesiumGS/cesium/commit/3d8f53819fcf942f2bfbebaedfa65cae45365e2a ?

Otherwise [`CHANGES.md`](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) is a good reference for finding relevant commits. In this case, the mouse wheel smoothing was changed in https://github.com/CesiumGS/cesium/pull/11062.

**Comment by zxj5470** [comment]
It's so weird. 

3d8f53819fcf942f2bfbebaedfa65cae45365e2a is committed at Feb 9 and
PR #11080 (Feb 19) has implemented mouse wheel smoothing.

and #11062 accepted #11080 (Feb 19) and add commits (Feb 21) and merged at (Feb 22).

So it's to blame git and JetBrains IDE 😢 

![image](https://github.com/CesiumGS/cesium/assets/20026798/65054b57-f569-42ce-873e-93d45036fb9b)
![image](https://github.com/CesiumGS/cesium/assets/20026798/f53bbdd9-232d-4d7c-aaed-20bbe742511b)

**Comment by ggetz** [comment]
Huh, probably just something with the merge order. Thanks @zxj5470.
