### ISSUE TITLE
Can't unset constrainedAxis in typescript without casting 

### ISSUE THREAD

**Issue by mbmccoy** [CesiumGS/cesium#11475]
Attempting to set `camera.constrainedAxis = undefined;` in typescript results in a compilation error. Since this is the documented approach to creating an unconstrained axis, the type of `camera.constrainedAxis` should probably be `Cartesian3 | undefined`.

Note that the workaround is fairly easy, if undesireable:

```ts
camera.constrainedAxis = undefined as any;
```

**Comment by ggetz** [comment]
Thanks @mbmccoy! Would you be able to submit the fix as a Pull Request?

See [`CONTRIBUTING.md`](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md) for how to get started.

**Comment by tspython** [comment]
I'll pick this up, I don't see any PR for it.

**Comment by javagl** [comment]
Regex-searching for 
```
@type \{.*\}
   \* @default undefined
```
brings up _many_ places (83 with a first shot) where the type is meant to be something specific, but the default value is `undefined`. I'm tempted to blindy do a bulk pass here and add that ` | undefined` everywhere, unless someone has doubts that this is the right thing to do here.

**Comment by javagl** [comment]
This can probably be closed, with the more generic question about the other places that show this pattern being tracked in https://github.com/CesiumGS/cesium/issues/11749#issuecomment-1950184016

**Comment by ggetz** [comment]
Closing in favor of https://github.com/CesiumGS/cesium/issues/11749#issuecomment-1950184016.
