### ISSUE TITLE
3d tileset could not be loaded in electron environment after cesium was packaged, but it worked perfectly when imported through cdn url

### ISSUE THREAD

**Issue by xiaobaiQJ** [CesiumGS/cesium#11487]
cesiumWorkerBootstrapper.js:30 Uncaught Error: importScripts failed for app://ThirdParty/Workers/draco_decoder_nodejs.js at app://ThirdParty/Workers/draco_decoder_nodejs.js
http://requirejs.org/docs/errors.html#importscripts
    at makeError (cesiumWorkerBootstrapper.js:30)
    at Function.req.load (cesiumWorkerBootstrapper.js:30)
    at Object.load (cesiumWorkerBootstrapper.js:30)
    at r.load (cesiumWorkerBootstrapper.js:30)
    at r.fetch (cesiumWorkerBootstrapper.js:30)
    at r.check (cesiumWorkerBootstrapper.js:30)
    at r.enable (cesiumWorkerBootstrapper.js:30)
    at Object.enable (cesiumWorkerBootstrapper.js:30)
    at r.<anonymous> (cesiumWorkerBootstrapper.js:30)
    at cesiumWorkerBootstrapper.js:30
makeError @ cesiumWorkerBootstrapper.js:30
req.load @ cesiumWorkerBootstrapper.js:30
load @ cesiumWorkerBootstrapper.js:30
load @ cesiumWorkerBootstrapper.js:30
fetch @ cesiumWorkerBootstrapper.js:30
check @ cesiumWorkerBootstrapper.js:30
enable @ cesiumWorkerBootstrapper.js:30
enable @ cesiumWorkerBootstrapper.js:30
(anonymous) @ cesiumWorkerBootstrapper.js:30
(anonymous) @ cesiumWorkerBootstrapper.js:30
each @ cesiumWorkerBootstrapper.js:30
enable @ cesiumWorkerBootstrapper.js:30
init @ cesiumWorkerBootstrapper.js:30
(anonymous) @ cesiumWorkerBootstrapper.js:30
setTimeout @ cesiumWorkerBootstrapper.js:25
req.nextTick @ cesiumWorkerBootstrapper.js:30
o @ cesiumWorkerBootstrapper.js:30
requirejs @ cesiumWorkerBootstrapper.js:30
(anonymous) @ decodeDraco.js:1

**Comment by ggetz** [comment]
Hi do you have any information on how your app was built or served? You'll likely need to host the static files, including the `ThirdParty` directory.

**Comment by xiaobaiQJ** [comment]
Thank you. I built the project with vue-cli5.0+electron, and all functions work normally after packing it into the desktop. Only part of the 3d tileset gave an error, which should be that the draco_decoder_nodejs.js path could not be found

**Comment by ggetz** [comment]
Thanks @xiaobaiQJ. You should make sure you are  somehow statically serving the `SourceThirdParty` directory along with your app. [For example, this is how we recommend serving the static files using webpack](https://github.com/CesiumGS/cesium-webpack-example/blob/main/webpack.config.js).
