### ISSUE TITLE
What units is maximumRenderTimeChange?

### ISSUE THREAD

**Issue by matthias-ccri** [CesiumGS/cesium#11481]
Is `maximumRenderTimeChange` in seconds or milliseconds? 

The [Scene docs](https://cesium.com/learn/cesiumjs/ref-doc/Scene.html) don't say. It only says:

> If requestRenderMode is true, this value defines the maximum change in simulation time allowed before a render is requested. See [Improving Performance with Explicit Rendering](https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/).

And the [Improving Performance with Explicit Rendering](https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/) page doesn't say either and only shows code examples where the value is `Infinity`.

**Comment by scscoville** [comment]
Seems to be in seconds, according to [Improving Performance with Explicit Rendering - #Handling Simulation Time Changes](https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/#handling-simulation-time-changes). "By default, when requestRenderMode is enabled, when the simulation time changes more than 0.0 seconds, a new frame will be requested".

**Comment by ggetz** [comment]
Thanks @scscoville.

Yes. In CesiumJS, unless otherwise noted, [units are SI units](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CodingGuide/README.md#units ).
