### ISSUE TITLE
Uploaded terrains blended with Cesium World Terrain do not load the custom portion

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium#11482]
In CesiumJS 1.108, loading a custom terrain from Cesium ion that has been blended with the Cesium World Terrain, only results in the Cesium World Terrain loading.  Correct behavior is observed when loading the custom terrain in CesiumJS 1.107

These terrains also correctly load with Cesium Native implementations such as Cesium for Unreal

CesiumJS 1.107 - full HD terrain
![image](https://github.com/CesiumGS/cesium/assets/123468416/0b6e6d48-f5ec-40ae-9748-d51dad541573)

CesiumJS 1.108 - no HD Terrain
![image](https://github.com/CesiumGS/cesium/assets/123468416/6c266d2f-22a2-4f27-807b-2e0bb6bd8cd0)

Sandcastle example: [Here](https://sandcastle.cesium.com/#c=hVPbcuI4EP0VFU+kiggZ+cowqWFIhjUFJiHOhay3phxbBAVZYmU5rNnKv4+MIcywWzVPcnef03364nYbDGXMFRiQnBbZ6BbESULyHCgBSlFIQAUHcZ4TlUe8xkBfcJiSRVww1d+BQ7EiHHwGUYOUo+XzMKFTOvLvtr4RUD/3+cxKBr7tr9aP94ORBzXo73S40iAfTx5m2dNrv5zfImv+MEfj8GYbXN6p+es9m1BkPYVsGXTu6dPljE0ebuh4MFo/6WST0EfBto8qe/54Q6evV51p6OMgnPwTvH7zoDtZrb6txHmYlYPg/LF/9XU8XAfp9R8zd7G5u7a3fnr7nT0u3WIeNT5FPOJKluDfiAOQCJ4r8EbJhkjdFSeb/XTg/c7XjBrJzh4IrmLKiYwarZoKgCJSat+1FG80JbIL4k1MD+OF9RP+ioELKTI91H41Zj9t1okA6Biuh5BTm2et6n0/+1Q9R5VCL++FjLUIrbSWDAlXVFGSwzhNm3tZPM5IVy9ousMDVhH0Zvdqtf4athasrGLdQzuVK9fZdLHuRxOxVPor5nin/JK8SELyvs5UNv880AA4dxzoGiaykYNM7FqeZ7aAaULTsi2rgw1sYYw93DphdFzPdJDrYUMj7JphaqdnI9szbMc2ThmG5xqOa3tux3bwnoGxaxiWgZDZMXHnlIGwh7BpeLZpGsjY13AdF2m5huti9z+qft/HgfDX2Qd3Q1O17IJjsizWA6cxO45SMCHhdNYPhlcfqITF2ToUQykKnnaBkgXZx95Pj2C/8QUrQ9E83sIB8A6SWCVL0NRrFvLseN6CEcjEy96v0e8Rb7QavVyVjFxUqC80WwupQCFZE8K2ItmaafV5+7lIVkTBJM8rXq99oPRS+gZo+vl/fo6qozzXkUXB2C3dkqhx0Wtr/C80JuKU8pfpG5EsLjWkktFbGhfjOgAh7LW1WRU95Soh2HMsf8r7Aw)

Browser: Chrome and Edge

Operating System: Windows

**Comment by ggetz** [comment]
I believe the issue here is this PR — https://github.com/CesiumGS/cesium/pull/11413. One option is to roll this change back entirely for 1.109. That would go back to the problematic behavior that was seen in https://github.com/CesiumGS/cesium/issues/11312, but would restore the previous behavior for the common case like this.
