### ISSUE TITLE
GeoJson Polygons disappear when zoom in

### ISSUE THREAD

**Issue by geozevallos** [CesiumGS/cesium#11490]
I added a service response to my scene as a GeoJsonDataSource. At glance, it shows but when i zoom in it disappear.

This is my code:

- https://codepen.io/geojorge/pen/XWodMxX

**Comment by ggetz** [comment]
Hi there,

I'm having trouble requesting the GeoJSON resource with the provided key. 

I did notice that terrain is enabled. You can either set `Cesium.GeoJsonDataSource.clampToGround = true;`, or omit the `terrain` option if not needed.

**Comment by geozevallos** [comment]
I set clampToGround = true, but it doesn't work properly.
