### ISSUE TITLE
Rendering Error with pickTranslucentDepth and Transparent Globe

### ISSUE THREAD

**Issue by 22-David** [CesiumGS/cesium#11495]
When using the pickTranslucentDepth feature alongside an active transparency setting on the globe, rendering encounters an error when the camera goes below the Earth's surface.

Steps to reproduce:
- Enable pickTranslucentDepth for picking translucent surfaces.
- Apply a transparency setting to the Cesium globe.
- Navigate the camera to a position where it goes below the Earth's surface.

I have created a sandcastle example to reproduce this error:
https://sandcastle.cesium.com/#c=jVLBbtswDP0VwqcE8GRnCza0dYMNCXYasEOKHQZfFJmJhdKUIVEJsmH/Psnphq3poToIeuR7jxSlqoKt4BhAHHgcveuiwduWqwq+OzeA5ZSQHiEYZIQYLB8mPLgY8NQjEkQWS1PQ6AG9ht5KmPDBu8idarll4zgIHC2e0MM9MJ5gjcHGQX2bYrO2MBNeOxZtGX1bzO+y8qJRUwNp94i8HbXB9VQs070jSgxkvSNcJ2CDdbxBQSPpkMrtNQW8dhuteXzwmgOlW7NscJQ+scXHTP6PeiC3QyV/yeb8VK97vWDvU7OfU+ufaOx10tVqed3UZYhqT+cHN/vZMkCHQSzrfJfbP1Nbay/ppPldth02eEiDCbM3H5aqXtyUsKzV+5vF2xIWdT0vYbKJ/smjLlv+Nb+DoiyaIGfCVc7n9dEOo/MC0dNMqUpwGEmnQtUumkcUZULIr5KpTfWvtOnsEWx3/8IzgiEdQsrsI9HW/sC2WDVV4l9JyekufbCvR/Skz5nWL1ZfLkGlVFMl+LJSnKOd9s+cfwM

**Comment by ggetz** [comment]
I believe this is the same issue as https://github.com/CesiumGS/cesium/issues/11427. There's a potential workaround described  in that thread.

I'm going to close this as a duplicate to keep discussion in one place. If you think this is a separate issue, please feel free to re-open. Thanks!
