### ISSUE TITLE
How to rotate the texture of Cesium.Material base on Primitive 

### ISSUE THREAD

**Issue by yangvictor** [CesiumGS/cesium#11504]
This is my example:
https://sandcastle.cesium.com/index.html#c=jVZtj9tEEP4rVr7UkYLjtyRNLnciOlBbqdCqVHwhqNo4E2fp2mvtbu6ank6qKp0KHGr5AgjoQfkAJ1UICSGh9MrLn4kv5V+wtpNc7Oy1Z0vW7uw8M7Mzz+zaoyEX2g6GXWDaphbCrrYNHI8C48NUpndLXjrfpqFAOATWLZU3umH2ZjiDexCC4RPaA6MPkRjeBi46vlTn4jYwJgfS9gARDilUmz85uIcCYMjgIBLP+t6ZWvJUq1r86VF8fBh/8fXs+8np05PZyyezk1/jk1/yin3pGodIYBq2VrezjZiQIxQ6xoDR4B3wGQDX8+Dksay64VpW0zJd23XtesOtaK5pmI7rOI5pu1bNbtQrCpxp5oXlghJlGGQOs8j21g0MAfVx6LcWEb+HxNAQ9JaUopDrMoSywm2EhTc8D/NWM0XJ7E1fPp5OPo//eTCdHM6eHk4nJ3Jt3RqjhLQ0s+Bnf2W+X86VUFr+61l88PN/P/05e/giPvry9NmjlQIjpkWUjH0a5sl1MxNeARqAYONiteeYq1gygnnDcUuBXS4qavjamnckIcdXAftDwfWP1sEXJ4FmVV4Ht63LNcuqOWa94SzhVl2KrXrTtS8Ab1oNq2k7Z85lTE7DuVw3m29Cy9jthgy+uYKuJ9iaYzdq7gXgb9j6OvrjcqEBCqw544zs4Pjgj/j3H04fHJ/JCQiNRkl/cMmWAiUQIXT3Jvbupi0i2AgK8TMggDgsKHVNnj0olGdXKzt4KpKp/x7Nvvo2Y2oe66+DVghXNKkrmndhobXgroyuK+avclS0gIRguDcSifM9dWk8Sihb9vp2MivG1llYSRmfquir+saNW533r7xbXnewv9rWWc0KGUZRBIglXnLpkWcOMIxIZ7msSlAw11JCi4AB6jHsacpEiHEEcuXStQD5cElB4lGIB5QFXDsnjzgBtrRuyTCq6ZhXs3DuXKc+vZOl6ZPI75aUHcJAblOo7xZbtyt2WQ2ji6NffVQ3TXVNzp3mJmVF6QrF4+PQGzIa0tGyJVb6cyPfhhHDARZ4BwrH9kKsz/s039avHj2Pf/tu+uKz6UTeM8/jxz8mF/aTh7OD49NvDl/9nb+tlz6MRW6SrtfuJfePNk6/9+VXFZu1mft1WFriBur39eW0vFGqlNpcjAlsLWy8jYOIMqGNGNElAQQEEZEs5NXeyLsLwvD4clPt6iq03cc7Gu5vKn6INI8gzuXKYETIB/g+dEtb7arUX4MSmt7xN3aAETRO1IbW1vVMaBhGuyqnaqSglPQQK1j+Hw.
In this case my texture orientation doesn't change with the direction of the polygon, how do I rotate the texture direction to match the polygon?

**Comment by ggetz** [comment]
Hi there, `rotation` isn't a valid [`ImageMaterialProperty`](https://cesium.com/learn/cesiumjs/ref-doc/ImageMaterialProperty.html?classFilter=ImageM) option. 

Could you use a model matrix to rotate the primitive instead? See the [Custom Geometry & Appearances](https://cesium.com/learn/cesiumjs-learn/cesiumjs-geometry-appearances/) tutorial for how primitives are handled as opposed to Entities.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
