### ISSUE TITLE
Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts()

### ISSUE THREAD

**Issue by aerialist7** [CesiumGS/cesium#11505]
Hi Team,

I faced with `importScripts` problem after upgrading from version 1.108 to version 1.109.
I use a CDN version of Cesium.

I prepared a simple example to reproduce the problem.
Just check the browser console.

Sandcastle example: 
 * not reproduced on Sandcastle but reproduced in the simplest example – https://aerialist7.github.io/cesium-sample/
 * source code here – https://github.com/aerialist7/cesium-sample

Browser: 
 * Chrome 116.0.5845.140 (Official Build) (arm64)

Operating System: 
 * macOS 13.5.1 (22G90)

**Comment by aerialist7** [comment]
@ggetz, hi! Could you please have a look?
It looks like it's related to this change #11400

**Comment by ggetz** [comment]
Thanks for reporting this @aerialist7. We're taking a look now. This appears to be an issue with cross-origin workers specifically - In this case between https://aerialist7.github.io/ and the CDN.

**Comment by ggetz** [comment]
@aerialist7 I have a branch,  `worker-inline`, which should resolve issues with the cross-origin workers. 

Could you try `http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/worker-inline/Build` in place of `https://cesium.com/downloads/cesiumjs/releases/1.109/Build/`?

**Comment by aerialist7** [comment]
@ggetz, there is a problem with HTTP
![image](https://github.com/CesiumGS/cesium/assets/32072831/14130711-4a33-4d25-a5b3-7b9570a31680)

Do you have an ability to deploy fixed version somewhere under HTTPS?

**Comment by protectione055** [comment]
> @aerialist7 I have a branch, `worker-inline`, which should resolve issues with the cross-origin workers.
> 
> Could you try `http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/worker-inline/Build` in place of `https://cesium.com/downloads/cesiumjs/releases/1.109/Build/`?

I encountered the same issue when running [Quickstart](https://cesium.com/learn/cesiumjs-learn/cesiumjs-interactive-building/#step-2-add-cesium-osm-buildings-and-cesium-world-terrain), and the browser console displayed these errors:
```plaintext
Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().
    at 25651789-ba2d-4340-a07b-11db1f1686b9:1:1
```
```plaintext
3e946eb2-f000-42b4-a8d5-6504ed8e6f07:1  Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().
    at 3e946eb2-f000-42b4-a8d5-6504ed8e6f07:1:1
```
```plaintext
5c8b4ffd-8ba9-4ce1-9ef2-466da5592ae5:1  Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().
    at 5c8b4ffd-8ba9-4ce1-9ef2-466da5592ae5:1:1
```
 After replacing the `src` of the `script` tag with this link, the issue was resolved.
