### ISSUE TITLE
JulianDate.toIso8601 builds a non compliant string with very small milliseconds

### ISSUE THREAD

**Issue by jfayot** [CesiumGS/cesium#11507]
```js
console.log(Cesium.JulianDate.toIso8601(Cesium.JulianDate.fromIso8601("2011-03-25T16:00:00.00000001Z"))
```
outputs:
```sh
2011-03-25T16:00:00.10000803740695119e-7Z
```
Which is not ISO8601 compliant !

In JulianDate.js, line 787, the comment says:
```js
//Forces milliseconds into a number with at least 3 digits to whatever the default toString() precision is.
```
but toString will automatically convert the milliseconds into scientific notation when lower than 1e-6.
number.toFixed is not appropriate neither, something more sophisticated needed here...

**Comment by ggetz** [comment]
Thanks for the report @jfayot! 

We'd be happy to review a fix if you or anyone else has the bandwidth to contribute!

**Comment by Alforoan** [comment]
can I take this please?

**Comment by jfayot** [comment]
> can I take this please?

Sure !

**Comment by jjhembd** [comment]
Here is a helpful [Sandcastle demonstrating the problem](https://sandcastle.cesium.com/#c=lVTva9swEP1XjrAPDmR2nY02I25YSb40jHbQsU+GRZHPsYgsBUmOyYr/90r+kbhNRjuDwTrdvXt692QqhTawZ1iiglsQWMIcNSty/3cd8+IBrddzKQxhAlU8GE5jEQtaV9IM6fbPcmHk/dPj5PoqtCBpIahhUni0UOoXy9HuD59jAdDWdOF7LduStuey4IyIBTHoW8Bm9xXK1KG416gD1JDuCQK4MwbznQEjXZM9KvuZIXSktFFMbGBN6NalEDh16kDecHvAcrm4yCxVMj/j1gYagh2c5OhzufFW85qStpqATOHTc+9IFZREgy6olVmnBV816gJUQImhGXiolFTD7rQdbh39ALKQpoceW5BeUsu6AtYkMmGVIiIhKjlKl0qVE7MaQcPjeEDCrcje6k40GyCpg8UEyoxx7KbgVHeDSJxy/+juwu8TaDpXsahqgYLgQcJOyTXHHEpmMriBhG2Y0Q7EtUwVqW1IOOyIMkfHnhQKXzv+NGNv/PX66su3cAQhfr5xnc983rdlOGwp/ezzmTR82H8QGn+I0ORdQuPhdDAaRNocOM66gX1n+U7ae1Eo7vl+4O4Lt9A6WBd0i8anWnfTjYJ+aZSwPbDk9sKvACgnWtsd6y3+xP5iPJhFgc0/K+WSJNYMj9YUnBxcWhbOfjRB3/ejwC4vVxop+ZqoN8gv), contributed by a [community member](https://community.cesium.com/t/conversion-problem-with-from-and-to-iso8601-datetime/36430).
