### ISSUE TITLE
Cesium能否读取.pbf文件，并作为底图显示在三维地球上？

### ISSUE THREAD

**Issue by Papillon-forest** [CesiumGS/cesium#11514]
https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/1/1/0.pbf
如上述由ArcGIS提供的土地利用地图url 我们能否通过CesiumJS提供的接口来拉取这个url呢？

**Comment by ggetz** [comment]
Hi @Papillon-forest, [`.pbf` vector tiles](https://docs.mapbox.com/data/tilesets/guides/vector-tiles-standards/) are currently not directly supported in CesiumJS. But there has been some [community work around vector tiles](https://github.com/CesiumGS/cesium/issues/2132#issuecomment-1079780231).

**Comment by ggetz** [comment]
Also, CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by Papillon-forest** [comment]
谢谢您的指导，我明白了。
