### ISSUE TITLE
Can you give me a list of which apis are available in 3D mode and not available in 2D mode?

### ISSUE THREAD

**Issue by CodeBoySun** [CesiumGS/cesium#11518]
Can you give me a list of which apis are available in 3D mode and not available in 2D mode? 
We were about to switch our existing project from 3D to 2D, but found that some of the apis didn't seem to work,like 'viewer.camera.computeViewRectangle()' is not useful in 2D mode. So I would like to ask if there is a list of which apis are not available in 2D mode, which is better for quick rectification projects.

**Comment by ggetz** [comment]
Hi @CodeBoySun, I don't think there is any top-level list available. Differences from 3D to 2D should be documented in the reference API where applicable.

There is a feature request to [improve the reference documentation search](https://github.com/CesiumGS/cesium/issues/3507), which I think would be applicable to this case. I'll note the use case there.

Thanks.
