### ISSUE TITLE
maybe a bug in Cesium3DTilePass.js

### ISSUE THREAD

**Issue by yipiaojun** [CesiumGS/cesium#11516]
hi,  @na9da , there maybe a bug in Cesium3DTilePass.js 

the pass option key is Cesium3DTilePass.PRELOAD,  but the assignment of pass is Cesium3DTilePass.SHADOW

as follows:

passOptions[Cesium3DTilePass.**PRELOAD**] = Object.freeze({
  pass: Cesium3DTilePass.**SHADOW**,
  isRender: false,
  requestTiles: true,
  ignoreCommands: true,
});

**Comment by jjhembd** [comment]
Thanks for catching this, @yipiaojun!
