### ISSUE TITLE
support minimum esm browser

### ISSUE THREAD

**Issue by mioxs** [CesiumGS/cesium#11513]
use Cesium 109 not support chrome 65
![image](https://github.com/CesiumGS/cesium/assets/49021590/9ce853ff-127a-4507-bd5d-c7129a76644b)
use Babel for conversion

```
 [
    '@babel/preset-env',
     {
        targets: { chrome: '61'},
     },
   ]
```

**Comment by ggetz** [comment]
Hi @mioxs, we're targeting es2020, which is more recent than Chrome 65. If you need to run on Chrome 65, I would suggest transpiling yourself with a tool such as babel. Thanks!
