### ISSUE TITLE
Cesium.Transforms headings are off by 90 degrees from North

### ISSUE THREAD

**Issue by tinco** [CesiumGS/cesium#11523]
At first I thought I was doing something wrong, and was using fixedFrameToHeadingPitchRoll incorrectly, but now I'm starting to think there's something very fundamentally wrong with the Cesium.Transforms module.

This is the code I was working on, that has headings off by 90 degrees from north towards east: https://community.cesium.com/t/is-the-fixedframetoheadingpitchroll-documentation-incorrect/26036

But as I'm working on our integration with Cesium I was looking at how the Cesium camera uses the headings and I noticed this line:

https://github.com/CesiumGS/cesium/blob/1.109/packages/engine/Source/Scene/Camera.js#L1248C1-L1249C1

That's a workaround to the same bug! The functions that work with HeadingPitchRoll objects in Cesium.Transforms simply do not produce or work with North=0, instead it's North=-90, or East=0.

At this point it's probably too late to change or fix anything in this module except for documenting the behaviour.

**Comment by ggetz** [comment]
Hi @tinco. Thanks for bringing this up.

While I don't think measuring  headings starting form north or east is more correct than the other, I agree that the documentation should reflect the correct behavior.
