### ISSUE TITLE
Cesium Asset loading issue: Failed to load resource: net :: ERR_CONNECTION_CLOSED 

### ISSUE THREAD

**Issue by jkbanwait** [CesiumGS/cesium#11528]
Cesium assets are not loading and observed below console error:

![image](https://github.com/CesiumGS/cesium/assets/107495815/b29f0ed0-abc0-4c27-98f7-97863503a7cf)

If I hover over this error and it shows the get request:
{"type":"GLTF","url":"https://assets.ion.cesium.com/us-east-1/<ASSET_ID>/model.glb","accessToken":"TOKEN","attributions":[{"html":"<span><a href=\"https://cesium.com\" target=\"_blank\"><img alt=\"Cesium ion\" src=\"https://assets.ion.cesium.com/ion-credit.png\"></a></span>","collapsible":false},{"html":"<a href=\"https://cesium.com/pricing/\" target=\"_blank\">Upgrade for commercial use.</a>","collapsible":false}]}

But if I reload the page, it works.

**Comment by ggetz** [comment]
Hi there, I don't think this is an issue with the CesiumJS library. I would suggest reporting the issue to the Cesium ion team [here](https://community.cesium.com/c/cesium-ion/9). Thanks!

**Comment by jkbanwait** [comment]
Thanks.
