### ISSUE TITLE
requestRenderMode does not render label background

### ISSUE THREAD

**Issue by lRawd** [CesiumGS/cesium#11529]
With requestRenderMode enabled, after adding a label with a background, and requesting a new render, only the label text is rendered. With the example below, right click the screen to add the label.

Sandcastle example:
[Example](https://sandcastle.cesium.com/#c=dVJdb9swDPwrhF+qAIaMvqZOsNYo1mAZBjTBngwUisQlQmTJk2in6ZD/PtlO0qYfDxZM8nhHniSdDQStxh16mIDFHRQYdFPx332OlYns48JZEtqiL5PRTWmHDh4kWuQe/zYY6BGtQv/TKYxM5Bt8xaElTRoDl84YlKSdLTbCrlFxodR9G+tzHSiSecZGMJnCv9ICfK3CuiEO3VFa2e8Q6ZR5v8RCekS7qIXEXuRhALELYilsK0LHdeTgAWlm64Zu+0kZq114HWqQk8JT1DoSSVGhF7zWcntvjK6D06rr4vHTHUd6ucvauBVyPEE7bYCoutQVuobeenB24exhdIwdSwBGrNCM4RxHmo3bjXv/08vknZDbtXeNVR/KhM80hqtqH/8CXZ0KhzPktMe4X3zIHoaxDylc97eRfuX6cl8jf5x9f1g+FfNZ8WN0k6RJHmhvcHoS+Kar2kVLG28Y5xlhVRsRh8lWjdwicRnCIAeQZ29bc6Vb0GryyUMFaUQIsfKnMWahX7BMpnkW8R9ajRNK2/WvFr0R+w62uZ7OhyTnPM9i+HknOWdWwr9j/g8)

Browser:
Firefox, Edge

Operating System:
Windows 10

**Comment by onsummer** [comment]
Also Windows 10 & Edge 116 I can see the label has been rendered:

![image](https://github.com/CesiumGS/cesium/assets/26168955/566e093e-93f4-447c-8ab7-9ba07400938a)

**Comment by ggetz** [comment]
Thanks for the report @lRawd. I opened a fix for this in https://github.com/CesiumGS/cesium/pull/11535.
