### ISSUE TITLE
Rectangle rendering issue

### ISSUE THREAD

**Issue by Wuzh994** [CesiumGS/cesium#11537]
Sandcastle example:
https://sandcastle.cesium.com/#c=bZFPT+MwEMW/ipVTkKqJ8xenhGpXZW8rIXURp1yMM7QWjl3ZTitAfPd1krasWC62xu/9xk8zwmjnyUHiES25JRqPZI1ODj08Tm9xG4mpXhvtudRo2+jqptWtFhNpsdug8FxvFQZ+bgSovfQSHfCui99bTYjmPS5JG22wI95y7dQggivwJ7iNFqPvUi/JxBEijLGd1NyjW56zXb6EZ2v6O9xaRBfPfkJYCSmtKGUsr6uMVfnirKQZ0KyoKpZWRVXSgpUXidVQ1vk1LWhRM1YX7BMqgJVpmpdpxmh+XbLsJF2d7j5ks5KrS7y1UcbC5tcdHKXf/VT7HY8plLP/I5wf8whP03ozpn8w8ZfZjZZoETXOvypcncP8kP3eWE8Gq2KAxGO/V+NokqdBvKAH4SZwtDbJv2jTyQOR3e03+yRCceeC8jwo9Ue+hV2smiT4/0OV4WEV2/sDWsVfR9suXf2eHwGgSUL5PemNUU/cfun8Fw

Browser:
Chrome Version 116.0.5845.179 (Official Build) (arm64)

Operating System:
macOS Ventura 13.2 (22D49)

Screenshots:
![image](https://github.com/CesiumGS/cesium/assets/84833907/628ca887-d008-45b9-8e84-3c1794243097)

**Comment by ggetz** [comment]
Thanks @Wuzh994 for the report. I believe this is the same shadow volume issue that came up in https://github.com/CesiumGS/cesium/issues/7065. I'm going to close this issue and add this report to that thread in order to keep everything in one place.
