### ISSUE TITLE
terrain generated by ctb can not display?

### ISSUE THREAD

**Issue by Brilliant-orange** [CesiumGS/cesium#11548]
There was a problem loading the terrain in cesium. The cesium globe displays normally after removing the terrain.
In cesium1.96, chrome displays the following error:
Cesium.js:85 An error occurred in "Py": Failed to obtain terrain tile X: 0 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 8894653434"
Cesium.js:85 An error occurred in "Py": Failed to obtain terrain tile X: 1 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 2017542741"

cesium code like this:
	var terrainProvider1=new Cesium.CesiumTerrainProvider({
		url:"http://localhost:9000/"
	});
    const viewer = new Cesium.Viewer("cesiumContainer", {
      baseLayerPicker: false, 
      imageryProvider: imageryProvider,
      terrainProvider:terrainProvider1
      });
    viewer.scene.globe.enableLighting=true;

The terrain folder contains layer.json but not meta.json,I can't find the reason for the error
However, in the latest cesium, chrome does not output any errors and just does not display the globe.
How can I solve this problem?

**Comment by twpayne** [comment]
Please do not spam people with mentions.

**Comment by ggetz** [comment]
Hi there,

The `CesiumTerrainProvider` API has changed. You'll need to create it with 

```js
try {
  const viewer = new Cesium.Viewer("cesiumContainer", {
    terrainProvider: await Cesium.CesiumTerrainProvider.fromUrl("http://localhost:9000/")
  });
} catch (error) {
  console.log(error);
}
```

Beyond that, this sounds like a data or server configuration issue that will be difficult to troubleshoot without access to the terrain provider. I would suggest taking any further questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by canbaoSama** [comment]
I want to import the local terrain file, but I still report this error:
 An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 1 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 10110061989"
An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 0 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 12780853914"

My code is as follows:
const terrainProvider = await CesiumTerrainProvider.fromUrl('src/assets/terrain', { requestWaterMask: true, requestVertexNormals: true })
