### ISSUE TITLE
Sample code needs to be updated

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11557]
Sandcastle example: https://sandcastle.cesium.com/index.html#c=dVJdb9swDPwrRF7iAKmc9NH5QIegw4oFWIFk3YuBQZboWJgiCRLtJB363yfbMbBmq590JI93pJmm8D0gCK2cU+YATnODAchCQI2CVIP6ApWSCI57CmBLoArhoG2BEGpfcoEsN7lpuIdG4Qk9rMDgCTYYVH1kL10sGYsObqwhrgz68RR+5wbiR+h9DD1720QZnw1E4ZET/rBey31fkkxy8zZZDGoVN1Lfyu0iDc3ORVuPDRr60hclvTUmeKSGtseVzQLSk3E1fYrDWpOUtekekGBLn/QuWzmnxC+UzzaoLr+6TsuCQIOszQ65nsrcFbZqAKqE5OpRYhlXIJP3HSeTYSPCmmA1Mm0PtzVdq7e4hulHA+8vDtn28fP+52b7tPnaMkbT0TLQReO67/+gjs56gtrrhLGU8Bh/O2FIizqKEROh29AyHUhLqRpQcpWPJB5tPoIusRq/3ikj8ZzB/Ww2W8AwcAa8iAPUhAuoUB0qyuazmTsv4KQkVdl9D3yXgXkHCktkjxl0gPBMd8JqG6/hVCnC8XqZRg/vrNwcVHQlNA8hZspa6516xXz0H5q2XMZL/9ag1/zSllTz9bYPMsaWaYT/sshaXXD/V8c/

Browser: all

Operating System: all

https://sandcastle.cesium.com/index.html#c=dVJdb9swDPwrRF7iAKmc9NH5QIegw4oFWIFk3YuBQZboWJgiCRLtJB363yfbMbBmq590JI93pJmm8D0gCK2cU+YATnODAchCQI2CVIP6ApWSCI57CmBLoArhoG2BEGpfcoEsN7lpuIdG4Qk9rMDgCTYYVH1kL10sGYsObqwhrgz68RR+5wbiR+h9DD1720QZnw1E4ZET/rBey31fkkxy8zZZDGoVN1Lfyu0iDc3ORVuPDRr60hclvTUmeKSGtseVzQLSk3E1fYrDWpOUtekekGBLn/QuWzmnxC+UzzaoLr+6TsuCQIOszQ65nsrcFbZqAKqE5OpRYhlXIJP3HSeTYSPCmmA1Mm0PtzVdq7e4hulHA+8vDtn28fP+52b7tPnaMkbT0TLQReO67/+gjs56gtrrhLGU8Bh/O2FIizqKEROh29AyHUhLqRpQcpWPJB5tPoIusRq/3ikj8ZzB/Ww2W8AwcAa8iAPUhAuoUB0qyuazmTsv4KQkVdl9D3yXgXkHCktkjxl0gPBMd8JqG6/hVCnC8XqZRg/vrNwcVHQlNA8hZspa6516xXz0H5q2XMZL/9ag1/zSllTz9bYPMsaWaYT/sshaXXD/V8c/

Sample code needs to be updated

**Comment by jjhembd** [comment]
Thanks for the report, @danchaotaiyang!

Where are you finding this sample code? I can see some problematic examples on this page:
https://cesium.com/platform/cesium-ion/content/cesium-world-terrain/
But let us know if there are other places that need to be fixed.

**Comment by danchaotaiyang** [comment]
> Thanks for the report, @danchaotaiyang!
> 
> Where are you finding this sample code? I can see some problematic examples on this page: https://cesium.com/platform/cesium-ion/content/cesium-world-terrain/ But let us know if there are other places that need to be fixed.

https://cesium.com/learn/cesiumjs-learn/cesiumjs-camera/
The second and fourth "OPEN IN SANDCASTLE"
