### ISSUE TITLE
debugShowBoundingVolume doesn't work with the splitter

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#11555]
When using the splitter for a side-by-side comparison, if you turn on `tileset.debugShowBoundingVolume` for a tileset on one side of the splitter, the bounding volumes appear on _both_ sides of the splitter. Ideally they should only render where the tileset is rendered. See this screenshot:

![image](https://github.com/CesiumGS/cesium/assets/8422414/808968aa-c6ae-47be-bffe-7f8caddb0ff1)

Sandcastle example: [Modified 3D Tiles Compare](https://sandcastle.cesium.com/#c=tVVtT+M4EP4rc91dKdyB0xW6020o6Ar0DiSWom2X/VIJUmfSWOvYke20lKr//ew4SVtgObTSpVITj2eeeebFYyqFNjBnuEAFxyBwAWeoWZmT20oWTDq0Wp9JYWImUE06e0cTMRFGLWE1EQC0guCYGgsQL2JmGgj/OjwfM44aDUmVzC+l6Gu7uEyCPz4d/tndh1WC03I2yuTiVJYiYWJ2K3mZYwRGlbgG5w5qikRTFEgKxXJm2Bw1iZMkcL69lvsiuuDMnDOF1DApLKmazmhHTq4Gf4+rSFrwRynzsWzhNsEpNsueRUcVxgaHOj8tGXe0dV8vBQ08kzB8jXEF2ChWi7ey/nL5z4WjvQYaG5pBgEpJtbcpheRIuJwF9wO3AVzGjhsYX4MI3q8qi/W9c792UYYhjCxxMBlCITWr/Mu0WmvOEtsZC2Yyv3ZsWq2J8PmptY4hkdRWThgyQzPg6D5Pl7bUk45X8c2zk5kK8aZxe+zC8LpEpqllfOUaK2xkRawsZg1da3xjicmqenk2WSwS/rSdR7ZcKEZFTHEwt7YXXinwuL7cHA3kco596ipl7dOYa6y20lL4urj9wP05AnXaWQrBLxvDWgqg0JRKVFVe77QT8tgpDiv61k+DR1AkTSrIw9HG4oUkAQTP8/TbE+w9CL3uG9LXKmmzdD3kD/T9+9XHbpd04dddEusP98/P5ROauxZNu9XlIW4IiKI0/SqxQZvhoM7fTiXcKHAA+z+q53hZYHWk786H365dPf9HPzeX12cXd6Nx/8vYd84PfDno15E+D7+OBnefh7eDVyj/N4wn1MD8ZOxNt78lyV9vfjrFb3TjQxpcnztHnf1Or2rLE9/OAH+xvJDKQKl4QEhoMC9s46MOpyX9bu8aqnUzw93zrh5Rq0YA7RCLIJ7aqVkaPNpsuu6P4Pfuhy2ZkUUE3eJhSzSN6feZctfWAZVcqgjeJYfut6WzcOfLYu0YZuiGfgT2bG27eDxgIsGHCD7Zp5Wvn8URZTajO9HQUmnnHxcHymb1Ebet3asXbiewl7A5sOT4hesdKI+1tjtpyfnIIk06bdY3Zs08P+mFVtagbn+3qvUVNLSMebx0JtnHkysvJIT0Qrt82dJIyafxUy//Ag)

Browser: Chrome 117.0.5938.92 (Official Build) (64-bit)

Operating System: Ubuntu 22.04.3 LTS

**Comment by ggetz** [comment]
Hi @ptrgags. The bounding boxes should also represent the requested tiles. I believe these hidden tiles are still being requested, so this result is expected.

Additionally, debugBoundingVolume is a debugging tool that is not meant to be used in production.
