### ISSUE TITLE
About building locally

### ISSUE THREAD

**Issue by verybigzhouhai** [CesiumGS/cesium#11559]
Hi，
    When I add a class in the engine folder, how to reference it in widgets? For example, when I add a Cesium3DFilesetBak class (rename it after copying the Cesium3DFileset class), the buildWidgets process will report an error when I execute the npm run release command. The reference here seems to come from node_ Modules, the class I added cannot be recognized.
    What should be done correctly when adding a class and referencing it in Widgets?
![image](https://github.com/CesiumGS/cesium/assets/37999729/7f01e14c-1408-4eba-8d43-3bfb197a3b1d)

**Comment by airchik** [comment]
@verybigzhouhai hi，i meet the same question, and i want to know if you can fix it, please tell me the reason, thanks~

**Comment by verybigzhouhai** [comment]
@ggetz Can you spare some time to take a look at this question? Thank you！

**Comment by ggetz** [comment]
Hi there, you'll need to build `engine` first in order to generate the top-level exports.

**Comment by verybigzhouhai** [comment]
@ggetz Thank you for your reply, but I didn't understand what you meant.
     When executing the npm run release, the buildEngine command should be executed first, followed by buildWidgets. 
    However, in Widgets/.../Viewer.js, import {xxx} from "@ cesium/engine" directly introduces the dependency module from @ cesium/engine, which means it accesses "node_ Tmodules" folder, but the classes I added myself only exist in the package folder?
    Should I be on Widgets Modify 'import {xxx} from "@ cesium/engine" ' to ' import {xxx} from "../../../engine/index.js" ' in Viewer.js. However, this should not be the correct way, although it can smoothly proceed with buildWidgets.
    The use of cesium js is very extensive, so adding classes to the engine should be common, but these modifications are usually not synchronized to @ cesium/engine. So can you provide a detailed explanation of how best practices are implemented? 
Thank you very much again！

**Comment by verybigzhouhai** [comment]
@ggetz I'm very sorry, but I still need your help

**Comment by ggetz** [comment]
> When executing the npm run release, the buildEngine command should be executed first, followed by buildWidgets. However, in Widgets/.../Viewer.js, import {xxx} from "@ cesium/engine" directly introduces the dependency module from @ cesium/engine, which means it accesses "node_ Tmodules" folder, but the classes I added myself only exist in the package folder?

Ah, so you are running a build command after installing cesium as a node module and adding a new class?

I would not recommend this approach. Generally, it is not recommended to manually add or change code in the `node_module` directly. And secondly, cesium build commands are designed to be run from a cesium developer context, not from within the context of the installed node module. 

Instead, any new code should be added to your project directly. Could you tell us a bit more about the code you're looking to add? We may have some recommendations on how to architect your solution.

Finally, CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
