### ISSUE TITLE
wording errors in the document

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11554]
Sandcastle example: https://cesium.com/learn/cesiumjs-learn/cesiumjs-imagery/

Browser: All

Operating System: All

https://cesium.com/learn/cesiumjs-learn/cesiumjs-imagery/

在 "更多图像提供商" 中搜索:
错误的单词: "TileCoordiantesImageryProvider" 改成 "TileCoordinatesImageryProvider"

Search in "More Imagery Providers"
Wrong word: "TileCoordinatesImageryProvider" changed to "TileCoordinatesImageryProvider"

**Comment by jjhembd** [comment]
Thanks for the report, @danchaotaiyang!

**Comment by jjhembd** [comment]
The document has been corrected. Thanks @danchaotaiyang!
Let us know if you find other errors.

**Comment by danchaotaiyang** [comment]
> The document has been corrected. Thanks @danchaotaiyang! Let us know if you find other errors.

Yes, I will
