### ISSUE TITLE
Billboard jitters when modifying imageSubRegion

### ISSUE THREAD

**Issue by syzdev** [CesiumGS/cesium#11569]
I want to use `CallbackProperty` to modify `imageSubRegion` to implement dynamic `BIllboard`, but I find that when the width and height of `billboard.image` are large enough, `BIllboard` will jitter after modifying `imageSubRegion`. And the larger the width and height of `BIllboard.image`, the more violent the jitter.

I implemented a simple case to reproduce this problem, in this case I repeatedly drew a 128*128 image on the Canvas, and then used the `CallbackProperty` to modify the `imageSubRegion` to get a `BoundingRectangle` at different positions.

In the picture below, the width and height of Canvas are 6400. The picture has been drawn for a total of 2500 times, and you can see that the jitter is very obvious.
![GIF](https://github.com/CesiumGS/cesium/assets/25605081/6bb353e9-1c83-4630-8e35-fe0df98b02a4)

In the picture below, the width and height of Canvas are 512. The picture has been drawn for a total of 16 times, and you can see that it is very calm.
![GIF2](https://github.com/CesiumGS/cesium/assets/25605081/7b31db66-cece-43f3-992a-7413c7201327)

You can modify `NumberOfRepeats` in the sample code to see different situations. Jitter starts when `NumberOfRepeats >= 5` in my computer.

Sandcastle example: [Cesium Sandcastle](https://sandcastle.cesium.com/#c=lVZtb9s2EP4rBwOFpVShnWQDusQOljot0GFth3TYvvgLLZ0tojSpkVScbPB/35GSY70l2Qx/4Mvdc8e75+6UamUd3AvcoYE5KNzBAq0ot+yPcBaN07BdaOW4UGjGCfyzVND42ZxnemcvwZkSk+6dLmV2o8SWOxyUcGKLkoCry+PdPr5aquN2MoHfcwRVblfkqF5DIVJXGrTgcu7Ib8zAaVghZIbvFKy1AeRpDkbvgKsMUi3LrQKhSAFhwdU9t0d4iQ6+BOyv6zsskDtL0fhx2vXhT5G5PODlKDa58554vNqbNiA9eoPfxN9IUGfn77pYn5Rwgku6t8Brj4D+74WUK81NxgJAGzOtxOaQ6bTconIsNeQtfpDod5SuIDD20WvpUf7wwZ3fkmolwjboFtVpND7PxoPxptwW6B9Zuye8q/avkjffWuPtQmzmjWefdGN61VOqw/iaVkOPCKslMqk3UdNw0kaMmzpPyagZ/smvo2aIwi2zJiWJMWOTsLeTXS4cfvMxsKxQm3HLk0pHK6l5RmpRDPPrbm1QGG+Jj02O+BQTKW2Dlbat5LkbeZ89d+cwvQqLWS8s/vjt27hrswVBBioIvxiAoONnIA6BeyB9b//kmKKr56UfPb/IVFt6WP6Jk8zXbJWUoJXAQwKPyRGisYwHjO/bR/uuQcrCTZYdC8t3Cp8Rm6JCFoh+vMuELSR/BMMVEUbYHpTYFlWxUcsprVCbgFU5WK7ucCO0goIbvkWHhg3otyW1lDZAvNelygjvDlNHxiUeu1inE9RI0Y101GA3OTm9XqMhnwZAdvQ0oGKvnkxe1bUQwq9c3PHwnhtYe+fvqK1QNi+mV30BLHTqa72eFb+UUnB1SwpM6V0UD2iomnkfPbRvYN12+3LZB5gwkRj5TI2TKpJnWTRA3EJbutfq8uDdghtHK64u2Nro7S1uDKKNTt/9wKYJXPzEpnHSh1kdGHH5XHWEMF7WfSd5QeYp2ZfNAbvgZICn338zukDjHqPIz8IEaKiV0g11k+avkmqP7F7uo/jZ4jvkxSLxILMfJC8s+j72mbuc8ZWN+rmtZW9rsqVYexzYEL9uK9DqYGIttTZRx/zJkXoxvOmQ5kX8Kh7Md6uosvOmS6j4P/SwBpRvZVGXpadN5ys7k76dUzj7n8Z6w/N1lf7ofCVANH1UrfwM+j4JX2Hx6y22WeL7lt1RMppZ9yjx+nD2M3VMbRyURkY0Wx1SA6UE28mqTL8jfcFYe4CbTZqqs0zcg8jmy1HnI3Q5glRya+lmXUrp374cXc8mJN9T9eOZauLrPRpq614sP7v+tTpkjM0mtB3WdFpTgZoO8r8)

Browser: Latest versions of Chrome

Operating System: Window 11

**Comment by syzdev** [comment]
@ggetz Thank you for your attention!

I want to add dynamic images to the scene (such as .gif), and there are currently two implementation methods that I can think of:
1. `HTML Overlays`: However, this method places dynamic images outside the scene and cannot interact with the scene.
2. `Billboard`: The inspiration for all of this comes from [#2319](https://github.com/CesiumGS/cesium/issues/2319). Although this discussion has been going on for a long time, the implementation method is still feasible, but the problem described above may occur when the Canvas size is too large.

In the example provided by @mramato, due to the smaller image size and fewer frames, the Canvas size ultimately handed over to `Billboard` was not large, so this issue did not occur.

**Comment by ggetz** [comment]
Got it, thanks @syzdev!

I think is likely something we'd address as part of support for #2319. I would suggest moving this discussion there. 

We're also happy to take intermediate PRs if you have the bandwidth to contribute. 😄

**Comment by syzdev** [comment]
Note: This may be a precision loss issue due to compression of texture coordinates.
