### ISSUE TITLE
The point labels and lines added by entities after executing viewer. scene. primitives. removeAll() are not displayed

### ISSUE THREAD

**Issue by freefer** [CesiumGS/cesium#11568]
My code scenario involves adding multiple clouds through primitives, and adding entities with labels, models, and points through entities. In some cases, I need to delete all objects and add them again, but I found that if I execute the viewer.scene.primitives.RemoveAll(), the objects managed by entities, such as points and labels, will also be deleted and will not display properly when adding entities again. Comment viewer.scene.primitives The code displays normally after removeAll().
test 
Test  Code

const viewer = new Cesium.Viewer("cesiumContainer", {
  shouldAnimate: true,
  terrain: Cesium.Terrain.fromWorldTerrain(),
});
const scene = viewer.scene;
 
viewer.scene.primitives.removeAll(); 
viewer.entities.add({
    id:"1111",
    position: Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
    label: {
      text: "Philadelphia",
    },
  });
viewer.scene.primitives.removeAll(); 
viewer.entities.add({
      id:"2222",
    position: Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
    label: {
      text: "Philadelphia",
    },
  });

**Comment by ggetz** [comment]
Hi @freefer,

For background, entities are a higher-level API that create primitive geometries under the hood. It's recommended not to mix the Entity and Primitive APIs for this reason. 

If you are using point cloud tileset primitives, I would recommend removing them specifically rather than using `removeAll`.

Thanks!
