### ISSUE TITLE
The document content needs to be corrected

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11579]
Sandcastle example:  https://cesium.com/learn/cesiumjs-learn/cesiumjs-particle-systems/#boxemitter

Browser: All

Operating System: All

The emitter type in the BoxEmiiter sample code should be new Cesium BoxEmiiter() should not be new Cesium CircleEmiiter(), and the code does not match the sample image

BoxEmiiter 示例代码中的 emitter 类型应该是 new Cesium.BoxEmiiter() 而不应该是 new Cesium.CircleEmiiter()，并且代码与示例图片不匹配

![image](https://github.com/CesiumGS/cesium/assets/13347321/9c791a86-eaad-437e-a8c4-16bba8fd0f09)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! I've made a fix on the website content which should be published shortly.
