### ISSUE TITLE
Can someone give me an example of nuxt3 ts referencing cesium's demo?

### ISSUE THREAD

**Issue by bbhxwl** [CesiumGS/cesium#11586]
It's not correct to use it like me.

<script setup lang="ts">
let Cesium :any=null;
if(process.client){
  Cesium=await import("cesium");
}
onMounted(()=>{
  Cesium.Ion.defaultAccessToken="******";
  let viewer=new Cesium.Viewer("map");
})

</script>

<template>
<div id="map" class="w-full w-full">

</div>
</template>

<style scoped>

</style>

**Comment by bbhxwl** [comment]
After running, that's it.


![image](https://github.com/CesiumGS/cesium/assets/26525599/cbffe6d9-d2d7-41a3-b94a-8f1125e61311)

**Comment by ggetz** [comment]
Hi there,

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

Thanks!
