### ISSUE TITLE
Link 404 in document

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11588]
Sandcastle example: https://cesium.com/learn/cesiumjs-learn/cesiumjs-terrain/

Browser: All

Operating System: All

https://cesium.com/learn/cesiumjs-learn/cesiumjs-terrain/

In this link
The link shown in the figure is 404.

在这个链接中
如图所示的链接是404。

![image](https://github.com/CesiumGS/cesium/assets/13347321/5904e270-fec2-48bf-a5cc-15666cb0045b)

https://cesium.com/learn/cesiumjs-learn/cesiumjs-imagery/

In this link
The link shown in the figure is 'Page not found'. 

在这个链接中
如图所示的链接是'Page not found'

![image](https://github.com/CesiumGS/cesium/assets/13347321/87d1a69b-c3df-4297-a144-d8ec24b19122)

Can the above provide accessible links?
以上是否能够提供可访问的链接?

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! I've corrected the links on the website. The new version should be published shortly!
