### ISSUE TITLE
The example code in the provided link needs to be updated.

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11591]
Sandcastle example:

Browser:

Operating System:

https://cesium.com/learn/cesiumjs-learn/cesiumjs-3d-tiles-styling/

The example code in the provided link needs to be updated.
链接中的示例代码需要更新了

![image](https://github.com/CesiumGS/cesium/assets/13347321/d681904e-1195-4b66-ade2-6b0e40bc3643)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! I just fixed this on the website. The update should be published shortly.
