### ISSUE TITLE
how to get  new Cesium.SampledProperty pitch angle direction angle and roll angle in

### ISSUE THREAD

**Issue by freefer** [CesiumGS/cesium#11593]
我设置了实体的orientation 为 sampledOrientationProperty=new Cesium.SampledProperty(Cesium.Quaternion)；并且添加了时序方向信息
  const time = Cesium.JulianDate.addSeconds(
        start,
        xxx,
        new Cesium.JulianDate()
      );
var pitch = Cesium.Math.toRadians(90);
      var heading = Cesium.Math.toRadians(0);
      var roll = Cesium.Math.toRadians(0);
      var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
      var quaternion = Cesium.Transforms.headingPitchRollQuaternion(
        position,
        hpr,
        Cesium.Ellipsoid.WGS84,
        Cesium.Transforms.localFrameToFixedFrameGenerator(
          "north",
          "west"
        )
      ); 
    sampledOrientationProperty.addSample(time, quaternion);
Now I'm through clock.onTick event ,get entity orientation = sampledOrientationProperty.getValue(time); how get pitch angle, direction angle, roll angle on orientation

**Comment by freefer** [comment]
var fix = Cesium.Transforms.localFrameToFixedFrameGenerator(
      "north",
      "west"
    );
    var modelMatrix = entity.computeModelMatrix(t);
    var hpr = Cesium.Transforms.fixedFrameToHeadingPitchRoll(modelMatrix, Cesium.Ellipsoid.WGS84,fix);
    var roll = Cesium.Math.toDegrees(hpr.roll);
    var pitch = Cesium.Math.toDegrees(hpr.pitch);
    var heading = Cesium.Math.toDegrees(hpr.heading);
 Would this be a good way to achieve the desired result？

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
