### ISSUE TITLE
I think this part of the content needs to be updated

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11608]
Sandcastle example: none

Browser: all

Operating System: all

I think this part of the content needs to be updated
我想这一部分内容需要更新了
https://cesium.com/learn/3d-tiling/on-prem/on-prem-3d-buildings/
![微信截图_20231105215137](https://github.com/CesiumGS/cesium/assets/13347321/83a6d9f0-193a-4b29-b13b-c3cbd66fb969)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! I've update this on the website. Updates should be published shortly.
