### ISSUE TITLE
OsmBuildings display issue

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11606]
Sandcastle example: none

Browser: all

Operating System: all

When there are multiple Cesium views on a single page, OsmBuildings is displayed incorrectly. This issue is particularly severe in single-page frameworks such as React and Vue, their route transitions do not refresh the page, and it generates a unique ID every time, however, the problem still persists,is there any way to solve this problem?

单页面存在多个cesium视图时，OsmBuildings显示错乱，这个问题在React、Vue等单页面框架中尤其严重，它们的路由切换是不刷新页面的，并且每次都会重新生成一个唯一的ID，但问题依旧存在，是否有办法解决这个问题呢？

![微信图片_20231104225146](https://github.com/CesiumGS/cesium/assets/13347321/b9941044-0723-4eb1-a124-72d1027e804c)
![微信图片_20231104225227](https://github.com/CesiumGS/cesium/assets/13347321/1c5d6a87-3e13-4cb6-a0b6-49ffa80e4b1d)

**Comment by ggetz** [comment]
Thanks for bringing up this issue! I beleive we're already tracking it in https://github.com/CesiumGS/cesium/issues/11484. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
