### ISSUE TITLE
I have found some issues in the document again

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11609]
Sandcastle example:

Browser:

Operating System:

https://cesium.com/learn/3d-tiling/on-prem/on-prem-imagery/

In the above document, the content has been exposed, and is this part of the content redundant?
And is it not a required option?
上面文档中，内容露码了，并且这部分内容是否多余呢？
而且不需要必选项吗？

![image](https://github.com/CesiumGS/cesium/assets/13347321/dddc6de5-7422-4c80-976a-bd602e15f319)

**Comment by ggetz** [comment]
It is required id `--input-list` is not supplied. Which is why it is not checked in the table.

I have made fixes to the formatting issue which should be deployed shortly.
