### ISSUE TITLE
Add custom materialProperty

### ISSUE THREAD

**Issue by happyfeet1996** [CesiumGS/cesium#11602]
Cesium provided MaterialProperty is much less than what Material was provided,i want to use a water type material in entity, i can not use water material directly. I tried to convert water material to WaterMaterialProperty, it is so difficult.

I used angular, and i saw a demo that show us how to define custom MaterialProperty in https://gist.github.com/mramato/cbeede0339a067d3cf26, but i tried the same way to make WaterMaterialProperty
 in sandbox, it does not work, hear is my code :

const viewer = new Cesium.Viewer("cesiumContainer");

console.log(Cesium.Material._materialCache);

Cesium.Material._materialCache.addMaterial('Water', {
    fabric: {
    type: 'Water',
    uniforms: {
      normalMap: Cesium.buildModuleUrl(
          "Assets/Textures/waterNormals.jpg"
        ),
      frequency: 500.0, // 控制波数的数字。
      animationSpeed: 0.002, // 控制水的动画速度的数字。
      amplitude: 8.0, // 控制水波振幅的数字。
      specularIntensity: 1, // 控制镜面反射强度的数字。
      // baseWaterColor: Cesium.Color.fromCssColorString("#006ab4"), // rgba颜色对象基础颜色的水。#00ffff,#00baff,#006ab4
      baseWaterColor: Cesium.Color.fromCssColorString("rgb(122, 77, 18)"),
      blendColor: Cesium.Color.fromCssColorString("#006ab4"), // 从水中混合到非水域时使用的rgba颜色对象。
      // opacity: 0.1 // 透明度
    }
  }
});

//Create an instance and assign to anything that has a material property.
//scene - the scene
//image - the image (I think both a url or Image object are supported)
//anchor - A Cartesian3 that is the most southern and westard point of the geometry
var WaterMaterialProperty = function(scene) {
    this._scene = scene;
    this.definitionChanged = new Cesium.Event();
    this.isConstant = true;
};

WaterMaterialProperty.prototype.getType = function(time) {
    return 'Water';
};

WaterMaterialProperty.prototype.getValue = function(time, result) {
    
    return result;
};

WaterMaterialProperty.prototype.equals = function(other) {
    return (this === other) || (other instanceof  WaterMaterialProperty );
};

function computeCircle(radius) {
  const positions = [];
  for (let i = 0; i < 360; i++) {
    const radians = Cesium.Math.toRadians(i);
    positions.push(
      new Cesium.Cartesian2(
        radius * Math.cos(radians),
        radius * Math.sin(radians)
      )
    );
  }
  return positions;
}

function computeStar(arms, rOuter, rInner) {
  const angle = Math.PI / arms;
  const length = 2 * arms;
  const positions = new Array(length);
  for (let i = 0; i < length; i++) {
    const r = i % 2 === 0 ? rOuter : rInner;
    positions[i] = new Cesium.Cartesian2(
      Math.cos(i * angle) * r,
      Math.sin(i * angle) * r
    );
  }
  return positions;
}

const redTube = viewer.entities.add({
  name: "Red tube with rounded corners",
  polylineVolume: {
    positions: Cesium.Cartesian3.fromDegreesArray([
      -85.0,
      32.0,
      -85.0,
      36.0,
      -89.0,
      36.0,
    ]),
    shape: computeCircle(60000.0),
    material: new WaterMaterialProperty(viewer.scene),
  },
});

const greenBox = viewer.entities.add({
  name: "Green box with beveled corners and outline",
  polylineVolume: {
    positions: Cesium.Cartesian3.fromDegreesArrayHeights([
      -90.0,
      32.0,
      0.0,
      -90.0,
      36.0,
      100000.0,
      -94.0,
      36.0,
      0.0,
    ]),
    shape: [
      new Cesium.Cartesian2(-50000, -50000),
      new Cesium.Cartesian2(50000, -50000),
      new Cesium.Cartesian2(50000, 50000),
      new Cesium.Cartesian2(-50000, 50000),
    ],
    cornerType: Cesium.CornerType.BEVELED,
    material: Cesium.Color.GREEN.withAlpha(0.5),
    outline: true,
    outlineColor: Cesium.Color.BLACK,
  },
});

const blueStar = viewer.entities.add({
  name: "Blue star with mitered corners and outline",
  polylineVolume: {
    positions: Cesium.Cartesian3.fromDegreesArrayHeights([
      -95.0,
      32.0,
      0.0,
      -95.0,
      36.0,
      100000.0,
      -99.0,
      36.0,
      200000.0,
    ]),
    shape: computeStar(7, 70000, 50000),
    cornerType: Cesium.CornerType.MITERED,
    material: Cesium.Color.BLUE,
  },
});

viewer.zoomTo(viewer.entities);

**Comment by ggetz** [comment]
The water material was not written to be used on Entities. If you would like to create a custom material, I would suggest reading through our [Geometry and Appearances Tutorial](https://cesium.com/learn/cesiumjs-learn/cesiumjs-geometry-appearances/#appearances) as well as the [Fabric Schema](https://github.com/CesiumGS/cesium/wiki/Fabric).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by s3xysteak** [comment]
Use `primitive` to  add water material:
```
    const material = new Cesium.Material({
      fabric: {
        type: 'Water',
        uniforms: {
          baseWaterColor: Cesium.Color.CADETBLUE.withAlpha(0.4),
          normalMap: waterImageUrl, // normal map image
          frequency: 1000,
          animationSpeed: 0.02,
          amplitude: 20,
          specularIntensity: 1
        }
      }
    })

    const waterPrimitive = new Cesium.GroundPrimitive({
      geometryInstances: new Cesium.GeometryInstance({
        geometry: new Cesium.PolygonGeometry({
          polygonHierarchy: polygon.hierarchy.getValue(), // hierarchy here
          perPositionHeight: true,
          vertexFormat: Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT
        })
      }),
      appearance: new Cesium.EllipsoidSurfaceAppearance({
        material,
        aboveGround: true,
        translucent: true
      }),
      classificationType: Cesium.ClassificationType.TERRAIN
    })
    waterPrimitive.show = defaultState

    viewer.scene.primitives.add(waterPrimitive)
```
