### ISSUE TITLE
Water effect on PolygonGeometry 

### ISSUE THREAD

**Issue by polluxll** [CesiumGS/cesium#11618]
There was no water effect on polygongeometry.
Sandcastle example:
https://sandcastle.cesium.com/#c=nVVtT9swEP4rVr+QSsxpKaVrVtCqDhjSGAgYm0TR5CbX4s2xM9spZIj/PifBTdyW8ZIP0fmeu/M9d6dzKLjSaE7hFiTaRRxu0QgUTWN8Wei8cSMsziPBNaEc5LjR/DDmcyLRDEQMWmau36lg2Uzww0fQux9zVHxJCXymIIkMb7JgjdcC9KwXshYjIrWRCO/gqRTxJ5hJADWUkmTeVWWN0Lt2q49bm6jTMn8H6Hf/p99e0T8GyoFKf92sGV29jMLrSRS394p020tp1aD+KtR/DmnXySzReQWht1AqMi970FnJL8+w/yzWW4fZoD2X2gq5V9F7G8Eim06RzfaaVAu4/RJ45ym4Y+Fl9LrpaprX9XP9VMlVfeZgWN4dCBkTHVjq+4zRRAkanadySkIYJgkQSXgI+HL/7GL/x8+Dk7Pj4UUZ5CFfDAx0vhiOzFoh2hi6y8FuhQI2aLUd7DIJFlItaBn2lmiQx/mPEubGtdoq3pRMJA0DdF/R1lkCAdr4nttu1Iqbcjo1vJVjjNCEKChsR4IJ6WyrQuPtbCMfbXW7m6jd7Vlxq9uxYgt33fnjeXXZMUlMFjdaJyrwfUV4FBKlGeBy0eJQxH55zzceU5MbhcgfKgVa+Rdwp1MJyi9q8bWIp/CvZLbhXDSV8CcFHppqtlut5b1GODVNpoKfJwBRYPJsbbkGccKoTiNTra4DqATClBF5xDVwRXWWO7+vLB6s+FBrXi4s2ncqaUw1nS/NxUK9OhB2VFTgzNUiL7KYSadFT4+uV+symYg5HEqRclMHLVOo0Y0fZypwB29BsbnEsXxEsQqBA04sIYVJFHku99yjsdkYKJ0x2LMBP9I4EVKjVDIPY1+D6YJxU/4kDX+DxqFS9qqBX3cdRHSOaLS75qlGISNKGWSaMnZO/8K4sTfwjf2KKxMkonx2YvYAI1ludtPe+1IqMcYD3xzXe2oh2ITIpcj/AA
Browser:
chrome
Operating System:
windows11
Cesium 1.111

**Comment by ggetz** [comment]
It looks like you'll need to specify the polygon `textureCoordinates`.

See `texturedPolygonWithHoles` in [this example](https://sandcastle.cesium.com/?src=Polygon.html)

**Comment by polluxll** [comment]
> It looks like you'll need to specify the polygon `textureCoordinates`.
> 
> See `texturedPolygonWithHoles` in [this example](https://sandcastle.cesium.com/?src=Polygon.html)

Is there any sample to set textureCoordinates for complex polygon? 
The original version did not require setting textureCoordinates

**Comment by polluxll** [comment]
https://sandcastle.cesium.com/#c=nVVtT9swEP4rVr+QSsxpKaVrVtCqDhjSGAgYm0TR5CbX4s2xM9spZIj/PifBTdyW8ZIP0fmeu/M9d6dzKLjSaE7hFiTaRRxu0QgUTWN8Wei8cSMsziPBNaEc5LjR/DDmcyLRDEQMWmau36lg2Uzww0fQux9zVHxJCXymIIkMb7JgjdcC9KwXshYjIrWRCO/gqRTxJ5hJADWUkmTeVWWN0Lt2q49bm6jTMn8H6Hf/p99e0T8GyoFKf92sGV29jMLrSRS394p020tp1aD+KtR/DmnXySzReQWht1AqMi970FnJL8+w/yzWW4fZoD2X2gq5V9F7G8Eim06RzfaaVAu4/RJ45ym4Y+Fl9LrpaprX9XP9VMlVfeZgWN4dCBkTHVjq+4zRRAkanadySkIYJgkQSXgI+HL/7GL/x8+Dk7Pj4UUZ5CFfDAx0vhiOzFoh2hi6y8FuhQI2aLUd7DIJFlItaBn2lmiQx/mPEubGtdoq3pRMJA0DdF/R1lkCAdr4nttu1Iqbcjo1vJVjjNCEKChsR4IJ6WyrQuPtbCMfbXW7m6jd7Vlxq9uxYgt33fnjeXXZMUlMFjdaJyrwfUV4FBKlGeBy0eJQxH55zzceU5MbhcgfKgVa+Rdwp1MJyi9q8bWIp/CvZLbhXDSV8CcFHppqtlut5b1GODVNpoKfJwBRYPJsbbkGccKoTiNTra4DqATClBF5xDVwRXWWO7+vLB6s+FBrXi4s2ncqaUw1nS/NxUK9OhB2VFTgzNUiL7KYSadFT4+uV+symYg5HEqRclMHLVOo0Y0fZypwB29BsbnEsXxEsQqBA04sIYVJFHku99yjsdkYKJ0x2LMBP9I4EVKjVDIPY1+D6YJxU/4kDX+DxqFS9qqBX3cdRHSOaLS75qlGISNKGWSaMnZO/8K4sTfwjf2KKxMkonx2YvYAI1ludtPe+1IqMcYD3xzXe2oh2ITIpcj/AA      **a example of poor performance**

**Comment by polluxll** [comment]
https://sandcastle.cesium.com/#c=zVZtT9swEP4rVr+QSszpC6VrVtBQBxvSGAgYm0SryU2uxZtjZ7ZT6BD/fU5C0rgvo632gXyI7Hvuzveczz77giuNJhTuQaIDxOEe9UDROMQ3qczpV/x03hNcE8pB9ivVd30+IRKNQYSg5dS2uxBsOhb84zPoPPY5Sr8oAz5RkET6d1NviVUBOrkVyjV6RGozIryJR1KEH2AsAdSRlGTq3M60EXpTr3VwbRc1a+ZvAZ3Wv+R7C/JnRwkwkw+qJaXb9ShsTiJdvZ2GW58LqwR1FqHOS0i9TGaOzgaEtqGURp7tQXMhviTCzotYexmWO23b1BbIbURvO4JpNM00mr0loaZwfR14fxXczOF5dFC1JdVBeV6ezcZZfjQ86FhCTwgZUE4M23XPZjmfRZ4ajomwhhvl5K/WW0MLNzbQM+sOtjmhq6nU/xeR+rpadYvCJmX7mllsePxeGZVtD1fyTcA4ezgRMiTay1c4ZoxGStDgKpYj4sNRFAGRhPuAb44vr4+//zg5vzw7us6cPCVdl4FOuu6p6dlEG0W78+YtN4UNOmu9eaf2ilHJaeb23hx7eZb8KGG231w68zciQ0l9Dz3OaOtpBB7a+Zbo7pRSGnM6MryVpYzQkChIdXuCCWldN6nE2d9DLmq0Wib3rXY+bLSa+bCGW/blzpPssjMSmSjutI6U57qK8MAnSjPA2SsG+yJ0s3W+8pCa2CgE7pFSoJV7nV2Dyk1z8SX1p/DPaLxjLTSS8DsG7ptstmq1+UcD4dRsMhX8KgIIPBNnrWErhBGjOg5MtloWoCLwY0bkKdfAFdXTxPjtTOMpHz6VNi8ZFNt3IWlINZ3M1UUhXiyIvFSUZ9VVERcpatLaotWl65R2mQzFBD5KEXOTBy1jKNENn2vKswuvoFid45i9ULHygQOOckIKkyBwbO5ZSVd2K12lpwwOc5fvaRgJqVEsmYOxq8HsQ9Lq3GHs/wKNfaXyxbpu2bQb0AmiwcGSlzDyGVHKIKOYsSv6B/qVw65r9BdMmSCmtY7PzU3AyDRRu6sffs6EGOOua6bLLbUQbEjknOe/
**A example of poor performance**
