### ISSUE TITLE
在进行加载wms数据的时候，链接后面的请求参数名称如何改为大写

### ISSUE THREAD

**Issue by ZhangLB123** [CesiumGS/cesium#11613]
在进行加载wms数据的时候，链接后面的请求参数名称如何改为大写

**Comment by ggetz** [comment]
Hi there,

You can implement a WMS service to your unique specifications with a [`UrlTemplateImageryProvider`](https://cesium.com/learn/cesiumjs/ref-doc/UrlTemplateImageryProvider.html?classFilter=url).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
