### ISSUE TITLE
Another publication error was found in the document

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11614]
Sandcastle example: None

Browser: All

Operating System: All

https://cesium.com/learn/3d-tiling/on-prem/on-prem-reality-tiler/

![image](https://github.com/CesiumGS/cesium/assets/13347321/04466501-8700-469d-83fa-60e72b850ae5)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! I've passed along this issue to the relevant tracker.
