### ISSUE TITLE
Disappearance of scaled non-uniform i3dm feature

### ISSUE THREAD

**Issue by Error806** [CesiumGS/cesium#11617]
I have an i3dm file that references a model approximately 1 meter in length. In the i3dm file, the scale_non_uniform property of the model in the feature is set to (1, 50, 1), effectively making the corresponding feature 50 meters long. When the camera is at certain angles relative to the feature, even though the feature's boundingVolume is still within the camera's view, the feature disappears from the camera's perspective. This issue does not occur when I scale the original model up by a factor of 50 and load it as a glb, b3dm, or i3dm file.

https://github.com/CesiumGS/cesium/assets/38496128/39c4d44e-b67a-4d56-b1a4-aa9d2a09f36d

The i3dm file and the original glb I used:
[testFiles.zip](https://github.com/CesiumGS/cesium/files/13314546/testFiles.zip)

For comparison, this is the model after the original model was stretched 50 times. I did not find any of the above problems with this model.
[50xFiles.zip](https://github.com/CesiumGS/cesium/files/13314555/50xFiles.zip)

**Comment by ggetz** [comment]
Thanks for the report @Error806.

I believe we're already tracking it in https://github.com/CesiumGS/cesium/issues/11176. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
