### ISSUE TITLE
I used CityEngine to export the model. Why is the spatial position incorrect and how can I adjust it?

### ISSUE THREAD

**Issue by bbhxwl** [CesiumGS/cesium#11610]
Import into CityEngine and use epsg: 4548. After exporting the model, how can I use it in cesium? The default location is incorrect.

![~7PH2~@SATFXNVRYL{0IOCC](https://github.com/CesiumGS/cesium/assets/26525599/64956b97-d2f8-4ed8-9a59-93f02b81d151)

**Comment by ggetz** [comment]
Hi there, 

If you want to simply drop a model into CesiumJS, I would recommend exporting it as EPSG:4978. 

Spending on your workflow, there may be different ways of solving your problem.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by bbhxwl** [comment]
> Hi there,
> 
> If you want to simply drop a model into CesiumJS, I would recommend exporting it as EPSG:4978.
> 
> Spending on your workflow, there may be different ways of solving your problem.
> 
> CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

CityEngine does not have 4978
