### ISSUE TITLE
Minor issues in the document

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11621]
Sandcastle example:

Browser:

Operating System:

https://cesium.com/learn/3d-tiling/on-prem/on-prem-terrain/

![image](https://github.com/CesiumGS/cesium/assets/13347321/46aeb3c2-1943-4cd9-857e-02d1488844d5)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! The fix should be published soon!
