### ISSUE TITLE
Another code exposure was found in the document

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11620]
Sandcastle example:none

Browser:all

Operating System:all

https://cesium.com/learn/3d-tiling/on-prem/on-prem-terrain/
![image](https://github.com/CesiumGS/cesium/assets/13347321/df905229-7199-4d27-86fc-8265ef527e13)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang! I've fixed the error. The fix should be published soon.
