### ISSUE TITLE
Adjust the hue of the image, why choose YIQ

### ISSUE THREAD

**Issue by jiaming1981** [CesiumGS/cesium#11639]
![hue](https://github.com/CesiumGS/cesium/assets/19943661/eeda3179-6434-4d61-9966-870f2d0324d6)
https://en.wikipedia.org/wiki/YIQ

Why not choose the commonly used HLS / HSB, Are there any special requirements to choose YIQ?

**Comment by ggetz** [comment]
I believe this is commonly used in image process to preserve the brightness balance. 

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
