### ISSUE TITLE
Different representations of the same material on different objects

### ISSUE THREAD

**Issue by verybigzhouhai** [CesiumGS/cesium#11634]
Hi,
      The water material has a different appearance on RectangleGeometry and PolygonGeometry.

ex:
https://sandcastle.cesium.com/index.html#c=zVbbbts4EP0VQk82YFBSZbeJ6gYNsukFaNoiSbsLVEVBS2ObuxSpkpQTZeF/X5KyZMlV0gItFvWDTM7MGZ7hHIpKBVcabSjcgETPEIcbdAaKljn+6GyjxEvd/ExwTSgHmXjjpwlPHU6lwMHAajx2U+NM+IZIZ7wQGTAT8G/CEVpK+FoCT6sYhUGAg4k13sYowKEbVnY4c8M7E+IGhBVr0k7yglFdZhCjyMZt27VuiAb5JbdPSli/kIuddVSTIAtJ07hmhJCuCpMt8f60QYk3qa0lp0shc9WGIbQgClzQmWBCxt0FnGXUBKJ94fh2MmStBq13g1ZXf+MYT5Dvo9Qu15i4oUnYBSnihs2ipCwz4JLBB8k6tBLvVCnQyr+GW11KUL7btbcug8J/F6vE26/UjDpN27NqjY5QO2swhFPTCir4VQGQ2a4GYZuw08ROmY3RJWxnNWbrsPa5HbuOM9BIQqoJXzErP6c7XEiaU003oDDJsl3hnTa9b/yjtqkrEDloWb02YibcCL3X15cH3j1uj+wBLhtODbKLQHvK8TcAs6Mi/wNWEkCNuhiEwnCKg9nx0exxNH0UzILpdNIPiB7haRQ8OT4Oo1kYBdNwcphghoOjBzNEBxm67nEv2EhHmsZkr4Cu1jpGsyAIegHrnaPPYgNSw+0LKzXdVn/OGC2UoNlVKZckhdOiACLtTuOP55fX5399efHu8uL0upNpu2fTGZIW2GvH/fm7fSELsYGXUpTcKHVpTgJ01mveKPHBG2aAhFqLmxiZ3Wnw27H9rxVba7YQrFoJ/hsp9n3NaFivO7qvKEgi0/UgsnUeqLZ5NRLTd0UJj7oKP5WSVKNPfUQt1Idk+n2p2xyP/48c0fdzzH4yx+fxb3wKf/wQNrfv8OH7Vedr9wGSktzIEZtbzn691AtloDTl7jqKH5blTsL3te4+4USB/Tku9RXlTby50hWDk4b7c5oXQmpUmgsZY1+DueBMpcpflOk/oHGqlK3Dhs79LnSe0Q2i2bOBrzCUMqKU8SxLxq7oHSTeydw38d9AmSAZ5at3pv2MVDZsHZ68qY0Y47lvpsNILQRbEHmQ+T8

**Comment by verybigzhouhai** [comment]
![image](https://github.com/CesiumGS/cesium/assets/37999729/e090078f-ccb7-4f8e-a8fb-12b4f8a2e058)

**Comment by ggetz** [comment]
Hello,

You need to 

1) Use `EllipsoidSurfaceAppearance` for both geometries
2) Set the texture coordinates for the polygon

[Sandcastle example](https://sandcastle.cesium.com/index.html#c=1VZtb9s2EP4rhD7ZgEBLkd01qhs0yNJ2wLIWSdoNqIqCls42N4pUScqJMvi/j6QsWXKUtEWLYfMHmbx7nuOR9/AlFVxptKFwAxI9Rxxu0BkoWub4vbONEi91/TPBNaEcZOKNnyU8dTyVAgdDq/nYdY0z4RsinfFCZMAM4O+EI7SU8LkEnlYxCoMAB7413sYowKFrVrY5c807A3ENwoo1aTt5waguM4hRZHHbdqwbokF+yu2XEtafyMXOOqqTIAtJ07jOCCFdFSZa4v1uQYnn19aS06WQuWphCC2IAgc6E0zIuDuAs4waINpPHN/6Q9Zq0Ho3aHXzbxxjH00mKLXDNSZu0iTsghRxk82ipCwz5JLBO8k6aSXeqVKg1eQabnUpQU3cqv3mIij8Z7FKvP1ITatTtH1WrdEl1PYaDuHUlIIKflUAZLaqQdgG7BSxM83G6AK2vZqzdVz73Y5dxRloJCHVhK+YlZ/THS4kzammG1CYZNlu4p0yvW38o7aoKxA5aFn9YsRMuBF6r66vDrx73p7ZI1w2OTXMLgPtU47vEcyKivxnWEkANepyEArDKQ5mx09nT6LpUTALplO/D4iO8DQKfjo+DqNZGAXT0D8MMMPB00cjRAcRuu5xD2ykI01hstdAV2sdo1kQBD3AeufoZ7EBqeH2pZWabmd/zhgtlKDZVSmXJIXTogAi7Urj9+eX1+d/fHr55vLi9LoTabvPptMkLbFXjofjd+tCFmIDr6QouVHq0uwE6IzXnCjxwQkzkIRai5sYmdVp+Nux/a8VW2u2EKxaCf4fUuzbOqNhve7SfU1BEpmuB5mt80C1zdFITN0VJTzqKvxUSlKNPvQZtVAfk+mXpW5jPPk3YkRfjjH7zhgfxw/vQqTrI/xMCJlRbkTZvaqa6ilqz2DjubfS3curqdDRKPBRMPa/Dht+Gzb8WmwwgP3Y62+/7Tz6cSfP//Lg2b3MUpKbfYrN9W+fdXUWGShttWM0Ej++X3d7+yFNP7SjosD+XC713e353lzpisFJk/sLmhdCalSalwrGEw3m5rdqnizK9C/QOFXKzsNC55MudZ7RDaLZ84HnKUoZUcp4liVjV/QOEu9kPjH4e1QmiNk9qzdGI4xUFrYOT36tjRjj+cR0h5laCLYg8iDyPw)

<img width="845" alt="image" src="https://github.com/CesiumGS/cesium/assets/4439461/f13f2388-e307-41a0-9964-2d0b1ceac7fd">

**Comment by verybigzhouhai** [comment]
@ggetz ，
Thank you for your reply. The reason for this issue is that after upgrading to the latest version of cesium, the previous usage was not updated correctly. Therefore, in the latest version of PolygonGeometry, if UV is not provided, will UV not be automatically calculated? The above example performs correctly in cesium 1.98.
![image](https://github.com/CesiumGS/cesium/assets/37999729/be2d3171-72e9-4681-b9df-5b7e13a7ec1b)
