### ISSUE TITLE
model.modelMatrix dosen't appear in model variables in cesium.js

### ISSUE THREAD

**Issue by luca-moscatelli** [CesiumGS/cesium#11647]
model.modelMarix is not a valid variable on my vscode , if i click on the type modelmatrix isn't in the groups of variables cesiumjs v:1,11

Operating System: windows 10

**Comment by ggetz** [comment]
@luca-moscatelli Are you sure `model` is an instance of `Model`? Can you provide a short code sample?

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
