### ISSUE TITLE
Unable to pull resources from Cesium due to CORS error

### ISSUE THREAD

**Issue by informatter** [CesiumGS/cesium#11643]
Hi there,

It seems like CORS is no longer working for the Cesium domain. It was previously working. It seems like this issue is related to a similar issue which happened in the past: https://github.com/CesiumGS/cesium/issues/8050

The issue is only happening in a production environment, not locally. 

The way we have always embedded Cesium.js in our app is as:
`https://cesium.com/downloads/cesiumjs/releases/1.108/Build/Cesium/Cesium.js`

@ggetz @hpinkos @mramato

**Comment by brianwthomas** [comment]
Looking into this.

**Comment by brianwthomas** [comment]
Thanks for the report and sorry for the delay, this issue has been addressed. Please reopen this if you're still having issue. Thanks again.

**Comment by mramato** [comment]
@aerialist7 Try clearing your cache (or try private/Incognito mode to confirm you are starting with a fresh cache). Sandcastle no longer shows this issue on several machines we tested.

**Comment by aerialist7** [comment]
Doesn't help

https://github.com/CesiumGS/cesium/assets/32072831/53c0e0c6-c6ea-4a3e-a051-917131639fcb

**Comment by mramato** [comment]
Thanks for the reports, we've identified this as a sporadic issue and have reproduced it and are looking into what's happening.

**Comment by jeffsyee** [comment]
@brianwthomas - thank you.  Appears to be working on our side now.

**Comment by aerialist7** [comment]
@brianwthomas, thanks, now it's ok
