### ISSUE TITLE
Unnecessary Bing Maps warning

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1165]
A Bing Maps key warning is generated when we construct the viewer widget with the following code.  Perhaps this needs to be done a different way?

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    selectedImageryProviderViewModel : new Cesium.ImageryProviderViewModel(
    {
        name : 'Open\u00adStreet\u00adMap',
        iconUrl : Cesium.buildModuleUrl('Widgets/Images/ImageryProviders/openStreetMap.png'),
        tooltip : 'OpenStreetMap (OSM) is a collaborative project to create a free editable map \
of the world.\nhttp://www.openstreetmap.org',
        creationFunction : function() {
            return new Cesium.OpenStreetMapImageryProvider({
                url : 'http://tile.openstreetmap.org/'
            });
        }
    })
});
```

**Comment by mramato** [comment]
Given our recent Bing map keys woes, we should probably create a much more "in-your-face" message for when the API key is set to the default, perhaps by overlaying an HTML element or ViewportQuad in the top center of the screen?

**Comment by pjcozzi** [comment]
Yes, we might also even ask that they get a key before downloading Cesium like [Leaflet](http://leafletjs.com/examples/quick-start.html) (or default to something low-res that we host).

Let's hold for now until we think more deeply.

**Comment by mramato** [comment]
Now that we are rotated keys, should we just close this?

**Comment by mramato** [comment]
We already have an issue for that in #1262
