### ISSUE TITLE
PolylineVolume curves before an expected point.

### ISSUE THREAD

**Issue by morita-shota** [CesiumGS/cesium#11652]
Hi, I am Morita.
I am trying to draw a PolylineVolume that passes through the specified points.

However, as the bending angles become larger, the PolylineVolume bends before the specified points.

Here is an example of the source code.

[Sandcastle Example](https://sandcastle.cesium.com/#c=lVRtb9owEP4rVj4lEnWgZZqUUTQGqJ3GRsW67sMyVW5yIdYcO7IdGKv473MS8sagWi1FuTs/d/fcYyeB4EqjDYUtSHSNOGzRFBTNEvxQxGzfCgp/KrgmlIP0Leedz33uukjHgFQKAY0ohCgVlGvl86AomQpFNTWmqfrD58isQ+EpkdpYhF/hSIpkBmsJoOzBVb+H8qfv9P4LPzTY4Wvwgx66fJvjff6zGKFkqmKSQsWyJUBd59K+GPbNqludBr0CM3gJc1GDujxTwXbMnMCDYFkC3cO66+zdSJLGNFB23uS5FKc+D68xD7oVAnjl6xASmc7LeUjLrIolRIOkhHk1Z8GExN9vP97P8ZbqeMLSmNh9/MbJE/Y+d1rsgWuqd13W8yLWZklDD/kWDX2rV9FuD+Yd+Z0+5SXGRSMKCpMwtMuu5/ePTqFFqKbUcPBOKd7RulzPjfmi7uU6I+uHxWT6qcHtK9MpjcJ3qtEjIZFd3RLzFSIRNd2cktC58TuDlileWaXXxI3ndecKcpZHnFfzWWe0lP4G9pX+McoN+p2dGOg61iuIQAIPoK5z243j6WLy+e7xfvl4s1p++zKrSuwbEXIBzNvqWSOldwzGFeY9TVIhNcokszF2NSQpM1Ir9ykLfoHGgVJ5bg4due3UUUg35iJen/jzoYARpcxOlLFiMN8aj1yD/yeVCRJSvl5uQDKyy2HxYLwogxjjkWvc05laCPZE5FHlvw)

It consists of an Entity with the 3 points given to the PolylineVolume, an Entity connecting the 3 points with a Polyline, and the 3 points themselves as Entities.
You can see that the second point, (140, 40, 0), is outside the PolylineVolume.

Is this behavior intended by Cesium?
If it is an intended behavior, how can I draw a PolylineVolume that passes through the specified points?

Thank you in advance for your assistance.
Morita.

**Comment by ggetz** [comment]
Hi, you can adjust the [`cornerType`](https://cesium.com/learn/cesiumjs/ref-doc/PolylineVolumeGraphics.html#cornerType) to `MITRE`. [Sandcastle Example](https://sandcastle.cesium.com/#c=lVRtb9owEP4rVj4lEnWgZZqUUTQGqJ3GRsW67sMyVW5yIdYcO7IdGKv473MS8sagWi1FuTs/d/fcYyeB4EqjDYUtSHSNOGzRFBTNEvxQxGzfCgp/KrgmlIP0Leedz33uukjHgFQKAY0ohCgVlGvl86AomQpFNTWmqfrD58isQ+EpkdpYhF/hSIpkBmsJoOzBVb+H8qfv9P4LPzTY4Wvwgx66fJvjff6zGKFkqmKSQsWyJUBd59K+GPbNqludBr0CM3gJc1GDujxTwXbMnMCDYFkC3cO66+zdSJLGNFB23uS5FKc+D68xD7oVAnjl6xASmc7LeUjLrIolRIOkhHk1Z8GExN9vP97P8ZbqeMLSmNh9/MbJE/Y+d1rsgWuqd13W8yLWZklDD/kWDX2rV9FuD+Yd+Z0+5SXGRSMKCpMwtMuu5/ePTqFFqKbUcPBOKd7RulzPjfmi7uU6I+uHxWT6qcHtK9MpjcJ3qtEjIZFd3RLzFSIRNd2cktC58TuDlileWaXXxI3ndecKcpZHnFfzWWe0lP4G9pX+McoN+p2dGOg61iuIQAIPoK5z243j6WLy+e7xfvl4s1p++zKrSuwbEXIBzNvqWSOldwzGFeY9TVIhNcokszF2NSQpM1Ir9ykLfoHGgVJ5bg4due3UUUg35iJen/jzoYARpcxOlLFiMN8aj1yD/yeVCRJSvl5uQDKyy2HxYLwogxjjkWvc05laCPZE5FHlvw).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by GatorScott** [comment]
For better or worse, users will compare Cesium's behavior to SVG and toolkits that draw lines.  I would expect the definitional points to be covered by the "pen" that is drawing the polyline.

**Comment by morita-shota** [comment]
@ggetz 
Thank you very much for kind reply.

> Hi, you can adjust the [`cornerType`](https://cesium.com/learn/cesiumjs/ref-doc/PolylineVolumeGraphics.html#cornerType) to `MITRE`. [Sandcastle Example](https://sandcastle.cesium.com/#c=lVRtb9owEP4rVj4lEnWgZZqUUTQGqJ3GRsW67sMyVW5yIdYcO7IdGKv473MS8sagWi1FuTs/d/fcYyeB4EqjDYUtSHSNOGzRFBTNEvxQxGzfCgp/KrgmlIP0Leedz33uukjHgFQKAY0ohCgVlGvl86AomQpFNTWmqfrD58isQ+EpkdpYhF/hSIpkBmsJoOzBVb+H8qfv9P4LPzTY4Wvwgx66fJvjff6zGKFkqmKSQsWyJUBd59K+GPbNqludBr0CM3gJc1GDujxTwXbMnMCDYFkC3cO66+zdSJLGNFB23uS5FKc+D68xD7oVAnjl6xASmc7LeUjLrIolRIOkhHk1Z8GExN9vP97P8ZbqeMLSmNh9/MbJE/Y+d1rsgWuqd13W8yLWZklDD/kWDX2rV9FuD+Yd+Z0+5SXGRSMKCpMwtMuu5/ePTqFFqKbUcPBOKd7RulzPjfmi7uU6I+uHxWT6qcHtK9MpjcJ3qtEjIZFd3RLzFSIRNd2cktC58TuDlileWaXXxI3ndecKcpZHnFfzWWe0lP4G9pX+McoN+p2dGOg61iuIQAIPoK5z243j6WLy+e7xfvl4s1p++zKrSuwbEXIBzNvqWSOldwzGFeY9TVIhNcokszF2NSQpM1Ir9ykLfoHGgVJ5bg4due3UUUg35iJen/jzoYARpcxOlLFiMN8aj1yD/yeVCRJSvl5uQDKyy2HxYLwogxjjkWvc05laCPZE5FHlvw).
> 
> CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

I expect PolylineVolume to have rounded corners and curve around specified points. As you suggest, I will post this on the forum.

Thanks.
