### ISSUE TITLE
doc: "Build a Flight Tracker" tutorial needs code adjustsments to work properly

### ISSUE THREAD

**Issue by yumemio** [CesiumGS/cesium#11650]
Hello 👋 I'm following along with the [Build a Flight Tracker](https://cesium.com/learn/cesiumjs-learn/cesiumjs-flight-tracker/) tutorial, and I noticed three subtle bugs.

The first two of them are related to the [Glitch project](https://glitch.com/edit/#!/remix/cesium-template) linked in the documentation, while the last one is found in the code snippet in the web page.

## Bug 1: The loaded Cesium version is outdated

The `<script>` tag in `index.html` loads an old version of CesiumJS (1.82).
This causes an error in step 2, where we use `Cesium.Terrain.fromWorldTerrain`:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'fromWorldTerrain')
```

Updating the `<script>` and `<link>` sources to refer to version 1.111 fixes the issue.

```diff
<head>
-<script src="https://cesium.com/downloads/cesiumjs/releases/1.82/Build/Cesium/Cesium.js"></script>
-<link href="https://cesium.com/downloads/cesiumjs/releases/1.82/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
+<script src="https://cesium.com/downloads/cesiumjs/releases/1.111/Build/Cesium/Cesium.js"></script>
+<link href="https://cesium.com/downloads/cesiumjs/releases/1.111/Build/Cesium/Widgets/widgets.css" rel="stylesheet">

  <link href="style.css" rel="stylesheet">
</head>
```

Code snippets in the web page are up to date.

## Bug 2: `await` is used without `type=module`

The provided `index.html` uses a plain `<script>` tag (as opposed to `<script type="module">`), which means we cannot use `await` in the top-level context.

```html
<script>
...
const osmBuildings = await Cesium.createOsmBuildingsAsync(); // we cannot use `await` here
viewer.scene.primitives.add(osmBuildings);
...
</script>
```

This causes the following error ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_await)):

```
Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules
```

The fix is either to add `type="module"` to the `<script>` tag...

```diff
-<script>
+<script type="module">
```

,,,or to replace `await` with a promise:

```diff
-const osmBuildings = await Cesium.createOsmBuildingsAsync();
-viewer.scene.primitives.add(osmBuildings);
+Cesium.createOsmBuildingsAsync()
+    .then(osmBuildings => {
+        viewer.scene.primitives.add(osmBuildings);
+    })
+    .catch(error => {
+        console.error('Error occurred:', error);
+    });
```

This bug, too, is already addressed in the web page's snippets (notably in the last one showing the complete code).

## Bug 3: code snippet in step 5 uses deprecated methods

The code snippet provided in Step 5 (Visualize movement over time) uses `createWorldTerrain` and `createOsmBuildings`, which are both superseded by async methods (`createWorldTerrainAsync` and `createOsmBuildingsAsync`).

The snippet can be updated like this:

```diff
const viewer = new Cesium.Viewer('cesiumContainer', {
- terrainProvider: Cesium.createWorldTerrain()
+ terrainProvider: await Cesium.createWorldTerrainAsync()
});
- const osmBuildings = viewer.scene.primitives.add(Cesium.createOsmBuildings());
+ const osmBuildings = await Cesium.createOsmBuildingsAsync();
+ viewer.scene.primitives.add(osmBuildings);
```

The code example in the last section (Complete source code) needs to be revised, too.

Thanks in advance! 😊

**Comment by ggetz** [comment]
Thanks for the report @yumemio! We'll update the tutorial shortly.
