### ISSUE TITLE
The inner radius of the ellipsoid is rendered differently for ConstantProperty and SampledProperty

### ISSUE THREAD

**Issue by Masahiro0326** [CesiumGS/cesium#11656]
Hello.

I created two ellipsoids with the same inner radius value but different types. One uses `ConstantProperty` and the other uses `SampledProperty`. When `ConstantProperty` is used, it is rendered correctly, but when `SampledProperty` is used, the inner radius of the ellipsoid is rendered short.

**near issue**
https://github.com/CesiumGS/cesium/issues/10245

I investigated the cause of this. After modifying the following file, it was displayed correctly. However, I don't know if this modification is correct.

https://github.com/CesiumGS/cesium/blob/ee12834487977c29747cd1d70e5aa541eb71b4a6/packages/engine/Source/DataSources/EllipsoidGeometryUpdater.js#L548-L562

I changed it as below.
```
if (defined(innerRadii)) { 
   if (in3D) { 
     const mag = Cartesian3.magnitude(radii); 
     options.innerRadii = Cartesian3.fromElements( 
       innerRadii.x / radii.x,  // changed
       innerRadii.y / radii.y,  // changed
       innerRadii.z / radii.z,  // changed
       options.innerRadii 
     ); 
   } else { 
     options.innerRadii = Cartesian3.clone(innerRadii, options.innerRadii); 
   } 
 } else { 
   options.innerRadii = undefined; 
 } 


```

Sandcastle example: https://sandcastle.cesium.com/#c=1VZtb9owEP4rp3yiUmYSCi1jgCbRftu0aUz7QvjgJgdYdWxkO3R04r/PzgsJhbVi2tRNygu+e+7J3fnBulgKbWDD8AEVjEDgA0xQsywl33JbK/LifD2RwlAmUEXexbtIRCLOI+PHlNu4WSQAfrgHAEsGEHmJjLMUhYk8vzALmqJzIOdsrSVL9p4NKs2kcM6QBJHnrDu/wViF3lahITBhUwFFE8ZgStM1x+SzkmtUZrvnXUvNjCMuaQBiqoxcKrpesfgGlwpRD2D2JgxDHy7t3euG5HJeoHclyz7fmib/7AD264LYtonaImb9bv+qG/hw+J5X4IoXihq+5FyzmqrB2uSddUq6w/fcb8KZMKg2lLtmdYJOp20f3aKh5cern3VcygRL7f5yGd8Pqs3/SM2KGOmSo0K3+sFFjaffX8S/beJLfinwHPpn4Afs1FbMbMWNtmnJWTKRXKrBYTOPTXYvl3fUblqn1/PBdjUAH8LL/rwJ2p3oX72LMjOcuWSNyrC07l6WcOdAwhP3Z6LC/M8arkwnKV+U7+4sQV73zhRk7zxB9l5dkEEux1yWf1OPCheoUMQIt0fn8itp7xdKeVZ7pzVnM3LX/Pc0du6hFwbnnXrXwT8iMnvmXQV/RGGRmDdmg4QaOpWZsuIaVUVN7Lxws7cTLmnScjNEMVMUcwipAzWhSdKq1w5WghZ8+1U+cXm+N9Rmy3Fc5fqepWupDGSKtwhpG7Sjgm2ebt9l8T0aEmvtAh102G6GDhO2saPM6MT8AzGnWlvPIuN8yh4x8sbDtsUfhbrymFh+shMOp1sHW4XjD4WREDJs2+XpSCMlv6PqCfNP

The `innerRadii` of "Ellipsoid1" is used `SampledProperty`.
The `innerRadii` of "Ellipsoid2" is used `ConstantProperty`.
The `radii` of "reference Ellipsoid" is the same value of Ellipsoid1's `innerRadii`.

Browser: MicroSoft Edge 119.0.2151.72

Operating System: Windows 10

**Comment by ggetz** [comment]
Thanks @Masahiro0326!

I believe you've correctly identified the issue here, which is the same issue as https://github.com/CesiumGS/cesium/issues/10245.

Would you be able to open a pull request with the fix?

**Comment by srtrotter** [comment]
@ggetz I've been tracking this bug as well and was just working on a fix. PR coming soon.
