### ISSUE TITLE
Assignment to constant variable.

### ISSUE THREAD

**Issue by swanghao** [CesiumGS/cesium#11651]
The development environment is normal. The online environment prompts "Assignment to constant variable"
![2](https://github.com/CesiumGS/cesium/assets/13250516/da36f14c-f7fc-4ad6-ab60-48904b200e44)

version：
   "cesium": "1.93",

**Comment by swanghao** [comment]
Oblique photographic data in b3dm format is used

**Comment by ggetz** [comment]
Hi @swanghao,

Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

**Comment by swanghao** [comment]
> Hi @swanghao,
> 
> Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

This problem only occurs in production environments,The local development environment is running properly,  This is the address we posted online:
http://47.96.131.222/b3dms/demo/#/

**Comment by swanghao** [comment]
> > Hi @swanghao,
> > Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!
> 
> This problem only occurs in production environments,The local development environment is running properly, This is the address we posted online: http://47.96.131.222/b3dms/demo/#/

This is a preview of the local run:
![微信图片_20231128132419](https://github.com/CesiumGS/cesium/assets/13250516/a318d7fd-b212-4a5f-89d5-9af8a14380ab)

**Comment by swanghao** [comment]
> Hi @swanghao,
> 
> Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

The share link of this case is accessible normally:

https://sandcastle.cesium.com/#c=bVLLbtswEPyVhdqDDFhUgqIXVzEKpAFyKNCiTXvSIRS1tthQXIO7siEH/vdSDwd58UBxHzO7M5AhzwJ7iwcMcAUeD3CNbLtW/R1zaZmYMb4mL9p6DGWy+FJ6hwJiHTJKjCT08Fh6OKcikz5oK2eu6fPp291UVptA7Z/g0gECUCaNyI5Xee6o1471BjPibZUJsihizozPGu23x4Y6pZ3tO29YGWrz/pD51uTzWPWPyZfJwDrsCLMuxQY9ql2wrRW7R1a6rtMZ86LxSNTe0bm0fG7HLera+u1PK6b5FXfB9EJdLCG7HO7P8b0YmE5gdGyAFEOgsJhMMdFjcqgcbdP7m6EAjka2s18r+Pg4Ik73I0vpS58sk4Kld7ieXAL4atsdBYEuOqdULtjunI4e5VVnHqJ6wzypGc4HIXKVDlB1IuSnTaZTW47AfgWVI/PwhDhNjyJ/PrWo7R5sffXObwDGaeZY2XTO/bZHLJN1kcf+N9BZ7Y89hjh3aGsu19+npFKqyGP4PnIW8Yr5Pw

**Comment by swanghao** [comment]
> Hi @swanghao,
> 
> Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

The issue has been resolved，The following code cannot be declared with constants,  Use let to declare objects,
![微信图片_20231128171807](https://github.com/CesiumGS/cesium/assets/13250516/2e74241e-8edc-4b21-a38a-7072f40a49af)

**Comment by 2496772010** [comment]
> > Hi @swanghao,
> > Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!
> 
> The issue has been resolved，The following code cannot be declared with constants, Use let to declare objects, ![微信图片_20231128171807](https://private-user-images.githubusercontent.com/13250516/286197852-2e74241e-8edc-4b21-a38a-7072f40a49af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzAwMDQsIm5iZiI6MTcxMDgyOTcwNCwicGF0aCI6Ii8xMzI1MDUxNi8yODYxOTc4NTItMmU3NDI0MWUtOGVkYy00YjIxLWEzOGEtNzA3MmY0MGE0OWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMWQxYjAyMDEyMzVlMDcyYTk0N2M0YzRlNjAyZjQwZDRiMTMyNDFjNDI2OWJmYzU0ODlmZDViZmQ3Yzk2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3ZR7xS6F3iLML7aJ9SwMWkdhTYkslE7vKgmc4GBqPU)

how you solve this problem,i encounter same prolem.

**Comment by 2496772010** [comment]
> > > Hi @swanghao,
> > > Would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!
> > 
> > 
> > The issue has been resolved，The following code cannot be declared with constants, Use let to declare objects, ![微信图片_20231128171807](https://private-user-images.githubusercontent.com/13250516/286197852-2e74241e-8edc-4b21-a38a-7072f40a49af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzAwMDQsIm5iZiI6MTcxMDgyOTcwNCwicGF0aCI6Ii8xMzI1MDUxNi8yODYxOTc4NTItMmU3NDI0MWUtOGVkYy00YjIxLWEzOGEtNzA3MmY0MGE0OWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMWQxYjAyMDEyMzVlMDcyYTk0N2M0YzRlNjAyZjQwZDRiMTMyNDFjNDI2OWJmYzU0ODlmZDViZmQ3Yzk2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3ZR7xS6F3iLML7aJ9SwMWkdhTYkslE7vKgmc4GBqPU)
> 
> how you solve this problem,i encounter same prolem.

My version is "1.75"
