### ISSUE TITLE
3D Tiles 1.1 Sandcastle Example Cleanup

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#11668]
3D Tiles 1.1 brought additional capabilities to 3D Tiles, including further metadata support and implicit tiling support. 

We used to refer to what became 3D Tiles 1.1 as "3D Tiles Next", and have several Sandcastle examples illustrating the above capabilities. At this point, all references to "3D Tiles Next"  should be "3D Tiles 1.1" and the Sandcastle category should either be renamed or incorporated into the 3D Tiles tab. I'm personally a fan of the later to keep things simple.

The tilesets used in the 3D Tiles Next sandcastles are also out of date and should be updated to 3D Tiles 1.1. These should be uploaded to the CesiumJS ion account.

Potentially, we should upgrade 1.0 tilesets to 3D Tiles 1.1. Now that https://github.com/CesiumGS/3d-tiles-tools/pull/41 is merged we can upgrade many tilesets to 3D Tiles 1.1 with i3dm and cmpt support planned for future PRs.

**Comment by javagl** [comment]
> we can upgrade many tilesets to 3D Tiles 1.1 with i3dm and cmpt support planned for future PRs. 

- I3DM should already be covered with https://github.com/CesiumGS/3d-tiles-tools/pull/52 , with one caveat: It (is difficult and) will not work with I3DMs that contain _animated_ GLBs. (Omitting some details: There are configurations of I3DM+(animated)GLB that technically and mathematically cannot be converted into a single GLB with `EXT_mesh_gpu_instancing`...)
- CMPT _could_ be trivial in _some_ cases, but impossible in others. Specifically: When someone is using CMPT in implicit tiling, then this can not always be converted into GLBs, _unless_ the CMPTs have a certain structure (also, some details omitted here).
