### ISSUE TITLE
Wrong conversion of quaternion to axis

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#11665]
The `Quaternion.computeAxis` function seems to be questionable in one case, and wrong in another case. When executing the following
```
const q0 = new Cesium.Quaternion(0,0,0,1);
console.log(Cesium.Quaternion.computeAngle(q0));
console.log(Cesium.Quaternion.computeAxis(q0, new Cesium.Cartesian3()));

const q1 = new Cesium.Quaternion(0,0,0,-1);
console.log(Cesium.Quaternion.computeAngle(q1));
console.log(Cesium.Quaternion.computeAxis(q1, new Cesium.Cartesian3()));
```
then the output will be
```
0
(0, 0, 0)
6.283185307179586
(NaN, NaN, NaN)
```
One _could_ make a case for the first part: The unit quaternion `0,0,0,1` describes "no rotation" - so what is the axis of "no rotation"? It's arbitrary. But I'd be **strongly** in favor to return a "valid" (unit-length!!!) axis there as well. So it should probably be `(1,0,0)`.

(I wonder how many "normalized result is not a number" errors have been caused by this under the hood...)

But the second output cannot be justified: These `NaN`s should not be there. One could argue whether it is a rotation about 0° or about 360°, of course, but `computeAngle` returns 360°, so the rotation axis could just be `(1,0,0)` as well.

Both cases boil down to [this part of the code](https://github.com/CesiumGS/cesium/blob/b9db20e9d56c3b01f56304a51e5440e2b16a5159/packages/engine/Source/Core/Quaternion.js#L680), which currently says
```
  const w = quaternion.w;
  if (Math.abs(w - 1.0) < CesiumMath.EPSILON6) {
    result.x = result.y = result.z = 0;
    return result;
  }
```

If everybody agrees, I could create a PR to change that to
```
  const w = quaternion.w;
  if (Math.abs(w - 1.0) < CesiumMath.EPSILON6 || Math.abs(w + 1.0) < CesiumMath.EPSILON6) {
    result.x = 1;
    result.y = result.z = 0;
    return result;
  }
```
(And update/add the unit tests, which probably do not cover that right now)

Then, the output will be
```
0
(1, 0, 0)
6.283185307179586
(1, 0, 0)
```

---

The following is ... somewhat unrelated, but I noticed this while debugging a bit: 

EDIT: Moved to https://github.com/CesiumGS/cesium/issues/11685

**Comment by javagl** [comment]
Just as an experiment: When doing this in `glm`...
```
import { quat, vec3 } from "gl-matrix";

async function run() {

  const q0 : quat = [0,0,0,1];
  const axis0 : vec3 = [0,0,0];
  const angle0 = quat.getAxisAngle(axis0, q0);
  console.log(angle0);
  console.log(axis0);

  const q1 : quat = [0,0,0,-1];
  const axis1 : vec3 = [0,0,0];
  const angle1 = quat.getAxisAngle(axis1, q1);
  console.log(angle1);
  console.log(axis1);
}

run();
```
then it will print
```
0
[ 1, 0, 0 ]      
6.283185307179586
[ 1, 0, 0 ]      
```

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11684
