### ISSUE TITLE
Cesium3DTileset constructor ignores some dynamicScreenSpaceError options

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#11677]
While setting up performance tests for `dynamicScreenSpaceError` (needed for #4196), I discovered that the parameters I passed into the `Cesium3DTileset` constructor options were doing nothing.

On inspecting the code, the options like `dynamicScreenSpaceErrorFactor` are ignored and just hard-coded as 4. 

The fix is to just make sure the option gets propagated with `defaultValue(option, default)` as usual.

Note that this is distinct from #6143 which is about one of these parameters not propagated correctly in the 3D Tiles Inspector.

**Comment by ptrgags** [comment]
Also such an update would be a good time to improve the documentation for these parameters. see https://github.com/CesiumGS/cesium/issues/4196#issuecomment-1843100677 for some initial thoughts.

**Comment by Saicbmm** [comment]
Yes, I believe the fact that the dynamicScreenSpaceErrorFactor option was hardcoded led to the constructor option not doing anything because it wasn't taking any input.
