### ISSUE TITLE
 Cesium error

### ISSUE THREAD

**Issue by pazman40** [CesiumGS/cesium#11676]
Sandcastle example:

Browser:

Operating System:

getting  Cesium error on 3d flight 24 on firefox as well,opera is fine

**Comment by ggetz** [comment]
I'm closing this issue due to incomplete info. If you believe this is still an issue, please feel free to re-open with a more detailed description. 

For example, please include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue.

Thanks!
