### ISSUE TITLE
Some geometries are not rendering correctly on Chrome on Mac

### ISSUE THREAD

**Issue by jangroeneveld** [CesiumGS/cesium#11671]
Some geometries are not rendering correctly on Chrome on Mac
In our codebase we noticed this with the PolylineGeometry and BoxGeometry, these start not rendering correctly when using a small size.

In the attached sandcastle the box shows completely normal on Chrome for Windows, but on Chrome for Mac it shows as follows:

<img width="589" alt="not a cube" src="https://github.com/CesiumGS/cesium/assets/6150944/929e1df9-8506-4022-93ff-8e66694b4f66">

Sandcastle example: [Sandcastle](https://sandcastle.cesium.com/#c=lZTbUtswEIZfZcdXTgmKaVpmSkymJGToTOlhgOEG50KxN1hTWfLokDQwefdKPgQ30AO5UKTVt6vV/iunUmgDK4ZrVHAKAtcwRc1sQW4rW5gEabWeSmEoE6iSoDdKRCKWVqSGSQGpLEprcMpUyjFUNGNW9+AxEeC2fPRSauZJ7Q64m4/8xlIqCDkaYM4WjdxfDMNjPzk4aHxbbx+QVr5NYl+oyYmRV7U9ZL1Rje+OIaXVeVgboXulKVXGzah4u9sFqBOGN1DFTaUOmxN7/T9Bmokd1DLNpE5m6weFxirxlJbb2frC1de6V4hiIn+6e9XVJyiMA1ETmmVhVQJBCzyBJLjwLCwcvGYmhwWukGPm6qOcHhqoyEBaw506SVAlXUq+8ctbya0P8bhXoZNnFRmSpZLFOfq09JlSdPMJ2X1udHjX3vDwwzsSud/Rri7DYxLtFlFnXqH/wuZtgXVOS5fk3d8VO4zI+z748UmYl8nXgf/BHe6D837boV6Bm41Pv3Xbmchkdju7nJ03bEENKkZ5h+RSkYur2ewr8bqe8TKnYeeURtMTMMri77bKdy/S5PJs+rnCtm7c1q+0bjZd5qjw6QlNpBUZE/fXlb2S/rtkwqnt3V/dG125O2K3UjuhYUiiOqGm2R+kLG5kuNf6Hgn6QazNhuO4FeUjK0qpDFjFQ0IGBouSu2LqwcKmP9CQVOv2GxAPuq5xxlbAstMXvmGQcqq121lazq/Zg3s543jg+GeuXFJfqm8rVJxuPJYfjS9rIyEkHrjly55GSr6gai/yLw)

Browser: Google Chrome Version 119.0.6045.199 (Official Build) (arm64)

Operating System: macOS Sonoma 14.1.1

**Comment by ggetz** [comment]
Thanks @jangroeneveld and @syzdev. I'm closing this and adding this particular report to https://github.com/CesiumGS/cesium/issues/9417.

**Comment by ggetz** [comment]
@jangroeneveld We recently shipped [a workaround for what might be a related issue](https://github.com/CesiumGS/cesium/pull/11788) in version 114. Would you mind confirming if you can still reproduce the error in the latest version of Sandcastle?

**Comment by jangroeneveld** [comment]
The issue seems to be fixed in the latest version of Sandcastle @ggetz

**Comment by ggetz** [comment]
Fantastic, thanks @jangroeneveld!
