### ISSUE TITLE
Bundling with ESBuild problems

### ISSUE THREAD

**Issue by simod** [CesiumGS/cesium#11687]
Dears,

I'm trying to bundle an app with ESBuild but it fails due to missing modules http, https, zlib and url as per following error:

✘ [ERROR] Could not resolve "https"

    node_modules/@cesium/engine/Source/Core/Resource.js:2076:48:

do you have a suggested workaround for it?

Thank you

**Comment by simod** [comment]
@ggetz thanks a lot for the super fast answer.
I tried setting them as external but seems that the app will still be looking for them at runtime.

index.js:13 Uncaught Error: Dynamic require of "http" is not supported

**Comment by ggetz** [comment]
@simod OK. It would help if you could provide your current configuration and build script for context.

**Comment by simod** [comment]
@ggetz Thanks, after more digging I realised that this error comes from geotiff.js. Nevertheless it seems that the difference is that with this config we flag those libraries as external, while with the previous we were disabling them.
The issue is shifter to geotiff this way.


This is my script
"esbuild src/index.js --outdir=public/static --bundle --sourcemap --servedir=public --loader:.js=jsx --external:https --external:http --external:zlib --external:url"

Thanks a lot
