### ISSUE TITLE
The file in the article cannot be downloaded.

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11682]
Sandcastle example: null

Browser: All

Operating System: All

The file in the article cannot be downloaded.
文章中的文件无法下载了

https://cesium.com/learn/ion/stories-introduction/

![image](https://github.com/CesiumGS/cesium/assets/13347321/ff5c0474-4a5e-46f3-8b61-5148c8d945ca)

![image](https://github.com/CesiumGS/cesium/assets/13347321/2c8c361c-e742-426a-a3bf-66728dc8fc97)

**Comment by ggetz** [comment]
Thanks @danchaotaiyang, I've passed on the issue to the relevant issue tracker.

@syzdev If you can let us know which posts have the broken links, we can see about fixing them.

**Comment by ggetz** [comment]
Thanks @syzdev! I've passed on this info to the relevant team.
