### ISSUE TITLE
Inconsistent type assumption for scratch variable

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#11685]
<sup>(I originally mentioned this in https://github.com/CesiumGS/cesium/issues/11665, but should probably be an own issue)</sup>

The [scratchVariable in ModelAnimationChannel](https://github.com/CesiumGS/cesium/blob/b9db20e9d56c3b01f56304a51e5440e2b16a5159/packages/engine/Source/Scene/Model/ModelAnimationChannel.js#L218) is initialized depending on the "path" of the channel: For `"translation"` animations, it is a `Cartesian3`, and for `"rotation"` animations, it is a `Quaternion`. But ... it is a global variable 😬 When initializing multiple channels, then there are cases where this should be a `Quaternion`, but it actually is a `Cartesian3`, meaning that some of the functions are just shoving some `.w` property into that poor `Cartesian3`. It happens to work (hooray to untyped languages), but ... feels wrong. 

Would the preferred way of fixing this be to convert that scratchVariable an instance variable in the `ModelAnimationChannel`?

**Comment by ggetz** [comment]
I think the preferred solution would be to have two scratch variables, one for each type.
