### ISSUE TITLE
Syntax Error in Example

### ISSUE THREAD

**Issue by hammad93** [CesiumGS/cesium#11698]
I was reading the documentation here, https://cesium.com/learn/cesiumjs/ref-doc/ImageryLayer.html#ImageryLayer

And noticed the first example needs a semicolon. `;`

```javascript
// Add an OpenStreetMaps layer
const imageryLayer = new Cesium.ImageryLayer(new Cesium.OpenStreetMapImageryProvider({
  url: "https://tile.openstreetmap.org/"
})),
scene.imageryLayers.add(imageryLayer);
```
Line 4 in above

I also believe that changing it in this line would regenerate the documentation with the right syntax,
https://github.com/CesiumGS/cesium/blob/b9db20e9d56c3b01f56304a51e5440e2b16a5159/packages/engine/Source/Scene/ImageryLayer.js#L145

**Comment by jjspace** [comment]
Thanks @hammad93, good catch! This will be updated soon
