### ISSUE TITLE
Cesium map labels only displaying in English

### ISSUE THREAD

**Issue by ghost** [CesiumGS/cesium#11695]
## The problem
After setting up Cesium, it works perfecty, but I would like to have the maps in Spanish.
I found that I can do that with the `BingMapsImageryProvider` and its member `culture`, so I came up with this.
```javascript
var imageryProvider = new Cesium.BingMapsImageryProvider({
    url: '//dev.virtualearth.net',
    culture: "es-ES",
    mapStyle: Cesium.BingMapsStyle.AERIAL_WITH_LABELS_ON_DEMAND,
});
console.log(imageryProvider);

$scope.map.scene.imageryLayers.removeAll();
$scope.map.scene.imageryLayers.addImageryProvider(imageryProvider, 0);

$scope.$apply();
```

As that console.log outputs, the culture is being saved correctly:
```javascript
Object { _key: "my_key", _resource: {…}, _mapStyle: "AerialWithLabelsOnDemand", _culture: "es-ES", etc...}
```

But, using one of the images as example, the petition url is still in English: [url](https://t2.ssl.ak.dynamic.tiles.virtualearth.net/comp/ch/02?n=z&mkt=en-US&it=A,G,L&og=2359)
(Manually changing them to `es-ES` works, that proves that the Spanish translation works)

Any help or guidance is apreciated.

**Comment by ggetz** [comment]
Thanks @iker-molero. I can reproduce, and seems to be a bug in `BingMapsImageryProvider`.
