### ISSUE TITLE
How to realize that position has height and Entity can be dragged and moved in the air

### ISSUE THREAD

**Issue by sheng930920** [CesiumGS/cesium#11706]
Hello, I am a newbie in Cesium development. I would like to ask how to realize that position has a height and Entity can be dragged and moved in the air. After dragging, the height remains unchanged and only the longitude and latitude of the position are modified.

**Comment by jjhembd** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. Please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

You may want to search existing answers on the Forum. For example, here is [a discussion about clicking and dragging Entities](https://community.cesium.com/t/click-and-drag/2054).

Thanks!
