### ISSUE TITLE
writeTextToCanvas() background longer than rendered text

### ISSUE THREAD

**Issue by AnonymousSausage77** [CesiumGS/cesium#11705]
I am trying to draw text to a label and rotate it. I also want to give the rotated text a background. I found this function:
Cesium.writeTextToCanvas() which does this, except it always appends whitespace to the beginning of the word leaving an ugly 'padding'. In the sandcastle, I have illustrated this behaviour by creating two examples, one with a single character '3' and a longer word, both with this whitespace appended.

![image](https://github.com/CesiumGS/cesium/assets/579118/00d9b09f-5bf3-4a64-871f-0620f573c1aa)
![image](https://github.com/CesiumGS/cesium/assets/579118/3c493918-0d8e-4b9a-9efb-9b804ed7a66e)

What I would expect to happen: I expect that the background (in the sandcastle, rendered as blue) would be the same length as the word that you enter and not any longer/shorter.

Sandcastle example:
https://sandcastle.cesium.com/#c=xZRdb5swFIb/yhE3JRIxEJIpydJoWxZpF50qLbQ3pRcOnASrxka2SZZW+e8zkI8q7aRdTBsIYx/O+9rnsUUqhTawYbhFBdcgcAsz1KwqyH0TcxMnbcYzKQxlAlXidD4mIhGthqAwzDDUhGaZ+5IIgPoppbZRKcZHtxlVxvaoiMhKyeIrrhWi/qwU3X1Dts6Ndh9qYX2F0ZB8CINwFHkA3ahPRr1w1Ot50AvgsfMQPHpt5pJxvpRUZWN4OWpZQdd4mnWrmMEYf5pYzqjYUG3LiRLHO+cDrGxhY0icsF8auLotUcCCCn3lgbavrkbFVlZyFixp+rRWshLZTHKpziXWI/Ll5m5+St53Tl0lDW2J9AdNcG/b/T9BGfTfogz/Bsp4bs9OPF/EF83/JhwGl4Tr2/dhgQZMjpDSAhVtjv2JfhsjK76LZUs/Q22YoH8A3205D70D4+HAg0EQtGuTitmdPdgcsORIMybWJ9vv1OTEyB82apG4Vgl2uXOqjQdCKpN7UJWvnVqbkpk0/51JNwqOcJTkfAwBCRosDRXHcyba7DhOj/w+saK0U0GluEuIb7AoObXF+ssqfUJDUq1rmHXqxH8tnWRsAyy7fudXASmnWtsvq4rzBXvGxJlOfJv/RsplQ+R2g4rTXZ2Wh9ObNkgImfh2+L7SSMmXVF04/wI

Browser: Chrome Version 120.0.6099.109 (Official Build) (arm64)

Operating System: MacOS Ventura 13.4 (22F66)

**Comment by AnonymousSausage77** [comment]
I have just made a breakthrough. 
The font that I was using { font: "14pt 'Open Sans', sans-serif" } has a comma.

By removing the comma between 'Open Sans' and sans-serif, such that the font is: "14pt 'Open Sans' sans-serif", it removes this extra space. How strange.

**Comment by Saicbmm** [comment]
I understand that your writeTextToCanvas() method is faulty. The blue background is too big for your text. Implementing this using HTML and CSS, the label could be created by using the <mark> tag around the text to highlight it. Then, using CSS, style the <mark> to highlight the text in blue. This way, there should not be any extra space in the background. I believe this methodology can be used in your program. 

Thanks

**Comment by ggetz** [comment]
Thanks for the report! I'm marking this as a duplicate of https://github.com/CesiumGS/cesium/issues/9767. We'll likely want to replace `writeTextToCanvas` with the newer, built-in version.

**Comment by donmccurdy** [comment]
Fix in progress:

- #13081
