### ISSUE TITLE
Where did some of the articles in "Tile 3D Content with Cesium" ?

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11703]
![微信图片_20231219000342](https://github.com/CesiumGS/cesium/assets/13347321/52694eda-7f1b-410d-a677-3ec6b5dae3dc)

**Comment by ggetz** [comment]
Hi there,

The documentation is still available at https://cesium.com/on-prem/ for the time being.

We'd encourage you to learn about [Cesium ion self-hosted](https://cesium.com/blog/2023/12/14/new-cesium-ion-self-hosted/), as we think it will ultimately include the cli tilers functionality.

**Comment by danchaotaiyang** [comment]
Yes, I finally saw them again, but I couldn't find the entrance on https://cesium.com/, and "Cesium 3D Tiling Pipeline Reality Tiler" and "Recommended Minimum System Requirements" are missing in https://cesium.com/on-prem/

The response from the Cesium team is that currently they do not have any sales partners in China. This means that Cesium-ion-3D-Tiling-Pipeline cannot be used in China. Many people, including myself, are not aware of alternative tools, and I personally am not comfortable with or trust third-party tools. Therefore, I hope that the Cesium team can establish sales channels in China as soon as possible.
