### ISSUE TITLE
Cesium.UrlTemplateImageryProvider unable to set - maps stays blue

### ISSUE THREAD

**Issue by volski** [CesiumGS/cesium#11702]
Sandcastle example: https://sandcastle.cesium.com/#c=bZBPa8MwDMW/iskpg2J3G9shS8ugp0Fhhf05+aImamom28F20qal331xNlib1eCDnn56PEmawhofmNJQoetWzraqRMdmzOCOLdCrRvMPR++oa4KAL5dcepSGscZRxmSyDaHOhCBbAG2tD9n948NUQK2EhtoL5R0giePhJI77/ncnXptKJpNooZVRutFLbLH3mk6Yhv2ZcDeNlDSnmydp5JDZEnKyVTpK/gcE1ircjXf5HLRUJsVQL6wJoAy6Pgcblhn5ZWNhiLsGj0vo0K1U8RWhDZDHoVWhLWx5rg2hk0mS+9ARziMU37PStXUhXi/lXITfC3uxbnrPwAvv42BEc3E+mpeqZaqcXdmBFQTe951NQ/SmDiiTeS56/t8oWSiVqV5bdARdxLa38+WPyDnPRV9enwzW0hrcyPkb

have update out version from "cesium": "1.100.0" to "1.112.0"
since the unable to set the imageryProvider: new Cesium.UrlTemplateImageryProvider({
        url: this.getMapURL(),
        minimumLevel: 0, maximumLevel: 20,
      }),

**Comment by ggetz** [comment]
In version 1.107, [Viewer constructor option options.imageryProvider has been deprecated in CesiumJS 1.104. It will be removed in 1.107. Use options.baseLayer instead.
](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#1107---2023-07-03)
