### ISSUE TITLE
`KHR_texture_transform` is not applied to property textures

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#11708]
The texture coordinate transformation that is defined with the [`KHR_texture_transform`](https://github.com/KhronosGroup/gltf/tree/main/extensions/2.0/Khronos/KHR_texture_transform) extension is applied to "visible" textures (like the base color texture). But is is apparently not applied to [Property Textures in `EXT_structural_metadata`](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_structural_metadata#property-textures).

The following is an archive with everything that is necessary to reproduce the issue:

[propertyTextureTransformTest-2023-12-19.zip](https://github.com/CesiumGS/cesium/files/13718858/propertyTextureTransformTest-2023-12-19.zip)

It contains

- A glTF asset that only contains a unit square. It uses the **same** texture for the base color and for a Property Texture: The texture just contains 8x8 pixels with increasing 'red' component values (so the base color will be black ... red, and the property values in the property texture will be in [0 ... 64)*3. It uses the _same_ texture transform for both usages of the texture, namely with an offset of [0.25, 0.25], and a scale of [0.5, 0.5]. 
- The JSON part of that GLB (for reference and convenience)
- A tileset JSON that refers to that GLB
- A sandcastle for testing

Switching between the "Default Shading" and the "Property Values" (which just renders the property texture values as a 'brighness' value with a custom shader) gives this result:

![Cesium Property Texture Transform Issue](https://github.com/CesiumGS/cesium/assets/5597569/d8fd4226-f973-4735-b9ab-e498fd56a826)

Showing that the texture transform is only applied in one case, but not the other.

**NOTE**: As part of fixing this, it should also be reviewed whether the texture transform is applied to [Feature ID Textures in `EXT_mesh_features`](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features#feature-id-by-texture-coordinates). I have not tested this yet, but assume that these will also not be affected by the texture transform (in doubt, I can create a similar test example if necessary).

**Comment by ptrgags** [comment]
@javagl indeed, `KHR_texture_transform` was only implemented for the material textures. It was not implemented for property textures (until your PR) nor for feature ID textures.

This is the first time I've seen these extensions used together, I think it's a fine addition if it's useful.

**Comment by javagl** [comment]
I would have seen this as ~"in the same category" (and there's the **NOTE** at the bottom of the first message here), and also assumed that it would be fixed ~"roughly the same way" (in fact, I'm digging into this right now). If you think that the note is not enough (or if it turns out that it has to be solved differently), I can open another issue.

**Comment by ptrgags** [comment]
@javagl My comment was just to keep the scope of each issue small. Indeed, feature ID textures will have a similar implementation, but I think it makes sense to do that as a separate PR.

**Comment by javagl** [comment]
I support this intention (and am aware that I tend to sneak "too much" into a single PR...). 

I opened https://github.com/CesiumGS/cesium/issues/11731 . 

From a quick look, it _seems_ like it could be solved in a similar way. But for _both_ issues, I still have to figure out a good way of _testing_ it. There actually already _is_ a [transform in the `PropertyTexturePropertySpec`](https://github.com/CesiumGS/cesium/blob/9f43e81832fd90a4d3e6b67f6b168b6131bf7ce6/packages/engine/Specs/Scene/PropertyTexturePropertySpec.js#L49), but it only checks whether this transform is 'there' - and not whether it is "applied" to the texture coordinates...

**Comment by ptrgags** [comment]
>I still have to figure out a good way of _testing_ it. 

I left some ideas for testing here: https://github.com/CesiumGS/cesium/pull/11709#discussion_r1440531224

**Comment by javagl** [comment]
Should be fixed by https://github.com/CesiumGS/cesium/pull/11709
