### ISSUE TITLE
I occur a wrong with visual effect  when I use polygon api + perPositionHeight to render a graphic

### ISSUE THREAD

**Issue by kmq116** [CesiumGS/cesium#11711]
This is my [sandcastle](https://sandcastle.cesium.com/index.html#c=bZNrb9sgFIb/CsqnVMoIGHNL02hZ9mHSqq3SpknTvA/UoTEahgiTVGnV/z58ieZmFZYFh/O8h8tL6V0TwdHoRx3ADXD6EWx0Yw41/NHFpsWk7MYb76IyTodicnVduMKVHVmelLvz9rTzLuG9DtQummh0A9V2O30uHABO1XoBiskmpYOjDtGUyoL9AD6aWIG9Du/2vklgilTa7KrYAOW2wB+iTYWLyaxVGpgF6HQBqIwOKpTVaXFe+EaFmHrKEfgQfP1R74LWzToEdfrUy05/9SzAmEPEiBAiy3OeZVlXgkiIpJSIE5YTwlIUoG6iT88zxFmOKcIIj/MJx0gQToWYAfoKyDlqC+SM8jFAM8mxoILhARghXHDGGKI4o2OEs9QQp4TMAEavigie0xxLTuSYSAWkSCoCiTMxYihFiOQiFzgfM12IUSkIu9xKxiUWjHApx0DO0kfSSdKL/LQYyYVkCMnx1nkmhEzyVPDz2QLw+2roJCfcDUboL2wBYjjoYbZWUQej7L/79tYHuPm5/gJbI63tvlJTBOlZbvDPK5Eh1qEXQh9u15vPXdpL+r/0Zm/bYO4n7+vvfjoy/tU1mMwmyyaerF4NzgLvTb33IYJDsFMI51HXe5tW3szvD+UfHWHZNK10m7qcj9Hl1hyB2d688fBAaVXTpJmHg7XfzFN6E6vlPOX/h1qvtsbtvqanZtWpTavw6rYPQgiX8zR8m4ze23sVLpT/Ag)
I expect to draw a folded polygon, like this
![image](https://github.com/CesiumGS/cesium/assets/59247607/cb90eb4a-ceb7-47dd-80e5-0a992cce1e74)
actual rendering effect
![image](https://github.com/CesiumGS/cesium/assets/59247607/efd7787d-0887-4441-b5b8-cc8ff303ee6c)
everything looks fine， but when I look at it from the side, it looks like it's blocked by something or has the wrong latitude and longitude connections.
![image](https://github.com/CesiumGS/cesium/assets/59247607/b1ccf7e8-eaf6-4162-abf4-79c70422cd4f)
I want to know why this is or how to solve this display effect.
Thanks to all the people.

**Comment by GatorScott** [comment]
This looks like a misuse of [PolygonGraphics](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html) which renders a polygon which "conforms to the curvature of the globe and can be placed on the surface or at altitude and can optionally be extruded into a volume.".  A glTF model may be better for this use case, if I understand correctly.

**Comment by ggetz** [comment]
Hi there,

It looks like the polygon is being triangulated as expected.

As @GatorScott said, this is not really the intended use case of PolygonGraphics.

I would suggest taking this question to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

I'm closing as this is not strictly a bug. Thanks!
