### ISSUE TITLE
Double click generates click

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1171]
The following code generates both events when a user double clicks.

``` javascript
handler.setInputAction(
    function () {},
    Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK
);
handler.setInputAction(
    function () {},
    Cesium.ScreenSpaceEventType.LEFT_CLICK
);
```

This makes it hard to assign different tasks to click and double click.  I don't think this is common in UI frameworks.

**Comment by DoisKoh** [comment]
🤕
