### ISSUE TITLE
请问这是出现了什么问题在3dtiles上面画的多边形

### ISSUE THREAD

**Issue by fdwszd123** [CesiumGS/cesium#11713]
### Verification

- [X] Yes
- 请问这是什么问题？我在3dtiles上面绘制的多边形，在有些角度看起来是正常的，而某些角度它出现了两层，我怀疑是地形高程比模型的高度高的问题
![Snipaste_2023-12-21_18-28-59](https://github.com/CesiumGS/cesium/assets/81911797/721d97e2-aabb-4aa7-9001-26d41c23f272)
![Snipaste_2023-12-21_18-29-15](https://github.com/CesiumGS/cesium/assets/81911797/5147dbf2-65b3-479f-84d7-8238aeef8098)

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
