### ISSUE TITLE
Inheriting WebMapServiceImageryProvider class for the layers to add set method.  The reload method does not take effect  How to refresh  thank you.    cesium version:1.112.0

### ISSUE THREAD

**Issue by Ewithome** [CesiumGS/cesium#11724]
### Verification

- [X] Yes

**Comment by Ewithome** [comment]
Inheriting WebMapServiceImageryProvider class for the layers to add set method.
The reload method does not take effect
How to refresh
thank you.
cesium version:1.112.0

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by Ewithome** [comment]
感谢您的来信！查收后我会第一时间给您答复！如果是重要资料，请给我电话或短信通知下！ 张益明   ：  13312914526
