### ISSUE TITLE
Cesium.js:1 Uncaught TypeError: Cannot set properties of undefined (setting ‘dayNumber’)

### ISSUE THREAD

**Issue by FS0729** [CesiumGS/cesium#11723]
### What happened?

It should return me **JulianDate**

### Reproduction steps

let time = Cesium.JulianDate.addSeconds(Cesium.JulianDate.now( ), 10 );

### Sandcastle example
`Cesium.js:94 Uncaught TypeError: Cannot set properties of undefined (setting 'dayNumber')
    at Ip (Cesium.js:94:14495)
    at Tt.addSeconds (Cesium.js:94:19719)
    at index.html:39:38`

### Environment

Browser:
CesiumJS Version: 1.99
Operating System: windows 11

**Comment by Leosunshine** [comment]
the third parameter of Cesium.JulianDate.addSeconds is required and should be a valid JulianDate. Did you just commented the parameter check as follows:
if (!defined(result)) {
    throw new DeveloperError("result is required.");
  }
Just create a JulianDate object and put it as the third parameter as:
let time = new Cesium.JulianDate();
time = Cesium.JulianDate.addSeconds(Cesium.JulianDate.now(), 10, time);

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
