### ISSUE TITLE
How to solve it

### ISSUE THREAD

**Issue by gaxz1** [CesiumGS/cesium#11726]
### Feature

May I ask how to remove the GLB or GLTF model and change its own brightness based on the current time of the sun? Also, can we fix the top or bottom circle in the middle and change it to follow the mouse, like Google Earth

**Comment by ggetz** [comment]
Hi @gaxz1.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
