### ISSUE TITLE
Support custom ellipsoids in Cesium3DTile bounding volume calculations

### ISSUE THREAD

**Issue by jjhembd** [CesiumGS/cesium#11720]
### Feature

Bounding volume calculations in `Cesium3DTile` currently assume the default WGS84 ellipsoid. These should instead use the ellipsoid associated with the `Globe` or `frameState.mapProjection` in case the user has specified a custom ellipsoid.

For tiles with `region` type bounding volumes, the custom ellipsoid will need to be made available to the `Cesium3DTile` constructor, which currently does not have access to `frameState`.

**Comment by javagl** [comment]
Maybe someone can quickly confirm whether this is obsolete with the recent generalizations from https://github.com/CesiumGS/cesium/pull/12000 - I _think_ that most places that assumed WGS84 should have changed to use the one that was configured to be the "default" one, right?
