### ISSUE TITLE
I noticed that when cesium rotates the Earth with the ctrl key and the left mouse button, it rotates at the center of the screen at the lower level, but at the higher level it rotates at the position of the first mouse click. Why is there such a difference? So that I now want to get the axis position of the Earth as it rotates but I don't know how to do that

### ISSUE THREAD

**Issue by 1692341334** [CesiumGS/cesium#11752]
### Verification

- [X] Yes

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
