### ISSUE TITLE
cesium loading primitive scene stuck

### ISSUE THREAD

**Issue by lpc-g** [CesiumGS/cesium#11755]
### Verification

- [X] Yes

**Comment by lpc-g** [comment]
Is there any situation where the primitive is loaded and the scene is stuck? I loaded 5000+ primitive post map elements here, the scene is stuck, but if the loading 700 is normal rendering, and no stuck is still very smooth, want to know whether this is caused by my computer GPU?

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
