### ISSUE TITLE
Alpha blending result abnormal

### ISSUE THREAD

**Issue by syzdev** [CesiumGS/cesium#11756]
### What happened?

Disable order independent translucency:
```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  orderIndependentTranslucency: false
});
```

When the model changes from opaque to translucent, the results appear abnormal, but when the model becomes more and more transparent, the results are normal.

![s](https://github.com/CesiumGS/cesium/assets/25605081/dea0806f-9cd9-4a4c-a530-538c8582860f)

### Reproduction steps

In the sandcastle example below, change the value of `Alpha` to `0.99`.

### Sandcastle example

[Reproduction sandcastle example](https://sandcastle.cesium.com/#c=tVfrb9s2EP9XiHyRBKiynUe7uYqxvLYEaJauefRDUxS0dLYIU6RAUk68If/7jpRsS7LTZljjDw6PvrvfvXkhpPrMqSJzBg+gyCER8EBOQLMyj+7cne8ljjyRwlAmQHkh+edekNVHqhTUhUihAPwS5kZRoXmZgEgWQzKhXEO45n8K7sWaqmAjjcwQTbkcQwSCjjl8YNPMMDFFi4wq4RkJPVscy8dIZ/IBGR3U85xHJpe6yEDBiwRK8RK2XMoX8VW+WcY/lCxFujbmxYJrxgYrpg5DzsyieTspRWKYFGQK5kRyqfzEfv9JcwgJ5UVGg3YKrRrHghh18p3cl5VcZORtUYA6oRr84GtTWIEplWjJRRMl8yMLVCGHpKBKw+9cUuNXBgSNkmja3uuRmwxcDC5lChzTT5OZJgYvtaEGiJwQWSqSM8EILQrOEmqdjdpRWSs4bPvq4IdkEPXD503AYp+DMg51rSmHfAxKEyaMJDMhk5ksDZFjDWpui1Y3bKjDseSKnBv+SlfQATxmIu2gIYa9OL26JMAhxzRr67u9u73AP9SQhHJOJpg2ZjruGyn5mNp8pjIprXCExXBW6TleXKS+V7N4wfNG2/AurGnYiXptfLhU3/KiK4x4V6vQNIU9lwIvwB4b60SxMfirivVx/txRXkKnQqsix3ZDDdGyVFfl7X0+v7g5w8G0kn5u4KyAEgVYTM4iv1RoVQZ25HQbo2pFh84wvwpyOYcjzv2W1irmhdTM6V43EVUGT1TsuY44hakC0P6bwe5e1H+3v/928GtI9vej/kF/713/7cqIruYMaFoNw1rxJTUZtuQnvMZh6w/2DjZkCmaSDCX63R+U5HzbfVZ05v95hfrRKvqEQn5tRljpDp2mDVypGIaLtgPh3gQs1FxHWUfrXyXmQQlk95cBDK0tnQBXBYAauymhaeq3ckaIwIE1JDar7ful/uHq1GFo2D5sEh02V4VD0kEliMi2wRI3q/Iy/8gegV+zv9G4we4vm1z00XJdY1cjx24fPx2epxb9FGwpVTdnID1bhmv5OmyddC5fhfVQI+uXprqOcwYezZB4l4zPyI0qk5nXDZ3QOKUSZFr3crAZombbeVHUu6Z5weGUGtpzUdW9qmIskMPp0vggjrHR+8F3IxP+2JUjphJFJ+aVHUGY+vQNj7X1B5ja6P+7UK0S5A4ylnB4NUcqmBqlTf20bJxLQzA+5BhfNFypXjkpNUqbqn0Z/JzcXM+YEJCSk4xiRxq7Nr9uw9ClO9/w+J/z8rU5Fq6pSBOqDeYXp+tN9dZfgij9elgEO+FOrM2Cw2gp9RvLC4kbE44/H800gGai4bo3xqYFEyVaB+8r5rjXFI1TNicsPbzf6fyfcb9DEk61xl8mJXdz835nFPeQf0MUF0v7qFzh0sbpwrJlg9GH6jKKoriH5HbJepNBkaUnsbELy2gdjtiMZboYNUMXGzVqhzY26chtvHEPT5u/dfMaM1Hg8mgWBaAV+DxO0Tv7UCCF9WfP9BHPA3fWBorqhwFSKWb/zRjXMrya23VnWG21IXHUbYEMeOc5CA8Fej+AtzVrUTDESB18B2KLsg2H8aIZHSRb8UO6EeBmVv4F)

### Environment

Browser: The latest version of Chrome
CesiumJS Version: 1.113
Operating System: Windows 11

**Comment by ggetz** [comment]
Thanks for the report @syzdev! I believe this issue is already captured in https://github.com/CesiumGS/cesium/issues/5698.

I'll add your report there, and close this issue to keep discussion in one place.
