### ISSUE TITLE
How to manage zIndex of entities and primitives which are clampToGround?

### ISSUE THREAD

**Issue by s3xysteak** [CesiumGS/cesium#11757]
### Verification

- [X] Yes

**Comment by s3xysteak** [comment]
refer to [community](https://community.cesium.com/t/how-to-manage-zindex-of-entities-and-primitives-which-is-clamptoground/28914/1)

When I use GeoJsonDataSource with `{ clampToGround: true }` and `GroundPrimitive` both, how could I manage the `zIndex` of them?

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
