### ISSUE TITLE
Rendering stops with "TypeError: Cannot read properties of undefined (reading 'rectangles')" or "TypeError: node is undefined"

### ISSUE THREAD

**Issue by ethanchristensen01** [CesiumGS/cesium#11769]
### What happened?

Cesium sometimes unexpectedly crashes with this message when I pan the map or zoom with my mouse. It started when I tried migrating my project from vue 2 + webpack to vue 3 + vite.

Firefox stack trace:
```
An error occurred while rendering.  Rendering has stopped.
TypeError: node is undefined
    findMaxLevelFromNode@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173294:24
    findMaxLevelFromNode@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173259:11
    TileAvailability.prototype.computeMaximumLevelAtPosition@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173054:10
    TileAvailability.prototype.isTileAvailable@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173111:15
    CesiumTerrainProvider.prototype.getTileDataAvailable@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:176157:26
    GlobeSurfaceTileProvider.prototype.canRefine@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:206614:47
    visitTile2@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:209462:20
    visitIfVisible@http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:209729:12
    visitVisibleChildrenNearToFar@…
```

Chrome stack trace:
```
An error occurred while rendering.  Rendering has stopped.
TypeError: Cannot read properties of undefined (reading 'rectangles')
TypeError: Cannot read properties of undefined (reading 'rectangles')
    at findMaxLevelFromNode (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173294:29)
    at findMaxLevelFromNode (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173259:11)
    at TileAvailability.computeMaximumLevelAtPosition (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173054:10)
    at TileAvailability.isTileAvailable (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:173111:15)
    at CesiumTerrainProvider.getTileDataAvailable (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:176157:26)
    at prepareNewTile (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:197834:35)
    at GlobeSurfaceTile.initialize (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:197669:5)
    at GlobeSurfaceTile.processStateMachine (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:197674:20)
    at GlobeSurfaceTileProvider.loadTile (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:206444:28)
    at processSinglePriorityLoadQueue (http://localhost:8080/node_modules/.vite/deps/cesium.js?v=a0fc6289:209851:18)
```

### Reproduction steps

This bug is difficult to reproduce. It might be something I'm doing wrong with my codebase, but it's a little too big to pinpoint what exactly it could be right now. I do know we call `sampleTerrainMostDetailed` quite a bit.

The relevant section of the cesium source code is here. https://github.com/CesiumGS/cesium/blob/9cf4839488409b5fd557905b83db4f4ba237b26f/packages/engine/Source/Core/TileAvailability.js#L446-L463

It looks like it's trying to traverse up a tree via `node.parent` while `node !== stopNode` (i.e. until `node === stopNode`), but it never checks if `node` is undefined. If `node` is undefined, that *most likely* means we already reached the root node. But why are we reaching the root node before `stopNode`?

Does that mean the program is in a broken state? If so, there should be a specific error message explaining how the invariants have been invalidated and what might have caused it.

Is `node !== stopNode` the right comparison? We're comparing references here, not the contents of the object. If this is the problem, maybe we should implement a `Node.isEquals` method or something.

If the comparison is correct and the state is valid, maybe a simple undefined check would fix this.

### Environment

Browser: Chrome 120.0.6099.217 and Firefox 121.0.1
CesiumJS Version: 1.106.1 and 1.112.0
Operating System: Windows 10
Dev Server: Vite 5.0.6

**Comment by ethanchristensen01** [comment]
For what it's worth, this bug seems to happen primarily with the Cesium World Terrain. When I use locally hosted terrain, this doesn't happen even if I get the occasional 404 error for a terrain tile at a certain level.

**Comment by ggetz** [comment]
@ethanchristensen01 Could you please provide your build configuration from before and after?

@jjspace Can you please take a look at this given that it seems to arise when switching from webpack to vite?

**Comment by ethanchristensen01** [comment]
@ggetz @jjspace [Here is a gist containing the old and new config files](https://gist.github.com/ethanchristensen01)/56c63bf26220b4b5a417ebddc0971b42

At some point, we tried using [vite-plugin-cesium](https://github.com/nshen/vite-plugin-cesium) instead of [vite-plugin-static-copy](https://github.com/sapphi-red/vite-plugin-static-copy), but this error was still occurring.

**Comment by ethanchristensen01** [comment]
I've updated the gist I shared earlier to include a file which creates the viewer like how I'm doing it. It's an unusual way of doing it, so that might be worth checking out.

**Comment by ethanchristensen01** [comment]
@ggetz I've updated the vite config to reflect the recommended configuration, thank you for the pointer there. Changing that didn't seem to fix the bug.

I did some more testing and found that having a lot of billboard entities (pins) in one location made the error happen more consistently. Switching from a secondary terrain provider to Ion will usually trigger the error.

These pins are supposed to be clamped to the ground. Their positions also get updated every few seconds, during which we might be getting the altitude of the terrain at the new position with sampleTerrainMostDetailed.

Tomorrow, I will test more with our old build to see if I can consistently break it there, too.

**Comment by jjspace** [comment]
@ethanchristensen01 Sorry updating the config didn't work. It sounds like this is possibly not be a vite/build issue? If you can consistently reproduce it in your project are you able to recreate it in a minimal [Sandcastle example](https://sandcastle.cesium.com/)?

**Comment by ethanchristensen01** [comment]
@jjspace I've been troubleshooting this when I've had the time to.

I narrowed down a single function where the error would consistently happen. This function accepts a `viewer` parameter and a second parameter, extracts `coordinates` from the second parameter, and calls `sampleTerrainMostDetailed(viewer.terrainProvider, coordinates)`. It runs about 4 times per second.

After trying almost everything I could think of, I tried logging out `viewer` in this function. It logged a `Viewer` wrapped with an es6 `Proxy`. Vue 3 wraps components' data members with `Proxy` to handle reactivity, so this was a sign that my function was getting called with a viewer instance defined in a Vue component. Unwrapping it with Vue's `toRaw` function fixed my error.

HYPOTHESIS: Calling `sampleTerrainMostDetailed` using a viewer wrapped with a reactive `Proxy` (i.e. Vue 3 `reactive`) can cause problems if the terrain updates while sampling the terrain. This is more likely to happen if the terrain is hosted remotely, as the terrain might not load as fast. Defining a viewer/a reference to a viewer in a Vue component should be avoided.

Unfortunately it's a little hard to set this up in Sandcastle.

**Comment by jjspace** [comment]
@ethanchristensen01 I'm definitely glad you found a solution to the issue! That said it sounds like this is an issue outside of Cesium itself and, as you said, I'm not sure we can do much about it. 

> Vue 3 wraps components' data members with `Proxy` to handle reactivity, so this was a sign that my function was getting called with a viewer instance defined in a Vue component. Unwrapping it with Vue's `toRaw` function fixed my error.

This is really helpful to know and we'll definitely keep it in mind if we see more people with similar issues. Thanks for sharing your investigations!

I'm going to close this for now as there's no further action at this time. If we see this reported often we may add some documentation somewhere but that can be assessed in the future.
