### ISSUE TITLE
Polyline  depthFailMaterial not working on dynamic Polyline 

### ISSUE THREAD

**Issue by GISALLNERD** [CesiumGS/cesium#11761]
### What happened?

Polyline depthFailMaterial not working on dynamic Polyline 

please find sandcastle below

### Sandcastle example

https://sandcastle.cesium.com/#c=7VVdb9owFP0rFk9BSk1MCIGUojH68VA6KtZtmkY1mcQQq06MbAeUVvz32STpgHVbN63THpYoH/fm3HuPfY/jkKdSgRUlayLACUjJGgyJpFkC32991rQWbu0hTxWmKRHTWv14mhZnuI2O8hQnNPy8YHxN08VIo3SqIickqaKKEglxFFkP0xQADSYBmNYuCjiYsYwAZoJ4ClRMgMzEHIdkWrMNfMlZbr4GYBttHFJn1JWDXbpDzNgMh3fXgi+JULll1U/6D4KoTKRfMULpN5y6cC54ckoWghA5EALn1qcj37OB69vgCDW3b7f1440N5phJUreL0msaqTgAyCntBCsiKGZ7TK5LwmZ8VyXgkVU5BgDMZF1zPUMBcGDTrtwKa1zp9x69IWdcO6phGAsOx5M356Pxh7PJ69G7sxK6qZhGZKnic0zZ1b9H0Tw32toUQipEJBVW+xpCf0lEzxNH0wYtz4jD1feWc/tfEi8uCdO0hW7nd2VQiUD3TRn+O83WcUHJOqZEYBHG+fNaXbGvjiOEfOi6ju/5nRbyuy0P2YeYVhcihLpuV18d12119gEH+N+p4LZh23X9Nup0un6z2fXbv1aig6Dnt33HMRkcB3l/uMIzCrz8JP2kwo+sx/W8u4L3lHs6mFxeTAYfbSPQmNBFrALQdMxRhoaMS3LDl0GxaRg5G2yp6VLD95wnN9w6ULSB1OxaT6qckX7F5BVNllwokAlmQdhQJFkyTU42Zll4RxQM5TbQQHuN3dBeRFeARidPbN6aJZZSf5lnjL2l9/oP2e81NP6bUMZxpH+t4xURDOcGFqP+qHBCCHsNbT4dqTjXe7E4yPwF

### Environment

Browser: chrome / firefox
CesiumJS Version: 1.113
Operating System: Windows

**Comment by ggetz** [comment]
Hi @GISALLNERD, thanks for the report!

I believe this is a duplicate with https://github.com/CesiumGS/cesium/issues/5333. I'm going ot close this issue and add your report there to keep conversation in one place.
