### ISSUE TITLE
Error displaying when apply water material to polygon

### ISSUE THREAD

**Issue by qmhc** [CesiumGS/cesium#11770]
### What happened?

![image](https://github.com/CesiumGS/cesium/assets/40221744/18d7b631-5e02-42f4-b9d9-bfe93194d00a)

It seems to work well until v1.108 (not sure).

Maybe a duplicate of https://github.com/CesiumGS/cesium/issues/11575.

### Reproduction steps

Just see the sandcastle below, no need to do anything.

### Sandcastle example

https://sandcastle.cesium.com/#c=lVRdb9owFP0rVp6ChJzQCgkyiobYVFUaWyfo9rDswcQ34M2xPX9As4r/PichKbA+tC+Jfe85916fHCeTwli0Y7AHjW6QgD2ag2GuwN/qWJgGWb2fS2EJE6DToPcuFanIaqaShlnml578IxWoZc+Jtn5FxDXOtSw+wEYDmHAwGOLxqI+urvB43EcxHvX6r2SNj6zhG2nDhjd6G210xkrFz5MzF8SCZoSf67U4RsOnqkVO1pplCao3CNlSQXKJxN+rxcqn+g3KCZZLXZiOhtCaGKhhc8ml7krUOzz7+jDDe2a3M662JIzxda/fEoUvRPiCqI6zdozThaSOw4PmYQtEKA1mxoA10QoerdNgon3V8XNdweBfapMGLfq5Qa7hjwORlQkaxHHcxYlgXiBviaUCoInXLx48JwvFmXUUKlIXNQoyx4m+ExaE95MvOWxyh+rlH4dTz9XTnYt/r1nhfbiDRn2zlfsEWe0aZTcgC7C6vPNsIryfk1Pu7UU2PIrfsjoB7yUvN1K0+No0963/w6eTu3Do1XM3YhGlgOiq8lnbj5wzZSSjS6dzksGsg7UDtD476kTWcge3WjpBm7M1PTpxmkuMTQYCsGoFMZhQGtaSncEyUoAmOOflSjYNKRjLRP3pklddkfZmVW/vgOa01Oljifg4WdAPJsaWHKbt937PCiW1Rc7bEOPIgneFH9BEa5f9BoszYypiBZ1Ep9QJZTvE6M0LPyWUcWKMz+SO8yX7C2kwnUQe/x+VS0KZ2HzZgeakrGDbwfRTE8QYTyK/fZlppeRroi8q/wM

### Environment

Browser: Chrome latest
CesiumJS Version: latest
Operating System: Windows 10

**Comment by qmhc** [comment]
Here is the rendered result in v1.108:

![image](https://github.com/CesiumGS/cesium/assets/40221744/b05d2a7f-6c5d-47ec-b1a6-019d760c19e1)

**Comment by ggetz** [comment]
Thanks @syzdev! @qmhc conversation will continue in #11767.
