### ISSUE TITLE
The result point  of function cartesianToCanvasCoordinates may be on the far side of globe

### ISSUE THREAD

**Issue by polluxll** [CesiumGS/cesium#11799]
### What happened?

let position = Cesium.Cartesian3.fromDegrees(lon,lat);
let screenPoint = scene.cartesianToCanvasCoordinates(position);
The ray passing through the Globe will have two intersections, the screenPoint is one of them on the front of Globe, but somtimes the screenPoint on the far side of Globe,

### Reproduction steps

1.Take some longitude and latitude coordinate points on the front of the Globe
2. Use cartesianToCanvasCoordinates function to convert screenPoints
3.Add screenPoints in screen.
...

### Environment

Browser: chrome
CesiumJS Version: 1.111
Operating System:Windows11

**Comment by ggetz** [comment]
Thanks for the report @polluxll.

I think we may need a bit more information to diagnose what is going on.

Can you describe the values that are getting unexpected results? Including a [sandcastle example](https://sandcastle.cesium.com/) may be helpful for troubleshooting.

**Comment by polluxll** [comment]
sample: https://sandcastle.cesium.com/#c=bVLBauMwEP2VwScFjOy09JI6oeAt3cPSlnbZky+qPInFKhojyUmzS/+9khOBk1ZgM/PevNHwRpKM87BTuEcLSzC4hxqdGrb8z4ixJpNjXpPxQhm0TTa7bYxGDz055RWZoDtpamF9iIS55mtL2x+4sYiOzcsyh+sy6dB45Q/nt92PGPvfGDid1H2RgnzKKeMXE/lzBB6s6DslHTCY9InHdbSHBXg7YH7O9Ood9av6h7CYlxdch2rT+Rdco0UjQwWk636eM/zx6fH+QixJk42SyZT1iDG4urmB/PQvwzeH2UT9AbNj8hENi8FxPXz0TaHjom3Z0cRkqZPBzlOZk2iQy7SK31QLsxOuJrKtMiKgLFka5TK8ANLINW2YkxHJ8qxy/qBxlYa6U9uerIfBasZ54XHb69ioeBvkX/RcOpdmrYqptGrVDlS7/OYVgdTCucCsBz1uoMlWVRHqv0g1iTD45mmHVotDLOvmq19HkHNeFSH9XumJ9JuwF50/AQ

**Comment by polluxll** [comment]
The position on the far side of Globe,but the screenPoint console the result (560.2366130452282, 139.68760016313576)

**Comment by ggetz** [comment]
Hi @polluxll, what would you expect the output to be instead?

It looks like the cartesian position is being translated to the corresponding canvas position as the function is documented to do.

**Comment by polluxll** [comment]
maybe the result can determine if the poistion is on the back

**Comment by ggetz** [comment]
Ah, thank you.

 I think that is beyond the scope of that particular function. I would suggest instead using a `pick` function like `globe.pick` or and intersection test to determine that instead.

**Comment by ggetz** [comment]
If you have additional questions, I'd suggest you go to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
