### ISSUE TITLE
`PolygonGeometryUpdater` uses the deprecated `PolygonGeometry.computeRectangle` function

### ISSUE THREAD

**Issue by jjspace** [CesiumGS/cesium#11797]
### What happened?

`PolygonGeometryUpdater` is using a deprecated function internally which can result in the deprecation warning getting logged to the console even if the user isn't directly using `PolygonGeometry.computeRectangle`

### Reproduction steps

1. Load the [Geometry Height Reference](https://sandcastle.cesium.com/?src=Geometry%20Height%20Reference.html) sandcastle
2. Observe the console

### Sandcastle example

https://sandcastle.cesium.com/?src=Geometry%20Height%20Reference.html

**Comment by ggetz** [comment]
@jjspace I think the deprecated function was not actually removed either. This should be fixed for the next release.

**Comment by ggetz** [comment]
@jjhembd Could you please take a look at this in prep for tomorrow's release?
