### ISSUE TITLE
what are the System Hardware Requirements for using cesium js is it that the machine must have 32 gb ram with external/integrated GPU?

### ISSUE THREAD

**Issue by Kriess2507** [CesiumGS/cesium#11806]
### Verification

- [X] Yes

**Comment by Kriess2507** [comment]
What are the system requirement for a windows for smooth rendering of the maps. Do we need to have a machine with 32 gb RAM and an integrated/external GPU or would it work smoothly even for the system with lower RAM say 4GB/8GB with no integrated/external GPU?

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

Generally, we don't have formal system hardware requirements, as it depends on what parts of the API an application would be using. CesiumJS can perform well on integrated GPU will less RAM if the application uses less resource-intensive features.
