### ISSUE TITLE
[DOCS] billboardCollection.add and labelCollection.add have doc issues.

### ISSUE THREAD

**Issue by s3xysteak** [CesiumGS/cesium#11813]
### Feature

`billboardCollection.add` and `labelCollection.add` have a same issue: the option do not contain `disableDepthTestDistance`, which should be contained.
In [BillboardCollection source code](https://github.com/CesiumGS/cesium/blob/1.114/packages/engine/Source/Scene/BillboardCollection.js#L475) you can see:
```js
BillboardCollection.prototype.add = function (options) {
  const billboard = new Billboard(options, this);
  // ...
}
```
but class `Billboard` do accept a `disableDepthTestDistance` option, you can see [class Billboard source code](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/Billboard.js#L66):
```js
// ...
// It checked if disableDepthTestDistance is defined
  if (
    defined(options.disableDepthTestDistance) &&
    options.disableDepthTestDistance < 0.0
  ) {
    throw new DeveloperError(
      "disableDepthTestDistance must be greater than or equal to 0.0."
    );
  }
//...
```
It also happened in labelCollection.

I think the problem actually caused by the type is not declared clearly. So I suggest that we can provide a param type for class `Billboard` and import the type from it to other function, like: 
```js
// in Billboard.js
/**
 * @param {{
 *   image: string | Property
 *   disableDepthTestDistance: number | Property
 *   // ...
 * }} options
 * @param {Instancetype<import('...../BillboardCollection.js').default>} billboardCollection
 */
function Billboard(){
  //...
}

// in BillboardCollection.js and any other used Billboard
/**
 * @param {Parameters<typeof import(...../Billboard.js).default>[0]} options
 */
BillboardCollection.prototype.add = function (options) {
  const billboard = new Billboard(options, this);
 // ...
}
``` 
If possible, I would be happy to provide a PR to address this issue. The PR would focus solely on modifying the comments and would not involve any code changes.

**Comment by ggetz** [comment]
Great, thanks @s3xysteak! We'd be happy to accept a PR!

**Comment by javagl** [comment]
This sounds like a whole "category" of improvemenets, i.e. cases where one could inline the structure of such (otherwise untyped) 'options' into the JSDoc. (Related: https://github.com/CesiumGS/cesium/issues/11749 )

**Comment by s3xysteak** [comment]
@ggetz The [BillboardGraphics](https://github.com/CesiumGS/cesium/blob/1.114/packages/engine/Source/DataSources/BillboardGraphics.js#L50) and [LabelGraphics](https://github.com/CesiumGS/cesium/blob/1.114/packages/engine/Source/DataSources/LabelGraphics.js#L8) already have similar type declarations. Should I 
use the type declarations here directly in Billboard and Label, 
or declare them in Billboard and Label and then reference them elsewhere, 
or simply copy the type declarations and use them in both Label and LabelCollection?  

I believe both approaches would not have any impact on the usage of the code (including TypeScript users). However, a less optimal solution might cause confusion during future maintenance.

**Comment by s3xysteak** [comment]
The best approach seems to be declaring the constructor type in the `Label` class and referencing this type in other places where Label instances are used, such as `LabelCollection.add` or `LabelGraphics`. Looking at the code in `LabelCollection.add`, it appears that it instantiates a `Label` object, but I'm not certain if `LabelGraphics` follows a similar logic.
