### ISSUE TITLE
add axis Parallel WGS84Axis

### ISSUE THREAD

**Issue by chen21439** [CesiumGS/cesium#11835]
### Feature

i wonder if can show Cartesian Axis in API,or show me the way to do it myself [localFrameToFixedFrameGenerator](https://community.cesium.com/t/cesium-transforms-eastnorthuptofixedframe-how-to-work/29832)

**Comment by chen21439** [comment]
is it possible to pass the parameter (firstAxisName,secondAxisName) to get Matrix in worldCordinator

**Comment by ggetz** [comment]
Hi @chen21439, the axes of the WGS84 ellipsoid are the [unit vectors](https://cesium.com/learn/cesiumjs/ref-doc/Cartesian3.html#.UNIT_X).

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
