### ISSUE TITLE
render to framebuffer has a bug

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium#11856]
### What happened?

In Cesium, when rendering to a texture, it always results in an empty texture once the camera reaches a certain height. I'm not sure if this is a bug. As shown in the example I provided below, I first render a box to the texture, then sample it as the material texture for another box.
Under normal circumstances, it should be red. However, when I elevate the camera height, it turns white because I use white to clear the frame buffer.

### Environment

Browser:Google Chrome121.0.6167.189
CesiumJS Version: 1.114.0
Operating System:windows 10

**Comment by ggetz** [comment]
Thanks for the report @engineerhe. Would you be able to put together an example with the minimum coded needed to replicate the issue? There's a lot here, so it's hard to track down the root cause.

**Comment by engineerhe** [comment]
@ggetz Thank you for your response. I have traced the cause, it's not a bug. I will close the issue.
