### ISSUE TITLE
The raise or lower of datasources is not effective

### ISSUE THREAD

**Issue by zendguofans** [CesiumGS/cesium#11885]
### What happened?

I am using cesium@1.115.0 Version, for my work, I need to modify the order of multiple GeojsonDatasources. When I use the raise or lower of datasources to implement functionality, I find that it does not work and there are no errors.

### Reproduction steps

I loaded three GeojsonDataSource  and adjusted their order.
The data are as follows:
polygon1：

{
  "type": "FeatureCollection",
  "name": "321",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::4490"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
      
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                119.922312251355635,
                31.729041332654734
              ],
              [
                119.904095462413977,
                31.731896202563501
              ],
              [
                119.897026260735132,
                31.738421619497824
              ],
              [
                119.890772736173062,
                31.752152184297131
              ],
              [
                119.905746106592233,
                31.766996213097134
              ],
              [
                119.925506986729729,
                31.760308955465035
              ],
              [
                119.918709677423138,
                31.743519601477765
              ],
              [
                119.922312251355635,
                31.729041332654734
              ]
            ]
          ]
        ]
      }
    }
  ]
}

polygon2:

{
  "type": "FeatureCollection",
  "name": "321",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::4490"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {

      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                119.916312575761197,
                31.736764370752599
              ],
              [
                119.904474216784863,
                31.738818961979899
              ],
              [
                119.904474216784863,
                31.744982735661793
              ],
              [
                119.900071521297789,
                31.745080573339283
              ],
              [
                119.905746106592233,
                31.766996213097134
              ],
              [
                119.930890389707258,
                31.762202166900103
              ],
              [
                119.923063375508036,
                31.743417332821949
              ],
              [
                119.916312575761197,
                31.736764370752599
              ]
            ]
          ]
        ]
      }
    }
  ]
}

polygon3:

{
  "type": "FeatureCollection",
  "name": "321",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::4490"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                119.915666125536859,
                31.739950051139662
              ],
              [
                119.90855030564498,
                31.742621790206869
              ],
              [
                119.904474216784863,
                31.744982735661793
              ],
              [
                119.900071521297789,
                31.745080573339283
              ],
              [
                119.899529879685403,
                31.765503515881456
              ],
              [
                119.920216017809722,
                31.766984876156343
              ],
              [
                119.934209581834992,
                31.763466645503488
              ],
              [
                119.920824433636909,
                31.745690322204847
              ],
              [
                119.915666125536859,
                31.739950051139662
              ]
            ]
          ]
        ]
      }
    }
  ]
}

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by syzdev** [comment]
You must ensure that `dataSource` exists in the collection.

[DataSourceCollection.add](https://cesium.com/learn/cesiumjs/ref-doc/DataSourceCollection.html?classFilter=DataSourceCollection#add) returns a `Promise` that resolves once the data source has been added to the collection.

**Comment by zendguofans** [comment]
The added code is as follows:
![49f18773a25104e085fde9d29904e72](https://github.com/CesiumGS/cesium/assets/134260609/9bc035ec-5f8a-4b4b-a708-4c2e9a8d9ce0)
I can ensure that the dataSource was successfully added.
![322da922105f38d2aa64f25cce505d6](https://github.com/CesiumGS/cesium/assets/134260609/94d440eb-cc07-45ac-8753-6490c67a4264)

**Comment by ggetz** [comment]
Hi @zendguofans, can you please include a minimal [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. Thanks!

**Comment by zendguofans** [comment]
javascript :


const viewer = new Cesium.Viewer("cesiumContainer");

function loadDataSourcesLayer(layerCode, jsonData, option={}) {
  let { style, filter, type } = option;
  console.log(layerCode);
  let json = {
    'type': 'FeatureCollection',
    'features': jsonData.features,
  };
  let newStyle = null;
  let strokeColor = null;
  let   imageSize = 0.4,
    strokenColor = '#00FFFF',
    strokenWidth = 3,
    fillColor = '#00FFFF',
    fillOpacity = 1;
  if (style) {
    let {  polygonStyle } = style;
    if (polygonStyle) {
      fillColor = polygonStyle?.color ? polygonStyle['color'] : '#00FFFF';
      fillOpacity = polygonStyle?.opacity ? polygonStyle.opacity : 0.4;
      strokenColor = polygonStyle?.strokencolor ? polygonStyle['strokencolor'] : '#00FFFF';
      strokenWidth = polygonStyle?.strokenwidth ? polygonStyle['strokenwidth'] : 3;
    }
  }
  if (type === 'Polygon') {
    newStyle = {
      stroke: Cesium.Color.fromCssColorString(strokenColor),
      fill: Cesium.Color.fromCssColorString(fillColor).withAlpha(fillOpacity),
      strokeWidth: strokenWidth,
    };
  }
  let sourcePromise = null;
  if (newStyle) {
    sourcePromise = Cesium.GeoJsonDataSource.load(json, newStyle);
  } else {
    sourcePromise = Cesium.GeoJsonDataSource.load(json);
  }
  sourcePromise.then((dataSource) => {
    dataSource.name = layerCode;
    viewer.dataSources.add(dataSource);
    viewer.scene.requestRender();
    return dataSource;
  })

}

 function getLayer(layerCode){
  //判断是否是DataSources
  let list = viewer.dataSources._dataSources;
  if (list.length > 0) {
      let item = list.find((item) => {
          return item.name === layerCode;
      });
      if (item) {
          return item;
      }
  }
  return false;
}

 loadDataSourcesLayer(
  'ChangZhou:school1',
  {
    "type": "FeatureCollection",
    "name": "321",
    "crs": {
      "type": "name",
      "properties": {
        "name": "urn:ogc:def:crs:EPSG::4490"
      }
    },
    "features": [
      {
        "type": "Feature",
        "properties": {

        },
        "geometry": {
          "type": "MultiPolygon",
          "coordinates": [
            [
              [
                [
                  119.922312251355635,
                  31.729041332654734
                ],
                [
                  119.904095462413977,
                  31.731896202563501
                ],
                [
                  119.897026260735132,
                  31.738421619497824
                ],
                [
                  119.890772736173062,
                  31.752152184297131
                ],
                [
                  119.905746106592233,
                  31.766996213097134
                ],
                [
                  119.925506986729729,
                  31.760308955465035
                ],
                [
                  119.918709677423138,
                  31.743519601477765
                ],
                [
                  119.922312251355635,
                  31.729041332654734
                ]
              ]
            ]
          ]
        }
      }
    ]
  }
  ,
  {
    type: "Polygon", style: {
      "polygonStyle": {
        "color": "#33ffff",
        "strokencolor": "#33ffff",
        "strokenwidth": 3,
        "opacity": 0.5
      }
    }
  });
loadDataSourcesLayer(
  'ChangZhou:school2',
  {
    "type": "FeatureCollection",
    "name": "321",
    "crs": {
      "type": "name",
      "properties": {
        "name": "urn:ogc:def:crs:EPSG::4490"
      }
    },
    "features": [
      {
        "type": "Feature",
        "properties": {

        },
        "geometry": {
          "type": "MultiPolygon",
          "coordinates": [
            [
              [
                [
                  119.916312575761197,
                  31.736764370752599
                ],
                [
                  119.904474216784863,
                  31.738818961979899
                ],
                [
                  119.904474216784863,
                  31.744982735661793
                ],
                [
                  119.900071521297789,
                  31.745080573339283
                ],
                [
                  119.905746106592233,
                  31.766996213097134
                ],
                [
                  119.930890389707258,
                  31.762202166900103
                ],
                [
                  119.923063375508036,
                  31.743417332821949
                ],
                [
                  119.916312575761197,
                  31.736764370752599
                ]
              ]
            ]
          ]
        }
      }
    ]
  }
  ,
  {
    type: "Polygon", style: {
      "polygonStyle": {
        "color": "#ccff00",
        "strokencolor": "#ccff00",
        "strokenwidth": 3,
        "opacity": 0.5
      }
    }
  });
 loadDataSourcesLayer(
  'ChangZhou:school2',
  {
    "type": "FeatureCollection",
    "name": "321",
    "crs": {
      "type": "name",
      "properties": {
        "name": "urn:ogc:def:crs:EPSG::4490"
      }
    },
    "features": [
      {
        "type": "Feature",
        "properties": {
        },
        "geometry": {
          "type": "MultiPolygon",
          "coordinates": [
            [
              [
                [
                  119.915666125536859,
                  31.739950051139662
                ],
                [
                  119.90855030564498,
                  31.742621790206869
                ],
                [
                  119.904474216784863,
                  31.744982735661793
                ],
                [
                  119.900071521297789,
                  31.745080573339283
                ],
                [
                  119.899529879685403,
                  31.765503515881456
                ],
                [
                  119.920216017809722,
                  31.766984876156343
                ],
                [
                  119.934209581834992,
                  31.763466645503488
                ],
                [
                  119.920824433636909,
                  31.745690322204847
                ],
                [
                  119.915666125536859,
                  31.739950051139662
                ]
              ]
            ]
          ]
        }
      }
    ]
  }
  ,
  {
    type: "Polygon", style: {
      "polygonStyle": {
        "color": "#ff0000",
        "strokencolor": "#ff0000",
        "strokenwidth": 3,
        "opacity": 0.5
      }
    }
  });
  viewer.camera.flyTo({
    destination: Cesium.Cartesian3.fromDegrees(119.915666125536859,  31.739950051139662,10000),
    orientation: {
        heading: Cesium.Math.toRadians(0.0),
        pitch: Cesium.Math.toRadians(-90),
        roll: Cesium.Math.toRadians(0)
    }
});

document.getElementById('changeLevel').onclick=function(){
   let datasource=getLayer('ChangZhou:school1');
       viewer.dataSources.lowerToBottom(datasource);
}



html:

<style>
      @import url(../templates/bucket.css);
    </style>
    <div id="cesiumContainer" class="fullSize"></div>
    <div id="loadingOverlay"><h1>Loading...</h1></div>
    <div id="toolbar"></div>
    <button  id="changeLevel"   style="position:absolute;left:100px;top:50px;width:100px;height:32px;">修改层级</button>
