### ISSUE TITLE
There is an issue with the optional parameters of SingleTileImageryProvider

### ISSUE THREAD

**Issue by zendguofans** [CesiumGS/cesium#11884]
### What happened?

When I use SingleTileImageryProvider and only pass in a URL parameter, my code will report that the tileWidth parameter accepts a number type, but it is actually undefined

### Reproduction steps

     baseLayer: new Cesium.ImageryLayer(new Cesium.SingleTileImageryProvider({
        url: 'data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg=='
      })),

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by zendguofans** [comment]
cesium@1.115.0

**Comment by syzdev** [comment]
https://github.com/CesiumGS/cesium/blob/72781237cc8137a84b172452fa0c78eb7949694b/packages/engine/Source/Scene/SingleTileImageryProvider.js#L86-L92

As you can see, `tileWidth` and `tileHeight` cannot be non numeric types or `undefined`.

**Comment by zendguofans** [comment]
Okay, I got it. I didn't pass in the parameters because I was looking at the documentation and the parameters were optional

**Comment by zendguofans** [comment]
![image](https://github.com/CesiumGS/cesium/assets/134260609/276acf5a-1e15-4bdb-8f74-4382919571ac)

**Comment by syzdev** [comment]
This is indeed a document issue:
https://github.com/CesiumGS/cesium/blob/72781237cc8137a84b172452fa0c78eb7949694b/packages/engine/Source/Scene/SingleTileImageryProvider.js#L19-L20

Should be modified to:

```js
 * @property {number} tileWidth The width of the tile, in pixels.
 * @property {number} tileHeight The height of the tile, in pixels.
```

**Comment by zendguofans** [comment]
Thank you
