### ISSUE TITLE
when tile load fail ，how control console output

### ISSUE THREAD

**Issue by Lemon-Cai** [CesiumGS/cesium#11896]
### Feature

![image](https://github.com/CesiumGS/cesium/assets/37281618/172894b8-d69f-4cf5-9f06-bf0e2ebef1e6)

like this， is bad experience. how to  optimise it

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
