### ISSUE TITLE
CesiumTerrainProvider: own terrain data is not loaded since v1.107

### ISSUE THREAD

**Issue by lukey78** [CesiumGS/cesium#11899]
### What happened?

With the release of 1.107 my own terrain data is not loaded anymore.
No error is shown in the console. The layer.json is fetched, but no terrain tiles.
It works perfectly until v1.106. 
Of course I fixed the constructor of CesiumTerrainProvider to the static one .fromUrl.

Is something new expected in the layer.json since v1.107?

### Reproduction steps

see sandcastle example

### Sandcastle example

https://sandcastle.cesium.com/#c=dZBNb8IwDIb/StQLIFWJdu0KmsR1X9K+LrmExkC0NOlsp4xN/PcFukmMMV8i530eR04TA7HoHWwAxVQE2Ig5kEutHI4XZ1fAY100h3YeAxsXAHVRik8dOoy9s4DVb+sREDN2/53KJcb2Cf1YB3FUozVzR5VSPODS2B4CJwQfV9JFxc4DAZM6DkaHh8VJIbwlIH4GZHi/jdgaT5VgTFD+C98AG2vYVGKZafjN7SY67MohmVzqUJRFTbz1MPvhrlzbRWSR8mJS5iXazhsGUovUvALLhmgv7tFaHau1db1wdnrmU0XjDVFOlsn7B/cBupjVKvN/VB+NdWF11wN6s91j64vZ9XAppaxVbs+bHKNfGDyZ/AU

### Environment

every browser

**Comment by syzdev** [comment]
The terrain can be loaded correctly using the following code (After Cesium 1.104):
```js
const viewer = new Cesium.CesiumWidget('cesiumContainer', {
  terrainProvider: await Cesium.CesiumTerrainProvider.fromUrl(
    'https://terrain.adventurelog.io/tilesets/adventurelog', {
      requestVertexNormals: true,
      requestMetadata: false,
  }),
})
```

> Is something new expected in the layer.json since v1.107?

No.

> Of course I fixed the constructor of CesiumTerrainProvider to the static one .fromUrl.

Starting with CesiumJS 1.104 The `readyPromise` pattern has been deprecated across the API. It will be removed in CesiumJS 1.107. This has been done to facilitate better asynchronous flow and error handling. 

Therefore, before 1.104, you can use the following code to load terrain:
```js
const viewer = new Cesium.Viewer('cesiumContainer', {
  terrainProvider: new Cesium.CesiumTerrainProvider({
    url: 'https://terrain.adventurelog.io/tilesets/adventurelog',
    requestVertexNormals: true,
    requestMetadata: false,
  }),
})

```

But after 1.104, you need to use the latest code to load terrain.

In addition, `terrainProvider` or `terrain` should be used in the constructor to load terrain, while `provider` does not exist in the construction parameters.

**Comment by ggetz** [comment]
@lukey78 As @syzdev pointed out, you need the `await` keyword since `CesiumTerrainProvider.fromUrl` returns a [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

The property is also `terrainProvider` not `provider`.

**Comment by lukey78** [comment]
Perfect, thanks!
