### ISSUE TITLE
Shared identical external textures from GLB files are not accounted for in resource statistics

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#11897]
**EDIT:** This issue originally claimed that external textures that are referred to from multiple GLB files are not shared internally. A pragmatic logging statement in the [`GltfImageLoader`](https://github.com/CesiumGS/cesium/blob/432e88a73ee21cfcf5afe9d31b36982e3d770e7f/packages/engine/Source/Scene/GltfImageLoader.js#L202) class suggests that the textures **are** shared, and actually only loaded once. But loading such an asset still causes undesired behavior, with the details updated below accordingly.

---

The following archive contains test data for this, namely a tileset and a simple Sandcastle for loading it:

[ExternalTextureSharing-2024-03-25.zip](https://github.com/CesiumGS/cesium/files/14749125/ExternalTextureSharing-2024-03-25.zip)

The tileset consists of a simple `tileset.json` that refers to 100 GLB files. These GLB files each contain trivial geometry (a unit square, two triangles). All these 100 GLB files refer to only **two** external textures (that are stored outside of the GLB, and referred to, from the GLBs, via their URI). These are PNG files with 2048x2048 pixels. 

So the whole tileset cotains two 2k-textures and a few bytes of geometry data, but when more tiles are loaded, it bails out with the message 

> "The tiles needed to meet maximumScreenSpaceError would use more memory than allocated for this tileset."

and starts omitting some tiles:

![Cesium External Texture Sharing](https://github.com/CesiumGS/cesium/assets/5597569/ab33128f-da16-425c-80a3-fbfcde907c45)

After a short investigation, it turns out that the external textures indeed **are** loaded only once. But the mechanism for computing the memory usage does not take this into account. The [`ModelStatistics`](https://github.com/CesiumGS/cesium/blob/432e88a73ee21cfcf5afe9d31b36982e3d770e7f/packages/engine/Source/Scene/Model/ModelStatistics.js) are accumulating the data for each model, and reporting the total size as the [`totalMemoryUsageBytes`](https://github.com/CesiumGS/cesium/blob/432e88a73ee21cfcf5afe9d31b36982e3d770e7f/packages/engine/Source/Scene/Cesium3DTileset.js#L1621), which eventually [triggers the message about the exceeded memory](https://github.com/CesiumGS/cesium/blob/432e88a73ee21cfcf5afe9d31b36982e3d770e7f/packages/engine/Source/Scene/Cesium3DTileset.js#L2724).

**Comment by kring** [comment]
CC CesiumGS/cesium-native#497
That issue actually makes it sounds like CesiumJS handled this at one time?

**Comment by javagl** [comment]
@kring Others may have to confirm this, but I also thought that this was supposed to be implemented. I tested it, inspired by the forum post at https://community.cesium.com/t/how-does-cesiumjs-manage-textures-shared-across-tiles/30404/2 , and it looks like it is not working as expected.

But **note** the **NOTE** that I edited in: It _might_ be that CesiumJS is actually doing the texture sharing, and it is only the "memory tracking" functionality that does not properly take this into account, and _assumes_ that the tiles need more memory than they actually need. (I think there's no really easy way to confirm that - e.g. something like the "Windows Task Manager - GPU memory" overview might not really be accurate enough here...)

**Comment by timoore** [comment]
> But **note** the **NOTE** that I edited in: It _might_ be that CesiumJS is actually doing the texture sharing, and it is only the "memory tracking" functionality that does not properly take this into account, and _assumes_ that the tiles need more memory than they actually need. (I think there's no really easy way to confirm that - e.g. something like the "Windows Task Manager - GPU memory" overview might not really be accurate enough here...)

You can run renderdoc with chrome and see the allocated textures; see e.g. https://edw.is/renderdoc-webgl/ . I don't know if there are more integrated tools than that.

**Comment by javagl** [comment]
An update: It now looks like the textures **are** shared, but only the mechanism for computing the "total memory usage" is flawed by not taking this into account, and causes tiles (unnecessarily) to be omitted. The issue text has been updated accordingly.

**Comment by javagl** [comment]
I had a short look at how this could be addressed. 

--

Some context - people might want to skip this if they already have a mental model of all that...:

- The computations are based on the [`Cesium3DTileContent.texturesByteLength`](https://github.com/CesiumGS/cesium/blob/3f9ce90de421875824d5e69a9b0827c1cba0f9e3/packages/engine/Source/Scene/Cesium3DTileContent.js#L107) value
- The specific one relevant here is the [`Model3DTileContent`](https://github.com/CesiumGS/cesium/blob/3f9ce90de421875824d5e69a9b0827c1cba0f9e3/packages/engine/Source/Scene/Model/Model3DTileContent.js#L78)
- This, in turn, obtains the value from the `ModelStatistics`, which keeps track of the texture size in [its `addTexture`](https://github.com/CesiumGS/cesium/blob/3f9ce90de421875824d5e69a9b0827c1cba0f9e3/packages/engine/Source/Scene/Model/ModelStatistics.js#L158) function
  - Note: This one already **does** check for duplicates, based on the `texture._id`!
- The `ModelStatistics` are updated as part of the `PrimitiveStatisticsPipelineStage`, with the loaded textures. 
- Based on the resulting values, the [`Cesium3DTilesetStatistics.texturesByteLength`](https://github.com/CesiumGS/cesium/blob/3f9ce90de421875824d5e69a9b0827c1cba0f9e3/packages/engine/Source/Scene/Cesium3DTilesetStatistics.js#L65) will be updated when tiles are loaded/unloaded

---

Now, there are two parts to this problem.

The (maybe) simpler one is identifying identical textures. 

Each `Texture` object already has an `_id` field. This is just initialized with a GUID when the texture is created. But there already is a [`cacheKey` in `GltfTextureLoader`](https://github.com/CesiumGS/cesium/blob/3f9ce90de421875824d5e69a9b0827c1cba0f9e3/packages/engine/Source/Scene/GltfTextureLoader.js#L45) that could be used for identifying identical textures. This will be a string like
`texture:http://localhost:8003/texture1.png-sampler-10497-10497-9729-9729-context-a4d9a28d-3340-4e39-8cbf-76f8423e1643` that could be forwarded to the `Texture`, to be used as its ID (as part of the [`CreateTextureJob`](https://github.com/CesiumGS/cesium/blob/3f9ce90de421875824d5e69a9b0827c1cba0f9e3/packages/engine/Source/Scene/GltfTextureLoader.js#L170).

---

The more difficult question is: How to handle these IDs and the size, _globally_ for the whole tileset?

The information about the textures and their sizes _has_ to be stored _and maintained_ on the level of the tileset. This would probably reside in the `Cesium3DTilesetStatistics`. And it would probably boil down to some mapping from the `texture._id` of the loaded textures to their size. 

This mapping has to be updated when tiles are loaded/unloaded. And right now, the update of the statistics is solely happening based on the information that is provided by a `Cesium3DTileContent`. So one could naively say that this interface _also_ has to maintain such a `texture._id -> size` mapping. But this would be a _considerable_ change in that interface (that is implemented by several classes). One could probably think about other options, but I don't have a really great idea how one could "nicely" transport this information from the `Model3DTileContent` to the tileset level. (And with 'nicely', I mean without breaking the interface and/or doing some `instanceof Model3DTileContent` checks....)

I'll think about some options, and maybe try out a few things, but maybe someone already has a strong preference for one approach here.

**Comment by javagl** [comment]
This came up in the forum, as the underlying reason for https://community.cesium.com/t/implicit-tiling-inconsistency-with-vs-without-textures/34640

**Comment by javagl** [comment]
This one should be closed via https://github.com/CesiumGS/cesium/pull/12331
