### ISSUE TITLE
ImageMaterialProperty incorrect texture mapping

### ISSUE THREAD

**Issue by jopenei** [CesiumGS/cesium#11890]
### What happened?

Using an ImageMaterialProperty as a material for entities from a dataSource does not work as expected. The image is mapped incorrectly onto the entity.

Additionally setting the height to 0 causes the same problem for polygon entities.

### Sandcastle example

https://sandcastle.cesium.com/#c=3VRdb5swFP0rFk9ESm0gJGnSNNqUVtOmTpvWaS9jmgy+AbdgI9sko1X/+wyBNMtSaS+TptkP3G+fey52IoU2aMNhCwpdIgFbtALNqwJ/aW1u5CStvpLCUC5ARc7gIhJJm1dQA4rT/NfMtwVN4X3n+qhkCcrU7mMkEOKNa44iJzOm1HNCqjKXlOEtv+cFME6xVClptLLRSCKLwp5ETFYVMZmSqUdWGST3oGJJFfteUmOPEVhvUuJ7QVj+OHvJj0uRRk4knhr4kbHb4kHIyqLD/QbkOy3FFTX0VlYqAdxgc9voPeCUa4NTbgHFlQZleTAgDLZAyZ3tVAAnI8/z2ZTFXjBK1j7MYMLimZf4Pp0FI7r2iaJbAhPKvPOJByMasDCejcLxJJmxkJ5DMJ56lIXhBMYMiKZFmQNOQd5ZcE0HA2wyEC7b40SXS/TYwNzNET97NKaMHUQ2vbc9m2cbtvi54TZ2Q/PKftZSXdMkc1t73RVH7dqZcCnzOpUCH8y/Fy9eCJWVye3vYyM7tlcylwp/ur7qMtq57IZjd9fJHlrTRouiqzfvMWUcFFVJVs/3hakyVqJihNdKFleQKgD9Wilau197dGe+7w9REA4PDMEpw3h4lDLe6d8GvaPvfP6Hd6Bf/8Bd6KE8DRr5ac//32ffmx6R7Z2fMhyy36b8n+x3zWTA08zMkXdyGg9SFp+lezSbwYUzdBba1Dks+5KveFFKZVClchdjYsC+IJYMTeLKArKPldaD7tYtyGHqgvEN4uzyxKOPkpxqbT3rKs9v+QNEznJBbPxvqQ2NXKQfNqByWjdhmb+82Rkxxgti1dOZRso8puqo8k8

### Environment

Browser: Edge
CesiumJS Version: 1.115 and 1.113 (for dataSource from GeoJSON) tested
Operating System: Windows

**Comment by ggetz** [comment]
Thanks for the report @jopenei. 

The [1.110 release](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#1110---2023-10-02) included some significant changes to how we handle polygon rendering. Would you be able to confirm if this behavior occurred before 1.110?

As a workaround, you can specify the uvs as described in https://github.com/CesiumGS/cesium/issues/11618.

**Comment by jopenei** [comment]
Hi Gabby,

thanks for pointing out the workaround. I will give it a try.

Also, I couldn't reproduce said behavior in release version 1.109.

**Comment by ggetz** [comment]
Thanks @jopenei, I'll mark this as a regression.

**Comment by dslming** [comment]
@ggetz 
The issue was not reproduced in v1.117, and I believe it has been resolved in 1.116.
I think it's the same issue as this one.  [11767](https://github.com/CesiumGS/cesium/issues/11767)

**Comment by ggetz** [comment]
Thanks @dslming! I'll close this as completed.
