### ISSUE TITLE
Texture Scaling with Texture Coordinates > 1 not working properly

### ISSUE THREAD

**Issue by jopenei** [CesiumGS/cesium#11891]
### What happened?

I am attempting to double the texture size on a polygon entity by adjusting the texture coordinates. This approach however leads to distortions for texture coordinates > 1.0. This behavior seems to exist at least since release version 1.97. Because of that I am unsure if this is intended behavior or a bug that has not been adressed.

### Sandcastle example

https://sandcastle.cesium.com/#c=7ZXfb5swEMf/FYsnIqU2EDIamkabspdJmzZp0zSp9MGYK3gzNrJNO1rlfx+Qn81SDVVTn8oLvvP37vDdR4YpaSy65XAHGl0iCXdoCYbXJf7e+9zEYb29VNJSLkEnzugikYlcx2CQllsOBtMscx8SiVClRJMrGaPeQqjgoKlmRRNvUy+ptu2Kygm+0ap8D7kGMO+0po17tQ5C6Mz3ZmMUhOO9w/dOOabjo5Dp2r4ebTdKakFzKuLD830oaQ6fNjtftKpA28Z92ObqHt5JYpQ4hbWViQnJhUqpwBk3TNXawBnLJGaqJMZSmVGd+RGpK6FoZogt2kP9NERpnnNJBZn8ICGJSBiFzKNswkIWUgbpmyiazSIvSLMwDSdscp6lgQdRiiuZJ87+c1bb4xTA88LGyNvYFn7bWsNSKZ21hdrO7lrfDcO042mHHKOrfa6DNuxmEbhB27tdz55UeUNV3r9VwVDVQcXrzWrVv1eJXL0Yj9ERft75KccjHqNXHp/Noz9G/iDS/P/Fo/9I9RRpL8Ga7x9fdcEpxyFrfcgra89jzcPTdvZ4OoykoboBqr7u4NvtXqnym3KP+BtdOGNnbmwjYLFN9JaXldIW1Vq4GBMLZSW6/pC0Zr/AYmZMl7mTzslh6Dzjt4hnlyd+/IgJaky7c1ML8ZXfQ+Is5qTV/xXaYcBl/vkWtKBNJyv8xce1E2M8J615OtIqJVKqjzL/AQ

### Environment

Browser: Edge
CesiumJS Version: 1.115, 1.97
Operating System: Windows

**Comment by ggetz** [comment]
Thanks for the report @jopenei!

I'm not sure if I would necessarily classify this as a bug. At least, given this is existing behavior, we're unlikely to change it unless there is a compelling reason to.

You can achieve repeated images by uses the `repeat` property on image materials instead:

```js
viewer.entities.add({
  polygon: {
    hierarchy: Cesium.Cartesian3.fromDegreesArray([
      -109, 24,
      -110, 24,
      -110, 25,
      -109, 25
    ]),
     material: new Cesium.ImageMaterialProperty({
          image: "https://global.discourse-cdn.com/standard17/uploads/threejs/original/3X/4/7/474c0ac3c4c4aceb67799702bd4b43c38db20e7b.png",
       repeat: new Cesium.Cartesian2(2, 2)
        }),
    height: 0,
        textureCoordinates: {
      positions: [
        new Cesium.Cartesian2(1, 1),
        new Cesium.Cartesian2(0, 1),
        new Cesium.Cartesian2(0, 0),
        new Cesium.Cartesian2(1, 0),
      ],
    },
  }
});
```
