### ISSUE TITLE
Movement handler stuck when clicking certain key combinations

### ISSUE THREAD

**Issue by Dphalos** [CesiumGS/cesium#11903]
### What happened?

If you do the reproduction steps, you get stuck with dragging mode even when you do not hold LEFT_CLICK.

https://github.com/CesiumGS/cesium/assets/27568710/9809b620-4960-4b9b-b8ba-47f8bd3b28cd

### Reproduction steps

1. Press and hold LEFT_CLICK Down
2. Press and hold ALT Down
3. LEFT_CLICK Up
4. ALT Up

### Environment

Browser: Google Chrome Version 123.0.6312.59 (Official Build) (64-bit)
CesiumJS Version: 1.115
Operating System: Windows 10

**Comment by ggetz** [comment]
Thanks for the report @Dphalos, I think this is an oversight in `ScreenSpaceCameraController`.

**Comment by jjspace** [comment]
Is this a result of our [intentional](https://github.com/CesiumGS/cesium/issues/6277#issuecomment-368673808) choice to separate mouse events based on what modifiers are held down? So the event at step 3 in the reproduction steps is "Left click up + alt" instead of just "Left click up"?
