### ISSUE TITLE
Requesting a `onerror` option to `UrlTemplateImageryProvider`

### ISSUE THREAD

**Issue by s3xysteak** [CesiumGS/cesium#11908]
### Feature

When using the UrlTemplateImageryProvider with offline maps for **an area**, it often throws a 404 error because the offline map is missing certain tiles. This behavior is actually expected, but the large number of 404 errors is affecting normal development. Could an option be added to catch this error and invoke a error handler callback? I would like to ignore these 404 errors in this way.

For example:
```js
const noop = () => {}

const imageryProvider = new Cesium.UrlTemplateImageryProvider({
  url: mapUrl + '{z}/{x}/{y}.png',
  onerror: noop
  // onerror: (error) => { throw new Error('oops.') }
  // onerror: undefined // Default behavior.
})
```

**Comment by ggetz** [comment]
Hi @s3xysteak, it's possible to add a listener to a the [`errorEvent`](https://cesium.com/learn/cesiumjs/ref-doc/ImageryProvider.html?classFilter=imageryP#errorEvent) property. 

However, I don't believe to's possible to prevent the 404 errors themselves once the request has been made, as they are handled by the browser.
