### ISSUE TITLE
Customize material for change default texture (flashes white blicking)

### ISSUE THREAD

**Issue by Meybiz** [CesiumGS/cesium#11917]
### Feature

Hey, everybody. I'm creating an Entity Plane and I'm adding
ImageMaterialProperty. When I update the position, the white background flashes. How can I access the original texture and change it?
`
cesium.viewer.entities.add({ 
name: "Red plane with black outline", 
position: new Cesium.Cartesian3.fromDegrees(-107.0, 40.0, 300000.0),
 plane: { 
 plane: new Cesium.Plane(Cesium.Cartesian3.UNIT_Z, 0.0),
  material: new Cesium.ImageMaterialProperty({ image: './logo512.png', transparent: true, }),
   dimensions: new Cesium.Cartesian2(60000.0, 61000.0) } });
`

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
