### ISSUE TITLE
How should the global use of viewer be solved after introducing cesium using renderjs in uniapp (app side)

### ISSUE THREAD

**Issue by 595lzj** [CesiumGS/cesium#11910]
### What happened?

I have two components A and B. In component A I introduce cesium via renderjs and initialize the viewer, then I pass the viewer to the store in vuex via store.commit, in component B I take the viewer via mapState or mapGetters and use it in component B. In component B I take the viewer via mapState or mapGetters and use it in component B. This works in the browser but in the app the B component can't get the viewer in the store.
Here's the code for my vuex:
`import Vue from "vue"  
import Vuex from "vuex"  
  
Vue.use(Vuex);  
  
const store = new Vuex.Store({  
    state: {  
        viewer: '1111111111', // 在这里定义你的viewer  
    },  
    mutations: {  
        setViewer(state, newViewer) {  
            state.viewer = newViewer;  
            console.log('---------------setViewer----------------');  
            console.log('--------vuex中的viewer为:' + state.viewer + '-----------');  
        }  
    },  
    getters: {  
        getViewer: state => {  
            console.log('---------------getViewer----------------');  
            console.log('--------vuex中的viewer为:' + state.viewer + '-----------');  
            return state.viewer;  
        }  
    },  
})  
export default store`
After initialization I tested it with these two statements:
```
store.commit('setViewer', '2222222');  
store.commit('setViewer', this.viewer);
```
It prints as follows on the browser side:
17:38:19.638 ---------------setViewer---------------- at store/index.js:13
17:38:19.640 --------vuex中的viewer为:2222222----------- at store/index.js:14
17:38:19.647 ---------------setViewer---------------- at store/index.js:13
17:38:19.655 --------vuex中的viewer为:[object Object]----------- at store/index.js:14
17:38:22.141 拿到的viewer:[object Object] at components/BasicFunction.vue:197
17:38:22.149 vuex中的viewer:[object Object] at components/BasicFunction.vue:198

It prints as follows on the app side:
17:38:23.568 ---------------setViewer---------------- at store/index.js:13 at app-view.js:1607
17:38:23.569 --------vuex中的viewer为:2222222----------- at store/index.js:14 at app-view.js:1607
17:38:23.569 ---------------setViewer---------------- at store/index.js:13 at app-view.js:1607
17:38:23.569 --------vuex中的viewer为:[object Object]----------- at store/index.js:14 at app-view.js:1607
17:38:47.482 拿到的viewer:1111111111 at components/BasicFunction.vue:197
17:38:47.484 vuex中的viewer:1111111111 at components/BasicFunction.vue:198

You can see that although the state.viewer has been printed in setViewer as the correct object, what you actually get is still the viewer defined by initialization in store: 1111111111.

Should I introduce cesium in a different way?
### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by 595lzj** [comment]
[demo.zip](https://github.com/CesiumGS/cesium/files/14801194/demo.zip)
这个问题工程可以复现出问题

**Comment by jjspace** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
