### ISSUE TITLE
Cylinder Entity not rendering at correct height or clamping to ground

### ISSUE THREAD

**Issue by parker-the-king** [CesiumGS/cesium#11921]
### What happened?

I'm trying to render an entity on a terrain map that consists of a center point which is on the ground, and then a cylinder which is centered at that point, but needs to be clamped to the terrain. The issue which we are seeing is that the cylinder starts well below the elevation of the point and renders into the earth. Here's a picture of the bug: 
[error pic.pdf](https://github.com/CesiumGS/cesium/files/14858787/error.pic.pdf)
As you can see the cylinder seems to be inside of the earth below the white center point near the mountain. What we want is for the cylinder to be clamped to the terrain almost "painting" the mountain and to be 1000 meters above the center point. 

Here's our code for rendering the entity:
new Entity({
  // @ts-ignore
  position: new CallbackProperty(() => {
    return Cartesian3.fromDegrees(lon ?? 0, lat ?? 0);
  }, false),
  point: {
    pixelSize: 10,
    color: Color.WHITE,
    heightReference: HeightReference.CLAMP_TO_GROUND,
  },
  cylinder: new CylinderGraphics({
    length: new CallbackProperty(() => {
      return height ?? 1
    }, false),
    material: Color.RED.withAlpha(0.5),
    bottomRadius: new CallbackProperty(() => {
      return radius ?? 1;
    }, false),
    topRadius: new CallbackProperty(() => {
      return radius ?? 1;
    }, false),
  }),
  show: false,
  name: "incident",
})

### Reproduction steps

1.
2.
3.
...

### Environment

Browser: chrome
CesiumJS Version: 1.115.0
Operating System: macOS

**Comment by ggetz** [comment]
>  What we want is for the cylinder to be clamped to the terrain almost "painting" the mountain and to be 1000 meters above the center point.

Can you expand on this a little? 

Expected behavior of `CLAMP_TO_GROUND` is shown in [this example](https://sandcastle.cesium.com/?src=Geometry%20Height%20Reference.html). 

If instead you're looking for terrain classification, see [this example](https://sandcastle.cesium.com/?src=Classification.html.)

**Comment by parker-the-king** [comment]
Ok, so we want our cylinders to behave exactly as the squares in the
CLAMP_TO_GROUND example that you sent me. Instead of stopping when they hit
the ground,  they extend all the way into the ground and we can see the
part that's underground which looks weird.  We want the top of the cylinder
to extend 1000 m above the center point of the cylinder (which is touching
the ground) and we want them to extend all the way down to the ground, but
not through it.

**Comment by ggetz** [comment]
Gotcha @parker-the-king. Is it possible to use `RELATIVE_TO_GROUND` and offset the height by the half the height of the cylinder (500m in this case)?

**Comment by parker-the-king** [comment]
We tried what you said in the sandbox and it worked perfectly.(Pictured in
the second picture below) Then we copied the exact same code into our
application and for some reason we got a completely different result (The
first picture below) The cylinder and point are given the same
coordinates, however the cylinder a couple hundred meters southwest and
below the point. We've been looking through our code base for some weird
configuration that would make the cylinder appear like that but we
havent found anything.


[image: image.png]
[image: image.png]

Here's the code we used to render both images:
const greenCylinder = viewer.entities.add({
  name: "Green cylinder with black outline",
  position: Cesium.Cartesian3.fromDegrees(-111.78852417809316,
40.658894298281034, -500),
  cylinder: {
    length: 500.0 * 2,
    topRadius: 794.0,
    bottomRadius: 794.0,
    heightReference: Cesium.HeightReference.RELATIVE_TO_TERRAIN,
    material: Cesium.Color.RED.withAlpha(0.5),
  },
});

const whitePoint = viewer.entities.add({
  name:"White point",
  position: Cesium.Cartesian3.fromDegrees(-111.78852417809316,
40.658894298281034),
  point: {
    pixelSize:10,
    heightReference: Cesium.HeightReference.RELATIVE_TO_TERRAIN,
    color: Cesium.Color.WHITE,
  },
});

**Comment by parker-the-king** [comment]
After more testing, we've learned that for the cylinders on our app, if we
leave out the heightReference: Cesium.HeightReference.RELATIVE_TO_TERRAIN
line of code, the cylinder is no longer off center.

**Comment by ggetz** [comment]
Thanks for the update @parker-the-king. So the fundamental issue is that clamp to ground for cyllinders behaves slightly differently than the rest of the geometries? Or was this specific behavior tied to your app configuration? In the later case, I think the issue can be closed.

**Comment by parker-the-king** [comment]
I'm not sure if it's a problem with they cylinder itself or something to do
with our app. I ended up just using an extruded ellipse instead of a
cylinder and it worked perfectly for some reason.

**Comment by parker-the-king** [comment]
In sandbox everything works so i'm thinking it might just be some weird
thing with our application
