### ISSUE TITLE
viewer.ready is undefined

### ISSUE THREAD

**Issue by angrycat9000** [CesiumGS/cesium#11932]
### What happened?

`viewer.ready` is `undefined` instead of a boolean as indicated in the [documentation](https://cesium.com/learn/cesiumjs/ref-doc/Viewer.html?classFilter=viewer#ready)

![image](https://github.com/CesiumGS/cesium/assets/48362463/87af96e9-48f7-4242-b11c-2a5509b670c8)

### Reproduction steps

1. Create a new `Viewer` object.
2. check the `ready` property

Reports `undefined`.  Expectation is `true` or `false`

### Sandcastle example

https://sandcastle.cesium.com/https://sandcastle.cesium.com/#c=bY7NCsIwEIRfJeTUgmzw3LQIXgUPgqdc0nTV4DYpSdpSn97+XETd28zON4zxLiY2WBwxsJI5HNkRo+1buK5eprhZ9dG7pK3DoHheKGdmzhMC+Xu20RBQN1Ne8B2XMU2ElXJsvYNtOx8S6wNlACJh25FOGEXdmycmMDEulUtUik9UNnZgtin/bGCGdIzz59YTXewLFa+kmPM/KHndWHc/DxhIT0vssa9OmwkAUszyP5m8p1qHr+Y3

### Environment

Browser: Checked Firefox 124.0.1 and Chrome 123.0.6312.58 on Linux
CesiumJS Version: 1.116
Operating System:  22.04.1-Ubuntu

**Comment by jjspace** [comment]
It seems this was an issue of docs, not implementation. Two properties of `Terrain` were incorrectly attributed to the `Viewer`
