### ISSUE TITLE
Having trouble resolving compilation errors when installing version 1.115 of Cesium in Vue3 using npm.

### ISSUE THREAD

**Issue by guanzheyuan** [CesiumGS/cesium#11931]
### What happened?

In a Vue 3 framework, after installing version 1.115 of Cesium via npm, it was noticed that the structure of Cesium in the node_modules is different from the previous older version. As a result, errors occur during the run startup.

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
@guanzheyuan Could you give us some details about your `Vue` configuration, and what version you were using before?
