### ISSUE TITLE
Add serial numbers to each demo in Sandcastle

### ISSUE THREAD

**Issue by Hiwen** [CesiumGS/cesium#11946]
### Feature

Hi, there.
I found a lot of demos in the Cesium Sandbox! It made me feel a bit difficult to find an demo quickly, despite the search function.
So I thought of a way to improve this problem by adding a serial number to each demo. Just like this:
<img width="577" alt="sntosandbox" src="https://github.com/CesiumGS/cesium/assets/13505993/c0aac90f-97d0-475c-8b2b-88701b919c72">

**Comment by ggetz** [comment]
Thanks for the suggestion @Hiwen! 

We do agree that Sandcastle has grown to a point where we'll need to re-address the organization at some point. We'll likely address this as a holistic effort in the future.

**Comment by Hiwen** [comment]
谢谢，您的邮件我已经收到，收到邮件后，我会在第一时间回复您。祝一切顺利！
