### ISSUE TITLE
strokeWidth setting does not take effect

### ISSUE THREAD

**Issue by xuehuangzheng123** [CesiumGS/cesium#11945]
### What happened?

![image](https://github.com/CesiumGS/cesium/assets/127759655/350e9ef7-4aac-4d21-bcb1-911245266cd3)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
Hi @xuehuangzheng123, thanks for the report. 

This should be addressed with https://github.com/CesiumGS/cesium/issues/6694.

I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
