### ISSUE TITLE
How can set Material class->fabric->uniforms->texture  in repeat Mode ？default is clamp

### ISSUE THREAD

**Issue by liuyehua** [CesiumGS/cesium#11943]
> ### What happened?

I cant set texture in texture in repeat mode

> `const material = new Cesium.Material({
            fabric: {
                uniforms: {
                    color: Cesium.Color.fromCssColorString(color),
                    diffusePower: 2.0,
                    alphaPower: 1.2,
                    center: new Cesium.Cartesian2(0.5, 0.5),
                    globalAlpha: 1,
                    image: '/model/white.png',
                },     
                source: `
                    uniform vec4 color;
                    uniform vec2 center;
                    uniform float diffusePower;
                    uniform float alphaPower;
                    uniform float globalAlpha;
                    uniform sampler2D image;

                    czm_material czm_getMaterial(czm_materialInput materialInput) {
                        czm_material material = czm_getDefaultMaterial(materialInput);
                        float time = czm_frameNumber/600.;
                        float per = fract(time);
                        vec2 st = materialInput.st;
                        vec2 repeat = vec2(4.0);
                        vec4 ccc = texture(image, st * repeat);
                        float alpha = distance(st, center);
                        material.alpha = color.a * alpha * alphaPower * globalAlpha;
                        material.diffuse = color.rgb * diffusePower;
                        material.diffuse = mix(material.diffuse,ccc.rgb,.5);
                        material.alpha += ccc.a;
                        return material;
                    }
                `
            },
            translucent: true,
        });`

<img width="536" alt="image" src="https://github.com/CesiumGS/cesium/assets/27567569/d9701574-ac5c-469d-9cc0-b0652f96e88e">

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
