### ISSUE TITLE
Can the options in WebMapServiceImageryProvider support customTags field?

### ISSUE THREAD

**Issue by itancc** [CesiumGS/cesium#11956]
### Feature

Can the options in WebMapServiceImageryProvider support customTags field? 
I have an idea:  on WebMapServiceImageryProvider source may be able to add some UrlTemplateImageryProvider options？
![image](https://github.com/CesiumGS/cesium/assets/46319251/a9ce7e17-d2d7-4bfc-ac2d-01a868fc0c15)

**Comment by itancc** [comment]
I commit a PR for this issue,  I really need this change to facilitate my implementation of a feature，Many thanks.

**Comment by ggetz** [comment]
Hi @itancc! Thanks for the interest!

There is a `parameters` option which lets you append additional query parameters. Is that sufficient for your use? If not, could you please explain your use case a bit further?

**Comment by itancc** [comment]
Here is some pseudo-code：
```
const imageryProvider = new WebMapServiceImageryProvider({
  parameters: {
    bbox: "{customBBox}",
  },
  // @ts-ignore
  customTags: {
    customBBox: (
      imageryProvider: ImageryProvider,
      x: number,
      y: number,
      level: number
    ) => {
    const rect = imageryProvider.tilingScheme.tileXYToRectangle(x, y, level);
      // here I can do some custom logic, like transforming the bounding box
      const customRect = transformBboxFunction(rect);
      return `${customRect.west},${customRect.south},${customRect.east},${customRect.north}`
    },
  },
});
```

**Comment by ggetz** [comment]
>  For example, I need to modify the BBox parameters because I will be performing a coordinate transformation,

Thanks @itancc. This may be a bit of an edge case in my opinion. Given that you're re-writing one of the existing parameters, it may be better for you to use `UrlTemplateImageryProvider` directly.

**Comment by itancc** [comment]
I hope to make the most of some optimizations available in the existing WmsMapServiceImageryProvider, such as cache, which I find excellent! If I switch to using UrlTemplateImageryProvider, I might need to rewrite a whole set of code similar to WmsMapServiceImageryProvider. So, it would be convenient if such an option could be provided. Also, this shouldn't be disruptive, right?
