### ISSUE TITLE
RequetErrorEvent during Jest testing.

### ISSUE THREAD

**Issue by McKayMower** [CesiumGS/cesium#11965]
### What happened?

I am writing tests in Jest. 

I have a React component for the Cesium viewer:

```
import React from "react"
import { CesiumComponentRef, Viewer } from "resium"

import { terrain } from "@/lib/cesiumConfig"
import getWebGLStub from "@/lib/helpers/getWebGLStub"
import { cn } from "@/lib/utils"
import { Viewer as CViewer } from "cesium"

(window as any).CESIUM_BASE_URL = window.location.href ?? "/"

interface Props {
  children?: React.ReactNode
  className?: string
  testing?: boolean
}

const ForwardRefCesium = React.forwardRef<CesiumComponentRef<CViewer>, Props>(({ children, className, testing = false }, ref) => {
  return <Viewer ref={ref}
    contextOptions={testing ? {
      getWebGLStub: getWebGLStub
    } : undefined}
    className={cn('relative flex z-[0] overflow-clip flex-1', className)}
    full
    timeline={false}
    animation={false}
    baseLayer={testing ? false : undefined}
    baseLayerPicker={false}
    sceneModePicker={false}
    navigationHelpButton={false}
    fullscreenButton={false}
    geocoder={false}
    selectionIndicator={false}
    terrain={testing ? undefined : terrain}
    homeButton={false}
    infoBox={false}
    skyBox={false}
    scene3DOnly={true}
    automaticallyTrackDataSourceClocks={false}
    skyAtmosphere={false}>
    {children}
  </Viewer>
})

export default ForwardRefCesium

ForwardRefCesium.displayName = "Cesium"
```

Now, in my Jest tests, I am failing tests due to request errors. See the image below.

![image](https://github.com/CesiumGS/cesium/assets/47837070/32fb0891-d5a4-42f8-bcb8-6c7d84909978)

Something to note: I am testing in a headless environment so I use the getWebGLStub helper function found in the cesium repository.

Since I am testing in a headless environment window.location (which is used in the requests) will be undefined.  When I go to render my component, it appears the requests for imagery layers are sent off. How can I disable these requests? Since these requests throw the error seen below, the tests automatically fail. 

![image](https://github.com/CesiumGS/cesium/assets/47837070/79db64a4-b64a-4027-b2dc-7d10658c8109)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser: N/A
CesiumJS Version: 1.115
Operating System: Ubuntu 22.04.3 LTS

**Comment by ggetz** [comment]
Hi @McKayMower, you can turn off imagery by providing the option `baseLayer: false` to the viewer. 

In many CesiumJS tests, we also stub out web requests to help with reliability. The exact mechanic of how to do that depends on your particular app though.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
