### ISSUE TITLE
Can't find ion-sdk-widgets/Source/TransformEditor

### ISSUE THREAD

**Issue by TammyCT** [CesiumGS/cesium#11962]
I want to use this SDK, but got 404.

DOC: https://help.agi.com/STKWebVisualizationLibrary/TransformEditorViewModel.html?classFilter=TransformEditorViewModel

Repo: https://github.com/CesiumGS/cesium/blob/1.71/Source/Widgets/TransformEditor/TransformEditorViewModel.js#L392

**Comment by ggetz** [comment]
Hi @TammyCT! That documentation is for the [Cesium ion SDK](https://cesium.com/platform/cesiumjs/ion-sdk/), which is a separate, but related, project to CesiumJS. It's not open source.

I'm going to close this issue as it's unrelated to CesiumJS. If you have further questions, I would suggest asking on the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
