### ISSUE TITLE
PostProcessStage not work correctly

### ISSUE THREAD

**Issue by Pure0319** [CesiumGS/cesium#11972]
### What happened?

I want to obtain the coverage of the viewing volume from a specific camera angle through the post-processing stage. For example, the shader code MainMAX is a transformation matrix from the screen coordinate system to the camera's 0-1 coordinate system
My code works normally in the old version, but there are problems after updating to the latest version
But this will not get the correct result, or it can only be shown in some angles
``
uniform float myNear;
    uniform float myFar;
    uniform float mylog2FarPlusOne;
    uniform float z_offset;
    uniform sampler2D colorTexture;
    uniform sampler2D depthTexture;
    uniform sampler2D CameraDepthTexture;
    in vec2 v_textureCoordinates;
    uniform sampler2D videoTexture;
    uniform mat4 viewport_w;
    uniform mat4 MainMAX;
    
    float my_reverseLogDepth(float logZ)
    {
        float near = myNear;
        float far = myFar;
        logZ = pow(2.0, logZ * mylog2FarPlusOne) - 1.0;
        logZ = far * (1.0 - near / logZ) / (far - near);
        return logZ;
    }
    
    void main() {
        vec2  MainDepth=vec2(gl_FragCoord.x/viewport_w[0][2],gl_FragCoord.y/viewport_w[0][3]);
        float MainDepth1=czm_unpackDepth(texture(depthTexture, MainDepth.xy));
        float MainDepth2= czm_reverseLogDepth(MainDepth1);
        vec4 MainInfo1=vec4(v_textureCoordinates.x*2.0-1.0,v_textureCoordinates.y*2.0-1.0,MainDepth2*2.0-1.0,1.0);
        vec4 MainInfo7=MainMAX*MainInfo1;
        vec4 BaseColor = texture(colorTexture,v_textureCoordinates);
        MainInfo7 = MainInfo7/MainInfo7.w;
        if(MainInfo7.w+0.0005>0.0&&MainInfo7.x+0.0005>= 0.0&&MainInfo7.x-0.005<=MainInfo7.w&&MainInfo7.y-0.005<=MainInfo7.w&&MainInfo7.y+0.005>=0.0&&MainInfo7.z+0.0001<=MainInfo7.w&&MainInfo7.z+0.005>=0.0){
            out_FragColor =vec4(1.0,1.0,1.0,1.0);
        }
        else{
            out_FragColor =BaseColor;
        }
    }
![image](https://github.com/CesiumGS/cesium/assets/169238533/ee778be4-5832-420a-88da-2b898679dbba)

But strangely, when I add an entity, it works normally again. Why is that?
addXYZ(videocamera)
    {
      
          let position=new Cesium.Cartesian3();
          position.x=videocamera.CameraPos.x;
          position.y=videocamera.CameraPos.y;
          position.z=10000;
          let  hprRollZero = new Cesium.HeadingPitchRoll(); //不做欧拉角旋转
          let convert=Cesium.Transforms.eastNorthUpToFixedFrame;
          let modelmatrix=Cesium.Transforms.headingPitchRollToFixedFrame(position,hprRollZero,Cesium.Ellipsoid.WGS84, convert);
          let BiaoDingCoordinate=new Cesium.DebugModelMatrixPrimitive({
      
              modelMatrix : modelmatrix,
            //  length : 100.0,
              width : 0.000001
          });
          viewer.scene.primitives.add(BiaoDingCoordinate);
    }
![image](https://github.com/CesiumGS/cesium/assets/169238533/2bcb6435-adc8-4e8c-8f7d-13ebcec604de)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:1.115
Operating System:

**Comment by ggetz** [comment]
Thanks for the report @Pure0319.

> My code works normally in the old version, but there are problems after updating to the latest version

Can you please provide the specific version numbers this is working in and not working in?

**Comment by Pure0319** [comment]
> Thanks for the report @Pure0319.
> 
> > My code works normally in the old version, but there are problems after updating to the latest version
> 
> Can you please provide the specific version numbers this is working in and not working in?
The old version is 1.58 very old work in
but 1.115 not work

**Comment by Pure0319** [comment]
# # @ggetz 
The old version is 1.58 very old version but work
 1.115 not work

**Comment by Pure0319** [comment]
@ggetz 
The old version is 1.58 very old version but work
1.115 not work

**Comment by Pure0319** [comment]
I guess there is a problem in executeCopyDepth step ，so i can not get right depth in my shader

**Comment by ggetz** [comment]
Thanks @Pure0319. This is likely related to https://github.com/CesiumGS/cesium/issues/11067.

I'm going to go ahead and close this issue in favor of #11067 to keep discussion in one place.
