### ISSUE TITLE
`WallGraphics`'s Property `outlineWidth` do not work

### ISSUE THREAD

**Issue by s3xysteak** [CesiumGS/cesium#11971]
### What happened?

expect:
The `outlineWidth` property of `WallGraphics` should work when set a number.

actually:
It is nothing happened when set `outlineWidth`.

### Reproduction steps

See line 25 in the reproduction, it has set outlineWidth but nothing happened to the wall entity.

### Sandcastle example

https://sandcastle.cesium.com/#c=nVLRTsIwFP2Vmz2NBDoIJsYxiAYJPhhN1OiD86Fsd6yxa0l7B5mGf7djEBEJifap99xzTk96b6KVJVgKXKGBIShcwRitKAv2vMH82Es29Vgr4kKhib3WIFaxSjZKVCiocsrGgqEiQQIt42nqf8YKQPECQ4i9qUFUsOJSQmZ0AbY0GU8QVoJy0CVJZx577VpSk0LYqAEW2jpH91i4SzbmhtyNqz6rna5x7qztlTG8ukExz8n6r40WoNPrnrNue1ee9feKXrc+e0Dn4t/c7knuQYg/kU+keGttLwUnNILL7y/SUhs2fZhM7raU7Q+HQKbEn9iLSCkPnXmNrl1v3Ux4O9JMVk/abwbdGnhtL7JUSRztQl2KYqENQWmkz1hAWCyky2ODWZm8I7HE2tqvpkbBvjRKxRJEOjyyYpBIbq3rZKWUj+LDbcYoChz/l1Rqngo1v1+ikbyqaXlvdNuAjLEocOVxJWktZ9wcOH8B

### Environment

Browser: 
Microsoft Edge
版本 124.0.2478.80 (正式版本) (64 位)

CesiumJS Version:
v1.117

Operating System:
Windows 10 22H2
19045.4291

**Comment by syzdev** [comment]
CC #40

**Comment by s3xysteak** [comment]
> CC #40

Thank you, I think this is a duplicate of the referred issue.
