### ISSUE TITLE
`scene.pickPosition` not work on `entity.point`

### ISSUE THREAD

**Issue by s3xysteak** [CesiumGS/cesium#11984]
### What happened?

scene.pickPosition a `entity.point` will always return undefined but works well on `entity.label`.

### Reproduction steps

1. Click the point and you will find out console log a `undefined`
2. Click the label then it will log the Cartesian3 where you clicked.

### Sandcastle example

https://sandcastle.cesium.com/#c=dVJdi9swEPwral5OBldOe+1L6oS2vhw1DclBzEHBEGR5k4jIkpFk53xH/nvlj4RwTR8stOud2dlZMSWNRTWHI2g0RRKOKALDq4I8dzmcjlgXR0payiXodOR9S2UqWYcEabltHLKnIF3MwRCa5/gtlQiVyriMkpNr8ohq625U3uMvm/F43H4+unX1/J6ESztBHaGL+AuINX+FCbof+30u54ZmAh6gtPsEjH3gxlLJXMmyKjKn7Gm1jpP4eb6Jl4/xMk7+dMBTdwqagbjQW3hxve4iwdkBFfDhbmhh9ur4k7LDTqtK5hNkdQX+laLVdmvA3p7zM3ZDffw6jNN2PXmti4NtW9EkCvdm9vaeDd5TmYv3u1kzDSDXJWUwrx3qV1+EBzZGZU1Ny9NqS+XAQZy6WJaV/cHahWD8dlkOOnloOusNaPsqAUSo3ZnQMJBASufH0wDAZ6Tnxjj5/xOWNCWQxfwx2USLOPrdShr5o9DYRsCsl4fQd16USltUaYEJCSwUpaDOtiCr2AEsYeYySxhcQ8Oc14jn0xtvFDFBjXF/tpXonko6moWBq/8HKhTNudytatCCNm3Z/tNs0ScJIWHgwttIq5TIqH7H/Bc

### Environment

Browser: Edge 124.0.2478.97
CesiumJS Version: 1.117
Operating System: Windows 11 23H2 22631.3447

**Comment by ggetz** [comment]
Good news @syzdev, I believe this is fixed with https://github.com/CesiumGS/cesium/pull/11983 which was just merged into main. The fix should go ut with the next release on June 3.
