### ISSUE TITLE
clamp_to_ground doesn't work, point can't clamp to 3dtile

### ISSUE THREAD

**Issue by YHLpuyu** [CesiumGS/cesium#11999]
### What happened?

I add a entity with point, and set `heightReference` to `CLAMP_TO_GROUND`, in scene i add both terrain and 3dtile, but the entity is just clamp to terrain not 3dtile. the sandbox [clamp to ground](https://sandcastle.cesium.com/index.html#c=zVVdbxo5FP0rFurDsKKGQAgkC9FSIJvREojCNFElJGo8F8aqxx7ZHkha8d/X85XMpHS1j+UF+95zrs89/hgqhTZoz+AACg2RgAMag2ZxiB/TmLOq0XQ+lsIQJkCtag30YyUQMqCUjVwVBC+b462S4ZNU3M8DTr2xEsf6nyuRLYM1BQF4x+UGsA+RCTzQZrSzUG1yjpViVAyW02yeYOlAHoZbwnWCMOolE0TTXgzjoMHYCuRAmCnUZX+diZelU5WuFCNtJ67vnLf6FxeJRoQq60WKhcywPWhMfN/Ji1eA36UMPVlOHRElhgbIsc1IVX9TJzlgLnfO12mSQFwSn4ldIfkKffiRMo5fsyorYT0jCgVE+Pz9/iypAhDLiFCY7kGY2wzkVORTYgvoTG5eBScNiyg2I2qYFM42FukAOaHcQ2gr5YILQw/RsGoJo9/upWYpu+DgKI9kaxVcSpSRw2ILkslOkShgNPU/CdgUEc4hKvMKm1K2HYkdM7EPf5z1W807YgJ87/4HnJhfoI+NX3nnvUSAZ9Mbbz2eueN/EvhKZB3wZ219zw2wUNtkfhZyk5KfICFcoVXNgu31eIsXprzekdeOO6kBE9hZIdr52Ovi7mWv3e61zvvt9lm300DnLdzq9C/6nd5l76LVuezWK4WZsOelJMHG2DPwJftulXQb5QSVXKo3CckMP0wnFYyMDbe3e3wC+nTretNT4Cfmm+AKtSu5ANguMA+wBQWCwmut22ocj2eju/u1t1j//bD4PK+K8ZkmGw6T4m2YMG1IWmwehxu7D/eLpeu5j9O1O79x5673pUQ/lsacbIC/s8nAszm1VwhtpUgzZ+eRQaEUUicH5B1Imxf+1tUsWWCZhPCNO5utR/PJevHZm7nz/+/YHpRhlPCFYrvSc/pYCeNPC89b3DV+2vDFdps+HaWX4fWQtZ1WA328rP9mG1QM7Teh1qgNUkevi+BfLIykMihW3MG4aSCM7I0G3dzE9Jt9t6nWxd0fNMvUgc/2iPnDEx8sRDnR2ma2MU9vyKp2PWha/E/U/EVe2D3h5CWBBWfXsyyIMR407fQ000jJN0S9q/wvl)
![QQ截图20240524102135](https://github.com/CesiumGS/cesium/assets/8923933/b9410618-73c6-4059-b5e8-f3b3dc28e5ff)

### Reproduction steps

1. add terrain
2. add 3dtile
3. add entity with points
4. set `heightReference` of point to `CLAMP_TO_GROUND`

### Sandcastle example

https://sandcastle.cesium.com/index.html#c=zVVdbxo5FP0rFurDsKKGQAgkC9FSIJvREojCNFElJGo8F8aqxx7ZHkha8d/X85XMpHS1j+UF+95zrs89/hgqhTZoz+AACg2RgAMag2ZxiB/TmLOq0XQ+lsIQJkCtag30YyUQMqCUjVwVBC+b462S4ZNU3M8DTr2xEsf6nyuRLYM1BQF4x+UGsA+RCTzQZrSzUG1yjpViVAyW02yeYOlAHoZbwnWCMOolE0TTXgzjoMHYCuRAmCnUZX+diZelU5WuFCNtJ67vnLf6FxeJRoQq60WKhcywPWhMfN/Ji1eA36UMPVlOHRElhgbIsc1IVX9TJzlgLnfO12mSQFwSn4ldIfkKffiRMo5fsyorYT0jCgVE+Pz9/iypAhDLiFCY7kGY2wzkVORTYgvoTG5eBScNiyg2I2qYFM42FukAOaHcQ2gr5YILQw/RsGoJo9/upWYpu+DgKI9kaxVcSpSRw2ILkslOkShgNPU/CdgUEc4hKvMKm1K2HYkdM7EPf5z1W807YgJ87/4HnJhfoI+NX3nnvUSAZ9Mbbz2eueN/EvhKZB3wZ219zw2wUNtkfhZyk5KfICFcoVXNgu31eIsXprzekdeOO6kBE9hZIdr52Ovi7mWv3e61zvvt9lm300DnLdzq9C/6nd5l76LVuezWK4WZsOelJMHG2DPwJftulXQb5QSVXKo3CckMP0wnFYyMDbe3e3wC+nTretNT4Cfmm+AKtSu5ANguMA+wBQWCwmut22ocj2eju/u1t1j//bD4PK+K8ZkmGw6T4m2YMG1IWmwehxu7D/eLpeu5j9O1O79x5673pUQ/lsacbIC/s8nAszm1VwhtpUgzZ+eRQaEUUicH5B1Imxf+1tUsWWCZhPCNO5utR/PJevHZm7nz/+/YHpRhlPCFYrvSc/pYCeNPC89b3DV+2vDFdps+HaWX4fWQtZ1WA328rP9mG1QM7Teh1qgNUkevi+BfLIykMihW3MG4aSCM7I0G3dzE9Jt9t6nWxd0fNMvUgc/2iPnDEx8sRDnR2ma2MU9vyKp2PWha/E/U/EVe2D3h5CWBBWfXsyyIMR407fQ000jJN0S9q/wv

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by YHLpuyu** [comment]
Browser: Microsoft Edge 125.0.2535.51 x64
CesiumJS Version: 117
Operation System: win10 home 22H2

**Comment by ggetz** [comment]
Hi @YHLpuyu, clamping is not enabled on all 3D Tiles by default for performance reasons. You'll need to provide the option `enableCollision: true`.  

See [this updated example.](https://sandcastle.cesium.com/index.html#c=zVVtbxo5EP4rFuqH5UQNgRBIDqKjQC6rIxCFbaJKSNR4B9aq117ZXkha8d/P+5bspvR0H8sX7JnnGT8zY89SKbRBewYHUGiIBBzQGDSLQ/yY2pxVjab7sRSGMAFqVWugHyuBkAGlrOWqIHjZHm+VDJ+k4n5ucOqNlTjW/1yJ7BisKQjAOy43gH2ITOCBNqOdhWqTc6wUo2KwnGbzBEsH8jDcEq4ThFEvmSCa5mIYBw3GRiAHwkyhLvvrTLzMnap0pRhpu3F957zVv7jIEwNBNhzGknOmmbQJJlISR5oEQhVBkWIhM2wPGhPfd/LTK8DvUoaeLLuOiBJDA+TYbKWqv8mXHDCXO+frNHEgLonPxK7I6Qp9+JEyjl+zKCthi0oUCojw+fsGLqkCEMuIUJjuQZjbDORU5FNiA+hMbh4FJxURUWxG1Nj0nW0s0gVyQrmH0EbKBRcVP0TDakkY/XYvNUvZBQdHuSU7q+BSoowcFj1KNjtFooDRtEGJwbqIcA5RmVeUKWXbldgxE/vwx1m/1bwjJsD37n/AifkF+tj4Ve28lwjwbHrjrcczd/xPAl+JLAP+rG3d8wJYqE0yvwt5kZKfICFcoVXNgu37ebMXRXl9RK8Zd9ICTGBnhWjnY6+Lu5e9drvXOu+322fdTgOdt3Cr07/od3qXvYtW57JbrwRmwt6XkgRrY8/Al+y7VdJtlB1UcqneJCQ7/DCdVDAyNtw+//EJ6NOt601PgZ+Yb4Ir1K74AmC7wDzAFhQICq+xbqt2PJ6N7u7X3mL998Pi87wqxmc6eaKTYnhMmDYkDTaPw43tw/1i6Xru43Ttzm/cuet9KdGPpTUnG+DvymTg2ZzqFUJbKVLP2XlkUCiF1MkFeQfS5oW/ZTVLDlgmJnzjzmbr0XyyXnz2Zu78/1dsD8owSvhCsV1p3j5WzPjTwvMWd42fGr7YbtPRUZoMr5es7bQa6ONl/TdrULG087bWqA3Sil4Xxr9YGEllUKy4g3HTQBjZFw26uYnpNzvYqdbF2x80y9SBz/aI+cMTXzREOdHaerYxT1/IqnY9aFr8T9R8Ii9sTzh5SWDB2fUsM2KMB027Pc00UvINUe8i/ws)
