### ISSUE TITLE
GroundPrimitive Merging Geometryinstances Picking up attribute information is disorderly

### ISSUE THREAD

**Issue by 956740472** [CesiumGS/cesium#12004]
### What happened?

The issue of merging geometryinstances, rendering GroundPrimitive, and picking up attribute information in click events is confusing, which has existed for a long time. The current solution is to render GroundPrimitive individually, which results in poor performance. If it cannot be fixed, it should be pointed out in the document to avoid discovering the problem halfway through the project. I hope the official team can fix the bug as soon as possible.

**This is the testing address: [click to jump to](https://sandcastle.cesium.com/#c=zVfbbuM2EP0VIYvCMuDQut/WSZt10yZoFg2aoC+bRUFLlM1GJgWSdtYt8u8d3WxZkQJ08xLagEnOmRly5nBIazFnUmlbSp6I0M40Rp60OZF0s0Z/lnP6KC6Hc84UpoyI0UT794FpdaMs5Z/4t0hLcSbJpBI8j6vfyiqSMWEELTO+ICghuVrdE6kulmBNqnsiBHTAsxIbUqlNp9VvtbQl4WuixM48Xt0tz3ZLzn6tpXprTXkluqJEYBGvdlGP3l6oH/SKVqPmWCjoYWajVPD1z2QpCJEXsNad/uVYo2iOj7zA8HxzovnI9dzAdie9KD+wDNsrUJ7lm4DvRQWWZXlOacsNTd8esGWaXhiWKNOxzLCD+jo+jMedxBxH1nrfkQ0M2wqtMmZ26IQD0QhNz3HcAuUbvjME8qwAZGX4Hd90BsJvh35Yhd8Lbdv87sDa7zuwvum5YUlG13B8e5CMFcdcxzKGIMBSw60MmUE4EFbfNT27zKPjBBD/7w6r8875atu251cxA/4MVIIQYhZUVDRDIxgibGgHFatdz7dMbyD+nmm7Ve0xrND/H4E9LrVFQcYsJp1S20T2uha3I9zkJDrU6ZZ7mkTayBz1ZrNxZr3FmdV1Zr3uzH6LM7vrzH7dmfMWZ07XmTN6NXe5oGuq6JZ0nAq+YcltI+zz2axHRtqXPQMmh/wcuvah63xtrQ/nOcGimD46YJ+xIoLi7GIvbrsv2rpG9Kp1wUVL8ULQONJ6REVTuxyWMJrzjIvRpB+zYTTlYi0HjVQxBQvRvgYUo/L4z6UsB3dKULbUR2K5wLrl2pPiYyB/PBr3G31+Od2Zem5pPo9fe0ntUy0RThJ9P+zlxQqzJOs+7e5iKGLsLscxudwSpq4qkH7kJsZsi2VttDaDJFHXLN+oi1hRznSy1c7O24GsyUjjR/B4vGqYAzzKuaSFbmu702mjV8v6dG9r2YCNwgDPCMo4pIUmo0mh8yOiSQuT8Hizhu2iJVGXGSm6n3bXCeDhFTsaI8rgfXt1//kG/DfqdR4mQ6G7B8qhm8tf7v+a31zPf+vkoN5FjNdwyRTBKx7VbWIn8BSmDBebiV6/cvTy0rCDoszblum70LM8uJaRO25RnQsKq6oNdhi+IjgB2katk7ZCiv8Bs5hJHe6tY1vlFUpVvBrSOHUMZHU1BM+yIQWjTfKG4ieTk5lUu4ycN8Kf6DrnQmkbkekITRVZ5xlUBTldbOJHolAs5fhjA/5QpOoaMtjdbsOSSMML4MZGkY/HAMXzSDONHzrTGUlV3/wCx4/Lsp6e1vWhPP7GRKu/KBh3VGrcB8NIwjTtCFP4S3Uq6T9Qsiwj/9aRPtFErQrJS9GK0OWqXOJLWUIlxAoukjQjXdnfGyBbuoPVMwUkiTQ4XFBrOyic0SU7pRB02YOoszabtjM2S+gWbqmzh5POn8WHEy3OsJQgSTdZdgebfTg5n00B/0I14yU7f98SARsoYCvz/KaaRAjNpjDs11ScZwssBi03BAHAPCtKk+Ll+Y5mMseswtBKDvuCqSM7/wE)**

**After clicking to pick, the current geometric ID will be displayed, and clicking from any perspective will cause confusion.**

### Reproduction steps

The issue of merging geometryinstances, rendering GroundPrimitive.
After clicking to pick, the current geometric ID will be displayed, and clicking from any perspective will cause confusion.

### Sandcastle example

https://sandcastle.cesium.com/#c=zVfbbuM2EP0VIYvCMuDQut/WSZt10yZoFg2aoC+bRUFLlM1GJgWSdtYt8u8d3WxZkQJ08xLagEnOmRly5nBIazFnUmlbSp6I0M40Rp60OZF0s0Z/lnP6KC6Hc84UpoyI0UT794FpdaMs5Z/4t0hLcSbJpBI8j6vfyiqSMWEELTO+ICghuVrdE6kulmBNqnsiBHTAsxIbUqlNp9VvtbQl4WuixM48Xt0tz3ZLzn6tpXprTXkluqJEYBGvdlGP3l6oH/SKVqPmWCjoYWajVPD1z2QpCJEXsNad/uVYo2iOj7zA8HxzovnI9dzAdie9KD+wDNsrUJ7lm4DvRQWWZXlOacsNTd8esGWaXhiWKNOxzLCD+jo+jMedxBxH1nrfkQ0M2wqtMmZ26IQD0QhNz3HcAuUbvjME8qwAZGX4Hd90BsJvh35Yhd8Lbdv87sDa7zuwvum5YUlG13B8e5CMFcdcxzKGIMBSw60MmUE4EFbfNT27zKPjBBD/7w6r8875atu251cxA/4MVIIQYhZUVDRDIxgibGgHFatdz7dMbyD+nmm7Ve0xrND/H4E9LrVFQcYsJp1S20T2uha3I9zkJDrU6ZZ7mkTayBz1ZrNxZr3FmdV1Zr3uzH6LM7vrzH7dmfMWZ07XmTN6NXe5oGuq6JZ0nAq+YcltI+zz2axHRtqXPQMmh/wcuvah63xtrQ/nOcGimD46YJ+xIoLi7GIvbrsv2rpG9Kp1wUVL8ULQONJ6REVTuxyWMJrzjIvRpB+zYTTlYi0HjVQxBQvRvgYUo/L4z6UsB3dKULbUR2K5wLrl2pPiYyB/PBr3G31+Od2Zem5pPo9fe0ntUy0RThJ9P+zlxQqzJOs+7e5iKGLsLscxudwSpq4qkH7kJsZsi2VttDaDJFHXLN+oi1hRznSy1c7O24GsyUjjR/B4vGqYAzzKuaSFbmu702mjV8v6dG9r2YCNwgDPCMo4pIUmo0mh8yOiSQuT8Hizhu2iJVGXGSm6n3bXCeDhFTsaI8rgfXt1//kG/DfqdR4mQ6G7B8qhm8tf7v+a31zPf+vkoN5FjNdwyRTBKx7VbWIn8BSmDBebiV6/cvTy0rCDoszblum70LM8uJaRO25RnQsKq6oNdhi+IjgB2katk7ZCiv8Bs5hJHe6tY1vlFUpVvBrSOHUMZHU1BM+yIQWjTfKG4ieTk5lUu4ycN8Kf6DrnQmkbkekITRVZ5xlUBTldbOJHolAs5fhjA/5QpOoaMtjdbsOSSMML4MZGkY/HAMXzSDONHzrTGUlV3/wCx4/Lsp6e1vWhPP7GRKu/KBh3VGrcB8NIwjTtCFP4S3Uq6T9Qsiwj/9aRPtFErQrJS9GK0OWqXOJLWUIlxAoukjQjXdnfGyBbuoPVMwUkiTQ4XFBrOyic0SU7pRB02YOoszabtjM2S+gWbqmzh5POn8WHEy3OsJQgSTdZdgebfTg5n00B/0I14yU7f98SARsoYCvz/KaaRAjNpjDs11ScZwssBi03BAHAPCtKk+Ll+Y5mMseswtBKDvuCqSM7/wE

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
To clarify, is this an issue that when picking from a low angle, sometimes the proper primitive is not picked?

The root cause of that is the stencil rendering approach, made worse by https://github.com/CesiumGS/cesium/issues/8480.

**Comment by ggetz** [comment]
There hasn't been any activity on this item recently. 

If you'd like to add more information about your use case, that may help us prioritize.

If you are interesting in contributing, please let us know and we'd be happy to discuss implementation or review a PR. 

Thanks!
