### ISSUE TITLE
`time` param of CallbackProperty.Callback should be optional

### ISSUE THREAD

**Issue by anne-gropler** [CesiumGS/cesium#12009]
### Feature

According to the [current signature](https://cesium.com/learn/cesiumjs/ref-doc/CallbackProperty.html#.Callback), the callback has 2 params:
1. `time`, of type `JulianDate`
2. `result`, an optional object

This implies that every CallbackProperty is time dependent. But this is not necessarily the case, as shown in [this Sandcastle](https://sandcastle.cesium.com/#c=rVLBTgIxEP2VcS/bjTgbRCDAQkwwnkw0MfG0l9IdsKHbkraLouHf7e4KMYon7WHSmb735nVaYbTzsJX0QhamoOkF5uRkVeJTU2N5JJp8brTnUpPNo2SS61yLhqn4glQgtgpI2ksvySEvCvaea4CNcaFi9PigO+fWhx3XPVxaU97QyhI5djHsY3dw1R0Mhh3ojXDUv6xX0qlFmi5jaAQBPL368Verc67Ugov1gzUbsn7HWhwAS2A6O9G4kM5zLegIhL+4a9fnBAQvyXI8XPsISNCbW/lKBbtM4BxiKOPj2ZIrR59ZK7kPcd/OOdf/NNtg/Or3ccZvxpQg9Vn83UD90EYRKrNiDRPbWPNwRf6Jq4qYrpRKkknUiTLnd4pmh8tdy3JjrIfKKoaYeio3igeX6aISa/IonKv71NAs/UrNCrkFWUxP/EAQijsXTpah66N8ozyaZWnA/6AqwwupV/dbsorvathzd3bXFhExS0N6mumNCZ/KflP+AA).

In my local app, I have the use case that sometimes, I need to get the current value of such a property elsewhere. I can do this using `getValue(time)`, although I don't need `time`, so I just pass `undefined` instead. However, I am using Typescript strict type checking, so the ts compiler does not allow me to pass `null` or `undefined` or anything other than a JulianDate. My current workaround is to write `getValue(undefined!)` , which is syntactically correct, but looks confusing at best, but mostly it looks wrong.

Would it be possible to make the `time` parameter optional, just as the `result` parameter? Or would that break something?

**Comment by ggetz** [comment]
Thanks for the suggestion @anne-gropler! I think it would be fine to mark the time parameter in the callback function signature as optional. We'd be open to review a PR.

However, I think the ` getValue` function would at least need to define a default time to use if undefined. Otherwise, this may break existing callback function that require the time parameter.

**Comment by anne-gropler** [comment]
> We'd be open to review a PR.

I opened #12099 for this.
