### ISSUE TITLE
DEFAULT_VIEW_RECTANGLE parameter doesn't work as expected

### ISSUE THREAD

**Issue by onderaltintas** [CesiumGS/cesium#12011]
### What happened?

Camera sets view on wider extent instead of given.

### Reproduction steps

1. Open sandcastle example
2. Run
3. Expected: Camera fits to Turkey.
...

### Sandcastle example

https://sandcastle.cesium.com/#c=fVPbbtpAEP2VFS8YCa1VmuaBEtQE3BaJXAQpeUGKBnsw2653rd0xlFb59w4Gp8TQ+m3PnHPmaqGRxMiTuBID9KrI5ARjApNqlEtnsyGmDtEHncv2+8v2xYf2Raf1cW4Efwf+ADJ0IIfR5+tv48fn2Sh6ep5Eg8fruy/jiG3Z/CCIreFEa4UbdBwwuKk8ZiUWNOPyObCGQBl0zbb4vZcKAUZlQMqa7hK0x3aFp2hjm6CrwctCax9z6eamIGKVeBtfgMcxbNE9qPgHq2vhlc3wvFCZpb2xP+uwj9HgLRdy3s+j5rFy9SOTqBjInjBIZai56TpuYK1S2Es9uaJ08SOjSIHW25nyaqH/o/qKOj/fiV/ZzQQNz25sbR45Z50/5UBiN/6f0+seb3GUQYpuWwaCI/w+RzMl3gXdQn4gPTi7Vpw6eF2wEIXToiuaK6Lcd8MQJCm+QstqX6ozyKV1adisJC+t1ukCulXaaYXI6SC6izrDVy4bcf7v+428aeEJF7foygX9ZQStvfBld/mNdqPnaauxX7l9UlluHe3KD6QMCbNcA6EPFwWfAsnY++qX6YXH0l6i1kIlV/NG7e7nDRFr8J4juzueql84b/R7IfNPpNpCokx6v0anYbujrd71x3tQStkL+XleSdbqBbia8x8

### Environment

Browser: Chrome 
CesiumJS Version: 1.117
Operating System: Windows 11

**Comment by GatorScott** [comment]
This is really a question for the forum, however setting 
Cesium.Camera.DEFAULT_VIEW_FACTOR = 0.0;
should give you what you want.

**Comment by ggetz** [comment]
Thanks @GatorScott. @onderaltintas CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
