### ISSUE TITLE
I have problem with visitTile, visitlfVisible, visitVisibleChildrenNearToFar

### ISSUE THREAD

**Issue by JHP0124** [CesiumGS/cesium#12024]
### What happened?

![이미지 20240605007](https://github.com/CesiumGS/cesium/assets/105851614/948148e1-b1e9-4c28-9f5d-61e33341d7d0)
![이미지 20240605011](https://github.com/CesiumGS/cesium/assets/105851614/c6b6de16-a48f-4969-a3fb-a342cdec8cf2)
![이미지 20240606003](https://github.com/CesiumGS/cesium/assets/105851614/e7d1ca6c-9f77-431f-9727-72a0833625b8)

this picture is chrome developer tools picture 

cesium js is repeat with visitTile과 visitlfVisible, visitVisibleChildrenNearToFar in red area and yellow area

this is nomal and correct?

my cesium is too slow.

if i moving in map, chrome browser is show me slowly the map

what’s problem??

### Reproduction steps

1. i just move the map in cesium js
2.
3.
...

### Environment

Browser: chrome
CesiumJS Version: 1.92
Operating System: window server 2019

**Comment by javagl** [comment]
Just a cross-link to https://community.cesium.com/t/i-have-problem-with-visittile-visitlfvisible-visitvisiblechildrenneartofar/32694

**Comment by JHP0124** [comment]
> Just a cross-link to https://community.cesium.com/t/i-have-problem-with-visittile-visitlfvisible-visitvisiblechildrenneartofar/32694
i modified my article
