### ISSUE TITLE
Icons missing in deployed sandcastle

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#12026]
### What happened?

I guess that's another instance of the "gulp src encoding" issue (similar to https://github.com/CesiumGS/cesium/issues/12022 and others): The icons are missing in the Sandcastle:

![Cesium Sandcastle Icons Missing](https://github.com/CesiumGS/cesium/assets/5597569/7ec4d89d-85f8-4ee8-80ee-dc9335a56984)

### Reproduction steps

Visit https://sandcastle.cesium.com/index.html (maybe disable caching...)

### Sandcastle example

https://sandcastle.cesium.com/index.html

### Environment

N/A, this is about the deployed Sandcastle of 1.118

**Comment by jjspace** [comment]
@ggetz this is another annoying gulp issue with how they corrupt data now right?

**Comment by ggetz** [comment]
Yes, in this case the `ThirdParty` copy step during the `buildSandcastle` function. I _think_ it's safe to provide `, { encoding: false }` even though there are non-binary files being copied in that step.
