### ISSUE TITLE
加载了倾斜摄影，有时候会卡死

### ISSUE THREAD

**Issue by spting0430** [CesiumGS/cesium#12037]
### What happened?

我加载了一个3dtileset的倾斜摄影，大概7G左右大小的，能够正常加载，但是在拖拽的时候，会出现卡死的现象，也没有报错，cpu和内存没有爆满，出现卡死的情况有时候拖拽到倾斜摄影上的时候会卡死，有时候刚显示出来就卡死，所以这是什么问题呢，是配置问题还是什么，因为没有报错信息，所以不知道该怎么去查

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:1.114
Operating System: chrome 125.0.6422.142

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. 

Additionally, would you be able to include a [Sandcastle example](https://sandcastle.cesium.com/) that replicates the issue? That would help us give us more context to determine the issue. 

Thanks!
