### ISSUE TITLE
Regression for rendering between 1.117 and 1.118

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#12041]
A user provided a glTF model at https://community.cesium.com/t/measurment-tools-stopped-working/32962/12 
When uploading this to Cesium ion and tiling it as 3D tiles, this is the result:
[Forum 32962 4x panel stojak as 3D Tiles.zip](https://github.com/user-attachments/files/15901780/Forum.32962.4x.panel.stojak.as.3D.Tiles.zip)

Here is a comparison of the model rendered in 1.117 and 1.118:

![Cesium Forum 32962 compare 117 to 118](https://github.com/CesiumGS/cesium/assets/5597569/08c165d5-0cb5-446b-95df-674d51324c67)

The actual model is stored as a composite tile. For convenience/debugging/analyzing that, I extracted the GLB parts from that, including the JSON parts of the GLBs, attached here:

[Forum 32962 composite elements.zip](https://github.com/user-attachments/files/15901924/Forum.32962.composite.elements.zip)

The GLBs are using (Draco and) the rendering-related extensions
```
    "KHR_materials_specular",
    "KHR_materials_ior",
```
which might help to narrow down where the error was introduced. I didn't do a bisection or analysis of https://github.com/CesiumGS/cesium/compare/1.117...1.118 yet, but maybe someone already has an idea based on the description here.

**Comment by jjhembd** [comment]
The model has the following value set in the `KHR_materials_specular` extension:
```json
        "KHR_materials_specular": {
          "specularColorFactor": [
            2,
            2,
            2
          ]
        },
```

Before version 1.118, CesiumJS did not support this extension at all. 

If I remove the `specularColorFactor` from the glTF and load in 1.118, the model renders as before:
![image](https://github.com/CesiumGS/cesium/assets/41167620/cda74ec3-8dde-489b-a812-77b4afa44d94)

It is not immediately clear to me what the impact of the `specularColorFactor` _should_ be in this case. But we could potentially have an error somewhere in https://github.com/CesiumGS/cesium/pull/11970

**Comment by javagl** [comment]
The [`KHR_materials_specular`](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md) extension spec is... quite elaborate and math/shader-heavy, so I can not quickly say anything profound. A few things that caught my attention:

- The [`specularFactor`](https://github.com/KhronosGroup/glTF/blob/cc633b8fdff15d4b0e062402d04c664191213c35/extensions/2.0/Khronos/KHR_materials_specular/schema/material.KHR_materials_specular.schema.json#L8) is constrained to `minimum:0.0, maximum:1.0`
- The [`specularColorFactor`](https://github.com/KhronosGroup/glTF/blob/cc633b8fdff15d4b0e062402d04c664191213c35/extensions/2.0/Khronos/KHR_materials_specular/schema/material.KHR_materials_specular.schema.json#L21) does **not** have a `maximum`. I found that strange at the first glance, and considered that this might have been omitted accidentally, **but...**
- Quickly skimming over the spec text brings up the [Materials with reflectance parameter](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md#materials-with-reflectance-parameter) section, which says
  > ... Typically, the reflectance ranges from 0% to 8%, given as a value in range [0,1], ...
  > ...
  > Therefore, by encoding an additional constant factor of 2 in `specularColorFactor`, we can convert from reflectance to specular color without any loss.

So that might explain where these `2, 2, 2` are coming from (and why there is no `maximum: 1.0` ... even though I'd ask whether there should be a `maximum: 2.0` then ...).

Maybe the possibility of these values being >1.0 is not taken into account properly. 

(As a preliminary workaround, I posted a version of the model in the form where the `KHR_materials_specular` extension was removed, just to at least have the _option_ to render it properly (or at least "better") for now...)
