### ISSUE TITLE
Horrible performance when Google 3D + clamped to ground (or relative) 3D models are drawn

### ISSUE THREAD

**Issue by matvey-tk** [CesiumGS/cesium#12055]
### What happened?

After upgrading Cesium we are experience horrible performance when even one clamped-to-ground or relative-to-ground 3D model Entity is added to the scene alongside the Google 3D Tileset.

Downgrading to 1.110.0 returns the original performance.

### Reproduction steps

1. Render Google 3D Tileset
2. Render any 3D model using clamp-to-ground height-ref
3. Rotate around center of screen with middle mouse button.

Possibly need to be near my example Camera location. Could be the complexity of the region.
Camera destination set to `Cesium.Cartesian3.fromDegrees(-80.18163, 25.75049, 1170.452)`

See sandcastle :)

### Sandcastle example

https://sandcastle.cesium.com/#c=jVZtTxs5EP4ro3xhcwQnIUBbIOgooRQJSAXp9T5EQs7u7K6vXjuyvQm5E//9xt6XhLYnHR9CbM/L45lnHqffh0/alAXgCy+WEkErkDwDHcelMUJlsM5RQWL42i9GEyh0gtKCy7kDbhAMSu7ECg/mqt8HpyEzulRJD7SBWFLQ7V4V60brjBJRKGEBFV9ITFhwnui1ygxPfCZyukIrCNnekA2HAzbYg4J/R58ZA8RMA1/zDbkG55nZQCGSROJBoUuLB7EU8XfglNZoxx0S2gDC+8eoHBqfxCK2EYUCTFOMXQVnVm/HuqC0/nBF8NfC5TCsykCXVwmaBv8t8CTBhM6oLmQfc4tgyVsrBCoaRcm5Sda+bNVdhAOFmRSZoCrAadffJdbKaolM6iyad+oirNBYodUp7M07sF+Xhv1x/fh0O32gjXmHDrpndS1u03An64xYgk5hoV8omc11KRNYYGinqjBfJn+VllCUxYIK0tpKvaZlooOZR+Rg8nj57fnj9M/rJxiDMyWeNbm2Hf1lillOjV4LKSEXSVXtTGqyEWmI8zbDzXR6c3f9TMHaLM35SqBHNaaardsShD0qVBzWV1o5LhSaeacH/8wVAPXZ0M5p4zCr1iw1uvimjUzqjajbm6vXtoSf5KamIQe7xFikIoYEC02liYnwNCfEZmrkmm6jXcshg0ttPIEqsCzmBRrOUrmZ6SgAStA6oUKIFtQVN46+cTUKuCaYGUQbHbwfsOH74cmoB4fH7N3x4OhDD4bDdwN2dHzo8QJNmSAu19FCfIAcwwy10e+5y5nTj7TLlY1GhzRRlTfAUrg4/y/Lg9GIHY0aU6OlPIVBWL2Gz6Q0deZBWztqavS2kd0KV10QS7OHLBCAEV3W1M6U02yceZuqz05ItOjohAacRqQGFxukMa7I9iXXjqaMS0HFjEeTWeUSdc9+SrU0ohBeoSyj8Yzq4N7w9Q3eQO0aaxiMxFLvG8WDiGaD++noAilfJrwWkPL1JTGBZj2pWsa2t6Bk98FzDBEZ9bx1F8YXTZdqkNQ9QleDq4+oLdqK/8OQJnAPBk2boALcssH/lUackkYw1n8KMj/hjvcrJe9/1C9flRSu/ULNcSnNz9Y9R5Hl7hFTIryKsQX1+e0+u7q7vP/yPJs+3zxOvz5MdiLYmEvyOzxutl7rw9eqY6/hc1u8K/KfPd9PJ9d3Xm5Gg/bcvxOkLb43RNJMKy5roeOx0bZ6HyxxhfrTyBmrHR+08/pDcpRotGqPdE/EKDcUyYdYlK6Sp5geCternTa63PPaxVcY5KASTG+24rL0D5IOau7FPBVVSLPDg6fZ5ePs+e5yRvcIU/zu+P3h2U/nJONjCAP/4eRkeLxjcPtwVbvTKzgYjH48Cp47Rym9vJGk+RF+/4z+nb+pJ+3s73cbelSBPIvHO1D2IRLwWxO/6lFry93WlnDt2l7OGtuG/lvuV42msev0OufWbSReNGz4XRReNomnMiKSOiSS0qzb/qKMv6NjsbVN3PP+rut5IlYgkvEv9N//+rCWTtJSyifxN847F+d9sv/JVeqgl1N6ZCXfeLN8eHFXbTLGzvu0/LWn01ouuPkh8r8

### Environment

Browser: Tested in Firefox and Edge
CesiumJS Version: 1.118
Operating System: Windows 11

**Comment by ggetz** [comment]
Hi @matvey-tk, thanks for the report! I believe this is the same root cause as https://github.com/CesiumGS/cesium/issues/11923. 

I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
