### ISSUE TITLE
Remove `SceneTransforms.wgs84To*` functions in 1.121

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#12059]
The following functions were deprecated in https://github.com/CesiumGS/cesium/pull/12000, and should be entirely removed for the 1.121 release:

- `SceneTransforms.wgs84ToDrawingBufferCoordinates` has been deprecated. It will be removed in 1.121. Use `SceneTransforms.worldToDrawingBufferCoordinates` instead.
- `SceneTransforms.wgs84ToWindowCoordinates` has been deprecated. It will be removed in 1.21. Use `SceneTransforms.worldToWindowCoordinates` instead.

**Comment by jvrjsanchez** [comment]
Hi gabby, can i take on this issue for a first time from jtc?

**Comment by ggetz** [comment]
@jvrjsanchez Go for it!

**Comment by jvrjsanchez** [comment]
This update ensures that our codebase aligns with the latest changes and improves future maintainability.

   - Updated method calls in the codebase from `wgs84ToDrawingBufferCoordinates` to `worldToDrawingBufferCoordinates`.
   - Updated method calls in the codebase from `wgs84ToWindowCoordinates` to `worldToWindowCoordinates`.
- Ran tests using the original `gulpfile.js` to execute them.
- Verified that all tests for `SceneTransforms` pass successfully in different viewing modes (3D, ColumbusView, 2D) and frustum configurations.
- Ensured that test output is correctly reported and errors are handled gracefully.

**Comment by ggetz** [comment]
@xiyuvi The name of the function, `wgs84`, was no longer accurate since it uses the current ellipsoid value. It defaults to, but is not restricted to, the WGS84 ellipsoid. 

The deprecation warnings, along with notes in `CHANGES.md`, should be reviewed to track any breaking changes in the future. See [this guide for details](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CodingGuide/README.md#deprecation-and-breaking-changes).
