### ISSUE TITLE
Possible (minor) bug in Classification Sandcastle

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#12062]
When disabling "Show Classification" in https://sandcastle.cesium.com/?src=3D%20Tiles%20Photogrammetry%20Classification.html then it still shows semi-transparent red boxes around the tileset:

![Cesium Classification Sandcastle](https://github.com/CesiumGS/cesium/assets/5597569/98831810-b060-427e-aa26-99f5ef94c982)

Despite the comment saying `// The same b3dm tileset used for classification, but rendered normally for comparison.`

Changing the alpha value to 0.0 fixes this, but if the semi-transparent box is intentional, then this issue can be closed quickly.

**Comment by ggetz** [comment]
Thanks @javagl! I believe they are intended to be transparent, though I'd be open to tweaking the comment for clarity.

**Comment by javagl** [comment]
OK, it wasn't entirely clear whether the semi-transparent bounding boxes had been intentional (and I just started digging into that whole "classification" topic on the implementation level, but probably have to skip more details here). Probably no important action here then.
