### ISSUE TITLE
How to create a face to enclose a cut plane

### ISSUE THREAD

**Issue by yjf-3** [CesiumGS/cesium#12072]
### What happened?

i want to create a face to enclose a cut plane?but no idea

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:Version 1.99 and above
Operating System:

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
