### ISSUE TITLE
BingMapsImageryProvider sometimes errors

### ISSUE THREAD

**Issue by RacingTadpole** [CesiumGS/cesium#12088]
### What happened?

Our error logs show we occasionally get a type error at this line: https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/BingMapsImageryProvider.js#L101
```
Cannot read properties of undefined (reading '1')
```

I was lucky enough to catch it happen once, and could see the reason is that https://dev.virtualearth.net/REST/v1/Imagery/Metadata did not return `bbox` in the `coverageAreas`, but instead returned `jsonBoundingBox`.

![image](https://github.com/user-attachments/assets/82ef641f-c068-4156-b5dd-99b104f2e878)

### Reproduction steps

```
const bingRoadImageryPromise = BingMapsImageryProvider.fromUrl(
    'https://dev.virtualearth.net',
    {
        key: BING_API_KEY,
        mapStyle: BingMapsStyle.ROAD_ON_DEMAND,
    }
)
```
It also happens with other map styles.
It happens very rarely.

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
@jjspace Could you please triage this issue?

**Comment by jjspace** [comment]
Thanks for the in depth info @RacingTadpole! I can confirm I've seen this issue happening too.
As for why I'm not really sure. It would be easy for us to add a fallback to the `jsonBoundingBox` property but I haven't been able to confirm if we should even expect that value from the API in the first place. I can't find any sort of specific documentation about what the structure of that `imageryProviders` object _should_ be for that [response](https://learn.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata). It's possible this is a bug on Bing's side. I'll keep digging

**Comment by jjspace** [comment]
This is definitely an issue on the API's side which can be confirmed with the node script below. We're going to work to report this to the Bing team and hopefully they are able to resolve it on their end. In the meantime I've opened a PR to modify the logic to skip over attributions that don't have the expected format so it doesn't crash the viewer completely like it currently does.

<details><summary>Node script</summary>
<p>

```js
const key = "BING_KEY";

async function checkBadProperty() {
  const response = await fetch(
    `https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?jsonp=loadJsonp517758&incl=ImageryProviders&key=${key}&uriScheme=https`,
    {
      headers: {
        accept: "*/*",
        "accept-language": "en-US,en;q=0.9",
        "cache-control": "no-cache",
        pragma: "no-cache",
        "sec-ch-ua":
          '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Linux"',
        "sec-fetch-dest": "script",
        "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "cross-site",
      },
      referrer: "https://sandcastle.cesium.com/",
      referrerPolicy: "strict-origin-when-cross-origin",
      body: null,
      method: "GET",
      mode: "cors",
      credentials: "omit",
    }
  );

  const text = await response.text();
  const json = JSON.parse(
    text.replace("loadJsonp517758(", "").replace(/\)$/, "")
  );

  const firstCoverageArea =
    json.resourceSets[0].resources[0].imageryProviders[0].coverageAreas[0];
  console.log(firstCoverageArea);

  if (firstCoverageArea.jsonBoundingBox) {
    console.error("\nFound bad bounding box!\n");
    console.log(JSON.stringify(json, undefined, 2));
    return true;
  }
  return false;
}

async function main() {
  let tries = 1;
  while (!(await checkBadProperty())) {
    // just loop until bad property is found
    tries++;
  }
  console.log("Found bad response after", tries, "attempts");
}

main();
```

</p>
</details>
