### ISSUE TITLE
there is a bug when cesium.VoxelProvider voxel dimensions.x>= 158, what should i do?

### ISSUE THREAD

**Issue by oubaguilai** [CesiumGS/cesium#12098]
### What happened?

there is a bug when cesium.VoxelProvider voxel dimensions.x>= 158 
![A](https://github.com/user-attachments/assets/745a21b6-7612-4b07-af37-227f9fa44a58)

### Reproduction steps

1. open https://sandcastle.cesium.com/?src=Voxels.html&label=All
2. this.dimensions = new Cesium.Cartesian3(158, 158, 8);

### Sandcastle example

https://sandcastle.cesium.com/?src=Voxels.html&label=All

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
@jjhembd Could you please triage this?

**Comment by oubaguilai** [comment]
Thanks for the suggestion, I also achieved the effect I needed after splitting it into multiple VoxelPrimitive objects.
