### ISSUE TITLE
is there a tool convert  data  to voxel 3dtiles?

### ISSUE THREAD

**Issue by lzp0070007** [CesiumGS/cesium#12097]
### Feature

I have a data for weather  ,like this Mosaic20230731000000_Z.dat   and  I have convert this data to json like this;
{"ymin":35.8,"zmin":0.5,"xmin":112.8,"ymax":42.8,"zmax":15,"xmax":120.0,"heights":30,"values":[0,0,1,2....],"rows":1440,"cols":1400}

is there a tool convert the data  to voxel 3dtiles?

**Comment by ggetz** [comment]
Hi there,

Currently we don't have an available tool for generating Voxel 3D Tiles as the spec is not quite finalized yet. However we are working on it. Keep an eye on the [Cesium blog](https://cesium.com/blog) for news, and feel free to reach out to support@ceisum.com if you have input.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
