### ISSUE TITLE
Creating Perpendicular Planes and Line Intersection in CesiumJS

### ISSUE THREAD

**Issue by hunao0221** [CesiumGS/cesium#12093]
### What happened?

I am trying to create a visualization in CesiumJS where:

	1.	There is a line connecting two geographic points.
	2.	There is a plane passing through the first point and perpendicular to the line.
	3.	There is another plane passing through the line and perpendicular to the first plane.

However, despite following the steps, the second plane does not seem to correctly pass through the line as expected. Below are the coordinates and my implementation steps.

Coordinates:

	•	Point 1: (118.5329951, 37.0466284)
	•	Point 2: (118.533065, 37.0466414)
![image](https://github.com/user-attachments/assets/783c8152-97f2-4f8f-95a4-21ceab7aa530)

### Reproduction steps

1.	Calculate the direction vector from Point 1 to Point 2.
2.	Create the first plane with a normal vector perpendicular to the direction vector.
3.	Create the second plane with a normal vector perpendicular to both the direction vector and the first plane’s normal vector.

### Sandcastle example

[Example in Sandcastle](https://sandcastle.cesium.com/#c=1VZbb9owFP4rFk9Bigzh0rWUVuso20vVTt1N09iDSQyx5tiR7cDo1P8+2yQkJC4q6x62vETx8bl83/mO45AzqcCK4DUW4AIwvAYTLEmWwM92zZu1Qvs94UwhwrCYtdrnMzZjYPt0OuAaL7QBqBiDkHMREYYUloAv7JJac5BywpTc+ehtJqtdDXTWPOMECe1HEOvDheDJNV4KjKUXBKdw2O+dnQ0DH/Rfwe7g5KR3OjBVOOL1nhmv3z0Z7sINgsEeKIPqKops/QsiitilfUsYxEwRRbCEKIq8X6XZPCmX2sbZKMfp1816cQRqTtZCfmL6gTzgEQi6ftMecsrFaAfSfMH76fX+xsfy8/FJaBJr4qKXY+v9Y9gQoEaQGhzDoSJs+aQQn4WVbkw4N56cCDkC3/I255R8d6Bbk0jFIzB0mBI9MoIgWsP+dXpzc/flCPgTRMOM6mAWckSEIYAzsNJvLoCZg2LuVE5Hrz5HpZdrlGQ2VwKFystbX8i7enaU2712dU6b0RgXCaJaEN4uq18WcAAeKiCpGClAJEixSDGLiLELA85JgJePM0VaINvkualdpyFLnfjLio8Anh9QeyW6goeCS1mlIktfTOxeVn+/iAbBlbO8ytRxJCNzqCAp9U9AxYJnyzgXSZ0Qm+K9zXDxN85UE8k5pxFJMJPbQXXR2fOCbhd2fWBf7ecP6Lv76fQWromKr2gaI68Lhy7vvLJKaou63htH7iOmfU/OYGFnozzkLcvrmISxs5FzruJG200jXR2u93Gbw0K63RbxtLhrkCtaf6HOG0X4zboO6X2PqIOCr1NU07rZYv4YB1j6X+X+5ubT9M/V7ujQsYp/SzdFFygPkdVkftEsmGz83R84Tz5yr0Z4+7zlt8ZSbSi+LFxekyTlQh/9gnoQdhROUjNdsjPPwh9YwVDKQo3jTtV1HJEVINGF47YMQqrloS2LjNqrz6x1Oe7o/Q1XypG+Oy/vVlhQtDHb4uDyZrsIIRx39KfbU3FO50jUIv8G)

### Environment

Browser: Chrome 126.0.6478.183
CesiumJS Version: 1.119
Operating System: MacOS 14.5 & Windows 11

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
