### ISSUE TITLE
Polyline Dashed moving with the camera

### ISSUE THREAD

**Issue by mickae1** [CesiumGS/cesium#12115]
### What happened?

When I'm using polyline dash, when I move the camera, the dash moved, is it possible to fix it ?

Thank you,

There is a post about it : 

https://community.cesium.com/t/about-polyline-dashed/17998

### Sandcastle example

https://sandcastle.cesium.com/?src=Polyline%20Dash.html

_No response_

**Comment by ggetz** [comment]
Hi @mickae1, 

This is a consequence of the existing polygon dash material being performed in screenspace rather than worldspace. Off the top of my head, I would say we're unlikely to change the existing dash material, but would be open to a PR adding a new, worldspace dash material.

**Comment by mickae1** [comment]
I've made a custom shader to make the dash not moving, but i'm using the st.s . the problem is that I'm unable to know the size of the line, do you know how I can I fix it ?

[link](https://sandcastle.cesium.com/#c=7Vdtb9NIEP4ro550dSB14kABpUl1UagqpAIVLYdOl1O1scfJHvautbtJCaj/ndn1S20nbUHixH1gpShe7zPPjHee2Zc1U6CXLEI1non9Xi9/Bh0qnhlYaYzASIi4zhK2gYQLhIjp5YzAj52BHXZj19wswSwRNBNRyLRJsET9xuMIYzg9u3p7cnGlDQGYiq7IEV8zw9eoKyR+Mig0l+I+NAwBBZvXHKCIeFz2yn8uIE4kM7C+ymSyscFPxCLBoxKwEjyWKoU1hk/dZ01lItXdw6cs243I3VjIOTMGlbgHcYZiYZYVIJRCm2LYRvia6Y85BMYQPPP7dyI/8Mgsz1GFKAxh+/7gqD0DvbsanJ5cwuvJ5cm7V5MzuBNWS7NcKVhIlgDXNuUKzUoJl++U0RdzGpGx62f8EyY1yw8ITCFwESGpSSHTUnCxAJoXkKLAl8ZGsX8xNFJtYIkKazSaTDOFmr5WO2gopYq4IO/AEkmE9qVTqNd3UVJ3jgsunDdSEQTuHWml9GbRnZoPCzLf5EfzCOssVZI+p1fVhNjOAs3rou/VB1+JbGWg0asi+VI+ALUGY/UwLslfYsxWya2PJuNRnYl0PABttdIA+dpsCcfCC8lynaur3+Z6Spowdh5cTRDGvvMI2DmCLWhoMReYUG5JBHVsHbriJOU5tw7towepjDwK2dePmrXRbdVKB3YQGdRmHLxvDPDY8xx1rVg78Dt4wfvRiDx3OjCmr33fqRvBVvg7VwMLxETjw6bbdk58hpPCONNWr/MN6VBnZMULyV3bei81Z1lguJ0uReuszdbh4/YS0Ru0Ushj8GhqDRyPrVkHvjQDLzLvMAcW0PMCv++eGjw39ptbtlUYBw+GUQtklAfS4rqNhAYPLLDTo6cWyU0jpHqn/lwwhQlLM892Hj3x+12r7i4EbTXeCncqUyoUlz5XdixN2VQqRdnxUv7Ja+S426iLrvPZaTKX9eezJFsyejFu+vHZbjhtcjHtyVtwtZg3DIrVubSrxty8HM3ETKxp319zvEZbuAKvYYqar1L/T/fO2w9ddyqFYZRAtU/xOxtNObT+c1vfdR0hCXhKa7ux+3+aJbSsF1suZIqn3O7bfk5RDmiicfZ+hdA+iyKvFs55gaWptJNL5wKvU4ZS8gTEU3E6gi8zAY2WSc2tsT05tJjPeYb2319QJIrinzJFCwdnYqLCb2KqDJ74sZLpS1woRD1Rim28vw+CwInrKcm+2yb7r9vBi0Pr+8mzn+E76LsPHxz+DOfPn7uKpkn/p5M7v+kUUeTL6NANzsRNW02D/7maDn+emoJBv5TTt8yqWxMmWvOFAObWmJjNFQ9vDzF0gs/PYkwpee1OX3Zfo3mfiaq6/dqZp7YyVAeeYlIL7iFsTXJpr3cN3jYK9nKJeSglOa1dck0reXkQtOccG6VcU3KTxN6cMrus3cXZJLvXvW1mkyGh9ks1Taz5/gOJLm4Y+mH621adQWq6s13/r5Ozs7cfut/DUx6DWkyX7yZvLs4n707eXH4XXX6eG8KL/neZFUe5IfTngW39fv6jdj/Nzb1uNF17QhwWV2Sr6Tt52kPbxCFt13ThoXvFzlQVmzvlvyGbctPfpQN3fNgycG/3t+IpKvaHVufgV3X+qs5f1fmDq3OvuzfSZpPgcf72D06hKQMrlXi+3zNIB2yi0735KvyIxg+1tiU96pVGo4ivgUfj2V7rHD/bs3cfrWkkXiXJBf+Ms73jUY/wDTO6S0Z073xLlZSwjYUsg+Oz/KXv+6MedbetjJTJnKka41c)

**Comment by ggetz** [comment]
Hi @mickae1,

Is something along the lines of [czm_metersPerPixel](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Shaders/Builtin/Functions/metersPerPixel.glsl) what you are looking for here?

**Comment by mickae1** [comment]
> Hi @mickae1,
> 
> Is something along the lines of [czm_metersPerPixel](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Shaders/Builtin/Functions/metersPerPixel.glsl) what you are looking for here?

unfortunetly, I would like to get the size of the line but, it seems impossible :(

**Comment by mickae1** [comment]
maybe in the vertex shader of shape assembly process we can get the length of the line for the step fragment shader?

![image](https://github.com/user-attachments/assets/72e85875-5cac-4e4e-9104-35a9ebeebe42)

**Comment by mickae1** [comment]
@ggetz or can we pass the length of the line with uniforms ?
but the problems is that, I have to create different material for each line .....

**Comment by mickae1** [comment]
I discovered this discussion :

https://stackoverflow.com/questions/52928678/dashed-line-in-opengl3
