### ISSUE TITLE
Huge lens flare artifacts

### ISSUE THREAD

**Issue by jjspace** [CesiumGS/cesium#12130]
### What happened?

When I open the Lens flare Sandcastle it has huge artifacts and makes the whole globe glow. This happens across all browsers.

![2024-08-16_14-14](https://github.com/user-attachments/assets/5948243c-3e02-442d-8b28-5c6ce7baaff3)
![2024-08-16_14-32](https://github.com/user-attachments/assets/735c6e14-080b-4c14-a448-d3e20cce379e)
![2024-08-16_14-32_1](https://github.com/user-attachments/assets/0164c4d2-e416-49f0-a6cb-6f5ba9eb4c8f)

### Reproduction steps

1. Open the [Lens Flare Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html?src=LensFlare.html)

**Comment by ggetz** [comment]
Duplicate https://github.com/CesiumGS/cesium/issues/7366
