### ISSUE TITLE
Failed to retrieve World Terrain from Quickstart Guide's code

### ISSUE THREAD

**Issue by k1mjunyoung** [CesiumGS/cesium#12131]
### What happened?

When I write the html code in my local environment and open it in chrome, the terrain doesn't call like the picture below. Is there something wrong with my local code?

![image](https://github.com/user-attachments/assets/77f8d837-8c79-4a76-baea-3eb06071de44)

Here is the code below.
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <!-- Include the CesiumJS JavaScript and CSS files -->
  <script src="https://cesium.com/downloads/cesiumjs/releases/1.120/Build/Cesium/Cesium.js"></script>
  <link href="https://cesium.com/downloads/cesiumjs/releases/1.120/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
</head>
<body>
  <div id="cesiumContainer"></div>
  <script type="module">
    // Your access token can be found at: https://ion.cesium.com/tokens.
    // This is the default access token from your ion account

    Cesium.Ion.defaultAccessToken = '~~~';

    // Initialize the Cesium Viewer in the HTML element with the `cesiumContainer` ID.
    const viewer = new Cesium.Viewer('cesiumContainer', {
      terrain: Cesium.Terrain.fromWorldTerrain(),
    });    

    // Fly the camera to San Francisco at the given longitude, latitude, and height.
    viewer.camera.flyTo({
      destination: Cesium.Cartesian3.fromDegrees(-122.4175, 37.655, 400),
      orientation: {
        heading: Cesium.Math.toRadians(0.0),
        pitch: Cesium.Math.toRadians(-15.0),
      }
    });

    // Add Cesium OSM Buildings, a global 3D buildings layer.
    const buildingTileset = await Cesium.createOsmBuildingsAsync();
    viewer.scene.primitives.add(buildingTileset);   
  </script>
 </div>
</body>
</html>
```

### Reproduction steps

1.
2.
3.
...

### Environment

Browser: Chrome
CesiumJS Version: 1.120
Operating System: Windows10

**Comment by ggetz** [comment]
Hello @k1mjunyoung,

I assume `Cesium.Ion.defaultAccessToken = '~~~';` is bring replaced by your access token in the actual code, correct?

Are there any messages [in the console](https://developer.chrome.com/docs/devtools/open)?

**Comment by k1mjunyoung** [comment]
Hello @ggetz.
Thank you for reading my issue.
It was a problem that occurred when I opened the html file directly to the browser.
It's solved by using Live server extension in vscode.
Thank you.
