### ISSUE TITLE
protobufjs v7.3.3 removed dist directory causing Cesium build to fail when resolving protobufjs/dist directory

### ISSUE THREAD

**Issue by stevethewright** [CesiumGS/cesium#12143]
### What happened?

Version 7.3.3 has removed the dist directory causing Cesium to fail in the build process. This happened in v7.3.1 and a similar issue was created here (#12034). v7.3.2 brought back the dist folder and that issue was ignored.

```
✘ [ERROR] Could not resolve "protobufjs/dist/minimal/protobuf.js"
 node_modules/@cesium/engine/Source/Core/GoogleEarthEnterpriseMetadata.js:1:26:
 1 │ import * as protobuf from "protobufjs/dist/minimal/protobuf.js";
```

This can be fixed by manually installing v7.3.2.

As suggested in the previous issue, it would be ideal to lock the protobufjs version, especially since this happened a second time.

### Reproduction steps

1. Update/install latest cesium version with v7.3.3 of protobufjs.
2. Build. (vite)
3. Error is shown.

### Environment

Browser: Firefox 129.0.2
CesiumJS Version: 1.120.0
Operating System: Ubuntu 22.04

**Comment by sincely** [comment]
I aslo hava some question !!!!!!!!!

**Comment by ggetz** [comment]
Thanks for bringing this up @stevethewright. We'll lock the working version of `protobufjs` in `package.json`.

**Comment by ggetz** [comment]
Opened https://github.com/protobufjs/protobuf.js/issues/2022.

**Comment by jjspace** [comment]
protobuf already released an updated version including the `dist` directory again so I'm going to close this https://github.com/protobufjs/protobuf.js/pull/2023 

Please update your npm packages
