### ISSUE TITLE
Cesium.js at version as 1.117.0+ Deprecate and remove SpotLight  and PointLight?

### ISSUE THREAD

**Issue by maxiaoqu** [CesiumGS/cesium#12142]
### Feature

when Cesium.js at version as 1.117.0+，Deprecate and remove SpotLight and PointLight? and when i want to use SpotLight and PointLight，What should I do?

**Comment by ggetz** [comment]
Hi @maxiaoqu, thanks for bringing up this issue! I believe we are already tracking it in https://github.com/CesiumGS/cesium/issues/8518. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
