### ISSUE TITLE
EllipsoidalOccluder Type export is missing

### ISSUE THREAD

**Issue by zhangheng0317** [CesiumGS/cesium#12152]
### What happened?

我在使用Cesium中的EllipsoidalOccluder时,发现没有ts类型导出,但实际是可以使用的
![image](https://github.com/user-attachments/assets/3c2bdfee-8537-4a86-9368-4e91b7f22db9)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:Edge
CesiumJS Version:120
Operating System:win11

**Comment by ggetz** [comment]
@zhangheng0317 That is because `EllipsoidalOccluder` is a private class.

Would you mind telling us about your use case? That might help determine if we make a class public.

**Comment by plainheart** [comment]
I have also been using this class for some time. It would be useful when there is a need to hide the HTML overlays when it is behind the ellipsoid.
