### ISSUE TITLE
Update `prettier`

### ISSUE THREAD

**Issue by jjspace** [CesiumGS/cesium#12172]
Prettier has been bumped a [major version](https://prettier.io/blog/2023/07/05/3.0.0.html), `v3.0.0` and multiple versions after, up to `v3.3.0` at time of writing. We're still on `v2.1.2`. We should probably do a push to update and address all breaking changes at once so we're closer to in sync and future updates are smaller. I just don't want to do that right before a release.
I think the biggest rule change that I know about is that trailing commas now default to `all` which will probably result in a very large PR of small, non functional, differences. They also changed some logic about how long lines wrap to make things readable and waste less vertical space which will probably affect most of our files.

**Comment by dave-b-b** [comment]
I'll take this one if it is still available.

**Comment by ggetz** [comment]
@jjspace Would you be able to advise @dave-b-b on this issue?
