### ISSUE TITLE
When different images are added in a specific order, all billboards will turn into black squares.

### ISSUE THREAD

**Issue by njueyupeng** [CesiumGS/cesium#12184]
### What happened?

I added two entities in the viewer, each with its own billboard. After refreshing the page, if entity1 is added first, billboard1 displays normally. However, when entity2 is added next, both billboards turn into black squares. If entity2 is added first and then entity1, there is no issue. Please refresh the page each time you test. THANKS。
<img width="1440" alt="截屏2024-09-05 15 22 35" src="https://github.com/user-attachments/assets/033f2394-7f8f-46c2-beab-e52553815167">

THE CONSOLE MESSAGE:
Cesium.js:3876 WebGL: INVALID_VALUE: texImage2D: width or height out of range
cesiumBillboardBlank/:1 [.WebGL-0x118007cee00] GL_INVALID_VALUE: Offset overflows texture dimensions.
7[.WebGL-0x118007cee00] GL_INVALID_OPERATION: Level of detail outside of range.

### Reproduction steps

1. Refresh Your Page
2. Click “Button1 ”
3. Click “Button2”。（Sometimes it requires clicking several times.）
4.  

### Sandcastle example

example:   https://njueyupeng.github.io/cesiumBillboardBlank/
Code is here:  https://github.com/njueyupeng/cesiumBillboardBlank/blob/main/index.html
### Environment

Browser: Google Chrome@128
CesiumJS Version:  1.95
Operating System:  MAC and Window

**Comment by ggetz** [comment]
Hi @njueyupeng,

I'm having trouble reproducing the issue with a standalone [sandcastle with other images](https://sandcastle.cesium.com/#c=lVTLcpswFP0VDRvjlgpI/IgdJ9PG7aIz6WThTDchk5FBBrVC8kjCjtPxvjPturuu+2X5jwqEAyY0aVgJ3XvOfR3dgIHyc10QYkmyFNx//33/58f9z1/Bg3GFBFgRvMYCnACG12BauMLPxZ3dMcgpZwoRhkXHAd8qcP7JhGc0esdIihQeAyUy7DQ8MMWhIpx9ZBEJkeKi1Y2wBT/jt2OwQFTiyrbtHgcsqFdDsQIyRZTqlAMrUWopx65L0hguSZgRGDJ3ITB2D7yDnuuNXK/vDgbRqDdfDEbhAPtwyeLAOn7EOSfxCxnD0fAgHPr9NsaQM6me6m1gNZobWPul7tcJoU4IxVi6hubmnMf8hq+woGhjEtiH7sr5L2AFNXlHSKEZz0SI93OfZlLx9P2D1e5IPXdKicIfmCJq0+keN7lwYZhyWupAM1b0sLASLGsw0zRYOUmIosiu/vf7ZKKYGjX3VUN+eQcbWtOtqS6uq+MiYyZDHc6UYxMW4VvN6nWbyq8XdzH/omvTbg2f/GMo1Q/jE1IJFIhFPLW7UPGZEoTFtj/oOo8hJHohYMklyRMfP8wJCaVPiB3ChdADw7HWr7TfDPuwPxoOh+D1fgDwCnjQ8zzfAT19ODw6OmyLMyeUzjkSOr+WSovU8zGMy2lcFd27dtpd1yRSyRj0jv5hTzCJE/WEg94969ZdUuyNxt22LpndGzHT03MrJbcTY6G3+mjrqjYPfA/elPiz+DLeHefpJS896z7b6jjTIwqRVBTnrJec0zkSZ5lSnOkd4gWWU+nWLlVa6dfrBmzbjP48rf8MrW9oLceaSLWh+HQX4C1Jl1wokAlq682jcLqkekNId56FX7GCoZS7bCZuHTqJyEoL/6RlLYKQIim1ZZFROiN3OLBOJ672fwSlHEX6lVyY5Za7Jf7pubmEEE5c/duOVKYBDea/). 

One of the images in your example is quite large, which may be causing the issue. I would suggestion reducing the filesize by user a smaller image and adding compression.
