### ISSUE TITLE
Enable require pull request reviews before merging in GitHub

### ISSUE THREAD

**Issue by lukemckinstry** [CesiumGS/cesium#12197]
### Feature

Under consideration is to enable the feature which is built in to GitHub to require an approval on a PR before it can be merged ([see feature docs here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-pull-request-reviews-before-merging)). When enabled the approval status is  shown in the "Checks" section at the bottom of a PR.

We discussed that the current team practice is to review and approval all PRs before merging, as described in the [Cesium contributor guide](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#opening-a-pull-request), so this enabling this feature would just effectively formalize an existing process.

Some feature details to highlight:
 - When the reviewer requests changes, the same reviewer must then later approve or withdraw the request. Alternatively an overriding reviewer can nullify the request and approve the PR. 
 - There is a mechanism in place to automatically dismiss stale pull request approvals. I don't think we should enable this.
 - As is the case currently, reviewers can self-assign themselves to a PR
 - If we ever use adopt code owners, we can require reviews from code owners

**Comment by ggetz** [comment]
I've enabled this rule in the admin settings, and have allowed overrides for maintainers.

<img width="906" alt="image" src="https://github.com/user-attachments/assets/8f01f50a-feb4-4d87-ba51-14a859f4a58b">

Please be on the lookout for how this is working out, and let us know here if there is any feedback.
