### ISSUE TITLE
Attempted import error: 'rbush' does not contain a default export (imported as 'RBush').

### ISSUE THREAD

**Issue by DoHung1997** [CesiumGS/cesium#12191]
./node_modules/@cesium/engine/Source/Core/RectangleCollisionChecker.js
Attempted import error: 'rbush' does not contain a default export (imported as 'RBush').

I have a problem when building cesium with nextjs. When I run "yarn build", it show this error

**Comment by ggetz** [comment]
@jjspace Can you please take a look at this?

**Comment by jjspace** [comment]
`rbush` is a dependency of `engine`. In the 1.120 update we [updated](https://github.com/CesiumGS/cesium/commit/3cb228d008befb674a09984ddbc78495385822c8) this to `v4.0.0` but that version [switched](https://github.com/mourner/rbush/releases/tag/v4.0.0) to only support ES modules and dropped CommonJS. We publish CesiumJS to be used in both ESM and CommonJS projects. I think this just means that in your project it's trying to build as CommonJS and failing on that package.
I think that short term we have to lock that package to `3.0.1` and longer term maybe investigate replacing it. Thoughts @ggetz

**Comment by ggetz** [comment]
@jjspace I agree. Let's move ahead with the locked version. 

How would you like to document the locked version? Maybe leave this issue open?

**Comment by jjspace** [comment]
@DoHung1997 Short term you should be able to override the version of `rbush` in your `package.json` to avoid the build error (See [this SO question](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions)). This will be pinned in the next release so you will be able to remove the [override](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides).

```json
{
  "dependencies": {...},
  "devDependencies": {...},
  "overrides": {
    "@cesium/engine": {
      "rbush": "3.0.1"
    }
  }
}
```

> How would you like to document the locked version? Maybe leave this issue open?

@ggetz That's fine, we can just leave this issue open and maybe rename it to match the other [dependencies issues](https://github.com/CesiumGS/cesium/labels/dependencies) or make a new one. I really wish we could add comments to `package.json` but that's apparently a discussion that's been shut down before so no luck there.

<details><summary>Down the rabbit hole</summary>
<p>

Just a collection of links I previously collected tumbling down the rabbit hole of finding out whether `npm` would support `.jsonc` or another alternative. Seems the answer is sadly a resounding "no" currently.

- [\[FEATURE\] Allow jsonc or JSON5 for package.json for commenting · Issue #793 · npm/cli · GitHub](https://github.com/npm/cli/issues/793)
- [\[RRFC\] Allow jsonc or JSON5 for package.json for commenting · Issue #424 · npm/rfcs · GitHub](https://github.com/npm/rfcs/issues/424)
- [\[RRFC\] Opt-in solution to support comments in package.json (among other features) · Issue #291 · npm/rfcs · GitHub](https://github.com/npm/rfcs/issues/291)
- [Use JSON5 for package.json · npm/feedback · Discussion #56 · GitHub](https://github.com/npm/feedback/discussions/56)
- [Support for comments in package.json · Issue #4482 · npm/npm · GitHub](https://github.com/npm/npm/issues/4482)

</p>
</details>

**Comment by DoHung1997** [comment]
Greate! it worked correctly. Thanks!
