### ISSUE TITLE
Texture WebGL: OUT_OF_MEMORY

### ISSUE THREAD

**Issue by cnchore** [CesiumGS/cesium#12219]
### What happened?

When using the videoElement material, the console reported an error and couldn't draw properly。

error info:
WebGL: OUT_OF_MEMORY: texSubImage2D: bad image data

### Reproduction steps

1. Visit the website: https://sandcastle.cesium.com/?src=Video.html
2. Opening the development console
3.
...

### Sandcastle example

https://sandcastle.cesium.com/?src=Video.html

### Environment

Browser: Chrome 129.0.6668.70
CesiumJS Version:1.121
Operating System: macos

**Comment by cnchore** [comment]
![image](https://github.com/user-attachments/assets/ab32467c-4191-4e99-9660-0779229a13e3)

**Comment by ggetz** [comment]
@jjspace Could you please check if this is a regression from https://github.com/CesiumGS/cesium/pull/12158? If not, would you mind bisecting to see where this broke?

**Comment by jjspace** [comment]
git bisect points to commit https://github.com/CesiumGS/cesium/commit/e00c68ad9d24e0373a4bbf928a5f5a441e22d7bd which was part of https://github.com/CesiumGS/cesium/pull/12100 from @jjhembd 

```sh
# "bad" commit
git checkout e00c68ad9d24e0373a4bbf928a5f5a441e22d7bd
# "good commit right before that one
git checkout e00c68ad9d24e0373a4bbf928a5f5a441e22d7bd~1
```
