### ISSUE TITLE
The text on the label is transparent.

### ISSUE THREAD

**Issue by c-Clithe** [CesiumGS/cesium#12210]
### What happened?

![1727061301109](https://github.com/user-attachments/assets/ab938d1a-560d-433e-8bd6-abd8ee594bc4)

Add a label using viewer.entities.add. 
The text of the label is set to white, but the text becomes transparent.

### Reproduction steps

viewer.entities.add({
            name: 'test',
            id: id,
            position: position,
            billboard: {
                      image: myImage,
                      scale: 0.35
            },
            label: {
                      text: 'test',
                      disableDepthTestDistance: 500,
                      show: true, 
                      pixelOffset: new Cesium.Cartesian2(0, -41),
                      fillColor: {
                          rgba: [255, 255, 255, 255]
                      }, // Cesium.Color.WHITE,
                      style: "FILL",
                      showBackground: false,
            }
})

MyImage has transparency.

### Environment

Browser:
CesiumJS Version: 1.120.0

**Comment by ggetz** [comment]
Hi @c-Clithe, I don't think this is a bug.

The problem is the line:

```
fillColor: {
    rgba: [255, 255, 255, 255]
},
```

This is not valid. You need to use the proper `Color` type:

```
fillColor: Cesium.Color.WHITE,
```
