### ISSUE TITLE
An error occurred while rendering a label when contextOptions.requestWebgl1 is true

### ISSUE THREAD

**Issue by eclosion** [CesiumGS/cesium#12249]
### What happened?

```
const viewer = new Cesium.Viewer("cesiumContainer", {
  contextOptions: {
      requestWebgl1: true,
  },
});

function addLabel() {
  viewer.entities.add({
    position: Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
    label: {
      "text": "text",
    },
  });
}
addLabel();
```
the code above will produce an error:
```
TypeError: Failed to execute 'texSubImage2D' on 'WebGLRenderingContext': parameter 9 is not of type 'ArrayBufferView'.
```
here is [sandcastle example](https://sandcastle.cesium.com/#c=bVDLbsIwEPwVy6cgpY5SCogQUCV6ROJQqb344jgLterYqR9QWuXfaxOgqGUP1u7szHhsrpV1aCdgDwbNkYI9WoIVviEvRyyhmB/npVaOCQWG4hR9U4UQDwh8unXrRDApejCWgQ8P1r1CtZV5gZzxkMZdF85uMKOKqo1XPMoQq+sVq0Amg17fJyGgnHACLAn75GTcaiuipjgnXDLjQsfUkGyMbp5gawBscjcZkXz8kI/HkxQNp2Q6uo81SHsbGa+7SktxfAXFxaU7Ebs+dAzcUfUbdIZTXFp3kLA4ezyKptXGIW9kQkjmoGklC9myyvN3cIRbG20itcyupWUtdkjU8xu/jLhk1obNxkv5LL6A4kWZBf4/qdSsFmq73oGR7BBpb/li1YOEkDIL422l01pWzPxx/gE)

### Environment

Browser: Chrome 129
CesiumJS Version: 1.122
Operating System: windows11

**Comment by ggetz** [comment]
Thanks for the report @eclosion!

I believe this is a regression from https://github.com/CesiumGS/cesium/pull/12100.

**Comment by ly1368489670** [comment]
Has version 1.123 not been modified?

**Comment by ly1368489670** [comment]
Has version 1.123 not been modified?
