### ISSUE TITLE
Geometry and Appearances Tutorial Part II Feedback

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1225]
This is feedback on the draft [Creating Custom Geometry and Appearances](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Geometry-and-Appearances) tutorial.
- [ ] `Adding Normals for Shading` -> This section should explain what a normal is at the start like how I explain winding order above.  The typical developer will have little to no idea.
- [ ] This section should also explain that we don't always need to duplicate vertices, and that `GeometryPipeline.computeNormal` is convenient in some cases, but we can often use knowledge of our geometry to compute better normals faster, which is the same story we tell for the bounding sphere above.
- [ ] This section also calls `GeometryPipeline.computeNormal` in the app, not in the geometry.  Although concise, this is going to confuse folks.  Who computed what?  When?  Make the geometry cohesive.
- [ ] @pjcozzi - Add an appearance example.

Once I get these merged (soon), let's add sections for:
- [ ] Visualizing the bounding sphere with `Primitive.debugShowBoundingVolume`.  1ddf5437e76cc057cd5fd1f53281deb76592b356
- [ ] Visualizing the primitive's reference frame (determined by the model matrix) with `DebugAxesPrimitive` (subject to rename).  87a0c5ad923c70e4e049671efc024c217ce75d44

Also, we'll build these into the Cesium Inspector, e.g., click on a primitive to draw its reference frame.  CC #1025 

I also made some edits you can look at.

CC #1207

**Comment by mramato** [comment]
Do we ever plan on finishing the tutorial?  Since it's a year old, it will probably need a bunch of updates beyond what's listed here.

**Comment by pjcozzi** [comment]
Yes, let's leave these notes.

**Comment by ggetz** [comment]
While the tutorials could use some updates, they're likely beyond the scope of what is listed here and will be part of a larger effort. Closing this issue as having it open is not particularly useful.
