### ISSUE TITLE
Setting verticalExaggeration greater than 1 affects 3D models

### ISSUE THREAD

**Issue by jianghumu** [CesiumGS/cesium#12256]
### What happened?

When the terrain exaggeration (verticalExaggeration) is set to 3, the 3D .glb models become overly exaggerated and distorted. This seems to affect the way the models are rendered when the terrain height is modified, leading to unexpected visual results.

Please provide a concise solution, such as adding a fix through a JavaScript file. Avoid updating or upgrading Cesium since many shaders are used, and version inconsistencies or upgrades might cause the previous project to stop functioning. The current version in use is Cesium 1.115.1. However, testing shows that the latest version, 1.122.0, still has this issue.

<img width="1336" alt="verticalExaggeration=1" src="https://github.com/user-attachments/assets/e534baa4-5320-4795-8e26-4e9cedce20cf">

<img width="1207" alt="verticalExaggeration=3" src="https://github.com/user-attachments/assets/a5d5e228-0f97-4bd6-a036-503738a3a9fc">

code：
const viewer = new Cesium.Viewer("cesiumContainer", {
  timeline: false,
  animation: false,
  sceneModePicker: false,
  baseLayerPicker: false,
  // The globe does not need to be displayed,
  // since the Photorealistic 3D Tiles include terrain
  globe: false,
});

const { scene, camera } = viewer;
scene.verticalExaggeration = 3.0;

camera.setView({
  destination: new Cesium.Cartesian3(
    -2710292.813384663,
    -4360657.061518585,
    3793571.786860543,
  ),
  orientation: new Cesium.HeadingPitchRoll(
    5.794062761901799,
    -0.30293409742984756,
    0.0009187098191985044,
  ),
});

// Enable rendering the sky
scene.skyAtmosphere.show = true;

// Add Photorealistic 3D Tiles
try {
  const tileset = await Cesium.createGooglePhotorealistic3DTileset();
  scene.primitives.add(tileset);
} catch (error) {
  console.log(`Error loading Photorealistic 3D Tiles tileset.
    ${error}`);
}

const viewModel = {
  exaggeration: scene.verticalExaggeration,
  relativeHeight: scene.verticalExaggerationRelativeHeight,
};

function updateExaggeration() {
  scene.verticalExaggeration = Number(viewModel.exaggeration);
  scene.verticalExaggerationRelativeHeight = Number(viewModel.relativeHeight);
}

Cesium.knockout.track(viewModel);
const toolbar = document.getElementById("toolbar");
Cesium.knockout.applyBindings(viewModel, toolbar);
for (const name in viewModel) {
  if (viewModel.hasOwnProperty(name)) {
    Cesium.knockout.getObservable(viewModel, name).subscribe(updateExaggeration);
  }
}

function createModel(url, height) {
  viewer.entities.removeAll();

  const position = Cesium.Cartesian3.fromDegrees(
    -123.0744619,
    44.0503706,
    height,
  );
  const heading = Cesium.Math.toRadians(135);
  const pitch = 0;
  const roll = 0;
  const hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
  const orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

  const entity = viewer.entities.add({
    name: url,
    position: position,
    orientation: orientation,
    model: {
      uri: url,
      minimumPixelSize: 128,
      maximumScale: 20000,
    },
  });
  viewer.trackedEntity = entity;
}

const options = [
  {
    text: "Aircraft",
    onselect: function () {
      createModel("../SampleData/models/CesiumAir/Cesium_Air.glb", 5000.0);
    },
  },
  {
    text: "Drone",
    onselect: function () {
      createModel("../SampleData/models/CesiumDrone/CesiumDrone.glb", 150.0);
    },
  },
  {
    text: "Ground Vehicle",
    onselect: function () {
      createModel("../SampleData/models/GroundVehicle/GroundVehicle.glb", 0);
    },
  },
  {
    text: "Hot Air Balloon",
    onselect: function () {
      createModel(
        "../SampleData/models/CesiumBalloon/CesiumBalloon.glb",
        1000.0,
      );
    },
  },
  {
    text: "Milk Truck",
    onselect: function () {
      createModel(
        "../SampleData/models/CesiumMilkTruck/CesiumMilkTruck.glb",
        0,
      );
    },
  },
  {
    text: "Skinned Character",
    onselect: function () {
      createModel("../SampleData/models/CesiumMan/Cesium_Man.glb", 0);
    },
  },
  {
    text: "Unlit Box",
    onselect: function () {
      createModel("../SampleData/models/BoxUnlit/BoxUnlit.gltf", 10.0);
    },
  },
  {
    text: "Draco Compressed Model",
    onselect: function () {
      createModel(
        "../SampleData/models/DracoCompressed/CesiumMilkTruck.gltf",
        0,
      );
    },
  },
  {
    text: "KTX2 Compressed Balloon",
    onselect: function () {
      if (!Cesium.FeatureDetection.supportsBasis(viewer.scene)) {
        window.alert(
          "This browser does not support Basis Universal compressed textures",
        );
      }
      createModel(
        "../SampleData/models/CesiumBalloonKTX2/CesiumBalloonKTX2.glb",
        1000.0,
      );
    },
  },
  {
    text: "Instanced Box",
    onselect: function () {
      createModel("../SampleData/models/BoxInstanced/BoxInstanced.gltf", 15);
    },
  },
];

Sandcastle.addToolbarMenu(options);

### Reproduction steps

code：
const viewer = new Cesium.Viewer("cesiumContainer", {
  timeline: false,
  animation: false,
  sceneModePicker: false,
  baseLayerPicker: false,
  // The globe does not need to be displayed,
  // since the Photorealistic 3D Tiles include terrain
  globe: false,
});

const { scene, camera } = viewer;
scene.verticalExaggeration = 3.0;

camera.setView({
  destination: new Cesium.Cartesian3(
    -2710292.813384663,
    -4360657.061518585,
    3793571.786860543,
  ),
  orientation: new Cesium.HeadingPitchRoll(
    5.794062761901799,
    -0.30293409742984756,
    0.0009187098191985044,
  ),
});

// Enable rendering the sky
scene.skyAtmosphere.show = true;

// Add Photorealistic 3D Tiles
try {
  const tileset = await Cesium.createGooglePhotorealistic3DTileset();
  scene.primitives.add(tileset);
} catch (error) {
  console.log(`Error loading Photorealistic 3D Tiles tileset.
    ${error}`);
}

const viewModel = {
  exaggeration: scene.verticalExaggeration,
  relativeHeight: scene.verticalExaggerationRelativeHeight,
};

function updateExaggeration() {
  scene.verticalExaggeration = Number(viewModel.exaggeration);
  scene.verticalExaggerationRelativeHeight = Number(viewModel.relativeHeight);
}

Cesium.knockout.track(viewModel);
const toolbar = document.getElementById("toolbar");
Cesium.knockout.applyBindings(viewModel, toolbar);
for (const name in viewModel) {
  if (viewModel.hasOwnProperty(name)) {
    Cesium.knockout.getObservable(viewModel, name).subscribe(updateExaggeration);
  }
}

function createModel(url, height) {
  viewer.entities.removeAll();

  const position = Cesium.Cartesian3.fromDegrees(
    -123.0744619,
    44.0503706,
    height,
  );
  const heading = Cesium.Math.toRadians(135);
  const pitch = 0;
  const roll = 0;
  const hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
  const orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

  const entity = viewer.entities.add({
    name: url,
    position: position,
    orientation: orientation,
    model: {
      uri: url,
      minimumPixelSize: 128,
      maximumScale: 20000,
    },
  });
  viewer.trackedEntity = entity;
}

const options = [
  {
    text: "Aircraft",
    onselect: function () {
      createModel("../SampleData/models/CesiumAir/Cesium_Air.glb", 5000.0);
    },
  },
  {
    text: "Drone",
    onselect: function () {
      createModel("../SampleData/models/CesiumDrone/CesiumDrone.glb", 150.0);
    },
  },
  {
    text: "Ground Vehicle",
    onselect: function () {
      createModel("../SampleData/models/GroundVehicle/GroundVehicle.glb", 0);
    },
  },
  {
    text: "Hot Air Balloon",
    onselect: function () {
      createModel(
        "../SampleData/models/CesiumBalloon/CesiumBalloon.glb",
        1000.0,
      );
    },
  },
  {
    text: "Milk Truck",
    onselect: function () {
      createModel(
        "../SampleData/models/CesiumMilkTruck/CesiumMilkTruck.glb",
        0,
      );
    },
  },
  {
    text: "Skinned Character",
    onselect: function () {
      createModel("../SampleData/models/CesiumMan/Cesium_Man.glb", 0);
    },
  },
  {
    text: "Unlit Box",
    onselect: function () {
      createModel("../SampleData/models/BoxUnlit/BoxUnlit.gltf", 10.0);
    },
  },
  {
    text: "Draco Compressed Model",
    onselect: function () {
      createModel(
        "../SampleData/models/DracoCompressed/CesiumMilkTruck.gltf",
        0,
      );
    },
  },
  {
    text: "KTX2 Compressed Balloon",
    onselect: function () {
      if (!Cesium.FeatureDetection.supportsBasis(viewer.scene)) {
        window.alert(
          "This browser does not support Basis Universal compressed textures",
        );
      }
      createModel(
        "../SampleData/models/CesiumBalloonKTX2/CesiumBalloonKTX2.glb",
        1000.0,
      );
    },
  },
  {
    text: "Instanced Box",
    onselect: function () {
      createModel("../SampleData/models/BoxInstanced/BoxInstanced.gltf", 15);
    },
  },
];

Sandcastle.addToolbarMenu(options);

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
Hi @jianghumu, [`ModelGraphics.enableVerticalExaggeration`](https://cesium.com/learn/cesiumjs/ref-doc/ModelGraphics.html?classFilter=model#enableVerticalExaggeration) was added in https://github.com/CesiumGS/cesium/pull/12141. This should address your issue.

Thanks!
