### ISSUE TITLE
Depth Test Against Terrain disabled but Terrain still overlaps Polygon

### ISSUE THREAD

**Issue by anne-gropler** [CesiumGS/cesium#12257]
### What happened?

I am drawing polygons that are just below the surface. I kept the depth test against terrain disabled so that the polygon is always shown.

However, when I zoom in on that polygon, and the camera is still above the surface, the lower part is cut off depending on the distance to the camera.

The polygon is not cut off when the camera is below the surface. The polygon is also not cut off when translucency is enabled, but this is not a workaround that would work for my use case. Hiding the globe skirts does not change anything.

![terrainOverlapSandcastlebug](https://github.com/user-attachments/assets/0a9a9a39-3f5e-4358-a95e-b5cebbc59b8a)

### Reproduction steps

1. Open the provided sandcastle.
2. Move the camera (zooming, panning, ...) and see how the cut-off part changes.

### Sandcastle example

https://sandcastle.cesium.com/#c=1VdZb+M2EP4rQvqwNpDQPCSRdLxGd5PsAXQPbLZ9afpAS7StRpYEikrWXeS/d6jDlo+kyAItUAEGpOEc3wzncpRnpfXuEn2vjffSy/S9d6HLpFqh32ra4OYkqr8v8syqJNPm5mR4fpNFtdwizWcaxBp5VEY606gmAstNtkMuI6N1dl2oSF+olTbKaTR5mgKHztQs1RfwkZRJnl1qqyMLL6B6rtLSaau1olgXdvlVl/bVAsCU9qs2Bl4O+KxRWZlWYDhao7kBS2/A7qu0WKrX68uktCqL9K6/H7Uyb5S5jlSqzIBihE89jPxTj2BcfxCEh8cNNPDjAxTlMr+/vk2MLTdH3mjk/VlB6AB0pErtwgQkiI2ySbbw7FJ7RZ6uFxDfLsoGgqFApSa7iK8ym9j14PtN5sHTSo299ts9K2W1SVQ67kQgxLlxAVldlGX9cW0N2B28+OkNPBi/GJ5uxQttPudl4m7inU4WSzv2rKl0j2OZwEWaaLke94FdqDSdqej2s8lBBUDcCrhnMPReTvv8nxvo7zplg993Bbxd5cbCm8rYgMmA+ZIgn4SMMsIE3JYvfBZwJH0cEiIxDYEkQ18AjVIRCk76Hv6jdiFAFcU4CELON9pDxn2OZcjwRr2PIE/8gPjcf5YBLhAOaOhLcKTRH4IqHggsqOSiVR9ShLmUVD5XvcAItMuQQzj4Rj9YBXsUvOj0B4hiQcLgIDp/7BPqPO7RuvOH0y4Pm4wZPwkrQJKTEOLVYiJgH9zFAe8QAYUIn4Y1oodh3VD26oH+eD30sS11dKvNLFcm/tAybDL3e995faezumj26unL1eVOkPI4Psb29svV1ccdRqMLqPvjkaID6roOg67Tk3n439Vnr4LwYQUF4qCAQvaMDKchkwiSBPpAIDit9dOAoYAJ+IR0avQzziUSoc+YZH7wLP1UIMaJlCygftDoD2EecNAuGbSTVr/gCDwThLOQ/2gDEAcNICAHDUAE/1GJMuRLzigPwGgLDCOJQ4g4ND6/ax0B4JcYWm3bmtpSbWe/djWZ6BKpOB5sB5njeZKDNlpgNCYZHKsUpqVbGjbYN/INHXX03ZZwMCw4gjsiQUBokytMYhT6nHAinAOdTyHkLA8xjBTag9qaihOzWU+O2zqDxcGHfuaHEkshCWT3qQdEeJUB5DhmmPtEUrdhYCm5pAQQwcgSkh3aq4pHDbnuDu5g4hMKGYM5q+3APJS+D2QqCCjFwhkSjAccOAjkERZCHBoyroc85RQH3FCgBByjHGZuvSFRwgKfCAEFQuEwdMQASgbMQbYyn1LGNrf59tf3Xmmr+bxr5g7BhzzWKditm21/s7pqFqtxL6Mf2QC3LA+1qRb+bZZHt3ll3b4W3Q42xrYrrM1z6IVu943zqFpBNqKFtlepdq+v1+9j2IBbnmbz3desiiJdv06yGNaocmvhtNPsZOa58QaNvQxC7Za/LZTG7WTubYXRUpWf7rNNf3ZCw2E3yfYRAN5Ps1KbOxesPoJaDJXVDHbvZKYHVRHDfHOAoBdApFyg5lXW5HJzOGitPLnlbnEeuazzrfjj2/pWwyM85zW8DtP5yenJpLTrVE+7rvZzsipyY73KpAOERlavihR4y9GsgmluUVSWjaPu+am75d44dwNwYfIqg/Qyi5ka+K4jtD+olq00NEzoTXC9Y88vvvXIs9zE2pwZFSdVuXv4cGA6yYrK9gHcwdUm8G/jTKXJAhJ4lcRxqg+tntm8GHt0x3J3NMutzVe7p4em0VIrANo3Poe/RGf37dIwy9N4X3wy6sd7Eid3XhK/PPJv0ItSVZZwMq/S9Dr5S9+cTCcj4D8QTXPlQH8Cx1O1dmxLMv2lISKEJiP4PC65KcDN9U+sS7bp1qGJneXxetofhBNrpruDcWLj6ddeynptTk9GcHDIuj/FJ80d2nWhXSTc3jjLv0EIIEvV2Qx6QEd2PetIbfQcaDXuGwbCHujjXly6svFc3Xht4Xhddf2bPj1Src/2Cz53rgu+e/fZT4K/AQ

### Environment

Browser: Firefox, Chrome
CesiumJS Version: 1.122
Operating System: Windows

**Comment by ggetz** [comment]
Hi @anne-gropler, this clipping is due to the depth plane. You can offset this lower with [the `depthPlaneEllipsoidOffset` option](https://cesium.com/learn/cesiumjs/ref-doc/Viewer.html#.ConstructorOptions). For example:

```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  depthPlaneEllipsoidOffset: -1000.0
});
```

**Comment by anne-gropler** [comment]
@ggetz awesome, thanks a lot! I was searching for options on the globe and terrain and didn't think of options on the Viewer. It now works perfectly for my use case!
