### ISSUE TITLE
When adding labels, the screen flashes black

### ISSUE THREAD

**Issue by netcanol** [CesiumGS/cesium#12261]
### What happened?

When adding tags, the screen flashes black，For details, please see the example,。after initializing Cesium, and then adding the geojson data with labels, there will be an instantaneous black screen, and it also includes creating several new labels separately。
This bug appeared in version 1.122 and in 1.119 it was fine；

### Reproduction steps

1.
2.
3.
...

### Sandcastle example

https://sandcastle.cesium.com/#c=bVJdi9swEPwri/tiQyJfj3soji+Uu7610EJKn/yyljapiCwZfeR6LfnvlSznkpAz2Eg7OzujkbnRzsNB0gtZeARNL/BMToaB/ZpqZVfwaf9stEepyXZFtep0p/nENKOXcRGp/zoNwHEgi808kDlOmlguLjKuD+hu8FSM+HEavEEtODqviKEQP41RPdqn4L3R0Y0yKECgx65YwDZonvShrJJ+tpTAjQmW0w9rBukompv1zpBLs8tkaT7u10F9eUNZUplQgK5grN7gMCpKDfV+UPUWuVTSS3IXSxaRaCqz5lymXRW/1epYrYpF0Tr/qmidmwA+y2E01kOwqowynqIM+ji2D3xPnnHnUtq5+YPPWeSo89Mj3++sCVo0YHc9lg/3Czi9d+zTmQ0wxiNLvWvgYfxzUe6NFWSXFoUM7ho83khLPQZ/aeBA1kuOaolK7nQDgxRC0a3q0puxgfsr5RPUm3i5wzU6S7f1ZWCtkAeQ4vGdnxK4Qucisg1KbeRf6op1W8f+G2q626j6PTpX+Jrafn9cf8tFxlhbx+37zDmESDm5PJk8d/8H

### Environment

Browser:
CesiumJS Version:1.122
Operating System: win11

**Comment by ggetz** [comment]
Thanks for the report @netcanol! 

I think this is the same bug as https://github.com/CesiumGS/cesium/issues/12231. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
