### ISSUE TITLE
Carto basemap link not working in our doc examples for `UrlTemplateImageryProvider`

### ISSUE THREAD

**Issue by lukemckinstry** [CesiumGS/cesium#12272]
### What happened?

In our docs for `UrlTemplateImageryProvider`, the basemap service from Carto is not loading imagery on the globe. It appears the service is still active https://github.com/CartoDB/basemap-styles.

The following code does not load tiles in sandcastle
```
const viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider: new Cesium.UrlTemplateImageryProvider({
        url: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        subdomains: 'abcd', // Carto supports these subdomains
        credit: '© CartoDB'
    }),
    baseLayerPicker: false // Disable default base layers if you only want the Carto basemap
});
```

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
@lukemckinstry The `imageryProvider` option was deprecated and [ultimately removed in version 1.107](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#1107---2023-07-03). Use `baseLayer` instead:

```js
const viewer = new Cesium.Viewer('cesiumContainer', {
     baseLayer: new Cesium.ImageryLayer(new Cesium.UrlTemplateImageryProvider({
        url: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        subdomains: 'abcd', // Carto supports these subdomains
        credit: '© CartoDB'
    })),
    baseLayerPicker: false // Disable default base layers if you only want the Carto basemap
});
```
