### ISSUE TITLE
Inactive OGC Web Services (OWS) URL in our doc examples for `UrlTemplateImageryProvider`

### ISSUE THREAD

**Issue by lukemckinstry** [CesiumGS/cesium#12271]
### What happened?

In the doc examples for [`UrlTemplateImageryProvider`](https://cesium.com/learn/cesiumjs/ref-doc/UrlTemplateImageryProvider.html?classFilter=UrlTemplateImageryProvider), it appears the url we provide for the OGC Web Services (OWS) server provided by the Australian government is no longer active 
http://programs.communications.gov.au/geoserver/ows?service=WMS&request=GetCapabilities

It is possible the service is active but moved, but I could not find it with a quick search.

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
@lukemckinstry I'm not sure what the word is on that particular services, but the documentation could be updated to use the same service we are using in our [WMS Sandcastle example](https://github.com/CesiumGS/cesium/pull/11948/files).
