### ISSUE TITLE
Features Checklist: Broken Link

### ISSUE THREAD

**Issue by jlpoolen** [CesiumGS/cesium#12280]
### What happened?

https://github.com/CesiumGS/cesium/wiki/CesiumJS-Features-Checklist

The sentence "Use legacy Google Earth Enterprise [terrain and imagery](https://sandcastle.cesium.com/index.html/?src=Google%20Earth%20Enterprise.html)" has a link to:

https://sandcastle.cesium.com/index.html/?src=Google%20Earth%20Enterprise.html

which, in turn, results in error:
```

    4[0]4
    Page Not Found
    The link you followed may be broken, or the page may have been removed.

    BACK TO HOME
```

### Reproduction steps

1.  Visit https://github.com/CesiumGS/cesium/wiki/CesiumJS-Features-Checklist
2.  Click   "Use legacy Google Earth Enterprise [terrain and imagery](https://sandcastle.cesium.com/index.html/?src=Google%20Earth%20Enterprise.html)"
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by jlpoolen** [comment]
Also broken: "Draw [3D models](https://sandcastle.cesium.com/index.html/?src=3D%20Models.html) using glTF 2.0"

Underlying link: https://sandcastle.cesium.com/index.html/?src=3D%20Models.html

Maybe everything to the subdomain "sandcastle" is no longer available?

**Comment by jjspace** [comment]
Thanks for noticing @jlpoolen, all the links on that page should be updated. [Sandcastle](https://sandcastle.cesium.com/) is very much still active and a great resource for developers. The links on that page just had an extra `index.html/` that was affecting the routing.
