### ISSUE TITLE
Flickering label tileset since 1.121

### ISSUE THREAD

**Issue by lukemckinstry** [CesiumGS/cesium#12287]
### What happened?

Since updating to 1.121 (user skipped directly to 1.122 but could not reproduce this with 1.120 or prior) user has a label tileset that keeps flickering.
Reported on forums here https://community.cesium.com/t/flickering-label-tileset-since-1-121-0/36316
User has not changed data since issue started occurring. 

[Here’s a sandcastle with the tileset in action](https://sandcastle.cesium.com/#c=bVJra9swFP0rwgziQCrlsbUjdcNGsw+DwgZxxwaGocg3iTZZMro3ybKS/z5ZSrp2q75I555z7stWziKxnYY9eHbDLOzZLaDeNvxLjOVVpiK+dZaktuCrrH9dWRV9qMBCsCU/jzCQZ5q0AQQKArmXms6Z0zWZl4nmK++ae2/y3oaoxakQk5qvwXFZN9pytQn4IqYSasNxrxHJtS69rGwAg35Si/Fw9HZ4NboUp7L8Bzrb65o9B5AOBp5P+bSXRUfnD5VlzMglmIinbDx4jJTwi6as9+ph/nHx+e79t+/lh6/lsRcEx36cO26At143mvQOMMxQ56fySXFalQp9e8lX5lC6VJKxGpC0laSdnT72Jz2Fl7STuKY5rD0A5snQnSv+ZvAXvb58BsfD7iTc765jZfvX2SAr4ipmZ+U73bTOE9uGr8C5IGhaI0Ndsdyqn2FxCrHrvpMW4qm1qPWO6frmhb+EKSMRA7PaGrPQv6HKZoUI+v+sxsla2/WnHXgjD51sM5rdpSDnvBABvuwk58xS+n8y/wE), try zooming or moving around Switzerland and you should see black flickering all over the place.

I am able to reproduce the issue on prod sandcastle.

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
Thanks for opening this report @lukemckinstry!

I think this may be a manifestation of https://github.com/CesiumGS/cesium/issues/12231. I'm going to close your issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
