### ISSUE TITLE
About gammaCorrect.glsl and invertGamma.glsl 

### ISSUE THREAD

**Issue by newpeople123** [CesiumGS/cesium#12295]
### What happened?

Is the content in Source/Shaders/Huiltin/Functions/gammaCorrect.glsl and Source/Shaders/Huiltin/Functions/invertGamma.glsl reversed? gammaCorrect should be ‘color=pow (color, vec3 (1.0/2.2))’, invertGamma should be ‘color=pow (color, vec3 (2.2))’?

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.

It looks like [your thread with this question was answered](https://community.cesium.com/t/about-gammacorrect-glsl-and-invertgamma-glsl/36244). 😄 

 Thanks!
