### ISSUE TITLE
PolylineMaterialAppearance::fragmentShaderSource & FragmentInput struct

### ISSUE THREAD

**Issue by mickae1** [CesiumGS/cesium#12305]
### Feature

Hi,

I think that there is no way at this moment to pass the FragmentInput struct to the custom shader PolylineMaterialAppearance :: fragmentShaderSource.

Is that correct ?

If it's true, I would like to be able pass custom attributes : 

> Custom attributes are also available, though they are renamed to use lowercase letters and underscores. For example, an attribute called _SURFACE_TEMPERATURE in the model would become fsInput.attributes.surface_temperature in the shader.

https://github.com/CesiumGS/cesium/blob/main/Documentation/CustomShaderGuide/README.md

With fragmentShaderText it's possible to pass the FragmentInput struct, but not with fragmentShaderSource

why ?

```
 fragmentShaderText: `void fragmentMain(
    FragmentInput fsInput,
    inout czm_modelMaterial material
  ) {
```

I'm interested to get the attributes in the call of the function czm_getMaterial()

**Comment by ggetz** [comment]
Hi @mickae1, CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by mickae1** [comment]
> Hi @mickae1, CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

I tried in the forum, but no one answered me :

https://community.cesium.com/t/custom-shader-attributes/36603
