### ISSUE TITLE
Wrong camera position in 2D mode

### ISSUE THREAD

**Issue by a-milenin** [CesiumGS/cesium#12318]
### What happened?

Camera object return wrong position in 2D mode

### Reproduction steps

1.  Zoom In to some place
2. Click "Pick camera position"
3. Check that viewport and camera position is correct
4. Switch to 2D mode
5. Zoom to some place
6. Click "Pick camera position"
7. See wrong camera position

### Sandcastle example

https://sandcastle.cesium.com/#c=fVPBbtswDP0Vwpc4QKCsO7pOMDQLsAEFNrTdevFFkZmUKC0ZEp2uK/LvU+zYCbIgF9skHx/foyzjbBDYEr6hhxlYfIMFBmoq9bvNpSPThgtnRZNFPxrfFrawj9qWRgdhVLosn5zjlfZ3jYiz6egnmVcwukKvoXaBhJwdTSAdw2wOH4UFMO3Yj6EKuzi8U6G6xtsjzKMRbTeM5xhlXFU3gnupDz0oPUCCQYtqw26FCpmpDo7KTjwArSEdaMedJujJ0UoUhWHvLD2U4KgigyEHsCbmDNaaA06O2UoLetKxcljmwrHz6u7+1/IEZZzzJdmIDdmR/gTgGuG48wzENxfyLem1EbvD127cbnPXeb/isj+OSR+SlRO7Nf1BfqS/UdHNp2GKuSDjYfl1qF9R+/zt+9PyHPhMpbxk8LkX375bC+0jmSR5kHfGed/3haraeYHGc6rUVLCqeb/U6aoxryjKhNAtACCfnrbmJW2BylmRnP3kRQKGdQixsm64tVwk83wa8f+1stPxEDc/tuhZv+9hLzfz+y6plMqnMbzcKd2tOWP+Bw

### Environment

Browser: Chrome
CesiumJS Version: 1.123
Operating System: Windows

**Comment by ggetz** [comment]
Hi @a-milenin, I think `position` here is in a different coordinate system than you expect. [`positionWC`](https://cesium.com/learn/ion-sdk/ref-doc/Camera.html#positionWC) will give you the camera position in world coordinates, which should be the appropriate value here.

I think your concerns are captured in https://github.com/CesiumGS/cesium/issues/4346.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
