### ISSUE TITLE
Depth Test Failure / Z-fighting

### ISSUE THREAD

**Issue by TJKoury** [CesiumGS/cesium#12337]
### What happened?

In 1.123, intermittent depth test failure or z-fighting issue.  Not present in <1.122, unsure if it was introduced in 1.122 or 1.123.  Goes away if `viewer.scene.globe.depthTestAgainstTerrain` is set to true.

![image](https://github.com/user-attachments/assets/ad544eed-a298-429f-aef6-09640617c479)

### Reproduction steps

Open sandcastle, track GeoEye-1, see the primitives show through the globe.

### Sandcastle example

https://sandcastle.cesium.com/?src=CZML.html&label=DataSources

### Environment

Browser: Version 131.0.6778.85 (Official Build) (64-bit)
CesiumJS Version: 1.123.1
Operating System: Pop!_OS 22.04 LTS

**Comment by jjhembd** [comment]
@TJKoury thanks for the report!
I wasn't able to reproduce the bug on Windows. 
![image](https://github.com/user-attachments/assets/e7c59046-d44d-435a-b567-e1a1c4ced270)

Could this be OS-specific? Something about depth textures not supported?

**Comment by TJKoury** [comment]
![IMG_2550](https://github.com/user-attachments/assets/c5cb3ba1-3c74-4489-9c55-5d1cf4e2043c)

Maybe, however here it is on mobile using an iPhone 14 Pro Max.  I have not tried it on Windows.  Track one of the satellites and see if that makes a difference.

It definitely did not do this prior to 1.122, some of the recent shader / pipeline work would be my guess.

**Comment by jjhembd** [comment]
Thanks @TJKoury,
When I track GeoEye1, I can sort of reproduce: I get brief flashes (maybe 1 frame) of the other side showing through. It only happens near certain time stamps.
Just wanted to let you know I'm working on it. I'll still need to refine my test case a bit, before I can properly trace back where it broke.

**Comment by jjspace** [comment]
@jjhembd this was also reported in https://github.com/CesiumGS/cesium/issues/12371, might be another good sample sandcastle to help track this down.

**Comment by Rubeanster** [comment]
Yeah I see the same issue since I upgraded from 1.114 to 1.124. Seems like while tracking an entity I get flickering from other polylines. I couldn't get it to happen while not tracking an entity but working with the camera is a bit harder in that case to orientate it so not certain on that one.

**Comment by jjhembd** [comment]
I traced the bug to a single line from #12188. We changed this:
```glsl
    positionEC = czm_modelView * position;
    gl_Position = czm_projection * positionEC;
```

to this:
```glsl
    positionEC = czm_modelView * position;
    gl_Position = czm_modelViewProjection * position;
```
Reverting this change fixes the bug on my machine.
