### ISSUE TITLE
How To load *.3tz

### ISSUE THREAD

**Issue by YOOSHIN-Yang** [CesiumGS/cesium#12378]
### What happened?

I have a *.3tz file. How can I load it with CesiumJS?
![cb2601392df8916d265456426f13939b2fa6e6c5](https://github.com/user-attachments/assets/1a057dc5-b42b-40c8-b298-568d0df8300b)
![a0e8fd02576acb176e6bd4d8830a26950620e98d_2_690x388](https://github.com/user-attachments/assets/da8270a0-7608-41c0-b96e-91e24846b6fa)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by javagl** [comment]
This was also asked (and answered) in the forum at https://community.cesium.com/t/how-to-load-3tz/37419/2

**Comment by YOOSHIN-Yang** [comment]
thanks

**Comment by YOOSHIN-Yang** [comment]
thanks
