### ISSUE TITLE
We need better credit management.

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#1245]
`CreditDisplay` does not have a way to iterate over existing credits, making it impossible to remove the Cesium credit without accessing private members.  We should also add an `id` properties to Credit so that you can easily find a credit in the display.

**Comment by garymazz** [comment]
Some of us who would like to use CesiumJS are obligated to have a formal credit and copyright pages in the app. The current mechanism prevents us from easily achieving this requirement.  Maybe an air of professionalism and trust in your user base is a good reason to better manage the credits.

**Comment by R1im** [comment]
Im making a game on top of CesiumJS and the 3 rows of credits in bottom look really bad on phone - taking 10% of display under it. I would like to replace it with just a logo in corner and giving credits in beginning of game and in menu

**Comment by pjcozzi** [comment]
@R1im - @hpinkos is working on improving credits in the [collapsible-credits](https://github.com/AnalyticalGraphicsInc/cesium/tree/collapsible-credits) branch.

What kind of game are you making?  Do you have a link to a demo? 😄
