### ISSUE TITLE
TileMapServiceImageryProvider can't handle casing differences in tilemapresource.xml

### ISSUE THREAD

**Issue by shunter** [CesiumGS/cesium#1299]
Mentioned on the group: https://groups.google.com/d/msg/cesium-dev/5u0HprX3WQs/6nFctSXdQhYJ

We use `getElementsByTagName` to retrieve values from the document, but that function is case-sensitive for XML documents, unfortunately.  What we can do instead is iterate the nodes in the document and check the node names with a case-insensitive regex.

**Comment by 2014sisi** [comment]
everybody i wanna download tilemapresource.xml but i could not find it
