### ISSUE TITLE
Dynamic Ellipse Performance

### ISSUE THREAD

**Issue by weull** [CesiumGS/cesium#1515]
On the current master (commit 72b6ddc9bf5c68c15b93c3bc47690f55fbc35c0f) , Cesium performance degrades greatly when rendering DynamicEllipses via CZML.  This has only become an issue in the last week or so - previous commit that I had tested where it was fine was 46c9ecc6d4b04ec6d90ef27b8ced61e198d3d605.

I've attached a DevTools CPU profile export (Cesium was idle at the time) and the CZML used for profiling.

CPU Profile:
https://www.dropbox.com/s/7lwo23f11vheway/CPU-20140227T160058.cpuprofile

CZML:
https://www.dropbox.com/s/7uk26trux0huahg/ellipses.czml

**Comment by killroy42** [comment]
Hmm, has this been resolved? I still get terrible performance. I am visualising around 110 entities. I can easily show a complex 3d model with each without any performance issues, but showing an ellipses with granularity = 1, just a few triangles, really tanks fps to be unusable. Should I load a model of a circle in? What am I doing wrong?

**Comment by hpinkos** [comment]
@killroy42 If your ellipses are dynamic, they are recomputed and redrawn every frame and this can have a negative impact on performance.  However, I wouldn't expect poor performance if your ellipses are drawn once and you're not changing the position or other properties.  Depending on your use case, I would probably recommend using a point instead.
