### ISSUE TITLE
Use longer dimension for camera Field of View (FOV)

### ISSUE THREAD

**Issue by emackey** [CesiumGS/cesium#1591]
Currently we have `camera.frustum.fovy` which represents the FOV along the vertical axis.  The downside is it's hard to establish an upper limit for the FOV in both the horizontal and vertical.

In STK, the FOV applies to the larger window dimension.  If the 3D window is wider than it is tall, the FOV applies to the width, otherwise the height.  This keeps the display more reasonable during window resizes by establishing an upper bound to the FOV.  I recommend Cesium should adopt the same behavior.

**Comment by pjcozzi** [comment]
I know this is closed, but folks interested in this issue, but also like http://www.gearthblog.com/blog/archives/2015/03/google-maps-earth-view-fov.html
