### ISSUE TITLE
Path trail/lead being drawn when no data available

### ISSUE THREAD

**Issue by GatorScott** [CesiumGS/cesium#1704]
Position data exists exactly for CZML stream interval but Viewer is attempting to draw trail/lead to non-existent data.

**Comment by OmarShehata** [comment]
It looks like even with the availability set, the path is still drawn. This came up [in this forum thread](https://groups.google.com/d/msg/cesium-dev/ACU_OBLeyYA/kKMw_sQ7AgAJ). Notice [in this Sandcastle](https://www.google.com/url?q=https%3A%2F%2Fcesiumjs.org%2FCesium%2FBuild%2FApps%2FSandcastle%2F%23c%3DzVh7b9s2EP8qRP6xvKqSndcaJynmutmawWmM2GsxNEVBS7RNhCIFknKSFvnuOz4kS44dJMCG1QgiWrw373539BJLtKTklkh0iji5RQOiaJFFn%2By7oJXYrwPBNaacyFaIflxzBB%2FKZ%2BKduOuhGWaKhCiO31OFp4ygc7eDbmk6J9pRK8JIoqng5zylCdZCbmCsiEC4p%2FLcC1GwtM9phjXpIS0Ly4fOuOXDdgP4lCPXREqwdiTFkqYENHmfEkmA%2F7OQLJ04kqB9zR%2Fax9f8msexl8bofKEpn6MpViRFYI0qeJwJWORCUa%2FHxSxSCeEkmjMxJRGx%2FMOS%2FdTa2ZSdklwvwD5lKZRAegELhaYEnil8I6XxKIWg5DnBMtqozEqagKD%2BHKiV9g41tY6JtjIl5qnIEC%2ByKZyzIuDWTEiUgCdUacI1kkQVTCvQ5WN1gfUiUkRfWdaPlnMMjMFeuyZ8KgqeKiRmSBQgmGYFsweBNM0I2A3JpTSWGszycv8sGMX8PZxDNJMiM4vApJ1d7Ha6ByHahT94dA%2FbRpWTIfKNInCajgm4karA6gnR3mEnrOfxijhol5Zf4BtItkKSMvOpQthFKgUuCeEx9q8CnzCR3ERWwwQ2nmWKYeKgNESvu09atKZD5M9TIfKVhhcoSAop4cC9joalj0jNfzj%2Fec2aQfUuGl5ejr6NJ5ejYyjFoYAT8jEkPF2TBGmhac6oBZlup56dYAcDYEFa1NPH5VUlpaSKvguRTUR51iYI5Zn%2BAaUhwWWEy2xPqExAnkQ51lBUHPAIag%2FS6d7U3oKYOjUJPyu4A51EZHmhyQD4mGH83SJBAMEJEdgVguCUFqpdIqDJzFyKnEh93wTPMc5yRtKRh4uRJ7IhNpym%2BALDToGvcwyPk1OTuWb16hTtH1Q6Sj1GNeZqdRC2PrW4cu8DWoouGfRz8zRE9MnsqQst8a%2BWDyABVpjvuXImc0mIMjFDr1DgAoZ%2BQd3oAP5bmxOhAu9Nu20D26B0uAPIXKOpu8zJXQOTgrYRf9DpgJTurwedusnl4Vif7ZEEJixh5YdLnpI8jvsMINl1CcijXFBARnNWBCcLpKwEdEvQ3OdaVIuOS1SoLBBMlNEY1I7QfPASU4anlFFIl1495KYYzznk6BKzgWC%2BCQZftpCsC7Yd0qJszz3DTftQnz37aG4%2BtL%2B21%2BirU%2B5Vy0cUJjI9tMGQnN4RNqbfCWy%2F2WBIIhgEtGrJA%2FM1mlz1P45H%2Fauzj5MNLKLQpvgHmzj%2FPhsOLz9vZ%2FpMUyj6Htpb83r19aHMGP9OEl0AWJS5A5sPDmEGDh48xGlzilWkqkxz%2FapWJ1tA5XW3uxt1u53Doz3Ts6LO0dH%2Bm33A8U7UqTpsP9EFZuy%2BTMmVZqfGW3G6LfucQ6sxwNM3ElELuwXJTWDqcgmGsHIvm%2F3cp%2Ft%2Fksfb8vdR3vp8LV37SxE7evgwp%2FURbXsul9z9QgszOSYuyv6AhaQQKd%2BIyhmwEpSJJclg30ejTtwIxicCrQ9CdLkiqPpAhT81W4YCuwHQ8aOcYWiLmUgJM4ckSQ4zmhnV6llgWB1JoxgLSeFFK4ri6q%2Bf5yp2IAjYjmPLpWKnrE%2BlX32DJUyYetaqHUJGYcAuslGttA%2F3%2FXHUPBgvxK21DhruwuQQQCjlN8j2d4eeKeQY6sIEahoQrCGxTSyVD6ZlbHhiBn5JMWvG1tb%2Bhd%2BqoroBGOrQduuhoCEHJmfMdSVit11hQXUt6KcpmhZamyoQttRWTpqe56Z2SNNU3ALDGJpTgpVmttW%2BJzMMw89ECDbF8p0VE7TM5QpNgOU9sMCVqhxBgtVs4QcfiZMbkp6VhQ5TEZlBONPjBpkfi9ZgoNHWPxDop3w%2BojpZ2Pkt6IRbZonXR522bf0vC4GCu9a6%2B5v8HgPd%2F%2BXzdoe3BqN7AHswWHSeCom1uYGxClFtsUI9JyZQdYnEM%2F2SuDhN6zZhA2NTARP0nR1d%2FJ0aJl47xFiIz4VHdQMC0Rb7Lggvgi8%2Fyhv1nUHn1nmdvYeGcCzQhwBbpLjzd%2FASOKC0rGpge%2ByS%2BTj7oxILzWWzIf4ytzi%2BPu00PHDzJqjohk9Q9dkcYFovstX04CxvGL55JHiofvDYFgM8l%2FaONBLsnovMgNVPEJCDlwbEu7Hy4t8IzgciM6p%2FttjsvjA23ouXheZriFoNwaagWoZiJ9w5UfqekbeO%2Bjea5QKmn0KyADq1JtApobepeFpAwcP1XCnDdhKXTCcpXSKanl7vrP06d72DEoaVgp1ZwWyvvt55exIDfYONCQuMl0siGb43JIvu26F7GUXRSQxfH3NpBwxA7uxe7Tzys67VP%2F8B&sa=D&sntz=1&usg=AFQjCNHwfRa9r5jNu9A6_pSl-PFnR3AhHQ), if you go to the very end or beginning of the timeline, the entity and points will disappear, but not the path.

The user fixed their issue by adding an extra `entity.isAvailable(time)` check in this line:

https://github.com/AnalyticalGraphicsInc/cesium/blob/54acd32f50c332605615a7b37b774c04690ef55c/Source/DataSources/PathVisualizer.js#L290

I wonder if the better approach is to have `isShowing` be false when the entity is not available? Or are those intentionally two distinct concepts? In any case, it sounds like we agree the path should be hidden in this situation.

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/9981
