### ISSUE TITLE
Inline examples in documentation

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#1839]
Currently, the quality and usefulness of our inline documentation examples is all over the place. As we're reviewing the entire code base for 1.0, it would be nice to determine some guidelines and standards for when and how to write a good inline example.  Obviously some of this stems from the fact that our codebase has changed over time and we have all learned a lot in the last couple of years.  I've been thinking a lot about this stuff while refactoring `JulianDate` and `TimeInterval`.

In my opinion here are some of the problems with the current examples (I'm guilty of some of these as well)
1. We overly document truly trivial things.  [Billboard](http://cesiumjs.org/Cesium/Build/Documentation/Billboard.html) is a good example of this.  Look at `horizontalOrigin` and others in that file.
2. We under document more complicated examples or provide examples that are "in a bubble" and useless without context.  For example, [CircleGeometry](http://cesiumjs.org/Cesium/Build/Documentation/CircleGeometry.html) could add a few more lines to actually show a complete example that creates a primitive and adds it to a scene.  This could also link to a running version of the same example on Sandcastle. (This is probably true for most if not all of the Geometry examples).
3. Quite a few examples seem to be carbon copies of each other; for example see `fromRotationX` and `fromRotationY` on [Matrix3](http://cesiumjs.org/Cesium/Build/Documentation/Matrix3.html).  The Billboard page I linked above does this too.  We also tend to copy some examples across objects, for example we have the same `destroy` example on almost every page and I'm not sure it's a useful example to begin with.
4. In some places we use incomplete examples or things like `...` for brevity.  For example see the bottom of [LabelCollection](http://cesiumjs.org/Cesium/Build/Documentation/LabelCollection.html).  This can lead to incomplete or missing information to the user; who is left wondering what "magic" happened in those lines.
5. Overly complicated examples that don't really add anything.  For example, [Matrix3.getEigenDecomposition](http://cesiumjs.org/Cesium/Build/Documentation/Matrix3.html#getEigenDecomposition).  I would personally get rid of the example, document the return type properly (as `EigenDecomposition`) and link to a wikipedia article on Eigen Decomposition.  I think the example is superfluous.

Obviously, there's no one magic set of rules that can be made for all documentation, since different types of objects require a different approach; but here are some potential guidelines I think we should consider.
1. Don't duplicate examples or mostly duplicate them with extremely trivial differences (particularly within the same file).  Instead, have a single set of examples on the constructor function that shows off most of the functionality of the object in one place. This helps eliminate duplication and give an overall feel for how methods work together.  For examples that are duplicated across files (such as `destroy`), it's better to include information in the to be written overview documentation that discusses general concepts instead of having an example.
2. Examples shouldn't try to teach people how to program, they should teach people how to use the API.  This means that not every method needs an example that shows something trivial like how to assign a property or how to call a function.  It's better to have no example and reduce the overall noise of of the documentation.
3. For types that are part of a larger piece (especially for very simple one (in the API sense) like CircleGeometry), have a simple but complete example for each type and then link to the tutorial and Sandcastle example that shows the big picture.  This is also true for items that work in pairs; for example Billboard can probably link to BillboardCollection and example and Label could link to LabelCollection and example rather than have their own inline examples.
4. For more complicated examples, consider linking to a Sandcastle example rather than have an inline example at all.

As I said, these are my own opinions from trying to use our compiled documentation as well as working on Cesium; but hopefully it can spur a conversation and help us come up with a set of guidelines we can all agree on.  I'm sure I left some stuff out and I'd be shocked if everyone agreed 100%.  What do you guys think?

**Comment by ggetz** [comment]
While these are useful principles for good documentation going forward, we're unlikely to do a pass over all previous inline docs. 

Since there's nothing directly actionable, I'm going to go ahead and close this.
