### ISSUE TITLE
gLTF Model Material Transparency Issue with setValue

### ISSUE THREAD

**Issue by Digicrat** [CesiumGS/cesium#1841]
On a gLTF model, I can use getMaterial() to get a reference to the material, and then the set/getValue() methods to adjust certain attributes.  

For the transparency attribute, however, I'm finding that I cannot adjust the transparency on a given material unless it had a transparency level set in the original model. And once it's set, I am unable to remove the transparency - even if I setValue() of the material's transparency back to 1 that material is still partly transparent

My use case here is that I want to start by showing the exterior of the model only, but when requested I will make sections of the outer skin transparent to reveal the internal components.

**Comment by rtemplin15** [comment]
has their been any updates to Cesium to fix this problem?

**Comment by pjcozzi** [comment]
No update, but perhaps the workaround above will be reasonable for you.

**Comment by hpinkos** [comment]
@lilleyse was this fixed with your recent model color changes?

**Comment by lilleyse** [comment]
It's close, but this is targeting individual materials whereas the color changes affect the whole model.

**Comment by j9liu** [comment]
This issue will no longer be relevant as of the 1.97 release since `ModelMaterial` will have been removed.

**Comment by XiaoHu1994** [comment]
@lilleyse 1.102.0 Can we consider adding a name attribute to ModelComponent.Material? This is convenient to do some custom material mapping

**Comment by lilleyse** [comment]
@XiaoHu1994 Sure, feel free to open a PR to add that.
