### ISSUE TITLE
Missing mouse exit/up event?

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1855]
- Run Sandcastle
- Zoom in and middle mouse tilt/rotate.  Hold down the middle mouse and leave the Cesium Canvas.
- Let go.
- Move the mouse back over the Cesium canvas and it is as if the button is still pressed.

In b29.

Perhaps this is not fixable because we don't get the up event?  Can we get the document's up event?

**Comment by pjcozzi** [comment]
Maybe related to #2522

**Comment by bampakoa** [comment]
@pjcozzi I can confirm that the described behavior is valid for Chrome. In the case of Firefox and Edge, when you leave the canvas and move the mouse, the tilt/rotate action is still active. If you let the mouse and go back to the canvas, the button does not seem pressed anymore.

**Comment by jjhembd** [comment]
This only happens when Cesium is run inside an iframe. It is therefore low priority.
Closing for now, though we will still be happy to review a PR if anyone wants to fix it.
