### ISSUE TITLE
JSDoc Issues

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1859]
Part of #1684 for post 1.0.  We should consider submitting issues for each to JSDoc.
- [x] After #1729, array types do not create links to the element type.  Not investigated yet.
- [x] Modules containing functions do not show the function signature.  Example `binarySearch`. This is because it can't tell whether the module is a function, or an object (example `WindingOrder`)  This may be fixable in our template.
- [x] Functions still must be declared as `var Foo = function()` instead of `function Foo()`.  I assume this is a parsing problem in JSDoc that we cannot fix on our end.
- [ ] `@link` inside `@default` does not create a link in the documentation, e.g., `@default {@link Cartesian3.ZERO}` just turns into `Cartesian3.ZERO`.  `@link` tags elsewhere appear to work.
- [ ] #832 - `@exception` for ECMAScript 5 properties.

**Comment by pjcozzi** [comment]
@mramato any update if these are still relevant with the latest version?

>* @link inside @default does not create a link in the documentation, e.g., @default {@link Cartesian3.ZERO} just turns into Cartesian3.ZERO. @link tags elsewhere appear to work.
*  #832 - @exception for ECMAScript 5 properties.

**Comment by mramato** [comment]
I'm pretty sure they are both still relevant, but we should actually try and see.  I'll do that when I get a chance.

**Comment by bampakoa** [comment]
@pjcozzi @mramato I can confirm that both

**Comment by bampakoa** [comment]
@pjcozzi @mramato I can confirm that both

> - @link inside @default does not create a link in the documentation, e.g., @default {@link Cartesian3.ZERO} just turns into Cartesian3.ZERO. @link tags elsewhere appear to work.
> - #832 - @exception for ECMAScript 5 properties.

are working with the latest version.

**Comment by pjcozzi** [comment]
Thanks for the research, @bampakoa.  @mramato if/when we are on the latest version, can you please close this?
