### ISSUE TITLE
PerformanceWatchdog page - Default column is too wide

### ISSUE THREAD

**Issue by PatMahoney** [CesiumGS/cesium#2059]
On the PerformanceWatchdog page, the Default column is too wide. It extends outside the border of the   rounded-corner blue border box. The causes the Description column to be extremely narrow. Perhaps the Defaut columns can be given a maximum size?

**Comment by ggetz** [comment]
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
