### ISSUE TITLE
Investigate new triangulation library

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#2074]
https://github.com/mapbox/seidel

Investigate for speed and robustness.

In addition to the runtime for the algorithm itself, we also care about the shape of the triangles that it produces since this will impact the speed of the Cesium subdivision step and the number of triangles it produces.

@DavidHudlow this may be of interest to you.

**Comment by mourner** [comment]
@pjcozzi FYI I wrote a new JS library for triangulation, this time much more robust while being many times faster. It's pretty awesome. Check it out: https://github.com/mapbox/earcut

**Comment by mourner** [comment]
It focuses on triangulation speed over quality though — producing less sliver triangles is something I might look into in future.

**Comment by pjcozzi** [comment]
Thanks for the note @mourner.  We'll have a look when we revisit this again.
