### ISSUE TITLE
Material Polyline demo needs better polylines

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#2109]
They currently cut through the earth and look really bad if you rotate to a horizon view.

**Comment by johnknelson** [comment]
Looks like it's been a while, but I'm curious, has it since become possible somehow to have a PolylineCollection follow the surface? I'm facing this issue and wanted to double check before I tried reorganizing my efforts into an EntityCollection.

**Comment by hpinkos** [comment]
@johnknelson yes, you can use `PolylinePipeline.generateArc`.  See the development Polylines example: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/gallery/development/Polylines.html#L61-L72

**Comment by hpinkos** [comment]
We do generally recommend using entities though, because they do handle a lot of those kind of options for you
