### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by trusktr** [CesiumGS/cesium#2321]
The following WebGL globe example seems to have a higher/smoother frame rate than Cesium: http://thematicmapping.org/playground/webgl/earth/

Why might this be? Any techniques Cesium can adopt?

**Comment by trusktr** [comment]
Nice, it's been a while, and this issue has since been fixed. The rotation/pan animation is smoooooth.

**Comment by lilleyse** [comment]
> I'm noticing the very slight lag just from rotating without zooming.

Yup, this was fixed in https://github.com/CesiumGS/cesium/pull/8811

> Fixed what seemed like a kludge in the camera panning code which had the side effect of panning every other frame. Basically panning felt like 30hz while other camera controls felt like 60hz. Panning feels so much smoother now.
