### ISSUE TITLE
Deprecate viewer.scene

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#2350]
Depending on how #2183 and future `viewer` getters work out, we may deprecate `viewer.scene` since users won't need to reach into it.

**Comment by emackey** [comment]
Don't we still have a lot of public API that requires a `scene` parameter as an argument?

**Comment by pjcozzi** [comment]
Yes.  We'll get there.  No rush.  This is not targeted for a particular version.

**Comment by mramato** [comment]
@emackey if you haven't been following #2315, you might want to check it out.  It starts to paint a picture of where we are going.  You should also try the Sandcastle in #2382 and let me know what you think.  At some point I'll probably make a request on the mailing list to get eye-balls on this stuff, maybe before we go into master, maybe not.

**Comment by emackey** [comment]
Yep I need to get up to speed on all that.  I'm sure you guys are still planning to leave some path for the render-to-texture folks, who today would create a scene with no viewer or widget attached.

**Comment by ggetz** [comment]
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
