### ISSUE TITLE
A question about how to draw triangles in Cesium?

### ISSUE THREAD

**Issue by zhangxianggis** [CesiumGS/cesium#2351]
hello, I want to know how to draw triangles in Cesium. 
Each vertex is a geopoint(lon,lat,elevation),and render each point use diffrent color?

here is my code but it always has some mistake

Thank you very much!!!

An error occurred while rendering. Rendering has stopped.
DeveloperError: All attribute lists must have the same number of attributes.
Error
    at new DeveloperError (http://localhost:9313/myCesium/Source/Core/DeveloperError.js:43:19)
    at Function.Geometry.computeNumberOfVertices (http://localhost:9313/myCesium/Source/Core/Geometry.js:189:27)
    at addPerInstanceAttributesToGeometry (http://localhost:9313/myCesium/Source/Scene/PrimitivePipeline.js:146:41)
    at addPerInstanceAttributes (http://localhost:9313/myCesium/Source/Scene/PrimitivePipeline.js:177:17)
    at geometryPipeline (http://localhost:9313/myCesium/Source/Scene/PrimitivePipeline.js:226:9)
    at Object.PrimitivePipeline.combineGeometry (http://localhost:9313/myCesium/Source/Scene/PrimitivePipeline.js:438:26)
    at combineGeometry (http://localhost:9313/myCesium/Source/Workers/combineGeometry.js:12:41)
    at DedicatedWorkerGlobalScope.<anonymous> (http://localhost:9313/myCesium/Source/Workers/createTaskProcessorWorker.js:55:42)

 var mypositions = Cesium.Cartesian3.fromDegreesArrayHeights([ 104.317776,31.59491,10,
                    105.317776,32.59491,20,
                    106.317776,33.59491,30]);
                var pos=new Float64Array(mypositions);

```
            var geometry = new Cesium.Geometry({
                attributes : {
                    position : new Cesium.GeometryAttribute({
                        componentDatatype : Cesium.ComponentDatatype.FLOAT,
                        componentsPerAttribute : 3,
                        values : pos
                    }),
                    normal:new Cesium.GeometryAttribute({
                        componentDatatype : Cesium.ComponentDatatype.FLOAT,
                        componentsPerAttribute : 3,
                        values : new Float32Array([0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0])
                    })
                },
                indices : new Uint16Array([0,1,2]),
                primitiveType : Cesium.PrimitiveType.TRIANGLES,
                boundingSphere : Cesium.BoundingSphere.fromVertices(pos)
            });


            var myInstance = new Cesium.GeometryInstance({
                geometry : geometry,
                attributes: {
                    color: Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.RED)
                }
            });

            viewer.scene.primitives.add(new Cesium.Primitive({
                geometryInstances : [myInstance],
                appearance : new Cesium.PerInstanceColorAppearance({
                    closed : true,
                    translucent : false
                })
            }));
```

**Comment by zhangxianggis** [comment]
Thank you!
However in China, it is not available to visit the Cesium forum. I have to ask some questions by email.
From some example ,I know in order to draw triangles,we should set the position and indices.
Here is my code.
but it says that
"DeveloperError: Appearance/Geometry mismatch. The appearance requires vertex shader attribute input 'position3DHigh', which was not computed as part of the Geometry. Use the appearance's vertexFormat property when constructing the geometry."

I don't know how to solve this problem?



var mypositions = Cesium.Cartesian3.fromDegreesArrayHeights([ 104.317776,31.59491,10,
105.317776,32.59491,20,
106.317776,33.59491,30]);
var pos=new Float64Array(3*3);

pos[0]=mypositions[0].x;
pos[1]=mypositions[0].y;
pos[2]=mypositions[0].z;

pos[3]=mypositions[1].x;
pos[4]=mypositions[1].y;
pos[5]=mypositions[1].z;

pos[6]=mypositions[2].x;
pos[7]=mypositions[2].y;
pos[8]=mypositions[2].z;

var geometry = new Cesium.Geometry({
attributes : {
position : new Cesium.GeometryAttribute({
componentDatatype : Cesium.ComponentDatatype.FLOAT,
componentsPerAttribute : 3,
values : pos
}),
normal:new Cesium.GeometryAttribute({
componentDatatype : Cesium.ComponentDatatype.FLOAT,
componentsPerAttribute : 3,
values : new Float32Array([0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0])
})
},
indices : new Uint16Array([0,1,2]),
primitiveType : Cesium.PrimitiveType.TRIANGLES,
boundingSphere : Cesium.BoundingSphere.fromVertices(pos)
});
var myTriangle = new Cesium.GeometryInstance({
geometry : geometry,
attributes: {
color: Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.RED)
}
});

viewer.scene.primitives.add(new Cesium.Primitive({
geometryInstances : myTriangle,
appearance : new Cesium.PerInstanceColorAppearance({
closed : true,
translucent : false
})
}));

At 2014-12-26 03:08:38, "Patrick Cozzi" <notifications@github.com> wrote:


Please ask questions like this on the Cesium forum.

If you are making a custom geometry, a simple example to look at is the box geometry:

BoxGeometry.js
createBoxGeometry.js

**Comment by flyingsnowers** [comment]
请问您是否解决了这个问题呢  如果解决了，我是否可以了解下是怎么解决的呢？
