### ISSUE TITLE
Sandcastle 'Are you sure' prompt doesn't work inside window history popstate

### ISSUE THREAD

**Issue by emackey** [CesiumGS/cesium#2622]
So if you visit a few Sandcastle demos by clicking icons in the gallery, Sandcastle uses `history.pushState` to create a "fake" history without leaving the page.  You can use the browser's back button (or forward button, or hold down back/forward and pick a page from the list) to move around within this history.  So long as you navigate within this special "faked" range of history, the browser won't actually fire `onbeforeunload`, and also, you won't get the "Are you sure" prompt for unsaved changes.

Sandcastle listens for this navigation with `window.addEventListener('popstate', ...)`, but I don't know off the top of my head if it can prevent this nav from taking place.

Not sure if the fix is easy or even possible without messing up the nav history.

**Comment by ggetz** [comment]
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
