### ISSUE TITLE
Promise type annotations

### ISSUE THREAD

**Issue by icholy** [CesiumGS/cesium#2730]
I want to update the annotations with Promises to take a type parameter (like you're doing with Array).
### Example:

https://github.com/AnalyticalGraphicsInc/cesium/blob/d880e17464355679f7ca39dde0fc0c8b80f5338f/Source/Core/TerrainData.js#L73

```
@returns {Promise|TerrainMesh}
```

Would be:

```
@returns {Promise.<TerrainMesh>}
```

Would this be accepted?

**EDIT**: [I need this for the TS definition files I'm writing](https://gist.github.com/icholy/540e0e4c3ecb05acc847)

**EDIT 2**: is this a better question for the mailing list?

**Comment by hpinkos** [comment]
As long as the documentation still builds, I don't see a problem with this change

**Comment by mramato** [comment]
TS definition file looks cool, are you generating that from the jsDoc or writing it by hand?  I unfortunately haven't had a lot of time to explore typescript, but I'm sure something like that would definitely be useful for many people.

**Comment by icholy** [comment]
@mramato I wrote a (very ugly) node.js script that generates it from the JSON output of `jsdoc -X`. Once I'm able to generate it without the compiler yelling at me (almost there) I want to run it against your tests. After that I'll add it to https://github.com/borisyankov/DefinitelyTyped

**Comment by emackey** [comment]
@icholy this seems cool.  Do you think this could / should eventually be added to Cesium's build/combine script, so that TypeScript definitions always keep up with new features?  I haven't played with TypeScript yet, I keep meaning to find time to look into it.

**Comment by icholy** [comment]
@emackey I wouldn't be against it (once it's fully automated). It could even be used as a way to enforce correct type annotations in the comments (to some extent at least).

**Comment by jumpinjackie** [comment]
@icholy Ah, I see someone else is also trying to make a (sorely needed) TypeScript definition for Cesium

I'm currently developing a JSDoc plugin to generate TypeScript definition files from parsed JSDoc doclets.

https://github.com/jumpinjackie/jsdoc-typescript-plugin

Initial focus is currently to automatically generate working TSD files for OpenLayers, but Cesium is also in my crosshairs.

Perhaps we could pool our efforts and knowledge together?

**Comment by mramato** [comment]
@icholy and @jumpinjackie I'm sure we'd be happy to ship an official TS definition file with Cesium if there's an easy way to automatically generate and validate it as part of our build process, so I'm all for this effort.

**Comment by icholy** [comment]
@mramato @jumpinjackie #2879 is my blocker

**Comment by mchoy** [comment]
@mramato Do you have any new updates on Typescript definition file for Cesium?

**Comment by thinkpadder1** [comment]
[André Staltz - All JS libraries should be authored in TypeScript](http://staltz.com/all-js-libraries-should-be-authored-in-typescript.html)

Check this [Cesium Typescript generator](https://github.com/s-innovations/S-Innovations.Cesium) made in C# 6.0... maybe you guys can use this as a base?

**Comment by thinkpadder1** [comment]
[André Staltz - All JS libraries should be authored in TypeScript](http://staltz.com/all-js-libraries-should-be-authored-in-typescript.html)

@emackey @mramato Check this [Cesium Typescript generator](https://github.com/s-innovations/S-Innovations.Cesium) made in C# 6.0... maybe you guys can use this as a base?

**Comment by pizza2code** [comment]
Also looking to use Cesium with our Typescript project.  Having defined types for Cesium would be very useful.

**Comment by speigg** [comment]
Generating type definitions from jsDoc would also make documentation bugs more obvious (there are a handful).
