### ISSUE TITLE
WebGL warning in 2D on some setups

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#3025]
See the [forum post](https://groups.google.com/forum/#!topic/cesium-dev/Pc5fHGblIsQ).

This is most likely due to 3D positions being stored in attribute 0 and 2D in attribute 1.  In practice, I don't know if this actually impacts performance on any drivers.

**Comment by nmschulte** [comment]
I can reproduce this warning on my machine as well, and it is only in 2D mode:

```
[.WebGLRenderingContext-0x7fbd53a41690]PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty
WebGL: too many errors, no more errors will be reported to the console for this context.
```

Please let me know if there is anything I can do to support this, even if that means confirming that there is no real performance issue and fixing whatever in the stack is broken.

I am using very recent versions of software (and hardware).  Mainly, the Intel Mesa drivers are very recent (probably more so than most users).  I am using Intel Haswell hardware (ignore the AMD VGA device in the printout below; it's not being used):

```
$ uname -a
Linux desmas-l 4.0.0-2-amd64 #1 SMP Debian 4.0.5-1a~test (2015-06-17) x86_64 GNU/Linux

$ glxinfo | super_awesome_grep_command_that_doesnt_exist
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

```
$ lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller [8086:0c04] (rev 06)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller [8086:0c01] (rev 06)
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06)
00:03.0 Audio device [0403]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller [8086:0c0c] (rev 06)
00:14.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI [8086:8c31] (rev 05)
00:16.0 Communication controller [0780]: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 [8086:8c3a] (rev 04)
00:1a.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 [8086:8c2d] (rev 05)
00:1b.0 Audio device [0403]: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller [8086:8c20] (rev 05)
00:1c.0 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 [8086:8c10] (rev d5)
00:1c.1 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #2 [8086:8c12] (rev d5)
00:1c.2 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 [8086:8c14] (rev d5)
00:1c.3 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 [8086:8c16] (rev d5)
00:1d.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 [8086:8c26] (rev 05)
00:1f.0 ISA bridge [0601]: Intel Corporation HM87 Express LPC Controller [8086:8c4b] (rev 05)
00:1f.2 SATA controller [0106]: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] [8086:8c03] (rev 05)
00:1f.3 SMBus [0c05]: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller [8086:8c22] (rev 05)
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Neptune XT [Radeon HD 8970M] [1002:6801] (rev ff)
03:00.0 PCI bridge [0604]: Texas Instruments XIO2213A/B/XIO2221 PCI Express to PCI Bridge [Cheetah Express] [104c:823e] (rev 01)
04:00.0 FireWire (IEEE 1394) [0c00]: Texas Instruments XIO2213A/B/XIO2221 IEEE-1394b OHCI Controller [Cheetah Express] [104c:823f] (rev 01)
05:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8411 PCI Express Card Reader [10ec:5289] (rev 01)
05:00.2 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 0a)
06:00.0 Network controller [0280]: Intel Corporation Wireless 7260 [8086:08b1] (rev 73)
```

**Comment by pjcozzi** [comment]
@nmschulte how many fps do you get (see the top right) if you browse to http://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html?stats=true

**Comment by nmschulte** [comment]
60 FPS (3D and 2D).  I can turn off VSYNC if you like.

**Comment by pjcozzi** [comment]
Thanks, no need to turn off VSYNC.  I would not worry about the warning on your setup unless you run into performance problems that you don't experience elsewhere.

**Comment by nmschulte** [comment]
It's going to be pretty easy to hit 60 FPS on that demo w/ this hardware doing software rendering.  I doubt the bit of indirection that this is indicating is going to impact the framerate at such low load.  Do you think that test is definitive?  I was thinking that by disabling VSync we could apply some load, but the event-loop nature of JS (that is: "WebGL") might mean it's not applicable.

**Comment by pjcozzi** [comment]
You could turn on terrain and then zoom into the Grand Canyon.

**Comment by nmschulte** [comment]
It didn't seem to have any effect (on FPS, but also visually (screenshots identical minus attribute text)) but in 3D, and only then while the data loads.  Does Cesium actually realize the terrain data in 2D?  I suppose it would be neat for applying time-of-day effects (read: realizing the light from the sun/moon: shadow casting, etc.).

**Comment by nmschulte** [comment]
I suspect you're right that Chromium is being overly concerned w/ this message, and in my case (or possibly most w/ recent desktop hardware/software cases) it's superfluous.  But, for the sake of the bug report, how hard is it to change the shaders to always use v-a 0, and is there a reason they're currently not?  Doing so would increase performance on those older implementations, and it probably matters most there too.

**Comment by ggetz** [comment]
Given the age of this report, I'm going to go ahead and close. If this is still an issue, please feel free to leave a comment or re-open. Thanks!
