### ISSUE TITLE
Add PolylineVolume to CZML

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#3062]
We're missing support for both polyline volumes via CZML

**Comment by sanuj** [comment]
@mramato I would like to work on this if this issue is still open. I read the CZML Guide. How may I get started on this?

**Comment by sanuj** [comment]
@mramato @pjcozzi Do I need to edit `Source/DataSources/CzmlDataSource.js` and `Specs/DataSources/CzmlDataSourceSpec.js` by adding functions like `processPolylineVolume` and `processCorridor` and so on, then create CZML examples for PolylineVolume and Corridor in `Apps/Sandcastle/gallery/` ?

**Comment by hpinkos** [comment]
We're also missing support for:

- [ ] Box
- [ ] Cylinder

**Comment by mlptownsend** [comment]
Is anyone working on adding polylineVolume to CZML? At first glance it doesn't appear to be more any more difficult to add in than the referenced commit that added corridors. Maybe needing a Cartesian2 analog of processPositions for the shapes property.

**Comment by hpinkos** [comment]
@mlptownsend this hasn't been a priority for us so I don't think we'll be adding it any time soon.  However, if you would like to open a pull request adding support, we're happy to review it!  Thanks

**Comment by hpinkos** [comment]
Also requested by @jrafidi in #8840
