### ISSUE TITLE
Scrollbar resets while viewing documentation

### ISSUE THREAD

**Issue by kepta** [CesiumGS/cesium#3467]
It seems that the scrollbar pulls back to its default position whenever the documentation page changes.
Now this can be irritating sometimes while reading the docs.
We can have the scrollbar retain its position depending on which doc the user is currently on.

**Comment by emackey** [comment]
Hi, which documentation are you talking about: Locally built, or the [iframe embedded docs](http://cesiumjs.org/refdoc.html), or the [stand-alone hosted docs](http://cesiumjs.org/Cesium/Build/Documentation/index.html)?  Personally I'm most frustrated by the iframe docs, this is on a roadmap somewhere for us to improve.

Also, there are two scrollbars in each set of documentation: One for the index and a separate one for the page.  Can you describe in more detail which scrollbar on which set of docs you are filing an issue for here?  Thanks!

**Comment by kepta** [comment]
I am sorry for being ambiguous. I was talking about 
https://cesiumjs.org/Cesium/Build/Documentation/SkyAtmosphere.html

Now when you you scroll down in the left pane and click on an API doc, the scrollbar doesn't retain its previous position and resets to default 0.

**Comment by emackey** [comment]
Yep that's a real bug.  The doc source is auto-generated from [the jsDoc template folder here](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Tools/jsdoc/cesium_template).  You can build it on your own system with `npm run generateDocumentation`, and it will be created in your `Build` folder.

The main problem here is that the table of contents (left-side pane) is part of the page, and the links all navigate to a new page with their own TOC left side.  So either the old page has to somehow communicate to the new page what that scrollbar position should be, or the top level could stay put and the documentation page could be an iframe that navigates.  The latter solution would double up our existing iframe troubles, where the top URL doesn't reflect what's being shown in the actual documentation pane.

Ideally we would have a single solution, that could be run locally or integrate with the website and Sandcastle, that would allow one to navigate around without losing their place in the TOC, all while showing their currently location in the top-level URL address bar.

**Comment by kepta** [comment]
We can calculate the approximate position of the scrollbar depending on the doc user currently is in.
Though that wont save the last scrollbar position but it is better than having set it back to zero.
Or we can communicate the previous scrollbar position using a # in the url ?

**Comment by ggetz** [comment]
Hi, This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
