### ISSUE TITLE
Autolinker being added to global scope

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#3497]
Below is a modified version of `HelloWorld.html` that compares items in the global scope before and after the combined `Cesium.js` is loaded.  This spits out 4 values

```
"Autolinker"
"Cesium"
"viewer"
"loadJsonp445142"
```

Cesium, viewer, and `loadJsonp445142` are all expected, but `Autolinker` is being required in `KmlDataSource.js` and should not be setting a global.  This is either a bug in Autolinker or something we are doing in correct.  In either case, we should investigate and fix the issue.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <title>Hello World!</title>
    <script>
        function arr_diff(a1, a2) {
            var i, a = [], diff = [];
            for (i = 0; i < a1.length; i++) {
                a[a1[i]] = true;
            }
            for (i = 0; i < a2.length; i++) {
                if (a[a2[i]]) {
                    delete a[a2[i]];
                } else {
                    a[a2[i]] = true;
                }
            }
            for (var k in a) {
                diff.push(k);
            }
            return diff;
        }
        var original = Object.keys(window);
    </script>
    <script src="../Build/Cesium/Cesium.js"></script>
    <style>
        @import url(../Build/Cesium/Widgets/widgets.css);

        html, body, #cesiumContainer {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
    </style>
</head>
<body>
<div id="cesiumContainer"></div>
<script>
    var viewer = new Cesium.Viewer('cesiumContainer');
    console.log(arr_diff(original, Object.keys(window)));
</script>
</body>
</html>
```

**Comment by yash14123** [comment]
I am taking this up.

**Comment by hpinkos** [comment]
Thanks @yash14123!  Hopefully this will be an easy fix.
Just for reference, if you were looking for other issues to tackle, we have the [beginner label](https://github.com/AnalyticalGraphicsInc/cesium/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner) for issues we think are good ones for new contributors.

**Comment by bampakoa** [comment]
@mramato I think that this can be closed according to your comment https://github.com/CesiumGS/cesium/pull/8034#issuecomment-533763940

**Comment by mramato** [comment]
@bampakoa thanks, I confirmed that it is indeed fixed.
