### ISSUE TITLE
Timeslider error

### ISSUE THREAD

**Issue by cfickler** [CesiumGS/cesium#3555]
Guys, I am seeing this timeslider error crop up now when using the timeslider. 

![timeslider_error](https://cloud.githubusercontent.com/assets/16298736/12994280/71349494-d173-11e5-8066-c3657b2aa3c1.jpg)

This error seems hard to produce but this next one is easy.

Uncaught DeveloperError: Invalid ISO 8601 date.
Error
    at new t (http://cesiumjs.org/NewYork/index.js:572:1200)
    at Function.I.fromIso8601 (http://cesiumjs.org/NewYork/index.js:574:19866)
    at E._makeTics (http://cesiumjs.org/NewYork/index.js:621:6358)
    at E.zoomTo (http://cesiumjs.org/NewYork/index.js:621:4695)
    at E.zoomFrom (http://cesiumjs.org/NewYork/index.js:621:5198)
    at HTMLDivElement.<anonymous> (http://cesiumjs.org/NewYork/index.js:620:30284)

Simply zoom the time scale out as far as possible and you will hit it. 

Also, as a request, can we re-enable the sliding of the timeslider with the left mouse button down? Having to use the middle mouse button is really non intuitive...(that's my 10 cents worth)

**Comment by mramato** [comment]
Thanks for the bug report.  We should probably have better defaults on the timeline to stay within valid ranges.

As for the control, we will most likely not make any changes in that regard until we completely refactor the timeline, which is some of the oldest UI code in Cesium.

**Comment by ggetz** [comment]
Thanks for bringing up this issue! It's a valid concern, and we're already tracking it in a previous issue, https://github.com/CesiumGS/cesium/issues/4425. I'm going to close your issue now to keep the discussion in one place. If you have any further input on this, please post it there instead.
