### ISSUE TITLE
Create DataSource asynchronously

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#3572]
From the forum:
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/JhAJJsg_dBA
https://groups.google.com/forum/#!topic/cesium-dev/pwL3LTU80a8

When loading larger files, Cesium is unresponsive while the GeoJson or KML DataSource is creating all of the `Property`.  Maybe this could be done with web workers instead.

**Comment by sirgalleto** [comment]
@hpinkos Is there any update regarding this? 

Any way I can help? I have zero experience with the Cesium source code, but I can try.

**Comment by OmarShehata** [comment]
@sirgalleto the entity geometry is already created asynchronously, the slow down likely comes from parsing the file itself. Parsing the file over multiple frames was done for KML as of 1.62, see https://github.com/CesiumGS/cesium/blob/master/CHANGES.md#fixes-wrench-14. 

If you're having issues with your project or looking for ways to contribute, I'd encourage you to post on the community forum: https://community.cesium.com/

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/JhAJJsg_dBA
https://groups.google.com/forum/#!topic/cesium-dev/pwL3LTU80a8

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/3572 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
