### ISSUE TITLE
Dealing with Gridded data?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [CesiumGS/cesium#3684]
Enhancement request:

At least in the oceanographic and meteorology communities (and other earth sciences) it's a common need to want to view results from gridded data.

There are multiple grid types (regular grids being the easiest but not very common type), but all share in common that there is a defined geometry of the grid, and then there is data associated with the that geometry, and that data varies with time.

So for efficient visualization you want a way to update the data while re-using the existing geometry -- GL is well suited to this, if the protocols support it. Ideally, one could push the grid to Cesium, and then push the updated data separately, rather than having to make one big ol' czml file with all the data for all time in it at once.

A common way to store this data is netcdf files -- you don't want to try to parse netcdf in the browser, but to get an idea what one might want to support, it makes sense to look at the data models encoded in the various common standards:
- CF metadata: http://cfconventions.org/ for rectangular and curvilinear grid
- UGRID: http://ugrid-conventions.github.io/ugrid-conventions/ for "unstructured grids" (triangular being the most common)

Another place to look for inspiration are WMS services that support these:
- THREDDS data server WMS (supports rectangular and curvilinear grids)
  http://www.unidata.ucar.edu/software/thredds/v4.6/tds/reference/WMS.html
- SciWMS (support UGRID (triangular anyway)
  http://asascience-open.github.io/sci-wms/

While these WMS services are nice, it would be really great to be able to do this rendering in the browser, for faster zooming and panning and querying of the data.

**Comment by pjcozzi** [comment]
Thanks for the info, @ChrisBarker-NOAA.  Perhaps this would fit well with [3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles).

**Comment by ChrisBarker-NOAA** [comment]
From an admittedly quick look at 3D Tiles, yes, it looks like it could be a good fit, particularly for really big data sets.

But for smaller datasets, I don't think it would be necessary -- and entire (2D, anyway) grid could be brought in to memory all at once, the the data on that grid updated on the fly (and maybe cached).

That could all work if there were a grid feature type (or a few...), and then 3D-tileified later on  down the road.

Maybe there is already a suitable way to do this in Cesium, but I haven't found it yet.

**Comment by pjcozzi** [comment]
This may be of interest: http://cesiumjs.org/demos/GridViz.html

**Comment by ChrisBarker-NOAA** [comment]
Yes, I've seen that -- I find the visualization odd, but it may be close to what we need. I'll poke in to see how it's done. 

Thanks

**Comment by mmcgarity** [comment]
I was able to get a very simple grid going with CZML polygons with time varying colors. You could conceivably create a larger grid with a desired resolution, and just tweak the color value for each grid over time. For some reason, the top-left polygon's translucency gets less and less as the playback loops. (this may be a bug..)

Not sure how to do this with the CZML writer. Any tips would be helpful. I'm still learning how the CZML writer works. 

Here's my code for the CZML object:
`var czml = [{
    "id" : "document",
    "name" : "CZML Geometries: Polygon",
    "version" : "1.0"
}, {
    "id" : "polygon1",
    "name" : "dynamic polygon on surface",
    "availability":"2012-08-04T16:00:00Z/2012-08-04T17:00:00Z",
    "polygon" : {
        "positions" : {
            "cartographicDegrees" : [
                -180, 60, 0,
                -130, 60, 0,
                -130, 30, 0,
                -180, 30, 0
            ]
        },
        "material": {
            "solidColor": {
                "color": [{
                    "interval" : "2012-08-04T16:00:00Z/2012-08-04T16:25:00Z",
                    "rgba" : [255, 0, 255, 255/2]
                    }, {
                    "interval" : "2012-08-04T16:25:00Z/2012-08-04T17:00:00Z",
                    "rgba" : [0, 255, 255, 255/2]
                    }]
                }
            }
        }
    },
    {
    "id" : "polygon2",
    "name" : "dynamic polygon on surface",
    "availability":"2012-08-04T16:00:00Z/2012-08-04T17:00:00Z",
    "polygon" : {
        "positions" : {
            "cartographicDegrees" : [
                -130, 60, 0,
                -90, 60, 0,
                -90, 30, 0,
                -130, 30, 0
            ]
        },
        "material": {
            "solidColor": {
                "color": [{
                    "interval" : "2012-08-04T16:00:00Z/2012-08-04T16:25:00Z",
                    "rgba" : [0, 255, 255, 255/2]
                    }, {
                    "interval" : "2012-08-04T16:25:00Z/2012-08-04T17:00:00Z",
                    "rgba" : [0, 255, 255, 255/2]
                    }]
                }
            }
        }
    },
    {
    "id" : "polygon3",
    "name" : "dynamic polygon on surface",
    "availability":"2012-08-04T16:00:00Z/2012-08-04T17:00:00Z",
    "polygon" : {
        "positions" : {
            "cartographicDegrees" : [
                -180, 30, 0,
                -130, 30, 0,
                -130, 0, 0,
                -180, 0, 0
            ]
        },
        "material": {
            "solidColor": {
                "color": [{
                    "interval" : "2012-08-04T16:00:00Z/2012-08-04T16:25:00Z",
                    "rgba" : [255, 255, 255, 255/2]
                    }, {
                    "interval" : "2012-08-04T16:25:00Z/2012-08-04T17:00:00Z",
                    "rgba" : [0, 0, 0, 255/2]
                    }]
                }
            }
        }
    },
    {
    "id" : "polygon4",
    "name" : "dynamic polygon on surface",
    "availability":"2012-08-04T16:00:00Z/2012-08-04T17:00:00Z",
    "polygon" : {
        "positions" : {
            "cartographicDegrees" : [
                -130, 30, 0,
                -90, 30, 0,
                -90, 0, 0,
                -130, 0, 0
            ]
        },
        "material": {
            "solidColor": {
                "color": [{
                    "interval" : "2012-08-04T16:00:00Z/2012-08-04T16:25:00Z",
                    "rgba" : [0, 0, 0, 255/2]
                    }, {
                    "interval" : "2012-08-04T16:25:00Z/2012-08-04T17:00:00Z",
                    "rgba" : [255, 255, 255, 255/2]
                    }]
                }
            }
        }
    }          
];
`

**Comment by ggetz** [comment]
Since a use case like this would more likely be accomplished through 3D Tiles, or possibly voxels, I'm going to go ahead and close this.

A CZML approach is unlikely to become a priority anytime soon.

Thanks!
