### ISSUE TITLE
Imagery artifacts in Imagery Adjustment Sandcastle

### ISSUE THREAD

**Issue by shunter** [CesiumGS/cesium#3940]
Happened to notice this randomly.  Play around with the sliders in the Imagery Adjustment Sandcastle example and I see this:

![image](https://cloud.githubusercontent.com/assets/32828/15410069/d5e40cc6-1de5-11e6-9c19-50e701ec9c04.png)

The artifacts are dependent on the values from the sliders.  Seen on two different Windows desktop systems (both NVidia).

**Comment by pjcozzi** [comment]
Most likely a driver bug.  Hopefully it is just something subtle in the post-processing part of the shaders.

**Comment by ggetz** [comment]
Given the age of this issue, and lack of additional reports, I'm going to go ahead and close. @shunter or others, if you can still reproduce please feel free to re-open.
