### ISSUE TITLE
Polyline outline width and coloring are not working

### ISSUE THREAD

**Issue by djone010** [CesiumGS/cesium#40]
When I set the polyline.width and polyline.outlineWidth, no matter what size I set, there is no noticeable difference.  The sandbox examples don't even seem to be working.  On the example for set interior and outline color, there should be a red outline, but all I see is the yellow line.

This seems to be the case both in chrome and firefox.

**Comment by MarchChadwick** [comment]
Would love to change the outlineWidth property.  No luck as yet.

**Comment by GatorScott** [comment]
The ANGLE project declared in 2014 that they would not be implementing wide lines.  Having said that, wide outlines are working for me on Windows 10 in

- Chrome 62.0.3202.62, ANGLE (NVIDIA Quadro M1000M Direct3D11 vs_5_0 ps_5_0)
- Firefox 56.0, ANGLE (NVIDIA Quadro M1000M Direct3D11 vs_5_0 ps_5_0)
- Edge 40.15063.674.0, Intel(R) HD Graphics 530
- Internet Explorer 11.674.15063.0, NVIDIA Quadro M100M

What configuration is failing for you?  I used webglreport.com to obtain the Unmasked Renderer shown above.

**Comment by MarchChadwick** [comment]
Hello GatorScott and thank you for response.  I am using Chrome with a Macbook pro.  Following PolylineOutlineMaterialProperty https://cesiumjs.org/Cesium/Build/Documentation/PolylineOutlineMaterialProperty.html in the Cesium sandbox https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Polygon.html&label=undefined  produces no change in outline thickness for me.

**Comment by hpinkos** [comment]
@MarchChadwick support for `outlineWidth` is dependent on your OS and your graphics card.  If the value of `scene.maximumAliasedLineWidth` is `1`, then your machine only supports 1px width geometry outlines.  See more information here: https://stackoverflow.com/questions/25394677/how-do-you-change-the-width-on-an-ellipseoutlinegeometry-in-cesium-map/25405483#25405483

In the future, please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for bug tracking and planning new features, and we might miss your question if you comment on a closed issue like this.  Thanks!

**Comment by thw0rted** [comment]
Since the docs are now going to link to this issue, I'll make a suggestion here for future readers.  If you're trying to make a filled shape with a thick outline, and can easily express that outline as an array of points (say, a PolygonGraphics or EllipseGraphics), it's pretty simple to add a PolylineGraphics to your entity instead of using the built-in `outline` property on your 2D shape.  Hopefully at some point in the future this won't be necessary, but for now this ensures a consistent appearance on any platform.

**Comment by sraimund** [comment]
I landed on this issue coming from outlineWidth property of the PolygonGraphics docs. Based on the suggested workaround of @thw0rted, here the code for converting polygons into polylines with outline:
```
const dataSource = await Cesium.GeoJsonDataSource.load("polygons.geojson");

for (const entity of dataSource.entities.values) {
    entity.polyline = new Cesium.PolylineGraphics();
    entity.polyline.positions = entity.polygon.hierarchy.getValue().positions;
    entity.polygon = undefined;
    
    entity.polyline.width = 3;
    entity.polyline.material = new Cesium.PolylineOutlineMaterialProperty({
        color: Cesium.Color.WHITE,
        outlineWidth: 2,
        outlineColor: Cesium.Color.BLACK
    });
}

viewer.dataSources.add(dataSource); 
```
An exemplary use case would be to style borders of administrative units (given as polygons).

**Comment by mzlan** [comment]
Hi，I set the browser angel default as opengl  and box outlineWidth working。

var outlineOnly = viewer.entities.add({
  name: "Yellow box outline",
  position: Cesium.Cartesian3.fromDegrees(-100.0, 40.0, 300000.0),
  box: {
    dimensions: new Cesium.Cartesian3(400000.0, 300000.0, 500000.0),
    fill: false,
    outline: true,
    outlineColor: Cesium.Color.YELLOW,
    outlineWidth:2,
  },
});
