### ISSUE TITLE
Wall geometries with all negative heights do not render

### ISSUE THREAD

**Issue by bmckilligan** [CesiumGS/cesium#4274]
I need to represent wall geometries close to the ground surface with terrain turned on.

due to the geoid offset at particular locations the elevation for the top of the wall will be a negative value for the wall geometries since cesium is using ellipsoid elevations rather than orthometric.

a working example with two walls, the top of the red wall just above 0

https://sandcastle.cesium.com/#c=3ZNvT9swEMa/yilvSKXgJIOxrQvVSkGaNKQhxsYLwgs3Plpr/lOdnXRl4rvjJIUVOmlM2qs5kpU7/567ix+l4QSNxCUSHILBJUzQyVqzb10uLqOqiyfWeC4NUhkl8LM0AB6JQuaMbCMF0vBBWBFyj5eWlLjokXiQlOZu8L40/dOEllNV4yVXKjTtuzM0XnqJjnEh4q4DgOEaYQg7R4GGZYvvJP1JFwxhzbVrYV3QW+PgcZQJJx/euNljN2T1Mc4I0Y3DUKv4ajd/tceygzcJ7L9jeb6f/Cr1l2td6e260sH1YKOW5j+krvVHlLO5b2e7yrME8gyuNyFpnkGQsTxptydYuFiSXG18oVWW2NHp1xO2lH4+Vos5jzP2egAbMlt7Fazr2G3pePKpR++2TCIUL/foHEXnyn/gUMay9u7/5NFu62TYXmLR+cnxv3Ro7cettfrCxs/caZEoiQrnVwpHpfkg9cKSh5pUzFjqUS9UGNOl07r6jp5VrpMU6YOgELIBKQ5/8/NDpbhz4eSmVuqLvMUyGhVp4J/IlOVCmtnnBknxVYvM89Fpn2SMFWkIt1XeWjXl9FjxHg

for the red wall in the provided example change  the maximumHeights  line 
from: 
maximumHeights : [0.01, 0.01 ],

to
maximumHeights : [-0.01, -0.01 ],

the red wall no longer renders

**Comment by hpinkos** [comment]
Thanks for including the code example @bmckilligan!

**Comment by bmckilligan** [comment]
the detail is, terrain needs to be turned on and the geographic location has a geoid offset height that is negative creating geometries that will be above ground, yet have negative  maximumHeights  

the particular location has a geoid height of around -20m

**Comment by jdurrie** [comment]
I followed a link here from the Cesium in 2017 google doc. I want to find the issue that's tracking local bathymetry. Is there a better issue I'm not seeing?

**Comment by ggetz** [comment]
@jdurrie You may want to take a look at the forum to find what you are looking for: https://groups.google.com/forum/#!searchin/cesium-dev/bathymetry%7Csort:relevance

**Comment by ggetz** [comment]
@jdurrie I opened #5665 to track local bathymetry specifically, please add any details in that issue. Thanks!

**Comment by hpinkos** [comment]
Also reported by @vla9isla8 in #8724

**Comment by bmckilligan** [comment]
Is there any chance this will get fixed?  I would like to implement wall geometries with the new underground transparency  in 1.70

**Comment by OmarShehata** [comment]
This may be a good time to revisit now that CesiumJS has better support for underground. @hpinkos do you know what is causing this issue, or do you have any advice on where to start looking if someone wanted to investigate?

**Comment by hpinkos** [comment]
I don't know exactly, but I suspect it's something silly like we're clamping the positions to the ellipsoid somewhere.  The best way to start looking into it would be to set breakpoints in `WallGeometry`/`WallGeometryLibrary` to see what it's spitting out for the `positions` values and how that differs from what's expected.

**Comment by bmckilligan** [comment]
fingers crossed this fix will be in the next release

**Comment by hpinkos** [comment]
@bmckilligan that's the plan!

**Comment by bmckilligan** [comment]
Fantastic, Thank you

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!searchin/cesium-dev/bathymetry%7Csort

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/4274 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
