### ISSUE TITLE
Real-time terrain exaggeration changes

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#4342]
Requested on the forum: 
https://groups.google.com/forum/#!msg/cesium-dev/WT-0NM4bxC4/ZcErFJSiCQAJ
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/2iqod4f4UIY

It would be nice to change the terrain exaggeration after the scene is constructed

**Comment by pjcozzi** [comment]
Not endorsing this as a current priority, but here's a related commit from #3200: https://github.com/AnalyticalGraphicsInc/cesium/pull/3200/commits/ab24a58246ab9762dae369a3ca8e054ef5d4dd53

**Comment by ggetz** [comment]
Requested on the forum: https://groups.google.com/forum/#!topic/cesium-dev/f8JE21h-Yqo

**Comment by mholthausen** [comment]
Is there any prospect of when this setting will probably be available in CesiumJS?

**Comment by guozhongzhe** [comment]
Is the latest version support to change the terrain exaggeration after the scene is constructed?

**Comment by dzungpng** [comment]
Another request from the community forum: https://community.cesium.com/t/dynamic-change-of-terrainexaggeration/11714

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!msg/cesium-dev/WT-0NM4bxC4/ZcErFJSiCQAJ
https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/2iqod4f4UIY
https://groups.google.com/forum/#!topic/cesium-dev/f8JE21h-Yqo

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/4342 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
