### ISSUE TITLE
Weird interaction between CzmlDataSource.process and tracked entity

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#4647]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/fILh9nJyI1w

The model in this example looks like its flickering.  To me it looks like it might be that the camera isn't tracking it correctly for a split second after the model moves.  This only happens when `czmlDataSource.process` is called.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var czmlDataSource = new Cesium.CzmlDataSource();
viewer.dataSources.add(czmlDataSource);

var czmlString = '[\
{\
  "id":"document",\
  "version":"1.0",\
  "clock":{\
    "multiplier":1,\
    "range":"UNBOUNDED",\
    "step":"SYSTEM_CLOCK",\
    "interval":"0001-01-01T00:00:00Z/9999-12-31T23:59:59.999Z",\
    "currentTime":"2016-11-15T00:15:53.63100000000122Z"\
  }\
},\
{\
  "availability":"0001-01-01T00:00:00Z/9999-12-31T23:59:59.999Z",\
  "id":"LineToTarget",\
  "polyline":{\
    "width":3,\
    "positions":{\
      "cartographicDegrees":[\
        -118.2437,34.0522,20000,-122.4194,37.7749,100\
      ]\
    },\
    "material":{\
      "solidColor":{\
        "color":{\
          "rgba":[\
            255,0,0,255\
          ]\
        }\
      }\
    }\
  }\
}]';

var czml = JSON.parse(czmlString);
czmlDataSource.process(czml);

var position = Cesium.Cartesian3.fromDegrees(-118.2437,34.0522,20000);
var heading = Cesium.Math.toRadians(135);
var pitch = 0;
var roll = 0;
var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);
var url = '../../SampleData/models/CesiumAir/Cesium_Air.glb';
var entity = viewer.entities.add({
        name : url,
        position : new Cesium.CallbackProperty(function() {return position;}, false),
        orientation : orientation,
        model : {
            uri : url,
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });

var i = 0;
viewer.trackedEntity = entity;

setInterval (function () {    
    position = Cesium.Cartesian3.fromDegrees(-118.2437+i,34.0522,20000);
    i += 0.001;       
}, 2000);    

setInterval(function () {
    czmlDataSource.process(czml);
}, 1000);
```

**Comment by AshitakaLax** [comment]
I also was able to get the same issue to repeat.  It appears like it is a camera tracking issue.
I have tried both running multiple czml documents and a single czml document
here is a single czml document.
[error-process.czml.txt](https://github.com/CesiumGS/cesium/files/6587646/error-process.czml.txt)

### Here is the Timeline

* 1st second Everything looks good
* 2nd second camera switches to a new perspective
* 3rd second camera switches back to the original orientation.

Here is the image of what it looks like normally at May 27 2021 23:44:54 UTC.
![image](https://user-images.githubusercontent.com/1018160/120558225-658dec80-c3bc-11eb-8cc4-f38e0d59d9f3.png)
Without touching anything but letting the time pass for 1 second May 27 2021 23:44:55 UTC.
![image](https://user-images.githubusercontent.com/1018160/120558419-a980f180-c3bc-11eb-808b-fa07011a1c1e.png)
One second later at May 27 2021 23:44:56 UTC it goes back to the expected camera position.
![image](https://user-images.githubusercontent.com/1018160/120558540-db925380-c3bc-11eb-8d3b-a14b70d70223.png)

I also reviewed the specific samples associated with the switch and they look good.

**Comment by srcejon** [comment]
Same problem here. Did you find a workaround @AshitakaLax?

**Comment by AshitakaLax** [comment]
No, I haven't found any solution to this issue, but I also haven't worked on the specific project for months either.

**Comment by Levi-Montgomery** [comment]
I am having the exact same problem. What is happening is that the model position is updating, then only on what appears to be the next frame does the camera position update. You will notice no flickering when the entity is not being tracked. However, you can still see how the green square lags behind by about a frame, as I was able to catch using my phone's slow motion camera.

https://www.youtube.com/shorts/UNAR6R40Ce8

**Comment by javagl** [comment]
There might be an underlying issue that is related to `trackedEntity` (independent of CZML). At least, the observation that was made in the forum thread around https://community.cesium.com/t/how-to-fix-flicker-upon-updating-position-of-an-entity/35516/2 **and** in the sandcastle that was shown in the initial post here is the same: The model seems to "jump" to a wrong position when it is the `trackedEntity`. When _not_ setting the `trackedEntity` (but zooming to the entity manually), then it does _not_ seem to flicker or jump.

**Comment by Levi-Montgomery** [comment]
I ran into the same issue. So the subtle bug here is that the creation of a Polyline is blocking the camera position update. The model position update isn't blocked, but the camera is, and that is what causes the model and camera to briefly separate (which we observe as a flicker).

If you draw a Polyline and update the camera position each at the same time, the camera position will not move until the Polyline is finished drawing. 

You can fix the bug from the cesium sandcastle provided in the original ticket by offsetting the two such that the polyline and model positions never update at the same time. When you have the numbers be 2,000 and 1,000, the flicker happens every other time. But if you offset one of them by, say, 500ms they will never happen at the same time.

This is a workaround, and I think the ideal fix would be to make Polyline creation not block camera position updates in Cesium.

Replace the bottom of the provided cesium sandcastle with this code to fix the tracking bug
```javascript

setInterval (function () {    
    position = Cesium.Cartesian3.fromDegrees(-118.2437+i,34.0522,20000);
    i += 0.001;       
}, 2000);    

// offset the intervals such that polyline update never happens at same time as model update
setTimeout(() => {
  setInterval(function () {
      czmlDataSource.process(czml);
  }, 1000);
}, 500);
```

**Comment by Levi-Montgomery** [comment]
So, actually, the offset is not needed. Simply doing the below should suffice, i believe the setTimeout's presence is enough to start up its own 'thread' and solve the blocking issue.

```javascript
setInterval (function () {    
    position = Cesium.Cartesian3.fromDegrees(-118.2437+i,34.0522,20000);
    i += 0.001;       
}, 2000);    

setTimeout(() => {
  setInterval(function () {
      czmlDataSource.process(czml);
  }, 1000);
}, 0);
```

**Comment by AshitakaLax** [comment]
Thanks for the response, I've done a real career shift. So, I'm no longer qualified to determine whether this resolves the issue. However, I would trust anyone else's opinion on the matter, and they should update the ticket accordingly.

Best of luck!

**Comment by ggetz** [comment]
Fixed by https://github.com/CesiumGS/cesium/pull/12230
