### ISSUE TITLE
Shadows have bad artifacts on iOS

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#4752]
@bagnell found this today on an iPad Pro and I confirmed it on my iPhone.  Happens with every model I tried, here's a screenshot. (tested on master) that kind of shows the problem.

![image](https://cloud.githubusercontent.com/assets/1495196/21168266/b52b804c-c180-11e6-96f9-dfe6f983461a.png)

**Comment by pjcozzi** [comment]
CC #4560
