### ISSUE TITLE
The glTF.scene should be optional

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#4793]
According to the specification, the [glTF.scene](https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#gltfscene) field is optional (i.e "not required"). 

But there are at least two places where `gltf.scenes[gltf.scene]` seems to be accessed directly:

- https://github.com/AnalyticalGraphicsInc/cesium/blob/43ca55b3693ee1b20fc731813d427a9e8040b758/Source/Scene/Model.js#L3204 
- https://github.com/AnalyticalGraphicsInc/cesium/blob/43ca55b3693ee1b20fc731813d427a9e8040b758/Source/Scene/Model.js#L1229

(others may exist - I did not systematically search for all possible occurrences).

When trying to load a glTF without a `scene` property, this obviously leads to the error 
> TypeError: t.scenes[t.scene] is undefined

(This basically applies to all the tutorial models. Right now, it can be tested quickly at https://cx20.github.io/gltf-test/examples/cesium/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF-Embedded-buffer )

---
(BTW: The linked lines also raise the question of whether cesium would be capable of handling *multiple* scenes, but this may be another issue...)

**Comment by pjcozzi** [comment]
CC https://github.com/KhronosGroup/glTF/issues/815

**Comment by javagl** [comment]
Seems to be resolved 👴 

![Cesium NoScene](https://user-images.githubusercontent.com/5597569/181361874-b760fbad-62c1-40dd-8d63-0d7bab48f41d.jpg)
