### ISSUE TITLE
Replace explicit checks for DeveloperErrors with calls to the new Check type

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#4794]
#4726 introduced a new private class, [Check](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Check.js), with static utility functions to do common parameter validation and throw a `DeveloperError`.  Using `Check` instead of explicit hand-coded conditionals is more concise.  For example:
```javascript
if (!defined(cartesian)) {
    throw new DeveloperError('cartesian is required');
}
```
becomes
```javascript
Check.typeOf.object('cartesian', cartesian);
```
#4726 also updated `Cartesian3` to use `Check`.

We still want to update the rest of the Cesium codebase to use `Check` when reasonable (very specific checks for `DeveloperError`s can still be hand-coded).  This is a great beginner issue.

* Start with the fundamental numeric types in the `Core` directory: cartesian, matrices, quaternions, etc.
* Open a pull request for one file at a time to start.
* Verify the reference documentation for the `@exception`s is still correct and that there are unit tests for the exceptions in the corresponding `Spec` file (try the [WebStorm plugin](https://github.com/AnalyticalGraphicsInc/cesium-webstorm-plugin) to flip between the source and spec file).

**Comment by pjcozzi** [comment]
@shehzan10

* [ ] `Matrix2`
* [ ] `Matrix4`
* [ ] `Cartesian4`
* [ ] `Spherical`

@austinEng

* [ ] `Matrix3`
* [ ] `Cartesian2`
* [ ] `Quaternion`
* [ ] `Rectangle`

All of these files are in the `Core` directory.

**Comment by lilleyse** [comment]
@WilliamKHo @moneimne @omh1280 Let's work on these to start. Open a separate pull request for each file to start.

@rahwang would you like to do the first round of reviews for these?

All these files are in the `Core` directory. For any checks that involve arrays, just use `Check.defined` as there is not a `Check.typeOf.array`. Some checks may also require using `Check.typeOf.number.lessThan` and related functions.

@WilliamKHo

* [ ] `arrayRemoveDuplicates`
* [ ] `AttributeCompression` (fix any of the "____ is required" checks, skip others)
* [ ] `AxisAlignedBoundingBox`
* [ ] `barycentricCoordinates`

@moneimne

* [ ] `binarySearch`
* [ ] `BingMapsGeocoderService`
* [ ] `BoxGeometry`
* [ ] `BoxOutlineGeometry`

@omh1280
* [ ] `Cartesian2` (fix just the "left and right are required" checks)
* [ ] `Cartesian3` (fix just the "____ is required" checks)
* [ ] `Cartographic`
* [ ] `CartographicGeocoderService`

**Comment by rahwang** [comment]
I'd be happy to @lilleyse !

@WilliamKHo @moneimne @omh1280

When you open a pull request for any of these, please tag. Ping if you need help!

**Comment by omh1280** [comment]
@rms13 
- [] PolygonPipeline
@Rudraksha20 
- [] TileAvailability

**Comment by ggetz** [comment]
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
