### ISSUE TITLE
Revert Firefox OIT Fix

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#4815]
This is a reminder to revert the changes to OIT in https://github.com/AnalyticalGraphicsInc/cesium/pull/4762 once the time is right.

OIT (in its original state before that PR) is working in Firefox nightly but still broken in Firefox 50.

**Comment by emackey** [comment]
This is a reminder to *not* revert a small change to `FXAA.js` that got merged with #4762, but was tagged during the review as being a fix for an unrelated thing.

**Comment by lilleyse** [comment]
And https://github.com/AnalyticalGraphicsInc/cesium/pull/5047

**Comment by mramato** [comment]
It's been 2 years, can we fix/revert the code referenced in this issue?

**Comment by squrki** [comment]
Assigned to this issue

**Comment by ggetz** [comment]
@squrki Perfect, thanks!
