### ISSUE TITLE
Ground primitive artifact on Mac/Intel

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#4820]
Potentially a precision issue.  Maybe a driver bug.

Select "Draw a Polygon" and zoom in to http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Ground%20Clamping.html&label=Showcases

![ok2](https://cloud.githubusercontent.com/assets/782098/21735347/367b5b9a-d437-11e6-93f0-069b83838bb1.gif)

Only happens in the closest frustum.  Note that it is most noticeable with a top-down view, not a horizon view.

This happens before #4751 added dynamically lowering the bottom cap.

This does not happen on Windows/NVIDIA.

**Comment by hpinkos** [comment]
Also reported here: https://groups.google.com/d/msg/cesium-dev/BHmN6Vj_hgE/eJrENGq3BwAJ

**Comment by ggetz** [comment]
I can no longer reproduce this on Mac/Intel.
