### ISSUE TITLE
Rectangle.validate is a no-op

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#4921]
It looks like `Rectangle.validate` has it's entire implementation wrapped inside of a pragma, but the function itself is exposed and documented.  This means if our users call `Rectangle.validate` nothing will ever happen.  We have two chocies

1. `Rectangle.validate` should not  pragma out it's implementation
2. `Rectangle.validate` should be marked private and removed from the API
3. Add `Rectangle.devValidate`  which we use internally and does pragma out, but make  `Rectangle.validate` always perform checks.

For simplicity, I would go with 1, but if @pjcozzi or @bagnell thinks this will lead to major performance issues, we should do 3.

**Comment by pjcozzi** [comment]
Probably 2, but will evaluate when it is a priority.

**Comment by hpinkos** [comment]
Would it make sense to add this type of validation to `Check`?  We should remember to put pragmas around calls to `Check` functions

**Comment by hotpocket** [comment]
I'll take this one.

**Comment by ggetz** [comment]
@hotpocket Got it!

**Comment by hotpocket** [comment]
I have submitted a pull request.  The fix seems too simple, so let me know if I've missed something obvious. Thanks!

**Comment by jjspace** [comment]
#12212 has been merged which deprecates `Rectangle.validate`. This should now be fully removed in 1.124
