### ISSUE TITLE
Intermittent GlobeSurfaceTile test failures on CI

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#4968]
@shehzan10 do you want to look at this at the bug bash?

These tests fail Intermittently.  Perhaps there is a way to simplify them and make them more consistent.

```
  Scene/GlobeSurfaceTile
    processStateMachine
      ✗ upsampled terrainData is copied to the tile once it is available
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      ✗ loaded terrain data replaces upsampled terrain data
	Failed: promise rejected: TypeError: Cannot read property 'state' of undefined
	    at Specs/customizeJasmine.js:79:26
	    at Object.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
```

**Comment by shehzan10** [comment]
Sure.

**Comment by hpinkos** [comment]
@shehzan10 did you get a chance to look into this yet? This test failure keeps making greenkeeper throw up errors

**Comment by shehzan10** [comment]
I did look into it around the February bug bash, but it was incredibly hard to reproduce as it was only happening intermittently. I don't really have any update on why this is happening because of that.

**Comment by mramato** [comment]
Does this test use external data? (If so that could certainly be part of the problem).

We should either fix this ASAP (preferred) or exclude the test in master (via `xit`) because it's making our unit tests too unstable.

**Comment by pjcozzi** [comment]
I agree with @mramato.  Given that we are focused elsewhere, perhaps just `xit` for now.

**Comment by pjcozzi** [comment]
Ignored for now in #5085.

**Comment by mramato** [comment]
We are still receiving frequent travis failures because of the below two related tests.  I would recommend we xit these as well, but there's a large problem here that we really need to look into sooner rather than later.
```
1) loaded terrain replacing upsampled terrain triggers re-upsampling and re-loading of children
     Scene/GlobeSurfaceTile processStateMachine
2) improved upsampled terrain triggers re-upsampling of children
     Scene/GlobeSurfaceTile processStateMachine
```

**Comment by pjcozzi** [comment]
Agreed.  @rahwang do you want to make this small change: https://github.com/AnalyticalGraphicsInc/cesium/issues/4968#issuecomment-287766749

**Comment by rahwang** [comment]
Sure thing!

**Comment by hpinkos** [comment]
Those other two tests are now ignored #5135

**Comment by ggetz** [comment]
The problematic tests have been removed at this point.
