### ISSUE TITLE
More accurate rendering of models in 2D

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#5112]
The larger the model, the less accurate it will be represented in 2D since it does not use the model's latitude in determining a stretching factor. Maybe just a scale will work, or maybe its harder than that since certain areas of the model vary by their latitude. @bagnell you probably have a better grasp of the details here.

I remember this being a known limitation when 2D model support was added. It's something that's worth more investigation considering many of our models will actually be large city sections.

From this forum post: https://groups.google.com/forum/#!topic/cesium-dev/jBmwFWHgVDo

3D:
![3d](https://cloud.githubusercontent.com/assets/915398/24023068/51ff543c-0a80-11e7-8433-20aa085f4a85.PNG)

Columbus View:
![auto generated inline image 1](https://cloud.githubusercontent.com/assets/915398/24023071/573c81c2-0a80-11e7-8445-ff3b6885310b.png)

**Comment by bagnell** [comment]
Yes, this was a known limitation when 2D support was added for models. For large models, we would need to go through the positions and project them to 2D. The farther the positions from the origin in model coordinates, the more inaccurate it will be in 2D.

**Comment by pjcozzi** [comment]
Maybe with emulating double-precision in the vertex shader (and with transform-feedback in WebGL 2.0, #797) the re-projection could be done on the GPU; it is not affine so it can't be burned into the model material.

Otherwise, I think we would have to use extra memory to store 3D and 2D positions.

**Comment by jadelhamilton** [comment]
Thanks I will look in to it and find something

**Comment by lilleyse** [comment]
Possibly affecting this photogrammetry tileset too, from https://groups.google.com/forum/#!topic/cesium-dev/KxpSBtfKetk.
![crackin2d](https://user-images.githubusercontent.com/915398/29797477-40b89522-8c25-11e7-8f93-433a5e3aa899.jpg)
However not noticeable for the AGI photogrammetry tileset.
![agi](https://user-images.githubusercontent.com/915398/29797490-536e2538-8c25-11e7-8fa6-421087dbdaab.PNG)

**Comment by lilleyse** [comment]
This came up on the forum: https://groups.google.com/forum/#!topic/cesium-dev/nq5SymE_PPg

**Comment by j9liu** [comment]
I'll close this, yes
