### ISSUE TITLE
Globe base color alpha does nothing

### ISSUE THREAD

**Issue by rahwang** [CesiumGS/cesium#5163]
The alpha color parameter of the `viewer.scene.globe.baseColor` object has no visual effect.

Reported in the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/UboMKwwn8Xk

**Comment by pjcozzi** [comment]
This would be part of subsurface.  We could also do a doc fix in the short term if it is confusing people.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/UboMKwwn8Xk

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/5163 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
