### ISSUE TITLE
Cesium.DefaultProxy always appends ?url-to-fetch to the request

### ISSUE THREAD

**Issue by cleder** [CesiumGS/cesium#519]
The Cesium.DefaultProxy always appends ?url-to-fetch to
the request which makes it harder for other
proxy implementations which perhaps expect a
/proxy?get_url=url-to-fetch parameter

So my wish is to have something like:

var provider = new WebMapServiceImageryProvider({
    url: 'http://sampleserver1/WMSServer',
    layers : '0',
    proxy: new Cesium.DefaultProxy('/proxy/?url=') /\* dont just append
     ?url to that proxyurl */
});

**Comment by 543802360** [comment]
good job!
