### ISSUE TITLE
Cesium learning materials update

### ISSUE THREAD

**Issue by rahwang** [CesiumGS/cesium#5207]
I’m currently working on a reorganization of all the Cesium tutorials, and our learning materials in general. Since we’re all about fostering a collaborative environment, I wanted to open up the discussion to the community. The more feedback the better! Experts and new users welcome!

Forum discussion here: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/trCbTMWdM5M

So far, I've been focused on tutorials, but feel free to comment on other resources (Sandcastle, blog, etc also.

# Overall roadmap

### Re-envision tutorials
* [ ] Create a Cesium overview tutorial (very short), as "tutorial 0"
* [ ] Restructure and cleanup existing tutorials
* [ ] Add stronger linkage to sandcastle examples, eg. links to all the relevant examples at the end
* [ ] Increase tutorial coverage (request contributions from the appropriate parties)
* [ ] Embed Sandcastle examples (longer term)

### Re-envision Sandcastle
* [ ] Comment / Clean existing examples. Link to tutorials when appropriate.
* [ ] Create an index page 
* [ ] Make examples more granular and short
* [ ] Improve coverage (request examples from appropriate parties) 

# General Tutorial Notes
* We should embed Sandcastle examples in our tutorials
  * So much of our tutorial lengths are images and code examples followed by links to the sandcastle examples they use.
  * See [Book of Shaders](https://thebookofshaders.com/08/)
* There should be some differentiation between tutorials and tech explanations. 
  * Most newcomers will want to get started quickly, and don't need exposure to underlying technical concepts right out the gate. 
  * How much underlying detail is helpful in tutorials? If it doesn’t belong in the tutorials, where should it go?
* We should have an overall quick start guide
  * that discusses the anatomy of a Cesium app
  * with links to relevant tutorials
  * a brief overview of Cesium's features for newcomers.
* Category headers / section divisions 
  * Are really important for readability and conceptual granularity. Worth reorganizing. 
  * Could we auto-gen a table of contents per tutorial? Or have sub-sections in the sidebar?
* What topics deserve tutorial coverage that aren't already there?

# Proposed New Tutorial Structure

## Quick start guide (very short)
* What is Cesium?
* Basic structure of a Cesium App
  * Links to all the relevant tutorials
  * Basic navigation
* Feature overview
* Resources overview
* Sandcastle links: index page (which also needs to be created)

## Cesium up and running
* Get browser Cesium-ready
* Selecting an Editor of IDE
* Downloading a Cesium release
* Setting up a web server
* Resources
* Sandcastle links: Hello world, Cesium widget

## Imagery Layers
* Adding Imagery
* Ready to use imagery
* Imagery providers
* Blending imagery layers
* Cross origin resource sharing
* Resources
* Sandcastle links: imagery, imagery adjustment, imagery split layers, imagery layers manipulation

## Terrain
* Adding Terrain
* Enabling terrain lighting and water effects
* Ready to use terrain
* Terrain providers
* Resources
* Sandcastle links: terrain, terrain exaggeration, 

## Creating Geometry
* What is an Entity?
* Our first entity
* Shapes and volumes
  * Link to Materials and outlines
  * Link to 3D Models
  * Link to Points, billboards and labels
* Heights and extrusions
* Selection and Infobox Description
  * Picking
  * Link to camera controls
* Managing entities
  * List info, remove, add
* Time-dynamic Entities
* Sandcastle: All the geometry ones! Display distance conditions, picking, show or hide entities, materials

### Points, Billboards and Labels
* Basic example
* Positioning
* Sandcastle links: billboards, labels, points, clustering, map pins, ground clamping, 

### Entity Styling
* Materials
* Outlines

### 3D Models
* Adding a model
* Basic properties
* Animations
* Picking
* Converting collada to glTF
* Troubleshooting
* Resources 
* Sandcastle links: 3D models, 3D model coloring

## Camera
* Default controls
* Camera Basics
* Camera Positioning and Animation
* Custom camera mouse/keyboard events
* Screen space camera controller
* Resources: camera tutorial, camera, headingPitchRoll, localToFixedFrame

## Primitive Geometry and Appearances
* What are Primitives?
  * Primitives vs Entities
  * Link to Creating Geometry
* Primitive Basics
* Geometry instances
  * Updating per-instance attributes
* Combining geometries
  * Picking 
* Appearances
  * Geometry and Appearance Compatibility
* Sandcastle links: geometry and appearances

# Proposed Sandcastle example organization (WIP)
* Basics / Beginner
  * Hello World
  * Cesium Widget
  * Rotatable 2D map?
* Camera and Views
  * Camera
  * Camera Tutorial (rename?)
  * Cardboard
* Imagery
  * Imagery
  * Imagery adjustment
  * Imagery split layers
  * Imagery layers manipulation
* Terrain
  * Terrain
  * Terrain exaggeration
* CZML
  * All the CZML ones
* Drawing and Styling Shapes
  * Geometry
    * All the basic geometry ones
    * 3D Models
      * 3D Models Coloring
  * Billboards, Points and Labels
    * Billboards
    * Points
    * Labels
    * Map pins
    * Clustering
    * Starburst
  * Styling and visibility
    * Distance display conditions
    * Materials
    * Show or hide entities
    * Shadows

**Comment by rahwang** [comment]
Thoughts, @slchow , @hpinkos , @pjcozzi ?

**Comment by slchow** [comment]
> Should we embed sandcastle tutorials?
That would be great.

> There should be some differentiation between tutorials and tech explanations.
If they're truly newcomers, maybe it's better to encourage them to sign up for Composer than have a super friendly intro to a library that will require fairly advanced skills to implement. 

> How much underlying detail is helpful in tutorials? If it doesn’t belong in the tutorials, where should it go?
It wouldn't hurt to start a blog series of short entries explaining basic technical workings of Cesium. That would streamline the tutorials, and you could link to the blogs (perhaps even with an icon) to find out more.

> We should have an overall quick start guide
Yes!

> Category headers / section divisions
Yes! Better headings and navigation would be really useful. I can't speak to the content here, so as far as that goes, you'll probably get better feedback from the community. I did read through all your reorganization in detail, and it looks good to me. I love the idea of breaking it down into smaller chunks and having better navigation between sections. 

From a purely user perspective, I find navigating Cesium globes pretty difficult (unless I'm on a touchscreen). Maybe as part of this a clearer explanation in the built-in hints explaining how to get around?

**Comment by rahwang** [comment]
From the forum:

"One issue I recently got caught on was how to listen to property changes, and I was given a solution on the forum (see here).  I don't see how I would have known how to do this by reading the documentation.  So if I could wish for another tutorial, it would be one to cover advanced coding and customization techniques for Cesium. 

But generally I use the Code Examples gallery to learn how to use the API, so my preference would be to see that maintained and grown."

https://groups.google.com/d/msg/cesium-dev/mW0VxrU3yhA/jUB8kTdNBAAJ

**Comment by rahwang** [comment]
## Increasing tutorial coverage

We have a lot of sandcastle examples with no associated tutorials. For the really minimal examples, this is probably fine, but here are some topics that I think may merit new tutorials, even if just short ones. As always, please comment / add / delete, or let me know if I've missed something @slchow @pjcozzi 

* CZML (in general)
* Interpolation
* Map modes (2D, 3D, CV)
* Shadows
* Label / billboard styling in general (e. clustering, starburst etc)
* Cesium inspector and how to use it

**Comment by mramato** [comment]
This is just a brain dump of some of my thoughts while reading the above, I'm sure I'll have more feedback as time goes on.

> Get browser Cesium-ready
> Selecting an Editor of IDE
> Downloading a Cesium release
> Setting up a web server

I think we have to be really careful about trying to teach our users how to program vs teaching our users 
how to develop with Cesium. We need to assume they have some base level of competence in web development and provide some links to external/third party tutorials if they don't.

Many of our users use npm to install Cesium, our tutorials should probably cover that as well.

I feel pretty strongly that what we need is quite a few boilerplate Cesium examples for different stacks, for example a bunch of hello world applications for Cesium with Angular2, React, ASP.NET etc.. maybe with different build systems like Webpack.  A non-trivial portion of our forum posts involve questions like "How do I use Cesium with...?"

As for Sandcastle, I think as a whole, we need many more fine-grained targeted examples.  Many of our examples could also be split up into multiple examples as well.  We should use forum questions as a way to help drive creation of Sandcastle examples.  We also need way more categories and I think your WIP layout has some holes in it that will become obvious as we reorganize.

> Time-dynamic Entities

Time in general needs way more than a single bullet point, and it goes way beyond entities.

I don't see much here about picking and interaction or dynamic modification of objects.  This is a major issue that comes up all of the time on the forum.

Your outline doesn't mention `Scene` at all, which is a really important part of Cesium that needs to be understood.

I also don't really see any mention of widgets.

I think we have to be careful to not make our Sandcastle examples too abstract.  In my experience, concrete use cases serve as better instruction than trying to each ideas (at least as far as code samples go).

I didn't see any mention of geojson, kml, or working with external data sources

Also, no mention of streaing realtime or pseudo realtime data, which comes up quite a bit on the forum as well.

> Cross origin resource sharing

This is a Cesium-wide issue, not specific to imagery layers.

Saving and storing a Camera view across scene modes comes up all of the time on the forum.  Same for how to take screenshots with Cesium (and the more advanced case of capturing video).

**Comment by rahwang** [comment]
Forum request for SampledProperty Sandcastle example with rotation:
https://groups.google.com/forum/?hl=en#!topic/cesium-dev/gb4HdaTTgXE

**Comment by rahwang** [comment]
As part of my quest to reorganize Sandcastle, and become more of a forum debugging ninja, I'm reading through all the Sandcastle code. As I go, I'll add a few clarifying comments where I think them helpful. To keep the discussion open, I'll add fine-grained pull requests with my comment additions for however many examples I go through each day.

**Comment by zwcloud** [comment]
Have these tutorials been finished?

**Comment by hpinkos** [comment]
Hi @zwcloud,  the completed tutorials are posted on our website here: https://cesiumjs.org/tutorials/

**Comment by Ranjan0968** [comment]
can anyone help me to make cockpits by cesium js 
![Screenshot (36)](https://user-images.githubusercontent.com/105446016/169783794-3e0995a2-9563-4d1c-b461-744d5ac6f593.png)
Like this
