### ISSUE TITLE
Call dispose on destroy for any observable created with knockout.defineProperty

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#5216]
The knockout es5 plugin creates a `knockout.computed` behind the scenes when we call `knockout.defineProperty`.  This `computed` listens to observables indefinitely unless we call `knockout.getObservable(this, propertyName).dispose()`.  This should be done in the `destroy` function for our widgets.

**Comment by mramato** [comment]
The version of the es5 plugin we are using is beyond ancient, it might be a good idea to update it and check if it fixes this issue as well.

**Comment by hpinkos** [comment]
Nope, current master does the same thing: https://github.com/SteveSanderson/knockout-es5/blob/master/dist/knockout-es5.js#L521

**Comment by mramato** [comment]
Thanks.  You should probably report a bug on their repository and verify that what you're suggesting is the correct fix.  I totally buy that what you're suggesting is needed, but we shouldn't let issues/bugs go unreported for the libraries we use.

**Comment by hpinkos** [comment]
I don't know if it's really a bug on their end.  It's the same as us recognizing that we need to `dispose` on subscriptions

**Comment by ggetz** [comment]
Given that we're likely to move away from knockout in the future, this is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
