### ISSUE TITLE
Include Cesium version number copyright header

### ISSUE THREAD

**Issue by Ismir11** [CesiumGS/cesium#5222]
Sometimes we loose track of the cesium version we are working with. Would it be possible to include the Cesium version number at top of the cesium.js file instead/in addition of at the bottom of the minified javascript?

**Comment by emackey** [comment]
You can just type `Cesium.VERSION` in the web console.

**Comment by Ismir11** [comment]
They have multiple versions of the cesium on their machines. They wanted easier way to identify the files

**Comment by mramato** [comment]
The `package.json` included with Cesium also has the version.

**Comment by pjcozzi** [comment]
What's the suggestion here?  Just close this?

**Comment by emackey** [comment]
Not sure.  If someone hands you a minified combined `Cesium.js` file, it's hard to know the version without actually loading the JS so you can evaluate `.VERSION`.  Looks like most of the 3rd party deps that are bundled in Cesium include their own version number as part of the copyright banner at the top, that survives the minification process.  It seems odd that all of these bundled packages all specify their version and we do not.

Also, I noticed that all of the included 3rd party ones all say `@license` as part of their top comment.  Cesium itself does not put the `@license` keyword on its own license at the top.  I think I saw cases some time ago where apps that included Cesium ended up including licenses just for the 3rd party stuff in Cesium but omitting the Cesium license itself.  We should probably fix this too.

**Comment by pjcozzi** [comment]
@emackey all good points, sounds like a nice beginner issues.  Perhaps for @klingerj?

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/10460
