### ISSUE TITLE
Evaluate SpectorJS

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#5279]
For WebGL debugging.

If anyone tries this with Cesium, please comment here with your thoughts.

http://spector.babylonjs.com/

**Comment by mramato** [comment]
It got added to the Chrome store, so testing it out with Cesium should be trivial: https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk

**Comment by pjcozzi** [comment]
Currently, if you have the **WebGL Insight** Chrome extension installed, it needs to be disabled for Spector to work.

**Comment by pjcozzi** [comment]
Tutorial: http://www.realtimerendering.com/blog/debugging-webgl-with-spectorjs/
