### ISSUE TITLE
Add eslint rules for formatting

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#5369]
When we switched over to eslint, we mostly maintained our jshint rules and whatever esline provided by default.  eslint has style rules as well as syntax rules, we should take advantage of these to provide uniform formatting to our code base.  Some of these are very simple, such as disallowing trailing whitespace, double blank lines, etc... Others can be custom and complicated (for example ensuring that matrix declarations are properly aligned).

We should explore the possibilities and decide what we want to do.  Many of these formatting rules can also be fixed automatically, providing us with the command line formatter we've craved for years.

**Comment by mramato** [comment]
http://eslint.org/docs/rules/#stylistic-issues has a good list to start with.

**Comment by ggetz** [comment]
I believe this is OBE since we added prettier.
