### ISSUE TITLE
Update a Contributor's Guide on best practices for GitHub issue labels

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#5488]
We recently updated our [issue labels](https://github.com/AnalyticalGraphicsInc/cesium/labels).  Let's document best practices for them once we know what they are based on some experience.  I think it will be:

* Try to apply one (or conservatively up to a few) `category` label (e.g., 3d-tiles, billboard, etc.) to each issue and PR so we know what areas of the code need work and are being worked on.
   * `category` labels roughly correspond to areas of the code but may vary in scope, e.g., `billboards` have their own category because they are popular even though they are fine-grained.  Loosely, labels with less than 5-10 issues may be candidate to merge with other labels, and labels with more than 50 issues may need to be divided.  We currently have some labels in booth categories that we can evaluate, and we may need the following new categories:
      * `category - geometry`
      * `category - ground primitive`
      * `category - point primitive`
      * `category - vr`
      * `category - performance`
      * `category - general`, ugh

* Apply only one `type` label (e.g., enhancement, bug, roadmap) to each issue and PR.  We may need the following category for evaluating ideas, tools, etc.
   * `type - research`

I also did some refactoring to our other labels:
   * `dev process` is now `category - tooling`
   * Removed `mobile` and `2.0`.  They were barely used and used inconsistently.  We can reconsider as experience shows, in particular, we may want some platform labels such as OS, browser, GPU if they are not overkill.
   * Rename `priority` to `priority - high`, and `next release` to `priority - next release` for better grouping.
   * Removed `bim` label since it wasn't used that much.  I am not opposed to project-specific labels like this for projects the core team are working on outside of the core Cesium repo to help start organized.

Finally
* I think the `cleanup`label should be removed.  It is used inconsistently and I don't know when we would want to filter on it or use it for decision making.
* We probably want to rename `beginner` and `onramping` to something like `beginner - easy` and `beginner - hard`.  I think the `onramping` label has been misunderstood.

**Comment by ggetz** [comment]
Given our label strategy has changed, this is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
