### ISSUE TITLE
Include Cesium drone model in this repo and the glTF sample models repo

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#5576]
@emackey what is the plan here?  Are we waiting for glTF 2.0 support?

#4009 / #5423

**Comment by emackey** [comment]
The current drone model (in the game repo) is just a glTF 1.0 model, with hard-coded PBR-like shaders based on @moneimne's earlier work (minus the env map of course).  It should work in Cesium master now.  I haven't made a glTF 2.0 version of the model yet.  Shouldn't be hard, just a matter of priorities.

**Comment by j9liu** [comment]
A 2.0 version of the Cesium Drone model is already in `Apps/SampleData/models/CesiumDrone`, so I'm going to close this issue.

**Comment by emackey** [comment]
Yes, sorry, this was added in #9215.
