### ISSUE TITLE
Support for subsurface / bathymetry

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#5665]
Add support for subsurface / bathymetry.

CC #526

**Comment by pjcozzi** [comment]
**Related**
* Globe base color alpha does nothing, #5163
* [translucent-terrain](https://github.com/AnalyticalGraphicsInc/cesium/compare/translucent-terrain) branch
* [cesium-groundpush-plugin](https://github.com/NICTA/cesium-groundpush-plugin)

**Comment by lilleyse** [comment]
Suggestion from the forum: do depth test when the terrain is opaque and disable depth test when the terrain is translucent, like this screenshot below:

![c](https://user-images.githubusercontent.com/915398/33583723-a9e8d5ce-d929-11e7-8ccf-dcf7a9265e2e.gif)

https://groups.google.com/forum/#!topic/cesium-dev/M7cKgT1IEsw

**Comment by ggetz** [comment]
Forum request specifically for underground camera controls: 

https://groups.google.com/forum/#!topic/cesium-dev/lSprfKeRJD8
https://groups.google.com/forum/#!searchin/cesium-dev/underground%7Csort:date/cesium-dev/kFW_x_slkrY/ZGSATjGVBAAJ

**Comment by ggetz** [comment]
Requested on the forum: https://groups.google.com/forum/?place=forum%2Fcesium-dev&showsearch=true&hideforumtitle=true&fragments=true&parenturl=https%3A%2F%2Fcesiumjs.org%2Fforum%2F&theme=default#!topic/cesium-dev/z_jJgEHgJqY

**Comment by OmarShehata** [comment]
Requested again: https://groups.google.com/d/msg/cesium-dev/Sb47qbQ_0NA/ODiezbeeAAAJ

**Comment by OmarShehata** [comment]
One thing to fix as part of this would be terrain skirts being visible when looking at underground data. This thread has screenshots and a Sandcastle of the issue:

https://groups.google.com/d/msg/cesium-dev/ZVgo6VNeOUo/-OW4eoMMGgAJ

The goal is to use clipping planes in order to:

> ...open the globe at a specific defined region for the user to see subsurface layers there (which are included through a tileset).

**Comment by lckinggis** [comment]
> 来自论坛的建议：当地形不透明时进行深度测试，并在地形半透明时禁用深度测试，如下面的截图：
> 
> ![C](https://user-images.githubusercontent.com/915398/33583723-a9e8d5ce-d929-11e7-8ccf-dcf7a9265e2e.gif)
> 
> https://groups.google.com/forum/#!topic/cesium-dev/M7cKgT1IEsw

hello，
I want to know how to achieve this effect.

**Comment by OmarShehata** [comment]
Requested again on the forum. There's also some sample code of a use case here and a possible texture rendering bug, but I haven't been able to reproduce this:

https://groups.google.com/d/msg/cesium-dev/79R_lZaCdds/YxECMxg_BgAJ

**Comment by yoyomule** [comment]
Does cesium optimize this problem at present?
I think there are several situations of underground mode:
1. When all the structures are underground, it is better for the earth surface to be translucent if it is roaming underground and looking at the model.
2. When half of them are underground and half of them are on the ground, if you roam underground and check the model, you should be able to distinguish who is which part of them is on the ground and which part is underground, and there should be clear boundaries.

**Comment by lilleyse** [comment]
@yoyomule we're adding underground support as part of https://github.com/CesiumGS/cesium/pull/8726 and https://github.com/CesiumGS/cesium/pull/8811

For (2), what type of distinction do you have in mind? Like a color or post processing effect? Curious if you have an images / screenshots for this sort of behavior,

**Comment by yoyomule** [comment]
Thanks.
![image](https://user-images.githubusercontent.com/10000818/81268890-1ec7a900-907b-11ea-82d4-68f62ac5753c.png)
![image](https://user-images.githubusercontent.com/10000818/81272060-87b12000-907f-11ea-8889-53604b571825.png)

**Comment by oi-eddyoj** [comment]
Hi, we are looking for this solution as autonomous underwater vehicles and unmanned surface vehicles are becoming increasingly more prevalent. We would like a portal for our data and I'm wondering if this feature is on the roadmap?

**Comment by OmarShehata** [comment]
@oi-eddyoj we are actively working on improving underground camera controls here: https://github.com/CesiumGS/cesium/pull/8811. That may help depending on your exact use case. Can you post some sample data or more info about your use case on the Cesium community forum (https://community.cesium.com/)? I can take a look and let you know if there's any known workarounds for the issues you're running into or if it's something fixed by those upcoming improvements.

**Comment by ggetz** [comment]
Hi all, given the work we've done in https://github.com/CesiumGS/cesium/pull/8726 and https://github.com/CesiumGS/cesium/pull/8811, I'm going to go ahead and close this issue. If there are any additional requests around subsurface/bathymetry/underground, please open a new issue. Thanks!
