### ISSUE TITLE
3D Tiles Inspector sliders do not display correctly in IE

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#5702]
![image](https://user-images.githubusercontent.com/3451886/28794444-69a40b42-7604-11e7-93c4-fba2b0f62e67.png)

**Comment by hpinkos** [comment]
This is probably an IE bug, but we might be able to work around it with CSS styling

**Comment by ggetz** [comment]
Closing since IE11 support has been dropped.
