### ISSUE TITLE
Naming convention for parked branches?

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#5923]
It's great to see slow moving pull requests moving to parked branches like https://github.com/AnalyticalGraphicsInc/cesium/pull/2929#issuecomment-338326141 and https://github.com/AnalyticalGraphicsInc/cesium/pull/2939#issuecomment-338317275.

Perhaps we should start to use a naming convention like `parked-` so it is easier to browse branches?

**Comment by ggetz** [comment]
It's possible to restore deleted branches that are attached to a closed PR: https://medium.com/@vbabak/how-to-deal-with-stale-branches-on-the-github-b49727480872.
