### ISSUE TITLE
Some tiles not get loaded when switching terrainProvider

### ISSUE THREAD

**Issue by Vineg** [CesiumGS/cesium#6021]
If you change terrainProvider during reprojection of the tile, right after
```
            this.state = ImageryState.TRANSITIONING;
            this.imageryLayer._reprojectTexture(frameState, this, needGeographicProjection);
```
gets called, Imagery stucks in TRANSITIONING state and prevents tile from loading. It is happens because `cancelReprojections` gets called.

is method `tileProvider.cancelReprojections` affects something at all? Maybe we could remove it? If you comment it out, everything seems working fine.

In our application terrainProvider is changed early and it randomly causes one or two halves of the globe not loaded:
![half](https://user-images.githubusercontent.com/1757455/33482753-988a94fa-d6ab-11e7-9e52-ad079b9bac4c.png)

**Comment by mramato** [comment]
Thanks @Vineg, this definitely sounds like a bug.  @bagnell any thoughts?



> In our application terrainProvider is changed early

What do you mean by this?  Are you setting the terrain provider right after creating the Viewer/Widget?  If so, you can try passing the `terrainProvider` option into the widget constructor, which should workaround the issue for you.

**Comment by Vineg** [comment]
> What do you mean by this? Are you setting the terrain provider right after creating the Viewer/Widget? If so, you can try passing the terrainProvider option into the widget constructor, which should workaround the issue for you.

@mramato, We load terrainProvider url with xhr and after it is loaded, we set it, so it is not immediatly after creating Widget, rather somewhat after it. I already workaround this issue by commenting out `cancelReprojections` in `QuadtreePrimitive.prototype.invalidateAllTiles` call.

**Comment by mramato** [comment]
OK, thanks.  Is this easy to reproduce in a Sandcastle example?  If you could share a simple test case that we can run ourselves that should make this much easier to fix.  Thanks.

**Comment by Vineg** [comment]
@mramato here you go https://pastebin.com/na4cK7kR
It works not every time, run example few times.

**Comment by mramato** [comment]
Thanks @Vineg!  

Here's the full example from the pastebin link:

```javascript
var viewer = new Cesium.Viewer('cesiumContainer',{
});

// Load PA terrain
var cesiumTerrainProviderMeshes = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/PAMAP/tiles',
    requestWaterMask : true,
    requestVertexNormals : true
});

var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles'
});

setTimeout(function() {
    viewer.terrainProvider = terrainProvider;
    setTimeout(function() {
        viewer.terrainProvider = cesiumTerrainProviderMeshes;
        setTimeout(function() {
            viewer.terrainProvider = terrainProvider;
        },70);
    },550);
}, 2000);
```

**Comment by ggetz** [comment]
Brought up on the forum: https://groups.google.com/forum/#!topic/cesium-dev/4wKjJWPoLAk

**Comment by Vineg** [comment]
Here is quickfix https://github.com/geoscan/cesium/commit/ce5c718cc402f8459bdfb7cb3dfd865f1400372e Maybe someone can review it?

**Comment by hpinkos** [comment]
@bagnell or @kring, can you take a look at this?

**Comment by kring** [comment]
I can still reproduce this with [this Sandcastle](https://sandcastle.cesium.com/#c=nVJfT8IwEP8qzV4YydKhCTGRQTS8gpJI8KUvZTukoWvx2g7R7LtbtqECZibeU+/37y6XFhxJIWAHSIZEwY6MwQiX00WFhZ20asdaWS4UYCf6YKrsDphiKo7JRPOMzO6JBUTPM1X4uNoyr6EZ6kJkgFMwazB+RpOfInALzxpl1ihDn0x8Ibw6MPbZ0zjlZkNuiUUH0Qm7ALTw9qAx59I0iq/FDkvY0/Gtg2uXATsXOWhnw5VTqRXaM6RZqj4RvUw9Qwa1vDWrNa/leINv+5/5/9j5UGV00+s2fRn1+1VTRuS616ueQRQkxu4ljI6eO5FvNVriUIaUxhbyrfT3NfHSpRuwNDXmGJjEP61JJgoisiELzr4YC0gquTGeWTkpn8Q7sGCUxF5/YZX+/wn18lgASr4/yNZXo0kNUkqT2Le/O63WcsnxLPkT).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/4wKjJWPoLAk

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/6021 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
