### ISSUE TITLE
Atmosphere is culled irregularly when near/far frustum is changed

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#6103]
![image](https://user-images.githubusercontent.com/4439461/34743555-1817b246-f558-11e7-85f5-17f200cfcc36.png)

```
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.camera.frustum.near = 0.15;
viewer.camera.frustum.far = 50000000;
viewer.camera.rotateRight(0.01);
viewer.camera.rotateDown(0.001);
```

Reported on the forum here: https://groups.google.com/forum/#!topic/cesium-dev/Q-_88AaT8sc

**Comment by emackey** [comment]
I've seen a similar effect when the atmosphere is near the back of a frustum in the multi-frustum stack.

The near/far planes are too extreme here for everyday use on a normal graphics card, but, maybe these extreme settings could be used to debug why this artifact shows up when it doesn't look like there's much there to Z-fight with.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/Q-_88AaT8sc

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/6103 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
