### ISSUE TITLE
Coding Guide: only write to properties once in a constructor function?

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#6139]
For the [Constructor Functions section](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#constructor-functions) of the Coding Guide, I suggest we add something like:

> In a constructor function, consider properties as write once; do not write to them multiple times or read them.  Create a local if they need to be ready.  For example:
>
>Instead of
```javascript
this._x = 2;
this._xSquared = this._x * this._x;
```
> prefer
```javascript
var x = this._x;
this._x = x;
this._xSquared = x * x;
```
I have always been doing this, but I _think_ it is widely done.  +1 or -1's?

**Comment by hpinkos** [comment]
Isn't this kind of already covered by "Avoid redundant nested property access"?

**Comment by pjcozzi** [comment]
Right this is related - and the code example kind of shows that, but I still think it is good to be explicit about constructor function property assignment style: write once and do not read.

**Comment by andynines** [comment]
It looks like this issue was addressed in https://github.com/CesiumGS/cesium/pull/6604 and is ready to be closed.
