### ISSUE TITLE
Lighting discontinuity when terrain water mask and globe lighting enabled

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#6141]
There's a visible seam at longitude 0 when both the terrain water mask and globe lighting are enabled:

![image](https://user-images.githubusercontent.com/3451886/35229464-812f6338-ff61-11e7-897f-a2a003ba5110.png)

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : Cesium.createTileMapServiceImageryProvider({
        url : Cesium.buildModuleUrl('Assets/Textures/NaturalEarthII')
    }),
    baseLayerPicker : false
});

viewer.scene.globe.enableLighting = true;

var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles',
    requestWaterMask : true,
    requestVertexNormals : true
});
viewer.terrainProvider = terrainProvider;
```

**Comment by hpinkos** [comment]
@ggetz also noticed this

**Comment by hpinkos** [comment]
@mramato no, I disagree with you.  This seam is only visible if both the terrain watermask and globe lighting are enabled so I don't believe it's a problem with the imagery

**Comment by ggetz** [comment]
I can no longer reproduce 🎉 

<img width="511" alt="image" src="https://github.com/CesiumGS/cesium/assets/4439461/72353f94-9419-4646-86ed-634be53fdd63">
