### ISSUE TITLE
Artifacts in vector tileset

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#6219]
@bagnell is this a tiling problem or Cesium problem?

![vector](https://user-images.githubusercontent.com/915398/36215937-70ae74aa-117b-11e8-96ae-8e2a80c32a42.gif)
<img width="195" alt="vector2" src="https://user-images.githubusercontent.com/915398/36216050-b8a829c2-117b-11e8-8696-a6f5899052a9.png">
<img width="271" alt="vector1" src="https://user-images.githubusercontent.com/915398/36216051-b8e5b06c-117b-11e8-9a2c-ac22ec4f22d3.png">

Roughly in this area:

<img width="399" alt="vector3" src="https://user-images.githubusercontent.com/915398/36216142-eb799304-117b-11e8-8849-f23bff4ec6dd.png">

**Comment by bagnell** [comment]
A tiling problem. I've seen the same issue with other datasets most likely caused by intersecting edges.
