### ISSUE TITLE
Skinning broken with log depth

### ISSUE THREAD

**Issue by bagnell** [CesiumGS/cesium#6447]
Using log depth when skinning shows artifacts.
![image](https://user-images.githubusercontent.com/1494815/38704350-05d6053c-3e74-11e8-93cd-675c4047cc57.png)
The current model implementation has a workaround until it is fixed. To see the issue, remove the two lines [here](https://github.com/CesiumGS/cesium/blob/dbd44f6bc55ded889fea93c100f7509e1e3e0fee/Source/Scene/Model.js#L1998-L1999).

**Comment by bagnell** [comment]
Babylon.js has the same issue. I think it's an issue with the model.

https://github.com/BabylonJS/Babylon.js/issues/4240

**Comment by emackey** [comment]
I'm not convinced it's an issue with the model, because it only happens when Log Depth is enabled.

**Comment by emackey** [comment]
Update: It is the fault of the model, for not having normalized bone weights.  See https://github.com/KhronosGroup/glTF/issues/1213#issuecomment-385532438

**Comment by lilleyse** [comment]
Also came up in https://github.com/CesiumGS/cesium/issues/8875 with this model: [miner.zip](https://github.com/CesiumGS/cesium/files/4676080/miner.zip)
