### ISSUE TITLE
GroundPolylinePrimitive and Ground Primitive materials render poorly on newer mobile devices

### ISSUE THREAD

**Issue by chris-cooper** [CesiumGS/cesium#6735]
![image](https://user-images.githubusercontent.com/484870/41953063-cc33ae9a-7a16-11e8-8255-42acc486e5d1.png)

These lines dance as the camera moves.  This is on an MP2F2LL/A.

**Comment by likangning93** [comment]
There seems to be a problem with materials on ground polygons too... maybe this is depth buffer related?

**Comment by likangning93** [comment]
At least part of this is weird depth buffer stuff:

![2018-06-27](https://user-images.githubusercontent.com/5395255/41983153-3d2322d2-79fb-11e8-878d-4e92ddebcbed.jpg)

[Sandcastle to reproduce.](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVhfU9s4EP8qOh4a+zAK0D7cFOgcE9KWOVqYJne9zjDTUW3F0SFbPll2Eph891vJsS05duF4AGv//HZX2l2tKIlEJaMrKtEFSukKTWjOigT/ZWjeKDTLiUgVYSmVI//sPi1BJw9pSkGl0sVmCayKqSSLRSoSquTmCw0VSWNO7yRLmGJlJbYo0lAxkSJO1I1I47mYZUsqWUi4BySmiogGiAPHfPro6T5F8KPhQyKViCXJlix0vZ5YHE+7qlVscVxjg1792StWG9Zy9Xef4JKyeKlA6hgfm8BqJ3MdDr0TLNXcHv+wEnoJDJJ6Nmbt9yCCUXmNUyETwtkj9SzJwFbzG4/GY3QnxT9wFgjoAmWcwPGtmFqikkqltx0thGz2pI0jIfHf38D+J6KWOP9XKtsaXqNfkbs+dNabDn/juPRnTtGC5Ooyy6RYs4QoegnJcmpcgdDiNKEQvHEzX5KIyu7+3rTHudsg42cfqGcicfYHP9Z7bSFaJ/8spBN6MBSpBpc0L7jaz1ZzlqdNrlZisI0XnQBd/qbld5KzFlOFTHfSwNnWlSnravzKIthUk7bwc+LWJImi/bJ1c9SuxwbUDa+B8AZK66jjTjBQqs/JNYCHLwTsyjlJORFJViha7a8pjFAIGbEUTj1HYoHUkrb6oxx9FlItp5AeiKQRmolCLb9SWIVCQsfMrQSrWU2rq7pQt/814NhoBK01vAJtO2fT2vaLIY2GDUlJrtxcJbzap+laUdN79h3Ha8sJ8sgSEPiZ+KZbZ5r6se6d+1FABRw9Z7bBqXO5B2bTD7Nx4l1IEutGMzMtBg5QhpDKFV//jBZcELW/LSNIpA7xEI3ONHlfubNHRtehDaru79eo7rIW9Xn1epsc7YrYKlvqpWARtH+Wen4H+Kmz1r8qY1zEVzRTy1tp/oC18DH5XqQZCR8MxVN0Db2Jnl55mhNz8YMaxryiByjm39/DgUx00eH1Bo0NhJ4zMjhf/Ljyfe1rx3xJwzdoJSSPjOLOMEvhdsupHmbgItKUFUsjsZqL6YZO2rL2OkaDbiD+WU/IYPM1qm7hKvt213HrBkA9QgAWYTWEdLpr6DvPSXvVNGlrO1xZ6wVzs7W5KaB2hoWrTGxlN8OyBUh5DfpRpwJ8CLeTmsNQpYHa2T5y68EBMlm6n6HNwYeCCz3A6oVXBKgM9MUWoBN83JcsbIE84KPzC4jm1Sv4BV8gq7939FJ/lzs63Hb7IPqnSZvKvHGjx94WUQ6jzhN6EYoJwrhfxzAYyNYlbUdNX/v5CO5e1O0V/9SCxbRSvk5zUIZnAHpr63zosG1VW93Vajyp1btq1fBSjxNv229XbOu3660ftAsoG0qkdsg1DCMcZBLhlw2/a7n3EnjbS7ZtV9/bZmbX7yCc1RuaYxilvJ+fhW/PZ0sYIXj3LTYLJaXpDHoonZbgy8dKyKuMhQQ0c42yU8Y5VdcpzDCXZprz6rHOS0RJE1NaTwPeSqplXuBwXUUVQiKgE/xycdE6DNRPQMSfbr/cfbz+/KEx6SpmLHy4EznT7s2KTDd4Gjmy9pvPzMrtmzMkCZXEYEw5Z1kO91UTI852sO1oY5vfORrRBbxqI69B9/eMDzw6+x50CykS90lXYZ7tI75gwu5oba2s2yUd5E0wlCPzTUbxzfT9/Pvk5nryh9+8zVkKtgi3nzlHvx3jkzOX3b6r6odtv8tD+3BFY3Ao97rmgq4F3/xHwTlRLsTDpfL2X7z/DzjofWu99k6Oq75q/Rl0Yg69IofXaOK1jUSy9Rt8fTX9PL+ef9OKB8HBea42nL6rDuZ3luhMRoXkHsZjRRN4boP18Y8ifKAKh7kp1/NxrXQesRKx6OL+oPPvlvsDFHKS58BZFJzPYLq4P3h3PgZ5Rw1uUxgM4luYdjjZaJHlybubiogxPh/Dcl9LCcF/EGkh/gc)
Need to zoom and pan a bit for this weirdness to happen, then it usually goes away when the view becomes static. It's weird that ground polygons with materials won't draw at all, though, even when the camera goes static.
Maybe something odd about vertex attributes...

**Comment by likangning93** [comment]
Part 2 of the problem (aka the part that's probably my fault):
materials on ground polygons work *roughly* correctly (jitter problem when moving from above) when using approximate inverse trig, but not when using planar methods!

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVRRT9swEP4rXl+aiMqF19GioYwNtLIhivZUCRnnkno4vsh2igD1v+8SN21I6cRcqa3v7vvuu8tdVsKylYInsGzKDDyxBJyqCv67sUVD2VwTNF4oA3YYny7MijBOggGCBCxvruRi2xPCMMsceIo74ccn5CdrAIDxyitwXKRp9BqAFqQXJtfAPrPXHZdEtKkywoMjx0bfbRvLM4vFV8gtgIuO+fGINV8hcfsbj3Z0BRFZJTRxDTkfq0Lk4MaB9n6GOd4nqNHyP2U+DKj1wqybuoP0F8TiDqNeIXGojmpeCpPqfj/nkgSaeSkkXKwIcxmCoqZxXApCNhQbMCfRV6as/Ln0Ck2UVSb8KXAFBeHjtkP9flqoQ861juLN81AZ26QpMAX2aTrdiSLrNRn59a/bm8urn9/jbuN3wFLJxxt0qpYwr8oSrYf0TWwjhYqXglxOCbObDSkKsKLhuNBalQ5Vuq2Dlxva0L8uXZ1+IzSFjKYvjbbs8V7yrgDMrSiXSrJtpUnH2kxM0jJ1OE/fZ9TC74iuhV9yj+3AdbNxClS+SuEgEZoPEqHJDzJJNA5p7jXmUc14xIb0Oaplvpv48L71z4H92xfw4X0kfaNa2IgFpe1W1i09emc3++f/d7V/1vvmdb9NnZj1duM7vfvXwq9Hhzb87rkEPrv4dnefzK6SH/HpYDSYOP+s4Sywf1FFvUissjqi4jwUpa6bOn6o5CN4Ll2TYzJuQZNUrZhKp4tB7628GDCphXPkySqt5+oFFoOzyZji38A0Cnpw+a8VWC2e65DlydksGDnnkzFd91EeUT8I22H8Cw).
Tap on the screen to place a ground polyline with a texture and zoom to it. This works roughly correctly in 3D but not in 2D/CV, or if the `offset` parameter is lowered to below one degree.
Interestingly, the setting the offset really low "almost" works for the first rectangle, placed at lat/long (0,0), but then doesn't work at all after that.

I'll keep updating with notes.

**Comment by likangning93** [comment]
Actually, to reduce noise I'm going to move tracking for this into a separate issue. I'm pretty confident it's a similar problem under the hood.

**Comment by likangning93** [comment]
Another problem:

[Sandcastle on a deployed branch](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/buildModuleUrlWorker/Apps/Sandcastle/index.html#c=dVRtb5swEP4rKPsQIzEHCoWkTatFyTZV2tZKiTpNpR8ccBOrxka2Icum/vddeEkhXfkCvnvu7vFzd5REWSWjO6qsK0vQnTWnmhUZvq9saJhUx7kUhjBB1dCx/sbCgsdQpcB0p2TJUoi+aCMTRYmhP6Xi6arGIDsWL/ZlLEoophMqKNSqi+LqCK7ayaXM76RmhkmhAdSknBNl4IsIHz8pmS3oRlGqZ5B8jx5qOh89z8OT4Nx1o2hyFgWeFziWH+KzKPTHYTQejwMv8J0u2J2MfdcN/MlZOAkrsBtNxud+GHqRH5wHsXi0j8yY0IaIhPZV+kplRo3a3zRe1IizaeygShetZCHSO8n3HLRsY9uYw5Mf737R18J5xexYarbg94BvbX2xGzcxRrF1AVqBv5NWb+WuT2UJllPyszYa2Z1yieSy09354fhuZNWeCoK6+NqsdXVYAlZs0PBDGM0Wiy9DG++Y2c54viXIxZFtN5dqZqaWP29EuxWrdu5YBtKUpw3pSXwEnfalJX7Qqe1sc+eUrovNQZ7llqRydy95kVGAGVXQhtL7ZDDJc0rU20FpGVUKzI4gVN+wWgK8qbm3uTQmaYrer9WIU69RQjKqCIaZeZ4Z1BudB+/R6VJ5XSYE2+Ji17H6b7ta1f/kXQFn/SRV1jb3O4Fe/g7wzeLzj9XN6pd9OXAGU232nF7Xan5iWS6VsQrFEcYjQ7Ocw99Bj9ZF8kwNTrQ+VJuO2qBpykqLpVfx4OTPEw+shBOtwfNUcL5kf2g8uJ6OAN8L45KkMF+3JVWc7A+QrXf9rTZijKcjOL6NMlLyNVGdjP8A)
```
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider : Cesium.createWorldTerrain()
});
var scene = viewer.scene;

var loopPositions = Cesium.Cartesian3.fromDegreesArray([
    -111.94500779274114, 36.27638678884143,
    -111.90983004392696, 36.07985366173454
]);

var instance = new Cesium.GeometryInstance({
    geometry : new Cesium.GroundPolylineGeometry({
        positions : loopPositions,
        width : 16.0
    }),
    attributes : {
        show : new Cesium.ShowGeometryInstanceAttribute(),
        color : Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.fromCssColorString('#67ADDF').withAlpha(0.7))
    }
});

var polylineOnTerrainPrimitive = new Cesium.GroundPolylinePrimitive({
    geometryInstances : instance,
    debugShowShadowVolume : true
});
polylineOnTerrainPrimitive.appearance = new Cesium.PolylineColorAppearance();

scene.groundPrimitives.add(polylineOnTerrainPrimitive);

viewer.camera.lookAt(loopPositions[1], new Cesium.Cartesian3(5000.0, 5000.0, 5000.0));
viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
```

On the iPad, going to a view where the camera is inside the volume seems to sometimes ignore that depth testing is supposed to be disabled:
![6cdb2068-bb55-498c-98fe-71ce1c66ed6e](https://user-images.githubusercontent.com/5395255/41995129-a890b598-7a1e-11e8-8053-68202df9ab30.png)

The depth test also seems to be against the "weird" depth buffer observed above.

**Comment by likangning93** [comment]
@bagnell and @mramato pointed out that logarithmic depth isn't supported on iPad/Safari, so the "looks like this is depth testing" problem is actually the far "cap" of the volume being beyond the far plane. This particular problem is reproducible on desktop by disabling log depth.

**Comment by likangning93** [comment]
> This particular problem is reproducible on desktop by disabling log depth.

So that's fixable, but depth texture problems are... still a problem.

**Comment by likangning93** [comment]
[Better proof of depth texture problem](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVhfU9s4EP8qOh4a+zAK0D7cFOgcE9KWOVqYJne9zjDTUW3F0SFbPll2Eph891vJsS05duF4AGv//HZX2l2tKIlEJaMrKtEFSukKTWjOigT/ZWjeKDTLiUgVYSmVI//sPi1BJw9pSkGl0sVmCayKqSSLRSoSquTmCw0VSWNO7yRLmGJlJbYo0lAxkSJO1I1I47mYZUsqWUi4BySmiogGiAPHfPro6T5F8KPhQyKViCXJlix0vZ5YHE+7qlVscVxjg1792StWG9Zy9Xef4JKyeKlA6hgfm8BqJ3MdDr0TLNXcHv+wEnoJDJJ6Nmbt9yCCUXmNUyETwtkj9SzJwFbzG4/GY3QnxT9wFgjoAmWcwPGtmFqikkqltx0thGz2pI0jIfHf38D+J6KWOP9XKtsaXqNfkbs+dNabDn/juPRnTtGC5Ooyy6RYs4QoegnJcmpcgdDiNKEQvHEzX5KIyu7+3rTHudsg42cfqGcicfYHP9Z7bSFaJ/8spBN6MBSpBpc0L7jaz1ZzlqdNrlZisI0XnQBd/qbld5KzFlOFTHfSwNnWlSnravzKIthUk7bwc+LWJImi/bJ1c9SuxwbUDa+B8AZK66jjTjBQqs/JNYCHLwTsyjlJORFJViha7a8pjFAIGbEUTj1HYoHUkrb6oxx9FlItp5AeiKQRmolCLb9SWIVCQsfMrQSrWU2rq7pQt/814NhoBK01vAJtO2fT2vaLIY2GDUlJrtxcJbzap+laUdN79h3Ha8sJ8sgSEPiZ+KZbZ5r6se6d+1FABRw9Z7bBqXO5B2bTD7Nx4l1IEutGMzMtBg5QhpDKFV//jBZcELW/LSNIpA7xEI3ONHlfubNHRtehDaru79eo7rIW9Xn1epsc7YrYKlvqpWARtH+Wen4H+Kmz1r8qY1zEVzRTy1tp/oC18DH5XqQZCR8MxVN0Db2Jnl55mhNz8YMaxryiByjm39/DgUx00eH1Bo0NhJ4zMjhf/Ljyfe1rx3xJwzdoJSSPjOLOMEvhdsupHmbgItKUFUsjsZqL6YZO2rL2OkaDbiD+WU/IYPM1qm7hKvt213HrBkA9QgAWYTWEdLpr6DvPSXvVNGlrO1xZ6wVzs7W5KaB2hoWrTGxlN8OyBUh5DfpRpwJ8CLeTmsNQpYHa2T5y68EBMlm6n6HNwYeCCz3A6oVXBKgM9MUWoBN83JcsbIE84KPzC4jm1Sv4BV8gq7939FJ/lzs63Hb7IPqnSZvKvHGjx94WUQ6jzhN6EYoJwrhfxzAYyNYlbUdNX/v5CO5e1O0V/9SCxbRSvk5zUIZnAHpr63zosG1VW93Vajyp1btq1fBSjxNv229XbOu3660ftAsoG0qkdsg1DCMcZBLhlw2/a7n3EnjbS7ZtV9/bZmbX7yCc1RuaYxilvJ+fhW/PZ0sYIXj3LTYLJaXpDHoonZbgy8dKyKuMhQQ0c42yU8Y5VdcpzDCXZprz6rHOS0RJE1NaTwPeSqplXuBwXUUVQiKgE/xycdE6DNRPQMSfbr/cfbz+/KEx6SpmLHy4EznT7s2KTDd4Gjmy9pvPzMrtmzMkCZXEYEw5Z1kO91UTI852sO1oY5vfORrRBbxqI69B9/eMDzw6+x50CykS90lXYZ7tI75gwu5oba2s2yUd5E0wlCPzTUbxzfT9/Pvk5nryh9+8zVkKtgi3nzlHvx3jkzOX3b6r6odtv8tD+3BFY3Ao97rmgq4F3/xHwTlRLsTDpfL2X7z/DzjofWu99k6Oq75q/Rl0Yg69IofXaOK1jUSy9Rt8fTX9PL+ef9OKB8HBea42nL6rDuZ3luhMRoXkHsZjRRN4boP18Y8ifKAKh7kp1/NxrXQesRKx6OL+oPPvlvsDFHKS58BZFJzPYLq4P3h3PgZ5Rw1uUxgM4luYdjjZaJHlybubiogxPh/Dcl9LCcF/EGkh/gc)

**Comment by likangning93** [comment]
@chris-cooper in the meantime, you might be able to adjust the near/far ratio in your scene to get better results for the specific use case.

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider : Cesium.createWorldTerrain()
});
var scene = viewer.scene;
scene.farToNearRatio = 50.0;

var loopPositions = Cesium.Cartesian3.fromDegreesArray([
    -111.94500779274114, 36.27638678884143,
    -111.90983004392696, 36.07985366173454
]);

var instance = new Cesium.GeometryInstance({
    geometry : new Cesium.GroundPolylineGeometry({
        positions : loopPositions,
        width : 4.0
    }),
    attributes : {
        show : new Cesium.ShowGeometryInstanceAttribute(),
        color : Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.fromCssColorString('#67ADDF').withAlpha(0.7))
    }
});

var polylineOnTerrainPrimitive = new Cesium.GroundPolylinePrimitive({
    geometryInstances : instance
});
polylineOnTerrainPrimitive.appearance = new Cesium.PolylineColorAppearance();

scene.groundPrimitives.add(polylineOnTerrainPrimitive);

viewer.camera.lookAt(loopPositions[1], new Cesium.Cartesian3(5000.0, 5000.0, 5000.0));
viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
```

I'm seeing that a near/far ratio of 50 seems ok for viewing lines at distances of centimeters to a couple meters. For further distances it seems to depend on the view angle. It might also depend on the terrain complexity at the particular view location.

But having to tweak far/near ratios for a specific platform really isn't ideal, I'll dig deeper on if we're unintentionally causing precision issues.

**Comment by likangning93** [comment]
> I might try transferring the depth to a float texture to see what happens. [EDIT] This is maybe what the fix was in that Unity forum post. I talked about float texture problems on iOS in another issue, but maybe Apple optimized for [0.0, 1.0] range.

Now I have learned two things:
* on Desktop, you can't render to a single-channel float buffer, which in retrospect makes sense
* on iOS you can't render to a float buffer at all, which in retrospect also kind of makes sense if their under-the-hood implementation for *reading* from float textures is actually an approximation

So copying globe depth to a float texture instead of the current packing isn't going to work. @bagnell also proved out that the packing isn't at fault here by providing the globe depth stencil texture directly to this on an experimental branch, we still had artifact problems.

**Comment by likangning93** [comment]
So I guess the conclusion is, depth texture precision on modern iOS devices just isn't sufficient.
Going back to that Unity post, their bug might also have been different since they use near/far 1/60 and I don't know if they bothered to test more view distances than the tens-of-meters in their images.

One more idea that @bagnell suggested is re-rendering all the terrain (and eventually 3D Tiles) to produce a depth texture instead of relying on the depth texture feature. If it worked this would also be an awesome addon for enabling support on platforms like Internet Explorer and lower-end mobile devices that don't have depth textures builtin, and it would also impact a lot of other Cesium features that depend on the depth texture.
But the big caveat is that it would be *slow*, and that's also still "if" we can get it working - note to people like future me, this isn't as straightforward as just packing `gl_FragCoord.z` into `gl_FragColor` in the fragment shader because the `gl_FragCoord.z` I think is part of the problem...

Could also be a lot of work to implement, so unfortunately I don't know how soon I'll be able to evaluate this.

**Comment by likangning93** [comment]
@chris-cooper another development: polyline-on-terrain problems don't seem to be as severe on the iPad 4. We've been testing (and reproducing the problem) on a first-generation iPad Pro, which supposedly has a similar SoC.

If you have older hardware available for your use case, that might also be an option.

**Comment by likangning93** [comment]
Relevant issue on three.js: https://github.com/mrdoob/three.js/issues/9092

**Comment by chris-cooper** [comment]
Thanks for the extra info @likangning93

**Comment by hpinkos** [comment]
Also reported by @Spec1alFx in #7377

**Comment by likangning93** [comment]
Just since it hasn't been written down here yet, fallback possibility: use the regular multi-pass algorithm with the polyline geometry + vertex shader, disallow materials beyond color.

**Comment by likangning93** [comment]
Some notes from the couple odd times I got to play around with this:
* it looks like depth interpolation on these devices is inaccurate as opposed to being just a depth buffer problem
* using a dedicated varying for depth seems to work fine though

[On Sandcastle, with a custom shader on a primitive](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1Vltb9s4Ev4rvHyxfFVkp+0Bi7wUlzpJY1zaBokvwWG9KBhpbPNKiVqKsqMs/N93SEnUi2XH7d6XMwLEHM7Lw+FwOBwvqSRLBiuQ5IxEsCIjSFgaeg+G5vR8MxyJSFEWgey55I9pRPAj4fcUEnUHUQDyswiAHBMlU3DzaRbSOcjsVoolQwacLBT7EqiCCePwmcb3IJfMh3GT2SlM6E8qeSX7lDIeoK2Uw78ld3rnSQIqGUzgWaUSksEXiv8pv6RSLcbjXj9Xs8b/6/7JNJpGS1xt4kMEuNh81Z4Z4qT573Exp5KpRcj8C4jV4mM6mxnXzChPNJvW4NMQJEViLpMPrf7Vgil4XFAOd+ArGs053EoWMsWWYJlkOfXIArVAVUNviJ8jwzBLI18xEZEl5SlMxAP47xzzvV95H1cakd5ST/XIm5z11+Fv+BX3qKIcWYolvTWkfg9trRvmFmy++HFr3nDTXk5rWfSGHTZpEGy6yfFxB8Vc0njBfIMix9HwXDNerZKGLO5nNGcqxeg8bPncJU1Gqvbjswrf7KmwzZdHYrkcIdmcRZSfKyXZU6ogwXUVa7pf0ECsHgRPQziPY6CSRj54c1C3nEZUFnE/EkIGqENBpcSxNl3yK25G/ndk/oa/uUXkzrl4Ag84Z3EiWFCSQxrjUfwvmB1yzalugp7zhF8VO6jx9qbTCEMgZ2gOdMiQRKRqscJs8e3m66OjN7TOUo+wMmSKMNz0jmd0PRa6vCJOMbpOGjrXeyO6Hn+6fg1S7WDsRKR1/TQkoIlaURn8Rf+Uan4aRyQwe/4PgFg9P4CkEWVLkAqe9SEAeS9S6eORry6GHi1NEQM7FgnT8fju4hp3q2FoN/uNWO3innFBFXmiyl+MA8tYY0WoGYvmWu1bsvzGIsSdgD6hcPmsIFLJpvqazHuU0YFoBF7lNLH2OqsGEuj766SFtnlyWwvBFEBCvOad/obuPzYoubZvt4UfMQv4L2FudMRpGF9RaXA6mhxifcB1SVHllTvQGXKJAXSZAfm7kfZFGKPPS51Ov3/SabdYHNqsIfBeVlu4GwdeR4e+ulsJYB9RjJSGpElmrwnqxDASMjJVRNMZXS5QmOMTJENj0mnAdxuQ+n3vOXvpikwLxB7FPCD1zVkd8h0LKHOJFaty1Ov2GgvXS0NqSDmusw3nTdtTr/n0km5T3UK8XfO25T6icLnJNTOH+0HMk4XWY13GIZqrhVPq3uJua3pwVhPfw8k53LbDfwiuEW7jtdq3AK6sD87qGrZCrpKcrr0xm1mXuOQwEKo2bGHfngWqbFjqtLAKpbXx3lo7Mniu/q1z5A3JoLZBWE8ZSs0BHWrXG1fbTNJ5iMxbL7f/q0vlJ26OPPKMto/ZQ2HjjITs2bHXyB3Wr+BFWPa6pEWcadrQ+wee+AKT94zbUH7P8ODjbH9X1ONLz7zwvsqL4i7RNp50ib24kgATkFhiZw7eMFe4W6bINkY0m347xrjn3gs51ZZc0mB7cVtL255k3xPIahV8AWPFIqz8Teqv5pIWlsxtL2LngtNCd6w3+oIlSj8mnFqcuKSJRV8rOtobtFXf+LwjIL3nXdaXW6xXsef+NevZjmT5nqTLkeBClmkidclSB9DQHOBduxOw2awhat7A9ClxWsF72AoBjfQIn/SofpcRK5Sb2CMGs3YMrsoYLBbpVqC7klGViXZ1Kpqv6+plXmvNzEGEoGQ2jvLdTMhxXeZTa7ouWhdvSlkkpXhbLH+ElD2A4+p7k23dr8brvlsNqH1INw1/xviSDF8wdr5tueM9ctxBdJtSnan+uJNcR1y2rk7yL/nDPC63IfFoEDi79q9fdlr0dbOgUcDbHb57HyMsuo+pD5dLRHKdMzllUwslE62lEPYSUOMIy/NzU747ZQfHCcUS9Epst2gDqwTN8ypc0zackQKArpLJ386qZoim6j6j9/nr3e31+Msna7ApGDP/e/kmuE9jfUQgaPCWt7Du16ByGlXdwLyXZ3Rclm0Ru0KvfDRW3ZC6+QJoADMWQeBY7f0N43UAZcOoavuM6m2kmRThqNRU03myqXGPVlpLal2LuCLgMGrcbREyyWLwbi6vJt9GN+PRv6qWKovQFuU3tjd2Rg5/GXpHJ83psiNmup1GuBvyNj9cwBwBJU7bnNu2oGu7qLmjXIjv56qu2vjx3Q8qdusnqNLiHA3zy6T2byuIiX7izfDF4lSpR7Ln99744vLLZDz5T+7Yezx3PlaaHPRhnwjBn6j8mCqFZ66XQBSQBfC45xJ7Em2c+fi4F9x0s53C9EymiUJbupwqw2AH2yznWu8BZQ5Kd8RfBdIrfjGAgMSYYMOEoA+In0qpHx5FT137q1fi07ET1/oLxdksKDWmgMm8qVBxWVKNLY2r+TS2Z7gBEu/L6TSn71r1w/jysbXgStAoLfzJs4lw2pP6E6ArdFGjUR9viSrdZSuXi7Wnbe1bWtZBezHdfbfDpJAMXV2a7AJlgFln7oJlueq4KmLWRdyOzPzSE+80mMZ1SzjKGqPtutddxCCVpR/0iW1xrE3dVFJw1LOH4cA9OE1UxuFDPvlPFuobRv9O5XjeQEEY6+5NMnhK/e+gPD8xl+jpoBQ6DdiSsOBsetD6aW16QHxOkwRnZinn9+wFpgcfTgfI3xDDchqr4flXrDw4zTTL4ujDTU70PO90gMNNKZWHb03jnw)

![weasel_shit](https://user-images.githubusercontent.com/5395255/66693154-cc084900-ec73-11e9-90e0-f3182d3a6e79.png)

The above Sandcastle computes UVs using depth from just drawing a Rectangle geometry, this is _NOT_ going through our depth packing code or even using a depth texture. The shader splits the display to show computed UVs on the bottom and a diff between depth-by-varying and depth using `gl_FragCoord.z`. As you can see, in the iOS example there's always some discrepancy in the diff, which occasionally leads to mangled texture coordinates, which is easier to catch when the camera is moving. Granted, the diff has been multipled by 1000 to be visible, but on other platforms there's no difference shown even with that multiplier. Here it is on my Adreno 308 (Qualcomm 425) smartphone:

![Screenshot_20191011-221337 (1)](https://user-images.githubusercontent.com/5395255/66693215-a3348380-ec74-11e9-923f-0068c7a37580.png)

**Comment by likangning93** [comment]
> depth interpolation on these devices is inaccurate

I put together a small example of this here: https://likangning93.github.io/webgl-examples/tests/depthPrecision/, code at https://github.com/likangning93/webgl-examples/blob/gh-pages/tests/depthPrecision/webgl-demo.js.

Similar to the above, the right third of the webgl display here is a diff between depth-by-varying and `gl_FragCoord.z` multipled by 1000 for visibility. Here's what I see on our first-gen iPad Pro:

![Image from iOS](https://user-images.githubusercontent.com/5395255/66693674-6a4add80-ec79-11e9-8b39-050b72db94d3.png)

The red bands indicate a discrepancy here across the depth range.

For comparison, here it is on my Qualcomm 425/Adreno 308 Android device:

![Screenshot_20191011-224641](https://user-images.githubusercontent.com/5395255/66693679-7fc00780-ec79-11e9-8960-2c3a4d51335a.png)

**Comment by likangning93** [comment]
Posted to the webgl dev list: https://groups.google.com/forum/#!topic/webgl-dev-list/O34GBqZBfmk

**Comment by xinaesthete** [comment]
Really encouraging to see some activity on this, good luck @likangning93

**Comment by lilleyse** [comment]
I'm testing https://github.com/CesiumGS/cesium/pull/9064 this on a Lenovo IdeaPad Duet Chromebook. Good results so far. There's subtler discontinuities on frustum switches but it's so much better than before. I tested every Sandcastle in this issue (@likangning93 whew -- lotta work went into this github issue).

Note: I don't see the banding artifacts in https://github.com/CesiumGS/cesium/issues/6735#issuecomment-541276819 so this device must have good enough depth texture precision. Need to test on the iPad pro next.

**before**
![polygon-bad](https://user-images.githubusercontent.com/915398/88739754-4e7dce80-d109-11ea-81b0-fa988bb92298.gif)
**after**
![polygon-good](https://user-images.githubusercontent.com/915398/88739756-4f166500-d109-11ea-9bdc-e3700470cb3d.gif)

**before**
![flicker](https://user-images.githubusercontent.com/915398/88739761-52115580-d109-11ea-86b1-9433ec1d9975.gif)
**after**
![flicker2](https://user-images.githubusercontent.com/915398/88739763-53428280-d109-11ea-9c43-db79be403365.gif)

**before**
![2018-06-27](https://user-images.githubusercontent.com/5395255/41983153-3d2322d2-79fb-11e8-878d-4e92ddebcbed.jpg)

**after**
![ezgif com-optimize](https://user-images.githubusercontent.com/915398/88739805-7705c880-d109-11ea-8b60-3d4e0a3ee156.gif)

**Comment by dennisadams** [comment]
@lilleyse I hope the polylines gifs got mixed up.

> There's subtler discontinuities on frustum switches

I've also noticed some frustum artifacts in entities and in classification.

**Comment by dennisadams** [comment]
Before:
![Peek 2020-07-29 16-27](https://user-images.githubusercontent.com/29460712/88807035-db806080-d1b9-11ea-8257-47d499003a28.gif)

After:
![a](https://user-images.githubusercontent.com/29460712/88807992-fa332700-d1ba-11ea-9591-b88fbb3eb897.gif)

Certainly better, but still has a problem on the frustum split . Notice the discontinuity on the polyline too.

**Comment by lilleyse** [comment]
@dennisadams that's a different issue that @IanLilleyT started looking into: https://github.com/CesiumGS/cesium/issues/8953.

**Comment by lilleyse** [comment]
Better view of the frustum discontinuity on an ipad 4:

![developmentGround Polyline Material - Cesium Sandcastle](https://user-images.githubusercontent.com/915398/88851963-8f362000-d1bb-11ea-97cb-d9944e7c16a6.png)

**Comment by dennisadams** [comment]
> @dennisadams that's a different issue that @IanLilleyT started looking into: #8953.

Actually this bug appears to predate #8953 as described there. 
Also, I don't see any artifacts in that sandcastle (`3D Tiles Photogrammetry Classification.html`) which is classified by a 3D tileset, compared to the one I mentioned (in `Classification Types.html`) which is classified by a polygon. 
I'll try to do some more debugging if I have time.
