### ISSUE TITLE
Terrain Rendering Glitch with WebGL 2

### ISSUE THREAD

**Issue by ProjectBarks** [CesiumGS/cesium#6756]
Using the latest master branch with cesium there appears to be a significant rendering bug causing terrain to disappear at certain angles and and be occluded with black artifacts at high zoom levels. This seems to be across chrome and firefox. [Video of problem](https://drive.google.com/file/d/1uhndQk5V_pjl8YnmP4rU-Oy9O9VYrvLn/view?usp=sharing)

When directly comparing 1.46 and the current master branch this becomes very apparent. This most likely has to do with texture/terrain replacement requests as the more parallel http requests occurring the frequency of artifacts increase.

**Comment by OmarShehata** [comment]
The video link seems to be broken? (gives me a 404)

**Comment by ProjectBarks** [comment]
@OmarShehata Updated!

**Comment by hpinkos** [comment]
Hello @ProjectBarks, thanks for sharing that video.  I was able to reproduce this in master using the following example:

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    contextOptions: { requestWebgl2: true },
    terrainProvider: Cesium.createWorldTerrain()
});
``` 

We're working on enabling WebGL 2 by default, and we'll fix this as part of that effort.  We have an initial pull request open here: #6314

Thanks!

**Comment by lilleyse** [comment]
It looks like the problem is log depth related, and the problematic PR is https://github.com/AnalyticalGraphicsInc/cesium/pull/6701. I thought maybe `modernizeShader` was doing something wrong with shader translation but it looked fine.

As a workaround, set `viewer.scene.logarithmicDepthBuffer = false`

**Comment by lilleyse** [comment]
See https://github.com/AnalyticalGraphicsInc/cesium/issues/6714#issuecomment-402299813 - it might be the same problem with `DISABLE_GL_POSITION_LOG_DEPTH`.

**Comment by OmarShehata** [comment]
I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap, so we can consolidate known bugs and discussion in this issue: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407.
