### ISSUE TITLE
debugShowGlobeDepth and debugShowPickDepth are broken

### ISSUE THREAD

**Issue by likangning93** [CesiumGS/cesium#6763]
Using `CesiumInspector`
* Show pick depth doesn't seem to do anything
* Show globe depth draws "clear" instead of the globe depth

These options have been temporarily removed from the `CesiumInspector` UI until they are fixed #7014

**Comment by mramato** [comment]
By dating back to, do you mean these happen in 1.46 as well?

**Comment by hpinkos** [comment]
Globe depth and pick depth broke in 1.45.  Probably related to log depth changes.

The frustum bug is a known issue: #6187

**Comment by hpinkos** [comment]
Hid these options from the UI in #7014

**Comment by hpinkos** [comment]
Related #5965

**Comment by ebogo1** [comment]
The code for debug globe and pick depth was removed in https://github.com/CesiumGS/cesium/pull/9965. Those commits can be reverted if this is fixed.

**Comment by ggetz** [comment]
Closing this. If we get further requests or have another reason to put this options back, we may re-open.
