### ISSUE TITLE
3d tileset basePath behaviour is incorrect on Windows

### ISSUE THREAD

**Issue by stuarta0** [CesiumGS/cesium#6776]
In our electron app on windows we were running cesium 1.44 and specifying 3d tilesets based on directory alone; e.g. "C:\gis\tiles\". In 1.44 it would tack on the "tileset.json" filename and use the url given ("C:\gis\tiles\") as basePath. Base path would then be used to resolve each tile path.

I'm trying to upgrade to 1.47 where it enforces supplying the full path to the tileset json. We're still using the convention of tileset.json so my path would now be "C:\gis\tiles\tileset.json". This fails in both 1.44 and 1.47 for the same reason: [a different conditional is fired](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.44/Source/Scene/Cesium3DTileset.js#L698-L708) which calls ```getBasePath``` on the tileset URL, which [checks for the last forward slash](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.44/Source/Core/getBaseUri.js#L34) and truncates. 

When using ```path.join()``` on Windows, the path will contain the system separator (backslash) and ```basePath``` becomes an empty string.

My current workaround is ```path.join(...).replace(/\\/g, '/')``` but I'd rather it were fixed in the core library. I'm not submitting a pull request as you'll be more aware of the ramifications of the change.

**Comment by lilleyse** [comment]
Thanks for the bug report @stuarta0.

@OmarShehata would you be able to check this out?

**Comment by mramato** [comment]
Cesium expects URIs, not file paths.  It's a common problem to conflate the two.  I'm actually surprised this ever worked.  I think handling the replacement yourself is actually the correct fix (and prepend `file://` to the path as well, i.e. `file:///C:/directory/tileset.json`

I don't think trying to officially support non-uri paths is a good idea (or a winnable battle), but if there's a definite bug somewhere in here, we should look into it. At the very least, we may be able to add better error handling.

CC @shunter What do you think?

**Comment by shunter** [comment]
Yeah, browsers work with URIs not paths.  File URIs should be used in all cases.  We should be very clear about that in the documentation, if we're not already.

**Comment by stuarta0** [comment]
One interesting behaviour I've noticed using the ```file://``` scheme with 3d tileset is this:

```javascript
const url = 'file:///C:/directory/tileset.json';
const t = new Cesium3DTileset({ url });
// t.url = 'file:/C:/directory/tileset.json'
// t.url !== url
```

It doesn't seem to affect cesium loading the data, but the url is not as expected. It seems because authority is parsed as empty string, the [Uri.toString method omits the double forward slash](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.47/Source/ThirdParty/Uri.js#L264) and just concats scheme + ':' + path + etc...

**Comment by shunter** [comment]
As far as I can tell from reading the spec, `file:/C:/directory/tileset.json` and `file:///C:/directory/tileset.json` are both correct, and are equivalent.  Authority is optional in URIs, so the first omits authority while the second includes an empty authority.
