### ISSUE TITLE
Zoom bug in orthographic 3D mode

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#6865]
Brought up on the forum: https://groups.google.com/forum/#!topic/cesium-dev/hBNRZ69Tx20

Using the scroll wheel to zoom moves the camera the wrong way at first

```js
// Power Plant design model provided by Bentley Systems
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.scene.camera.switchToOrthographicFrustum();

var tileset = new Cesium.Cesium3DTileset({ url: Cesium.IonResource.fromAssetId(3837) });

tileset.readyPromise.then(function(tileset) {
    viewer.scene.primitives.add(tileset);
    viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0.5, -0.2, tileset.boundingSphere.radius * 4.0));
}).otherwise(function(error) {
    console.log(error);
});
```

**Comment by hpinkos** [comment]
Zooming also causes the terrain to disappear at the bottom of the screen:

![image](https://user-images.githubusercontent.com/3451886/43484773-4dbcfdf0-94dd-11e8-9117-1bba531bf459.png)

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11206
