### ISSUE TITLE
Geocoder summary documentation is incorrect

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#6870]
It currently says:

> A widget for finding addresses and landmarks, and flying the camera to them. Geocoding is performed using the Bing Maps Locations API.

Since this was written, the geocoding type is has been made configurable and it also no longer defaults to Bing (it uses Cesium ion instead).

We could probably expand on the documentation summary a bit and just remove the last sentence.

**Comment by OmarShehata** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/8783
