### ISSUE TITLE
Expression 'evaluate' functions should not pass frameState paramter

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#6874]
In the [Cesium.StyleExpression](https://cesiumjs.org/Cesium/Build/Documentation/StyleExpression.html) page, the `frameState` description isn't very descriptive. Clicking on it to find out more goes to:

https://cesiumjs.org/Cesium/Build/Documentation/FrameState.html

Which is a 404.

**Comment by mramato** [comment]
`FrameState` is a private class, so it's not supposed to be documented or mentioned in the docs for that matter.  So the problem here is in `StyleExpression`, not FrameState

**Comment by ggetz** [comment]
Fixed in #6890
