### ISSUE TITLE
[npm] Deliver new Build for websites with HTTP/2

### ISSUE THREAD

**Issue by SunBlack** [CesiumGS/cesium#6886]
If you currently install Cesium via `npm install cesium` you got two directories in Build directory:
* Cesium: Containing combined and minified Cesium sources (3MB Cesium file)
* CesiumUnminified: Containing combined but not minified Cesium sources (10MB Cesium file)

What I currently miss:
* CesiumHTTP2 (or something like this): Not combined but minifed Cesium sources (=> Source directory but minified each file separate). 

With this we could increase loading speed of page by preventing loading unnecessary data.

**Comment by ggetz** [comment]
This should be possible through additional tooling that uses treeshaking.
