### ISSUE TITLE
Mixed EOL characters in Cesium.js

### ISSUE THREAD

**Issue by fuweichin** [CesiumGS/cesium#6910]
There are Mixed EOL characters(CRLF and LF) in Cesium.js , both minified and unminified, which may cause potential issues, for example: in some text editor Cesium.js is rendered incorrectly before editing.

So Cesium developers can avoid the problem by keeping line-endings the same between files.

**Comment by ggetz** [comment]
Thanks @fuweichin, this should be solved since [the introduction of prettier](https://github.com/CesiumGS/cesium/pull/8744).
