### ISSUE TITLE
precision lost issue when using Float32Array

### ISSUE THREAD

**Issue by yaozhihang** [CesiumGS/cesium#6983]
It seems that `Float64Array` shall be used in the following code line, instead of `Float32Array`
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Workers/createVectorTilePolylines.js#L33
because `Float32Array` may lead to precision lost, such that the verticies of polylines cannot be placed on the accurate positions on the Cesium map.

**Comment by mramato** [comment]
Thanks @yaozhihang.  @bagnell can you take a look at this?  At first glance this looks like we are storing unencoded values so it looks like a bug.

**Comment by bagnell** [comment]
Vector Tile polylines are rendered relative-to-center. All of the positions are offsets from the `RTC_CENTER` or the tile region center. So there is no loss of precision and they are rendered accurately.

For more information about RTC rendering, see:
http://help.agi.com/AGIComponents/html/BlogPrecisionsPrecisions.htm

@yaozhihang, have you seen any precision issues?

**Comment by mramato** [comment]
Thanks for the test case @yaozhihang!  @bagnell any ideas?  Could the Float64Array workaround be masking a bug somewhere else?

**Comment by jbo023** [comment]
this can be closed, it is fixed with 
https://github.com/CesiumGS/cesium/pull/8658/

**Comment by mramato** [comment]
Thanks @jbo023!
