### ISSUE TITLE
Improperly clipped polyline

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#7072]
Using the callback property sandcastle: http://localhost:8080/Apps/Sandcastle/index.html?src=Callback%20Property.html

I'm seeing the line get clipped improperly:

![polylinebug](https://user-images.githubusercontent.com/1495196/46086692-a1d20f00-c176-11e8-867a-c5c38e2eecfe.gif)

**Comment by mramato** [comment]
May be the same issue as https://github.com/AnalyticalGraphicsInc/cesium/issues/6741#issuecomment-406717425

I'm marking this next release, but I mean Nov 1st since it's unlikely we'll be able to fix this for Oct 1st.

**Comment by shunter** [comment]
I'm seeing the same thing with CZML, so it's not related to callback:

https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/?source=https%3A%2F%2Fgist.githubusercontent.com%2Fshunter%2Fab554c40f21e4f6873b0e07725ea0302%2Fraw%2Fe89b5663f6ec59a38357dcf42e31497f06f67e5d%2Fout.czml

(turn off terrain and zoom to AGI HQ)

![capture](https://user-images.githubusercontent.com/32828/46978974-42449080-d09e-11e8-87d8-7d0ff0cd46c5.gif)

**Comment by shunter** [comment]
Visually it looks like the polyline is rendered behind the globe at low altitudes.

![capture](https://user-images.githubusercontent.com/32828/46979060-8afc4980-d09e-11e8-9b4f-c7ac7c6f2d08.gif)

**Comment by lilleyse** [comment]
Also https://groups.google.com/forum/#!topic/cesium-dev/NZwZnQnmC2U

**Comment by likangning93** [comment]
@mramato does toggling log depth get rid of the clipping? It seems to make a difference for me but I'm not sure if it's the same bug or something different.

**Comment by ggetz** [comment]
Should this be moved to `priority  - high` then?

**Comment by ngodichat** [comment]
Is there any update on the fix for this issue? I am still seeing this issue in the current version in SandCastle. Can you please give me some update? Thanks!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/NZwZnQnmC2U

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/7072 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
