### ISSUE TITLE
Polyline artifact with log depth off

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#7074]
This is a copy of https://github.com/AnalyticalGraphicsInc/cesium/issues/6741#issuecomment-408198164 since that issue has multiple bugs reported in it.

From @lilleyse 

Another polyline artifact but only when log depth is off. I wasn't able to git bisect due to unrelated shader errors but it seems to have been introduced with the log depth changes.

[Sandcastle link](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVLLbpwwFP0Vi01AogYGhkdCRk2nyz5GShWpKl14wAxWjY1sA5pE+feaxySEdtGyse49j3uuTYcE6AjusQC3gOEe7LEkbQ0fxp55lY/lnjOFCMPiyrrJWKc1MscMa8mkhWOpofGElJ+QIKqqSf4RN6r60JblOKBEVA60yeNIW7xHQvGTQE1F8rcJloj5zoO+l4Rx6HtRtEkCzw9t4MIwieOtG0deEAVhuAls4LvQvWQUuPhPey8OvDjW9pvZPfG2/tZ1ozjYJt6r++SPhOD9gUuiCGdS2//IGNDfXyZAxYdSA4iZ670t+990q32sjP18yULJ8jkwUzoUlhAVhfk0uTecnkfWNZg7U/cS/3q1j/1K6kmhKk3YuotmySnl/X0rSpQPpuPbLvAaKSwIohpaXPthTnE3zPo8Uw6CN1ios3m5AU65gPvvd1+sye85Y8/zvU8LPnJef+Pmal3rxrCNVKozxbtJ+J7UDRcKtIKaEDoK1w3VQ6VzbPNfWMFcysE3dS6itCAdIMVtZqz+/MwAOUVSaqRsKb0njzgzdqmj+W9klKOCsNPXDguKzgOl8nafpiaEMHV0+adKcU6PSCwcfwM)

![line](https://user-images.githubusercontent.com/915398/43281881-c8a878e0-90e2-11e8-92f7-3f90f8851f65.gif)

**Comment by kring** [comment]
I was looking at this one to see if it was fixed by #8600, but it appears to be already fixed in master. Closing.
