### ISSUE TITLE
VideoSynchronizer broken in Edge

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#7082]
At least the 'Clock synchronization' button in this example doesn't work anymore:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Video.html

Probably broken by #6789

**Comment by mramato** [comment]
I just tested this in master as part of the preUpdate changes @lilleyse put in.  What browser/OS are you using?

**Comment by mramato** [comment]
Just verified with head of master again and it works as expected for me.

**Comment by hpinkos** [comment]
Oh sorry, I thought I had tested this in a few different browsers.  But it looks like it's working in Chrome but not in Edge.  The 1.45 release seems to work in edge but the more recent releases do not

**Comment by jjhembd** [comment]
The example works OK in the current version of Edge. Probably Edge's switch to a chromium backend fixed the problem.
