### ISSUE TITLE
Distorted Box Entity in iOS

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7100]
This [Sandcastle example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=ZZFda8IwFIb/yqE3VujSug0GWmWz7mrCYBu76k3aHDWYD0nSOh3+96W2otMDCcnJ+z45OampgZrjFg2MQeEWMrS8kuT7mAt75XGbaeUoV2h6/VGuclV7l0E21T/e1doJKscdR0soY+FvrsCHohJhCL0PZFB48Za7FRSClmvQlROe2Ita5UZb79ZqeCogo8b5FVUPZGG0nOHSINrwbpA8kSSCx6SZ/dTvAA1+CN29TTAuUVmPtD5/8bIzOEzIfdSMwQnShKQODacCzqVooQ35eJ1dqLryvciZCm8Pjp5rxHT+kr210kOuDl0v2/bttZZfOmy72h8FUZBatxM4afXPXG60cVAZERISO5Qb4Qu1cVGVa3SktLbBpfHJlDJeA2fjPLj6wjyAUlBr/cmiEuKT7zEPJmns9f9sQlPG1fK9RiPorpGsBpN5mySEpLHf3rqc1qKg5oL4Bw) looks like a perfectly fine box on desktop:

```
var viewer = new Cesium.Viewer('cesiumContainer');

var redBox = viewer.entities.add({
    name : 'Red box with black outline',
    position: Cesium.Cartesian3.fromDegrees(-107.0, 40.0, 0.0),
    box : {
        dimensions : new Cesium.Cartesian3(0.2,0.2,1),
        material : Cesium.Color.RED,
        outline : true,
        outlineColor : Cesium.Color.BLACK
    }
});

viewer.zoomTo(redBox);
```

![box_fine](https://user-images.githubusercontent.com/1711126/46296692-f86d8d80-c568-11e8-8114-78bb2da610b8.png)

On iOS, the vertices seem to be displaced?

![distorted](https://user-images.githubusercontent.com/1711126/46296734-0b805d80-c569-11e8-8a23-733ca9ba01f9.jpg)

[Forum post](https://groups.google.com/d/msg/cesium-dev/8PX7fEE4lwA/z8NDEkwzAwAJ) tested on iOS 11. I just tested on iOS 10.2.1

**Comment by mramato** [comment]
I can confirm this is still an issue in iOS 12.0 on an iPhone 7, but someone should check iPad as well to see if it's software/vs hardware issue.

**Comment by OmarShehata** [comment]
I can reproduce this on the iPad Pro in the office, with iOS 12.2. This [forum post](https://groups.google.com/forum/#!topic/cesium-dev/bqiEt4oXAnE) may be the same issue. Here's another Sandcastle that, on desktop draws 20 lines:

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=bZLBTsMwDIZfxfRCx6p0gwMSKxPShAQSEkggOBAOoU03a2k8JVmngfbuuO0Q25gvTmx/f22ntXJQo15pB9dg9Qom2uOyEq9tLD7N2+uEbFBotTvtjaSVtmaqVO7R4RQtg8MBG5y1fgRpCvclhBl6MAwB+3ym7FQXEAhkdJSWUQLKeAJ8mhFDK3JzDzQ/kbYkB3EDIRezPkIG5+z7fexJ+y0tsDV5KkuvAxchpHApBm2vbbKdRmgbMKD2QhVFvOUaW5BZt51ewU60y3gmyHpOve+sZ6Jc4JOyFzEMoP83TgIwSHam62+b6iX7wnt2XHh4IDw8LvxxoFypoB0qwx3/apIhJ97u7l9u/0o33XHTPOimfdNuR19E1QvFBxvrjUDaKIkyH9ZGjzv2BqsFuQBLZ2Ih0qCrheGP+/Rzmc91ELn3jXqW/kJZgTVgcS2jg99KRpAb5T1nyqUxz/ilZTTOUq7fwwypAu30sdbOqHVTMhuOH7qgECJL+fqfCkTmU7kdxR8)

But on the iPad, only 4 lines are drawn. I haven't tried this myself but there's a suggestion in the forum thread there to modify the function in https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/translateRelativeToEye.glsl to add:

```
if (length(highDifference) == 0.0) highDifference = vec3(0);
```

Before the highDifference is returned to fix this issue.

**Comment by jjhembd** [comment]
Resolved by https://github.com/CesiumGS/cesium/pull/11788

**Comment by onsummer** [comment]
Reason here: https://bugs.webkit.org/show_bug.cgi?id=237434
