### ISSUE TITLE
Ground atmosphere breaks imagery on non-earth ellipsoid

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7124]
[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=bVLva9swEP1XjL/YgSA1+0HBc8NGGd2gY4WM9YuhnO2LrU2WhCTbZCX/+2TLbuK0+iL07t27p7vrQAfIOVNGsjK4CQT2wS0a1jbk6wzHm+v31x+urtYX9+pTJjqX34B60PIPFpZJsdS4Q1lpUDUrToz4pd4sUHGZ40XiAC2ZlI48YmrZ32nZivKLbaRRNeoheQ/coKN5SamsceBzJgJ3Fg6T5XPtKaN24q8JysHgPRxQP7DiL+rEl8jEcbLdMexRL33/HrE4KsbnrRQWmEAdrUdHqxd/rIEK9WGUH4x6LbKAHXnxJlCW3z3g7HesdIXOSj9i/gPUDnXHCrzkTY1oNQ+SIKqtVSahtMfc9YJwLQsCpiVYtjSafs+9NcfmrYCnHoqnoTnAZ4ICDQ1aT5r0h2M1COOCKKwLWN3O/RzOXuoGBjwav0aVqCIfPU4syzgT1a6osXHzeHOXfp1R4ufT/iZnq3xcnfTwkZW2ToKPm3dn4DdkVW1H1M10NcwmXIepsQeOW0/7zBoltR3aFhNCLTaKg0VD89ZthCWFGUea0jkpLVkXsPImCy8WIAuDgoMxLrJvOd+xf5iF25Q6/iKNSyjd3352qN0ABkq92d57kBCSUvd8nWWl5DnoM8X/).

The imagery flickers or just disappears if you zoom in. If you turn off ground atmosphere by uncommenting this line:

```
//globe.showGroundAtmosphere = false;
```

It works fine. This [came up on the forum](https://groups.google.com/d/msg/cesium-dev/xCYpXgNXyGM/ezCv3l8YAgAJ). 

@bagnell

**Comment by OmarShehata** [comment]
This was reported again here https://github.com/AnalyticalGraphicsInc/cesium/issues/8142#issuecomment-529447044 as a case of something that was working up to 1.49 and broke in 1.50 (when the GroundAtmosphere was introduced).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/xCYpXgNXyGM/ezCv3l8YAgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/7124 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
