### ISSUE TITLE
Expose globe._surface._tilesToRender

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7148]
The use case is getting the loaded `level` of the tiles, which was recently [rediscovered on the forum](https://groups.google.com/d/msg/cesium-dev/CmTu8CICUmo/ADerwio3BQAJ) and originally [posted here](https://groups.google.com/d/msg/cesium-dev/cIHbsAKnRa8/kg8x5PDPEAAJ).

If this is already possible to do with the public API please let me know and feel free to close.

**Comment by hpinkos** [comment]
@OmarShehata can you explain the use case for this please?

**Comment by OmarShehata** [comment]
@hpinkos it's described in more detail in the first linked thread, but basically if you want to hide a datasource when a certain level of imagery loads (because you're using a GeoJSON as a base map and there's no way to put entities under imagery).

The other thread seems to just be requesting additional information from their server based on what's in view.

**Comment by OmarShehata** [comment]
I think the original use case here or figuring out the level doesn't really work, since there's no consistent "level" a map has in 3D in the same way there is in 2D (like a horizon view will have levels that are high close to the camera and low level tiles far away).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/CmTu8CICUmo/ADerwio3BQAJ
https://groups.google.com/d/msg/cesium-dev/cIHbsAKnRa8/kg8x5PDPEAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/7148 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
