### ISSUE TITLE
Camera picking doesn't work when globe is off

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7171]
The context for this is trying to view a model with the globe turned off. See [this thread](https://groups.google.com/d/msg/cesium-dev/fbDaRU9xIPI/FFTJQynCDAAJ) for more background. 

The problem starts with the fact that this particular model is not on the surface of the earth. But this is actually not a problem when the globe is turned on. 

To see what I mean, go to this [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVVbT9swFP4rVveQdEqdcpOmUtAGTGLSuAjYnvriJKeph2NHtlNaJv77jpM4Tcq0p6VF5Ny+7/hc3DXTZM3hBTQ5IxJeyCUYXhX0Z60Lg7QWL5W0jEvQQUR+LyTBJ45zoRIgM7JkwsBCvo1PF9J91i3kjcpAIGobsAKer+yMTNG19myZnqVKn1VlqdUsfQ67yAbOgVmlRMJcgplKqwKkpTnYrwLc68X2WxYGrUvggvZxWVmK7QWXGZe52eFHHrdHxAUYsMNKNP+Orp4aY9gep9JiRgJK4+77pSxN/MiKUsAVsyweBMZtePcSt2T0l1Ey6MrntRpYtr3XquAGqF2BDJeVTC1XMmxdxr6wTfuoSUECLTUvuOVrMJRlWed7OnB9Vap4Ut4Y9U97jbxYp3tu09UDkzmEUzqNyGRKTyJfH5qoqq7mY7kCDVRjSGXIR3JIp2NH9TamCnPWL5j8Lm/QWuku61RJowRQofLWctoVYb+D2O27xIBes0RAv4NBM1TBmJoqManmSY+vsY2H84e9va2KBEe7NbeV4UsScnPLbr2+i3OPBltp2bq+uRTrauLIpExblWtWrniK2H5melq6xC46BZpY1739GmLzLOiuT4hsKr1kKQxBa4yjGvIBq86kCfsZYDVlzm2VQUSGemZbNbazz6KWy2bi/yvJsLb1ammEcQ5K/pUM++f234ZNQpE//mA4d/7h2IP7ehZuIm6Y1XyzI2jk4/ooT7sMwl42vbEbRaO5sVsB5w30Z16USlu36iHutwVcbYYJxEmVPiNlaozP4oO/o3pDk+B1lmvX5hnRecLC48OI+L8p/eRj3VPisuIwzMhxuempE6Uz0JNmwfrGtz1aLsvK9snXoC1PmZgwwXM5IwXPMgHvGSdWlTNyOGD1pkRZq4q+FWnnsS/RPONrwrOzxWjvR2IxIqlgxqBlWQnxyF9hMTqfx+g/CBOqvmvuMFfBts5ldXD+vVFSSucxiu+j2iOje5OTs5xf1wPnnWt1UxK7LQGDtLvKMK+CS5QmB1NcAyeyDYon01Y0FkqUD/A1wxt8kuCPBsprJiqYtUMdkVr8UaIHKoOaJthlM6C1sLEOFyvgeP6FWyP4A/wB). Use the slider to move the height of the tileset way up. You can still move the camera just fine if you click onto the tiles and pan/rotate. If you miss and click on the background, it moves too fast and you'll probably lose the model.

But if you turn the globe off, you'll see that even if you do click on the tile itself when panning/rotating, it behaves as if you're clicking on the background. 

For people using Cesium to view 3D Tiles without the globe, I think this can be really annoying. I'm not sure if there's an easy fix that the user could do (couldn't figure out an easy way to push the model to the ground, or if this camera behavior is intended).

**Comment by hpinkos** [comment]
@OmarShehata for this case, the user will probably want to implement their own camera controls. See this tutorial: https://cesiumjs.org/tutorials/Camera-Tutorial/

**Comment by OmarShehata** [comment]
I'm running into this again with an NYC tileset. Testing without the globe on makes orbit controls and panning really hard.

**Comment by OmarShehata** [comment]
I keep running into this. Right now it's a tileset that happens to be underground, and is moved with a modelMatrix above ground. For debugging purposes, I need its modelMatrix to be identity, so I turn off the globe to see it, but then suddenly it's very difficult to maneuver the camera.

I also run into it whenever I want to show a high resolution tileset, where the terrain/globe doesn't matter, so I turn the globe off to speed things up/reduce network requests, but then again, I suddenly can't can't click and drag around as easily anymore.
