### ISSUE TITLE
Make unit tests on Appveyor pass undere IE11

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#7241]
You can view our appveyor builds here: https://ci.appveyor.com/project/AnalyticalGraphics/cesium

IE 11 currently has ~15 failing tests, but that may change by the time we look more into this.

Once all tests are passing, we should add back `--failTaskOnError` to the test CLI command in appveyor.yml so we don't break it in the future.  Currently IE11 failures do not fail the build

**Comment by ggetz** [comment]
Closing since IE11 support has been dropped.
