### ISSUE TITLE
Disable SceneMode picker in Terrain Clipping Planes demo

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#7370]
Since clipping planes don't work in 2D and CV, we should disable the mode picker in the demo: http://localhost:8080/Apps/Sandcastle/index.html?src=Terrain%20Clipping%20Planes.html&label=All

**Comment by mramato** [comment]
This is as simple as setting scene3dOnly to true in the Viewer contructor.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/8087
