### ISSUE TITLE
Default Sandcastle to 3D Tiles tab/example

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#7462]
via @GatorScott and 👍 from me.

Given the importance of 3D Tiles, perhaps Sandcastle should default to the 3D Tiles tab at the bottom and/or a 3D Tiles example.

**Comment by ebogo1** [comment]
This might still be a good idea but the "3D Tiles Interactivity" Sandcastle isn't necessarily a great first impression of what Sandcastles can do. One fix could be to write an updated and simple Sandcastle with more than a blank globe that's easy enough to understand.

**Comment by ggetz** [comment]
Closing as we'll want to curate a helpful selection of example for the first tab.
