### ISSUE TITLE
Incorrect decoding of draco model with high quantization bit number

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7471]
This was reported [by Chris Wang on the forum](https://groups.google.com/d/msg/cesium-dev/x_GU7yw0lTw/TJyW75ZeDAAJ). 

The glTF file attached [in this post](https://groups.google.com/d/msg/cesium-dev/x_GU7yw0lTw/3kDUYfV4DAAJ) was encoded with the following Draco parameters:

```
sOpt.pos_quantization_bits = 20;
sOpt.tex_coords_quantization_bits = 15;
```

And renders incorrectly in Cesium. Here's what it looks like in Bablyon:

![babylon](https://user-images.githubusercontent.com/1711126/50790876-252ef080-128e-11e9-8c67-426e21c315ff.jpg)

And in CesiumJS:

![cesium](https://user-images.githubusercontent.com/1711126/50790863-1cd6b580-128e-11e9-84a4-a04e8c455079.jpg)

@lilleyse believes this might be because the quantization is hardcoded in a few places in our Draco decoding.

**Comment by lilleyse** [comment]
> @lilleyse believes this might be because the quantization is hardcoded in a few places in our Draco decoding.

Specifically I wouldn't be surprised if UNSIGNED_SHORT is hardcoded somewhere.

**Comment by wangzhongliang** [comment]
@lilleyse Hi Sean, will this be fixed soon? if not, can you tell me where is possibly hardcoded, so that I can fix myself.

**Comment by wangzhongliang** [comment]
When I set dequantizeInShader to false, the model is not distorted, and displays well. 
Hope it will help.

**Comment by lilleyse** [comment]
This also came up in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/511

**Comment by lilleyse** [comment]
Opened an issue in the Draco repo about whether it's possible to query the quantization bits without decoding to quantized form: https://github.com/google/draco/issues/573

@sanjeetsuhag and I talked offline - if there's no way to do it in the API, we'll need to dequantize in our own code.

**Comment by Ben-Mack** [comment]
@lilleyse Has this bug been fixed on the latest Cesium?

**Comment by lilleyse** [comment]
@Ben-Mack, no, still an open issue

**Comment by lilleyse** [comment]
Came up again in https://github.com/CesiumGS/cesium/issues/10977

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/10979
