### ISSUE TITLE
Broken link to terrain formats documentation

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium#7478]
The constructor doc for [CesiumTerrainProvider](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/CesiumTerrainProvider.js) has a broken link to the documentation of the terrain formats it supports.

This is the broken link:
https://cesiumjs.org/data-and-assets/terrain/formats/

I can't seem to find the updated URL, otherwise I would have just opened a PR for this.

The two supported terrain formats are meant to be "open" so that other tools can produce and consume them, so it's pretty important that the documentation be available.

**Comment by hpinkos** [comment]
@kring maybe just point to the specs?

Here's the one for quantized-mesh: https://github.com/AnalyticalGraphicsInc/quantized-mesh
Do we have a published spec for `heightmap 1.0` somewhere?

**Comment by hpinkos** [comment]
It looks like we don't.  I threw up the content of the old page here: https://github.com/AnalyticalGraphicsInc/cesium/wiki/heightmap-1.0
