### ISSUE TITLE
Particle texture visible behind globe when zoomed out

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#7511]
What's going on here?  Load the example below and zoom all the way out.

![image](https://user-images.githubusercontent.com/3451886/51699261-4c015c80-1fda-11e9-8408-a6ba8b4a8be2.png)

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var scene = viewer.scene;
var particleSystem = scene.primitives.add(new Cesium.ParticleSystem({
    image : '../../../../Apps/SampleData/fire.png',

    imageSize : new Cesium.Cartesian2(25, 25),

    emitter : new Cesium.CircleEmitter(2.0)
}));
```

**Comment by OmarShehata** [comment]
Reported again in https://github.com/AnalyticalGraphicsInc/cesium/issues/8408.

**Comment by hpinkos** [comment]
The texture also shows up in 2D, as per https://github.com/CesiumGS/cesium/issues/8654

**Comment by hpinkos** [comment]
Also reported https://github.com/CesiumGS/cesium/issues/9253

**Comment by Lemonjay** [comment]
![image](https://user-images.githubusercontent.com/9245295/174467541-7a5278b1-c8cf-4548-aac2-4028b7e5127e.png)

BUG: the texture shows in Scene2D
How to solve this bug ?

**Comment by ggetz** [comment]
Reported on the forum: https://community.cesium.com/t/particle-system-on-flat-projection/19454/2
