### ISSUE TITLE
Imagery Layers Sandcastle fails to load Bing Maps Road

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7524]
Go to https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers%20Manipulation.html

Click "Bing maps road" from the drop down. Observe the blue globe. Observe:

```
An error occurred in "BingMapsImageryProvider": An error occurred while accessing https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Road?jsonp=loadJsonp622672&incl=ImageryProviders&key=undefined.
```

I think that Sandcastle just needs to be updated since it works fine if you go to any Sandcastle and select Bing Maps Roads from the imagery widget?

**Comment by mramato** [comment]
This is because it's using BingMapsImageryProvider directly (and there's no BING key embedded in Cesium).  The example should just be updated to either use ion or remove that particular provider.

**Comment by abuDarda97** [comment]
Hi @OmarShehata I can work on this issue, where is the file located?

**Comment by OmarShehata** [comment]
@abuDarda97 this can be another easy fix - just go here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/gallery/Imagery%20Layers%20Manipulation.html#L118-L121

Replace that section with ion imagery, which can be created using `createWorldImagery`. An example of that here: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers.html

Then just double check it looks the same as the default imagery in Cesium, and open the PR!

**Comment by mramato** [comment]
Cam up again here: https://github.com/CesiumGS/cesium/issues/7128#issuecomment-629031364

Our examples should be the last place we let trivial bugs linger, it would be good if someone opened a PR to fix this.

**Comment by NaorYael** [comment]
In my case the key expired, try generate a new one
