### ISSUE TITLE
High Resolution Photogrammetry in Sandcastle

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#7532]
It'd be nice to find a higher resolution photogrammetry model to use for Sandcastle examples.
Then the `Polylines on 3D Tiles` photogrammetry example should be updated.  Also probably update the examples for sampling and clamping to 3D tiles.

cc #7522

**Comment by outsider787** [comment]
Are you still looking for a higher resolution photogrammetry model?
I may be able to provide a model Cesium could use.
