### ISSUE TITLE
Terrain exaggeration causes incorrect vertex normals

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7580]
This was [reported on the forum](https://groups.google.com/d/msg/cesium-dev/H4NSHaavEdM/a8HQufXhAwAJ). 

Supplying a `terrainExaggeration` seems to scale the normals incorrectly, causing the terrain to look washed out.

Here is with `terrainExaggeration: 1`:

![no_exaggeration](https://user-images.githubusercontent.com/1711126/52970067-89aa9880-3380-11e9-89ca-c6dc6147de94.png)

With `terrainExaggeration: 2.5`:

![exaggeration_1](https://user-images.githubusercontent.com/1711126/52970072-8ca58900-3380-11e9-99b4-18e783deec2b.png)

With `terrainExaggeration: 4.5`:

![exaggeration_2](https://user-images.githubusercontent.com/1711126/52970075-90391000-3380-11e9-963f-478f930da4ec.png)

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=jVNdb9owFP0rFi8EKXW+CWG0GmorDantqsL6lBeTXIg1x85sJ5RO/e8zgaxh3aT5xfbNufeenHvsOOgL3RZIghKs1lRwpEFKQjkSG/QInKs9awinBGW1JBpytN6fx5cV0ZQwdEM0QfMsA6WQ9Thf3sxHKXccVGhdTR1nt9vhiqic4ErVGPLaSXlDJGoo7ECiS8Rhh65B0brEz23MGmbt9VpwbQiBHNroZ8qRWSeOj1I0NAc57Scft9U5wjolHlYt2bQDLwR/Mr9eywzwRopyrhToRW4FSRSP7PccCT9qUPoZpIaXByFLwhSaIi1rOILeOjQtyRbk/p3aqVMmwci3ogzuSbUE2dAMFufYPsn+6hNe15Tl9yKvGXyTzBq2hJWzghddmyE6D8TshN0SqYvFYjj6WPE305OIty9ka1iQdvhT5OMo5W+jTyk382nngFUGHHBGSoPCG7ZfiY5pbjShvEvtBmB6mxPhQSvpDWwlgLIu4ggnnhsGiY1CF4+9MIoDG3mR6x4YGaf8Z8EnkpuzKejhIPDD0Is8z53EoT8Z28gUTqLQ98PAj/w4ScaxjfxgjMdx7I4nSRJG7iTsFBCSgvHWqVtP/QJMD759p3BPdIG16FoHntt3R0V1VvwTfOFFZ1YSjBmsi92Tc/4u95aJNWDgZM3gzjxRfeBz2TquBQ/swUzpPYOrY5nPtKyE1AezWBg7GsqKGcMpZ11n30HjTKlDl5nTJc1y2iCaX6aDP55ZOkAZI0qZL5uasSV9hXRwNXMM/iyNiVakrw1IRvYHSOFd3R2DGOOZY64fs7QQbE1kr+Iv).

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/H4NSHaavEdM/a8HQufXhAwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/7580 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
