### ISSUE TITLE
Self overlapping polygon incorrectly shows through globe

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7604]
If you have a polygon that wraps around the globe, you'll be able to see it through the globe in areas where it overlaps itself, even when `viewer.scene.globe.depthTestAgainstTerrain` is true.

The tip of this polygon is on the other side of the globe:

![self-translucent](https://user-images.githubusercontent.com/1711126/53570898-958f1b00-3b35-11e9-9571-55adf7a733e2.png)

If you rotate the view, you can see that it is correctly occluded by the globe if it is not self overlapping:

![tip](https://user-images.githubusercontent.com/1711126/53570942-ac357200-3b35-11e9-8a50-c8be33762feb.png)

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=ZVJRT9swEP4rVvbQVAoOKewFQrW2PDAJNDTKXpY9uMk1sXDs6OykC4j/ziUhLB2ybPm+O3+f77MbgayRcABkV0zDgW3Ayrrkv3rMn6V9uDHaCakBZ8FLohkTWpbCSaMv2F4oC0EHGswAv+sMKqBFuy0KbVWdgk7bad1OWLgVLeC9TJ8ApyknS1CkM8Wk3pu1+TuFClPCunbuWD8Hk5rsmNCSOtwR+llrXytlUwTQR1SJfp1fJrobDXnjUJIxg0OcmpJOguUiy/zeiMqoNjeaXbA+pKtJQIFp0RI0sfN+qLsZs/5Qzcb8RqCjndBnfI+mvIacLmZXiKL1f0enAftK8yTq1sX7PDk7/zMfaebBsKNXAZRCkfrIbJTBnnRjbR88UE8692dfFtH6fBHN5vwgXbFSVSH8Ux6NVHTPbVvBP6bVAPCfN493667m9cOrd396t3muzA44fQNXbMG6VU4/x7otUDNSk5kOa7j0Ai+2rlWwHNS+ybIy6FiNyuc8dFBWinqx4a6mh3M8tbaTisPxUJzJhsnsKvH++6KJx1IlrKVM98QP8hkSbxmHVH90TBmRkQ8/GkAl2q6kiJa3A8g5j0MKP59yxqidwAnjGw)

Forum thread: https://groups.google.com/d/msg/cesium-dev/hv4L3eq4Ny0/Ut6Kp4efBgAJ

**Comment by hpinkos** [comment]
Thanks @OmarShehata.  Looks like it's a problem with `GroundPrimitive`.

**Comment by Sparviero-Sughero** [comment]
any news about that?

**Comment by hpinkos** [comment]
@Sparviero-Sughero sorry, we haven't had a chance to look into this one yet.  If you have time to find a fix, we would be happy to review a pull request!

**Comment by ggetz** [comment]
I can no longer reproduce as of Cesium 1.107.
