### ISSUE TITLE
Can 3dtiles support custom shaders?

### ISSUE THREAD

**Issue by AstrosChen** [CesiumGS/cesium#7652]
When I looked at the api, I didn't find that [Cesium3DTileStyle](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileStyle.html?classFilter=3dtil) supports custom shaders, or does 3dtiles itself not support shaders? Is there any other solution?

**Comment by hpinkos** [comment]
@lilleyse ?

**Comment by astoroschen** [comment]
hi @lilleyse , look here

**Comment by OmarShehata** [comment]
@astoroschen in general, no, Cesium doesn't support letting you override the vertex/fragment shaders in 3D Tiles.

Most common effects can be done with either the 3D Tiles Styling language, or [classification primitives](https://cesium.com/blog/2018/11/05/dynamic-3d-tiles-annotations/). There's also a PR open to allow custom uniforms in the styling language to make it even more expressive https://github.com/AnalyticalGraphicsInc/cesium/pull/5380.

If your tiles are b3dm (batched 3d models), this thread has some pointers on what you'd need to do to override the shaders. It involves modifying the source a bit:

https://groups.google.com/d/msg/cesium-dev/z7892t42q4M/xhN1_pyrFAAJ

Can you tell us a bit more about what you're trying to do?

**Comment by OmarShehata** [comment]
This is relevant, some screenshots of potential effects that might be hard to do just with the styling language:

https://groups.google.com/d/msg/cesium-dev/P7i9JVenzj8/JvLWlwsmBgAJ

**Comment by astoroschen** [comment]
> 这是相关的，一些可能很难用样式语言做的潜在效果的截图：
> 
> https://groups.google.com/d/msg/cesium-dev/P7i9JVenzj8/JvLWlwsmBgAJ

Hi @OmarShehata ，Thank you for your answer.
When I was writing the project, I noticed that there was such an effect on the Internet.
![tilesshader](https://user-images.githubusercontent.com/16367328/55393498-f3b58080-556f-11e9-8cab-9378b15d609c.gif)
I just want to use shader to achieve, the result is not supported.
So, After reading your answer, I feel that it is impossible to achieve the effect on the gif picture. I don't know if you have any other good methods. :)
sincere thanks

**Comment by OmarShehata** [comment]
Yeah I can't think of a straightforward way to do this right now with the public API in CesiumJS. 

We have been looking more closely at what it would take to support custom materials on 3D Tiles. There's no definite timeline on it though. We can keep this issue opened, perhaps labelled as "enhancement" ?

**Comment by OmarShehata** [comment]
I think this would be another good application of making an easier API for custom shaders. This [user on the forum](https://groups.google.com/d/msg/cesium-dev/usVaZRlrPf0/VoyxlvaBAgAJ) wants to be able to set a plane under which the model/geometry becomes slightly transparent:

![Transparent](https://user-images.githubusercontent.com/1711126/59373644-1acec200-8d18-11e9-9d71-f58e3b26393e.png)

The use case is to be able to see "pipes underground", and while a similar thing can be achieved with clipping planes, in this case it's helpful to have the geometry still visible but transparent.
