### ISSUE TITLE
Classification does not work on 3D Tilesets with transparent styles

### ISSUE THREAD

**Issue by likangning93** [CesiumGS/cesium#7753]
@lilleyse observed that Classification (polylines-on-terrain, polygons-on-terrain, etc.) don't work when applied to 3D Tilesets with a transparent style, likely because the 3D Tiles are rendering in the wrong pass.

[Here on Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=nVRdb9MwFP0rVnhIKgWnEyuIrRt07SYqMYbWwFNePOe2NTh2ZDspHdp/5yZx25SxF6xKrn3vOff4fqRmhtQCNmDIBVGwIVOwoiro9/YuCnl7nGrlmFBgwpj8zhTBJQq2ArP9anQtckSf7ZDcAHOQCgm3rFyAqQWH+bFz5DmaVRl5wD5UQua3Oq8kfDMyCifWgrNJCr9cZcAmXxjuTF4z49bzeTjoaJ5wfxqcZypTNT7HYWiEHb+n297M0s64U4DRz0hIabL/TcrSJgtWlBJmzLHkCJh4+P5P4oPRH1arcC9jd2vdVsLLQhaNeSeFa6kNimn3KAtevcd1c5MFMRnS0eBA3pWLWg4KaGlEIZyowVKW55EP3Dh6t0eti1T3DV2WDOT3wB1Tq1ah9waU7oQn88IUKwBLFN5DTpxhysoKQztk8PAw7hz3F+jdqzDX2uRCYVPYQ6X3senS6GIGKwNgo9fvRvTtySgmp0M6PI1Jd/bH0SA+kBZIZwTr9c60yRu9v57RjXDriSzXLGoS1wNxyawVS8GZE1ql2xJ68Gc2enWXfvIdtk/+gqmcM+tQOKYo1St8wlXlnFZR2CanZKZJTlt5nBZnKojJslK8oY34GvhPyAe7/PxPo/SaxdORDy+3Dfl3S53QYdNS3fic++cFcTBulVx2lo+iKLVxzZREOBoOcCqaMiYPFYZ1lFvbwMbJDjTORU1EfpEFf303sqBLPlqWlZQL8QhZcDlO0P8IJjXDVlnd1WAk2zYu65PLz90lpXSc4PE5ymktH5jpMf4B)

![DIGITALSTYLE](https://user-images.githubusercontent.com/5395255/56322721-d835a280-6137-11e9-816e-7692de163dd3.JPG)
![ohTehNoes](https://user-images.githubusercontent.com/5395255/56322723-d9ff6600-6137-11e9-841d-5a4aed800327.JPG)

**Comment by lilleyse** [comment]
3D Tiles might be able to use the saved derived command approach being done in https://github.com/CesiumGS/cesium/pull/8726

**Comment by lilleyse** [comment]
This was fixed in https://github.com/CesiumGS/cesium/pull/9399
