### ISSUE TITLE
Simplify model caching

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#7801]
Model.js has a global glTF json cache and a per-context WebGL resources cache. To help simplify the code we might want to consider using the per-context cache for everything. Some other things that could make the code easier to follow and less bug prone would be:

* Avoid saving pipeline extras on the glTF object (CC https://github.com/AnalyticalGraphicsInc/cesium/issues/7688)
* Have a separate file like `ModelCache`
* Simplify the interaction with 3D Tiles, especially with i3dm tiles.

But mainly I think the area just needs some cleanup, as it probably started out simple but has gotten more complex as glTF 2.0 and 3D Tiles happened.

**Comment by j9liu** [comment]
@lilleyse can this issue be closed now that `ModelExperimental` has replaced `Model` ?
