### ISSUE TITLE
Scene Transition between 2D and 3D

### ISSUE THREAD

**Issue by SurabhiJain** [CesiumGS/cesium#783]
In Cesium webgl when I select 3D view and zoom any place on globe at some extent, after that when I choose 2D view then entire 3D is converted into 2D map but my requirement is that:
1) it should converted from 3d to 2d as going in cesium andl 
2) that 2D map should maintain the zoom level of 3D from which I have selected 2D view

In brief "How to maintain camera position" during transition?
Some help will be great and much appreciated, please.

**Comment by bwyss** [comment]
Are there any future plans to address this issue? From my perspective a good solution would be to take a similar approach as Mapbox-gl
![2d-3d-transition](https://user-images.githubusercontent.com/340159/59124089-9cd37b00-8913-11e9-9e8c-8dace311dd8f.gif)
