### ISSUE TITLE
Pointcloud performance issues. 

### ISSUE THREAD

**Issue by ThornM9** [CesiumGS/cesium#7932]
Browser: Chrome
Operating System: Ubuntu

Code sample:
```
var url = <INSERT URL>;
var viewer = new Cesium.Viewer('cesiumContainer', {});
var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url: url
}));
tileset.style = new Cesium.Cesium3DTileStyle({
    pointSize:2
});

tileset.readyPromise.then(function() {
    var bounding = tileset._root._boundingVolume;
    var center = bounding.boundingSphere.center;
    var cart = Cesium.Ellipsoid.WGS84.cartesianToCartographic(center);

    var dest = Cesium.Cartesian3.fromDegrees(
            cart.longitude * (180 / Math.PI),
            cart.latitude * (180 / Math.PI),
            bounding._boundingSphere.radius * 1.0);

    viewer.camera.setView({ destination: dest });
});

viewer.scene.debugShowFramesPerSecond = true;
```

The Cesium version I discovered the issue in is 1.57. I tested in an earlier version of Cesium (1.47) and there are no performance issues. In 1.57, the FPS is constantly < 10, often < 5. In 1.47 the FPS is constantly > 15, which is I assume is just due to tileset size. 

Unfortunately I can't share the tileset I've been testing on. "http://cesium.entwine.io/data/half-dome/cesium/tileset.json" is the closest thing to public I could find for you, but there are some CORS issues occasionally. 

For context, the tileset I'm using was generated with Entwine from a las file originally. It seems like tilesets in the sandcastle don't have the same issue, maybe because they were generated in Cesium Ion? I couldn't test these tilesets properly since I can't import them into my application.

**Comment by OmarShehata** [comment]
To help narrow down where the issue is, are you able to tile your LAS file using Cesium ion and see if it still performs better in 1.47 compared to 1.57?

> It seems like tilesets in the sandcastle don't have the same issue, maybe because they were generated in Cesium Ion? I couldn't test these tilesets properly since I can't import them into my application.

Your application is a CesiumJS based app, right? Why couldn't you import those tilesets?

Another thing that might help here is that we host Sandcastles for all previous versions of CesiumJS. So for example you can get a hosted version 1.47 with this link:

https://cesiumjs.org/releases/1.47/Apps/Sandcastle/index.html?src=Offline.html

Which might make it easier to quickly test versions and share comparison links.

**Comment by ThornM9** [comment]
Thanks for your comment Omar, I hadn't been using Cesium Ion up until this point. I tiled my dataset with Cesium Ion and the performance improved massively, so I suppose this is an issue with Entwine. I'll report an issue on their Github and see if it can be fixed.

**Comment by lilleyse** [comment]
@ThornM9 are you able to share the tileset with someone on the Cesium team? You can send it to support@cesium.com and we can figure out when the performance regression was introduced.

Or if you are comfortable with using `git bisect` you can find out which commit introduced the slowness.

**Comment by ThornM9** [comment]
@lilleyse Thanks for the response, I thought that the issue would be solved by Entwine, but they never ended up responding to my issue.

I used git bisect to find the commit responsible for the performance issues for entwine point clouds, the first bad commit hash is: 06f133bf55c800272a38c3908ae6404ff2168bf6

**Comment by OmarShehata** [comment]
@ThornM9 I appreciate you debugging this further and finding the first commit that causes this issue. Did you send the tileset you're testing with to support@cesium.com ? Otherwise we can't verify/merge a fix without having a reproducible test case.

**Comment by ThornM9** [comment]
@OmarShehata Just sent it in
