### ISSUE TITLE
Depth test failed when enable Webgl2

### ISSUE THREAD

**Issue by JiaoJianing** [CesiumGS/cesium#7942]
Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=zVhbc9s2Fv4rGL+EmqgUrxAp29m6dtpJm0w862z7EGV2YBKWMIEIFgTluB7/9x5cSIG+dDv7squRJfDgnO/cDyDviUR7Rm+pRKeoobfonHas34W/GlrwqjKP56JRhDVUvpqj+3WD4MWaG/GD+LZCN4R3dI4WiwvWkWtO0Tu7g25ZvaHKcneU00ox0bxralYRJeQzgiMTgDsuJ70VPa/PGrYjiq6Qkr2RQ28bI0fMBsh1ll1RKcHaSyn2rKagyflUSQryvwnJ60+WJZjNrUgFDtJv6mNrYFboHkn6e0879Ru93vDE6kQP6+ZhdmwlbNDCrqINDbdss724a8iOVf8kzYZCLI13wLtu9hDilqjtL/TuUnTMaACGz1/0rtK7XDTvWac0UZPiJArTZZzEMc7LuUfJsiT3nzFeprjwKWWexIUvk8TLJMozn4KT5XI54SnLZY59njTBURZPKFlepFHqU3BZxtjHyaIojyJfKovLpIx8m7M0yotsQsmycjnxIiuyOF/GHiVPSrDA15XjIp1qx1EcRYlPSOK09C3GGhr7BIwB1zdmGWlHc5OaITlE+clJcRiVUZGWcVxarIGSFUVUTCgRzqN4QinSfJlOKXGaLX1KluDlMpvwpGk85dFBLSc4SVHgifIsxmlaTmBwmk1h0iTGxdRkHOFkApwvyySdULICiiWfUKI4TyeUBINfU0Ke4EcUyOgjShJPI5hEJRg09RyAvhyys/Vzg9PQBg4nYWoDDyRX65rmduPQKcYZ5HxYJcWwi20Z4SgssgElHTfxsJmOK2cjgLjAAK1MBtFBAtSWA62IB4nlcjAvGo1PykEiSfxaNNMGvPWHzzhFlFCEf2I7zRAZ6o2QKNBb7DQ6RuzEzZmQ02ajtkB5/Xqm+e71hwWpe2lGKWCw09MI/QNFaIXyY8txUPH6dGR1eweMikgFE5c06fRMOR/p4Y0Uuwu6kZR2gbPqM/syH5rNrLduNXMKHs/QsO27bXA/mLEaDZqj1vGsPFseLM6DAYO/xeKKKnQt+qbukLhBoof4sl3Prf8KvBzDrgAFfHF+/NxzALyAs8T6AYtAu2kWCfTCHCXwhq8Yz2bHBxTRPgtC6vqKwglUd4HRND+kcu7H7yASWFjjxQfyFY7OXtLhHGcdIgqpLUU1yElaG19CY4atm4qL6mtodLl6MWtNbwD7+BlW0Y6con2ZseqlpM3fRDWfw3k51MhIC8/fn324fHsxOqrTpT3hcBGBCPnJsln0FAx84R9C7D6JIa7aeBu5xeIn6B2oF7g+IEmaWuxQxWQFiOa0hjtEAzcYtUWQujvWbNCWwiGvOhPHm76xF5VK7Npe0XOQ5Fr0R66ZghnyWqqVoqVS3U2b4YrsWk7roZovHVMwe9JOraQ6np90TYyt/bS5n7SH3+XOHGgiHwya+LEU9Fv4uLHtdLEp/TvV6+v46wJ2JlnXDZKJSqBM6T9n29DZg/iDHy1JVQ9pGwDHfjflc25TZRoDSpRBQgawUSIcenXcOX0xxWNdnlWqJ5zfIXu/9BQMaE7dOLfNM6Od9ji4tzhjhR/MI3vCOLlmXD9AweutjkAaGFxW5R4SSDpLnI6t0OJNxFd+HnR23jmMc8HdrTv4/AJLMFaPHYQr29jzAxUG28o0l0vK7Iu+WA9u/aujZrq6SNZjdDs32Idgr8YdT/qsV0Jf7ysbY5dFIRlEyXU/6QBUp3EA2ok93cG+i4TPPAnErxTGDYTn44FhbMSx0jxb3gtSm4hbedRyArNoJ2rKdYIkhdLvAOlRDayVZVmhMZK9ZPD4KgwX4/usbbuFbQBoEbIwMt3Cqjpj0q3+Dctww9XNqzEBOwa/gPrdJftG+RX7gwIyzlwqHJOuvB/hsFo9fyAH36XRHOm37+7VVtwaV3Qn6mIjqGXNV2QmcGcHGBQjiuGnm54AsIYe0IHvwsOZ7bsN4RG8d4mIRwc4JbWuuBWYMNAU/EDjlng4DkePodEkI3yazkvB77RtP3Fx+8FxjPkcbVirDexfCn1WgsLwoHKtKsGFnIKea1Kg2VDsf8wGqYfZCAA/eY2/ceRNJ3fxGEcLhGQw9C9Gwv9FA7/cnP9Nbp+m0ctx9L/LrcloNH78h9zmL6TWXTwkqb7S+u0w8e0QMGcFcq91czQ/OunUHadvLPV7tmsF5KWXPIBBoCh0FrjYLa57AIMbVNdpRSeLQeikZnvE6tP10aP/z6yPUMVJ18HOTc/NMFgfvTlZAP9EjMMgg0vNxz2VnNxplm385r0lhmF4soDHp1JKCH5NQImz+7BjTqRW2EPoA216X6v7/hM

Browser:Chrome  74.0.3729.169 x64

Operating System:Win7 x64

When enabling webgl2,path will cover the airplane model.Seems like depth test between them has some issues.

**Comment by OmarShehata** [comment]
@JiaoJianing can you provide a screenshot or a gif of the issue here? I can't seem to recreate this. I only see a plane, no trailing path in that Sandcastle.

**Comment by OmarShehata** [comment]
I think I see the issue in the other WebGL 2 issue you posted https://github.com/AnalyticalGraphicsInc/cesium/issues/7952. 

Here's what Cesium man looks like with WebGL 2:

![depth_error](https://user-images.githubusercontent.com/1711126/59889528-c6bc8100-939a-11e9-89f9-d723d597e00f.gif)

Here's what it should look like:

![correct](https://user-images.githubusercontent.com/1711126/59889534-c91edb00-939a-11e9-9a20-47b7ba1a5076.gif)

**Comment by JiaoJianing** [comment]
When enable webgl2, It looks like this:
![1](https://user-images.githubusercontent.com/12868409/59902520-03d35280-9431-11e9-98d5-306eef3ec455.gif)

When disable webgl2, It looks right:
 @![2](https://user-images.githubusercontent.com/12868409/59902566-2d8c7980-9431-11e9-8405-add67dc0bb60.gif)
@OmarShehata

**Comment by OmarShehata** [comment]
I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap, so we can consolidate known bugs and discussion in this issue: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407.
