### ISSUE TITLE
Post Process Failed when enabling webgl2

### ISSUE THREAD

**Issue by JiaoJianing** [CesiumGS/cesium#7952]
Sandcastle example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=pVb7byI3EP5X3PzCInFmc0nuVEJQ81JVKXecSpuoElLl3R3Aitfe2l4IPeV/79j7BpLqEoSEHzPfPL8xa6bJmsMGNLkgEjbkGgzPU3rvz4Je7LfXSlrGJejegHyfS4Ifs1K5SC4lT5kFMiJW5zCYy7mNURae7DSzXEkzIt81/JODsQ8QLcXHQvB5Lp/75056Lgvr1MQgga74cnWzlSzl8e9MLgGdWjBhwMnKNfqaKcMdMF6Unl4zbXHF5AldaJXewFIDmODD8ccTGn4+Pf10/POAnJ7S8Cw8+Rx+cmYdUK4FYvQoHdbfyywzwxlLMwE3zLJhqhIQZljY+cJkufobl3Qpot557bzVLH6E5FZabrcIWx6D23MwlCVJUOYNY3PpQvOD4qCOaFQvyxtvH49LTffJNS+Ui6M6jz4kZ/WL17modCKBjl3K5GHFLcxWajMq8jk4cP2rZgkri3ZGw0pEY0msBGMOqNd390zkMCIhPSuvpLu55wbh9vUMF9g9YOvGwTB8FGVJH6WKH1Vui7wGdVxV7axSImKuYxMV5ymmmS7B3gpwy6vtb0nQK0V6TmUXlWWZ2F5xmXC5NA36oMJ1OgulSeBs+Xpx2SS3X+WWL0ijTFfMTDfym1YZaLsNnFq/3y7drhfo8TQyoNcsEtD2wqtSk0cm1jyCIM+wLPBNGYvoyEfj/Kuq77LmHPmphG+JzSxbwh2PNNNbys2sTvoszzKFpEmCNvcab5HBRgmgQi2D3h8rbrDQaoOuYrrBEKksMQUEsStoVxMb2JKsME997p+r5jTOG9Nwo+B7tuOuKSvcwrwoVT2J/ifKWAOmqhWpuwz6Vd902v0NwFcdNu1g11x4C3BDsi5qi0ZvgP3aImGDi82dy9iPnL3WCuomaCqAY8y1aIIOXCFBgMlW2zdiVVe2FHNsTaVTQ2MllG6NbLelf93e3U0fzg9Molct7o20/kGI2vayHmsI9zVPI3zWXkBrJmCNWRfmdZ86Q/KAcu1Np032vekO1Aqo1QWvurEzdEv+HSgyXhwNjsbGbgVMChu/8NQzGt+WAN9CC/gMopoZRjk+bZbGxdwZDyulccLXhCcX86Od/wjzIxILZgzeLHIhZvxfmB9NxkOU76gJxdwEnq5BC7Z1IqvjyV1xSCkdD3G7r1XOaBTHU+tyMRnbSCXbMo6x1ZNm6I5tMmnGwXiI2+7lmMssxzm2zcBFsoL4MVJPGALmjH2I8JGojiEZtXrbR1Sj4VK/aN9PDcJkQnyTvduJPQJ0fTkMqt2/KURMucTdsVuxJ7cKcWksZOVp2+K6eNRfoMiA+Ps/fXeNSM+b6/1IXupmf39KOvz78XyETT6adIQ0fCkjXZq+OxN+TpOCuO/Oxc4QOOgG/njK4K9nkDspiPYf

Browser:Chrome 74.0.3729.169 x64

Operating System:Win7 x64

**Comment by OmarShehata** [comment]
Thanks for reporting this! Looks like a bug to me. What it should look like:

![correct](https://user-images.githubusercontent.com/1711126/59889559-f2d80200-939a-11e9-9c9f-a01012e2fa2e.gif)

What it looks like with WebGL 2 mode:

![depth_error](https://user-images.githubusercontent.com/1711126/59889565-f4a1c580-939a-11e9-9d57-1cfe4221cd24.gif)

**Comment by OmarShehata** [comment]
I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap, so we can consolidate known bugs and discussion in this issue: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407.
