### ISSUE TITLE
GEE terrain provider is flat if we start out zoomed all the way in

### ISSUE THREAD

**Issue by tfili** [CesiumGS/cesium#8001]
I believe it has something to do #7061. Setting `scene.globe.loadingDescendantLimit = 0` fixes the issue, but that will obviously slow down terrain loading.

If you start out zoomed out and zoom in everything works fine.

http://localhost:8080/Apps/Sandcastle/index.html#c=lVJNb9swDP0rQi52gFRK7MT5aBoMSIuhQIsN27BdfFFs1hYmS4ZE20mL/PfJcVLE22GoTuLHeyQfWXNDMoBnQJ5y5OSOKGjIFqyoCvpZ60zCAzeYPygEUxph31P9q8RvYHVlEvDfYkXcq4wkK+LliOWKsaZpKLQk8E5CtclYmHqjLr80en9wiCvKe3jhlcSvbcT32CmDecNYHYfD21jFqnad1wIaMP2mf558vpeczK1WyIUC443IuTlR8AzMwTHXInXo1X9HfuwjLlO2r7gIt7qWsYsfh+fxHI9xTXyg4o8+4kMVj50+jJFfAnNdIcFcWNIAabTykOS8BsLVgeQgshxdxC2GvGpdQErECdnpSm0CCmgm9Q6o1DwVKruH1plyhU+iEOikH3fb6BCwRxf1z6N1zs54VLaEBLV5FnuhhteghBdgOLWA7e4us6ZgUSiOQqueXlunlPtxFfo3QTQLF9GURtNJNA7n0TIckZtpGETBIqDTZTAPFrPZckTCxXy+nAZ04WLz5Ww8Od3R7WA0WFs8SNh0JT+JotQG2/P1KWUIRSm5K8Z2VfIbkCbWto2v2QW0TkVNRHoXD/66tnhAEsmtdZGXSsrv4hXiwWbNXH4Pdlb1Sw1G8kObkk82T52TUrpmzvwXhVrLHTdXjH8A

@kring Do you have any ideas?

**Comment by ggetz** [comment]
Close due to inactivity. We're unlikely to fix this in the foreseeable future.
