### ISSUE TITLE
Cannot call sampleTerrainMostDetailed on ArcGISTiledElevationTerrainProvider 

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8007]
This [came up on the forum](https://groups.google.com/d/msg/cesium-dev/grjkeKWG9Ig/fGsnzkEMAgAJ). If you try calling `sampleTerrainMostDetailed` on an `ArcGISTiledElevationTerrainProvider` it complains that:

```
sampleTerrainMostDetailed requires a terrain provider that has tile availability.
```

[Sandcastle link](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=lVNbb9owFP4rES8kGnO4lIUCRZtgWiu1WjWq7aHpg5scEmuOjY6dIFb1v+/kNgrlZXmyj893voudgqNTCNgBOleOgp2zBCPyjP2sam43qrZLrSwXCrDbc15C5dBnAZFK96gLEQNO34K/YPTtZv0gJMRfJRTcCq0ejvvdZkz55SinTje1dmumvg8tYhQzjlEiDIt05tdLH8FY3wAWgpT5vzTKA8Vo5TcstLrJeAJraiTRNdWrF6pXbxaqUBXk2vBsK+FeGzL+WHY04pccrU6Qb1MRsQ3qbAUJAhj3YxCwwejiYhL0x5fjIBj3L3vOaMI+BUEwHPaHk8FkckEcTxUFkVQRspOgGAKP97TLhAFmU1DuJldRqd8V5kd56L2UcmvRCDZH1WqrNTcm77SxK6B7oZjd82S9g0tv1sZdphCqE2rKNZfWeM21RFoZLYFJnbjdW0rX5jFMu86HVskdtymzus3mH81j/4nJpt8rw34/Tavk/8a1gPPzrkEkqa2GHcHSql5CKrua/OKOMj94pqw0nnNcH1TIWafXmRu7l7Co+z6LbKvRlo/WZcy3QJTc0lt8zqPfYFlkTImc+y1oHovCEfFV2Dn5l8KOE0luDJ1scinX4g+EncXcp/4jmNQ8Fir5Ti9Z8n3Zkg4Wt3WRMTb3afseZbWWzxzfTPwL).

But you can see that it does compute an availability here: https://github.com/AnalyticalGraphicsInc/cesium/blob/3601fc73247ab3526c4f18be38ccc8c1860a541b/Source/Core/ArcGISTiledElevationTerrainProvider.js#L158 It just doesn't seem to expose it as a property.

If I just throw a `.availability` property, the call works but the returned height is undefined. I traced this to terrainData.interpolateHeight returning undefined here: https://github.com/AnalyticalGraphicsInc/cesium/blob/3601fc73247ab3526c4f18be38ccc8c1860a541b/Source/Core/sampleTerrain.js#L107 Everything that's passed in looks fine, so I'm not sure why it's undefined (and it correctly figured out that the max level at this point is 16).

@tfili

**Comment by OmarShehata** [comment]
Came up [again on the forum](https://groups.google.com/forum/#!topic/cesium-dev/6e2E4lTXvgw).

**Comment by smills2929** [comment]
It's worth mentioning that you can't call sampleTerrain at all. It's not just 'sampleTerrainMostDetailed' that doesn't work.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/grjkeKWG9Ig/fGsnzkEMAgAJ
https://groups.google.com/forum/#!topic/cesium-dev/6e2E4lTXvgw

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8007 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
