### ISSUE TITLE
"KML Tour" feature is not documented

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#8073]
There's a Sandcastle example called KML Tours and the docs include some classes like KmlTour, KMLTourWait, KMLTourFlyTo, but all of them have no top level description or useage information.  The KmlDataSource class appears to have a `kmlTours` property but it's completely absent from the documentation.

**Comment by OmarShehata** [comment]
Thanks for catching this @thw0rted ! I think it would make sense to add the `kmlTours` as a public property, and top level descriptions in those classes, and link to the Sandcastle for [KML Tours](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML%20Tours.html).

**Comment by srothst1** [comment]
@OmarShehata @shehzan10 

Updated documentation for `KmlTour` related classes including `KmlTourWait`, `KmlTourFlyTo`, and `KmlTour`. Let me know if you have any suggested edits.

For `KmlTour`, I provided a link to the KML tour sandcastle demo. Should this link should go underneath or above `@see KmlTourWait`?

The documentation references `KmlTourSoundCues`, yet I was not able to find this class in the documentation - how should we handle this?

**Comment by shehzan10** [comment]
@lilleyse @srothst1 Should this be closed as the PR has been merged? Or is there anything still left?

**Comment by srothst1** [comment]
@shehzan10 I think that this issue can be closed. The documentation for `KmlTourWait`, `KmlTourFlyTo`, and `KmlTour` has been updated. The documentation for non-existent `KmlTourSoundCues` has been removed. An issue related to `KmlTourSoundCues` has also been created [here](https://github.com/CesiumGS/cesium/issues/9602) for future tracking.
