### ISSUE TITLE
Tests should not modify window.devicePixelRatio

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8130]
Our unit tests can't run in IE11 anymore after this PR https://github.com/AnalyticalGraphicsInc/cesium/pull/8083#issuecomment-527568810 which modifies the `window.devicePixelRatio` to ensure consistent unit test results on all devices.

The spec says that this property should be read-only, and it seems that only IE11 has an issue with this.   It would be a good idea to revert this change and ensure our unit tests are consistent across different device pixel ratios.

**Comment by OmarShehata** [comment]
I actually can't seem to run IE11 tests anymore, I don't get the `SCRIPT5045: Assignment to read-only properties is not allowed in strict mode` error. Just a blank screen.

My IE version is 11.719.18362.0.

I tested on a few versions back too, same behavior:

* https://cesium.com/downloads/cesiumjs/releases/1.67/Specs/SpecRunner.html
* https://cesium.com/downloads/cesiumjs/releases/1.66/Specs/SpecRunner.html

Anyone else seeing this?

**Comment by mramato** [comment]
I can check on my personal laptop later tonight, but it may be time to stop worrying about running unit tests in IE11 and just switch to IE11 smoke screen testing.

**Comment by ggetz** [comment]
Closing since IE11 support has been dropped.
