### ISSUE TITLE
pickPosition isn't accurate when depthTestAgainstTerrain is false

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8179]
When `globe.depthTestAgainstTerrain` is false `pickPosition` will pick the depth plane instead of the globe. You can test it out in this [sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=1ZPbjtMwEIZfxepNUym4OTkHtq2AgsRKsFRshISUG9eZtta6dmU7LQvi3dc5FHWpuNorchF5Zvz9E/8TH6lGRw4n0GiOJJzQEgxv9vhbl/PGrAuXSlrKJejx5KaSR8cYBhIc0rO4C13JFS8SmNE9aIoN2FbP+1VJ5J4ajOWSWq4ken3ZdEm1dSsqYy9JkjAlOCZpGpKCxLmPXpEwybMsw4RESUqKPPZRnEUkCwKcFiQIcxLmE7/voTQH983XPT4Crbncrrhlu69KCC/FUR47Ng6yMCtInrpOISZpEYV5SsIwIVFRRD4KztIg61JTaTZK7532oPuZWs1/JPj2/Ye78rb8Xsnfk86QSt5TWTNqrABM67pUSqypftdYq6Q3XnH2gE7c7pwtB7srnTdvt85rY0vQ2i2Q1Q2MfbRpJGuP403Q4GPv8VaoNeB/wfMOv7kEtDuAG+1kSPbT1AByqZSu28GAef4z/JlL5EVB4CP3uqQPyvDO6PnQ4eDOtBqS3pX2GWVKGuU8EWrrnSXa2uDbC13bUGFeYlvH/4++jfzRzNhHAYt++xu+PyhtUaOFh/HUwv4gWrnpumEPYDEznfJseoZmNT8iXs+r0V+XvxohJqgxrrJphLjnP6EaLWZTt/8ZJlR3xb4cQQv62G7ZhYtPfRJjPJu68Jqy/YQvFJ8A).

The discrepancy will get even worse once we push the depth plane to fix https://github.com/AnalyticalGraphicsInc/cesium/issues/7879. I have some ideas for getting `pickPosition` to work regardless of `depthTestAgainstTerrain`...

`GlobeDepth` will need to get composited into `PickDepth`. `GlobeDepth` stores the globe depth before it gets cleared while `PickDepth` stores the depth after all passes have been rendered. We'll need a command that writes globe depth back into pick depth but only where pick depth isn't set. So if someone does pick position on an object under terrain it will still pick that object but everywhere else it will pick terrain.

This would normally require a copy texture because the pick depth is both read/write, but we may be able to use the stencil bit being added to https://github.com/AnalyticalGraphicsInc/cesium/issues/4381 to avoid that. In this case the framebuffer's depth attachment would be `GlobeDepth`'s depth-stencil texture, its color attachment would be the pick depth (which is not actually a depth texture), and it's texture uniform would be `globeDepthTexture`, which like pick depth is not a depth texture but a color texture with packed depth values. The shader would be a passthrough shader and the render state would be color writes, no depth writes, and stencil test. With this approach I'm hoping `gl_FragDepth` is not involved.

I'm a little concerned about translucent objects. Those objects will write the stencil bit to avoid getting overdrawn in https://github.com/AnalyticalGraphicsInc/cesium/issues/4381 but it actually should overdraw in this depth compositing. Maybe there need to be two stencil bits (color overdraw vs. depth overdraw) based on whether the command writes depth.

**Comment by lilleyse** [comment]
Initial attempt using the primitive color framebuffer is here. I'm abandoning this approach since it doesn't support depth-only commands: https://github.com/AnalyticalGraphicsInc/cesium/tree/fix-pick-position

Started a second approach that executes the globe depth copy during a second depth plane pass here: https://github.com/AnalyticalGraphicsInc/cesium/commits/fix-pick-position-2

**Comment by theosche** [comment]
Hello, any update on this ? Is there some workaround ? Thank you very much !

**Comment by ggetz** [comment]
This came up on the forum as well: https://community.cesium.com/t/scene-pick-returning-point-inside-the-globe/18940

**Comment by katSchmid** [comment]
Any update?

**Comment by ggetz** [comment]
This is a duplicate https://github.com/CesiumGS/cesium/issues/4368. Closing to consolidate reports.
