### ISSUE TITLE
Fix aliasing on thin models

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8228]
For 3d models that have thin parts (think the frames around a window of a building), when you zoom out or look at them at an angle such that the line occupies a very small area of the screen, you get some very noticable artifacts in CesiumJS.

Model: [lines.gltf.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3673190/lines.gltf.zip)

How it looks in Blender:

![blender](https://user-images.githubusercontent.com/1711126/65913774-704dde00-e39e-11e9-80b5-dde4d9a542a0.png)

Now if we look at it at an extreme angle:

CesiumJS:
![lines_cesium](https://user-images.githubusercontent.com/1711126/65913556-236a0780-e39e-11e9-8478-7b001139fdc9.png)
BabylonJS:
![lines_babylon](https://user-images.githubusercontent.com/1711126/65913561-2533cb00-e39e-11e9-8bc9-69f39dfc6276.png)
ThreeJS:
![three_lines](https://user-images.githubusercontent.com/1711126/65913565-25cc6180-e39e-11e9-88d0-50179d40f49f.png)

I _think_ this is because the other two engines are using MSAA to get the lines to still look decent even when they may be sub-pixel thick.

**Comment by mramato** [comment]
This is easy to see on the Cesium hot air balloon as well, just zoom out slightly while looking at the ropes holding the basket to the balloon. http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Models.html&label=All

**Comment by OmarShehata** [comment]
Came up again [on the forum here](https://groups.google.com/d/msg/cesium-dev/CBFHAKRU1bo/yskluTIZAQAJ).

**Comment by OmarShehata** [comment]
Came up again in https://github.com/CesiumGS/cesium/issues/8642.

Here's a [Sandcastle](https://sandcastle.cesium.com/index.html#c=lVPbctowEP0VDy+QCRXYGGIIZGpzC4QkxFxD6YOwha0iJFcWEKfTf69kSJqkL+nO2NrLWa1We7SHXNtjdEBca2gUHbQmivFuC6apL5f1UrPJqICYIp49u1zSIx4gKrDAKAbQ93O/lhT7NS2LtzBAXzxESDa/pBEjScBoTUZDjDjkXpjUXko0IRdSg7QE1pxtWyjgCMU25zDJfdN1C1hmVUpeKxmgqETPa7peBeVKyTDNC+k3gVGumCe3UapIp8SaVtk4+VSWxOnAKpmWclmgmtoXZVP/fiZPuIUCcQxJ7W3zPdXE7Sky5CxCXCRpiyogu/ShgLXUKEQ0uFzBGFXMPJ469+6heNMNmC3lbjQJ25NAaq2espOm/ahWNDTxk1K6c7czu3bHK2NR9I1OsnhwnEW3ihcjp7+adehi2iePM7fseYQM0wTSd9udCbrjscHbbtC0b52pY4el3sivup3H5mY4qzxFt0P/nCQX+81+QFE0Q/bP0aZnb1qGtw7v+wUrOp+v9vPZ3nnoNe3gM99NMm6VfTK4XpmjXuCVNp2u7cx/PJC7jmUbc9Wj7fTdSbnNN/0gCBoNNX2OIgTFu5t9nbmR0w01mmJRTcFjhPG/xFAWcNstcMAitEkUwlwRVBTwd/pTq+ThKxOfGduOWe4DL4+QEaS+B2NBkOLpmDGygtzZCcFoLusi6kvmQ6Fd4yDUXBRn89p6Rz2BZfhMTlyTctqXo5iRnYqMPEiQfC/G5ekknywyYIf/rlEE5WOVTD5Tj0VC0NUx4yveRowLbcdJDoCCQNuISMrGhdXO2yABvDi9gXrhJanu472G/cYy8+FRLzOaR2Acy8h6R8gIP6Nl5qpekPh3aYRBH9Pgfo84gYmChPrV4OgEANQL0vw3Sxxv482OfwA) reproducing essentially the same effect but on a texture. This should be easier to fix because having mipmaps for this texture could help.

**Comment by weiyinggh** [comment]
I also encountered the same problem, hope to solve it quickly, thank you!
