### ISSUE TITLE
Support rendering cesium to new window

### ISSUE THREAD

**Issue by sgparrish** [CesiumGS/cesium#8235]
For the most part, rendering cesium to a window generated with `window.open` works great. I've encountered the following issues:
- Animation widget styling wrong and dragging not working
- Timeline widget dragging not working
- Fullscreen button not working

[See this demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lVLBjtMwEP0VK5eUVbDLBaGlrVgqOK3gsAguubjxNDZ17MieNBTEvzN2tlVbKiRSJar95r15fp69DMzB+M045Ue2ZGP+w30PblaWFUtvXWgwrcbl6/m8Go1CvXwzn9fFi7e1Sz8hmESUjWYRDxZqtyfRzdDsANcxkqjyzdCBQ94EkAgfLKTVrLTG7cqkcirmeOiBGCXCDxRNjOUFGsAmMLeJGgAvYR1gm3CN2Md7IRqIZui+R+5DK9Z5Id4Pxirx0PdRPEmnGhnRgkDoekvWopjU+HPrUzT8dAYNUnHZU0BqrUlrdup/zCMdf2q99g6lcRD+EYIy+5zBFYM3Vsb4aCJyqdSs3A7WPpmfkGtv2Np4dbiwdaU3mUvW9gbG7IhU2JQK/5r3rjkV+yWd6SQa7+4ZhgEqhqYDujeY1r8nWXFXu08egaEGtvXWepqj9r527CV7OCrQbKkWMA8JobdBFWTbEkpxQXQlstGHHSM8mZ2GMxO/PNv4D15FMzntRzZqcKzze1CMPiH77mWgIM+bfKTMI10X1RIVSe1cvXZ3oqiKRZ7GFRHoeWe63gdkQ7Azzm+OVUpsIY6kBV0/M2pZF1fZ1wXLE0DI8errYrUQVH9Bs14qOvdnOoWVh1SiX60ep03O+ULQ8m8Wem83Mpwp/gE)

These issues are all caused by these widgets assuming the global `document` object is the document in which they are being rendered. The Animation widget styling fails because it attaches css styles to `document` to copy into the generated SVG elements. The Animation and Timeline widgets' dragging fails because they attach mouse listeners to `document`. The Fullscreen button command fails because it defaults the fullscreenelement to `document.body`.

Screenshot of Animation widget rendering issue:
![image](https://user-images.githubusercontent.com/1388256/65978914-7dbca400-e442-11e9-9859-02fb69815c59.png)

**Comment by hpinkos** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/8236
