### ISSUE TITLE
Plane entity not rotating correctly

### ISSUE THREAD

**Issue by IanLilleyT** [CesiumGS/cesium#8268]
This came up in a [forum post](https://groups.google.com/d/msg/cesium-dev/_S5Z3oaJdvQ/_JEOWflNBQAJ).

[Sandcastle demonstration](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=7Vfhbts2EH4Vwn8sAxpt1067OXawNk3bAEmXNe6aZB4CWjrbxChSICnHbpB3H0lRjqS4S5YEGFBUCWyRvLvv7rsjeV4SiZYUrkCiEeJwhfZB0SzBf7i5oBm54b7gmlAOshmi6wlH5qF8Jt6IFRqgGWEKwnxWAYNIU8EPeUwjooWsCyxILK6UmdUyu50UGYtfc5oQDX5pwm9auxM+4UvjYSoUtVaNj96/fSK1eSO8h2dSJG9hLgFU8FP3RQ93XvX7L7u/hKjfx52dTu9V52WIdjqdDu5Yk9bgIpWfBGMXIEU17g9AYsrnJ1RHCysRFBpCUjAkVL0YS8LVTMhE4UVN8ffMxCK5EQ8K78MybB7cLOOOLhRJMPLHIgYWcJKAkQU6X+gWurYM5TzlicLGD2MPFJaQiCW89l56GeOrE1jv+kTNnEE0Go1QM2WEw+Wq2crXfC7tk+uY0OogJI6Dkpx9nL2B+wqrK0Wog81bXcA6YHRrFstLpWyc2Kngbso/fzwcX56FyGY0vGsppglwZcBV1dzGwouga1RD1P2GAVuHkhJm1JsYt01dzkG1cyuXR2IuLg3vkpE1Tvm8ucWAyDSjHKplvkVgXzC3RQoH7RB/+XA4Pqiq3NRMlKtxUB7dirnt417yLzCbcFsxrL+LYjj/UQzPUQxfv4tiuPhRDE8rhqn4H6+Iqesqrh+RvF7Qt7nr2Y+de/NXYfbN0efnJ9bzpCWJ/ob4oKCvcj3f3tqJvfyPiZZ09aAOYyze0RXE76TheHuPERZWDhijqRI0xl/en/7cL9z0/qkIOOBU0sSYWPp8lvh9C9Nsfnzr3UkhWU562ftBeVSikQGf64VZ7tperLRwReN8Hnc8gS3r4823WqRPQgeejhCllpAQSRN0qygb3+Pd09ttNeG5ea5+r8Z1pRZwFaQ0KoL3vWeqXdWP0J8+Pg0rbY8gdwyiCxTkNdUqThwj7Tpx2317/oINOeVec3PulztkX8I3m2a/Cnf2ZLjVf4E7fzLc+mFw9ufM46HsmVmGsRB/7d5J4tn5xZY8fhQcHgRZg7Ubwd1X9v9fg/PF/3iQ3gNA3G54NIS9tXv3Qdi99hQEB1JGKHJk/04JjyOiNAN7Bo6FYFMij4Fngc+eVbxXyKTYyjXCxlDpNYO9HOxXmqRCapRJFpjWQUNiqtNcXO1pZo4EjSPlzA/bhdIwpktE49GkUfsVPmmgiBGlzMosY+yUfoVJY2/YNvIVNSZczn/LOxIrsujuHeWTGONh2wzvauk8opLFfwA).

Select `Plane Z` and then select between `Heading`, `Pitch`, and `Roll` in the second drop down. Notice how `Heading` looks exactly the same as `None`. For comparison, select `Box` from the first drop down.

I tracked it down to `PlaneGeometryUpdater : createPrimitiveMatrix`. If the function becomes just `return transform;`, the Z-Plane works, but then the X and Y planes become Z-planes too. 

I think the core problem is how the up vector gets set, since it ignores `transform`. If the function is passed two different transforms with the same Z column, such as when `Heading` vs `None` is selected, the resulting matrix will be the same.

Any thoughts @hpinkos, @OmarShehata?

**Comment by baothientran** [comment]
I haven't tested it thoroughly, but if the plane is transformed/oriented in the local coordinate using the plane normal and distance as it is, then multiply with the `transform` to convert to world coordinate, it works for me

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/_S5Z3oaJdvQ/_JEOWflNBQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8268 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
