### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#8291]
We haven't updated README.md significantly in a while.  We should update it to 
- Have a nicer looking layout
- Highlight our most recent demos
- Highlight our supported features (see https://github.com/AnalyticalGraphicsInc/cesium/wiki/CesiumJS-Features-Checklist, which also needs to be updated )

**Comment by yukinoda** [comment]
@hpinkos 
I've added some small update to the `getting started` section in #9775

**Comment by ggetz** [comment]
A brief section about how to include modules from the `cesium` package should be a big help for [questions like these](https://community.cesium.com/t/czml-using-offline-map/20579/2).
