### ISSUE TITLE
No error is displayed if Cesium rejects a QM tile.

### ISSUE THREAD

**Issue by sevvie** [CesiumGS/cesium#8340]
Browser: Brave, Chrome

Operating System: Windows

In attempting to generate quantized mesh terrain tiles, I've made a mistake I cannot seem to track down, in no small part due to Cesium's relative quietness around errors such as this. As far as I can tell, after generating quantized mesh terrain tiles with a patched cesium-terrain-builder from the ASTER GDEM-10km-colorized GeoTIFF and loading it into Cesium with a simple script, when I attempt to zoom in tiles will disappear from either z1 or z2 (I can't tell which) and the problem persists until I reach the limit of zooming for the provided data (z5 in this case).

I'm not complaining about your Quantized Mesh support or support for third-party productions -- I'm solving those problems myself -- but rather the strange behaviour being associated with no output in the console whatsoever. You do provide output when the terrain can't be read -- Cesium throws that it can't handle tile 0, 0, 0 or 0, 1, 0 if the received data is wrong. But if Cesium rejects the tiles even if they seemingly validate ahead of time, there's nothing to go on in debugging such a thing.

![image](https://user-images.githubusercontent.com/1657272/67965996-4b78a080-fbc0-11e9-8876-fda292a2c5b8.png)

Here's an example of what I presume are "rejected" tiles? As I zoom in, the region grows to encompass about 2x2 tiles on zoom level 2, but if I rotate the globe the affected region changes. And if I rotate the globe to look at it directly from above or below, all terrain tiles disappear. Again, with no output to go on and understand why it is occurring.

I'm not sure if this is a bug, a feature, or a question, so forgive me if I've labelled this incorrectly.

**Comment by OmarShehata** [comment]
@sevvie thanks for reporting this. I would say at first glance this is something we can have some improved error reporting for. For example, when there is a detected tile failure, you don't get the actual error (I opened an issue for that here https://github.com/AnalyticalGraphicsInc/cesium/issues/8313).

Are you able to share a sample that reproduces this? There might just be a missing check on a failed promise to report this.

**Comment by hpinkos** [comment]
closing due to lack of response.  @sevvie if you are still having an issue please comment on the Cesium Community Forum: https://community.cesium.com/
