### ISSUE TITLE
Revisit release packaging

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8343]
With the ES6 transition, index.release.html (which is the main index.html you get when you run an official Cesium release) has some inconsistency across browsers.  None of these are showstoppers on their own, but depending on user interest and feedback we might want to figure out a path forward at some point

1. `Run tests` in `index.release.html` no longer works in IE11 or Edge. This is because they both require the "built" version of the tests to function, which isn't an option in `Run tests` for the release.  Should we really include this in the release packaging anyway?  Seems pretty non-standard.

2. Cesium Viewer is unbuilt, so it no longer works in IE11, probably not a big deal

3. Sandcastle is the `unbuilt` version which doesn't really work in Edge (or is buggy/excruciating slow).  We could just use the "built" version of Sandcastle which only depends on CesiumUnminified in the release if we wanted, but Chromium-based Edge is due out soon, so maybe its not important.

**Comment by ggetz** [comment]
Closing as OBE due to IE11 support and Edge updates.
