### ISSUE TITLE
Post Processing sandcastle issue

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8345]
Run http://localhost:8080/Apps/Sandcastle/index.html?src=Post%20Processing.html&label=All

1. There is an odd flash full screen flash when you enable each of the effects the first time.
2. I got a random crash the first time I enabled black and white about undefined `v` in a UniformSample or something similar (not sure of the exact details, I couldn't reproduce)

**Comment by lilleyse** [comment]
This was fixed in https://github.com/CesiumGS/cesium/pull/9649
