### ISSUE TITLE
Outline fails to render correctly on a non-flat terrain

### ISSUE THREAD

**Issue by nicolas-van** [CesiumGS/cesium#8364]
When using the outline feature on entities with no height, it is stated by the documentation that the outline should display correctly as long as the `fill` property is `false`. This is indeed completely working as long as we have a flat terrain (see the working example bellow). But as soon as we add a terrain provider the entity doesn't display correctly anymore (see the broken example).

By playing a little with the camera in some un-natural ways I was able to see that the ellipse is still displayed, but actually *under* the terrain.

Sandcastle examples: 

* [Working example with a flat terrain.](https://sandcastle.cesium.com/#c=zVPBbtQwEP0VK5dNpeBktT2FdAXdllNREbTlkovrTNqBiWc1dra0qP9eJ5uFshSJAwd88rx5b578bFt2PqgNwh2IOlIO7tQKPPadvhqxdGbHcsUuGHQgs0x9r52KK88DiETwg/AGG5ByJ7UCJsBnFmoutpT0IKvd48Hr2tXOjpYWxRJEy623BhcwIHhtmiadHNbsI8bux+CVkRB3xi10K9ydwI0A+PTVvFjoIlOHhS4Go0HrTAelmn2ERgERrj0odsr30hoLs4k0dcrdkYblocP36FjefkNfqkURh2Z7bfPlT+0WiUrVGvLwDOU+UAyvVEH6F/AVE/9Mb6z08dnl6cR8fDG6dz3Rv4xv/l/k18WHI2job9KYjv7A3F1wuhfEQEmypPLhnmC5lb7Bbs0SVC+Uah2fb7em6Ofz695+haCtH2VVvhNVDW4UNkd1svcL6kRZMt7HThvv4RM+QJ0sqzzyf5ERmwbdzfkGhMz9QLmdL8+2oNa6ymP5uyow07WRZxOfAA)
* [Broken example with a non-flat terrain](https://sandcastle.cesium.com/#c=zVPBbtQwEP0VK5dNpeBktT2FdAXdllNREbTlkovrTNqBiWc1dra0qP9eJ5uFshSJAwd88rx5b578bFt2PqgNwh2IOlIO7tQKPPadvhqxdGbHcsUuGHQgs0x9r52KK4BIhD4Ib7ABKXdCK2ACfGah5mJLSQ+y2j0evK5d7exoaFEsQTTcOmtwAQOC16Zp0mn+mn3E2P0YvDIS4s64hW6FuxO4EQCfvpoXC11k6rDQxWA0aJ3poFSzj9AoIMK1B8VO+V5aY2E2kaZOuTvQsDx0+B4dy9tv6Eu1KOLQbK9tvvyp3SJRqVpDHp6h3AeK0ZUqSP8CvmLin+mNlT4+uzydmI8vRveuJ/qX8c3/i/y6+HAEDf1NGtPRH5i7C073ghgoSZZUPtwTLLfSN9itWYLqhVKt8wDdmqKfz697+xWCtn6UVflOVDW4Udgc1cneH6gTZcl4HzttvIdP+AB1sqzyyP9FRmwadDfnGxAy9wPldr4824Ja6yqP5e+qwEzXRp5NfAI) (only difference with the previous example is that we added a terrain provider)

Browser: Chrome 78

Operating System: Ubuntu 18.04

**Comment by hpinkos** [comment]
Thanks for opening this issue @nicolas-van! This is a known issue we are tracking here: https://github.com/CesiumGS/cesium/issues/6694
I"m going to close this as a duplicate
