### ISSUE TITLE
NormalizedResult is not a number from viewer.scene.pick()

### ISSUE THREAD

**Issue by tinco** [CesiumGS/cesium#8370]
Operating system: Windows 10
Browser: Firefox 70.0

One of our beta testers encountered this error while using our app. At first I thought maybe we're feeding it some incorrect data which is usually the case with a DeveloperError, but in this case  we're feeding it the result from pickPosition and the DeveloperError originates from quite deep down the Cesium stack.

Our code is basically:

```
    this.mousePosition = viewer.scene.pickPosition(mouseScreenPosition)
    let pickedObject = viewer.scene.pick(mouseScreenPosition)
```

The error happens on line 2. Unfortunately I've not captured the mouseScreenPosition, there's some chance that there's a weird return value there. I've modified our code to track this bug and log the mouseScreenPosition so perhaps this bug gets hit again and we get more info.

```
./node_modules/cesium/Source/Core/DeveloperError.js in DeveloperError at line 43:19
./node_modules/cesium/Source/Core/Cartesian3.js in normalize at line 421:19
./node_modules/cesium/Source/Core/PerspectiveOffCenterFrustum.js in computeCullingVolume at line 234:20
./node_modules/cesium/Source/Scene/Picking.js in getPickPerspectiveCullingVolume at line 184:26
./node_modules/cesium/Source/Scene/Picking.js in getPickCullingVolume at line 193:16
./node_modules/cesium/Source/Scene/Picking.js in pick at line 234:36
./node_modules/cesium/Source/Scene/Scene.js in pick at line 3485:30
./src/components/CesiumViewer.vue?b62d in pick at line 628:39
./src/components/CesiumViewer.vue?b62d in handleMouseMove at line 601:12
./src/components/CesiumViewer.vue?b62d in action at line 575:31
./node_modules/cesium/Source/Core/ScreenSpaceEventHandler.js in handleMouseMove at line 259:13
./node_modules/cesium/Source/Core/ScreenSpaceEventHandler.js in listener at line 67:13
./node_modules/@sentry/browser/esm/helpers.js in n at line 74:23
```

**Comment by hpinkos** [comment]
Sorry we missed your question @tinco.  If you are still having trouble, please post a question in the Cesium Community Forum: https://community.cesium.com/
