### ISSUE TITLE
Cesium Inspector picks the wrong tile with terrain

### ISSUE THREAD

**Issue by IanLilleyT** [CesiumGS/cesium#8379]
Clicking at the red arrow results in the wrong selected tile. This seems to only be a problem when terrain is enabled.

<img width="620" alt="Screen Shot 2019-11-08 at 10 50 08 AM" src="https://user-images.githubusercontent.com/1328450/68491245-798d5e80-0218-11ea-8975-8e9981ee42a9.png">
<img width="650" alt="Screen Shot 2019-11-08 at 10 50 18 AM" src="https://user-images.githubusercontent.com/1328450/68491231-72665080-0218-11ea-9c15-8c08ac2572a9.png">

After digging around a little bit, it picks the correct tile after `scene.globe.pick` in `ImageryLayerCollection.prototype.pickImageryLayerFeatures`, but somewhere along the way a different tile gets chosen. I didn't look into it too much after that.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/8567
