### ISSUE TITLE
Expose RequestScheduler in the public API

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8384]
We should consider exposing parts of `RequestScheduler` in the public API, especially concurrency settings like `maximumRequests`, `maximumRequestsPerServer`, `requestsByServer`, and `throttleRequests`. This would give developers more control over tile request concurrency.

In fact before `RequestScheduler` was introduced [`throttleRequestByServer.maximumRequestsPerServer`](https://cesium.com/downloads/cesiumjs/releases/1.34/Build/Documentation/throttleRequestByServer.html?classFilter=throttle#.maximumRequestsPerServer) was part of the public API.

Any reasons not to do this? It would be a quick PR.

**Comment by wadeward** [comment]
Hi guys, just following up on this request . Is it possible that you can provide us an angular-cesium example of how to use the TileProviderError , such as a small snippet of code just to understand how best to capture the errorEvent..thanks

**Comment by OmarShehata** [comment]
@wadeward I think your question is not related to this issue. Please open a thread in the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) with some more information on what you're trying to do.
