### ISSUE TITLE
Setting transparency to 3dtiles caused a crash

### ISSUE THREAD

**Issue by verybigzhouhai** [CesiumGS/cesium#8394]
As the title says, I set the color with transparency for my 3dtiles, and then the program crashes at some point during the program browsing. I tracked the error code and thought that the error might come from a gltf containing a mesh, but the mesh does not contain a primitive, so model._nodeCommands.length is 0. This caused the final crash.
So we need to determine if the first item of the array exists before accessing to solve this problem.
`if (defined(nodeCommands[0]) && (!defined(nodeCommands[0].translucentCommand) || forceDerive)) {
                // code
            }`
https://github.com/AnalyticalGraphicsInc/cesium/blob/63e97a531640b9cdd99b4eb20e1686a99d4f0eeb/Source/Scene/Model.js#L4028
![image](https://user-images.githubusercontent.com/37999729/68833684-093a7d80-06ef-11ea-9e2e-98e61785ad65.png)

**Comment by OmarShehata** [comment]
Thanks for looking into this and opening the PR @verybigzhouhai ! Are you able to provide a Sandcastle example that reproduces this issue? The better fix may be to get the Model primitive to skip the update step if `nodeCommands.length === 0`, because there's at least one other update step that assumes an existence of nodeCommands[0]:

https://github.com/AnalyticalGraphicsInc/cesium/blob/63e97a531640b9cdd99b4eb20e1686a99d4f0eeb/Source/Scene/Model.js#L4268

**Comment by verybigzhouhai** [comment]
@OmarShehata Ok, you are right. I have noticed the same problem with this code before. I will try to reproduce the problem with a simple model, not in the model I am using now.

**Comment by verybigzhouhai** [comment]
@OmarShehata I reproduce this error, using the following code and the gltf file in the attached file. This gltf file contains the mesh, but does not contain any primitives. I want to add this judgment at the same time when judging whether to display the model update, how do you think?Or at an earlier time？
https://github.com/AnalyticalGraphicsInc/cesium/blob/63e97a531640b9cdd99b4eb20e1686a99d4f0eeb/Source/Scene/Model.js#L4737

But there seems to be no way to upload the gltf file as an attachment.I sent it to the gmail mailbox I saw in your profile, if you think this is not a good fit, please let me know the other way.

Below is the code. This error will be triggered when you click the button.

var viewer = new Cesium.Viewer('cesiumContainer', {
    infoBox : false,
    selectionIndicator : false,
    shadows : true,
    shouldAnimate : true
});

var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, -1000);
var heading = Cesium.Math.toRadians(135);
var pitch = 0;
var roll = 0;
var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

var entity;

Sandcastle.addToolbarButton('test', function() {
    entity = viewer.entities.add({
        name : "",
        position : position,
        orientation : orientation,
        model : {
            uri : '1.gltf',
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });
    viewer.trackedEntity = entity;
    entity.model.color = Cesium.Color.WHITE.withAlpha(0.5);
});

**Comment by OmarShehata** [comment]
@verybigzhouhai you can actually host your glTF model on Cesium ion now (https://cesium.com/ion) and then link it in your Sandcastle code.

I can see how this empty glTF reproduces the error, but I was hoping to see how this can be reproduced with a non empty 3D Tileset when setting it to transparent with the styling language (is that how you were setting the transparency?)

**Comment by verybigzhouhai** [comment]
@OmarShehata I tested it according to the method you said, but it is not the same as the expected result. The processing of ceium ion on empty gltf does not generate any tile file, and the box property in tileset.json has a lot of null values. Is this Normal value(null)? so it didn't trigger the same error, the 3dtile file I used before came from the contextcapture software.
Below is a snapshot of the sandcastle link and tileset.json
https://sandcastle.cesium.com/index.html#c=lVRdc9owEPwrGl5sZjIC4kBSQjIl0FIzMSRg8kHcByELkJElKslQ6OS/V8ZOYtKn+kWju9u73T2NKxXQk4hr0CGKJnF/DBDGRCmgBdiJRAIqOEBKEa0CntVAV3AYkjlKmG4fin2xIhxcAYvs+stZD9Mh7buTvVsbUFe5fFTHHbfhrtZPD53+F2iKfoW9VVpEp4+TM6+7cqbjau359Jtz69/XvdjTQ//eGeyqVS96iKYRi6fdtjP0n+ltp7+emmZetHK88Zaix+9VNxK/B75XG3Qney+a1Ob3sHoRPXl6hC4GN5tGIznzVjekfu5G4XPjtIeGPdyIcb379GMWX1iXAQ/4BkmwoWRLpJHByTa3Az4cYraFD9eO4BpRTqR1Av4EHJhPEylN6E6KDQ0NullEZ4d/XGLnyPRLJGuCD1dHRBnLMYFzKeJ2arob2rVyVv9qzteyYZvxhAoTTuCCiRkx21jrpU+Ubi/MJKXzkUaLlgl5V6gpI6apCR/1WEsaU003REEUhnY27h8ZTtfP4P8roF4/O3cKIsoHPmPEQ4yUZiQd6gvBZkjeJFoLblvaSDEezxOOdfoA7fK73xkHqPSOkeNdFWmO03SRKBZMyCYoRNIYD2naXzXBSzEBwIuVGmcoWAegHZT8UXswvmuPvg18EJROQBXWrZ9FUOHy+ib2Ml/Z+9L2QsS+sHMVuSlQ6CWRW6qI/aHYbFDIMjiSwJUwdjGxyLOXhTmlk1LrYMp1FvxK47WQOt2QDWFFk3jNkPG1MkvwyhiIlUphrcobqBXSDaDhVVD69NiDEsDM/AJMZp4wNqZ7EpSuWxVTfwRjAoWUL4YbIhnamZKMSGtZu77NUhDCVsVc07Gf0Tp7AYXOfwE

![image](https://user-images.githubusercontent.com/37999729/69019556-11930100-09ec-11ea-8785-6eadc1d57eb5.png)

**Comment by verybigzhouhai** [comment]
@OmarShehata Sorry, is there such a new development in this question?

**Comment by dzungpng** [comment]
@verybigzhouhai This PR might be fixing the issue: https://github.com/CesiumGS/cesium/pull/9271

**Comment by lilleyse** [comment]
@verybigzhouhai sorry that your PR https://github.com/CesiumGS/cesium/pull/8395 slipped through the cracks but https://github.com/CesiumGS/cesium/pull/9271 was just merged and will hopefully fix this.
