### ISSUE TITLE
could cesium add the technique "_3DTILESDIFFUSE" when using extension "KHR_materials_pbrSpecularGlossiness"

### ISSUE THREAD

**Issue by hanaimin** [CesiumGS/cesium#8396]
Hi,
I generate my glTF material with "KHR_materials_pbrSpecularGlossiness" extension. but this extension not allow using "Cesium.Cesium3DTileColorBlendMode.REPLACE" because of no "_3DTILESDIFFUSE" generated automaticaly.  

the processPbrMaterials.js code logic may be here:
 var baseColorUniform = defaultValue(techniqueUniforms.u_baseColorTexture, techniqueUniforms.u_baseColorFactor);
        if (defined(baseColorUniform)) {
            baseColorUniform.semantic = '_3DTILESDIFFUSE';
        }

Could cesium add the feature for supporting "Replace" color blend mode when using "KHR_materials_pbrSpecularGlossiness" extension?

**Comment by OmarShehata** [comment]
This sounds like it should be an easy fix that should have gone in the initial spec gloss PR https://github.com/AnalyticalGraphicsInc/cesium/pull/7006. 

@hanaimin if you can put together a Sandcastle example testing this, and open a PR to fix it, we'd be happy to review it!

**Comment by j9liu** [comment]
I'm closing this issue since `Model` no longer supports techniques as of the 1.97 release.
