### ISSUE TITLE
memory leak caused by reusable variable

### ISSUE THREAD

**Issue by vinstics** [CesiumGS/cesium#8403]
Sandcastle: [sandcastle](https://sandcastle.cesium.com/#c=ZVLBTuMwEP0VKxziSlmnFCoEDRUCDgghgWi0p1wcZ2gHnHFlO0EF8e84Tbq0Sy72zLx5b+bFrbSsRXgHyy4ZwTu7AYdNLf5uczxW2/DGkJdIYOPRrKAeL5Q26k2oxlogn2MNhwz3jUZJt9IDn5xOz6aTiTienp6dTzqKQBKEPWpw4A/7+uPkNu+L/LMgFr7G6gsWC5EuZL3WEHhlegBN7xCstGq1Sa+lV6tclhp+coOWeHWG4oK+hin6VZwCArG2WKPHFpyQVcWHjr2NP4ypc7MrJPtT34GskJZPGJSfJS2Bj8U4YX/G4iRh4Trq9V4aUh4NsQqct2bDR8N6g8K/dEB/FaQMOaNBaLPkC0mVks5r6Io/UTdrbowupb1uvDfE44ElTobLaBYlUeb8RsO8l7vCem2s71zlwVMPwdPwp1xaNuotuKSc61Q66JHvyVm5ZWefrEIX0JsLVnYvYMbCoFm6Y88qbBlWl0X039MpIqa0dC5UXhqtF/gBRTTP0oA/aNNm6+RjCzaIdJDV8fyhTwohsjSEv7uGIfcYvwE) (run and click destroy button several times and then use F12 to take heap snapshot)
Browser: Chrome 78
Operating System: Windows 10

Some module scope reusable variable will "remember" last model after destroy when I use Cesium by "window.Cesium". How can I avoid this? Example:
![image](https://user-images.githubusercontent.com/16721670/69037699-49696b00-0a23-11ea-8042-d9e8390fe845.png)
![image](https://user-images.githubusercontent.com/16721670/69037787-7ddd2700-0a23-11ea-8c80-0a09b4d7f1c3.png)
Some of them can have a workaround like below:
![image](https://user-images.githubusercontent.com/16721670/69037912-bda40e80-0a23-11ea-8684-9293f1882c37.png)

**Comment by OmarShehata** [comment]
@vinstics did you figure out why you were seeing a memory leak here?

**Comment by vinstics** [comment]
> @vinstics did you figure out why you were seeing a memory leak here?

@OmarShehata Caused by closure. It had been clearly described in my post. You can search the highlighted key word in the source code to see what happened. I want to fix but too many such use case and I'm worried about introducing side effects.
