### ISSUE TITLE
something wrong , setting polygon extrudedHeight and perPositionHeight 

### ISSUE THREAD

**Issue by xxbld** [CesiumGS/cesium#8416]
var orangePolygon = viewer.entities.add({
    name : 'Orange polygon with per-position heights and outline',
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArrayHeights([-108.0, 25.0, 300000,
                                                               -104.0, 25.0, 200000,
                                                               -100.0, 25.0, 300000,
                                                               -100.0, 30.0, 300000,
                                                               -104.0, 30.0, 200000,
                                                               -108.0, 30.0, 300000]),
        extrudedHeight: 0,
        perPositionHeight : true,
        material : Cesium.Color.ORANGE.withAlpha(0.5),
        outline : true,
        outlineColor : Cesium.Color.BLACK
    }
});
Sandcastle example: 
![image](https://user-images.githubusercontent.com/13309211/69589417-f9903280-1026-11ea-9443-98290e4333c1.png)

**Comment by hpinkos** [comment]
Thanks @xxbld, this is a known issue.  I've added a comment to https://github.com/CesiumGS/cesium/issues/2924 so we can notify you when we have a solution.
