### ISSUE TITLE
[Documentation] Cesium.PostProcessStageLibrary.createSilhouetteStage

### ISSUE THREAD

**Issue by Crocsx** [CesiumGS/cesium#8418]
From the [Documentation](https://cesium.com/docs/cesiumjs-ref-doc/PostProcessStageLibrary.html)

`Cesium.PostProcessStageLibrary.createEdgeDetectionStage` do not accept any parameters.

but in this [Sandcastle](https://sandcastle.cesium.com/?src=3D%20Tiles%20Feature%20Picking.html)

An array of `PostProcessStageComposite` is passed as parameter.

I believe the doc should be updated for the post process effects

**Comment by hpinkos** [comment]
Sorry we missed your question @Crocsx .  If you are still having issues, please comment on the Cesium Community Forum: https://community.cesium.com/

**Comment by lilleyse** [comment]
I opened the doc fix here: https://github.com/CesiumGS/cesium/pull/8957
