### ISSUE TITLE
How to change billboard visibility and positions for entity loaded via KML

### ISSUE THREAD

**Issue by keikland** [CesiumGS/cesium#8420]
I routinely read KML files into Cesium and have a jstree where I store name of and reference to the hierarchy of entities.   While I can easily  change visibility and shapes of the entities, the billboard is not defined and is not among the children.  I have traced some billboard references to visualizers in the var items = KMLdatasource._visualizers.BillboardVIsualizer._items AssociativeArray.   This stores  billboard,entity pairs, which looks like what I am after.  If i then do items.get(entity.id.slice(0,-2)+'pt').billboard I get the object I seek. This logic/operation seems very awkward, though, and is probably not stable.  Any suggestions about how I can do this more directly and without exposing myself to future Cesium logic changes?

**Comment by OmarShehata** [comment]
Thanks for bringing this up @keikland. At first glance this does sound like a feature request that would make sense to add. Can you share a [Sandcastle example](https://sandcastle.cesium.com/index.html?) with a sample KML that contains a billboard and your current workaround for obtaining it from the entities list? That'll help us triage what all needs to be done for this feature.

**Comment by keikland** [comment]
Sure, I will see what I can do in the simplest possible way.  I was able to find a much better approach after the post and have now implemented KML billboard /point animation using the time slider and Ajax.

Kjell

On 13 Dec 2019, at 23:37, Omar Shehata <notifications@github.com> wrote:

﻿

Thanks for bringing this up @keikland<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeikland&data=02%7C01%7C%7C43b7ef44bf3e47d83f4208d7801cf7ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637118734209383707&sdata=47P9OrE5Mk0V3BNSgjcyH0WujLUuWVDH4EcO5utFNuU%3D&reserved=0>. At first glance this does sound like a feature request that would make sense to add. Can you share a Sandcastle example<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsandcastle.cesium.com%2Findex.html%3F&data=02%7C01%7C%7C43b7ef44bf3e47d83f4208d7801cf7ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637118734209383707&sdata=%2BNMUo7xBgFHhZAlOhfOd7TvjWlDvxptFshOhC%2FpWVT8%3D&reserved=0> with a sample KML that contains a billboard and your current workaround for obtaining it from the entities list? That'll help us triage what all needs to be done for this feature.

**Comment by OmarShehata** [comment]
@keikland can you share the current approach? If there's a good way to do this without making a change to the core library that would be great and we can close this issue.

**Comment by keikland** [comment]
Hi. I think you can get the gist of it with the code below, which is a simplified version of my working code that updates positions when the timeslider changes.  Basically two parts: 

1) identify the KML placemarks/Cesium entities of interest based on KML extendeddata.  (It could be generalized to other criteria too.) 
2) Iterate over the Cesium entities and find if an array of new Lat/Lon positions target the specific KML placemarks, along with an optional visibility of entity children.

Hope it makes sense, and good luck.
Kjell

// Get a map of KML Cesium entities of interest.
function KMLcollectChildren(kmlSource, placemarkExProp) {
    var kmlEntities = new Map(), entities = kmlSource.entities.values;
    for (var i = 0; i < entities.length; i++) {
        if(Cesium.defined(entity._kml.extendedData) && Cesium.defined(entity._kml.extendedData[placemarkExProp]))
                kmlEntities.set(entity._kml.extendedData[placemarkExProp].value, entity);
        }
    }
    return kmlEntities;
}

// Set new positions of placemark billboards and change visibility of associated objects
var scratchCartesian3 = new Cesium.Cartesian3();
function KMLchangePositions(kmlSource, kmlEntities, idPositionsArray, placemarkExProp, assocVisible) {
   // Make position mapper
   mapper = [];
   idPositionsArray.forEach(function(item, idx) {
    	mapper[item[placemarkExProp]] = idx;
    });

   // Update entity elements
    kmlSource.entities.suspendEvents();
    for(const [id, entity] of kmlEntities) {
    	var decorators = entity._children;
	if(decorators && decorators.length) {
		var idx = mappert[id], position = (idx === undefined ? null : idPositionsArray[idx]);
	    	for(var i=0; i < decorators.length; i++) {
	    		var item = decorators[i];
                        // Hide/show allociated placemark children (here polyline only)
	    		if(item.polyline && (item.polyline.show != assocVisible))
	                	item.polyline.show = assocVisible;
                        // Hide/show billboard if no position is given
	            	if(item.billboard && (item.billboard.show == (position === null)))
	                	item.billboard.show = assocVisible;
                        // Update billboard position
	            	if(position && item.position)
	                	item.position = Cesium.Cartesian3.fromDegrees(position.Lon, position.Lat, 0, Cesium.Ellipsoid.WGS84, scratchCartesian3);
	    	}
	}
    }
    kmlSource.entities.resumeEvents();
//  updateScene();
}
