### ISSUE TITLE
Shading effect for partial terrain

### ISSUE THREAD

**Issue by cr8tpro** [CesiumGS/cesium#8423]
I am going to apply shading effect to terrain.
Applying to entire globe layer is possible but for partial rendering is impossible.
In Cesium, load terrain using CesiumTerrainProvider and it doesn't support material property.

https://sandcastle.cesium.com/?src=Globe%20Materials.html

This sample shows how to apply shading effect to entire globe layer.
But when I load specific terrain like 
       viewer.terrainProvider = new Cesium.CesiumTerrainProvider({
            url: Cesium.IonResource.fromAssetId(asset_id),
            requestVertexNormals: true
        });
        console.log (viewer.terrainProvider);
and I can't find material property in terrainProvider. Also it affects entire globe layer when I load specific partial terrain.
I think it would be good if there is feature to style partial terrain, not entire.

Best
Bojan

**Comment by wq8806** [comment]
I meet the same problem，Could anyone provide some help？

**Comment by hpinkos** [comment]
Sorry we missed your question @cr8tpro .  If you are still having issues, please comment on the Cesium Community Forum: https://community.cesium.com/

**Comment by cr8tpro** [comment]
I am not sure why you closed this issue. Cesium itself doesn't provide shading effect for self loaded terrain.

**Comment by hpinkos** [comment]
I'm sorry @cr8tpro, I misread what you were asking for. 

Terrain inherently covers the extent of the entire globe, so you're right that can't apply that material styling to just a sub-section of the terrain.
Unfortunately, I don't think this is a feature we're going to add to open source CesiumJS.  We have additional analytics features such as measuring slope and shading a polygon drawn on terrain based on the slope as part of our Cesium Analytics package.  You can learn more about this here: https://cesium.com/ion-sdk/
