### ISSUE TITLE
How to change northUpAxisfactor value in EntityView.js？

### ISSUE THREAD

**Issue by hanyingling** [CesiumGS/cesium#8426]
How to change northUpAxisfactor value in EntityView.js？
更改northUpAxisfactor值？如何更改northUpAxisfactor值

function createModel(url, height) {
    viewer.entities.removeAll();

    var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, 3e8);
    var heading = Cesium.Math.toRadians(135);
    var pitch = 0;
    var roll = 0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            uri : url,
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });
    viewer.trackedEntity = entity;
}

createModel('../../SampleData/models/CesiumAir/Cesium_Air.glb', 3e8);

**Comment by hanyingling** [comment]
或者：  var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, 3e8);
    var heading = Cesium.Math.toRadians(135);
    var pitch = 0;
    var roll = 0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            uri : url,
            minimumPixelSize : 128,
            maximumScale : 20000
        }
    });
    viewer.trackedEntity = entity;

**Comment by hanyingling** [comment]
如何更改 deep space 距离 ？

**Comment by hpinkos** [comment]
Sorry we missed your question @hanyingling.  If you are still having issues, please comment on the Cesium Community Forum: https://community.cesium.com/
