### ISSUE TITLE
Edge Test Failure - SkyAtmosphere draws sky with color correction active

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8429]
```
Scene/SkyAtmosphere draws sky with color correction active
Expected [ 0, 0, 0, 255 ] not to equal [ 0, 0, 0, 255 ].
```

http://localhost:8080/Specs/SpecRunner.html?built=true&release=true&spec=Scene%2FSkyAtmosphere%20draws%20sky%20with%20color%20correction%20active

May or may not be related to https://github.com/AnalyticalGraphicsInc/cesium/issues/7896 which seems to have fixed itself as of 1.64.

**Comment by ggetz** [comment]
Closing as no longer reproducible.
