### ISSUE TITLE
exportKML throws error in IE11

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8432]
The [exportKml Sandcastle](https://sandcastle.cesium.com/index.html?src=Export%20KML.html) does not work in IE11. The Sandcastle itself fails silently because it's missing a `.otherwise(console.error)`, but it's not just a download issue. Looks like this line fails in IE11:

https://github.com/AnalyticalGraphicsInc/cesium/blob/e5548f7166001180cc3fd46421f2f210b4b2dc66/Source/DataSources/exportKml.js#L390

With the error `TypeError: Argument not optional`.

**Comment by ggetz** [comment]
Closing die to dropped IE 11 support.
