### ISSUE TITLE
Incorrect computeBoundingSphere defined(...) check 

### ISSUE THREAD

**Issue by chrisdirkisaurecon** [CesiumGS/cesium#8458]
In ModelUtility.js, line 210, there's a check to see if min and max are defined:
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/ModelUtility.js#L210

However, in this scope, min and max are already defined. Either the check should be for amin and amax, or the gltf accessor's min and max should be asserted to be required somewhere.

Sandcastle example: n/a

Browser: n/a 

Operating System: n/a

**Comment by chrisdirkisaurecon** [comment]
The pull review/patch is obvious, so sorry for not submitting :)

**Comment by OmarShehata** [comment]
Thanks for pointing this out @chrisdirkisaurecon ! Do you have a test case, like a glTF model you've used, to show that it produces an incorrect result? 

It would also be great to have a contribution submitted to improved this! You can check out the [contributing guide here](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).
