### ISSUE TITLE
Prepare Chromium-based Edge release

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8468]
The "new Edge" based on Chromium comes out on Jan 15th, but beta/dev/canary builds are already available at https://www.microsoftedgeinsider.com/en-us/.  They support both Windows and Mac (as well as Android).

We should do some initial testing on Cesium to make sure there are no surprises and everything works.  I expect it to go smoothly since it's essentially Chrome.

One thing we should verify is `FeatureDetection` Currently, `FeatureDetection` has functions such as `isEdge`, `isChrome`, etc.. when the "new Edge" comes out based on Chromium, it's user agent will be changing once again.  We need to figure out if `isEdge` works on the new Edge or if it's going to return false.  The version number will also jump to be on par with Chrome.

I think what we want is to rename current `isEdge` and `edgeVersion` functions to `isLegacyEdge` and `legacyEdgeVersion` and just write new versions for the new Edge.  Once "old Edge" is dead (which I think will happen fairly quickly) we can then remove the legacy versions.

**Comment by mramato** [comment]
I marked this next release since the new Edge is slated for Jan 15th we should at least confirm that Cesium works before our next release.

**Comment by mramato** [comment]
I did initial testing of Sandcastle examples and no big surprises.  We can do more thorough testing once the official version is out.  I'll leave this open until we know all tests are passing

**Comment by mramato** [comment]
Running the unit tests on today's official release, I only had 3 failures, all related to `DeviceOrientationEvent` not being defined.  Tests should probably check for this and be skipped if it's not supported.

**Comment by hpinkos** [comment]
@mramato can this be closed?  what is left to do here?
