### ISSUE TITLE
How to improve scene performance when there are a large numbers of GroundPrimitives in the scene?

### ISSUE THREAD

**Issue by LyjPeppers** [CesiumGS/cesium#8484]
I've met some performance problems, I wonder if someone can give me some advice on the following questions:
          1  I need to render one vector layer which contains about 5430 ground polygon with outline, I added a PrimitiveCollection which contains a GroundPrimitive with all the polygonGeometry  in the same GeometryInstance array and a GroundPoyline with all the polygonGeometry  in the  same GeometryInstance array. But when I observe the vectorlayer from different perspectives ,the scene  show two kinds of performance. On top of the entire vector layer, it shows a nice FPS about 60.But the FPS decreses to the range from 9 to 24 while I change  the perspective of camera horizontally.
         2. The 5430 polygon contains 446540 vertex and some of them have a public side.
         3. The method I added the vector layer is just same to the link of [.](https://cesium.com/docs/tutorials/geometry-and-appearances/).  I had tried an example in sandcastle like this:
        const geometryInstanceList = [];
        for (let i = 131.001; i < 132.001; i += 0.001) {
            for (let j = 46.001; j < 46.100; j += 0.001) {
                const instance = new Cesium.GeometryInstance({
                    geometry : new Cesium.PolygonGeometry({
                      polygonHierarchy: new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray(
                          [i, j,
                          i, j + 0.001,
                          i + 0.001, j + 0.001,
                          i + 0.001, j]), []),
                      vertexFormat: Cesium.PerInstanceColorAppearance.VERTEX_FORMAT,
                      extrudedHeight: 0
                    }),
                    attributes : {
                        color : Cesium.ColorGeometryInstanceAttribute.fromColor(Cesium.Color.fromRandom({alpha: 1}))
                    },
                    id: 'circle'
                });
                geometryInstanceList.push(instance);
            }
        }
        const primitive = new Cesium.GroundPrimitive({
            geometryInstances : geometryInstanceList,
            appearance : new Cesium.PerInstanceColorAppearance({
                translucent : false,
                closed : true
            })
        });
        viewer.scene.primitives.add(primitive);

        How can I improve the scene performance above?  Does someone give me some suggestions for optimization?  Thank a lot!!!

**Comment by tommulder** [comment]
I have this issue also. I have a large geojson where i want outlines and rendered interiors of approx 1200 polygons clamped to terrain. The top down view is ok but zooming into it and changing the view slows the frame rate to an unuseable speed. I have resorted to turning off rendering of the polygons when the camera moves (using camera onStart and onStop events).

**Comment by OmarShehata** [comment]
I think the right solution here is Vector Tiles: https://github.com/CesiumGS/cesium/issues/2132. Closing in favor of that issue, but feel free to search through or post on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) about ways to optimize your particular application.
