### ISSUE TITLE
Polyline drawing on 2D map is not correct when crossing 180E

### ISSUE THREAD

**Issue by icgp** [CesiumGS/cesium#8490]
I drew four lines in the ICRF coordinate system. They move in the earth fixed coordinate system. When the red line crosses 180E, its drawing is not correct, and the other three lines are OK.

https://sandcastle.cesium.com/#c=vVZRT9swEP4rVl9IIHWTjklbW9Cm0m1IMCaotgfKg0ncYs2xI9splIn/vrPjNEm3IW1Iy0Nin7/77vPd2e2aKLRm9J4qdIQEvUdTqlmZ46/OFuylbjqVwhAmqNqLfiwEgkenVNBzmdGRd7iqDfhqOvs8G55EFTAnhbUOT9Co5j6vTfjyYv5+PluIp3C8EAuxBjEcwnxjmbkDPYfjxjaVXFqNnsNN8cdPF1fzb59O5zOPzImhihHe3cy5twZe/JLcKpaOkJ/ax2wKOkJ7jnYvauylYEupct0B2ye1yFEjrVl9qoZPfltW1m25+u/KOom6nJ08K7CQfGO3orvyvngzkHCaGiZFUHtkQ1sN0H+Hv5wOkjextyuSsdLSJHH1eLumq5wKk8pSGFgdxp2Kx2BKFYVsnMEsiKP+4et9CBH5TxxVvFGbxkrZCscky4IfsBHNrE5dlSaO0L1tplHTV9G2SUZNu+w0YNKV8zZ2ImpNyauXiUr+TdSwK6oPOe/I6r9U1/DvdUFjWzE7ynby1X9BEX2A55W1j1ctzt1f2F1TuFAsB8K1D7AN91sovaQigzkgZ2tQeca0gRUVLEvhjgAKHDRChuU0rE+fzQZL1XIuP7AHmjU31VwRod1JxanMi9LQ0wYG50exh8AxjSsitkSBd83oEmRmQYs3DNvH3QY1NX8TsmI9xEsl80tpiFXtZHA37PCNG7amDDlcz7xiAdZthHH34liIbUo4H65pGnCxiiBG2MpJKvUZMfVVAbPAAjyToqZUAl03a2IV7lcukTNqJv5gBJYboHnq6Gh1IXjB6QeYfYtV4sbw9j1YX0hT14TtKgJYF0SAZMuRoL61xCEadFzGLQditg4QwjpA1OccqiNzfeNtkFsUuAYCazyGz+So64vYwcEvlQdZgLfi0AH47NfKxzswl34rqYZVel0F20CooAV2S7lDZvsBlq/jGyCqUrmD2HhE8kfEo0cMO4gGY9ODi1LfBa2foilRBkZEvAoeok30GIZNN7ZayfpWXdGLehNtNpweV4B3LC+kMqhUPMB4YGhewP6oHtyW6XdqcKrdfTAZ1E6TjK0Ry44WvZ0/QYseSjnRGlaWJedX7JEueseTAeA7blzC3sTqYk0VJxsLuUuOzyojxngygOmvXkZKfktUi/En
![errorline](https://user-images.githubusercontent.com/12581997/71317129-1a796580-24b7-11ea-8365-dc4653637bda.png)

**Comment by hpinkos** [comment]
I was not able to reproduce this: 
![image](https://user-images.githubusercontent.com/3451886/84539741-fc502d80-acc1-11ea-8945-f12d0813c43b.png)

@icgp if you are still having an issue with the latest version of Cesium, feel free to reopen this.  Thanks!
