### ISSUE TITLE
Single page application, memory overflow

### ISSUE THREAD

**Issue by IKangXu** [CesiumGS/cesium#8492]
Single page switch route and re create a three-dimensional ball. The memory of the last three-dimensional ball cannot be released. After multiple switches, the memory will only grow on the Internet. The three-dimensional ball is placed in the global variable. It is not in the state management of any single page application framework. Please ask how to release the cache of the model loaded by the previous route correctly. It is very urgent

**Comment by hpinkos** [comment]
Sorry we missed your question @IKangXu.  If you are still having trouble, please post on the Cesium Community Forum: https://community.cesium.com/
