### ISSUE TITLE
Move cesium map by javascript on iOS

### ISSUE THREAD

**Issue by pqhuy87it** [CesiumGS/cesium#8495]
![IMG_0105](https://user-images.githubusercontent.com/5575899/71494819-7d8b4380-288d-11ea-9422-d8762b9fe874.PNG)
![Screen Shot 2019-12-27 at 9 41 58](https://user-images.githubusercontent.com/5575899/71494823-824ff780-288d-11ea-8b5d-0892ef506202.png)

I am working with cesium map, i want to display weather information on over map. I created an overlay, when i move on overlay to change area i want map below also change. I can pass location include longitude and latitude by javascript but i don't know how to apply them into cesium to move map, can you instruct me?

**Comment by OmarShehata** [comment]
There's a lot of options here depending on what you're trying to do. One way is to turn off the screen space camera controller and control the camera directly like in this code example: https://sandcastle.cesium.com/index.html?src=Camera.html

If you're still having trouble please use the Cesium community forum for questions: https://community.cesium.com/
