### ISSUE TITLE
How to display an line at high position in 2D?

### ISSUE THREAD

**Issue by Rokkregin** [CesiumGS/cesium#8497]
I want to show an line in 2D mode,but the line has a large height like link below.
It can be displayed correctly in 3D mode,but when we change to 2D mode,only lower parts can be displayed.
So how to display a line with large height in 2D mode?
https://sandcastle.cesium.com/#c=xVdtb9owEP4rFl/KpCwklKxbS6ttdOqXrqC12qQ1/WCSK7Hq2JHtgOjEf98l5rVAJrRsjQDFvud8d34e2ceYKhI9p5yck/tfoSD4hA0Whw1yii+xjPIUhAkbzsImaApza+/n12tyBTIFoxjoUzKQfMqZgDX4GJRmUsw9fNcLG6GYOWQ7loL4etN3LdQ3iEmxMok4TTMcGEkMKMrEGj5bhkefeYCFRTODaeiXJmuOqDJypGiWsOgSRgrAAu83gcXz9iRwyDF+PWeH0W8vrJvGh9Vw5qwnllKsglG+Oy8tOYt7kku1yz7PvcpsIWo0pLaedlBmXnzw9WHbYbY5NduX94TFJinXDDbmS3ru5JWSubDEGpWDRcz2ED/kOexn/orLCRMjUqCsBKQgJgGic/VII3gV/k8q+T+pi/9FQcUe1KQA30Pu/c4HFECR5x4VOLvijDCLgZyAjeW57Z0oQzNQ67DgYEn5XrVgpKJiVCGZfmm3Ypkwk6B2aPREZG7KKWpIAmyUGEJFTB4lnyvstUVVcBJ4+OxX1hJSq7z6dmPqPGP8d0HVKbNTOXN+eocE8/5wnFUF+rEUXPvwU69aoVmuMl6h0EFpJ1QpOVnp8TVU1zl2SKmoKt2tQLXq7lNRfl3nWue91YHv/+3dRlV0N80WVN30b74siTn0pIqpTqrams/FpWZB5EXj9P8UECzI3c9/8E/4v8TCa6LfngCrn1pam86K3IezUIRijM3ymAHebdguC5iQHmiWp+73cq55FJXDnhQGG1NQR2/OrE9MDb2VuYpgoGTKNKD73LWHvffl0uxySeNm0Y+XruWy7spbuzSOm1urrWGfpUzv5G5IUU3DaXS1mXK4CMVHlmZSGZIr3nTdloE048ibbg3z6AmMG2lduHVbC4duzMaExefIzWahuFvY+GmNlsec81v2jLK96LYQv+FWVIc3bR//FHA6LSCJf3FtJ13X7bZwuO1lpORDqtZWDMVv

**Comment by hpinkos** [comment]
Sorry we missed your question @Rokkregin.  If you are still having trouble, please post on the Cesium Community Forum: https://community.cesium.com/
