### ISSUE TITLE
how to clip or flatten multiple terrain or 3d tiles

### ISSUE THREAD

**Issue by DepapepeOne** [CesiumGS/cesium#8501]
:exclamation: Please use the [forum](https://groups.google.com/forum/#!forum/cesium-dev) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

**Comment by OmarShehata** [comment]
You can use clipping planes to clip areas in 3D Tiles or terrain: https://sandcastle.cesium.com/index.html?src=Terrain%20Clipping%20Planes.html. 

Multiple clipping planes are not yet supported, see: https://github.com/CesiumGS/cesium/issues/8751
