### ISSUE TITLE
Fog too strong at some angles

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8502]
Fog can be too strong at certain angles.

This is especially true if the camera is below ground but it can also happen if there's a big elevation difference between foreground and background.

[Sandcastle](https://sandcastle.cesium.com/#c=bZFvb9sgEMa/CvKbupKLDYaANzealE1apf2ptqjVJL+h9nVFw1ABcdtN++4jcSJlbXkFd/c8v+NuUh71EPRmvHbeDGvwXmmLztFqF8S9BxXhOJefvu3slGSThgfwqdTCw6H8ahfLT2bLlbMxKcCfFOhPZ1E6cTa59G7SQ1K/eYXe2b9bRqLs3HDowQLu1Qhe4QBxC8n3fgOEqK2K2tnkddTJSvmYbsrW+RmTQjY1wQshpCQ1WRSIVYI2C45ZXTVSNISKAp1xxgUTmDaNrCgXgp4WM8V5DekrLykfQQ3a/rzUsb/75ozJK0yZIJxSUUlBZC05T8YVrgjnIpFrmloRRNSphwWmsq5YxTmhlBF2oIEd1l7ZcOv8mHB71GcVvX5k+OL9hy/ri/WP/ZSyImtDfDKwnMXv9HjvfEQbb3KMywjjvUkbDOXNpv8FEfchbGVteRC1g56QHs677NnSugz1RoWQMrcbY77r39Bly7ZM9f/JjNvN4OsE3qinbckdWX6agxjjtkzPl6ronLlR/sjxHw)

![artifacts](https://user-images.githubusercontent.com/915398/71627828-e55dc900-2bc2-11ea-8e0a-94f7240f2235.gif)

**Comment by ggetz** [comment]
Given the latest atmosphere updates, this no longer appears to be an issue.

Without lighting
<img width="853" alt="image" src="https://github.com/CesiumGS/cesium/assets/4439461/2568373d-f1a5-4b81-845b-946ff2db69bf">


With lighting
<img width="850" alt="image" src="https://github.com/CesiumGS/cesium/assets/4439461/8b13a7aa-0f2a-40ba-889d-7580cf309943">
