### ISSUE TITLE
Alphabetical ordering in Specs

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8512]
Now that spec files import from `'../../Source/Cesium.js';` should we include all files alphabetically?

This used to look like
```js
define([
        'Core/CesiumTerrainProvider',
        'Core/Rectangle',
        'Core/Resource',
        'Scene/Globe',
        'Scene/SingleTileImageryProvider',
        'Specs/createScene',
        'Specs/pollToPromise'
    ], function(
        CesiumTerrainProvider,
        Rectangle,
        Resource,
        Globe,
        SingleTileImageryProvider,
        createScene,
        pollToPromise) {
        'use strict';
```

and now looks like

```js
import { CesiumTerrainProvider } from '../../Source/Cesium.js';
import { Rectangle } from '../../Source/Cesium.js';
import { Resource } from '../../Source/Cesium.js';
import { Globe } from '../../Source/Cesium.js';
import { SingleTileImageryProvider } from '../../Source/Cesium.js';
import createScene from '../createScene.js';
import pollToPromise from '../pollToPromise.js';
```

but should it be

```js
import { CesiumTerrainProvider } from '../../Source/Cesium.js';
import { Globe } from '../../Source/Cesium.js';
import { Rectangle } from '../../Source/Cesium.js';
import { Resource } from '../../Source/Cesium.js';
import { SingleTileImageryProvider } from '../../Source/Cesium.js';
import createScene from '../createScene.js';
import pollToPromise from '../pollToPromise.js';
```

Could be a super simple beginner issue? @mramato thoughts?

**Comment by mramato** [comment]
The ordering doesn't matter in practice so I'm not sure this is worth spending time on.  Do other devs feel like this helps our code base in some meaningful way that I'm missing?

That being said, I'm not against keeping stuff sorted, but it should probably be validated with eslint and use an automatic process that already exists, instead of us string to role our own.  All modern IDEs have this ability already built in, I'm sure there's an eslint rule or gulp task we could use as well.

**Comment by lilleyse** [comment]
eslint has a [`sort-inputs`](https://eslint.org/docs/rules/sort-imports) rule and it seems to detect the problems. For whatever reason I couldn't get it to make the changes with `--fix`. I might look into this again later.

**Comment by hpinkos** [comment]
I agree with Matt that ordering doesn't matter, so I'm going to close with. It's not important enough to spend more time on.
