### ISSUE TITLE
Keep (very) old browser support?

### ISSUE THREAD

**Issue by fredj** [CesiumGS/cesium#8515]
Hi all,

Cesium is currently able to gracefully degrade on old browsers [without ES5 support]( https://caniuse.com/#feat=es5).

Is that something that you want to keep?
If it's not the case:
 - [x] `Core/defineProperties` (#8633)
 - [x] `Core/freezeObject` (#8640)
 - [x] `Core/isArray` (#8526)

can be removed while still maintaining gracefully degrade for IE >= 9

See also https://github.com/AnalyticalGraphicsInc/cesium/issues/4554#issuecomment-257316621

**Comment by OmarShehata** [comment]
I believe we only officially support IE11+, so this sounds like this would be OK to remove these. I'm marking this issue as "cleanup".

**Comment by fredj** [comment]
I think everything has be done, closing

**Comment by mramato** [comment]
Thanks again for your work on this @fredj!
