### ISSUE TITLE
polyline width error

### ISSUE THREAD

**Issue by hanyingling** [CesiumGS/cesium#8519]
var viewer = new Cesium.Viewer('cesiumContainer');
var glowingLine = viewer.entities.add({
    name : 'Glowing blue line on the surface',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArray([-75, 37,
                                                        -125, 37,
                                                       -125,20]),
        width : 1000,
        material : new Cesium.PolylineGlowMaterialProperty({
            glowPower : 0.2,
            taperPower : 0.5,
            color : Cesium.Color.CORNFLOWERBLUE
        })
    }
});
viewer.zoomTo(viewer.entities);
Error：
![cap](https://user-images.githubusercontent.com/33933148/72033825-5b9eb180-32ce-11ea-94b5-1a2f0291e1b1.PNG)

**Comment by OmarShehata** [comment]
I think these are the same issues described here, just more obvious with a larger width: https://github.com/CesiumGS/cesium/issues/4011
