### ISSUE TITLE
how can i add a CylinderGeometry in the way of  adding  primitive

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium#8524]
![image](https://user-images.githubusercontent.com/39166385/72202099-90f5fb80-3496-11ea-861a-045b7ab57cfd.png)
in this constrctor,i can't find position parameter,so how can i add a CylinderGeometry in the place where i want to put

**Comment by Hiwen** [comment]
You can code like this, I wish this can help you!

    var geometry = new Cesium.CylinderGeometry({
      length: 1,
      topRadius: 10,
      bottomRadius: 10,
      slices: 12,
    });

    var m = Cesium.Matrix4.multiplyByTranslation(Cesium.Transforms.eastNorthUpToFixedFrame(
        Cesium.Cartesian3.fromDegrees(113, 36)), 
      new Cesium.Cartesian3(0, 0, 0), 
      new Cesium.Matrix4()); 

    instances[i] = new Cesium.GeometryInstance({
      geometry: geometry,
      modelMatrix: m,
      id: ‘yourid’
    });
  }

  viewer.scene.primitives.add(new Cesium.Primitive({
    geometryInstances: instances,
    appearance: new Cesium.MaterialAppearance({
      material :  new Cesium.Material({
        fabric : {
            type : 'Color',
            uniforms : {
                color : new Cesium.Color(1.0, 0, 0, 1.0)
            }
        }
    }),
      faceForward : true
    }),
    allowPicking: false,
    interleave: true,
    releaseGeometryInstances: true
  }));

**Comment by OmarShehata** [comment]
Thanks for the code example @Hiwen. 

@engineerhe please use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) for general questions. You might also find this guide helpful on understand how to construct geometry with the primitive API in CesiumJS: https://cesium.com/docs/tutorials/geometry-and-appearances/
