### ISSUE TITLE
Custom Model rendering issue/default Cesium rendering issue

### ISSUE THREAD

**Issue by devond5** [CesiumGS/cesium#8562]
[ForCesium.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/4099828/ForCesium.zip)

Attached in the Zip file is the model I am using and a video of the issue I am seeing for your reference. 

I work for a company that is using a more detailed model of the one provided, and are seeing this model rendering issue. It is prominent when the model is loaded into a cesium sandbox. However, I also loaded the model into the gltf vs code extension and saw a similar result. The thing that makes me think this is a Cesium problem is from the video you can see I first view the model and animations in Babylon.js and there are no issues, but when I view the model from the Cesium model preview I see the problem. The filament sheet when it is close or intersecting another object with some camera changes there is a blending issue. For instance, if you rotate to the bottom of the model after the animation, the filament is clearly intersecting the black rectangle but with a move of the camera the filament is more prominent and the black rectangle is hidden. Also when the filament is fully animated and you rotate around the purple filament brace blends through the filament.

This is a problem for my employer because the accuracy of the model is of the upmost importance. The modelers of the model have also tried adding UV's and image maps but that did not solve this.

In the sandcastles I have messed around with frustums, camera properties, etc. I was not able to find an immediate solution. 

While you are looking at this issue and determine it is something on the model side that needed to be changed to fix this then let us know what it is so that our modelers can determine how to create for Cesium users, but I would think that cesium out of the box should be able to handle models the way babylon.js or three.js can.

Cesium Version: "1.61.0"
Sandcastle example: Load attached glb or gltf into the 3D models sandcastle to see the blending problem.

Browser: Chrome 79.0.3945.117

Operating System: Windows 10 Enterprise(1809)

Devon Despain

**Comment by sanjeetsuhag** [comment]
@devond5 This is a known issue related to [logarithmicDepthBuffer](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html#logarithmicDepthBuffer). 

Turning this option off makes the bottom of the box visible through the filament:

`viewer.scene.logarithmicDepthBuffer = false;`

**Comment by devond5** [comment]
Perfect we were tying to figure this out for the longest time!!

**Comment by mramato** [comment]
@devond5 I'm glad you are happy with this workaround, but I've re-opened this issue since it should be fix for when the depth buffer is enabled as well.
