### ISSUE TITLE
FooGraphics documentation should explain the limitations of outlineWidth

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#8577]
Sandcastle example: open any basic shape (e.g. Rectangle) and try to set an outlineWidth, or search "outlineWidth" on this tracker and read any of a bunch of existing issues, starting with #40 (!)

Browser: any

Operating System: Windows only, apparently

Since the very beginning of Cesium, people have been trying to use the `outlineWidth` property on EllipseGraphics, RectangleGraphics, PolygonGraphics, etc, then coming here or to the mailing list to complain that it "doesn't work".  The reason why is explained over and over in those issues, and boils down to the ANGLE engine only supporting a width of 1, which is reflected in `scene.maximumAliasedLineWidth`.

Rather than having this conversation here every few months, please update the docs for this property in those various classes to add a note along the lines of

> NB: this property will be ignored on all major browsers on Windows platforms.  For technical details, see (link to one of these issues).

Previous issues: #40 #4223 #4352 #6667 #7022 #7265 #8485 #8523

Affected classes (tested):
* BoxGraphics
* CorridorGraphics
* CylinderGraphics
* EllipseGraphics
* EllipsoidGraphics
* PlaneGraphics
* PolygonGraphics
* PolylineVolumeGraphics
* RectangleGraphics
* WallGraphics

Of note, PolylineGraphics clearly isn't using the underlying GL engine's outline mechanism and works as expected.

**Comment by OmarShehata** [comment]
I fully support this. (Even I made this mistake at one point and I was definitely aware of the ANGLE issue before). I think people will still be confused when it doesn't work, but at least then the answer will be in the doc. This will no longer be an issue when we switch to use polylines for all lines: https://github.com/AnalyticalGraphicsInc/cesium/issues/8319

I'd be happy to review a PR for this.

**Comment by thw0rted** [comment]
That's a good point about still being confused.  Would you support a check in the constructor / setter that warns about setting a non-default value?  I feel like there was some kind of "warnOnce" function but I'm struggling to remember the context.  If that sounds like a good idea, would it be better to warn only when the Scene doesn't support a bigger `maximumAliasedLineWidth`?  I think maybe always warn, because it might not break for the dev testing on a Mac, but then it will quietly fall apart for customers viewing it from Windows.

**Comment by OmarShehata** [comment]
There is indeed a oneTimeWarning, there's an example here:

https://github.com/AnalyticalGraphicsInc/cesium/blob/db3f21e093c5c3561e780cc761c6a87cee52f588/Source/DataSources/PolylineGeometryUpdater.js#L528-L530

My vote would be to always warn when setting a non-default value, because the more common case is that your app will be viewed by users on Windows and non Windows machines.
