### ISSUE TITLE
More information needed in Model#readyPromise otherwise function

### ISSUE THREAD

**Issue by fnicollet** [CesiumGS/cesium#8584]
Hello,

When loading a Cesium model, a few different issues can happen (404, CORS issues, etc.). 

Using this simple piece of code:
```
var tileset = new Cesium.Cesium3DTileset({
	url: "http://someurl/tileset.json"
});

tileset.readyPromise.then(onTileSetReady).otherwise(function (error) {
	console.log(error, arguments);
});
```
The error object will just contain an empty JSON object:
```
{
statusCode: undefined
response: undefined
responseHeaders: undefined
}
```
With no helpful information. It would be nice to have at least the statusCode (404, 200, etc.) and maybe a message for other non-obvious errors, such as a missing "Access-Control-Allow-Origin" header. It would help developpers provide better error messages in their code

**Comment by fnicollet** [comment]
Turns out the CORS issues cannot be differentiated from another network error, see https://stackoverflow.com/a/19325710/808102
But it would be nice having the proper statusCode

**Comment by hpinkos** [comment]
Hi @fnicollet, glad you were able to figure out your issue.  Unfortunately, with a CORS error we don't get any information about the cause of the error on our side either.  For other errors like a 401 or 404, the log will work correctly.
