### ISSUE TITLE
Bad label rendering with logarithmicDepthBuffer=false

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium#8588]
Use the [Clamp to Terrain](https://sandcastle.cesium.com/?src=Clamp%20to%20Terrain.html) Sandcastle example and add: `viewer.scene.logarithmicDepthBuffer = false;` after the viewer is created. Or use [this link](https://sandcastle.cesium.com/#c=7Vpvc9o4E/8qevoGM0cV/8WmTToPSWgvcwQyhGun03Q6Chag54zFSCJpepPvfivLJsaY/Lk2fe7FeTIDtndX0mr3t79VuCICXTF6TQU6QCm9RkdUstUCv8+eWY1JdnvEU0VYSkWjhf68SBFcigoBj84Ev2IxFa8KxYmgRNEPXCTx2IhYzYv0tvn6IjXjYDmhKcWzhF9SHNOlmo+pVN0ZSEqVq8BclFjRqk7CZ0QwNV+wybFWPFxNp9nEpySRWvoiPSdpPCFSJRSTOD6mU7JK1Jjz5JKIU5qurE/5/Pf2ik805miSkMUSLTlLlURcoEuWJJeciFgiSRVSc4rmlM3makRhRJpOKFIcHfW7p2dfxsMv70bD3wfHWnHU63fHJ+97d083h1P0q0KvUONYkGt0psdD17Ai1CeXNGm0jBBPJU3oRAtOV+lEMQ5OLByvryvYNQrrzr1DU8UUo1Iv2SqJ6WvJJdMG0HqHjohQ8I2kHp4KvjimM0GptF46roudThC1kN+GL07QbFVN6em+QpUR9DXhCSz+bgh9i89/+3jY/73X2hZfsq80OWffKKg4do0AX6kE4u2ozuzHXr8//LBb6QOLwaGvkFcjUt3EtelfN1/gytZuWrqtWE705tU7ptjvIx1gNNZRMxN8lcaNmtlNeebfhuMvFZIklS8lFWza+IELqTPFBfumEzwZCjZjpUj5tfIG93tvxzUWrqhQbLKt/37jOT7snvf6J4O6gJhCvtVu9mG/e/RbjYKc8+tDMvnDOBO0NF7UyF2uZQrzJZDLHllOC5k/G4fNe02cQX6xdFYxUqSTa+nUqbMQM0kuE3pcgN0xk4qYXRusFpeQwWfD85MMNk4Gb08GJ+OPGpdiwAiZYY8JMHAtJCyECJ8W8FuJy7vbDHBLgGGAQglYC417Gi9uAD80ZuaKtyVkL0HUYQGE/3BsWgN2fRqyBZlpdzcw3su+y70pmbAE3IBnPzbDnmNLSsXqiAvBYi5kC9yX3MxgPxDUPCRgT0g6S6iEgpIk6JKaogaYQ1aKL0iWickNYlMdUjeICJqlHQhkFYgAiKc6LlWO5mB1PeqcSJTy3Ce6zkGMiFUMuuYRXksOhuPeK3ROldKZkisA6tlmWnkqmLmBBL6nPBZLfY7Qm+S268OlCEz5UGR2IQtvrE/bFvSVR20Rs37rHjHXycTg4z4hLxfalvlchzvXeSV0bdvGdWUWogIKDEmqqPtu1OsNsA6LbrKcE8vGQfOJcf2N88WYW7T5IMScmTB+HoDJTNdv8pxRQcRkflP/uhoHn+ow37Neul4QOV6EIz/0fNuNYCNfeqHv26GL/aAT+A7cwb6BlBNEOAgd3wkDLwyaO7Z649o9aOh6DvY7Lpiy27ZnRg0c28NhFLXbtutEQTasHdou7oRBGLbdtve9wwYdB6zZrmsHvles1fU72HY7YRj5gVmrC67ADoiEEUzpu5dqR2Df7gQBrKBtBoWpeBiGtv0ocgoPd9oOjtqeCw5wO83P26PePiELNHn9WUkwhpuVADx9ajYAnFv/yadtigiWq+WSCyVP83XJKRe9PEuGadGVlTurZrOaAdcsjfk1JglQOKtRtGV5lSocJrMiknIgq2ZImD9km5oziZYJUTDuolGsvbgEhYWmpYe3G477N7n/Te5nSu4S+TNT+dLnM/7FJPv/lrM6Fgg8RUo2Be6kQ2V8sywRwaOtd3jcG426J4O6hkWNuCKbbBcSdI4VH5EYvCEt/xnxZVTQw+cos2vuuetwgAvom2AjSnxqPaFtom9Yjt0ypMfO7mqjbBdwj3rHPwu3T3n8jz+3Weg51m/NSrA8MeDvHCg5dKlEkb1MpUiTU5IWCQNf8Sy5fOYTiQVL2WK1OCufErlRbQB81YLn0NmYoyT7ORti4x+kz5hKxUM3X7pTN11UdqAJGlIVrc7TOueEpjMwcKDXYr+uVkZoz4Tqc30+Wg8hURt3oGZ0vHLVzaIujR/QizptvxM2t8aEOr5TzQ1xJ4rcoEYtP6AwPjtbe+sAffpcmhowBGRpcQZv7NfwsZ+74DX65Re2RUuyCW2tA0jK0jIrbK191AJje8jKHfoSOc0qE9HG1ml2UC1RfCbIcs4mVqJtgReq6vUrxMuVnFuF2eYunpMPdD2nqZV/l5mhnGqdcqmOqSIMAqigapUj99aOGTRbd/FlbMpaP/LpVJ9t61DDdmVtdfuS28L37U9W6YzcJ/YZ5+3/Lwf5YK+30rMyrYdxsWB+WRY+itsV5DhJ2FJyFuMP784jH09Ke5y18WO+RljT1hfO28FvgF5u8oGueYAHw9ozznJHHux4X6popXA8y9c7NAfcBa+HQFgCPb+x/txNwGoP5oej7uBd7x7aVjlJdx8W3X14W696u8urGYC+hbg//SmuAKrwf/ZDDY2tZMkmuK4BlohZlr711Nqz7TAE6mNH0EtEHS8CEh20PV8zfMdzvA4wamghgNdHTuBiINVBAB2G067C3Bom6scBkz40IL7didphFLRdoG1Qf7DnO52wE9mavkMnAU1EB0qTDd2LHbY9p+1uobHJ/QlZQOeGE87/6CrLLLKVT+IxKmMBhUk3ntZdhRDsq49PjnuD8cn44wYkP0zw1lijG1uDtw8W9Ed150Uk/82WfK1emthT2/HbGkb0UMe9G3d/zKHpmsFAzAC7cDW7aD1KNLpf1PCbkugjD1Gzk+oxf/fAP5ruQ/YfiupPR/RHotjfQLDbxzdWPwmxNojNMyLWE9Hqu5BKg9PnFmrorvRwpRSkWKNZ/bWDoGbNBRKhu96imtmCLvgV7SaJpa3cZpZetF7sS3WT0DdG579soREEGsTEgtZQ0YVGECr3LlfQMCk8kVIr7+8VSvsxu0IsPrh4UfnJyMULc4gCb6arJOvnLl682d8D+Q21hBP9z9XhFRUJudEic+dN3zzEGO/vwe22ljI/7QBxM+/Sm5xI03RVGm9TpuTRnTJAEmcJ7WsiCzPZKWbI4rax4vMv).

By spinning around a bit, you should be able to get a view like this:
![image](https://user-images.githubusercontent.com/924374/73710948-78a59380-4759-11ea-85d0-1f574325610d.png)

I think what's happening here is that some of the letters are being drawn behind the background, but I don't know why. It still happens even if you remove `disableDepthTestDistance : Number.POSITIVE_INFINITY`. Using logarithmic depth fixes it, though.

Ubuntu 19.10, Chromium, renderer says `GeForce GTX 1650/PCIe/SSE2`.

**Comment by kring** [comment]
It's a bit harder to make this happen in Firefox - more spinning around required - but it does happen.

**Comment by jjhembd** [comment]
Hi @kring, I can't reproduce this in 1.104, in either Chrome or Firefox. Please re-open if you think it's still an issue.
