### ISSUE TITLE
Add another globe to the right to show where you are in the main globe

### ISSUE THREAD

**Issue by hijazikaram** [CesiumGS/cesium#8619]
Can we add a way where we can show another map in the top right/left that shows the user where hes located based on the bounding rectangle coordinates.

**Comment by OmarShehata** [comment]
@hijazikaram do you mean something like a minimap widget? I would say this is better done as an external widget, not necessarily built-in to the CesiumJS library itself. 

Feel free to open a thread on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) if you need help implementing something like this.
