### ISSUE TITLE
How to pick st (Texture coordinate) value from Cesium?

### ISSUE THREAD

**Issue by Hiwen** [CesiumGS/cesium#8627]
I want to pick a  position or a pexil, and I need to know the st (Texture coordinate) value of the position. But I din't found any API coudle do this.  Someone can helps me, thanks very much!

**Comment by OmarShehata** [comment]
Hey @Hiwen, please use the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) for questions like this. If you can explain a bit more about your use case I or another member of the community may be able to help you accomplish what you need to do.
