### ISSUE TITLE
Classification example broken under WebGL 2

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium#8629]
The [Classification Sandcastle example](https://sandcastle.cesium.com/?src=Classification.html) works fine under WebGL1. However, when I switch to WebGL2 by [changing the first lines](https://sandcastle.cesium.com/#c=7VoLb+M2Ev4ragrUMuAwej+cBy6bOLcBmiZYe7cHNIeFLDExb2VJpSgnuSL/vUNKlCXZSbytc9keasC2RA3nxZmPM7QXAVUWBN9hqhwqCb5TTnBOijn6JMbUXihuT9KEBSTBtDdQfrtOFHgxTCkMXdF0QSJMh3JiSHHA8M8pjaNJSaL2B+WUELjge3aZMZIm+VBy4i+Kfy1wzn7G09vYGCqMFrh8+HidPPb3r5PrZAGa5iFOMChaaozE7X75KAzmmAbwTAyi8raeCGOsa+JJQBlcBYmp6obumJ6PTMd0fdd1DHeg7Fou3Bomcizd9zTLMAeKpXm6aejItQzPtHTdtvqV+Hka4fgiYJTcg5RKwoQGSX6T0nmOcJCzn1LKZh+zSXpG7nF0RkFFtVRMcpll9EPKAu6fJZeSq4luaDp/j4OIJLdXhIWzD2kcqw17Vp4ZyNF91/BcD0xwTMcbKBrSxEe/IbEryRKSpB7Chlhcqg31Bk94UgoA/xmVmA7zeREzksUPasNlA67HoOnE5ZpPCxJzu96T21kMb1avcUbJnDCywDkKoqjpipM4yHNyQ0Kh65WkU6uIu8XpHDP6cJ7kLEggxJVh05x/dh6rjUCVU5U64N+l93KCcNwpmeMk5xHenMdfCwxuuj+DeAjYcv4VplLQSRqn9DjLcED5Lfo0+jAZ/evz2eWHi+PJoM0sqsW0lW+shceXweYfcNVfTn/sN3g1A3fYvGvQBAwGpgUTjuoYFXKdl9YIE7oOPJbzhYMESWu1xIBeR071Yff7HZvzWXrXtnYMI09KUzmMNO1usCMRMOot0riY414FNTVOtaJn8pDhhn0rz9DJaHz+8eKzefp5cv7jiONVGbwbYI6l+UjTPd81XcOxK8wxbAPpFuCNDalbYY4PMKQZLlw6msCcP48328UaG7mebZq+ZjmubXtc8RbWbB9nrC3jDKMY1xijfysg05gximOS5SmJ5NQuvlBYE/IkGpjIsCs4sL49OGjSl8N5Lm7GQJvcqr3vzwy+Eff66I6w2XGczQL1f4gRiv6WKGEhz7Pgy7Z8p0YJGwE+aI5tm45ECUgFXdN9w3L1v0HCVHc1EfOvBxPG3zDxzcGEZh5b7pvBhPF2MGH6HuIg4GuaYdUoAaUfPHBtKDEqlPBc5NuO4bie6djbgYkyMercXJ/EzeTdbvPQEL1J1pr/f1lrIAuytvw0/4ppq2nW2dnZm6Wt+ZZpC7W9Ybuur5m6WeetjzzN11zY3HWZtxayPNvTfc+wtpS3281Z/RVz1voGc3aczTDFzyVswWUAlP3l0tG2T09H2pulo/VK6XhTJKEI9pmMq3fV6ZLal84tTw5Rjhk/A22uaoRzRpIyW4bPZrSFeDFuaC4UuvIk0fKQ7ZuW4+t+mdAGJL4P/bwDNbFtNl2bUgIpKgV1Fn1WVtXwQONnB7bmm6YnNnjD8e3OAmW89gZSqIQ133AN3/cd3fZc6KWcxjpIb4OTHtf7aQLJmG/TSZYJNaZpG64FFtRNjWfyow/oYHRdHrc6HlddswwNfPgHvARNh+6ZnuaC/ZYDxdDTLjI1aKh4A2UbjuP67iYeIgk/1mvHoBrOcPgFR7W7yI0ix5QfflC+K5Fs3dRxkWUA2Y25/HVHkii9Q0EM9GpvMiO5MqXpXQ5bS5QCMiQpU/JyZqVQJ2N6XPHKkPLiaRUAaStd918iFaDR2d0EwsjGa/nJN4d9KXzlTBfdYvYkbOSqPKjrI4E4hxuhDWLppyAusPqdXI7KnvZJz2aiof9/BeHGhsKN1xBubijcfA3h1obCrS0IbydskUUBw+WetuC0daa9EOeQfjAHFMkCmuOzOA1YxUDKEFULiTHAYicpxJd5Oikfqr8pBY3rDew8TT7gPC1oWG7SxznQnEcqwJ/j9EvQWVv7VLKWJRP/XeyClxEgXkKPMAdHw9aPZmutHLRnCBdtMK3hnIrDyu46XB3qkooNZti5B78u68kvSRp+SQuGoHQMv6i1rXUDmqbxNOBwFKUhxE4iUGUUY3757gEc2qtIev01XIMMatR3ALSgXL7kPpB8180B/pdTQOFFMI1xc05POpGHbzHNQwhPrK7z3h9jK9amxbsR1mU8dLfu5W+hBaXgkcvpf3AIYbbfGq2r5vawWOP2EM/DamRZo9ZCZkESxd3OZxyCKsk4C0I8WgCL9yWRKn+yhZm5OAcsx3l5cZ5kBTsWmavKFIZGYiEWtc5cLjEjPN9Lq5bNAgzW5Agn0VWaE+l2uTNX2kX4hiQ4UpuM+ny7fuY5IlG/tVNzfh0C5fDwsOv0frdeoZgVNNlvVRxtrh0tugxXODYah8OV1X0BfbvM959ijcKqAujEyRPUFZK3I6jV0bQFA22RVBavp6wteplUFisvkI1LHddRPXZqqD8bPDWcbxJmGzN7fm3bgbLq747Y/RXapsfXK7C/tnvdZhB2VrQbj6uU1aJ2QnG/nWHPlOXPZFedAr8YNq92B4r41g3v36uhsz4fftEl6aOC4xx/db6/kps3z/NNc3yz/N4wt1/Ia/7XocFTW484Jri4/Dgefb64/DTiVu8Mdg5y9hDjo3L+P8hcNFRQqqkI7TE8z2LYYvO9aQFRz1CY59JZ38vao7EmUyhSbmkKWg0VejsNVMuAjrZ6a8hrOjqDak6USVZ23xiepjTCdLc8SWo+BNMO9qSuBxFZKCQ6vN7p/FnreqfsAuHJTRHHY/JffL1zdLAH9K1pUMly6ZcQ9nHwwElm+tGP5SBC6GAPbldnVSYDeanTAePVytEBm6bRQz1Gj5bmHLDo6ACChEEVLhUrVd4tR0FhKGKC3SlUYfxZDPCyUhLuHC3/CcRbivxgr5wNOoKASvBeLXm7OsjytaWGbGeVGwivr1ZnbcPemFyrTXgtpDCIXK4Y72+m6X1X37LtGdZVvFjxr1EER9W5oqjo1+jRBsK2VjRIbiHIlDlJ4E5DGr8O7uFaF9c5w1n5QO8oLjqpYbv5GChi9KMobYe8+gVRvTri1qvA/2LIJUG0w525gZgWw1VnwZcIafgWEc5HymT4HQ) to:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: Cesium.createWorldTerrain(),
    contextOptions: {
        requestWebgl2: true
    }
});
```

The classification no longer works correctly.

# WebGL1

![image](https://user-images.githubusercontent.com/924374/75142792-ea18a680-5747-11ea-8aed-887aa0b1bf71.png)
![image](https://user-images.githubusercontent.com/924374/75142802-f00e8780-5747-11ea-9f91-d5a558ebc845.png)

# WebGL2
![image](https://user-images.githubusercontent.com/924374/75142757-d5d4a980-5747-11ea-9cf1-0ea5d3912251.png)
![image](https://user-images.githubusercontent.com/924374/75142776-dff6a800-5747-11ea-92c4-fa19543494db.png)

Chrome, Windows 10, renderer: `ANGLE (NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0)`

**Comment by kring** [comment]
Same behavior in Firefox and with my laptop's integrated GPU (`ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0`).

**Comment by mramato** [comment]
Lots of stuff is broken under WebGL2, it's going to take a concerted effort to fix/validate/maintain it and given the current WebGL2 adoption rate, it hasn't been a priority.

**Comment by aboutqx** [comment]
From https://caniuse.com/#search=webgl2， it seems that webgl2 is ready to be commonly used.

**Comment by mramato** [comment]
@aboutqx thanks for the link.  I didn't realize caniuse provided usage stats.  The stats we previously had indicated it was much lower. @lilleyse weren't you looking for a source for this last week? (click the link and look in the upper right).

**Comment by lilleyse** [comment]
Ah cool, I wish it could break down support by WebGL extension but it's better than nothing.

**Comment by lilleyse** [comment]
Actually I take that back. See https://caniuse.com/#search=EXT_frag_depth

**Comment by mramato** [comment]
Yeah, caniuse is awesome, I just never noticed the stats in the upper right before.  Pretty sad that frag depth is that low.  Is an extension still needed for it in WebGL2?

**Comment by lilleyse** [comment]
frag depth is core in WebGL 2 (and probably others)

74.31% support of WebGL 2 kinda makes a much better case for switching if we can get all the features that were previously WebGL 1 extensions.

**Comment by mramato** [comment]
> frag depth is core in WebGL 2 (and probably others)

Stuff like this is what I'm most excited about, a lot of mobile devices that can support extensions like this don't, but their WebGL2 implementation does, so it's a big win for Cesium.

**Comment by kring** [comment]
Zero support for WebGL2 on Safari, though, which is probably irrelevant on desktop but a problem on iOS. 😠

**Comment by OmarShehata** [comment]
I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap, so we can consolidate known bugs and discussion in this issue: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407.
