### ISSUE TITLE
Rendering has stopped in Chrome

### ISSUE THREAD

**Issue by cctomato** [CesiumGS/cesium#8634]
When I load a 3dtile file in chrome, occasionally the browser will report an error.But loading is normal most of the time.please see the picture below.
![3](https://user-images.githubusercontent.com/18543001/75337880-d0529d00-58c8-11ea-914c-cdaadef35da9.png)
![4](https://user-images.githubusercontent.com/18543001/75337894-d5175100-58c8-11ea-8cab-945c2ace322f.png)
I don't know why this happens occasionally, please help me！

**Comment by OmarShehata** [comment]
@cctomato have you been able to get this to happen in [Sandcastle](https://sandcastle.cesium.com/index.html?) ? If so, can you share a link (click "share" in the top) ? This will help us reproduce and fix the issue.

**Comment by cctomato** [comment]
@OmarShehata thank you for your reply！This error appears randomly, and it is difficult for me to reproduce it again.I checked some information and a buddy encountered the same situation as me.There is a function createPotentiallyVisibleSet (scene) in View.js. During a loop, the attribute radius of the variable boundingVolume may be NaN. His solution was to add a judgement.
![error](https://user-images.githubusercontent.com/18543001/75411678-0b051580-595b-11ea-8316-4c1e8546147a.png)
......
if (defined(boundingVolume)) {
    if(isNaN(command.boundingVolume.radius)){
        continue;
    }
}
......
But i don't know if he is right.What a sad story

**Comment by OmarShehata** [comment]
@cctomato thanks for the additional info. Does this error happen while you're using the application, or does it happen when you switch tabs? Can you test and see if this ever happens for you with an empty scene,with no 3D Tiles or anything?

**Comment by mramato** [comment]
Closing do to lack of activity.  Please feel free to re-open if you can provide instructions for us to reproduce the problem.
