### ISSUE TITLE
Is it possible to print multiple points at the same time using czml?

### ISSUE THREAD

**Issue by breeze0512** [CesiumGS/cesium#8641]
I am studying CZML using an example.
I want to print multiple points at the same time in one czml.
For example. I want to make czml file that included this information.
exist four points in time A to B
exist six points in time B to C
exist three points in time C

Is this possible in CZML?
If you know how, please let me know...

**Comment by OmarShehata** [comment]
Yes, this is possible. There are many CZML examples on Sandcastles you might find useful. This one defines a point that moves over time:

https://sandcastle.cesium.com/index.html?src=CZML%20Point%20-%20Time%20Dynamic.html

You can change it to define multiple points, each having their own start/stop times. If you're having issues implementing this I encourage you to check out the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev. If you don't find an answer there, please open up a new thread with your question there.
