### ISSUE TITLE
while tilting map the material of the polygon which using ImageMaterialProperty looks strange

### ISSUE THREAD

**Issue by Noah-Gilga** [CesiumGS/cesium#8642]
I had used this image material on a polygon,and it looks correct when the viewer camera pitch is 90°
![texture_polygon](https://user-images.githubusercontent.com/42824389/75523337-c8b90280-5a46-11ea-86db-7a5c479c7a94.png)
![correct](https://user-images.githubusercontent.com/42824389/75523547-32391100-5a47-11ea-916a-48af186cda31.jpg)
**but after i tilt the map,the part of material which far away from the camera looks incorrect
![incorrect](https://user-images.githubusercontent.com/42824389/75523734-86dc8c00-5a47-11ea-8a96-406e474a7343.jpg)
**

**Comment by mramato** [comment]
Thanks for writing up and issue @Noah-Gilga. I believe this is a known limitation in how clamped ground geometry currently computes texture coordinates on some (all?) devices, but I couldn't find an existing issue for it. @likangning93 do you know if an issue exists and/or can you add some more details about the known limitations here so we can fix them in the future.

@Noah-Gilga how are you adding the polygon?  If it's through the Entity API, you can try setting the height of the polygon explicitly to 0. Basically setting a specific height causes a different rendering path under the hood but this option only works if you're not using terrain.  If it's through Primitive API, using Primitive instead of GroundPrimitive does the same thing.

**Comment by Noah-Gilga** [comment]
> Thanks for writing up and issue @Noah-Gilga. I believe this is a known limitation in how clamped ground geometry currently computes texture coordinates on some (all?) devices, but I couldn't find an existing issue for it. @likangning93 do you know if an issue exists and/or can you add some more details about the known limitations here so we can fix them in the future.
> 
> @Noah-Gilga how are you adding the polygon? If it's through the Entity API, you can try setting the height of the polygon explicitly to 0. Basically setting a specific height causes a different rendering path under the hood but this option only works if you're not using terrain. If it's through Primitive API, using Primitive instead of GroundPrimitive does the same thing.

thanks for replying my issue.And here's my codes :

viewer.entities.add({
        id: 'image-cell',
        polygon:{
          hierarchy: Cesium.Cartesian3.fromDegreesArray([118.849999, 32.000001, 119.5632447, 34.25641, 119.23647,32.48521, 119.0000, 31.8348, 118.9, 31.7541]),
          material: new Cesium.ImageMaterialProperty({
            image: '../test-map-engine/test/images/texture_polygon.png',
            repeat: new Cesium.Cartesian2(120, 300),
            color: Cesium.Color.RED.withAlpha(0.6),
          }),
        }
      });
Today i try setting the height of the polygon to 0, but it doesn't works.

**Comment by OmarShehata** [comment]
@mramato why do you think this is an issue with texture coordinates? 

It sounds like @Noah-Gilga is referring to the moire effect here. Here's a [Sandcastle](https://sandcastle.cesium.com/index.html#c=lVPbctowEP0VDy+QCRXYGGIIZGpzC4QkxFxD6YOwha0iJFcWEKfTf69kSJqkL+nO2NrLWa1We7SHXNtjdEBca2gUHbQmivFuC6apL5f1UrPJqICYIp49u1zSIx4gKrDAKAbQ93O/lhT7NS2LtzBAXzxESDa/pBEjScBoTUZDjDjkXpjUXko0IRdSg7QE1pxtWyjgCMU25zDJfdN1C1hmVUpeKxmgqETPa7peBeVKyTDNC+k3gVGumCe3UapIp8SaVtk4+VSWxOnAKpmWclmgmtoXZVP/fiZPuIUCcQxJ7W3zPdXE7Sky5CxCXCRpiyogu/ShgLXUKEQ0uFzBGFXMPJ469+6heNMNmC3lbjQJ25NAaq2espOm/ahWNDTxk1K6c7czu3bHK2NR9I1OsnhwnEW3ihcjp7+adehi2iePM7fseYQM0wTSd9udCbrjscHbbtC0b52pY4el3sivup3H5mY4qzxFt0P/nCQX+81+QFE0Q/bP0aZnb1qGtw7v+wUrOp+v9vPZ3nnoNe3gM99NMm6VfTK4XpmjXuCVNp2u7cx/PJC7jmUbc9Wj7fTdSbnNN/0gCBoNNX2OIgTFu5t9nbmR0w01mmJRTcFjhPG/xFAWcNstcMAitEkUwlwRVBTwd/pTq+ThKxOfGduOWe4DL4+QEaS+B2NBkOLpmDGygtzZCcFoLusi6kvmQ6Fd4yDUXBRn89p6Rz2BZfhMTlyTctqXo5iRnYqMPEiQfC/G5ekknywyYIf/rlEE5WOVTD5Tj0VC0NUx4yveRowLbcdJDoCCQNuISMrGhdXO2yABvDi9gXrhJanu472G/cYy8+FRLzOaR2Acy8h6R8gIP6Nl5qpekPh3aYRBH9Pgfo84gYmChPrV4OgEANQL0vw3Sxxv482OfwA) using the original image. This looks like an under-sampling issue (like here https://github.com/CesiumGS/cesium/issues/8228) which can be fixed through rendering at a higher resolution, or using a texture with mipmaps.

**Comment by mramato** [comment]
@OmarShehata Gary would be able to answer this more completely than I can, but I believe there are some prevision limitations in the ground primitive material implementation. I could be mis-remembering though. @likangning93?

Now that we have sample code, I agree with you that it's probably the same as your linked issue

**Comment by mramato** [comment]
Spoke with @likangning93 offline, and I was mis-remembering. He said the limitations had to do with incomplete implementations of required extensions on mobile.

So we can probably close this as a duplicate and track it in #8228

**Comment by likangning93** [comment]
One more thing - mipmapping might not help since the texture itself is so small in screenspace at these views, I'm not sure how mipmapping interacts with images that repeat this often. @Noah-Gilga I believe we have some procedural materials that might be more helpful for this, here's a [Sandcastle](https://sandcastle.cesium.com/index.html#c=ZVLbTuMwEP0VKy9NpaxT51LSbqgWdVf70hVIIBAiPJhkaC0cu5o4Remq/47dFFrgPHnOnGPPxRuOZCPgFZCcEwWvZA6NaGt6u+f8QbkP51oZLhTgYPizUL2egjLCCGgoryr/f6GIhaimZCBqvoQfJUg5CHp6rWW31Gp6UDmsBCDHctVN35+cczT2xFVMn1HXv2GJAM0FIu/8B8YymiUTi4DEER05sIAwNqHpOI6S5MzyCY3ScXKgo3hsSatNsjQ6cM5ldYxmcZI5KqOTfXyWJuxxGBzLq7kBFFxOT4fyF0X175C4Qr0GNJ1/0pODtGOa61YZ8sn60Vzkp7YENhqdvuZQaqmRHKfhQnr/Z7G4vDsKd8P+vCvUzq3iYxlbresb7X9ZjZN4gZc3ppMw662/RL3WaEiL0qc0NFCvpe2pCZ/a8gUMLZu9LQ/fTXklNnax54X35TMUHiklbxqbeW6lvBZbKLxZHlr9J5vUvBJqebkBlLxzkhWbLXqSUpqHNvzuMlrLJ44nN74B).

**Comment by OmarShehata** [comment]
Thanks for the additional suggestions Gary. I'm closing this and we can continue discussion in the other issue.

**Comment by blueRaining** [comment]
![image](https://user-images.githubusercontent.com/41565968/205494019-db8e9484-b379-40e6-9108-7a58d6cad93b.png)

**Comment by blueRaining** [comment]
> @mramato为什么你认为这是纹理坐标的问题？
> 
> 这听起来像@Noah-Gilga这里指的是莫尔效应。这是使用原始图像的[Sandcastle 。](https://sandcastle.cesium.com/index.html#c=lVPbctowEP0VDy+QCRXYGGIIZGpzC4QkxFxD6YOwha0iJFcWEKfTf69kSJqkL+nO2NrLWa1We7SHXNtjdEBca2gUHbQmivFuC6apL5f1UrPJqICYIp49u1zSIx4gKrDAKAbQ93O/lhT7NS2LtzBAXzxESDa/pBEjScBoTUZDjDjkXpjUXko0IRdSg7QE1pxtWyjgCMU25zDJfdN1C1hmVUpeKxmgqETPa7peBeVKyTDNC+k3gVGumCe3UapIp8SaVtk4+VSWxOnAKpmWclmgmtoXZVP/fiZPuIUCcQxJ7W3zPdXE7Sky5CxCXCRpiyogu/ShgLXUKEQ0uFzBGFXMPJ469+6heNMNmC3lbjQJ25NAaq2espOm/ahWNDTxk1K6c7czu3bHK2NR9I1OsnhwnEW3ihcjp7+adehi2iePM7fseYQM0wTSd9udCbrjscHbbtC0b52pY4el3sivup3H5mY4qzxFt0P/nCQX+81+QFE0Q/bP0aZnb1qGtw7v+wUrOp+v9vPZ3nnoNe3gM99NMm6VfTK4XpmjXuCVNp2u7cx/PJC7jmUbc9Wj7fTdSbnNN/0gCBoNNX2OIgTFu5t9nbmR0w01mmJRTcFjhPG/xFAWcNstcMAitEkUwlwRVBTwd/pTq+ThKxOfGduOWe4DL4+QEaS+B2NBkOLpmDGygtzZCcFoLusi6kvmQ6Fd4yDUXBRn89p6Rz2BZfhMTlyTctqXo5iRnYqMPEiQfC/G5ekknywyYIf/rlEE5WOVTD5Tj0VC0NUx4yveRowLbcdJDoCCQNuISMrGhdXO2yABvDi9gXrhJanu472G/cYy8+FRLzOaR2Acy8h6R8gIP6Nl5qpekPh3aYRBH9Pgfo84gYmChPrV4OgEANQL0vw3Sxxv482OfwA)这看起来像是一个采样不足的问题（就像这里的#8228），可以通过以更高分辨率渲染来解决，或者在这种情况下使用带有 mipmap 的纹理。

![image](https://user-images.githubusercontent.com/41565968/205494049-e33c8443-618a-4f7b-aa33-f198ed6492a6.png)
This still looks problematic

**Comment by blueRaining** [comment]
> @mramato why do you think this is an issue with texture coordinates?
> 
> It sounds like @Noah-Gilga is referring to the moire effect here. Here's a [Sandcastle](https://sandcastle.cesium.com/index.html#c=lVPbctowEP0VDy+QCRXYGGIIZGpzC4QkxFxD6YOwha0iJFcWEKfTf69kSJqkL+nO2NrLWa1We7SHXNtjdEBca2gUHbQmivFuC6apL5f1UrPJqICYIp49u1zSIx4gKrDAKAbQ93O/lhT7NS2LtzBAXzxESDa/pBEjScBoTUZDjDjkXpjUXko0IRdSg7QE1pxtWyjgCMU25zDJfdN1C1hmVUpeKxmgqETPa7peBeVKyTDNC+k3gVGumCe3UapIp8SaVtk4+VSWxOnAKpmWclmgmtoXZVP/fiZPuIUCcQxJ7W3zPdXE7Sky5CxCXCRpiyogu/ShgLXUKEQ0uFzBGFXMPJ469+6heNMNmC3lbjQJ25NAaq2espOm/ahWNDTxk1K6c7czu3bHK2NR9I1OsnhwnEW3ihcjp7+adehi2iePM7fseYQM0wTSd9udCbrjscHbbtC0b52pY4el3sivup3H5mY4qzxFt0P/nCQX+81+QFE0Q/bP0aZnb1qGtw7v+wUrOp+v9vPZ3nnoNe3gM99NMm6VfTK4XpmjXuCVNp2u7cx/PJC7jmUbc9Wj7fTdSbnNN/0gCBoNNX2OIgTFu5t9nbmR0w01mmJRTcFjhPG/xFAWcNstcMAitEkUwlwRVBTwd/pTq+ThKxOfGduOWe4DL4+QEaS+B2NBkOLpmDGygtzZCcFoLusi6kvmQ6Fd4yDUXBRn89p6Rz2BZfhMTlyTctqXo5iRnYqMPEiQfC/G5ekknywyYIf/rlEE5WOVTD5Tj0VC0NUx4yveRowLbcdJDoCCQNuISMrGhdXO2yABvDi9gXrhJanu472G/cYy8+FRLzOaR2Acy8h6R8gIP6Nl5qpekPh3aYRBH9Pgfo84gYmChPrV4OgEANQL0vw3Sxxv482OfwA) using the original image. This looks like an under-sampling issue (like here #8228) which can be fixed through rendering at a higher resolution, or in this case using a texture with mipmaps.

![image](https://user-images.githubusercontent.com/41565968/205494250-fc3dc693-fd50-421e-852f-c8773daa95de.png)
This still looks problematic
