### ISSUE TITLE
"Error [ERR_REQUIRE_ESM]: Must use import to load ES Module" using Nodejs with version higher than 12.10

### ISSUE THREAD

**Issue by MaxwellHuang2015** [CesiumGS/cesium#8645]
## Problem?Bug?
Hey guys, I just cant believe that this bug exist so long but no one find it out!.
Here is the problem, if we download the cesium source code, and download the latest Nodejs from its website, just act like a newbee, and after the 

``` shell
npm install
node server.js
```
![1](https://user-images.githubusercontent.com/11213148/75611706-eb870c00-5b57-11ea-9925-39488c80bb58.png)

I promise that you will fail to run the cesium successfully! The message in the terminal will just like this, telling you that 
**Error [ERR_REQUIRE_ESM]: Must use import to load ES Module**
I search this problem on the internet and found out that no one mention about this disaster problem in the topic of we Cesium. 

## Templory Solution 
Forturnately, I found out that the problem is due to that **the ESM turn on by default since Nodejs 12.11**. That is the problem! I think that in the new version, maybe it is necessary to fix this in the code? 
For those who are in a rush to use Cesium tools, and dont have enough time the look into the code and fix the problem by modifying the source code manually, here is the solution~
**Remove the latest version Nodejs, most likely to be 12.16.1 now. Then download the Nodejs in version 12.10. If you dont know how to access the old version of Nodejs, here is the link [Nodejs version 12.10](https://nodejs.org/dist/v12.10.0/)  Reinstall this old version Nodejs, and retry the command to set up Cesium**

![2](https://user-images.githubusercontent.com/11213148/75611713-f3df4700-5b57-11ea-9c48-3b6c3dab295b.png)

Hope that some one can fix this problem in the upcoming release! And have a good day everyone!

**Comment by mramato** [comment]
Thanks for writing up this issue @MaxwellHuang2015 

We're actually trying this in #8644 so I'm going to close this as a duplicate.

We'll most likely have a fix for the issue you describe as part of tomorrow's release.

**Comment by MaxwellHuang2015** [comment]
@mramato Thanks for your reply and your efforts to maintain this project sooo much~~
