### ISSUE TITLE
Why does the Labels SDF example exist?

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8652]
I'm not sure why this example exists: http://localhost:8080/Apps/Sandcastle/index.html?src=Labels%20SDF.html&label=All

All labels use SDF and we already have the standard Labels Sandcastle demo. To end users and people learning Cesium, this demo doesn't add anything.

Should we just delete it or am I missing something?

**Comment by lilleyse** [comment]
Maybe just add the animation effect to a new dropdown in the labels demo? Otherwise yeah, no reason to keep it around.
