### ISSUE TITLE
Particle system fireworks demo leaves white blob at 0,0,0

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8654]
1. Run the particle system fireworks demo: http://localhost:8080/Apps/Sandcastle/index.html?src=Particle%20System%20Fireworks.html&label=All
2. Switch to 2D or CV

![image](https://user-images.githubusercontent.com/1495196/75700180-a6f69000-5c7f-11ea-9ae3-7cdc88c319a0.png)

Is this a CesiumJS bug or just a problem with the demo?

**Comment by mramato** [comment]
Same thing happens in all Particle Systems demos, so I assume this is a problem at the Cesium level

It's even a bigger problem in the primary Particle System demo:

![image](https://user-images.githubusercontent.com/1495196/75700389-fe94fb80-5c7f-11ea-837c-072a4e80f151.png)

**Comment by hpinkos** [comment]
Duplicate https://github.com/CesiumGS/cesium/issues/7511
