### ISSUE TITLE
3D Tiles - Polylines Rendering Bug

### ISSUE THREAD

**Issue by jtfell** [CesiumGS/cesium#8656]
I've encountered an issue where the rendering gets out of whack for polylines rendered as part of 3D Tiles .vctr data sources.

It is obvious when rendering a regular polyline via the entities API vs rendering a polyline with the exact same points as a `.vctr` file. You can see the difference in rendering in this [screenshot](https://imgur.com/a/WSmW67K). The regular polyline (white) is as expected, an approximation of a catenary, while the `.vctr` tile (red) diverges from this noticably.

I have created an easy replication setup on a [branch on my fork](https://github.com/jtfell/cesium/tree/3d-tiles-polylines-rendering-bug). All you need to do is:

1. clone my fork, checkout `3d-tiles-polylines-rendering-bug`
2. run `npm install && npm start`
3. navigate to `http://localhost:8080/Apps/CesiumViewer/polyline-index.html`
4. slowly rotate around the line

Browser: Chromium 
Operating System: Debian

**Comment by lilleyse** [comment]
@jtfell I opened https://github.com/CesiumGS/cesium/pull/8658 to fix this.

**Comment by jtfell** [comment]
Amazing, appreciate the super quick turnaround @lilleyse! I tested with my full dataset and it looks perfect.
