### ISSUE TITLE
Problem using distanceDisplayCondition in CZML format

### ISSUE THREAD

**Issue by ironexmaiden** [CesiumGS/cesium#8657]
I am trying to add  **distanceDisplayCondition** parameters into a corridor described by CZML format

[in this example](https://sandcastle.cesium.com/#c=fVRta9swEP4rwl+agqfYWbuxNC0bCfRLu4S222B1KKp0ScRkKZzkhGbkv+/8krcl1Bjk0z3Pne65kxcCmVzlhl2z57+ZZfRkkVZZxLr0oZwscrAhi+KNz4ocGm//9/0duwWXQ0ANvstGzrwZbaGCbwgLQK+dbTgpT7Ios+uYHWdDUH2HqJXD0wkfQDHZIJizzBc4ERLYUocZQ1dYVQMspdyLILdBKUqTtvbMndeBDuf/dzVEgcFNUcxnWg5gigA18PkQWD4f0k6Hp19idvGJlvQiZkl8jNoiO2mFLJf3cR93uEPYeGeu4/2alPZBWAkD7edGvPWdVVWNWUQHT+M0SZLxtj01ZQZ6OgsPMAEEYpZI6u7dt/vRy9Pw5fZh+OP7YKtnTVlqFWaVGJ0k4cmBLxcBUAtzWlTvjKY+m+N+7An/nruG4PRV1M3oXF6WKpZv2vk8PiasD7f2zOaTlvX4qtRkQddhoWEJSBfCwpL1wesi5z+rvdaZrEzSNAiaczyjMWZULJI1QrfQCrC74UgEEuKXQ6OeakjrnK3Pr+osSgTx6AqUQMRce6CEDbFP93GwdXPjhGqVd7SiVgfhO7bnQqnWUbQ97Mq5/MmdhpT1R3HU8+HNwE1mv+p87jCwAk2L83aAnGYogG+/FvIPBC69L2m99obQU3rBtLqmnh1KQ72RRnhPnklhzKNe0Vzd9NqEP6CV1Wk7HdJvgqa1hMzSm7t6k3Pea5N5zArOmVeBexEz+w8
)
 unfortunately I realized that this option is not working through CZML format, a colleague of mine made an example with JS entity with the example below

[entity example ](https://sandcastle.cesium.com/#c=fVRta9swEP4rwl+agqfYWbuxNC0bCfRLu4S222B1KKp0ScRkKZzkhGbkv+/8krcl1Bjk0z3Pne65kxcCmVzlhl2z57+ZZfRkkVZZxLr0oZwscrAhi+KNz4ocGm//9/0duwWXQ0ANvstGzrwZbaGCbwgLQK+dbTgpT7Ios+uYHWdDUH2HqJXD0wkfQDHZIJizzBc4ERLYUocZQ1dYVQMspdyLILdBKUqTtvbMndeBDuf/dzVEgcFNUcxnWg5gigA18PkQWD4f0k6Hp19idvGJlvQiZkl8jNoiO2mFLJf3cR93uEPYeGeu4/2alPZBWAkD7edGvPWdVVWNWUQHT+M0SZLxtj01ZQZ6OgsPMAEEYpZI6u7dt/vRy9Pw5fZh+OP7YKtnTVlqFWaVGJ0k4cmBLxcBUAtzWlTvjKY+m+N+7An/nruG4PRV1M3oXF6WKpZv2vk8PiasD7f2zOaTlvX4qtRkQddhoWEJSBfCwpL1wesi5z+rvdaZrEzSNAiaczyjMWZULJI1QrfQCrC74UgEEuKXQ6OeakjrnK3Pr+osSgTx6AqUQMRce6CEDbFP93GwdXPjhGqVd7SiVgfhO7bnQqnWUbQ97Mq5/MmdhpT1R3HU8+HNwE1mv+p87jCwAk2L83aAnGYogG+/FvIPBC69L2m99obQU3rBtLqmnh1KQ72RRnhPnklhzKNe0Vzd9NqEP6CV1Wk7HdJvgqa1hMzSm7t6k3Pea5N5zArOmVeBexEz+w8)

and it seems that this way is working. Is it a bug? or I do not use the **distanceDisplayCondition** option properly?
Browser:
Chrome v80
Operating System:
ubuntu 18.04

**Comment by OmarShehata** [comment]
It looks like you need to change:

```
"distanceDisplayCondition": [1, 1000]
```

To:

```
"distanceDisplayCondition": {
            "distanceDisplayCondition": [1, 1000]
        },
```

See: https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/DistanceDisplayCondition

**Comment by ironexmaiden** [comment]
@OmarShehata you are right! consider the issue closed
