### ISSUE TITLE
Ground polygon regression in 1.67

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8664]
Ground polygons are getting clipped strangely in 1.67. It happens with `viewer.scene.logarithmicDepthBuffer = false` or `true`

Git bisect points to https://github.com/CesiumGS/cesium/pull/8630. @mramato any ideas?

[Sandcastle](https://sandcastle.cesium.com/#c=nVhtb9s2EP4rnPfB8qZJsZ2gXZIW80u2DsuSIXU7FHEQUBJjE6VEgaLjqEP/+46UKFEvTrYKqCPynjs+vDuejn3EAi2wkBP0Bi1IRnexp4bwhpPJ2Tp5LOXTHvm0lD9SsicCAAnZG9BHPecMQz1c8ERimhAxHCkdLfOykCTEY3yDBZXbmIZLksrtfPfwoI1JsSMAXicPuySUlCcwQ50Ex8RVbzjZMHgLOeNihP5ZJwie0jJJJJWUZB6OIqcUqUcpn+pft55MOcs3PDlFFlA9W0oEFuE2P+1u3HsQPF6SjSAkmwmB83eEbrYyc26bNuAxVD3sPbn2KHfRkXfkHlYIGgrBywphQyHsV7gbtSZiLAnosNPCl7Xwa/H6VYXsqwqEinWIqeAm1CpvnOnYm0xPXrloCosdHx+PyqxIaTLfURa1M+Ovat6xkqEvZCpQ6BQNF2pNF11s8lQOS/Ypz6hOihei42jCyjHFS262H1DGAo5FhBqRpzHeqEVr9traQrnGMSupgXdz/Wl2Ob/8cOGi49cjT/IllvjDzaVjO/iRCElDzK4F3VCL7MfGvDe/Xq2u/yz9Dd5WjoFXK/eVIfIEvnMYDghzwQE0kf8v8QtNO/MLH77kQr2UcmHxktsbrNzYOT/akx1HrsiTNFtouPO3m4uLq+dc+Y3u7Mlk1PNYrl6VJ8jBLgogbyonyy0Fz0I24zNrIoCJwJ4IYSI0Z6ayGtNIu09breMGByXbxaq4qsOk41YsWx+wUZkNSBC5E0mJjHdM0pTl8/w9bBwLB8yo837SUdU8zKa8VHDJZZ4SL9sFEX2kEYHVDU2nwQyrvVXEi+275a4NKYULwg4uKHGhjcPhQXsNHNSwWVk0qmAYNAbLuI2et9HYrA9/gzZ60UGHCmUzaeCXbbzCNnmUoblVzHUNnuvfhf5d3qkonJkSmlBGloRJ3DZbVr1GZYVwTn72Xp2Yk2BJp1oKoD7p5LVXCdeJoVlnuyLyQEUmL8kjYYqJYVXnhWNKeUZCnkQGWavdHt010Mj30cVTipMIzZATcCl5PCpMgGtFZcGy96wJvIGmoeTKd0JujYHa2u30oP4SOdBhwMdt5KErLgloYYn2ZCgIguIhtwRyUQgOEeH776rocBFjpmuS1fLoEvX3u99XF94empUZS7fYOfImxkMBDj/voQpmvYrzy9nij37FLfQNTPUOvYqLT7Orht5JR2/+wsofehivE99XzdR6cAVRRzcU6irSwV8P3DoTXNsZSs9ozRSskQZuayMKXWDnLez4rmO2AC5awMkh4LIFnAKw6f9uulfMNfVm/h3mPpu30QfZzxZt6EH+s2Ub+l92YPjrDVj5f3RwmYK9BT1MvmBvQXvI1y5ctsDTLri2vCySpT6+mnF3txV+3saPn8cv2vjJ8/hlG99L33yGQEGVvAZcHcGqHRvioWuQHh41ZYElC1qy0JKV35yqWdhzwaIVn2ORqxImaOjUVx7TtlWfaih5v0JrhbZSptmp75MEjvxnmpKIYo+Lja9GvmXsPuRcRDSBzv8+yzNJ4u/hhgbcMjB7HxC5JwT+WgpQT++r7tBSz+oPZQp+MtTsb76+yplbj9002ILAEoS2IGx8jCOS8FgtrCudA3ci9BOCi84I/YAcuGDp0dMI/QilX48CNdIyg+wcLGN7P17xtGs1fcZq2rZa2AEjhTHfJlxCLOCkXDDUZnDvgtamDi6o7u6Fsb4Fe3aqLvNjMLTXP5PKxWUXY7qIqbMfuyCHf9PuJVDlk1q4N1VVVpdXLqUJpS7jTF/2nUq5PGjFzeULh7sBd1r3mNHZt/z/wsAdnGcyZ+Rtsa1faJxyIdFOMMfzfEj3lKnc9YNd+JlIL8wypXbuG6VzaCcQjd6sBy3z6wEKGc4ykDzsGHtPv5D14O25D/iGGuMYzsfmGo4Uw7mCbMdvL4tJz/POfRh2tSTnDA6dZfFf) - zoom towards the triangles and look at them from a horizon view.

**1.66**

![2](https://user-images.githubusercontent.com/915398/75993099-fa0e5400-5ec6-11ea-9113-9380ed61b6d3.png)

**1.67**

![1](https://user-images.githubusercontent.com/915398/75993098-fa0e5400-5ec6-11ea-94c7-71c7ded0d66c.jpg)

**Comment by mramato** [comment]
Thanks for catching this.  I'll look into it ASAP.  Step one is figuring out if it's all ground primitives or just entity ground primitives, that should narrow down the issue pretty quick.

**Comment by mramato** [comment]
I can reproduce this, but I have no idea why it's happening yet.  It only occurs with the PerInstanceColorAppearance not MaterialAppearance.

**Comment by mramato** [comment]
@lilleyse as far as I can tell, this is a bug in using PerInstanceColors with GroundPrimitive, but I need to port your example to the Primitive API directly to be sure.

My guess is that it's always been a problem and my change just exposes it because we are attempting to use the feature now instead of batching colors into separate primitives

Any thoughts of where we should be looking?

**Comment by lilleyse** [comment]
> My guess is that it's always been a problem and my change just exposes it because we are attempting to use the feature now instead of batching colors into separate primitives

Hm that is possible...

@likangning93 has a better grasp of the system than me. Thoughts @likangning93?
