### ISSUE TITLE
Sunspots on models

### ISSUE THREAD

**Issue by devond5** [CesiumGS/cesium#8668]
[ForCesium.zip](https://github.com/CesiumGS/cesium/files/4299270/ForCesium.zip)

The problem: My employer needs accurate representations of the sun hitting our model and there are sunspots on the opposite side of the model when the sun is hitting it. I know this is not a model problem, because it doesn't appear on babylon or three.js. There are two videos that show this anomaly one with the flaps facing sun and one with flaps facing away.

Sandcastle example: 3D models sandcastle with viewer.scene.logarithmicDepthBuffer = false; and pointing to the model provided in the zip

Browser: Chrome/Firefox

Operating System:Windows

Cesium: 1.61

**Comment by OmarShehata** [comment]
See response here: https://github.com/CesiumGS/cesium/issues/8738
