### ISSUE TITLE
Anti-Aliasing not working >= 1.66.0 

### ISSUE THREAD

**Issue by craigp1231** [CesiumGS/cesium#8671]
It seems as though Anti-Aliasing has stopped working since version 1.66.0. 

[https://sandcastle.cesium.com/?src=Polyline.html&label=All](url)

![image](https://user-images.githubusercontent.com/4073362/76163573-1ae0de80-613f-11ea-9183-299fb50e30c4.png)

When reverting back to version 1.65.0, the AA seems to work as expected.

**Version 1.65.0** - Anti-Aliasing working
![image](https://user-images.githubusercontent.com/4073362/76163658-f9342700-613f-11ea-8c01-645563274a9b.png)

**Version 1.66.0** - Anti-Aliasing not working
![image](https://user-images.githubusercontent.com/4073362/76163690-41ebe000-6140-11ea-97fa-74def4b30162.png)

**Version 1.67.0** - Anti-Aliasing still not working
![image](https://user-images.githubusercontent.com/4073362/76163728-9727f180-6140-11ea-934f-c46eec9dbeda.png)

**Comment by craigp1231** [comment]
Consequently setting `useBrowserRecommendedResolution: false` resolves the issue. Is this a bug or not?

**Comment by lilleyse** [comment]
@craigp1231 it's not a bug, we changed the default behavior in 1.66. From `CHANGES.md`

> * `useBrowserRecommendedResolution` flag in `Viewer` and `CesiumWidget` now defaults to `true`. This ensures Cesium rendering is fast and smooth by default across all devices. Set it to `false` to always render at native device resolution instead at the cost of performance on under-powered devices. [#8548](https://github.com/CesiumGS/cesium/pull/8548)

Technically it's still not applying anti-aliasing, the aliasing is just less noticeable because it's rendering at higher resolution on high density displays. If you want to enable anti-aliasing as well you can set `viewer.scene.postProcessStages.fxaa.enabled = true`.
