### ISSUE TITLE
geoJSON vector data tiles disappear

### ISSUE THREAD

**Issue by kabeer2000** [CesiumGS/cesium#8675]
Dear Sir,

I found an example of how to show geoJSON data on cesium and I followed that example 

the data is displaying but tiles are disappearing when I zoom in more and more

I tried with same with us sample data same this the data displays but when zoom in tiles are disappearing

here is the example what I used

https://sandcastle.cesium.com/index.html?src=GeoJSON%2520and%2520TopoJSON.html 

here is how my data appears

image.png

image.png

I am using reactJS 

here is my code

            this.state.Viewer.dataSources.add(this.state.Cesium.GeoJsonDataSource.load('data/adu_governorate..geojson', {
                    stroke: this.state.Cesium.Color.HOTPINK,
                    fill: this.state.Cesium.Color.PINK.withAlpha(0.5),
                    strokeWidth: 3
                }));

Thank you
Mohammed Kabeer

**Comment by OmarShehata** [comment]
Posted the answer to your forum thread here: https://groups.google.com/forum/#!topic/cesium-dev/poKEu10hJVY

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/poKEu10hJVY

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8675 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
