### ISSUE TITLE
all geojson data is not diplaying

### ISSUE THREAD

**Issue by kabeer2000** [CesiumGS/cesium#8679]
Dear Sir,

I am displaying geojson which has around 897 records it displays data but not all. out of 897, it displays around 100 records

is there any limitations or license I don't understand because all is the same data from a single geojson file

Thank you
Mohammed Kabeer

**Comment by GatorScott** [comment]
Many people are able to display 1000s of GeoJSON entities.  The [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev) is the resource for finding help.  Be sure to supply as much information as you can when you ask a question over there like the platform (e.g. Chrome), OS, and in this case a sample or prototypical item.

Github is used for bugs, that are hopefully reproducible in Sandcastle, and features.

**Comment by OmarShehata** [comment]
The discussion was moved to [this forum thread](https://groups.google.com/d/msg/cesium-dev/5A2mfG1dq60/cZKx2bU2AwAJ). The issue was some of the polygons used an unsupported CRS.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/5A2mfG1dq60/cZKx2bU2AwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8679 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
