### ISSUE TITLE
Cesium.Resource set headers

### ISSUE THREAD

**Issue by yanwei7210** [CesiumGS/cesium#8680]
Sir,

code:
var resource = new Cesium.Resource({
        url: 'http://127.0.0.1:8080/xx',   
       headers: {
          'blade-auth':"aaaaa"
	  }   
});
var terrainProvider = new Cesium.CesiumTerrainProvider({
        url : resource
    });
    viewer.terrainProvider = terrainProvider;
	util.flyToPoint(viewer,[107.3682261,32.1608059],-18,50000,3);

server receive header , Access-Control-Request-Headers is 'blade-auth' , but  value  'aaaa' isn't  sended ?

https://github.com/yanwei7210/yanwei7210/blob/master/question.png?raw=true

Thank you 
 yanwei

**Comment by OmarShehata** [comment]
Running that code in [Sandcastle](https://sandcastle.cesium.com/index.html#c=ZVBdT8MgFP0rhBdmMqHzxYV1jcleTTRqfOKFtVdLpLBcaLdp/O+yj5q1u5Dc3MM5hwOdRtIZ2AKSJXGwJSsIpm34+xGbsPI4rryL2jhAdrNQrksahOBbLGGoejmjkx/lWrSSsDrGjRRidnfPs7Rmcp7NM7HbsalyNegKMEiS2Gxt03Cr21gzqag+lKLK/abd3xkBMaV4Rt+Zahz41N6GlHMOIv/z9nbH5/FrxxGyoFOah7i3UChHUj2YZuMxkuQ64VxEaDZWRwhi3ZZfEHkZwsE/F70or0xHTLVUdPSVipLS6hDSyUdr7av5BkWLXCT+QGa9roz7fOoArd4fKPWseDyBnPNcpPFaFb23a40Xjn8) and checking the network tab shows that the header value is sent:

![image](https://user-images.githubusercontent.com/1711126/76994439-bdaa1180-6924-11ea-8768-b39aa7b0fded.png)
