### ISSUE TITLE
EllipseGraphics `rotation` documentation is wrong (or the code is)

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#8682]
[Sandcastle example](https://sandcastle.cesium.com/#c=nVTLbtswEPwVQhfLgEorSAy0qmI0dn0o4CBB+kJR9UBLa4sNRQrkyo5T5N+7sqT4kT7S8qIld4czO1ppJSxbSViDZedMw5pNwMmq4J+2Z34v3W4nRqOQGmyv/zrRiU6NdsisQYHSaEJmJq0K0MiXgFMFdTjevMv8xOuKEq+BrohwriqYKiVLB4Rt6DlBJEpwXGSZ/yPRjFZpnKzBUSdrIixSJPQpX1hTvIWlBXD+i1dDHgbsLORhP2igWhTAItYbExdDK7RTVUocQSMbsoAJnTG4Q1tlQEGrZy0xZ6ZCRe322ru6XMRaXfVyUMhLqY29uJOOUifDkBbJOCoR3x9LTsMnJY8eRvvuT4RSc5HeXltTgsWN7/fZ+ajLXgrMOZobkZERzu+u4CtBvfYDthDKQX+PpKB+rRSK7Xw0ylg+nn2c8rrhC1Xmwg/5cB/VmkAgsgj2EjnIZY4R6/p4aJ9KzEEdeIRk73MaO2zhqIOHRD+0s/OnSVGbWu0BfTc+LmJfd6f1+us4BWfhvhfPxAz/A/PPPOER5ttevJYZ5hE7+8XLP3r3X6az2dXn3zh8b0zxwfhHftclXuDFDjcKRg30jSxKY5FVVvmcDxCKUhGhG8yr9BaQp24LiwcdKM7kisnsPPGOfi2Jx1IlnKPMolLqvbyHxBvFA6o/gClDc6+XVyuwSmzqkvxkNGsOOefxgLZPUWgMDR6RtLrj7bCOdjbddB+inzVO93e5WOqywuai3f+M4aaE+kToJUllhdS0C+tI3FF08rKOHUJZb3bMg466U/kT).

[The docs](https://cesium.com/docs/cesiumjs-ref-doc/EllipseGraphics.html) say that rotation is

> the numeric property specifying the rotation of the ellipse clockwise from north

but the example shows that rotation is a Cartesian angle from the X axis, i.e. East is zero and it increases counter-clockwise.

**Comment by thw0rted** [comment]
Update: the property detail is as above, but the constructor option is documented as "counter-clockwise from the north", as is the related texture option, `stRotation`.  So, I guess all 4 places are wrong.

**Comment by hpinkos** [comment]
Thanks for your input @thw0rted.  However, the documentation is correct.  We've made the decision that the `semiMinorAxis` is the direction of the ellipse that points due-north at 0 degrees, so any rotation applied rotates the shorter axis away from north.

**Comment by thw0rted** [comment]
😳😳

Thanks for the clarification.  This could totally be a case where I'm not remembering my middle-school geometry correctly.  I had made the assumption that semi-*major* axis was supposed to be the "zero" line and it never even occurred to me to think otherwise.

Would you consider re-opening this to clarify in the documentation?  If nothing else, it'll help me out in 6 months when I've forgotten this conversation and have to figure it out again 🙄
