### ISSUE TITLE
Per-entity property for disableDepthTestAgainstTerrain ?

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8685]
Came up [on the forum here](https://groups.google.com/forum/#!topic/cesium-dev/cvfgIZakSXQ). The desired goal is to have labels not occluded by terrain, which you can do by setting `viewer.scene.globe.depthTestAgainstTerrain = false;`, but here the 3D Tiles _should_ be occluded by terrain (because they're partially underground). 

Being able to set this on only the label entities would be useful here.

**Comment by hpinkos** [comment]
For labels and billboards, you can use `disableDepthTestDistance` and for  geometry you can use a `depthFailMaterial`.  See https://sandcastle.cesium.com/?src=Clamp%20to%20Terrain.html

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/cvfgIZakSXQ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8685 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
