### ISSUE TITLE
How make a  ground primitive represents geometry draped over model instead of terrain or 3d Tiles？

### ISSUE THREAD

**Issue by HelloXiaofeng** [CesiumGS/cesium#8687]
:exclamation: Please use the [forum](https://groups.google.com/forum/#!forum/cesium-dev) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

**Comment by OmarShehata** [comment]
Can you describe your use case more @HelloXiaofeng ?

I'd say the best workaround for now is to tile your model as 3D Tiles. Feel free to follow up the discussion [on the forum](https://groups.google.com/forum/#!forum/cesium-dev).
