### ISSUE TITLE
How to clipping multiple planes on the Cesium3DTileset?

### ISSUE THREAD

**Issue by itsegg** [CesiumGS/cesium#8688]
I want to clipping multiple planes on Cesium3DTileset, but now I can only clipping one plane.

**Comment by OmarShehata** [comment]
You can find an example of multiple clipping planes here:

https://github.com/CesiumGS/cesium/blob/master/Apps/Sandcastle/gallery/development/Many%20Clipping%20Planes.html

If you're still having issues, I encourage you to search through the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) or open a new thread there if you don't find the answer you're looking for.
