### ISSUE TITLE
Memory full, CPU 500+

### ISSUE THREAD

**Issue by wh123660** [CesiumGS/cesium#8691]
For loops multiple primitives and then puts them on 3dfile, resulting in memory full, CPU full and crash. How to solve this problem?

3dtile code will not be written
**code:**

data.forEach(e=>{
        szi = new me.cesiumInstance.Cesium.GeometryInstance({
            id:id,
            geometry : new me.cesiumInstance.Cesium.FrustumGeometry({
                frustum : me.frustum,
                origin :  position,
                orientation : quaternion, 
                vertexFormat : me.cesiumInstance.Cesium.VertexFormat.POSITION_ONLY
            }),
            attributes : {
                color : me.cesiumInstance.Cesium.ColorGeometryInstanceAttribute.fromColor(me.szcolors)
            }
        })
        me.szarr.push(szi)
        szi = new me.cesiumInstance.Cesium.GeometryInstance({
            id:id,
            geometry : new me.cesiumInstance.Cesium.FrustumOutlineGeometry({
                frustum : me.frustum,
                origin : position,
                orientation : quaternion 
            }),
            attributes : {
                color : me.cesiumInstance.Cesium.ColorGeometryInstanceAttribute.fromColor(me.szllinecolors)
            }
        })
        me.szlarr.push(szi)
})
            me.p1 = new me.cesiumInstance.Cesium.Primitive({
              show:me.showcmrs,
              geometryInstances : me.szarr,
              appearance : new me.cesiumInstance.Cesium.PerInstanceColorAppearance({
                  flat : true
              }),
              modelMatrix:me.modelmatrix
            })
            me.p2 = new me.cesiumInstance.Cesium.Primitive({
              show:me.showcmrs,
              geometryInstances : me.szlarr,
              appearance : new me.cesiumInstance.Cesium.PerInstanceColorAppearance({
                  flat : true
              }),
              modelMatrix:me.modelmatrix
            })
            me.cesiumInstance.viewer.scene.primitives.add(me.point)
            me.cesiumInstance.viewer.scene.primitives.add(me.p1)
            me.cesiumInstance.viewer.scene.primitives.add(me.p2)

**Comment by OmarShehata** [comment]
There could be a few different ways to resolve this depending on what you're doing. I'd encourage you to open a thread in the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev) with some more information about your project, like how many primitives you're creating, what else is in your scene, what error message you get when it crashes, and/or a [Sandcastle example](https://sandcastle.cesium.com/index.html?) reproducing the issue.
