### ISSUE TITLE
Camera.getRectangleCameraCoordinates incorrect in 2D

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8697]
Came up [on the forum](https://groups.google.com/forum/#!topic/cesium-dev/E5nR05bILVg). 

[Sandcastle](https://sandcastle.cesium.com/#c=jVRNj9owEP0rFheClDoJSYCk7Kot0FO7rZZVe8nFm5jFqrFR7MDSav97x/lmF6T1AeHxvHkzbx4cSI4OjB5pjm6QoEe0oIoVO/yrjFnDtLwupNCECZoPbfQvEQiOSqmg32VG4waybiJ4vVjdrcZLlIiX0cdEJCKVQmmU01QT8cQpUNVVjlTpGH3w8MwNJn44dUM3jILpxEZKFnobIxf7E9d3A3/s+5NoHEZhaCNKWhQEgyjygsifBj48CZk3MM+bBcFsOvYjbzLzoZeylTURWQp4TjHJsgcp+SPJvxRaS2ENv/IT0hKlZEdzgp+ovm9aXpShhZR5xgTRVIESm0KkmgFuVE9TjZnBTCYHXmDQSlz8npJWK5BRDVU1z/EbfnqQVk1nTo8s7l+6DMc5y2k57Cql3FC9pvdo0+IvCVA3W3XZZq6EZvrU4zmA6V69dkpRc2dUmRaaSdvkGPVmTzvp4r53W4W7FrAxmt3VwaW9+gHjqf69NNLI7th2wJMzwlFr+IXkMsf3qyU+Mr39zPdbYoHxRrWw7biNTAgm+imZ0BaXwkacAKGmz3qEzuW7pIA5e6lYtcSmAZLD7IwIH29yubsnGXxXbfV+95w8Un6mnjmGPS4/7fOHjCnQIaVLpvacnOD3n9XUPZ2XV5Is10aea86oq/pi9wcBEd40s2fPlK/ZX1hy2MP1bWrUbEW8vtxydzYa3v0eGtgFxMVtG8TqGuKKgYbrd3O0iIpjYA/mSp84va0m/MR2e+gCFTm3MHY03YGosF7nsUj/UI1TpQxs7jSgecYOiGU3yeDVn3QyQCknSsHLpuClpMngdu5A/hmMSzCMePpxoDmsz6RsvdtvVRBjPHfg+halq7+FXsX/). Notice that flying to the position returned by `viewer.camera.getRectangleCameraCoordinates(rectangle)` goes to the other side of the world. Flying directly to the rectangle, either by:

```
viewer.camera.flyTo({
        destination: rectangle,
    });
```

Or by `viewer.flyTo(rectangleEntity)` works as expected. This also works as expected in 3D.

**Comment by hpinkos** [comment]
`getRectangleCameraCoordinates` returns the camera position in world coordinates, which means that it's the camera position that has already been projected into the correct scene mode (3D/2D/CV).  `flyTo` expects a WGS8 coordinate.  You can use the `convert` option for `flyTo` to tell it the position is already projected.

```
 let result = viewer.camera.getRectangleCameraCoordinates(rectangle);
 
  viewer.camera.flyTo({
        destination: result,
        convert: false
    });
```

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/E5nR05bILVg

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8697 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
