### ISSUE TITLE
scene.sampleHeight and scene.clampToHeight returning incorrect values

### ISSUE THREAD

**Issue by jrafidi** [CesiumGS/cesium#8707]
The sandcastle below is a modified version of the "Clamp to 3D Tiles" sandcastle, where I've removed the terrain provider and 3D tileset. When the sandcastle starts, zoom out a bit to see the yellow line. The truck model _should_ be moving along the yellow line, but it's not there. If you uncomment the `console.log` on line 28, you'll see that the truck is positioned at roughly -9km height.

In my experience with this in my own application, I have seen the results of `scene.sampleHeight` and `scene.clampToHeight` deviate from the result of `globe.getHeight` by either 9km or 18km 
(interestingly both results were kilometers _above_ ground, unlike the sandcastle). In both cases, 3D tiles were not accounted for, but I believe those methods are supposed to consider 3D tiles into the height (the tiles in question were maybe 500 meters or more above the my terrain).

Sandcastle example: https://sandcastle.cesium.com/index.html#c=ZVRdT9swFP0rWV9Ipc75bhJW0LYODSTYEFRI07oH47ith2NXtlMoE/9913HTljbKg30/zj3X99grrLwVo89UeWeeoM/emGrW1OihtfknpN2OpTCYCapO+p+mYgU5mlBBIcXlona7cREuydPO1W7B5ZxUGGbWm8il1MwwKW6VXFK1NVfY4HvZKELBUTNt62xojV9r/m3rRlziyj9BKLjH9ZJT6wnGHNYT+V3JRlSIQIIj7djssDXCVeUf1eojs6DCnzWCWGp7AX3v31R48LkegNTOh1obA9A5NV/XV8DKMb5h/GmiGvLUkrDZh00DjgNEnWcTqA1Wxrdpb313fpsDxTVVGGlq7JD8DamKasMEtvmn+4McAwissEj8KI6GaZigokizrBjGRTbwPqZ5MkyyHKVlkmRRUoItDYsoLkuUR9mwLMq07A9cDakYUD2ucUlxxcT8lhmyuJOc+ymKizKOoxyQirAowiFUClGal2WYh1GaZ2EM/8Abojgv86KM8rxIkyRKulJUVBOFhZ5JVXunXaEbbBR7SdHVt4sfk6vJr+3RdOPqDq0bVSs+pBey4dUXwWpsrJiMaujmkK3e5ONfSoyeyIsXwpvKRvx2I/nTjcLK287H3AExmAFI52IFMddMG3CpnV62pTv0bqqAejh6K5YHzBvqO56kUQpAJ6ymnVo6FAJtAYIjQpzELymbL4zfoQ6OGtkHOdAYYFnIvQA28/y2ygd4CBrO3zVivyDwiBRacnvv5v6evuRc4eWCETSDO7QVXIvWR4uW5T6VN7dsRwfr3qA30mbN6bmzf2b1UgKPRnEfrrahcLVhbjp4hGtEDSJa28xR0CWNKrbyWHU27R28VtMeCABrDZ4ZdHTPXum0dz4KIP5dmn1GQL8/V1RxvLYhi+j82hkRQqMAtsdZRkr+iNUe4n8

Browser: Chrome 80.0.3987.149

Operating System: MacOS 10.14.6

**Comment by lilleyse** [comment]
@jrafidi `clampToHeight` works by rendering the scene from the viewpoint of the surface normal and getting the rendered depth. The base globe without terrain does not write depth by default so the depth you're seeing is probably the depth plane.

A workaround is to set `viewer.scene.globe.depthTestAgainstTerrain = true;`
[Sandcastle](https://sandcastle.cesium.com/index.html#c=ZVRdb9owFP0rGS8NEjP5giQdrdbRaq3UblUbVZrGHoxjiFfHRrZDS6f+910nBFJAPNi+95x7ru9x1lg5a0ZfqHLOHEFfnCnVrCrRU33mnpB6O5XCYCaoOul/mYk1YDShggKkwaJ6uw0RLsnzPlRvIQTBTi5acjmnKKcrU2RUm4sl8GuTUaVgAWijKtqggJIKw8xmy7+Smhkmxb2SK6p2xzk2+FFWilAIlExbddtmpm8lv9yFEZc4d08QGj7icsWpjQynHNaZ/K5kJXJEANC02kjec2uE89w9qtVHpqDCXVSCWGmdhL7zbyYc+DU9gKh9DNVnDEiX1Hzb3ICqRvEd48+ZqshzLcKiD5sGnoYQtZFtojZYGdfC3vvdWye4pAojTY0drbsVlcPVM4Et/rQ7/imQwAqL0PUDfxx5IUqSaDRKxkEyGjifozgch6MYRWkYjvwwhbPIS/wgTVHsj8ZpkkZpf9DUkIqB1OMa1xTnTCzvmSHFg+TcjVCQpEHgx8CUeEnijaGSh6I4Tb3Y86N45AXwHzhjFMRpnKR+HCdRGPphW4qKPFNY6IVUpXPaFrrDRrHXCN1cXv3IbrJfu6tpx9VeWjuq2rJIF7Li+YVgJTZ070ibYP0m538pMTqTV6+EV7nN+N2M5E87itroMB/zAMJgBmCdqzXk3DJtIKT2ftmVbtnbqQLr4eitWZ4wr6jb6CSVUkCasZK2bmlZCLQFDI0Q0lj8mrJlYdyWdXDUSJfkwGPAZSk7CWzhuHWVT/D5qDj/0Ij9DYcOkUJLbt/d0u34Sy4VXhWMoAW8oZ3harY+KmqVXSnvzbIeHax7g95Emw2n5835V1auJOioFHfhaRsKTxvmpodzeEbUIKK1RU6GLWiSs7XD8rNZ7+AbN+uBAbDWEFlAR4/sjc5655Mh5H+A2c8I+PfnmiqONzal8M9vm0OE0GQI22OUkZLPseow/gc)

As for the `globe.getHeight` and `scene.sampleHeight` discrepancy, `globe.getHeight` returns the height using a ray-triangle intersection test of selected globe tiles whereas `scene.sampleHeight` returns the rendered depth, which can sometimes result in differences. However the `depthTestAgainstTerrain` workaround should minimize that.

**Comment by jrafidi** [comment]
@lilleyse thank you for the quick reply - I have found a different boolean settings that we were setting false that was causing the issue (`scene.useDepthPicking`).
