### ISSUE TITLE
Sky atmosphere gets brighter when the sun is offscreen in HDR mode

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#8718]
If you look carefully the sky atmosphere gets brighter when the sun is offscreen. I captured this gif on the [globe-alpha](https://github.com/CesiumGS/cesium/tree/globe-alpha) branch where it's more noticeable.

![sun-bug](https://user-images.githubusercontent.com/915398/78192940-3e016400-7447-11ea-9050-7082f4b2ac69.gif)

[Sandcastle](https://sandcastle.cesium.com/#c=bZDNTsMwEIRfxcqlRUIOHDiRRpUKNyQkQJxy2TjbxOpmXfknVXh6NomAFvDJO/PNaO0BvBosntCrjWI8qR0Gm3r9PmvrlZnHneMIltGvru4rXngdDDLqzrbdw8jQW/MC3KLURJ9QMAGlvCVXT+JFaBZnZL7p6IEDJfHM+MhQEzY/PQuy97LD2xknwI2++/ZrMId/7ew6K0IcCcuKlZyt7Y/OR5U8rbXOI/ZHgoghr5M5YNQmhOmRRf4VKho7KNtsquzXZ1SZMgQhiLNPRK/2A6usLHLhL2LkoLHcPg/oCcYJ6W7Lp0XUWhe5jH9T0TmqwZ81fgI)

Here's the results of my investigation so far:

When the sun is onscreen the sky atmosphere gets rendered to the sun's post process framebuffer. It turns out the framebuffer uses 8-bit color always, even if HDR is enabled. I thought changing the pixel datatype would be enough to fix the problem but the sun post process just draws a black box (ignore the blue spheres). I didn't want to spend too much time investigating right now this but if anyone picks it up in the future here's my in-progress diff: [sun.diff.txt](https://github.com/CesiumGS/cesium/files/4417977/sun.diff.txt).

![sun-bug-1](https://user-images.githubusercontent.com/915398/78193215-00e9a180-7448-11ea-9623-030ebec3a7ce.JPG)

**Comment by jjhembd** [comment]
@lilleyse I can't reproduce after https://github.com/CesiumGS/cesium/pull/10063, although I'm not quite sure if I'm testing correctly. Are we ok to close this?

**Comment by lilleyse** [comment]
It's still there, but more subtle since the atmosphere ring is smaller.

Also, I needed to update the sandcastle because it was using an outdated API. Here's a new [sandcastle](https://sandcastle.cesium.com/#c=jZBPS8NAEMW/ypJLK8hED56ahkrFkyAoeMplspkmSyezYf+kxE/vJkW06sE5zbz5vcfsjujUaOhETm2V0EntyZvYw9uirVd6GfdWAhoht7raVHLmwWsSgs603cMk2Bv9gtJSigkuUsISmMJbtvUsXpgWcUGWDoJD8RzTTk9Qoz4+oqZ7HjpMzhu42/wJHlw6618kCdZMzddt2XVW+DAxlZWoVDvTD9YFFR2vAfJA/cAYyOd11EcKoL2fX17kn6aiMaMyzbbKfvxQlSnN6H3aHCLzq3mnKiuLPPEXNrbYGGmfR3KM04x0t+XTWQSAIk/jb1ewlmt03xI/AA).

https://user-images.githubusercontent.com/915398/232624523-f4a85bfc-ef33-4ef0-bb3b-267e20184589.mp4

**Comment by lilleyse** [comment]
This is also low priority, so I'm just going to close it
