### ISSUE TITLE
Why use different methods to draw cubes

### ISSUE THREAD

**Issue by daniel-lij** [CesiumGS/cesium#8719]
I just started to learn about cesium. I found that cesium can use viewer.scene.primitives.add to add primitives, or viewer.entities to add primitives. Why there are two ways to do the same thing. Can you tell me why? Thank you

**Comment by OmarShehata** [comment]
Welcome to the Cesium community @daniel-lij ! You can read about the difference between the Entity API and Primitive API here: https://cesium.com/docs/tutorials/geometry-and-appearances/.

For general questions like this, the Cesium forum is a good place to ask: https://groups.google.com/forum/#!forum/cesium-dev. We use GitHub for tracking bug reports and feature requests.
