### ISSUE TITLE
Billboard close to the terrain

### ISSUE THREAD

**Issue by mylove10086** [CesiumGS/cesium#8720]
When cesium has terrain and the number of billboard entities is greater than 10,000, when using Cesium.HeightReference.RELATIVE_TO_GROUND to set the grounding position of the billboard, it takes a long time for the billboard to move to the ground and cesium keeps refreshing the position of the billboard. Is there a better suggestion for this

**Comment by OmarShehata** [comment]
I believe the underlying issue here is that `globe.pick()`, which is used to find the terrain height at any point for each entity, needs to be optimized. There's an issue open for this here: https://github.com/CesiumGS/cesium/issues/8481
