### ISSUE TITLE
Wall not visible underground

### ISSUE THREAD

**Issue by vla9isla8** [CesiumGS/cesium#8724]
Cesium display wall only if maximumHeights points is > 0.

Sandcastle example: https://sandcastle.cesium.com/index.html#c=rVRdb9owFP0rFi9QiZrAiqa1FK2FTnuoVKnQ7mHh4Sa5JBaOjWyHjE7977v5aBtoV1UbfnCub849vj458QYM2wjM0bBzpjBnE7QiS/l9meu0w3I50cqBUGjaR2e+8lVVwW2ICnksdYA8wrVL5mjdRUxI6+ZoDAXEugRp8ezNogDC1TcIcZJJKVT8PtgmOp+thHH2bzgbGkQ1WxeMkKKBom+jpSQEKggkTmghrNBqig5DR0GDi9hIDYPRD5CS8jU3KiecQMshijq/fcVoKKJnp6x9ixHLCzQ4lqCIE9fuVogye8pqfDHW2opiR0vpWuUJGEcRqE98aXQ6xZgOYC9Iue33ks12fh73+0PuddnJSTEPvGJQ9ML7j+P4i/eadnHUIE6FEmmW1p1Q19TL0/bsOVw0K8ChESAbJ9RSG357Na1Aj756rCxUiR3IDD+u9iWhK2Fz4RJmIXdaU5DUHYKKmM4cWQkP9Rle9B/+n+pEM+DDQ9B4B+nG+3yQbrzDaOM9a7PrQPi178BB4b23p8X73i09XgLLJ9tP7D4/YuvL67urXV/XJn7QOp3rzp6lC0Cr2xpZt5U4rgq/inStjWOZkR3Oew7TtaTdbC/IwhU6HtqybNR7KhpFYsNEdO639q5mv8VCCdbSmyVdpzPxgH5rPOoRfqdMaojorr3ZoJGwLSBJf3xdJTnnox4tX1fRjyYDMA3GPw

Browser: Chrome

Operating System: Windows

**Comment by hpinkos** [comment]
Thanks @vla9isla8, this is a known issue.  I added a comment to #4274 so we can notify you when it's fixed
