### ISSUE TITLE
Occlusion issue with changes to log depth equation

### ISSUE THREAD

**Issue by TJKoury** [CesiumGS/cesium#8725]
Issue: 

When adding primitives that are far (at least 11000000 m in one axis) away from ellipsoid center, occlusion is broken. 

[This commit](https://github.com/CesiumGS/cesium/commit/ae9bebf940f271d18a90e9a2824779170f523808) seems to have changed the behavior.

Sandcastle example:
[Example](https://sandcastle.cesium.com/index.html#c=fZltbxvHFYX/ysJfIgfyaN5fXNto6gaJizY1kKD+ULcALW3sRSlSICknbuD/3ucM5UZSMhaQgFzuzty599xzzl2fnU1/Wl/P099Wuzfrefpu/vkwfTNv5t3qsGw301+u1x9OJ29tnJbL1dt592H6cbe9nL776vuvXm/er3bT+2X+ad5NT6fN/NP0fN4v15fmH/3ayRfn/evz7eawWljyi9Ppl9ebib+btV7utu+Xi3n3+PbDL7abF3d/PvllWu338+HFxeMp1Jimjw9fbz4+/IPWUghX22Vz2BPCMRZz3PbVcvF2Ppj9OacxV7vlcjks7+e9WV1cnNza7qUefvnp5+fb9Xo+19FPHh43uPlbz4fpPLDHzWPPV7sDn1abcPuuftvVdr9oBUX0z9s/Tv2Y5+HkkXMxuZpiMD6mXP3p9Kgm11yIyTQba261cI0bfOOjyc27EGx6eHp3vbMvf3i37Kdvrj9M/+bvy7Pf3S4550uuJjhXasg+n04x1RZZuLVU2CM4dgvV1hKzidqqphrz/e1u1osuulS9cZVbM1GDkOZDrtoipBCri5EFY6mxuGYiewY+pDRY0OVQQgumJRt9ztGz4iNXeKCa1CIfSvMkJJfIjcHYVpzX3oP1HgVno02FG5PPpbamBXMJrjbD/0Pw1WZd8qyTvYnVulBdq6MII4kiKSYXy1FYjaWiJVmuZltjrU0JzMWVaE0r1Kx4n0bxeVeIjHPYzBq+KoGOmEM03npPQWw+hldiCcmUFjxJCXV0XpfJFdXMwTWtR65aSaVmky0P53KTAbCl/JXUckocebQeRyPF1XC4QAy1CY1eyGzRUCLSx9MsGSt1K8WAnVY4/nBFnSsmawrQDkKIKizIm0AKWLcCce2SqRflMSCx+QwMRznkrDWZADwy2bI+8XBz2QHM2pxlGStY58rhYzSJWpccrRtFmHLMjiQSQLE2lKqK+gRWvOGnUKtPBVj7GJ112aRQQVbKZbggB+VwNG+hPfqJ+Q5aivEl0WwUlSq7qgNEU8lPUtgjDAIHa0t0ptWabEm2Y44TwyXGBwpQU1KZfW0c3VSbAE1zbVSUVCAY23iWggQnXuCTtyAkeXYC1305m2hoqMoXm1z0MXwmwBqhMNd8q9n1FgvWsbY1vQ1dbL1M2XuARICAArSPUkjCQ87gFWpxkSMTIMQDrL1ztlQfYAdKHAMbsm0i07nFYQIDKYJqaNpEPar1PVn0DDGnAOJsh0zkOxgwSb0Ij4x5sDofDH0LZVERcR6952tUxDak3KkdBNbi2IGmgfPdMLzOVRlOAduJFZQq7wAH9XW0K51TO69aVxwI5NxwlktxsCC5slC+QVVCSjAd4KV1YSaWywlAAz3JDB3cEjytHynxZ2jGQaK6sbJ/ilEJpLx0aTDsVkBSaSoIoRYKosQAhtGCQaij5cAUzFwFQKSK/vK0a/IlFCsdRCHpapUIgnao42A5MkV0zSAiKAehcl6YGa0zyBOdAhFwDWEBKdlY0Bgomx8WhHPGBKHzJPQUXZclJID+57gNipVkqCLsgjAYkMApwM1oSfoxZCSIPNMpRNKXtNSRDGYvTiYpQaCB38AC7ANiUL9RjJUGA/uFrg0V6lL6vQgfNYW8IP7Oqp1gwWqI/BaGKaQzCA7it1KNgjB3fIBliuThsdC6fwDZdC8naQAhIhFD3qdopAYdQnGRiBQ7J7Qs7aSliQtO7CFGqKrQOkihMDDmVbozWWuiNIgKdWKl6TBVWA2EF9BLDTwyTLsZ+i+h7jT6EDf8boEhfGTBmvqk4bZSMjQsGlDFMngnxBVqLKVkldEPA2zkhgDpYPJJ0yvAGAMZRdZSlh3zXESZii8sSAEtXiAOeZqgLMaMiCIiHDpPS8uM2J3etr4LNMAsSF2kJKwMGY8WFE4BjboPJvVkkNQXCNYQr6PvmjwiBGZbVXwJX1OGbssH+AisFljayzl03mKlpmwBQawmx4U8EL2s9oR3fBlGl0gRHAWic4wldlniwEAaJ2szlrOnlCb3paAOrVmcQhgHCA8C2wYRoj8s3Z/GZzqkmEjIKdKkaxjWWDzXUheKPFROzuaLw5yyOZ2lEHE4XfuoswCYe4RAEObHLoBPzjP2HlVtaXgOJENP3SvgaggG9YW+rW8yiaxmoVqu5SD/OW47ihF5uAAX4NhP7Bvdgh8RnTiSR0lQOPwOnif3nhzRVmqAhA6hBYpISx0CDVIevCQHhzKcnJEQbzEKrAUwRwVmfNBJpDfQK6wn3ge4jBxGh6a1vACDFwRN6IODEdQrQ2HCa0B1oJfnIkDu+XNSOLoQFWEqcUcvIyuNW5KYNpp9qJ3wD/mL6oeIWGRRAo4Nn6bhx6kgfcKBCVBiL7OJ2RrVI9Ehmhaa7EzrtgqO42g6m6xWCZ0XHTqHJbZMB4kKjTkQu8dNyEPQMfPRKdDLPEwJJE1VLI23LLA0Nh6Iezc0CuxFHWkvnG+j7zktqyijKrdauBNMkg/L1hzpAzAMjUIR89L95MRptNJAAtiITl+F9XQcydAODS5Vs97otNFiLDGgDn9hNYZpXqqgkDFBosSF1kWYwtMwSaLCzm6ocVAAYLaWEKETjR2ygGDSRFkbJkR5JRQJSaLdvKLEAuQx/Ar1MF1FZD5YEBV1OCWtW2GJ7rMYlakaYy7MhWcaVhchc07iSnUBqZUIOxGmjIyVJQbNvT30CgFdwENXghzSC5xEz9NvsghYGgXYcPdoCvKteczLW/f5kOOr6CniKEYKF6vXiRE4nAH9WvoUg4GrANKpYbzYhf1w6HhXTAxkiqkdtQfOmHUMXEoAVnND6GNrkS0nXK4Kf/qMfpAB/sMF5PH8qomNioigqXUn99qVlyG529jUNL0y8TH+i7ARfzc8r9c4jF5qDAfN6g/YEv2g5pAMbdF9OcwK2cA4nhZPY1/p5POrjLmeRcOJBS0iGJgJhSKSzthZQwC6hYFhGi7D+Bhm2JA2Qs+xZx29WFPfRx1YKSlb0IHKoW5zsmLMiJ/Bc5HOoKvgIfT3U3AT3cBszdxE8fuBaebaJ1cWQ8GGJlWeGSo3MpJ0iBc/OyYdhBNvLUh6bYFxps2a3p+w/3hQcrJmHvKD2qNmIFaDPSAvjkafwt3pmD6HvjUpALrADD7yf7A4/I2H1tzsZfZkoYhObKo3KMcXUpwxSt3kDpxMzDC+QgdjmcU0khmOK6uLdjJLMFDcAJKZhO5FhEgfJJuGbK8mpa305gXYFAUIxSYQrtnYRniqyWDREYrZdU9ThvoLNLgf/S1YIEgldzUP8ma0A2a5Mw6wgVb07hGGduNXO5AHw5ZBjfCLYKW/zMRt6U1R0zuE2s0QXMEIJTeJEhHxkJ1heWEekoPoKHWf2ApPQ/YoeuJox5EGmy0T2+iOIH86zB6EQmOI1Uq3lPK2cBTFQIagsHp8v0V1AQLzgl47ISSf8btwFFxM0zE2V41cj/A+De00UAypzcoCKkxcxdCQSVO8e3h7uX+ZH7e7r1fn705Orran0/Jwevrs0+vxT3/HF9v9jfW9X6Zpe31YL5v51XJxePd4sqf3f79afp7X3y//nR9P7nd+vXlH/ZhPv/nxfLve7h7//023vplX37744eu7N36884L8+PXXC5/exa8u593K7OeD/lHg7jEu5v1h2ayOcZwHo39Z+PP8djfP+xMwjLVE0Gm5RoP2N2+MtJqL5QAYmUXDjj+93MDj2C6bd2u23S3z5nCzw70UvptXF8vmLbnDzyB3rsopNyas7O6l5Go5nJPkRxh+bqxIfHMBf1jbvRt32/WaBe+k5dcvZOjB6YMn+8OH9fzsePmPy+XVdneYrnfrE2PODvPl1Xp1mPdnb67P/zMfzPl+r7Q+Ofv00JOL5f20XDx9/eDeP668fjCdr1f7Pb/8eL3ulX/94NmTM+6/89h624/99/fzbr36oFveuWd/PV40xjw54+tvnzpst+s3q92tFf8H)

Browser: FF, Chrome

Operating System: Linux

**Comment by lilleyse** [comment]
It seems like the bug only happens when the scene is rendering two frustums. @kring any ideas?

**Comment by kring** [comment]
So the immediate problem is that, in the far frustum, the globe, depth plane, and centers of the points are rendered with a range (`czm_currentFrustum` value in the shader) of: [90000000, 99999998430674944]. But the point _outlines_ are rendered with a range of [100000000, 99999998430674944]. Wat?! Investigating...

**Comment by kring** [comment]
Hmm ok so it's the opaque frustum near offset. For log depth, it adjusts the near plane by 10%, or in this example 10 million meters! So basically the depth values are just rubbish. When log depth is off, we only adjust the near plane by 0.01% instead of 10%, and if I change the code to do the same for log depth this bug goes away. @lilleyse (or anyone else) do you have any idea why we need such a huge near offset with log depth? Here's the line I'm referring to: 
https://github.com/CesiumGS/cesium/blob/740ef62abdf2360f7bed5d3c3c70f602cd5d59c1/Source/Scene/Scene.js#L1611

**Comment by lilleyse** [comment]
@kring not sure, this was the last conversation on github about it https://github.com/CesiumGS/cesium/pull/5851#discussion_r172322129. I kinda took that change for granted.

If 0.9999 works we should probably just switch.
