### ISSUE TITLE
glTF model clippingPlanes  removeall error

### ISSUE THREAD

**Issue by changqingom** [CesiumGS/cesium#8728]
Cesium version : 1.68

chrome version :  80.0.3987.149

when excute `glTFModel.clippingPlanes.removeAll()` i got a  rendering error  :  `gltf_clippingPlanes  UniformSampler`   value is undefined

I've tried other models . I think the multi Bounding Volume model has this problem. 

model link : https://sketchfab.com/3d-models/white-silver-green-residence-ec516ba32f03403f97954472c5d4b2cf#download

![image](https://user-images.githubusercontent.com/33093289/78643389-c61fb780-78e6-11ea-91f8-c9f328f226ce.png)

```javascript
window.viewer = new Cesium.Viewer("cesiumContainer", {
  // terrainProvider: createWorldTerrain()
  imageryProvider: false,
  animation: false, 
  baseLayerPicker: false, 
  geocoder: false, 
  timeline: false, 
  sceneModePicker: false, 
  navigationHelpButton: false,
  infoBox: false, 
  fullscreenButton: false, 
  homeButton: false, 
  selectionIndicator: false, 
  navigationInstructionsInitiallyVisible: false,
  shouldAnimate: true,
});

const options = {
  id: "example-model",
  // url: '/model/Duck.glb',
  // scale:400000,
  /*-------------------------------------------------------- */
  url: "/model/white_silver_green_residence/scene.gltf",
  scale: 400,
  position: [108.947048, 34.259415],
};

window.model = Cesium.Model.fromGltf({
  modelMatrix: Cesium.Transforms.headingPitchRollToFixedFrame(
    Cesium.Cartesian3.fromDegrees.call(null, ...options.position),
    new Cesium.HeadingPitchRoll(
      Cesium.Math.toRadians(0),
      Cesium.Math.toRadians(0),
      Cesium.Math.toRadians(0)
    )
  ),
  ...options,
  url: options.url,
  clippingPlanes: new Cesium.ClippingPlaneCollection({
    edgeWidth: 1,
    planes: [new Cesium.ClippingPlane(new Cesium.Cartesian3(-1, 0, 0), 0)],
  }),
});

viewer.scene.primitives.add(model);

viewer.camera.setView({
  destination: new Cesium.Cartesian3(
    -1953829.2409311095,
    6618724.811636659,
    3227893.906284791
  ),
  orientation: {
    heading: 0.24165191356149585,
    pitch: -0.9933975711287646,
    roll: 6.283006645076183,
  },
});

```

**Comment by OmarShehata** [comment]
There does seem to be something about this model that causes the renderer to be in an invalid state when the clipping plane is removed. Running it myself I get a different stack trace sometimes:

```
TypeError: Cannot read property '6' of undefined
TypeError: Cannot read property '6' of undefined
    at regenerateShaders (http://localhost:8080/Source/Scene/Model.js:4981:49)
    at Model.update (http://localhost:8080/Source/Scene/Model.js:4835:17)
    at PrimitiveCollection.update (http://localhost:8080/Source/Scene/PrimitiveCollection.js:374:27)
    at updateAndRenderPrimitives (http://localhost:8080/Source/Scene/Scene.js:3010:27)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2836:13)
    at Scene.updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:2644:13)
    at render (http://localhost:8080/Source/Scene/Scene.js:3319:15)
    at tryAndCatchError (http://localhost:8080/Source/Scene/Scene.js:3338:13)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:3413:13)
    at CesiumWidget.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:704:25)
```

**Comment by prasuncct** [comment]
I think it is related. There is a list of uniforms out of which there is one UniformSampler named "model_clipping_planes" with value as undefined.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/82934147/188849562-2363fa51-5607-4284-93b0-596522a452e4.png)

**Comment by lilleyse** [comment]
@prasuncct or @changqingom could you check if this is fixed for you in the latest release CesiumJS 1.97? We refactored the model loading code and this may have been fixed.

**Comment by prasuncct** [comment]
@lilleyse I am not loading the gltfmodel but the pointcloud (las). It does not seem to be fixed yet.  
![cesium_error](https://user-images.githubusercontent.com/82934147/189030127-553bf5ed-baa0-4944-9dcf-d5a4532c2986.jpg)

**Comment by lilleyse** [comment]
Point clouds and glTF models now use the same `Model` class under the hood so the behavior should be similar.

Would you be able to put together a sandcastle that demonstrates the problem?

**Comment by jinjun1994** [comment]
> 
Can you see this sandcastle?
Click the removeAll button twice , all  types fail



 [Hello World - Cesium Sandcastle](https://sandcastle.cesium.com/#c=7Rprc9s28q+guplEusjUw3aak+ze+dWJb5raFyvJ9KJMhiJhCTVJsAAoR03932/xIgGKsuSmHy+T2CSwu9gX9sX0eugkjlGIooTkOcnmKE/CDHdhRT2gOaYpFmyFBEV8Qe+RWGDEcM4wx5kIBaEZordydZr1eiV2FqOIZoLRRCGk4TwjooixgTXEY8JFmEUY3ROx0IC04DiYZtMM0LlAS4LvMUPHKMP36AxzUqTBe7XWnrYi9X4G54Qkw2za6qKv0wwhkt3SU/plhG7DhOOuXOI4wZFk9jKLSRQKyqrdh87YHscjDGwdm2MD9TqW3JiFKKHRXRAVjIHwE5JKWMPVv4uEhNl5KHBwy2h6yemrl/1BWx4+bQ37w+Fe/9VefzDp90fq73+nrWnWGVeiSgtczX4FNjlQ/ThtnV6+kSJNW9eUZAKdJbSI9cJlpvVmXt/QGCfT1qexqzW1CISURmI8K+antADhs/l7mhQp5hdZOEtw7GoJx3N8I1YJAJW7ghVm80uY5gmerHLMRy63atfo5KIC8mA+9j8pMIZTusQnSTJSp4LylQYSLJAI2RyLX4DlftAf6zXlJheZIIJgpZVPZkPbE8fXEsCsWRdWa1zRBY+8UZDG4e4XONM+hmJ6X6pePr8Gn03qrnYTMYyzmzyM8MUSxDNAyqqujwRRmC1Drg3qUAs4FpdZXogT5Xzt2yJTD6gt1ZACxY42kOYjJ9EdjrXKgBFNWi6W4EFOOZEU5EHg6bdI8YIswzG+hasQt11KHfTs2VaggMS7wgVKlx0JarhHvj2A9UaUcQNskMKNYSRMqpt0RhPKgg+vLycXgQwMJ0m+CNvgFIedRgq0EOCxWKE1UrFYSp28MulZmGIWnuk4Ja2FldMrg0lvUy6qkB/AUbubnEI6e/DTxY+Tz+dXH37uWMd7C0yG3IY6av2uyK3XFflf53Mlrc0eZ2wlXaZmX0+dnWabPsFOg280U82VIGhpPq0lVDx/qi1lGBvvZsV316UN3+UxiF03obyM1ojy+a8zo0Nt59Cxu0FNsMOJCGWYLWMKJBMmrk1gCVZor9rCWVxtGAPZQP3i2NDa8Yq8uXp3c/H5zdX7C63fUiIABi0rZrXCfzQ7bR1pNP8Mi4JlaM2hkTZPUBYTx5ZDw69BrEKQzDkPZdohCZQywuQQLHONFLQ8JqFhPNEw7YIlNl57uca3/Jm7dya9UQvjcgsZ9KN+RRtR2xbABwFbwVOY7cuQ2EXqx94g6He6FTws2he7/Mn8ljn+A4nFYlSVCcF64kf/REATjRR9pTRtNGQVVquSgpyRFPxkiXkQxrHh3eVb/do/t7r8ahkEpY7kj5J9X7ej2rsBe9D5x+cpUHXODZSpfq2DjjVSJfAjBdHYcTZLFxw0Xl1DWUdkzSJJBVCtNkTX6prNDPGbfIGZckpDy98Y+1gsjEkh/cmHCvS6kdaKArr/ndJ0Qh1PMad0G33nNYghFUlEtHgbZnMMLnQI3tMPhl179N/RAfhS6T3OkVWxIf98Z2i+CQUjXw4C/FsB6dIBqKzCKBWBYGHGbylLuy5Ijcjl+cXPk8vJLxVIxUmlYIQgNE+gW/CbFkQ4lP7gg2GSrJAtlMCVQ6F6C8POc44kQ6hkKPDonuQ5YIcZAi9WBCDlpYo92QKBq0MaVORqh4MTyFVrN8S13TWCc4S2c3n4mSZ4XNcExK+JhElUi/VUtTbHi46j1vFmjgCBzlmYL0jk5GlnVTU4JV2fN1+uxw70PfzbTm28WkG0lYcFJvOFsOFB/9nMV2DA95olXod0z/OCWJDKKKRtvW57Kegm42/LBPrgRks/VFcZ+EVtme+IbLfG8OuozmGCs7lYjNGLF8S7eqZTMcVZDQm8tk3W1Vy1casqbWDT1ql08dWV0V7dEWo0qOfpivQIefjQ70JrnnEgAemjSWPDtg+Pqug3hIj42Ka/16nB2ip5tL1IrmEaQTxuk2QWRneQd3LMxGqN521105ocpud+TABTpTt9/9qeEqlJQA/8wXl7cNMI8rv6IC/4ou14iOewRv9eNh67FQBk4iiEdOakYswYZbV8TBMcJHRu9koKthD0qj1VIfy/1nPGEuY++nFZM6aC1TmeQ71vk//eYLgf9L8/OHg5+Idh5ABqisP+/vf9l2Zhv2/Y1raw0ViVJ15AXASCvoVliIbtwf4hiD525yVg+XJgVNZQYIa1xUVe68+8Wggw2ub0rqbaVWTcwygj5cSz5HBioz8PFjWC/ylkLMiqAG7VaFQAHFUKMI3H49Exgx7XLZWrOFkj7bA6cl/Mtko+TswsGPErcB6FCZz0qlxIoa5Ki/SafMHJDfkd9gZ96yy7l+y+bxlBIX/KUVGZHcoOTML8yTy1e456cn7aqPOmVLQ9Dal70NXXwb3Ufy6PPDGHPCl/1HKHu7kpZ+ycLx66TkB2IueWHPFgojdU7ddUfiaQosgBByfzTHs5yhldkhhi3GyFTsGkCV6hmxUXOOV2hDMj6TvmzLUuafYWc1qwSI/yT7gcxcTtwfCgf9AfVl8LcjmXV2P53fBfHgwHFTaxQ3yFrL8TBEHvRg3Qz0MR9ryWuVcO/aunq+pq92wN/Cun2bQ1ruZToAXNXp282uLmlBPCzNNneAzmyUwRmWbu/ENrqpyOTeTV1d96lCfpBoioio2ruysX5HXSbFieBKXglDIexzQq1JwJLuVFokZOpytQ1bRlYKYteZpR7F1GoztwKh0z2mVKawIJZRt3anipQLv2cC1EDUsaQbJyNeOYLWVudDGnrfWPHMCfQuLFjEeMzLBTh8A1fB8mBS7DElNKrHxcNtQWCB0fH9c+mDglTLMR1JVBYEP8OKnBJlKeAz+F4nATRdepq0JOXVBTQ0iXKKHKYVI4o0vwHyjPQlJWital/WbJiW7bG6bmYmpwqAqpw1fByy467AevhofexMNRgyelrgztlSohnbT2RId6ZAz1mGctPbdqGAAbzXUcK20dkSFF9dtlWq8vdxdFx4eybLVMuQVqeXtqad1FKp/HpRhPFKL8Trkr726TUX4AKakY0IqdkoiJCZpIvfKo8DXqpoGrhiutrmAbP52ita+s7jzX/dLy4PHoi+F+sqT2Y6Ul88cfVQknfdPgOL6qUYJaW/XsGfqucScg/BxzwegKHNv/mGEVPnRHDs1EsGl13K96j8HXVV9dCj8sbCKwVndWJ25j0HyqMgMb+NHqtlQyhgrB/EPoiMMVwz9Yov8iaU6ZkFV8G7I8lDdgfwh3vVkB1TUcxnklx99sAnakkEXinMmQMEJsPgvbB8Musv8gQroazuVoNJuP0EH+xVmeURZjtqeHJf7mw9rRRH7achlYQnlKoO/YCxOo3kbQcsRxgtdP3RM0H6Ghd7LdmlEhaOrvrh+tOjXsSX9LM7F3r0ZncuiUxHX0o56r76OYLBGJjxv+CwpYPeQcdm6LRLVK09YPRz2AX0OVCQWYvgLBk3AlwRaDH37Si0EQHPXgtRmzrI1K8x/pL34IivhwT1ZgAEVzoTsP9z9udHVAHaGmUgaO03QqutpMAralsAsc3c3oF5BSUZFSqq6g5R2swOR/HXkkuxk+dNsxQs/VOc8diWSGqobpS4W8M1fyBm1iaj09beVFwylMxDWqPxj7NjWVoWYrI1VWMk6pvUO//Q8)

**Comment by jinjun1994** [comment]
> Point clouds and glTF models now use the same `Model` class under the hood so the behavior should be similar.
> 
> Would you be able to put together a sandcastle that demonstrates the problem?
> 
Can you see this sandcastle?
Click the removeAll button twice , all  types fail



 [Hello World - Cesium Sandcastle](https://sandcastle.cesium.com/#c=7Rprc9s28q+guplEusjUw3aak+ze+dWJb5raFyvJ9KJMhiJhCTVJsAAoR03932/xIgGKsuSmHy+T2CSwu9gX9sX0eugkjlGIooTkOcnmKE/CDHdhRT2gOaYpFmyFBEV8Qe+RWGDEcM4wx5kIBaEZordydZr1eiV2FqOIZoLRRCGk4TwjooixgTXEY8JFmEUY3ROx0IC04DiYZtMM0LlAS4LvMUPHKMP36AxzUqTBe7XWnrYi9X4G54Qkw2za6qKv0wwhkt3SU/plhG7DhOOuXOI4wZFk9jKLSRQKyqrdh87YHscjDGwdm2MD9TqW3JiFKKHRXRAVjIHwE5JKWMPVv4uEhNl5KHBwy2h6yemrl/1BWx4+bQ37w+Fe/9VefzDp90fq73+nrWnWGVeiSgtczX4FNjlQ/ThtnV6+kSJNW9eUZAKdJbSI9cJlpvVmXt/QGCfT1qexqzW1CISURmI8K+antADhs/l7mhQp5hdZOEtw7GoJx3N8I1YJAJW7ghVm80uY5gmerHLMRy63atfo5KIC8mA+9j8pMIZTusQnSTJSp4LylQYSLJAI2RyLX4DlftAf6zXlJheZIIJgpZVPZkPbE8fXEsCsWRdWa1zRBY+8UZDG4e4XONM+hmJ6X6pePr8Gn03qrnYTMYyzmzyM8MUSxDNAyqqujwRRmC1Drg3qUAs4FpdZXogT5Xzt2yJTD6gt1ZACxY42kOYjJ9EdjrXKgBFNWi6W4EFOOZEU5EHg6bdI8YIswzG+hasQt11KHfTs2VaggMS7wgVKlx0JarhHvj2A9UaUcQNskMKNYSRMqpt0RhPKgg+vLycXgQwMJ0m+CNvgFIedRgq0EOCxWKE1UrFYSp28MulZmGIWnuk4Ja2FldMrg0lvUy6qkB/AUbubnEI6e/DTxY+Tz+dXH37uWMd7C0yG3IY6av2uyK3XFflf53Mlrc0eZ2wlXaZmX0+dnWabPsFOg280U82VIGhpPq0lVDx/qi1lGBvvZsV316UN3+UxiF03obyM1ojy+a8zo0Nt59Cxu0FNsMOJCGWYLWMKJBMmrk1gCVZor9rCWVxtGAPZQP3i2NDa8Yq8uXp3c/H5zdX7C63fUiIABi0rZrXCfzQ7bR1pNP8Mi4JlaM2hkTZPUBYTx5ZDw69BrEKQzDkPZdohCZQywuQQLHONFLQ8JqFhPNEw7YIlNl57uca3/Jm7dya9UQvjcgsZ9KN+RRtR2xbABwFbwVOY7cuQ2EXqx94g6He6FTws2he7/Mn8ljn+A4nFYlSVCcF64kf/REATjRR9pTRtNGQVVquSgpyRFPxkiXkQxrHh3eVb/do/t7r8ahkEpY7kj5J9X7ej2rsBe9D5x+cpUHXODZSpfq2DjjVSJfAjBdHYcTZLFxw0Xl1DWUdkzSJJBVCtNkTX6prNDPGbfIGZckpDy98Y+1gsjEkh/cmHCvS6kdaKArr/ndJ0Qh1PMad0G33nNYghFUlEtHgbZnMMLnQI3tMPhl179N/RAfhS6T3OkVWxIf98Z2i+CQUjXw4C/FsB6dIBqKzCKBWBYGHGbylLuy5Ijcjl+cXPk8vJLxVIxUmlYIQgNE+gW/CbFkQ4lP7gg2GSrJAtlMCVQ6F6C8POc44kQ6hkKPDonuQ5YIcZAi9WBCDlpYo92QKBq0MaVORqh4MTyFVrN8S13TWCc4S2c3n4mSZ4XNcExK+JhElUi/VUtTbHi46j1vFmjgCBzlmYL0jk5GlnVTU4JV2fN1+uxw70PfzbTm28WkG0lYcFJvOFsOFB/9nMV2DA95olXod0z/OCWJDKKKRtvW57Kegm42/LBPrgRks/VFcZ+EVtme+IbLfG8OuozmGCs7lYjNGLF8S7eqZTMcVZDQm8tk3W1Vy1casqbWDT1ql08dWV0V7dEWo0qOfpivQIefjQ70JrnnEgAemjSWPDtg+Pqug3hIj42Ka/16nB2ip5tL1IrmEaQTxuk2QWRneQd3LMxGqN521105ocpud+TABTpTt9/9qeEqlJQA/8wXl7cNMI8rv6IC/4ou14iOewRv9eNh67FQBk4iiEdOakYswYZbV8TBMcJHRu9koKthD0qj1VIfy/1nPGEuY++nFZM6aC1TmeQ71vk//eYLgf9L8/OHg5+Idh5ABqisP+/vf9l2Zhv2/Y1raw0ViVJ15AXASCvoVliIbtwf4hiD525yVg+XJgVNZQYIa1xUVe68+8Wggw2ub0rqbaVWTcwygj5cSz5HBioz8PFjWC/ylkLMiqAG7VaFQAHFUKMI3H49Exgx7XLZWrOFkj7bA6cl/Mtko+TswsGPErcB6FCZz0qlxIoa5Ki/SafMHJDfkd9gZ96yy7l+y+bxlBIX/KUVGZHcoOTML8yTy1e456cn7aqPOmVLQ9Dal70NXXwb3Ufy6PPDGHPCl/1HKHu7kpZ+ycLx66TkB2IueWHPFgojdU7ddUfiaQosgBByfzTHs5yhldkhhi3GyFTsGkCV6hmxUXOOV2hDMj6TvmzLUuafYWc1qwSI/yT7gcxcTtwfCgf9AfVl8LcjmXV2P53fBfHgwHFTaxQ3yFrL8TBEHvRg3Qz0MR9ryWuVcO/aunq+pq92wN/Cun2bQ1ruZToAXNXp282uLmlBPCzNNneAzmyUwRmWbu/ENrqpyOTeTV1d96lCfpBoioio2ruysX5HXSbFieBKXglDIexzQq1JwJLuVFokZOpytQ1bRlYKYteZpR7F1GoztwKh0z2mVKawIJZRt3anipQLv2cC1EDUsaQbJyNeOYLWVudDGnrfWPHMCfQuLFjEeMzLBTh8A1fB8mBS7DElNKrHxcNtQWCB0fH9c+mDglTLMR1JVBYEP8OKnBJlKeAz+F4nATRdepq0JOXVBTQ0iXKKHKYVI4o0vwHyjPQlJWital/WbJiW7bG6bmYmpwqAqpw1fByy467AevhofexMNRgyelrgztlSohnbT2RId6ZAz1mGctPbdqGAAbzXUcK20dkSFF9dtlWq8vdxdFx4eybLVMuQVqeXtqad1FKp/HpRhPFKL8Trkr726TUX4AKakY0IqdkoiJCZpIvfKo8DXqpoGrhiutrmAbP52ita+s7jzX/dLy4PHoi+F+sqT2Y6Ul88cfVQknfdPgOL6qUYJaW/XsGfqucScg/BxzwegKHNv/mGEVPnRHDs1EsGl13K96j8HXVV9dCj8sbCKwVndWJ25j0HyqMgMb+NHqtlQyhgrB/EPoiMMVwz9Yov8iaU6ZkFV8G7I8lDdgfwh3vVkB1TUcxnklx99sAnakkEXinMmQMEJsPgvbB8Musv8gQroazuVoNJuP0EH+xVmeURZjtqeHJf7mw9rRRH7achlYQnlKoO/YCxOo3kbQcsRxgtdP3RM0H6Ghd7LdmlEhaOrvrh+tOjXsSX9LM7F3r0ZncuiUxHX0o56r76OYLBGJjxv+CwpYPeQcdm6LRLVK09YPRz2AX0OVCQWYvgLBk3AlwRaDH37Si0EQHPXgtRmzrI1K8x/pL34IivhwT1ZgAEVzoTsP9z9udHVAHaGmUgaO03QqutpMAralsAsc3c3oF5BSUZFSqq6g5R2swOR/HXkkuxk+dNsxQs/VOc8diWSGqobpS4W8M1fyBm1iaj09beVFwylMxDWqPxj7NjWVoWYrI1VWMk6pvUO//Q8)

**Comment by jinjun1994** [comment]
> Point clouds and glTF models now use the same `Model` class under the hood so the behavior should be similar.
> 
> Would you be able to put together a sandcastle that demonstrates the problem?
