### ISSUE TITLE
Cesium 1.68.0 from npm -> code: 'ERR_REQUIRE_ESM' 

### ISSUE THREAD

**Issue by swiss-knight** [CesiumGS/cesium#8733]
Hello devs, 

I cannot start the `server.js` app because of the following:

```
$ cd webproject/
$ npm install cesium@1.68.0
$ npm audit fix
```

```
$ npm start server.js 

> cesium@1.68.0 start /home/username/webproject
> node server.js "server.js"

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/username/webproject/server.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cesium@1.68.0 start: `node server.js "server.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cesium@1.68.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-04-08T13_01_47_312Z-debug.log
```

I've google for this `'ERR_REQUIRE_ESM'` error and I found this thread:    
https://github.com/CesiumGS/cesium/issues/8644

Where  @mramato said:

> This is fixed in master and will be released as part of 1.68 on April 1st.

But I have precisely downloaded Cesium version 1.68.0.

### Operating System:    
Ubuntu 18.04    
Cesium 1.68.0. (from npm).    

```
$ node --version
v12.16.1

$ npm --version
6.13.4
```

Thanks.

**Comment by OmarShehata** [comment]
What's your node version? What does your `server.js` look like?

**Comment by swiss-knight** [comment]
`server.js` was the one from the main repository.

I cleaned all my stuff and started again from scratch by downloading the zip at https://cesium.com/downloads/ 

It seems to work nicely again.

I guess I have been fooled by the `package.json` and/or `package-lock.json` from the previous version.
