### ISSUE TITLE
Cannot set property isDestroyed of #<Polyline> which has only a getter 

### ISSUE THREAD

**Issue by zouyaoji** [CesiumGS/cesium#8735]
Sandcastle example:
[click me](https://sandcastle.cesium.com/#c=ZZFdb4IwFIb/SsONkLgDfjDdRLOFXS5xyZbdjF1UOGq30pK2YJjxv6+gmOnu6MP7lPccKqpIxXCHisyJwB2JUbMyh/eWub20PcZSGMoEqp43S0RlnULymluiL7WXE44l55gaJoV7bVjhLAPNMnefCGKRZk1ck/vurpgqY5+oGMFayfwJNwpRPypFa/ejcQi5mYQwCPpkdAfhpN+xCQRDy6YQjjo2DSBscjY+/sMGNjcMYXz76bV0xzKztQ2GiTi0vdstgE5RIBSK5bZjdap9HqIJajRvLEdZGndditPg+26SDLVRsl6uvuxOzqJHDrZREATezOk7kTY1x8Wx2wPLC6kMKRV3AXyDecGpXYa/KtNvNJDq9quR30lRxirCsnniXP2wxCEpp1rbN+uS81f2g4mziHybv9C4pBkTm2WFitO6iWwHi+cjBIDIt8f/lpGSr6j6c+Mv)

Browser: Google Chrome 版本 80.0.3987.162（正式版本） （64 位）

Operating System:windows

Upgrade cesiumjs to version 1.68, throw an exception when calling Cesium.destroyObject to destroy Cesium.Polyline.

![image](https://user-images.githubusercontent.com/24430116/78793625-3ca2df00-79e5-11ea-90a4-a7e9687a941a.png)

**Comment by mramato** [comment]
@zouyaoji In the future, if you're looking for technical help, please use our forum: https://community.cesium.com

That being said, the sample code you have provided is incorrect. If you wish to remove the polyline from the scene you should call `polylines.remove(polyline)` not `destroyObject(polyline)`. By calling destroyObject directly you are destroying an object that is still being actively used in the Polyline collection.  By default, `polylines.remove(polyline)` will also destroy the object, so there's no reason for you to call it manually.
