### ISSUE TITLE
Color.GREEN is wrong

### ISSUE THREAD

**Issue by loshjawrence** [CesiumGS/cesium#8736]
https://github.com/CesiumGS/cesium/blob/a53bb2c1f380dc95101710ab3316d078eebacf49/Source/Core/Color.js#L1367
Should this be `#00FF00` in the same way RED, BLUE, WHITE, BLACK are maxed out?

**Comment by shunter** [comment]
"green" is #008000 in the CSS spec.  

https://www.w3.org/TR/CSS2/syndata.html#value-def-color

00FF00 is called "lime".

**Comment by hpinkos** [comment]
The colors characters defined in that file are based on the named HTML colors. 
https://www.w3schools.com/colors/colors_names.asp
For full green, use `Color. LIME`
