### ISSUE TITLE
Undesired Sun Spots on Model

### ISSUE THREAD

**Issue by beavelar** [CesiumGS/cesium#8738]
The problem: My employer needs accurate representations of the sun hitting our model and there are sunspots on the opposite side of the model when the sun is hitting it. I know this is not a model problem, because it doesn't appear on babylon or three.js. There are two videos that show this anomaly one with the flaps facing sun and one with flaps facing away.

Sandcastle example: 3D models sandcastle with viewer.scene.logarithmicDepthBuffer = false; and pointing to the model provided in the zip

Browser: Chrome/Firefox

Operating System:Windows

Cesium: 1.65

[ForCesium.zip](https://github.com/CesiumGS/cesium/files/4452626/ForCesium.zip)

**Comment by OmarShehata** [comment]
@beavelar have you tried the new lighting settings introduced recently? Example here: https://sandcastle.cesium.com/index.html?src=Lighting.html

If you're still having issues please open a new topic on the Cesium community forum: https://community.cesium.com/
