### ISSUE TITLE
Field Of View Is Not Changing When Camera is Changing ???

### ISSUE THREAD

**Issue by anujsinghwd** [CesiumGS/cesium#8741]
- Field Of View is not Changing when change the view.
```jsx
viewer.camera.changed.addEventListener(function () {
         // Always console the same fov value
         console.log(camera.frustum.fov);
});
```

**Comment by OmarShehata** [comment]
The camera's field of view is an angle of the camera frustum, see: https://cesium.com/docs/cesiumjs-ref-doc/PerspectiveFrustum.html?classFilter=frustum#fov.

My guess is you're trying to compute the area visible by the camera? For asking general questions like this, please use the Cesium community forum (https://community.cesium.com/).
