### ISSUE TITLE
Changing contour color alpha doesn't work

### ISSUE THREAD

**Issue by shayb-datumate** [CesiumGS/cesium#8748]
Hi all,

I need to be able to let the user change the opacity of the contour lines on the fly, but when I change the alpha of the contour color it doesn't change the opacity.

I've made an example in the sandcastle, you can see it here:
[Sandcastle example](https://sandcastle.cesium.com/#c=rVZtb+I4EP4rVu8DQQKThPBaWt1tb09XaauetO32C19M4oJVx45sh5Zb9b/f2HFIoPR0rS4SEI/n5XlmxmO2RKEto89UoQsk6DO6opqVOf7hZEEndcsrKQxhgqpOD/1cCgSPoUqB6C8ltyyjal4bpooSQx+k4tldpRJ0l+K1e74US1FFwinJqSJYU2PDBN5jRrVhghgmxbwN5YooA29EDINhHEdhiCfJLJ7EU/juodEsmszGIQ6TSRgn41HSQ8NwMhmHMR4n49lkEs8m3V4VQSpGgUgVwUe1z4aSjIn1HI3wbDqNRlEym4K3eDrqNUoFM+lmjvoRHo2jZJTE0+EsiZJpHLeUlOR8jsJK8NrwhiynkENZqivJpc11Tc4u8cOf13dfccqloIG1aOnfC/YoVa7B5OerczYYoLsNdVW7kRnlyCiSPmlkQKiBHUXyEYElyplgiBQFZ6njjCvHjeFFnQQf63tBUpeHaAQJ7R3sPbDMAP34WH5rbcwObIBtjQ/6ZUuVcZCacDnNV1RpxMAQPQmZPsnSILnSVG3JilMNAH1a6l3suAV7H906whcmsiP34NQKfr+9QZTTHCqtbSas7P4afohBKeEcQToRMz4ZRkq+IrYgmUxLa4TX1Hyt7L/srrOg41U6NvYxPJvdncUCadMNzF7tt8L7WIrUFgCVRQb1uYGPYoQH3Tr/FsmayxUFHP6M6JQKip3wvFHKvWnTQLUz/KhkfrcraNAB9FtX8KuqRA55q2Stlqr94dLLTmviZ1t9D84xxO22eMdIV+10ysx32juGqT8j7SMDEMzmN15sSPDGm+/BKtnWoUsbbiWrfgWNV6t0XAhneVxcaITbfXO2i9tpk+90sS5XOlVsRYO60gHMrx+El7R7dMTeZLQgStM/uCSmsTnfD44PQ/KJ/SSopmL/MyxfoU/COuqHQ3mrMU6B9qjPemcLbXacXlYhfmV5IWFClYoHGA8MzQsO3aAHqzJ9oganWtenBmc0l/20vgLbF8cKhtNayVJkfYdljn4ZhsPhcHze0pEK7se+gium1HDFFC+tzYJk/uY5EOdErZlwUjTc77yexsNEAWO0hcqOXhj5vE84W4OXnGUZp2/c940s4K5qnC8GdYYWGdsill0sz47u/+UZSjnRGnYeS86/s7/p8uxyMQD9AzOogeV1C1A42VmVTXT5rRJijBcDWL618kMT1CtMbqeOd8h6r1PrtZb28ecALarsOGLg5Lm6xaLhuHgBLgbmJUgVEWvgYS9MWEU4tO/kBd5H8G/DrrShxX4LRgfpr2Dog2Rrm2x+dIH2kBPfuyEzRx2HoQOQ0QJOmDhwYOiLObZ3KbWal3mL5OCQ5QnS3yAzyA2l93jHo//GO/oQbRfy06SddUMZAH6Es58s7xFOwvcJh23Cbb6wEf0rYR/005S9fUP6NOX9CfG//wA)

Browser: Chrome

Operating System: Windows

Cesium: 1.66

**Comment by OmarShehata** [comment]
Thanks for pointing this out @shayb-datumate ! The contour material was not using the supplied alpha value. This was fixed in https://github.com/CesiumGS/cesium/pull/8749 and will be available in CesiumJS 1.69.

**Comment by shayb-datumate** [comment]
Great! Thanks for the quick response 👍🏻
