### ISSUE TITLE
Partial translucency on globe

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8752]
This PR https://github.com/CesiumGS/cesium/pull/8726 is going to add support for globe translucency so you can visualize underground data.

It was requested on the forum to be able to turn on this translucency just for an area of the globe, instead of the whole thing: https://community.cesium.com/t/viewing-tiles-under-surface-imagery-obscures-tiles/9290/2. The use case there is that you have a house, and want to show what's underneath the house but still keep the surrounding ground solid.

In the meantime, the workaround to accomplish this would be to use clipping planes on the globe .

**Comment by lilleyse** [comment]
There are some pretty hacky ways to do this with the globe translucency PR, like using an imagery cutout on the opaque layer and adding another imagery layer with alpha.

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    orderIndependentTranslucency : false
});
var scene = viewer.scene;
var globe = scene.globe;

globe.baseColor = Cesium.Color.TRANSPARENT;
globe.undergroundColor = undefined;

var layers = viewer.imageryLayers;
var imageryBaseLayer = layers.get(0);

var defaultImageryLayerCutout = Cesium.Rectangle.fromDegrees(-90, 20, -70, 40);
imageryBaseLayer.cutoutRectangle = defaultImageryLayerCutout;

var alphaImagery = Cesium.createWorldImagery();
var alphaLayer = layers.addImageryProvider(alphaImagery);
alphaLayer.alpha = 0.5;
```

![clip2](https://user-images.githubusercontent.com/915398/79132969-40ce5400-7d79-11ea-9b7b-046babdc34d1.gif)

**Comment by lilleyse** [comment]
This was added to the API in https://github.com/CesiumGS/cesium/pull/8726, no longer need to use the hacky code above.
