### ISSUE TITLE
Cesium splatter map textures

### ISSUE THREAD

**Issue by mogmog** [CesiumGS/cesium#8753]
I am new to Cesium and so need some help.

I am keen to try applying the following technique to the 3d model - applying fake textures depending on the height - snow for high altitude, grass for low altitude etc.

This is apparently called splatter maps.

A bit like this

https://stackoverflow.com/questions/18880715/texture-splatting-with-three-js

What strategy would be recommended in terms of feeding altitude data to a custom shader?

**Comment by OmarShehata** [comment]
Welcome to the Cesium community @mogmog ! We use GitHub for bug reports and feature request. I'd encourage you to post your question over in the community forum: https://community.cesium.com/.

I think the easiest way to start on this project may be to look into creating a custom globe material. There's a few built in that color terrain based on slope/elevation etc: https://sandcastle.cesium.com/index.html?src=Globe%20Materials.html
