### ISSUE TITLE
Error in Terrain Clipping Planes for 2D & Columbus View

### ISSUE THREAD

**Issue by mholthausen** [CesiumGS/cesium#8754]
When using the Terrain Clipping Plane, it is expected that when activated, the terrain will be clipped at the specified location in all views (3D, 2D, Columbus View).
This is not the case in the 2D view and the Columbus view. The clipping plane is here always displayed in the ocean south of Ghana, even if the starting point is a different one to the sandcastle location.

Sandcastle example: (modified sandcastle to quickly see the clipping plane)
https://sandcastle.cesium.com/#c=3Vp7b9s4Ev8qRA4Hy1eb0fvhJL1Lk3SbQ7sNmnSLQ1IcaImxtZFFQY8kvkW++w0fetlK6+5m748LsFtJHP7mwZnhcOj9ffS5oChM4iyL0wXKEpLSApUMFTShYRnf02SNlnFEUUbyskDsFpVLihYJm1NUVPktCSm+SW/Se5Kj+5g+0BwdoZQ+oBNaxNUK/yK+aaNQvJ6wtCRxSvPRBP12kyL4K+7Wx+WKFdmS5nSGbklS0IkaWrIqiY7TeEVKimaozKt6qKR5DkAXObsH4fJZzS7MKdB+YXkSXUkSbVyjhTSl1unHNFkrNjfp0/hAii4VOlIqYEGLxceDWjv6SFZZQq/WGVjoCF2PJEv0gaSgzeiyxOgdGC0t+NtPOUkjdELSNUvRecESkCoafT1oDfWBRTQBHGWGHvqs96rkD6s8p2l51o5s0F3rX2tStZ4XYjnPUjJPaNQ3II0W9LJcJ0DVHwejKClLxpI54esZsbBaAW+8oOVZQvnjm/V5pI0UyYibUa3AXcrCO1aVuMxJeKc1qg6RkCxL1m/iNAIpipZ0UrMeC+Pv76O3DMTheNxJi5K7w8OSpqh4iMtwyT92DSHFHzbCkVBSaThghGZc2SBOaEFL8Z4wEkkNYMk1KdttlUKUwBrnnEwb18up/AgMFZcxLXBOV+yeHieJmNehkJ6W5fEq5tFWU2qKMad+6jHakKJhCMJmrIgFzVEdDicQtPBEUgvf5mz1iUTwXGhTE+u+awZeYHuW5Rim706Qjl3Hd11T1w1Lt1zDtSfIsHX4w7pUtuYjtFq30dJoSaJIU/Lwv0aeWfM4aUfn7BEGOuT8L4rBuQog5EHQSSOtIlotUyvdBJm+knPSh+OJI49JgpoEccISluMv786vzjA4z/I4yZZE07G1ORX8E/xiI+1sDAqwQeyW/Ek+PnVM+EesthJpY8tuVR7DxxHG+5ciDk5JSfYFbbHfeIt6+jc8Qm6bjzaNFUOmrVYX8SNNLuP/cNXBM7Ys+siJLkOScAKw+7dUFRkURzQrl1e0KI8XkJCLUmXmNtZa0n7Q9reSk+4Y2FpsUCzt2k5o/IGUecx9S/opDtkqq0r6oR3TFOI/qwRcCmxFccoetHHXB9RWOEPXfQM8J5A27K3I4P6JhJcKB0VTb9hXfxB4+mcBS0gp958APB0CbnG/dnjw9PwljsrlbChT/52LCOvDUftzRBwORWWXrtn0BveJjie3zjmHDegtFDwnVcIFGfJfKFkeLu9iXip1dpJO1ItdjEZndQqVPjqY5S9LWU+0SR52whNR4GxVbLeMp/9kvYC5JGcVFB8EKHklN1fUNMLdrSJOhYwd737Gz0zL8W3LxpajG47j2h7sC1PLsy3HsTF8Mw3dMQP4aDu+ofs69jzD9W3dt7v+8jy45/sutm3fdD3HsBW4bbsedlzT83zPDxS2qePACALP9XTf2RHcDAIM4juW7jgKOgC5dd8LdNsLvI7cQWBarh64wW7Qrm3ANuoYbhA4roR2LN/BFuyfnm5atiegdT+wMGyznql7vrGj2I7tmdj3A9tyXasGNx0Xg0IOgIvNmcttOia2IEs7puu4O4LbXErA8z3T9K3a4JYRYMsHC/iurTsC3QShYTV13TIsf0erWJ7jY1hSA2oJQ0kOtodQBSnBJwxfSg5lB6y6Yxmeq1v+jthgDAw6+0EQuI4lwQHQA7cwXd+zTW4rALd1L8A2VDWu4+g7Cm6bhoVd8MEAHhQ2rBh38cB2LUMhO7rJkU3dgvXYcTGdwMWmFcBccA2BbAWBDiYxwectMIutsA0Hg2Km43j2rg7uBjYIZHg6uLCvKxfXLf7Rsd3Ad325lnxdsRvoQA+htmPwQFxj8EXf8nUzqE3iuhApDvwrfIdDG7YDgeBYtg+Rths0RJwLLuH5pqm7ygUN24JVs7iPQEaRHghej80AwhIc3NgR2gEYWE4XvAEsL7HBPSAxmXoAiuiGjB03gPg1IeI9x4PAlNhfe5WuTJPvabool5As5StOxHtD2MnKkM1pk1x5TqYkXG4k6xZ9q9i5/qo2Ez5V4yQxfNUP4J/DniwH6NWreNwtAjlxSh/L8zSijzBJi9ErZIzRX/vz+hNWcSRGBw8MvCyVc6/jrxMFc93wgE/DazAed7h8k8OqSsqYnwDXvJwkuVZT8/oA3LZ+bevJWvAqGwRMWb4iCZSuHaQdhOSIebxYDktZVHO+aZfagAV+iM3zLFq5Bc1Ekm6rLekGIcKcFUU9vcp2EugbcK1E8mmiiPsycc+XxTUc3OBYnoYUzdcoy2lJxaFeNIuE16O4QKQU7wykjDc0k99ORPzQSAREv/hXhaUSRh1JuwiNAEe9KbxlccGX6FSNawOsnnO1foDirCqW2vNFr5KtFqQx9dMLHnCaU0kf5/+1aAYHew+VcN2GUb0/+bJhO/GPdXolB7Xf4EicNOqcs/QTLViVh1Q0Qo4LoDmPNEj81riVGPy2ytOaAYakHq0vgDwuKAbPTbW6Ptd6ubemFx50krAqulwS7v6YlBAIFVFNmZ5qSr3j6NeqKNGSiuRQsEY7iBc4Iqs+Z9/VQ4hTtshJtozDfvTWX4WSTTjXzSQ85wcDkOtSNFux3K42A0l1db/bROpKgROWLuKyiiCU+t9Bd/l5IGTZ7a1cxxdlNDUHWEEGT4uEPNsda5K8lGlSW2GnPFqbt9t9aJjId1todNVKoXUk6iedGq2AyKXPOzkPbKpttIFC1ZAa5Yu5BgeOCTL5sQeexqNOn2ZjZ3mmE8kLgE4bsm/Qvitx5x70sa15OSxqxeN8wxfl94MtqUKyojnB/O1Nb4bWB+gt1Dsqwu+CN4c/kXRBNVFPTHUMZaWS4G8IToH9MqDHMWHs7rgUKwbV2ErbWM7z07Ofr86v/tUk+TFmkCLyB8gVbZqA6GV5P1csc/agvh90Eub28V9cIcgbBG3cNgAu4vAOkbZLqDbV7oXD9zrCTdCUrM0RG37eyySndJFTWmhTA85IJj9V8dLfggo+sALLBtMaemvLjd3YEi2eztiW63RYb6xx0wBtd9WN3uKLNgzVvGbRC0xJUf7M8nL5Obtib+NHGr3NwT8awf4nHcNG95fuGL4Q8HbH8EWBp0PAwx3DKoU1qZE/0YW6SJD3WjsVJ+Ji8PnqpB7u9fReOEfB/weTI6Qsp5Oyfne6Eqlm8yoOyuSP84Lm97yS617FjQZLvdGYb5lFmMfzTrq7J0lFm3Q3FKCYNvdsgvjgWxeWLY3asXYXerv03UXiwfvArpzDKtUVN2/nfrPk/j2abF/7DmsCrvVLTxl1I6kkj29RQ4KOjo42b457m9T2TaeIHUTB+b+DZGwjtX3sHwEyt4F6O2J7uFIm3ZvsHYqa6bUc+Ue8yiBz83OAhvF+SQGbQGbZn1fhHRQqYVHUIH+pr7o7DHlqWIhO+gxBNUU0m7ek1H869ruVQwalEqz4DNnZ40H3hjOPaD6V0dsdfNpgG6dwhu51c2hexiFJpnAGX6QzfjyNErrNcVqybIbMHtd6aM7Kkq26o8D2cL820WEU36M4OrrZ2/hpxs0ehCMpChi5hbTIbwJv9l4f7gN9bxpfEeDzEWRNyJqTLI3X7+VHjPHhPrxuz1IqA7mU6VD+0ARFpCTTeZxyGpZxjy42fgUhA3E28DsIIZ7EqVGlRUsY5AouaXg3Z4+gmcDgmonff+z12AoyGj1zuFX8P2cwBaQYCQ4jYI1+Er8d2byRod0z8R+TZzupPC/MGdCiQhK3MtTr8F8

Browser:
Google Chrome Version 81.0.4044.92 (64-Bit)

Operating System:
Linux Mint 19.3

As you can see here, the Clipping Plane takes place in the ocean west of Africa in the ocean, even though it should be at clipping around the cesium man.
![Bildschirmfoto vom 2020-04-14 15-42-24](https://user-images.githubusercontent.com/43119593/79231587-9a607c80-7e66-11ea-880d-781baae894c0.png)

**Comment by OmarShehata** [comment]
I believe clipping planes are currently only supported in 3D. There's an issue here to add support for 2D & CV: https://github.com/CesiumGS/cesium/issues/6871.

Perhaps would be useful to add an error or warning when switching to 2D/CV with clipping planes in a scene to explain this?
