### ISSUE TITLE
Add method for finding all primitives/entities in a section of the viewport

### ISSUE THREAD

**Issue by jrafidi** [CesiumGS/cesium#8755]
My application has a concept of selection that can be applied to one or more primitives on the map. I want to support a click-drag box selection to select multiple items in an area (right mouse button down, drag to make a box, right mouse button up, select all items in the box). Ideally, this would function like `scene.drillPick`, but return everything within that box.

I've tried `scene.pick` and `scene.drillPick` with the width/height parameters, but the results are very inconsistent. Looking at the code, it seems like those parameters are just for expanding the area in which the pick will look.

Would it be possible to add something like `scene.drillPickAll` or something similar, to get everything within the define region?

The section of the code I found, where a single object is returned: https://github.com/CesiumGS/cesium/blob/master/Source/Scene/PickFramebuffer.js#L92-L122

**Comment by OmarShehata** [comment]
I'm not sure whether this is better implemented in the application or as part of the library, because I imagine the application may want to control some of this logic. For example, would you count something that's partially occluded over the horizon to be "visible" inside this box? What about something on the other side of the globe but has depth test disabled? 

I'll mark this as an enhancement, happy to hear thoughts from others.

I think one way to accomplish this is initiate scene.pick calls in a grid fashion to cover the rectangle you're testing in, and then remove duplicates.

**Comment by jrafidi** [comment]
Unfortunately, I think doing a `scene.pick` for each pixel in the rectangle is going to be too slow. The code linked above relies on output from `gl.readPixels` (https://github.com/CesiumGS/cesium/blob/master/Source/Scene/PickFramebuffer.js#L79) which is very slow from my testing. This is why I think we need an additional function that makes the read call once and returns everything it finds.

Regarding occlusion: I would expect the same behavior as `scene.pick`. If that includes items that are occluded by the globe, I would be okay with implementing my own occlusion check. Alternatively, if you're imagining this as a different style of API than `pick`, there could be options for `maxDistance` or something similar.

**Comment by hpinkos** [comment]
Doing a whole bunch of `scene.pick` is way too slow to be used for this kind of thing.  I would suggest dragging a rectangle then testing [`Rectangle.contains`](https://github.com/CesiumGS/cesium/blob/master/Source/Core/Rectangle.js#L795) on the positions of your primitives to see if they are inside the bounds of the rectangle.  You can use [`camera.computeViewRectangle`](https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Camera.js#L3685) to get a rectangle for your camera view if you didn't want to draw one out.
