### ISSUE TITLE
Dead link Cesium Electron

### ISSUE THREAD

**Issue by philip-firstorder** [CesiumGS/cesium#8757]
This link is not working anymore:
https://cesium.com/blog/2016/04/04/creating-cesium-desktop-apps-with-electron/

**Comment by OmarShehata** [comment]
I think it might have been renamed to https://cesium.com/blog/2016/04/04/an-introduction-to-cesium-desktop-apps-with-electron/ ? Where did you find your link @philip-firstorder ?

**Comment by philip-firstorder** [comment]
Was one of your pages, not sure which, but you should find it by just searching for the link in your code.

**Comment by OmarShehata** [comment]
This URL is not present on any of cesium.com's pages. If you end up finding where you stumbled on that link, let us know!
