### ISSUE TITLE
Modify the order of functions 

### ISSUE THREAD

**Issue by mycleaerlife** [CesiumGS/cesium#8782]
could you please modify the order of function [scene._globe.render(frameState);] in [updateAndRenderPrimitives] I want this function can be execute first,and I will use 'primitive' to do more things withow modify source code

**Comment by OmarShehata** [comment]
@mycleaerlife can you share more details about what you're trying to accomplish, and why it can't currently be done?

**Comment by mycleaerlife** [comment]
Thanks for your reply.
1.I just want to modify command`s shader,and I want to current frameState`s all commands to render my texture in  this [primitive.update(fameState) ] function , althogh this [frameState.afterRender(funciton(){})] function can get All Commands, but those are all Previous frame`s informations,maybe  change the order of that functions could be better. 
2.the globe-command`s ShaderProgram regenerartes in every frame.  Can you provide an external listener or a callback function that i will modify shader before  it push into commandslist.

that all above are my thoughts ，maybe there are  better solutions

**Comment by OmarShehata** [comment]
@mycleaerlife it's still unclear to me what use cases are enabled by making this change. I'm closing this but feel free to search through the community forum (https://community.cesium.com/) or ask your question there. If you can provide an example of your custom shader and/or screenshots of what you're trying to accomplish that might help others recommend possible solutions and workarounds.
