### ISSUE TITLE
GLSL files still have 4-space indentations

### ISSUE THREAD

**Issue by emackey** [CesiumGS/cesium#8791]
But VSCode is configured for 2-space indentations now.

VSCode could be reconfigured to treat `*.glsl` as 4-space (there is a way to do that by filetype), or we should reformat the GLSL files to 2-space.

Which would be better?

**Comment by mramato** [comment]
For some reason, shaders have always used slightly different formatting (for example, put braces on their own line). Is there a technical reason this is the case?

If there's no technical reasons for being different, I vote for consistent formatting throughout.  It looks like someone started a prettier [glsl plug-in](https://github.com/lindenbark/prettier-plugin-glsl), but it was never finished.

I'm also fine with punting and keeping this issue open and just switching glsl to 4 space indents until we care enough to fix it.

@kring any thoughts here?

**Comment by kring** [comment]
It'd be fun to finish the GLSL formatter, and doesn't sound like it'd be terribly hard (https://medium.com/@fvictorio/how-to-write-a-plugin-for-prettier-a0d98c845e70). But it's hard to justify the time I think.

Let's just update .editorconfig to use 4 spaces for GLSL, for now.
