### ISSUE TITLE
Imprecise 3D Tile rendering coordinates

### ISSUE THREAD

**Issue by anaezes** [CesiumGS/cesium#8792]
Hello,

I am developing an application in which I need to render 3Dtiles according to the position of a vehicle in real time.
I converted the tifs from EPSG:4326 to tifs ESPG:3857 with GDAL wrap, converted the tifs to .obj with blender and blender-gis and checked that the pivot is in the center. With GDAL, I checked the geographic center of each tif and then placed each asset / tile in its respective location. However, as you can see in the image, they are superimposed.

I am using Cesium ION to save the tiles and I tried in different ways to render them:

1st I adjusted the position (lat, lon) in Cesium ION. It did not work.
2nd I did not adjust the location in the ION and defined it in real time from a JSON. It did not work.
3rd I used the center of the first rendered tile as a reference, and calculated the position of the others in relation to this one (adding the width or length to the point respectively). It did not work.

I leave attached a print with a demonstration of the error happening.
I checked and the coordinates given to each tile are 3768.08 m apart, which should be the value to be side by side and not overlap. The error is about 30%.

Can someone help me solve this problem?

[Code example](https://sandcastle.cesium.com/#c=vVRdb9owFP0rFk+J1JqGb1ZarQWKghoYbUqhijSZ5AIOjk1th49O/e9zSNu13aQ9TFoeolzfc86998R2sYh6knCN2qBomvRvEQlDUAppgfYilYgKjohSoFXAcwx2BccRzEnK9MUB7IsVcHSGggLs+8tZL6RD2nfvnlxnQF3l8ptq2HZr7mo9Gbf7TWxAj1FvlYFWw944mfqXidd2Yq/Tj6/9UdXzR3rqj7YP1IkH8Xg19MO9iU+8uEuv2/31gxHzYm838FdGfBDPypcs3Lu1e1M8LLsZhk/3/SjDTicjOoy7zrDjVjy/ezKIL5u4MeuU6PJ+Mht968aPw1p7UG9OOg/HwpfT+tK5rYpGSv3vepPeBYXTgAd8QyTaUNiCNGNy2L7YhceHNSsohIe4LbgmlIMMCnbOO+SxCoEDXjAxA6yWYmtE5oQpOH1DwE4Dj6wX2XwxD8odnzIwg6o1hFpIj+4ot9+60lkStFH8UGstaUI13YDCJIqsgKP3bX9QBm39yPIIpZJ9Qb9+8g0oswNCwHMpkotsD7iR1SzVTsr2UU5IRATMI1rS3RvRN9tJzYVMFAai9EBIvbxb++KK7iC6kiQBKydnz2s/RGrzRXj5UKsDCwmgrOMGblQqlWazdoQqDq426iWnUTpCjp038GwHvztR+q9WVF6t+Gcz/mpFvdl0TMmPVpzY9icn8tGfhEh8Yb14YmOhlyC3VIE1T3mos1NtgZRC2ugwcSi4EgwwE4uXdaP2nL0KR4WW0nsG5xnuK03WZojMHwvjooZkzYhpuDhLwxVoHCqVkVrFV0orohtEo7M/HBEUMnOzmMw8ZeyWPkFQOG8VDf4DjQkSUb4YbkAysjeQrI3W0jm/zhMY41bRhFnRz1wtBJsR+U73Jw)

![tiles](https://user-images.githubusercontent.com/17862764/80193415-ab508100-8610-11ea-861d-88b3a7ee079a.png)

**Comment by OmarShehata** [comment]
The Cesium community forum (https://community.cesium.com/) is the right place to post questions like this. I noticed you opened a thread already, I've posted my response there: https://community.cesium.com/t/imprecise-3d-tile-rendering-coordinates/9432/2?u=omar.
