### ISSUE TITLE
now  polygon donot support callback,why? 

### ISSUE THREAD

**Issue by wang1120** [CesiumGS/cesium#8794]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

**Comment by OmarShehata** [comment]
Please post your question in the community forum (https://community.cesium.com/) with some more information, like what you're trying to achieve and a code example.
