### ISSUE TITLE
Cesium on Android

### ISSUE THREAD

**Issue by JiaweiLin** [CesiumGS/cesium#88]
Im sorry if this question has been asked before. Has anyone tried running Cesium on Android and is it possible to do so? I would like to find out whether it is possible to run Cesium on Android.

**Comment by vaishakha** [comment]
Is there any cesium library for an android native app?

**Comment by hpinkos** [comment]
@shangtianhao @vaishakha There is not a separate Cesium library specifically for Android applications.  However, there are a few different ways to add Cesium to your Android app.  One option would be to use Cordova.  You can see our blog post about this here: https://cesium.com/blog/2016/05/18/an-introduction-to-cesium-android-apps-with-cordova/

Cesium also works in the web browsers for most (if not all) modern Android devices.  I believe you can also add it to a native app using a WebView.
