### ISSUE TITLE
trackedEntity doesn't follow moving entity if it has a "box" geometry

### ISSUE THREAD

**Issue by 461255824** [CesiumGS/cesium#8800]
if i use SampledPositionProperty and entity has box, when trackedEntity,  the viwer can't fllow the entity center

**Comment by OmarShehata** [comment]
Was able to reproduce by adding a box entity to the truck in this [time dynamic wheels Sandcastle](https://sandcastle.cesium.com/index.html#c=zVdbb9s2FP4rRF4sN4osy/E1abEsbbcOae01abYHAwUt0TYRihRIKo479L/vkBJtyZaHPM6AbV3O5eN3Ljx8xhI9U7IhEr1FnGzQLVE0T4NH+8xrxfb2VnCNKSey5aN/5hzBR61FzpIbTlOsyQRpmZM5/9m+mvM573Q+4yeCVC6JM04VwhrpNUEJWJQkQZqmJJjzZwCgNJYa/Je+/8gZxfw92A2WUqTmwjPQ7EUUdkc+6nbhG8G33zYujREtNGb3JBY8UWCrG1454yJrtI2TpBT3LAC/ZsKvsrHX8gp/dlFBzET8FFjlB1gNeLHX5jkHyWNBke3kRHZKLM6lJPxVFu3vV8xXZL/C292z4G46nX2/f5jO9nqGdQaRDH4IkT4It3KDx8UO3UoCK0UYZViv0VJIJHLIErKmMSNosUWMyIzyFVoQvSGEI70RKBOKaiq4KmPq7utpdY/TjJFkVr6cSZERqbde+6qSCbNG1Vt4A1eY97yLqDcc9/uDYDge94bRaHDpo4vLwaDfj0ZBFPbDXhgNej7qDaJR2O0F3XDQH48Hw5FzQ3jyOieDsBcMw+FlN+wNL4ell0HUCy5H43EYjQonw9EgDEbRMLzsD4bGB5B4A4RBJKjewkWsgcSsXCzaUMbQij4TlCtbEhBtkGsppDIClYF5ghKokdjig7LBfGvlebVonPlHa90xeVDFjTKei42Plpgp4lipWzxJTLnAe5AhFv5mTQgD9BLKx0IWz1DxBiqigB+5oJfuS/xW64avGGnGfqDlfcnTBZEO614btEKbueYxt0LTZaFc9AHz1iSxZwSoFYe/67eHwlfo/Jy2XX8zwktcEuFR1DkUN0icoC5q9TU9prT55vXNpnADjN9B2UHKmMrDiAt+YQp5D1MJiEbZZF2x4jgmUK1gy9SlgwthtoH66Nb3GQo9yMTGK0z5KKquzolXeswuGwLTC7xa2frV8vIPnPmnkso5dLlpqbNMe4bdvR0nCIR8NQlXyUGFFlhBAQHUtdgAL6rOBmxCqXi2/GlEcLy2gVOaZI6cxnoJVkQ/YpY7JHWpKlMp0USqGZFFXBsJS/GKU50nxDttx67mK05oblI4DPrRVacDtVTYr0QypjLO0yWBDSMmLpCzT5BeVRNvUFQx7sq0hvMQeaduepeGlbo7h7rw9g6jg5xuN5QMiBx7vzq0vOP9MAX2IoasnwbTMudFm8yzBHLh3jTQO7wgrFSRROVM76v6fxLgpxRs/G621TJmUuQ88Q7Nv0G9YLDvAZLoXPKK8jlqwV1nLVuOj2qAm/vqLWZsgeOnXWN1FDYzVvoslf/MgWTJTX2a0ezmhSobD++Yhm9fPj18/9tvimuN7vbOpVlDZUuqNPoHibmCHp7i4y37i0hI/f1uZW4JJR+TI2Z2E6vdO44MmeIrbbT+sg2mNWkC5Ndkvqc0eZUcjFmyWRBwuWHsJklq41cKKNluBLDPPtjxAbCWM54dJyh0fKgfx8FuHJvsLks0QlJQwOXLhuFhuhc4miAgeAZjroUBHkNqbZEita4Lg0HVhRbFKWA331ANErDvQFsuG9tCvACSErj5JJAmXNmATE7sH/0g9JH7aft7XXM8kRQz0HRaggkZ/Hr37UMh9bOUtszWHeeSwoNWEHSKPgSbMu5YOdX5zZbsY7HI+l2wYotWBYPMeXFQKpdgU7zyvinzJk1P64CZ6XN1wJq86Ml/Vvthn3QFV4GzhNOeWXYUZi9IAYALBRQuqyuC09/mVzC7sstGxfnPr0YMRgLYN95TlTG8hfNjQo8z7P0JKS80gYTJrR5KsiXT5dKk16ksAK1e0PdR2C6Z2hd4efyRAJok+4qpVpAZLav3gVH6CG3u9Bmha5EOzc8lgAULZ/7ZtdJbRt4VEH6haSbgdJtL5kEeaQJ5ZMaxziIHJHCyU3aSvO44peuEPiOavJ2fHZy952coZlgpeLPMGbunP8j87N11B+RrakzArs9XUxjCgVQjsu6+uyseBkFw3YHbYy0tBCSKrFj8Fw).

**Comment by mramato** [comment]
This seems to be a problem with all geometry in general, not just position based geometry.  Debugging points to the problem is that the primitive is never "ready" therefore we can never get it's bounding sphere for zoom purposes.  This is most likely an order of operations issue where we are getting the bounding sphere before the primitive update happens (since it's all supposed to be synchronous).

This has probably been broken for quite while and no one noticed. The fix should hopefully be simple, but we have to dig in and figure out where the root of the problem is.

**Comment by hpinkos** [comment]
Duplicate #5164

@461255824 I've added a comment to #5164 so we can notify you when it's fixed
