### ISSUE TITLE
how to dynamic polylinegeometry

### ISSUE THREAD

**Issue by chenguang1994** [CesiumGS/cesium#8801]
i want to update polylinegeometry positions ,callbackproperty  cause error , remove and add may exist blink , It's a lot of data and polyline so not think over entity. could you hele me?thx

**Comment by OmarShehata** [comment]
Please use the [Cesium forum](https://community.cesium.com/) for asking questions. Try posting what code you've tried so far [in Sandcastle](https://sandcastle.cesium.com/index.html?) and what errors you're getting.
