### ISSUE TITLE
Entity constructor fails when passed null or undefined `name`

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#8804]
Sandcastle example: [here](https://sandcastle.cesium.com/#c=tVRdT8IwFP0rTV8cCXYCPhicxAhETYwmKPrSl7pdtLG7JW2HouG/2wKTr/gBiX3penfO6TlnyUbCkJGEVzDkhCC8kjZYWeTsfjqL9tLpsa3RCYlg9irHHDnOGAzQSSfBMpFl0QdH4heKHJqE0xsETquz2VBbj9PYLNXbwjj/JLDBBkbnHXgyADbar9UPquTwoPLFk+iaZK4cVqqVNguZcGIPF5d33eoCM5RvoG7lu7dxNB9POE5+db6ly9p2Lnvdzl89OjMu1X6wuyi7wAwG/utkyxdsF6ZeWeGuB/ou1NlVf7n5b5LN0023kHBCUuHSZxKBMZXymlSj1QqYn2kTcdovQ3EaOJuQQA5iuzSGhVK7l9XYrazzXrd7/S9tNX5riFZpYt1YQWuGO5X5UBtHCqMixmIH+VAJnzh+LNIXcCy1NjCTuCQlmRwRmZ1wuvZD4JSkSljr3wx8qSEKp60k9vgVmtIik/h0MwKjxDhAnmutq9mQMZbE/rjJclqrR2GWFD8B)

Browser: N/A

Operating System: N/A

---

I did a bit of digging and eventually got lost in how property-definition interacts with `Entity#merge` as called at the end of the constructor, and I can't spend any more time on it right now.  Obviously for now the fix is to not pass a null/undefined name, but shouldn't be required -- the docs say that `name` is "optional", so an options object with no `name` should be treated the same as one with `name: undefined` or `name: null`.

**Comment by OmarShehata** [comment]
Thanks for reporting @thw0rted . This does appear to be a corner case with `name` as far as I can tell. The error returned here is:

```
DeveloperError: name is a reserved property name.
```

Where it checks if this property already exists (this['name'] exists by default but is undefined?)

https://github.com/CesiumGS/cesium/blob/ecdea14c4b57d1bd5e5eef9374e8cf1aa8b3c490/Source/DataSources/Entity.js#L526-L528

**Comment by YonatanKra** [comment]
I'm unable to reproduce this locally. Only on `sandcastle`.
Is this a sandcastle only issue?
Here's my "HelloWorld" example: http://ycc.co.il/cesium/Apps/HelloWorld.html

**Comment by thw0rted** [comment]
@YonatanKra I just wanted to check, from your PR it looks like you figured out why it wasn't reproducing.  Thanks for putting in the work!

**Comment by YonatanKra** [comment]
@thw0rted - seems like there was an issue with my local build.
I rebuilt and it suddenly showed.
I created a test for this edge case, made it pass and now it's supposed to be good to go :)
