### ISSUE TITLE
cesium 1.66 - 1.68  label fuzzy 

### ISSUE THREAD

**Issue by CaptainYYH** [CesiumGS/cesium#8807]
i found cesium 1.65 - 1.68  label fuzzy 。plz update

example

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <script src="https://cesium.com/downloads/cesiumjs/releases/1.68/Build/Cesium/Cesium.js"></script>
  <link href="https://cesium.com/downloads/cesiumjs/releases/1.68/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
</head>
<body>
  <div id="cesiumContainer" style="width: 700px; height:400px"></div>
  <script>
   var viewer = new Cesium.Viewer('cesiumContainer');

var citizensBankPark = viewer.entities.add({
    name : 'Citizens Bank Park',
    position : Cesium.Cartesian3.fromDegrees(-75.166493, 39.9060534),
    point : {
        pixelSize : 5,
        color : Cesium.Color.RED,
        outlineColor : Cesium.Color.WHITE,
        outlineWidth : 2
    },
    label : {
        text : 'Citizens Bank Park',
          font: '32px Helvetica',
        scale: 0.5,
        style: Cesium.LabelStyle.FILL_AND_OUTLINE,
        outlineWidth : 2,
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM,
        pixelOffset : new Cesium.Cartesian2(0, -9)
    }
});
viewer.scene.postProcessStages.fxaa.enabled = false
viewer.zoomTo(viewer.entities);

  
  </script>
</body>
</html>

**Comment by CaptainYYH** [comment]
and 3dtiles also have this bug

**Comment by mramato** [comment]
Cesium's default behavior changed in 1.66. From the 1.66 change log:

> * `useBrowserRecommendedResolution` flag in `Viewer` and `CesiumWidget` now defaults to `true`. This ensures Cesium rendering is fast and smooth by default across all devices. Set it to `false` to always render at native device resolution instead at the cost of performance on under-powered devices. [#8548](https://github.com/CesiumGS/cesium/pull/8548)

To get the previous behavior back set

`viewer.useBrowserRecommendedResolution = false`
