### ISSUE TITLE
Support vertical exaggeration of 3D Tiles

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8809]
This was requested on the forum here (https://community.cesium.com/t/3d-tiles-exaggeration/9423/3) and here (https://community.cesium.com/t/how-to-change-the-scale-for-box-defined-tilesets/9131/3).

The idea is to vertically exaggerate 3D Tilesets in the same way you can terrain, often for the same reasons (to make it easier to see certain features).

This is a [Sandcastle example](https://sandcastle.cesium.com/#c=lVbbbts4EP0VIi+WAYW2LDuW4zTYNuklQJsEjbuLBfxCSxObCEUKJOUmW+Tfd0hdLDtpgPrBFodzOXPmkPKWabLl8BM0eUck/CQXYHiZ07+9LeilfnmhpGVcgu6F5NdSEvxY0BpNt1pteQb6tAlMNTAL/ygtskXlEvSX8rk/X8qlrCpRk4IEuhZqBTSDwm4WYOz7NfoaWwchGqtLqKIQI5fcciZulcFf5bbrehdMW3xiMqb3WuWXsNYAJjiejukwSpIoHo6S4XA0TkIyHtKTWRSN4zieRuNkFIVkOokdsk6FG80Bm62LdBj5Aizjcn3Lbbr5roTYKzeK6GiaTGfJNBnN4iSehOQYbfE4ng0nk2EyHY1PsNyQDqfRyWwSzRDaLBlHE1+9y0rKctCMGrBuBEHNdoYEcelRnR5yEVYuagf89JVmai+Q2UIzae6VztuZfWNW88cxvbr8eL24Wvy7mxfyYrkARLNPRvUTXy6qzeAXKbVo810p+R2MKnUKnqX3Bn2usgDZHsd98vyi6ULzHAFvwVCWZUFdssJwX8rUT2MN9iMz9lppu/lRtF003iHRIJhL8gX4emP7jVJdE0jOuhJV5UxXqpRunHfFBjSyjjSBnu8CUpSVWmtWbHi6L7bG6jtr1RdUFfp1im443Xg8mGUf4LydWwXttRpW7Sp0c/Y7UEGWu+iWFkOhQ5b6xB8h+6RRXAdINdhSS5cEDc+HhN+lTMArVBtnf5Nxqz7j+WYCof3p4ObdLF9V6pMcSJXLLWgDQVMm7Kqzdgr63VTCJfL9HEi5vUCCiA5D4r98f69HV8lfInJy8A7Bznevlabvl6F5KSwvxFOnm995HOIIG4p+Q8DbvNTDb6E1EtjWb4VvKgNHfj1Xz8qpYwj9/OGsEz9IlT6o0lLMlD4EbWjnFlFKrJh7yWQqLXM8btTJQoB7/PCEl0Ovdum5oMO8rMDmP3B/ZM0uf9jk3RXa1xLWwzt3TgaDCrxp9zGS2A03pD6dqHe7AQJC8MIonr3WHSK+WRnQW7bCMXdQ9HzyXp+acmVSzVcQNKcoqKS0RyGiui7zFb5f93TG70nAzTW7rs1t0G5Utacfkn8L19eZVsqT3yrsj8/uvL30l/IoPDoz9knAeVXlL54XeHjdHR9QOrCQFxgLZrAq0wesnhrjQs8GTdBZxreEZ++WRwf/H5ZHJBXMGNy5L4W44//B8uj8bID+e2FC+ZftDR5ywZ6cyyY6/1oZKaVnA1y+jKrFgO4Vbrdz7mlofL2Vy6K0xD4VgDHIzxoxkJxLXA1p5J7ZIz5HqBxcGAtFu5Mxy45XqEO0bJko8TTUdPrVjwId0NbzJXo7IHslLTxalxibx9XkjbQ+QYP9fw) @lilleyse put together showing one way to do this today just by using the 3D Tilesets model matrix/transform to scale it.

The issue with this is that it's scaling from one fixed point. Stuart Attenborrow explains the problem with this on the forum with these two gifs:

What's currently happening:

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/a/a1ac1b90ef5c24e6b9c26b1b0389ae6023287daf.gif)

What should instead be happening:

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/9/951951b679d790d4f477e03e0e22bb0c24bd72f1.gif)

I believe this scaling would need to happen in the shader for this to have the desired effect.

**Comment by dementiev** [comment]
+1, any updates on this?

**Comment by OmarShehata** [comment]
We aren't actively working on this at the moment but we'll add to this issue if there's any update!

**Comment by avh** [comment]
Any updates? I would love to see this feature implemented...

**Comment by bmckilligan** [comment]
Just wondering if there has been any developments on this.  or perhaps even an api for point clouds that includes longitude ,latitude, elevation properties

**Comment by vectoron** [comment]
I have a need this feature to be used with the Google tile set.

**Comment by ggetz** [comment]
Support added in https://github.com/CesiumGS/cesium/pull/11655
