### ISSUE TITLE
Remote GeoJsonDataSource causes memory leak/timeline breaking

### ISSUE THREAD

**Issue by psusmars** [CesiumGS/cesium#8812]
When loading a remote GeoJsonDataSource by using a string and the class constructor like this:
```

var data = new Cesium.GeoJsonDataSource("x");

viewer.dataSources.add(data);
data.load("https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json");
```
There appears to be a render loop that occurs that causes Cesium to get stuck in processing the data. The CPU gets pegged and memory continues to increase. You are also no longer able to advance time using the timeline.

Sandcastle example: https://sandcastle.cesium.com/#c=ZVDNSgMxEH6VkEtXkASvui1CBUEEDwVPuaTJ2E3NZspkskt9epNqxWou4fsnmSyJKcAMJJYiwSzWkEMZ1euJ6xbuBNeY2IYEtLi6M8mkqaa8ZXuZeQR8ypgeqrDBQg66b/epS/kfPivrfddwM7RbRbS+M3JgPuRbrcnOahd4KNuSgVydh8TK4aj3ONikZ6To1Q5Q7euiHm1mIO2wJKZQ+8+KkW1BXss+8zHCyiRRz30YD0gsCsVOKc0wHqJlyHpb3DvUnZxbrNfnUO/DJIJfGvnnP4wULtqcq/JWYtyEDzBy1evqv4i154W0e5mAoj02y3Czev4ilVK9rvB/ihHj1tKvxk8

Browser: Chrome Version 81.0.4044.92 (Official Build) (64-bit)

Operating System: Pop!_OS 19.10

**Comment by OmarShehata** [comment]
@psusmars this is the same issue as https://github.com/CesiumGS/cesium/issues/8042#issuecomment-519591381. You can fix it by applying the suggested fix there:

```
var viewer = new Cesium.Viewer('cesiumContainer');
var dataSource = Cesium.GeoJsonDataSource.load('https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json');
dataSource.then(function(data) {
    // Change the arcType to GEODESIC, which is what it was in CesiumJS 1.53.
    for (var i = 0; i < data.entities.values.length; i++) {
        var entity = data.entities.values[i];
        if (Cesium.defined(entity.polygon)) {
            entity.polygon.arcType = Cesium.ArcType.GEODESIC;
        }
    }
    viewer.dataSources.add(dataSource);
});
```
