### ISSUE TITLE
2D INFINITE_SCROLL Drag map to appear black shadow

### ISSUE THREAD

**Issue by ccmostmosthandsome** [CesiumGS/cesium#8813]
Cesium 1.59
chrome 79
please see blog：
https://blog.csdn.net/yel_liu/article/details/85069925

**Comment by ccmostmosthandsome** [comment]
need  INFINITE_SCROLL mode，not Cesium.MapMode2D.ROTATE。
give me some ways to imporve, thanks

**Comment by OmarShehata** [comment]
You can enable infinite scroll by passing this option as your map mode: https://cesium.com/docs/cesiumjs-ref-doc/MapMode2D.html?classFilter=MapMode#.INFINITE_SCROLL.

Please use the Cesium community forum for questions: https://community.cesium.com/

**Comment by kongmoumou** [comment]
I found this bug appear every time in windows 7, even at the latest chrome 91 and cesium 1.83.

It appear in MapMode2D.INFINITE_SCROLL when u zoom out the map, every drawed entity has a black shadow. MapMode2D.ROTATE is normal but we want the INFINITE_SCROLL feature.  Could u help us? Thanks a lot! @OmarShehata 

![image](https://user-images.githubusercontent.com/35442047/125945168-126a5f69-a1eb-496e-9731-8f25bbdf0b46.png)

![image](https://user-images.githubusercontent.com/35442047/125945267-a9545c1a-568b-4643-b2f5-d860725fcbeb.png)
