### ISSUE TITLE
Line clamped to ground obscured with terrainExaggeration

### ISSUE THREAD

**Issue by vrana** [CesiumGS/cesium#8823]
Using `terrainExaggeration` with a polyline clamped to ground sometimes obscures the line. It doesn't happen with all lines at all places but I have a reproducible example. It doesn't matter if `depthTestAgainstTerrain` is disabled or not.

Sandcastle example: https://sandcastle.cesium.com/#c=pZPBjtowEIZfxcplQ5UaaGCrzbKoK3bVHlp1RVF7KD0YewjWOjayHSitePdOEmdBKVIPveF/Zv75MjNwo50ninlyR8YDej26Gd0uNW9UnaM6HNO3J01AbgFcpd+MX9StYhxQ+72M0Er6UsAyyiq/dDRMUDQ6b9XK7811esTittyDtUzqJ2t2UoBFoxk4WRaUW2AevhmrxKLJiXu3narHnyzPwWJboyssesLaSdjXdhr2reXXWouveP2cGe3RA+xVgvCadFGSM+28EerHiqTpQB0HDTRXZgVUwNZvFuD8fY5FzgdwpFgz5eA0M+NkYA5oM2Y9/mI6pWtriodm1DGuIak2lJBhOkrJq0s8ZyycFShSZczzvY/bLsn5DD4AE1LnT9LzzZzpHOIQ+MT8hnozxzDTLg7L7iXkcvx1OsBYOhj0evU2A4G3jD+DeNR4CQf8vCBD9ZbgKBMirofdwmX/mEB9XvTliBIShHBqvaQxUweFq8yaRRKyl8JvMjIcJM27wFOykqlTN6OMpfPHh5DQ4riMfD/N7f/QfgRvrlixXZj31pRaZMTbEurIsXNJ3dlhNqzxqwSmREk0cf6gYNp4EvJOFltjPSmtiinteyiwPWL2VyW6eMqdq7yr1En/vHQi5I5IcbeMOv+DZVShOoeRdanUF/kL/7PTSR/z/ypVpj6jzzuwih2qtM1w+rERKaWTPj4vV3pj1IrZjvMf

Browser: Chrome and Firefox
Operating System: Linux, others too

![image](https://user-images.githubusercontent.com/117453/81085316-5efe1e80-8ef7-11ea-90ef-96fad64f43ce.png)

**Comment by OmarShehata** [comment]
Thanks for reporting @vrana . This is already logged here: https://github.com/CesiumGS/cesium/issues/8436 so I'm closing this as a duplicate.
