### ISSUE TITLE
Cesium memory leak

### ISSUE THREAD

**Issue by h11a** [CesiumGS/cesium#8837]
Hi Guys,

I am having what appears to be a memory leak issue when using cesium js in an angular project (this happened in angular js and angular 8). 

If I create a map on a page and then navigate to and from that page the ram usage for that browser tab (i am using chrome) just keeps going up until webgl crashes. 

In my angular 8 project we initialise the map like so and add some simple gltf objects.

```
    <ac-map [sceneMode]="">
        <ac-layer acFor="let track of placeHolderObj$" [context]="placeHolderService" [debug]="true">
            <ac-model-desc props="{
                scale: track.blenderObject.positionSettings.scale.toString(),
                position: track.blenderObject.positionSettings.degreePosition,
                orientation: track.blenderObject.positionSettings.orientation,
                uri: track.blenderObject.gltfBlob.toString(),
                color: track.getAsCesiumColour(track.color),
                show: track.visible,
                shadows: Cesium.ShadowMode.CAST_ONLY
                }">
            </ac-model-desc>
        </ac-layer>
        <ac-layer acFor="let track of placeHolder$" [context]="placeHolderService" [debug]="true">
            <ac-array-desc acFor="let blenderObject of track.blenderObjects" [show]="true"
                           [idGetter]="blenderObjectIndex">
                <ac-model-desc props="{
                scale: blenderObject.positionSettings.scale.toString(),
                position: blenderObject.positionSettings.degreePosition,
                orientation: blenderObject.positionSettings.orientation,
                uri: blenderObject.gltfBlob.toString(),
                color: track.getAsCesiumColour(track.color),
                show: track.visible,
                shadows: Cesium.ShadowMode.DISABLED
                }">
                </ac-model-desc>
            </ac-array-desc>
        </ac-layer>
    </ac-map>

```
And we only do a few simple changes in the type script .e.g. setting the camera position and click listeners. 

Currently I am using your angular cesium package but this was also happening a few months ago when we were using angularjs with the regular cesiumjs library. 

Does anyone have any ideas what could be causing this memory leak and how to solve it (e.g. should we be disposing of something?)

I can provide more information if you need it. 

Browser: Chrome

Operating System: Windows

Thanks a lot.

**Comment by bampakoa** [comment]
@h11a I noticed that you are using some observables in your template (those that end with the $ character). Make sure that you unsubscribe from them when your component is destroyed. Generally, you should first have a look for Angular-based artifacts that could potentially create a memory leak.

Have you also tried to create the map and gltf objects using pure Cesium.js objects? BTW, [angular-cesium](https://github.com/articodeltd/angular-cesium) is an external 3rd party library that is not currently maintained by the Cesium team.

**Comment by h11a** [comment]
Hi @bampakoa 

I was experiencing the same issue when i was using regular js. I dont think this issue is related to the angular library. Here is some code from my original Js project.

```
                    function buildCesiumMap() {
                        var newViewer;
                        try {
                            var imageryProvider = new Cesium.GridImageryProvider({
                                backgroundColor: new Cesium.Color(1.0, 1.0, 1.0, 1),
                                glowColor: new Cesium.Color(0.9, 0.9, 0.9, 1),
                                cells: 1,
                            });

                            newViewer = new Cesium.Viewer(element[0].querySelector('#cesiumContainer'), {
                                requestRenderMode: true,
                                maximumRenderTimeChange: Infinity,
                                imageryProvider: imageryProvider,
                                baseLayerPicker: false,
                                homeButton: false,
                                navigationHelpButton: false,
                                sceneModePicker: false,
                                infoBox: false,
                                timeline: false,
                                fullscreenButton: false,
                                showRenderLoopErrors: false,
                                geocoder: false,
                                selectionIndicator: false,
                                shadows: true,
                                shouldAnimate: false,
                                navigationInstructionsInitiallyVisible: false,
                                animation: false,
                                contextOptions: {
                                    webgl: {preserveDrawingBuffer: true}
                                }
                            });
                            // newViewer = newViewer;
                            newViewer.screenSpaceEventHandler.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
                            camera = newViewer.camera;

                            cameraController = newViewer.scene.screenSpaceCameraController;
                            cameraController.minimumZoomDistance = 10;

                            cameraController.enableTilt = false;
                            cameraController.enableTranslate = false;
                            cameraController.enableCollisionDetection = true;
                            cameraController.minimumCollisionTerrainHeight = 10;

                            newViewer.terrainShadows === Cesium.ShadowMode.ENABLED;
                            var bc = newViewer.bottomContainer;
                            bc.hidden = true;
                            newViewer.forceResize();

                            var scene = newViewer.scene;

                            tronImageryProvider = new Cesium.UrlTemplateImageryProvider({
                                url: 'PLACEHOLDER_URL',
                            });
                            baseImageryProvider = new Cesium.UrlTemplateImageryProvider({
                                url: 'PLACEHOLDER_URL',
                            });


                     
                        } catch (e) {

                            newViewer = null;
                        }
                        console.log("BUILT NEW MAP");
                        return newViewer;
                    }

```
This was called when our "map-directive" was created. If we created one of these on a page then left it and came back so another was created (and repeated) the memory would just slowly increase until crash. Its like some memory isn't getting released when it is garbage collected.

**Comment by OmarShehata** [comment]
@h11a are you able to reproduce this in a [Sandcastle example](https://sandcastle.cesium.com/index.html?) that we can run?

**Comment by bampakoa** [comment]
@h11a the line `return newViewer;` seems suspicious for a memory leak. Do you clean up the viewer object that is rendered from the `buildCesiumMap` function?

**Comment by h11a** [comment]
Ok I couldn't get the angularjs imports to work on the sandcastle website so I have made a plunkr showing the behavior.

https://plnkr.co/edit/5rsKicM3Flf3QdvE

If you click on cesium then home then cesium and repeat you will see the memory usage for the tab on the task manager just keep going up. After a while webgl will crash depending on your hardware. 

All I have done is create two angularjs controllers, a home and cesium. The cesium controller just instantiates a cesium object and the home just console logs.

**Comment by OmarShehata** [comment]
I see a `new Cesium.Viewer` call but not destroy on the old viewer. That'll certainly cause resources to grow and not get cleaned up.

There is a documented issue with re-creating the viewer like this in any case: https://github.com/CesiumGS/cesium/issues/5462#issuecomment-308130948. I would try keeping a reference to the viewer if it already exists and re-using it between route changes.

**Comment by subrat71** [comment]
I am using cesium js 1.50 version with angular js application. As per my requirement i need to run two cesium instances (2D & 3D) on a single page. Data will be updated through API call and i am using CZML object structure to create the drawing elements.
Application runs for 3 to 4 hours, then chrome Dev tool crashes at 1400 iteration. 
I am running in 8GB RAM, i3 Processor.
Any help or suggestion for me me check ?

**Comment by OmarShehata** [comment]
Discussion for https://github.com/CesiumGS/cesium/issues/8837#issuecomment-640421224 moved to the forum here: https://community.cesium.com/t/cesium-js-dev-tool-crashed-when-two-instances-are-running-for-long-time/9823.
