### ISSUE TITLE
DebugCameraPrimitive uses FrameState's frustum splits even when using a custom camera

### ISSUE THREAD

**Issue by IanLilleyT** [CesiumGS/cesium#8848]
Brought up on the forum: https://community.cesium.com/t/debugcameraprimitive-depth/9603

[Example](http://localhost:8080/Apps/Sandcastle/index.html#c=dVJtb9owEP4rVr40laILaWnH1oAmAdIqrQMxWk1VJGSSg1pz7Mh2gti0/z7bGWtawP7i556XxHduqCINwx0qMiQCd2SMmtUlPPlaeJF7OJbCUCZQXVzeZaKxHp2jQGtpveChpVoypyUq+jZw7GuhF7qQVgOV1MwwKaz4v1AZe6LiGjZKlhPcKkQdDuCmfzW4TpLbq4j0P0D/ZmBR/+MgIknPr05qwRTmZ2MFbqnB8Jh4/Ha/XD1Hb3/7wIaXnQ/U1cnknEtxNvhHx79RtTZWs5HNa9ADNS8wv1/NnqaL1fLLYjo9NgikblIJ9E6EtVTbjZ5XZMI3HCrFStvnBjXQogg7F5zgut62w5kfROHvTJDDFD/9O0S+JrlUtnS4ooOwmE4y8ce3x+0gClJt9hxHzuHWZ1ZWUhlSKx4CxAbLitsJ6Hhd5z/RQK61MztpGnetacEawophFrx7h1lAck61tsym5vw7+4VZMEpjqz+yckkLJrazBhWneyd7SUZf2yIApLGFp51GSr6m6l3yXw)

Notice how the debug camera frustum is extremely large even though the near and far planes are `1.0` and `10000000.0`, which should cover less than the earth.

The problem is `DebugCameraPrimitive` is using `FrameState's` frustum splits to render frustums, which doesn't make sense when passing in a custom `Camera` object. This creates a feedback loop where the `DebugCameraPrimitive` is created, `FrameState` adjusts its frustums to fit the `DebugCameraPrimitive`, then `DebugCameraPrimitive` uses `FrameState's` frustum splits to grow even larger, then `FrameState` adjusts its frustums to fit the larger `DebugCameraPrimitive`, and so on, eventually getting quite large.

`DebugCameraPrimitive` shouldn’t be using `FrameState's` frustum splits at all, since they come from a different `Camera`. But then this will mean `DebugCameraPrimitive` can only render one frustum per camera, as `Camera` doesn’t have a concept of multi-frustum, which will break some debug visualizations in the cesium inspector.

Some fix ideas:
1) `DebugCameraPrimitive` only renders one frustum. The cesium inspector would have to render multiple frustum geometries manually using the scene's camera and the associated `FrameState` frustum splits. 
2) Create a new debug primitive type that takes a list of frustums as arguments.
3) Add multi-frustum to the `Camera` class. Not sure how this would work exactly.

I'm leaning towards option 1.

**Comment by tkazik** [comment]
Thank you for opening that issue. I agree and think that option 1 is probably the best shot:
- It is the easiest to implement
- It should be enough for 95% of the use cases
As a next step, we then could think about multiple frusta...
