### ISSUE TITLE
PixelFormat.flipY has a bug

### ISSUE THREAD

**Issue by huweijian5** [CesiumGS/cesium#8852]
in file **cesium\Source\Core\PixelFormat.js**
 
the function **flipY** has a bug,the row and flippedRow shoule be 
```
var row = i * width* numberOfComponents;
var flippedRow = (height - i - 1) * width* numberOfComponents;
```
please check it and fix it

**Comment by lilleyse** [comment]
@huweijian5 agreed, this looks like a bug. It's hard to trigger this code by normal means because the texture's source data needs to be an array buffer and needs to set flipY to true, which is an unusual combination. Do you have sample code that triggers the problem that we could test with?

**Comment by huweijian5** [comment]
i just create a new texture as below
`
let dataBuffer,width,height;//dataBuffer store the RGB binary data 

 let videoMaterial = new Cesium.ImageMaterialProperty({
        image: ""
        //image:videoTexture   //why not ？It looks invalid
    });
 let videoTexture = new Cesium.Texture({
            context: viewer.scene.context,
            pixelFormat: Cesium.PixelFormat.RGB,
            pixelDatatype: Cesium.PixelDatatype.UNSIGNED_BYTE,
            width: width,
            height: height,
            flipY: true,
            source: {
                arrayBufferView: dataBuffer
            }
        });

        videoMaterial.image = videoTexture; //but it work
`
