### ISSUE TITLE
How to add Headers information in Cesium.WebMapServiceImageryProvider

### ISSUE THREAD

**Issue by YinDake** [CesiumGS/cesium#8855]
Hello, I may not be able to access the cesium community for some reason, so I come here to ask questions. Excuse me, we are currently using the geoserver server as the map publishing server. We need to use cesium to interact with the geoserver, but our geoserver has limited access permissions. We need to use basic authentication to verify to access related services. How does cesium need to be able to add authentication information to the access header information? We have n’t found relevant interfaces and documentation after a long time. How do I get it? (This is translated by Google. If you can't understand the problem, please contact my email yq1220@qq.com. I will try to use Google Translate to describe this problem clearly. Please forgive me for my bad English)

**Comment by OmarShehata** [comment]
@YinDake can you tell me what issue you're having with the Cesium community? We've recently switched away from Google Groups so it should be accessible for everyone now:

http://community.cesium.com/

The URL you pass to the [WebMapServiceImageryProvider](https://cesium.com/docs/cesiumjs-ref-doc/WebMapServiceImageryProvider.html?classFilter=WebMap) can be a Resource object, which lets you set the headers you need: https://cesium.com/docs/cesiumjs-ref-doc/Resource.html.

**Comment by YinDake** [comment]
Thank you very much for your answer and helped me a lot! Cesium community I do n’t know why I often have access timeouts here, sometimes I ca n’t access the webpage, I guess it may be a problem with the company ’s network, thank you for your help .
