### ISSUE TITLE
ICRF view crashes on zoom

### ISSUE THREAD

**Issue by alicjamusial** [CesiumGS/cesium#8859]
Zooming into sandcastle example of ICRF view causes the camera to go inside the Earth and moving the view there causes very weird things to happen - seeing stars, poles and mirrored continents... There's no way to zoom to see cities - every attempt to do so causes this extremely weird behaviour.

Is there any way to fix that?

Sandcastle example: https://sandcastle.cesium.com/?src=Camera.html (View in ICRF)

Browser: any

Operating System: any

**Comment by OmarShehata** [comment]
I've noticed this too in the past. It is possible to zoom to cities by doing a direct camera flight (try entering `-73.9708912,40.7779202` in the geocoder for example to fly to central park), it's just that the camera controller is moving too fast at this scale. 

I think this may be something you can work around in your application by modifying the camera controller's zoom/pan speed when in ICRF so I'm tempted to close this issue, but I'm curious what others thinks. @mramato ?

**Comment by mramato** [comment]
Cesium doesn't have an "ICRF" mode as much as the Sandcastle example setting the camera transform directly to keep the camera in a continually updating ICRF-based transform.  This means that it's normal checks and balances for things such as keeping the camera above the ground do not take place.  For example, `adjustHeightForTerrain` is hidden inside of `ScreenSpaceCameraController` and completely out of the loop in the way Sandcastle's ICRF demo works.

We could probably expose more camera helpers to make implementing ICRF at the app level a little more straightforward, but I don't know if there's a dead simple solution here.  You could try exposing `adjustHeightForTerrain` as a property on `ScreenSpaceCameraController` in a local clone and calling it after lookAtTransform in the Sandcastle and see if it helps.

The geocoder is a different issue.  The camera computes a destination up front and doesn't expect the underlying transform to change "under its feet" during the flight.  We would probably have to completely change how camera flights are computed by storing start/end positions and recomputing the flight on the fly as the camera transform changes from frame to frame.  In theory it sounds straight forward but could be completely intractable so we wouldn't know until we try.

**Comment by alicjamusial** [comment]
Thank you both for the answers. I'll try to play with `adjustHeightForTerrain` and also:
> modifying the camera controller's zoom/pan speed

@OmarShehata which methods exactly would be applicable for that? How could I the most easily check how high the camera is to slow it down then? Thank you for advance for any hint.

**Comment by OmarShehata** [comment]
@alicjamusial I think you might find the answer to these questions on the Cesium community forum: https://community.cesium.com/. If not, feel free to start a new topic there!

@mramato I'm going to close this since it sounds like ICRF views are currently something the application can try to handle, but feel free to re-open/open a new issue if you think we should have one for "Built-in support for ICRF" and everything that entails.

**Comment by mramato** [comment]
@OmarShehata can you link to that forum thread?  We should leave a paper trail for anyone who stumbles on this with a similar question.

I'm okay with closing this, might be nice to flesh out a standalone ICRF Sandcastle example in the future that deals with any potential quirks, but ICRF rarely comes up.

**Comment by OmarShehata** [comment]
Sure thing! There isn't a specific forum thread that answers all these questions, but this one discusses configuring the screen space camera controller, which has other properties to control camera speed/zoom etc: https://community.cesium.com/t/what-unit-is-amount/2517

This thread discusses how to get camera height: https://community.cesium.com/t/height-of-camera-giving-negative-numbers/2289/3
