### ISSUE TITLE
Cannot find module 'cesium' in React (even after npm install) 

### ISSUE THREAD

**Issue by hsh2001** [CesiumGS/cesium#8861]
- Sandcastle example:
Sandcastle doesn't support import statemet!
```js
import Cesium from 'cesium';
```

- Browser: Error in CLI. Not a problem of browser.
- Operating System:  macOS 10.15.4
- Runtime:
  - node v12.16.3
  - npm v6.14.4

**Comment by hsh2001** [comment]
It works with require statement. 
```js
const Cesium = require('cesium');
```
Why don't you support ES6 module statement?

**Comment by hsh2001** [comment]
package.json
```json
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/core": "^7.9.6",
    "@craco/craco": "^5.6.4",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/cesium": "^1.67.5",
    "@types/color": "^3.0.1",
    "@types/jest": "^25.2.2",
    "canvas": "^2.6.1",
    "cesium": "^1.69.0",
    "craco-cesium": "^1.2.0",
    "delay": "^4.3.0",
    "node-sass": "^4.14.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "resium": "^1.11.0",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build; node dev/after-build.js",
    "test": "npx jest",
    "eject": "react-scripts eject",
    "lint": "npx eslint './src/**/*.{ts,tsx,js,jsx}'"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react-test-renderer": "^16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.32.0",
    "@typescript-eslint/parser": "^2.32.0",
    "eslint": "^6.6.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.9.0",
    "prettier": "^2.0.5",
    "react-test-renderer": "^16.13.1",
    "svgexport": "^0.4.0",
    "ts-jest": "^26.0.0",
    "uglify-js": "^3.9.3"
  }
}
```

**Comment by mramato** [comment]
@hsh2001 In the future, please ask for help on the forum, https://community.cesium.com.  If you still need help after the below answer, please start a thread there.

Ultimately, this is not a Cesium issue but instead a problem with your project configuration.  The below:

> ```js
> import Cesium from 'cesium';
> ```

is actually invalid JS code, the ability to import a module directly from NPM is something built into build tools, such as `webpack` and `rollup`, for example, https://github.com/rollup/plugins/tree/master/packages/node-resolve. When running in the browser without these tools, you need the full relative path to the specific JS file you are trying to load.

Inside Sandcastle itself, `Cesium` is automatically defined for you already.  Sandcastle is a prototype/learning tool, not meant for normal application development.

So Cesium is fully ES6 compatible and we use node resolution plugins in our own apps we build off Cesium, but you need to configure your own tools to behave that way.

**Comment by hsh2001** [comment]
(English is not my native language. Sorry for my bad english)

Yes, you are right! The import statement is not standard module system in ES. But in React, all JS/TS codes are built by `webpack` automatically. But the code below still doesn't work. 

```js
import Cesium from 'cesium'
```

Because `Cesium` does not export `default` module. In 'import/export' statement, there is a statement called `export default` that exports objects representing the module. Please refer to this link for more information.

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/export

So you have to add above script to set `Cesium` as default export.
```js
exports.default = Cesium;
```

**Comment by OmarShehata** [comment]
@hsh2001 please use the community forum for questions (https://community.cesium.com/). This helps others find the answers they're looking for as well.

You need to import the specific classes you need as in this example: https://github.com/CesiumGS/cesium-webpack-example/blob/master/src/index.js or do `import * as Cesium from 'cesium';`.

**Comment by hsh2001** [comment]
Thank you for help @OmarShehata !

**Comment by Mr-Lion** [comment]
> 
> 
> @hsh2001 bitte benutzen Sie das Community-Forum für Fragen ( [https://community.cesium.com/ ](https://community.cesium.com/)). Dies hilft auch anderen, die Antworten zu finden, nach denen sie suchen.
> 
> Sie müssen die spezifischen Klassen, die Sie benötigen, wie in diesem Beispiel importieren: [https://github.com/CesiumGS/cesium-webpack-example/blob/master/src/index.js ](https://github.com/CesiumGS/cesium-webpack-example/blob/master/src/index.js)oder do `import * as Cesium from 'cesium';`.

Hi,

First of all, thanks to all and I am pleased that I have found something meaningful here.

However, as far as the community is concerned, it is total shit there.
Because there you get as good as no answers.
My last post there was 15 days ago.

I have problems with the whole sample codes when I add them to my TypeScript file. The compiler paints me as well as everything red. It is teeming with mistakes and none gives me a clever answer.

The imports into the whole examples are all wrong, except for this here: "import * as Cesium from 'cesium';" 

Is there no discord channel for cesium, where you can support support?
The community is not only shit in answers / support, it is even in the overview of the entire forum shit.

**Comment by vtomar123** [comment]
Compiled with problems:
ERROR in ./src/component/map.js 6:0-35
Module not found: Error: Package path ./Cesium is not exported from package D:\map\fliterev-map\node_modules\cesium (see exports field in D:\map\fliterev-map\node_modules\cesium\package.json)

I have tried with may ways to import like -

>  "import * as Cesium from 'cesium';"
>  "import Cesium from 'cesium';"
> "import * as Cesium from 'cesium/Cesium';"
> "import Cesium from 'cesium/Cesium';"
>  "import { Viewer, createWorldTerrain, Cartesian3, Color } from 'cesium';"

 but still shows error

**Comment by vtomar123** [comment]
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
        
        explain this
