### ISSUE TITLE
How to use ArcGisMapServerImageryProvider to load custom TiledMapService

### ISSUE THREAD

**Issue by prohsj** [CesiumGS/cesium#8876]
ArcGisMapServerImageryProvider,the tileInfo is like below,how to set the options？

"tileInfo": {
    "rows": 256,
    "cols": 256,
    "dpi": 96,
    "format": "PNG8",
    "compressionQuality": 0,
    "origin": {
      "x": -20037700.0,
      "y": 30241100.0
    },
    "spatialReference": {
      "wkid": 102100
    },
    "lods": [
      {
        "level": 0,
        "scale": 125000.0,
        "resolution": 33.0729828126323
      },
      {
        "level": 1,
        "scale": 64000.0,
        "resolution": 16.933367200067735
      },
      {
        "level": 2,
        "scale": 32000.0,
        "resolution": 8.466683600033868
      },
      {
        "level": 3,
        "scale": 16000.0,
        "resolution": 4.233341800016934
      },
      {
        "level": 4,
        "scale": 8000.0,
        "resolution": 2.116670900008467
      },
      {
        "level": 5,
        "scale": 4000.0,
        "resolution": 1.0583354500042335
      },
      {
        "level": 6,
        "scale": 2000.0,
        "resolution": 0.5291677250021167
      },
      {
        "level": 7,
        "scale": 1000.0,
        "resolution": 0.26458386250105836
      },
      {
        "level": 8,
        "scale": 500.0,
        "resolution": 0.13229193125052918
      },
      {
        "level": 9,
        "scale": 250.0,
        "resolution": 0.06614596562526459
      },
      {
        "level": 10,
        "scale": 125.0,
        "resolution": 0.033072982812632296
      }
    ]
  },

**Comment by OmarShehata** [comment]
Hey @prohsj , for questions please use the Cesium community forum: https://community.cesium.com/. 

I'd look at the code example here: https://sandcastle.cesium.com/index.html?src=ArcGIS%20MapServer.html. If you're having trouble please post on the forum with the full code that you tried.
