### ISSUE TITLE
rotates and scales the model smooth

### ISSUE THREAD

**Issue by yoyomule** [CesiumGS/cesium#8879]
When cesium rotates and scales the model, it feels not so smooth, and sometimes there will be problems such as floating and disappearing of the model. I experienced the model operation effect of this [website,](https://app.modelo.io/share-token/lP9L1xvSJo?_ga=2.90362138.1631734895.1590563450-2048537059.1590563450) and I feel much better. Can cesium provide such parameter adjustment to meet this smooth effect.

**Comment by OmarShehata** [comment]
@yoyomule there's a few camera parameters you can tweak like inertia, see the ScreenSpaceCameraController doc: https://cesium.com/docs/cesiumjs-ref-doc/ScreenSpaceCameraController.html?classFilter=ScreenSpace

You can also lock the camera to a specific point in space so you can orbit around a model like in that link you provided, see this thread with a code snippet on how to do that: https://community.cesium.com/t/vertical-polyline-cannot-be-explored/8176

If you're still having issues please start a new topic in the Cesium community forum with some more information like how you're currently setting up the model in your CesiumJS app..

**Comment by ruanhailiang** [comment]
@yoyomule I also encountered the same problem, do you have a solution now?

**Comment by yoyomule** [comment]
> @yoyomule I also encountered the same problem, do you have a solution now?

At present, it has not been solved well. I think this is a gis system and a system that just looks at the model may be different in principle. It is not feasible to get such a good experience for the gis system.
