### ISSUE TITLE
Remove Timeline.addHighlightRange

### ISSUE THREAD

**Issue by YonatanKra** [CesiumGS/cesium#8885]
remove in [1.73.0]

**Comment by OmarShehata** [comment]
This is from this PR right https://github.com/CesiumGS/cesium/pull/8845 ? 

Why does this function get a deprecation period longer than these other two https://github.com/CesiumGS/cesium/issues/8887 https://github.com/CesiumGS/cesium/issues/8886 ? CC @hpinkos

**Comment by YonatanKra** [comment]
@OmarShehata 
I just thought more ppl are using addHighlightRange than the others so give them some more time. I'm not attached to either.

**Comment by lilleyse** [comment]
Since https://github.com/CesiumGS/cesium/pull/8845 wasn't merged I'm going to close this issue.
