### ISSUE TITLE
About cesiumScriptRegex in buildModuleUrl

### ISSUE THREAD

**Issue by xiaobaogeit** [CesiumGS/cesium#8902]
About removing some regular rules in this submission（#8251）, do you want to consider whether error will be reported when adding time stamp. 
> example:`/((?:.*\/)|^)Cesium\.js(?:\W|$)/`

**Comment by OmarShehata** [comment]
@xiaobaogeit can you explain your context a bit more here? What problem are you trying to solve?

The PR that fixes the issue linked above, changed:

```
    var cesiumScriptRegex = /((?:.*\/)|^)cesium[\w-]*\.js(?:\W|$)/i;
```

to

```
    var cesiumScriptRegex = /((?:.*\/)|^)Cesium\.js$/;
``` 

This is to make sure it finds `Cesium.js`, and can guess the CESIUM_BASE_URL path correctly. Is your library file not called `Cesium.js`? Have you tried explicitly defining `window.CESIUM_BASE_URL` if this automatic check isn't working for you?

**Comment by xiaobaogeit** [comment]
@OmarShehata  When a version stamp is added, there will be problems with the basic path obtained.
```javascript
    <script type="text/javascript" src="/scripts/Cesium/Cesium.js?v=1.7"></script>
```
So we need to modify the regular
```javascript
    var cesiumScriptRegex = /((?:.*\/)|^)Cesium\.js(?:\W|$)/;
```

**Comment by OmarShehata** [comment]
Is that version stamp typically to invalidate cache or something else?

That seems like a reasonable change to me anyway - @mramato I noticed this would have worked before your PR here: https://github.com/CesiumGS/cesium/pull/8314

Would you have anything against putting that back in as suggested?

**Comment by mramato** [comment]
Just an oversight while trying to clean things up.  The old regex was too lenient and it would mistake files like `CesiumSomething.js` as being the location of Cesium.  Happy to look at a PR that make the query use case work without re-introducing the `CesiumSomething.js` issue.
