### ISSUE TITLE
Information in provided in LICENSE.md

### ISSUE THREAD

**Issue by OliverFendt** [CesiumGS/cesium#8906]
Hi,

in the LICENSE.md file there is after the Apache-2.0 license the following statement

> Patents US9153063B2 US9865085B1 US10592242
>Patents pending US15/829,786 US16/850,266 US16/851,958

What does that mean? 
Are these patents licensed to the users of the software under the terms and conditions of the Apache-2.0?
Can you please provide clarity on this?

**Comment by OmarShehata** [comment]
You are correct, these patents are licensed to users of this software under Apache License 2.0. See specifically the "Grant of Patent License" clause here:

https://github.com/CesiumGS/cesium/blob/master/LICENSE.md
