### ISSUE TITLE
Why does the widgets folder contain css/js/png ？

### ISSUE THREAD

**Issue by lzc1718** [CesiumGS/cesium#8910]
Why don't you put css 、png in the assets file?

**Comment by OmarShehata** [comment]
Not sure why you're suggesting these files be moved to a different folder since the styling and assets in the Widgets folder contain the styling and assets for the widgets, but feel free to follow up on the forum: https://community.cesium.com/t/why-does-the-widgets-folder-contain-css-js-png/9787/2.
