### ISSUE TITLE
 How to use GIF image in billboard？

### ISSUE THREAD

**Issue by zhishao008** [CesiumGS/cesium#8916]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:

How to use GIF image in billboard？ Help!!!

**Comment by OmarShehata** [comment]
Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices.

Animated billboards are not supported but some possible implementation techniques are discussed here: https://github.com/CesiumGS/cesium/issues/2319
