### ISSUE TITLE
Is the definition of the function CesiumMath.lessThan/CesiumMath.lessThanOrEquals wrong? 

### ISSUE THREAD

**Issue by lzc1718** [CesiumGS/cesium#8917]
//bug1
 CesiumMath.lessThan = function (left, right, absoluteEpsilon) {
    //>>includeStart('debug', pragmas.debug);
    if (!defined(left)) {
      throw new DeveloperError("first is required.");
    }
    if (!defined(right)) {
      throw new DeveloperError("second is required.");
    }
    if (!defined(absoluteEpsilon)) {
      throw new DeveloperError("relativeEpsilon is required.");
    }
    //>>includeEnd('debug');
    return left - right < -absoluteEpsilon;
  };

//bug2
 CesiumMath.lessThanOrEquals = function (left, right, absoluteEpsilon) {
    //>>includeStart('debug', pragmas.debug);
    if (!defined(left)) {
      throw new DeveloperError("first is required.");
    }
    if (!defined(right)) {
      throw new DeveloperError("second is required.");
    }
    if (!defined(absoluteEpsilon)) {
      throw new DeveloperError("relativeEpsilon is required.");
    }
    //>>includeEnd('debug');
    return left - right < absoluteEpsilon;
  };

**Comment by kring** [comment]
No, that is correct, even though it looks a little weird flipping the sign like that. Remember that if `left - right` is between `-absoluteEpsilon` and `absoluteEpsilon`, then the two numbers are considered _equal_ and thus `lessThan` should return false.
