### ISSUE TITLE
UrlTemplateImageryProvider minimumLevel and maximumLevel

### ISSUE THREAD

**Issue by kamiedge** [CesiumGS/cesium#8920]
Hi, when i try to set minimumLevel or maximumLevel, cesium freeze 

Sandcastle example: https://sandcastle.cesium.com/#c=bVBNi8IwEP0roRcVZIKwl621LHhaEHZhP065xHbUsPkoSRqtpf99U1tYVw0kMG/eezMvgVsSBB7RkhXReCRrdKJW8H3BpiwpLvXaaM+FRsuS2ZJppkPUCcX3aJv/wi8rP1FVknt8Hfrv1gRRRrOWaRJPbSVJyeTgfeVSSlvXgRcSwVSonbeIXvEKdpYap+LbnjvanuJtOqj0fjIfXChVQgtVqw0GlCl5/sP56QpfPDHdjTtfMsG49oY3aB3wsrzdcyTMlsk8yZxvJOaDNyEvQlXG+j7DFID6Mamj27r4QQ+Fc/2snprRa2lWikBEuXrwoaSQ3LnY2dVSfogzsiTPaOTfSaXhpdD7t4BW8qanHRb5ZgABIKOxfKz0xsgttzfOvw

Browser: 
Chrome 83.0.4103.61 (Official Build) (64-bit)
FireFox 77.0.1 

Operating System: MAC 10.13.6

**Comment by xiaobaogeit** [comment]
@kamiedge  Because the `minimumLevel` setting is too large

https://github.com/CesiumGS/cesium/blob/2d3852c31c3874f0a2e3bb30e24e5d4c4104ce2b/Source/Scene/UrlTemplateImageryProvider.js#L110-L112

**Comment by mramato** [comment]
Thanks for the assist @xiaobaogeit 

@kamiedge we request that you use our community forum, https://community.cesium.com, for support in the future. We try to reserve GitHub issues for confirmed bugs and feature work.

Thanks!
