### ISSUE TITLE
Wrong type definition for EllipsoidTangentPlane.fromPoints

### ISSUE THREAD

**Issue by zoran995** [CesiumGS/cesium#8926]
Hi,
function `fromPoints` in `EllipsoidTangentPlane` has wrong type definition
[source code](https://github.com/CesiumGS/cesium/blob/2bdece46e5bef742a8cda20dfd5560f16a487e80/Source/Core/EllipsoidTangentPlane.js#L58-L59)
[doc](https://cesium.com/docs/cesiumjs-ref-doc/EllipsoidTangentPlane.html?classFilter=ellipsoid#.fromPoints)

**Comment by OmarShehata** [comment]
Thanks for reporting @zoran995 . I can see that its input is stated as `Cartesian3` when it should be an array of `Cartesian3`. 

CC @mramato

**Comment by mramato** [comment]
Thanks, will fix this ASAP and it will be out with 1.70.1 later this week.
