### ISSUE TITLE
wgs84ToWindowCoordinates returns undefined for negative z

### ISSUE THREAD

**Issue by jony89** [CesiumGS/cesium#8946]
Hey,

I have noticed that `SceneTransforms.wgs84ToWindowCoordinates` returns `undefined` for cases where z value in a 2d world is negative (does that means the coordination behind the camera?)

What is the logic behind this? why are we returning `undefined`?

These are the lines in `SceneTransforms.js`:

```js
    if (
      positionCC.z < 0 &&
      .....
    ) {
      return undefined;
    }
```

**Comment by OmarShehata** [comment]
@jony89 please use the forum for general questions (https://community.cesium.com/). It helps to understand the context of your use case, if this is causing an issue in your app etc.

Here's the relevant section of the code here: https://github.com/CesiumGS/cesium/blob/638c6ebffe86a17637acc8dc5c223f404131f993/Source/Scene/SceneTransforms.js#L242-L251

It looks like this check only applies for perspective cameras, which implies that a point with a negative Z in clip space is not on screen.
