### ISSUE TITLE
How do go about creating 3d tileset classification?

### ISSUE THREAD

**Issue by digiiitalmb** [CesiumGS/cesium#8951]
I want to classify my 3d tilesets, can someone let me know what software can be used to generate classification tileset? 

I see this tileset in sandbox examples
https://github.com/CesiumGS/cesium/tree/master/Apps/SampleData/Cesium3DTiles/Classification/Photogrammetry

But can't find any information on how it's being produced.

Would appreciate if anyone could point me into the right direction. Maybe there is some app that allows generate classification tileset?

Thanks

**Comment by OmarShehata** [comment]
Hey @digiiitalmb - please ask questions on the Cesium community forum: https://community.cesium.com/. 

There's nothing unique about classification tilesets, you can create them the same way you create any other 3D Tilesets. There's a couple of different ways you can do this depending on your use case so please post your question to the forum and let's discuss it there.
