### ISSUE TITLE
Artifacts in classification example in 1.70?

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8953]
This was reported over email - the classification example (https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Photogrammetry%20Classification.html) has these artifacts, almost as if the the classification tileset is being clipped too early by the near plane, only on mobile (Android or iOS). 

I put together an example on Glitch to make it easier to test on mobile (you can fork it and change the CesiumJS include to 1.69 to see that it works there, and the artifacts are only present in 1.70.

https://glitch.com/edit/#!/classification-cesium-error?path=index.html%3A5%3A68

### 1.70

![Screenshot_20200612-122848](https://user-images.githubusercontent.com/1711126/84529864-31538480-acb0-11ea-9dd0-aa4feed519b1.png)

### 1.69

![Screenshot_20200612-122903](https://user-images.githubusercontent.com/1711126/84529860-2ef12a80-acb0-11ea-8aeb-8db91db95d96.png)

**Comment by OmarShehata** [comment]
I don't see an obvious place to start looking as the cause of this break in the CHANGES for 1.70, any advice @lilleyse ?

**Comment by IanLilleyT** [comment]
Either https://github.com/CesiumGS/cesium/pull/8854 or https://github.com/CesiumGS/cesium/pull/8870

**Comment by OmarShehata** [comment]
Git bisect confirms this is the commit that introduced this issue: https://github.com/CesiumGS/cesium/pull/8854/commits/2da52de16d6a3022278a328d8242f17e10f28f02

**Comment by OmarShehata** [comment]
Marking as priority next release since it's a regression that's breaking some people's applications.

**Comment by IanLilleyT** [comment]
If we figure out why this regression happened, it might help us understand non-3D Tiles classification bugs on mobile. Last time I looked I didn't have any leads, but I'll look some more soon.

**Comment by IanLilleyT** [comment]
Haven't had a chance to look into this enough, so it should be pushed to the next release (again). It's looking like a multi-frustum problem though.

**Comment by lilleyse** [comment]
`git bisect` points to https://github.com/CesiumGS/cesium/commit/2da52de16d6a3022278a328d8242f17e10f28f02

It's a multi-frustum problem that can be triggered by disabling log depth.

[Local sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=vVXbbts4EP0VwS+RsC6tq2U1TrCObSAGmjZw1C4WdVEw0tgiSokCSTnVFvn3HVmyYzsBdp+qF4mcczhnLhxtqTS2DJ5AGldGAU/GFBSrcvJlt2deJLvlVBSasgLkRd/4tSoMfDRIiVv3UmxZCvL9nphIoBr+EpKncQsxrVXxbF2uitYPUQkUQDZcPAJJodRZDEpPNohUuqOgFi0rOOdwsaGS6Sxnyawh3lTr9U74mnLVoBGP8WjGQYE+Dah9ebO4NZq/jEryg+qFKJagRCUTIGsp8olCzCI1h3boW8Zr9aVkOdNsC4rQNDU7j9ZOQrcgmIi0xvzkTAHRGRTmuioSzQRmpEtio/ZRVEXKis1DmYGEJvKOf2q47BitioTmIClpVjcnMPOU1T9OwS0KQss900m2pMUGTJvYfeOdTYL+mQwiEVop4w8jsBFkWW+650L8mOhY0kKthczNzs8d1ZL99MliNv8YL+K/G/KzdSgPYIZ0jYF2h+3WrMtkl5hS8HojCuP9vt2aJ2PoVCZZjdtHYd232Nu9dS9jSqXGL1p4u5IuMSIUOsEGq82v7xziOZHvDSM3DD3Ht123b9hkGI1G9tANPDuymzdmZwf0oiCIRrZr+64THoCRE4SjMHTcwH8Beo7r2lEQecM9MEQ3nutH9mh4OND3gpHr+rYf+PbogAudaBgEwTCKRt8sq/8Seo53SjLKjUPHTgUXkiznM/KEN2LCy4xiOYNjUsKpUmzNEto0XVyXcER/ZSM3n+Lblvx8Ui9RNhCFBft6uPs/NR510R1SGzdCZxedZ4QCh6QBvPT7cRnb+pOuxOQNlVf/ofLyRebRPDrT1I2S3yQrni+Xk8XH/6XMmxm7KfSbpE3nD4vPd9+92fd48WF+pPAbfj/QIk2o0hya6xcLwR+pvIOiMruyN33Q6/fGStccrvea/mR5KaRuZqhJyEBDXnJsUTV4rJIfOLsSpfYjYzw4po5TtjVYerXqnf1ZVr22X9Gyrjh/YP/Aqnc9HiD+FZWL3SD7tAXJad3AMuf6Q7tJCBkPcPk2U7cBnp38Lw)
