### ISSUE TITLE
Failed to execute npm run release

### ISSUE THREAD

**Issue by verybigzhouhai** [CesiumGS/cesium#8961]
Hi，
I am not sure if this is a problem,
When I execute the npm run release command, an error is thrown: No gulpfile found.
Is it because of gulpfile.js -> gulpfile.cjs. I tried to "release": "gulp release" -> "release": "gulp -f gulpfile.cjs release" in package.json, the command can be executed correctly.

![image](https://user-images.githubusercontent.com/37999729/84747131-7564c300-afe9-11ea-9c36-268a947f4eb7.png)

**Comment by OmarShehata** [comment]
Hey @verybigzhouhai - I'd ask on the forum if you're not sure if what you hit is a bug or not: https://community.cesium.com/

I think you just need to run `npm run build` to generate that file before running `npm run release`.
