### ISSUE TITLE
A lot of  Lables  are drawn by LableCollection  ,but it is very Caton  （The label will be drawn, but wait for a while）

### ISSUE THREAD

**Issue by yankai12** [CesiumGS/cesium#8971]
var labelboard = viewer.scene.primitives.add(
        new Cesium.LabelCollection({ scene: viewer.scene})
      );
// array.length=3000
 for (let i = 0; i < array.length; i++) {
let tmp = array[i];
let lon = parseFloat(tmp.geometry.coordinates[0]);
let lat = parseFloat(tmp.geometry.coordinates[1]);
  labelboard.add({
          position: Cesium.Cartesian3.fromDegrees(
            parseFloat(lon),
            parseFloat(lat)
          ),
          text: text,
          font: "15pt  Source Han Sans CN",
          style: Cesium.LabelStyle.FILL_AND_OUTLINE,
          // clampToGround: true,
          //  heightReference : Cesium.HeightReference.NONE,
          heightReference: Cesium.HeightReference.CLAMP_TO_GROUND,
          outlineWidth: 5,
          verticalOrigin: Cesium.VerticalOrigin.BOTTOM, //垂直位置
          horizontalOrigin: Cesium.HorizontalOrigin.LEFT, //水平位置
          pixelOffset: new Cesium.Cartesian2(5, 0), //偏移,
          pixelOffsetScaleByDistance: new Cesium.NearFarScalar(
            1000,
            4.0,
            15000,
            0.9
          ),
          scaleByDistance: new Cesium.NearFarScalar(1000, 1, 15000, 0.9),
          translucencyByDistance: new Cesium.NearFarScalar(
            1000,
            1.0,
            400000,
            0.9
          ),
          distanceDisplayCondition: new Cesium.DistanceDisplayCondition(
            10.0,
            8000.0
          )
        });
}

**Comment by yankai12** [comment]
I am so  sorry  
    let tmp = array[i];
        let lon = parseFloat(tmp.geometry.coordinates[0]);
        let lat = parseFloat(tmp.geometry.coordinates[1]);

**Comment by yankai12** [comment]
he Label will be drawn, but wait for a while

**Comment by OmarShehata** [comment]
Please use the Cesium community forum for questions: https://community.cesium.com/. 

CesiumJS constructs geometry/entities asynchronously, which is where the delay comes from (otherwise the browser will freeze while this computation is happening).

**Comment by yankai12** [comment]
I found a strange problem, if I give text a value by default, instead of taking it from the array, the efficiency is very fast

**Comment by OmarShehata** [comment]
Can you post a full Sandcastle example I can run? [See instructions here](https://community.cesium.com/t/how-to-share-custom-sandcastle-examples/9828).

**Comment by yankai12** [comment]
I have about 3000 points, the main slow process is that the process of generating pictures with different text is stuck

**Comment by yankai12** [comment]
I have about 3,000 points. The main slow process is that the text is stuck in different texts. If the text is the same, there will be no stuck.

**Comment by yankai12** [comment]
you can try

**Comment by yankai12** [comment]
A lot of  Labels can be  Caton  ,I try to  use Worker to solve it But it is  no  significant effect

**Comment by OmarShehata** [comment]
@yankai12 please post your question on the community forum: https://community.cesium.com/

**Comment by yankai12** [comment]
Thank you

**Comment by HelenGiser** [comment]
@yankai12 Hi! Have you solve this problem yet？I have the same puzzle.

**Comment by yankai12** [comment]
ye



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HelenGiser"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 晚上6:37
收件人: "CesiumGS/cesium"<cesium@noreply.github.com&gt;; 
抄送: "上善若水"<614018819@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [CesiumGS/cesium] A lot of  Lables  are drawn by LableCollection  ,but it is very Caton  （The label will be drawn, but wait for a while） (#8971)





 
@yankai12 Hi! Have you solve this problem yet？I have the same puzzle.

**Comment by HelenGiser** [comment]
Give me some hints ? @yankai12

**Comment by HelenGiser** [comment]
> ye
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HelenGiser"<notifications@github.com&gt;; 发送时间: 2020年11月12日(星期四) 晚上6:37 收件人: "CesiumGS/cesium"<cesium@noreply.github.com&gt;; 抄送: "上善若水"<614018819@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [CesiumGS/cesium] A lot of Lables are drawn by LableCollection ,but it is very Caton （The label will be drawn, but wait for a while） (#8971) @yankai12 Hi! Have you solve this problem yet？I have the same puzzle. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Cound you give me some tips?
