### ISSUE TITLE
Polyline with height height greater than 0 breaks Datasources hierarchy

### ISSUE THREAD

**Issue by Lampent** [CesiumGS/cesium#8980]
The bug occurs when we add to a polyline inside a Datasource a 'height' property with a value greater than zero. When creating polyline with 'height' greater than 0, the polyline ignores the DatasourceCollection Hierarchy and goes above all entities.

The required view to reproducing the bug is 2D.

The following code creates two Datasources, one that contains cesium Entity with polyline and one that contains cesium Entity with a billboard.

[The first example works as expected, the polyline will be under the billboard (same as the Datasources hierarchy).](https://sandcastle.cesium.com/#c=jVNdb5swFP0rV7xAJGZEu2gSpdG0TNpLpT202suoKoMdYs34In8QpVP/+wyUNiSNMp7uPT7n+H6YjmroBN9xDbeg+A7W3AjXkF8DFhVBNeRrVJYKxXURLG4K1XkVo5beo9MVT+fStTMWm+9vx1FosX1Pw1ODq0sGJdoZMngU6sCBcGWFFdwQylj0t1AwfIo2PIPwh+Zcgd66pgTp2wjjidCi3PdIBm+aV9x4O1Qmg99TWVRbH1F1TTbaV8Nr72qiT1+WMVwvFzFc4KVXI/Exnt20E8xuM0jJcoJfCvVy3GB6psGpzgz+s8pJWAopS6SaHXcuGlr3MyMkGUKTjM5Pd1jjE3ZcS7onrarDGJIEGN9QJ20GTvnQT5LN3MwWdxlY7fghe06pqPQXfj5tf3yY5H0KY/MHax/e0iVWeoYl0SMP+G14XGf4z4jNA0av2bSDxU0QB7mxe8lXU9lfRdOituC0jPzsLG9aSf0qktJVf7gllTG9b0/Nk0NpzkQHgt1+8K9BJakx/mTjpLwXz7wIVnni+SdSiZQJVf8c19PTtunqbgQJIXni04+VFlGWVB85/wM)

[In the second example, bug reproduced, the polyline will go above the billboard regardless of Datasources Hierarchy.](https://sandcastle.cesium.com/#c=jVNdb5swFP0rV7xAJGZEu2gSpdG0TNpLpT202suoKoMdYs34In8QpVP/+wyUNiSNMp7uPT7n+H6YjmroBN9xDbeg+A7W3AjXkF8DFhVBNeRrVJYKxXURLG4K1XkVo5beo9MVT+fStTMWm+9vx1FosX1Pw1ODq0sGJdoZMngU6sCBcGWFFdwQylj0t1AwfIo2PIPwh+Zcgd66pgTp2wjjidCi3PdIBm+aV9x4O1Qmg99TWVRbH1F1TTbaV8Nr72qiT1+WMVwvFzFc4KVXAzGGdPEYzy7bCWa3GaRkOcEvhXo57jE90+NUagb/WegkLIWUJVLNjpsXDa37sRGSDKFJRuenO6zxCTuuJd2TVtVhDEkCjG+okzYDp3zoh8lmbmaLuwysdvyQPadUVPoLP5+2P75N8j6FsfmDzQ/P6RIrPcOS6JEH/Da8rzP8Z8TmAaPXbNrB4iaIg9zYveSrqeyvomlRW3BaRn52ljetpH4VSemqP9ySypjet6fmyaE0Z6IDwW4/+N2gktQYf7JxUt6LZ14Eqzzx/BOpRMqEqn+O6+lp23R1N4KEkDzx6cdKiyhLqo+c/wE)

Note that the only difference between the two examples is that in the second example one of the polylines coordinates as a height of 1. 
 "positions: [Cesium.Cartesian3.fromDegrees(-75, 35), Cesium.Cartesian3.fromDegrees(-125, 35, 1)],"

I am assuming this is a bug because in other graphic entities like BillboardGraphic when creating an entity with a height greater than zero the entity will not break the Datasources hierarchy.
[Billboard with height under another billboard (same hierarchy as Datasources).
](https://sandcastle.cesium.com/#c=zVNNT8JAEP0rm14oSd2mKjGplRjxaOIB4qmXaXeKG7c7ZD9K0PDfXYogiMaLB/c08/a9177ptAPDOolLNOyGaVyyCVrpW/7UY3EZ1X0/Ie1AajRlNLwudRdUAhxMyZsas2PpxFtH7f3+Oh44Wny2g1OD898MKnJHSO9R6gMHjtpJJ9FyECJ+KzXrz4JsQEnne28wLlSgL3hjgiXODaKNz65GCbsYDZOdsJJKVQRG5Gxv1h/ZwhxzNuA87UubNlBLJd2Kz2UzSFiaMoENeOVy5nUow9jEkYV9pmXOnPF4yD6m1KDCU6524LrU66+Zs7/JnLDsv8W+PI293VH+mX4b+mAD+rX6jZX9wFIUkBnd9Xv2g+srUTuj+KPbzX54HSVRYd1K4Xj32reyXZBxzBsVh4E5bBcKwidIK1+/oOO1tRvfDbVID6WFkB2T4uab347VCqwNN41XaipfsYzGRRr4J1JFIKSeP3ZoFKw2tOds/LAFOedFGtrvlY5IVWC+OL8D)

Cesium view: 2D

Browser: Chrome

Operating System: Windows

**Comment by hpinkos** [comment]
Thanks @Lampent, this is a known issue.  I have added a comment to https://github.com/CesiumGS/cesium/issues/3647 so we can notify you when the issue is fixed.
