### ISSUE TITLE
Simple Rollup app example

### ISSUE THREAD

**Issue by rapha-opensource** [CesiumGS/cesium#8982]
It would be very helpful to have a sample app with Rollup, similar to [cesium-webpack-example](https://github.com/CesiumGS/cesium-webpack-example).

I'm trying to setup a basic Svelte/Sapper app that loads the Cesium viewer, it is proving to be difficult. Specifically the loading of assets (Assets, Widgets, Workers, etc.)

**Comment by hpinkos** [comment]
Thanks for the suggestion @rapha-opensource!  We're currently in the process of planning new learning material and we will consider adding something like this.

In the meantime, I would recommend posting in our [community forum](https://community.cesium.com/).  There may be someone who is using rollup that can help.

**Comment by sanjeetsuhag** [comment]
@rapha-opensource I've been experimenting with Svelte and I wrote up a post on the community forum about (using CesiumJS in a Svelte application](https://community.cesium.com/t/using-cesiumjs-with-svelte/10341).

**Comment by TJKoury** [comment]
Check out [c137.js](https://www.npmjs.com/package/c137.js).  [Here's an example](https://github.com/DigitalArsenal/cesium-webpack-example/tree/c137.js) using it with Rollup.
