### ISSUE TITLE
How tile  exchange high level  to low level  and  low to high?

### ISSUE THREAD

**Issue by VINOlive** [CesiumGS/cesium#8985]
![level12](https://user-images.githubusercontent.com/7323049/85359436-d429bf80-b548-11ea-9813-fb6fcff30d78.png)
![level13](https://user-images.githubusercontent.com/7323049/85359456-e3107200-b548-11ea-882e-fdcab90da32b.png)

To meet the requirements of the scenario, I need to know the method how different level tile exchange.
I read the source of Cesium, but finally almost give up,  it was so complicated .
I found the `_createTileImagerySkeletons` ,  `getImageryFromCache`,   `removeImageryFromCache` method, but how tile exchange or replace ?

Any help thank u!

**Comment by OmarShehata** [comment]
Hey @VINOlive , for questions please use the Cesium community forum: https://community.cesium.com/. We use GitHub issues for tracking bug reports and feature requests.
