### ISSUE TITLE
Transforms.eastNorthUpToFixedFrame can't calculate the right coordinate system if HAE is not zero

### ISSUE THREAD

**Issue by renjianqiang** [CesiumGS/cesium#8989]
I think there is problem to calculate the NEU coordinate system, look for these code:
```javascript
var center = Cesium.Cartesian3.fromDegrees(45.0, 45.0, 0);
var transform = Cesium.Transforms.eastNorthUpToFixedFrame(center);
//up: (0.5000000000000001, 0.5, 0.7071067811865476)

var center1 = Cesium.Cartesian3.fromDegrees(45.0, 45.0, 10000000);
var transform1 = Cesium.Transforms.eastNorthUpToFixedFrame(center1);
//up: (0.49897299707101883, 0.4989729970710187, 0.7085562055249607)
```
The `transform`'s up vector is not equal to  `transform1`'s because they have different height, but i think these should be equal. so
 i look at the code, then i found these code: 
```javascript
//Transforms.js
ellipsoid.geodeticSurfaceNormal(origin, scratchCalculateCartesian.up);
```
I think that is the problem. the `origin` maybe not on the ellipsoid , but `ellipsoid.geodeticSurfaceNormal` can only figure the `origin`'s  normal vector which is right on the ellipsoid. The `origin` should `scaleToGeodeticSurface` just like this:
```javascript
var p = Ellipsoid.scaleToGeodeticSurface(origin, new Cartesian3());
```
Further more, there are some way easier to figure out the NEU if we know the geographic coordinates:
```
up = (cos(longitude)*cos(latitude), sin(longitude)*cos(latitude), sin(latitude));
east = (-sin(longitude), cos(longitude), 0);
north = Cartesian3.cross(up, east);
```

I think it should be fixed even there is a little difference between `transform` and `transform1` in application. 
If this is a bug, please fix it, or let me know why.
Thanks.

**Comment by renjianqiang** [comment]
is there anyone can help me solve this promblems?

**Comment by OmarShehata** [comment]
I'm not sure what the intended behavior of `Cesium.Transforms.eastNorthUpToFixedFrame` should be when the given point is not on the surface. The suggestion here is to scale the given point with `scaleToGeodeticSurface`. 

@hpinkos what do you think?

**Comment by renjianqiang** [comment]
Thanks for your reply.  I'm not sure the intended behavior too if the elevation is not zero, but i think most of developers will use `Cesium.Transforms.eastNorthUpToFixedFrame` to generate a coordinate frame for the purpose which place a model on a high mountain or satellite.
If the point must on the surface, the cesium should restrict the condition in implementation, or illustrate in the documentation. Otherwise,  the step that scale the given point with `scaleToGeodeticSurface` should be integrated into `Cesium.Transforms.eastNorthUpToFixedFrame`.

**Comment by renjianqiang** [comment]
By the way, can anyone tell me this is right?
![image](https://user-images.githubusercontent.com/16470294/87427904-13ad6e00-c614-11ea-8e50-5882eae95009.png)

**Comment by hpinkos** [comment]
You're right that theoretically the `up` vectors of these two transforms should be the same regardless of the height of the position.  It looks like the very large height value is resulting in a slight loss of precision for the `geodeticSurfaceNormal` calculation.  We would have to investigate whether any changes to `Transforms.eastNorthUpToFixedFrame` negatively impact performance. 

That being said, even though the values look different, the difference between the resulting transforms is negligible as demonstrated in [this sandcastle example](https://sandcastle.cesium.com/#c=vVPLbtswEPyVhU4KIKwsNL6oilHAaU5OU6BpgwK60OLaJkqRAknJSYv8e0nRr6Y+pDlUB0Jc7QxnVsOBGRgEbcnAFSjawpys6Fv8NtbSOmnG/Vwrx4QiUycX72tVq4hBUk44QRYZ5+mvWgF02vqKVuWeac6M829MvcOV0e01rQ2RTS+nOMkgrsUkPhdZZBDKlTCy+Z14JPlF/KTSt2Wx1mipzfGAsMPvHxeLu4ex4dmvz1GmF+oNNl7maPD1kiYBH7DOMGVX2rRH+P2+ZJGYdZ+0cZuv3b2+8VL5jWEtpfHEwLHD3DJnxOMlWnIjXLIwpPTAnr1pXEd1u79yMFv8k9sD40vTxRtcF38kxPoiYWdE62Mx7JJyErRrWvbrW81JxhF93nfGOLXHL1DCybggz+HACk4DD0QBIkmt3QbKnSuMqdkKHos4Cen4DxqLV4mcntE43WtMsqSy7knSLAYf4INoOz956I1MEXNHbeejRDZf9s0PcthYG6yF1io/hVZcDCD41ZkbDY1k1vovq16OV61OZlXu+/+CSs24UOu7gYxkT6FtU8wWsYiIVe6355FOa7lk5gXzbw)

There is nothing actionable for us to do here.  @renjianqiang I suggest adjusting the height in your application if the lack of precision for positions very far away from the earth is resulting in a noticeable error in your application.

**Comment by renjianqiang** [comment]
Thanks a lot! I will compute the NEU on the surface and move it to the original height.

I know there is only a very little error, and for performance reasons will not modify the implementation, but i really suggest to illustrate this problem in the documentation.

**Comment by renjianqiang** [comment]
Thanks a lot! @hpinkos 
I will compute the NEU on the surface and move it to the original height.

I know there is only a very little error, and for performance reasons will not modify the implementation, but i really suggest to illustrate this problem in the documentation.
