### ISSUE TITLE
cesium uses czml to load gltf model

### ISSUE THREAD

**Issue by yiwenzhang666999** [CesiumGS/cesium#8990]
After cesium loads the gltf model with czml, the initialization angle is wrong, how to adjust,How to make the direction of the car and the road direction consistent after initialization
![car](https://user-images.githubusercontent.com/31643589/85512227-3c050680-b62c-11ea-9e31-0e5b5b764ed5.JPG)

**Comment by OmarShehata** [comment]
Please use the Cesium community forum for questions: https://community.cesium.com/. We use GitHub issues for tracking bugs and feature requests.
