### ISSUE TITLE
glTF file can not see in Cesium 1.70 without Errors

### ISSUE THREAD

**Issue by superLicw** [CesiumGS/cesium#9007]
Here are two glTF files of my own, which is normally displayed in the windows 3D viewer, but cannot be displayed when them been loaded into cesium through the code.
Is there any expert here who can help to see why?
 I put them here：

[https://drive.google.com/file/d/1e1EJjCs_XSLGUoSMLBMBnp29teza5ZmM/view?usp=sharing](https://drive.google.com/file/d/1e1EJjCs_XSLGUoSMLBMBnp29teza5ZmM/view?usp=sharing)

[https://drive.google.com/file/d/1lYZ_eaP4FXDtuqoSxBcGarzam_12QnkT/view?usp=sharing](https://drive.google.com/file/d/1lYZ_eaP4FXDtuqoSxBcGarzam_12QnkT/view?usp=sharing)

Thank you very much.

**Comment by OmarShehata** [comment]
Answered on the community forum: https://community.cesium.com/t/gltf-file-can-not-see-in-cesium-1-70-without-errors/10054.
