### ISSUE TITLE
Test Failure - Scene/GroundPolylinePrimitive/picking in Columbus View

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9008]
When running [Scene/GroundPolylinePrimitive](http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FGroundPolylinePrimitive) specs together, the `"picking in Columbus View"` test fails. However, when run on its own, it runs fine.

The test suite ran fine until https://github.com/CesiumGS/cesium/commit/97492e7a29e55905acb5f3a84d026047dcf901b8.

**Comment by mramato** [comment]
That commit doesn't make any sense to me in terms of how it could have caused this.  I did a bisect and it pointed to 4e730efd99bab6ef32237633dae88d2415b9b1d2, which also makes no sense.  So I have no idea what's going on here.
