### ISSUE TITLE
Instance rotation?

### ISSUE THREAD

**Issue by bertt** [CesiumGS/cesium#9014]
I'm trying to horizontally rotate instances in an i3dm tile to an angle (instance pointing north = 0, east = 90, south = 180, west = 270) but can't get it working in Cesium. In my case every instance has an own rotation angle. 

I'm trying things out with defining NORMAL_UP and NORMAL_RIGHT unit vectors per instance but either the instances are drawn but not rotated (so pointing north), or the instances are not drawn at all.

Any pointers/samples how to get this working?

**Comment by bertt** [comment]
a function something like this? https://github.com/PrincessGod/objTo3d-tiles/blob/master/lib/obj2I3dm.js#L166

**Comment by OmarShehata** [comment]
@bertt can you post your question to the Cesium community forum? https://community.cesium.com/

We use GitHub issues for tracking bug reports and feature requests.

**Comment by bertt** [comment]
ok see https://community.cesium.com/t/instance-rotation/10163

**Comment by xsxWang** [comment]
> ok see https://community.cesium.com/t/instance-rotation/10163

how to set the size of every instance in an i3dm tile？such as a box ,there are two instance in an i3dm tile, but different size，different length or different width or different height or  both?

**Comment by bertt** [comment]
In the feature table there is scale (1 value for all directions) and scale_non_uniform (vector3) defined per instance.

**Comment by xsxWang** [comment]
thank u！
yes，i‘m thinking about the 'scale_non_uniform',but the direction of some instance is wrong ,like this:
![QQ图片20201224165851](https://user-images.githubusercontent.com/41726838/103076859-9dbd2200-4609-11eb-995f-44d5f1ea0948.png)

**Comment by bertt** [comment]
the directions are defined in NORMAL_UP and NORMAL_RIGHT

**Comment by xsxWang** [comment]
> the directions are defined in NORMAL_UP and NORMAL_RIGHT

first time, i set NORMAL_UP and NORMAL_RIGHT and not set 'scale_non_uniform' , it is not wrong.
second time, i set NORMAL_UP and NORMAL_RIGHT, also set 'scale_non_uniform' , it is wrong

im confused.
