### ISSUE TITLE
Camera.position was error after use viewer.flyTo()

### ISSUE THREAD

**Issue by wemamawe** [CesiumGS/cesium#9016]
hi, I use viewer.FlyTo() to move the camera to a position, then the camera shows like the picture. 
![image](https://user-images.githubusercontent.com/29365634/86432985-06e36d00-bd2c-11ea-9a7c-351c98b69f5f.png)

i use mouse to zoomTo the destination, which is same place , then the camera shows like the bellow picture.
![image](https://user-images.githubusercontent.com/29365634/86433010-1498f280-bd2c-11ea-90fa-88e10e87bdf6.png)

**Comment by mramato** [comment]
@wemamawe The camera position property itself is not enough to tell you the location, it depends on the transform as well, which defines the camera's reference frame. This is not a bug and working as intended.

If you need help trying to do something with Cesium, please ask questions on our community forum: https://community.cesium.com.

Thanks.

**Comment by wemamawe** [comment]
@mramato thanks for your answer;
 after i use `viewer.flyTo() `
,the camera move to a position , and then, if i want to use `camera.rotateLeft()`, the camera will rotate faw away, just rotate 1 degree.
