### ISSUE TITLE
How to make my 3dtiles beautiful like this?（http://cesium.marsgis.cn/cesium-example/editor.html#63_jzwStyle）

### ISSUE THREAD

**Issue by lxydft** [CesiumGS/cesium#9020]
im sorry for ask question at there,i can't open this url .( https://community.cesium.com)

i add 3dtiles in my page. but i only know how to change its color by height.
i want to get a result like this page.（http://cesium.marsgis.cn/cesium-example/editor.html#63_jzwStyle）
please help me or give some ideas.
thanks you first.

**Comment by OmarShehata** [comment]
@lxydft can you tell me why you can't open the community forum? Do you get an error? Can you take a screenshot of it?

I'd love to have this discussion on the forum so I want to help you get access.

**Comment by lxydft** [comment]
e.... maybe its my network.I've connected to that address.I also saw you. hhh
I searched for some questions on it.Can you see the effect in my link.
In your opinion, if I want to solve this problem, what should I focus on.Thank you!

**Comment by OmarShehata** [comment]
Glad to hear the forum is working for you now! Please post a new topic on the forum and let's move the conversation there.
