### ISSUE TITLE
Model orientation within the sun's reference frame.

### ISSUE THREAD

**Issue by devond5** [CesiumGS/cesium#9026]
Hello Cesium team,

My employer wants to visualize a spacecraft, and this spacecraft uses hardware that keeps the default rotation of the spacecraft to where the bottom of the spacecraft is always pointing the sun. We are able to use/ pass quarternions to affect the heading pitch and yaw, but they are in the earths reference frame. We need the -z axsis at the quarternion identity (0,0,0,1) to always be pointing at the sun. 
I feel as if this would be an appropriate enhancement to make, or if you know a work around. 
Big picture: If Cesium is going to be used in a broader sense (space) use case, then It might be a good idea say if we wanted position to be relative to the earth, but are in orbit around the moon or mars. If the orientation is always relitive to the planets surface instead of earths, we could then use the orbital orientation to even make a perspective on where we are looking relative to that planet's surface.

**Comment by OmarShehata** [comment]
I think this would be a special case of allowing entity's to define their own reference frames more generally (see https://github.com/CesiumGS/cesium/issues/6041 and some initial work done on supporting this here https://github.com/CesiumGS/cesium/pull/5817). So in that way you could define a "sun" entity and then have your orientation relative to that.

Feel free to continue discussion in the forum thread about other workarounds until this is supported: https://community.cesium.com/t/attitude-of-model-relitive-to-the-sun/10176.
