### ISSUE TITLE
Wrong assessment of terrain tile visibility

### ISSUE THREAD

**Issue by dennisadams** [CesiumGS/cesium#9033]
Bumped into this piece of code while dealing with #9032 :
https://github.com/CesiumGS/cesium/blob/44ac2ff1293fc89cccfb58fc70f372123215261b/Source/Scene/GlobeSurfaceTileProvider.js#L578-L585

This seems like a simple oversight, expecting `computeTileVisibility` to return a boolean. But `computeTileVisibility` actually returns a `Visibility` value where `Visibility == {NONE: -1, PARTIAL: 0, FULL: 1}`. This leads to cases where partially visible tiles pass as non-visible (since 0 evaluates as false), and where non-visible tiles pass as visible (since -1 evaluates as true). 

I assume it's supposed to check if the `Visibility` return value is not `Visibility.NONE`, just like here:
https://github.com/CesiumGS/cesium/blob/44ac2ff1293fc89cccfb58fc70f372123215261b/Source/Scene/QuadtreePrimitive.js#L1191-L1194

On a sidenote, although the [`Visibility.js`](https://github.com/CesiumGS/cesium/blob/44ac2ff1293fc89cccfb58fc70f372123215261b/Source/Core/Visibility.js) and [`Intersect.js`](https://github.com/CesiumGS/cesium/blob/44ac2ff1293fc89cccfb58fc70f372123215261b/Source/Core/Intersect.js) objects are quite equivalent, it may be clearer to always return a `Visibility` value from `computeTileVisibility` and not an `Intersect` value like here for instance:
https://github.com/CesiumGS/cesium/blob/44ac2ff1293fc89cccfb58fc70f372123215261b/Source/Scene/GlobeSurfaceTileProvider.js#L742

**Comment by mramato** [comment]
Thanks @dennisadams this looks like a pretty obvious bug.  I wonder how long it's been there (git blame is a little useless because of format-only changes that went in a while ago).

@lilleyse are we missing something here or is this just an oversite?

**Comment by lilleyse** [comment]
It looks like it's been there since https://github.com/CesiumGS/cesium/pull/7061. Sorry to keep passing this along, but @kring could you check this?

**Comment by kring** [comment]
Good catch @dennisadams! This is definitely a bug, and it will cause a one-frame delay in loading imagery sometimes, and load imagery that isn't needed at all other times. The cases where either occur should be relatively rare (which is why we didn't notice before), but they'll happen. Are you up for opening a pull request to fix this?

**Comment by dennisadams** [comment]
Sure
