### ISSUE TITLE
mouse middle drag can not work normally when model is transparent

### ISSUE THREAD

**Issue by happyfeet1996** [CesiumGS/cesium#9037]
I set my 3dtiles model transparent, like this:
![image](https://user-images.githubusercontent.com/40989006/87872436-1bda2480-c9eb-11ea-902b-f0521ddb7ad0.png)
I used mouse middle drag to rotate model, it do not rotate centered by the point that the mouse on the model.it rotate by the point that cross the model and on the groud.I can not rotate transparent model like normal model,but when i used mouse left click to highlight model ,it can select transparent model normally. like this:
![image](https://user-images.githubusercontent.com/40989006/87872537-0fa29700-c9ec-11ea-949b-581975f5455f.png)
I need to cross the transparent model to select the model do not have transparent attributes,how can i do it?

**Comment by lilleyse** [comment]
@happyfeet1996 try setting [`scene.pickTranslucentDepth`](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html?classFilter=scene#pickTranslucentDepth) to true.

Here's a sandcastle demo for reference: [Sandcastle](https://sandcastle.cesium.com/#c=dVRtb9MwEP4rp37qpM5JmnRNS5kYKxKTgE2sAiHlixtfG2uuXdmXloH479hO9gKMfkh153t57jk/ThK4ACd3e4UgcGfAbCBfwkoqdLBBTq1F2Mv6TuotHCU10JgDWuBagEOFNcEaG36QxlY6SeBtK5UIsYITh9q0ltDdh6qfvl3C9R71MhzsjSWu5tAQ7edJcjweM6bva7Y1h8RJwkQYSZRILUlykgd0SS5O131xtudbrPSBWzhIPHo4r0HjES7RyXbHvkTfsBrU0b40mrjUaKvBCH5WGoDQWu+5seYgBdr5Q2Jt/cD41VglVl3I8GRU6V8nryrt28WyzNWokW2VWSMTuKdmhY4utj7YUZ/l4ZBtMWZ5Tm6RgBqEbhoFNd+h5RE6kAFlzB1wgo9cN5yI626yPvrGeD6kCTV7lJc8cCq5ztnGmt0StxbRDcNgp9OCpVlZZnk6LtN0XJSj4C5SdjbLsiLP82lWlOMseqeTvNJhtGfdrq1Ez1bf8Bmn75EH5m8k1c1no9Q/rccZG0/L6aycluNZXuaT2OPUu/Min6WTSVpOx8VZ1zpl6TQ7m02ymQc7K4ts0iN5TnFHE3NIYaHDuDnhuZY64pv/zVCsbJ4GmL8wVIxBLVaWa7cxdve4+4+crPxesKvlu0+rq9W3p737DX4wXMQVhkv8cAsdUFAJUsdgb/xJW/eXL1fdYTdEa9Vj2yujP6PzMqkxUnrhfNiVGPrlFPnj5fuDl72VOxk1wbgQw75vh7U3mKN7L+j/QrkNxx2Y2ijjFVAN7HbNh+PJZARPn5RlJ9XgZQWERyHSqFpv0zJI4eHiD0aDRYRwHlqE3xv/xHjNh9mHjCWE/sXxWnPJuq3vPODaudAjhC6S56kLIQ8gxesX1Ay14s75k02r1K38gdXgfJH4+H9SlYm399q/XIrfh7AmO//QORlji8SbL2eSMWrN7V+VfwM)

Also in the future you can post questions like this to the [Cesium Community](https://community.cesium.com/)

**Comment by happyfeet1996** [comment]
> @happyfeet1996 try setting [`scene.pickTranslucentDepth`](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html?classFilter=scene#pickTranslucentDepth) to true.
> 
> Here's a sandcastle demo for reference: [Sandcastle](https://sandcastle.cesium.com/#c=dVRtb9MwEP4rp37qpM5JmnRNS5kYKxKTgE2sAiHlixtfG2uuXdmXloH479hO9gKMfkh153t57jk/ThK4ACd3e4UgcGfAbCBfwkoqdLBBTq1F2Mv6TuotHCU10JgDWuBagEOFNcEaG36QxlY6SeBtK5UIsYITh9q0ltDdh6qfvl3C9R71MhzsjSWu5tAQ7edJcjweM6bva7Y1h8RJwkQYSZRILUlykgd0SS5O131xtudbrPSBWzhIPHo4r0HjES7RyXbHvkTfsBrU0b40mrjUaKvBCH5WGoDQWu+5seYgBdr5Q2Jt/cD41VglVl3I8GRU6V8nryrt28WyzNWokW2VWSMTuKdmhY4utj7YUZ/l4ZBtMWZ5Tm6RgBqEbhoFNd+h5RE6kAFlzB1wgo9cN5yI626yPvrGeD6kCTV7lJc8cCq5ztnGmt0StxbRDcNgp9OCpVlZZnk6LtN0XJSj4C5SdjbLsiLP82lWlOMseqeTvNJhtGfdrq1Ez1bf8Bmn75EH5m8k1c1no9Q/rccZG0/L6aycluNZXuaT2OPUu/Min6WTSVpOx8VZ1zpl6TQ7m02ymQc7K4ts0iN5TnFHE3NIYaHDuDnhuZY64pv/zVCsbJ4GmL8wVIxBLVaWa7cxdve4+4+crPxesKvlu0+rq9W3p737DX4wXMQVhkv8cAsdUFAJUsdgb/xJW/eXL1fdYTdEa9Vj2yujP6PzMqkxUnrhfNiVGPrlFPnj5fuDl72VOxk1wbgQw75vh7U3mKN7L+j/QrkNxx2Y2ijjFVAN7HbNh+PJZARPn5RlJ9XgZQWERyHSqFpv0zJI4eHiD0aDRYRwHlqE3xv/xHjNh9mHjCWE/sXxWnPJuq3vPODaudAjhC6S56kLIQ8gxesX1Ay14s75k02r1K38gdXgfJH4+H9SlYm399q/XIrfh7AmO//QORlji8SbL2eSMWrN7V+VfwM)
> 
> Also in the future you can post questions like this to the [Cesium Community](https://community.cesium.com/)
Thank you for your patience, I understand
