### ISSUE TITLE
Viewer.ConstructorOptions has incomplete JSDoc/TypeScript definitions

### ISSUE THREAD

**Issue by benjaminabb** [CesiumGS/cesium#9046]
In [JSDoc](https://cesium.com/docs/cesiumjs-ref-doc/Viewer.html#.ConstructorOptions) property globe is only typed `Globe` but should be `Globe | false`

This is only defined in the description 
> The globe to use in the scene. If set to false, no globe will be added.

Therefore the TypeScript definition is wrong.

**Comment by konashredbiker** [comment]
Also in [EasingFunction ](https://cesium.com/docs/cesiumjs-ref-doc/EasingFunction.html?classFilter=EasingFunction#.QUADRACTIC_IN) `QUADRACTIC_IN` is probably a typo. Same for out and in_out.

**Comment by OmarShehata** [comment]
Thanks for reporting these @konashredbiker ! Feel free to open a PR to fix these if you'd like, see the contributing guide here: https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request

**Comment by OmarShehata** [comment]
I opened a separate issue for the EasingFunction https://github.com/CesiumGS/cesium/issues/9220 since the globe type is fixed in https://github.com/CesiumGS/cesium/pull/9063.
