### ISSUE TITLE
Remove deprecated MapboxApi, BingMapsApi classes

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#9051]
They were deprecated in 1.72 and can be removed in 1.73 See #9049, #9039 for details.

**Comment by Arc128** [comment]
can I still use the bing map imagery from my Cesium ion assets to view in sandcastle demos. in Cesium 1.73

**Comment by hpinkos** [comment]
@Arc128 yes, your bing imagery from ion will continue to work without you having to make any code changes.  This deprecation is just a little bit of code cleanup to remove a function we're no longer using.
