### ISSUE TITLE
Update docs in `Model.js` to point to correct url for `KHR_texture_basisu` extension

### ISSUE THREAD

**Issue by YoussefV** [CesiumGS/cesium#9054]
With [KTX2 integration nearing](https://github.com/CesiumGS/cesium/pull/9040), we'll be adding support for the `KHR_texture_basisu` extension in GLTF's. This is just a reminder that the [url pointed to](https://github.com/CesiumGS/cesium/pull/9040/files#diff-bcedb35459e5bed46206bad4990bc7f1R176) in the jsdoc in `Model.js` currently points to a PR as the adoption of `KHR_texture_basisu` is not yet fully complete.

This is just a reminder that once that Khronos PR is merged, we need to update the link to reflect the actual webpage for the extension

**Comment by lilleyse** [comment]
Will be addressed in https://github.com/CesiumGS/cesium/pull/9040. See https://github.com/CesiumGS/cesium/pull/9040#discussion_r501197339
