### ISSUE TITLE
Odd graphics issue with semi-transparent polygons on iOS

### ISSUE THREAD

**Issue by Maarondesigns** [CesiumGS/cesium#9059]
On iPhone 11  (haven't tested on other iPhones) the fill inside semi-transparent polygons has odd rings on top of them that can be seen in [this video](https://www.youtube.com/watch?v=bVfVp74Gv-M). It may be an issue related to the resolution/definition that the screen is trying to render. I have noticed other odd issues on iOS regarding polylines being 'chopped up' into little parallel segments when rotating the camera.

Browser:
Safari and/or iOS fullscreen app standalone

Operating System:
iOS 13.5.1

**Comment by OmarShehata** [comment]
@Maarondesigns can you share a Sandcastle to reproduce?

**Comment by Maarondesigns** [comment]
Well, after uploading the geometries to cesium ion and then banging my head against my desk because it was not reproducing this behaviour... I updated my site from cesium 1.62 to 1.71 and it is fixed.

**Comment by OmarShehata** [comment]
Thanks for confirming! This is why it's always helpful to include the CesiumJS here :slightly_smiling_face:
