### ISSUE TITLE
Batch attributes checked for 'value' while polyline geometry attribute has 'values'

### ISSUE THREAD

**Issue by blauwepiet** [CesiumGS/cesium#9062]
When making polyline geometry (not entities because they do not scale with a lot of polylines) I get the following rendering error:

`An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined`

I looked through it and it seems that in the function `createBatchTable` the attributes `value` property is checked while the polyline geometry `position`'s property is `values` with an s.

Sandcastle example: https://sandcastle.cesium.com/#c=bVLRattAEPyVQ08SOCfSEAqOYhrc0gYCNSSkD1YeNtLaObK6E3snGSXk37PyOalo/SC4nZ2Z3R3UA6ve4A5ZXSqLO7VEb7pG3++xtEyqfb10NoCxyGWSXZS2tIRBkQBeZOuHCI2lbjv/lB5Mbk3TEq4cDWPvJ7oGAw+6YoTwWaaTqccF6WtplWqdN8E46+cf7CVwkBfYM71h13zHLSP6K2YY0vXJ1/OZOpPv5PTL/vWQzcSmtG9ZFk+IZ2tfoUXdsmnEvpcLoK6nO60+OnGN7WGpa+sDWElnHnMYzRW0LQKP8Hwa5tUnHD2UClJ56mR0mKsNkMdZbDSSDBugv0c6cqz//Lq++3GgAJHbrUz1bOx2Kn7L9sddJLOk8GEgXES+Ut8kVsdBdUyp1nlASVnm+Pyxq54x6Mr7MZKRWuRTaVGbXpn68shvoCoC76Wz6YhuzQuWyaLIhf+flBzUsurvHplgGGlPp4ubCGqti1zK48rgHD0C/+P8Dg

Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
Operating System: Ubuntu 18.04

**Comment by OmarShehata** [comment]
Given a geometry, you need to create a `GeometryInstance`, and then pass an array of that to the `instances` of a primitive (you're passing the geometry directly). 

[Here's a Sandcastle creating a polyline primitive](https://sandcastle.cesium.com/#c=bVJRi9swDP4rIk8J9BxuxxjkcmWlG9vBYION7eFyD26itGaOHWQnRzb632fHSa/pGghY0ifp+yT1nKAX+IIED6DwBbZoRNewn6MvLqJytLdaWS4UUhEl94UqlEQL0jmMS3t6Di5vsrYzh3gq8k3LwXs/oW7Q0sBKQm5PZnzW7xIa/y0UQKuNsEIrk824LSfrXlzdsZp08wH3hGg2RHyIn27evV3Bnftvbt+Mr+dkVahjkiw5PypjuSpfudeaIJ6joOugLIGRQ+8mJKaM5YxmrnO9wNl/+ymSjZVWs5tbS2LXOQEZnLAApZaaXhV667L0Zs4cVY+Q+BzPfn1+/PExOXU6Tq+jVw5L1WFFsyQPOPrphCtgpkSFrCXRuMn3Ds2rarGoORLU7i+ImmzZbOTBzaDKA2mlOxevuTRhJrxtkZPHZXDlFkZlmxMmnpZ5H62i3NhB4nqW+140rSYLHcmYsdRi00p3aCbddeVvtKw0JgwCIE/PU/NK9CCqhyt3DqXkxrhI3Un5XfzBIlrnqcP/lyo1r4Taf+2RJB887HC7/hKcjLE8deb1TKu13HG6qPwP).

This article explains a bit more about creating primitives in CesiumJS: https://cesium.com/docs/tutorials/geometry-and-appearances/. 

@blauwepiet let's move this to the [Cesium community forum](http://community.cesium.com/) - if you're having trouble visualizing a lot of lines we can discuss how to get better performance depending on your use case (like different recommendations if the lines are dynamic or not etc).
