### ISSUE TITLE
3D tile wireframe display is tangled

### ISSUE THREAD

**Issue by chris-cooper** [CesiumGS/cesium#9066]
There's some [assumptions in the code](https://github.com/CesiumGS/cesium/blob/1.71/Source/Scene/Model.js#L4449-L4450
) that triangle winding will support display as a LINES primitive which seem unlikely with real world data.  e.g. in [the sandcastle](https://sandcastle.cesium.com/?src=3D%20Tiles%20Inspector.html&label=3D%20Tiles)

![image](https://user-images.githubusercontent.com/484870/88621630-4eb7a300-d0e4-11ea-999b-5380227210bb.png)

![image](https://user-images.githubusercontent.com/484870/88621603-3c3d6980-d0e4-11ea-861d-c8ccd988257d.png)

**Comment by OmarShehata** [comment]
I'm marking this as an enhancement because I think the current `debugWireframe` mode is intended for debug purposes, and a nicer looking wireframe for presentation would need a different technique.

**Comment by 3DGISKing** [comment]
Maybe we need additional renderer resource(index buffer) for correct rendering wireframe.
