### ISSUE TITLE
Why does camera.flyto() not return a promise or take a callback?

### ISSUE THREAD

**Issue by bluninja1234** [CesiumGS/cesium#9072]
Using `viewer.flyTo(entity)` returns a promise that gets resolved when the viewer's camera has zoomed to the entity. However, when using `camera.flyto(options)`, there is no promise returned. Why is this, or is it just an error in the documentation?

**Comment by OmarShehata** [comment]
@bluninja1234 `camera.flyTo` takes a `complete` function callback that is called when the flight is complete. It's a different API from the `viewer.flyTo`. See: https://cesium.com/docs/cesiumjs-ref-doc/Camera.html?classFilter=camera#flyTo. 

For general questions please use the Cesium community forum: https://community.cesium.com/.
