### ISSUE TITLE
I hope cesium can realize the presentation of 3D text.

### ISSUE THREAD

**Issue by yoyomule** [CesiumGS/cesium#9074]
Hello, I hope cesium can realize the presentation of 3D text.
like this:
![image](https://user-images.githubusercontent.com/10000818/88892846-0df09300-d278-11ea-8ba5-2cd4d1b20c7e.png)

**Comment by OmarShehata** [comment]
I'm not sure if it's a common enough use case that it should be built-in to CesiumJS? You can of course generate geometry like this and load it in CesiumJS as part of your app.

**Comment by yoyomule** [comment]
It is hoped that this text is dynamically rendered through the input text, rather than imported from the outside after the model is made, so that the universality will be lost. I think it still has a certain effect, such as making three-dimensional marks on buildings.
