### ISSUE TITLE
Mapbox not working

### ISSUE THREAD

**Issue by Maarondesigns** [CesiumGS/cesium#9078]
Mapbox currently getting 401 error. Happened on my local but is also not working on cesium site. 
![image](https://user-images.githubusercontent.com/40376601/89204556-4b109a00-d584-11ea-97e6-448f9ab0c8d1.png)

**Comment by OmarShehata** [comment]
@Maarondesigns it looks like you're using the free demo token included in CesiumJS. You need to create a Mapbox account and get a token to use in your app when using this imagery provider in your application.

Mapbox has decided to no longer provide a free demo token for the Cesium community. This is listed as a breaking change in the latest release here: https://github.com/CesiumGS/cesium/blob/master/CHANGES.md#breaking-changes-mega

**Comment by Maarondesigns** [comment]
Ah, bummer. Thanks!
