### ISSUE TITLE
Custom atmospheric lighting 

### ISSUE THREAD

**Issue by AliFlux** [CesiumGS/cesium#9080]
Hi.

It would be great if we could set the lighting color of the atmosphere (which is apparently plain white). To be clear, I am talking about the lighting which can be set using `lightingFadeInDistance` and `lightingFadeOutDistance`. The subtle rim halo around the globe could be made better with customization.

There is option to change the hue/brightness/saturation of the atmosphere, but that affects the whole globe and makes imagery weird when tweaked (photo below). We just need to change the lighting color.

![sky atmosphere](https://user-images.githubusercontent.com/8333794/89212697-5c39c500-d5dd-11ea-86e7-1607a6a39717.PNG)
Increasing saturation in sky atmosphere sandcastle example makes the imagery yellowish.

![Google Earth Sky Atmosphere](https://user-images.githubusercontent.com/8333794/89212876-b470c700-d5dd-11ea-864b-7d6d26a9f6a3.PNG)
The effect we're looking for is somewhat similar to Google Earth.

**Comment by ggetz** [comment]
@AliFlux I think this is possible with [the newer atmosphere shader parameters](https://sandcastle.cesium.com/?src=Atmosphere.html).

<img width="628" alt="image" src="https://user-images.githubusercontent.com/4439461/202753871-109b99fb-a3d5-4c35-9550-57afa6b58931.png">

OK to close as complete?
