### ISSUE TITLE
Edit metadata OSM buildings/3D tiles

### ISSUE THREAD

**Issue by parthgundi** [CesiumGS/cesium#9087]
Hi,

Is it possible to edit metadata about buildings in the OSM buildings dataset e.g. if I want to add a field for 'for-sale' & consequently style the buildings accordingly on the map.

**Comment by OmarShehata** [comment]
This isn't currently possible without regenerating the 3D Tileset, but it is a feature we've considered. Let's move this discussion to the [Cesium community forum](https://community.cesium.com/). Can you create a new post there with a bit more background about your use case? There's a few different approaches you can take depending on what you're trying to do.

**Comment by OmarShehata** [comment]
I was wrong, it's possible to edit feature properties in a 3D Tileset in a number of ways. This forum thread explains how to add new properties and style then on the fly, as well as how to make those changes persist: https://community.cesium.com/t/edit-metadata-osm-buildings-3d-tiles/10540/2?u=omar
