### ISSUE TITLE
Line Geometries around the antimeridian crashing

### ISSUE THREAD

**Issue by jay-hennen** [CesiumGS/cesium#9089]
Sandcastle example: [here](https://sandcastle.cesium.com/#c=nRdtb9o4+K94/dIE0qSQtreDdrq+bZoOrZV6232A6uQGAy7GjmwHxqb+93vsvEDAMLRUFcnj5/3dcyyRSDUVXKErNMp4Yt49H/0ccASPJDqTvPwyTxQpojXlY6QnVCEtkJYZyT9meEoUohothJyuSFRCOInvHjhbdtAIM0Xys7fugJv/AZ+DGnNKFkSCFpws0C1RNJuF3yzMO07s563gGlNO5HFQKu35vmUQRU9EoyxFlKeZRkOssQHGaCIk/WHoGGJAqgxULwieIqWx1D2sjQlqQkc6R0A4kUKBYROCWu9Pc90q3CvU+uPP8Lybg4F5TpMr/ZEJrOP2tZR46RmAfbvJRiOwIW7EjXbjzOo7EhJ5hgEFytMu/FyCLPhtXl0Urq9QXnOUV0CJ4afZrGJTSu/TptduvPrPgFkp2gSKBjq1qoKnwdGF2DWRsZFY8qu4XTRos2V41SDxFuTcQM7bIIlWkkBIAlERjIRMjL0Sv4xRjIYUjwVfBcNYaGC/5caKMISUrAnba2lFVpp6Anhhq4u2D+PisN3dPjsvzuJtuytEP7e7KizIKojNGMpBYg0Gj4mYES2XaCTFrJa7xjGpFJD4qlf4pqpOgxHAKZ1RTeekKgt/vU7NY1N3sgBaU6Pd+iEdIe/dAUzMs41Wr9PH1TljpOghG/LetnVLBBPyWmvDreB0a0CfCrd85pDPPCEGhb5kmoTGTxbF21ZynUN407u+/buOs6mQ0YBnsx7hYz0xDjZ+7Z8+h8xCHNhsE9WBQ4ffy0T+SnmVx15BG0oyzBLiVcHUAnpTgLj/s+i1FgBVxdEJanXffB+qq23eXfqrBBIpmXyph+MWmgC8YR57pwH8uShTob6vF9zFWa6otaxVOgFkxyhCbReHsmYLig2MqoFN8zKcQhnmxVq4F02bV21ntm1ZYcN+R8aSEOXlFTh9DlDxBiUcoNOgJLtnjKZK0GH476en92dB5aNNG9yiUpxMvZIksG4KkDdtxFHbPySlM/kfpIC1eft0TqTeceyaCavsXO9f9cdGAkiK/OrTZ4eZrmnC6tNk8zHt4RW9uwJ85O/AsXiQ7/3CajMRKhNhAnUPI8vHzYGEKweXb03U3oH/hggsG+g3tP+1As3mLqHbYAeo4HJy4uCyliVrTmG/Tj4YJ/VGUDZSz+ECXDZVhTq7XATZT+3c6ri4Vm3Z2+PhRMxSwQnXd9Am9DIlwKvq1BtH4d3D15vefXAAN/VIZCUfWMZ7iOaYZdZKU8w7guY7ouZgSWHpSCwvkznBnkn5T83Ux3Vw2Pv85f7JQfwiMuDPx0/phMg16psa3HbDb5AYRhPP2LSh/JurW0NumHHqzo9y0LoCWe4oHfMW7MujnWlk53xnNe4P8zVmTCweaTIFy2v3hr12gnXG2WDn9tIS4uHQc60t++wufaM6pQ9duqYpwdKg1SoFkrQkt2vJdYW2q2RGDOuOXdd2JLQGcsVgheAFnsOZvktDteTJRAouMpO+1p2uBB920PFIiGPHmZqIRccslJth2IxDsckUoVg7NLe9KDIXQRMdrhHUMhIje9nSExjvxVLhwXYkZjOw0V4widK+ISzuXGkZ39V67PX7cQBrQHkJgNf8Phnay2dY5UJ1F8nlQ46tC15dSHbJgD/gXS34++QcBUeXSi8Z+ZA74C8KvUvCLVUyLwwjTWYpM7eA6CVLpkSHibLKXUYl0eWQziEgV4Ojjfvv4AglDCsFJ6OMsSf6gwyOPlxGgF8jg73OtI0HmCIMLw3KpPWhlwPDMLyM4HObSgvBXrBc4/g/)

Browser: Version 84.0.4147.89 (Official Build) (32-bit)

Operating System: Windows 10 Enterprise 64-bit

Possibly related to #6187?

The sandcastle hopefully illustrates the issue and how the geometries are getting setup. This situation occurs when rendering subsets of certain global regular grids in our app. The processLines is pretty much the exact same as what's in our code. I'm aware of the scene3DOnly viewer option but unfortunately our app exclusively uses Cesium in 2D mode.

**Comment by hpinkos** [comment]
@jay-hennen errors like that usually occur because you have a cartesian position at (0, 0, 0) that can't be projected to 2D.  Since you're using a custom geometry, I'm not exactly sure where the problem is coming from, but I think it's in your geometry type and not a Cesium bug.  If you need more help debugging, please post to the [cesium community forum](https://community.cesium.com/).
