### ISSUE TITLE
CallbackProperty function should get the entity or object as a parameter

### ISSUE THREAD

**Issue by onderaltintas** [CesiumGS/cesium#9092]
Hallo from Maxico!
Como estais amigos?

Right now CallbackProperty gets function but inside the function, you can never know which entity's callback property function it is. It was already stated in cesium bug reports that it is about javascript scoping but it is not actually. I didn't understand why in forums and google groups, people insisted on this is a problem of Javascript. Lemme explain the situation and the solution please:

When you define callback property for each entity seperately; you need to create function for each entity that is against Javascript best practices. Normally if you want to use a function that can be used for all entities and have no difference, you create that function as one static with prototyping. Right now, for 50000 entities, you need to create 50000 functions just because functions don't have a clue which entity they are working with. If the manager of callback property function (the function that executes callback property function) could pass the right entity as a parameter to function, you can give one function to all of these entities, so, only one function you can create for all entities' new positions. To make it clear, I will provide an example about what should be done:

function move(time,result,entity){
      var oldPosition = getOldPosition(entity);
      var newPosition = moveByOneDegree(oldPosition);
      setPosition(entity, newPosition);
}

viewer.entities.add({
    somethingsomething...
    position: new Cesium.CallbackProperty(move);
}

Try to make it at current state.

If you don't have entity as parameter (or any object reference) you are totally lost so you need to either bind the original object (that creates totally new function) to use as "this" or you need to execute a function that creates a function for each object scope. This is not a good way of design in Javascript and creates thousands of scoping problems. 

Regards,
Arriba arriba, andale andale,

**Comment by hpinkos** [comment]
Hello @onderaltintas!  I agree this would be a useful change to make.  We actually already have an issue open for this (https://github.com/CesiumGS/cesium/issues/3726) so I'm going to close this issue as a duplicate and make a comment in #3726 that you requested this feature
