### ISSUE TITLE
Resource silently fails to load if used multiple times.

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#9093]
Take the below code:

```js
var viewer = new Cesium.Viewer("cesiumContainer");

var resource = new Cesium.Resource("../../SampleData/simple.czml");

resource.head().then(function () {
  return viewer.dataSources.add(Cesium.CzmlDataSource.load(resource));
});
```

[Same code in Sandcastle](https://sandcastle.cesium.com/index.html#c=bZBNS8QwEIb/SugpBZni2W4RukdBsOApl2wya4NpIvnosiv+dye1FT+2hJJM5nnmJbMMbDZ4wsB2zOGJ9RhNnuB5qXFRqeXce5ekcRhEVd8JJ9xMXMDoc1D4m3xaq8QCNLQGOb1Z3Mskm2jKFtRlsptok8CIUvMa0oiOH7NTyXjHeM3ehWM0KuXg1qSgyTUsVASpNV8n96Tdf1+B9STc9HWZ9lF+1U3VxnS22BVx+e4plQ+J5WA55U1IIWXC2ByyesUEKsYClta2+Ym22szM6N2VV2LKyhjp5pitHcwFRdW1DfX/Q0tM414eZwxWnkvbeNs9fBUBoG3oeJ1M3tuDDH/Mnw)

If you comment out the `resource.head()` line, it works as expected but obviously you are now losing the head call. Basically, it looks like resources used to be re-usable, but since #8843, they can only ever be used once specifically this line in the PR here: https://github.com/CesiumGS/cesium/pull/8883/files#r470300910

Perhaps something is not being re-initialized on the second call?  It can't be a race condition because we wait for the head call to finish before calling load.  If I make two identical resources, it works.

CC @lilleyse @OmarShehata

**Comment by mramato** [comment]
`resource.clone.head()` also works as a workaround.  So definitely some undesired state being saved across calls.

**Comment by lilleyse** [comment]
> Perhaps something is not being re-initialized on the second call?

Without looking too closely, this sounds pretty likely.

The original problem was that 3D Tiles was holding onto request objects and it can be fixed in another way

* Roll back https://github.com/CesiumGS/cesium/pull/8883
* Add the fix here: https://github.com/CesiumGS/cesium/issues/4549#issuecomment-634503841
* Keep the fixes in https://github.com/CesiumGS/cesium/pull/8889
