### ISSUE TITLE
How  can I  change  radius  in  CircleGeometry

### ISSUE THREAD

**Issue by yankai12** [CesiumGS/cesium#9094]
I have draw  a lot of  circle  ,but I  can  not set a new radius  to change it 
   let id= primitive.geometryInstances[j].id;
                let attributes=primitive.getGeometryInstanceAttributes(id);
                attributes.boundingSphere.radius=this.radius;

     primitive.geometryInstances[j].geometry._ellipseGeometry._semiMajorAxis=Number(this.radius);
                primitive.geometryInstances[j].geometry._ellipseGeometry._semiMinorAxis=Number(this.radius);

**Comment by OmarShehata** [comment]
Please ask your question on the Cesium community forum: https://community.cesium.com.
