### ISSUE TITLE
In file 'CesiumViewer.js', we can see ' import {...} from "../../Source/Cesium.js"; ' on the top, but Cesium.js doesn't exist in the repository

### ISSUE THREAD

**Issue by heimiguoguo** [CesiumGS/cesium#9101]
Sandcastle example:

Browser:

Operating System:

**Comment by OmarShehata** [comment]
You need to build the library. See the [build guide](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md#build-guide).

For any follow up questions, please post on the Cesium community forum: https://community.cesium.com/.
