### ISSUE TITLE
ktx runtimeError

### ISSUE THREAD

**Issue by SeanSure** [CesiumGS/cesium#9104]
i use ImageViewer to converthdr to ktx,but tips RuntimeError: Texture arrays are unsupported,how to convert it correct

![image](https://user-images.githubusercontent.com/30064315/90618104-166a3700-e242-11ea-8f90-52fbd49b6d2f.png)

**Comment by SeanSure** [comment]
[cloud_layers_4k.zip](https://github.com/CesiumGS/cesium/files/5095452/cloud_layers_4k.zip)

**Comment by OmarShehata** [comment]
Try using Google Filament to generate your KTX like this Sandcastle describes: https://sandcastle.cesium.com/?src=Image-Based%20Lighting.html. Note that recent versions of Filament are using an unsupported pixel type: https://github.com/CesiumGS/cesium/issues/9088. 

If you have more questions, please post on the Cesium community forum: https://community.cesium.com/.

**Comment by SeanSure** [comment]
> Try using Google Filament to generate your KTX like this Sandcastle describes: https://sandcastle.cesium.com/?src=Image-Based%20Lighting.html. Note that recent versions of Filament are using an unsupported pixel type: #9088.
> 
> If you have more questions, please post on the Cesium community forum: https://community.cesium.com/.

thanks a lot

**Comment by SeanSure** [comment]
> Try using Google Filament to generate your KTX like this Sandcastle describes: https://sandcastle.cesium.com/?src=Image-Based%20Lighting.html. Note that recent versions of Filament are using an unsupported pixel type: #9088.
> 
> If you have more questions, please post on the Cesium community forum: https://community.cesium.com/.

which release can be use to convert ktx?
