### ISSUE TITLE
Ellipse on ground has hole in it when camera is perfectly perpendicular to ground

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#9114]
[Sandcastle](https://sandcastle.cesium.com/index.html#c=bVNNc9owEP0rO1wiT11hyAcDAaZtMu2lmWQmTHqIc1DsBauRJWYlQ2mH/17ZxuBAfJJWb9++fbteCYKVxDUSTEDjGm7QyiLnT1WMxZ2kut8Y7YTUSHEnhH+xBnBI5CMPZFYyRRo1iQmhcPjLkEpnNYQFsd4G17GO9cpXQ+2k2/hqdVle3SVaLtKUVdRLY33E6D3njSDnT0Kf8zmZ/BYXhGjZ5150wYfDq8tB/zKE8yEfXPSvev4YBWHJg0rJpcVRLRjAYi7vpDb09Y+0I+gPorD1IH63Hsr4di/7Ueg0EdYpLEXOjFGvgr4VzhnNzr6rDTgDa+myxhSwIl8qqRdnIcwLnZTNsKBScXDgYdeld6IO8KZvvkD3JFSBbGdRokzyxpOCyCNnMsdSFpzytOwyCxLLTCaVYXv/2PuUmmaXVWnG3czujHW36EeuMG1UHE08hOf3bC9B7SZ3GWq275vQFsoFzRDKrzShafZe/yBT6NTLr5HP0cv1AXoM4xnKRebg0wR6UdQCNlaJHEnwudrMDGuVBEjROqnFyWLtnXLm4NNx2eDAtA2aqtsmyo1vmdbSIkuMtsbviffKUIncrVAn7Iyt2yicNkxfZL405KAgxTjvOvT2+z/Hdl+L5A0dT6xtKo277dRxKlcg08kH/yYkSljrX+aFUo/yL8ad6bjr8SepyojUL+j9CkmJTQnLetOfdZBzPu7668eZrl7/FnON+A8). This flies to an entity by sampling the ground position there and flying to that lat/lon/height.

It produces a hole in the middle of this ellipse which goes away if the camera is tilted: 

![mask](https://user-images.githubusercontent.com/1711126/91327393-70fc1980-e793-11ea-83d0-eab3fbd01f0e.gif)

**Comment by OmarShehata** [comment]
This appears to happen with polygons too. Instead of an inner circle it'll be a smaller polygon of the same shape.

**Comment by hpinkos** [comment]
I imagine this would happen with all `GroundPrimitive`s

**Comment by lilleyse** [comment]
Once https://github.com/CesiumGS/cesium/pull/9108 is merged it will be possible to work around this bug by setting `viewer.scene.logarithmicDepthBuffer = false;`

**Comment by OmarShehata** [comment]
This seems to only happen in CesiumJS 1.71. Could not reproduce in 1.70 and 1.69.

**Comment by lilleyse** [comment]
`git bisect` points to https://github.com/CesiumGS/cesium/commit/c72dfbba550fba1e98fdb4b8df97714e284f4970 from https://github.com/CesiumGS/cesium/pull/8850. First guess is that some geometry is getting cut off by the near or far plane. CC @IanLilleyT

**Comment by mioxs** [comment]
```js
viewer.entities.add({
    position: Cartesian3.fromDegrees(-75.1641667, 39.9522222, 0),
    label: {
      text: 'hello',
      heightReference: HeightReference.CLAMP_TO_GROUND,
    },
    ellipse: {
      semiMinorAxis: 250000.0,
      semiMajorAxis: 400000.0,
      material: Color.RED.withAlpha(0.5),
      height: undefined,
      outline: true,
      outlineWidth: 12,
      outlineColor: Color.ORANGE.withAlpha(1),
      classificationType: ClassificationType.TERRAIN,
      heightReference: HeightReference.CLAMP_TO_GROUND,
    },
  });
```

open this issues,set ellipse.height undefined is scuccessful,but outlines are unsupported on terrain.
