### ISSUE TITLE
How to display a certain "Primitive" under a certain "ImageryLayer"?

### ISSUE THREAD

**Issue by WebHero0544** [CesiumGS/cesium#9116]
hi, How to display a certain "Primitive" under a certain "ImageryLayer"? I looked at the API. "Primitive" and "ImageryLayer" were able to adjust the order of display separately, but now "Primitive" is always above "ImageryLayer", as shown in the following code:

`
                const geoHeatImagePrimitive = this.viewer.scene.primitives.add(new Cesium.Primitive({
                    geometryInstances: new Cesium.GeometryInstance({
                        geometry: new Cesium.RectangleGeometry({
                            rectangle: Cesium.Rectangle.fromDegrees(res.startLon, res.startLat, res.endLon, res.endLat),
                            vertexFormat: Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT,
                            height: 0
                        })
                    }),
                    appearance: new Cesium.EllipsoidSurfaceAppearance({
                        material: new Cesium.Material({
                            fabric: {
                                type: 'Image',
                                uniforms: {
                                    image: res.url
                                }
                            }
                        })
                    })
                }), 0)

            const tileLayer = this.viewer.imageryLayers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({
                url: '/MapCache/googleMap/gis/mixed/Map_x={x}y={y}zoom={z}.png',
                tilingScheme: new Cesium.WebMercatorTilingScheme(),
                minimumLevel: 1,
                maximumLevel: 20,
            }), 1)
`
In the above code, "geoHeatImagePrimitive" is always above "tileLayer". How to solve this problem? Who can help me

**Comment by OmarShehata** [comment]
I would use a SingleTileImageryProvider if you want to play an image underneath another imagery layer, see: https://sandcastle.cesium.com/index.html?src=Imagery%20Layers.html. 

Please use the Cesium community forum for asking questions: https://community.cesium.com/.

**Comment by WebHero0544** [comment]
Ok, thank you very much
