### ISSUE TITLE
Request view outside tile.

### ISSUE THREAD

**Issue by HAPPYFUNSIGHT** [CesiumGS/cesium#9130]
We want to load tiles that are larger than the current view so that we don't get jagged when we pan and zoom slightly.

**Comment by OmarShehata** [comment]
Here's a discussion on the Cesium community forum about how to load tiles outside the camera to improve the experiencing when zooming and panning: https://community.cesium.com/t/increase-terrain-cache/8945/2?u=omar

**Comment by HAPPYFUNSIGHT** [comment]
Good!
