### ISSUE TITLE
support ploygon scale or The model is shown in the popover

### ISSUE THREAD

**Issue by 4NK4** [CesiumGS/cesium#9138]
Support for polygon scaling or support for model pop-up rendering, which facilitates separate manipulation and layered display of building models

**Comment by OmarShehata** [comment]
You can scale a polygon by scaling the coordinates and recreating the entity. You can do this dynamically with a CallbackProperty. I'm not sure what you mean by showing the model in the popover.

For any follow up questions please post on the Cesium community forum: https://community.cesium.com/.
