### ISSUE TITLE
add Image into cesium but the image has position offset

### ISSUE THREAD

**Issue by QJvic** [CesiumGS/cesium#9142]
I add the same image both in leaflet and Cesium. In leaflet, the image works fine; but in Cesium, the image looks like have some position offset in lat.

Sandcastle example: https://codepen.io/qjvic/pen/WNwMGYr

Browser: chrome85.0.4183.83

Operating System: win10

**Comment by OmarShehata** [comment]
I think the difference is coming from Leaflet using a different map projection than CesiumJS:

![image](https://user-images.githubusercontent.com/1711126/92508018-e923ff80-f1d5-11ea-804d-8835887e611c.png)

See: https://github.com/CesiumGS/cesium/issues/3877#issuecomment-456117791

> Cesium supports map image data in Web Mercator or Plate Carree/Equirectangular projections. This issue captures community interest in having native support for other projections.

You can reproject your imagery so it appears correctly by uploading a GeoTIFF or other common raster formats to Cesium ion (https://cesium.com/ion). For any follow up questions please post on the Cesium community forum: https://community.cesium.com/

**Comment by QJvic** [comment]
> I think the difference is coming from Leaflet using a different map projection than CesiumJS:
> 
> ![image](https://user-images.githubusercontent.com/1711126/92508018-e923ff80-f1d5-11ea-804d-8835887e611c.png)
> 
> See: [#3877 (comment)](https://github.com/CesiumGS/cesium/issues/3877#issuecomment-456117791)
> 
> > Cesium supports map image data in Web Mercator or Plate Carree/Equirectangular projections. This issue captures community interest in having native support for other projections.
> 
> You can reproject your imagery so it appears correctly by uploading a GeoTIFF or other common raster formats to Cesium ion (https://cesium.com/ion). For any follow up questions please post on the Cesium community forum: https://community.cesium.com/

As you point, 'Cesium supports map image data in Web Mercator or Plate Carree/Equirectangular projections. ' My image is in Web Mercator and has position offset. When I use a image in WGS84, It works fine and has no offset. Is this normal？
