### ISSUE TITLE
How to prevent stuck on low configuration computer

### ISSUE THREAD

**Issue by huochaimindy** [CesiumGS/cesium#9146]
My computer's graphics card configuration is very low (it can be considered that there is no graphics card). I use 2D data and observe special stuck in 2D mode. Are there any settings that can make cesium load more smoothly?
I have another question  that whether the rendering mechanism of 2D mode and 3D mode is the same. In other words, is 2D mode more fluent than 3D mode in the same situation?

**Comment by OmarShehata** [comment]
Please ask your question in the Cesium community forum (https://community.cesium.com/) and include a bit more information on your application/OS/browser etc and what kind of data you're loading so that others in the community can provide some ideas on optimizing your app.
