### ISSUE TITLE
Error while creating a polyline in Cesium

### ISSUE THREAD

**Issue by smv1796** [CesiumGS/cesium#9155]
I am using the following code to create a polyline in my ReactJs app. I am getting "DeveloperError: Expected value to be greater than or equal to0.0125, the actual value was 0" error message. Can someone please explain to me why am I getting this error.

var viewer = new Cesium.Viewer("cesiumContainer");

var redLine = viewer.entities.add({
  name: "Red line on terrain",
  polyline: {
    positions: Cesium.Cartesian3.fromDegreesArray([180,90, 180, -90]),
    width: 5,
    material: Cesium.Color.RED,
    clampToGround: true,
  },
});

**Comment by OmarShehata** [comment]
Your polyline has no length because (180, 90) and (180 , -90) are the same point on the Earth. 

Please use the Cesium community forum for asking general questions: https://community.cesium.com/.

**Comment by smv1796** [comment]
Then why doesn't it give the same error for (-180,90) and (180,90)?

**Comment by smv1796** [comment]
How come (180, 90) and (180, -90) are the same points. It is clear one is at the north pole and the other one is at the south pole.

**Comment by smv1796** [comment]
> Your polyline has no length because (180, 90) and (180 , -90) are the same point on the Earth.
> 
> Please use the Cesium community forum for asking general questions: https://community.cesium.com/.
How come (180, 90) and (180, -90) are the same points. It is clear one is at the north pole and the other one is at the south pole.

**Comment by GatorScott** [comment]
This is a limitation of using Vincenty's solution for calculating the distance between two points.  The solution fails when the ends of a line segment are nearly 180 degrees apart.  You'll need to avoid using such long lines.

**Comment by smv1796** [comment]
> This is a limitation of using Vincenty's solution for calculating the distance between two points. The solution fails when the ends of a line segment are nearly 180 degrees apart. You'll need to avoid using such long lines.

Has Cesium specified this thing anywhere in its documentation?
