### ISSUE TITLE
  How to make the creatematerialpropertydescriptor class support htmlIframeElement

### ISSUE THREAD

**Issue by jxdnsong** [CesiumGS/cesium#9156]
I have seen the example of playing video. I want to integrate iframe, but adding htmlIframeElement  judgment in the creatematerialproperty method is useless

![图片](https://user-images.githubusercontent.com/16662799/93405909-e8b7f280-f8c0-11ea-889b-d23302e274d2.png)

**Comment by OmarShehata** [comment]
Is the goal to use an iframe as a material on geometry in the 3D scene? I'm not sure this is a common enough use case to consider   in CesiumJS right now. I'm closing for now but curious to hear more about your use case. 

Feel free to re-open the discussion in the Cesium community forum (https://community.cesium.com/) with more details about what you're trying to do and get ideas on how you might achieve it.
