### ISSUE TITLE
the customize CESIUM_BASE_URL will be changed in electron

### ISSUE THREAD

**Issue by cavencj** [CesiumGS/cesium#9157]
When I customize `CESIUM_BASE_URL` to `JSON.stringify ('./libs/dc-sdk/resources/ ')` in the electron environment. I found that `CESIUM_BASE_URL` changed to `libs/dc-sdk/resources/` when requesting `draco_wasm_wraper.js`, which eventually made it unable to load this file, but the other workers were still  use './libs/dc-sdk/resources/ '
`normal:`
![image](https://user-images.githubusercontent.com/33321375/93452011-7b30b400-f90a-11ea-8999-79133d867816.png)
`unnormal:`
![image](https://user-images.githubusercontent.com/33321375/93452165-ad421600-f90a-11ea-9f76-24e62faada3d.png)

**Comment by OmarShehata** [comment]
@cavencj does it work if you set:

```
CESIUM_BASE_URL = '/libs/dc-sdk/resources/'
```

Or 

```
CESIUM_BASE_URL = 'app://libs/dc-sdk/resources/'
```

?

I'm not sure why the draco worker would be special (it may be the only WASM worker?) This is where it gets loaded:

https://github.com/CesiumGS/cesium/blob/master/Source/Scene/DracoLoader.js#L30

It wraps the URL in `buildModuleUrl()`: 

https://github.com/CesiumGS/cesium/blob/master/Source/Core/TaskProcessor.js#L176

**Comment by cavencj** [comment]
I tried the way you said it. still not works, in the `TaskProcessor ` I found that the other workers to add a `baseUrl` parameter, but have not found in the `getWebAssemblyLoaderConfig` function, as a result of this reason?
code: 
```js
var bootstrapMessage = {
    loaderConfig: {
      paths: {
        Workers: buildModuleUrl("Workers"),
      },
      baseUrl: buildModuleUrl.getCesiumBaseUrl().url,
    },
    workerModule: TaskProcessor._workerModulePrefix + processor._workerName,
  };
```

```js
  config.modulePath = buildModuleUrl(wasmOptions.modulePath);
  config.wasmBinaryFile = buildModuleUrl(wasmOptions.wasmBinaryFile);
```

**Comment by TJKoury** [comment]
Try it with [C137.js](https://www.npmjs.com/package/c137.js), it’s a single-file solution that does not need to request external resources.

**Comment by OmarShehata** [comment]
@cavencj have you had a chance to try adding the `baseUrl` the same way other works do here and see if that fixes it?

**Comment by dzungpng** [comment]
Closing this issue as we have not heard from the original poster in a while. Please feel free to re-open it to continue the discussion if necessary.
