### ISSUE TITLE
Documentation is unreadable/messy on small screen

### ISSUE THREAD

**Issue by zarov** [CesiumGS/cesium#9162]
I splitted my screen in half, one with my editor, the other with the documentation, and I encountered a problem, as you can see below, when I scrolled horizontally:

![Screenshot from 2020-09-21 09-21-48](https://user-images.githubusercontent.com/741255/93742006-aad30b00-fbed-11ea-864b-fbae9fe44b9c.png)

I am not sure how this can be fixed, but maybe if you set a width to `#main` using something like `calc(100% - 300px)`, you could work it out.

**Comment by OmarShehata** [comment]
It looks like this is only a problem for classes that have long widths like Cesium3DTileset: https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html?classFilter=Cesium. 

Perhaps the easiest thing is if we could have the horizontal scrollbar apply just to the main body. Or make the search panel on the left have a solid white background and be on top.
