### ISSUE TITLE
gltf texture issus

### ISSUE THREAD

**Issue by helen00** [CesiumGS/cesium#9164]
hi, i output a gltf file, and gltf-viewer tool looks right，but in cesium the texture seems wrong, who has idea to solve this problem? or is cesium has someway to change or compute uv？
![gltfviewer](https://user-images.githubusercontent.com/28391325/93765271-2ca35280-fc47-11ea-96bc-6fb34053a659.png)
![cesiumviewer](https://user-images.githubusercontent.com/28391325/93765277-31680680-fc47-11ea-932f-6bf7ac0bcf2a.png)

[3F8B3C4A-C82B-4c94-818D-8F792FA2A287_50.zip](https://github.com/CesiumGS/cesium/files/5255257/3F8B3C4A-C82B-4c94-818D-8F792FA2A287_50.zip)

**Comment by jtorresfabra** [comment]
Hi @helen00,

I did a quick try and it seems your model does not pass the gltf2 validator, image attached:

![image](https://user-images.githubusercontent.com/1784900/93768380-973d9980-fc19-11ea-8a04-3c9fee4ecb33.png)

Also when loading it in Cesium it only works partially in Firefox, and does not work at all in Chrome, showing in the console something like:

```
[.WebGL-0xe56bcf90700]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 2
bucket.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```
Can you provide a valid gltf2 file (valid meaning correct when using the validator) to discard it is not a problem in the model itself. 

Thanks!

**Comment by helen00** [comment]
thanks for your reply, I did find some mistakes by  https://github.khronos.org/glTF-Validator/, I don't know if it has an impact

![QQ截图20200921210456](https://user-images.githubusercontent.com/28391325/93769946-2369b400-fc4e-11ea-8329-4bd630d03138.png)


i use cesium1.72  ,console has  no error, except  texture display problem

**Comment by jtorresfabra** [comment]
Can you provide a file without the errors please? That way we can discard the errors in the file are causing the problem. 

Thanks.

**Comment by helen00** [comment]
sorry  not  now   
In fact, I want to use cesium to test whether my output gltf is correct, i am writing a output tool, 
it seems that， now i should  pass the gltf2 validator first

**Comment by OmarShehata** [comment]
Closing since the original model has errors. If there is a valid model that renders correctly in other viewers and doesn't in CesiumJS we can re-open. 

@helen00 otherwise I encourage you to post your work on the community forum if you're unsure or have questions along the way: https://community.cesium.com/.
