### ISSUE TITLE
Convert from Cartographic radian to Cartographic radian?

### ISSUE THREAD

**Issue by swiss-knight** [CesiumGS/cesium#9171]
I don't get it:

![image](https://user-images.githubusercontent.com/19967599/94344379-220a0400-001f-11eb-8087-06594b47fcb9.png)

https://github.com/CesiumGS/cesium/blob/da4ddc58830606d89f762dc7d79b3dfe4103c6d1/Source/Core/Cartographic.js#L52

Is this transform useful for something?

**Comment by onsummer** [comment]
It is like a static method in some static language?

**Comment by dzungpng** [comment]
For the future for questions like this, please post it on the [community forum](https://community.cesium.com/).
