### ISSUE TITLE
Scale smoothing effect

### ISSUE THREAD

**Issue by HAPPYFUNSIGHT** [CesiumGS/cesium#9180]
Hello, can I improve the zoom experience? Make the scaling smooth. Can refer to Google Earth's gradient zoom effect!

I tried“ `viewer.scene.screenSpaceCameraController . inertiazoom = 1;` ", but it doesn't work

**Comment by dzungpng** [comment]
For questions like this, please post it on our [community forum](https://community.cesium.com/). We have team members and others who regularly check the forum so you will receive a quicker response! Please include screenshots/videos/gifs if possible to demonstrate what you are looking for.
