### ISSUE TITLE
3D Tiles Tileset Infinite Loading Loop

### ISSUE THREAD

**Issue by nikeshsraj10** [CesiumGS/cesium#9181]
Browser: Chrome 85.0.4183
OS: Windows 10

We discovered that if a tile in a 3D Tiles tileset contains a `content` attribute with no `uri` , that Cesium will repeatedly re-fetch the tile itself. This occurs regardless of whether the tile has children or not.

**Comment by OmarShehata** [comment]
@nikeshsraj10 are you able to share a sample 3D Tileset that reproduces this issue?

**Comment by dzungpng** [comment]
Closing this issue as we have not heard from the original poster in a while. Please feel free to re-open it to continue the discussion if necessary.
