### ISSUE TITLE
Dimensionless SVG does not render in Firefox

### ISSUE THREAD

**Issue by nmschulte** [CesiumGS/cesium#9188]
This issue seems specific to Firefox.  In Chromium this works fine.  My tests are on Linux but I have confirmation this issue exists on Windows and MacOS as well.

Paste this example into the Sandcastle at https://sandcastle.cesium.com/; note that the SVG referenced has no top-level `width` nor `height` attributes.
```javascript
var viewer = new Cesium.Viewer("cesiumContainer");
var collection = new Cesium.BillboardCollection();
viewer.scene.primitives.add(collection);
collection.add({
  position: Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
  image: "https://raw.githubusercontent.com/lupomontero/psl/master/browserstack-logo.svg",
  width: 200,
  height: 200,
});
```

**Comment by nmschulte** [comment]
In Firefox `width` and `height` are `0` at this point for the SVG in question; in Chromium they are `300` and `65`.  It's not clear where Chromium gets its "intrinsic" dimensions for SVGs that don't specify.  For some other "square" SVG I have, the intrinsic dimension is 150x150.  Chromium must be inspecting the viewbox/geometry and scaling to fit some internal sizing somehow or such.

https://github.com/CesiumGS/cesium/blob/master/Source/Renderer/Texture.js#L664

**Comment by nmschulte** [comment]
It seems this issue is related: https://github.com/whatwg/html/issues/3510.  Discovered via this issue to Firefox, marked as _resolved_ and _invalid_: https://bugzilla.mozilla.org/show_bug.cgi?id=1328124

It may be possible to work-around this in CesiumJS by setting width and height if the loaded image has zero dimension and zero intrinsic dimension:
```diff
diff --git a/Source/Core/Resource.js b/Source/Core/Resource.js
index 4dba57ae1a..1972b21852 100644
--- a/Source/Core/Resource.js
+++ b/Source/Core/Resource.js
@@ -1865,6 +1865,10 @@ function loadImageElement(url, crossOrigin, deferred) {
   var image = new Image();
 
   image.onload = function () {
+    if (image.naturalWidth === 0 && image.naturalHeight === 0 && image.width === 0 && image.height === 0) {
+      image.width = 100;
+      image.height = 100;
+    }
     deferred.resolve(image);
   };
```

**Comment by OmarShehata** [comment]
It looks like this isn't a Firefox bug as much as undefined behavior and different browsers handle it differently? Does this workaround make sense to be done at the application level instead? You can load your image and check if it has 0 width/height before passing it to CesiumJS:

```
var viewer = new Cesium.Viewer("cesiumContainer");
var collection = new Cesium.BillboardCollection();
viewer.scene.primitives.add(collection);

var image = new Image();
image.src = "https://raw.githubusercontent.com/lupomontero/psl/master/browserstack-logo.svg";
image.crossOrigin = "anonymous";
image.onload = function() {
  if (
      image.naturalWidth === 0 &&
      image.naturalHeight === 0 &&
      image.width === 0 &&
      image.height === 0
    ) {
      image.width = 300;
      image.height = 150;
    }

  collection.add({
    position: Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    image: image,
    width: 200,
    height: 200,
  });
};
```

**Comment by nmschulte** [comment]
Following the conversation about the issue is difficult without all of the context/knowledge of Firefox architecture to be honest.
It sounds like there are two issues at play, depending how far down the tech. stack you look.  Either way, it sounds like Firefox's behavior is "bad," and might need fixed at two different branches, leading to a yet undetermined UX: either what a typical user expects (a rendered SVG with no intrinsic dimensions), or an error message of some sort.

Your fix seems like a nice workaround.  It seems like it will bypass the Resource (request) queuing feature, but the cache will still function; do you agree?

The only other issue is that a client might have to blindly load a resource and not know the MIME type.  It looks like `Billboard`'s `image` accepts a `Resource` too: it should be possibly to modify a `Resource` instance's `fetchImage` to perform the fix-logic and still use the queue and cache?
