### ISSUE TITLE
Geojson default

### ISSUE THREAD

**Issue by meriem1998** [CesiumGS/cesium#9195]
hello i am loading a bunch of points of intrests from a geojson file into the cesium map only i want to change the default configuration of the point feature i already changed the image into pois icons and added a label to each point 
but i don't want it to be highlighed when hovered like in the picture bellow can you please tell me how i can do that ?

![Sans titre-2](https://user-images.githubusercontent.com/37738650/95718361-3f1d1480-0c66-11eb-8461-965d415a19a4.png)

**Comment by OmarShehata** [comment]
Hey @meriem1998 - we use GitHub issues for tracking feature requests and bug reports. I encourage you to post your question on the Cesium community forum: https://community.cesium.com/. 

If you haven't already seen it, you may find the resources on the docs page here helpful as well: https://cesium.com/docs/.
