### ISSUE TITLE
Invisible wall at WGS84 elevation zero affecting clipping and zooming

### ISSUE THREAD

**Issue by chris-cooper** [CesiumGS/cesium#9198]
We're having issues rendering geometry and navigating below the WGS84 ellipsoid when terrain is below that level.  We prefer not to use underground camera navigation as we still want the camera to stay above the terrain.  We require `depthTestAgainstTerrain: false` (rendering and navigation are more consistent with `depthTestAgainstTerrain: true`).

1) There is strange clipping behaviour on 'below WGS84 ellipsoid' geometry that should remain visible.

![visibility-issue](https://user-images.githubusercontent.com/484870/95926665-8c38ec00-0e08-11eb-828d-a46c5dbf98db.gif)

2) There is an invisible wall that prevents a user from zooming the camera in.  The wall can be broken through by angling the camera past it as shown in this vid:

![invisible-wall](https://user-images.githubusercontent.com/484870/95926682-9955db00-0e08-11eb-8bcc-75c76965dbe5.gif)

[Sandcastle example](https://sandcastle.cesium.com/#c=tVZtb9s2EP4rhLEP8uLSTtJgm+0Yc5Ki+6DMhuesKOKgpaWzRJQWBZJ2lgb+7zuJ1Gu8AN1WBJGp0z13z909pLRnihhQivFkruSeh6DIJbkGzXdbGihgBj5IJcKl9fG6o1WySvaI2nN4zJ0TeCwAf+Y2b9UJ8vtrmRgEgVp1euR5lZB2qmHb0Mud+BYEwoZkw4SG3MYSvmWGy6QyHjIulgXVASRAIyHXQENITbwEbaYRRtbGUUemObIsIOXJ1Y6LsF3EvLS7agOJUQhmMAp8mUTc7EJAzPkFffvT+dmo5YE0C4dTenHxy6AWZMu+wDznkkrNs3rI5cS1kiIcTaApC0MvbxchCdtiH1YdJItNtLYCOixX7sGaC7GWTIVD4uCEYNsijFAVSzdK4mSEVJ4rOL+hi9nHqX/l373rkbc/d6mRN8ywu4XvdXtFrD0owwMmZopHHNMXU2+Y6dVsuZzdlqAYeBSbBWxAQRJAifqtaafX/vR2/mk5+/R+Mbv7/cbCD3mYg51D0URsz3uQU2MjYC9jt5jYsjMvKYAKGXmf7bMh+eHZrg6fbTCsBjWgDaQaI5xlQ7KmEIRhaBrQwemoCIfDzZpUbQ3bs4/vfH/2gT5yE09FGjNvQC+6OWiD7c2i/YWQN6cj/B1fkvz3BLORvs3cfbZUbGZR01ZbbSeI/NFyG1mEvVpyiLxmyshIsTTmwRQF/4RB7osZFKRrPrkMbiBSANorM/faIn5jc/Zcjyst/PuQJ62QNuLD8bLmTuHZkI5VSbcs9YJs9DVCuGLJeU5nwUJcay+gdUJUODLZ2tHolgQaE/HxIMLcr2zRapNmh1a5S7N9Kp7sOVZ6VptXDxvl9SqPRx6aeEjOaiY8+kBxJoZWhuWTg1sduo3uNUqojqMXc3hVUsz8J0m1BVwKqWr9t0rq5Z74p5CvSIqZhqSOVPk9JJVd66nzHO5l0PRyM/uesqvx+J9k52h+lXK7lJ6jXzwkVXmH7GL/s79DfhK7Lmu2TQW4l/Wt1OYG8ONBQOi1vxHI/TcqpX0EdR/w/RZD4m12SZD1wbPJw3rA/HAuZFO8Ycgxx/vBg5t4XnHz9eQ5LYzcB8sq6fQ6Y22eBEyKfv7Kt6lUhuyU8CjtG8Ac2HrdX++CL2BooHXRzHG/Dh2HfE94eHnkg4sEgmmNTzY7If7gX1Ehk3Ef/V9AhURBJ9EM3+6CPWVu8enEt0ZK6biPt8eRRkqxZqoV+W8)

Browser: Chrome

Operating System:  I'm on linux, but I believes the problem occurs on other platforms.

**Comment by chris-cooper** [comment]
See also https://github.com/CesiumGS/cesium/issues/7879

**Comment by hpinkos** [comment]
@chris-cooper pretty sure this is related to https://github.com/CesiumGS/cesium/issues/6840
`disableDepthTestDistance` is automatically set on billboards that are `heightReference: CLAMP_TO_GROUND` in an attempt to prevent them from sinking into terrain

**Comment by ggetz** [comment]
I believe this was all covered by https://github.com/CesiumGS/cesium/pull/9200 and https://github.com/CesiumGS/cesium/issues/7594.
