### ISSUE TITLE
WebGL2.0. When i add 500 entities, there will be a few seconds of severe lag. But in WebGL1.0, it's ok.

### ISSUE THREAD

**Issue by caoyang0521** [CesiumGS/cesium#9201]
I tracked down the code and found that it was the modernizeShader module that caused it, and when I moved the interface call to ShaderProgram, that was fixed.

<img width="965" alt="屏幕快照 2020-10-14 下午3 40 58" src="https://user-images.githubusercontent.com/72854858/95958421-b3f17980-0e33-11eb-90c8-09c45cca6698.png">
<img width="941" alt="屏幕快照 2020-10-14 下午3 41 10" src="https://user-images.githubusercontent.com/72854858/95958426-b5bb3d00-0e33-11eb-8697-7e4303a9ee54.png">

**Comment by lilleyse** [comment]
@caoyang0521 I haven't thought enough about the implications of this change but I noted it in https://github.com/CesiumGS/cesium/issues/797#issuecomment-709622992.

**Comment by mramato** [comment]
@ggetz I assume this is fixed do to the recent changes with WebGL 2?

**Comment by ggetz** [comment]
@caoyang0521 We shipped WebGL2 by default in 1.102. `modernizeShader` is no longer called, so this should be fixed. Thanks!
