### ISSUE TITLE
Postprocessing is initially disabled and will fail if enabled again

### ISSUE THREAD

**Issue by bbbbx** [CesiumGS/cesium#9204]
Click the example's "enable" checkbox.

Sandcastle example:

[https://sandcastle.cesium.com/#c=fVVRb+I4EP4rFk+hUAMt190rUN0VWN3qdrfVstp7iYScxIBbx45sh5au+t9vxgmQQO5aqfWMZ76Z+cYz2TJDtoK/cEMmRPEXMuVW5Cn96XVB2Iq9PNXKMaG4CVtd8itUhNiNzmXypxIpc/yWOJPzbqje26NQhWoLqJm2wgmtALfEnDLj4MTUNV0Znc742nBug8vB1TXtfxgObwa/d8lwSPu/9a8/9G8QCoFyIwEjbFHaW7A0k3zGHOulOuHS9gror0yVpyUc6VpGYQu9fRHUGRY/82SunHA7gCrVHGXBLWVJEviaFEuhFIjXRWlfwO3h5NU+8G1BAgFjcfR4rzOwMmydQpTFhiXcLHRuYk4maBi2ciVW2qTE+orM1YzEWmrzg7+63PARCQGkRTqFMYDthFqTLY+vyHbpCqOp1iYRCui3J/axVtYRoRz5e/792/zL8p/Psx9/QeWDm1NkLRKSQmcDPLXrl7/qIpbrM7COZwAWv6XLTLxy+Z0BOaTnFchtpo2jby+j/3CHvKDzTD5qi81oKIdcIstB01WXfKR9cuFzaDdHuCZsy4F6/pPJnGMI0AV92m+yhyaQAJkSYNgfwb9xjTTQdDrtc78GbmpwTwXc0xncUyPc/0DiT62gzoSUvFzNguqr6dao7RR9uvCkB6JLntptatbRqDnM+7m6QVVLpDchK6mZC2qv7KJWcBPna7n8BChTTL1ozzCoAnfJ4LxZZTIwXMXrhpl0j0bDerLHkbYxV5xWrhYOQIsJ9wN+XHCPJ0ZBOdD1ob1tHOJi2NuhOs46JvAVNwMk45G4YpHkCQAwaf1q9LZl9Gel42edu2I3BQfv/c5zWsuIITuJjnOMT9fczSXH4/3uM5TTKm3CFjqd4rIsk7t7oWBs1vaI390jo49/rBgN9x68nWMR7aIGsSJHV7ph9uFFAWcZN24XoFO7vd+DJ/ELJSGY9UNkudkiG9U8vPvBzOaRjY2IeJBnCcx5pTuYKbANBCJ/q1zF/qtyZheUuVS6T8smAI33UDZnqlJOeYfwgNwA5/sVqlbXP9qxdTvJ7/YZ/yFSXHO4+gP4MDkOaxz3Uy/K4VvjaLxPHDx7VddxIrZEJJOGLyuJJbMWbla5lAvxxsPW3bgH9meuMHXY2AcYGsl2aLYZ3H0plJTScQ/EZs/DozlUMnbIw0FERaSTXUWBKlOTUZPczQsGxz04n9+OhcpyR9wu41jshsfPkX6FKoFodhnB09yrcUrKbviKT+BAUY0OYi0/kCsF7KvGX5SLv/8C](https://sandcastle.cesium.com/#c=fVVRb+I4EP4rFk+hUAMt190rUN0VWN3qdrfVstp7iYScxIBbx45sh5au+t9vxgmQQO5aqfWMZ76Z+cYz2TJDtoK/cEMmRPEXMuVW5Cn96XVB2Iq9PNXKMaG4CVtd8itUhNiNzmXypxIpc/yWOJPzbqje26NQhWoLqJm2wgmtALfEnDLj4MTUNV0Znc742nBug8vB1TXtfxgObwa/d8lwSPu/9a8/9G8QCoFyIwEjbFHaW7A0k3zGHOulOuHS9gror0yVpyUc6VpGYQu9fRHUGRY/82SunHA7gCrVHGXBLWVJEviaFEuhFIjXRWlfwO3h5NU+8G1BAgFjcfR4rzOwMmydQpTFhiXcLHRuYk4maBi2ciVW2qTE+orM1YzEWmrzg7+63PARCQGkRTqFMYDthFqTLY+vyHbpCqOp1iYRCui3J/axVtYRoRz5e/792/zL8p/Psx9/QeWDm1NkLRKSQmcDPLXrl7/qIpbrM7COZwAWv6XLTLxy+Z0BOaTnFchtpo2jby+j/3CHvKDzTD5qi81oKIdcIstB01WXfKR9cuFzaDdHuCZsy4F6/pPJnGMI0AV92m+yhyaQAJkSYNgfwb9xjTTQdDrtc78GbmpwTwXc0xncUyPc/0DiT62gzoSUvFzNguqr6dao7RR9uvCkB6JLntptatbRqDnM+7m6QVVLpDchK6mZC2qv7KJWcBPna7n8BChTTL1ozzCoAnfJ4LxZZTIwXMXrhpl0j0bDerLHkbYxV5xWrhYOQIsJ9wN+XHCPJ0ZBOdD1ob1tHOJi2NuhOs46JvAVNwMk45G4YpHkCQAwaf1q9LZl9Gel42edu2I3BQfv/c5zWsuIITuJjnOMT9fczSXH4/3uM5TTKm3CFjqd4rIsk7t7oWBs1vaI390jo49/rBgN9x68nWMR7aIGsSJHV7ph9uFFAWcZN24XoFO7vd+DJ/ELJSGY9UNkudkiG9U8vPvBzOaRjY2IeJBnCcx5pTuYKbANBCJ/q1zF/qtyZheUuVS6T8smAI33UDZnqlJOeYfwgNwA5/sVqlbXP9qxdTvJ7/YZ/yFSXHO4+gP4MDkOaxz3Uy/K4VvjaLxPHDx7VddxIrZEJJOGLyuJJbMWbla5lAvxxsPW3bgH9meuMHXY2AcYGsl2aLYZ3H0plJTScQ/EZs/DozlUMnbIw0FERaSTXUWBKlOTUZPczQsGxz04n9+OhcpyR9wu41jshsfPkX6FKoFodhnB09yrcUrKbviKT+BAUY0OYi0/kCsF7KvGX5SLv/8C)

However, if the enable property is true initially, it's fine.

```diff
var viewer = new Cesium.Viewer("cesiumContainer", {
  shouldAnimate: true,
});

var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706);
var url = "../SampleData/models/CesiumMan/Cesium_Man.glb";
viewer.trackedEntity = viewer.entities.add({
  name: url,
  position: position,
  model: {
    uri: url,
  },
});

var fragmentShaderSource =
  "uniform sampler2D colorTexture; \n" +
  "varying vec2 v_textureCoordinates; \n" +
  "const int KERNEL_WIDTH = 16; \n" +
  "void main(void) \n" +
  "{ \n" +
  "    vec2 step = czm_pixelRatio / czm_viewport.zw; \n" +
  "    vec2 integralPos = v_textureCoordinates - mod(v_textureCoordinates, 8.0 * step); \n" +
  "    vec3 averageValue = vec3(0.0); \n" +
  "    for (int i = 0; i < KERNEL_WIDTH; i++) \n" +
  "    { \n" +
  "        for (int j = 0; j < KERNEL_WIDTH; j++) \n" +
  "        { \n" +
  "            averageValue += texture2D(colorTexture, integralPos + step * vec2(i, j)).rgb; \n" +
  "        } \n" +
  "    } \n" +
  "    averageValue /= float(KERNEL_WIDTH * KERNEL_WIDTH); \n" +
  "    gl_FragColor = vec4(averageValue, 1.0); \n" +
  "} \n";
const postProcess = viewer.scene.postProcessStages.add(
  new Cesium.PostProcessStage({
    fragmentShader: fragmentShaderSource,
  })
);

var viewModel = {
-  enabled: false,
+  enabled: true,
};

Cesium.knockout.track(viewModel);
var toolbar = document.getElementById("toolbar");
Cesium.knockout.applyBindings(viewModel, toolbar);
for (var name in viewModel) {
  if (viewModel.hasOwnProperty(name)) {
    Cesium.knockout
      .getObservable(viewModel, name)
      .subscribe(updatePostProcess);
  }
}

function updatePostProcess() {
  postProcess.enabled = Boolean(viewModel.enabled);
}
updatePostProcess();
```

Browser: Chrome 86

Operating System: Windows 10

BTW, the fragment shader is from [https://sandcastle.cesium.com/?src=Custom%20Post%20Process.html&label=Post%20Processing](https://sandcastle.cesium.com/?src=Custom%20Post%20Process.html&label=Post%20Processing)

**Comment by chriswingler** [comment]
I was able to reproduce this a couple times where it would complain about the `v._target` parameter here:

`gl.bindTexture(v._target, v._texture);`

from this function in `Cesium.js`:

```
  /**
   * @private
   * @constructor
   */
  function UniformSampler(gl, activeUniform, uniformName, location) {
    /**
     * @type {String}
     * @readonly
     */
    this.name = uniformName;

    this.value = undefined;

    this._gl = gl;
    this._location = location;

    this.textureUnitIndex = undefined;
  }

  UniformSampler.prototype.set = function () {
    var gl = this._gl;
    gl.activeTexture(gl.TEXTURE0 + this.textureUnitIndex);

    var v = this.value;
    gl.bindTexture(v._target, v._texture);
  };

  UniformSampler.prototype._setSampler = function (textureUnitIndex) {
    this.textureUnitIndex = textureUnitIndex;
    this._gl.uniform1i(this._location, textureUnitIndex);
    return textureUnitIndex + 1;
  };
```

Then for some reason I was no longer able to reproduce the issue.

**Comment by j9liu** [comment]
Transcribing from Slack:

> When I add a `postProcess.update` call before `postProcess.execute` in `Scene.prototype.resolveFrameBuffers`, it seems to prevent any crashes. But the function `postProcess.update` should have been called at some point in `Scene.prototype.updateAndExecuteCommands`, so we're actually calling `postProcess.update` twice in order for it to work. This doesn't seem like the best fix -- do people have any suggestions / ideas about what's happening, or where I should look?

@lilleyse 's response:
> It seems to be a logic bug in `PostProcessStageCollection` where the texture cache is not properly updated even though the stage becomes ready that frame.

**Comment by lilleyse** [comment]
Here's what I noticed so far when debugging this

* Put conditional breakpoint on [line 558 in PostProcessStageCollection.js](https://github.com/CesiumGS/cesium/blob/4fb9fbb097663898733ef5850f4df7d0174f3af0/Source/Scene/PostProcessStageCollection.js#L558): `this._stages[0].enabled`
* Stage is enabled but not ready
* The texture cache is updated on line 653 but since no stages are active it doesn't generate framebuffers
* Stage becomes ready at line 666
* `Scene` thinks post process is ready (`environmentState.usePostProcess` becomes true), but the framebuffer was not created.
* `postProcess.execute`  returns early because it sees there are no active stages
* `postProcess.copy` doesn't (this is where the bug happens)

**Comment by j9liu** [comment]
@lilleyse - I see what you outlined, but I'm having difficulty parsing what the intended behavior in this pipeline supposed to be.

"Active" stages are supposed to be both `ready` and `enabled`, so when the stage is first re-enabled, it's still not active because it's not `ready`. However, `PostProcessStageTextureCache.prototype.update` won't create the framebuffers unless there is at least one active stage. What here should be changed? Should `PostProcessStageTextureCache.prototype.update` create the framebuffers if at least one stage is `enabled`, rather than fully "active"?
