### ISSUE TITLE
How to get the edge points after executing clipping planes for 3DTiles in Cesium?

### ISSUE THREAD

**Issue by peterchen2001** [CesiumGS/cesium#9207]
How to get the edge points after executing clipping planes for 3DTiles in Cesium?

**Comment by OmarShehata** [comment]
Please ask questions in the Cesium community forum (https://community.cesium.com/). We use GitHub for bug reports and specific feature requests.

If you're asking how to visualize the edges, you can pass an edgeWidth property to your clipping planes, see the doc here: https://cesium.com/docs/cesiumjs-ref-doc/ClippingPlaneCollection.html?classFilter=clipping.
