### ISSUE TITLE
How to realize that the vertex of a cone is fixed and the circular surface can be rotated ?

### ISSUE THREAD

**Issue by BaiH-ang** [CesiumGS/cesium#9209]
I want to make a cone on the surface of the earth. The apex of the cone is on the surface of the earth. The circle can rotate in the air.
PLEASE HELP ME

**Comment by OmarShehata** [comment]
Closing to move questions about using CesiumJS to the community forum: https://community.cesium.com/t/how-to-realize-that-the-vertex-of-a-cone-is-fixed-and-the-circular-surface-can-be-rotated/11259.
