### ISSUE TITLE
how to get the position of gltf model

### ISSUE THREAD

**Issue by WindDancerUBI** [CesiumGS/cesium#9210]
when I click the surface of the gltf model, I only get the point which is only on the surface of earth, not on the position of gltf model where i click
this problem just like this [click here](http://chuantu.xyz/t6/741/1603260045x1822611246.png)

**Comment by WindDancerUBI** [comment]
I use the pickPostion() function to get the postion which i click(i click the gltf model),and then i add this postion to the entities, the result is ttaht position is on the surface of earth,not on the surface of the gltf model.

**Comment by OmarShehata** [comment]
Glad you figured it out! In the future please ask questions on the Cesium community forum (https://community.cesium.com/).
