### ISSUE TITLE
Cesium.ColorGeometryInstanceAttribute.fromColor white is not white (but gray) and always transparent

### ISSUE THREAD

**Issue by onderaltintas** [CesiumGS/cesium#9213]
Sandcastle example: https://sandcastle.cesium.com/?src=Cesium%20Inspector.html

Browser: Chrome

Operating System: Windows

Greetings from El Salvador,

On cesium sandcastle example please replace "Cesium.Color.RED.withAlpha(0.5)" part to "Cesium.Color.WHITE.withAlpha(1)" or "Cesium.Color.WHITE". Unfortunately it is always gray and transparent. Like ma from requem for a dream says, "if this is white, then what is gray?".

Thanks,

**Comment by mramato** [comment]
You need to add `translucent: false` to the `PerInstanceColorAppearance` constructor.  [Complete example](https://sandcastle.cesium.com/#c=fVRdT9swFP0rVp9SqXNgwAsraKWjG9IKiGWwh0iTG98Wa44d2U5pmfrfd+MkToCyPCS27zn33C9nzQxZC3gCQ86IgicyBSvKnN77sygdZH4/1coxocCkgxH5mypCHBiDJ7dGrwUHc9oSMwPMwYM2kic1JBqOUrUbfkpVqtYoZzNQgGq1LPVbNPovXUm9AMqhcI8JWDdZoQPrGk9IcqYE7ymOJ5w3ouRK2QIypw0q1F5h40DxqAmqPqw3ATsXG6GGPWe3RuTCiTXYNpoinFDGeVTl3atRwEe+IoSsQOfgzBYlHFNYudM+/Osra8vqeKGIF3rTounS6PyLyEFZoZXtSISswTjYzLTJmQvUWzCtwFRLbSZFAcxUW3p/eZdc/vo9u7mbT5JR54cH7y/inTJ0bwVTR9HxQfXQgxE5CquTZjUMnnbdMtcc5Jw5IzYhsnp7TPNSOlHI7cU2wbisZA6loy6cBu6NS0zOUmDWXWvjHn8WiZ6JDfCZYTn0OORt0HXhYGUAbPTh8OCkCvoY38OONuxVYX/mPlX/+ugTfofR5BYF3x2OOTQtSldNQ695WdWcUBvfqtcDMmmZPhUP2ZtyZaAP366Sy32Z7ZpV6A4LE/Gi3e8PTjdzzjesxLuBA7dk0kKQyaS2wE/9BX2puMOiVNdsMBqMrdtKOG85n0VeYFtJaWREaewgL3AawMaLMvsDjmbWVsQKOo771DEXayL42Z7fEwbCrEXLspTyh3iGdHA+jhH/hio140KtbvAaSbatYI+H59/rQ0rpOMbtfqbTWi4YioVMerb6VzUHVb5S7qOetc4vSufwzv0HZRkWBPbj+ut/)

I'll add that if you don't have a specific reason to use the Primitive API, I would recommend the Entity API which is much more user-friendly. Also, in the future, please ask questions like this in our community forum: https://community.cesium.com where it's more likely to get a faster response. (GH is used primarily for confirmed bugs and feature tracking).

Thanks.

**Comment by onderaltintas** [comment]
Hi there, 

Actually I've written here because I was -and still am- thinking that it is a bug (setting something "white" and expecting "white" but resulting gray is a bug in normal terms). My intention was not asking a question but reporting a bug. If you are considering setting a color option as "white" but seeing it as "gray" is fitting the design and documented somewhere, awkwardly but easily this can be closed as "as design". Confirmed bug cannot be confirmed if it was not written here and letting the developers know about the issue. When there is a bug but it was not posted here how can you confirm it as a bug? Don't you think there is a logic problem here?

**Comment by OmarShehata** [comment]
> Confirmed bug cannot be confirmed if it was not written here and letting the developers know about the issue. When there is a bug but it was not posted here how can you confirm it as a bug? Don't you think there is a logic problem here?

If you believe what you're reporting is a bug then yeah opening a GitHub issue makes sense. In general when in doubt you can open a community forum topic to discuss. The Cesium team actively monitors the community forum, a lot of times a forum discussion will help narrow down how to reproduce an issue and then open a GitHub issue once there's a reproducible test case etc.

So I'd encourage you to open a forum topic if you haven't already - there's several reasons where the color may not show up as expected (the lighting in the scene/time of day, HDR/gamma correction, the material type used and whether you're using an unlit material etc).
