### ISSUE TITLE
BingMapServer culture invalid

### ISSUE THREAD

**Issue by duizhenpeng** [CesiumGS/cesium#9217]
imageryProvider:new Cesium.BingMapsImageryProvider({
         culture:'zh-Hans',
        url : 'https://dev.virtualearth.net?mkt=zh-Hans',
         key : 'bingKey',
         mapStyle : Cesium.BingMapsStyle.ROAD_ON_DEMAND
  }),

**Comment by OmarShehata** [comment]
It sounds like you're getting an error from Bing maps that the parameter you're passing is not supported? Closing as this is not actionable from the CesiumJS side. See the BingMapsImageryProvider doc: https://cesium.com/docs/cesiumjs-ref-doc/BingMapsImageryProvider.html#.ConstructorOptions

> The culture to use when requesting Bing Maps imagery. Not all cultures are supported. See http://msdn.microsoft.com/en-us/library/hh441729.aspx for information on the supported cultures.

Feel free to post your question to the Cesium community forum: https://community.cesium.com/ if you need more help.

**Comment by duizhenpeng** [comment]
![image](https://user-images.githubusercontent.com/10702327/97652828-52b7e000-1a9a-11eb-9da4-1f414437756a.png)
It seems to be supported, but it is invalid.

**Comment by OmarShehata** [comment]
Can you post the error that you're getting?

**Comment by duizhenpeng** [comment]
All Code 
`var viewer = new Cesium.Viewer("cesiumContainer",{
  imageryProvider:new Cesium.BingMapsImageryProvider({
         culture:'zh-Hans',
         url : 'https://dev.virtualearth.net?mkt=zh-Hans',
         key : 'MyKey',
         mapStyle : Cesium.BingMapsStyle.ROAD_ON_DEMAND
     })
});
viewer.scene.globe.enableLighting = false;


viewer.zoomTo(viewer.entities); `

There is no error message, but the map does not return the correct Chinese label texture.

**Comment by duizhenpeng** [comment]
![image](https://user-images.githubusercontent.com/10702327/97653235-408a7180-1a9b-11eb-845d-bc59cb4c68a8.png)
