### ISSUE TITLE
Fix "Quadractic" typo in EasingFunction

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#9220]
A PR for this was initially opened here but the change was rolled back since it required a few more changes outside the scope of the PR (https://github.com/CesiumGS/cesium/pull/9063#discussion_r460922311). 

I believe this is all the changes required:

* In `EasingFunction.js`, change `QUADRACTIC_IN`, `QUADRACTIC_OUT`, `QUADRACTIC_IN_OUT` to the correct spelling
* Update the spec in `TweenCollectionSpec.js` to use the new enums
* Since this a breaking change, add an additional option in `EasingFunction.js` with the old spelling to allow for a deprecation period?
* Throw a `deprecationWarning` anywhere that takes an EasingFunction to detect the old spelling ? Or perhaps just as a getter on `EasingFunction` ?

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/9264
