### ISSUE TITLE
3D to 2D Transformation 

### ISSUE THREAD

**Issue by bocheta** [CesiumGS/cesium#9225]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
hi guys, im just a beginner  with Cesium js, i want to know how can i Transform a  3D shape to 2D shape.
thank you

**Comment by OmarShehata** [comment]
Hi @bocheta , please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. Thanks!
