### ISSUE TITLE
Polylines not displayed correctly at long zoom distance on iOS

### ISSUE THREAD

**Issue by sparsematrix** [CesiumGS/cesium#9232]
I have seen this in my app which uses WKWebView and also with the default Materials example when loaded in iOS Safari.

Navigate to the default sandcastle example (https://sandcastle.cesium.com/?src=Materials.html) in Safari on iOS 13.5.1 or 13.4 (perhaps others).
From the "Polyline materials" selection, choose "Polyline Outline".
Observe that the polyline is just a large blocky red line. It is not a while line with red outline as it should be.
Select any of the other 2 polyline types.
Observe that the lines cannot be seen at all.
Re-select "Polyline Outline".
Zoom in tightly on the giant red polyline. At sufficient zoom you will notice that it does correctly render as white with red outline.
Switch to either of the other 2 choices and notice that you can now see the polyline at this tighter zoom. If you zoom out the line will disappear.
Sandcastle example: https://sandcastle.cesium.com/?src=Materials.html

Browser: iOS Safari

Operating System: iOS 13.4 and 13.5.1

I am using 1.67 currently as it does not present this issue. One of my colleagues reported to me that it was the latest he found that still worked.

**Comment by dzungpng** [comment]
I have reopened issue #9035.
