### ISSUE TITLE
Division by zero in barycentricCoordinates.js

### ISSUE THREAD

**Issue by PhilippeSymbol** [CesiumGS/cesium#9234]
https://github.com/CesiumGS/cesium/blob/ec320dd43f56219036625c8d7a4d7fded9b1dc5a/Source/Core/barycentricCoordinates.js#L101

https://github.com/CesiumGS/cesium/blob/ec320dd43f56219036625c8d7a4d7fded9b1dc5a/Source/Core/barycentricCoordinates.js#L104

**Comment by lilleyse** [comment]
There's a PR open to fix this: https://github.com/CesiumGS/cesium/pull/9175

**Comment by IanLilleyT** [comment]
https://github.com/CesiumGS/cesium/pull/9175 has been merged
