### ISSUE TITLE
ImageryProvider / TerrainProvider errorEvent does not fire for some network errors

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#9238]
Sandcastle example: I put up [this demo on Glitch](https://glitch.com/edit/#!/cesium-terrain-error-handling?path=index.html%3A46%3A0) so that I could check if it's a regression.  I'm going to try older versions soon.

Browser: Chrome release, latest (but shouldn't matter)

Operating System: Win 10 latest (but shouldn't matter)

Load up the demo and it starts with locally served imagery on an Ellipsoid terrain provider.  Now, you can switch to an Ion imagery or terrain provider, either pointing to a "bad" URL (required assets should 404), or to the default URL but with an invalid API key (which should give a 401).  Watch the console output -- all errors should log a message, via the errorEvent.

In both cases (401 and 404), the IonImageryProvider does not fire the errorEvent.

The CesiumTerrainProvider does not fire for the bad API key (401), but it does fire for the bad URL (404).

**Comment by thw0rted** [comment]
Update: I went back as far as 1.62 because that's where `TileMapServiceImageryProvider` was introduced (as a replacement for the `create*` functions).  It would be pretty simple to go back further, but that's more than a year and behavior is the same, so it's probably not a regression.

I noticed that the one case that does "work" -- terrain provider, bad URL -- actually makes a request doesn't trigger the handler, to `{base path}/layer.json`, but then goes ahead and starts requesting tiles anyway (`{base path}/0/0/0.terrain`, and `0/1/0.terrain`).  When these tile requests fail, the errorEvent does fire.  So, I would guess that these providers aren't raising their errorEvent for some resource loads that are needed early in the lifecycle, but maybe the terrain provider is able to try to run without this preliminary metadata.

**Comment by thw0rted** [comment]
I dug through the code a bit and it looks like at least for some providers, the initial network request (for provider metadata / capabilities) is created in the constructor, and chained to create the `readyPromise`.  So, I think what I'm seeing is unhandled rejection of the readyPromise, in the 3/4 of cases I didn't understand above.

I'm going to test this out.  If I'm wrong, I'll update here and keep looking for an answer.  If I'm right, I'd like to suggest an update to the docs, explaining that `readyPromise` will reject if there's an error with initial setup of the provider, and I'd also ask if it makes sense to fire `errorEvent` when the `readyPromise` rejects, just for consistency.

**Comment by ggetz** [comment]
This should be OBE after https://github.com/CesiumGS/cesium/issues/10909 is closed. I'll close this issue in the meantime. Thanks!
