### ISSUE TITLE
polygon's height not work

### ISSUE THREAD

**Issue by chengang0621** [CesiumGS/cesium#9244]
when I draw two polygons，like this [example](https://sandcastle.cesium.com/#c=5VPbatwwEP2VwS+xwZXtmKXtxllatlAKhZYm9KXug9aetUVlaRnJTp2Sf498WdbZhkKeKxkxo3Pm5oM6TtAJvEOCa1B4B1s0om3Y9/HOz71i9LdaWS4UUu6F8CdXuR02HI3caiqRPqkSD+gOZW+JKyPbAlXRr2HPpcHwyH4IrpypOleasPyqZV9p5cpPfTAXLaxAw3hZ+q4WgOINriH3vmEJh5nuPtPSnhfoWhpIM7CGMQSgFkicitqVn2facrLO4iple9LNB6wI0bwn4r3/YwoCeJUkKxaHRzd9vXDOscsnWLykpulTbElNk39gpwI/g9moUVS1XSfxsEKYLhtukQSXp+m01DQOtjVmdG4sCVX5F1TtuH+5WoXxsNmb4GLK/ODOhRbD31AvUOPjwAf8baktT8L8L2rAapTD4fBiRXJvlCQOZ1HY2yD3zjSBUZZJg3utm1vtnykSXIEXepmxvcTNseN3ojlostCS9BmLLDYH6foy0a4tfqFlhTFjdreyaBmalaIDUV4/8+KhkNwYh+xbKW/EvXtxmyxy/L9CpealG/BLhyR5P9DqZPN5umSMZZFzn4+0Wssdp7PMjw)，the height of green polygon is large then red，but it looks red is above green.

how to solve this problem.

**Comment by OmarShehata** [comment]
When using transparent materials, they are drawn in the order of the display list. If you add the green polygon first, it will appear correctly.

But of course, only when viewed from the top. If you move the camera to the ground and look up, the green polygon will render above the red, even though it is physically further away from this vantage point.

Not sure what the options are here on the engine/rendering-side.

**Comment by hpinkos** [comment]
@chengang0621 if you have any follow up questions, please ask on our [community forum](https://community.cesium.com/)
