### ISSUE TITLE
Pitch Problem in Cesium

### ISSUE THREAD

**Issue by bocheta** [CesiumGS/cesium#9246]
Hi friends, i'm a beginner with CesiumJs, i want to sync the view between CesiumJs and MapBox. my issue is that when i switch from 3D to 2D my pitch value jumps( i-e my camera pitch is 45° so i switch the view to 2D is stills 45° but when i go back to 3D (Cesium) my Pitch is ZERO. i do not understand why.

 public setView(view: View<Box>) {

        const westSouth = view.extension.minimum;// i read Longitude and latitude for the current position
        const eastNorth = view.extension.maximum;

        const destination = new Rectangle(westSouth.longitude * (Math.PI)/180, westSouth.latitude*(Math.PI)/180, eastNorth.longitude *(Math.PI)/180, eastNorth.latitude*(Math.PI)/180);
var pitch = this.viewer.camera.pitch;

      this.viewer.camera.setView({
            destination: destination,

            orientation: {

                heading: view.camera.bearing * CesiumRenderer.degreesToRadians, // Heading is the rotation from the local north direction where a positive angle is increasing eastward
          

               pitch: -Math.PI/2 , //topdown -> the horizon PITCH SET
    
            },

        });

    }

 public getView(): View<Box> {
    
        var heading =  this.viewer.camera.heading * CesiumRenderer.radiansToDegrees;
        var pitch = this.viewer.camera.pitch * CesiumRenderer.radiansToDegrees + 90 ;// ISSUE when i switch pitch jumps to 0
        var roll = this.viewer.camera.roll * CesiumRenderer.radiansToDegrees;
        //TODO: calculate from heading, pitch, roll
//if(heading<0) heading = heading + 2*Math.PI;//Test de Tolerance

        const camera = new Camera(heading, pitch);//heading pitch

        const viewRectangle = this.viewer.camera.computeViewRectangle();
        //const Frustum = this.viewer.camera.switchToPerspectiveFrustum();

         //camera = this.viewer.camera.switchToPerspectiveFrustum();
        const bBox = new Box(

 new LngLat(viewRectangle.west * CesiumRenderer.radiansToDegrees,viewRectangle.south *CesiumRenderer.radiansToDegrees),              
                          
 new LngLat(viewRectangle.east * CesiumRenderer.radiansToDegrees,viewRectangle.north * CesiumRenderer.radiansToDegrees)
     
        );

        return new View<Box>(bBox, camera);
    }

**Comment by hpinkos** [comment]
Hello @bocheta, please ask questions like this on our [community forum](https://community.cesium.com/)
