### ISSUE TITLE
cesium + vite

### ISSUE THREAD

**Issue by vinnitu** [CesiumGS/cesium#9247]
I have opened question about using cesium in es6 style, can you give me advise how to solve this issue?

https://github.com/vitejs/vite/issues/1058

**Comment by cxdev** [comment]
`cesium` need a BaseUrl to find its assets, you should copy Assets in your publicFiles like 

![image](https://user-images.githubusercontent.com/55689896/101112660-c8264b80-3618-11eb-81a2-538f24172d8c.png)

and add `window.CESIUM_BASE_URL` where there are  in your `main.js`.

you can see https://cesium.com/docs/tutorials/quick-start/#step-2-set-up-the-cesiumjs-client Install with NPM

**Comment by hpinkos** [comment]
@vinnitu if you have follow up questions, please ask on our [community forum](https://community.cesium.com/)

**Comment by nshen** [comment]
I wrote a vite plugin for cesium, it is very easy to use, please check.
https://github.com/nshen/vite-plugin-cesium

**Comment by martinageradams** [comment]
@vinnitu  I wrote a simple Vue Cesium Vite App template, you can refer to it.
https://github.com/martinageradams/vue-cesium-vite-app

**Comment by zouyaoji** [comment]
or
[quickstart of vue-cesium](https://zouyaoji.top/vue-cesium/#/en-US/component/quickstart#use-starter-kit)

https://github.com/zouyaoji/vue-cesium-vite-starter
