### ISSUE TITLE
EllipsoidGeodesic surfaceDistance is NaN

### ISSUE THREAD

**Issue by littlemurph** [CesiumGS/cesium#9248]
For certain pairs of start and end values very close to lat 0.0 lon 0.0, the EllipsoidGeodesic will calculate a surfaceDistance of NaN.

The sandcastle example below demonstrates one such pair.  The label displays the value of the calculated surfaceDistance.

Sandcastle example: https://sandcastle.cesium.com/#c=tVRRa9swEP4rIk8OOIql2k6bumGQlr0E+lDoGPhFkS+pmCIZSUnbjf73nR2nTZPAMtjOD+ZO+r67++7sjXBko+AZHLkhBp7JFLxar+hjG4vKnmz9qTVBKAOu7PWvS1OaDeJ8EC7MrPyMnGLQLp2on5SMSkPQBglN0EZ5axcZG/E0ZXlMBowmbISWZUme5JynlzBg/CMFmOqcBA1/xnnG8zy9RK40SxiypxTJr654xpIUE45Ge+RtfxRMUEGBp6Kqol9bstp6jFkzPpWQBtu4eCBMtBOgH++QyoQx6XjQVy+gH9RPGBOWxLuotNq6D/LGo9/vZrP7b92VN3y//cMytyL+xyKbQWmtam9V9RXs53Hd7Z1UGJLvssXdeP+i1YM1aPu7oAtnV7ewdAA+SijLYlwInu0a1mIOeq/hAC/Y/0Nwyiyj/bqpX7uFkHCrsEIjoX/cqrTGWw1U2z9A34WRDOU4e5GuOxA/A9SJd1jWsTxVV1Qk8aOQvN9Ctk8v7hU+vGqY7NT5ola1dYGsnY4oHQZY1Vog03C+lj8gUOl9U2VztRjuQ4tKbYiqbk78MojUwns8Wax1u2plb1IM8f4RVFtR4VjuN+C0eG2uPbHJbBuklBZDdE8jg7V6LtwB828

Browser:
Chrome 87.0.4280.66 (Official Build) (64-bit)
Firefox 78.4.0esr (64-bit)

Operating System:  RHEL 7.7 & Windows 10

**Comment by hpinkos** [comment]
Thanks for the detailed bug report @littlemurph!  I'm surprised this fails too.  It could be related to https://github.com/CesiumGS/cesium/issues/3057?

**Comment by littlemurph** [comment]
I really can't say if #3057 is the same issue or not but since it looks it hasn't made much progress I've submitted a small PR that fixes this particular issue.
