### ISSUE TITLE
When globe.translucency.enabled = true, the picture of the particle effect will be displayed on the globe.

### ISSUE THREAD

**Issue by marsy0217** [CesiumGS/cesium#9253]
Sandcastle example:
[Sandcastle demo](https://sandcastle.cesium.com/#c=rVjdbts2FH4VzcAAuVVkJ26QzEmDJWkyBGh+kLgt1roIaIm22VCkR1GJnSJAn2Db5S52s7vdbQ+w1+mwvcUOfyRRlhwM2IDAks4/eT6ec5hbJLxbgu+w8J57DN95hzglWRK+1jR/2Ir09yFnEhGGxbAVeB+HzPPSKc9ovM9IgiTue1JkOBiyh/bOkA3ZLVhNI8wwGDXWQ/0JTP0MYzzKJldTfncsUILTCyyucMRZDPLKkjZiJCeUj5T8TE4HOJX7EwgjlQMsBLyU4sojorMpAlI33NYGOh3v8x+fPv/42+eff//rl1///vTDnz99b0SlQCylGXiIFqDhunJZYMb9DDFDI4qdKCvcsYBdOkYR3reB6ICWpUYoumkSGjK79adITsMUy0vEYp6cZclI7Q6O/d76Zrm9CY8xBVFB5mDEqg6UozEXSRpilMozLuT01WzAj8kcx3qrfZU7K32IhIQ3xHoq9OQFngiMU39tazPc/GprayvwnnXDbm97u9cesrbdZJwQKbE4YUQSRF/yCEnCWRU8pWEfDASe/lnvwqOMfwYyJKL4EMFnqsnjjEXa2ATLkwRNsN82WCNjz//C2o7xGHAY+1X9tpX0luxCXDGPsgQzGUYCA1SPKFZfCtlaYthSMdU1wzsSyynob3Sb+VNMJlPpCqhlAYglnsuNF8BYUoBVHRouON+IS8eFTjjCE8IuIP9+nYdE5G8HnvmD/XTRMnhzfn1xEmhU1jUjylO8wuqYUHolF1Sd1GFLTEb+xuZm4OU/7WGrUcVaelA/AstMsHpCHwqoEqgSWXI0n0EgkN8rcq/c9QAPFlQJmjdJaMjsVPFyAVCmlt8EuQ1/S6Fty2BNaY4ykUqr8cyxSMkYS5IYRwWV6fN2Pj4mAt9xcZPqDGt25QCclufvKhJIRtNqQIb1zG9XoW1AmBv3+XgMJz2A3aVcBCbU1GJZrxq2w56v+qFFceyb5DQfysAwrQ/z0XxK24ppUtq8xNK/XZeuGLrcUO3LBpLHG1Tiqu9V1V+e2wF/wwWN686SjEoyowvrxal9Kx3V11tkpOr8Trkc8AsbQ905YbdYpLiorZX1ViMPGqm5v9xjarDoHmCha/0BlncY57abjo110HRemrf0wiakEaMuAgpNWGKkwisgW5TaosY2I3M5WQeLC05UpdU63vJGBzk9Nx8ugcdbtQjDzmuZag71swHtAw5DFuOr7zIkVL+wNtre3nOTgSf6USyqqS1C5WS4WECTxNujy/OgFCjWcospj4hc5Kw8Wl0xHxwwMIUoW9CMiK+jW2vMf9vrWKHGkrlCqcgtcF9C1dMzUq+kormlrofdgkoNyYnvifaqRddyU23vaf5qF2VmqZkgcCTJLU6dMuVAL0fB1SKVOPGLHBDV9/vOBFBsbipB5VDVyb4tlzkHs9ilQ+eWUz1dqemjXUOTirWvl1fansF81Tf9JqiEohberzef0ndCUrXPl3oK7rp0VZD67pqvZlMs8JHhQGzrZWym8PftsyDnLapfvBWsbBaDy0NEqRoo++bYFlynQvYbymVTweyvLqIPRcksevr8VE/fa26Lnp+i+VLXXlixbZdUk7q3UpsuSUttup1XZ/d8pk6x6srvVFAfK7XyUmWxG25t2sDVQMv6XplVK3dAM5WtcNuS9QzeV/DXhIfAMS2MzSUL3+SWC1//3fT/Ee2KjVgZ9cja7q62/d5MMFx4vsoCUdVjBx679Vlpx3v6lDjjy/zRNqcwFGjUlBVq8ajGQmssKhr3j2rca437ioYZiFa2wjl4AJVSXuPOmcB0kVHzj7mh+fmAXKLzHfG+rBBCitlETt8vjwLmvCswv9fuil3+YHb5A+xyT+3qh6JPGZVwlqXTojM1FNYDJVbWVc8zdcTdKQbzvHvJhOvWk3qhKcDTLydpl2n6UBPTlI289z2YVf+rAditNBHcWgVa+kdCaKg7rsj542ld63XLy6i9ihrFkHJ+sy+LAc93C2bF+CM6S0PQyYujs8HJ4Nvywiu5e6WoTxJpNpICRWZeemSgd+PRhJUjvfJd92MaOuTJdyIK3PDyixNiE2qnEhc2FyfX56+PLq/h0umtKaamooinFo91nzGXVW91kVdnJ4Prt0WjcXb51czXkShyK2jtpuq6upeD7GuSzLiQXiaoH4YdGCZmcCPBaWeURTcYbv1pms9eux1XdTcmtx6Jnzf8i8uLKEpT4Iwzqtv9sLW32wH5mirlKCZscg43BIoWSmy6vvfSEMMw3O3AZ7Om5Bw6t1iy/A8)

Browser:

Google Chrome 84

Operating System:
windows 10

![image](https://user-images.githubusercontent.com/26667880/100335832-62323680-3010-11eb-9965-96e8f52c5a9b.png)

When `globe.translucency.enabled = true`, the picture of the particle effect  will be displayed on the globe.

**Comment by hpinkos** [comment]
Thanks @marsy0217 , this is a known issue https://github.com/CesiumGS/cesium/issues/7511

I've added a comment to #7511 so we can notify you when this has been resolved.  We're always happy to review pull requests if someone has a chance to look into this!
