### ISSUE TITLE
Does cesium support to show the wireframe and the textured model at the same time now?

### ISSUE THREAD

**Issue by wyq521** [CesiumGS/cesium#9256]
i want to show the wireframe and textured model at the same time,in the threejs i can make it with EdgeGeometry,how can i do that in cesium?(except load model twice)

**Comment by hpinkos** [comment]
See https://cesium.com/docs/cesiumjs-ref-doc/Model.html?classFilter=model#debugWireframe

In the future, please ask questions like this on our [community forum](https://community.cesium.com/)
