### ISSUE TITLE
Tileset styling in CZML

### ISSUE THREAD

**Issue by runaas** [CesiumGS/cesium#9259]
CZML has provision for adding a Tileset in a CZML-stream. However, I find no way of using a Style with a Tileset in CZML. 

Adressing a style could be done both by the uri mecanism of CZML, where it could either be referenced externally through an uriValue, or internally with a ReferenceValue, or even directly in the property.

"tileset": {
    "uri": "http://myserver.com/my3DTIlesService/tileset.json",
    "style": "http://myserver.com/styles/MyBestStyle.json"
}

"tileset": {
    "uri": "http://myserver.com/my3DTIlesService/tileset.json",
    "style": {
        "show": "true",
        "color": {
            "conditions": [
                ["${buildingType} ===  'residental'", "color('green')"],
                ["${buildingType} === 'comercial'", "color('red')"],
                ["${buildingType} ==== 'public'", "color('blue')"],
                ["true", "color('#ffffff')"]
            ]
        }
    }
}

**Comment by hpinkos** [comment]
Hello @runaas, please ask questions like this on our [community forum](https://community.cesium.com/)
