### ISSUE TITLE
how to zoom the map when mouse in a html element

### ISSUE THREAD

**Issue by chengang0621** [CesiumGS/cesium#9265]
I use a div element replace the entity cover the map，when mouse in the div and rolling the wheel，it can't zoom the map.
if set the div 'pointer-event:none'，it will be work good ,but the div can't trigger click event，Is there a solution to solve the problem.

**Comment by hpinkos** [comment]
Hello @chengang0621, please ask questions like this on our [community forum](https://community.cesium.com/)
