### ISSUE TITLE
TypeError: Cannot read property 'disableCullingCommand' of undefined

### ISSUE THREAD

**Issue by Radik24** [CesiumGS/cesium#9278]
Hi, I'm getting `TypeError: Cannot read property 'disableCullingCommand' of undefined` when `backFaceCulling: false` in Cesium3DTileset. Is it issue with cesium, or my data? I tried multiple cesium versions (1.76.0 currently). Thanks
![cesium](https://user-images.githubusercontent.com/23722745/101799698-c4109700-3b0c-11eb-84c4-285217b8f2e0.png)

**Comment by Radik24** [comment]
It seems to be issue in node_modules/cesium/Source/Scene/Model.js on line 4546

i replaced `if (!defined(nodeCommands[0].disableCullingCommand) || forceDerive)` with `if (!nodeCommands[0] || !defined(nodeCommands[0].disableCullingCommand) || forceDerive)` and it's not throwing error now

**Comment by lilleyse** [comment]
@Radik24 there's actually an open pull request to fix that! https://github.com/CesiumGS/cesium/pull/9271

Could you confirm if that branch works for you?

Also do you have a Sandcastle example that triggers the bug? That would be helpful for testing.

**Comment by Radik24** [comment]
@lilleyse i used `"cesium": "https://github.com/TerriaJS/cesium.git#node-commands-undefined2"` in my package.json, built it and it works!

Sorry I don't have Sandcastle

Thank you!
