### ISSUE TITLE
Sandcastle example should use https instead of http for map tiles

### ISSUE THREAD

**Issue by mclayton7** [CesiumGS/cesium#9279]
Sandcastle example: https://sandcastle.cesium.com/?src=Imagery%20Layers%20Manipulation.html&label=All

Browser: Chrome (latest)

Operating System: Windows 10

The USGS WMTS example should use https instead of http because Chrome won't allow mixed content (an https website requesting http). I'll open a PR shortly to fix this.

![image](https://user-images.githubusercontent.com/3297057/101988187-af8fe400-3c5d-11eb-92fd-1c3e0cf5ccb3.png)

**Comment by OmarShehata** [comment]
Fixed in: https://github.com/CesiumGS/cesium/pull/9280. Thanks again!
