### ISSUE TITLE
ManagedArray.js Bug

### ISSUE THREAD

**Issue by artlifecq** [CesiumGS/cesium#9283]
In this file, there is a code problem:
Object.defineProperties(ManagedArray.prototype, {
  /**
   * Gets or sets the length of the array.
   * If the set length is greater than the length of the internal array, the internal array is resized.
   *
   * @memberof ManagedArray.prototype
   * @type Number
   */
  length: {
    get: function () {
      return this._length;
    },
    set: function (length) {
      //>>includeStart('debug', pragmas.debug);
      Check.typeOf.number.greaterThanOrEquals("length", length, 0);
      //>>includeEnd('debug');
      var array = this._array;
      var originalLength = this._length;
      **if (length < originalLength) {
        // Remove trailing references
        for (var i = length; i < originalLength; ++i) {
          array[i] = undefined;
        }
      } else if (length > array.length) {
        array.length = length;
      }**
      this._length = length;
    },
  },........

if the length is less than  array.length will cause a memory leak, possibly array has many elements, but the this._length=0. It is easy to modify and can fix many memory leak bugs.

**Comment by hpinkos** [comment]
@artlifecq I'm sorry, I don't understand.  Why would this cause a memory leak?

**Comment by artlifecq** [comment]
for example:
        var managedArray=new Cesium.ManagedArray();
        for(var i=0;i<1000;i++){
            managedArray._array.push(new Object());
        }
        managedArray.length=0;
        console.log(managedArray._array);//？？？
        console.log(managedArray.length);//0
        console.log(managedArray.pop());//undefined

**Comment by hpinkos** [comment]
@artlifecq you are using the `managedArray` incorrectly in the snippet you posted above.  You shouldn't be manipulating `managedArray.values` directly.  Instead, use `managedArray.push`.

```js
var viewer = new Cesium.Viewer("cesiumContainer", {
    terrainProvider: Cesium.createWorldTerrain(),
});

  var managedArray=new Cesium.ManagedArray();
    for(var i=0;i<1000;i++){
        managedArray.push(new Object());
    }
    managedArray.length=0;
    console.log(managedArray._array);
    console.log(managedArray.length);
    console.log(managedArray.pop());
```

The code also calls `managedArray.trim()` when necessary to resize the internal array.
I can see that memory is growing in the sandcastle example you provided, but I'm not sure `ManagedArray` is the culprit here.
