### ISSUE TITLE
i find safari don`t work with load base64 img

### ISSUE THREAD

**Issue by CaptainYYH** [CesiumGS/cesium#9284]
Browser: 
safari don`t work with 
google worked

It's OK to use canvas to transfer in. No matter Google or Safari, I guess img needs onload to draw img

code：
billboard: {
              image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAAC8CAYAAACOjwsWAAAa/0lEQVR4Xu1deZhVxZX/nbqv6RZRkEURemPfumkWBVkUQYOCuKG4Q4OSmMlkjPMlk2Q0iSaTZJKMmRidz4wZBbrRfMbdaNyNKy7I1guyQy+goKDI2su7deY79/Xyul93v3vfvfe9br31+Qf2O3Xq1PndqnPq1KkqQictmeWP9g7p8Kkgs79m7keaTwIxaVImTBOGESJmVkxQgKZINxQTQxORNs0wwzCgWBtgYlZ0WBF9Bjb2hlXo0915V33eGbve0JHUi5a7a3lG/Zcqm0gNJjZPF4kMZUDDTPNSOgWj3tSmxZLJ+IRZ70zrqasqBi2p8bKdRHmlFhC+Qw0sGTxUkRpJmk9jA/UE3S3RziRSj6HqyEQaK9qnWW/eU7BzO+jnOhFeXtRJCSCZ7z7Qm040xijQcJmCkg1Ce4oTcGSK0+CtfNTcuHvq0qRPa0kFZFDZX07T4dqJCKn+HOYQDC++KR94mACFKIyw3qtC6Wt35V+3z4dW2mSZFEAGbirqE6rHJILq77VN8FtRYnMYem84Dav3jCo84Hd7/gKy5v607FDGZCIawaQ763iwpWNiZTLzlqpwzQc44+Z6W5USIPINkMz1y4cRME0pMpg67eTkSGXEMLVmk4FVu8cv2eaosk1izwEZuu2e9Nqak2eAeQCBkuox2eyzazIG14Ho4/SMQ29uH3ZLrWuGUQw8BWRgyUOZBsKzBAgmVl4K2tl4yRpVgDER+seeght2eyWfZ4AMKisaqzWf+VWZnuwqWKYxpejDXfmFpXbrdETnCSC5ZcvPNcPIJcP/KYpBPYi5LynqyZp6gDiDGSHpJBHCYKohxUdY85dMtJ/AR7xQVEc82OQ6I4SKivwlb7htyx0gfIfKLh88V5ncTyt4GuKQjjFTiMAjGDSMmEeBqL8on4B6iOQSx2LLYWicHjUIJhgaDPkvLQIS72WiTQTexqAtRBx2q7jW9ZVGvTbos6q8nc+7WeknDMjo8ke7HTWPXQygl6fTFCMDwEQAUwAaCkYNCCd4okDGcZDw5+0A3gOwFgTPYlgyfQE4eKLR/dmP8q6qS0TmhAARMI7omkthoheMxkhrIs23qDMEoFlgAYNqAPYGhHbFouMAZ4CwFuB/ANjhugfCwFQyZg/2UBnPJAKKc0D4DpVTPuQyDqOPJ2AwxgB0MQinIzI6kl9klDA+AfhZEDa6FsBUTCEcqMzb8bTT6csxINkbiuYR8WlupylizgHUlQxkAykCIlbzNQRUAfpxJqp0A4xMX8y0r2pc4XNO+DgCJLe0eIap9WBya8CZFgA4F4h4R52wiNF/A8SPuZGNNeoNpXZWjF30pl0+tgHJXFs0lpSe4Ma1JcZwBpYAOBGgdLtCpoaOZQV+lIDlTNiaqAziErNW63ZPtLdOsQVI5oaigQbRha4ChIzZAF3aiUdFezoPA/wMCC8nCooEJk3mF3ePK9wTj0dcQCauuT/ts9AJ10BpF16PWgrNeZ65r/F65fXv4i4rKgf0Awmz1up4v/DxR9bGiRTHBSS7tOh8YuQmFJsiToemWwEaCKCTT1FxVV0L8B4ovhtMjgOKVuyLUFE1tvDVjlrqEJCsshVDwOrsRLZYGTiRmH4A4DTJV4jb3a5BIAu/fUx8FwFHnYosW8Qg/XZ1/uJ21zztA8KPGtkba6+HNp2vDayRoX4M0OmS2+FU8M5NTxKU+QRK/yaRkQJl1FSNSX8YdFUk9aVVaVdZOaVFU6AxihU7d00ZPwIox4+RcV3v4fjrF9vEyU8lbibAlSD81qkQpCkMhU2VYwsldGMPkOzSh08hDl+RkN2AWgrmsX7YjHHd++KZoXPx0IGtuH3P+y0609PohndGzscLX1bhh7vfdaqnROhrQVSaiKGP2JPQE1Vjr//C1gjJ2lB8ASktX7izIq4t01y/vKlVI+cjs1sPK5Q7edPj+LT+eJN8f8qZgbk9IyL/bM9qFB3Y7Ez2RKitYCU/n4hLzFpVVo9b9FJcQPqvW9YvXRkXO52qmDGcQN/za51xbe9h+E3mlCb51xz9FFfseLHp/5flzsKMkwYiRCRhd1y382W8e2RvImp2WifM4D+Sw8WjTF212nx274QbP4tuMMaGuBgd/wlQb6e9sUMfIoXyMdfgBBXCwl2v4oHcmUgnA1fveAnvH42kTF1wcha21x7CP52ahwWnDEE9a8zc8jSq63zfn5Kdm89B+Hc7fYmmaWuUtABk8JpHe5ppNVc6XpFbsSk+269wyG8zp+Ca3sOw8fjnmLvtOdzcbwxuO32iNWWduSk23PTaiEsxNL0nDpq1OGvTEziuPd+PaqV7CbPQ205jX7KCN+ozHt95xlVfNjJsAUjO+mVTodJGM5m2ExQkastQP/Rrquqf1h3vjboCCoRZW57BjtqI7BvGXI1TjHT86pO1+PNnLSPmPYw0rB61ACeqELbXfonztjzj9ONNhD5M0L9zEiUmNjR0/UeV429s8kJaArKh6EbntoO+T8DwRHpgp85TQ+dgQvd+eOPwHhTueq2pykU9c3BfzgzUsYm88kdQyy3d+jEn9MZzwy6ygHzpyyp8q9L1dndccRnYSsS/j0sYRSC2pHJc4bKYEZK59oGhpIzpjqK51uaS+qZfu3tTevTHI4NnW17VxI8exefhlhGLN0dejtxuJ+G5gxX456q3YvRwQ5/h+NXAs6y///e+DfjjPk8SQzrQt+xC6v9zsskViQab7+yeuFS2la1UAavIxhMUD3CCLph+DGCQozoOiNeMXoB+oRPwyOfb8KPdsesoGTkygsSrmrXlaeysPYQ+oQysHX2V1Uprj+WanS/jPf89r10g/o2Dbsp5o48bN7Isma098vpjix1GnGQP/Ba/tl2/1W8Mbj9dch1gGWdZmW+pOYhrd76M75yah6V9R1u/CQBSNtd8gQu2Pmt5XyVjrrY8Mik/3fMBvjAjI+utwx/jSzOh3AP7+rWSJvgeR3v0JtAjrfsK2YO3ALGmqzRjuqPUT6ZvNWSH2BfWAaWAMevkTKuGeExSxIWdvvlJ/C5zKq7uPdT6W/nxyBEOUfoNO1+x/j2+e188NVTWp8De+mOYuvmJZIda1oL4z3a7KxmQXB+ZtixAstev/AYM0/7UI6k0mu5uY1awK4NtuqxuPfD2yPmWcm+tfgdPfbETfUMZ+HD0Astg372vBH/YVxLDr7DPSPxi4CTr72uPfYb521+w3aYHhAzFt1opTHaLaeyqGr/wlQggJUWFkAit3cJqGsAyUTuPBNtto4Hu+WHzIB7Tnrqj1pfeWO7KmmYtAMOsUfDRX3HEjD0hcG/2ObikV65V5eEDW3Fbq/iXQ1GckNcA9ChIr7Jdiam2qqCwiHLXL+8Fgy7XcJB5qOnfQIjMGT4WmbKW586yWliw40WsPvppU2tiKzbmXYs0UnjlUDWWVrzepiSvj7gMg9NPtn77yZ4PsPLAFh8ljmLN2A7F/2W3MSXZmCY/RQM3FA1PA0+zmwpKQBoz/Y/dhtzQNS7+yo4fwLxtf49hdetpBfjX0wqsv5+/9Rlsq4ksGsVd/na/Mda/M8jAWT36W/8Wb0ycgiR4WlZ7RPxdFkXbKJKKWg9aRVmlK84hYKSNOg0klAfGTQC626/jnFIULQoXJZ67+SlU1B1uk0nZmGtwstGtxYo8GiipJIvHxv0T8cYuS449OQbCgwCX2+09A5spp2TlFUxmH7uVQDQfGhfYpk+AUEIfJaOvhgQVXzu0GzdWSKZn22X+KYPxh6zp1o/frXoLzx6ssEImEjoRPlJkfSKBxqQXhZfA/KTddomNA5RbumKJI/vB6jZAsg79Kw/mzsL5DS5v41TDYCsmJcqVsinvuqa1RuMCUAx7/sZHrJX9sIyeeHn4JZYnJuXVQ7txUwfA+tMbqgTpX9vlLXaEcsqKb2K5fsJ2oXvA/maQiHc0pMEQi4fVWGZETV0CSPeGxZ+AJBFdmd5kNX64YfF3+SmDcXfD6BEe935airv2brDdU9eEBMlUucUuH5Iz+1mlxYvtZpUQc0+G+hWceGR2pWmDTtxacW+ltI7a/nTAGU2r9feP7MXVO9vOY/v1wLNwfZ/m2GfjtOZCLCdV5WaK25moKbzeUWXrVoms9csX2w8o0mBo3OLXFm20sAYRysdc2zQKLtz6LDbVNG9Bt/5ddg9lF7Gt0riWkd9kOrto29/xUcMK34l2HdNaCXa4B+CddupKoNGZDdGYCMIigHxfEP7HwMlY1GeE1Q9xU2Uqal2W9B2FOwecaf354/qjmLKpeeEYTStrFlnZSyKElGM6jGmbn4iJHttRmjMalmMOxVByBiV+idiQkhU32T1awEwziHAlGL4ed44OjYhdmLTpsRYJDdFdk8iu0EvpKLlhSHrEyMueu5SkxLgIdcx4nIhtZb/LEQbKXl/8TbsHb5jpAgIuizrTFx/2BCj+Onh202JOYlcSw2qvRK/mZZNKNqskbJ+hYv0UGSnRpXWiRAKixquiGXiaiGOyS9qsKAd9sktXSNTWXmHMs047+Vga9zikCUlUEDc23p544x661Hnsix1WwkNbgLQl9lU7XsL6Y/t97JF1Ksv2oZ1OB4jsnw9IO9FS0L2fluGuvevjKmv0Cb3xwrB5Fp1McVM3PWHZlM5RHANS/M3mK/I67gJpzGGyznj4kq+7sM8I/HLgZEuIo7remn6s8802imz1SgxLyoZj+3Hp9udt1PKdRC4XfIYVbMb+FTtaGBJjJkBXyPlvr7sSnXslvMXotufGttV2r1A6pvewbga0iuRvyQ5hKot1nh78BBPaDkW3Ei6yMNxQdCPZTKhmljuv6Ho/9kGidwG9UOL+cI2VGJHiUsPgh4mw2o4crCnsbKUOGsGMb/sR6f1B/3E4o/upHcotydayVy6bUvG+fllrtJWJYkcxHtIcI8L/MtjWJozjlToz9SXgZ35ktttRQmOOlkxnkmzdBUotA78gYltunLVSz3GaHMd0nx/nPuwotwsCYoL4O3b6JjSSNEc5JUVLHZ0DYfwCIDmmlvTS9QDhfSBrRrFVrHuis0qWX0NEkU1nO4VpEYBICDbJpesBglUgLrarJmY+RHLKFuDB9itZt4te51f6aEdydC1A6DhD/8WuhxXpN+2krJLiPMU8yW6SNRH11CZ+TZT8azG6EiDMCCsDtzGzrb0QsR+aaDWdVlJ8ajfCXLubVA1I3glG8yrM7vBySdeVAAFZtwvdabfL4vLWMZ63QiA5JcU3OTmkw6ALFWOe1yt22QNpPCfYVkd6h9KtPXIJphwI208KjKeUP31ajgf2fxSPzPbvskLXhOcI3HzmLk5tObxTWbDowYbMxeKLQdr2F0+k+rHmO7zeyn166FwrLzfZ5fEvduD71faTDG3IV0+Kfs6sW5wf7LAeq0+qChY9GwFkw4oxDJpsN4RiMY6cRbftDNjohHVUbU7DSVo79F7RPLj/Iyt9yLvCO52cYbdCJuAPqsYt3mgBMmLzgyfV1IcWMDu5JIAmgLHQjzCKd4pJCSdJkFsJ8Dq7rRNROCMt/NiWkTcdbj6wU/LQlaCws1O0THIw5RS7DX9N6L4AsRxksl849HlVwQ1WLKgJEHF/DaIzHb1ewDQdjCuTkYViv3cppIzcevo4iNvfc24lnvXiD/OH1QWLrJTTJkByd72eoQ9XL7S7WdXEl0ky8+ynoqZQX0lo+gCIb3PWjmJ1UtbKikEzLbexxc5fVtmK2XI3ljOGli2RcIqLC86ctdhJqWV0FDuxHZZvRKiozl/clOPUEpB1Dw5AKG22s0WipZ7vgSly6O/rWohlIfNHJ9237s8K179cPeGmpq3NmL3xnJIVVzA5m4KYqC9piQI7PDbqRPrOTWuyws+I7e17NHaFGAcqCxa3yO6LASR3/fJcEzjXfnppA/uvq4FPwJBbU5Vc4A+8UTF+SYsFUJvZI9klRVeC2JkLHMFlKZjkSJOvmY2daLDUgVhOnDq/HJPp86qCwphtzzYBGVK2LKuOQ+clYEvESbvTujb861DkenJlP4DYqBKxHd0o/NqO/BurW6up/Sv+1hfPZUNHDoo7KA377uL6RbLdvrrlKEO2IZzZDVEHmWp35fhFbSaOtQtI7q7lvfRhY4HjdYkFAA0C4/teBx87EbbyfsnvAd7lXCZZd5iPVQxacrCtuh1mIOZsKBqvFRUkMnX5fcOcc0V4ViOhG+QsQy4viWouqRxX2G5+bNyUUBcGXmQYAiY50uX7eRLP1N0xoxqQw3tMovm1Y8ijSeICMmDN/X1DRvp8FyuM/tD0LyD08uuSsySAIQcYD0LxvZLlmlB7JhA2a5/8+IybO8zRiguINJ5d/tBorq+f5Hht0iC59Ywe42YAsn/i6/n2hJTVcaVjcrKaCPdb7xcmUKwEuLS01VV5N8TdlrQFiMiQU1I8C8y5dpMh2pTbeiEBlwNk+wrBBPrvYRWWZ7yfSuQa2EYhrIuTiSoqCxa1f9g+SmLbgFiglBXPZ9au9liJKIdlY0ujb6cN20cOa+4nwkpmdvfSDqn9lfmL7F8e4ORzGrDm/u6h9Iz5YHY97RDTuQyeL48P+n3u3XYf5Vw5Mwj0JBO7v6SR6Fi4tkbshkx7toqjESIc5SnutHq+xNHtD+2IYtkW8IVgkqs65BZL+1dE2eqebSK5cs4A8UsEejFRWxHdmpyorU+jvzl98tsxINJo7url/TmdLrJ7ejeuWuR1NqXOgebzrRO+Xr1bGK/hSGCwDopehdZvefWmoXWatpb/XjFpiWOPLCFALFDKl/fnsJrrysi3qTC5bYinAZQv5z598Mpk+kgDuAxEq5zc1hMPX/ndymAP6ecr8pyDYdW300h7NHJPfDcjbQ4ogTdG7DU8CppGg+Q6WitgKW4nAyQKjfOMBsnbUQKo9FGiz5+AsRHK2kjaZK95h1Rs1NSZ9S+0vs/dCRdXgEhDkkJ0vN6YQxoneTaFtd+DgdZRCHmcmKiv1uilCL0YaL6diLmCFFWybBYR7QdYLoeP+xiXE6W1prXeLFQ4fEKa+YKk8rji5aZyU12+Q2WW5s4mjf6JLh4TlYM0spjoJ431WeE+YmuPIinFughZYe/usRUvO33Vsy0BXY+QaKYSjATxhCSMlKZmCchiTg0g1mPETOs6ChY6/So8BUQalzcPFTCTgG7eG/zY7hFUFjMndYSI4WagTgOv23mb0AkongNiNc53qKzSodMU62F+g5JsQCLnONS26rHbV3kxRcXYIyfoOaWNjBaexszd/bItyQLEChASHdOgVV6Pimi9+jNCWiGXU1Y8ijVPYmbl+mHjVrxjAAHuo0jigSdFHhgmIk2KVlfmL/LHXY6SNCmANLY3qKxorKkxnokokV3Itr2SVjbEI0CsQ/zMbCis35Vv72FhL76ApALSKLCMGK3NApCR4RYYr0eIlU3IZo1SRkkyRkRSbUi8LyZr3YMDlJE2EtCDtGYzETvjBSBiH5SS283ULm3Wb45O7YzXB69/T8kIaasTkjGpFQ1hzVkgIiUXddu4FIcY2Qy6vZEn25iyLE9J4uzMTIqqleYdrTMIvVa0XX6dBpBogSXEb9RyfzYwULHRj8HdG+9QV8yh6JsnOgJEbkbQJDEtK6CVRqBjmszPyMQeM532Og2N21WqG7pOCUhMh16/IzTgpAG9Qt1CJ2sK9TCgenAYJ4J0OoFHMNFdjXWI+ZfMxlsUwlET+oji8JFwXfjQx4c/PoiZP/f7/Tw3WFh1uwYgHXQzp2TlBIZuuoaVwZdWFyz+m2vNpIjBVw4QgC6R48Up0qfrZgNAXKvQWwYBIN7q0zW3Lg9I9toVExGiNc2aCKYs11+FGwbZpSsmgqMB0ZdUFSwJbIgbpbqpGwDiRns+1I0BROHiqvxC21d7+yCSK5Zd34a0nrICQFx9EK4rx4wQxsWND/26Zp4CBl1+hGStKz6DDP6wSXcBICn4jKKaDABJrf5jWs8qKz6DdDBCOg0srQEhpeZV5i+Mfae100jcsSBd34a0GiEBICn+8mJHCM+rzF8cjJBU4RIDiOZ5leMDQFKFB7LWLz+TlGp6MIUCQFKGhdVwAEhq9R/r9gYjpHMhklX+0Jlkms1TFtFFlWPbvmmnc0netjRd3+0NAOlc31kwQjoXHnJAaJIifNAoFgVTVmoRigFE00Xt3daWWknttd7lbUgsIPqiyvFLOsW7q/YgaEn11QOEMLdybKHNt2cTUZm/dQJA/NWvY+5dH5DyoknKjDbqwQhx/BV4WSGzZNlkBeP9Zi8rAMRL/TrmlVlSPFmBA0Aca86nCgEgPik2UbYxgJiYWzkh8LIS1afreq0BUVBzKgoW2n4/0LUAHjPo8l5WbknxZB1lQzTUnN0BIB5/Jg7YxQKi5+wuWBKMEAc69JQ0t2T5WRrqvUamGgEgnirYKbMAEKca85k+AMRnBTtl3xoQNujC6rxFLznl01novwJeVksbwkwXVo8LAEnZB5Zb8tBZGmaTUQ8ASRkUkYZz1hVNYQPvNooRABIA4qkGurwNySktmsIcjBBPvwo3zAJA3GjPh7oxgCi+IPr1ZR+a9JXlV2/KCgDx9YOJyzx2yuILqsc1v08el0EnI+j6I2T9sqmsjFXNbm8ASEq/sZwAkJTqP6bxnPUrp7LSwQjpLLDklK2cyroZECg1uyp/4SudRT6ncnR9GxIA4hRzf+mDEeKvfh1zz16/YhoUvdNUMZiyHOvQ0woxgGg9u2r8ksCGeKplB8wCQBwoKxmkMYAQvlE1tvDVZLTtRxtd3svKLl8xDWaUDQkA8eM7sc8zAMS+rpJCmb2haDoIbzc1FoyQpOi93UYCQFKr/5jWYwAx8Y2qCYFRTxlMASApU33bDccAAuP8qoIbXutkYtoWp+u7va2NOvj8qoLFASC2PwGPCbPLi6bDjPKyAkA81rBDdlkly88mqLeaqwUjxKEKvSUPAPFWn665BYC4VqG3DLJKVp5N0E1TFoHOqyxY9A9vW0kety7vZQWAJO9jsdVSAIgtNSWPKGvdinPIoDcbWwymrOTpvs2WskpXnEMcAJJiGJqbjwXEPK+y4MbAqKcKoRhADMyqzCt8PVXyuG2363tZraesABC334S7+jEjhDGrclwwQtxp1UXtzHXLZijDeKPJywoAcaFND6pmriueoQwOAPFAl56wCADxRI3eMcksLZ6hOBgh3mnUJafWgCilZlbkL2yawlyyT3r1Lu/2BoAk/ZvpuMEYQLSeWTF+SZcdIf8PJw6LqAgyrHsAAAAASUVORK5CYII=')
 
}

**Comment by CaptainYYH** [comment]
@ @twpayne hello？LOL

**Comment by hpinkos** [comment]
@CaptainYYH please create a reproducible example in [sandcastle](https://sandcastle.cesium.com/) and post in the [community forum](https://community.cesium.com/) for help.
