### ISSUE TITLE
How? RectangleGeometry extrudedHeight gradient ramp Color Material bottom-up (floor-sky)

### ISSUE THREAD

**Issue by 4NK4** [CesiumGS/cesium#9285]
As the title suggests,What should I do?
![102080948-55a04180-3e4a-11eb-8fb3-6ce631477eb5](https://user-images.githubusercontent.com/28991681/102084147-b120fe00-3e4f-11eb-8406-4bb455768b81.png)
`
static GetRectangle3() {

    return new Cesium.Primitive({

      geometryInstances: new Cesium.GeometryInstance({

        geometry: new Cesium.RectangleGeometry({
          rectangle: Cesium.Rectangle.fromDegrees(121.5, 37.8, 121.7, 37.9),
          vertexFormat: Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT,
          extrudedHeight: 150000,
          //stRotation: Math.PI * 0.5,
          height: 150.0,
        }),
        id: "rectangle",
        attributes: {
          color: Cesium.ColorGeometryInstanceAttribute.fromColor(
            Cesium.Color.fromRandom({
              alpha: 0.5,
            })
          ),
        },
      }),
      appearance: new Cesium.EllipsoidSurfaceAppearance({
        material: new Cesium.Material({
          fabric: {
            type: "Color",
            uniforms: {
              color: new Cesium.Color(0.0, 1.0, 0.0, 0.5),
            },
            source: `uniform vec4 color;czm_material czm_getMaterial(czm_materialInput materialInput)
            {
              czm_material material = czm_getDefaultMaterial(materialInput);
              material.diffuse = vec3(0.0,1.0 - materialInput.str.r ,1.0);
              return material;
            }`,
          },
        }),
      }),
    });
  }

`

**Comment by 4NK4** [comment]
I don't want to use image Texture.

**Comment by hpinkos** [comment]
@4NK4 this is not something supported by the RectangleGeometry.  The texture coordinates are based on the lon/lat position of the vertices, so the texture stretches along the height of the wall to match whatever is on the edge of the rectangle.

You would have to implement a custom geometry type to accomplish a gradient from the ground to the top of the shape.  The code samples in this guide are outdated, but this explains the general concepts you would need to write a custom geometry: https://github.com/CesiumGS/cesium/wiki/Geometry-and-Appearances
