### ISSUE TITLE
Georeferenced B3dm tile Looks down in the southern hemisphere 

### ISSUE THREAD

**Issue by maptheworld** [CesiumGS/cesium#9292]
Hi Everone, 

I have a georeferenced model with ecef coordinates that is located in the southern hemisphere, when loaded to cesium, it  's orientation looks down !!! despite that it  s correctly located to the matched area... any workrounds to make it look upward ???

Thanks 
Cheeers

**Comment by hpinkos** [comment]
Hello @maptheworld, please ask questions like this on our community forum: https://community.cesium.com/
