### ISSUE TITLE
Multiple globes?

### ISSUE THREAD

**Issue by jumpjack** [CesiumGS/cesium#9295]
Is it possibile to have multiple globes (or textured ellipsoids, or textured sphere-objects, or whatelse) in the same scene? I am trying to show multiple planets.

**Comment by hpinkos** [comment]
The Cesium scene currently only has support for a single `Globe`.  We add the moon using a textured EllipsoidPrimitive.  See https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Moon.js

I can see you've already asked some follow up question on the community forum- please continue to use the forum for any more questions.  Thanks!
