### ISSUE TITLE
Camera translate broken when picking 3d tiles point cloud with transparency

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#9302]
Reported https://community.cesium.com/t/3dtileset-picking-issue-when-style-applied/11871

[Sandcastle example](https://sandcastle.cesium.com/#c=tVVtb9s2EP4rhDbAUirTjpesg+MGS7MBK9DFQZLuk75Q0lkmQpECX5y4hf/7jnqzbG9FP7QGDPN4D++ee3hHb5gmGw4voMk7IuGF3ILhrqT/1HvhKKvNWyUt4xL0KCZfErmLrhKZyOYcNRlIoIVQKdAcKrt+AmNvCsQb+wRa4wJjW+2gOdVm/FvlINCB8Qh+VMUybrdzcj6dxs1Wpbi0j/wzkHoX89YBWobPUmXPyllqNcuewz5k1GexSomU+cJylbkSpKUF2D8F+OX77Yc8HLWQkT90HJdVldi+5zLnsjD7+HEXd5CICzBgDxVsfn7546lxhm2dTot5B/mg5AMY5XQGdKVVeWMQiLTOf72YnUdDFW6Fcvnjmnku806y/YdZC9Ixy5Wc10rHx4iSvfLSlTdD4NsTlFS6ZKLPs2LCQI3Z9ZeeyLZaqoHl23ukzQ1QuwYZrpzMfOiwhUQd04NOqTQvueUbMJTleY+9OoB+Vqp8Up0zHgr7F9T07rnN1g9MFhBO6TQm4ym9jLuroKly9cU9VmvQQDUecYackRmdRj7VLqIKOesXJL/njd2qdM86U9IoAVSoovVc9TIcNws21jI1oDcsFTBsllHb2KOIGpeaTPN0kLB1RkdTgJ1058oUB7ADtOrwFQm5uWN3vSMadoMG67Rssbvmp1PE2K2A/2/RR+8OB7GSIFNC6SSY41IXKSMh+fnL7fLj8oHq3dnsEtXu7OLITls7Cd70JU38DJM3SRAlQUuw66h+8e2q9m/Df+vau3t59o9Jr+0edKLu3vXN+p7MKT2dOcy953FGsG/f7lsqiINFfUnXTeDfeVkpbf2LEVI6sVBWglkwk9Rlz5gwM6Yj/lP31A24pvgqFtqPwZz46wsvZjHpvlP6W3e2FgcHsZ74i+p1sJ0qnYMeN8MzdO6O0nJZOTtMvgFtecbEmAle4FNT8jwXcJpxbFU1J7ODrJ0rVdaqcujFtItJJ9Ei5xvC83fYp4f/UUlAMsGMQc/KCeG1ToLrxQTxB8eEqq9piVwF23rI+vz6Y7NJKV1M0Dw91ZaM8IaT91wvmx7v0PV+o4ndVoCntH+nkFjJJVpTv2KvuPJ/awExFipv4DJnlo1T/NNBe8OEg3k3QDGp7U8VQnB3VMcf7Xkc5LPwan1grB2ty68GbkPUhdz77iResh9TS9/937+aPrR/Xjr2/wI)

When the point cloud is opaque, you can click and drag to translate the camera relative to the point cloud.  This makes it way easier to navigate when you're trying to look at details of a tileset. However, when transparent style is applied, the camera moves as if you were picking the globe instead of the tileset.

**Comment by lilleyse** [comment]
`viewer.scene.pickTranslucentDepth = true` should do the trick: [Sandcastle](https://sandcastle.cesium.com/#c=tVVtb9s2EP4rhDbAUirTjpesg+MGS9MCK9DGQeLtk75Q0lkmTJECSTlxC//3HvVuexv6YRNgmMd7ePfcoztqxzTZcXgBTd4RCS/kHgwvc/pXteePksq8V9IyLkGPQvItkofgJpKRrM9Rk4AEmgkVA02hsJsVGHuXId7YFWiNC4xtdQk3J2cKnmxXmkkjSrTtB3e4hyK4IfdFpSDQgakJPqpgCbf7ObmcTsN6q1Bc2mf+FUi1ixSrAE0xW6mSrSottZolW78LGXRZrFIiZk6DVCVljmRoBvajALd8v/+U+qMGMnKHTuOyohD791ymXGamjx+2cQeJuAAD9ljs+u+XD6va6Td1llrMW8gnJZ/AqFInQNda5XcGgUjr8ter2WUwVOFeqDJ93jDHZd5K1j/MWpAls1zJeaV0eIrI2SvPy/xuCHx7hpJK50x0edZMGKgwh64/ItlUSzWwdP+ItLkBajcg/XUpExfabyBBy/S4QTTPueU7MJSlaYe9OYJ+VSpfqdYZDoX9Ayp6j9wmmycmM/CndBqS8ZReh+2roLEqqxf3XGxAA9V4pDTkgszoNHCpDgFVyFm/IPmeNza20h3rREmjBFChssZz08lw2izYWMvYgN6xWMCwWUZNY48CasrYJJrHg4SNMziZAuykhzKPcVZbQKMOXxOfmwf20DmCYTdosKWWDfZQ/7WKGLsX8M8t+uzc/iBW5CVKKB15c1zqLGbEJz9/u19+Xj5RfbiYXaParZ2d2HFjR96brqSJm2HyJvKCyGsIth3VLX5c1e5u+HtdO3cnT3+ZdNr2oDN1e9cP63s2p/R85jB3z+OCYN++7VvKC71F9ZJu68C/87xQ2robw6d0YiEvBLNgJnGZbDFhYkxL/Kf2qhtwjfFWzLQbgzlxr8+/moWk/U3pb+3ZShwcxGrir4rXwXasdAp6XA/P0Hk4SctlUdph8h1oyxMmxkzwDK+anKepgPOMY6uKOZkdZW1dsbJW5UMvpl1MWokWKd8Rnr7DPj3+nEUeSQQzBj3rUgindeTdLiaIPzomVPWalshVsL2DbC5vP9eblNLFBM3zU03JCK85Oc/tsu7xFl3t15rYfQF4Srt7ConlXKI1dSv2iiv3WfOIsVA4A5cps2wc40cH7R0TJczbAQpJZf9ZIAR3R1X8Uc/jKJ+FV+sCY+1oXf9r4CZEVcij607iJPt/aum6/7+vpgvtrpeW/Xc)
