### ISSUE TITLE
Cartesian3.fromDegreesArray()  gives different results than Cartesian3.fromArray()

### ISSUE THREAD

**Issue by jumpjack** [CesiumGS/cesium#9309]
According to their names,  they should behave in a similar way, but Cartesian3.fromDegreesArray creates an array of Cartesian3, while Cartesian3.fromArray creates one single Cartesian3 element!

Cesium.Cartesian3.**fromDegreesArray**(coordinates, ellipsoid, result) → Array.<Cartesian3>Core/Cartesian3.js 929
Returns an **array** of Cartesian3 positions given an array of longitude and latitude values given in degrees.

Cesium.Cartesian3.**fromArray**(array, startingIndex, result) → Cartesian3Core/Cartesian3.js 253
Creates a **Cartesian3** from three consecutive elements in an array.

**Comment by mramato** [comment]
Hi @jumpjack, The Cesium API uses radians/meters by default everywhere if a specific unit is not specified, so `Cartesiuan3.fromArray` expects values to be in radians.

If you have additional questions, please start a thread on our forum: https://community.cesium.com/

**Comment by GatorScott** [comment]
I don't think this was about the degrees/radians behavior but rather that fromArray() creates a single Cartesian3 as output while fromDegreesArray() creates an array of Cartesian3.  Suggestion is that if you provide 6 values (x0, y0, z0, x1, y1, z1) to fromArray() it would produce an array of two Cartesian3.

**Comment by hpinkos** [comment]
@jumpjack you should be able to use [Cartesian3.unpackArray](https://cesium.com/docs/cesiumjs-ref-doc/Cartesian3.html?classFilter=cart#.unpackArray) to get the functionality you're looking for

**Comment by jumpjack** [comment]
@GatorScott  is right (by the way, where does this degrees/radians hypothesis on my question come from?!? I didn't mention radians, and I did put in bold the key words)

@hpinkos I don't need a workaround, I know how to avoid this Cesium bug; I was just informing the staff about the misleading name of the functions.
