### ISSUE TITLE
Using certain rectangle of ImageryProvider will cause Cesium stop rendering

### ISSUE THREAD

**Issue by ZenDay** [CesiumGS/cesium#9312]
Sandcastle example: https://sandcastle.cesium.com/#c=bZLfb5swEMf/lRMPIZGQjcOPQQrRqj5MlTp1Wtq9jD044CZoBke2oSWI/30mpFXa9eUkf+9z3zvb11IJbcmemYQUavYMN0yVTYV+nbR5ZuWn842oNS1rJjNrcZXVWY0xXBcF0BquZf7tdgPf6WHDZGt8yorumOyA087wdUvfpLtRUabR1BG9k43tWX7i3YOYv0siWhS3k/BDirYsxtlquJz4UfIHVh041ewj2Y8oQCP5Cuy91ge1wrjSvRrQTogdZygXFW415p1U6X72kvYvw6xL+26YHdP+ONjO5KCabSEq8xBqBb9t13bAJmNYjsGz/5wxyXJNa+O7uhzw56s6JyiOIj/2A5eEfkhiP3TARV7sx8QlsbeMojgkDpywgET+F9eNQ9cNlq9Y4Pu+SzziestgMfYcTFwsrsByrETpjrP1NAnA17I6CKnHy88Rwvr8RApvm/wv0yhXavzREU3wZWlSlC2URfrJCkDOqVIm89RwvimPLLPWCTb8f6Vc0KKsd/dmL8w6jNierO8mESGUYHP8vFILwbdUfnD+Bw

Browser: Chrome 87.0.4280.8

Operating System: macOS Mojave 10.14.6

Cesium Version: 1.72

Using certain rectangle of ImageryProvider will cause Cesium stop rendering.

Reason:
In function `ImageryLayer._createTileImagerySkeletons`: 
```js
  var clippedImageryRectangle = Rectangle.intersection(
    imageryRectangle,
    imageryBounds,
    clippedRectangleScratch
  );

// .... something doesn't important
    imageryTilingScheme.rectangleToNativeRectangle(
      clippedImageryRectangle,
      clippedImageryRectangle
    )
```
In fact, the result of `Rectangle.intersection` would not always return a real `Rectangle`. In some cases, it will return a value `undefined`. But Cesium DID NOT check the rectangle is `defined` or not, which would cause Cesium stop rendering.

**Comment by ZenDay** [comment]
An solution about this problem might be:
```js
  var clippedImageryRectangle = Rectangle.intersection(
    imageryRectangle,
    imageryBounds,
    clippedRectangleScratch
  );

  if(!defined(clippedImageryRectangle)) {
    return false;
  }

// .... something doesn't important
    imageryTilingScheme.rectangleToNativeRectangle(
      clippedImageryRectangle,
      clippedImageryRectangle
    )
```

But I'm not exactly clear about what does this function do, so the code above is just an possible correction.

**Comment by hpinkos** [comment]
Thanks @ZenDay!  I think that's the correct fix too.  I've opened a PR with the fix here: https://github.com/CesiumGS/cesium/pull/9319
Thank you for including a sandcastle example to reproduce the error.  That was really helpful for finding the fix.
