### ISSUE TITLE
When rendering, there will be many burrs on the distant elements

### ISSUE THREAD

**Issue by ruanhailiang** [CesiumGS/cesium#9315]
When rendering, there will be many burrs on the distant elements. How to deal with them or give me a suggestion.Here is a picture of the result of my run.
![7b062bea0e66a9ec614ae9d7794799a](https://user-images.githubusercontent.com/15086045/104296042-2984e880-54fc-11eb-91b1-0f91159c22e4.png)

**Comment by hpinkos** [comment]
Hello @ruanhailiang, this looks like a known issue with your polyline rendering.  I'll add a comment to https://github.com/CesiumGS/cesium/issues/4224 so we can notify you if it's fixed.
