### ISSUE TITLE
polygon render failed

### ISSUE THREAD

**Issue by wanggit13579** [CesiumGS/cesium#9318]
`var viewer = new Cesium.Viewer("cesiumContainer");

var data = [
      110,30,0,110,30.2,61803,110,30.4,117557,110,30.6,161803,110,30.8,190211,110,31,200000,110,31.2,190211,110,31.4,161803,110,31.6,117557,110,31.8,61803,110,32,2,110.1,32,2,110.1,31.8,61803,110.1,31.6,117557,110.1,31.4,161803,110.1,31.2,190211,110.1,31,200000,110.1,30.8,190211,110.1,30.6,161803,110.1,30.4,117557,110.1,30.2,61803,110.1,30,0];
var purplePolygonUsingRhumbLines = viewer.entities.add({
  name: "Purple polygon using rhumb lines with outline",
  polygon: {
    hierarchy: Cesium.Cartesian3.fromDegreesArrayHeights(data),
    fill: true,
    material: Cesium.Color.PURPLE,
    perPositionHeight: true,
    outline: false,
    outlineColor: Cesium.Color.MAGENTA,
  },
});

const points = viewer.scene.primitives.add(
        new Cesium.PointPrimitiveCollection()
      );
for (let i = 0; i < data.length / 3; i++) {
   points.add({
     position: Cesium.Cartesian3.fromDegrees(
       data[3 * i],
       data[3 * i + 1],
       data[3 * i + 2]
     ),
     pixelSize: 2,
     color: Cesium.Color.YELLOW,
   });
 }

viewer.zoomTo(viewer.entities);`
**render polygon isn't by order.**

**Comment by hpinkos** [comment]
Hello @wanggit13579.  The `perPositionHeight` option only works for positions that are mostly coplanar.  We have no way of determining what is supposed to be the flat face for an arbitrary set of points in 3d space, like the arc shape you're trying to draw here.  However, if you split this shape up into 10 different rectangular polygons using `perPositionHeight`, it should render as expected.
