### ISSUE TITLE
why new material() a err

### ISSUE THREAD

**Issue by PZD2937** [CesiumGS/cesium#9320]
`new Cesium.Material({
            translucent: symbol.lineOpacity,
            fabric: {
                //type: 'lineStyle',
                materials: {
                    color: {
                        type: 'Color',
                        uniforms: {
                            color: transformationColor(symbol.lineColor, symbol.lineOpacity) || defaultOptions.symbol.lineColor,
                        }
                    },
                    image: {
                        type: 'Image',
                        uniforms: {
                            image: symbol.linePatternFile
                        }
                    },
                    polylineDash: {
                        type: 'PolylineDash',
                        uniforms: {
                            dashLength: symbol.lineDasharray
                        }
                    }
                }
            }
        })`

![image](https://user-images.githubusercontent.com/50706050/104541796-471d9380-565d-11eb-936e-0585cbe428e7.png)

复合材质是这样用的吗，代码和官网示例结构一样的啊，不知道为什么报这个错

**Comment by PZD2937** [comment]
![image](https://user-images.githubusercontent.com/50706050/104542333-4802f500-565e-11eb-88c0-315f3465e0b7.png)

**Comment by hpinkos** [comment]
I'm guessing one of your uniform values is `undefined`.  In the future, please ask questions on our community forum: https://community.cesium.com/
