### ISSUE TITLE
Any way to determine if a polyline intersect with a shredview region in cesiumjs?

### ISSUE THREAD

**Issue by peterchen2001** [CesiumGS/cesium#9323]
Any way to determine if a polyline intersect with a shredview region in cesiumjs?

**Comment by dzungpng** [comment]
For questions like this, it would be better to post to the community forum: https://community.cesium.com/ where others from our team and community are actively answer questions. Issues are for bug report, feature requests and enhancements. Please include an example Sandcastle or code sample of what you are trying to achieve (for instance, an example of a polyline and "shedview" region). That will help clarify what shedview is (I assume you mean viewshed) in this case.
