### ISSUE TITLE
how to compute geometric error in 3D Tiles rightly

### ISSUE THREAD

**Issue by SuperMarioStack** [CesiumGS/cesium#9324]
hello,I know the geometric error is measured in meters,and it means the error of the simplified geometry compared to the actual geometry.but I dont know how to compute it. for example, I have a osgb data and it's lod type is DISTANCE_FROM_EYE_POINT,when I convert the osgb to 3DTiles,how to compute the GEOMETRIC ERROR param? Is there some relation between DISTANCE_FROM_EYE_POINT and GEOMETRIC ERROR?

**Comment by dzungpng** [comment]
There has been some discussion on this topic which you can reference here:

https://github.com/CesiumGS/3d-tiles/issues/162
https://community.cesium.com/t/understanding-geometric-error/8480/2

For future questions similar to this, please post them on our [community forum](https://community.cesium.com/), where there are engineers and other users who can help answer your questions.
