### ISSUE TITLE
cut a hole to see through the tunnel

### ISSUE THREAD

**Issue by 0mao0** [CesiumGS/cesium#9329]
can I cut a hole on the terrain and txtures to see through the tunnel.
Or can cesium make "some parts of the map" transparent?
![image](https://user-images.githubusercontent.com/39977902/104793429-71965a80-57dd-11eb-96ea-01b02e4a1d72.png)
![image](https://user-images.githubusercontent.com/39977902/104793476-bcb06d80-57dd-11eb-9fde-d464cb05abfd.png)

**Comment by dzungpng** [comment]
I believe what you are looking for is terrain clipping planes. Please refer to [this Sandcastle](https://sandcastle.cesium.com/#c=3VqNb9u4Ff9XiAzDyTub0feHk3TLpeldhutd0KRXDE0w0BZja5FFQaKSeIf873sk9UHZclN3vWJYgcaW+Mjf+36PpA8P0fuSonma5HmSLVCekoyWiDNU0pTOefJA0zVaJjFFOSl4idgd4kuKFimbUVRWxR2ZU3yT3WQPpEAPCX2kBTpBGX1EZ7RMqhX+Tb4zbg7m8vmMZZwkGS1uDsbo95sMofJ+fcpXrMyXtKBTdEfSko7lwJJVaXyaJSvCYYAXlXrPaVHAEpcFewC+immDNC8oEH5gRRpfKxJjpBaa04w6r3/N0nW7zPPoSPGsJDmpeceSFsuXR41Y9Ims8pRer3NQzQn6KNa8OVCo6C3JQBT16opj9BPoLSvbVz8WJIvRGcnWLEMXJUuBxViO3h51SnvLYprC0lIhOty09yTXnFdFQTN+3r3vE300bxVdbdNLadLzjMxSGmtqpPGCXvF1CiSbg881a5yxdEaEQWM2r1aAiheUn6dUfP1hfRGDWWuamwOh0NoS9xmb37OKY16Q+b3RSjhEQvI8Xf+QZDHwUXak4wZ8JM1weIjeMGBIrCf8tOSgR/S4pBkqHxM+X4qXuhaUAIM6AHGEnLWM22roxmstJCktKZfPKSOxkgDsbije7qoMAgXMWwgyY6SsWPsTKCrhCS1xQVfsgZ6mqZyF+v6WF8kqEcHW0Bk1qKB97oFscFCDAZs5KxNJcdIExBlELHwjmYPvCrZ6R2L4XhpiAkITG5uhb0dB5AaO41l26I/ViIl9L/R92zQtx3R8y3frAcs1TWyK70pwhSslXHcR1EpM4tj4Xc1seJu23+olZ+xpimoihOIEHKuEUfB7LYV0chiKhTFqPu1QfI7GzQoiVRQJSdukcMZSVuAPP11cn2NwlOVpmi+JYWKnmwNeCNbXM4z2Vs4fWq0mfJafz61CvkAHK+HvmhaqIplC5sD48Er682vCyaEkKg9by9ff/glfIVvN6nwjl0sgY1ary+SJplfJv0EusK2moCcxejUnKYyA9oblkAkQxzTny2ta8tMFZNOS12m1C5CGsB9n/QJwpo+BAmVZYVmjFinYW8KLBDxB+RKes1Vecfq2GzLqxf5epeAHoBGKM/ZojBorqro1VblZ/NvFgNEQoF0eJtzKrP90TgIBEzTeL/51I1+MNPl2UCpmvhnS5POhbutPkYY/JDFfTocy8l8F82gqldXRvxSbtClrg2Wgc/jGi2dQXN5AP3NWpQJ8282hI3m8uk9EH6TViDbqZXWi8XmTEJU3D2bwK676hCaBQ307k+3LVit2x0RqT9cLmEkKVkE3QYBStGizmprGuCsCScbbJmWXkRojTGzHC13HxY5nWp7nu4HbGmziBK7jeS6GIdsyPTvqxlwvtMzQxEFg+aFrhq4aaGz6MmgQhj523dD2A89y+6Cu6wfY8+0gCIMw6mPaJo6sKAr8wAy9vUHtKMIgrueYnteHjEBOMwwi0w2iYFvOKLId34z8aF9I37WgzHqWH0We34P0nNDDDlTYwLQdN9AhzTByMBTlwDaD0NpbTM8NbByGkev4vrMBans+Bj14ANqVdSWn7dnYgUrh2b7n7w3qCnEAIAxsO3Q2DOpYEXZCUGHou6ano9ogJHiRaTqWE+6tXSfwQgyuZEG7YvUlBRNDxgBxwDmtsCcpNDvge55jBb7phHtjglIxaCuMosj3nB4oAAXgn7YfBq6tqR5AXTOIsAs9lu955t6CurblYB9iJYIvfUxwERGikes7Vh/RM22BaJsOmH1vJ/IiH9tOBKuAj+qIThSZoFobQtcB9bp9TMvDoBbb8wJ3/wD1IxdYtgITgi40+yFqOmLMc/0o9MOeDwm3wn5kwmxIKHsnBUhsGGImdELTjjZU6/sQ+h586i4tIC3Xg7D2HDeEfLIvJOQUH3wzCG3b9PuhYrkOuIkjfBYybi9SIHixHUEaggC19ob0YF1wIx/cEizbwwR3hUxumxHIb1q9nOBHkL1syHyBF/QT0a22AVA152eaLfgSKo96xKl8rsm08gZFkbZ1ShQ3SubLjarXrLzVVn68ldVYTDMEQQLvzCP4OO5xcYS+/z4ZNR21IMzoE7/IYvoEE4wEfY+sEfpzf05HvEpiOTK4kxIdfaMjNf9jcjveeNPC3Q52VJ2RRrVSa/RPIq+qlCdis7wW3TspjK7jV7NaLBN7483BDqgTtMoHgTJWrEgKW4fdCJ8ljYAoksVyWJyymomGiRsv6+7L4HdDdwJKmrEi7etG0QxOnxesLFu21RLt5i3fj8lPwHRcqm/jmrjjU4SV2irB1rnkJJtTNFujvKCcygMVeVYnQwolJSJcPjPgONEkVc9nMjBpLGOtv4NTnX/DhGjrNQO3wCc9cnFQdCls9roeb/U1APeis/YTAc6rcmns3KI0jDacjRS7z19lu9psNPtL/D9sYsCZfoadSXPcJU9a1dcNBckP5/W1GmwUUxXdocsFy97RklXFnMqTp9MSCC9iA6pIfe5SswyOWhVZg4OhRMTrS5iQlFStisFhM6PdOhmj7pikmSQd5ixlVXy1JMLpMeHg/hWpD8M0EeuYOY3/VZUcLalMECVr5YQYSbLmfLmZIAsRRCVbFCRfJvN+rDZvpZxt8Grb5IbNmdi6AXdX8pwbqzrY7oaPdLT6WP0zD/JkfOicpCxbJLyK6XgXAahmY1zfmfd4YXd3ygO+GSsTeyczUC+yMiU7Tzm3Sgqq+deWr5U7fukgY7TNQmNK7ciqY0M9u1Ir1x2fhsbzSHPDZq0ScgTdHWAihVDjd017Kl3cHBSLmQEbxDGCZhv+mMFIOwN81qF2nTSLTkY7ZtYV3XdWEUSDXrwxqwBnqERW2fB19f5og585WdGCYPH0Q49es15/oWGb/URl1F+KW4B3JFtQQ7Q/aGJie9yw9BcE+/sBi/ZZSRm7P+XSeNBhrowNy168Pv/l+uL6H83053pBzCBJFY+Qs7REBTmEFXq2WhbsEcm37fTBkyF5YaTui7TDoctkfo9Id8Zfl3L9dunT9wBtxHG2maU2/L+X0V7TRUFpaUws2IHaYvcKOyHkwP4lciLHBT1bplJsfavR7wgcU5z5tSNbbqVBb/hAe0belfHe0fTXOnGup7RGLzElJf+FFXz5Pr9mb5InGr8pwD9ajr7hkXMj+jc5dP4DwHYeO/9RWJN9wJr9RZWBVRuwd3Sh7p+0y6D/zbZOXpTv6uuaQe10+qV8O5hrPyvPwt/BjA9p18O97PCl6VamyY2bY7Gg2GX8Oitp8SDUpt8e3xwMKvbmQLIjOoVyXiQzPWU/kLSibcoeSjOYtjfEkvhoaHdyPkBT1+M9Jdh2ts9nf/BaW2d6WL7G08XtxSdd/b8Qa/sHDJ8SCzzwt55k9S17LUZy15Ggk5OTzZ9CaCV4++5elmFEIVReWMfaXKe7v9lnGXtzmV6xb1bSNHswPjiWHeKrZtbfklUOxUlstwyMDzmF1QnkwMNZNb+HBm1ell1786fmBxxaAykSyULeI00R9JDEcKFNav6bOOxmQ4mDFhHMP0Vu/nSkd2VFTIuJCvL+4PMWdJLlFdcZeKAFT+YknZA0WWRTseePU7qNOuEsnyK7h9wMzRjnbNUfraGPD3WFHcfJA0rik4GfH0HYkrKEkTtIqeKi/Obg1fEh0G9NFZYC1F+B85SsBdnSevWzeokxPj6Ex+GZ7Y9jWvsdq99VoZhwMpklmaBiOVc1p/dbHxWtUzQULgCn1unWVXrmMCyEXdL5/Yw9gZRyFSGlqAjwrANLst1FSM19n8fy91ffSYTvNFl+lD+d2rywrHPk12FsOwm9yNU5TEGlmtNnRrfRfwA) for an example. 

For future questions that are not bug report, feature requests, or enhancement requests, please post on our [community forum](https://community.cesium.com/) where there are engineers and users actively answering questions. Thank you!
