### ISSUE TITLE
Create Cesium3DTile yourself

### ISSUE THREAD

**Issue by mylove10086** [CesiumGS/cesium#9330]
I want to create Cesium3DTile myself, and then add it to the root.children array of the object created by Cesium3DTileset. Is it possible?
       In other words, I want to add a b3dm file to the created Cesium3DTileset object. Is there any good way to achieve it?
Add in this place below
tilesets.root.children.push(new Cesium3DTile())

**Comment by katSchmid** [comment]
You have to edit the tileset.json file, spec here https://github.com/CesiumGS/3d-tiles

**Comment by mylove10086** [comment]
Thank you very much for your answer to me, I have solved the problem。
Thank you very much for your answer, I have solved the problem.
I added the function to create Cesium3DTile in the Cesium3DTileset.js source code file, and then added it to tilesets.root.children.push(ts);.

ICesium3DTileset.prototype.addCesium3DTile = function (children, parentTile) {
   var childTile = new Cesium.Cesium3DTile(this, this.resource, children, this.parentTiles);
   return childTile;
};

  ts = tileset.addCesium3DTile(c);
       tilesets.root.children.push(ts);

**Comment by katSchmid** [comment]
next time you have questions maybe try  https://community.cesium.com/
