### ISSUE TITLE
Rendering polyline takes lot of time -- waits until workers are downloaded

### ISSUE THREAD

**Issue by ajinra020307** [CesiumGS/cesium#9333]
Iam using the latest cesium code, while trying to render a polyline it requests the server for workers and wait until it gets loaded to render the line. How can i solve/fix the issue?

**Comment by hpinkos** [comment]
Hello @ajinra020307, Cesium renders geometry like polylines in workers so the calculations don't tie up the main thread and stall your application.  I'm not sure why this would be running slowly, but feel free to open an issue on our community forum with more detail about your appliaction: https://community.cesium.com/
