### ISSUE TITLE
How to use mipmap in compressed texture

### ISSUE THREAD

**Issue by qwedsazh** [CesiumGS/cesium#9342]
How to use mipmap in compressed texture？

**Comment by qwedsazh** [comment]
If  use compressed texture in cesium,  can't use mipmap

**Comment by OmarShehata** [comment]
@qwedsazh how are you loading your textures? What formats are you using? If you're using [loadKTX](https://cesium.com/docs/cesiumjs-ref-doc/global.html?classFilter=loadK#loadKTX) notice that mipmaps are not yet supported. I think it wouldn't be difficult to add support for and we're happy to accept contributions.

I'm closing this issue but it would be great to hear more about your use case and what you're trying to accomplish in a new [thread on the Cesium community forum](https://community.cesium.com/).
