### ISSUE TITLE
can custom Fabric  use ArrayBufferView?

### ISSUE THREAD

**Issue by xduoo** [CesiumGS/cesium#9359]
can custom Fabric  use ArrayBufferView?
  //gridData 50*50
      let array = new Uint8Array(250)
      for (let i = 0; i < 250; i++) {
        let v = parseInt(Math.random() * 255)
        array[i] = v
      }
      console.log(array)
      return new Cesium.Appearance({
        material: new Cesium.Material({
          fabric: {
            uniforms: {
              speed: 0.1,
              **gridData: array,**
            },
            source: this.getMS(),
          },
        }),
        translucent: false, //
        renderState: {
          blending: Cesium.BlendingState.PRE_MULTIPLIED_ALPHA_BLEND, //
          depthTest: { enabled: true }, //
          depthMask: true, //
        },
        fragmentShaderSource: fragShader, //
        vertexShaderSource: vertexShader, //
      })

**Comment by dzungpng** [comment]
You can checkout the Fabric documentation for more information. Currently, according to the doc, uniform arrays are not supported yet but is on the roadmap.

Please use the Cesium community forum for general questions about using the library: https://community.cesium.com/.

**Comment by xduoo** [comment]
ok
thank you very mush！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CesiumGS/cesium"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CesiumGS/cesium] can custom Fabric  use ArrayBufferView? (#9359)





 
You can checkout the Fabric documentation for more information. Currently, according to the doc, uniform arrays are not supported yet but is on the roadmap.
 
Please use the Cesium community forum for general questions about using the library: https://community.cesium.com/.
