### ISSUE TITLE
Camera.twistLeft and Camera.twistRight don't trigger Camera.changed

### ISSUE THREAD

**Issue by easternmotors** [CesiumGS/cesium#9365]
I have been using `Camera.changed` when the position/orientation of the camera changes but it seems that both `Camera.twistLeft(amount)` and `Camera.twistRight(amount)` don't trigger an event (though it seems like it may rarely?).

The twist command doesn't change the position of the camera, only the orientation (from what I understand). Even though `Camera.changed` doesn't specifically mention if it only triggers on camera position change or both camera position and orientation change, `Shift + Click + Drag` (to my knowledge) only changes the camera orientation yet still triggers `Camera.changed`.

`Camera.twistLeft(amount)` and `Camera.twistRight(amount)` don't appear in the CHANGELOG but `Camera.changed` has been around for a while (Released as part of 1.23) so my thought was maybe it was introduced after the `Camera.changed` work was done?

Just wanted to verify this was a bug and not intended functionality.

Sandcastle example: https://sandcastle.cesium.com/#c=bVNBbtswEPzKQhcrQErJ11Y2mjoJUMBAgbjpSRdG3MiEKa5KUhLcon8vKSWOLVo3zszODJZizw30Egc0sAKNA2zQyq5hv0YsLZNqPG9IOy41mjK5+VLqUmcZ7NA5qWto0VTo6Ro3e65rFGAJNEFDPTaeALc3aPekhAVuEAz+7qRBMZrc6SNUvEHDP/Re2ynh4c4icFBUl3rqyCYpiyNXkJ/1gq6FzeQ6CWArrcPQf+ZUTfOMC/HQe8t3XZrewGoNf0sNUJG2pJD5IuniwlYswjb+nVayMcgdzqLvKifJ84PUggZm0X3XDk3P1XnIZS03+B5Pst67NGf5cky5hWWen6KeHnbP25+7z+NBER3uadDwCQYyB3sCt/jqInD0jdDn9gIKt/GNV4eBGxERUVYAH8lcFUcdAhh3COisgyHn1xmFTXBkO8Gx8YTPrMcFv1kIQqsXbmQ/yHejcza5TQrrjgrX4crC91U2LRn/wxmVMpY5bFrl02z20lUHdKyyNlxZkBbZ+WghZA9SrK68MKgUt9Yzr51SO/kHy2RdZF4fjSriwj/BHz0axY9Btl+utxPIGCsyf7w+6YjUCzcz5/8

Browser: Chrome 88, Firefox 82

Operating System: Windows 10

**Comment by malaretv** [comment]
I think this issue might need to be reopened, as above PR only seems to handle the case when camera is looking straight down. 

Looking at any view where the camera isn't looking straight down still shows no camera changes when twistLeft/Right are called. 

Example
https://sandcastle.cesium.com/#c=bVTRbtowFP2VK16aSq2JSQJJB2gd69RJSJtKuyde3PgWLIzNbIeITfv3OQlQIOUJn3PvOUf3Ot4yA1uBJRoYgcISJmhFsSa/aiyYd/L6PNHKMaHQzDvXn+YK9j3E5qiQ5GyNhpE3uXvWwd+KBuBonVDMCa3uToUnzDj/j6koaAoBbnuDMEpiSmKaxUk/S/s3Ryru9SntxyQb0HQQD2h0pKLUA7RPeskg6fdoL2qI632BNgJ95pb/IzIu1OKncPnySUt5TJGQLMm8TJRFSUqzE6fbkIQRjXyAfhbTHk3S9J30XPWLojAK4zSLe2kYR2E2OE/DC7OPEtbIv2qK3S7M0PkpLWCDJq/iLnCyZGqBHKwGpWGtt7j2BLilQbvUkltgBsHg70IY5LXIvdpBs4L3el9bSO7hwiIwkHoxV/ud7bfVthxB6FMdckGxgUmj2hTAVFiH1R24UMqbfsI4f9h6yUNdEFzDaAz1hci1sloi8UGCqzNZflXNoh5IbT0xyBxeWN/n1fTmqhSK65JYdN+VQ7Nl8tTkPJYrfY4nsVi6wC+J1i43QMPwaPX0MHuZPs/u6oPUevVVlwpuodRmZY/gFN9cC6x1W+jL5gyqtvGF5auSGd4iWl4V+E2bD4tbGSqwnaFCLzIY7T+CtlkDt2QbuC3c4BfS9YD3ElyjVVeuZt/Jg9Ap27npDK3bSRwfPqHPYr3Rxl84IwNCug7XG+ndbPe1yFfoSG5t8+gADLunrUMutiD46INXCnLJrPXMWyHlTPzBeWc87Pr6VqvU9YPwY4tGsl1VtqTjaQMSQoZdf/y402ktX5m5UP4P
