### ISSUE TITLE
Problem with CZML and Wall with minimumHeigths/maximumHeights

### ISSUE THREAD

**Issue by jsanchezfr** [CesiumGS/cesium#9374]
I have been testing in Sandcastle with “wall” and its property “minimumHeights”:
With “viewer.entities.add” it seems to work, but if I use it from a CZML, it doesn’t go (or I don’t set it right).
I’ve traced the code a bit and it seems that it doesn’t interpret it in “processArray” inside “cesium.js”.

Sandcastle example:
[Sandcastle](https://sandcastle.cesium.com/#c=nZRdb9owFIb/ipWrIGUmkBAYpdU2Om2VOnVap1Ua4cJNToNVx0a2A4KK/z7nm68Kab4gsf2+x855DmdFJFpRWINE14jDGk1B0SzFf4o1O7SiYj4VXBPKQYZW5yrkIV8ZX7RNmXHNQo7QW/6DEI3HKLRiEWUpcB1aTrnMSQr5xvTvj3v0DUQKWlJQY/RTsE0ieCNcgVRU8Fzbw261vHPQ4RGh5ZstdBj7SQqeNIHWhLFx+Vr5EFILsR4jLTNw6qWlUFSbA9X4DUVEapFIslzQ6BYSCaDQeIaaUXvy8aGH+wPPdXwfB6PAc1Dguth1jiXeaNRI+u5Zie9/LCRBf+gMzioGXhnEGwXvKALXKxT9oe8E78Q4vut8X1KOXWNLKadpln4Hmiy0wTTLY6Je+QWof/DwyodfBHX2MrXb1bOQz5uikRA/GTambsqyw6ZODAJQmMSxXbCqiT68VjgLmDXHE4otw7p4p4akeSPcwy9SpBXMz1KSTfVJ9uw4Q8PLNAeXaQYXaQ4v0hxdpHl611Ix71TS/+dX+YkGSQlrMyqYkPjX19vqDxnyXdsHYqLJo8hkBIc9ZGr6w22zZ+eGVoqZILGdt5AO1gvg9kvGoxyj3SlJV+XROsoKaed5vEa2FSL9LfZ227pKQH/Z3MV20TU6nau8IqvbW441UXrD4KZO8SeaLoXUKJPMxrirIV0ykwzVfc6iV9A4Uqo8F6FJd986ienK9KbrMx0TRYwoZXZeMsYe6RZC62bSNfoTa54TypMH0wYZ2eSyRe/mvlzEGE+6ZnreqYVgz0QeRf4H)
Browser:
Chromium / Firefox
Operating System:
Windows 10

**Comment by shunter** [comment]
`minimumHeights` and `maximumHeights` must be specified in CZML like:

```json
"minimumHeights": {
  "array":  [0.0, 1000.0, 200.0, 200.0, 300.0, 400.0],     
}
```

because they can be specified either as a list of double values or as a list of references.

See https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Wall and https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/DoubleList
