### ISSUE TITLE
Unable to unset image uniform for Material

### ISSUE THREAD

**Issue by nmschulte-aviture** [CesiumGS/cesium#9385]
It seems not possible to "unset" the `image` uniform for a `Material`.

Just as I can create a `Material` with `image: undefined`, I expect I can set `image = undefined` to achieve the same state.
However, it seems setting `image = Cesium.Material.DefaultImageId` (`'czm_defaultImage'`) does not work _either_; nothing can achieve this, the only work-around is to create a new `Material` (and destroy the old one).

See the following demo ([paste into Sandcastle](https://sandcastle.cesium.com/)):

```javascript
var viewer = new Cesium.Viewer("cesiumContainer");
var scene = viewer.scene;
var rectangle = scene.primitives.add(
  new Cesium.Primitive({
    geometryInstances: new Cesium.GeometryInstance({
      geometry: new Cesium.RectangleGeometry({
        rectangle: Cesium.Rectangle.fromDegrees(
          -120.0,
          20.0,
          -60.0,
          40.0
        ),
        vertexFormat: Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT,
      }),
    }),
    appearance: new Cesium.MaterialAppearance({
      flat: true,
      material: Cesium.Material.fromType(Cesium.Material.ImageType, {
        // image: '../images/Cesium_Logo_Color.jpg',
        // image: '../images/checkerboard.png',
        image: undefined,
        color: Cesium.Color.RED.withAlpha(0.5),
      }),
    }),
  })
);

Sandcastle.addToolbarButton('"Cesium_Logo_Color.jpg"', function() {
  rectangle.appearance.material.uniforms.image = '../images/Cesium_Logo_Color.jpg';
});
Sandcastle.addToolbarButton('undefined', function() {
  rectangle.appearance.material.uniforms.image = undefined;
});
Sandcastle.addToolbarButton('Cesium.Material.DefaultImageId', function() {
  rectangle.appearance.material.uniforms.image = Cesium.Material.DefaultImageId;
});
Sandcastle.addToolbarButton('"czm_defaultImage"', function() {
  rectangle.appearance.material.uniforms.image = 'czm_defaultImage';
});
Sandcastle.addToolbarButton('""', function() {
  rectangle.appearance.material.uniforms.image = '';
});
Sandcastle.addToolbarButton('"does_not_exist"', function() {
  rectangle.appearance.material.uniforms.image = 'does_not_exist';
});
Sandcastle.addToolbarButton('"checkerboard.png"', function() {
  rectangle.appearance.material.uniforms.image = '../images/checkerboard.png';
});
```

**Comment by dzungpng** [comment]
I can confirm that this is the current behavior. It would make more sense if setting `image` to undefined removes the previous image from the geometry.

I made this Sandcastle which could be a potential workaround: [link](https://sandcastle.cesium.com/#c=dVRbb9owFP4rFi8kEjWh2vZAKRoDOiG16gSo2kMk5CYnwZtjR7YDYxP/fbbTXAjtE/H5Lnzn5DghPxCJDhSOINE94nBEc1C0yPCLq3lhL3LnueCaUA4y7Pl3oVOpCDgYUanG7migEqQZSeHNcWWfvVEQDNBtEFi5Q7GSkWH0MR66sxqWf717FKnYzQUTEv/K0/6l5zLL9elD45IoIdKEp8wGcLFwLmlGNT2AwiSOvZCjdq8/KtT7ZxGEUhAZaHlacWWMzATGbfr3DlqpGt0FfV2lqXQNHzVRx1d0nEiRLSCVAMprFAjdjG4DHAzapavCzZdu5ZMpNGe/hR1AavjzIGRGdB1jyRjNlaDxppAJiWCW50CkbRe/LNfb5c/dw/P6abatfc6VZf1AasnFPJ6IBkkJaxybgSTMRtCygNo3e6OPu3o3n+0pB68LuL2wyAC1Ru3WZ1z+tLqP7KLV5uXarZcLfKR6P2P5nngB/ux/2ObZD3m5eRvC44gobd6c2bGtEOyVyG+F1oJ7/W7EBSSkYNolXcX9AUoKHmlqqH6ZuV4M3IwRV7PABaeJeV8KV/esuRsmy9m/6w16E6VPDKZV8K80y4XUqJDMM1dOQ5abYZtb91pEv0HjSCnbh6VOhm3pJKYHROP7dz4FKGJEKYMkBWMb+hfC3nQyNPwrKRMkpjx9NrvGyMnS9qPpY1nEGE+G5vi+UpeD7Dj/Bw). Although it also removes the base color of the geometry and setting base color to RED again does not seem to have an effect. I tried setting `requestRenderMode = true` and call [`requestRender`](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html#requestRender) after setting the image to `undefined` but that did not help. 

This might be related to an older issue here: https://github.com/CesiumGS/cesium/issues/5080
