### ISSUE TITLE
Half of the earth 

### ISSUE THREAD

**Issue by VINOlive** [CesiumGS/cesium#9386]
Sorry the community is too slowly to open.
My project is rely on the terrain,
but I use terrainProvider.readyPromise.then(function(value){console.log(value)}),
also cann't solve the problem like below picture.
Any help, thank you.

Cesium Version 1.78
![111](https://user-images.githubusercontent.com/7323049/108683124-271aa300-752c-11eb-91b3-2fa907389669.png)

**Comment by gaowqspace** [comment]
I meet the same question. Have you fix it?
