### ISSUE TITLE
Camera.changed event not firing when camera.roll equals 0

### ISSUE THREAD

**Issue by TJPovey** [CesiumGS/cesium#9403]
When camera.roll = 0, the camera.changed event doesn't fire when changes only occur to the heading. e.g. if the user is looking down and rotates the camera. This causes issues with our compass not updating.

Sandcastle example:

Try the rotate buttons in the sandcastle below, you'll see that the camera.changed event is fired only when the roll =/= 0:
[Sandcastle](https://sandcastle.cesium.com/#c=zVVNbxoxEP0rIy7dVZYFDj0UCGqLUqVSolYEtVK1F+MdWAtjI9tAaZX/3vHaJNBAo0SK0tt6Pt68Gb8dr5mBtcANGjgHhRsYohWrRf6ttiVFg9fnoVaOCYWmaKS9QhWKa2UdcLZAwygzQOThTAHhI1+i4UiZMxxWTM2wpNB23n5bQ7Ra8F1ICUo7mAqDsKlQwUiTSVhoF0qiAycWaD+Rt04NpQM2D4g5K8uLNRW5Etah8pwVQBIrx7IpnA/gt3fAHuLZWS+YSs1XC4rOZ+guJPrPj9vPJXXveZXUcy4UQV+Or6+Ixj3Co/kVslKo2d8IsYXofRRlKRyvTmDUvkcRDE31BIB31fm3hUp3FzNC64df4X4UOA1tKNQ/yvg0X+fhpTS4FHxeNDJI7m8jglOS11sSb2iprXBCq+5dj9GQQQjQRnhVhZg90V6GeX71I/E6StrZznXNXJU7PaIApmzSfNdOM2indd9pj3Bv0wNR1oI8VBqg7wi0ktsgVROkqt44r9bTU5E4fcZQpnI71ruRlGidUOz4VJ44lEPxQRM62YGYsv07T7M4ohedkBGz6j8e0dkTR9TIGn3rthIHoS7Ae7FYauNgZWSS5y2Hi6VkDm1rsuJzdDm3No0/cb+1n9ovxRpEeX5kEQOXzFryTFdS3ohfWDQG/RbFP0iVuu7jyxqNZFsfVnUGV8GY53m/RcfjmU5rOWFU7K6T2lczJPeE8fnM6JUqm1xLbbowkWTqwZRoNi1x6kLH4KIHE21KJH9n+ROslqIkgQiHPUIe+3UK9T7twq7MPom4hA8o+jkdnibmBTlGhRznd7fkX5NhLd7j/OLz8Zrs/F91nFx4mZ7AbbJyTquYHN6bwQ09VqP4Qv1AoymjjjoBcRIvbGpiS0sCYSg1n2+ExefCxbW2w/ugnGieAt1v+Q8)

Rotating with the middle mouse button will cause the changed event not to be fired, as expected. The rotate buttons are there for convenience. 

Assuming this is related to #9365

Browser:
Chrome: Version 88.0.4324.190

Operating System:
Windows 10
Version: 1803
OS build: 17134.1304

Thanks,
Tom

**Comment by Lkkkk520** [comment]
i think what you say is right
