### ISSUE TITLE
Cesium will crash when use Cesium3DTileStyle but not write all the cases

### ISSUE THREAD

**Issue by Anigod** [CesiumGS/cesium#9418]
![image](https://user-images.githubusercontent.com/12766336/110407109-45e96f80-80be-11eb-92a1-2612b6ef7caa.png)

When we were using Cesium3DTileStyle, we only wanted to change the color of some objects, but it crashed. After looking at the source code, we found that we need to write all the cases and the default is white, maybe it is better to adjust this to add the default handling here

![image](https://user-images.githubusercontent.com/12766336/110407134-54378b80-80be-11eb-8cb9-9fa9646980e1.png)

**Comment by dzungpng** [comment]
@Anigod Thank you for the suggestion. As you mentioned, it might be helpful to add a default `true` condition to avoid the error, although it could confuse users where the default color comes from. It might be better to document this behavior (I couldn't find it written down in the [API reference](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileStyle.html) or the [3D Tiles Styling guide](https://github.com/CesiumGS/3d-tiles/tree/master/specification/Styling)).

**Comment by Anigod** [comment]
> @Anigod Thank you for the suggestion. As you mentioned, it might be helpful to add a default `true` condition to avoid the error, although it could confuse users where the default color comes from. It might be better to document this behavior (I couldn't find it written down in the [API reference](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileStyle.html) or the [3D Tiles Styling guide](https://github.com/CesiumGS/3d-tiles/tree/master/specification/Styling)).

@dzungpng Thank you for your reply.

I've looked at the source code and the default color is white. This won't cause any unintended changes, but it's probably important to note it in the documentation as well. Maybe I can add a note in the documentation as well as the default white to avoid errors.

**Comment by Anigod** [comment]
@dzungpng Thank you for your reply.

I've looked at the source code and the default color is white. This won't cause any unintended changes, but it's probably important to note it in the documentation as well. Maybe I can add a note in the documentation as well as the default white to avoid errors.
