### ISSUE TITLE
Support of BIL images as TerrainProvider ?

### ISSUE THREAD

**Issue by gribouille139** [CesiumGS/cesium#9426]
Hye, 
In France, a public service called Geoportail use WMS flux provided by IGN. Requests are in this format : 
`https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?LAYER=ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES&FORMAT=image/x-bil;bits=32&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=WGS84G&TILEMATRIX=12&TILEROW=1012&TILECOL=4228`
![image](https://user-images.githubusercontent.com/73525724/110936537-55242380-8331-11eb-9ab9-16a967349ac5.png)

I would like to use this flux as as CesiumTerrainProvider in CesiumJS. 

I tried with https://github.com/kaktus40/Cesium-GeoserverTerrainProvider with no result... 

Any idea please ...?

**Comment by dzungpng** [comment]
For questions like this one, please post on the [Cesium Community Forum](https://community.cesium.com/), where our engineers and community members can help answer. We limit Github postings to feature requests and bug reports. Thank you!
