### ISSUE TITLE
Entity Polygon update position flickering

### ISSUE THREAD

**Issue by fbeqirllari** [CesiumGS/cesium#9437]
Updating polygon positions on Entity is flickering.

[Sandcastle](https://sandcastle.cesium.com/index.html#c=jVRRb5swEP4rFi8BlRhIy9QlabWqndRJk1Yt0l5CNblwDdaMHdkmCZvy33cYEtJsmuYX++78fXe+j2PDNNlw2IImN0TCltyD4XVFvzmfP8qdea+kZVyCHgWzTGZyg6iCWbZQtc7hLfK+NlZVD8eoP3pSolkpaRy4S0YHtKGsKPzBHjKAtNw2yD4EqfPxHvQrk6RfklUwJSMLxo7CwW1KtSVTYnUNzlupAsSUHIG15lOSeZRGC1atBbRlR+6Sibr33HHdn77jka7ES+YdE1Rc8qqunvgOxIL/xAqSyfUQZbs2usiZwMgkxtXH9iclrrvukJOq2gU7LLqA4hH4qrTTZBKeRgkpOWim87I5wx1IDbYJez49ysI0NoczeUlfNeoDKw1g7rRmjb8cJ8lVmL4Lx0n8vtuThKZhepnJ5yA8p9+feSpmQXMmyJBMCaXp148PdMtteSfWJfNjmgYDbt83wn0SqPUOZZ7EvdFqPk6cmUkD9pPEBBsm/Nda5u2z/KB7846Mb0g6c+eGXCDFjLSYlrolYhoYci1jckGakKQJ7jvc35oTmvYXrq5bz3NHSHLsnxJAhVr5LZMrv/so6aHByP7PBjvgMn4OXS3LBA/xWx6nPj3KeTZMWIJl0j5ptQZtG/8k1o/V4wHp/4fS7hlB0IuQyX1ILvGzDGZe6M2NbQTcHjT6wKu10hZHRPg4HxZwPlBoE73U+Q+wNDcm6Bs1j06h84JvCC9uMu/s55F5JBfMGIy81sINTObdziO8/wdUKFZwufqyAS1Y014rk9vPnZNSOo/Q/DvSKiVemD5j/g0)

**Comment by bucibucii** [comment]
// This is an example of using Cesium "Offline", meaning disconnected from the
// external Internet.  It must still be served from a local web server, but
// does not rely on any outside resources or services.  For more info, see:
// https://github.com/CesiumGS/cesium/wiki/Offline-Guide
var viewer = new Cesium.Viewer("cesiumContainer", {
    imageryProvider: new Cesium.TileMapServiceImageryProvider({
        url: Cesium.buildModuleUrl("Assets/Textures/NaturalEarthII"),
    }),
    baseLayerPicker: false,
    geocoder: false,
});
var i = 0;
var b = [{
    lon: 4.25832182,
    lat: 51.28233363,
    alt: 0
}, {
    lon: 4.25824362,
    lat: 51.2823683,
    alt: 0
}]

var c = [
  [4.25827565, 51.28237055, 4.25839278, 51.28231875, 4.258368, 51.28229672, 4.25825087, 51.28234852, 4.25827565, 51.28237055],
[4.25819675, 51.28240487, 4.25831485, 51.28235395, 4.2582905, 51.28233173, 4.25817238, 51.28238265, 4.25819675, 51.28240487]]

var entity = viewer.entities.add({
    model: {
        uri: "../SampleData/models/GroundVehicle/GroundVehicle.glb",
    },
    position: new Cesium.Cartesian3.fromDegrees(b[i].lon, b[i].lat, b[i].alt)
})

var polygon = viewer.entities.add({
  height: 0,
    polygon: {
          hierarchy: new Cesium.CallbackProperty(
            () =>
              new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray(c[i])),
            true
          ),
          material: Cesium.Color.RED,
          //heightReference: Cesium.HeightReference.RELATIVE_TO_GROUND,
          extrudedHeight: 2.0,
        }
})


setInterval(function() {
    if (i < b.length) {
        entity.position = new Cesium.Cartesian3.fromDegrees(b[i].lon, b[i].lat, b[i].alt)
     polygon.polygon.hierarchy =  new Cesium.PolygonHierarchy(Cesium.Cartesian3.fromDegreesArray(c[i]));
      
        i += 1;
    } else {
        i = 0
    }
}, 1000);

viewer.zoomTo(viewer.entities);

**Comment by dzungpng** [comment]
@bucibucii I looked at the example you provided and did not spot any flickering (there is a very quick flicker when the polygon's position is updated but this is expected due to rendering update). Can you describe a bit more in details what kind of flickering you are experiencing and how to reproduce it (any videos would be helpful as well)?

**Comment by bucibucii** [comment]
> @bucibucii I looked at the example you provided and did not spot any flickering (there is a very quick flicker when the polygon's position is updated but this is expected due to rendering update). Can you describe a bit more in details what kind of flickering you are experiencing and how to reproduce it (any videos would be helpful as well)? 

    There is a small flickering yes but if you update that every seconds it gives a bad view for the eyes, i don't if there is any other option to do it. I tried with Callback works fine but with 200 entities kills my gpu![ezgif-6-7f52358dbc65.gif](https://user-images.githubusercontent.com/2406460/115950590-735a7300-a4dc-11eb-81f5-cafa6386c117.gif)

I have 200 entities updating positions every 1 seconds. Is it better to use primitives or entities?

**Comment by bucibucii** [comment]
https://user-images.githubusercontent.com/2406460/115955659-32705780-a4f8-11eb-8057-635ab9fd030d.mp4
