### ISSUE TITLE
Pixelated Text when using Label

### ISSUE THREAD

**Issue by JakeG-9191** [CesiumGS/cesium#9444]
Issue: See the attached screenshot for example of issue that some team members are encountering, which are the dark pixels surrounding the label text. I have NOT been able to recreate this issue, but have been notified that multiple team members are encountering this issue both in development and in production. For some, it appears to be a consistent issue, for others, it is more random and only happens from time to time. 

We are using a label to add fillColor as well as text to each of these objects, and the pixelation appears to be an issue no matter how near or far the user is zoomed. Any thoughts on what the issue is / some potential solutions are greatly appreciated.

Sandcastle example: N/A

Browser: Chrome 89.0.4389.90

Operating System: Mac OS | Big Sur 11.2.3

<img width="800" alt="Screen Shot 2021-03-22 at 16 28 43" src="https://user-images.githubusercontent.com/53546048/112225482-7ec33180-8bf2-11eb-8037-5dff5d9b33c9.png">

**Comment by dzungpng** [comment]
There is some discussion here regarding image scaling which you may find relevant: https://github.com/CesiumGS/cesium/issues/7875. 

In particular, setting `viewer.resolutionScale = window.devicePixelRatio` can help with the pixelation. I created an example here:
[Sandcastle link.](https://sandcastle.cesium.com/#c=dVNbb9owFP4rRzyBFJw45AKMoqnZKk2i6jSmPYzw4MQGrDo2cxxomfrf5wRIqWAvTvJdzs0nO6IhPxQC7mCRSoC/9QHA6RjSDlV5VTBp0o5zhCUpWE3ck5LnkPx+nEHGhcgU0RSIpCBIxkQr3zFdciVrB0beCX5zrvKUqmD9SvI/FetzepUtYSWvihZucozPEQBWtoJECaUvMAC9zsgYFn4YOvDhWDpn0Vv7tlLSNFX6WwOzKueUQKJkqQRr0wJslOYHqyTiSfM1b/qafX34eSEpzatoan74Nptd4Ia9mButWMNG7e9J/rzWqpJ2GEZXrCWzlvhvfxj7DgxHDoSx7c7zrrs7P7eq5Ka5jTZKTrSxBRGLLd4jYx9HgwijwBtFoyDGOHbeyX4QDyI/HCAch4PADzG+IANviP0oRsEwCqMo9kZBSy4/VFOfy0+pTOXO7t+Osz3TdgMl28NxQuhXg3XTTt58J/XYuWQ67fSs7+hAlBgyV5W2GkQo7Z68id3nLy2FhCK0W+94r9ekdN2TXTN7wVU9k3lOBLMF7Lmkao8o2/GcfecvTPwglm9sHaczaa53eu7pMy+2ShuotOgi5BpWbAWxA3WzKn9mBuVlWWespRP30jqhfGdX/+5Gd5ALUpaWWVVCzPnB7t904lr9lbVui8v1k/3JBHmtZRs8nR1BhNDEtZ+3nUYpkRF9Efmo+Ac)

Without `viewer.resolutionScale = window.devicePixelRatio`:
![image](https://user-images.githubusercontent.com/38567338/116898460-663c3300-ac04-11eb-8b54-822887552cfb.png)


With the above set: 
![image](https://user-images.githubusercontent.com/38567338/116898409-56245380-ac04-11eb-85e0-0fb552c9a75b.png)

**Comment by lilleyse** [comment]
`viewer.useBrowserRecommendedResolution = false` is another way of telling CesiumJS to render at the screen's native resolution.

**Comment by ggetz** [comment]
I think this is the same issue already documented in https://github.com/CesiumGS/cesium/issues/4235. I'm going to close this issue to keep the discussion in one place. If you have any further input on this, please post it there instead.
