### ISSUE TITLE
STK CZML Exporter

### ISSUE THREAD

**Issue by Rookiemin** [CesiumGS/cesium#9446]
Can STK export the ground track into CAML file and load it into Cesium?

**Comment by GatorScott** [comment]
The capabilities of the STK CZML exporter are described [here](https://help.agi.com/stk/12.2.0/index.htm#czmlExport.htm?Highlight=czml).

**Comment by dzungpng** [comment]
In the future for questions about the API or third party libraries related to Cesium platform, please post on the [Community Forum](https://community.cesium.com/). We use Github for bug report, feature request, and roadmap questions. Thank you!
