### ISSUE TITLE
Artifacts with globe translucency and globe interior

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#9461]
https://sandcastle.cesium.com/?src=Globe%20Interior.html&label=All

The ellipsoid representing the mantle shows through the back side of the globe at certain camera angles.  It was unclear if this is related to the other issues we have open about globe translucency.

![image](https://user-images.githubusercontent.com/3451886/113329258-58d11780-92eb-11eb-85cd-7587053641e1.png)

**Comment by lilleyse** [comment]
I think this is just the red ellipsoid being too big and extending outside of the low LOD terrain tiles. Not a globe translucency bug. Fix here: https://github.com/CesiumGS/cesium/pull/9463
