### ISSUE TITLE
Broken TS definition comments [1.80.0]

### ISSUE THREAD

**Issue by turansky** [CesiumGS/cesium#9465]
All multiline examples and parameter descriptions are broken

Left - `1.79.1`
Right - `1.80.0`

<img width="1440" alt="Screenshot 2021-04-05 at 02 26 19" src="https://user-images.githubusercontent.com/9942723/113524346-b8167c80-95b6-11eb-9c75-c9568ef5f8e5.png">

**Comment by turansky** [comment]
@hpinkos Problem is common, all multiline examples and parameter descriptions are broken

**Comment by mramato** [comment]
My shot in the dark is that something changed in jsDoc or the library we use with it to generate TS definitions.  I tagged this next release so we figure it out (Even if it's by temporarily pinning to an older version of a library if that is indeed the case)

**Comment by mramato** [comment]
I can't reproduce this.  So it either was a third party library issue which was fixed for us or whomever built 1.80.0 had something go wonky (was that you @hpinkos?).  I'm more likely to believe the third party answer.

![image](https://user-images.githubusercontent.com/1495196/116762248-d5890b80-a9e7-11eb-9504-2f29a755e589.png)

I'm actually handling Monday's release, so I'll be sure to do a double check as part of that process.

**Comment by turansky** [comment]
Is new line required after `}`?

```
}

/**
```
instead of
```
}/**
```

<img width="345" alt="Screen Shot 2021-05-01 at 2 58 28 AM" src="https://user-images.githubusercontent.com/9942723/116764227-1d7c5280-aa29-11eb-924c-c20b38f9f946.png">

**Comment by mramato** [comment]
> Is new line required after `}`?

I noticed that and said to myself "I can't see why that would matter" and got lazy.  Since you also noticed and asked, I ran a small test locally and sure enough it appears that it does matter and it was preventing this particular class from having it's documentation picked up.

Going to open a fix now.  Thanks for helping me not be lazy. :smile:

**Comment by mramato** [comment]
@turansky I opened #9522 which will go out in tomorrow's release.

**Comment by turansky** [comment]
More issues were detected during [cesium-kotlin](https://github.com/turansky/cesium-kotlin) development.

WA for #9522 - [here](https://github.com/turansky/cesium-kotlin/blob/6eeacf090e2a2b35a955aae58c295ba509388cf1/buildSrc/src/main/kotlin/com/github/turansky/cesium/Declarations.kt#L130)

"Missed parent" - main problem
