### ISSUE TITLE
Erros during Build Process

### ISSUE THREAD

**Issue by ManChrys** [CesiumGS/cesium#9467]
Hello guys,

i git clone the repo and after that i tried to build it, but i had some errors. More specifically :

1)git clone repo
2)cd to repo's folder
3)run npm install

![Screenshot from 2021-04-06 12-49-04](https://user-images.githubusercontent.com/67521662/113692871-ad530900-96d6-11eb-9299-6f889fe06e2f.png)

Log file

[2021-04-06T09_41_42_038Z-debug.log](https://github.com/CesiumGS/cesium/files/6263723/2021-04-06T09_41_42_038Z-debug.log)

### **EDIT**
after i install rollup ( npm install --global rollup ) and run npm install --legacy-peer-deps

i had the following Warnings

![Screenshot from 2021-04-06 14-52-46](https://user-images.githubusercontent.com/67521662/113707100-17c07500-96e8-11eb-8c9a-d5c4e2b72c01.png)

If someone can help me i'll appreciate it.

Thanks in advance.

**Comment by bampakoa** [comment]
@ManChrys  warnings in the second screenshot are not something that you should be aware of. It may be from another package down the dependency tree that is used from cesium.

However, the first error that you got is a bit strange because cesium does not require `rollup` to be globally installed. Could you please make sure that you close cesium in an empty directory? (One that does not have a `node_modules` folder in it)

**Comment by ManChrys** [comment]
Hello my friend and thank you for the fast response.

I  tried your solution and i think everything its ok. Im i right ?

geo@geo-X570-GAMING-X:~/cesium$ npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 914 packages, and audited 915 packages in 36s

59 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
geo@geo-X570-GAMING-X:~/cesium$ npm run build

> cesium@1.80.0 build
> gulp build

[11:03:14] Using gulpfile ~/cesium/gulpfile.cjs
[11:03:14] Starting 'build'...
[11:03:17] Finished 'build' after 3.09 s
geo@geo-X570-GAMING-X:~/cesium$ npm start

> cesium@1.80.0 start
> node server.cjs

Cesium development server running locally.  Connect to http://localhost:8080/

**Comment by bampakoa** [comment]
@ManChrys  to access the built version, you need to use the `npm run buildApps` script (Check out [here ](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md) for more details on how to build the code).
In your case, I think that selecting the **Cesium Viewer** option (next to the built version) should suffice.

**Comment by dzungpng** [comment]
Closing this issue as the original question seems to have been resolved. @ManChrys Please feel free to follow up if it requires further discussion. Thanks @bampakoa for your inputs!

**Comment by ManChrys** [comment]
@bampakoa thank you a lot for your help!! ✌️✌️

**Comment by e3dio** [comment]
Please re-open this issue, am getting the same `npm install` error, master cloned to empty directory

> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cesium@1.82.1
npm ERR! Found: rollup@2.51.1
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^2.22.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-uglify@6.0.4
npm ERR! node_modules/rollup-plugin-uglify
npm ERR!   dev rollup-plugin-uglify@"^6.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by hst-m** [comment]
There are 2 issues open for this same problem library `rollup-plugin-uglify`:

https://github.com/CesiumGS/cesium/issues/9129 npm reports security vulnerability in rollup-plugin-uglify -> serialize-javascript
https://github.com/CesiumGS/cesium/pull/9214 switch to using terser plugin instead of uglify
