### ISSUE TITLE
Replace third party libraries with npm modules

### ISSUE THREAD

**Issue by ebogo1** [CesiumGS/cesium#9473]
This issue will serve as a task list for replacing third party modules with npm modules. Here is the task list (incomplete for now; I'll be updating this as we go).

- [x] Create staging branch for npm changes - https://github.com/CesiumGS/cesium/tree/npm-third-party-staging
- [x] Merge first pass PR into staging (https://github.com/CesiumGS/cesium/pull/9466/)
- [x] Move to npm; or other - see https://github.com/CesiumGS/engineering/issues/69#issue-834201104)
    - [x] `sprintf` (https://github.com/CesiumGS/cesium/pull/9476)
    - [x] bitmap-sdf.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [ ] ~google-earth-dbroot-parser.js~ leaving in ThirdParty, at least for now
    - [x] graphmesplitter.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [x] jsep.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [ ] ~knockout-3.5.1.js, knockout-es5.js, knockout.js~ (need longer term plan to get rid of knockout)
    - [x] LercDecode.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [x] measureText.js (https://github.com/CesiumGS/cesium/pull/9765)
    - [x] mersenne-twister.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [x] NoSleep.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [x] pako_inflate.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [x] protobuf-minimal.js (https://github.com/CesiumGS/cesium/pull/9747)
    - [x] purify.js (https://github.com/CesiumGS/cesium/pull/9688)
    - [x] Uri.js (https://github.com/CesiumGS/cesium/pull/9740)
    - [x] zip.js (https://github.com/CesiumGS/cesium/pull/9696)
- [ ] Other files in Source/ThirdParty:
    - [x] GltfPipeline (https://github.com/CesiumGS/cesium/pull/9699)
        - [x] Follow-up to update instructions in https://github.com/CesiumGS/gltf-pipeline README.md
    - [ ] Basis: Workers/basis_transcoder.js & basis_transcoder.wasm
    - [x] Draco: Workers/draco_decoder.js, Workers/draco_wasm_wrapper.js, & draco_decoder.wasm (https://github.com/CesiumGS/cesium/pull/9778)
    - [x] FXAA3_11 in Source/ThirdParty/ Shaders/ (https://github.com/CesiumGS/cesium/pull/9704)
    - [x] Source/ThirdParty/Workers/inflate + deflate.js (https://github.com/CesiumGS/cesium/pull/9696)
- [x] compare built CesiumJS sizes: .zip went from 63.6 MB to 64.0 MB, .tgz went from 21.4 MB to 21.9 MB as of 038f732 in `npm-third-party-staging`
- [x] rename ThirdPartyNpm to ThirdParty (https://github.com/CesiumGS/cesium/pull/9705)
- [x] test branch in cesium-analytics (needed a one-line change to update a `when` import), gltf-pipeline, swayze, and obj2gltf
- [x] update CHANGES.md (IE11 dropped, started moving third parties to npm)

**Comment by mramato** [comment]
`cesiumWorkerBootstrapper.js` also has an entire copy of RequireJS in it because we needed to be able to load modules in a worked.  We'll have to investigate if there is an alternative solution or (worst case) generate this file as part of the build step.

**Comment by lilleyse** [comment]
@ebogo1 https://www.npmjs.com/package/ktx-parse should be added after https://github.com/CesiumGS/cesium/pull/9513 is merged

**Comment by lilleyse** [comment]
Just checking, does this task list account for third party libraries in `cesium/ThirdParty` and `cesium/Sandcastle/ThirdParty`?

**Comment by ebogo1** [comment]
By `Cesium/ThirdParty/` do you mean `codemirror-5.52.0`, `dojo-release-1.10.4`, `jasmine-2.20`, and `jslint-2.11.0`? As for the ones in Sandcastle, I'm not sure what the plan is for those; I had a comment about it in the original post of #9688.

**Comment by lilleyse** [comment]
One more late breaking third party library to account for - meshopt. Added in https://github.com/CesiumGS/cesium/pull/9694.

`Source/ThirdParty/meshopt_decode.js`

Here's the npm library that we should try using instead: https://www.npmjs.com/package/meshoptimizer

**Comment by ggetz** [comment]
Closing, as the original scope of this issue has been covered. Knockout.js, workers, and Sandcastle dependencies  will be a separate effort.
