### ISSUE TITLE
Will have a plugin for babylon and cesium

### ISSUE THREAD

**Issue by DeZhao-Zhang** [CesiumGS/cesium#9474]
Now we can add cesium in ue4 by using cesium for unreal, but this will use ue4 to show the scene and in the desktop.Will we have a plugin to add babylon in cesium,so that we can use the rendering ability of babylon and also show in the web?

**Comment by ggetz** [comment]
Hi @DeZhao-Zhang. Thanks for the interest, but there are no plans to integrate with Babylon.
