### ISSUE TITLE
Hello, I cannot set the material of the picture for the cylindrical primitive 

### ISSUE THREAD

**Issue by kk1625846601** [CesiumGS/cesium#9487]
Hello, I have encountered a problem, the content is: I want to make the radius of a cylinder change dynamically. I inherited and rewritten the primitive update method, and it succeeded. But a new problem occurred: the picture material I posted on the cylinder could not be displayed normally. I don't know why, please help me find the reason, thank you very much. The code content is as follows: 
function changeCylinderPrimitive(options) {
	this.length = options.length;
	this.topRadius = options.topRadius;
	this.bottomRadius = options.bottomRadius;
}
changeCylinderPrimitive.prototype.getGeometry = function () {
	return new Cesium.CylinderGeometry({
	        length: this.length,
	        topRadius: this.topRadius,
	        bottomRadius: this.bottomRadius
        });
};
changeCylinderPrimitive.prototype.update = function (frameState) {
	var geometry = this.getGeometry();
	if (!geometry) {
		return;
	}		 
	this._primitive = new Cesium.Primitive({
	        geometryInstances: new Cesium.GeometryInstance({
		        geometry: geometry,
	        }),
	        releaseGeometryInstances: false,
	        modelMatrix: Cesium.Transforms.eastNorthUpToFixedFrame(Cesium.Cartesian3.fromDegrees(-90,20,500)),
	        appearance: new Cesium.MaterialAppearance({
		        material: new Cesium.Material({
			        fabric: {
				        type: 'Image',
				        uniforms: {
					        image: './data/circle.png',
				        },
			        }
		        }),
		        faceForward: true
	        })
        });
	var primitive=this._primitive
        primitive.update(frameState);
};

var pr=new changeCylinderPrimitive({
        length: 500,
        topRadius: 1000,
        bottomRadius: 1000
})
viewer.scene.primitives.add(pr)

**Comment by ebogo1** [comment]
Hi @kk1625846601, thanks for your question! Since this isn't a bug or feature request, please open a thread on our community forum ([https://community.cesium.com/](https://community.cesium.com/)) and continue the discussion there - more users are likely to see your post there and might be able to help.

**Comment by kk1625846601** [comment]
> Hi @kk1625846601, thanks for your question! Since this isn't a bug or feature request, please open a thread on our community forum (https://community.cesium.com/) and continue the discussion there - more users are likely to see your post there and might be able to help.

Thank you very much.I will try it.
