### ISSUE TITLE
poor Performance : ParticleSystem

### ISSUE THREAD

**Issue by baichongjin** [CesiumGS/cesium#9503]
App/Sandcastle/gallery/Particle System.html
set the options.sizeInMeters true,like this:

`new Cesium.ParticleSystem({
    sizeInMeters : true
})`
in this situation, run this app, the FPS is very very low(0 FPS),
even blue screen;

I'm try to debug the source code,the shader file(BillboardCollectionVS),

`gl_Position = czm_projection * positionEC;`

replace with

`vec4 positionWC = czm_`eyeToWindowCoordinatines(positionEC);
 `gl_Position = czm_projection * vec4(positionWC.xy, -positionWC.z, 1.0);`

It's OK!
I don't know why?

**Comment by ebogo1** [comment]
Thanks for opening this issue! I was not able to see worse performance with the `sizeInMeters` option set to true so it's tough for me to reproduce this behavior.. 

@lilleyse Any ideas why this shader change might improve ParticleSystem performance?

**Comment by baichongjin** [comment]
![QQ截图20210423090624](https://user-images.githubusercontent.com/12964427/115803462-7ccbd880-a413-11eb-8640-0f95a8bc8ee7.png)
![QQ截图20210423090804](https://user-images.githubusercontent.com/12964427/115803465-7e959c00-a413-11eb-83fb-f7d780a01875.png)

my GPU is GTX730

**Comment by baichongjin** [comment]
if you attemp zoom or move, it should be more worse.
