### ISSUE TITLE
No Support for 'Flat Earth' rendering mode?

### ISSUE THREAD

**Issue by jim808** [CesiumGS/cesium#9512]
Just for fun, add in a map mode for flat earthers.
As a bonus, why not put a series of turtles under the Earth's disk.

**Comment by ebogo1** [comment]
Hi @jim808, thanks for the suggestion. We already have a Columbus View in CesiumJS - see this [Sandcastle](https://sandcastle.cesium.com/#c=bY7BisIwEIZfJeTkwjJhz8Yilj0sVDwU3UtAYjq6wWkiSVpxn960ehB1bvPN/81MrwPrLZ4xsBlzeGYlRtu1sBnZRHEz9qV3SVuHQfGPqXLK3RyIBh1C6xvM+l2tB7bMCMpVtV4u1vV28/P9mzX+yWVMF8JCOTbW3LYnHxLrAk0ARML2RDphFLvOHDGBiXG4N0SleFRlY3tmm9mbB5khHWOe7Dui2v6j4oUUOf+ikteNdYdVj4H0ZYj9fRXVDQKAFLl9bybvaafD0+Yr) for an example. No turtles yet, unfortunately.
