### ISSUE TITLE
Inspector does not request to a required redraw

### ISSUE THREAD

**Issue by SunBlack** [CesiumGS/cesium#9523]
When debugging some changes, we sometimes want to take a screenshot of always the same position. This is currently difficult because a click in the inspector does not always cause a redraw.

[Sandcastle example](https://sandcastle.cesium.com/#c=bVLRbtsgFP0VlJc6UkawAdvJ0mhT+rBIqzpl1Z78Qu2bBg1DBjhtOu3fh40npe2eDOeeyznnXp+ERScJT2DRNdLwhDbgZNfiHwOWXNXDdWO0F1KDvZqh35VGyNWggd7caXVGS+RtB7Me9rIFFXhLtBfKRUxo2QovjUaXqIVfHTi/A92AvTUNXD7TimfZdm0s3oc3NwehH3vKVu+llv5c6T/Tj5Wu9Cn491KBAx8CxCR4cIePVrbSyxM4LJomuQgXP/TmPjYmQ6TOquU/wtboHTjT2Rrw3pr2swu0bZOkOcvS6axXH+WjIDz74DUZuyP4SmSr3RFqb+ytfJb6VW80W4sWrMBBpp98dNSEAUk9zG55uZuNsD6chKZJT0OIMZIWjOGcsZRxmrJZxLOME55ilpKiXKQp4dlYYHzBWUYwLVhRMkZpD0+HorESwrLfiX4B0Uj9+E36+rAzSo3SPIjmBaUl4YQuCl6MCh8Izoo8J0XKaUkXZZmPhRxnZRq8lAVnhJCSD9LDPiezycr5s4J1pCL0SbZHY32/mwTjuYf2qETIPn/o6p/gce1cP8ueuppftq4aeUKyua4mb37gaoJqJZwLlX2n1Hf5AtVkvZoH/rtWZYbIdyewSpx72iFdf40gxng1D9f/d3pj1IOwb17+Cw):

![Sandcastle](https://user-images.githubusercontent.com/483922/116876397-adceb900-ac1c-11eb-8f5c-8433d3e783c3.gif)

As you can see, the inspector is only redrawn after you moved the mouse pointer over the tileset.

I debugged it until here:
https://github.com/CesiumGS/cesium/blob/ab07bcb130d99baaae08ce5e4346ae79899136e0/Source/Widgets/Cesium3DTilesInspector/Cesium3DTilesInspectorViewModel.js#L486-L498
`that._tileset` is undefined until you move with the cursor over the tileset

**Comment by lilleyse** [comment]
Hey @SunBlack!

You can attach the tileset to the inspector directly with:

```
var inspectorViewModel = viewer.cesium3DTilesInspector.viewModel;
inspectorViewModel.tileset = tileset;
```

[Sandcastle](https://sandcastle.cesium.com/#c=bVPLbtswEPwVwpfIgEtTEinJrmO0cA410CCFG/SkCyOtY6IU6ZKUYrfov5d6BFbjnETOzu7sLFcNN6gR8AIG3SIFL2gDVtQV/tFhwU3RXTdaOS4UmJsZ+pMrhGwBCuK7ByXPaImcqWHWwk5UID1vifZc2h7jSlTcCa3QGDXwqwbrdqBKMPe6hHGZip9EVVd98NHX3By4em4pW7UXSrhzrv5OP+YqV43v3wkJFpw30DvBXXf4aEQlnGjAYl6Wwchc/4nvHvvEoLNUG7l8JWy12oHVtSkA742uPltP25ZBmNAonM5a9UG+F4ST870GQ3YP/ieyVfYIhdPmXpyEurQuXvF23u0Y5MVF8W6BrnrH9EWu0/FlGMNp3Gc/mIJXYDj2sTatd1/6xxCqe6fleA823Dh/4ioOWhpClJIwpRQnlIaUxSGd9XgUMcJCTEOSZoswJCwaApQtGI0IjlOaZpTGcQtPu6A2AvxiXYl+AV4K9fxNuOKw01IO0syLJmkcZ4SReJGydFD4QHCUJglJQxZn8SLLkiGQ4CgLfS9ZyighJGOddLc7k9lkZd1ZwrqnIvRJVEdtXLsHAcZzB9VRcu99/lQXP8Hhwtr23Vrqaj5OXZWiQaK8zSdvfpZ8ggrJrfWRfS3ld/Eb8sl6Nff8q1SpO8sPDRjJzy3tEK6/9iDGeDX31/czndbyiZs3lf8B)

**Comment by SunBlack** [comment]
Ah wait, it is not intended that these options are global for all tileset? In this case it would make sense to disable all options which requires a picked tilset and maybe the tileset group should not be collapsed, so the button to pick a tileset is visible.

**Comment by SunBlack** [comment]
Played a bit with it now, when 2 tilesets are [present](https://sandcastle.cesium.com/#c=vVRRb9owEP4rFi8NUmYS4pBAabWpfRjSqla02hMvJrkQa47NbIdCp/33OTEpoe3epj2Bv/vu++7O5+yoQjsGz6DQFRLwjG5As7rC31vMu8ja440UhjIB6sJHv1YCIZ2BgOj2XvADmiGjavAb2LAKuOXNUEG5dhgVrKKGSYH6qIKfNWizBJGDupM59GUqumdVXbngk9W8KanYNJSFKJhg5rASv4eXK7ESO1u/YRw0GNuA6wS31eGtYhUzbAca0zz3es25n+j2ySV6bUu14rOOsJBiCVrWKgNcKFl90Za2yL1wQsbh0G/cG/sj+7kE4R2LwApofniwOUzDEJsmVNQiawbgDd3wmppLYJvS3BeFK3wc4OCyi61lLXImNo/bEhTYaKd9HnjlZ1QZuVF0W7LMsrsme2jbRAPYEBXeuQ620zKghq96ulYFzeBcqs2MWqElze1/7fV9MZdiw0ydg4/OcXv3DrYtnjxk1/k/tehP9eRllJXibgc/MtT12lIy47mi/G4Afv9BnPje0El3t1LZ7eV31Ci2P8m7M2mbeTr5e71aGpVui//v3r4awt7YN+Ydsx14ZrIQeguZkeqO7Zn4oNiMVqAotjbNF8NVlNuHzUTb4+wvI2xoCBEShAkheEJISOIoJL7Dx+M4iENMwiBJp2EYxONjgMTTmNi3EiUkSQmJogYetkGpmF3j96Zf7Xu0q/7ATFYuJedH69iaTpIoSoM4iKZJnBwdPgV4nEwmQRLGURpN03RyDEzwOA1tLWkSkyAI0ri1bm9w4A/m2hw4XDsqQp9ZtZXKNHfjYTwyUG3tnYMerevsh12ZTGu3QwjNR/3Uec52iOVXq8GbD+9qgDJOtbaRoub8kb3AanA9H1n+u1Qu25bvd6A4PTS0Mrz+5kCM8Xxkjx9nGin5mqo3yn8A)

Current behavior:
- First hovered tileset is automatically picked
- Picking another tileset applies current settings to it and previous tileset keeps settings

![Sandcastle](https://user-images.githubusercontent.com/483922/117129474-0201a680-ad9f-11eb-8942-01b5303fbd1e.gif)

Expected behavior for selecting:
- Variant 1) No tileset is automatically selected
- Variant 2) As long as the mouse is over a tileset current settings will be applied. Moving the mouse away will remove debug infos from this tileset. Picking a tileset explicitly locks the tileset (so no change on mouse move events)
- Variant 3) Options are applied for all tilesets until a tileset is explicitely picked than the options are just for the picked tileset

Expected behavior for selecting:
- In case debug state will ne not reset if a tileset is unpicked: Current debug settings of tileset are loaded when picking another tileset
- Otherwise: Current settings will be applied to all currently picked tilesets. All other tilesets resets their settings.

**Comment by ggetz** [comment]
Closing this since this is unlikely to be a priority in the near future. If anyone has the bandwidth to contribute updates, let us know and we'd be happy to review. Thanks!
