### ISSUE TITLE
SingleTileImageryProvider fetches images when show is false

### ISSUE THREAD

**Issue by jnewmoyer** [CesiumGS/cesium#9529]
Using the SingleTielImageryProvider with a layer, we are seeing an issue where Cesium pulls the image resource even when show is set to false on the layer. It does not display the image, but the request can be seen to the resource in the Network tab. 

The example below can be used to observe this. 

Sandcastle example: https://sandcastle.cesium.com/#c=bVJdb9owFP0rVp6CRB3KxOggRWNdpUXKtKpU60sk5CSXYNWxI9sE0ar/ff4gLJS+xLHvOb7n+NyWSNRS2INEt4jDHt2Borsa/3VnYRYUbn8nuCaUg8yCIXrLOEK0JhXIw4MULS1BzjpiIYFoeBaSlYmHhA6PkNIHBidcIngftLJFvLx/TJbp+jl5+rVOlz/u09XQct8HbsmJgpQcQD7Q4sW23BCmwJTeB/OMZ7w1XpitK+PFm8KqAA74KNaR1dwjc0aKl99E5gwM3PMwKTtBnbHQdu49jNH9EfGGiFKgk3KGvtxcj43cjHtFvR6YsGZLTKcRnlzUckmrreagrPIxHp3sNMce5+GsKK8YPFEGF1L8U+8km6EswDhyzlXkietUVGItWpDGLm54ZdL0BAmFJvbSUz6P3QneSFH/hEoCqPBqOsGjIRrf2O/V16nbfMPTyeAY1HkQ57KTXgph58yMk9qK/cxl6fj/owjd72AeDIPYTc/Cq0XoO60bIbU1GhqXGuqGmbFTUb4zo6FxoZS9ykLjqE+NS9oiWt5+MtioYCZHU9nsGFvRV8iCRRwZ/AWVCVKaCP74h7Sw7fUi9YcY4zgy28+ZWgiWE/nh5n8

Browser: Chrome

Operating System: Windows

This seems like a bug to me. In my opinion the resource should not be fetched until the layer is actually turned on. This is the way other providers work, including the WMS provider. 

In our use case, we may have many user added images on the map, but only a few selected at a time, so we do not want the overhead of many unnecessary requests going on in the background. 

Thanks.

**Comment by ebogo1** [comment]
Thanks for opening the issue @jnewmoyer. 

@mramato is this a bug? I vaguely remember discussing this a while ago (or something similar) and don't remember what the decision was at the time.

**Comment by ggetz** [comment]
I don't think this is a bug. The image is fetched to confirm that the provider is valid and ready to render, similar to how the Bing Maps provider fetches a metadata file before it is marked as ready.

**Comment by jnewmoyer** [comment]
This seems like an odd choice to me. Most use cases I can imagine would not prefer this. Maybe a lazy loading property could be added? Otherwise users need to implement their own provider.

**Comment by jjhembd** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11075
