### ISSUE TITLE
EntityCluster support customized primitive

### ISSUE THREAD

**Issue by qmhc** [CesiumGS/cesium#9532]
I can only add label, point and billboard primitives by listening the cluster event, but I want to be able to add primitives more freely.

Currently I can add primitive by `cluster.label.position`:

```js
dataSource.clustering.clusterEvent.addEventListener(
  (clusteredEntities, cluster) => {
    const position = cluster.label.position

    scene.primitives.add(new Primitive(/* use position */))
  }
)
```

However I cannot know when these primitives should be removed, because the cluster event is for each clustering point be created rather than camera changed each time.

Expected usage case:

```js
dataSource.clustering.clusterEvent.addEventListener(
  (clusteredEntities, cluster) => {
    cluster.customPrimitive = new Primitive()
  }
)
```

For my suggestion, may be made some modifications [here](https://github.com/CesiumGS/cesium/blob/1.81/Source/DataSources/EntityCluster.js#L228):

```js
function addCluster(position, numPoints, ids, entityCluster) {
  const cluster = {
    position,
    billboard: entityCluster._clusterBillboardCollection.add(),
    label: entityCluster._clusterLabelCollection.add(),
    point: entityCluster._clusterPointCollection.add(),
    customPrimitive: undefined
  }

  // ...

  entityCluster._clusterEvent.raiseEvent(ids, cluster)

  if (defined(cluster.customPrimitive)) {
    entityCluster._customPrimitives.push(
      entityCluster._scene.primitives.add(cluster.customPrimitive)
    )
  }
}

function createDeclutterCallback(entityCluster) {
  return amount => {
    // ...

    const scene = entityCluster._scene
    const customPrimitives = entityCluster._customPrimitives // Primitive[]

    // ...

    if (defined(customPrimitives) && customPrimitives.length) {
      customPrimitives.forEach(scene.primitives.remove)
      customPrimitives.length = 0
    }
  }
}
```

Thanks.

**Comment by qmhc** [comment]
I noticed that I can listening to the `camera.changed` event before adding dataSource into viewer to perform remove primitives, but I think this may not atomic.

Another expected usage is to add a before event:

```js
function createDeclutterCallback(entityCluster) {
  return function (amount) {
    // ...

    entityCluster._beforeClusterEvent.raiseEvent()

   // ...
  }
}
```

**Comment by ebogo1** [comment]
Thanks for the suggestion @qmhc! We're currently working on other parts of the code but we'll keep an eye out on this for the future. In the meantime, the users on our [community forum](https://community.cesium.com/) might be able to help figure out a workaround.

**Comment by qmhc** [comment]
Thanks for your reply @ebogo1!

In my opinion, this case is different from #5760.

I want to create and add a custom primitive at the clustering position to instead of the original primitive, is not to know whether the entity is clustered.

Currently I use the following way:

```js
const customClusterPrimitives = []

const removeListener = viewer.scene.camera.changed.addEventListener(() => {
  customClusterPrimitives.forEach(viewer.scene.primitives.remove)
  customClusterPrimitives.length = 0
})

dataSource.clustering.clusterEvent.addEventListener(
  (clusteredEntities, cluster) => {
    cluster.label.show = false
    cluster.point.show = false
    cluster.billboard.show = false

    const position = cluster.label.position
    customClusterPrimitives.push(
      scene.primitives.add(new Primitive(/* use position */))
    )
  }
)

// on destroy
removeListener()
```

I want `EntityCluster` can provide a way to resolve this case to avoid external actions.

**Comment by ebogo1** [comment]
Ah, my mistake. Thanks for the clarification!

**Comment by qmhc** [comment]
@ebogo1 Hey, I just want to make some abundant of 3D marker by `Primitive` to replace the flat billboard which is original.

**Comment by ebogo1** [comment]
@qmhc Yeah, that seems to be what is covered by #4656 as well :+1:. I'll leave a comment there as well, thanks.
