### ISSUE TITLE
How to ignore the label whose disableDepthTestDistance=Number.POSITIVE_INFINITY when using pickPosition()

### ISSUE THREAD

**Issue by FlyingBamboo** [CesiumGS/cesium#9540]
When a label with disableDepthTestDistance=Number.POSITIVE_INFINITY covered another regular one, the pickPosition() get the position on the first one, returns undefined.
See: https://sandcastle.cesium.com/#c=vVNRb9owEP4rpzwFiRkoK1XTFG0DpkVaAQmGNClSZZwDLBw7sp1QVvHf5yQEVW0f+jDND5Hvu/su/r6zC6qh4HhADfcg8QAjNDxPyarC/NhjVTxS0lIuUcde6y6Wsaw5BKXllqMhNEn851gCZMo4RMmg6TSi2rodlX2y0Sod41YjGr+sBfh0c016g8+9weCmXSP9W3J7fVWuM9Drlot0y6hVYYKuUQTwXOctPtkAYm++44ImKLIdp7F3JhtGBQZwRboNsFOHb5Ttt1rlMgnA6hyr1Ml9T6W2/6es/0+VJdzQtcAxZna3RGPH3FgqmauZ5unaKZrPFtEyWk0eo+n3aBotf3/YkosphjmFcpFRhpPCOfSDykSUONpIZrn9ykqD/E0u602qCkxdXatSVLi71pjobtulJ0okGWf7+Tl3obkhJA1YngOAKWmUQCLU1s9eZE7tZiiLV0dcHjMkD7Nfi8njw2w1ad15bS809ihwWMsH+MLTTGkLuRY+IR2LaSaom2xnnbM9WsKMqf8OEHZeUsOEF8CT+3deCTBBjXGZTS7Egv/B2BuGHVf/hioUTbjczgrUgh7Lsl1v+LMGCSFhx4XvM61SYk31q85/AQ

Do you have any ideas to ignore the label with disableDepthTestDistance=Number.POSITIVE_INFINITY when pickPosition() works?

Otherwise, is it possible to ignore all labels when pickPosition works?

Thanks anyways.

**Comment by ebogo1** [comment]
Thanks for reaching out @FlyingBamboo! Since this isn't a bug or a feature request, please continue this discussion on our [community forum](https://community.cesium.com/c/cesiumjs/5). We get a lot more traffic there so it's likelier you'll get some help with this one :)
