### ISSUE TITLE
Allowing user to specify getFeatureInfo URL for WMS

### ISSUE THREAD

**Issue by martin-bom** [CesiumGS/cesium#9545]
Hi all,

I would like to request a feature that allows users to specify the URL for the WMS getFeatureInfo.
The original ticket was here: https://github.com/TerriaJS/terriajs/issues/4751

I have a suggestion to add the feature by updating the file
under `Source/Scene/WebMapServiceImageryProvider.js`, line 185:

Original code:
`var pickFeatureResource = resource.clone();`

Suggest to change to:
```javascript
var pickFeatureResource = resource.clone();
if (defined(options.parameters.featureurl)) {
    var featureurl = Resource.createIfNeeded(options.parameters.featureurl);
    pickFeatureResource = featureurl.clone();
}
```

Thank you very much.

**Comment by ebogo1** [comment]
Thanks for opening the issue @martin-bom! If you're up for it, you can open a pull request with your suggested change; we'll take a look and review it when we get the chance.
