### ISSUE TITLE
position been changed when try to rotate primitive

### ISSUE THREAD

**Issue by QianWu184** [CesiumGS/cesium#9546]
I try to rotate a primitive, but when i use code like this, i find position be changed at same time.how could i do to make it right. can any one help me?（the oldModelMatrix is Matrix4.IDENTITY）
`
let matrix3=Matrix3.fromRotationY(Math.toRadians(angle));
let rz = Matrix4.fromRotationTranslation(matrix3);
let result = Matrix4.multiply(oldModelMatrix, rz, oldModelMatrix); 
`

**Comment by QianWu184** [comment]
The primitive has 1000 rectangles, each with its own location

**Comment by ebogo1** [comment]
Hi @QianWu184, thanks for reaching out. Since this isn't a bug or feature request, this kind of discussion is better suited for our [community forum](https://community.cesium.com/c/cesiumjs). The community is more active there and you'll be more likely to get help if you open a thread there.
