### ISSUE TITLE
Add console warnings when a tileset contains unsupported extensions

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#9552]
If a tileset specifies an extension in `extensionsRequired`, that is not supported, we should log at least a warning in the console.

* We'll need to put together a list of supported extensions:
    * `3DTILES_metadata`
    * `3DTILES_implicit_tiling`
    * `3DTILES_content_gltf`
    * `3DTILES_multiple_contents`
    * `3DTILES_bounding_volume_S2`
    * `3DTILES_batch_table_hierarchy`
    * `3DTILES_draco_point_compression`
    
Some things to consider:
 
* See how `ModelUtility.js` handles glTF `extensionsRequired` and do something similar
* Also, we probably would need to update `Model` to include `EXT_feature_metadata`

**Comment by lilleyse** [comment]
Couple more notes for this:

* The new function should be `Cesium3DTileset.checkSupportedExtensions` modeled after `ModelUtility.checkSupportedExtensions`. It can be marked as `@private` in the doc.
* The function should be called in `Cesium3DTileset.prototype.loadTileset`
* Use `oneTimeWarning` to print the unsupported extension
* See https://github.com/CesiumGS/cesium/blob/master/Specs/Data/Cesium3DTiles/GltfContent/glTF/tileset.json for an example tileset that uses `extensionsRequired`.
* Make sure to add a test in `Cesium3DTilesetSpec.js`

**Comment by mramato** [comment]
Why would these be warnings instead of errors?  Does a user have any way to handle this themselves so they could choose to not load the tileset or show a message to their users?

**Comment by lilleyse** [comment]
Hm, I suppose it should be a runtime error instead like what `ModelUtility` does.
