### ISSUE TITLE
how to  realize 3D interpolation under BIM model constraints?

### ISSUE THREAD

**Issue by calm-zxy** [CesiumGS/cesium#9556]
![QQ截图20210521141247](https://user-images.githubusercontent.com/55907096/119090844-b4439a00-ba3e-11eb-8b1c-bae7ab0b0deb.png)
Now, I have a cuboid-like geological model (3Dtiles). I want to do 3D interpolation around a 3D geological model. My approach is to fill three-dimensional geological models with tens of thousands of boxes(BoxGeometry). However, if two small models(Cesium3DtilesFeature) are adjacent to each other, then the interpolation results of the two regions need to be multiplied by different coefficients to indicate that the two small models are different rocks. So I need to determine whether a point(lon+lat+alt) is in a Cesium3DtilesFeature.  
This is the result of the interpolation so far. I cannot judge which Cesium3dtileFeature each box belongs to, so  the interpolation results of adjacent Cesium3dtileFeature  are completely consistent。
![QQ截图20210521142121](https://user-images.githubusercontent.com/55907096/119091968-6596ff80-ba40-11eb-86c7-0b3e71f624eb.png)

**Comment by ebogo1** [comment]
Hi @calm-zxy - since this isn't a bug or feature request the discussion would be better suited for our [community forum](https://community.cesium.com/c/cesiumjs/5). More community members are active there and you'll be likelier to receive help. Thanks!
