### ISSUE TITLE
How to use aws sdk in CesiumJS source files

### ISSUE THREAD

**Issue by Kennnyoung** [CesiumGS/cesium#9559]
Hi, I am trying to use aws sdk in the source files. After npm install package.json file, when I use import AWS from ‘aws-sdk’ and run npm run build it prints

“code: ‘UNRESOLVED_IMPORT’,
importer: ‘Source/Core/Resource.js’,
message: “‘aws-sdk’ is imported by Source/Core/Resource.js, but could not be resolved – treating it as an external dependency”,
source: ‘aws-sdk’,
url: ‘rollup.js’,
toString: [Function (anonymous)]”

in the console. Does anyone know how to solve this issue? Thank you.

**Comment by ebogo1** [comment]
Hi @Kennnyoung, I see you have opened a thread on our forum. I'll close this issue and we'll continue the discussion there.
