### ISSUE TITLE
Disable shadowMap fading

### ISSUE THREAD

**Issue by kalosma** [CesiumGS/cesium#9564]
The shadow map is fading when the light source is low in the horizon.
Though this is a desirable behavior on earth, and bodies in general, where there is an atmosphere it does not make very much sense on other celestial bodies where no atmosphere is present like the Moon.
When the sun is low in the horizon the shadowMap darkness should be preserved.

I'm attaching a simple sandcastle example for demonstrating the current behavior: advance the time through the timeline for seeing the shadows fading

[sandcastle](https://sandcastle.cesium.com/#c=nVVRb9s2EP4rhF/iAjYlJU6bqW6wtgnSDMlazN4CDAYCWjpLXChSICm7aZH/3qMoyZbm7mF6kXj87uPdfcfTlmkCQvDSKJ6Sd0TCjnwEw6uCXrfmcfTm7M0sDCeD96u3K7mSQzR9uFlczJCqo0XYFo8pWPlFq38gsVzJ/lE3oDLNypwne8S48/fnOIpMqDUMXJ2pj61R1ORqd6NVJdP3tlCmzEE71w0TBt6SIECSBIxh+plslCaWCzDEKuL8CJdEKjkFpm2+T6SlBsnWAu54llsuMyS1uoIuSAtaMy4xky1PQffD9a9lHzL+vpIEn0qLmJzk1pYmDoKNi4iyxGbMAk1UETTMgagk04+ZSKMwPJl43y7I+DDel33tVGkNxtIc1RMj7i8bxjrX2L8a0yC1eGhoYObpeV/z2Je83cpZqnYmrkvWZ120W02p/PpepUCvf3//4e76auJycR6o3ic8j1RyL+Kft80JIHwatzLlCbNK9yNYMwN37Bn0F548wWDT8gIEl9CLLwOVqHQI5XKjPqivg/QSkOBCPkbOJC+Yr3drfunk2XLYDZvlr9o2Pknq5UclLZYJ9MmkFtNJ671ofSzdqKxpzbRrdE+O52agn+u0XRM0bj0zQntrytL01hu6Pj2I7QHW96xcgN7yBIa4fT+Tg4bewRr7jAqtEspMRSGtgrZ9hQ8N0a65H3cseXSNx0QLKJlmBVgPavhrxTSTBjdBWtJTzT14sbHijrVOLShlduJ3XzrBUe5skeRQoOhHR9LyADL+fvSikZdXez544KnNY3IenR4YP4EbF7XVXUt/L1vx/a3Aeu616UwI7L5pwb7yoiquuLFMJm6e4QjAh4b1SCsOsSnTTxIvB4L8rjO0F5DgCC6UamLAzQXY+miy4zjycmApJj0hJbdJjp2bEq2E6BouQS00owas61GvdwoGx2HT4O24wwGKX0ye0Y1WxRVkGsCMW4WmUUTPo06w6eyM/jKbdevo7Az/Nu3q+I/G7/ryK82xDZoImh5pMukiumc2p1b9gVZsnHE0o+etdnWuPwNOZ6f0okW6WvwMiFp4mGuxl1bntm5CJU8UxdN2iaMGpWlIfqsEel+5Se8KdWvUxeswGq9Gp+FpNA3Pp6ezZTSLwzB2Yofh36vRwf1vaVX5P1gv/ps1qbS7XA3x8Tz2Pu0Apd+UKpZqfBw/IUcDd2ePJqO5sc8CLlvdf+VFqbR102RMKf4Ei1JgRiZYVzhjLU1MPQoddB4cus5TviU8fbcaDQboakQSwYzBnU0lxIJ/g9Xoch4g/l+uQtX983kLGmeUg+XR5Z03UkrnAS6Pe1qlxJrpAfMP)

Current behavior
![animation](https://user-images.githubusercontent.com/17494757/119348151-c28ef180-bc9c-11eb-9e94-d30e00b44975.gif)

Desired behavior
![shadow_map_darkness_no_fading](https://user-images.githubusercontent.com/17494757/119349518-86f52700-bc9e-11eb-91d7-b20ed9cb86e9.gif)

Browser:
any

Operating System:
any

I already implemented this feature/fix and will push a pull request in a few

**Comment by kalosma** [comment]
Just committed a trivial fix for this #9565

**Comment by ebogo1** [comment]
Thanks @kalosma - we'll take a look at the pull request.
