### ISSUE TITLE
Missed TS declarations in Cesium `1.82.0`

### ISSUE THREAD

**Issue by turansky** [CesiumGS/cesium#9581]
`package.json`:
```JS
"types": "./Source/Cesium.d.ts",
```

[Source directory](https://unpkg.com/browse/cesium@1.82.0/Source/) - no `Cesium.d.ts` :(

**Comment by mramato** [comment]
@turansky There was an issue with the 1.82.0 published package, it has been republished properly as 1.82.1.  Thanks!
