### ISSUE TITLE
Static resources unavailable for Cesium `1.82.1`

### ISSUE THREAD

**Issue by turansky** [CesiumGS/cesium#9583]
`1.81` - [Cesium.js](https://cesium.com/downloads/cesiumjs/releases/1.81/Build/Cesium/Cesium.js) - works
`1.82.1` - [Cesium.js](https://cesium.com/downloads/cesiumjs/releases/1.82.1/Build/Cesium/Cesium.js) - doesn't work

Is it expected?

**Comment by mramato** [comment]
1.82.1 was an npm only release to fix a publishing error with 1.81. So this is expected. There are no code changes between 1.82 and 1.82.1 and anyone outside of the npm ecosystem should just be using 1.81.
