### ISSUE TITLE
How to change the anchor point of billboard rotation?

### ISSUE THREAD

**Issue by YoonDaeHyoung** [CesiumGS/cesium#9584]
My entities code:
`map.entities.add({
    position : Cesium.Cartesian3.from Degrees(),
    billboard : {
        image : Cesium.writeTextToCanvas('ANCHOR POINT', {
            font : '12pt Arial, sans-serif',
            fillColor : Cesium.Color.AQUA
        }),
        rotation : Cesium.Math.toRadians(0),
        alignedAxis : Cesium.Cartesian3.UNIT_Z,
        verticalOrigin : Cesium.VerticalOrigin.CENTER,
        horizontalOrigin : Cesium.HorizontalOrigin.LEFT
    }
})`

I have to rotate the text using my code.

I need to rotate text from origin point.

However, the rotation of the billboard is based on the image center, not the origin point.

How do I rotate the text at the origin point?

Or can you tell me the location of the code related to rotation?

![image](https://user-images.githubusercontent.com/85214526/120431984-36737d00-c3b4-11eb-9adf-a7a14bc13f76.png)

**Comment by ebogo1** [comment]
Hi @YoonDaeHyoung - for general questions like this please make a post on our [community forum](https://community.cesium.com/c/cesiumjs/5). There are many active users on the forum and you're more likely to get help over there. Thanks!

**Comment by YoonDaeHyoung** [comment]
Ok. Thanks!

**Comment by matthew-viglione** [comment]
Adding link to community post for others who land here with the same question: https://community.cesium.com/t/how-to-change-the-anchor-point-of-billboard-rotation/13923
