### ISSUE TITLE
When I add a 3dTiles, it throw an error in 1.82.1

### ISSUE THREAD

**Issue by Calerme** [CesiumGS/cesium#9590]
The same code works in 1.81, but when I change the version to 1.82.1, the bug is exists.

Sandcastle example:

```javascript
const viewer = new Cesium.Viewer("cesiumContainer");
const tilesetModel = new Cesium.Cesium3DTileset({
    url: "./data/tileset.json"
});
viewer.scene.primitives.add(tilesetModel);
viewer.zoomTo(tilesetModel);
```

Browser:
Chrome

Operating System:
windows

![image](https://user-images.githubusercontent.com/12893097/120736487-eb29ad80-c51e-11eb-812a-e6512ecb9571.png)

**Comment by tange387** [comment]
I have the same problem, but it works normally in version 1.7* and reports an error in version 1.81

**Comment by lilleyse** [comment]
@tange387 would you be able to share your tileset as well?

**Comment by z3214965** [comment]
I have the same problem

**Comment by lilleyse** [comment]
Hi @z3214965 @tange387 @Calerme or anyone else who comes across this issue - if you're able to share your tileset with us please do, it'll help us fix this bug faster.

If you can't share it on github you can email it to us at support@cesium.com.

**Comment by lilleyse** [comment]
We found a tileset that had the problem and opened a PR that fixes the crash: https://github.com/CesiumGS/cesium/pull/9618. The fix should go out with the July 1st release.
