### ISSUE TITLE
`Matrix4.inverseTransformation`: misleading documentation

### ISSUE THREAD

**Issue by atlight** [CesiumGS/cesium#9594]
https://github.com/CesiumGS/cesium/blob/80ceefef2ee8e2f3236c38b8f7fb639caa38a3d8/Source/Core/Matrix4.js#L2589-L2592

I don't know who is defining "affine transformation" to be a composition of a rotation and a translation. Every definition I've found gives an affine transformation as an arbitrary (invertible) linear transformation followed by a translation. 

However, `inverseTransformation` returns subtly wrong results when, for instance, a non-uniform scale component is introduced.

The situation regarding this function is confusing, and could be improved:
* The documentation of `inverseTransformation` (and the cross-reference in the documentation of `inverse`) should be reworded to avoid using the term "affine transformation".
* Moreover, the function name is misleading. It does not invert all transformations. It should be called `inverseRotationTranslation`.

This issue was a real time-waster for me; hopefully the situation can be improved for future users.

**Comment by ebogo1** [comment]
@atlight You're correct that the documentation is misleading here. We do specify that the matrix is expected such that `the upper left 3x3 elements are a rotation matrix, and the upper three elements in the fourth column are the translation`, but we can do a better job with the wording.

The first step here can be to reword the docs, and later we might rename `inverseTransformation` to something more correct. I'll leave this issue open to track progress on both for now, thanks for pointing this out.

**Comment by j9liu** [comment]
@atlight @ebogo1 Would it make more sense if the documentation for `inverseTransformation` read something as follows?

```
* Computes the inverse of the provided matrix assuming it is
* a composition of a rotation and a translation,
* where the upper left 3x3 elements are a rotation matrix,
* and the upper three elements in the fourth column are the translation.
* The bottom row is assumed to be [0, 0, 0, 1].
```
The documentation for `inverse` can be adjusted similarly:

```
* Computes the inverse of the provided matrix using Cramers Rule.
* If the determinant is zero, the matrix can not be inverted, and an exception is thrown.
* If the matrix is a composition of a rotation and a translation, it is more efficient
* to invert it with {@link Matrix4.inverseTransformation}.
```

As for the alternative to `inverseTransformation`, maybe @ebogo1 let me know what you or others think of in the near future and I can work on replacing the name?

**Comment by ebogo1** [comment]
@j9liu I think your idea is a good place to start - should be fine to open a PR for those docs changes. 

As for a new name for `inverseTransformation`, I don't have an idea right off the bat. I think `inverseRotationTranslation` might be too verbose though.

**Comment by ptrgags** [comment]
Just happened to notice this issue. "affine transform" is certainly not the right word, that would be a general linear transform + translation.

Does this method work for reflection matrices too? If so, you could use the term [isometry](https://en.wikipedia.org/wiki/Isometry) which is any rotation, reflection, translation, or composition thereof. (basically any linear transformation that preserves distance). Though not sure how many developers would be familiar with the term.

**Comment by ptrgags** [comment]
Hm actually I think this method does support rigid transformations in general. Looking at the code, it computes:

```
inverse transformation:
rotation = R^(-1) = R^T // true for any orthogonal matrix, including reflections!
translation = -R(-1) * t = -R^T * t

where the forward transformation was: f(x) = Rx + t
R is a matrix, x and t are vectors.
```

[Orthogonal matrices](https://en.wikipedia.org/wiki/Orthogonal_matrix) are any rotation or reflection (or composition of the two). Rotations have positive determinants, reflections have negative determinants (which just means it reverses orientation)

**Comment by ptrgags** [comment]
Tried it in a [Sandcastle](https://sandcastle.cesium.com/#c=bZLNboMwEIRfZcUlIFHTRD01JKqUa6seWvXExYCTWF1sZC9J6NPXJkb5IcgHdnbn89hQaWUJDlIchYEVKHGEjbCya9jPoMVFVA31RiviUglTRMmyUIWqBucHJyNPL84abEEYRrIMtihb0AcH74GfpAWuaiDDlUVOAsoe4kUKfiUjcqvNkZs6pAm8uFAAT/MUnoe1SH3tXua35Vm5Lr1SqGQJl8xSuTxWuA0CnAXl2+dy2zecpFZxCJLe5Ej86c+c1ui6q+iK03RIssX+Yg3kB4wzRaNgqHfxLDheZyN/7ITGvTwL5KkhNCaGMW5s97rDGkoBshaKJPXJBBKGk2WURrmlHsXa36l/3mTTakPQGYwZy0g0rf+WNiu76lcQq6z1ND+aZ9fWvJYHt+XqwS8FFXJrXWfbIX7JP1FE6zxz8xMral5Ltft0Z0Te+7H9fP1+FhljeebKx07SGktu7sj/), indeed, it handles a matrix with a reflection correctly. So it is indeed handling rigid transformations/isometrires (same thing)

**Comment by j9liu** [comment]
Oh! Then perhaps we can change the wording of the documentation to say "Computes the inverse of the provided matrix assuming it is a rigid transformation." However, it wouldn't necessarily be true that "the upper left 3x3 elements are a rotation matrix," right?
