### ISSUE TITLE
WMTS Imagery Prodiver drops query parameters with subdomains

### ISSUE THREAD

**Issue by ebogo1** [CesiumGS/cesium#9598]
This was found on this [forum thread](https://community.cesium.com/t/wmts-imagery-provider-with-subdomains-drops-query-parameters/13611). I believe this is happening because of the behavior in the `requestImage` function of `WebMapTileServiceImageryProvider.js`. If the WMTS imagery provider's `_useKvp` is false, the `templateValues` object does not look like it includes the relevant parameters. In my testing it looks like this flag is set to false with subdomains but true without them.

Sandcastle example: [link](https://sandcastle.cesium.com/#c=bVNrT9swFP0rVoVUkMB5NE1pKWiodFOlMCbYyqZ1Aje5DRaOU9lOgVX97/OjabuCv/ncc+4598ZJSy4V+nGbIHfOUfNJqbnseV5B5gqkWsoVpq9SkfQZc1DNswlPrWhw8/Xz6MtalMGMVEw96NKM5ltScvlreIv2SIy8gdhyri9/PiTD8TDRnNDfwOPR8L4O9XvCEToJwgifhq1uK+hEYSfq+uGxwTUahXE36rT8dtzutuOOhU/iGHf9INC8ViuKA9/BURdHUduP/KAdx2Ecnmr0jzatbV8KJS9FLrXr0vArwXro8WCpd7TyDpZu6pUnQSxoCo+2p6ymWVkQymVvvcdmELaatmaHrWF77E5sTVEG10QJ+noHanTV264oFzRz+oK80qIqElgAc202+7L1WSkKonYMmrQgOXhznrsGUr0x2A1Qm5jyam/yb6Jc0AyEnp7DCxqApFWB72F6Tebfddo7N/bIWIi3mn1YL+1op92Cwst+o7HFDpupvQ5KrvTS9FswOsfH1LVOzNokJln2kVd9cX6ziqeKlhxJUANSgCDG5xBjnEEubyFVR+5bboMZUEdbxzI3wnMGeCbK4gpyASD/058Z+Tphai2wNrM2y0z/JZQTk6C3ab4yktWEv4tknrWpNY4bfftpLkxrcz7RYl4KZV6cJnoKijkj+hf0plX6DAqnUrocCPW9XWk/owtEs/NJY2+vkwZKGZFSV2YVY3f0L0waF31P899JWUkyyvObBQj9ZA3tKbhIHKhj9z19/VipypJNidjr/A8)

- query URL with parameters (no subdomains): `https://maptest.ixstack.net/default_config/service?tilematrix=3&layer=default_layer&style=default&tilerow=3&tilecol=3&tilematrixset=default_grid&format=image%2Fpng&service=WMTS&version=1.0.0&request=GetTile `
- query URL without parameters (with subdomains): `https://maptest2.ixstack.net/default_config/service`

**Comment by lilleyse** [comment]
> In my testing it looks like this flag is set to false with subdomains but true without them.

Can you tell if this is intentional or an oversight? Also, if the fix is simple enough this could be marked as `good first issue`.

**Comment by ebogo1** [comment]
I asked @tfili about this; it looks like setting the flag was intentional but the check for the `{` character was too general to track the case where just the `{s}` keyword is provided. 

I looked over the WMTS spec, and it doesn't look like there's an official way to specify a subdomain with KVP - 
![image](https://user-images.githubusercontent.com/31491650/121255527-843b2a00-c879-11eb-9704-b8271c7389a1.png)
 
The easiest solution here is probably - 
1. In the [constructor](https://github.com/CesiumGS/cesium/blob/afaf1466adaf82d9f82f6c3027991f044dac380e/Source/Scene/WebMapTileServiceImageryProvider.js#L231): if there is a `{` character found because of the {s} keyword, and there are no other keywords, it is safe to use KVP; else continue using templates like we are now.
2. In [`requestImage()`](https://github.com/CesiumGS/cesium/blob/afaf1466adaf82d9f82f6c3027991f044dac380e/Source/Scene/WebMapTileServiceImageryProvider.js#L333), the behavior for when `useKvp` is false can stay the same, but if it is true, it should replace the `{s}` keyword in the request URL. This is because the first change makes it so that `useKvp` can be true even when a subdomain is provided.
