### ISSUE TITLE
Add Table of Contents/Summary at the top of API Doc pages

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#9609]
We got some feedback on our JS doc layout used for our API doc.  It would be convenient to list all the properties and methods in a class at the top of the page instead of having to scroll through everything to see what methods exist.  See the [Android docs summary](https://developer.android.com/reference/android/app/ActionBar#summary) for an example.

**Comment by ggetz** [comment]
Consolidating with https://github.com/CesiumGS/cesium/issues/3507.
