### ISSUE TITLE
Artifacts in clamp to terrain example in 1.81

### ISSUE THREAD

**Issue by ale-siradel** [CesiumGS/cesium#9611]
When drawing polygon with Ipad on clamp to terrain demo, there are some artifacts and polygon not well displayed on terrain.  

Sandcastle example:
https://sandcastle.cesium.com/?src=Clamp%20to%20Terrain.html

Browser:
Safari

Operating System:
iPad Air 3

![IMG_0001](https://user-images.githubusercontent.com/85868545/121861050-c3460100-ccf9-11eb-9acd-a674a5e39c0b.PNG)

**Comment by mramato** [comment]
This is longstanding limitation in iOS, which is lacking `EXT_frag_depth`. I _think_ it will finally be fixed with iOS/iPadOS 15 which is going to be using ANGLE, but have not been able to confirm yet.

**Comment by ggetz** [comment]
Given the ANGLE updates, and the transition to WebGL 2 by default which supports what used to be the `EXT_frag_depth` extension, this should be OBE.
