### ISSUE TITLE
cross-origin-resource-policy (CORP) is missing for dev.virtualearth.net

### ISSUE THREAD

**Issue by MontolioV** [CesiumGS/cesium#9612]
Hi! Thanks for such a marvelous product as Cesium, it's really great!
Currently I face an issue that some requests are been blocked when using COEP policy. The motivation to use it is explained here:
https://developer.chrome.com/blog/enabling-shared-array-buffer/#origin-trial
https://web.dev/coop-coep/

Is it possible to add `Cross-Origin-Resource-Policy: cross-origin` to `dev.virtualearth.net` server response headers?
![image](https://user-images.githubusercontent.com/24456439/121926344-8e13d000-cd46-11eb-96dc-25daad1b1d22.png)

If this issue should be addressed to other place please let me know.
Best regards!

**Comment by ebogo1** [comment]
Hi @MontolioV - this looks to be an issue with `http://dev.virtualearth.net/` (Microsoft's server for Bing Maps) being incompatible with COEP and this is outside of Cesium's control.
