### ISSUE TITLE
How to raise the rectangle extrudedHeight

### ISSUE THREAD

**Issue by Mirror-Yu** [CesiumGS/cesium#9623]
How to raise the rectangle extrudedHeight？I want to pull up the height by moving the points，but it's always inaccurate.Can someone tell me how to solve it, and it would be nice if I could show the code.Thank you very much！

**Comment by Mirror-Yu** [comment]
![image](https://user-images.githubusercontent.com/52779170/122498670-1da8cf80-d022-11eb-9b65-230c5f698e68.png)

**Comment by ebogo1** [comment]
Hi @Mirror-Yu - this type of question would be better suited for our [community forum](https://community.cesium.com/c/cesiumjs/5). We have more active active there so you'll be likelier to get a response. Thanks!
