### ISSUE TITLE
Remove Scene.terrainExaggeration, Scene.options.terrainExaggeration, CesiumWidget.options.terrainExaggeration, and Viewer.options.terrainExaggeration in 1.85

### ISSUE THREAD

**Issue by IanLilleyT** [CesiumGS/cesium#9626]
Dynamic terrain exaggeration (https://github.com/CesiumGS/cesium/pull/9603) moved the `terrainExaggeration` field into `Globe`

`Scene.terrainExaggeration`, `Scene.options.terrainExaggeration`, `CesiumWidget.options.terrainExaggeration`, and `Viewer.options.terrainExaggeration` are now deprecated and will be removed in 1.85

**Comment by ptrgags** [comment]
This was fixed in https://github.com/CesiumGS/cesium/pull/9766
