### ISSUE TITLE
Zoom glitch on mobile

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [CesiumGS/cesium#9631]
Repo
https://github.com/worldpeaceenginelabs/PWA-SPA-LOGIN-MAINSCREEN-MENU-Starter-Kit
Live Demo
https://cloud-atlas.org (only Google Login)

Hi Community.

I am experiencing a glitch on mobile.
Reproducing the glitch:
1. search for an address (the map zooms automatically to the searched place)
2. zoom out slow or fast (map turns/flips upside down)

Can you help?

**Comment by ebogo1** [comment]
@worldpeaceenginelabs I am unable to reproduce this bug on mobile in Cesium [Sandcastles](https://sandcastle.cesium.com/). What device are you seeing this bug in? Are you able to reproduce this bug on that device in a Sandcastle too?

**Comment by wisdomware** [comment]
I also saw a similar glitch as @worldpeaceenginelabs on iOS. What I did was created a WKWebView and loaded the CesiumJS webpage via the URL. Next, I search for an address, and CesiumJS then flies to that location. Then when I start pinching-n-zooming, the map rotates quickly (or does a fast spin) at the center location where I am trying to  pinch-n-zoom in.

**Comment by worldpeaceenginelabs** [comment]
Sorry for answering so late.
Yes, it seems to be device independent, since it does it on my mobile, my tablet (both Android) and now on IOS too.

@wisdomware did you do it with my app? Do you think its a bug in my code or a general bug in the Cesium code?

**Comment by ggetz** [comment]
Due to lack of activity, I'm going to close this issue. @wisdomware  @worldpeaceenginelabs If you have any update, feel free to reopen it. We're aware that touch controls in general need some attention, see https://github.com/CesiumGS/cesium/issues/4363, so please add a comment there if relevant.
