### ISSUE TITLE
MyLocation Button

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [CesiumGS/cesium#9632]
Hi Community.

Is there a MyLocation button available to show the users location with a blue dot on the map?

I searched everything, maybe i miss the right search term?

Thanks for your help!!!

**Comment by j9liu** [comment]
Hello @worldpeaceenginelabs ! This question would be better addressed on the [community forum](https://community.cesium.com/). We have more members active there, so you're more likely to get a response. Thanks!

**Comment by worldpeaceenginelabs** [comment]
I'll do. thx
