### ISSUE TITLE
Issues when upgrading husky

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#9636]
From @mramato in https://github.com/CesiumGS/cesium/pull/9628

> husky 6 doesn't work for me as well as 4 did (I did a completely fresh clone just to confirm everything was new). I often use git gui to commit and husky just doesn't run. I think it may be related to typicode/husky#125 or typicode/husky#715 or typicode/husky#980
>
>Can we roll back just this one library (for now) we can figure out what's wrong with it later.

See https://github.com/CesiumGS/cesium/pull/9628/commits/22b347b0a35f8f898bcf918d3a3477d6d85781c1 for the changes needed to upgrade to husky 6.

**Comment by yukinoda** [comment]
@lilleyse 
in #9774, husky is working as expected in my local environment with dummy commits, can you have a look?
