### ISSUE TITLE
Bathymetery Info Disable from cesium end

### ISSUE THREAD

**Issue by bibuzz** [CesiumGS/cesium#9642]
I have used mapserver to created tiles of the world tiff file. But the world tiff file contains bathymetery data and on viewing the tiles on Cesium using new Cesium.CesiumTerrainProvider , the land is below the oceans, like in a trench. ( the land 3d works well )

Is there any way that I can disable the bathymetery from cesium end, like any flag or something?
![cesium](https://user-images.githubusercontent.com/21257394/123631729-b61a2d80-d834-11eb-87fb-528a1b075df3.png)

**Comment by bibuzz** [comment]
My zoom level is only till 9 for the generated tiles. If I generate till zoom level 18 will this solve this issue?

**Comment by ebogo1** [comment]
Hi @bibuzz - thanks for opening a thread in the forum. I'll close this issue since we like to keep general questions on the community forum instead.
