### ISSUE TITLE
When I use Cesium.Cartesian3.lerp to calculate the point, it will jump to the page path address

### ISSUE THREAD

**Issue by xiaobaogeit** [CesiumGS/cesium#9646]
When I use the Sandcastle example, it can run normally, but when I open a new page directly and run it directly in the console, it will jump to the path.
`http://localhost:544/Apps/HelloWorld.html` to `http://localhost:544/Apps/(-2379556.799372864,%20-4665528.205030263,%203628013.106599678)`
Sandcastle example:
https://sandcastle.cesium.com/index.html#c=jZFRT8MgFIX/CulTm1RKoQWadYvJXjU+mPjUF9ahIzJoKO0yf710m3PTxcgT957z3XMDo3BgVHInHZgDI3dgKXs1bOHLoRc3UXuol9Z4oYx0TZTMGtOYMXDatsIrawJ5opbC+XAThkAtXRc3BoRzMfbbcNIAuMOEVWVJIasqwjCnRXqWCkrLEnOIUYkIwpScJUIxRzmBOaJlVVHGj0KS/juSIgIZYkWOCCvYdSbFBBa8qhDmV5GMUwQ5ZqgoKbtOfBR+Azu7i1EK8N9rJJOYzKI0qnu/13LxlXCvtp11HgxOxxBmXm47LQKVrYb2XXrY9v30+pO1zi7Req1GoNbzG98FWi36Piivg9bP6kM20aLOgv8Xqq1YK/P2NEqnxX6ybfLFw7EJIayzUN4mvbV6JdyPyZ8
Browser:
chrome 91.0.4472.101(64)
Operating System: Win10
Cesium Version: 1.82

**Comment by j9liu** [comment]
Hi @xiaobaogeit ! I'm unable to replicate this on my device, so I'm not sure what's wrong. What happens when you run this in `http://localhost:8080/` instead?

**Comment by xiaobaogeit** [comment]
You can try the code
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Use correct character set. -->
    <meta charset="utf-8" />
    <!-- Tell IE to use the latest, best version. -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Make the application on mobile take up the full browser screen and disable user scaling. -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <title>Hello World!</title>
    <script src="https://sandcastle.cesium.com/CesiumUnminified/Cesium.js"></script>
    <style>
      @import url(https://sandcastle.cesium.com/CesiumUnminified/Widgets/widgets.css);
      html,
      body,
      #cesiumContainer {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    <div id="cesiumContainer"></div>
    <script>
      var viewer = new Cesium.Viewer("cesiumContainer");
	  var location = Cesium.Cartesian3.lerp(
		new Cesium.Cartesian3(
		  -2379556.799372864,
		  -4665528.205030263,
		  3628013.106599678
		),
		new Cesium.Cartesian3(
		  -2379603.7074103747,
		  -4665623.48990283,
		  3627860.82704567
		),
		Math.pow(0, 2),
		new Cesium.Cartesian3()
	  );
    </script>
  </body>
</html>
```

**Comment by ebogo1** [comment]
@xiaobaogeit What do you mean by running it in console directly - are you running the lerp code in the browser's JS console? What behavior are you seeing when doing so?

**Comment by xiaobaogeit** [comment]
@ebogo1  You can watch this animated picture, or you can directly use the code of the entire page I posted before, and the effect will jump to the URL. <br>
![lerp-error](https://user-images.githubusercontent.com/19976188/124852587-151b3780-dfd7-11eb-9d39-ba6d3ae350a6.gif)
