### ISSUE TITLE
PolylineCollection Spec Failure 

### ISSUE THREAD

**Issue by srothst1** [CesiumGS/cesium#9675]
The following spec always fails on my local machine:

[Scene/PolylineCollection renders with model matrix](http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FPolylineCollection%20renders%20with%20model%20matrix)
Expected to render [0,0,0,255], but actually rendered [255,255,255,255]

This occurs even when all checks are successful on GitHub. Does anyone else have this issue?

Operating System:
Windows 10

**Comment by j9liu** [comment]
There's an issue open for this #7892 , the test failure has persisted for a while.
