### ISSUE TITLE
Erratic clampToHeight and heightReference behavior when toggling tileset on/off

### ISSUE THREAD

**Issue by srothst1** [CesiumGS/cesium#9680]
Desired functionality: Allow users to accurately toggle billboards on and off their 3D Tileset. In this application, terrain data would likely be turned off to improve performance. 

Current functionality:

When the viewer is loaded for the first time, the billboards are correctly placed on the 3d tileset (with `HeightReference.NONE` and getting the position using `viewer.scene.clampToHeight)`.

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/4/49d19afa2607662cf5a4c36b196f7dbe153fe0f8.png)

After clicking the toggle button once, the billboards are properly placed on the ground. This is because `HeightReference.CLAMP_TO_GROUND` is used and we are lading Cesium World Terrain.

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/a/a48045e36e221af361c99b52a8bd237f74f04dc4.png)

However, when clicking the toggle button a third time (with the goal of showing the 3D Tileset), we see that the billboard are "stuck" on the ground yet the labels are positioned above the 3D Tileset.

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/d/d7602aa8f423b550b43dbd7fa08cdd75b6cbf4a8.png)

A `.gif` showcases this behavior

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/3/356719391147ecd1a28be1d4d73b90bd24e7195e.gif)

Upon further testing, I noticed that this error also occurs in the following circumstances:

- This error seems to occur for any number of billboard values.

- If toggled is initialized to true (`let toggled = true;) we see even more erratic behavior when toggling the tileset on and off. It seems like the billboards disappear and then re-appear.

This issue stems from a [community forum post](https://community.cesium.com/t/clamptoheight-heightreference-incorrect-behavior-when-toggling-tileset-on-off/14407). Here is a [sandcastle example](https://sandcastle.cesium.com/#c=xVfbbttGEP0V1i9RAJXe+8Vx3Dq2kQRw4sBRWxS2EVDiSiZCkSpJ2UkK/3sPKS4l0g4a9KWAIZO7Z2dmz5yZ5c7yrKyCu8TduyJ4GWTuPjhxZbJehr83Y6PrvVnzfpJnVZRkrrjeGwd/X2dBULmiwMiHIr9LYlcc7C4+S9NkVeZJPOmDRs/H9dLC/bV2ZXXpMoy9y2N3EFTF2mHu4fmL6+w62wQUljOXuTB2q+p2AvzxAqbKqrWJcOtFwKeuCqokdaWr/Fu+WKQuBmQepaVrbM6ara7yMqkSPGLuqo7l6mctQ2k1FVpoYhhjYixISLhRRAlhqSL6ZtxDKmO5JhKTLVJaRYjUxugh1CpLGKY091DDDSVWGsL6UMY4ldJSy5mHarwaQ2FeDLBSKia05LKLQBkpCPzxIdRoZi2xSigPlRiRkkhK+1D4J0LUZjqo4JJry4QaBMs59qoM40Z3UGIZk5woO4AqpYXVMOF5lUxLJS1XmvehgghtLcWuOyiVikuEawbECootyJrFji2iqFFcGzVgQCAxmnBmmY8VSeVgFQQOYhXGWm05MaJLl6CEYoGWAwYkoYLTerwLQEEqkioQMYAyUMq4QC47EUBWnGmiuBpgYdcYifA6FTKsp/BkuBxgNTccWrDGR6ugVQbLeOxDFWWqFqHq8gWpY7WAxodQbgXTFBLzEaAuDAiDGMQgAigASWMUnj0WArSKaRjoQzVT9SYYlx5a6wDKsFDuAGqZscJCTLKFWoldMcIHejEEpSQt0V26QIVRlEDjA20bwagAr4S26UJZNlQTyHBAq6JCKCVVV7NQgar/mBUDbUluGVFKwLPHMsUoCsOyoQooAmNGWbnlSljDoC9qHykWAq931kHhHf1A0WHFcCbqWampR6KHoDQEalYNS6ZuMZpQzyrSV28U9fWoDg1DG1KqM0rANSwiM4PirmlEBNCzl6A2DCRD3cPughkDVVlfBEpIhWAMiq0RwM1Oly6ak+E4TdGlR0l5kkbLVZItJvkblyxuq+fBy6PNIdQeFC6r0NVdGRZumd85LBxtDpJg2/DDeV6cRbPb0cgPbc0EwcZvdZ+ffmhn+8fhSVRUeIoyHs6LfHnqFoVzZWfqityMO1dX9Kb2vjXbhPcVBofhRnE8agPYRnrQC2Psp6dJmk7zqIgPgm5JECTLaIHj83ovDPeb53J/Hs2SFP7CRTLHab3Flrf5fXfS+sHbhtFLN3cgfQZTj+kOfvEsvOmDw/cX78+Cg+/Nnpwfv/vwaXLx6fXlxW/vT3ecxkkZTVN36k/206Ssosb722yeZAi+Az90T2k0dWlv85X7Uh0Ez87rCWykcM/+m4//iYU5vqkQ/jRP44DS1Zdng1y9imafF0W+zuJHWZt2Uyd5mhed8+YtfH15/OcOeJV8cenFfI7vo4MnNc1GlIwDxp5vWd88PPgqgtDmT1dil46NyMPVtnx6X3GzeqVfNuopPLjarO2q5sE77VnofTWONtgmwIedzoGKmmw+BevWsa3wqhvcJaD5x0/bFb4U10XaEfo2zy5dma8LZLIu/OMSwLfxCD1SqQ1fHUm9aFdFssT27toqb/1vom6B3/J8Ocl3p+rJQQf0jPe3E2wBo1oanrnNb2sxjNK02dp5HsUubpvj2R3YPkcxIMpi9MhPy+uLHdKGdrCfHzDy0OvntecnE/M90jZL+rxtkwjhOxSxiztHH6MsnkVllbo6vkmep9OoeLWuqjzDJWbSXAg6A3m2n8/r5hjM19mskeuolfL26vBT+9jmpS6AdqRTfRv84CqEta16ZoWLKvdHXqT+JjTymepRsjPqs9rmIXC4v/yrux+6erUuthXifTTXrqDeZW9ub7x3WFZfU3fkS/zXZLnKi6oukBHOm8otVyn2V+5P17PP0MmsLL2Xw/3dpYdxchck8csnbpMBGkNZYma+TtOPyTd3vXd0uA/8o6Up1AdtXdy5Io2+1rBbenS+GQzD8HAfr0+vrDZqGFj+Bw) that showcases the error.

Browser: Chrome

Operating System: Windows 10

**Comment by AnonymousSausage77** [comment]
Is there any news on this? I am facing this issue currently. My only solution at the moment is to completely rebuild the viewer whenever the map is changed which is not a particularly flashy solution.

**Comment by ggetz** [comment]
@AnonymousSausage77 https://github.com/CesiumGS/cesium/pull/11604 will be adding height references that allow billboards and entities to clamp to 3D Tiles without using `viewer.scene.clampToHeight`, as well as clamp to terrain. The ability to toggle between the two is accounted for there.
