### ISSUE TITLE
Add support for MESHOPT

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9683]
This issue will serve as a task list of adding support for glTF models that use [EXT_meshopt_compression](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Vendor/EXT_meshopt_compression/README.md).

- [x] Integrate WASM meshopt decoders in CesiumJS
- [x] Extend GltfLoader to support EXT_meshopt_compression
- [ ] Add dequantization pipeline stage

**Comment by ptrgags** [comment]
@sanjeetsuhag can we close this?

**Comment by lilleyse** [comment]
This is supported in `GltfLoader`, which is used by `ModelExperimental`
