### ISSUE TITLE
Procedural Clouds in CesiumJS

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#9691]
This issue tracks the progress of adding procedurally-generated clouds to CesiumJS.

# Inspiration
## GeoFS
![image](https://user-images.githubusercontent.com/32226860/126679686-c12ff05d-a066-4fba-9d04-4aec20364488.png)
![image](https://user-images.githubusercontent.com/32226860/126679767-d7cbf7db-3d4a-4bfe-971a-8b6f288bd37f.png)

Dzung, who initially worked on this feature for Cesium, modeled her clouds system after GeoFS. Cumulus clouds were represented with billboard png images, and GLTFs were used for the flat clouds. Supposedly, they are also generated on real weather data.

## Google Earth
![image](https://user-images.githubusercontent.com/32226860/126681932-0da95774-f83d-48db-89a8-0451acee1b2a.png)

Google Earth features an imagery layer of cloud on its globe that might be real data. It fades as you zoom in and out.

## Horizon Zero Dawn
![image](https://user-images.githubusercontent.com/32226860/126679486-c273ba20-1f6b-4372-9f67-f2cb4fca4249.png)

Horizon Zero Dawn (HZD) implements procedural volumetric clouds according to this presentation [here.](http://advances.realtimerendering.com/s2015/The%20Real-time%20Volumetric%20Cloudscapes%20of%20Horizon%20-%20Zero%20Dawn%20-%20ARTR.pdf) Their process of modeling the clouds can be summarized as follows.
- Three textures are used along with a variety of signals / inputs to define the shape of the clouds.
   - [Texture 1]: 3D texture with four channels, the first channel containing Perlin-Worley noise and the others containing layered Worley noise 
   - [Texture 2]: 3D texture with three channels, all different resolutions of Worley noise
   - [Texture 3]: 2D texture with three channels, all [curl noise](https://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph2007-curlnoise.pdf)

The first texture is used as a base shape, and at the edges of the base cloud, the second texture of noise is subtracted, such that it "erodes" the edges of the cloud. The curl noise is used to distort [Texture 2] to fake distortions from atmospheric turbulence. This is further modified by height gradients depending on cloud type and a "coverage signal" (not well-explained in the presentation), as well as a multiplier that reduces density towards the bottom of the clouds (apparently clouds grow denser with altitude).

This algorithm is for their fluffy cumulus clouds. Flat cirrus clouds are apparently rendered as textures above a certain height.

## Unreal Engine Plugin
![image](https://user-images.githubusercontent.com/32226860/126684710-e96b236a-c9c6-485b-84af-b2952c410538.png)

The [trueSKY](https://simul.co/) plugin generates good-looking clouds. I have not done a lot of research into this, though.

# Implementation

I will be focusing on implementing *billboard* clouds in Cesium, since it presents a more reasonable scope than volumetric clouds. This will involve the following details:

- New primitive type similar to `BillboardCollection` and `Billboard`: `CloudCollection` + `Cloud`
   - With this API, user can add or remove clouds themselves, e.g. for taking good screenshots
   - Might want an overarching `Clouds.js` that can host multiple Cloud Collections
   - A cloud should keep track of what type of cloud it is (cumulus + round vs. stratus / cirrus + flat), since they will be rendered differently
- Procedurally generated image in the shader based on noise function and parameters passed in as uniforms Cl
   - should generate color but not save to a texture, don’t want to take up texture space
   - geometry is instanced with scale + position attributes, but if browser doesn’t support instancing, it should still batch into a single draw call
- Option to autogenerate clouds
   - Procedurally place clouds depending a wrapping noise function
   - Should add / remove clouds when camera moves
   - Radius of generation vs. vision
      - the generation radius is bigger than the vision one
      - when a cloud leaves the vision radius, it is not necessarily destroyed, until it leaves the generation radius
      - clouds should be generated before they enter the player's vision
- Animation over time (extra)

# Timeline
I have about four or five weeks to complete this, since I leave on August 27th.

- [x]  Create `Cloud`, `CloudCollection`, and `Clouds` classes, and their corresponding specs.
  - [x] `Cloud` and `CloudCollection` done as of 7/29. #9701 The structure of `Clouds`, if we even include it, will be discussed later. 
- [x] Create the shaders and rendering commands to visualize the clouds. #9701 
- [x] Develop a convincing procedural cloud texture
- [ ] Implement autogeneration to generate these clouds (big task, will break into subtasks later)

cc @lilleyse

**Comment by lilleyse** [comment]
> Procedurally generated image in the shader based on noise function and parameters passed in as uniforms Cl

Depending on performance it might be better to create a small set of procedurally generated textures on initialization and then reuse them by multiple cloud instances. Maybe there's a way to modulate the texture in a cheap way so that individual cloud instances still look unique.

**Comment by ggetz** [comment]
@j9liu Is this issue at a point where it can be closed? Is there any remaining work in this issue that we plan on still tackling?

**Comment by j9liu** [comment]
Yes, I can close this issue. Everything else related to future work on clouds is listed under #9764 .
