### ISSUE TITLE
Billboards change position if camera is rotated

### ISSUE THREAD

**Issue by srothst1** [CesiumGS/cesium#9693]
This issue stems from the following community forum post: https://community.cesium.com/t/billboards-change-position-if-camera-is-rotated-or-map-is-displayed-wrong/14516

Billboard positions seem to change as the camera is rotated. In this example, one billboard is added to the scene. The camera is set 200 meters above the billboards. As the heading and pitch are rotated, we see that the billboard position is changed. This seems to occur with Cesium World Terrain and ESRI World Imagery. [This sandcastle demo](https://sandcastle.cesium.com/#c=zVVtb9s2EP4rhD7JnUvbzYqmjhN0sbvNQBMZtpZtgACDps4SEYoUSCqBO+S/7yTLtqTUyD4OhgSR9xzv4b08fmKGPAl4BkOuiYJnMgUriow+VHt+5PFqPdXKMaHARF7vKlISHMlEnGuh3B0zj5V37TllxuEXUxd0a3Q2g8QAWH80ohefRpeX/Z8/0+Gni8/D/ofhsDwrUvv41HJQQDnLwDBqwZUU/H8iRUgM1gnFnNBq3InbL+3aCEB+pZ2MSeVCSAosFioZH3jdMZfS8M9gvZj394hcOJ6OyfvRuyZkMV8HD1+Xa4TWOKOlHJMhLVcvkXo5z3ord6H+H3Ou67Y4cZkxx1a6MBza9Z8W1mHxjlbshMMlsspx3wh1EuIjzlIWx/65GHsW56wUEyKcqM/AlETu8FOY3zGJvKWuU3YrpOWpMFkmnAOZF+rRRV6/6SPi0sPUHpLtdOEOd+hAsVjciHxfrMgLsXYdRK6tOFPLE2gjpNxoZuKqoKd95JKxpLoApYPq2w6eU+FglbIc75urpBOvdlkVmyUkVdxGcW51oco+WQJ3TCUS/NHwY5/sX5fl0+scxrXUpnXGtNzxR3SI8Oar62k5k8j8A5rbhicwTqAxMCIR6tiyD61tehuEYXDXcR0MCOwg2G5xytukjtrhl2zwecUnBZGkbglbMKA4HOP+3t6n02+/3C3WYbD+bRn8cT97zSAWlm0kzCB3aVnwmbCYzPLE+yLbYFMvgtU8nD98Xc/vf53fz8O/W2e8nBYvb7S1TfUzTpczBZymcFfP+kk4G8NewbaF4lWv8xSLDIfW93uRquRixVTMmXUSaAxcMgN+G9m7IiWufE7h3rfjHZRjNf/rqgSKLfEb3K5RQoa9hvtPZ+gSwrWyGrlInZxO6FWmNwX+bbk8I5gNyTzG7B9M/1Ur22pZ6SW+MM1ljVUjzShLodZyw8xt4RyWIvKmrYzjEJNj2fxexbJbvaujGkfK63sT63YSbg5Mvogs18aRwkgftcJBlkuGMzHYFPwRHOXW7nNKyGTQdJ3E4omI+PoH/9gEm8NatGwLKVfiO0TezWSA+FeuUlcZDHC2US9LWDq6+bbfpJROBrj8safb56Vz8r8) showcases the behavior.

Browser: Chrome

Operating System: Windows 10

**Comment by lilleyse** [comment]
I don't think this is a bug. The billboard's vertical origin is `BOTTOM` and horizontal origin is the default `CENTER` so it stays fixed relatived to that point. I drew a point entity in this [this sandcastle](https://sandcastle.cesium.com/#c=zVbtb+I2GP9XLD6FLWfguul6lFZbaXdDahsErLeTIiGTPBCrjh3ZTjs29X/f47xAkh67aZ8mlCj28/bz8/Izz0yTZw4voMklkfBCpmB4ntLHYs8Le1GxnippGZegw17/IpQCLEl5nCku7T3TT4V1ZTll2uIXk2d0q1V6AzsNYLzRiJ59GJ2f+z98pMMPZx+H/vvh0PkKZRmfmggk0IiloBk1YB0E769QEhKDsVwyy5Ucd+L6Tq40B8Tn5GRMChNCEmAxl7txjeue2YSuPgfr+cwvNTJuo2RM3o2+a6rMZ+vg8XaxRtVKTyshxmRI3eo1lK+nUW/FfqX+x5irus2PWG6YZUuV6wja9Z/mxmLxDlLshPoQaWFYNkKVhPigZyiLY+9UjBLFKSnFhHDLKx+YktDWP4n5HZOwt1BVyq65MFHCdZpya0FkuXyyYc9v2vDYWejKQrC9ym19ho4qFivSPCuLFfZWWLuORqYMP1HLo9KGC7FRTMdFQY/7iCVlu+IAlA6KbzN4SbiFZcIyPG8md514lcky3yxgV8RtFOda5dL1yQIiy+ROgDca/uiT8nXunn7HWaSE0i0fU7fjjegQ1ZuvrqWJmEDk71HcFjyDthyFgeY7Lg8t+9japtfBahXcd0wHAwJ7CLZbnPI2qAN3eA4NPm/wJMB3iV3AFjTICA5xf23v0+ndz/fz9SpYf1oEvz3cvEUQc8M2Am4gs4kr+A03mEzn8SFPN9jU82A5W80eb9ezh19mD7PVl5aP1+OiJgSk0qIzcJKqueg2NM7v6T4ipfWBDDL+B4gl/9Nlf1iNdVXHZg3pl9u7u+CzXzPIf00P8oR/IIp/GFKTqBc8odU5HDllXzHX8RpoUFehts1lVExulGDLQj3IXj+UxXmXTMYRM1YAjSESTIPX1uxfEKfnnmO4d+14NQ8uZ79fOEW+JV4D2yUS4rDfMP/+BFyXaGkUYhFqd/TQL0TfvK6+Tf4n6L9xARxi+rXo3zJ/m/sL9scXptl1rGykGXtypZTYMH2dW4ulCHvTVsaRksihbF6/QNmt3kWjZXp+b2LsXsBVjeQnnmZKW5Jr4SHzWUgzwXDCB5s8egJLI2PKnBIyGTRNJzF/Jjy+/Mr/D4LNYQxKtrkoxiPsXU0GqP/GVKgigwEyFbK/U0tGV3flJqV0MsDl1y1tmZeO578B) to see what's going on.

The desired behavior may be achieved by setting `verticalOrigin: Cesium.VerticalOrigin.CENTER`.

![image](https://user-images.githubusercontent.com/915398/126842411-1462a4a6-bd18-4963-91f9-d7bb2f472787.png)

**Comment by srothst1** [comment]
@lilleyse Thanks for the feedback. I posted an update on the community forum thread.
