### ISSUE TITLE
Use model.silhouetteSize & createSilhouetteStage() will cause a webGL render problem

### ISSUE THREAD

**Issue by SADYX** [CesiumGS/cesium#9698]
Description: Use entity.model.silhouetteSize & PostProcessStageLibrary.createSilhouetteStage() at the same time will cause a webGL render problem like this
<pre>
[Cesium WebGL] Fragment shader compile log: ERROR: 0:6: 'czm_pickColor' : undeclared identifier
ERROR: 0:6: '=' : dimension mismatch
ERROR: 0:6: 'assign' : cannot convert from 'const highp float' to 'FragColor mediump 4-component vector of float'

[Cesium WebGL] Fragment shader translation failed.
An error occurred while rendering.  Rendering has stopped.
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:6: 'czm_pickColor' : undeclared identifier
ERROR: 0:6: '=' : dimension mismatch
ERROR: 0:6: 'assign' : cannot convert from 'const highp float' to 'FragColor mediump 4-component vector of float'
</pre>

Sandcastle example: [example](https://sandcastle.cesium.com/#c=jVLva9swEP1XhD/ZYGRn+ea6oSEpY5Cxjmz9UpWh2BdHTJaCdHZJS//3nX9saTMzJvxBp3vv3bs7t9KxVsETOHbNDDyxFXjV1Py+fwtFUPTxyhqUyoATQXQljDAt8bzSB9sAInx0AIYERvKd9XjnLFH9FmUFG7Vz0p144UAi3JYVrAGhQGVNnw87zQs13hi1t672vLDaurP4qgv55tPn23+RNJgKD8RKeTqbAHrQZABKQjw8Un6YAfcFGODHC/+ey7IMhWF0/qvF7Z9qQ38PA7c7F0biIfMYCXMeLBhUeCJro6s+VqONl4FBHlU3wOzt1lbSId2kmfO9s/UaKqrhw9mHNJ6ncRqN1Wpbgs7Yy9lV41TGRMB5Qt9W1kcNa4ky6ZE+GeSXyo23H3Tlld6JIJ7qrF9R9n5hy6/fl5PgrXqGjM15OmZfhXmNzht5trb+ZsNhJNFVEAe5x5OGxW+tG1UfrUNqQYdkHoHM0wp8smuKn4C88L6T66B58paal6plqrye+MdZoaX3lNk3WncGRbDIE8L/RdVWlspUX1pwWp462GG22AyPnPM8oXCaidbqnXQXyr8A)

Browser: Chrome

Operating System: Windows 10

**Comment by j9liu** [comment]
Thank you for noting this bug @SADYX! There is an issue open for the same bug at #9664, so I am going to close this issue to avoid duplicates. Any progress on this bug will be noted on that issue's thread.
