### ISSUE TITLE
Handle resource destruction in ModelExperimental.js

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9709]
A instance of `ModelExperimental` is destroyed when the primitive is removed from the scene. We need to make sure we are cleaning up all JS and WebGL resources. For example, if `instances` are defined, a `VertexArray` may be created in the `InstancingPipelineStage.js`.

We want to find the right data structure to track all these resources that will need destroying - across the scene graph objects and the render resources.

**Comment by ptrgags** [comment]
@sanjeetsuhag did we handle this? there's a `_resources` array for items that need to be cleaned up at destroy() time, correct?

**Comment by sanjeetsuhag** [comment]
Yes, the base functionality is covered.
