### ISSUE TITLE
glTFLoader spec issue when releasing CesiumJS 1.84

### ISSUE THREAD

**Issue by srothst1** [CesiumGS/cesium#9710]
The following specs failed when I ran them on my Linux machine yesterday afternoon during the CesiumJS 1.84 release. @ebogo1 was not able to reproduce these spec failures. Let me know if you would like more details - I can't think of much more to add here. @ebogo1 feel free to chime in with any more information that you have collected.

[final.pdf](https://github.com/CesiumGS/cesium/files/6927819/final.pdf)

**Comment by ebogo1** [comment]
One thing to note is that @srothst1 was able to reproduce these failures on the 1.83 release too, so this was not a recent regression.

**Comment by lilleyse** [comment]
The relevant failures are:

```
Scene/GltfLoader resolves before textures are loaded when incrementallyLoadTextures is true
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in http://localhost:8081/ThirdParty/jasmine-2.2.0/jasmine.js (line 1803)
attemptAsync/timeoutId<@http://localhost:8081/ThirdParty/jasmine-2.2.0/jasmine.js:1803:23

Scene/GltfLoader destroys glTF loader
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in http://localhost:8081/ThirdParty/jasmine-2.2.0/jasmine.js (line 1803)
attemptAsync/timeoutId<@http://localhost:8081/ThirdParty/jasmine-2.2.0/jasmine.js:1803:23
```

**Comment by lilleyse** [comment]
From https://github.com/CesiumGS/cesium/pull/9712#issuecomment-897176570

> @lilleyse hm that is the same type of error that we're seeing. Our unit tests were modeled after the GltfLoader one so whatever the fix there is, it's probably applicable here too... We should discuss this tomorrow


> @lilleyse I see that `waitForLoaderProcess` only waits for the `promise` and not the `texturesLoadedPromise`. Do you think that's playing a part here?
> 
> https://github.com/CesiumGS/cesium/blob/ffcc025a9ed8c9f54e7d7ce6cb09bf89bcdac273/Specs/waitForLoaderProcess.js#L3-L14
>
