### ISSUE TITLE
 how to set  material  to  Polygon(extruded)'s side  , not top ?   

### ISSUE THREAD

**Issue by zwzhlj100000** [CesiumGS/cesium#9714]
How to set  material  to extruded Polygon  side  ？polygon.material  is top material  ,when extruded Polygon  ,side  no material

**Comment by ebogo1** [comment]
Hi @zwzhlj100000 - for questions like these please make a post on our [community forum](https://community.cesium.com/). We have more active users there and you'll be likelier to get help. Thanks!
