### ISSUE TITLE
Changing Pointcloud Style and Eye Dome Lighting causes Rendering to stop

### ISSUE THREAD

**Issue by anne-gropler** [CesiumGS/cesium#9715]
Sandcastle example: [Link](https://sandcastle.cesium.com/index.html#c=vVhbU9s4FP4rZ+hu69DUuREoIbDb0nbbHSgMYbsPpNNRbCXR1pFSS4bQNv99jyRfYscOYR+WGWJb5/adi27nloRwy+gdDeEYOL2DUypZNHM/mTFnuOOZ71PBFWGchsOd2tGQWwnXC4T31fWiMKRcXbMZzev4MwoY4W+Iok57r3vQbbfdVnfv4LCtVaASNK1YQCVVeTn76Ly5tkTnx5ADRGHQ00+A4Y7rNgZkNg8o6iaNHHvjUjCuTgMR+SuvfzM1vaShGbgMxZyGiiFvbN39Rwo+3KkP+XLFOelRTt15yGZMsVsqXeL7TiyxwvZdiNm1SAj1VT/eU+IzPrlkypteET6hTtNt1uFFS/928b2m9SQg5inawdTIuUQpyiOimOAYIBVGNI2bVPcohaM3n3FsHHHPcCHEgaY4nMxo3XLVwMTPvFsjA/ZdZypG6dMxiQL1iQQRdQpcCBNRHqXy0p1HcmoTAqCN9Mxv3Q4Ynp59mCETz6UGnSIb7nwUYF4x4vBjaWthhXxFfUPR8p4IRNjDjJsX59mT8biJf89qWbZysqeaDf4IMX5YkVVqarALv/xQdIZ1QFQU0mWFuoGic0A8jdcYm3VteR1wAk23C79BjDWk/rMa9JLPEaqoxP2BKxrORYBTpcpeUvs57UU/4HneHDI4WG3wosC3OX5XOLeK3sYp9wT3mS412YMbOwT4UgxFH0PR0iqyzOm8HR7qCHyubxZsFwU9DwXrgI5sId3JS+/vj8edDkpjbraQ3rPS4WREnHa3Wwfz09TirS3Eu6m4lW61X6LoFoL7OdQmuQ8LHeSFUqPNtvmpbaPjpdUxlQEuTi8PuibM2t39LYQPU2GipTupcLc0YHoFy2fnnflby619LktL9DokXM4J7jje/fqUNIlrZmnbruzfM5/CmbiD64y5VLeT17ebVofVjCvgVNxVLA2dqkUGRWAQjSQ1a7hMDWe6mL+E4+NjaMHPn2A/T9DFJjx9Gn/2odNsVhg4F36Fzl+hbfRWSb4ayU1rKBnJQkBwobHzrCJ1bCK4mFEVMg/exZuW3LjQaTt6OcekO54o2qvV0hVPM0rGiww5uiJr9CrPQw/+K1yicfp0ElL6AF7yEGBSgniNoY0clxeDD9cfLj4ub5qf69u5OPgWbtwhJdK3jNaATXhFWPSkkUguYNQGzORZo7U20NoJrQrIlYi4Pjo9mC0NaxwIdLUCl0dZUIUr1FYeB+ztYg6E+7jIbIctEJMqZEhqlyPDyqCLebsKNtIeB/pdSAxQEsAlWSuWXCg1ZxXgdWJrE/FBWJfiblPdzsVdoWzr0KnSdc64ycs5WWxwb8Zydegu9PZ20E2dmJFFjv5d09sZfYMzpwEetiwEttjklqcZ1xzDXdbYqpyZVJ/YSHgP5mj36FOd3Vtwq7H79i319hCDTLQapcuyo1n8ApBp6cY7VEYpV2dOtRUmUvHC0cRaONiMExr6OrMl2lZzDa4uhabZ7z9GsxEN1y24C3sMzFVwHvCms81fkoK5e9n8yLIrx+nF2cXVsuzkr+HpA2f8X1USmZG5kKzkyJFUfn46x9cbcwBZncnl4+14fBVDowEJg6443U+Q0MRNEJiSEBCp3Z7NBcerGy7+Qt9mda5ACZxhXymoaRoefU0GMSff8ES5foEZEUmRzFMP1wMZV0iKeKXAyu6B+IxNS7wWV95P44O7SXF6iS45D+5ieVWtSHgXZ3M0h/dyxmmWm/g7nbQB5RM11crt26o3WeEpNksA6D5Dx/8S9xu+aIpG0nGTOl/WH7M0WKu5e082uAvVV5ncZMu0tNzS5QF/Os5a+JJtwzhRq21eHrJ7RzJ9yq4ahYx142tz5lE7BZidojP4CTXOaNqSwVDb1K42Y0KKjnBImZxaEu+kG2S4q9tiqypNe2aZNFrS7tDF3KQt7RHhvHA0keFI8wgf/aSnY504gufPWYwjVYK8lumGfc7aQLHqXDNI0YWKWz/uSksI2WiAN5teIRDWwVqhSzTAjdDDhQDpOCWuhQhGJDynPHJW7Wr2IudkEtDXkVKC69MWJyPE/irrn+n06zKor8TcFPuUel+pP+Sx42wMTtYXw/mWtfzWUvRQwy7WbdOTFsY2wN/eU3iDFw84Y5OpQs3/D3x6T7XVxGipCzv1nb7JxUkywX5nuGaHSjdoHddt6Imq+1iyMYpQVrmelLZE9d8TZXMKI+Nygkn/+Uyi4H0PRrqrnEos7Uu/sWq177NbYP5xSXtaH5SkRMo4CoKBWaxP+g3kXxMNhHH74paGaFezTVsnZ3bQdd1+Az/LJWMnCpr/BQ)

How to reproduce:

1. Open Sandcastle, wait till globe is loaded.
2. click "Enable Eye Dome Lighting" so that it is disabled.
3. click the dropdown (which should show "no style") and select "Red".
4. click "Enable Eye Dome Lighting" again so that it is enabled.

**Current behaviour**: Rendering stops
```
An error occurred while rendering.  Rendering has stopped.
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:83:13)
    at ShaderProgram.throwOnDestroyed (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:32753:13)
    at beginDraw (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:244323:19)
    at Context.draw (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:244429:5)
    at DrawCommand.execute (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:103058:13)
    at executeCommand (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:306453:15)
    at executeCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:306811:11)
    at executeCommandsInViewport (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:307479:5)
    at Scene.updateAndExecuteCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:307207:7)
    at render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:308091:11)
```

**Expected behaviour**: Seeing the point cloud in red style and Eye Dome Lighting (EDL) applied, regardless of having EDL disabled before switching styles.

**Other Findings/Workarounds**:

1. It is generally possible to see the Red style together with EDL. For that, just directly choose the "Red" style. Then, you can disable and enable EDL as you please.

2. If you follow the steps to reproduce the issue, but instead of "Enable Eye Dome Lighting" you click "Enable Attenuation", then this error does not occur.

3. A workaround is to re-set the tileset's style after setting EDL. For that, in Sandcastle function `addToggleButton("Enable Eye Dome Lighting", ...)`, after `tileset.pointCloudShading.eyeDomeLighting = checked`, add the following two lines: 
```
const styleDefinition = tileset.style.style;
tileset.style = new Cesium.Cesium3DTileStyle(styleDefinition);
```

Browser: tested on Firefox 90.0.2 and Chrome 92.0.4515.131

Operating System: tested on Windows 10

**Comment by ebogo1** [comment]
Thanks @anne-gropler - I can reproduce this in Chrome on macOS as well. We'll look into this as soon as we can.
