### ISSUE TITLE
PinBuilder- Base64 string 

### ISSUE THREAD

**Issue by vlkpa** [CesiumGS/cesium#9721]
Hello all, i have svg icon from my backend represented as base64 string and i want to insert it into pinBuilder, there is a method pinBuilder.fromUrl(url: Resource | string, color: Color, size: number) to insert path to file but is there a way how to insert directly Base64 string (or encoded base64 = svg icon as HTMLElement) into PinBuilder? not relative path/Resource to icon as in pinBuilder.formUrl method?

**Comment by ggetz** [comment]
Hi there, you should be able to create a Resource and embed the base64 string as in a data URI.
