### ISSUE TITLE
Exploring what's possible with Custom Shaders

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#9728]
Custom Shaders (issue #9518 and initial implementation #9725) allows applying user-defined vertex and fragment shaders to glTF models as well as 3D Tiles. This is new behavior, as the old materials system was not compatible with 3D Tiles.

While the implementation is still a work in progress, we still want to gather ideas of what exciting things will be possible with this new feature.

Here are a few ideas we've seen already, though more are welcome!

* glTF supports storing [application-specific semantics](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes) (custom vertex attributes). For example, a mesh could have `_TEMPERATURE`. Custom shaders provides a method to access these values and use them in the shader
*  (requires glTF `EXT_feature_metadata`) Make a tileset that includes simple polygons with metadata labeling them as "grass" or "building" etc. Then use custom shaders to procedurally apply textures
* A user could apply a mask/tint to areas of imagery data in more nuanced ways than with styling. This will be even more useful once `EXT_feature_metadata` is available and the shader can use metadata to mask where the shading should be applied.
* If we include cartographic WGS84 coordinates (caveat: 32-bit precision limitations on the GPU) you could easily overlay a lat/lon grid over 3D tiles.
* @srothst1 had a couple interesting ideas for visualization:
    * Weather visualizations on a tileset with terrain/imagery. For example, maybe visualize wildfires or other extreme weather events in the news. This would probably be a good use case for `EXT_feature_metadata` feature textures or feature ID textures.
    * We talked about how you might represent [The Valley Curtain](https://christojeanneclaude.net/artworks/valley-curtain/) in CesiumJS. While certainly you could do something simple with a glTF and animations alone, with a custom vertex shader you could simulate the curtain flowing in the breeze (perhaps with procedural noise or something)

Thanks to @mramato and @srothst1 and others for some of the above ideas.

@mramato mentioned a couple more ideas in slack, could you expand on them in more detail here?

**Comment by lilleyse** [comment]
A while back there was a [PR](https://github.com/CesiumGS/cesium/pull/5380) to add uniforms to the styling language and one of the sandcastles I put together was flying a plane around a mountain and shading based on distance. 

![mutables](https://user-images.githubusercontent.com/915398/39262033-39963db6-488c-11e8-9d14-28e6429dd3d3.gif)

**Comment by mramato** [comment]
Here's some random questions/ideas:

* Just to confirm my understanding, with these new capabilities, I could have a 3D Tiles roof marked as "grass" and have a custom grass shader used for drawing now?
* Should/could there be a way to extend the 3D Tiles styling language so that you can provide an easily transportable way to share these visual enhancements without them being app-specific?  For example, if I have a bunch of custom shaders to render Cesium OSM Buildings based on their material metadata (glass, brick, grass, etc...) it would be great to have a way to include that with the tileset.
* Can 3D Tiles/glTF ultimately replace (or heavily augment) the Geometry and Appearances system?  Would generating 3D Tiles (or glTF models) on the fly and then attaching materials to them be cleaner more uniform solution?
* Does this mean we now have a clean way to do video on models or video on 3D Tiles? Similar to what we can already do in G&A.

**Comment by mramato** [comment]
Does this get us any closer to being able to drape imagery layers over 3D Tiles?

**Comment by lilleyse** [comment]
Random thought that came to mind after talking with @srothst1  - would it be possible to make certain built-in uniforms available to custom shaders like node id and primitive id? That way someone could color specific nodes of a model like in https://community.cesium.com/t/how-to-color-specific-part-of-model/14898. Of course, the better solution would be to use `EXT_feature_metadata` where this type of functionality would be built in.

**Comment by ggetz** [comment]
@ptrgags Given we've done the initial work on the custom shader implementation, is there anything actionable left in this issue that we'd plan to address, or can it be closed?

**Comment by mickae1** [comment]
> Random thought that came to mind after talking with [@srothst1](https://github.com/srothst1) - would it be possible to make certain built-in uniforms available to custom shaders like node id and primitive id? That way someone could color specific nodes of a model like in https://community.cesium.com/t/how-to-color-specific-part-of-model/14898. Of course, the better solution would be to use `EXT_feature_metadata` where this type of functionality would be built in.

did you make certain built-in uniforms available to custom shaders like node id and primitive id ?
