### ISSUE TITLE
Implement reflective shadow map in cesium.

### ISSUE THREAD

**Issue by zsunpl** [CesiumGS/cesium#9744]
Hello guys!
      I want to implement reflective shadow map algorithm in cesium. I dive into cesium source code and found that , the builtin gbuffers without normal frag output. which is a key input for the RSM algorithm. Also the shadowmap does not include normal and position frag output. So I'm now confused, should I modify the framebuffer and shadow map source code  or just  redefind  new framebuffer and shadow map objects to extend their ability? Or any other ideas?  Thanks a lot!

**Comment by ebogo1** [comment]
Hi @zsunpl - thanks for the question. For general help like this, please use our [community forum](https://community.cesium.com/). We have many more active users there and you'll be likelier to find help.
