### ISSUE TITLE
ktx2 texture with mipmap has moire pattern in Cesium

### ISSUE THREAD

**Issue by jz0224** [CesiumGS/cesium#9746]
The 3dtiles and gltf files are attached below. The gltf file is exported from 3dtiles file, and display correct in gltf viewer. The Cesium version is 1.83.
![cesium](https://user-images.githubusercontent.com/30064494/130346351-e3f93659-0a88-4798-81a6-2d863a1e4876.png)
![gltf_viewer](https://user-images.githubusercontent.com/30064494/130346356-15f6eebc-4b88-494a-99c4-8558c615bbac.png)
[3dtiles_mipmap.zip](https://github.com/CesiumGS/3d-tiles/files/7026737/3dtiles_mipmap.zip)
[gltf_mipmap.zip](https://github.com/CesiumGS/3d-tiles/files/7026740/gltf_mipmap.zip)

**Comment by lilleyse** [comment]
@ebogo1 can you take a look at this?

**Comment by ebogo1** [comment]
This should be fixed after https://github.com/CesiumGS/cesium/pull/9876/. Feel free to reopen or leave another comment if you're still having issues!

**Comment by hujiaxu** [comment]
> This should be fixed after #9876. Feel free to reopen or leave another comment if you're still having issues!

I found a similar problem in Primitive. [https://github.com/CesiumGS/cesium/issues/12413](#12413)

**Comment by hujiaxu** [comment]
> This should be fixed after #9876. Feel free to reopen or leave another comment if you're still having issues!

I found a similar problem in Primitive. [https://github.com/CesiumGS/cesium/issues/12413](url)

**Comment by hujiaxu** [comment]
> This should be fixed after #9876. Feel free to reopen or leave another comment if you're still having issues!

I found a similar problem in Primitive. [#12413](https://github.com/CesiumGS/cesium/issues/12413)
