### ISSUE TITLE
es6 reference problem 

### ISSUE THREAD

**Issue by ll151** [CesiumGS/cesium#9789]
:exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
![image](https://user-images.githubusercontent.com/18732863/131946867-8cb2ec8d-1c67-4891-a738-5538b3bc796d.png)

**Comment by puxiao** [comment]
When I update to the latest version 1.85.0.
I also encountered the same problem.

**Comment by puxiao** [comment]
Hi @ll151 
Have you solved this problem ?
How ?

**Comment by ll151** [comment]
> Hi @ll151
> Have you solved this problem ?
> How ?

Roll back version to 1.82
