### ISSUE TITLE
Can Custom Geometry support GroundPrimitive?

### ISSUE THREAD

**Issue by cangshudada** [CesiumGS/cesium#9791]
I use Geometry to pass in custom vertex data to get the GeometryInstance. Can I support GroundPrimitive and how?
This is an example of generating Primitive, which is normal： [This is an example of generating Primitive, which is normal](https://sandcastle.cesium.com/index.html#c=tVVtj9o4EP4rFp+g4kzeX1i6Kl22vZXQLSp7/VKqrUkGSC+xI9thj1b893PeE0rV+1IJhWQ8z8wz42fsI+HoGMELcPQaUXhBdyCiLMEfC9twMwiK7ztGJYko8M1gdLOhG7rLaCAjRtEe5AMVklDlOByh7xuKUMCUBaVMRLnLnOexP+ULCP1h+IbtGD72HF93TFs3zDEyXdPVTR3nT03XbH+MLMNyHM3Atu77tqHp7riHt7DlW7pj+bpv13gDO6brG4ZnaW4dwMaar/mua3l9vItNyzfVkuPVcAcbnqLjuI5Zom3fx77lKX/PtAr455u2OiIlj7aZBNFv3HtgCUh+mjfrw1EBawG47swvkMPvJeeAJSmjQOWCSCJPKUxryN3lCl48/v12eT++AIoV8CbsFJnV+pHEGYhpd6eKlfMPjAMWM/4b6L5bPs6ffsHWumD7SRuj8qfXL5fvn7tlcJAZp9eo18Ktme8r+/Sac+3U7cu4NqU8SlQLj/DUrXfVteKnDw/zv94v79cNassyGkZ0v04PwFvY254Z7zhLPgKXUT5hna0aVXHOo7bacz6b5TxjEQAF3DATmIThsFNYw66sbH/RFNXp/mwXWUiaAuG5pdekeWOu2yTVl4gzxUFO0Y7EAiq6HGgIfK0EoEI0Pd3GUNTcNqEyFI548bCeK10v6pKr/x0n+0RlWB9IHpNlPOf15Uj4SUHREQILHZ8L8d5UImJRiBJ1lA1HpaFhoDoQP79TAe9Krfdx5y+1CtVOwL8XCRtF5CnNZp7MxZ/R/lBF+KnPkr1cc7FQj/fPS2pRu5gRibZEBoeH8H8UXARL1VgH35LnfPxUkFXFqzq1Ksfn6gDo5i10X4ETFkKc3xkrzr5CcTN8gJgU2mf3J0CvUHrT6/SqPQPTfo8rPRNxosGBM8oy0SroPCrvn0rjAUmAEyxA5slL7YUgZERJHrw9eYjaNRERahbjtIA9B6Vp3fCwZtuu6fjqJnF1vbg4sKYbuqZpuu6ZvqMOFlvTRkXuIvVgPJgJeYrhti7oTaROLi5RxuMhxhMJSapqBzHZZsE/IHEgRN3N2aQLnYXREUXh6yvXLApiIoRa2WVxvI6+wWZwO5so/x+gatPzQXlUyozJKXc76LfL0ogxnk3U53WkZCzeEn4R+T8)

This is an example of generating GroundPrimitive, it will report an error：[This is an example of generating GroundPrimitive, it will report an error](https://sandcastle.cesium.com/index.html#c=tVVtj9o4EP4rFp+g4kzeX1i6Kl22vZXQLSp7/VKqrUkGSC+xI9thj1b893PeE0rV+1IJhWRmnplnxjPjI+HoGMELcPQaUXhBdyCiLMEfC9lwMwiK7ztGJYko8M1gdLOhG7rLaCAjRtEe5AMVklBlOByh7xuKUMCUBKVMRLnJnOe+P+UKhP4wfMN2DB97jq87pq0b5hiZrunqpo7zp6Zrtj9GlmE5jmZgW/d929B0d9zDW9jyLd2xfN23a7yBHdP1DcOzNLd2YGPN13zXtbw+3sWm5ZtK5Xg13MGGp+g4rmOWaNv3sW95yt4zrQL++abNjkjJo20mQfQL9x5YApKf5o1+OCpgLQDXlfkFcvi95BywJGUUqFwQSeQphWkNubvU4MXj32+X9+MLoFgBb9xOkVnpjyTOQEy7J1Vozj8wDljM+G+g+275OH/6BVvrgu0nbYzKn16/XL5/7qbBQWacXqNeN27NfF/Jp9eMa6NuXca1KOVRokp4hKduvquuFD99eJj/9X55v25QW5bRMKL7dXoA3sLe9sR4x1nyEbiM8gnrHNWo8nMetdme89ks5xmLACjgPc+9NUwEJmE47KbX15dZ7i8KpKren/MiIklTIDyX9Ao2b8R1yaT6EnGm+Mgp2pFYQEWdAw2Br1UzKBdNfbcxFPm3BakEhSFePKznqscXdfrV/46TfaIirA8k98kynvP6ciT8pKDoCIGFjs9FI99UDcWiECVqrQ1HpaBhoCoQP79TDu/Kvu/jzl/qjlSnAv9eBGy6Iw9pNrNlLv6M9ofKw09tluzlmomFerx/nlKL2sWMSLQlMjg8hP8j4cJZqkY8+JY856OonKwqXtUGqwyfq2XQjVvMQAVOWAhxfn+sOPsKxS3xAWJSzAG7PwF6hdKbXqVX7T5M+zWuepuIEw0OnFGWibaDzqPyLqr6PSAJcIIFyDx42XshCBlRkjtvtxBRpyYiQs1itBaw56B6Wjc8rNm2azq+ulVcXS8uEazphq5pmq57pu+oJWNr2qiIXYQejAczIU8x3NYJvYnUFuMSZTweYjyRkKQqdxCTbRb8AxIHQtTVnE260FkYHVEUvr5y5aIgJkIozS6L43X0DTaD29lE2f8AVYeeD8qj6syYnHKzg367LIUY49lEfV5HSsbiLeEXnv8D)

**Comment by ggetz** [comment]
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
