### ISSUE TITLE
ponographic site is injecting into Cesium

### ISSUE THREAD

**Issue by baoxiao1990** [CesiumGS/cesium#9796]
we found a pornagraphic website [http://www.frontierwebdev.com/ ] is injecting into Cesium‘s two files, they are:
1. cesium\Source\ThirdParty\sprintf.js-->Riddler (http://www.frontierwebdev.com/)
2. cesium\LICENSE.md-->Riddler (http://www.frontierwebdev.com/)
Hope to remove all things about that site, thank you very much!

![licence md](https://user-images.githubusercontent.com/37405785/132297377-7b4f3c17-2d98-43e9-9448-566ed9646a1d.png)
![sprintf js](https://user-images.githubusercontent.com/37405785/132297386-f5aa52d6-4f98-495c-8a14-fd595b35390b.png)

**Comment by ebogo1** [comment]
@baoxiao1990 Thanks for noticing - this was addressed in https://github.com/CesiumGS/cesium/commit/31dbbc0d6d159b2290193cfb888436140d4635e4. We removed sprintf from CesiumJS so the LICENSE.md entry was no longer needed.
