### ISSUE TITLE
Improve testing for `Model`

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9813]
The specs for `Model` currently consist of a lot of repetitive code that can be refactored into leaner and more concise specs by utilizing the patters used by `MetadataTester` and `Cesium3DTileTester`. 

- https://github.com/CesiumGS/cesium/pull/9806 adds a `ShaderBuilderTester`. 
- What's really needed is a `RenderResourcesTester` that can generate mocks and validate results.
- Lots of good suggestions of testing architecture are in https://github.com/CesiumGS/cesium/pull/9773

**Comment by ggetz** [comment]
Closing as we want to avoid helper functions in specs. They make things harder to debug.
