### ISSUE TITLE
dynamic display enity

### ISSUE THREAD

**Issue by abigstupidbear** [CesiumGS/cesium#9834]
Is there any way to dynamically adjust the display results of entities according to the height. For example, a point above 200000 meters in height, a billboard between 20000 and 200000 meters in height, and a model display below 20000.

What I think of is to establish three data sources to control the display and concealment according to the  height value. Is there a better way?

**Comment by ebogo1** [comment]
Hi @abigstupidbear - please make a post on our [community forum](https://community.cesium.com/) for general help like this. Thanks!
