### ISSUE TITLE
How to use IndexedDB to store B3DM ?

### ISSUE THREAD

**Issue by wikiNed** [CesiumGS/cesium#9839]
Now I have a problem that need your help.I tried to use IndexedDB to store my B3DM.And I have changed some code of Scene\Cesium3DTiles.BUT there is a problem,the promise of localforage and resource.fetchArrayBuffer are different.

**Comment by wikiNed** [comment]
`var promise = resource.fetchArrayBuffer();`

**Comment by wikiNed** [comment]
`  var promise = localforage.keys().then(function (keys) {
    if (keys.indexOf(resource.url) === -1) {
      return resource.fetchArrayBuffer()
    } else {
      return localforage.getItem(resource.url)
    }
  });`

**Comment by ebogo1** [comment]
Hi @wikiNed - please make a post on our [community forum](https://community.cesium.com/) for general questions like this. There are more active users on the forum and some might be more familiar with your setup. Thanks!
