### ISSUE TITLE
Custom Shaders: let the shader control `gl_PointSize`

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#9851]
It would be useful for custom shaders to be able to control the point size when rendering point clouds. This is available in styling language, so custom shaders should support the same.

I'm thinking: 

* add a `float vsInput.pointSize` to the `VertexInput` struct in the custom vertex shader
* in `ModelExperimentalVS.glsl` should be used to set `gl_PointSize` if custom shaders is used (which we consider mutually exclusive with styling)
* I'm not sure how this will interact with the point cloud attenuation... maybe the struct value would be initialized with the attenuation point size and then the custom shader could modify this value if so desired?

CC @lilleyse @sanjeetsuhag

**Comment by lilleyse** [comment]
> I'm not sure how this will interact with the point cloud attenuation... maybe the struct value would be initialized with the attenuation point size and then the custom shader could modify this value if so desired?

Currently what happens is that the point size style overrides attenuation. Probably fine to keep it that way for custom shaders too.

**Comment by ptrgags** [comment]
I just realized what I said above is incorrect. `vsInput.pointSize` would be read-only, we want to make an output variable instead.

it would be better to replace the `inout vec3 positionMC` parameter with a struct that has both `vec3 positionMC` and `float pointSize` fields.
