### ISSUE TITLE
Revert early returns on image bitmap specs in Firefox and Safari

### ISSUE THREAD

**Issue by ebogo1** [CesiumGS/cesium#9875]
After https://github.com/CesiumGS/cesium/pull/9874 gets merged, the `"correctly ignores custom color profile when ImageBitmapOptions are supported"` and `"correctly ignores gamma color profile when ImageBitmapOptions are supported"` Resource.js specs should stop returning early once Firefox and/or Safari add support for the `colorSpaceConversion` option for [`createImageBitmap()`](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap).

**Comment by lilleyse** [comment]
> All good for the Firefox side. We can live with the occasional color space artifact until the `colorSpaceConversion` option is supported, as we did for several years with Chrome. It's worth the tradeoff of actually being able to use `ImageBitmap` on Firefox now.

This assumption ended up biting us for feature id textures. This issue can be closed once https://github.com/CesiumGS/cesium/pull/10111 is merged.
