### ISSUE TITLE
Add statistics to ModelExperimental, ModelExperimental3DTileContent

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9886]
- For 3D Tiles to be accurate with its memory tracking / caching, `ModelExperimental3DTileContent` needs to report the `pointsLength`, `trianglesLength`, `geometryByteLength`, `texturesByteLength`
- `ModelExperimental` should also report this information, could be useful for performance debugging.
- The actual information will probably need to be read by the `GltfLoader`.
- We should look into adding more granular statistics - tracking metadata etc.

**Comment by ptrgags** [comment]
Gltf3DTileContentSpec had one unit test concerning `geometryByteLength`. That file will get removed with https://github.com/CesiumGS/cesium/issues/10049, so just wanted to save a permalink here for safekeeping: https://github.com/CesiumGS/cesium/blob/7ea0e20c671abff80ecf80661413be8e188d926c/Specs/Scene/Gltf3DTileContentSpec.js#L94-L107

**Comment by j9liu** [comment]
@ptrgags what's left to do on this issue, now that `ModelExperimental` and `ResourceCache` both have statistics?
