### ISSUE TITLE
Implement MSAA with WebGL 2

### ISSUE THREAD

**Issue by ebogo1** [CesiumGS/cesium#9900]
CesiumJS has noticeable aliasing artifacts, especially with thin geometry (see https://github.com/CesiumGS/cesium/issues/8228). With multisampled render targets in WebGL 2, MSAA is a good step towards fixing them. 

To implement MSAA in CesiumJS, we need to decide which render targets will need to get multisampled to avoid artifacts. One idea was to start with the color framebuffer in [GlobeDepth.js](https://github.com/CesiumGS/cesium/blob/main/Source/Scene/GlobeDepth.js). There are also questions about how this would interact with translucency passes, and whether there might need to be additional logic for compute commands to perform MSAA if needed.

I'm opening this issue to have a space to discuss the MSAA roadmap and implementation details for CesiumJS.

**Comment by ebogo1** [comment]
## SMAA Screenshot dump

no AA, `viewer.useBrowserRecommendedResolution = false` 
![liberty-noaa](https://user-images.githubusercontent.com/31491650/140558400-b43c8b6d-0eec-444d-8d1c-6c42fc07bb74.png)
SMAA, `viewer.useBrowserRecommendedResolution = false` 
![liberty-smaa](https://user-images.githubusercontent.com/31491650/140558428-758cdf73-926d-4f33-91e3-6a09d403cf32.png)
no AA, `viewer.useBrowserRecommendedResolution = true`
![noaa](https://user-images.githubusercontent.com/31491650/140559731-9e69302b-a8ea-4fe0-b667-d1c288c84f51.png)
SMAA, `viewer.useBrowserRecommendedResolution = true`
![smaa](https://user-images.githubusercontent.com/31491650/140559748-124fd85c-5bbd-4c8b-92a7-3bd14de5920f.png)
FXAA, `viewer.useBrowserRecommendedResolution = true`
![fxaa](https://user-images.githubusercontent.com/31491650/140559768-d214e5f3-1697-4da1-b697-ae1d9bd58b11.png)

no AA, `viewer.useBrowserRecommendedResolution = true`
![lines-noaa](https://user-images.githubusercontent.com/31491650/140561448-4a11e41c-181c-4fdd-b0f0-10ea70309074.png)
SMAA, `viewer.useBrowserRecommendedResolution = true`
![lines-smaa](https://user-images.githubusercontent.com/31491650/140561482-f79604f1-4b9a-47cc-9ecd-94bb7ec45459.png)
FXAA, `viewer.useBrowserRecommendedResolution = true`
![lines-fxaa](https://user-images.githubusercontent.com/31491650/140561498-9c9d8697-c200-4f7f-b8f0-baa25cda288c.png)

**Comment by lilleyse** [comment]
@ebogo1 could you put together a sandcastle where you can switch between a few scenarios (including the two above) and a dropdown that lets you select the AA mode (FXAA, SMAA, None) and a checkbox for `useBrowserRecommendedResolution`? Even better if you could post an S3 link so anyone can try it out.

I've very interested to see how it looks in action. SMAA seems equal or better than FXAA.

**Comment by ebogo1** [comment]
## SMAA findings

I put together a [hacky branch](https://github.com/CesiumGS/cesium/compare/smaa?expand=1) with SMAA shaders from Three.js (see Three's [SMAAPass.js](https://github.com/mrdoob/three.js/blob/a39e8498622d4ca154b0642d1161d9bceeb3f917/examples/js/postprocessing/SMAAPass.js) and [SMAAShader.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/shaders/SMAAShader.js)). First thoughts are that it's seems much more straightforward than trying to integrate MSAA (plus it works with WebGL 1) and looks comparable but better than FXAA. I've posted a few comparison screenshots - https://github.com/CesiumGS/cesium/issues/9900#issuecomment-962126274. 

----

As a really high-level overview, SMAA consists of three passes: 
1. Calculate edges in the rendered scene texture.
2. Calculate blending weights for these edges using two hardcoded texture files. In the `smaa` branch these are the png files in Source/Assets/Textures/SMAA/, which came from the data URLs that Three.js loads as uniforms (see [these lines](https://github.com/mrdoob/three.js/blob/a39e8498622d4ca154b0642d1161d9bceeb3f917/examples/js/postprocessing/SMAAPass.js#L144-L154) in Three's `SMAAPass`).
3. Use the blending weights to perform AA on the rendered scene texture.

In CesiumJS, this means two `PostProcessStage`s for the edge pass and weights pass, a `PostProcessStageComposite` to combine them in that order, a `PostProcessStage` for the blend pass, and a final  `PostProcessStageComposite` to feed the blend weights and render texture into the blend pass. This all happens in `PostProcessStageLibrary.createSMAAStage()`.
  
A couple related resources:
- the [smaa implementation](https://github.com/iryoku/smaa) from the authors of [this paper](http://www.iryoku.com/smaa/)
- minimal three.js example to render a texture onto a full-screen quad: [threejs-smaa.zip](https://github.com/CesiumGS/cesium/files/7488086/threejs-smaa.zip)
- [Local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bZBBT8MwDIX/itXLOmlKxZmuQozjJCQGnHrxEq+LSJ0qcToNxH8nXXdAsBwi+dnve05GDDBaOlGANTCdYEPRpl69X7SyLfSl3ngWtEyhLZb3Lbe8QzYaozhSaMyr926P4TGJeC4XO8ZhsYJDYi02C8uvluEaowKxyeQJA6A9R58Zznflta+RR4xK/BMKvr1s8w62x46qgbucPvm+p6tYFXWUs6NmAk3nwfaDDwIpuFKpSqgfHArFap/0B4nSMc6pAHX121obO4I16xuvBe0wxtw5JOd29pPaoqmrPP/P6jway93zSMHheRo73jXbWVRK1VUubztl/r0/5B8) to print a data URL containing the rendered scene texture (useful with the three.js example above)
- [Local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=tVfbbts4EP0VIi+Vtwqtu61cik3TLjZA0w0SYy9o+sBItE2EIg2ScuJd5N93qJsl22n7sJsAtjycOTPknBmO1kShNaNPVKFzJOgTuqSalQX+vZI590dZ9ftSCkOYoOr+yEX/3AuEDFUKJDdKrllO1UlrmClKDP1DKp7PahVn5N6Ll9HpvbD/a3AoV4ZJocHjFwtV4VnEZ3OC7o/uDDElRXKOPrEHqswGfNYaYEM5zUBrXorMYiBn1JqjZh+YCsMMoxorWsg1veDcsc4HOjqjguKMFFQRrKmx23U6IIRyqg0TxLo46R/LJVEGnogIna0yQn4Y+pGf4tALgtCbTGK3v3ocJXGSTH0cw7IXhWEwXI/8MAnCACegl3pe5MXb1VFPUyoGe9sP6ldKciYWN8xky1sJ2+2DJ9gLgyiO4yj2vSCZpsPQPOzFyRQ00sSPPN8PJskwuAQH0yBMvBQ2lnqBnxyOjYp8pojQc6mKjgvXxCj2HOGrDx8/z65mf3X6DRsOpGSlWAHZW0P6SJ73dtJPQvUVfpgxTiF3/bwhVCre+b+S4pZqWaqM4rmSxYUG9avcmcRhFPajfxm1zy1TXqrV+nOHnzeSbzjUgv4fePlDjESvUfJ4AokOfexFkzSYpNMkcNFxPI3T1Pdw6sdJFKVp6KIAMu15AZ7EURQEvp+8yrLB0SK0rJkGAfg4SPwkBLr7sT+NJ+HEReMxokQbF2Kdk5IbtCYcCplpBCxDjpDKLEdDwJXlLMBZHqaJN4UC8iFwLwlj164D5BDM4VI+2hBy+SR2wBRwH7AAyvNCL44gNs/zkyD1omlyAKyX/wEx60cmmOlS7ezz4mtF4Tsi8gw2zanl60xK/kDUNRWl0zS50UG1xYLT96UxUkCLvaWZLAqoIJqj24pWyKiSuj02ZUuaPdK8IVVDllLT90o+aap6CJbwvKyszlFjdtr1XziC99RA70ZCGmQk1C154BQ9SLNEBCRLijRwEBlWUIzxdyL/5c+LCxvunHD9/XibCpfawK0B94qGTr+Aepg/E4LrQPJDQX8zhLvr/yIEXXw7hHVzTV7LnHJQqK9ARbLHayYqyrlbCXmG+hiIthqrhlGVmT8UWbvYG+pdylIYC1eLNV1Amk1tPRTVXod6A2srX1AzqwNqD2rbqBQ1pRLoc1nAreuYJdO4Cr6mfk18sL8ZRvZDOIPd7ODdDUL9Ibj+7ho0yFSVqO3Ns7Rd9BaoI4va9o7S3AlwbC06miyGOq3bxmlz//RBBdwCQwurYzFfrP8OuCCPtDpqJ7NhuohLAWRT9omY5omJTLUEBYYBL1k7GdkOfwHz06a2H52iVmtJ2WJpQCXwgFXV9tslXlV96+m0ExOr3rqtxHBPI8euMVjxTuHrDFWO4PHt2+7w60+rl7OdCbG7dwJn7xDdPUnbP2uYPQgMl0NBOPubOqDhvuKnQ9mGlcGqHCLKhSKrJcuqK/8DXSgK/RvOpDp4tzm+Fqk59lcQjOy8O5Wn1qzL1Bf2FWzh5yAym4e353az+Bn9VKW5WbepaFY2/ZWXHus68JZUTWqh6sHXsd+kvclsLQ22spxpm26/ltSybQFyO6jUt8O3Bq9eAm72bOtE9Mi+c1fW7Nn3uTf5DEMD9jVRVW0W7zabnlG/A+za9BuK02fMIc4PvA+53/Pzidrzqg52PPA9ZFFXvNvi7yu7TRLdJm1uD37Ixzqmilh7Z2iz041lndOT7WM3yz2x3CxPUNBcPfZPL+XTST1dNPPMdhK3roH4G3DLYJvOMDHHyN+Sv17ABbzpKUb4tnquG0lVe7PNijpvIHSp3rxqi0vB7EuDxplV3OkxVuTYoFzU/4QRFxoiahP7Yr+gUo7cozNtNpy+a/f7MytWMHbatwIH47GhxQrOnurxQwkXvMGZ1m1kZ+O+6VnO1ojl5wdegFHGidawMi85v4OWdX/07mwM+numXFbj8m9rqjjZWLWl/+5TLYTh6mwMPw9bmnqQ3EH+Fw) with FXAA, SMAA, and `useBrowserRecommendedResolution` checkboxes with a few different scenes

**Comment by ebogo1** [comment]
## MSAA findings

I made another [branch](https://github.com/CesiumGS/cesium/compare/msaa) for testing MSAA; to make it quicker to integrate, there are a couple hacky changes to use `SceneFramebuffer` instead of `GlobeDepth`. Only the color and depth textures are multisampled in this branch and if we move forward with MSAA, there is more planning to do for considerations of which other framebuffers to multisample, interpolation options (i.e. should `idTexture` use MSAA; should depth use the same interpolation as color...), usage with `GlobeDepth`, etc.

---

A brief list of changes in the MSAA branch:
- `SceneFramebuffer`'s framebuffer is split into two framebuffers. The first one has multisampled renderbuffer attachments and is bind-ed as `gl.READ_FRAMEBUFFER` during the `gl.blitFramebuffer` call. The second has the original texture attachments and is the `gl.DRAW_FRAMEBUFFER` during the `gl.blitFramebuffer` call. A similar double framebuffer + blit setup would need to be added for any framebuffer we want to apply MSAA to.
- In most of `Scene.render()`, the first of `SceneFramebuffer`'s framebuffers is active. The second, non-multisampled framebuffer is only used after the blit at the end of each frame. 
- `RenderbufferFormat` is made to support the `DEPTH24_STENCIL8` format for use with WebGL 2 and the `RGBA8` format for consistency with the target texture's format during the `gl.blitFramebuffer` call.

Here is a [Sandcastle](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/msaa/Apps/Sandcastle/index.html#c=7VprU9tIl/4r2nyJ2Zi2+qoWJFPLJWTIhIQBJrchtSXsxtaLLPmVZALzFv99n5ZkW5JFBrbIbm3VUglY3X1OH53Lc87p9nWQOteh+W5S55UTm+/OnsnC+ZR8LMZ658+GxfNeEudBGJv0/Fnf+dd57Di5SVOMHKfJdTgy6daCcJiaIDefkjQanZVLeht9SzAEC3OTf5jlYRJnWyUXx0nNP+cmyz+Zi3HEtpw8nZti+R1+321sn8fncSkfyYYmNiSbx7tRkkwh7mUQZWa7NT9LshxCQezsNA/GJiOzIMvOJmkyH0+IiYOLyIxAbDcquUMDwWhkRu/CC5Pmt3XGi6nX8Rgv3zWzG0SQJu6aOk6i2whkWdfku+DCRF0TZ9DRPO3ca8/K3slt9/CoNlxOZMF0hu3HlcIx/6fVa6V2a4ot5/zZ0enOjpNcXsKu5QSWmsgMMXk5j4eW1OltLKgcp6HreD6FyiyLU7tZIds8HplLvPVouyS5Wxize2t682Q704ftyJ5uR/awHcXT7SgetqN+uh11e8dvSw9LfuhZiL58buBbThVY/y2RhsHUpAHJTG4Rqbdc5DgjoEYYB5Z8q45ce0Ga41MQ895qseNQzqmgPuEuY9z1PNmvz24KJZXSlEhMu4Jz1pwXlCvGGVFY57uucOVqdqO2MklDA6RcE+pXE4wQi8dhPpycJFHUEE0RlzMhpRSSukxpvymaS1ypNFb4igqXUuappnCKMM24cn28mO8yqrplM/HoLA3i7DJJp0u4PgryNLwR5HD/9fuzw7Mvy/UV9pYP4aXT+7c6SNbM1TLYLA2nYR5eA3hB0HjPupGKP3z/LISXmbxuV/szT6OlhIdJfGKyZJ4ODblMk+lOBoLDUc+TXPCNhiLuNmpvvr363IL3Cvormsq9+2sRNRg4p8W2W84kz2fZ1mAwDvPJ/IIMk+ngN2SUOMneIK/MBuPo7GCzjJnNo2RkomzQDAa2ObS5AIkSZrC55H83GDaZdKVLJfE9JQTTnDddjmuhBUewYE5IF6puRgPCQStNqM+5J7XmTxgMnPhaMSoUVdadtWwHgw0EyYTnKi5cJZqSIVZcl3IXIktGpRC+plQ8WTy0o6GsC5rBAGCcmHA8yW1KgjTE3W7Nzlq11po+QNN3Fr82WuTQKjYFhzUTF+Gxb8apMVnT3JRx4noCSvVbhgS2uBy6bAyX8nfHkhVhal281NRKjqUuMzJpvdBZchDemNFBCv9tCFa+S3PvWfo3G2PLhyLOwqiWrNDOmyi/7ASb82eEDPCvDOL9IA8G0zKQ2V4VuaWxyTi6WAbv4qemkK36Q3tZGIfT+fQYyohOw78ALJTphyPYsgrtBLCfil+/JrkThKlzUZa7j0SvB+GWcx9wWbBSwCugkSuo4lqrfglRnvaJ1MjGVPkYs7AkqUAO96ivONX3glHLAyp/3XIE4QqY5rs+Z8r3BWsZcGY9egtRyQR1qasFMEprj+vWuhROv1WCEbI1Zy5X3EVidwGrq5V3P8SWqrO4H1zY/4PL/3lwKXlUpm4+PS3QMKkeDjSrpvZhSLNAiWXH+z+LDx5qZ06JKzyfebZ6ADxILX2fusSnEhWO7/O+w4ATiEfioSxgjFL1SHiAAJQw1CUcHQSVVEuPe30LsybI8j5kvQzmUQ5fitD3hJmNL6cXJ2k+2eiAEbCzpb2vXI2ehEJwVDSyXyF3k1kP5riyIoyS7/HGOtY4FdhwVwrIhhJIMQs2qoPZQ/FnacwGAsGx8uVMb81z6mceDy+zzyZoApwgNc7FfDy+dS7MMJhnRe9YHYeQf2TOcBLEY3CGK+QT45weodG9AC4MJ00vtCROZM9Xfoof3ueGXOEHCUkr2JKj+oQXMk9L9GtISb6nXenBXShKbuQwrEPe4mhh2MPccJmjbLeH3CbRxGIjqZtxXWWoTXSyCnu7SrmFDK2WsUpQtbG7H1e6xXnVWi4qtfw3mFlTV8FlD3ubwga9jTYGW/wtmRakDQ3MkiwsFfPj5LTpSUIVKgUFdaOJQbdgf5qt4hKyJmEUAEZnkzBooG2j/3WciCy2f1xyrMnS6HKWYjWHXbdI6t3YHEG/QWQLQNbI+40DxR9FneMUcWdD7vVNkYscK3hXeVi+4pvTQXn+OwizbG6ygWZMt6JtgnphnIajYgSh+tCYW/lWFeNdZwoIBijddHhDONpynofTYGw2hyaKnjejADA0hqe0gTxEeKfDye3fuNBOmga3vT8p1UQjd/g+/IiRwjaIakpRdSIJCGH9SxCkVlENM64wiLVCFwBgxywV1lGiudB2SBO/eEYeot822pk7yE0aBlEDZQ7tax5VM8dpMrMHGe1KAyqxy6CVEQqMreJhMIvH2xdBZpTohx93P5x8d397M0528PP+9I/J6z/G+LR/aJ9v93a+2L/mWIQ39sObzycHn349ObtgX90RO7j9+vvu7tc3fvj1dPftxaeD+OvHt9GXTydyOIyi44Igenvy+uAP8z7NWPr6ZLy3c7T7cXdnwg9PR/7JwZe9q+NP6mZ2dDx6Ed1611fX72Iz+2R2/nl6dbhztc+Gl5MPbwd69uLzxfXnT9e7vx/u7Ywf8v+327N9OYre/XohTg/HQ3518GZn9/M/fo/eH+gd9tm+487u25M/5Ov06u14PH716nm/rbvUzEyQd2M761FmTei6G2t0wyRKVpcfe/aJnLzeJ98RSjtAlQD1tmqT3bWOrRqos/jYiu/VvUBXhD9NCttkGv6rJdobJrnvM5QjyB2uzWDa96VUSmAIWUsiBxHuK+kpj/OfksFcxB76Jt/jFGtcv3UsWmawNVY/TGiN6uNRKDhLk9F8mC9g0PfahS90b+seZ2jvaB4PgeXVTgMBYcJydL3KWl4E/TxX4JpLLj3Uz8LVVLmoqbmSkvlEoYamPvcZR00tbYEhgYFUMnS4wpOP9AUXXT3aaI3e3fckhzuJLm9ATqSon6hAoSwovJS1usqmOzDqwhs4937sDvc2MnzfKU6mnd3Do8cbE0RrlVJeHnQ/or182tNyjST1iMPy8kLx57kXZdyeIRNUxTA/ZTYzbkpXK/RARHGuBadcWJ/jnGlB7Dg6L8Ee7V6Cu0Jxl2vP3vBQcQ/W2BMkn1NlXYtK7en7vUsgHhjcVfsP867ywuw0iEdD9ImRsZY+S5LoIkiPTDzvVddolu7+Ra3b3LI4HQzaBONxZHbneY7a+vzZiQGGTU0MezonRVNeXq/X/Hc4McMrMyrcFXi4sC2ar900+Z6ZtMbD+lU0r0rginDbki2u6auvEhxV5yjl1wTSYHh1FMZFCPdXI8ENuunG0GrFrGoiCzLaHLJ00m2u20vmcW7ZlcOZGUPgvKRuDpW7Ntc1qO342ORnpUALPa3CPDVIwrHzvrgo7eWTMCOF8KXRSy8A/XFTsgfxabxNi99pQ9QHsau/XcXtPL4rDLW66pjY8D2BDyXTkvbUmFGPEWkpll4ybq5ZbFttWoFWnWkMGG1S2DWW553df8l4GlyZQtW9oRWz70RJfJoDJfApyKtPYTxMqx2thy3asKw65ixr9WH5ms5iVf2QtOqVFlNR4b+LnbaXw0Fe9J75avgySZ2enQsx427jz0un2AgfX7xYKr/8bdeNwtbha62EXFNif21kgRwlmzUWJE7SaRCFf5keVvTv2WfJZSXWELNJk2MyTgO0vMNG4wqdFIrvV+pbcKrUfg+HPFnu3it2WpAtLfVn+A20eGxIZu3w4pV9WXLj/Hth5mremqKaua3P3NW8bsl84VSVaY+K0+tNWpm9smw5ylZjozAr7+eKkXJsFYCL84mHH2wcr9GWhqg5e+vkrPSe9T1JaqbJtdmJoqrua4oG76ukKs+d22BTI6ojQJumDii9usd0+Xxj96bv1/Z5Z6y+CsUOGns3vWgZvKvgry/uV0bsV2br19g3/bGUqXCsNR02TguWm26tPi7T9fdwlKMCYGR1FpZNku+1L6I1joLs1nB8+y2CEK/Zaxpm06Er5y8nyKKhX0XPopEvYu/sdmZ6z4u+8fm9tGQeh+XlR9FutjDGDvWsUH2n/pva251VK3ln/xSRUvPJWo9RWnQI3eQNM/1ZyvQvB6mzaAoUWgDfnlx6ykeFdrtVNAaCEvyyvQKzxyV/bZWtgdAERZ30fBTvyyKpxksQl2mfMQ+d3pIX94lnv2SDWsynK16SEobF2vM1kx3MpCYo+ZXUWrt8xQwSCHQn2qVCiRo3eyiLHkZqzrqYcYI+Aq9pLwRXzBRBl+NrhbK0LpkmFB8831e8g5dAG4XyUklalwv7a0mF1QzzVrwUJVoraET6uosXI1CAJxh2rWnMjkpoUXmokmvMJCpsjfdE29SlMm4bPIYeG6X3ihkl1PMoiLFTjZdPtBRc+qLzJbm9BKSu71Ftj7krXugX8Ya+S7myOyx4ecK6hS+EUB2smCZcQQHo8XiNlUc09YpTCYzXeGlsoTxuL4G6mHEC07toGN2VtzIFg3lWZX7dWzWM7tpOVogu3VO8DPzGk5LSFSvYkaIl1fb7YTWxNFTLPCaF9mWZub5VKFLGWHGyebvKMF0nnWtItECGjyjEp6bW9KytdDqwLpsEMxChoJ/Nc1MEvr0NprWevfP4sUQYaQ+Dqv90RXEZ2taosTP2GaF5WPakp8WzzT1kb+f07D8/vH/3pd4jrReGDRFT9HLz7H6A+rYq1iJ02LXEpZrJqqS17II4a+DxBFXMSTneC1FyKHetiCGzeTbpdddcpYSgK1gNk6xXbbLRd5pzWRgv5zY2/q6qedZ/9jLLbyPzy0K1/xFOZ0ma25a/R8ggN+gKYbJscDFHO5aTYZYtJH85qJO+HIXXTjh61fGFbmcYBVmGmct5VNwWnz/75eUA69dIo6Roqz9cmzQKbu2yCf3lXTlICHk5wGM3ZV62si3O/wU) from the MSAA branch with the same scenarios as the SMAA Sandcastle and a dropdown to change the number of MSAA samples. This Sandcastle requires WebGL 2.

**Comment by ebogo1** [comment]
Based on the results from prototyping MSAA and SMAA, we decided to move forward with MSAA as an option for WebGL 2 contexts. The plan is split across a couple PRs, but details might change once I work through more of these changes -

1. Remove unused code from Scene.js and GlobeDepth.js - i.e. https://github.com/CesiumGS/cesium/issues/6763 still takes up a few lines and the Primitive Framebuffer in `GlobeDepth` is unused.
2. Create a new wrapper around `Framebuffer` to manage resources like Renderbuffers and Texture attachments. Refactor `GlobeDepth`, `Sceneframebuffer`, `OIT`, etc. to use this wrapper instead of creating and destroying Framebuffers and attachments directly. The idea is to make it easier to add a `multisample = true` option for classes using Framebuffers without having to add the same multisample behavior in different places. 
3. Add a `multisample` option to the new Framebuffer wrapper and add MSAA. Two big challenges here are -
    1. Managing the temp and copy depth framebuffers used by `GlobeDepth`. Depending on how blit interacts with transparent textures and stencil textures, there can definitely be a cleanest way to handle `GlobeDepth` MSAA.
    2. Finalizing decisions on which framebuffers need to be multisampled when MSAA is enabled and which interpolation each should use if multisampled.
4. (Follow-up) Once MSAA is working, it's possible that it'll expose more code in `Scene`, `View`, and classes that own framebuffers that can be refactored. No estimate on this for now, but it's something I'm looking out for.
