### ISSUE TITLE
Regression: sampleTerrain no longer works in NodeJS

### ISSUE THREAD

**Issue by bkuster** [CesiumGS/cesium#9906]
# Issue
`sampleTerrainMostDetailed` no longer works. Error received: `require is not defined`.

# Reasoning
`require` is no longer defined within an ESM module.

# Reproducable
```javascript
import { CesiumTerrainProvider, Cartographic, sampleTerrainMostDetailed } from "cesium";

const provider = new CesiumTerrainProvider({ url: 'https://berlin.virtualcitymap.de/datasource-data/5d2c8614-d474-442d-8975-c2b4a4c0ae94/' });
sampleTerrainMostDetailed(provider, [Cartographic.fromDegrees(0, 0)])
  .then((updated) => {
    console.log(updated);
  })
  .otherwise((err) => {
    console.error(err);
  });
```

# Fix/Workaround
Use deferred import statements, as can be seen in this commit: https://github.com/virtualcitySYSTEMS/cesium/commit/25f59d6fb7635d3f0547b19419fa47294a02ea38

The question is, if cesium can support this for all its platforms? If so, I'm happy to open a PR.

**Comment by hpinkos** [comment]
Thanks for reporting this @bkuster!  @ebogo1 we should look at this ASAP since it's a regression

**Comment by ebogo1** [comment]
@bkuster I am able to reproduce this issue in CesiumJS 1.73 on Node 14 and 16. Which versions of CesiumJS and Node did you notice this regression in?

**Comment by bkuster** [comment]
@ebogo1 I just stumbled across this issue today using Node 12 and cesium 1.79 (but I would assume the regression is older) while updating my module to ESM. I could also reproduce it in Node 14 & 16 (using 1.79). To verify, I then created a new package with the above code and used the latest cesium from npm & Node 14.

**Comment by ebogo1** [comment]
I don't believe there's a workaround without revisiting how we package CesiumJS for Node - this issue will happen with any file that happens to call `loadWithHttpRequest` in Resource.js.

**Comment by xtassin** [comment]
I am still getting a "is not defined" exception when trying to call Cesium.sampleTerrainMostDetailed from a NodeJS Application with a locally built Cesium 1.97.0

I use require to declare Cesium in my application such as:
const Cesium = require("./cesium");

Most other code methods seem to be working fine.
