### ISSUE TITLE
Resolve inconsistency between getPropertyIds and getPropertyNames

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#9914]
For `3DTILES_metadata`, classes like `TilesetMetadata`, `TileMetadata` and `GroupMetadata` have a property called `getPropertyIds()`, whereas, `ModelFeature` and `Cesium3DTileFeature` have `getPropertyNames`. These should ideally all have the same signature.

We should go with `getPropertyIds`.

**Comment by javagl** [comment]
I actually stumbled over this when creating the sample sandcastles (and the fact that [`// It's all just metadata, eventually`](https://github.com/javagl/3d-tiles-samples/blob/a546b82299ae5700525ba825564f857130a4e25f/EXT_mesh_features/CommonTestingSandcastleCode.txt#L75) wasn't resolved by the fact that I used an obscure approach to obtain what I then called "property keys", once being IDs and once being names). (I'll update thes latest versions of these sandcastles when this is merged).

The more technical question is whether this leads to the respective classes actually being what is referred to as an 'implementation of an `interface`' in the Java world, with the `interface` being `MetadataEntity` here. The name `MetadataEntity` does not appear _publicly_ yet. I wondered whether the goal was to be able to say: "Whatever you have there, if it is 'metadata', then you can call these functions on it". But maybe that's beyond the scope of this issue and the PR.
