### ISSUE TITLE
How to reduce unexpected ripple on 3d model?

### ISSUE THREAD

**Issue by shmike623** [CesiumGS/cesium#9915]
Hi all,
When I loaded 3d module with CesiumJS in Chrome, I met an unexpected ripple issue, like showed in the image below. Do you know the root cause, or how to fix it? Thanks in advance
![issue](https://user-images.githubusercontent.com/93755229/140462864-e1577006-0c78-440d-a9f2-9b893edf6ece.PNG)

**Comment by srothst1** [comment]
@shmike623 thank you for creating an issue :+1: 
Here are a few potentially relevant resources that I would like to add to this thread:
- https://github.com/CesiumGS/cesium/issues/9746
- https://community.cesium.com/t/how-to-reduce-unexpected-ripple-on-3d-model/16016/3
- https://community.cesium.com/t/moire-pattern-when-turning-on-soft-shadows/16011/3

**Comment by ggetz** [comment]
@shmike623 There was a fix for a similar issue in https://github.com/CesiumGS/cesium/pull/9876. I'm going to close this issue, but feel free to re-open if you're still having issues. Thanks!
