### ISSUE TITLE
camera.pickEllipsoid broken in SCENE2D with trackedEntity

### ISSUE THREAD

**Issue by paherbst** [CesiumGS/cesium#9916]
If using the map in 2D and i set “trackedEntity” to an entity, then any time i try using “camera.pickEllipsoid” it gives me points that are centered around lat, lon (0,0).

everything works as expected in 3D.

look at the following example. The first right click will place a point and set “trackedEntity” to that new point, from then on if you right click, it should add more points where you click, but they all end up around (0,0). zoom out to see so.

[Example](https://sandcastle.cesium.com/#c=jVVtbyI3EP4rFl9Yqo2BECIlB1HvgOqQSDgFetdWSCfHOwtWjL2yvVzSiv/esWFhF7iqILHreXtmxvMMG2bIRsAPMKRPFPwgA7AiX9OvQRbVeTgOtHJMKDD1mPyzUAQ/loOCR53AfeEyKyR0Nhg9ja6H8UJtGx8Wyn93GDR4Uc7UhlnKkmS0AeUmwjoUezTEgTe3BpUjUgRe2yD9hwKUkCCimQnPIaQsly7yIEGL/taRtc4tfNFWOKFRXqlrwIzDN6aud9EplwIff8SkfPzzEFGCIxYkcAfJRHMWQvZJpZxM8NcCLqqAH8KIlETnYfp9kqsEUuxs0jjWSP4DkbM1GBYgR1KKzGqR/ARzi333ybtHZl7BjBVaRKU26KVh2Upwmhq9PvTlLM1GEXAbk5RJC8WVprniIbkTiGyfSBmjEYrbXY/cB975HEvDvqMfhLmIDs1QWDC5J/XCqx4XmgKH3J9dbifU9MwSfL+cEJVaLYXLE4jJZT2i7dTtRglSKId4pavKxBvImfjbJ9mNj3KupTal1PyRPo+GJROdO4lXP7hk+e3zeD46t/0mErdC2+uDant4k+wFZDU5TybfPL4C/lovhUt1qKPevsk8X5S2GeNQtrDuXR65PfGxZ15EfxtPJt8/Pg2/T3+fT8ZP/ytJQjZgnOBMTo1YitKVfa3I6afpfD59jE/aO01TnDF0ukzkVkyu7o6XtN2P625uPfP2A+YM46+QjPycvSP5zrl30bA6ryEoQmx3JGg2yV9ar4nTBCdHJQR327v2Cw8X62FC++QS75w+su6ksgo3h7A0ADa6arc79Pr2ttvt3MSkc0tbd527zk0XR7TVCjT1oAluU6Y4IGin1WrR1l7+orFeoZazbAUGqlvxU0V3IEx8CBaCVzaQP524VRHiMsBnYF7zRTi+emZqCVGLYt5X4bfqRw2a5pb8Qrp0X1UFWGr9+tHNsdk21WZdbLRH5ox4u6Hj4ehpPp7jBq/FtV6Y4ofd5f4q1pk2juRGRpQ2HawzJDnY5kuOt42r31qP1msWTr1EbIhI+ovayb/goka4ZNaiJs1lYP+i9tBron3FTepQ9RSHX7J3b7JqP0x2Qkppr4nHcy+ntXxhphTxXw)

**Comment by srothst1** [comment]
cc: https://community.cesium.com/t/camera-pickellipsoid-broken-in-scene2d-with-trackedentity/16004

**Comment by ItayBa** [comment]
Having the same issue.
Does someone have an idea to where this bug might be occurring in the code?

**Comment by ItayBa** [comment]
Same as #3242

**Comment by ebogo1** [comment]
At first glance I suspect the bug starts somewhere in the different behaviors for 3D and 2D in `Viewer` when a tracked entity is set.
https://github.com/CesiumGS/cesium/blob/10112c84d7de58067b04ccb641772165af4ba81b/Source/Widgets/Viewer/Viewer.js#L1417-L1456

Since this very similar and likely related to #3242, I think this issue should be closed. We'll post updates to this bug in the other issue as soon as we get a chance to take a closer look.
