### ISSUE TITLE
I load a model（gltf,glb), but the display is wrong

### ISSUE THREAD

**Issue by panergongzi** [CesiumGS/cesium#9928]
1,in Three.js，Bybalon,Filament is normal

![图片1](https://user-images.githubusercontent.com/34262259/141405823-f7bd9e09-c61c-4c55-ba21-2c30fdecebbf.png)
2,in cesium There was something wrong with the tree's leaves
![image](https://user-images.githubusercontent.com/34262259/141406007-f688f799-e2b3-4f31-8b8e-4c0d75a724ed.png)
the tree data
[tree.zip](https://github.com/CesiumGS/cesium/files/7524752/tree.zip)

**Comment by ebogo1** [comment]
Thanks for reporting this @panergongzi - I can reproduce this on macOS in Chrome and Firefox, and this definitely looks like a bug on our side. We'll post updates on this issue as soon as we get a chance to look into this.

**Comment by panergongzi** [comment]
My development environment is in windows10,chrome

**Comment by ebogo1** [comment]
A couple more data points: 

- This model from Sketchfab works as expected both with `Model` and `ModelExperimental`: https://sketchfab.com/3d-models/trees-and-foliage-c3423a86515444a2b323d422ac16e710
- The model in the original issue post has the same artifacts with `ModelExperimental` ([Sandcastle](https://sandcastle.cesium.com/?src=Model%20Experimental%203D%20Models.html&label=3D%20Tiles%20Next))
- Is it possible this is related to the `KHR_materials_pbrSpecularGlossiness` extension? The Sketchfab model does not use this.

**Comment by ptrgags** [comment]
@ebogo1 was correct, it had to do with handling the alpha from the specular glossiness extension. I opened https://github.com/CesiumGS/cesium/pull/9943 to fix it. 

![image](https://user-images.githubusercontent.com/8422414/143905422-7fb8b33c-54de-4abe-8d49-e395d2ddbfe2.png)
