### ISSUE TITLE
Navigation and Compass 

### ISSUE THREAD

**Issue by abhijitgujar86** [CesiumGS/cesium#9930]
Navigation and Compass are one of the good default features to have to make the map look complete. There are other library that can add this feature to cesium ( external dependency ) but i think this feature must be a part of basics.  

here are few reference examples .

1. https://github.com/alberto-acevedo/cesium-navigation
2. http://larcius.github.io/cesium-navigation/
3. https://www.npmjs.com/package/@cmcleese/cesium-navigation
4.  https://github.com/dvgis/cesium-widget

**Comment by ebogo1** [comment]
Thanks for the interest, @abhijitgujar86! If we get around to implementing this we'll post updates here.

**Comment by cavencj** [comment]
@ebogo1    I have also made some widgets extensions based on Cesium at   https://github.com/dvgis/cesium-widget
Can they be merged into your organization?

**Comment by ebogo1** [comment]
@cavencj Thanks for the interest! We'll take a look at your repo when we get a chance. Were you thinking of opening a PR into the CesiumJS repo?

**Comment by ggetz** [comment]
Thanks @abhijitgujar86 ! Navigation widgets like this are great additions to a cesium app, but ultimately I believe widgets like this are out of scope of core cesiumjs and belong in a component library operating in a layer above it. Widgets like this can also be difficult to generalize for all use cases. We probably won't take on this feature anytime soon. Sorry!
