### ISSUE TITLE
how to use the translation of Cesium.NodeTransformationProperty API

### ISSUE THREAD

**Issue by fanfafafanfan** [CesiumGS/cesium#9933]
Please provide a demo，about translation， thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ebogo1** [comment]
@fanfafafanfan We have an example of using `NodeTransformationProperty` in the [Time Dynamic Wheels Sandcastle](https://sandcastle.cesium.com/?src=Time%20Dynamic%20Wheels.html). If you have any specific questions or need more help, please make a post on our [community forum](https://community.cesium.com/c/cesiumjs/5).
