### ISSUE TITLE
cesium warning in node terminal

### ISSUE THREAD

**Issue by biqbalgis** [CesiumGS/cesium#9936]
I am using ol-cesium 2.10.0.

when i run the project i have the following warnings on terminal.

WARNING in ./node_modules/cesium/Source/Core/buildModuleUrl.js 80:25-32
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/cesium/Source/Core/buildModuleUrl.js 114:14-21
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Thank you

**Comment by bampakoa** [comment]
@biqbalgis you may find #8401 useful 😉

**Comment by biqbalgis** [comment]
> @biqbalgis you may find #8401 useful wink

Yeapp. A great thread. thank you. :)

**Comment by ebogo1** [comment]
@biqbalgis Thanks for reporting this. Since this looks like a duplicate of the linked issue, I'll close this one. If anything new pops up feel free to leave a comment here or open another issue.
