### ISSUE TITLE
Move 3dtilesFeature

### ISSUE THREAD

**Issue by h2936817294** [CesiumGS/cesium#9937]
when I pick a feature, Can I move this feature alone?

**Comment by ptrgags** [comment]
HI @h2936817294 , yes this is possible with the new `ModelExperimental` and the `CustomShader` class, though there are some limitations.

[Local Sandcastle Example](http://localhost:8080/Apps/Sandcastle/index.html#c=nVZtb9s2EP4rB3/oZNSh5CRtFycu1rpxmy1BisXrh8FASksnmytFCiRlJxny33ckZdlNXz4sCCQdeXe8u+e5o9fcwFrgBg2MQeEGJmhFU7FPYS2Z9/IgT7RyXCg0817/dK7mak12tbbCCa3IsrWacOPoi6sjVhpdvcOlQbTJXAEcDA+PWPbq+Pjl8GTgF46PWfYiO3qVvQxiNlfes/e7qp8E8wF5IdTyo3D56k8tZZINwP9vDUpxh8XU8ApnhitbalPtYuqWLJM65zLq6Wln8x4pL+60CXHOe0obt5r3BlHaoHXzXgyOTgtlYTl5+sLyxhhUbiYq3B33eyMp/3fcYSjBhdW/vsyGrevD7HBIhTgYZrPsZHT8anR8wrK/d+7TFGYrBIsSc4cFVLpACUmUCScOEksHuRT5lz4IC4YLS3pCOQ2OLLkwQErCOYmwEA6cDl4LrLSyjtJEcrqmYhJ6xoNnQZdkEk/aCLeCErlrDMLFO8tiffPGOl3drHjxlCaTvZ3kX59ko0Qo9giCSAu323Sm0XG3A+DuaxJbX39Fyxmtsenl9ZvZYKu25rIhvaMoP/rXY9hcI/HtLh4/wzs3gs9hWYui3bsi1iafwueFqhsqog3vAdVMk5g/VLch96hz3bioFD/621BFCUlrybhzRiwaIjprS3VR3GYwHn+ban+XaoCWEKupRUTeSCrrUs6mbeFX3AK/Q3pIsVSEaEDifHI+hVxrQ+wn5OwArIbnDwS8+sXBnmeDXMp7IlhTE3GBgiM20GF2pRtZwAKJMtoiIOW8XBEpYIkuEKbWxB3gudHWshjhJthstPmyf8SC+sCXwRsV3HHYUMgh+MA/zzrfXYDcuoPQQgdNDaVvMNbh2JaVbSfH1YQ9wPMxDLOMZaf78PrH54AxuVhW1GbfR3m7G3CetkJEuvwB0ldUSiMo1Kr96FAqpeYOOlCJ6uXPMU/hpIt7640Voiwb60fCGvOjpNOngcWy8Oif7nKcq8fdRI1kGLcTmdmcRhOrjaioWms6mxdFEk9re+bKG5zf1XSyT5xO90PnvXRl0jFvSdKIuJHe1JjblEYTT4OdTb3ipfZ1Td82Qvoha6/QcQ9w6umZLrbLB1W7zry/djz6v/3hMPpKalUe+/4dk4SYIiPCFvcfKVQaX4wopZKyUXm4TJKg0WGynbjEI8NZKe9n+q1ulI/ppl6hwajPFl8tDnaNVzQ09cjxiCr/ogspIrCrvNLUMGS9nbxjOIyU9JsBhyewbO8qrgr5dCre5HTtqZua53i+Jlg+RKUk4plzsrT+6NaYWYyUfRMq8FUp1uhxbasRLl0a/VhcL/7xN8IYWorQYqfcdVdM0o+uNq4CS7rDi2TfRx+ePYOf7LPbjsD9DpR9lH307eimnwvfjEA/j37kL4IAxET8n56fwNY11uPgR1iE6+XyfDq7nVxeTP7on/YGvTPr7iW+3jLmN1H5yxEaIxPGUodVLf34pWagPBzLre23TX+W7pueFWINohh/51cTDWBuLe2UjZQ34oGif32Wkv43pjSDPI+v6f6S/N6rrYavL+MiY+wsJfH7lk5rueDmief/AA) -- in this example you can click a feature, and that feature will be moved into the air a little bit 

| Click one building| Click a different building |
|--|--|
|![image](https://user-images.githubusercontent.com/8422414/145473996-25674732-ce6e-4957-a7ea-090ec8e7e0e7.png)| ![image](https://user-images.githubusercontent.com/8422414/145474051-c84191bf-1486-490a-afdc-db90e1df9037.png) |

How this works:
* I use picking to select the feature and get its ID. 
* I pass the ID as a uniform into the custom shader
* In the vertex shader I use the value to adjust the vertex position.

A couple of things to note:
* This example relies on experimental code. Some details may change in future releases
* the custom vertex shader is designed for small adjustments of the position. if you go far outside the model's bounding volume some details may be culled/clipped
* This method will work best when the model's coordinates are predictable. The model I used here is not ideal, as +z doesn't point exactly upwards here. But this model comes with CesiumJS's unit tests.

I'm not sure if this is what you had in mind. If you have further questions about using CesiumJS, please see our [community forum](https://community.cesium.com/c/cesiumjs/5).

**Comment by lilleyse** [comment]
@ptrgags this might be a useful thing to show in Custom Shaders Models sandcastle once we have an ENU-aligned sample model.
