### ISSUE TITLE
WebMercatorProjection has a background color

### ISSUE THREAD

**Issue by mylove10086** [CesiumGS/cesium#9949]
I have a problem, ask for help
When I add the image of WebMercatorProjection to the map, when I set the background color to other colors during reprojection (ComputeEngine.js), sometimes the background color appears in the reprojected image.As shown in the picture below, I can’t find out where my code is wrong, is there any possible situation?
![1](https://user-images.githubusercontent.com/41406024/144198916-ecc44b36-3718-462c-8181-16a76b21134b.png)

**Comment by mylove10086** [comment]
Now I find that the reprojected picture has a background color. But I still can’t find the reason, this is the projected pictur
![1](https://user-images.githubusercontent.com/41406024/144565339-d274860f-1752-41e7-a9ed-3f337e70d370.png)
e

**Comment by ebogo1** [comment]
@mylove10086 For general questions like these, please post in our [community forum](https://community.cesium.com/c/cesiumjs/5) - we have many active users there that are likelier to see your post and have suggestions. It might be helpful if you include some sample code as well!
