### ISSUE TITLE
glb model load uncompleted

### ISSUE THREAD

**Issue by vmoeak** [CesiumGS/cesium#9959]
I use https://github.khronos.org/glTF-Validator/ check the glb file, it passed check. But when  I use cesium load it, it only show part of model.
![image](https://user-images.githubusercontent.com/30279416/144575591-9bdc5773-925e-4d01-9008-dc039438f98e.png)

**Comment by vmoeak** [comment]
This is my glb file
[flight.glb.zip](https://github.com/CesiumGS/cesium/files/7648136/flight.glb.zip)
.

**Comment by hljwkwm** [comment]
I have the same situation.

**Comment by zero406-CC** [comment]
我想是因为不允许vec3 和vec2共享一个bufferview造成的，比如你的位置和法线可以是一个，但是纹理坐标得另外一个bufferview，可以试试。

**Comment by zero406-CC** [comment]
I think maybe it‘s because vec3 and vec2 can not share one bufferview,u can try split vec2 to other bufferview。

**Comment by j9liu** [comment]
I'm able to load this model properly with the new `Model` implementation in the 1.97 release:
![image](https://user-images.githubusercontent.com/32226860/187968533-dbb482ae-89e6-4b35-8d5d-37a60a2a2146.png)

Closing this issue now.

**Comment by moxuanzhu** [comment]
I have a gltf  load uncompleted in lastest verison, thr url [https://sandcastle.cesium.com/?src=Hello%20World.html&label=Showcases&code=eyJjb2RlIjoiLy8gR3JhbnQgQ2VzaXVtSlMgYWNjZXNzIHRvIHlvdXIgaW9uIGFzc2V0c1xuQ2VzaXVtLklvbi5kZWZhdWx0QWNjZXNzVG9rZW4gPSBcImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpxZEdraU9pSmlaamMzWW1RME15MHlZV1kzTFRSbU56RXRZamhrT1MwMVpUTTJaV1JoWm1WaU5USWlMQ0pwWkNJNk5qVXhPVGNzSW1saGRDSTZNVFl5T1RrME5EWTNNWDAuMDJyalBBRGhtcHkyc3ZvUlhPYnJPUHp5Tkt3SWlnNVBTRHM0M0Nvd3dnZ1wiO1xuXG5jb25zdCB2aWV3ZXIgPSBuZXcgQ2VzaXVtLlZpZXdlcihcImNlc2l1bUNvbnRhaW5lclwiKTtcblxuKGFzeW5jICgpID0+IHtcbiAgXCJ1c2Ugc3RyaWN0XCI7XG4gIHRyeSB7XG4gICAgY29uc3QgcmVzb3VyY2UgPSBhd2FpdCBDZXNpdW0uSW9uUmVzb3VyY2UuZnJvbUFzc2V0SWQoMTQ3OTM2NCk7XG4gICAgY29uc3QgZW50aXR5ID0gdmlld2VyLmVudGl0aWVzLmFkZCh7XG4gICAgICBwb3NpdGlvbjogQ2VzaXVtLkNhcnRlc2lhbjMuZnJvbURlZ3JlZXMoMCwgMCwgMTAwKSxcbiAgICAgIG1vZGVsOiB7XG4gICAgICAgIHVyaTogcmVzb3VyY2UsXG4gICAgICB9LFxuICAgIH0pO1xuICAgIHZpZXdlci50cmFja2VkRW50aXR5ID0gZW50aXR5O1xuICB9IGNhdGNoIChlcnJvcikge1xuICAgIGNvbnNvbGUubG9nKGVycm9yKTtcbiAgfVxufSkoKTtcbiIsImh0bWwiOiI8c3R5bGU+XG4gIEBpbXBvcnQgdXJsKC4uL3RlbXBsYXRlcy9idWNrZXQuY3NzKTtcbjwvc3R5bGU+XG48ZGl2IGlkPVwiY2VzaXVtQ29udGFpbmVyXCIgY2xhc3M9XCJmdWxsU2l6ZVwiPjwvZGl2PlxuPGRpdiBpZD1cImxvYWRpbmdPdmVybGF5XCI+XG4gIDxoMT5Mb2FkaW5nLi4uPC9oMT5cbjwvZGl2PlxuPGRpdiBpZD1cInRvb2xiYXJcIj48L2Rpdj5cbiJ9](url)
