### ISSUE TITLE
Disabling baseLayerPicker in Viewer messes up pickPosition

### ISSUE THREAD

**Issue by GimpMaster** [CesiumGS/cesium#9985]
I found an interesting bug. I've been looking at the Draw On Globe example where you can draw path's and points on the globe based on mouse clicks. The demo was working great but my code had massive alignment issues on where the path's and points were drawn. 

I finally tracked it down to disabling the baseLayerPicker on the Viewer. If you set it to false the pickPosition no longer gives good coordiantes. The more you TILT you screen the worse it seems to get. 

See the sand case below where all I added was baseLayerPicker: false.

Sandcastle example:

https://sandcastle.cesium.com/#c=nVdtc9o4EP4rOr6cmaEiaZt7IWnnUkIb5pLCBNrMXekkir1gTY3kkWQId5P/fitLxjYveTm+ANLual+efbRaMEUWHJagyDsiYEm6oHk2p1/ztWDSCPP/XSkM4wLUpNEi/04EIRoSCA2Xoi8iHjIjVYdMWaKhZXe5mMoP8r66dMc0XLAVqCEPf8BamrTb5OTVK7RnDBczYqTbIHcK2A9NTAwkRY2h1NweZ00ZUAq9GSq54JE15Z0OUcXAtVRJNHYiQRPPfmgeT1CPT0nwk4uV6hAE0KrdUZamUhmImi6+JReRXFKWgDKYhnHMNboklxozFUnQREhDtFOqOUgnDXvegz3Sn+ZyeM2jGRg8WgGIUcpC6C1AmHMmIjyEKpjLBfRFmpnTPLGBdcNHNtpQGq9SoBe9j+Obs8GXDxe9m+5Fv/vnRNiTp5nI9YlLx1ByYYKlTUrhog9xgbVP7S6W3nuKplECNGVRFORCBEWcVofUjLSKXTTQIV6WkFAmsqxI1/6j1+f9ca9VSKT8HpIR/wc65Gi9GAOfxeYKpqBAhLA2cF5fp92L08vhzXhw8+lq8OXzmdd/yL/zOhOiwGRKOMdcIWygkWJY0tmljADDnTQSRPOkUU2XlRjFLIWgiPiMGVbJlbab+REWSjWD70qTzSIXufjjqbXpS1ZWr5LBMuO6Q6qutEqJMGHzdCw/KZmJqEOMyqCyu+SRiTvkzXrpociTy9ADAdthu6OwHs2wz/5HIDMLkkocMQfFVBiv9sYxR4AqzpJOlXty0Fz6HWzyFFtwFZRKZAe66JKb+DRJYxYc0F+bpXBzbxIqWCkq67HCEBALyLGQd4/G4L99P97a9CvTRDLLXUOPOLsWu66uk+pod+sHBU0wVNXWO69NkRSrhLCGagBW3RcICfQaSIYFvd3LbrfYYAorLrQBFhE5XcuGbI5FyoV7ScJTLXl0S7RE4mXGm18CQebKqTiUSiHve95YxiDIXGbaMjeylyqomRY9A0yZuPCixNC2hy4kWuDE1QjPvq1ZuEVsJwm5w3hFBFNsnMjCWGYqdwMjdMTsfEF/Z4m8A1r0rK+D1wxqpptrvFvJLQjQBMTMxHmTHDRLlNeKjwFWSbdu/7hQ2badZjreJ52T10qwOQ+LTV2HVZclyR3DVBatUuKkWW3H5/a7+/jWqJwzdJLnRVdvJ6n02vdXzdSW+HHZmu7S35kjDLak5s1MFBr+tJek9olKoUV068n7N7943YDxoq7dAccalEo4WgBgFV7QRCCizWB3HFex2dwH6HU/2qC+siSDmtpjkJZp8CTkd9h6eF7uLwdfRr2by8HXnlVEnrgCC5K85919hRTGzc+ODjxqCBaIuDkrFyyWcwVaGQWQxeZcIDoc6Hx2HguyROiepti8PJ0bGzV/TLJi18ltMs+aEY83nH1sr36/PbwQxJt5On6yblf9T+e1prHolmnBat+sVQ9FA/c4WE4aZ7auF+i8xseH20Lh/PmBj4hdVJdP+t6Lnk3jivpJXQ/9vKUHongiVLupWSPB+hugwo1PvgeKU4gDk7sSG5WppKS+iSh+7sim29g7u1Zm39a+zHnWfnbynu3F+uLYcuR7XtkRIilk2iRgJ8WxlHhJqUsQWeDr7Tv3bynnOJnYlx/DSwJZmdhhzl7o+aNTl+8oN6skUv44NdXnURfpG38x8YZOlZyfwQyhp4NXh69f09cHR7+1yNtf6OHvR0ctcnhwcEAP3FRYu0MLC8FRLtEi9e+me1zt8mSsmNBTqeYFw+Lsqvj9W9o/630e98d/WcVGq3GizSqB90U+/+DzHCyZSgJK2wbmaYJp1+27DB/IhoZ6fbudtKuqJxFfEB692/E4tw8DrXFnmiX5G2vSeH/SRvktVSSPCKs5wEEpYSsrFh++v3CLlNKTNv7drWlcJTcs/wc

Browser:  Chrome / Edge

Operating System: Windows

**Comment by GimpMaster** [comment]
I should note that if I set viewer.scene.globe.depthTestAgainstTerrain = true; 

The pickPosition is accurate...however I then have issues with billboards and points being depth tested against terrain and drawing underneath.

**Comment by ggetz** [comment]
I think this is a combination of two other issues. The `pickPosition` due to `depthTestAgainbstTerrain` value issue is detailed in https://github.com/CesiumGS/cesium/issues/4368. That value being set by Viewer and BaseLayerPicker is discussed in https://github.com/CesiumGS/cesium/issues/6991.
