### ISSUE TITLE
Support for KHR_mesh_quantization & EXT_meshopt_compression 

### ISSUE THREAD

**Issue by wallabyway** [CesiumGS/cesium#9987]
Hi Cesium,
I'm in the process of testing cesium with gltf datasets, for 3d-tiles-next.

My gltf files are compressed with EXT_meshopt_compression and KHR_mesh_quantization, using [gltf-pack](https://github.com/zeux/meshoptimizer/tree/master/gltf)

I noticed support for these glTF extensions, is in progress...
https://github.com/CesiumGS/cesium/issues/9520

I'm wondering, is there a preview of this, in a feature branch somewhere ?

Greatly appreciated.

**Comment by lilleyse** [comment]
Try setting `Cesium.ExperimentalFeatures.enableModelExperimental = true` before creating an tilesets.

We're in the process of refactoring the glTF loader and some new functionality like meshopt is behind this experimental flag.

**Comment by wallabyway** [comment]
That did it - thanks!

![Screen Shot 2022-01-05 at 8 31 11 AM](https://user-images.githubusercontent.com/440241/148256864-52a2703b-e921-42d9-9ad1-600a79e5e2f4.JPG)

I'll add it to [here](https://github.com/wallabyway/minimal-pointcloud-gltf)

**Comment by lilleyse** [comment]
@wallabyway great!
