### ISSUE TITLE
`ModelExperimental` - Default material

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#9992]
According to the [glTF spec](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes-overview),

>If material is `undefined`, then a default material **MUST** be used. 

The "default material" is described here: https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#default-material

This should be easy to handle, there's a couple things to check:

* Ensure that the `MaterialPipelineStage` doesn't throw an error if `primitive.material` is undefined. A no-op is probably okay
* Ensure that the shader defaults match what is described in the spec
* find a model to test with

**Comment by j9liu** [comment]
@ptrgags and I found that gltf-pipeline creates a default material, but we should make sure that for other things loaded as `ModelExperimental` that a default is created, and that the shader defaults are as expected.

**Comment by ptrgags** [comment]
I confirmed that `GeoJsonLoader` and `PntsLoader`.

However, I think `defaultModelMaterial()` in `ModelExperimentalFS.glsl` isn't quite matching the spec. 

According to the spec, default material should have:

* metallic: 1
* roughness: 1
* baseColor: `[1, 1, 1, 1]`

In other words it should be a metallic but rough material, whereas the shader currently defaults to a smooth non-metal.

**Comment by j9liu** [comment]
@ptrgags From a glance it doesn't seem like the material struct for `ModelExperimental` has a metallic factor, and that the other fields (`f0`, `diffuseColor`, `roughness`) are derived from the metallic factor in `czm_pbrMetallicRoughnessMaterial`. Should this be invoked with the default metallic roughness values in `defaultModelMaterial()` ?

**Comment by ptrgags** [comment]
I agree, hardcode the computed values. I think they'll all turn out to be straightforward constants like `vec3(1.0)` but better safe to check

**Comment by lilleyse** [comment]
Technically we can use whatever default we want in `ModelExperimental` but it's good to be consistent. I get these values:

```
czm_modelMaterial defaultModelMaterial()
{
    czm_modelMaterial material;
    material.diffuse = vec3(0.0);
    material.specular = vec3(1.0);
    material.roughness = 1.0;
    material.occlusion = 1.0;
    material.normalEC = vec3(0.0, 0.0, 1.0);
    material.emissive = vec3(0.0);
    material.alpha = 1.0;
    return material;
}
```

**Comment by jjhembd** [comment]
Hi @ptrgags, I'm looking at this and have a couple questions.

> I confirmed that GeoJsonLoader and PntsLoader do create a default material.

Is there anywhere else I need to check to make sure we always get a default material?

Also, in [PntsLoader](https://github.com/CesiumGS/cesium/blob/main/Source/Scene/ModelExperimental/PntsLoader.js#:~:text=const%20metallicRoughness%20%3D%20new,metallicRoughness%20%3D%20metallicRoughness%3B), I see this:
```javascript
  const metallicRoughness = new MetallicRoughness();
  metallicRoughness.metallicFactor = 0;
  metallicRoughness.roughnessFactor = 0.9;

  const material = new Material();
  material.metallicRoughness = metallicRoughness;
```
Based on the spec, do we need to set `metallicFactor = 1.0` and `roughnessFactor = 1.0`?

This is my first time looking through the code, so let me know if I'm misunderstanding the context here.

**Comment by ptrgags** [comment]
Hi @jjhembd,

>Is there anywhere else I need to check to make sure we always get a default material?

At this point I think it's really just `ModelExperimentalFS.glsl` that needs to be updated since that's hard-coding defaults in the shader. 

As far as the `ModelComponents.Material()` goes, I think we covered all the main cases in the above discussion, but I guess it doesn't hurt to do a search through the code for `ModelComponents.Material` `ModelComponents.MetallicRoughness` and `ModelComponents.SpecularGlossiness` to double check nothing is hard-coding an unexpected default.

>Also, in PntsLoader...

That's a good question... `.pnts` not technically a glTF file in the first place (unlike .b3dm and .i3dm which wrap a `.glb` file). So I don't think this particular case has a correct answer, it's more about what we think looks good as a default. Might be good to compare `Model` vs `ModelExperimental` rendering the same `.pnts` model and try to make them match.

**Comment by ptrgags** [comment]
Oh @jjhembd here's [A modified Sandcastle example](https://sandcastle.cesium.com/#c=3RsLU9s4+q9oubmp0waTBNqyoXSOhsf2hmwZoO3MlQ6r2EqiotheyYZkb/jv93162HJiKH3s7aOzG2JZ+t76XlIGTPFiFh7MMyb5jCU5FYeM5oVkKmQJHQk2TGMm/Pdkl+SyYDsXSZQmKifXnN0wCaMJuyEDA++dHgsu1iL9PEhhIU+YvFhrk/9eJISkMmbydRKzjMFHkp9LmihRRCyJFn0ypkKx9kVy2wIsF4nBEEYija7CqJASFwA1gNPi+3chOE32ac7CsUxnr1W6/azTDRDTxVqv0+uud7vrnR/Pe51+73l/83nY6T7rPNvaev50c2v72fbWj5vP/3OxdpEYfBsbRHNNslTxnKcJTyZk98v+IRwjHwekonZAZQ7faLKpqd1nE8mY0tSud3ubYef51taz7o9tHNjaCjtPO5vPO8/0Y8fQaCBPsyWx/8RoDLSe8DyanqZCBJ02wf+qJWM+Z/GhpDOmJT5O5ayiqxxSIYgaLEHPSw/LNUcMdEjzVFrJJqnMp6BT83TDVF4T4qBQeTojZ1MKyib7bMwTLQlFvkSKAGhf0skElZBPGZmlhWLkhgtB2DyjSbyhppInV/Yl6C103Jr3WpeWiJq4DH3mTaDNski45r9vrJQQQP6ORcAxQU0RARYGcGOgh4Ct5gAxTyuqzJriEt+XIAjJFxnrO6RvDYpzGAvfHQx6bTfrmooCpvn0OTvpBZ0Q9Rh2Wnb6rf5rPq8ZTJsbNs7ZPO+TX0riX489mXGlKZ+w2FEt+WSatyvJkYlMb9RDVws2ri02erDLr1MeW9KGsPeDd/rr6yQrwGUo/bdNeJLCY/Tb7FJDMHPeFLmZZL60DLxSmqR8E7qtNRyQJ7soni55bMUfzuGrxRPSPJd8VIAwQzDZGRXDwY6Vo/nzS+VszObnY458ToFpZSwHeEYpILcxG9NC5GQG1iA5Fc7cgHb0nFbDD7M4gRoA09ZGWhrJsT8anrw61YpGGfWbQOG08PTg5HhvcHA53Ds/OH29d6yXADd7WSYWmm5LX2WyALxNQC7w9ZrVpkQpeGieoLlbMJSMeE5gHogCfa9KCc8fKUITjnKIQ5w3BsljlGgwRm0P7r22iEP7YGxifIdNDK2QS2nX7aFRgTN6xYDgaMqiKyZHKZVxydkNz6dANKEim1LgmeaAMZKMKqbMS5CDhhJzOkkTwJwUsxHErmRcJJH25Ah/4AE/N7ADi+OM/8ZahkBjGDVCjEG85Um+vSclXQRbYKneyvqT4ckBmtH5vqNql/Rgqo+TrJNuSxs22B8JBAPWYFpnB/688IHCwJMnLSfCcvInM/nT8uRP3mRHCYewPYf5fIn4J+TTjpuJIQA5d547o5LnC5Iar7IkXjLh16CButY8SBlsYiaTsE5GXEmD13DzMQnKl/8EUUE0gUDouxEAqoBrpEX9WlCwDQlmTN4zkiawYxJmPJ2bAy+BNpokTPxQAfGp/YCa1IL5iNp5+rSk5tZjJAVg8oZjDGOP4mUSAOFIUMhzyCvYBRQNBIQCL6gAG40XHiAdTakAqWs6Owr3ZALgUd5IPYwDKhYaC7KrUNuIz9i/ZagNlpU1agUAf4DQA8x8LCXfyDJIfxPZDmAqjDk4LbLhW63vdvWHZGA6ie8jz2teNLAKwxga6/3SrxFg4+ENj/Np37dE+2LK0JU2vcG8Ik0eoSmDYWUpxvY26ITc0AS2rOQqq29cFk+YDW4zkP2YRxS9wSEXsL6/RP5wZUb488He6cHZuUU/o5PPwlidUgOiHd6tiz7RqkMCddzlqrZLZ/nWRrUar56xE4q7ckbVVROmIYx/ZW5VXPqAHpIvne0NT44PTi97+8tZUwPzDZlSY3iC1PX3DFAaNIt6aIEDjKogp/FqXuLeXnZ2auu2loOHNeTeflCXX7tE0PIgOJpCyGjGmL+ARfB5sDzcRlSbgU4wawhD2bovUxqkAtyJ4KvhVmcVGIZ1VoGFBXh/rO5AY3KhA62G4PucJvvaQzf1lzEwYChhUPMqzeOUJejeMZGrFKH9Ls7lqip60UFBTd3+Y3KoP52J1i1wMmqabeLX0lx6n7E2OjqIbxGIapoKSD54UiXGTcb4E876a3u7v7EhYcpXtxzyUtfMPnn4L+Yqgvfe0tt7zOYci0A2p7NM6CIYLCZmM7QNCUIwFpUm1yA73doAC451kpVKjmPJpPRzlp2QPJlbQGUNDhVJTJ4scFg3Gh4/HqU5Nk9wUpo9fhxWtJilI41WcZUDFlO4vGejo2OfGL1olQkqVI0HBeZ/4wpcSnAfMuyxkYzPIf6jQdK8reHoHQKgIopB4/ToVbhUFh1JGiPfLs+o1UEKKwTMjJ/tVINVZrdaGm1CJqlMTaRsMdRc3KgHVTXqQeWMaqhjMB+qykTrJ0CNMZfMMB/46mz5m9sw92HTy5Q7mCnXEBxJBtFiFcXCR6FNo2YYn0PURUTcRzQCD4Im1DEVPH5NZzx3FXyVm39tdl59r+fmajUp94a0qR1qSyud4Uk1FoKpNeS8k7q12Xx3xQbr6Yrf56AiheDMc0XevvObHuEyhq/2+g7At3n8JUb/NN6+IXj7TtuR3b4/DLS8IN/og+9qAM+wU2eaWyevTo2wlFOdeXkykn/j3u89Wkd7Fzy60qFFUw3k6uR7WVwPsZHrr7eRsUipkds+RCuaRGglgiWTfBoYeflR3MwGOjm1pyZqlqb5FOJcZkSx2dF/fIAOAPBcraRxjO1JMklFDL4VQnHuNKYyFhWCSjIFR6RbsKrBpstZS0WTGy+rpm3Uz1P86EL9VFLQSBU6KGXMxoluIlKlOHYYV0iQaTGZJlBQYKYrIHwH3bBD1it42jK6bQLDzejAh2JjaMZsDLMScPs1Qpd4z35+suuY1PxZS8TeukNx5751x1+AcyDSIn5Pr9nXb0UmaIaplW4+cyysAD4oGOO86UEDLW4T4qSHbMLD4zd758u7sPMlZyy/0zGHS9n0/EeKzPUuXvghSncFbZoAheSE6UZd92MbCk8eTUs4Jh9ELywgmUiLEVY6tCHg1TL44hqU1HB+Uh25hPNFZXBDV+prdYOpgr5BjXGBXhOppIAMk885uaH6rMFucp3qlGAgt5nC5qTgIpBfVGMIgoAnWMvzItapy4iiIaSGdUizITJQPH2iGSsh2SazT06g5eIaqQiIIjELogo5BpQtgwrpK8Fgqgt0A+vYEwNm+HV5fmKDQDr2T1Og5o+YOUKwIHJ3qkpNgaCDiVEVWX9JPqx3y696cNkVVqxD5gyb//Fn1PIbHgOEnRWXquW+64HDTDcJDEi0zQyT3+I6nAMAM2o2UsvOtE879x7EAXo8iXuKSW6IjWBEe5edKJIVQhn7AHXjJhktdN/RBXsudZLYiBIAnJmCogs+CRA+1USvkuq5pj8iT2pgO+LSRBYOLhKsEY3IHACshM2VkDkRlyfap+oCex3FvFwFl4te6rcPrn8dpRSFWCgUh44PJKNQSeV22+JhYVmgTPSVAFFVKcs7EPVvDhnRlr3iEqJoWXPo3JyNxzxCP6XIDcMzyGmqIG5TOeKwhyQXiyYfNX6Yj7ojWe2EeIjWAEPzfdm5q/u0Gh57GBk38WOrBbbYNNq44fTETQysPfzomuhqt+Gmvw3vTZChmldfekflzisr2qox5dCGM6JCpGnSJxdrYbhxpnsI+zSnG2bahomrr8ys+lM4ESN7PySWacI+A2Mf5/jfvfUZvUnUg9af4Exv5YyLq3NZRFd9I7l7QQzd5OVnD+AEsrIkfscgnAh2P9Ajf2r9yeetliPdD/GkNnfpsYR5qw0D2x94EKiwfsK9gveqyrtAsbEZ8gHxuUJe+8OLNXt1x5ablkwCMVcxAfu8T8qmT+C5F/NSX1oIDLlhTVbtxisSlfdqonU5E1si9ESmEYsLdEHfTqy19PYdJ1zfRKjX7C/diPretHqnJd9ELLbKXU8FUkUUwfcm1eulfy8DcH2f72kJ9f7PN1E6NM2KqvIm15ySoe5mIKTvt8uWOh/NVNtLnJ8h+kBfobP3Ib8bvaVLbq/e0fsWavfsZSSi3SLRfvEbyKz75XZjLfslJvFRe+USu4+xkFA8RF4lbCmzd18V+A0WZpLPOJYgKpQM07A9IYKW10s39/B271xF4zgwRNlieOV2r76ReiTycVAKBkjr40dZJ/tk9mtP5RSXF0s+7zdcL50uXVT1L5kGVbrlErl2NTTNpPdkIR8IwTNMV8P3R2fbW96Ehvuu7mXZTtPZurtnZS6Q6goRPMuMKxZCFpsElcnoGaXduLvJgEHScCwW5+kr3IvA3VmGt2/M/HBUG2xXZoeuCwH3dQvJkbTj97rPYINEVOWQM4ACz9NUjKgcsqQIdAgvk8ADPPchUD3FgsmvzAarJBBKCOmuWYN96AoWaoowSW+0zdVtLFX52yzGC9hAoibkWB9NMRms7DZ7Odc0dBDDme3l7JJgBRNkwSUleJmo2+mY2nZjoymZCBXL3eHExZrJnPHW+So2I+OmLf1lMGwSjrkWtiT3It0jWEm24NXANAx27+jz1i67qwgPhM6wFaKl+ZPRKpKma5U9LdKaWV4z3MJWxlgG/lB6pNJczYHOjnfEY7t0HAJzbK/+rzgQeFnCL6srIz+Nx/IS4w1vFgc1YK17cNeweBwP9G7CXw1IcA4ww/wUQTOuPNHaKxfuCh2K1WvPm6rD00gZQ1Z4wd8WJCyolKQV23ZKOltShu4dHh8cnl/uv3n/s9/tBCYo+DQbBe7W8/9by7orUMqi5bUmJlZ45lSl/LHC/c0uQ7eBUdl34y8cVDGC6j3Kgyo0WOGzJD5ZdvCVBsohT6RmyLlqTb5xOmXH2Iyv5BTLOzo26QvxDx+WkqbPL7n9rIkM37w9O7gcvnl38Mfs7a/dX3ajrGwgt+8esjPenhie19prL1S+EOylU+i/+CxLZY4pRQAlbs6gxMUW9MYIEkKWh5FSVVL1j9yEO7+HNaLRlcl4+0RORjTY6rWJ+78TbvvtsAzCEYTdPtnK5t7wSP8AaR2T+0LVX96uoOa6+1e74yJzHlGxTgWfQOSe8RgUuIp1PU+zPunVMLtX5hi//taifrHhC+xFzK8Jj3cbfkyFR0JKwZtxIQT2Qi/WXr7YgPkrS0WqE643QLmgC5w27b48NoNhGL7YgMfmlVYIS5D/Bw) that sets up the default material. Basically I (ab)used a `CustomShader`'s `REPLACE_MATERIAL` mode so the material is set to the default rather than what was in the glTF.

The relevant code is this part
```js
// Modified this shader to use the default material
const textureUniformShader = new Cesium.CustomShader({
  lightingModel: Cesium.LightingModel.PBR,
  mode: Cesium.CustomShaderMode.REPLACE_MATERIAL,
  // Apply the texture to the model, but move the texture coordinates
  // a bit over time so it's animated.
  fragmentShaderText: `
    void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material)
    {
    }
    `,
});
```
