### ISSUE TITLE
Sandcastle header links to Contributor's Guide that does not exist

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#9999]
Opening the `index.html` or `standalone.html` in the `Apps/Sandcastle` directory causes the [`Sandcastle-header.js`](https://github.com/CesiumGS/cesium/blob/2fd0e8f7e4212bd1e7084299187f70597a6bbfd8/Apps/Sandcastle/Sandcastle-header.js) to open a confirmation box saying 

> You must host this app on a web server.
> See contributor's guide for more info?

Confirming that leads to [`https://github.com/CesiumGS/cesium/wiki/Contributor%27s-Guide`](https://github.com/CesiumGS/cesium/wiki/Contributor%27s-Guide), but this page does not exist. 

For people who usually go to the online sandcastle, but just want to run the whole thing locally to try something out, this link should point to a helpful summary. After a while of browsing, https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/BuildGuide/README.md#build-the-code might be the right place. In hindsight, it's obvious ("That's how it's _always_ done..."), but some people might appreciate a **tl;dr** like

- Run `npm install`
- Ignore any vulnerabilities that are reported
- Run `npm run build`
- (Optional, but recommended to avoid error messages): Run `npm run generateDocumentation`
- Run `npm run start`
- Browse to http://localhost:8080/Apps/Sandcastle/ 

---

If the link should just be updated to lead to the "BuildGuide", then I could open a PR for that. If it should point to something like a `SandcastleQuickstart.md` containing the bullet points from above, I could also do this. Just drop me a note.

**Comment by TheMagicNacho** [comment]
I created a pull request for this issue #10034

**Comment by javagl** [comment]
As a clarification: This issue mainly referred to the link at https://github.com/CesiumGS/cesium/blob/2fd0e8f7e4212bd1e7084299187f70597a6bbfd8/Apps/Sandcastle/Sandcastle-header.js#L108 that points to a page that does not exist. Extending the `TestingGuide.md` with a link to how to start the server is fine, but will not fully resolve this issue. Whether the link in the sandcastle should point to the `BuildGuide`, or to a new "Quickstart.md" page where the aforementioned steps are summarized has to be decided. (I'd be in favor of the latter, and maybe create a PR for that at some point, but maybe there's some recommendation from the Cesium team for that)
